elastic/beats

inputs/udpjson/udpjson_test.go

This PR is quite lame ! But after cloning the project it failed to run 'make test' due to a typing problem in this assert.
I guess something moved in a related dependency since the last successful build.

Fix udpjson test assertion.

---

etc/packetbeat.yml

Amend Thrift description in Packetbeat config.

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/elastic/libbeat/logp/log.go
Godeps/_workspace/src/github.com/elastic/libbeat/service/service_unix.go
Godeps/_workspace/src/github.com/elastic/libbeat/service/service_windows.go
main.go

Added windows service functionality based on https://github.com/elastic/libbeat/pull/26.

Basic windows service functionality

---

README.md

CodeCov Badge

---

docs/index.asciidoc
docs/new_protocol.asciidoc

I went with providing examples from multiple modules, rather than focusing on a single one.
CC-in recent protocol contributors @urso, @andrewkroh, @albanm . Please let me know if you find the guide lacking in any major area.

First pass at the protocol dev guide.

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/elastic/libbeat/beat/beat.go

Sync libbeat via Godeps

---

docs/gettingstarted.asciidoc

Use `[packetbeat-]YYYY.MM.DD` to better manage query and dashboard in Elasticsearch.
With this pull request must change the dashboard.

Use [packetbeat-]YYYY.MM.DD

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/elastic/libbeat/beat/beat.go
Godeps/_workspace/src/github.com/elastic/libbeat/beat/beat_test.go
Godeps/_workspace/src/github.com/elastic/libbeat/outputs/elasticsearch/api_test.go
Godeps/_workspace/src/github.com/elastic/libbeat/outputs/elasticsearch/output_test.go
Godeps/_workspace/src/github.com/elastic/libbeat/outputs/redis/redis_test.go
Godeps/_workspace/src/labix.org/v2/mgo/bson/bson.go
Godeps/_workspace/src/labix.org/v2/mgo/bson/bson_test.go
Godeps/_workspace/src/labix.org/v2/mgo/bson/decode.go
Godeps/_workspace/src/labix.org/v2/mgo/bson/encode.go
packetbeat.go

See https://github.com/elastic/libbeat/pull/51

Update beat to new channel transport.

---

deploytools/saltstack/README
deploytools/saltstack/packetbeat/init.sls
deploytools/saltstack/packetbeat/packetbeat.conf
deploytools/saltstack/packetbeat/packetbeat.yml
deploytools/saltstack/packetbeat/pillar.example

This pull request is for deploying the packetbeat agent automatically using saltstack. http://www.saltstack.com/ I use it in my environment and thought I would contribute it here to help speed deployment for other folks who also use it. Feel free to ask any questions or ping me for basic support.

Add saltstack deploy method

---

.travis.yml
Godeps/Godeps.json
Godeps/_workspace/src/github.com/elastic/libbeat/beat/beat.go
Godeps/_workspace/src/github.com/elastic/libbeat/cfgfile/cfgfile.go
Godeps/_workspace/src/github.com/elastic/libbeat/cfgfile/cfgfile_test.go
Godeps/_workspace/src/github.com/elastic/libbeat/logp/logp.go
Godeps/_workspace/src/github.com/elastic/libbeat/outputs/elasticsearch/output.go
Godeps/_workspace/src/github.com/elastic/libbeat/outputs/elasticsearch/output_test.go
Godeps/_workspace/src/github.com/elastic/libbeat/outputs/fileout/file.go
Godeps/_workspace/src/github.com/elastic/libbeat/outputs/fileout/file_test.go
Godeps/_workspace/src/github.com/elastic/libbeat/outputs/lumberjack/lumberjack.go
Godeps/_workspace/src/github.com/elastic/libbeat/outputs/outputs.go
Godeps/_workspace/src/github.com/elastic/libbeat/outputs/redis/redis.go
Godeps/_workspace/src/github.com/elastic/libbeat/outputs/redis/redis_test.go
Godeps/_workspace/src/github.com/elastic/libbeat/publisher/publish.go
Godeps/_workspace/src/github.com/elastic/libbeat/service/service.go
main.go
packetbeat.go

This is related to the libbeat change: https://github.com/elastic/libbeat/pull/65
Also update to Golang 1.5 was made.

Update client flags for newest version of libbeat

---

docs/fields.asciidoc
etc/fields.yml

* dupliate was introduced in 931eb08

remove duplicate 'transport' field

---

.gitignore

Add more stuff to gitignore

---

.travis.yml

Removed the email notifications as hipchat will probably make
enough noise.

Added hipchat notifications for Travis build

---

docs/configuration.asciidoc
docs/index.asciidoc
docs/overview.asciidoc
docs/windows.asciidoc

Used the correct format for external links this time.

Fix external links

---

docs/overview.asciidoc

Requested by https://github.com/elastic/packetbeat/issues/282

Add new protocols beta3 overview doc

---

docs/gettingstarted.asciidoc
docs/gettingstarted.in.asciidoc

Reported on twitter: https://twitter.com/olvesh/status/649494193098858496

Fix link to the beta3 sample dashboards

---

protos/dns/dns.go
protos/dns/dns_test.go

Enhancing DNS protocol plugin to publish an event when a transaction expires.
This was created in response to https://discuss.elastic.co/t/dns-protocol-and-reading-pcap-files/31868

 Publish expired DNS transactions

---

CHANGELOG.md
protos/memcache/memcache.go
protos/memcache/plugin_tcp.go

Bug 299 memcache exception

---

docs/command-line.asciidoc

As -N option is common for all beats.

Move -N option to libbeat

---

CHANGELOG.md
docs/new_protocol.asciidoc

- update new protocol to libbeat changes
- add section about protocol registration
fixes #267

update new protocol guide

---

CHANGELOG.md
docs/configuration.asciidoc

Add dns protocol analyser configuration documentation to
configuration.asciidoc
fixes #269

add dns protocol config doc

---

CHANGELOG.md
docs/fields.asciidoc
scripts/generate_field_docs.py

Add documentation about the direction field

---

etc/packetbeat.yml

Refresh packetbeat.yml with changes from libbeat.yml.

---

CHANGELOG.md
deploytools/saltstack/packetbeat/init.sls
docs/index.asciidoc
packetbeat.go

Brought in changes from the beta4 branch.

Merge beta4

---

docs/gettingstarted.asciidoc
docs/overview.asciidoc

Edits to make the content consistent with other beats and make the content more task-oriented.

implements technical edits to the getting started info

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/elastic/libbeat/common/mapstr.go
Godeps/_workspace/src/github.com/elastic/libbeat/logp/log.go
Godeps/_workspace/src/github.com/elastic/libbeat/outputs/elasticsearch/api.go
Godeps/_workspace/src/github.com/elastic/libbeat/outputs/elasticsearch/bulkapi.go
Godeps/_workspace/src/github.com/elastic/libbeat/outputs/elasticsearch/client.go
Godeps/_workspace/src/github.com/elastic/libbeat/outputs/elasticsearch/output.go
Godeps/_workspace/src/github.com/elastic/libbeat/outputs/elasticsearch/topology.go
Godeps/_workspace/src/github.com/elastic/libbeat/outputs/elasticsearch/url.go
Godeps/_workspace/src/github.com/elastic/libbeat/outputs/fileout/file.go
Godeps/_workspace/src/github.com/elastic/libbeat/outputs/logstash/client.go
Godeps/_workspace/src/github.com/elastic/libbeat/outputs/logstash/logstash.go
Godeps/_workspace/src/github.com/elastic/libbeat/outputs/mode/balance.go
Godeps/_workspace/src/github.com/elastic/libbeat/outputs/mode/failover.go
Godeps/_workspace/src/github.com/elastic/libbeat/outputs/mode/mode.go
Godeps/_workspace/src/github.com/elastic/libbeat/outputs/mode/single.go
Godeps/_workspace/src/github.com/elastic/libbeat/outputs/outputs.go
Godeps/_workspace/src/github.com/elastic/libbeat/publisher/async.go
Godeps/_workspace/src/github.com/elastic/libbeat/publisher/bulk.go
Godeps/_workspace/src/github.com/elastic/libbeat/publisher/client.go
Godeps/_workspace/src/github.com/elastic/libbeat/publisher/output.go
Godeps/_workspace/src/github.com/elastic/libbeat/publisher/preprocess.go
Godeps/_workspace/src/github.com/elastic/libbeat/publisher/publish.go
Godeps/_workspace/src/github.com/elastic/libbeat/publisher/sync.go
Godeps/_workspace/src/github.com/elastic/libbeat/publisher/worker.go
Godeps/_workspace/src/github.com/elastic/libbeat/service/service_windows.go

Update to most recent libbeat version

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/elastic/libbeat/common/streambuf/streambuf.go
docs/fields.asciidoc
etc/fields.yml
etc/packetbeat.yml
scripts/Makefile
tests/system/pbtests/packetbeat.py

This is the Packetbeat part of https://github.com/elastic/libbeat/pull/285

Added documentation for the beat fields

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/elastic/libbeat/beat/beat.go
Godeps/_workspace/src/github.com/elastic/libbeat/cfgfile/cfgfile.go
Godeps/_workspace/src/github.com/elastic/libbeat/common/geolite.go
Godeps/_workspace/src/github.com/elastic/libbeat/logp/log.go
Godeps/_workspace/src/github.com/elastic/libbeat/logp/logp.go
Godeps/_workspace/src/github.com/elastic/libbeat/outputs/elasticsearch/client.go
Godeps/_workspace/src/github.com/elastic/libbeat/outputs/logstash/client.go
Godeps/_workspace/src/github.com/elastic/libbeat/outputs/logstash/logstash.go
Godeps/_workspace/src/github.com/elastic/libbeat/outputs/outputs.go
Godeps/_workspace/src/github.com/elastic/libbeat/outputs/tls.go
Godeps/_workspace/src/github.com/elastic/libbeat/publisher/preprocess.go
Godeps/_workspace/src/github.com/elastic/libbeat/publisher/publish.go
Godeps/_workspace/src/github.com/elastic/libbeat/publisher/worker.go
docs/fields.asciidoc
etc/fields.yml
tests/system/pbtests/packetbeat.py
tests/system/templates/packetbeat.yml.j2
tests/system/test_0026_test_config.py

This required a libbeat update, which required a few fixes for the system
tests, which got stuck otherwise because the Redis output was started.

Removed the version field.

---

docs/command-line.asciidoc
docs/configuration.asciidoc
docs/gettingstarted.asciidoc
docs/https.asciidoc
docs/index.asciidoc
docs/kibana3.asciidoc
docs/new_protocol.asciidoc
docs/release-notes.asciidoc
docs/windows.asciidoc

I've moved some things around and fixed a few minor nits. Note that I've added a placeholder for the release notes, but I'm not building the file. It's there for when we want to start adding release notes to the doc.

adds a few structural changes and fixes some typos

---

docs/configuration.asciidoc

Cherry-pick of #394 
@dedemorton  mentioned that this was missing from the 1.0.0 release branch.

Fixes intro to conf file

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/elastic/libbeat/beat/beat.go
Godeps/_workspace/src/github.com/elastic/libbeat/outputs/logstash/client.go
beat/packetbeat.go
main.go

Update to most recent libbeat version

Adapt packetbeat structure to newest libbeat structure

---

.gitignore
.travis.yml

* Add .gitignore file
* Fix codecov coverage

Repo adjustments

---

.appveyor.yml
libbeat/scripts/Makefile
libbeat/scripts/aggregate_coverage.py

This a adds a python script to handling the aggregation of `.cov` files. This simplifies the aggregation process for Windows.

Push system-test coverage reports from appveyor

---

filebeat/docs/migration.asciidoc
filebeat/etc/beat.yml
filebeat/harvester/log.go
filebeat/tests/system/config/filebeat.yml.j2
filebeat/tests/system/test_prospector.py

* Clean up config
* Clean up docs
* Make it full dependent on input_type config

Improve stdin implmentation

---

libbeat/scripts/update.sh

Add Linux support to make update

---

Makefile
libbeat/scripts/Makefile

A few days ago when I first used goreportcard it detected some code that could be simplified so I'm adding it to our checks.
Also removing some verbosity from the clean command too.

Add "make simplify" target

---

packetbeat/docs/gettingstarted.asciidoc

Changes headings to make formatting across platform-specific sections consistent regardless of heading level.

Adds minor formatting changes

---

filebeat/docs/getting-started.asciidoc

Changes headings to make formatting across platform-specific sections consistent regardless of heading level.

Minor formatting changes for filebeat

---

topbeat/docs/gettingstarted.asciidoc

Typo fix plus changed formatting for platform-specific headings so all sections stand out equally regardless of heading level.

Adds minor formatting and fixes typo

---

winlogbeat/docs/configuration.asciidoc
winlogbeat/docs/fields.asciidoc
winlogbeat/docs/getting-started.asciidoc
winlogbeat/docs/overview.asciidoc
winlogbeat/etc/fields.yml

General style changes to make doc style consistent with the doc for other Beats.
@andrewkroh Please review.

Implements technical edits for Winlogbeat doc

---

.gitignore

Add .vagrant dir to .gitignore

---

libbeat/docs/gettingstarted.asciidoc

I still need to update the section on loading the dashboards, but I think it's probably worth getting these changes into the doc build now.

Add windows install steps to the Getting Started

---

Makefile
libbeat/CHANGELOG.md
libbeat/cfgfile/cfgfile.go

See https://github.com/elastic/beats/pull/435 for more details

Change default directory of the config file to be identical with the binary

---

Makefile
libbeat/cfgfile/cfgfile.go

This is to make sure all project are run in the testsuite.
Run make fmt and make update to bring everything up-to-date

Introduce beats and project list in Makefile

---

filebeat/harvester/log.go
filebeat/tests/system/test_crawler.py

Filebeat harvesters were hanging in an endless loop when there was no permissions to read a file. This should be fixed now. Tests for files without reading permissions were added.

Better handle errors when opening file

---

topbeat/beat/sigar.go
topbeat/beat/topbeat.go
topbeat/docs/fields.asciidoc
topbeat/etc/fields.yml
topbeat/etc/topbeat.template.json
topbeat/tests/system/test_system.py

Adding more details about mem.actual_used and mem.actual_free is requested by https://discuss.elastic.co/t/what-is-actual/36548.

Update all actual_used and actual_free fields

---

packetbeat/decoder/decoder.go

rahter implement decoder loop directly to have better control on per layer
processing.

Implement decoder loop directly

---

libbeat/common/string.go
packetbeat/CHANGELOG.md
packetbeat/protos/redis/redis.go
packetbeat/protos/redis/redis_parse.go
packetbeat/protos/redis/redis_test.go

- fix panic in redis parser
- some more redis parsing errors
- add support for command pipelining
- reduce allocations in redis parser

Backport redis protocol changes

---

filebeat/CHANGELOG.md
filebeat/docs/configuration.asciidoc
filebeat/harvester/log.go
filebeat/tests/system/test_crawler.py

This backports PR elastic/filebeat#302, commit
91436ef59ac44786ffa47404f2fd675f29d3950f.

Backported filebeat Improve force_close_file

---

filebeat/docs/getting-started.asciidoc
libbeat/docs/gettingstarted.asciidoc
packetbeat/docs/gettingstarted.asciidoc
topbeat/docs/gettingstarted.asciidoc

Because we cannot merge from the 1.0.0 branch ( :( ), I cherry picked the docs changes from the 1.0.0 branch to master. @dedemorton can you check that nothing was lost, please?

Docs cherry picks

---

packetbeat/etc/beat.yml
packetbeat/etc/packetbeat.yml

Fixed minor typo in a comment in the main config.

Updated packetbeat.yml to fix minor typo.

---

CHANGELOG.asciidoc
libbeat/docs/index.asciidoc
libbeat/docs/release.asciidoc

* Cherry-picked the unified CHANGELOG from master
* Added a commit to close the changelog for 1.0.1
* Also added shortcuts for easy linking to github issues/pulls

Add release notes

---

CHANGELOG.asciidoc
filebeat/CHANGELOG.md
libbeat/CHANGELOG.md
libbeat/docs/index.asciidoc
libbeat/publisher/async.go
packetbeat/CHANGELOG.md
topbeat/CHANGELOG.md

Cherry-picked the latest changes from the 1.0.1 branch.
Contains mostly Changelog updates + the change in the default for the bulk size.

Cherypicks from 101

---

filebeat/docs/getting-started.asciidoc
packetbeat/docs/gettingstarted.asciidoc
topbeat/docs/gettingstarted.asciidoc

Added note with most permissive script execution policy because the level of permission required seems to differ by Windows OS.

Closes issue #540

---

filebeat/docs/getting-started.asciidoc
packetbeat/docs/gettingstarted.asciidoc
topbeat/docs/gettingstarted.asciidoc

This changes have already been reviewed in PR #559

Cherrypick doc changes from master

---

.gitignore
filebeat/.gitignore
libbeat/.gitignore
packetbeat/.gitignore
topbeat/.gitignore
winlogbeat/.gitignore

Moved the very common stuff (*.swp, *.exe, etc.) in the top level
.gitignore and removed them from the individual .gitignore files.

Cleanup gitignore just a bit

---

packetbeat/docs/new_protocol.asciidoc

update guide after repo renaming

change link and description

---

packetbeat/docs/new_protocol.asciidoc

Cherry picked PR 573 to master

---

packetbeat/docs/new_protocol.asciidoc

Cherry pick for 573

---

filebeat/docs/index.asciidoc
packetbeat/docs/index.asciidoc
topbeat/docs/index.asciidoc
winlogbeat/docs/index.asciidoc

Attempt to fix doc build failures. See http://build-us-00.elastic.co/job/Docs/2671/console

Fix for bad cross-document links

---

libbeat/docs/communitybeats.asciidoc

Added Execbeat as new beat
Fixed also URL pointing to this file

Added Execbeat as new beat

---

CHANGELOG.asciidoc
libbeat/docs/release.asciidoc

Cherry picked cefcef18edd64cb0fa27da2f49b5f4cdea8cf893 which was apparently forgotten.

Cherry picked closing changelog commit

---

CHANGELOG.asciidoc
filebeat/main.go
libbeat/docs/index.asciidoc
libbeat/docs/release.asciidoc
packetbeat/main.go
topbeat/main.go
winlogbeat/main.go

This is a merge PR. I edited the commit to keep 'master' as branch name in docs and modified the versions to use 1.2.0.

Merge 1.1 into master

---

dev-tools/get_version
dev-tools/set_version

Part of #633, needed for the unified build process.

Added set_version and get_version scripts.

---

libbeat/docs/gettingstarted.asciidoc

Added link to support matrix in response to https://github.com/elastic/beats/issues/135.

Add link to Elastic support matrix to getting started doc

---

libbeat/docs/communitybeats.asciidoc

I've released [hsbeat](https://github.com/YaSuenag/hsbeat).
So I would like you to add it to Community Beats.
Please merge it.

Add hsbeat to the list of beats

---

.travis.yml
libbeat/docker-compose.yml
libbeat/scripts/Makefile
scripts/docker-entrypoint.sh
scripts/docker/elasticsearch/Dockerfile-2.2.0
scripts/docker/elasticsearch/config/logging.yml
scripts/docker/elasticsearch/docker-entrypoint.sh
scripts/docker/test.env

Update tests to elasticsearch-220

---

libbeat/docs/gettingstarted.asciidoc

This closes https://github.com/elastic/filebeat/issues/229

Add clarification to section about logstash input beats plugin

---

CONTRIBUTING.md
libbeat/beat/beat_test.go

Adds Golang update part of this PR https://github.com/elastic/beats/pull/602

Add Golang version to contributing guide

---

libbeat/docs/shared-logstash-config.asciidoc

Clarify how to enable and disable logstash output

---

filebeat/docs/getting-started.asciidoc
packetbeat/docs/gettingstarted.asciidoc
topbeat/docs/gettingstarted.asciidoc
winlogbeat/docs/getting-started.asciidoc

Adding a note that I overlooked when I updated doc for #479

Add note indicating that Windows XP users may need to install PowerShell

---

filebeat/docs/getting-started.asciidoc
packetbeat/docs/gettingstarted.asciidoc
topbeat/docs/gettingstarted.asciidoc

I can't cherry pick these changes from the 1.1 commit because it includes Winlogbeat changes and Winlogbeat doesn't exist in 1.0.1.
So....this closes #703

Change Powershell ExecutionPolicy in 1.0.1 Getting Started docs

---

libbeat/beat/beat.go

The beat now runs in a independent go process and is not the blocking process anymore. This makes it possible to Start and Stop a beat without stopping the running process. This can be useful for:
* Reloading configuration
* Running multiple beats in parallel
The Service signal handler now calls beat.Exit() instead of beater.Stop() to make sure the beat is properly shut down.

Run a beat inside a go process

---

CONTRIBUTING.md

Fix community beats link in CONTRIBUTING.md

---

dev-tools/deploy
dev-tools/packer/docker/xgo-image-deb6/beats-builder/gopacket_pcap.patch
dev-tools/packer/docker/xgo-image/beats-builder/gopacket_pcap.patch
dev-tools/set_version

* The set_version script also creates the version.yml file in packer
* The deploy script simply calls the required make commands in the packer
folder
* Also updated the gopacket patch

Add deploy script

---

filebeat/crawler/prospector.go
filebeat/crawler/prospector_log.go
filebeat/crawler/prospector_stdin.go
filebeat/crawler/registrar.go
filebeat/input/file.go

The goal is to simplify prospector and harvester to make the code easier to read and understand.

Simplify Harvester

---

dev-tools/README.md
dev-tools/merge_pr

Creates a local branch, does the merge in it. In case of conflicts
it stops and can be resumed with `--continue`. It pushes to your
fork so you can then open the PR.
Automatically deletes the temporary branches before it needs them.

Added script to merge one branch into another

---

topbeat/tests/system/test_filesystem.py

fs.used_p is a number (integer or float)

Fix #752: test case failed

---

libbeat/tests/system/base.py
libbeat/tests/system/beat/beat.py
libbeat/tests/system/config/mockbeat.yml.j2
libbeat/tests/system/test_base.py

This is the foundation so the system-test libraries can also be used by other beats

Add general python system-test libraries to be used by other beats

---

Vagrantfile

To support running the newly updated system tests I added PyYAML to the box.

Add PyYAML to Windows vagrant box

---

winlogbeat/docs/fields.asciidoc
winlogbeat/docs/getting-started.asciidoc
winlogbeat/etc/fields.yml

@andrewkroh Please review. Minimal changes here...solid writing...nice job.

Copy edits for Winlogbeat

---

topbeat/docs/configuration.asciidoc
topbeat/docs/fields.asciidoc
topbeat/etc/fields.yml

Some minor edits for style/consistency. I also ran the python script to generate the asciidoc file (I didn't remove the swap fields; they were removed by [another commit](https://github.com/monicasarbu/beats/commit/244bf28037696c66b414249bdc3382e5099f5be2), but the python script wasn't run afterwards.

Edit new/changed content added to topbeat for 1.1 

---

libbeat/docs/gettingstarted.asciidoc
libbeat/docs/outputconfig.asciidoc
libbeat/docs/shipperconfig.asciidoc

- a few minor copy edits for style/consistency
- Made libbeat doc consistent where we refer to the Beats input plugin for Logstash.

Edit new/changed content added to libbeat for 1.1

---

CHANGELOG.asciidoc
packetbeat/protos/pgsql/pgsql.go

Check length in pgsql parser before parsing column content in case column
length > buffer length.

Validate length in parser

---

libbeat/scripts/Makefile

See https://github.com/elastic/beats/pull/721#discussion-diff-50017330

Add integration test report to Makefile

---

filebeat/docs/migration.asciidoc
packetbeat/docs/configuration.asciidoc

Forward ported docs fixes from 1.0.1 branch

---

libbeat/docs/communitybeats.asciidoc

Add Elasticbeat to community beats page

---

libbeat/docs/outputconfig.asciidoc

Add proxy_url option to config documentation

---

libbeat/scripts/Makefile

This should help solve https://github.com/elastic/beat-generator/issues/4

Make Beat path dynamic for vendor directory in Makefile

---

filebeat/docs/configuration.asciidoc
filebeat/docs/migration.asciidoc
filebeat/harvester/processor/multiline.go
filebeat/harvester/processor/multiline_test.go
libbeat/docs/gettingstarted.asciidoc
libbeat/docs/outputconfig.asciidoc
libbeat/docs/shipperconfig.asciidoc
packetbeat/docs/configuration.asciidoc
packetbeat/docs/fields.asciidoc
winlogbeat/docs/fields.asciidoc
winlogbeat/docs/getting-started.asciidoc
winlogbeat/etc/fields.yml

PR automatically created with dev-tools/merge_pr.

Merge 1.1 branch into master

---

dev-tools/merge_pr

Also makes the script executable.

Delete temp branch with -D in dev-tools/merge_pr

---

libbeat/beat/beat.go

See https://github.com/elastic/beats/pull/789 and https://github.com/elastic/beats/pull/755

Fix exit for beats if version flag is provided

---

packetbeat/docs/gettingstarted.asciidoc

This replaces PR https://github.com/elastic/beats/pull/792

Fixed/added packetbeat path for linux installs.

---

CHANGELOG.asciidoc
libbeat/docs/release.asciidoc

Did another merge, because of the changes in CHANGELOG, which shouldn't diverge too much.

Merge 1.1 branch

---

CHANGELOG.asciidoc
filebeat/docs/migration.asciidoc

This PR replaces #796 (ran into bizarre issues with the rebase in the other PR).

Copy edits for filebeat and changelog - take 2

---

.travis.yml

* Remove travis workaround as issue should be resolved
* Update to docker-compose 1.5.2 and set it with environment variable
* Cleanup docs

Clean up travis.yml

---

filebeat/tests/system/requirements.txt
libbeat/scripts/Makefile
packetbeat/Makefile
packetbeat/tests/system/requirements.txt
topbeat/tests/system/requirements.txt
winlogbeat/tests/system/requirements.txt

* Introduce variable to set path to environment
* Decouple environment from system tests to make it available also for other things

Refactor python virtual environment

---

filebeat/Makefile
packetbeat/Makefile
topbeat/Makefile
winlogbeat/Makefile

Got broken when the config files were moved one folder up.

Fix install_cfg target

---

libbeat/docs/gettingstarted.asciidoc

This closes (I think) https://github.com/elastic/beats-dashboards/issues/64.
@andrewkroh Can you review this please?

Add doc for loading dashboards on Windows.

---

filebeat/docs/configuration.asciidoc
packetbeat/docs/configuration.asciidoc
topbeat/docs/configuration.asciidoc
winlogbeat/docs/configuration.asciidoc

Document that restart is required to apply configuration changes

---

libbeat/outputs/mode/balance.go
libbeat/outputs/mode/failover.go
libbeat/outputs/mode/mode.go
libbeat/outputs/mode/single.go

Fix guaranteed flag checks

---

libbeat/outputs/mode/balance.go
libbeat/outputs/mode/failover.go
libbeat/outputs/mode/mode.go
libbeat/outputs/mode/single.go

Merge PR to propagate the fix for #874.

Automatic merge 1.1 branch to master

---

libbeat/docs/gettingstarted.asciidoc
packetbeat/docs/gettingstarted.asciidoc
topbeat/docs/gettingstarted.asciidoc

Fixed a few minor nits and removed redundant info

Fix issues found during 1.1 testing of getting started

---

filebeat/beat/filebeat_test.go
filebeat/beater/filebeat.go
filebeat/beater/filebeat_test.go
filebeat/beater/publish.go
filebeat/beater/publish_test.go
filebeat/beater/spooler.go
filebeat/beater/spooler_test.go
filebeat/main.go
filebeat/tests/system/test_prospector.py
libbeat/beat/beat.go
libbeat/libbeat.go
libbeat/mock/mockbeat.go
libbeat/tests/system/beat/beat.py
libbeat/tests/system/test_base.py
packetbeat/beater/packetbeat.go
packetbeat/main.go
topbeat/beater/config.go
topbeat/beater/sigar.go
topbeat/beater/sigar_test.go
topbeat/beater/topbeat.go
topbeat/beater/topbeat_test.go
topbeat/main.go
winlogbeat/beater/winlogbeat.go
winlogbeat/main.go

In a next step https://github.com/elastic/beats/pull/864 must be fixed.

Refactor beats to match model from beat-generator and exit param

---

libbeat/Dockerfile
libbeat/docker-compose.yml
libbeat/outputs/logstash/logstash_integration_test.go
libbeat/scripts/Makefile

* Remove global docker file, move dockerfile to libbeat
* Add files with relative path
* Simplify Makefile

Cleanup Dockerfile as build is now dependent on Docker volume

---

filebeat/etc/beat.yml
filebeat/filebeat.yml

This makes uncommenting easier.

Fix indentation in filebeat config

---

testing/environments/base.yml
testing/environments/docker/elasticsearch/Dockerfile-2.2.0
testing/environments/docker/logstash/Dockerfile-2.2.0
testing/environments/es17-ls15-kb41.yml
testing/environments/snapshot.yml

Use own Dockerfile for Logstash

Improve test environment

---

libbeat/outputs/elasticsearch/client.go
libbeat/outputs/elasticsearch/client_test.go
libbeat/publisher/client.go

Make index configurable in document

---

libbeat/scripts/generate_fields_docs.py
libbeat/scripts/generate_template.py
packetbeat/Makefile
winlogbeat/Makefile

This is to prevent errors during creation of template and docs

Check for missing fields in fields.yml

---

filebeat/docs/configuration.asciidoc
filebeat/docs/getting-started.asciidoc
filebeat/docs/support.asciidoc
libbeat/docs/gettingstarted.asciidoc
libbeat/docs/newbeat.asciidoc
libbeat/docs/outputconfig.asciidoc
packetbeat/docs/gettingstarted.asciidoc
packetbeat/docs/troubleshooting.asciidoc
topbeat/docs/gettingstarted.asciidoc

Cherry picked the low-hanging fruit (pun intended) from 1.1 doc changes.

Cherry pick doc changes from 1.1 into 1.0.1

---

filebeat/docs/getting-started.asciidoc
packetbeat/docs/gettingstarted.asciidoc

Cherry-picked low-hanging fruit from master.

Cherry pick doc master to 1.1

---

CHANGELOG.asciidoc
filebeat/docs/index.asciidoc
filebeat/main.go
libbeat/docs/index.asciidoc
libbeat/docs/release.asciidoc
packetbeat/docs/index.asciidoc
packetbeat/main.go
topbeat/docs/index.asciidoc
topbeat/main.go
winlogbeat/docs/index.asciidoc
winlogbeat/main.go

Version bumps and closing the changelog for 1.1.1.

Version bumps for 1.1.1

---

libbeat/docker-compose.yml
testing/environments/docker/elasticsearch/Dockerfile-2.2.0-shield
testing/environments/docker/logstash/Dockerfile-2.2.0

Update test builds to latest elasticsearch and logstash version.

---

filebeat/config/config.go
filebeat/crawler/prospector.go
filebeat/crawler/prospector_test.go
filebeat/harvester/log.go
filebeat/tests/system/test_prospector.py

Improve harvester closing logging

Refactor max-bytes to be setup in prospector

---

filebeat/tests/system/test_crawler.py
filebeat/tests/system/test_multiline.py

See https://github.com/elastic/beats/issues/902

Add multiline test for rabbitmq

---

libbeat/service/service.go
libbeat/service/service_unix.go
libbeat/service/service_windows.go

Update libbeat service to be more GoLint compliant

Update service for GoLint

---

libbeat/docs/outputconfig.asciidoc

Un-deprecate Redis output

---

winlogbeat/beater/winlogbeat.go
winlogbeat/main_test.go
winlogbeat/sys/eventlogging/common.go
winlogbeat/sys/eventlogging/eventlogging.go
winlogbeat/sys/eventlogging/eventlogging_windows.go
winlogbeat/sys/eventlogging/strings.go
winlogbeat/sys/wineventlog/wineventlog_windows.go

This addresses multiple documentation level GoLint errors within the Winlogbeat.
Signed-off-by: Kevin Kirsche <kev.kirsche@gmail.com>

Address comment level GoLint bugs in Winlogbeat

---

filebeat/docs/getting-started.asciidoc
packetbeat/docs/gettingstarted.asciidoc
topbeat/docs/gettingstarted.asciidoc
winlogbeat/docs/getting-started.asciidoc

Fix #1015
Signed-off-by: Kevin Kirsche <Kev.Kirsche@gmail.com>
#1017 I screwed up a merge to match master

Update Getting Started Documentation Titles

---

filebeat/docs/getting-started.asciidoc
packetbeat/docs/gettingstarted.asciidoc
topbeat/docs/gettingstarted.asciidoc
winlogbeat/docs/getting-started.asciidoc

Fix #1015
Signed-off-by: Kevin Kirsche <Kev.Kirsche@gmail.com>
#1017 I screwed up a merge to match master

cherry pick doc changes from #1018

---

filebeat/docs/migration.asciidoc

fix typo in migration guide

---

libbeat/common/net.go

Use more consistent variable naming between functions and fix the function name at the beginning of the Godoc comment

Use more consistent naming in common/net

---

filebeat/docs/reference/configuration.asciidoc
libbeat/docs/outputconfig.asciidoc
packetbeat/docs/reference/configuration.asciidoc
topbeat/docs/reference/configuration.asciidoc
winlogbeat/docs/reference/configuration.asciidoc

@andrewkroh Here's the fix for the Kafka display issue. Made a few minor edits. Still needs a few edits, but it's good enough for now. This topic *really* needs an example.

Fix build problem with Kafka output section

---

.github/ISSUE_TEMPLATE.md

Preview:
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.
For confirmed bugs, please report:
- Version: 
- Operating System: 
- Steps to Reproduce:

Adding a Github issue template

---

packetbeat/docs/overview.asciidoc

Removed mention of Redis being deprecated

---

packetbeat/docs/new_protocol.asciidoc

cherry pick of #1020 
The links make navigation easier.

add intro links to new protocol topic

---

packetbeat/etc/fields.yml

Remove dead section reference

---

CHANGELOG.asciidoc
filebeat/crawler/prospector.go
filebeat/tests/system/test_registrar.py

Fix registrar for rotating files.

---

testing/environments/docker/kibana/Dockerfile-4.4.0
testing/environments/latest.yml

* Timelion was added so it can be used for testing
* Updated to Kibana 4.4.0

Update Kibana environment and add timelion

---

CHANGELOG.asciidoc
filebeat/docs/index.asciidoc
filebeat/main.go
libbeat/docs/index.asciidoc
packetbeat/docs/index.asciidoc
packetbeat/main.go
topbeat/docs/index.asciidoc
topbeat/main.go
winlogbeat/docs/index.asciidoc
winlogbeat/main.go

Version bumps and closing the Changelog for 1.1.2.

Release 112

---

libbeat/outputs/logstash/transport.go
libbeat/scripts/Makefile

use mutex to protect connection state

---

filebeat/docs/getting-started.asciidoc
filebeat/docs/migration.asciidoc
filebeat/docs/reference/configuration/filebeat-options.asciidoc
filebeat/etc/beat.yml
filebeat/filebeat.yml
filebeat/tests/load/filebeat.yml
filebeat/tests/system/config/filebeat.yml.j2

Improve prospector config

---

libbeat/docker-compose.yml
libbeat/outputs/kafka/kafka_integration_test.go
libbeat/scripts/docker-entrypoint.sh

Uses a Docker image containing both Kafka and Zookeeper. Only Kafka 8 for now.

Added basic Kafka integration tests

---

filebeat/docs/faq.asciidoc
filebeat/docs/index.asciidoc
filebeat/docs/reference/configuration/filebeat-options.asciidoc
libbeat/docs/shared-faq.asciidoc
packetbeat/docs/faq.asciidoc
packetbeat/docs/index.asciidoc
packetbeat/docs/reference/configuration/packetbeat-options.asciidoc
topbeat/docs/faq.asciidoc
topbeat/docs/index.asciidoc
winlogbeat/docs/faq.asciidoc
winlogbeat/docs/index.asciidoc

Cherry pick of the FAQ topics (https://github.com/elastic/beats/pull/1051) into 1.1. Closes #699.

FAQ additions and fixes after review

---

.travis.yml
metricbeat/helper/metricset_test.go
metricbeat/helper/module.go
metricbeat/helper/module_test.go
metricbeat/helper/register.go
metricbeat/module/apache/apache.go
metricbeat/module/mysql/mysql.go
metricbeat/module/redis/redis.go

Needs https://github.com/elastic/beats/pull/1126 to be merged first.

Metricbeat moduler tests

---

metricbeat/etc/beat.yml
metricbeat/helper/interfacer.go
metricbeat/helper/metricset.go
metricbeat/helper/metricset_test.go
metricbeat/helper/module.go
metricbeat/helper/register.go
metricbeat/include/list.go
metricbeat/metricbeat.yml
metricbeat/module/apache/status/status.go
metricbeat/module/mysql/status/status.go
metricbeat/module/mysql/status/status_test.go
metricbeat/module/redis/info/info.go
metricbeat/module/redis/info/info_test.go

- Extend MetricSeter interface with a Setup function
- Add hook to Setup/Configure MetricSeters

Add redis pool configuration for metricbeat

---

metricbeat/helper/module.go

If a service does not respond with stats requested by a metricset, an error is sent to elasticsearch instead. This allows to also track and monitor errors of systems.

Send error event when service is down

---

metricbeat/Makefile
metricbeat/docs/fields.asciidoc
metricbeat/etc/fields_base.yml
metricbeat/etc/metricbeat.template.json
metricbeat/module/redis/info/fields.yml

* Automatically collect metricset fields docs
* Create initial docs
* Introduce fields_base.yml for base information
This PR depends on https://github.com/elastic/beats/pull/1131 (must be merged first)

Introduction of fields in metricsets

---

dev-tools/packer/Makefile
dev-tools/packer/beats/filebeat.yml
dev-tools/packer/beats/metricbeat.yml
dev-tools/packer/beats/packetbeat.yml
dev-tools/packer/beats/topbeat.yml
dev-tools/packer/beats/winlogbeat.yml
dev-tools/packer/docker/xgo-image-deb6/beats-builder/Dockerfile
metricbeat/Makefile

* Update outdated debian dependency links
* Update installing of packer deps to fetch most recent version from remote
* Fix outdated beats config paths

Add nightly build for metricbeat

---

filebeat/filebeat.yml
libbeat/etc/libbeat.yml
metricbeat/helper/interfacer.go
metricbeat/helper/metricset.go
metricbeat/helper/metricset_test.go
metricbeat/helper/module.go
metricbeat/metricbeat.yml
metricbeat/module/apache/status/status.go
metricbeat/module/mysql/status/status.go
metricbeat/module/redis/info/info.go
metricbeat/module/redis/info/info_test.go
packetbeat/packetbeat.yml
topbeat/topbeat.yml
winlogbeat/winlogbeat.yml

* Refactor Redis Host handling
* Improve error handling
* Move general config loading to module to prevent dependency of ucfg in each metricseter

Update MetricSetter interface by passing MetricSet

---

CHANGELOG.asciidoc
filebeat/docs/getting-started.asciidoc
filebeat/tests/system/test_prospector.py
libbeat/docs/index.asciidoc
libbeat/docs/release.asciidoc
libbeat/docs/shared-template-load.asciidoc
libbeat/outputs/elasticsearch/client_integration_test.go
packetbeat/docs/gettingstarted.asciidoc
topbeat/docs/gettingstarted.asciidoc
winlogbeat/docs/getting-started.asciidoc

I took master versions for pretty much everything.
Besides the docs changes, there's only a tiny change in a Filebeat test (@ruflin can you check that one?) and CHANGELOG cleanups.

Automatic merge branch 1.2 to master

---

libbeat/docs/communitybeats.asciidoc

Adds a space to fix a run-together word

Fix minor space problem

---

filebeat/docs/index.asciidoc
libbeat/docs/shared-env-vars.asciidoc
packetbeat/docs/index.asciidoc
topbeat/docs/index.asciidoc
winlogbeat/docs/index.asciidoc

Cherry-pick doc about using environment variables in config files

---

libbeat/scripts/generate_template.py
metricbeat/docs/fields.asciidoc
metricbeat/etc/fields.yml
metricbeat/etc/fields_base.yml
metricbeat/etc/metricbeat.template.json
metricbeat/helper/metricset.go
metricbeat/helper/module.go

Add support for integer in templates

Add round trip time to metricset request

---

libbeat/docs/outputconfig.asciidoc
packetbeat/docs/overview.asciidoc

Cherry pick of #1008 and #1048

Un-deprecate redis in 1.1 doc

---

metricbeat/module/apache/status/data.go

This continues work on #1196 and refractors variable names.

Rename variables and output fields

---

metricbeat/docker-compose.yml
metricbeat/etc/beat.yml
metricbeat/metricbeat.yml
metricbeat/module/apache/status/status.go
metricbeat/module/apache/status/status_test.go

Implement server_status_path config option for status metricset

---

libbeat/docs/communitybeats.asciidoc

Adds WMIbeat to community beats documentation

New community beat: WMIbeat

---

libbeat/docs/shared-env-vars.asciidoc

@andrewkroh I meant to add this section when I added the content for #1163, but somehow I overlooked it. I think it is useful information and worth adding.

Add troubleshooting to section about env vars

---

filebeat/crawler/registrar.go

Typo in debug registrar message fix

---

packetbeat/docs/faq.asciidoc

Cherry-pick of #1233 into master.

Cherry-pick into master: FAQ about capturing loopback traffic on Windows

---

CHANGELOG.asciidoc
libbeat/docs/index.asciidoc
libbeat/docs/release.asciidoc

@andrewkroh there were some conflicts in winlogbeat, but I always took the master version, as i assume they were backporting artifacts.

Automatic merge 1.2 branch into master

---

CHANGELOG.asciidoc

Update changelog with adding NFS support in Packetbeat #1231

Add support for NFS in Packetbeat

---

libbeat/beat/beat.go

I didn't like the `goto` statements I added.

Code cleanup to remote goto's

---

metricbeat/etc/beat.yml
metricbeat/metricbeat.yml
metricbeat/module/redis/info/info.go
metricbeat/module/redis/info/info_test.go

- Extract pool creation to func
- Add Auth
- Return event errors from Redis Fetch()

Add Redis AUTH

---

testing/environments/docker/elasticsearch/Dockerfile-2.3.0
testing/environments/docker/kibana/Dockerfile-4.5.0
testing/environments/docker/logstash/Dockerfile-2.3.0
testing/environments/snapshot-2x.yml

You can start this testing environment with
`make start ENV=snapshot-2x.yml`.

Added Dockerfiles for ES 2.3, LS 2.3, KB 4.5

---

filebeat/docs/fields.asciidoc
filebeat/filebeat.yml
topbeat/docs/fields.asciidoc
winlogbeat/docs/fields.asciidoc

Update all beats

---

filebeat/docs/index.asciidoc
libbeat/docs/index.asciidoc
packetbeat/docs/index.asciidoc
topbeat/docs/index.asciidoc
winlogbeat/docs/index.asciidoc

Hey look, same version everywhere :-)

Set docs versions for 5.0.0-alpha1

---

filebeat/docs/index.asciidoc
libbeat/docs/shared-config-ingest.asciidoc
packetbeat/docs/index.asciidoc
topbeat/docs/index.asciidoc
winlogbeat/docs/index.asciidoc

First draft of documentation about configuring beats to use ingest node.

Add doc about configuring ingest node

---

libbeat/docs/gettingstarted.asciidoc

Dir name for windows had copy/paste error.

fix directory name

---

libbeat/docs/shared-template-load.asciidoc

Fix typo and config file default.

Fix config filename

---

libbeat/docs/outputconfig.asciidoc

@urso Please review. I changed the language a bit from the text that I gave earlier.

Clarify support for Redis output

---

libbeat/docs/shared-config-ingest.asciidoc

@tsg I've added your example to the ingest node content.

Add example to the ingest node topic

---

dev-tools/packer/docker/xgo-image-deb6/beats-builder/gopacket_pcap.patch

Follow up for #1347 and #1354.

Fix the patch also for the deb6 image

---

topbeat/docs/gettingstarted.asciidoc

Cherry-pick proc monitoring example change into master.

cherry-pick change to config example that shows how to turn off process monitoring

---

filebeat/docs/reference/configuration/filebeat-options.asciidoc

Cherry pick of PR #1377 into 1.1

Clarify meaning of spool_size and harvester_buffer_size in 1.1 docs

---

filebeat/docs/reference/configuration/filebeat-options.asciidoc

Cherry pick of PR #1377 into 1.2

Clarify meaning of spool_size and harvester_buffer_size in 1.2 docs

---

dev-tools/packer/platforms/binary/run.sh.j2
dev-tools/packer/platforms/centos/run.sh.j2
dev-tools/packer/platforms/darwin/run.sh.j2
dev-tools/packer/platforms/debian/run.sh.j2
dev-tools/packer/platforms/windows/run.sh.j2
dev-tools/packer/xgo-scripts/before_build.sh
libbeat/scripts/Makefile

This installs the `etc/kibana` folder, if it exists in the Beat, to the home directory of the installation.

Install the etc/kibana dir in the home directory

---

winlogbeat/beater/winlogbeat.go
winlogbeat/main.go
winlogbeat/sys/doc.go

Godoc: https://godoc.org/github.com/elastic/beats/winlogbeat

Add missing godoc for Winlogbeat packages

---

vendor/github.com/elastic/gosigar/README.md
vendor/github.com/elastic/gosigar/examples/df/df.go
vendor/github.com/elastic/gosigar/sigar_darwin.go
vendor/github.com/elastic/gosigar/sigar_openbsd.go
vendor/github.com/elastic/gosigar/sigar_unix.go

These changes are needed in order to build topbeat on OpenBSD.
/cc @andrewkroh

sync with gosigar master

---

metricbeat/TODO.md
metricbeat/docs/developer-guide/create-metricset.asciidoc
metricbeat/docs/developer-guide/index.asciidoc

This is a first version with all required information. Cleanup in a second step is needed.

Metricbeat metricset developer guide

---

CHANGELOG.asciidoc

Shameless plug, but I think it's worth mentioning :smile:

Mention OpenBSD support for topbeat/packetbeat

---

filebeat/docs/index.asciidoc
filebeat/docs/securing-filebeat.asciidoc
libbeat/docs/https.asciidoc
libbeat/docs/shared-faq.asciidoc
libbeat/docs/shared-tls-logstash-config.asciidoc
packetbeat/docs/index.asciidoc
packetbeat/docs/securing-packetbeat.asciidoc
topbeat/docs/index.asciidoc
topbeat/docs/securing-topbeat.asciidoc
winlogbeat/docs/index.asciidoc
winlogbeat/docs/securing-winlogbeat.asciidoc

@andrewkroh You should probably review this since it's based on the doc you wrote.

Add more info to doc about configuring TLS

---

metricbeat/etc/fields.yml
metricbeat/etc/fields_base.yml
metricbeat/module/apache/status/status.go
metricbeat/module/apache/status/status_integration_test.go
metricbeat/module/apache/status/status_test.go
metricbeat/module/redis/info/info.go
metricbeat/tests/system/config/metricbeat.yml.j2
metricbeat/tests/system/test_apache.py
metricbeat/tests/system/test_redis.py

Improve host config parsing for apache-status metricset.
Document common fields in fields.yml.

Add apache-status system test for Metricbeat

---

CHANGELOG.asciidoc
filebeat/beat/publish_test.go
filebeat/crawler/crawler.go
filebeat/crawler/prospector.go
filebeat/crawler/registrar.go
filebeat/harvester/harvester.go
filebeat/harvester/harvester_test.go
filebeat/harvester/log.go
filebeat/input/file.go
filebeat/tests/system/filebeat.py
filebeat/tests/system/test_prospector.py
filebeat/tests/system/test_registrar.py

A direct commit backport was not possible as too many things changed in the prospector and harvester
Closes #1281

Backport of #1375

---

libbeat/docs/shared-template-load.asciidoc

Tiny change, but it's been bugging me. :-) Here's the fix. The fix is not relevant to 5.0 bec the wording has been changed there already.

Fix heading for  section about loading index template

---

libbeat/docs/outputconfig.asciidoc

This edits the docs added with PR #1353

Edit doc for Redis changes

---

filebeat/beater/publish.go
filebeat/crawler/prospector_log.go
filebeat/harvester/harvester.go
filebeat/harvester/linereader.go
filebeat/harvester/log.go
filebeat/input/event.go
filebeat/input/file.go
filebeat/input/state.go

* Cleanup variable naming
* Update state also if lines are skipped / excluded
* Introduce option to update state without sending an event

Filebeat refactoring and cleanup

---

metricbeat/TODO.md
metricbeat/docs/fields.asciidoc
metricbeat/etc/beat.yml
metricbeat/etc/fields.yml
metricbeat/etc/fields_base.yml
metricbeat/include/list.go
metricbeat/metricbeat.template.json
metricbeat/metricbeat.yml
metricbeat/module/system/cpu/cpu.go
metricbeat/module/system/cpu/fields.yml
metricbeat/module/system/memory/fields.yml
metricbeat/module/system/memory/memory.go
metricbeat/module/system/system.go
metricbeat/tests/system/test_system.py

* Add note what kind of refactoring is needed for fields.yml collection
This is the first step of https://github.com/elastic/beats/pull/1081

Add System module with CPU and Memory stats

---

libbeat/docs/newdashboards.asciidoc

This PR is just very small note about important requirement for export of the visualizations from elasticsearch. 
I have learned it from code, when I was not able to export what I was expecting :)
Feel free to adjust my text to more understandable format.

Update documentation with note about dashboard names requirement

---

testing/environments/docker/logstash/Dockerfile-2.3.2

Updated logstash version in env

---

filebeat/docs/index.asciidoc
libbeat/docs/index.asciidoc
packetbeat/docs/index.asciidoc
topbeat/docs/index.asciidoc
winlogbeat/docs/index.asciidoc

Opening this early, but should be merged only shortly before making the release.

Updated versions for 1.2.2 release

---

winlogbeat/config/config.go
winlogbeat/config/config_test.go

Change filter to filters in Winlogbeat config validation

---

metricbeat/Makefile
metricbeat/docs/fields.asciidoc
metricbeat/etc/fields.yml
metricbeat/etc/fields_base.yml
metricbeat/metricbeat.template.json
metricbeat/module/apache/fields.yml
metricbeat/module/apache/status/fields.yml
metricbeat/module/mysql/fields.yml
metricbeat/module/mysql/status/fields.yml
metricbeat/module/redis/fields.yml
metricbeat/module/redis/info/fields.yml
metricbeat/module/system/cpu/fields.yml
metricbeat/module/system/fields.yml
metricbeat/module/system/memory/fields.yml
metricbeat/scripts/fields_collector.py

* Add python script to collect fields.yml files
* Update templates and docs
* Add fields.yml for each module

Collect fields for modules and metricsets

---

packetbeat/docs/fields.asciidoc
packetbeat/etc/fields.yml
packetbeat/packetbeat.template.json
topbeat/docs/fields.asciidoc
topbeat/etc/fields.yml
topbeat/topbeat.template.json
winlogbeat/docs/fields.asciidoc
winlogbeat/etc/fields.yml
winlogbeat/winlogbeat.template.json

Update docs and templates
This PR depends on https://github.com/elastic/beats/pull/1493
Closes https://github.com/elastic/beats/issues/1176

Convert all int to integers in fields.yml

---

libbeat/scripts/generate_template.py
metricbeat/docs/fields.asciidoc
metricbeat/etc/fields.yml
metricbeat/metricbeat.template.json
metricbeat/module/apache/status/fields.yml
metricbeat/module/redis/info/fields.yml
packetbeat/docs/fields.asciidoc
packetbeat/etc/fields.yml
packetbeat/packetbeat.template.json
winlogbeat/docs/fields.asciidoc
winlogbeat/etc/fields.yml
winlogbeat/winlogbeat.template.json

* Add field validation to generation script
* Add Nested document support

Update templates with valid fields

---

CHANGELOG.asciidoc
libbeat/outputs/mode/single.go
libbeat/outputs/mode/single_test.go

Fix output plugins blocking startup if remote is not reachable.

---

filebeat/docs/index.asciidoc
filebeat/docs/reference/configuration/filebeat-options.asciidoc
libbeat/docs/loggingconfig.asciidoc
libbeat/docs/outputconfig.asciidoc
libbeat/docs/shared-directory-layout.asciidoc
libbeat/docs/shared-path-config.asciidoc
packetbeat/docs/index.asciidoc
topbeat/docs/index.asciidoc
winlogbeat/docs/index.asciidoc

Note that I've changed the location of the Directory Layout topic because I thought it would be useful for users to see this topic along with the installation steps. 
This PR closes #1448

Edit content about new directory layout added in PR #1441

---

dev-tools/import_dashboards.ps1
dev-tools/import_dashboards.sh

Looks like this PR was lost when moving between repos:
https://github.com/elastic/beats-dashboards/pull/98
Reapplied to make the lion happy.

Fix timelion issue with the default dashboards

---

filebeat/docs/migration.asciidoc

Cherry picks changes from #1520 into 1.2.

Cherry pick migration info for LSF to Beats input plugin

---

dev-tools/import_dashboards.ps1

- Catch the error when creating the kibana index (might exit already)
- Fixed broken lines
Fixes #1523.

Fix errors in the import_dashboards.ps1 script

---

dev-tools/import_dashboards.ps1
dev-tools/import_dashboards.sh

Catch errors from import_dashboards

---

packetbeat/docs/capturing.asciidoc
packetbeat/docs/thrift.asciidoc

PR #1490 missed a couple of topics that show config examples. 
Relates to #1417

Add packetbeat namespace to a couple of topics missed in PR #1490

---

filebeat/crawler/crawler.go
filebeat/crawler/prospector.go
filebeat/crawler/prospector_log.go
filebeat/crawler/prospector_stdin.go
filebeat/crawler/registrar.go
filebeat/harvester/harvester.go
filebeat/harvester/log.go
filebeat/harvester/stdin.go
filebeat/input/event.go
filebeat/input/file_other.go
filebeat/input/file_other_test.go
filebeat/input/file_windows.go
filebeat/input/file_windows_test.go

* Rename variables to be more meaningful
* Further cleanup separate of log and stding
* Remove references where not needed
* Several small reorganisations

Cleanup Filebeat code and structure to make it more readable

---

filebeat/crawler/prospector.go
filebeat/crawler/registrar.go
filebeat/input/file.go
filebeat/tests/system/test_registrar.py

Following changes were made
* All state information is fetched in advance for later comparison to prevent race conditions
* State is also written to registrar file if offset is 0, same for path
* Test case to validate fix added
Closes #1528

Testcase and Fix for Issue 1528

---

libbeat/docs/communitybeats.asciidoc

Novice users might not realize that they need to create the PR against the Beats repo, so I'm adding a link here.

Add link to Beats repo

---

CHANGELOG.asciidoc
libbeat/docs/release.asciidoc

Included a slight reorganization for the Changelog.

Closed changelog for 5.0-alpha2

---

libbeat/outputs/transport/transport.go

fix typo in DialerFunc typedef

---

metricbeat/mb/mb.go
metricbeat/mb/mb_test.go
metricbeat/module/zookeeper/fields.yml
metricbeat/module/zookeeper/mntr/data.go
metricbeat/module/zookeeper/mntr/mntr.go
metricbeat/module/zookeeper/mntr/mntr_integration_test.go
metricbeat/module/zookeeper/testing.go
metricbeat/module/zookeeper/zookeeper.go
metricbeat/tests/system/test_zookeeper.py

Also fixed all golint warnings for the ZooKeeper packages.

Add system test for the ZooKeeper mntr MetricSet

---

packetbeat/docs/reference/configuration/packetbeat-options.asciidoc

Edit new amqp content

---

vendor/github.com/elastic/gosigar/README.md
vendor/github.com/elastic/gosigar/sigar_darwin.go
vendor/github.com/elastic/gosigar/sigar_darwin_test.go
vendor/github.com/elastic/gosigar/sigar_interface.go
vendor/github.com/elastic/gosigar/sigar_linux.go
vendor/github.com/elastic/gosigar/sigar_linux_test.go
vendor/github.com/elastic/gosigar/sigar_openbsd.go

Merges:
```
From d752b700e76fa8e1a9270a8b5d332f5f736b2f94 Mon Sep 17 00:00:00 2001
From: nickivanov <nickivanov@users.noreply.github.com>
Date: Wed, 4 May 2016 10:28:24 -0400
Subject: [PATCH 1/2] Support process group ID (pgid) for Darwin and Linux (#26)
From e9bc408cebda400d161a8b852b38405fadce7502 Mon Sep 17 00:00:00 2001
From: Jasper Lievisse Adriaanse <jasper@humppa.nl>
Date: Fri, 6 May 2016 04:08:27 +0200
Subject: [PATCH 2/2] Implement CpuList for OpenBSD (#28)
```

Sync with elastic/gosigar as of e9bc408

---

glide.yaml
vendor/github.com/urso/ucfg/.travis.yml
vendor/github.com/urso/ucfg/CHANGELOG.md
vendor/github.com/urso/ucfg/error.go
vendor/github.com/urso/ucfg/error_test.go
vendor/github.com/urso/ucfg/path.go
vendor/github.com/urso/ucfg/reify.go
vendor/github.com/urso/ucfg/reify_test.go
vendor/github.com/urso/ucfg/testdata/error/message/invalid_regexp_w_meta.golden
vendor/github.com/urso/ucfg/testdata/error/message/invalid_regexp_wo_meta.golden
vendor/github.com/urso/ucfg/validator.go
vendor/github.com/urso/ucfg/validator_test.go

[release notes](https://github.com/urso/ucfg/releases/tag/v0.2.1)

Update ucfg v0.2.1

---

libbeat/scripts/Makefile

Fix make update command

---

metricbeat/Makefile

* Make paths dynamic
* Do not expect that directories already exist (first run)

Improve Makefile to make metricset generator possible

---

libbeat/docs/newdashboards.asciidoc

@monicasarbu should review this one.

Edits for dev guide on creating kibana dashboards

---

libbeat/scripts/Makefile
libbeat/scripts/generate_fields_docs.py

I added the same options in libbeat/scripts/generate_fields_docs.py as it is  in libbeat/scripts/generate_template.py

libbeat: fix 'make update' rule for community beats

---

filebeat/docs/index.asciidoc
libbeat/docs/index.asciidoc
libbeat/docs/release.asciidoc
packetbeat/docs/index.asciidoc
topbeat/docs/index.asciidoc
winlogbeat/docs/index.asciidoc

Please review but should be merged only tomorrow closer to the release time.

Versions bump 1.2.3

---

metricbeat/docs/fields.asciidoc
metricbeat/docs/modules/apache.asciidoc
metricbeat/docs/modules/mysql.asciidoc
metricbeat/docs/modules/nginx.asciidoc
metricbeat/docs/modules/redis.asciidoc
metricbeat/docs/modules/system.asciidoc
metricbeat/docs/modules/zookeeper.asciidoc
metricbeat/etc/beat.short.yml
metricbeat/etc/beat.yml
metricbeat/etc/fields.yml
metricbeat/metricbeat.short.yml
metricbeat/metricbeat.template-es2x.json
metricbeat/metricbeat.template.json
metricbeat/metricbeat.yml
metricbeat/module/apache/_beat/config.short.yml
metricbeat/module/apache/_beat/config.yml
metricbeat/module/mysql/_beat/config.short.yml
metricbeat/module/mysql/_beat/config.yml
metricbeat/module/nginx/_beat/config.yml
metricbeat/module/nginx/stubstatus/_beat/fields.yml
metricbeat/module/redis/_beat/config.short.yml
metricbeat/module/redis/_beat/config.yml
metricbeat/module/redis/_beat/fields.yml
metricbeat/module/system/_beat/config.short.yml
metricbeat/module/system/_beat/config.yml
metricbeat/module/system/_beat/fields.yml
metricbeat/module/zookeeper/_beat/config.yml
metricbeat/scripts/config_collector.py
metricbeat/scripts/docs_collector.py

* Adjust nginx to new naming structure
* Add dynamic title to docs

Auto generates title for config files

---

libbeat/docker-compose.yml
libbeat/scripts/docker-entrypoint.sh
metricbeat/docker-compose.yml
metricbeat/docs/fields.asciidoc
metricbeat/etc/fields.yml
metricbeat/metricbeat.template-es2x.json
metricbeat/metricbeat.template.json
metricbeat/module/doc.go
metricbeat/module/mysql/status/data.go
metricbeat/module/zookeeper/mntr/_beat/fields.yml
metricbeat/module/zookeeper/mntr/data.go
metricbeat/module/zookeeper/mntr/mntr_integration_test.go
metricbeat/tests/system/metricbeat.py
metricbeat/tests/system/test_zookeeper.py
testing/environments/base.yml
testing/environments/docker/logstash/Dockerfile-snapshot

* Introduce dedot script for easier testing
* Add documentation for key naming
This PR should be merged first: https://github.com/elastic/beats/pull/1651

Update fields for zookeeper with dots

---

dev-tools/import_dashboards.sh

This PR:
- fixes usage of simple variable 
- add check for file before trying it to remove

Fix simple variable usage and add check before removing tmp file

---

packetbeat/docs/packetbeat-filtering.asciidoc

This was just a test (didn't work) so I'm removing the passthru block.

Remove passthru link

---

libbeat/docs/gettingstarted.asciidoc

Update Java version to 8

---

libbeat/docs/index.asciidoc

Add banner to 1.2 dev guide indicating that it's out of date

---

libbeat/scripts/Makefile

Placed in a `scripts/` folder in the home path.

Add the migration script to the distributions

---

README.md

Point to instructions for building Beats from the source

---

filebeat/docs/migration.asciidoc

Fix example config to include fields_under_root

---

filebeat/filebeat.yml
libbeat/_beat/config.yml
metricbeat/metricbeat.yml
packetbeat/packetbeat.yml
topbeat/topbeat.yml
winlogbeat/winlogbeat.yml

This makes it really easy to go to debug mode. The default in the code (when the option is commented out) is still ERR.

Debug level in the default config (commented out)

---

metricbeat/module/apache/status/data.go

Metricbeat - apache: Move regexp.MustCompile to 'var' for performance improvement

---

testing/environments/alpha2.yml
testing/environments/docker/elasticsearch/Dockerfile-5.0.0-alpha1
testing/environments/docker/elasticsearch/Dockerfile-5.0.0-alpha2
testing/environments/docker/elasticsearch/Dockerfile-snapshot
testing/environments/docker/elasticsearch/setup.sh
testing/environments/docker/kibana/Dockerfile-snapshot
testing/environments/docker/logstash/Dockerfile-snapshot
testing/environments/docker/sredis/Dockerfile
testing/environments/snapshot.yml

Add script to simplify common parts between elasticsearch docker images

Add alpha3 snapshots for testing

---

dev-tools/packer/README.md
dev-tools/packer/platforms/darwin/run.sh.j2

Fixed arch for darwin

---

libbeat/scripts/generate_fields_docs.py
metricbeat/docs/developer-guide/index.asciidoc
metricbeat/docs/fields.asciidoc
metricbeat/docs/modules/system.asciidoc
metricbeat/module/system/_beat/docs.asciidoc
packetbeat/docs/fields.asciidoc

* Add docs for additional config options in system
* Change generation script to float intermediate titles. This only has an affect to metricbeat and packetbeat flows.
* Clean up organisation of the developer guide docs

Metricbeat documentation improvements

---

filebeat/docs/filebeat-filtering.asciidoc
libbeat/docs/filtering.asciidoc
libbeat/docs/filteringconfig.asciidoc
metricbeat/docs/metricbeat-filtering.asciidoc
packetbeat/docs/packetbeat-filtering.asciidoc
topbeat/docs/reference/configuration.asciidoc
topbeat/docs/topbeat-filtering.asciidoc

Update documentation for generic filtering to include details about conditions and update the examples for each Beat.
cc-ed: @dedemorton

Update generic filtering doc 

---

CHANGELOG.asciidoc
libbeat/docs/release.asciidoc

Also added Metricbeat to the Changelog template

Closing the changelog for alpha3

---

dev-tools/packer/Makefile

Removed it from the packer Makefile for now.

Disable topbeat build

---

testing/environments/docker/logstash/Dockerfile-snapshot
testing/environments/docker/logstash/setup.sh
testing/environments/snapshot.yml

Logstash has now binaries in a different directory

Fix logstash build

---

generate/metricbeat-metricset/.gitignore
generate/metricbeat-metricset/CHANGELOG.md
generate/metricbeat-metricset/LICENSE
generate/metricbeat-metricset/Makefile
generate/metricbeat-metricset/README.md
generate/metricbeat-metricset/cookiecutter.json
generate/metricbeat-metricset/tests/cookiecutter.json
generate/metricbeat-metricset/{{cookiecutter.beat}}/Makefile
generate/metricbeat-metricset/{{cookiecutter.beat}}/README.md
generate/metricbeat-metricset/{{cookiecutter.beat}}/glide.yaml
generate/metricbeat-metricset/{{cookiecutter.beat}}/main.go
generate/metricbeat-metricset/{{cookiecutter.beat}}/module/{{cookiecutter.module}}/_beat/config.yml
generate/metricbeat-metricset/{{cookiecutter.beat}}/module/{{cookiecutter.module}}/_beat/docs.asciidoc
generate/metricbeat-metricset/{{cookiecutter.beat}}/module/{{cookiecutter.module}}/_beat/fields.yml
generate/metricbeat-metricset/{{cookiecutter.beat}}/module/{{cookiecutter.module}}/doc.go
generate/metricbeat-metricset/{{cookiecutter.beat}}/module/{{cookiecutter.module}}/{{cookiecutter.metricset}}/_beat/data.json
generate/metricbeat-metricset/{{cookiecutter.beat}}/module/{{cookiecutter.module}}/{{cookiecutter.metricset}}/_beat/docs.asciidoc
generate/metricbeat-metricset/{{cookiecutter.beat}}/module/{{cookiecutter.module}}/{{cookiecutter.metricset}}/_beat/fields.yml
generate/metricbeat-metricset/{{cookiecutter.beat}}/module/{{cookiecutter.module}}/{{cookiecutter.metricset}}/{{cookiecutter.metricset}}.go
metricbeat/Makefile
metricbeat/scripts/generate_imports.py

This takes the code from https://github.com/ruflin/metricbeat-metricset-generator and copies into the beats repository.

Add metricbeat metricset generator

---

filebeat/docs/index.asciidoc
libbeat/docs/dashboards.asciidoc
libbeat/docs/index.asciidoc
libbeat/docs/installing-beats.asciidoc
libbeat/docs/newdashboards.asciidoc
libbeat/docs/outputconfig.asciidoc
libbeat/docs/overview.asciidoc
packetbeat/docs/index.asciidoc
topbeat/docs/index.asciidoc
winlogbeat/docs/index.asciidoc

Exorcises topbeat from the alpha3 docs

Remove topbeat references from the doc

---

CHANGELOG.asciidoc
libbeat/outputs/mode/balance.go

Backport fix for loadbalancer deadlock

---

libbeat/docs/communitybeats.asciidoc

Adds cloudtrailbeat plus a couple of minor edits.

Add cloudtrailbeat to community beats list in master

---

filebeat/docs/getting-started.asciidoc
libbeat/docs/shared-logstash-config.asciidoc
packetbeat/docs/gettingstarted.asciidoc
topbeat/docs/gettingstarted.asciidoc

Cherry pick doc change from master into 1.2

Add info about testing the config file

---

metricbeat/docs/developer-guide/create-metricset.asciidoc
metricbeat/docs/developer-guide/faq.asciidoc
metricbeat/docs/developer-guide/index.asciidoc
metricbeat/docs/developer-guide/metricset-details.asciidoc
metricbeat/scripts/module/metricset/metricset.go.tmpl

Like this the beat generated by beats generator and metricset generator is the same.
This also gives an example on how state should be handled in a metricset.

Modify metricset generator to be countbeat

---

libbeat/docs/communitybeats.asciidoc

Cherry pick community beats fixes from 1.2

---

CHANGELOG.asciidoc
packetbeat/protos/memcache/plugin_tcp.go

Memcache gap handler: add missing nil-check

---

CHANGELOG.asciidoc
metricbeat/module/system/core/core.go

Solves bug https://github.com/elastic/beats/issues/1787

Fix the CPU values returned for each core

---

Makefile
libbeat/scripts/build_docs.sh

Add build docs script

---

libbeat/docs/newdashboards.asciidoc

Was "To make made it even ..." before.

Removed typo "made" from the note

---

libbeat/outputs/elasticsearch/output_test.go
testing/environments/5.0.0-alpha4.yml
testing/environments/docker/elasticsearch/Dockerfile-5.0.0-alpha4
testing/environments/docker/elasticsearch/Dockerfile-snapshot
testing/environments/docker/kibana/Dockerfile-5.0.0-alpha4
testing/environments/docker/kibana/Dockerfile-snapshot
testing/environments/docker/logstash/Dockerfile-5.0.0-alpha4
testing/environments/docker/logstash/Dockerfile-snapshot
testing/environments/docker/logstash/logstash.conf.2.tmpl

* Disable tests which use _ttl
* Temporarly disable user / password for LS build because it breaks the build

Update dependencies to alpha4

---

metricbeat/docs/modules/mongodb.asciidoc
metricbeat/etc/beat.full.yml
metricbeat/etc/beat.yml
metricbeat/etc/fields.yml
metricbeat/metricbeat.full.yml
metricbeat/metricbeat.yml
metricbeat/module/mongodb/_meta/config.yml
metricbeat/module/mongodb/_meta/fields.yml

And comment it out in the full config.

Remove MongoDB from the default config

---

CHANGELOG.asciidoc

Update changelog with the changes from #1837

Update changelog with the mongodb module

---

filebeat/docs/getting-started.asciidoc
libbeat/docs/gettingstarted.asciidoc
metricbeat/docs/gettingstarted.asciidoc
packetbeat/docs/gettingstarted.asciidoc

@tsg Here are the updates to the file names. Please merge this when the release goes live. I noticed that the name of the logstash package changed in the release tracking issue, so I've updated that, too. I'll assume it won't change again since it's on the download site. :-)

Update file paths for 5.0.0 alpha4

---

filebeat/docs/version.asciidoc
filebeat/filebeat.full.yml
libbeat/docs/version.asciidoc
metricbeat/docs/version.asciidoc
packetbeat/docs/version.asciidoc
winlogbeat/docs/version.asciidoc

To be merged shortly before the release.

Docs version bump to alpha4

---

filebeat/docs/filebeat-filtering.asciidoc
libbeat/docs/shared-template-load.asciidoc
metricbeat/docs/gettingstarted.asciidoc

Fixes a few small nits found while testing the GS topics.

Fix a few minor issues noticed during testing

---

dev-tools/packer/platforms/windows/run.sh.j2

Fixed the folder name for the windows packages

---

filebeat/docs/filebeat-filtering.asciidoc
libbeat/docs/filtering.asciidoc
libbeat/docs/filteringconfig.asciidoc
metricbeat/docs/metricbeat-filtering.asciidoc
packetbeat/docs/packetbeat-filtering.asciidoc
winlogbeat/docs/winlogbeat-filtering.asciidoc

This PR adds annotations to indicate configs that are required for alpha4 vs beta1. Also includes a few quick edits (I need to do a more thorough edit later).

Add config examples with deprecation text to support alpha4 and beta1

---

glide.yaml
vendor/github.com/elastic/gosigar/.appveyor.yml
vendor/github.com/elastic/gosigar/.gitignore
vendor/github.com/elastic/gosigar/.travis.yml
vendor/github.com/elastic/gosigar/concrete_sigar_test.go
vendor/github.com/elastic/gosigar/psnotify/psnotify_test.go
vendor/github.com/elastic/gosigar/sigar_darwin_test.go
vendor/github.com/elastic/gosigar/sigar_freebsd.go
vendor/github.com/elastic/gosigar/sigar_interface_test.go
vendor/github.com/elastic/gosigar/sigar_linux.go
vendor/github.com/elastic/gosigar/sigar_linux_common.go
vendor/github.com/elastic/gosigar/sigar_linux_test.go
vendor/github.com/elastic/gosigar/sigar_unix.go

Update gosigar library to include the fix from  elastic/gosigar#34

Update vendor with the latest gosigar library

---

libbeat/outputs/mode/lb/async_worker.go
libbeat/outputs/mode/lb/sync_worker.go
libbeat/outputs/mode/single/single.go

Transform a debug in Info for the loadbalancing mode, to make sure
we have at least an Info on any connection failure.
Part of #1931.

Log connection attempts

---

libbeat/docs/loggingconfig.asciidoc
libbeat/docs/runconfig.asciidoc
packetbeat/docs/reference/configuration/packetbeat-options.asciidoc

Cherry-pick doc changes from PR #1964 into 1.3.

Remove optional from config topic headings

---

packetbeat/docs/index.asciidoc

Update link to the processors definition

---

filebeat/docs/faq.asciidoc
libbeat/docs/shared-tls-logstash-config.asciidoc

Just a couple of unrelated changes based on confusion I've seen in forum discussions.

Modify ca statement

---

filebeat/beater/filebeat.go
filebeat/config/config.go
filebeat/main.go
filebeat/publish/publish.go
filebeat/tests/system/test_prospector.py
generate/beat/{{cookiecutter.beat}}/beater/{{cookiecutter.beat}}.go
generate/beat/{{cookiecutter.beat}}/main.go
generate/metricbeat/metricset/{{cookiecutter.beat}}/main.go
libbeat/beat/beat.go
libbeat/beat/beat_test.go
libbeat/libbeat.go
libbeat/mock/mockbeat.go
libbeat/publisher/client.go
libbeat/publisher/publish.go
metricbeat/beater/metricbeat.go
metricbeat/main.go
metricbeat/tests/system/test_base.py
packetbeat/beater/packetbeat.go
packetbeat/main.go
packetbeat/publish/publish.go
winlogbeat/beater/winlogbeat.go
winlogbeat/config/config.go
winlogbeat/main.go

pass Beater constructor to beat.Run + simplify Beater interface to only require
Run and Stop methods.

Simplify Beater interface

---

filebeat/docs/faq.asciidoc
libbeat/docs/shared-tls-logstash-config.asciidoc

Cherry-pick of doc changes made in 1.2:
* Add workaround for restriction around intermediate CAs
* Add FAQ topic to Filebeat doc explaining that newline is required at eof

Modify ca statement (#1971) in master

---

filebeat/docs/faq.asciidoc
libbeat/docs/shared-tls-logstash-config.asciidoc

Cherry-pick of doc changes made in 1.2:
* Add workaround for restriction around intermediate CAs
* Add FAQ topic to Filebeat doc explaining that newline is required at eof

Modify ca statement (#1971)

---

libbeat/docs/event-conventions.asciidoc
libbeat/docs/index.asciidoc
libbeat/docs/newbeat.asciidoc

Update the developer guide about how to create a new Beat and also include the conventions about how to name the fields in the event.

Update the developer guide about how to create a new Beat

---

generate/beat/{{cookiecutter.beat}}/README.md

Use `make setup` instead of `make init` and `make commit`.

Update the README with the latest changes

---

CHANGELOG.asciidoc
libbeat/outputs/console/console.go
libbeat/outputs/console/console_test.go

Check stdout being available in console output

---

CHANGELOG.asciidoc
libbeat/outputs/console/console.go
libbeat/outputs/console/console_test.go

backport of #2047 fixing #2035 in 1.3.

Backport: Check stdout being available in console output

---

filebeat/docs/multiline.asciidoc

... at least in this single document. ;-)

Docs: Use [source,yaml] format for all YAML snippets.

---

filebeat/docs/multiline.asciidoc

Forward ported fix from #2062

---

filebeat/docs/multiline.asciidoc

Forward ported docs fix from #2062 to 1.3 branch

---

libbeat/common/fmtstr/formatevents.go
libbeat/common/fmtstr/formatevents_test.go

Add Unpack method to EventFormatString and MustCompile, in order to make
EventFormatString usable with `config.Unpack(...)`

EventFormatString unpack for use with configurations

---

filebeat/docs/filebeat-filtering.asciidoc
libbeat/docs/processors-config.asciidoc
libbeat/docs/processors.asciidoc
metricbeat/docs/metricbeat-filtering.asciidoc
packetbeat/docs/packetbeat-filtering.asciidoc
winlogbeat/docs/winlogbeat-filtering.asciidoc

- changed beta1 > alpha5
- changed "coming" to "added" in preparation for the upcoming release.

Update doc annotations for alpha5

---

libbeat/docs/communitybeats.asciidoc

cherrypicks this change into 1.3

Move up note about community beats support (1.3 branch)

---

libbeat/docs/communitybeats.asciidoc

cherry-picks the change into the 5.0 branch

Move up note about community beats support (5.0 branch) 

---

libbeat/docs/communitybeats.asciidoc

cherrypick the change into master

Move up note about community beats support (master branch) 

---

libbeat/docs/communitybeats.asciidoc

I goofed yesterday. I created a PR to merge this into 5.0, but selected master instead. Derp. This time I *really* mean it.

Move up note about community beats support (5.0 branch)

---

testing/environments/docker/kibana/Dockerfile-5.0.0-alpha5
testing/environments/docker/logstash/Dockerfile-5.0.0-alpha5
testing/environments/docker/logstash/setup.sh

Also fixed the Logstash image, since I think the location of the
logstash-plugin script was changed.

Update testing env to latest alpha5 IRC

---

filebeat/harvester/reader/multiline.go
filebeat/harvester/reader/multiline_test.go

* Document functions
* Rename and split up some of the functions for simplicity
No changes to the logic were made.

Cleanup Multiline Code

---

filebeat/docs/reference/configuration/filebeat-options.asciidoc

Cherry-picks changes for #2127 into 1.3.

clarify order of execution for inlcude_lines and exclude_lines (cherrypick into 1.3)

---

filebeat/docs/reference/configuration/filebeat-options.asciidoc

cherry-pick doc changes for #2127 into master.

clarify order of execution for inlcude_lines and exclude_lines (cherry-pick into master)

---

libbeat/docs/loggingconfig.asciidoc

* change defaults shown in doc for to_syslog and to_files

change defaults shown in doc for to_syslog and to_files (cherrypick into 5.0)

---

CHANGELOG.asciidoc
libbeat/docs/release.asciidoc

Closing changelog for alpha5

---

CHANGELOG.asciidoc
libbeat/docs/release.asciidoc

Port closing changelog for alpha5 (#2139)

---

metricbeat/module/mysql/mysql_integration_test.go
metricbeat/module/redis/info/_meta/data.json
metricbeat/module/redis/redis_integration_test.go

* Fix make generate-json for redis and mysql by including the data flag

Update redis json example

---

testing/environments/docker/logstash/Dockerfile-snapshot
testing/environments/docker/logstash/setup.sh

Remove git as dependency as not needed.

Improve Logstash build to make it more reliable

---

filebeat/docs/version.asciidoc
libbeat/docs/version.asciidoc
metricbeat/docs/version.asciidoc
packetbeat/docs/version.asciidoc
winlogbeat/docs/version.asciidoc

Don't merge this one yet, please. Let's do that ~1h before the release time.

Docs version bump to alpha5

---

libbeat/docs/dashboards.asciidoc

This is a proposal documentation of the workaround for #2208.

Document workaround for alpha5

---

glide.yaml
vendor/github.com/elastic/gosigar/cgroup/util.go

Depends on: https://github.com/elastic/gosigar/pull/40
Fixes #2200

Update gosigar to fix cgroup bug

---

libbeat/docs/dashboards.asciidoc

@monicasarbu Not sure if I got the details quite right in this note. Please review.

Remove note about Kibana versions

---

filebeat/docs/multiline.asciidoc

This is a replacement for PR #2053 (using Tudor's suggestion for the change). Didn't include the explanatory sentence because it was no longer relevant.

Fix multiline example

---

libbeat/docs/dashboards.asciidoc

Remove note about Kibana version support (cherry-pick into 5.0)

---

metricbeat/docs/faq.asciidoc
packetbeat/docs/faq.asciidoc
winlogbeat/docs/faq.asciidoc

Cherry-pick of changes from #2211 into 5.0.

Add links to topics covered in the FAQ (cherry-pick into 5.0)

---

libbeat/tests/system/base.py
libbeat/tests/system/test_base.py
libbeat/tests/system/test_dashboard.py

* Move test_version test to base tests as it should not be in base.py

Add system test to load dashboards

---

filebeat/docs/multiline.asciidoc

Cherry pick #2228 into 5.0

---

filebeat/docs/reference/configuration/filebeat-options.asciidoc

Add details that it doesn't apply to files seen before.
Closes #1458

Improve tail_files documentation

---

CHANGELOG.asciidoc
libbeat/outputs/elasticsearch/client.go
libbeat/outputs/elasticsearch/client_test.go
libbeat/outputs/elasticsearch/json_read.go

- Fix json recursive structured raw content collection
- Add unit test based on ingest node error message
Resolves: #2229

Fix Elasticsearch structured error reponse parsing error

---

CONTRIBUTING.md

Just a light edit because I noticed a few typos while going through these instructions.

Edits to CONTRIBUTING.md

---

filebeat/docs/faq.asciidoc
libbeat/docs/faq-limit-bandwidth.asciidoc
libbeat/docs/shared-faq.asciidoc
packetbeat/docs/faq.asciidoc
topbeat/docs/faq.asciidoc
winlogbeat/docs/faq.asciidoc

Made additional changes to accommodate Topbeat for 1.2.

Add FAQ structural changes to 1.2

---

libbeat/tests/system/test_dashboard.py

Working on making some Jenkins jobs green.

Run dashboard tests only with integration tests

---

filebeat/docs/faq.asciidoc
libbeat/docs/faq-limit-bandwidth.asciidoc
libbeat/docs/shared-faq.asciidoc
packetbeat/docs/faq.asciidoc
topbeat/docs/faq.asciidoc
winlogbeat/docs/faq.asciidoc

a cherry pick a day keeps the merge conflict away....

Cherry pick FAQ changes into 1.3

---

libbeat/docs/processors-config.asciidoc

Document contains processor works on an array of strings

---

glide.yaml
vendor/github.com/tsg/gopacket/layers/ip4.go

Update gopacket library, to include the fix from https://github.com/tsg/gopacket/pull/4 requested by https://github.com/elastic/beats/issues/2201.

Update gopacket library

---

glide.yaml
vendor/github.com/elastic/gosigar/cgroup/cpuacct.go
vendor/github.com/elastic/gosigar/cgroup/reader.go
vendor/github.com/elastic/gosigar/cgroup/util.go

Merges elastic/gosigar#42 into Beats

Update gosigar version

---

libbeat/dashboards/import_dashboards.go

Depends on #2320 
Add -only option to be able to import only dashboards or index-pattern. By default both, dashboards and index-pattern are imported.
Fix script to be able to import dashboards from a local directory. For this, -dir option is used only to import from a local directory, and it's not used in addition to the -url or -file options. If the dashboards archive contains dashboards for multiple Beats, then you can specify the Beat name under the -beat option.

Import only dashboards or index pattern

---

CHANGELOG.asciidoc

As requested by @brandonmensing.

Clarify deprecation notice for symlinks

---

libbeat/docs/event-conventions.asciidoc
libbeat/docs/newbeat.asciidoc

First pass edit of content changes made for alpha. I have quite a few questions added as comments.
@monicasarbu Can you respond to the general questions?
@ruflin I think Monica said that the naming convents are based on something you wrote. If so, can you answer my questions in that section? Adding some concrete examples might be enough to clarify what you mean there.

Edits to content about generating a beat

---

testing/environments/docker/logstash/Dockerfile-snapshot
testing/environments/docker/logstash/logstash.conf.2.tmpl

* Add more debug options for easier debugging

Update Logstash to most recent Snapshot

---

libbeat/dashboards/import_dashboards.go

Use packetbeat-* instead of packetbeat as name for the index pattern.

Fix index-pattern name in Kibana

---

filebeat/filebeat.full.yml
libbeat/_meta/config.full.yml
metricbeat/metricbeat.full.yml
packetbeat/packetbeat.full.yml
winlogbeat/winlogbeat.full.yml

Set info as log level in the full configs

---

filebeat/harvester/reader/multiline.go

* Rename clearBuffer to clear as it clears the reader
* Renamed resetBuffer to load as it loads data into the reader

Use message struct to store internal state in multiline

---

filebeat/input/file/state.go
filebeat/prospector/prospector_log.go
filebeat/registrar/registrar.go
metricbeat/docs/fields.asciidoc
metricbeat/etc/fields.yml
metricbeat/metricbeat.template-es2x.json
metricbeat/metricbeat.template.json
metricbeat/module/beats/filebeat/_meta/data.json
metricbeat/module/beats/filebeat/_meta/fields.yml
metricbeat/module/beats/filebeat/data.go
metricbeat/module/beats/libbeat/_meta/data.json

* Improve registrar metrics
* Add data.json files

Add registrar stats to filebeat metricset

---

Makefile

Just to show the progress along the way.

Echo a message before building the dashboards

---

libbeat/docs/index.asciidoc

Override default header for Dev Guide topics only (1.1)

---

libbeat/docs/dashboards.asciidoc
libbeat/docs/newdashboards.asciidoc

I have updated the docs to include the latest changes about the Kibana dashboards.
Implements https://github.com/elastic/beats/issues/1943.
cc-ed @dedemorton

Update docs for managing Kibana dashboards

---

libbeat/dashboards/import_dashboards.go

This PR fixes unzipping of any zip archive that contains the dashboards. The zip archive can have either a separate directory containing subdirectories: `index-pattern`, `dashboard`, `search`, and `visualization`, or directly these directories.
If any of the directories is missing, no error is printed.

Fix unzipping of any zip archive with the dashboards

---

filebeat/spooler/spooler.go

In the previous code, the flush always happened after timeout, independent if a flush just happened before. This could lead to unnecessary flushes. In case the spooler is full and data is flushed, the ticker will be reset.
Previously the ticker was set to timeout/2. Now it is timeout.

Change spooler timeout flush to happen after lastFlush + timeout

---

packetbeat/docs/faq.asciidoc

Remove note about Npcap being

---

filebeat/docs/reference/configuration/filebeat-options.asciidoc

Fix regexp syntax used in examples

---

packetbeat/docs/filtering.asciidoc
packetbeat/docs/packetbeat-filtering.asciidoc

Adds name changes described in #2243 
@monicasarbu Will these changes get merged into 5.0 before the Beta, or do I need to cherry-pick them? The changes that you made for #2241 are only in master (I think) so I'll leave these in master, too.

Fix examples for changes in #2167

---

filebeat/docs/reference/configuration/filebeat-options.asciidoc

Fixed a few typos and minor grammatical issues. 
Still plan to do a technical edit of this content before GA.

Fix typos in close options

---

filebeat/docs/reference/configuration/filebeat-options.asciidoc

Cherrypicks #2396 into 1.3 branch.

Fix regexp syntax used in examples (cherry-pick #2396 into 1.3)

---

filebeat/docs/reference/configuration/filebeat-options.asciidoc

Cherry pick #2396 into master branch.

Fix regexp syntax used in examples (cherrypick #2396 into master)

---

filebeat/docs/reference/configuration/filebeat-options.asciidoc

Cherrypicks #2396 into the 5.0 branch.

Fix regexp syntax used in examples (cherrypicks #2396 into 5.0)

---

filebeat/docs/fields.asciidoc
filebeat/etc/fields.yml

Clarify how to set beat.name (cherry-pick #2398 into 1.3)

---

filebeat/docs/reference/configuration/filebeat-options.asciidoc

Fix typos in close options (cherry-pick #2403 into 5.0)

---

packetbeat/docs/faq.asciidoc

Remove note about Npcap being (cherry-pick #2399 into 5.0)

---

packetbeat/docs/faq.asciidoc

Cherry-picks changes from #2399  into master.

Remove note about Npcap being (cherry-pick #2399 into master)

---

packetbeat/docs/faq.asciidoc

Cherry-picks changes from #2399 into 1.3

Remove note about Npcap being (cherry-pick #2399 into 1.3)

---

filebeat/docs/fields.asciidoc
libbeat/_meta/fields.yml
metricbeat/docs/fields.asciidoc
packetbeat/docs/fields.asciidoc
winlogbeat/docs/fields.asciidoc

Fix for #2280 in the master branch.

Clarify how to set the shipper name

---

libbeat/docs/visualizing-data.asciidoc

Add overview links to dashboard container topic (cherry-pick into 1.3)

---

metricbeat/module/system/diskio/_meta/data.json

Reported here: https://discuss.elastic.co/t/diskio-documentation-update/59601

Fix diskio sample event in docs

---

filebeat/harvester/log_test.go
filebeat/harvester/reader/json.go
filebeat/harvester/reader/message.go
filebeat/harvester/reader/reader.go
filebeat/harvester/reader/timeout.go
filebeat/harvester/util.go

Minor naming cleanup in reader

---

dev-tools/packer/xgo-scripts/before_build.sh

Backport of #2458

---

libbeat/dashboards/Makefile
libbeat/dashboards/import_dashboards.go
libbeat/docs/dashboards.asciidoc
libbeat/docs/newdashboards.asciidoc

Backport #2429 to 5.0

---

filebeat/docs/getting-started.asciidoc
filebeat/docs/index.asciidoc
libbeat/docs/shared-logstash-config.asciidoc
libbeat/docs/shared-template-load.asciidoc
packetbeat/docs/index.asciidoc
topbeat/docs/index.asciidoc
winlogbeat/docs/index.asciidoc

Also made a few misc changes to reflect some changes that we've made or are making in master.

Clarify that manual template loading is required for Logstash output

---

filebeat/docs/index.asciidoc
libbeat/docs/index.asciidoc
libbeat/docs/shared-ssl-logstash-config.asciidoc
metricbeat/docs/index.asciidoc
packetbeat/docs/index.asciidoc
winlogbeat/docs/index.asciidoc

Change security doc URL to variable

---

filebeat/docs/getting-started.asciidoc
libbeat/docs/shared-logstash-config.asciidoc
libbeat/docs/shared-template-load.asciidoc

Cherry-picks issue #2449 into master.

Clarify that manual template loading is required for Logstash output (cherry-pick into master)

---

filebeat/docs/getting-started.asciidoc
libbeat/docs/shared-logstash-config.asciidoc
libbeat/docs/shared-template-load.asciidoc

Clarify that manual template loading is required for Logstash output (cherrypick into 5.0)

---

filebeat/tests/system/test_multiline.py

Test https://discuss.elastic.co/t/multiline-breaks-on-empty-line-n-n-restarts-new-line/59717

Add multiline system tests to check for consecutive newlines

---

CHANGELOG.asciidoc
filebeat/input/event.go
filebeat/publish/publish.go
filebeat/tests/system/config/filebeat.yml.j2
filebeat/tests/system/test_publisher.py

Backport of https://github.com/elastic/beats/pull/2455

Fix async publisher sending empty events

---

dev-tools/packer/version.yml
filebeat/filebeat.template-es2x.json
filebeat/filebeat.template.json
libbeat/beat/version.go
metricbeat/metricbeat.template-es2x.json
metricbeat/metricbeat.template.json
packetbeat/packetbeat.template-es2x.json
packetbeat/packetbeat.template.json
winlogbeat/winlogbeat.template-es2x.json
winlogbeat/winlogbeat.template.json

Set version to 6.0.0-alpha1 in master

---

dev-tools/packer/version.yml
libbeat/beat/version.go

This will require a `make update` after master is merged into it.

Set version to 5.0.0-beta1

---

filebeat/beater/channels.go

ensure closed channels can not be used for sending after having been closed.

filebeat Channels close

---

metricbeat/docs/metricbeat-in-a-container.asciidoc

The sub-topics are short and can all go on a single page.

Add float tags to Running Metricbeat in a Container topic

---

libbeat/dashboards/import_dashboards.go

Testing the snapshot builds its a little bit painful the load the snapshot dashboards. Because of this I introduce a -snapshot flag to load these dashboards automatically. This could even be improved if the snapshot build of `import_dashboards` would by default load the snapshot dashboards. It would require that additional flags are passed to the build.

Allow snapshot dashboards to be loaded

---

filebeat/docs/getting-started.asciidoc
packetbeat/docs/visualizing-data-packetbeat.asciidoc

Fix links that are broken in the doc build.

Fix broken links in doc build

---

libbeat/docs/communitybeats.asciidoc

Updates list of community beats in the current release of the docs.

Cherrypick communitybeats 9.13.16

---

filebeat/docs/index.asciidoc
libbeat/docs/index.asciidoc
packetbeat/docs/index.asciidoc
topbeat/docs/index.asciidoc
winlogbeat/docs/index.asciidoc

Should only be merged a couple of hours before the release.

Docs version change to 1.3.1

---

packetbeat/protos/http/http.go

Remove println from Packetbeat http header code

---

libbeat/docs/outputconfig.asciidoc
metricbeat/docs/developer-guide/create-metricset.asciidoc
metricbeat/docs/metricbeat-in-a-container.asciidoc

Cherrypicks doc changes for #2549 and #2564 into 5.0.

Cherrypick doc changes into 5.0

---

filebeat/docs/faq.asciidoc
filebeat/docs/reference/configuration/filebeat-options.asciidoc
libbeat/docs/shared-command-line.asciidoc
libbeat/docs/shared-ssl-logstash-config.asciidoc
winlogbeat/docs/fields.asciidoc
winlogbeat/etc/fields.yml

Resolves issues listed under "Misc content changes" in #2482 
@urso The changes to faq.asciidoc are the result of some comments that you made. Can you make sure I got the details right? Also can you confirm that the root CA restriction is removed? If so, let me know whether to backport the changes.

Misc content changes

---

dev-tools/cherrypick_pr

Modeled after `merge_pr`. Didn't fully test this yet, waiting for
something to cherry pick :-).

Added script to simplify cherry picking

---

libbeat/outputs/redis/client.go

Fix redis error log message

---

CHANGELOG.asciidoc

Plus taking out the Metricbeat Beats module from the changelog.

Light Changelog editing

---

libbeat/dashboards/import_dashboards.go

Backport: Fix dashboard link (#2598)

---

libbeat/docs/outputconfig.asciidoc

* Running `make collect` revealed some updates

Add note about compression_level vs cpu usage to docs

---

testing/environments/docker/elasticsearch/Dockerfile-snapshot
testing/environments/docker/kibana/Dockerfile-snapshot
testing/environments/docker/logstash/Dockerfile-snapshot

Beside the hash change, "download" was changed into "downloads".

Updated testing env to beta1 RC4

---

filebeat/docs/version.asciidoc
libbeat/docs/version.asciidoc
metricbeat/docs/version.asciidoc
packetbeat/docs/version.asciidoc
winlogbeat/docs/version.asciidoc

Please don't merge this one until 1-2 hours before the release time.

Version change for docs

---

filebeat/docs/getting-started.asciidoc
libbeat/docs/gettingstarted.asciidoc
libbeat/docs/newdashboards.asciidoc
metricbeat/docs/gettingstarted.asciidoc
packetbeat/docs/gettingstarted.asciidoc

Backport: Fix URLs for download (#2621)

---

libbeat/docs/newdashboards.asciidoc

Cherrypicks doc changes from #2576 into 5.0 branch.

Cherrypick dashboard edits

---

CHANGELOG.asciidoc
metricbeat/Makefile

Backport of 2632

---

libbeat/docs/communitybeats.asciidoc

A Beat to stream data from OpenConfig-compatible network devices.

Add openconfigbeat to the community beats

---

CHANGELOG.asciidoc
filebeat/harvester/reader/line.go
filebeat/tests/system/test_harvester.py

Based on https://github.com/elastic/beats/pull/2416

Fix input buffer on encoding problem

---

libbeat/docs/gettingstarted.asciidoc

Fix ES URLs for download

---

libbeat/docs/gettingstarted.asciidoc

Noticed more incorrect download links while testing the GS, so I changed the URLs to match the download site.

Fix addl download links

---

libbeat/docs/gettingstarted.asciidoc

cherry-picks #2675 into 5.0 branch.

Fix addl download links (cherrpick 2675 into 5.0)

---

CHANGELOG.asciidoc
libbeat/common/mapstr.go
libbeat/processors/actions/drop_fields.go
libbeat/processors/actions/include_fields.go
libbeat/processors/processor_test.go

Backport: Fix drop_fields when the first field is unknown (#2685)

---

CHANGELOG.asciidoc
filebeat/docs/reference/configuration/filebeat-options.asciidoc
filebeat/filebeat.full.yml
libbeat/_meta/config.full.yml
libbeat/docs/outputconfig.asciidoc
metricbeat/metricbeat.full.yml
packetbeat/packetbeat.full.yml
winlogbeat/winlogbeat.full.yml

Backports the following doc PRs to 5.0:
#2597 
#2620 
#2633 
#2628

Backport mutliple doc changes to 5.0 (2597, 2620, 2633, 2628)

---

CHANGELOG.asciidoc
glide.yaml
vendor/github.com/elastic/go-ucfg/CHANGELOG.md
vendor/github.com/elastic/go-ucfg/README.md
vendor/github.com/elastic/go-ucfg/reify.go
vendor/github.com/elastic/go-ucfg/types.go
vendor/github.com/elastic/go-ucfg/util.go

fixes issues regarding dynamic type conversation of settings read from
environment variables

Update go-ucfg to version 0.3.7

---

filebeat/README.md
metricbeat/README.md
packetbeat/README.md

* Adjusts Metricbeat README.md to be in line with other beats
* Fixes old issue link in Filebeat and Packetbeat

Update Metricbeat README.md file

---

testing/environments/docker/elasticsearch/Dockerfile-snapshot
testing/environments/docker/kibana/Dockerfile-snapshot
testing/environments/docker/logstash/Dockerfile-snapshot

Updated testing env to the latest RC1 build

---

CHANGELOG.asciidoc
libbeat/docs/release.asciidoc

Forward port: Preparing changelog for RC1 (#2721)

---

filebeat/docs/version.asciidoc
libbeat/docs/version.asciidoc
metricbeat/docs/version.asciidoc
packetbeat/docs/version.asciidoc
winlogbeat/docs/version.asciidoc

Do not merge this one please until a few hours before the release. Otherwise we break the release links in the getting started guide.

Update docs versions to rc1

---

CHANGELOG.asciidoc

Fwdport: With RC1 build5, two more fixes got in (#2730)

---

dev-tools/packer/version.yml
filebeat/filebeat.template-es2x.json
filebeat/filebeat.template.json
libbeat/beat/version.go
metricbeat/metricbeat.template-es2x.json
metricbeat/metricbeat.template.json
packetbeat/packetbeat.template-es2x.json
packetbeat/packetbeat.template.json
winlogbeat/winlogbeat.template-es2x.json
winlogbeat/winlogbeat.template.json

Lets merge this one immediately after the release is done.

Bump version to rc2

---

libbeat/docker-compose.yml
libbeat/docs/outputconfig.asciidoc
metricbeat/docker-compose.yml
metricbeat/docs/modules/redis.asciidoc
metricbeat/module/redis/_meta/docs.asciidoc

Make sure libbeat and metricbeat use the same version

Update redis dependency to 3.2.4

---

CHANGELOG.asciidoc
glide.yaml
vendor/github.com/elastic/gosigar/sigar_darwin.go

Update Gosigar dep

---

CHANGELOG.asciidoc
glide.yaml
vendor/github.com/elastic/gosigar/sigar_darwin.go

Backport of #2573. Original message: In an attempt to fix #2747.

Update Gosigar dep (#2753)

---

README.md

Update README.md with Heartbeat and Metricbeat

---

.travis.yml
libbeat/docker-compose.yml
metricbeat/docker-compose.yml
metricbeat/module/redis/info/info_integration_test.go

Update to docker-compose 1.8.1 in travis

Use alpine image for redis build

---

filebeat/input/file/state_test.go

Verifying that states work as expected.

Add unit tests for state cleanups

---

dev-tools/packer/platforms/binary/build.sh
dev-tools/packer/platforms/centos/build.sh
dev-tools/packer/platforms/darwin/build.sh
dev-tools/packer/platforms/debian/build.sh
dev-tools/packer/platforms/windows/build.sh
dev-tools/packer/readme.md.j2
dev-tools/packer/xgo-scripts/before_build.sh
filebeat/Makefile
libbeat/scripts/Makefile
metricbeat/Makefile
packetbeat/Makefile
winlogbeat/Makefile

* Add README.md to homedir to be part of each package
* Update description of each beat to make more sense in this context
* Add version.yml to package.yml file so it doesn't have to be added in each build
Closes https://github.com/elastic/beats/issues/1064

Add README.md to beats packages

---

metricbeat/docs/modules/mysql.asciidoc
metricbeat/module/mysql/_meta/docs.asciidoc

Closes https://github.com/elastic/beats/issues/2738

Update metricbeat mysql docs with username/password

---

filebeat/docs/index.asciidoc
filebeat/docs/upgrading.asciidoc
metricbeat/docs/index.asciidoc
metricbeat/docs/upgrading.asciidoc
packetbeat/docs/index.asciidoc
packetbeat/docs/upgrading.asciidoc
winlogbeat/docs/index.asciidoc
winlogbeat/docs/upgrading.asciidoc

Backport: Point to the upgrade docs from the docs for each beat (#2744)

---

CHANGELOG.asciidoc
glide.yaml
vendor/github.com/elastic/gosigar/CHANGELOG.md
vendor/github.com/elastic/gosigar/sigar_windows.go
vendor/github.com/elastic/gosigar/syscall_windows.go

Update vendor with the gosigar library to include the changes from https://github.com/elastic/gosigar/pull/49 and https://github.com/elastic/gosigar/pull/50

update gosigar library

---

libbeat/docs/breaking.asciidoc
libbeat/docs/upgrading.asciidoc

Backport: Edit upgrade and breaking changes doc

---

CHANGELOG.asciidoc
metricbeat/docs/fields.asciidoc
metricbeat/etc/fields.yml
metricbeat/module/system/memory/_meta/fields.yml

Update documentation to include the change from gosigar https://github.com/elastic/gosigar/pull/49
This should be merged after we update Beats with the latest changes from gosigar https://github.com/elastic/beats/pull/2770

Update how actual free memory on Windows is calculated

---

CHANGELOG.asciidoc
glide.yaml
vendor/github.com/elastic/gosigar/CHANGELOG.md
vendor/github.com/elastic/gosigar/sigar_windows.go
vendor/github.com/elastic/gosigar/syscall_windows.go

Backport #2770: update gosigar library (#2770)

---

libbeat/docs/communitybeats.asciidoc

Add openconfigbeat to list of community beats in 5.0.

Add openconfigbeat to the community beats (#2650)

---

libbeat/docs/outputconfig.asciidoc

I've added an example provided by @urso

Add Kafka config example

---

testing/environments/docker/elasticsearch/Dockerfile-snapshot
testing/environments/docker/kibana/Dockerfile-snapshot
testing/environments/docker/logstash/Dockerfile-snapshot

Update testing env with the latest build candidate

---

filebeat/docs/how-filebeat-works.asciidoc
filebeat/docs/reference/configuration/filebeat-options.asciidoc

@ruflin Edits for `shutdown_timeout`. Note that I moved the entry because it was appearing under the Logging config.

Edit `shutdown_timeout` config option

---

libbeat/docs/outputconfig.asciidoc

Backport #2740 and #2810 to 5.0.

Backport #2810

---

README.md

Refreshed the information a bit, and changed wording here and there.
@dedemorton Can you review this one, please? I tried to make it better, hopefully I didn't make it worse :-).

Updated the main README file

---

libbeat/docs/faq-refresh-index.asciidoc

Changed the path to Kibana docs to use a variable and did a light edit while I was there.

Use variable for filepath plus some light edits

---

filebeat/docs/how-filebeat-works.asciidoc
filebeat/docs/reference/configuration/filebeat-options.asciidoc
libbeat/docs/upgrading.asciidoc

Backports doc PRs #2822 and #2766 to the 5.0 branch.

Backport doc changes 10.21.16

---

filebeat/docs/getting-started.asciidoc
filebeat/docs/index.asciidoc
libbeat/docs/config-file-format.asciidoc
libbeat/docs/faq-refresh-index.asciidoc
libbeat/docs/shared-logstash-config.asciidoc
libbeat/docs/yaml.asciidoc
metricbeat/docs/configuring-logstash.asciidoc
metricbeat/docs/index.asciidoc
packetbeat/docs/configuring-logstash.asciidoc
packetbeat/docs/faq.asciidoc
packetbeat/docs/gettingstarted.asciidoc
packetbeat/docs/index.asciidoc
winlogbeat/docs/getting-started.asciidoc
winlogbeat/docs/index.asciidoc

This PR backports changes from the following PRs:
#2826 
#2726 
#2837 
#2838

Backport doc changes into 5.0

---

filebeat/docs/configuring-howto.asciidoc
libbeat/docs/breaking.asciidoc
libbeat/docs/upgrading.asciidoc
packetbeat/docs/configuring-howto.asciidoc

Update overview links

---

filebeat/docs/version.asciidoc
libbeat/docs/version.asciidoc
metricbeat/docs/version.asciidoc
packetbeat/docs/version.asciidoc
winlogbeat/docs/version.asciidoc

Opening this one early for reviews, but please wait with merging until the day of the release.

Update docs version to 5.0.0

---

dev-tools/packer/version.yml
filebeat/filebeat.template-es2x.json
filebeat/filebeat.template.json
libbeat/beat/version.go
metricbeat/metricbeat.template-es2x.json
metricbeat/metricbeat.template.json
packetbeat/packetbeat.template-es2x.json
packetbeat/packetbeat.template.json
winlogbeat/winlogbeat.template-es2x.json
winlogbeat/winlogbeat.template.json

Please don't merge this one until **after the release**.

Bump version to 5.0.1

---

filebeat/docs/configuring-howto.asciidoc
filebeat/docs/index.asciidoc
filebeat/docs/load-balancing.asciidoc
filebeat/docs/reference/configuration/filebeat-options.asciidoc
libbeat/docs/breaking.asciidoc
libbeat/docs/https.asciidoc
libbeat/docs/index.asciidoc
libbeat/docs/upgrading.asciidoc
packetbeat/docs/configuring-howto.asciidoc
packetbeat/docs/index.asciidoc

Cherry-picks the following PRs into 5.0:
#2852 
#2851 
#2850 
#2780

Backport: doc changes 2852, 2851, 2850, adn 2780 into 5.0 

---

CHANGELOG.asciidoc
libbeat/docs/release-notes/5.0.0.asciidoc
libbeat/docs/release.asciidoc

Backport: Combined 5.0.0 release notes (#2813)

---

libbeat/docs/breaking.asciidoc

Forward port of #2841 into master.

Forwardport: Update breaking.asciidoc (#2841)

---

winlogbeat/make.bat

Revert "Fix gotestcover executable in make.bat for winlogbeat"

---

.appveyor.yml
Vagrantfile

Enable AppVeyor builds of Metricbeat

---

metricbeat/Makefile
metricbeat/scripts/config_collector.py
metricbeat/scripts/docs_collector.py

Fix for #2880 .
This fix is suggested by @ruflin 
https://twitter.com/ruflin/status/793348937625309184

beat name in YAML should be set actual name #2880

---

libbeat/docs/shared-command-line.asciidoc

This is a replacement for PR https://github.com/elastic/beats/pull/2917/

Change packetbeat reference to a beatname var

---

metricbeat/docs/modules/apache.asciidoc
metricbeat/docs/modules/haproxy.asciidoc
metricbeat/module/apache/_meta/docs.asciidoc
metricbeat/module/haproxy/_meta/docs.asciidoc
metricbeat/module/haproxy/info/_meta/docs.asciidoc
metricbeat/module/haproxy/stat/_meta/docs.asciidoc

* Fix duplicated info name
* Change ruby to log docs
* Document supported versions
See https://github.com/elastic/beats/issues/2485

HAProxy docs updated

---

libbeat/docs/shared-command-line.asciidoc

Backport of #2934 
The world's smallest cherry-pick. :-)

Backport: Change packetbeat reference to a beatname var

---

filebeat/docs/reference/configuration/filebeat-options.asciidoc

Adds clarification about glob support requested in issue #2108

Explain limitation of glob support

---

filebeat/docs/reference/configuration/filebeat-options.asciidoc

backport: Explain limitation of glob support

---

libbeat/docs/index.asciidoc
packetbeat/docs/packetbeat-geoip.asciidoc

Cherry-picks doc changes from #2965 and #2962

Backport: doc changes in #2965 and 2962

---

filebeat/docs/getting-started.asciidoc
filebeat/docs/load-balancing.asciidoc
filebeat/docs/reference/configuration/filebeat-options.asciidoc
libbeat/docs/gettingstarted.asciidoc

Random doc fixes:
The explanation about regexp replaces the changes proposed in https://github.com/elastic/beats/pull/2233/
The explanation of what we mean by "lock-step" fixes issue #2981 
Feel free to squash commits before merging.

Misc changes

---

testing/environments/docker/elasticsearch/Dockerfile-snapshot
testing/environments/docker/kibana/Dockerfile-snapshot
testing/environments/docker/kibana/bin/kibana-docker
testing/environments/docker/kibana/config/kibana.yml
testing/environments/snapshot.yml

* Switch to official kibana docker files
* Make use of docker-compose v2 args params
x-pack is currently still disabled.

Improve docker-composes handling

---

metricbeat/module/mongodb/status/status.go

Fixed the password option in Mongodb

---

filebeat/docs/version.asciidoc
libbeat/docs/version.asciidoc
metricbeat/docs/version.asciidoc
packetbeat/docs/version.asciidoc
winlogbeat/docs/version.asciidoc

Please don't merge this one until 1-2 hours before the release time.

Version change for docs to 5.0.1

---

CHANGELOG.asciidoc
libbeat/docs/release.asciidoc

Backport https://github.com/elastic/beats/pull/2955

Backport: Closing changelog for 5.0.1 (#2955)

---

dev-tools/packer/version.yml
filebeat/filebeat.template-es2x.json
filebeat/filebeat.template.json
libbeat/beat/version.go
metricbeat/metricbeat.template-es2x.json
metricbeat/metricbeat.template.json
packetbeat/packetbeat.template-es2x.json
packetbeat/packetbeat.template.json
winlogbeat/winlogbeat.template-es2x.json
winlogbeat/winlogbeat.template.json

Should be merged only after 5.0.1 is live.

Version bump to 5.0.2

---

metricbeat/docs/gettingstarted.asciidoc

Backport: Clarify example of how to configure modules

---

Makefile

Fix _meta directory for packaging

---

CHANGELOG.asciidoc

PR #2995 didn't make it in 5.0.1, so we need a changelog item for it.

Add changelog item for #2995

---

CHANGELOG.asciidoc
metricbeat/docs/fields.asciidoc
metricbeat/module/kafka/_meta/fields.yml
metricbeat/module/kafka/partition/partition.go
metricbeat/module/kafka/partition/partition_integration_test.go

* Mark kafka as experimental module as still subject to change

Fix flaky kafka partition test

---

libbeat/docs/outputconfig.asciidoc

Mention the similarity to the "indices" array option and add an example.
I am not that familiar with the configuration of beats so please double-check the example.

Improve "pipelines" documentation

---

metricbeat/docs/fields.asciidoc
metricbeat/metricbeat.template-es2x.json
metricbeat/metricbeat.template.json
metricbeat/module/doc.go
metricbeat/module/docker/cpu/_meta/data.json
metricbeat/module/docker/cpu/_meta/fields.yml
metricbeat/module/docker/cpu/cpu_test.go
metricbeat/module/docker/cpu/data.go
metricbeat/module/docker/cpu/helper.go
metricbeat/tests/system/test_docker.py

Restructure event fields in docker cpu metricset

---

filebeat/docs/overview.asciidoc
filebeat/docs/reference/configuration/filebeat-options.asciidoc
libbeat/docs/communitybeats.asciidoc
libbeat/docs/index.asciidoc
libbeat/docs/newdashboards.asciidoc
libbeat/docs/outputconfig.asciidoc

Cherry-picks doc changes for the following PRs:
#2953 
#3002 
#3010 
#3036 
#3041

Backport: doc changes in #2953, #3002, #3010, #3036, #3041

---

CHANGELOG.asciidoc
vendor/github.com/elastic/go-ucfg/CHANGELOG.md

See https://github.com/elastic/beats/pull/2605

Cleanup CHANGELOG entry for json_decode

---

dev-tools/packer/version.yml
filebeat/filebeat.template-es2x.json
filebeat/filebeat.template.json
libbeat/beat/version.go
metricbeat/metricbeat.template-es2x.json
metricbeat/metricbeat.template.json
packetbeat/packetbeat.template-es2x.json
packetbeat/packetbeat.template.json
winlogbeat/winlogbeat.template-es2x.json
winlogbeat/winlogbeat.template.json

Should be merged only after the 5.0.2 release.

Bump version to be ready for the next release

---

metricbeat/module/kafka/partition/_meta/data.json
metricbeat/module/kafka/partition/partition.go

Make error fields optional in partition event

---

metricbeat/module/kafka/partition/_meta/data.json
metricbeat/module/kafka/partition/partition.go

* Update data.json
(cherry picked from commit 93955f32c435af7bd34f9c7e7e638d7b5546233a)

Backport: Make error fields optional in partition event (#3089)

---

filebeat/docs/version.asciidoc
heartbeat/docs/version.asciidoc
libbeat/docs/version.asciidoc
metricbeat/docs/version.asciidoc
packetbeat/docs/version.asciidoc
winlogbeat/docs/version.asciidoc

Since this is a new branch and it won't be set as current until right before the release date, we can merge this anytime.

Bump versions for 5.1

---

metricbeat/module/docker/docker.go

Currently fetching container stats is very slow as each request takes up to 2 seconds. To improve the fetching time if lots of containers are around, this creates the rrequests in parallel. The main downside is that this opens lots of connections. This fix should only temporary until the bulk api is available: https://github.com/docker/docker/pull/25361
(cherry picked from commit 78f547f235a177e23454c910f77e87a810a4a2ac)

Backport: Fetch container stats in parallel (#3127)

---

libbeat/scripts/generate_index_pattern.py

Backport of #3147 
(cherry picked from commit c51642b9e6303a5d30c212492014d742ca423370)

Backport #3147: Adjust script to generate fields of type geo_point

---

filebeat/docs/filebeat-filtering.asciidoc

somehow managed to revert this in a previous PR. doh.

Fix quotes

---

libbeat/docs/repositories.asciidoc

Cherrypicks #3152 into master.

Remove -prerelease from the repo names

---

CHANGELOG.asciidoc
libbeat/docs/release.asciidoc

Added the 5.1.0 and 5.1.1 sections, removed duplicates.

Cleaned up Changelog in master

---

metricbeat/docs/modules.asciidoc
metricbeat/docs/modules_list.asciidoc
metricbeat/scripts/docs_collector.py

Backport: Auto generate modules list (cherrypicks #3131)

---

CHANGELOG.asciidoc

Cherry pick #3207.
(cherry picked from commit 0f4103ffadaf22bcb03a7c666cd175d806bdf4c2)

Cherry-pick: Add 3140 to changelog (#3207)

---

winlogbeat/docs/reference/configuration/winlogbeat-options.asciidoc

Cherrypicks #2919 into 5.1 branch.
@andrewkroh

Forwardport: Update winlogbeat-options.asciidoc (cherrypicks #2919 into 5.1)

---

.travis.yml

* Explicitly define all targets
* Use environment variable for Golang version
* Update docker-compose version to 1.9.0
* Add os x targets for heartbeat
* Remove docker update as not needed anymore
* Add heartbeat coverage report

Improve travis targets

---

CHANGELOG.asciidoc

there was a typo in the changelog

fix typo in changelog

---

filebeat/docs/reference/configuration/filebeat-options.asciidoc

See https://github.com/elastic/beats/issues/3220#issuecomment-268240447

Clarify when registry file is updated in docs

---

generate/packetbeat/tcp-protocol/README.md
generate/packetbeat/tcp-protocol/cookiecutter.json
generate/packetbeat/tcp-protocol/{{cookiecutter.module}}/pub.go
generate/packetbeat/tcp-protocol/{{cookiecutter.module}}/trans.go
generate/packetbeat/tcp-protocol/{{cookiecutter.module}}/{{cookiecutter.module}}.go

fix cookiecutter and update types in templates

Fix packetbeat tcp plugin generator

---

libbeat/docs/communitybeats.asciidoc

Minor edits to cloudflarebeat entry (cherrypicks #3287 into 5.2)

---

libbeat/scripts/Makefile

Add NOSETESTS_OPTIONS Makefile variable.

libbeat: community beats can configure nosetests

---

CHANGELOG.asciidoc
glide.yaml
vendor/github.com/elastic/go-ucfg/CHANGELOG.md
vendor/github.com/elastic/go-ucfg/merge.go

Update go-ucfg to version 0.4.5

---

generate/metricbeat/metricset/{{cookiecutter.beat}}/Makefile
metricbeat/Makefile
metricbeat/scripts/generate_imports.py

Fix metricbeat generator beat path

---

libbeat/scripts/generate_index_pattern.py
libbeat/scripts/generate_template.py

Added support for types short and byte in templates

---

libbeat/docs/dashboards.asciidoc
libbeat/docs/outputconfig.asciidoc
metricbeat/docs/how-metricbeat-works.asciidoc

Fixing a few minor issues I noticed while updating other stuff....

Fix a couple of typos and a broken link

---

CHANGELOG.asciidoc

There was a new re-spin so #3222 made it in.

Update changelog for 5.1.2

---

filebeat/docs/version.asciidoc
heartbeat/docs/version.asciidoc
libbeat/docs/version.asciidoc
metricbeat/docs/version.asciidoc
packetbeat/docs/version.asciidoc
winlogbeat/docs/version.asciidoc

Let's wait with merging this one for another couple of hours.

Bump docs version for 5.1.2

---

dev-tools/packer/version.yml
filebeat/filebeat.template-es2x.json
filebeat/filebeat.template.json
heartbeat/heartbeat.template-es2x.json
heartbeat/heartbeat.template.json
libbeat/beat/version.go
metricbeat/metricbeat.template-es2x.json
metricbeat/metricbeat.template.json
packetbeat/packetbeat.template-es2x.json
packetbeat/packetbeat.template.json
winlogbeat/winlogbeat.template-es2x.json
winlogbeat/winlogbeat.template.json

5.1.2 is out, so bumping the version.

Bump version to 5.1.3

---

libbeat/dashboards/import_dashboards.go
libbeat/tests/system/test_dashboard.py

I also did a little bit of grammar fixing on the error messages while I was in there.
Fixes #3027

Make import_dashboards always exit 0 on errors

---

heartbeat/docs/getting-started.asciidoc

Should have commented out the include block about importing dashboards because we don't have that ability yet.
Also removed a little leftover content from Filebeat. :-P

Remove content about dashboards

---

libbeat/scripts/generate_template.py

Support type "nested" with empty property list

---

heartbeat/beater/heartbeat.go

(cherry picked from commit 9fd38338bb460b3a5fde01f6041f63802ea143d4)

Add heartbeat 'beta' log message

---

metricbeat/scripts/module/config.yml
metricbeat/scripts/module/metricset/data.json

Update data.json to also have dynamic values.

Adjust default period to 10s in generator

---

heartbeat/monitors/active/http/check.go
heartbeat/monitors/active/http/config.go
heartbeat/monitors/active/http/http.go
heartbeat/monitors/active/http/task.go

- by default set HTTP method to OK
- by default mark connection as failed HTTP code >= 400

Update http monitor check settings

---

heartbeat/_meta/beat.full.yml
heartbeat/_meta/beat.yml
heartbeat/heartbeat.full.yml
heartbeat/heartbeat.yml

- add banner to configuration files
- use a small sample config in heartbeat.yml only.
(cherry picked from commit d18bdda8375ea758c43a3a54e5b880d79ce13dd0)

Update heartbeat sample configuration files

---

filebeat/fileset/modules_integration_test.go
filebeat/fileset/modules_test.go
filebeat/prospector/prospector_log_other_test.go
libbeat/scripts/Makefile

Add -s to gofmt to also simplify code

---

heartbeat/docs/overview.asciidoc
heartbeat/docs/page_header.html
libbeat/docs/communitybeats.asciidoc
libbeat/docs/newbeat.asciidoc
libbeat/docs/outputconfig.asciidoc
libbeat/docs/shared-template-load.asciidoc

Cherrypicks the following doc changes into 5.2: #3292, #3372, #3388, #3426, #3437, #3458

Cherrypick multiple doc changes into 5.2 (#3292, #3372, #3388, #3426, #3437, #3458)

---

libbeat/docs/communitybeats.asciidoc
libbeat/docs/outputconfig.asciidoc
libbeat/docs/shared-template-load.asciidoc

Cherrypicks the following doc changes into 5.1:  #3372, #3388, #3426, #3437

Cherrypick multiple doc changes into 5.1 ( #3372, #3388, #3426, #3437)

---

filebeat/docs/index.asciidoc
libbeat/docs/index.asciidoc
metricbeat/docs/index.asciidoc
packetbeat/docs/index.asciidoc
winlogbeat/docs/index.asciidoc

Fixes links that incorrectly pointed to the 5.0 version of the docs.

Fix link URLs

---

CHANGELOG.asciidoc
metricbeat/module/ceph/health/data.go
metricbeat/module/ceph/health/health.go
metricbeat/module/ceph/health/health_test.go
metricbeat/tests/system/test_ceph.py

* Add system tests to check for doc fields
* Fix docs / fields which do not correspond
* Use shared client

Ceph cleanup module

---

libbeat/docs/index.asciidoc
libbeat/docs/installing-beats.asciidoc
libbeat/docs/newdashboards.asciidoc

Cherrypicks changes from #3487 and #3483 into 5.2 docs.

Cherrypick doc changes (#3487 and #3483) into 5.2

---

libbeat/logp/metrics.go
libbeat/monitoring/adapter/go-metrics-wrapper.go
libbeat/monitoring/adapter/go-metrics_test.go
libbeat/monitoring/metrics.go
libbeat/monitoring/monitoring.go
libbeat/monitoring/registry.go
libbeat/monitoring/registry_test.go
libbeat/monitoring/snapshot.go
libbeat/monitoring/visitor.go
libbeat/monitoring/visitor_expvar.go
libbeat/monitoring/visitor_kv.go
libbeat/service/service.go

- Pass Mode to monitoring.Var to filter within structured variables
- do not return errors in Visitor interface
- add helper functions ReportX

Monitoring variable snapshoting improvements

---

filebeat/config/config.go
filebeat/docs/reference/configuration/reload-configuration.asciidoc
filebeat/tests/system/config/filebeat.yml.j2
libbeat/cfgfile/reload.go
metricbeat/_meta/common.full.yml
metricbeat/beater/config.go
metricbeat/docs/reference/configuration/reload-configuration.asciidoc
metricbeat/metricbeat.full.yml
metricbeat/tests/system/config/metricbeat.yml.j2

* Update docs
* Update config file
See https://github.com/elastic/beats/issues/3430

Rename reload config options according to #3430

---

CHANGELOG.asciidoc

See https://github.com/elastic/beats/issues/3546

Add known issue for filebeat

---

heartbeat/_meta/kibana/dashboard/f3e771c0-eb19-11e6-be20-559646f8b9ba.json
heartbeat/_meta/kibana/search/c49bd160-eb17-11e6-be20-559646f8b9ba.json
heartbeat/_meta/kibana/visualization/091c3a90-eb1e-11e6-be20-559646f8b9ba.json
heartbeat/_meta/kibana/visualization/0f4c0560-eb20-11e6-9f11-159ff202874a.json
heartbeat/_meta/kibana/visualization/1738dbc0-eb1d-11e6-be20-559646f8b9ba.json
heartbeat/_meta/kibana/visualization/920e8140-eb1a-11e6-be20-559646f8b9ba.json
heartbeat/_meta/kibana/visualization/c65ef340-eb19-11e6-be20-559646f8b9ba.json

I'm opening this early, but we shouldn't merge it until we figure out if this can/should work with older versions of Kibana.

Heartbeat HTTP sample dashboards

---

metricbeat/docs/fields.asciidoc
metricbeat/metricbeat.template-es2x.json
metricbeat/metricbeat.template.json
metricbeat/module/docker/container/_meta/fields.yml
metricbeat/module/docker/image/_meta/data.json
metricbeat/module/docker/image/_meta/fields.yml

* Add docs for labels and tags

Update docker image with data.json

---

filebeat/docs/command-line.asciidoc

Closes https://github.com/elastic/beats/issues/3104

Add docs for -once command line option

---

packetbeat/_meta/kibana/search/NFS-errors-search.json
packetbeat/_meta/kibana/visualization/NFS-errors.json
winlogbeat/_meta/kibana/visualization/Event-Levels.json
winlogbeat/_meta/kibana/visualization/Sources.json

Backport: Remove exclude pattern from visualizations (#3548)

---

metricbeat/docs/fields.asciidoc
metricbeat/docs/modules/couchbase.asciidoc
metricbeat/docs/modules/prometheus.asciidoc
metricbeat/docs/modules_list.asciidoc
metricbeat/metricbeat.full.yml
metricbeat/module/couchbase/_meta/docs.asciidoc
metricbeat/module/couchbase/_meta/fields.yml
metricbeat/module/couchbase/bucket/_meta/docs.asciidoc
metricbeat/module/couchbase/bucket/_meta/fields.yml
metricbeat/module/couchbase/cluster/_meta/docs.asciidoc
metricbeat/module/couchbase/cluster/_meta/fields.yml
metricbeat/module/couchbase/node/_meta/docs.asciidoc
metricbeat/module/couchbase/node/_meta/fields.yml
metricbeat/module/prometheus/_meta/docs.asciidoc
metricbeat/module/prometheus/_meta/fields.yml
metricbeat/module/prometheus/collector/_meta/docs.asciidoc
metricbeat/module/prometheus/stats/_meta/docs.asciidoc
metricbeat/module/prometheus/stats/_meta/fields.yml

Cherrypicks edits for Prometheus (#3520) and Couchbase module (#3541) into 5.x branch.

Cherrypick doc changes into 5.x (cherrypicks #3520 and #3541)

---

metricbeat/docs/fields.asciidoc
metricbeat/docs/modules/couchbase.asciidoc
metricbeat/docs/modules/prometheus.asciidoc
metricbeat/docs/modules_list.asciidoc
metricbeat/metricbeat.full.yml
metricbeat/module/couchbase/_meta/docs.asciidoc
metricbeat/module/couchbase/_meta/fields.yml
metricbeat/module/couchbase/bucket/_meta/docs.asciidoc
metricbeat/module/couchbase/bucket/_meta/fields.yml
metricbeat/module/couchbase/cluster/_meta/docs.asciidoc
metricbeat/module/couchbase/cluster/_meta/fields.yml
metricbeat/module/couchbase/node/_meta/docs.asciidoc
metricbeat/module/couchbase/node/_meta/fields.yml
metricbeat/module/prometheus/_meta/docs.asciidoc
metricbeat/module/prometheus/_meta/fields.yml
metricbeat/module/prometheus/collector/_meta/docs.asciidoc
metricbeat/module/prometheus/stats/_meta/docs.asciidoc
metricbeat/module/prometheus/stats/_meta/fields.yml

Cherrypicks edits for Prometheus (#3520) and Couchbase module (#3541) into 5.3 branch.

Cherrypick doc changes into 5.3 (cherrypicks #3520 and #3541) 

---

filebeat/config/config.go

Filebeat: Add err check for config file read

---

libbeat/monitoring/metrics.go
libbeat/monitoring/visitor.go

- introduce ReportNamespace and ReportVar
- add FuncVar and NewFunc to register functions with libbeat/monitoring

Add monitoring utilities

---

dev-tools/packer/version.yml
filebeat/filebeat.template-es2x.json
filebeat/filebeat.template.json
heartbeat/heartbeat.template-es2x.json
heartbeat/heartbeat.template.json
libbeat/beat/version.go
metricbeat/metricbeat.template-es2x.json
metricbeat/metricbeat.template.json
packetbeat/packetbeat.template-es2x.json
packetbeat/packetbeat.template.json
winlogbeat/winlogbeat.template-es2x.json
winlogbeat/winlogbeat.template.json

Opening a bit early, should be merged **after** the release.

Version bump to 5.2.2

---

libbeat/docs/communitybeats.asciidoc

Mcqbeat can monitor status of queues in memcacheq.

I made a new beat

---

Makefile
NOTICE
dev-tools/generate_notice.py

This way it's checked automatically by the CI and we keep the NOTICE
file always up to date.

Add `make notice` to `make check`

---

filebeat/scripts/module/fileset/config/config.yml
filebeat/scripts/module/fileset/manifest.yml

There were some changes in the structure of some files, and this is
needed to update the generator as well.
Part of #3159.

Filebeat modules: Fix generator files

---

dev-tools/cherrypick_pr

If you add the `--create_pr` parameter, and have a GH token in
`~/.github_token`, the script will also create a PR for you, with the right
title and tags already set.

Optionally use the GH API to open PRs from the cherrypick_pr script

---

filebeat/scripts/module/fileset/config/config.yml
filebeat/scripts/module/fileset/manifest.yml

Cherry-pick of PR #3621 to 5.3 branch. Original message: 
There were some changes in the structure of some files, and this is
needed to update the generator as well.
Part of #3159.

Cherry-pick to 5.3: Filebeat modules: Fix generator files

---

dev-tools/cherrypick_pr

Fix the cherrypick_pr script

---

filebeat/docs/getting-started.asciidoc
filebeat/docs/index.asciidoc
heartbeat/docs/getting-started.asciidoc
heartbeat/docs/index.asciidoc
libbeat/docs/gettingstarted.asciidoc
libbeat/docs/index.asciidoc
libbeat/docs/repositories.asciidoc
metricbeat/docs/gettingstarted.asciidoc
metricbeat/docs/index.asciidoc
packetbeat/docs/gettingstarted.asciidoc
packetbeat/docs/index.asciidoc
winlogbeat/docs/getting-started.asciidoc

Cherrypicks #3600 and #3601 into 5.2 branch.

Cherrypick doc changes into 5.2 (#3600, #3601)

---

filebeat/docs/getting-started.asciidoc
heartbeat/docs/getting-started.asciidoc
heartbeat/docs/index.asciidoc
libbeat/docs/gettingstarted.asciidoc
libbeat/docs/index.asciidoc
libbeat/docs/repositories.asciidoc
metricbeat/docs/gettingstarted.asciidoc
metricbeat/docs/index.asciidoc
packetbeat/docs/gettingstarted.asciidoc
packetbeat/docs/index.asciidoc
winlogbeat/docs/getting-started.asciidoc

Cherrypicks #3600 and #3601 into 5.3 branch.

Cherrypick doc changes into 5.3 (#3600, #3601)

---

metricbeat/docs/developer-guide/metricset-details.asciidoc

update doc about how to run single integration test

---

filebeat/docs/modules-dev-guide.asciidoc

Hot fix for the docs build. The error was introduced by #3616.

Fix docs build broken by the dev guide

---

filebeat/filebeat.full.yml
heartbeat/heartbeat.full.yml
libbeat/_meta/config.full.yml
metricbeat/metricbeat.full.yml
packetbeat/packetbeat.full.yml
winlogbeat/winlogbeat.full.yml

Cherry-pick of PR #3665 to 5.3 branch. Original message: 
Some of the dashboards config option were singular and did not work because of this.

Cherry-pick to 5.3: Fix dashboards config naming

---

filebeat/docs/modules-dev-guide.asciidoc
filebeat/docs/modules-overview.asciidoc
filebeat/docs/modules_list.asciidoc
filebeat/docs/reference/configuration/filebeat-options.asciidoc
filebeat/scripts/docs_collector.py
filebeat/scripts/module/fileset/manifest.yml
metricbeat/docs/developer-guide/metricset-details.asciidoc

Cherry-pick of PR #3616 to 5.3 branch. Original message: 
Basic guide for creating a new module.
Part of #3159.

Cherry-pick to 5.3: Filebeat modules dev guide

---

libbeat/beat/beat.go
libbeat/service/service.go

Fix early logging race

---

dev-tools/cmd/import_dashboards/import_dashboards.go
dev-tools/cmd/index_template/index_template.go
dev-tools/set_version
libbeat/beat/beat.go
libbeat/outputs/elasticsearch/client_integration_test.go
libbeat/version/helper.go
libbeat/version/version.go

This PR is to reduce the number of changes in https://github.com/elastic/beats/pull/3681 .

Extract version to separate package to prevent cyclic imports

---

metricbeat/module/mysql/_meta/kibana/dashboard/66881e90-0006-11e7-bf7f-c9acc3d3e306.json
metricbeat/module/mysql/_meta/kibana/search/67e88e60-0005-11e7-aaf1-b342e4b94bb0.json
metricbeat/module/mysql/_meta/kibana/visualization/0f506420-0006-11e7-bf7f-c9acc3d3e306.json
metricbeat/module/mysql/_meta/kibana/visualization/1a99f2b0-0006-11e7-bf7f-c9acc3d3e306.json
metricbeat/module/mysql/_meta/kibana/visualization/1eda2280-0008-11e7-82f3-2f380154876c.json
metricbeat/module/mysql/_meta/kibana/visualization/1ede99e0-0009-11e7-8cd4-73b67e9e3f3c.json
metricbeat/module/mysql/_meta/kibana/visualization/45a00c10-0006-11e7-bf7f-c9acc3d3e306.json
metricbeat/module/mysql/_meta/kibana/visualization/4c36c420-000a-11e7-8cd4-73b67e9e3f3c.json
metricbeat/module/mysql/_meta/kibana/visualization/a2175300-000a-11e7-b001-85aac4878445.json
metricbeat/module/mysql/_meta/kibana/visualization/e784dc50-0005-11e7-bf7f-c9acc3d3e306.json

Makes use of Timelion for some derivatives.

Added a dashboard for the Metricbeat MySQL module

---

dev-tools/get_version

Command was broken when version file was moved to its own package.

Fix get_version command

---

filebeat/docs/getting-started.asciidoc
filebeat/docs/modules-dev-guide.asciidoc

Cherrypick doc changes (PR #3672 and #3673)

---

CHANGELOG.asciidoc
libbeat/docs/release.asciidoc

Closing changelog for 5.3.0

---

metricbeat/mb/module/wrapper.go

- replace metricset expvar stats with libbeat.monitoring
- add support to delete stats for unloaded modules/metricsets (with reference counting)

Metricbeat module stats based on libbeat/monitoring

---

libbeat/docs/config-file-format.asciidoc
libbeat/docs/shared-faq.asciidoc

Add info about config file ownership and permissions

---

filebeat/tests/system/test_registrar.py

Prompted by two failures that seem unrelated to my changes:
https://travis-ci.org/elastic/beats/jobs/211879514
https://travis-ci.org/elastic/beats/jobs/211881826

filebeat: add some debugs in test_registrar

---

libbeat/docs/communitybeats.asciidoc
libbeat/docs/config-file-format.asciidoc
libbeat/docs/newbeat.asciidoc
libbeat/docs/shared-command-line.asciidoc
libbeat/docs/shared-faq.asciidoc

Cherrypicks doc changes for the following PRs: #3725 , #3753 , and #3736

Cherrypick doc changes into 5.3 (PR #3725, #3753, and #3736)

---

libbeat/docs/communitybeats.asciidoc
libbeat/docs/newbeat.asciidoc
libbeat/docs/shared-command-line.asciidoc

Cherrypicks the following PRs: #3725  and #3736

Cherrypick doc change into 5.2 (#3725 and #3736)

---

metricbeat/docs/modules/redis.asciidoc
metricbeat/module/redis/_meta/docs.asciidoc

Cherry-pick of PR #3756 to 5.x branch. Original message:

Cherry-pick to 5.x: metricbeat: add password for redis module in doc

---

libbeat/monitoring/report/elasticsearch/elasticsearch.go

- initial xpack endpoint availability: every 30 seconds
- publish error backoff 1 - 60 seconds (exponential backoff)
- no retry -> drop on publish error to not overload endpoint with old and
new metrics from many beats

Update monitoring client retry parameters

---

libbeat/docs/communitybeats.asciidoc

Icingabeat collects data from the Icinga 2 API

Add icingabeat to the list

---

libbeat/docs/communitybeats.asciidoc

Details of beats at : https://github.com/deepujain/nvidiagpubeat/

nvidiagpubeat: Monitor NVIDIA GPUs.

---

filebeat/docs/faq.asciidoc
filebeat/docs/getting-started.asciidoc
heartbeat/docs/getting-started.asciidoc
libbeat/docs/config-file-format.asciidoc
libbeat/docs/gettingstarted.asciidoc
libbeat/docs/repositories.asciidoc
libbeat/docs/version.asciidoc
metricbeat/docs/gettingstarted.asciidoc
packetbeat/docs/gettingstarted.asciidoc

This PR closes issue #3783 and #3649. Also fixes a heading level that incorrect.
@tsg Note that after we merge this PR, we'll probably want to add something to the release checklist to verify that `:release-state: released` is set in version.asciidoc. I added the `release-state` variable to version.asciidoc so that we can change the state in one place. It's less visible there, tho, so we'll just need to make a note to check it when we're publishing the docs for a release.

Misc doc changes

---

libbeat/docs/communitybeats.asciidoc

Moves nvidiagpubeat (added in https://github.com/elastic/beats/pull/3794) to the correct position in the list.

Sort list of community beats

---

metricbeat/module/haproxy/info/_meta/data.json
metricbeat/module/haproxy/info/info_integration_test.go
metricbeat/module/haproxy/stat/_meta/data.json
metricbeat/module/haproxy/stat/stat_ingetration_test.go
metricbeat/module/haproxy/testing.go

Update `data.json` files with correct info.

Use environment variables in haproxy testing

---

codecov.yml

This will report on each commit the patch change in coverage. Project report is disabled.

Add codecov config for commit status

---

libbeat/docs/repositories.asciidoc

Backport to 5.2: Add workaround for Heartbeat install issue

---

CHANGELOG.asciidoc
filebeat/module/system/syslog/ingest/pipeline.json
filebeat/module/system/syslog/test/darwin-syslog-sample.log
filebeat/module/system/syslog/test/darwin-syslog-sample.log-expected.json

Filebeat syslog module: support for lines without a program name

---

CHANGELOG.asciidoc
libbeat/tests/system/test_http.py

Add tests for http endpoint

---

filebeat/docs/index.asciidoc
heartbeat/docs/index.asciidoc
libbeat/docs/config-file-format.asciidoc
libbeat/docs/shared-faq.asciidoc
libbeat/docs/yaml.asciidoc
metricbeat/docs/index.asciidoc
packetbeat/docs/index.asciidoc
winlogbeat/docs/index.asciidoc

Backport to 5.3: Update yaml tips

---

CHANGELOG.asciidoc
metricbeat/module/prometheus/collector/collector_test.go
metricbeat/module/prometheus/collector/data.go
metricbeat/module/prometheus/stats/stats.go

Cherry-pick of PR #3947 to 5.x branch. Original message: 
Fixes https://github.com/elastic/beats/issues/3946

Cherry-pick #3947 to 5.x: Fixing panic on prometheus collector when label has ,

---

CHANGELOG.asciidoc
metricbeat/module/kubelet/container/container.go
metricbeat/module/kubelet/container/data.go
metricbeat/module/kubelet/doc.go
metricbeat/module/kubelet/node/data.go
metricbeat/module/kubelet/node/node.go
metricbeat/module/kubelet/pod/data.go
metricbeat/module/kubelet/pod/pod.go
metricbeat/module/kubelet/system/data.go
metricbeat/module/kubelet/system/system.go
metricbeat/module/kubelet/volume/data.go
metricbeat/module/kubelet/volume/volume.go

I also did some small style fixes and added the changelog entry for the module

Mark `kubelet` module as beta

---

generator/beat/{beat}/LICENSE
generator/metricbeat/{beat}/LICENSE

Bump LICENSE year in beat templates

---

libbeat/docs/newbeat.asciidoc

Fixes broken doc build in 1.0.1

fix doc build

---

libbeat/docs/version.asciidoc

Please don't merge this one until a few hours before the release.

Bump docs version to 5.3.1

---

metricbeat/docs/fields.asciidoc
metricbeat/docs/modules/kubelet.asciidoc
metricbeat/module/kubelet/_meta/docs.asciidoc
metricbeat/module/kubelet/_meta/fields.yml
metricbeat/module/kubelet/_meta/test/stats_summary.json
metricbeat/module/kubelet/container/_meta/fields.yml
metricbeat/module/kubelet/container/container_test.go
metricbeat/module/kubelet/node/_meta/fields.yml
metricbeat/module/kubelet/node/node_test.go
metricbeat/module/kubelet/pod/_meta/fields.yml
metricbeat/module/kubelet/pod/data.go
metricbeat/module/kubelet/pod/pod.go
metricbeat/module/kubelet/pod/pod_test.go
metricbeat/module/kubelet/system/_meta/fields.yml
metricbeat/module/kubelet/system/data.go
metricbeat/module/kubelet/system/system.go
metricbeat/module/kubelet/system/system_test.go
metricbeat/module/kubelet/volume/_meta/fields.yml
metricbeat/module/kubelet/volume/data.go
metricbeat/module/kubelet/volume/volume.go
metricbeat/module/kubelet/volume/volume_test.go

Add all missing fields for `kubelet` module.
Related to #3965

Add kubelet module fields

---

metricbeat/module/elasticsearch/node/_meta/docs.asciidoc
metricbeat/module/elasticsearch/node_stats/_meta/docs.asciidoc

Update docs to include more details about the supported metricsets of the Elasticsearch module.
(cc: @dedemorton @ruflin )

Update docs to include more details about the Elasticsearch metricsets

---

filebeat/docs/getting-started.asciidoc
heartbeat/docs/getting-started.asciidoc
metricbeat/docs/gettingstarted.asciidoc
packetbeat/docs/gettingstarted.asciidoc
winlogbeat/docs/getting-started.asciidoc

The doc build still isn't picking up the correct version info, so I'm doing this to force the books to rebuild.

Force doc rebuild

---

libbeat/common/mapstr.go
libbeat/common/mapstr_test.go

Add DeepUpdate to MapStr for recursive-deep updating an event.

Add (*MapStr).DeepUpdate

---

libbeat/template/template.go

This was accidentially removed in https://github.com/elastic/beats/pull/4055

Set 10000 field limit also for ES v5

---

filebeat/docs/multiline.asciidoc
filebeat/docs/reference/configuration/filebeat-options.asciidoc

Cherrypicks issue #4086 
Feel free to merge directly upon reviewing.

Backport: Warn Beats users not to do multiline handling in Logstash (#4086 into 5.3)

---

libbeat/cfgfile/glob_watcher_test.go

Looks like a copy-paste mistake? @ruflin

Remove duplicate code in glob_watcher_test.go

---

metricbeat/docs/modules/docker.asciidoc
metricbeat/docs/modules/system.asciidoc
metricbeat/docs/reference/configuration/metricbeat-options.asciidoc
metricbeat/module/docker/_meta/docs.asciidoc
metricbeat/module/system/_meta/docs.asciidoc

Removed as requested in #4143 
@tsg Let me know if this statement needs to go somewhere else.

Remove docker statement

---

filebeat/docs/modules-overview.asciidoc
libbeat/docs/communitybeats.asciidoc

Cherrypicks #4108 and #4148 into 5.3
Please feel free to merge upon review.

Backport: #4108 and #4148 into 5.3

---

metricbeat/module/jolokia/jmx/_meta/docs.asciidoc

Fix the configuration file from the Jolokia docs.
cc-ed @dedemorton

Fix Jolokia docs

---

metricbeat/module/system/fsstat/_meta/docs.asciidoc

Forward port: Cherrypick #4095 into master

---

filebeat/docs/getting-started.asciidoc
heartbeat/docs/getting-started.asciidoc
libbeat/docs/dashboards.asciidoc
metricbeat/docs/gettingstarted.asciidoc
packetbeat/docs/gettingstarted.asciidoc
winlogbeat/docs/getting-started.asciidoc

Because sometimes the things that seem obvious to us are not so obvious to users....

Clarify doc for Windows commands to indicate that Powershell is required

---

metricbeat/docs/modules/docker.asciidoc
metricbeat/docs/modules/system.asciidoc
metricbeat/docs/reference/configuration/metricbeat-options.asciidoc
metricbeat/module/docker/_meta/docs.asciidoc
metricbeat/module/system/_meta/docs.asciidoc

Backport: #4147 to 5.3

---

dev-tools/packer/version.yml
filebeat/filebeat.template-es2x.json
filebeat/filebeat.template-es6x.json
filebeat/filebeat.template.json
heartbeat/heartbeat.template-es2x.json
heartbeat/heartbeat.template-es6x.json
heartbeat/heartbeat.template.json
libbeat/beat/version.go
libbeat/libbeat.template-es6x.json
metricbeat/metricbeat.template-es2x.json
metricbeat/metricbeat.template-es6x.json
metricbeat/metricbeat.template.json
packetbeat/packetbeat.template-es2x.json
packetbeat/packetbeat.template-es6x.json
packetbeat/packetbeat.template.json
winlogbeat/winlogbeat.template-es2x.json
winlogbeat/winlogbeat.template-es6x.json
winlogbeat/winlogbeat.template.json

Version bump in preparation for 5.4.1.

Bump version to 5.4.1

---

filebeat/harvester/log.go

On shutdown it could happen, that the offset reported in the registry is +1 event compared to the offset which was actually sent to the output. The reason is that the internal harvester state was modified before successful sending of event, which could lead on the shutdown of the harvester to a wrong offset reporting.

Fix problem on shutdown with offset + 1 event

---

CHANGELOG.asciidoc
metricbeat/module/system/diskio/_meta/docs.asciidoc
metricbeat/module/system/diskio/diskio.go
metricbeat/module/system/diskio/diskio_test.go
metricbeat/module/system/diskio/doc.go
vendor/github.com/shirou/gopsutil/disk/disk_darwin.go
vendor/github.com/shirou/gopsutil/disk/disk_darwin.h
vendor/github.com/shirou/gopsutil/disk/disk_darwin_cgo.go
vendor/github.com/shirou/gopsutil/disk/disk_darwin_nocgo.go
vendor/github.com/shirou/gopsutil/disk/disk_fallback.go
vendor/github.com/shirou/gopsutil/disk/disk_freebsd.go
vendor/github.com/shirou/gopsutil/disk/disk_linux.go
vendor/github.com/shirou/gopsutil/disk/disk_openbsd.go
vendor/github.com/shirou/gopsutil/disk/disk_windows.go
vendor/github.com/shirou/gopsutil/net/net_linux.go
vendor/vendor.json

Implement diskio metricset on macOS

---

metricbeat/module/system/_meta/kibana/visualization/217025e0-2a69-11e7-99f0-399f2a11b723.json

Remove the filter from the visualization. This fixes https://github.com/elastic/beats/issues/4226

Remove filter from visualization

---

filebeat/docs/how-filebeat-works.asciidoc
filebeat/docs/overview.asciidoc
libbeat/docs/config-file-format.asciidoc

Cherry-picks the following PRs into master:
https://github.com/elastic/beats/pull/4194
https://github.com/elastic/beats/pull/4195
https://github.com/elastic/beats/pull/4196
https://github.com/elastic/beats/pull/4199

Forward port: #4194, #4195, #4196, and #4199 into master

---

dev-tools/cherrypick_pr

This makes it possible to use the new features without having to copy it to a separate location.

Backport cherrypick script changes to 5.x branches

---

dev-tools/export_dashboards.py
libbeat/docs/version.asciidoc

This is in preparation for the 6.0.0-alpha1 release.

Set release-status to `prerelease`

---

CHANGELOG.asciidoc

Update CHANGELOG with the missing tasks

Update CHANGELOG with missing tasks

---

CHANGELOG.asciidoc
filebeat/module/mysql/slowlog/ingest/pipeline.json

Cherry-pick of PR #4183 to 5.4 branch. Original message: 
The IP grok expression was bogus.

Cherry-pick #4183 to 5.4: Fix mysql slowlog parser

---

metricbeat/module/windows/perfmon/_meta/data.json
metricbeat/module/windows/perfmon/pdh_integration_windows_test.go

Add test to create `data.json`file. See #3828 for more info.

Perfmon metricset add real data example

---

docs/devguide/newbeat.asciidoc

Reported here: https://discuss.elastic.co/t/docs-creating-a-new-beat/85561

Fix developer guide _meta/beat.yml instead of etc/beat.yml

---

metricbeat/module/jolokia/jmx/_meta/docs.asciidoc

Quick fixes for #4319 
This content still requires a technical edit for feature GA.

Fix misc doc nits

---

libbeat/docs/communitybeats.asciidoc

Forward-ported from changes in 5.4 branch.

Fix typos in community beats

---

.appveyor.yml
.gitignore
.travis.yml
Makefile
dev-tools/aggregate_coverage.py
dev-tools/generate_notice.py
filebeat/scripts/docs_collector.py
filebeat/tests/system/config/filebeat.yml.j2
filebeat/tests/system/test_json.py
libbeat/tests/system/beat/beat.py
libbeat/tests/system/requirements.txt
metricbeat/scripts/docs_collector.py
metricbeat/scripts/fields_collector.py
metricbeat/tests/system/config/metricbeat.yml.j2
metricbeat/tests/system/test_system.py
packetbeat/tests/system/config/packetbeat.yml.j2
packetbeat/tests/system/test_0002_thrift_basics.py
packetbeat/tests/system/test_0006_wsgi.py
packetbeat/tests/system/test_0013_redis_basic.py
packetbeat/tests/system/test_0019_hide_params.py
packetbeat/tests/system/test_0040_memcache_tcp_bin_basic.py
packetbeat/tests/system/test_0040_memcache_tcp_text_basic.py
packetbeat/tests/system/test_0041_memcache_udp_bin_basic.py
packetbeat/tests/system/test_0041_memcache_udp_text_basic.py
packetbeat/tests/system/test_0060_flows.py
script/config_collector.py

Fixes elastic/beats#3166
Test environment:
Arch Linux
Python `3.6.1` installed via `pyenv`
```
$ docker --version
Docker version 17.05.0-ce, build 89658bed64
```
Tested by running `make check && make`

Python 3 support

---

filebeat/harvester/reader/multiline.go
filebeat/harvester/reader/multiline_config.go
filebeat/harvester/reader/multiline_test.go
filebeat/tests/system/test_multiline.py

Fix panic on empty multiline pattern

---

NOTICE
dev-tools/generate_notice.py

* Adds auto-detection for the common license types
* Adds option to create a CSV file summary. This is convenient for creating
spreadsheets and the like

Add a CSV summary for the dependencies

---

metricbeat/docs/modules/kubernetes.asciidoc
metricbeat/metricbeat.full.yml
metricbeat/module/kubernetes/_meta/config.yml

Disable kubernetes event metricset by default

---

filebeat/_meta/common.full.p2.yml
filebeat/_meta/common.p2.yml
filebeat/filebeat.full.yml
filebeat/filebeat.yml

Fix typo in the configuration files

---

filebeat/harvester/reader/multiline.go
filebeat/harvester/reader/multiline_config.go
filebeat/harvester/reader/multiline_test.go
filebeat/tests/system/test_multiline.py

Cherry-pick of PR #4377 to 5.x branch. Original message: 
Closes #4165 and #3023 .

Cherry-pick #4377 to 5.x: Fix panic on empty multiline pattern

---

filebeat/docs/modules-getting-started.asciidoc
filebeat/docs/modules-overview.asciidoc
filebeat/docs/modules.asciidoc
filebeat/docs/multiline.asciidoc
filebeat/docs/reference/configuration/filebeat-options.asciidoc
libbeat/docs/outputconfig.asciidoc
libbeat/docs/regexp.asciidoc
libbeat/docs/shared-ssl-logstash-config.asciidoc
packetbeat/docs/flows.asciidoc

Just a handful of minor doc changes that have been discussed during chats in slack. Wanted to get them into the doc because most of them aren't tracked anywhere.

Misc doc fixes

---

filebeat/docs/modules-getting-started.asciidoc
filebeat/docs/modules-overview.asciidoc
filebeat/docs/modules.asciidoc
filebeat/docs/multiline.asciidoc
filebeat/docs/reference/configuration/filebeat-options.asciidoc
libbeat/docs/newbeat.asciidoc
libbeat/docs/outputconfig.asciidoc
libbeat/docs/regexp.asciidoc
libbeat/docs/shared-ssl-logstash-config.asciidoc
packetbeat/docs/flows.asciidoc

Backports #4451 and #4300 to 5.4.

Backport: Doc changes for #4451 and #4300 into 5.4

---

filebeat/docs/modules-getting-started.asciidoc
filebeat/docs/modules-overview.asciidoc
filebeat/docs/modules.asciidoc
filebeat/docs/multiline.asciidoc
filebeat/docs/reference/configuration/filebeat-options.asciidoc
libbeat/docs/newbeat.asciidoc
libbeat/docs/outputconfig.asciidoc
libbeat/docs/regexp.asciidoc
libbeat/docs/shared-ssl-logstash-config.asciidoc
packetbeat/docs/flows.asciidoc

Backports #4451 and #4300 to 5.5.

Backport: Doc changes for #4451 and #4300 into 5.5

---

filebeat/docs/index.asciidoc
heartbeat/docs/index.asciidoc
libbeat/docs/config-file-format.asciidoc
libbeat/docs/shared-env-vars.asciidoc
libbeat/docs/yaml.asciidoc
metricbeat/docs/index.asciidoc
packetbeat/docs/index.asciidoc
packetbeat/docs/reference/configuration/packetbeat-options.asciidoc
winlogbeat/docs/index.asciidoc

Cherry-pick #4200 and #4505 into 5.4

Backport to 5.4: #4200 and #4505

---

CHANGELOG.asciidoc
metricbeat/module/docker/diskio/helper.go

was just reads because of wrong function call.

fix docker.diskio.total

---

libbeat/docs/version.asciidoc

Let's merge this a bit later, around 2-3 PM.

Bump docs version to 5.4.2

---

testing/environments/5x.yml
testing/environments/docker/kibana/Dockerfile-4.6
testing/environments/docker/kibana/Dockerfile-snapshot
testing/environments/latest.yml

timeout was being reached in some travis tests, this should avoid that

Increment kibana healthcheck retries

---

CHANGELOG.asciidoc
libbeat/docs/release.asciidoc

Looks like we're going to have our first empty release.

Close changelog for 5.4.3

---

filebeat/_meta/common.reference.p2.yml
filebeat/filebeat.reference.yml
filebeat/prospector/udp/prospector.go

We can still make it beta before the release if we see it works well.

Add experimental flag to udp prospector type

---

NOTICE
vendor/github.com/ericchiang/k8s/README.md
vendor/github.com/ericchiang/k8s/client.go
vendor/github.com/ericchiang/k8s/labels.go
vendor/golang.org/x/tools/LICENSE
vendor/golang.org/x/tools/PATENTS
vendor/golang.org/x/tools/go/ast/astutil/enclosing.go
vendor/golang.org/x/tools/go/ast/astutil/imports.go
vendor/golang.org/x/tools/go/ast/astutil/util.go
vendor/golang.org/x/tools/go/buildutil/allpackages.go
vendor/golang.org/x/tools/go/buildutil/fakecontext.go
vendor/golang.org/x/tools/go/buildutil/overlay.go
vendor/golang.org/x/tools/go/buildutil/tags.go
vendor/golang.org/x/tools/go/buildutil/util.go
vendor/golang.org/x/tools/go/loader/cgo.go
vendor/golang.org/x/tools/go/loader/cgo_pkgconfig.go
vendor/golang.org/x/tools/go/loader/doc.go
vendor/golang.org/x/tools/go/loader/loader.go
vendor/golang.org/x/tools/go/loader/util.go
vendor/vendor.json

We no longer require our own fork, changes accepted by upstream
cc // @ruflin

Update to latest k8s version

---

auditbeat/docs/fields.asciidoc
auditbeat/module/audit/kernel/_meta/fields.yml
auditbeat/module/audit/kernel/audit_linux.go

Adds a missing field to the fields.yml. And also improves a debug message.

Add "action" to auditbeat fields.yml

---

Heartbeat/_meta/kibana/default/dashboard/Heartbeat-http-monitor.json
Packetbeat/_meta/kibana/default/dashboard/Packetbeat-cassandra.json
Packetbeat/_meta/kibana/default/dashboard/Packetbeat-dns-tunneling.json
Packetbeat/_meta/kibana/default/dashboard/Packetbeat-dns.json
Packetbeat/_meta/kibana/default/dashboard/Packetbeat-flows.json
Packetbeat/_meta/kibana/default/dashboard/Packetbeat-http.json
Packetbeat/_meta/kibana/default/dashboard/Packetbeat-mongodb.json
Packetbeat/_meta/kibana/default/dashboard/Packetbeat-mysql.json
Packetbeat/_meta/kibana/default/dashboard/Packetbeat-nfs.json
Packetbeat/_meta/kibana/default/dashboard/Packetbeat-overview.json
Packetbeat/_meta/kibana/default/dashboard/Packetbeat-pgsql.json
Packetbeat/_meta/kibana/default/dashboard/Packetbeat-thrift.json
Winlogbeat/_meta/kibana/default/dashboard/Winlogbeat-overview.json

Depends on https://github.com/elastic/beats/pull/4413.
Update the dashboards for Kibana 6.x for Packetbeat, Heartbeat and Winlogbeat

Update dashboards for Packetbeat, Heartbeat and Winlogbeat

---

dev-tools/packer/version.yml
filebeat/filebeat.template-es2x.json
filebeat/filebeat.template-es6x.json
filebeat/filebeat.template.json
heartbeat/heartbeat.template-es2x.json
heartbeat/heartbeat.template-es6x.json
heartbeat/heartbeat.template.json
libbeat/beat/version.go
libbeat/libbeat.template-es6x.json
metricbeat/metricbeat.template-es2x.json
metricbeat/metricbeat.template-es6x.json
metricbeat/metricbeat.template.json
packetbeat/packetbeat.template-es2x.json
packetbeat/packetbeat.template-es6x.json
packetbeat/packetbeat.template.json
winlogbeat/winlogbeat.template-es2x.json
winlogbeat/winlogbeat.template-es6x.json
winlogbeat/winlogbeat.template.json

Looks like we forgot to set this one.

Bump version to 5.6.0 in 5.x branch

---

libbeat/docs/shared-path-config.asciidoc

Fixes config option name (missed in #4547).

Fix config option name

---

libbeat/docs/gettingstarted.asciidoc
libbeat/docs/shared-directory-layout.asciidoc
libbeat/docs/shared-path-config.asciidoc
metricbeat/module/system/process/_meta/docs.asciidoc

Cherry-picks the following doc PRs into 5.3: 
#4530 
#4542
#4547
#4628 
#3581

Backport to 5.3: #4530  #4542 #4547 #4628  #3581 

---

libbeat/docs/shared-directory-layout.asciidoc
metricbeat/module/system/process/_meta/docs.asciidoc

Forward ports a couple changes that were made in older branches: #4542 and #3581

Forward port to master: #4542 and #3581

---

libbeat/docs/communitybeats.asciidoc

Add a [cockroachDB beat](https://github.com/stanxii/cockroachbeat).

add cockroachbeat link to beats

---

filebeat/module/nginx/access/machine_learning/datafeed_low_request_rate.json
filebeat/module/nginx/access/machine_learning/datafeed_remote_ip_request_rate.json
filebeat/module/nginx/access/machine_learning/datafeed_remote_ip_url_count.json
filebeat/module/nginx/access/machine_learning/datafeed_response_code.json
filebeat/module/nginx/access/machine_learning/datafeed_visitor_rate.json

Updated for machine learning datafeed; types, query filters and frequency.

Update ML datafeed settings

---

auditbeat/module/audit/file/metricset_test.go

The test was unreliable because occasionally an "updated" event is received when moving a file. This makes the test more robust.

Fix file integrity test case

---

libbeat/docs/communitybeats.asciidoc

Adding a new beat to listen to a mqtt broker, and add any message received to elasticsearch

Adding mqttbeat

---

libbeat/docs/communitybeats.asciidoc

Cherry-pick of PR #4674 to master branch. Original message: 
Adding a new beat to listen to a mqtt broker, and add any message received to elasticsearch

Cherry-pick #4674 to master: Adding mqttbeat

---

filebeat/module/nginx/access/machine_learning/datafeed_low_request_rate.json
filebeat/module/nginx/access/machine_learning/datafeed_remote_ip_request_rate.json
filebeat/module/nginx/access/machine_learning/datafeed_remote_ip_url_count.json
filebeat/module/nginx/access/machine_learning/datafeed_response_code.json
filebeat/module/nginx/access/machine_learning/datafeed_visitor_rate.json

Cherry-pick of PR #4676 to 5.x branch. Original message: 
Updated for machine learning datafeed; types, query filters and frequency.

Cherry-pick #4676 to 5.x: Update ML datafeed settings

---

filebeat/docs/fields.asciidoc
filebeat/filebeat.reference.yml
filebeat/module/redis/_meta/config.reference.yml
filebeat/module/redis/_meta/config.yml
filebeat/module/redis/_meta/fields.yml
filebeat/modules.d/redis.yml.disabled

They were missing from the module.

Added FBM Redis sample configuration files

---

libbeat/docs/version.asciidoc

As usual, let's only merge this one when the release is confirmed.

Set docs version to 5.5.1 in 5.5 branch

---

dev-tools/packer/version.yml
filebeat/filebeat.template-es2x.json
filebeat/filebeat.template-es6x.json
filebeat/filebeat.template.json
heartbeat/heartbeat.template-es2x.json
heartbeat/heartbeat.template-es6x.json
heartbeat/heartbeat.template.json
libbeat/beat/version.go
libbeat/libbeat.template-es6x.json
metricbeat/metricbeat.template-es2x.json
metricbeat/metricbeat.template-es6x.json
metricbeat/metricbeat.template.json
packetbeat/packetbeat.template-es2x.json
packetbeat/packetbeat.template-es6x.json
packetbeat/packetbeat.template.json
winlogbeat/winlogbeat.template-es2x.json
winlogbeat/winlogbeat.template-es6x.json
winlogbeat/winlogbeat.template.json

5.5.1 was released, so bumping versions in the 5.5 branch.

Set version to 5.5.2 in the 5.5 branch

---

libbeat/_meta/kibana/default/index-pattern/libbeat.json

The version embedded in the file needed updating for 7.0.

Update libbeat index-pattern version

---

CHANGELOG.asciidoc
libbeat/_meta/kibana/default/index-pattern/libbeat.json
libbeat/docs/release.asciidoc

Same as #4752, but for the master branch.

Close changelog beta1 (master)

---

auditbeat/auditbeat.reference.yml
filebeat/filebeat.reference.yml
heartbeat/heartbeat.reference.yml
libbeat/_meta/config.reference.yml
metricbeat/metricbeat.reference.yml
packetbeat/packetbeat.reference.yml
winlogbeat/winlogbeat.reference.yml

Add more info for each configuration option from the `setup.template.settings` section available in the reference file.

Add more info for each option under setup.template.settings

---

dev-tools/packer/docker/fpm-image/Dockerfile

Cherry-pick of PR #4790 to 6.0 branch. Original message:

Cherry-pick #4790 to 6.0: Pin FPM version

---

libbeat/_meta/kibana/default/index-pattern/libbeat.json
libbeat/docs/version.asciidoc

This one should be merged a bit before the release.

Set docs version to beta1

---

CHANGELOG.asciidoc
heartbeat/monitors/util.go

Fix wrong timestamp in heartbeat events

---

CHANGELOG.asciidoc
metricbeat/module/mysql/_meta/kibana/default/dashboard/Metricbeat-mysql.json

Cherry-pick of PR #4857 to 6.0 branch. Original message: 
This updates the metricbeat mysql dashboard.

Cherry-pick #4857 to 6.0: Fix MySQL CRUD expression

---

CHANGELOG.asciidoc
libbeat/cmd/root.go
libbeat/plugin/cli.go

Cherry-pick of PR #4799 to 6.0 branch. Original message:

Cherry-pick #4799 to 6.0: Fix go plugins not loaded when beat starts

---

libbeat/docs/breaking.asciidoc
libbeat/docs/communitybeats.asciidoc

Cherry-picks #4760 and #4829 into 6.0 branch

Backport to 6.0: #4760 and #4829

---

CHANGELOG.asciidoc

Added breaking change CHANGELOG entry for the removal of the _all field

---

filebeat/docs/reload-configuration.asciidoc

Cherry-picks #4930  and #4941 into 6.0

Backport to 6.0: Config reload docs

---

dev-tools/packer/version.yml
filebeat/filebeat.template-es2x.json
filebeat/filebeat.template-es6x.json
filebeat/filebeat.template.json
heartbeat/heartbeat.template-es2x.json
heartbeat/heartbeat.template-es6x.json
heartbeat/heartbeat.template.json
libbeat/beat/version.go
libbeat/libbeat.template-es6x.json
metricbeat/metricbeat.template-es2x.json
metricbeat/metricbeat.template-es6x.json
metricbeat/metricbeat.template.json
packetbeat/packetbeat.template-es2x.json
packetbeat/packetbeat.template-es6x.json
packetbeat/packetbeat.template.json
winlogbeat/winlogbeat.template-es2x.json
winlogbeat/winlogbeat.template-es6x.json
winlogbeat/winlogbeat.template.json

Should be merged today, please.

Bump version to 5.5.3 in the 5.5 branch

---

libbeat/docs/communitybeats.asciidoc

Add kafkabeat to community beats doc

---

metricbeat/module/rabbitmq/_meta/kibana/5.x/dashboard/Metricbeat-Rabbitmq.json
metricbeat/module/rabbitmq/_meta/kibana/5.x/search/Metricbeat-Rabbitmq.json
metricbeat/module/rabbitmq/_meta/kibana/5.x/visualization/Rabbitmq-Erlang-Process-Usage.json
metricbeat/module/rabbitmq/_meta/kibana/5.x/visualization/Rabbitmq-Memory-Usage.json
metricbeat/module/rabbitmq/_meta/kibana/5.x/visualization/Rabbitmq-Number-of-Nodes.json
metricbeat/module/rabbitmq/_meta/kibana/5.x/visualization/Rabbitmq-Queue-Index-Operations.json
metricbeat/module/rabbitmq/_meta/kibana/default/dashboard/Metricbeat-Rabbitmq.json

Take over this PR:https://github.com/elastic/beats/pull/4497 where a dashboard for RabbitMQ is added.

Add 5.x rabbitmq dashboards

---

auditbeat/auditbeat.reference.yml
filebeat/filebeat.reference.yml
heartbeat/heartbeat.reference.yml
libbeat/_meta/config.reference.yml
metricbeat/metricbeat.reference.yml
packetbeat/packetbeat.reference.yml
winlogbeat/winlogbeat.reference.yml

@simitt Thanks for spotting this one.

Fix typo in reference config file

---

packetbeat/scripts/tcp-protocol/README.md
packetbeat/scripts/tcp-protocol/{protocol}/pub.go.tmpl
packetbeat/scripts/tcp-protocol/{protocol}/{protocol}.go.tmpl

- Update to the tcp protocol generator to work with changes to the publisher pipeline in beats
- minor fixes in readme

Adapt packetbeat tcp protocol generator to new publisher pipeline

---

generator/beat/{beat}/.travis.yml

The command seems to do nothing helpful so I just removed it.

closes #4837 Travis errors on chmod command

---

auditbeat/auditbeat.reference.yml
filebeat/filebeat.reference.yml
heartbeat/heartbeat.reference.yml
libbeat/_meta/config.reference.yml
metricbeat/metricbeat.reference.yml
packetbeat/packetbeat.reference.yml
winlogbeat/docs/fields.asciidoc
winlogbeat/winlogbeat.reference.yml

Cherry-pick of PR #4792 to 6.0 branch. Original message: 
Add more info for each configuration option from the `setup.template.settings` section available in the reference file.

Cherry-pick #4792 to 6.0: Add more info for each option under setup.template.settings

---

libbeat/docs/communitybeats.asciidoc

Adding the beat also to this branch

Add Cloudfrontbeat to the community beats

---

CHANGELOG.asciidoc
dev-tools/packer/platforms/centos/beatname.sh.j2
dev-tools/packer/platforms/debian/beatname.sh.j2

Fixes #5040.
Credit to @exekias for finding the solution.

Fix /usr/bin/beatname script to accept -d "*"

---

libbeat/publisher/pipeline/pipeline.go

Update the publisher pipeline to only drop events from the
queue on beat.Client close when: guaranteed mode is set and no global
ACK handler is registered.

Modify events dropping on Close

---

libbeat/cmd/run.go
libbeat/tests/system/test_cmd.py

Fix accidental removal of `--setup` flag

---

libbeat/cmd/run.go
libbeat/tests/system/test_cmd.py

Cherry-pick of PR #5060 to 6.0 branch. Original message: 
Fixes #5059

Cherry-pick #5060 to 6.0: Fix accidental removal of `--setup` flag

---

libbeat/docs/shared-download-and-install.asciidoc

Merging without review to fix broken link in the docs.

[Docs] Fix broken link to repo install instructions

---

libbeat/api/server.go

The previous log message was too crpytic.

Improve log message for metrics endpoint

---

CHANGELOG.asciidoc
metricbeat/docs/fields.asciidoc
metricbeat/module/kubernetes/event/_meta/fields.yml
metricbeat/module/kubernetes/event/event.go
metricbeat/module/kubernetes/event/types.go

Fixes https://github.com/elastic/beats/issues/5093

Fix kubernetes events module to be able to index time fields properly

---

libbeat/docs/communitybeats.asciidoc

Cherrypicks  #4915 and adds edit to githubbeat description.

Backport: Cherrypick community beats updates into 6.0

---

auditbeat/Makefile
filebeat/Makefile
heartbeat/Makefile
libbeat/scripts/Makefile
libbeat/scripts/generate_fields_docs.py
metricbeat/Makefile
packetbeat/Makefile
winlogbeat/Makefile

Instead of https://github.com/elastic/beats/pull/5106

Introduce BEAT_TITLE as suggested by @tsg

---

libbeat/docs/command-reference.asciidoc

Backport: Cherrypicks #5117 into 6.0

---

dev-tools/packer/version.yml
filebeat/filebeat.template-es2x.json
filebeat/filebeat.template-es6x.json
filebeat/filebeat.template.json
heartbeat/heartbeat.template-es2x.json
heartbeat/heartbeat.template-es6x.json
heartbeat/heartbeat.template.json
libbeat/beat/version.go
libbeat/libbeat.template-es6x.json
metricbeat/metricbeat.template-es2x.json
metricbeat/metricbeat.template-es6x.json
metricbeat/metricbeat.template.json
packetbeat/packetbeat.template-es2x.json
packetbeat/packetbeat.template-es6x.json
packetbeat/packetbeat.template.json
winlogbeat/winlogbeat.template-es2x.json
winlogbeat/winlogbeat.template-es6x.json
winlogbeat/winlogbeat.template.json

Bump version 5.6.1

---

dev-tools/packer/version.yml
filebeat/filebeat.template-es2x.json
filebeat/filebeat.template-es6x.json
filebeat/filebeat.template.json
heartbeat/heartbeat.template-es2x.json
heartbeat/heartbeat.template-es6x.json
heartbeat/heartbeat.template.json
libbeat/beat/version.go
libbeat/libbeat.template-es6x.json
metricbeat/metricbeat.template-es2x.json
metricbeat/metricbeat.template-es6x.json
metricbeat/metricbeat.template.json
packetbeat/packetbeat.template-es2x.json
packetbeat/packetbeat.template-es6x.json
packetbeat/packetbeat.template.json
winlogbeat/winlogbeat.template-es2x.json
winlogbeat/winlogbeat.template-es6x.json
winlogbeat/winlogbeat.template.json

Bump version 5.5.4

---

libbeat/docs/outputconfig.asciidoc

[Docs] Fix incorrect ES output config example

---

CHANGELOG.asciidoc
filebeat/beater/filebeat.go
filebeat/config/config.go
filebeat/registrar/registrar.go

Cherry-pick of PR #5146 to 6.0 branch. Original message:

Cherry-pick #5146 to 6.0: Add flush timeout setting to filebeat registrar

---

dev-tools/packer/platforms/debian/run.sh.j2

Fixes duplicate daemon start after #5086.

Fix systemd unit file name in Debian package

---

auditbeat/auditbeat.reference.yml
filebeat/filebeat.reference.yml
generator/metricbeat/{beat}/main.go.tmpl
heartbeat/heartbeat.reference.yml
libbeat/_meta/config.reference.yml
libbeat/beat/info.go
libbeat/cmd/export.go
libbeat/cmd/export/config.go
libbeat/cmd/export/template.go
libbeat/cmd/instance/beat.go
libbeat/cmd/instance/beat_test.go
libbeat/cmd/modules.go
libbeat/cmd/root.go
libbeat/cmd/run.go
libbeat/cmd/setup.go
libbeat/cmd/test/config.go
libbeat/cmd/test/output.go
libbeat/cmd/version.go
libbeat/outputs/elasticsearch/elasticsearch.go
libbeat/scripts/Makefile
libbeat/scripts/generate_index_pattern.py
libbeat/template/load.go
libbeat/template/load_integration_test.go
metricbeat/cmd/test/modules.go
metricbeat/metricbeat.reference.yml
packetbeat/packetbeat.reference.yml
winlogbeat/winlogbeat.reference.yml

This is a breaking change in how a new Beat is created, and adds the possibility to specify a different Index Pattern.
fyi @roncohen

Allow IndexPrefix to be set.

---

filebeat/crawler/crawler.go
libbeat/cfgfile/reload.go

Unless I'm wrong we marked loading confs from separate files as stable, while keeping config reload in beta

Update `beta` messages for config reload

---

libbeat/outputs/logstash/async.go
libbeat/outputs/logstash/sync.go
libbeat/outputs/transport/client.go

Resolves #5198 . I have to expose the `host` of client.

[Logging] Include Logstash host info in debug messages #5198

---

CHANGELOG.asciidoc

Added changelog entry for #5189
