elastic/beats

heartbeat/docs/heartbeat-options.asciidoc
Forward ports #13941 to master.
=> [DOCS] Forward port: Add  POST and response.body examples (#13941)

metricbeat/docs/modules/graphite.asciidoc, metricbeat/module/graphite/_meta/docs.asciidoc
Backports #13900 to 7.4 branch
=> [7.4][DOCS] Backport: Fix typo in Graphite module docs (#13900)

CHANGELOG.next.asciidoc, libbeat/common/mapstr.go, libbeat/common/mapstr_test.go, libbeat/publisher/processing/default.go
Backports the following commits to 7.4:
- Implement deep merging of fields  (#13909)
=> [7.4] Implement deep merging of fields (#13909)

heartbeat/docs/heartbeat-options.asciidoc
It was difficult for me to know which schema to use when specifying the proxy. Provided an example.
=> Provide proxy_url example

heartbeat/docs/heartbeat-options.asciidoc
It was difficult for me to know which schema to use when specifying the proxy. Provided an example.
(cherry picked from commit 9098de2202d71bb5deba0e2d73c67d622cfda325)
=> Provide proxy_url example (#10335)

auditbeat/docs/modules.asciidoc, filebeat/docs/autodiscover-hints.asciidoc, filebeat/docs/fields.asciidoc, filebeat/docs/filebeat-general-options.asciidoc, filebeat/docs/inputs/input-redis.asciidoc, filebeat/docs/modules.asciidoc, filebeat/docs/modules/osquery.asciidoc, filebeat/module/osquery/_meta/docs.asciidoc, heartbeat/docs/heartbeat-options.asciidoc, journalbeat/docs/general-options.asciidoc, libbeat/docs/config-file-format.asciidoc, libbeat/docs/outputconfig.asciidoc, libbeat/docs/processors-using.asciidoc, libbeat/docs/regexp.asciidoc, libbeat/docs/template-config.asciidoc, libbeat/scripts/generate_fields_docs.py, metricbeat/docs/fields.asciidoc, metricbeat/docs/modules.asciidoc, packetbeat/docs/faq.asciidoc
Backports #13753 to the 6.8 branch
=> [6.8][DOCS] Backport: Fix markup issues for asciidoctor migration 

metricbeat/docs/metricbeat-options.asciidoc
Replaces https://github.com/elastic/beats/pull/12877/
=> [DOCS] Fix typo

auditbeat/docs/modules.asciidoc, filebeat/docs/autodiscover-hints.asciidoc, filebeat/docs/fields.asciidoc, filebeat/docs/filebeat-general-options.asciidoc, filebeat/docs/inputs/input-redis.asciidoc, filebeat/docs/modules.asciidoc, filebeat/docs/modules/osquery.asciidoc, filebeat/module/osquery/_meta/docs.asciidoc, heartbeat/docs/heartbeat-options.asciidoc, journalbeat/docs/general-options.asciidoc, libbeat/docs/config-file-format.asciidoc, libbeat/docs/outputconfig.asciidoc, libbeat/docs/processors-using.asciidoc, libbeat/docs/regexp.asciidoc, libbeat/docs/template-config.asciidoc, libbeat/scripts/generate_fields_docs.py, metricbeat/docs/fields.asciidoc, metricbeat/docs/modules.asciidoc, packetbeat/docs/faq.asciidoc
Backports #13753 to the 6.7 branch
=> [6.7][DOCS] Backport: Fix markup issues for asciidoctor migration 

auditbeat/docs/modules.asciidoc, filebeat/docs/autodiscover-hints.asciidoc, filebeat/docs/fields.asciidoc, filebeat/docs/filebeat-general-options.asciidoc, filebeat/docs/inputs/input-redis.asciidoc, filebeat/docs/modules.asciidoc, filebeat/docs/modules/osquery.asciidoc, filebeat/module/osquery/_meta/docs.asciidoc, heartbeat/docs/heartbeat-options.asciidoc, libbeat/docs/config-file-format.asciidoc, libbeat/docs/outputconfig.asciidoc, libbeat/docs/processors-using.asciidoc, libbeat/docs/regexp.asciidoc, libbeat/docs/template-config.asciidoc, libbeat/scripts/generate_fields_docs.py, metricbeat/docs/fields.asciidoc, metricbeat/docs/modules.asciidoc, packetbeat/docs/faq.asciidoc
Backports #13753 to 6.6 branch.
=> [6.6][DOCS] Backport: Fix markup issues for asciidoctor migration

auditbeat/docs/modules.asciidoc, filebeat/docs/autodiscover-hints.asciidoc, filebeat/docs/fields.asciidoc, filebeat/docs/filebeat-general-options.asciidoc, filebeat/docs/inputs/input-redis.asciidoc, filebeat/docs/modules.asciidoc, filebeat/docs/modules/osquery.asciidoc, filebeat/module/osquery/_meta/docs.asciidoc, heartbeat/docs/heartbeat-options.asciidoc, libbeat/docs/config-file-format.asciidoc, libbeat/docs/outputconfig.asciidoc, libbeat/docs/processors-using.asciidoc, libbeat/docs/regexp.asciidoc, libbeat/docs/template-config.asciidoc, libbeat/scripts/generate_fields_docs.py, metricbeat/docs/fields.asciidoc, metricbeat/docs/modules.asciidoc, packetbeat/docs/faq.asciidoc
Backports #13753 to 6.6 branch.
=> [6.5][DOCS] Backport: Fix markup issues for asciidoctor migration

auditbeat/docs/modules.asciidoc, filebeat/docs/autodiscover-hints.asciidoc, filebeat/docs/filebeat-general-options.asciidoc, filebeat/docs/inputs/input-redis.asciidoc, filebeat/docs/modules.asciidoc, filebeat/docs/modules/osquery.asciidoc, filebeat/module/osquery/_meta/docs.asciidoc, heartbeat/docs/heartbeat-options.asciidoc, libbeat/docs/config-file-format.asciidoc, libbeat/docs/outputconfig.asciidoc, libbeat/docs/processors-using.asciidoc, libbeat/docs/regexp.asciidoc, libbeat/docs/template-config.asciidoc, metricbeat/docs/modules.asciidoc, packetbeat/docs/faq.asciidoc
Backports #13753 to 6.3 branch.
=> [6.3][DOCS] Backport: Fix markup issues for asdciidoctor (#14011) (#14012)

CHANGELOG.next.asciidoc, x-pack/libbeat/management/enroll.go, x-pack/libbeat/management/manager.go
=> Log CM deprecated

.github/CODEOWNERS
Update Integrations team name/handle
=> Update Integrations team name

vendor/github.com/google/gopacket/afpacket/afpacket.go, vendor/github.com/google/gopacket/afpacket/sockopt_linux.go, vendor/vendor.json
Vendor adriansr/gopacket/afpacket as google/gopacket/afpacket, containing a fix for the afpacket feature under x86 32-bit.
Currently in review at https://github.com/google/gopacket/pull/720
=> [Auditbeat] Fix system/socket DNS capture on x86 32-bit

packetbeat/docs/packetbeat-options.asciidoc
@jstrassb pointed out this place where we use binary gendered language. We don't want to marginalize anyone, so here's a fix. Also cleaned up a couple other minor grammatical problems.
=> [DOCS] Remove binary gendered language

auditbeat/docs/index.asciidoc, heartbeat/docs/index.asciidoc, metricbeat/docs/index.asciidoc, packetbeat/docs/index.asciidoc, winlogbeat/docs/index.asciidoc
=> [DOCS] Remove has_ml_jobs for Beats that don't support ML

filebeat/docs/filebeat-modules-options.asciidoc
Closes https://github.com/elastic/beats/issues/11729
=> [DOCS] Change title to improve retrievability

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
=> Bump docs version for 6.8.4

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
=> Bump docs version for 7.4.1

filebeat/docs/filebeat-modules-options.asciidoc
Backports #13931 to 7.4 branch.
=> [7.4][DOCS] Backport: Change title to improve retrievability (#13931)

filebeat/docs/filebeat-modules-options.asciidoc
Backports #13931 to 7.5 branch.
=> [7.5][DOCS] Backport: Change title to improve retrievability (#13931)

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
This reverts commit 31923fb11219ecb51a0c8d41be5d4ede04ccdd79.
=> Revert "Bump docs version for 7.4.1 (#13949)"

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
This reverts commit 6ca94661140b9cbe5842ba7f0a335a25b4aa75f2.
=> Revert "Bump docs version for 6.8.4 (#13969)"

metricbeat/docs/modules/mongodb.asciidoc, metricbeat/module/mongodb/_meta/docs.asciidoc, metricbeat/module/mongodb/collstats/_meta/docs.asciidoc, metricbeat/module/mongodb/dbstats/_meta/docs.asciidoc, metricbeat/module/mongodb/metrics/_meta/docs.asciidoc, metricbeat/module/mongodb/replstatus/_meta/docs.asciidoc, metricbeat/module/mongodb/status/_meta/docs.asciidoc
Cherry-pick of PR #13932 to 6.8 branch. Original message: 
resolves elastic/beats#13820
=> Cherry-pick #13932 to 6.8: add docs on what privileges are needed for using metricbeat mongodb module

metricbeat/docs/modules/mongodb.asciidoc, metricbeat/module/mongodb/_meta/docs.asciidoc, metricbeat/module/mongodb/collstats/_meta/docs.asciidoc, metricbeat/module/mongodb/dbstats/_meta/docs.asciidoc, metricbeat/module/mongodb/metrics/_meta/docs.asciidoc, metricbeat/module/mongodb/replstatus/_meta/docs.asciidoc, metricbeat/module/mongodb/status/_meta/docs.asciidoc
Cherry-pick of PR #13932 to 7.4 branch. Original message: 
resolves elastic/beats#13820
=> Cherry-pick #13932 to 7.4: add docs on what privileges are needed for using metricbeat mongodb module

metricbeat/docs/modules/mongodb.asciidoc, metricbeat/module/mongodb/_meta/docs.asciidoc, metricbeat/module/mongodb/collstats/_meta/docs.asciidoc, metricbeat/module/mongodb/dbstats/_meta/docs.asciidoc, metricbeat/module/mongodb/metrics/_meta/docs.asciidoc, metricbeat/module/mongodb/replstatus/_meta/docs.asciidoc, metricbeat/module/mongodb/status/_meta/docs.asciidoc
Cherry-pick of PR #13932 to 7.5 branch. Original message: 
resolves elastic/beats#13820
=> Cherry-pick #13932 to 7.5: add docs on what privileges are needed for using metricbeat mongodb module

libbeat/docs/security/basic-auth.asciidoc
Backports https://github.com/elastic/beats/pull/13927
=> [7.4][DOCS] Fixes link to role mapping (#13927)

packetbeat/docs/packetbeat-options.asciidoc
Backports #14139 to 7.4 branch.
=> [7.4][DOCS] Backport: Remove binary gender references (#14139)

packetbeat/docs/packetbeat-options.asciidoc
Backports #14139 to 7.5 branch.
=> [7.5][DOCS] Backport: Remove binary gender references (#14139)

libbeat/docs/security/basic-auth.asciidoc
=> [DOCS] Fixes link to role mapping (#13927)

CHANGELOG.next.asciidoc, metricbeat/docs/modules/azure.asciidoc, x-pack/metricbeat/metricbeat.reference.yml, x-pack/metricbeat/module/azure/_meta/config.reference.yml
Should fix https://github.com/elastic/beats/issues/14224
=> Update metricbeat azure config example

CHANGELOG.next.asciidoc, metricbeat/docs/modules/azure.asciidoc, x-pack/metricbeat/metricbeat.reference.yml, x-pack/metricbeat/module/azure/_meta/config.reference.yml
Cherry-pick of PR #14328 to 7.5 branch. Original message:
Should fix #14224
=> Cherry-pick #14328 to 7.5: Update metricbeat azure config example

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
DO NOT MERGE UNTIL DAY OF RELEASE
=> Bump docs version for 7.4.2

CHANGELOG.next.asciidoc, winlogbeat/docs/modules/sysmon.asciidoc, x-pack/winlogbeat/module/sysmon/_meta/docs.asciidoc
Mark the Winlogbeat `sysmon` module as GA.
It is feature complete, and has seen a good amount of adoption.
=> GA the Winlogbeat Sysmon module

CHANGELOG.next.asciidoc, x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go, x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
=> [Metricbeat] Fix cloudwatch metricset copying address in for loop

CHANGELOG.next.asciidoc, x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go, x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
Cherry-pick of PR #14391 to 7.x branch. Original message: 
closes #14376
=> Cherry-pick #14391 to 7.x: [Metricbeat] Fix cloudwatch metricset copying address in for loop

CHANGELOG.next.asciidoc, x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go, x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
Cherry-pick of PR #14391 to 7.5 branch. Original message: 
closes #14376
=> Cherry-pick #14391 to 7.5: [Metricbeat] Fix cloudwatch metricset copying address in for loop

libbeat/monitoring/report/elasticsearch/client.go
- [Monitoring] Use op_type = create with ES version >= 7.5.0  (#14313)
=> [7.5] [Monitoring] Use op_type = create with ES version >= 7.5.0 (#14313)

metricbeat/tests/system/test_logstash.py
=> Skip flaky test: test_beat.Test.test_xpack

CHANGELOG.next.asciidoc, metricbeat/module/elasticsearch/cluster_stats/data_xpack.go, metricbeat/module/elasticsearch/elasticsearch.go, metricbeat/module/elasticsearch/test_elasticsearch.py
- Convert license struct to MapStr  (#14378)
=> [7.5] Convert license struct to MapStr (#14378)

libbeat/docs/security/basic-auth.asciidoc
Backports https://github.com/elastic/beats/pull/13927
=> [7.5][DOCS] Fixes link to role mapping (#13927)

CHANGELOG.next.asciidoc, metricbeat/module/elasticsearch/ccr/ccr.go, metricbeat/module/elasticsearch/elasticsearch.go, metricbeat/module/elasticsearch/test_elasticsearch.py
- Check license expiry date zero value  (#14591)
=> [7.5] Check license expiry date zero value (#14591)

filebeat/docs/configuring-howto.asciidoc, filebeat/docs/getting-started.asciidoc, libbeat/docs/shared-central-management.asciidoc, libbeat/docs/shared-cm-tip.asciidoc, metricbeat/docs/configuring-howto.asciidoc, metricbeat/docs/gettingstarted.asciidoc
Backports #14104 to 7.5 branch.
=> [7.5][DOCS] Backport: Deprecate central management

libbeat/processors/actions/docs/rename.asciidoc
Backports #14408 to 7.5 branch.
=> [7.5][DOCS] Backport: Fix description of rename processor

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
=> Bump docs version for 6.8.5

CHANGELOG.next.asciidoc, winlogbeat/eventlog/eventlog.go, x-pack/winlogbeat/module/security/test/testdata/security-windows2012r2-logon.evtx.golden.json, x-pack/winlogbeat/module/security/test/testdata/security-windows2016-4672.evtx.golden.json, x-pack/winlogbeat/module/security/test/testdata/security-windows2016-logoff.evtx.golden.json, x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4720_Account_Created.evtx.golden.json, x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4722_Account_Enabled.evtx.golden.json, x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4723_Password_Change.evtx.golden.json, x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4724_Password_Reset.evtx.golden.json, x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4725_Account_Disabled.evtx.golden.json, x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4726_Account_Deleted.evtx.golden.json, x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4738_Account_Changed.evtx.golden.json, x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4740_Account_Locked_Out.evtx.golden.json, x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4767_Account_Unlocked.evtx.golden.json, x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4781_Account_Renamed.evtx.golden.json, x-pack/winlogbeat/module/security/test/testdata/security-windows2019_4688_Process_Created.evtx.golden.json, x-pack/winlogbeat/module/security/test/testdata/security-windows2019_4689_Process_Exited.evtx.golden.json, x-pack/winlogbeat/module/sysmon/test/testdata/sysmon-10.2-dns.evtx.golden.json, x-pack/winlogbeat/module/sysmon/test/testdata/sysmon-9.01.evtx.golden.json
- set host.name to computer name for windows events and sysmon
Fixes #13706
=> [Winlogbeat] Set host.name to computername

filebeat/tests/system/test_shutdown.py
Skips flaky test described in  #14647.
=> Skip test_shutdown_wait_ok flaky test

libbeat/docs/outputs/output-logstash.asciidoc
Quick link update for new APM ILM content.
=> [docs] Update APM ILM link

x-pack/dockerlogbeat/magefile.go, x-pack/dockerlogbeat/main.go, x-pack/dockerlogbeat/pipelinemanager/libbeattools.go, x-pack/dockerlogbeat/readme.md
This is another round of cleanup to standardize naming and clean up the readme.
=> [docker logging plugin] More cleanup

heartbeat/docs/configuring-howto.asciidoc
When this was merged we should have unset this var
=> [Heartbeat] Unset hints var in heartbeat after use

CHANGELOG.next.asciidoc, x-pack/filebeat/input/httpjson/input.go
Cherry-pick of PR #14728 to 7.x branch.
=> Cherry-pick #14728 to 7.x: Fix a problem where interval is not used as time.Duration

x-pack/metricbeat/module/aws/cloudwatch/_meta/docs.asciidoc
Cherry-pick of PR #14731 to 7.5 branch. Original message:
=> Cherry-pick #14731 to 7.5: Fix typo in cloudwatch doc

x-pack/metricbeat/module/aws/cloudwatch/_meta/docs.asciidoc
Cherry-pick of PR #14731 to 7.x branch. Original message:
=> Cherry-pick #14731 to 7.x: Fix typo in cloudwatch doc

auditbeat/docs/page_header.html, docs/devguide/page_header.html, filebeat/docs/page_header.html, libbeat/docs/page_header.html, metricbeat/docs/page_header.html, packetbeat/docs/page_header.html, winlogbeat/docs/page_header.html
Related to elastic/docs#1426
Applies to 6.2 and earlier. Version needs to be updated for each branch.
=> [6.2][DOCS] Adds EOL banner to Beats docs

filebeat/docs/page_header.html, libbeat/docs/page_header.html, packetbeat/docs/page_header.html
=> [1.0.1][DOCS] Adds EOL banner to Beats docs

filebeat/docs/page_header.html, libbeat/docs/page_header.html, packetbeat/docs/page_header.html, winlogbeat/docs/page_header.html
=> [1.1][DOCS] Adds EOL banner to Beats docs

filebeat/docs/page_header.html, libbeat/docs/page_header.html, packetbeat/docs/page_header.html, winlogbeat/docs/page_header.html
=> [1.2][DOCS] Adds EOL banner to Beats docs

filebeat/docs/page_header.html, libbeat/docs/page_header.html, packetbeat/docs/page_header.html, winlogbeat/docs/page_header.html
=> [1.3][DOCS] Adds EOL banner to Beats docs

filebeat/docs/page_header.html, libbeat/docs/page_header.html, metricbeat/docs/page_header.html, packetbeat/docs/page_header.html, winlogbeat/docs/page_header.html
=> [5.0][DOCS] Adds EOL banner to Beats docs

filebeat/docs/page_header.html, libbeat/docs/page_header.html, metricbeat/docs/page_header.html, packetbeat/docs/page_header.html, winlogbeat/docs/page_header.html
=> [5.1][DOCS] Adds EOL banner to Beats docs

filebeat/docs/page_header.html, libbeat/docs/page_header.html, metricbeat/docs/page_header.html, packetbeat/docs/page_header.html, winlogbeat/docs/page_header.html
=> [5.2][DOCS] Adds EOL banner to Beats docs

filebeat/docs/page_header.html, libbeat/docs/page_header.html, metricbeat/docs/page_header.html, packetbeat/docs/page_header.html, winlogbeat/docs/page_header.html
=> [5.3][DOCS] Adds EOL banner to Beats docs

filebeat/docs/page_header.html, libbeat/docs/page_header.html, metricbeat/docs/page_header.html, packetbeat/docs/page_header.html, winlogbeat/docs/page_header.html
=> [5.4][DOCS] Adds EOL banner to Beats docs

filebeat/docs/page_header.html, libbeat/docs/page_header.html, metricbeat/docs/page_header.html, packetbeat/docs/page_header.html, winlogbeat/docs/page_header.html
=> [5.5][DOCS] Adds EOL banner to Beats docs

filebeat/docs/page_header.html, libbeat/docs/page_header.html, metricbeat/docs/page_header.html, packetbeat/docs/page_header.html, winlogbeat/docs/page_header.html
=> [5.6][DOCS] Adds EOL banner to Beats docs

docs/devguide/page_header.html, filebeat/docs/page_header.html, heartbeat/docs/page_header.html, libbeat/docs/page_header.html, metricbeat/docs/page_header.html, packetbeat/docs/page_header.html, winlogbeat/docs/page_header.html
=> [6.0][DOCS] Adds EOL banner to Beats docs

auditbeat/docs/page_header.html, docs/devguide/page_header.html, filebeat/docs/page_header.html, libbeat/docs/page_header.html, metricbeat/docs/page_header.html, packetbeat/docs/page_header.html, winlogbeat/docs/page_header.html
=> [6.1][DOCS] Adds EOL banner to Beats docs

libbeat/docs/repositories.asciidoc
Forward ports community contribution #14218 to master.
=> [DOCS] Forward port: add `systemctl enable heartbeat-elastic` to HB doc (#14218)

libbeat/docs/repositories.asciidoc
Backports community contribution #14218 to 7.x.
=> [7.5][DOCS] Backports community contribution #14218 to 7.x.

CHANGELOG.next.asciidoc
Add missing changelog to #14825
=> [metricbeat]add missing changelog to #14825

libbeat/processors/decode_csv_fields/docs/decode_csv_fields.asciidoc
trim_leading_whitespace should be trim_leading_space
=> [DOCS] trim_leading_whitespace should be trim_leading_space

heartbeat/docs/heartbeat-options.asciidoc
(cherry picked from commit 177774965b49466c6b5f9a1a7767d66f9f29ee1f)
=> [Heartbeat] Document the user agent sent by heartbeat (#14805)

dev-tools/mage/dockerbuilder.go, dev-tools/packaging/packages.yml
Cherry-pick of PR #14796 to 7.x branch. Original message:
=> Cherry-pick #14796 to 7.x: Create extra set of UBI based images

CHANGELOG.next.asciidoc
This PR adds missing CHANGELOG entry to be introduced in https://github.com/elastic/beats/pull/14840
=> Add missing CHANGELOG entry

libbeat/docs/release-notes/highlights/highlights-7.5.0.asciidoc
Adds notable highlights to the Beats docs for 7.5.
=> Add Beats 7.5 highlights

x-pack/agent/pkg/tokenbucket/token_bucket_test.go
Fixed flaky test by adding delta to ensure bucket ticker ticked
=> [Fleet] Tokenbucket fix

libbeat/docs/release-notes/highlights/highlights-7.5.0.asciidoc
Backports #14892 to 7.5 branch
=> [7.5][DOCS] Backport: Add Beats 7.5 highlights

libbeat/docs/release-notes/highlights/highlights-7.5.0.asciidoc
Backports #14892 to 7.x branch
=> [7x][DOCS] Backport: Add Beats 7.5 highlights

CHANGELOG.next.asciidoc, x-pack/metricbeat/module/aws/utils.go
I finally was able to reproduce this problem with creating 165 EC2 instances in the same region but different availability zones.
When there is a large amount of AWS EC2 instances in same region, ec2 metricset starts to lose data from some of the instances. After one data collection, you can see only some of the instances have metrics in Elasticsearch. For example, with 165 EC2 instances in us-east-1, I was only able to collect metrics from 159 EC2 instances.
Only seeing metrics from 159 instances:
The problem turned out to be in two places:
1. When splitting a large array into smaller size arrays, there is 1 data point missing for every split caused by the wrong right index in for loop.
2. Pagination is missing for ListMetrics AWS API call. This is the main problem causing the data loss. …
=> [Metricbeat] Add pagination to ListMetrics AWS API call

libbeat/docs/monitoring/monitoring-beats.asciidoc, libbeat/docs/monitoring/monitoring-metricbeat.asciidoc
Meant to push this commit with  #14996.
=> [DOCS] Comment out unwanted links

libbeat/docs/monitoring/monitoring-internal-collection.asciidoc, libbeat/docs/monitoring/monitoring-metricbeat.asciidoc
Backports #14996 to the 7.5 branch.
=> [7.5][DOCS] Backport: Remove incorrect information about monitoring data routing

libbeat/docs/monitoring/monitoring-internal-collection.asciidoc, libbeat/docs/monitoring/monitoring-metricbeat.asciidoc
Backports #14996 to 7.x branch.
=> [7.x][DOCS] Backport: Remove incorrect information about monitoring data routing

libbeat/docs/monitoring/monitoring-beats.asciidoc, libbeat/docs/monitoring/monitoring-metricbeat.asciidoc
Backports #14998 to the 7.x branch.
=> [7.x][DOCS] Backport: Comment out unwanted links (#14998)

libbeat/docs/monitoring/monitoring-beats.asciidoc, libbeat/docs/monitoring/monitoring-metricbeat.asciidoc
Backports #14998 to the 7.5 branch.
=> [7.5][DOCS] Backport: Comment out unwanted links (#14998)

CHANGELOG.next.asciidoc, filebeat/input/kafka/kafka_integration_test.go, libbeat/outputs/kafka/client.go, libbeat/outputs/kafka/kafka.go, libbeat/outputs/kafka/kafka_integration_test.go, libbeat/outputs/kafka/partition.go, libbeat/publisher/event.go, testing/environments/docker/kafka/run.sh
- Adding publisher event cache  (#14568)
=> [7.x] Adding publisher event cache (#14568)

CHANGELOG.next.asciidoc, filebeat/input/kafka/kafka_integration_test.go, libbeat/outputs/kafka/client.go, libbeat/outputs/kafka/kafka.go, libbeat/outputs/kafka/kafka_integration_test.go, libbeat/outputs/kafka/partition.go, libbeat/publisher/event.go, testing/environments/docker/kafka/run.sh
- Adding publisher event cache  (#14568)
=> [7.5] Adding publisher event cache (#14568)

CHANGELOG.next.asciidoc
This PR adds missing changelog entry for PR: https://github.com/elastic/beats/pull/14977
Master issue: https://github.com/elastic/beats/issues/14855
=> Update CHANGELOG to PR#14977

CHANGELOG.next.asciidoc
Cherry-pick of PR #15045 to 7.x branch. Original message: 
This PR adds missing changelog entry for PR: https://github.com/elastic/beats/pull/14977
Master issue: https://github.com/elastic/beats/issues/14855
=> Cherry-pick #15045 to 7.x: Update CHANGELOG to PR#14977

CHANGELOG.next.asciidoc, metricbeat/module/docker/cpu/helper.go
=> Cherry-pick #15070 to 7.5: fallback to different CPU calculation if we have no online_cpu count

CHANGELOG.next.asciidoc
Missed adding a CHANGELOG entry for #15071 in that PR. So adding it now. Thanks for catching, @faec!
=> Adding missed CHANGELOG entry

CHANGELOG.next.asciidoc
When I merged #14206, neither myself nor anyone else noticed that I was missing a changelog. Adding that now.
=> [metricbeat] Add changelog entry for system/service metricset

CHANGELOG.next.asciidoc
* add changelog entry for system/service metricset
(cherry picked from commit 90ede956599fdb291489b4de886249dcd2782b5a)
=> Cherry-pick of 15146 to 7.x: [metricbeat] Add changelog entry for system/service metricset

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
=> Bump docs version for 6.8.6

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
=> Bump docs version for 7.5.1

docs/devguide/newdashboards.asciidoc
The PR extends dev guide with dashboard naming convention rules.
Issue: https://github.com/elastic/beats/issues/4984
=> [Docs] Update guide with dashboard naming convention

CHANGELOG.next.asciidoc, x-pack/filebeat/module/misp/threat/config/input.yml, x-pack/filebeat/module/misp/threat/manifest.yml
Cherry-pick of PR #14767 to 7.x branch. Original message:
=> Cherry-pick #14767 to 7.x: Fix SSLconfig in input.yml for Filebeat httpjson input in the MISP module

metricbeat/module/kibana/stats/stats.go
- Move HTTP calls to Kibana from New() to Fetch() (#15270)
=> [7.5] Move HTTP calls to Kibana from New() to Fetch() (#15270)

metricbeat/module/kibana/stats/stats.go
- Move HTTP calls to Kibana from New() to Fetch() (#15270)
=> [7.x] Move HTTP calls to Kibana from New() to Fetch() (#15270)

metricbeat/module/elasticsearch/elasticsearch.go, metricbeat/module/elasticsearch/test_elasticsearch.py
- Handle changes to license fields  (#15152)
=> [7.x] Handle changes to license fields (#15152)

NOTICE.txt, vendor/github.com/elastic/go-sysinfo/CHANGELOG.md, vendor/github.com/elastic/go-sysinfo/NOTICE.txt, vendor/github.com/elastic/go-sysinfo/README.md, vendor/github.com/elastic/go-sysinfo/go.mod, vendor/github.com/elastic/go-sysinfo/go.sum, vendor/vendor.json, winlogbeat/sys/eventlogging/eventlogging_windows.go
Updates elastic/go-sysinfo to latest version.
Closes #14311
Closes #15265
=> Update elastic/go-sysinfo to v1.2.0

x-pack/agent/pkg/tokenbucket/token_bucket.go, x-pack/agent/pkg/tokenbucket/token_bucket_test.go
This PR changes how we do testing for the bucket, instead of using time
based assertions we use a scheduler. In the tests we can manually
trigger the tick when the TokenBucket can drop. We also rely on the
blocking behavior and the fact that the tests will timeout.
So errors like the following in the CI should be removed:
```
=== RUN   TestTokenBucket
--- FAIL: TestTokenBucket (0.22s)
token_bucket_test.go:37:
Error Trace:	token_bucket_test.go:37
Error:      	Not equal:
expected: 4
actual  : 5
Test:       	TestTokenBucket
```
=> [Agent] Fix flaky tests concerning the TokenBucket

CHANGELOG.next.asciidoc
- Adding CHANGELOG entry (#15280)
=> [7.5] Adding CHANGELOG entry (#15280)

CHANGELOG.next.asciidoc
- Adding CHANGELOG entry (#15280)
=> [7.x] Adding CHANGELOG entry (#15280)

NOTICE.txt, x-pack/agent/pkg/agent/errors/types.go, x-pack/agent/pkg/agent/operation/monitoring.go, x-pack/agent/pkg/agent/operation/operation_config.go, x-pack/agent/pkg/agent/operation/operation_fetch.go, x-pack/agent/pkg/agent/operation/operation_install.go, x-pack/agent/pkg/agent/operation/operation_remove.go, x-pack/agent/pkg/agent/operation/operation_start.go, x-pack/agent/pkg/agent/operation/operation_stop.go, x-pack/agent/pkg/agent/operation/operation_verify.go, x-pack/agent/pkg/agent/operation/operator.go, x-pack/agent/pkg/agent/operation/operator_handlers.go, x-pack/agent/pkg/agent/program/program.go, x-pack/agent/pkg/agent/program/spec.go, x-pack/agent/pkg/core/plugin/app/process_cred.go, x-pack/agent/pkg/core/plugin/process/process.go, x-pack/agent/pkg/filewatcher/watcher.go, x-pack/agent/pkg/fleetapi/action.go, x-pack/agent/pkg/fleetapi/checkin_cmd.go, x-pack/agent/pkg/fleetapi/client.go, x-pack/agent/pkg/fleetapi/enroll_cmd.go, x-pack/agent/pkg/packer/packer.go, x-pack/agent/pkg/reporter/reporter.go
Second batch of onboarding packages to our custom error type
Packages migrated
- reporter
- packer
- fleetapi
- filewatcher
- process
- operation
- agent/program
Related: #14463
=> [Agent] Onboard custom errors package - part 2

heartbeat/docs/heartbeat-options.asciidoc
We missed adding these docs in #13795
(cherry picked from commit 2c94e7205233c2a4dbfb25b4d0c7feb7eaa5181a)
=> [Heartbeat] Add docs for rootless pings (#15194)

dev-tools/packaging/packages.yml
Cherry-pick of PR #15307 to 7.x branch. Original message: 
None
=> Cherry-pick #15307 to 7.x: Revert ubi packaging

NOTICE.txt, vendor/github.com/elastic/go-sysinfo/CHANGELOG.md, vendor/github.com/elastic/go-sysinfo/NOTICE.txt, vendor/github.com/elastic/go-sysinfo/providers/linux/container.go, vendor/github.com/elastic/go-sysinfo/providers/linux/host_linux.go, vendor/github.com/elastic/go-sysinfo/providers/linux/machineid.go, vendor/github.com/elastic/go-sysinfo/providers/linux/os.go, vendor/github.com/elastic/go-sysinfo/providers/linux/procnet.go, vendor/github.com/elastic/go-sysinfo/providers/windows/helpers_windows.go, vendor/github.com/elastic/go-sysinfo/providers/windows/process_windows.go, vendor/github.com/elastic/go-sysinfo/types/host.go, vendor/vendor.json
=> cherry-pick of #15329 to 7.x: Update go-sysinfo to v1.2.1

x-pack/agent/pkg/agent/application/action_dispatch.go, x-pack/agent/pkg/agent/application/application.go, x-pack/agent/pkg/agent/application/config.go, x-pack/agent/pkg/agent/application/emitter.go, x-pack/agent/pkg/agent/application/enroll_cmd.go, x-pack/agent/pkg/agent/application/handler_action_policy_change.go, x-pack/agent/pkg/agent/application/info/agent_id.go, x-pack/agent/pkg/agent/application/local_mode.go, x-pack/agent/pkg/agent/application/managed_mode.go, x-pack/agent/pkg/agent/application/once.go, x-pack/agent/pkg/agent/application/periodic.go, x-pack/agent/pkg/agent/application/stream.go, x-pack/agent/pkg/agent/cmd/enroll.go, x-pack/agent/pkg/agent/cmd/run.go, x-pack/agent/pkg/agent/storage/storage.go, x-pack/agent/pkg/agent/transpiler/rules.go, x-pack/agent/pkg/core/plugin/server/server.go, x-pack/agent/pkg/core/remoteconfig/grpc/factory.go, x-pack/agent/pkg/dir/discover.go
Last step of onboarding to custom error type
Fixes: #14463
=> [Agent] Onboard to custom errors type - step 3

x-pack/dockerlogbeat/magefile.go
=> Cherry-pick of #15346: [Elastic Logging Plugin] Fix tarball file name in dockerlogbeat build

script/build_docs.sh
Backports #15159 to 7.5 branch.
=> [7.5][DOCS] Backport: Switch doc build to use direct_html flag (#15159)

script/build_docs.sh
Backports #15159 to 7.x branch.
=> [7.x][DOCS] Backport: Switch doc build to use direct_html flag (#15159)

filebeat/docs/modules/kafka.asciidoc, filebeat/module/kafka/_meta/docs.asciidoc
Closes https://github.com/elastic/beats/issues/5898 (got lost in issue backlog for awhile).
=> [DOCS] Adds description for missing kafka_home parameter

journalbeat/docs/getting-started.asciidoc
Backports #15137 to 7.5 branch
=> [7.5][DOCS] Backport: Add note about broken dashboards (#15137)

journalbeat/docs/getting-started.asciidoc
Backports #15137 to 7.x branch.
=> [7.x][DOCS] Backport: Add note about broken dashboards (#15137)

x-pack/agent/pkg/agent/application/managed_mode.go
=> [Agent] Increase frequency of the Agent polling

libbeat/docs/monitoring/monitoring-beats.asciidoc, libbeat/docs/monitoring/monitoring-internal-collection-legacy.asciidoc, libbeat/docs/monitoring/monitoring-internal-collection.asciidoc, libbeat/docs/monitoring/monitoring-metricbeat.asciidoc, libbeat/docs/monitoring/shared-monitor-config-legacy.asciidoc
Backports #15003 to 7.x branch.
=> [7.x][DOCS] Backport: Clarify changes in monitoring settings (#15003)

libbeat/docs/monitoring/monitoring-beats.asciidoc, libbeat/docs/monitoring/monitoring-internal-collection-legacy.asciidoc, libbeat/docs/monitoring/monitoring-internal-collection.asciidoc, libbeat/docs/monitoring/monitoring-metricbeat.asciidoc, libbeat/docs/monitoring/shared-monitor-config-legacy.asciidoc
Backports #15003 to 7.5 branch.
=> [7.5][DOCS] Backport: Clarify changes in monitoring settings (#15003)

NOTICE.txt, libbeat/docs/monitoring/monitoring-beats.asciidoc, libbeat/docs/monitoring/monitoring-internal-collection-legacy.asciidoc, libbeat/docs/monitoring/monitoring-internal-collection.asciidoc, libbeat/docs/monitoring/monitoring-metricbeat.asciidoc, libbeat/docs/monitoring/shared-monitor-config-legacy.asciidoc
Backports #15003 to 7.4 branch.
=> [7.4][DOCS] Backport: Clarify changes in monitoring settings (#15003)

NOTICE.txt, libbeat/docs/monitoring/monitoring-beats.asciidoc, libbeat/docs/monitoring/monitoring-internal-collection-legacy.asciidoc, libbeat/docs/monitoring/monitoring-internal-collection.asciidoc, libbeat/docs/monitoring/monitoring-metricbeat.asciidoc, libbeat/docs/monitoring/shared-monitor-config-legacy.asciidoc
Backports #15003 to 7.3 branch.
=> [7.3][DOCS] Backport: Clarify changes in monitoring settings (#15003)

x-pack/agent/pkg/agent/application/enroll_cmd.go
Fix enroll to include os.Hostname when enroll is performed
Fixes: #15465
=> [Agent] Send hostname when enrolling

CHANGELOG.next.asciidoc, filebeat/docs/modules/azure.asciidoc, x-pack/filebeat/filebeat.reference.yml, x-pack/filebeat/module/azure/_meta/config.yml, x-pack/filebeat/module/azure/_meta/docs.asciidoc, x-pack/filebeat/module/azure/activitylogs/config/azure-eventhub.yml, x-pack/filebeat/module/azure/activitylogs/config/kafka.yml, x-pack/filebeat/module/azure/activitylogs/ingest/pipeline.json, x-pack/filebeat/module/azure/activitylogs/manifest.yml, x-pack/filebeat/module/azure/auditlogs/config/azure-eventhub.yml, x-pack/filebeat/module/azure/auditlogs/config/kafka.yml, x-pack/filebeat/module/azure/auditlogs/ingest/pipeline.json, x-pack/filebeat/module/azure/auditlogs/manifest.yml, x-pack/filebeat/module/azure/signinlogs/config/azure-eventhub.yml, x-pack/filebeat/module/azure/signinlogs/config/kafka.yml, x-pack/filebeat/module/azure/signinlogs/ingest/pipeline.json, x-pack/filebeat/module/azure/signinlogs/manifest.yml, x-pack/filebeat/modules.d/azure.yml.disabled
Cherry-pick of PR elastic/beats#15480 to 7.x branch. Original message:
Integrate the azure-eventhub input with the filebeat azure module
Replace the usage of the kafka input with the azure-eventhub input.
=> Cherry-pick #15480 to 7.x: Integrate the azure-eventhub input with the filebeat azure module

x-pack/agent/pkg/fleetapi/client_test.go, x-pack/agent/pkg/fleetapi/round_trippers.go
Fix an nil ptr issue when the Kibana host is not reacheable.
=> [Agent] Fleet auth round tripper nil ptr

libbeat/docs/template-config.asciidoc
=> [7.x] [DOCS] Remove outdated CCR note (#15506)

CHANGELOG.next.asciidoc, metricbeat/module/docker/cpu/helper.go
=> cherry-pick of 15070 to 7.x: [metricbeat] Fallback to different CPU calculation

libbeat/common/docker/helpers.go, metricbeat/module/docker/config.go, metricbeat/module/docker/container/data.go, metricbeat/module/docker/docker.go, metricbeat/module/docker/helper.go, metricbeat/module/docker/helper_test.go, metricbeat/module/docker/image/data.go
=> backport of 15058 to 7.x: [libbeat] move Docker helpers to libbeat, add some godocs (#15058)

x-pack/dockerlogbeat/pipelinemanager/clientLogReader.go
=> backport of 15099 to 7.x: Use docker helper functions to format output

libbeat/processors/decode_csv_fields/docs/decode_csv_fields.asciidoc
Forward ports #15249 to master branch.
=> [master][docs] Forward port: update settings for `decode_csv_fields` (#15249)

libbeat/processors/decode_csv_fields/docs/decode_csv_fields.asciidoc
Backports #15249 to 7.x branch.
=> [7.x][docs] Backport: update settings for `decode_csv_fields` (#15249)

libbeat/docs/security/users.asciidoc
=> [docs] Clarify privileges required for the writer role

libbeat/common/config.go, libbeat/common/logging.go, libbeat/common/mapstr.go, libbeat/common/mapstr_test.go, metricbeat/autodiscover/builder/hints/metrics.go
Backports the following commits to 7.6:
- Mask password discovered via module autodiscover hint  (#15616)
=> [7.6] Mask password discovered via module autodiscover hint (#15616)

libbeat/cmd/instance/imports_common.go
- Adds missing imports  (#15624)
=> [7.x] Adds missing imports (#15624)

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
=> Bump docs version for 7.5.2

libbeat/docs/shared-ilm.asciidoc
since 7.0 elasticsearch is using java.time style patterns.
YYYY becomes yyyy
-
=> Change joda style pattern to java style

libbeat/docs/security/users.asciidoc
Backports #15604 to 7.5 branch.
=> [7.5][docs] Backport: Clarify privileges required for the writer role (#15604)

libbeat/docs/security/users.asciidoc
Backports #15604 to 7.x branch
=> [7.x][docs] Backport: Clarify privileges required for the writer role (#15604)

libbeat/docs/version.asciidoc
Document python requirement as >= 3.7.
=> Update documented Python version to 3.7

CHANGELOG.next.asciidoc, filebeat/docs/modules/aws.asciidoc, x-pack/filebeat/filebeat.reference.yml, x-pack/filebeat/module/aws/_meta/config.yml, x-pack/filebeat/module/aws/_meta/docs.asciidoc, x-pack/filebeat/module/aws/cloudtrail/config/cloudtrail.yml, x-pack/filebeat/module/aws/cloudtrail/manifest.yml, x-pack/filebeat/module/aws/elb/config/s3.yml, x-pack/filebeat/module/aws/elb/manifest.yml, x-pack/filebeat/module/aws/s3access/config/s3.yml, x-pack/filebeat/module/aws/s3access/manifest.yml, x-pack/filebeat/module/aws/vpcflow/config/input.yml, x-pack/filebeat/module/aws/vpcflow/manifest.yml, x-pack/filebeat/modules.d/aws.yml.disabled
Cherry-pick of PR #15656 to 7.x branch. Original message: 
- add "shared_credential_file" to cloudtrail config
Fixes #15652
=> Cherry-pick #15656 to 7.x: [Filebeat] Add support for specifying AWS cred file

CHANGELOG.next.asciidoc, filebeat/docs/modules/aws.asciidoc, x-pack/filebeat/filebeat.reference.yml, x-pack/filebeat/module/aws/_meta/config.yml, x-pack/filebeat/module/aws/_meta/docs.asciidoc, x-pack/filebeat/module/aws/cloudtrail/config/cloudtrail.yml, x-pack/filebeat/module/aws/cloudtrail/manifest.yml, x-pack/filebeat/module/aws/elb/config/s3.yml, x-pack/filebeat/module/aws/elb/manifest.yml, x-pack/filebeat/module/aws/s3access/config/s3.yml, x-pack/filebeat/module/aws/s3access/manifest.yml, x-pack/filebeat/module/aws/vpcflow/config/input.yml, x-pack/filebeat/module/aws/vpcflow/manifest.yml, x-pack/filebeat/modules.d/aws.yml.disabled
Cherry-pick of PR #15656 to 7.6 branch. Original message: 
- add "shared_credential_file" to cloudtrail config
Fixes #15652
=> Cherry-pick #15656 to 7.6: [Filebeat] Add support for specifying AWS cred file

CHANGELOG.next.asciidoc, x-pack/filebeat/module/zeek/notice/config/notice.yml
=> [Filebeat] Fix typos in zeek notice fileset config file

filebeat/docs/filebeat-options.asciidoc
Should fix https://github.com/elastic/beats/issues/15801
=> Add azure input documentation for inputs

filebeat/docs/filebeat-options.asciidoc
Cherry-pick of PR elastic/beats#15803 to 7.x branch. Original message:
Should fix elastic/beats#15801
=> Cherry-pick #15803 to 7.x: Add azure input documentation for inputs

CHANGELOG.next.asciidoc, heartbeat/monitors/active/http/http.go, heartbeat/monitors/active/http/http_test.go, libbeat/common/transport/tlscommon/tls_config.go, libbeat/kibana/client.go, libbeat/outputs/elasticsearch/client.go, metricbeat/helper/http.go, x-pack/filebeat/input/httpjson/input.go
Pass TLS options to forward proxies (#15516)
Fixes a bug where TLS options would not be passed to forward proxies. This fixes a reported issue where x509 client cert auth doesn't work due to the cert parameters not being passed in.
Since this doesn't give us a full dialer we can't easily record TLS certificate expiry with proxies in heartbeat with this approach, so those fields would be missing. I think it makes sense to merge this change as-is and fix that secondary bug in a subsequent PR. I've opened a separate issue ( #15797 ) to cover that.
I've tested this manually against with the following config: https://github.com/elastic/uptime-contrib/tree/master/testing/configs/client-auth , note that you'll need the included client certs in that directory, and will need to alter the YAML to …
=> [7.6][heartbeat][libbeat][metricbeat][filebeat] 

libbeat/processors/actions/docs/copy_fields.asciidoc
yml example had wrong indentation.
=> fixed yml syntax

libbeat/processors/fingerprint/fingerprint_test.go
- Adding benchmarking of various fingerprinting methods  (#15086)
=> [7.x] Adding benchmarking of various fingerprinting methods (#15086)

libbeat/common/streambuf/streambuf.go
- Refactoring
Remove superfluous debug message log from streambuf.
Reduce the usage of global loggers.
- Relates #15699
=> remove debug logging from streambuf

filebeat/docs/modules/aws.asciidoc, x-pack/filebeat/module/aws/_meta/docs.asciidoc
This PR is to fix Filebeat aws module documentation to show all filesets and dashboard sreenshots.
=> [Filebeat] Update filebeat aws module doc to show all filesets

CHANGELOG.next.asciidoc, x-pack/filebeat/module/aws/cloudtrail/ingest/pipeline.yml, x-pack/filebeat/module/aws/cloudtrail/test/console-login-json.log-expected.json
Cherry-pick of PR #16088 to 7.x branch. Original message: 
- fix typo
=> Cherry-pick #16088 to 7.x: [Filebeat] fix mapping error for cloudtrail additonalEventData field

filebeat/docs/modules/aws.asciidoc, x-pack/filebeat/module/aws/_meta/docs.asciidoc
Cherry-pick of PR #16075 to 7.x branch. Original message: 
This PR is to fix Filebeat aws module documentation to show all filesets and dashboard sreenshots.
=> Cherry-pick #16075 to 7.x: [Filebeat] Update filebeat aws module doc to show all filesets

filebeat/docs/modules/aws.asciidoc, x-pack/filebeat/module/aws/_meta/docs.asciidoc
Cherry-pick of PR #16075 to 7.6 branch. Original message: 
This PR is to fix Filebeat aws module documentation to show all filesets and dashboard sreenshots.
=> Cherry-pick #16075 to 7.6: [Filebeat] Update filebeat aws module doc to show all filesets

libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc
Replaces https://github.com/elastic/beats/pull/9351.
@eedugon I made a few minor editorial changes. Please review my changes. Again I'm sorry that this got lost in the PR backlog.
=> [docs] Adding clarifications for client based PKI (replaces #9351)

filebeat/docs/configuring-howto.asciidoc, libbeat/docs/shared-deduplication.asciidoc
Backports #15171 to 7.x branch
=> [7.x][docs] Backport: Add new topic about data deduplication (#15171)

libbeat/docs/version.asciidoc
Sets the release state to released for 7.6.
MERGE THE DAY OF THE RELEASE.
=> [docs] Set release state to released

libbeat/scripts/Makefile
It is missing from the last PR #16127
=> Add GOFLAGS to system-test-env

filebeat/docs/modules/cisco.asciidoc, x-pack/filebeat/module/cisco/_meta/docs.asciidoc
This PR is to continue @loekvangool's #16208 for updating cisco Metricbeat module documentation.
=> [Metricbeat] Update docs.asciidoc for cisco module

filebeat/docs/modules/cisco.asciidoc, x-pack/filebeat/module/cisco/_meta/docs.asciidoc
Cherry-pick of PR #16265 to 7.x branch. Original message: 
This PR is to continue @loekvangool's #16208 for updating cisco Metricbeat module documentation.
=> Cherry-pick #16265 to 7.x: [Metricbeat] Update docs.asciidoc for cisco module

CHANGELOG.next.asciidoc, x-pack/filebeat/input/httpjson/httpjson_test.go, x-pack/filebeat/input/httpjson/input.go
Cherry-pick of PR #16315 to 7.x branch. Original message: 
Add a TLS test and more debug output to httpjson input
=> Cherry-pick #16315 to 7.x: Add a TLS test and more debug output to httpjson input

CHANGELOG.next.asciidoc, metricbeat/module/ceph/_meta/config-mgr.yml, metricbeat/modules.d/ceph-mgr.yml.disabled
Update changelog with changes introduced in https://github.com/elastic/beats/pull/16254
=> Update changelog with changes in PR 16254

libbeat/common/event.go
Cherry-pick of PR #16149 to 7.x branch. Original message: 
- Refactoring
Remove usage of logp.Debug/Warn by creating a logger instance in the GenericEventNormalizer. The `Normalizer` uses `logp.New` for now to keep the change less disruptive.
Getting rid of global loggers functions.
- Relates elastic/beats#15699
=> Cherry-pick #16149 to 7.x: Reduce use of global loggers in libbeat/common

filebeat/docs/overview.asciidoc
Forward ports #15075 to master.
=> [master][docs] Forward port: Typo in introduction text (#15075)

filebeat/docs/overview.asciidoc
Forward ports #15075 to 7.6 branch.
=> [7.6][docs] Forward port: Typo in introduction text (#15075)

filebeat/docs/overview.asciidoc
=> [7.x][docs] Backport: Typo in introduction text (#15075)

libbeat/_meta/config.reference.yml.tmpl
This reverts commit 523528b7516adbda814d8770a2e259a4464023b0.
=> Revert "match reference.yml to code default (#16476)"

auditbeat/auditbeat.reference.yml, filebeat/filebeat.reference.yml, heartbeat/heartbeat.reference.yml, journalbeat/journalbeat.reference.yml, libbeat/_meta/config.reference.yml.tmpl, metricbeat/metricbeat.reference.yml, packetbeat/packetbeat.reference.yml, winlogbeat/winlogbeat.reference.yml, x-pack/auditbeat/auditbeat.reference.yml, x-pack/filebeat/filebeat.reference.yml, x-pack/functionbeat/functionbeat.reference.yml, x-pack/metricbeat/metricbeat.reference.yml, x-pack/winlogbeat/winlogbeat.reference.yml
reenable #16476 and add updated per beat reference files.
=> Fixed reference.yml

auditbeat/auditbeat.reference.yml, filebeat/filebeat.reference.yml, heartbeat/heartbeat.reference.yml, journalbeat/journalbeat.reference.yml, metricbeat/metricbeat.reference.yml, packetbeat/packetbeat.reference.yml, winlogbeat/winlogbeat.reference.yml, x-pack/auditbeat/auditbeat.reference.yml, x-pack/filebeat/filebeat.reference.yml, x-pack/functionbeat/functionbeat.reference.yml, x-pack/metricbeat/metricbeat.reference.yml, x-pack/winlogbeat/winlogbeat.reference.yml
Cherry-pick of PR #16487 to 7.x branch. Original message: 
reenable #16476 and add updated per beat reference files.
=> Cherry-pick #16487 to 7.x: Fixed reference.yml

filebeat/tests/system/test_modules.py, libbeat/tests/system/requirements.txt
The fileset of the iptables test didn't skip the @timestamp field, so
I have included the iptables.log data to the list of dataset to remove.
I also changed the assertion slighly to be relevant on the order of the
expectation and instead of dropping the JSON output in the log we will
display the difference as a diff.
Fix issues with elastic/beats#15980
I will make another PR to master to add the new assertion which gives you more information about what the error is instead of just dropping the whole JSON object.
-
=> Fix the iptables issues

auditbeat/auditbeat.reference.yml, filebeat/filebeat.reference.yml, heartbeat/heartbeat.reference.yml, journalbeat/journalbeat.reference.yml, libbeat/_meta/config.reference.yml.tmpl, libbeat/outputs/redis/docs/redis.asciidoc, metricbeat/metricbeat.reference.yml, packetbeat/packetbeat.reference.yml, winlogbeat/winlogbeat.reference.yml, x-pack/auditbeat/auditbeat.reference.yml, x-pack/filebeat/filebeat.reference.yml, x-pack/metricbeat/metricbeat.reference.yml, x-pack/winlogbeat/winlogbeat.reference.yml
- Doc update
Output reference config files and redis output docs.
The redis host setting accepts passwords and URL schemas by now.
This change update the reference config files and docs.
- Relates #16206
=> Update redis host settings docs

metricbeat/module/prometheus/collector/_meta/docs.asciidoc, metricbeat/module/prometheus/collector/collector.go
Cherry-pick of PR #16568 to 7.x branch. Original message: 
Closes https://github.com/elastic/beats/issues/16564
=> Cherry-pick #16568 to 7.x: Apply filters on prometheus 'up' metrics

.gitignore, x-pack/agent/.gitignore
Move specific gitignore into agent directory
=> Move specific gitignore into agent directory

heartbeat/docs/autodiscover-kubernetes-config.asciidoc, metricbeat/docs/autodiscover-kubernetes-config.asciidoc
- Closes https://github.com/elastic/beats/issues/16592
=> Update prometheus annotation example in docs of Autodiscover #16592

x-pack/libbeat/processors/add_cloudfoundry_metadata/docs/placeholder.asciidoc
Adds placeholder file for setting up path in conf.yaml.
=> [docs] Add temporary placeholder ot get doc PR build working for new processor

libbeat/docs/gettingstarted.asciidoc, libbeat/docs/shared-getting-started-intro.asciidoc
This PR switches trial sign-up links over to the standard attribute we're introducing that should provide some metrics for how effective these links are.﻿
Details for attribute are in https://github.com/elastic/docs/pull/1737, if you want to know more. 
We'd like to start collecting some metrics for ESS trial sign-ups from the docs.
Relates to https://github.com/elastic/marketing-ops/issues/7367
=> Switch to standard ESS trial links

.ci/packer_cache.sh
* Add Oracle Docker images to the packer images of immutable workers
related to https://github.com/elastic/beats/pull/12890
=> feat: add Oracle Docker images to the worker cache

heartbeat/docs/autodiscover-kubernetes-config.asciidoc, metricbeat/docs/autodiscover-kubernetes-config.asciidoc
Cherry-pick of PR #16597 to 7.6 branch. Original message: 
- Closes https://github.com/elastic/beats/issues/16592
=> Cherry-pick #16597 to 7.6: Update prometheus annotation example in docs of Autodiscover #16592

heartbeat/docs/autodiscover-kubernetes-config.asciidoc, metricbeat/docs/autodiscover-kubernetes-config.asciidoc
Cherry-pick of PR #16597 to 7.x branch. Original message: 
- Closes https://github.com/elastic/beats/issues/16592
=> Cherry-pick #16597 to 7.x: Update prometheus annotation example in docs of Autodiscover #16592

auditbeat/auditbeat.reference.yml, filebeat/filebeat.reference.yml, heartbeat/heartbeat.reference.yml, journalbeat/journalbeat.reference.yml, libbeat/_meta/config.reference.yml.tmpl, libbeat/docs/shared-kibana-config.asciidoc, metricbeat/metricbeat.reference.yml, packetbeat/packetbeat.reference.yml, winlogbeat/winlogbeat.reference.yml, x-pack/auditbeat/auditbeat.reference.yml, x-pack/filebeat/filebeat.reference.yml, x-pack/functionbeat/functionbeat.reference.yml, x-pack/metricbeat/metricbeat.reference.yml, x-pack/winlogbeat/winlogbeat.reference.yml
Documents the `space.id` setting available when setting up Kibana assets.
So users can understand how and when to use this setting.
=> Document Kibana Space ID setting

testing/environments/latest.yml
Related to https://github.com/elastic/beats/issues/16437.
=> Update testing environments to latest version

filebeat/docs/multiline.asciidoc
this patch fix regex patter for adding last line of java stacktrace with contains line with "..."
=> fix pattern for java stacktrace

libbeat/processors/dissect/docs/dissect.asciidoc
Adds a real-world example to the dissect docs.
Examples sometimes say more than words.
=> [docs] Add example to the dissect docs

filebeat/docs/modules/cisco.asciidoc, x-pack/filebeat/module/cisco/_meta/docs.asciidoc
Backports #16434 to 7.6 branch.
=> [7.6][docs] Backport: Update cisco.asciidoc (#16434)

auditbeat/auditbeat.reference.yml, filebeat/filebeat.reference.yml, heartbeat/heartbeat.reference.yml, journalbeat/journalbeat.reference.yml, libbeat/_meta/config.reference.yml.tmpl, metricbeat/metricbeat.reference.yml, packetbeat/packetbeat.reference.yml, winlogbeat/winlogbeat.reference.yml, x-pack/auditbeat/auditbeat.reference.yml, x-pack/filebeat/filebeat.reference.yml, x-pack/functionbeat/functionbeat.reference.yml, x-pack/metricbeat/metricbeat.reference.yml, x-pack/winlogbeat/winlogbeat.reference.yml
Add the missing ":" at the end of the option in the YAML.
-
=> Fix a formatting issues in the configuration related to ca_sha256

libbeat/docs/outputconfig.asciidoc, libbeat/docs/outputs-list.asciidoc, libbeat/docs/reference-yml.asciidoc, libbeat/outputs/redis/docs/redis.asciidoc, x-pack/functionbeat/docs/configuring-howto.asciidoc, x-pack/functionbeat/docs/index.asciidoc
Backports #16539 to the 7.x branch.
=> [7.x][docs] Backport: Clean up output docs to use opt-out includes (#16539)

libbeat/processors/dissect/docs/dissect.asciidoc
Backports #16588 to 7.x branch.
=> [7.x][docs] Backport: Add example to the dissect docs (#16588)

libbeat/processors/dissect/docs/dissect.asciidoc
Backports #16588 to 7.6 branch.
=> [7.6][docs] Backport: Add example to the dissect docs (#16588)

filebeat/docs/multiline.asciidoc
Forward ports #13516 to 7.6 branch.
=> [7.6][docs] Forward port: fix pattern for java stacktrace (#13516)

filebeat/docs/multiline.asciidoc
Forward ports #13516 to 7.x branch.
=> [7.x][docs] Forward port: fix pattern for java stacktrace (#13516)

metricbeat/docs/modules/kafka.asciidoc, metricbeat/module/kafka/_meta/docs.asciidoc
small documentation fix to continue https://github.com/elastic/beats/pull/16261
Co-authored-by: marnikvde <marnikvde@users.noreply.github.com>
=> Fix documentation typo for kafka metricbeat module

metricbeat/docs/modules/haproxy.asciidoc
Completes the change started in https://github.com/elastic/beats/pull/16703.
=> Generate haproxy module docs

libbeat/outputs/elasticsearch/client_integration_test.go, libbeat/scripts/Makefile, x-pack/libbeat/Makefile
This PR the fixes the minor issues introduced when merging the branch `go-modules`.
Make the tests green.
=> Get ES password from the correct environment variable during testing

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
=> Bump docs version for 6.8.7

dev-tools/mage/common.go, dev-tools/mage/pkg.go, dev-tools/mage/pkgspecs.go, dev-tools/mage/pkgtypes.go, dev-tools/packaging/packages.yml
Cherry-pick of PR #16624 to 7.x branch. Original message: 
The Agent has special requirements:
- Only Elastic licensed
- Bundle Metricbeat
- Bundle Filebeat
This PR isolate all the required changes for the devtools to correctly
build the agent. This can be merged as is because it doesn't impact
building any other beats.
-
=> Cherry-pick #16624 to 7.x: Agent required changes for building the agent artifacts

libbeat/docs/processors-list.asciidoc, x-pack/libbeat/processors/add_cloudfoundry_metadata/docs/add_cloudfoundry_metadata.asciidoc
Adds abbreviated title and fixes list alphabetization.
=> [docs] Add abbreviated title for add_cloudfoundry_metadata processor

libbeat/docs/processors-using.asciidoc
Backports #13506 to 7.6 branch.
=> [7.6][docs] Backport: Update processors-using.asciidoc (#13506)

libbeat/docs/processors-using.asciidoc
Backports #13506 to 7.x branch.
=> [7.x][docs] Backport: Update processors-using.asciidoc (#13506)

.github/CODEOWNERS
Backport of elastic/beats#16841  to `7.x.`
=> Remove integrations from CODEOWNERS (backport to 7.7)

Makefile
The `make snapshot` is currently breaking because of the agent there is
a problem when building the dependencies. I am temporary disable the building of the agent to move forward and will make another PRs to fix the actual problem.
-
=> Disable x-pack/agent from build

filebeat/docs/multiline.asciidoc
Backports elastic/beats#13516 to master.
=> [master][docs] Forward port: fix pattern for java stacktrace (#13516)

.github/ISSUE_TEMPLATE/flaky-test.md
Add `flaky-test` label to the issue template.
=> Add label to flaky test template

libbeat/docs/shared-ilm.asciidoc, libbeat/docs/shared-template-load.asciidoc
Backports elastic/beats#16704 to 7.6 branch.
=> [7.6][docs] Backport: Clarify how ILM affects template setup options (#16704)

x-pack/agent/pkg/agent/application/fleet_gateway_test.go
The test was not correctly setup to block, so when the test was
successful on fast machine it didn't actually block at at. This commit
ensure that the loop is blocked on the next fetch period before trying
to stop it.
This fixed is required to enable the fleet gateway tests. The failure was before this fix only reproduceable on slow system like a CI environment.
- Closes: #16771
=> Fleet gateway had a deadlocking test

CHANGELOG.next.asciidoc, libbeat/docs/processors-list.asciidoc
Cherry-pick of PR #16961 to 7.x branch. Original message: 
I forgot to change the conditional from ifdef to ifndef. It was also missing a changelog entry.
Follow up to #16013.
=> Cherry-pick #16961 to 7.x: Fix docs for translate_sid processor

CHANGELOG.next.asciidoc, x-pack/filebeat/module/cef/log/ingest/pipeline.yml, x-pack/filebeat/module/cef/log/test/cef.log, x-pack/filebeat/module/cef/log/test/cef.log-expected.json, x-pack/filebeat/module/cef/log/test/fp-ngfw-smc.log-expected.json
Cherry-pick of PR #16338 to 7.x branch. Original message: 
- related.hash
- related.ip
- related.user
- fix description
Closes #16157
Closes #16289
=> Cherry-pick #16338 to 7.x: [Filebeat] Improve ECS field mappings for CEF module

CHANGELOG.next.asciidoc, libbeat/common/kubernetes/metadata/config.go, libbeat/common/kubernetes/metadata/resource.go, libbeat/common/kubernetes/metadata/resource_test.go, metricbeat/module/kubernetes/util/kubernetes.go
=> Use default configuration in kubernetes metadata enrichers

auditbeat/docs/howto/howto.asciidoc, filebeat/docs/howto/howto.asciidoc, heartbeat/docs/howto/howto.asciidoc, journalbeat/docs/howto/howto.asciidoc, metricbeat/docs/howto/howto.asciidoc, packetbeat/docs/howto/howto.asciidoc, winlogbeat/docs/howto/howto.asciidoc, x-pack/functionbeat/docs/howto/howto.asciidoc
We decided to change the group heading slightly so it's clear what the section contains.
=> docs: change how to heading

CHANGELOG-developer.next.asciidoc
Add changelog entry about TEST_TAGS environment variable introduced in #16937 and #17075.
=> Add entry about TEST_TAGS in the developer changelog

CHANGELOG.next.asciidoc
This PR is to add the missing changelog for **https://github.com/elastic/beats/pull/16892**
=> [Metricbeat] missing changelog for PR 16892

journalbeat/cmd/root.go, journalbeat/config/config_test.go
Adds tests for journalbeat/config.SeekMode.Unpack
Getting acquainted with the code base and get the code coverage a bit higher.
Run the unit tests.
-
=> Enhancement: journalbeat: tests for config

metricbeat/module/postgresql/_meta/kibana/7/dashboard/Metricbeat-postgresql-overview.json
Backports https://github.com/elastic/beats/pull/16132 to `7.x`
=> Backport [Metricbeat] Fix PostgreSQL Dashboard (#16132)

metricbeat/module/mysql/_meta/kibana/7/dashboard/Metricbeat-mysql-overview.json
Backports https://github.com/elastic/beats/pull/17019 to `7.x`
=> Backport Fix MySQL default dashboard (#17019)

.github/PULL_REQUEST_TEMPLATE.md
Adds an item in the PR checklist for adding CHANGELOG entries.
Often we forget to add CHANGELOG entries to our PRs.
=> Add checklist item for CHANGELOG entry

libbeat/processors/add_process_metadata/gosigar_cid_provider.go
Cherry-pick of PR #17351 to 7.x branch. Original message: 
- Enhancement
Current solution caches whole content of cgroup file for each process. Let's cache only found container ids. 
Also, current solution skips kube-proxy container processes, because cgroup path has suffix /kube-proxy. 
Caching such a pile of useless data has performance impact.
- 
Relates #15947
=> Cherry-pick #17351 to 7.x: add_process_metadata: container id: Do not cache whole cgroup file for each process

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
DO NOT MERGE UNTIL RELEASE DAY.
=> Bump docs version for 6.8.8

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
DO NOT MERGE UNTIL RELEASE DAY.
=> Bump docs version for 7.6.2

Jenkinsfile
- bug
Run auditbeat tests if metricbeat has been modified.
Auditbeat reuses the metricbeat framework. Changes in the code of metricbeat must trigger auditbeat tests as well.
- #16953
=> Add metricbeat as dependency for auditbeat to Pipeline check

Jenkinsfile
Cherry-pick of PR #17393 to 7.7 branch. Original message: 
- bug
Run auditbeat tests if metricbeat has been modified.
Auditbeat reuses the metricbeat framework. Changes in the code of metricbeat must trigger auditbeat tests as well.
- #16953
=> Cherry-pick #17393 to 7.7: Add metricbeat as dependency for auditbeat to Pipeline check

heartbeat/docs/getting-started.asciidoc
Minor typo in heartbeat documentation.
=> Typo in Heartbeat docs

heartbeat/docs/getting-started.asciidoc
(cherry picked from commit 176f95ef78c9a18479c82fc9fee4e9ae03703c6c)
Forward port of https://github.com/elastic/beats/pull/17434
=> [Heartbeat][Docs] Fix typo (#17434)

filebeat/input/kafka/config.go, libbeat/outputs/kafka/config.go
Cherry-pick of PR #17470 to 7.x branch. Original message: 
None
=> Cherry-pick #17470 to 7.x: Enable GSSAPI authentication when Kerberos is configured

auditbeat/auditbeat.reference.yml, filebeat/filebeat.reference.yml, heartbeat/heartbeat.reference.yml, journalbeat/journalbeat.reference.yml, libbeat/_meta/config.reference.yml.tmpl, libbeat/outputs/kafka/config_test.go, metricbeat/metricbeat.reference.yml, packetbeat/packetbeat.reference.yml, winlogbeat/winlogbeat.reference.yml, x-pack/auditbeat/auditbeat.reference.yml, x-pack/filebeat/filebeat.reference.yml, x-pack/metricbeat/metricbeat.reference.yml, x-pack/winlogbeat/winlogbeat.reference.yml
Fix the kafka TestConfigAcceptValid test.
- Closes elastic/beats#17506
=> Fix kafka TestConfigAcceptValid test when when GSS-API mechanism is used

CHANGELOG.next.asciidoc, x-pack/filebeat/input/s3/input.go
=> Revert "[Filebeat] Get AWS credentials again when token expired"

auditbeat/auditbeat.reference.yml, filebeat/filebeat.reference.yml, heartbeat/heartbeat.reference.yml, journalbeat/journalbeat.reference.yml, libbeat/_meta/config.reference.yml.tmpl, libbeat/outputs/kafka/config_test.go, metricbeat/metricbeat.reference.yml, packetbeat/packetbeat.reference.yml, winlogbeat/winlogbeat.reference.yml, x-pack/auditbeat/auditbeat.reference.yml, x-pack/filebeat/filebeat.reference.yml, x-pack/metricbeat/metricbeat.reference.yml, x-pack/winlogbeat/winlogbeat.reference.yml
Cherry-pick of PR #17507 to 7.x branch. Original message: 
Fix the kafka TestConfigAcceptValid test.
- Closes elastic/beats#17506
=> Cherry-pick #17507 to 7.x: Fix kafka TestConfigAcceptValid test when when GSS-API mechanism is used

auditbeat/auditbeat.reference.yml, filebeat/filebeat.reference.yml, heartbeat/heartbeat.reference.yml, journalbeat/journalbeat.reference.yml, libbeat/_meta/config.reference.yml.tmpl, libbeat/outputs/kafka/config_test.go, metricbeat/metricbeat.reference.yml, packetbeat/packetbeat.reference.yml, winlogbeat/winlogbeat.reference.yml, x-pack/auditbeat/auditbeat.reference.yml, x-pack/filebeat/filebeat.reference.yml, x-pack/metricbeat/metricbeat.reference.yml, x-pack/winlogbeat/winlogbeat.reference.yml
Cherry-pick of PR #17507 to 7.7 branch. Original message: 
Fix the kafka TestConfigAcceptValid test.
- Closes elastic/beats#17506
=> Cherry-pick #17507 to 7.7: Fix kafka TestConfigAcceptValid test when when GSS-API mechanism is used

Jenkinsfile
The helper scripts in jenkins expect patterns to be configured as
regular expressions, not glob patterns.
We noticed no OSS tests in libbeat changes are run at all. Fixing the patterns should help.
-
=> Fix jenkins match patterns

CHANGELOG.next.asciidoc, metricbeat/docs/modules/ceph.asciidoc, metricbeat/metricbeat.reference.yml, metricbeat/module/ceph/_meta/config.reference.yml, metricbeat/module/ceph/_meta/docs.asciidoc, x-pack/metricbeat/metricbeat.reference.yml
This PR adjusts Ceph docs to contain information about different exposed ports.
=> Ceph: describe exposed ports

x-pack/agent/pkg/agent/application/fleet_gateway_test.go
Cherry-pick of PR elastic/beats#16931 to 7.x branch. Original message: 
The test was not correctly setup to block, so when the test was
successful on fast machine it didn't actually block at at. This commit
ensure that the loop is blocked on the next fetch period before trying
to stop it.
This fixed is required to enable the fleet gateway tests. The failure was before this fix only reproduceable on slow system like a CI environment.
- Closes: elastic/beats#16771
=> Cherry-pick #16931 to 7.x: Fleet gateway had a deadlocking test

libbeat/docs/command-reference.asciidoc, libbeat/docs/security/api-keys.asciidoc, libbeat/docs/shared-securing-beat.asciidoc, libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc
Backports https://github.com/elastic/beats/pull/15835
=> [docs] Documentation updates from APM (#15835)

x-pack/agent/pkg/agent/application/config.go, x-pack/agent/pkg/agent/application/enroll_cmd.go, x-pack/agent/pkg/agent/application/fleet_acker.go, x-pack/agent/pkg/agent/application/fleet_acker_test.go, x-pack/agent/pkg/agent/application/lazy_acker_test.go, x-pack/agent/pkg/fleetapi/ack_cmd.go, x-pack/agent/pkg/fleetapi/ack_cmd_test.go
Cherry-pick of PR elastic/beats#17148 to 7.x branch. Original message: 
Onboard to a change introduced here: https://github.com/elastic/kibana/pull/60324/files
Changing content of ACK request from []actionIds to []Events
Fixes: elastic/beats#17106
=> Cherry-pick #17148 to 7.x: [Agent] Onboard to new ACK

CHANGELOG.next.asciidoc, metricbeat/module/logstash/_meta/Dockerfile, metricbeat/module/logstash/_meta/pipeline/logstash.conf, metricbeat/module/logstash/docker-compose.yml, metricbeat/module/logstash/logstash_integration_test.go, metricbeat/module/logstash/node_stats/node_stats.go, metricbeat/module/logstash/node_stats/node_stats_test.go, testing/environments/local.yml
- Fix initialization of Logstash service URL  (#17497)
=> [7.7] Fix initialization of Logstash service URL (#17497)

CHANGELOG.next.asciidoc, x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-blob-storage-overview.json, x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-file-storage-overview.json, x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-queue-storage-overview.json, x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-storage-overview.json, x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-table-storage-overview.json
This PR is to fix azure storage related dashboards. For example the overview dashboard:
=> [Metricbeat] Fix azure storage overview dashboard

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/auditbeat/auditbeat-daemonset.yaml
Fix typo introduced in #17443.
=> Fix typo in auditbeat kubernetes manifest

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/auditbeat/auditbeat-daemonset.yaml
Cherry-pick of PR #17595 to 7.x branch. Original message: 
Fix typo introduced in #17443.
=> Cherry-pick #17595 to 7.x: Fix typo in auditbeat kubernetes manifest

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/auditbeat/auditbeat-daemonset.yaml
Cherry-pick of PR #17595 to 7.7 branch. Original message: 
Fix typo introduced in #17443.
=> Cherry-pick #17595 to 7.7: Fix typo in auditbeat kubernetes manifest

journalbeat/docs/config-options.asciidoc
Cherry-pick of PR #17632 to 7.x branch. Original message: 
None
=> Cherry-pick #17632 to 7.x: Fix tyop in the documentation of Journalbeat

journalbeat/docs/config-options.asciidoc
Cherry-pick of PR #17632 to 7.7 branch. Original message: 
None
=> Cherry-pick #17632 to 7.7: Fix tyop in the documentation of Journalbeat

journalbeat/docs/config-options.asciidoc
Cherry-pick of PR #17632 to 7.6 branch. Original message: 
None
=> Cherry-pick #17632 to 7.6: Fix tyop in the documentation of Journalbeat

filebeat/docs/modules/aws.asciidoc, x-pack/filebeat/input/s3/input.go, x-pack/filebeat/module/aws/_meta/docs.asciidoc
This PR is to fix some documentation typo and improve error messages in s3 input.
=> Fix filebeat documentation and s3 input error messages

auditbeat/auditbeat.reference.yml, filebeat/filebeat.reference.yml, heartbeat/heartbeat.reference.yml, journalbeat/journalbeat.reference.yml, libbeat/_meta/config.reference.yml.tmpl, metricbeat/metricbeat.reference.yml, packetbeat/packetbeat.reference.yml, winlogbeat/winlogbeat.reference.yml, x-pack/auditbeat/auditbeat.reference.yml, x-pack/filebeat/filebeat.reference.yml, x-pack/metricbeat/metricbeat.reference.yml, x-pack/winlogbeat/winlogbeat.reference.yml
Cherry-pick of PR #17701 to 7.7 branch. Original message: 
None
=> Cherry-pick #17701 to 7.7: Provide better defaults in reference configuration for Kerberos auth

auditbeat/auditbeat.reference.yml, filebeat/filebeat.reference.yml, heartbeat/heartbeat.reference.yml, journalbeat/journalbeat.reference.yml, libbeat/_meta/config.reference.yml.tmpl, metricbeat/metricbeat.reference.yml, packetbeat/packetbeat.reference.yml, winlogbeat/winlogbeat.reference.yml, x-pack/auditbeat/auditbeat.reference.yml, x-pack/filebeat/filebeat.reference.yml, x-pack/metricbeat/metricbeat.reference.yml, x-pack/winlogbeat/winlogbeat.reference.yml
Cherry-pick of PR #17701 to 7.x branch. Original message: 
None
=> Cherry-pick #17701 to 7.x: Provide better defaults in reference configuration for Kerberos auth

filebeat/docs/modules/crowdstrike.asciidoc, x-pack/filebeat/module/crowdstrike/_meta/docs.asciidoc
Product name in `crowdstrike` module should be CrowdStrike (uppercase `S`)
=> fix productname in CrowdStrike module docs

x-pack/elastic-agent/docs/elastic-agent.asciidoc
Currently only support CONFIG_CHANGE
=> [Agent] Add an early list of action that the agent can support.

Jenkinsfile
We are currently investigating an issue with the CI job that fails with
the macOS workers. Lets disable the job for everyone so we don't stuck
anyone.
-
=> [Elastic-Agent] Temporary disable the macOS job on the Elastic-Agent

libbeat/outputs/logstash/docs/logstash.asciidoc
Backports #17496 to 7.x branch
=> [7.x][docs] Backport: output.logstash.index doc update (#17496)

heartbeat/docs/autodiscover-hints.asciidoc
Backports #14365 to 7.6 branch.
=> [7.6][docs] Backport: Add hints based autodiscover docs for heartbeat (#14365)

heartbeat/docs/autodiscover-hints.asciidoc
Backports #14365 to 7.x branch
=> [7.x][docs] Backport: Add hints based autodiscover docs for heartbeat (#14365)

x-pack/elastic-agent/docs/elastic-agent.asciidoc
Cherry-pick of PR elastic/beats#17733 to 7.x branch. Original message: 
Currently only support CONFIG_CHANGE
=> Cherry-pick #17733 to 7.x: [Agent] Add an early list of action that the agent can support.

x-pack/elastic-agent/CHANGELOG.asciidoc, x-pack/elastic-agent/magefile.go
Cherry-pick of PR elastic/beats#17767 to 7.x branch. Original message: 
We don't plan to release the arm64 package buts let's keep it as a
target.
Make sure you are running go 1.10.13 and that your docker instance has more than 2 gb of memory assigned to it. 
-
=> Cherry-pick #17767 to 7.x: [Agent] Allow arm64 as a testing packages

Jenkinsfile
- feat: filter changes using go list output (#17397)
=> [7.7] feat: filter changes using go list output (#17397)

CHANGELOG.next.asciidoc, x-pack/filebeat/input/httpjson/httpjson_test.go, x-pack/filebeat/input/httpjson/input.go
Fix issue 17734 to retry on rate-limit error in the Filebeat httpjson input.
=> Cherry-pick #17735 to 7.7: Fix issue 17734 to retry on rate-limit error in the Filebeat httpjson input. 

libbeat/docs/release-notes/breaking/breaking-7.7.asciidoc
Backports #17739 to 7.x branch.
=> [7.x][docs] Backport: Add breaking changes for 7.7 (#17739)

libbeat/docs/release-notes/breaking/breaking-7.7.asciidoc
Backport #17739 to 7.7 branch.
=> [7.7][docs] Backport: Add breaking changes for 7.7 (#17739)

CHANGELOG.next.asciidoc, filebeat/docs/inputs/input-common-unix-options.asciidoc, filebeat/docs/inputs/input-syslog.asciidoc, filebeat/include/list.go, filebeat/input/syslog/config.go, filebeat/input/syslog/input.go, filebeat/input/unix/config.go, filebeat/input/unix/input.go, filebeat/inputsource/common/closeref.go, filebeat/inputsource/common/config.go, filebeat/inputsource/common/conn.go, filebeat/inputsource/common/conn_test.go, filebeat/inputsource/common/handler.go, filebeat/inputsource/common/listener.go, filebeat/inputsource/common/scan.go, filebeat/inputsource/common/scan_test.go, filebeat/inputsource/tcp/handler.go, filebeat/inputsource/unix/config.go, filebeat/inputsource/unix/handler.go, filebeat/inputsource/unix/server.go, filebeat/inputsource/unix/server_test.go, filebeat/tests/system/test_syslog.py, filebeat/tests/system/test_unix.py
Cherry-pick of PR #17492 to 7.x branch. Original message: 
This adds Unix stream socket support as an input source.
- Closes #10934
=> Cherry-pick #17492 to 7.x: [Filebeat] Unix stream socket input source

x-pack/elastic-agent/CHANGELOG.asciidoc
We were missing a changlog entry for https://github.com/elastic/beats/pull/17843
This PR takes care of it.
=> [Elastic-Agent] missing changelog for protocol change in elastic-agent

metricbeat/docs/modules/kafka.asciidoc, metricbeat/module/kafka/README.md, metricbeat/module/kafka/_meta/docs.asciidoc, metricbeat/module/kafka/_meta/supported-versions.yml, metricbeat/module/kafka/broker/_meta/docs.asciidoc, metricbeat/module/kafka/consumer/_meta/docs.asciidoc, metricbeat/module/kafka/docker-compose.yml, metricbeat/module/kafka/producer/_meta/docs.asciidoc, testing/environments/docker/kafka/Dockerfile
- Update Kafka versions  (#17819)
=> [7.x] Update Kafka versions (#17819)

metricbeat/docs/modules/kafka.asciidoc, metricbeat/module/kafka/README.md, metricbeat/module/kafka/_meta/docs.asciidoc, metricbeat/module/kafka/_meta/supported-versions.yml, metricbeat/module/kafka/broker/_meta/docs.asciidoc, metricbeat/module/kafka/consumer/_meta/docs.asciidoc, metricbeat/module/kafka/docker-compose.yml, metricbeat/module/kafka/producer/_meta/docs.asciidoc, testing/environments/docker/kafka/Dockerfile
- Update Kafka versions  (#17819)
=> [7.7] Update Kafka versions (#17819)

docs/devguide/fields-yml.asciidoc
Closes https://github.com/elastic/beats/issues/16342
=> [docs] Edit docs about field mappings

docs/devguide/fields-yml.asciidoc, docs/devguide/index.asciidoc, docs/devguide/newbeat.asciidoc
Backports #17740 and #12505 to 7.7 branch.
=> [7.7][docs] Backport: Edit docs about field mappings 

docs/devguide/fields-yml.asciidoc, docs/devguide/index.asciidoc, docs/devguide/newbeat.asciidoc
Backports #17740 and #12505 to 7.x branch.
=> [7.x][docs] Backport: Edit docs about field mappings

deploy/kubernetes/metricbeat-kubernetes.yaml, deploy/kubernetes/metricbeat/metricbeat-daemonset-configmap.yaml, metricbeat/docs/running-on-kubernetes.asciidoc
Cherry-pick of PR #17867 to 7.x branch. Original message: 
Adds required information for Openshift compatibility.
In order to have updated docs regarding Openshift support.
=> Cherry-pick #17867 to 7.x: Improve Openshift documentation

.ci/packaging.groovy
It adds a trigger to run the packaging job after a merge on the master branch.
This release fresh snapshots on every successful build.
=> feat: trigger packaging after a successful build on master

filebeat/docs/running-on-cloudfoundry.asciidoc, filebeat/docs/running-on-kubernetes.asciidoc, metricbeat/docs/running-on-cloudfoundry.asciidoc, metricbeat/docs/running-on-kubernetes.asciidoc
Backports #17955 to 7.7 branch.
=> [docs] Fix attribute resolution in example (#17955)

libbeat/docs/release-notes/highlights/highlights-7.7.0.asciidoc
Backports #17887 to 7.x branch.
=> [7.x][docs] Backport: Add release highlights for 7.7 (#17887)

CHANGELOG.next.asciidoc, filebeat/input/log/input.go
Fixes a small typo in a log message
So the log message is not confusing.
=> Fixes typo in log message

.ci/packaging.groovy
It adds a new pipeline to make the packaging
It replaces the multi-job we use for each branch and pull request, so everything will be in a single job, and the job logic in a Jenkinsfile.
related https://github.com/elastic/beats/issues/16603 https://github.com/elastic/beats/pull/17563
=> ci: [7.7] packagin pipeline job

Jenkinsfile
- ci: comment PRs with the build status (#17971)
=> [7.x] ci: comment PRs with the build status (#17971)

CHANGELOG.next.asciidoc
This PR is to add changelog entry for two PRs that both adding static mapping in aws module.
=> Add changelog for PR #17650 and PR #17614

filebeat/docs/modules/activemq.asciidoc, x-pack/filebeat/module/activemq/_meta/docs.asciidoc
Backports #17989 to 7.x branch.
=> [7.x][docs] Backport: Remove incorrect tag (#17989)

filebeat/docs/modules/activemq.asciidoc, x-pack/filebeat/module/activemq/_meta/docs.asciidoc
Backports #17989 to 7.7 branch.
=> [7.7][docs] Backport: Remove incorrect tag (#17989)

Jenkinsfile
- ci: support runbld to aggregate data (#18037)
=> Cherry-pick #18037 to 7.x: ci: support runbld to aggregate data

x-pack/metricbeat/module/aws/_meta/config.epr.yml
This PR adds `config.epr.yml` file to Metricbeat aws module for https://github.com/elastic/package-registry project with all optional config parameters.
=> Add config.epr.yml to Metricbeat aws module

CHANGELOG.next.asciidoc, x-pack/auditbeat/module/system/process/process.go, x-pack/auditbeat/module/system/process/process_test.go
- Closes https://github.com/elastic/beats/issues/17525
=> [Auditbeat] Add system module process dataset ECS categorization fields

x-pack/elastic-agent/CHANGELOG.asciidoc, x-pack/elastic-agent/pkg/agent/application/fleet_gateway.go, x-pack/elastic-agent/pkg/agent/application/fleet_gateway_test.go, x-pack/elastic-agent/pkg/agent/application/managed_mode.go
This PRs fixes a few issues:
1. Fix the flaky tests found in the Gateway (#17709)
2. Fix isses on shutdown (#17760):
- when the gateway was stuck in a retry loop.
- when mutliple signal (ctrl-c) were sent to the application.
Well it fixes panics.
-
=> [Elastic Agent] Fix issues with the Gateway     

filebeat/docs/fields.asciidoc, libbeat/scripts/generate_fields_docs.py, x-pack/filebeat/module/netflow/_meta/fields.yml, x-pack/filebeat/module/netflow/fields.go
Backports #16784 to 7.x branch.
=> [7.x][docs] Backport: Fix netflow field docs by removing duplicate topic (#16784)

x-pack/elastic-agent/pkg/agent/application/enroll_cmd_test.go
The windows tests should be fixed by now.
Fixes: #16860
-
=> [Elastic Agent] Enable windows enroll cmd test

x-pack/elastic-agent/pkg/agent/application/enroll_cmd_test.go
Cherry-pick of PR elastic/beats#18189 to 7.x branch. Original message: 
The windows tests should be fixed by now.
Fixes: elastic/beats#16860
-
=> Cherry-pick #18189 to 7.x: [Elastic Agent] Enable windows enroll cmd test

x-pack/elastic-agent/CHANGELOG.asciidoc, x-pack/elastic-agent/pkg/agent/application/fleet_gateway.go, x-pack/elastic-agent/pkg/agent/application/fleet_gateway_test.go, x-pack/elastic-agent/pkg/agent/application/managed_mode.go
Cherry-pick of PR elastic/beats#18135 to 7.x branch. Original message: 
This PRs fixes a few issues:
1. Fix the flaky tests found in the Gateway (#17709)
2. Fix isses on shutdown (#17760):
- when the gateway was stuck in a retry loop.
- when mutliple signal (ctrl-c) were sent to the application.
Well it fixes panics.
-
=> Cherry-pick #18135 to 7.x: [Elastic Agent] Fix issues with the Gateway     

x-pack/elastic-agent/pkg/agent/warn/warn.go
Closes https://github.com/elastic/beats/issues/18214
(cherry picked from commit e4f1bce6f8bc320611fc4a0ae603708c0c7e2d3c)
=> [Agent] Update log message to be Experimental instead of Alpha

metricbeat/docs/running-on-kubernetes.asciidoc
This PR fixes a broken link in the docs.
=> Fix docs link

metricbeat/docs/running-on-kubernetes.asciidoc
Cherry-pick of PR #18228 to 7.x branch. Original message: 
This PR fixes a broken link in the docs.
=> Cherry-pick #18228 to 7.x: Fix docs link

.ci/packaging.groovy, Jenkinsfile
- test: build docker image (#17905) (7d0a45a4)
=> [7.x] test: build docker image (#17905) (7d0a45a4)

.ci/packaging.groovy, Jenkinsfile
- test: build docker image (#17905) (7d0a45a4)
=> [7.7] test: build docker image (#17905) (7d0a45a4)

filebeat/docs/filebeat-options.asciidoc
Backports #17999 to the 7.7 branch.
=> [7.7][docs] Backport: Add missing HTTP JSON input (#17999)

filebeat/docs/filebeat-options.asciidoc
Backports #17999 to 7.x branch.
=> [7.x][docs] Backport: Add missing HTTP JSON input (#17999)

x-pack/elastic-agent/pkg/agent/operation/monitoring.go
Backport of https://github.com/elastic/beats/pull/18275
=> [Elastic Agent] Fix logging read from runnings process

metricbeat/docs/modules/kubernetes.asciidoc, metricbeat/metricbeat.reference.yml, metricbeat/module/kubernetes/_meta/config.reference.yml, metricbeat/module/kubernetes/_meta/docs.asciidoc, metricbeat/module/kubernetes/apiserver/_meta/docs.asciidoc, x-pack/metricbeat/metricbeat.reference.yml
Cherry-pick of PR #17636 to 7.7 branch. Original message: 
As agreed with @exekias , I'm adding in this PR some changes in Kubernetes module main document and in the majority of metricsets, including descriptions and configuration details for each one.
=> Cherry-pick #17636 to 7.7: Metricbeat Kubernetes module and metricsets docs proposal

metricbeat/docs/modules/kubernetes.asciidoc, metricbeat/metricbeat.reference.yml, metricbeat/module/kubernetes/_meta/config.reference.yml, metricbeat/module/kubernetes/_meta/docs.asciidoc, metricbeat/module/kubernetes/apiserver/_meta/docs.asciidoc, x-pack/metricbeat/metricbeat.reference.yml
Cherry-pick of PR #17636 to 7.x branch. Original message: 
As agreed with @exekias , I'm adding in this PR some changes in Kubernetes module main document and in the majority of metricsets, including descriptions and configuration details for each one.
=> Cherry-pick #17636 to 7.x: Metricbeat Kubernetes module and metricsets docs proposal

deploy/cloudfoundry/filebeat/filebeat.yml, deploy/cloudfoundry/metricbeat/metricbeat.yml
Fixes cloudfoundry deployment configs for metricbeat and filebeat to have the proper indentation.
So when deploying to cloudfoundry the processor works.
- Fixes #18279
=> Fix cloudfoundry deployment configs for metricbeat and filebeat

deploy/cloudfoundry/filebeat/filebeat.yml, deploy/cloudfoundry/metricbeat/metricbeat.yml
Cherry-pick of PR #18311 to 7.x branch. Original message: 
Fixes cloudfoundry deployment configs for metricbeat and filebeat to have the proper indentation.
So when deploying to cloudfoundry the processor works.
- Fixes #18279
=> Cherry-pick #18311 to 7.x: Fix cloudfoundry deployment configs for metricbeat and filebeat

deploy/cloudfoundry/filebeat/filebeat.yml, deploy/cloudfoundry/metricbeat/metricbeat.yml
Cherry-pick of PR #18311 to 7.7 branch. Original message: 
Fixes cloudfoundry deployment configs for metricbeat and filebeat to have the proper indentation.
So when deploying to cloudfoundry the processor works.
- Fixes #18279
=> Cherry-pick #18311 to 7.7: Fix cloudfoundry deployment configs for metricbeat and filebeat

deploy/cloudfoundry/filebeat/filebeat.yml, deploy/cloudfoundry/metricbeat/metricbeat.yml
Cherry-pick of PR #18311 to 7.8 branch. Original message: 
Fixes cloudfoundry deployment configs for metricbeat and filebeat to have the proper indentation.
So when deploying to cloudfoundry the processor works.
- Fixes #18279
=> Cherry-pick #18311 to 7.8: Fix cloudfoundry deployment configs for metricbeat and filebeat

auditbeat/auditbeat.docker.yml, filebeat/filebeat.docker.yml, heartbeat/heartbeat.docker.yml, journalbeat/journalbeat.docker.yml, libbeat/_meta/config.docker.yml, metricbeat/metricbeat.docker.yml, packetbeat/packetbeat.docker.yml, x-pack/auditbeat/auditbeat.docker.yml, x-pack/filebeat/filebeat.docker.yml, x-pack/metricbeat/metricbeat.docker.yml
Backports #18218 to 7.7 branch.
=> [7.7][docs] Backport: Prettify processor snippet in docker yml files (#18218)

auditbeat/auditbeat.docker.yml, filebeat/filebeat.docker.yml, heartbeat/heartbeat.docker.yml, journalbeat/journalbeat.docker.yml, libbeat/_meta/config/default.docker.yml.tmpl, metricbeat/metricbeat.docker.yml, packetbeat/packetbeat.docker.yml, x-pack/auditbeat/auditbeat.docker.yml, x-pack/filebeat/filebeat.docker.yml, x-pack/metricbeat/metricbeat.docker.yml
Backports #18218 to 7.x branch.
=> [7.x][docs] Backport: Prettify processor snippet in docker yml files (#18218)

metricbeat/docs/modules/kubernetes.asciidoc, metricbeat/metricbeat.reference.yml, metricbeat/module/kubernetes/_meta/config.reference.yml, metricbeat/module/kubernetes/_meta/docs.asciidoc, metricbeat/module/kubernetes/apiserver/_meta/docs.asciidoc, x-pack/metricbeat/metricbeat.reference.yml
Cherry-pick of PR #17636 to 7.8 branch. Original message: 
As agreed with @exekias , I'm adding in this PR some changes in Kubernetes module main document and in the majority of metricsets, including descriptions and configuration details for each one.
=> Cherry-pick #17636 to 7.8: Metricbeat Kubernetes module and metricsets docs proposal

CHANGELOG.asciidoc, libbeat/esleg/eslegclient/bulkapi.go, libbeat/esleg/eslegclient/bulkapi_mock_test.go, metricbeat/metricbeat.yml, x-pack/elastic-agent/CHANGELOG.asciidoc, x-pack/elastic-agent/pkg/agent/application/decorators.go, x-pack/elastic-agent/pkg/agent/application/decorators_test.go, x-pack/elastic-agent/pkg/agent/application/introspect_output_cmd.go, x-pack/elastic-agent/pkg/agent/application/local_mode.go, x-pack/elastic-agent/pkg/agent/application/managed_mode.go
To make sure we use the v2 templates we must send on bulk request the
params `prefer_v2_templates=true` if not it will default to v1 and will
not try to use the v2 template at all.
Reference: #17809
-
=> [Elastic Agent] Add params `prefer_v2_templates=true` on the ES output

dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl, dev-tools/packaging/templates/docker/docker-entrypoint.elastic-agent.tmpl
Moves yum install of epel-release and jq to the docker file and not something that is done on first start of the docker container.
So on startup is faster and so it doesn't need access to the yum repo, in closed environment there might not be access to yum.
- Closes #18345
=> Move yum install of epel-release and jq to the docker file

auditbeat/auditbeat.docker.yml, filebeat/filebeat.docker.yml, heartbeat/heartbeat.docker.yml, journalbeat/journalbeat.docker.yml, libbeat/_meta/config/default.docker.yml.tmpl, metricbeat/metricbeat.docker.yml, packetbeat/packetbeat.docker.yml, x-pack/auditbeat/auditbeat.docker.yml, x-pack/filebeat/filebeat.docker.yml, x-pack/metricbeat/metricbeat.docker.yml
Backports #18218 to 7.8 branch.
=> [7.8][docs] Backport: Prettify processor snippet in docker yml files (#18218)

filebeat/docs/modules/googlecloud.asciidoc, x-pack/filebeat/module/googlecloud/_meta/docs.asciidoc
Fixes typo in example configs.
=> [docs] Fix typo in googlecloud examples

CHANGELOG.next.asciidoc
This PR is to add missing changelog for PR elastic/beats#18398 .
=> Add changelog for PR 18398

libbeat/docs/shared-systemd.asciidoc
Backports #18423 to 7.x branch.
=> [7.x][docs] Backport: Use beatname_pkg variable to resolve package name (#18423)

x-pack/elastic-agent/CHANGELOG.asciidoc, x-pack/elastic-agent/pkg/agent/application/decorators.go, x-pack/elastic-agent/pkg/agent/application/decorators_test.go, x-pack/elastic-agent/pkg/agent/application/introspect_output_cmd.go, x-pack/elastic-agent/pkg/agent/application/local_mode.go, x-pack/elastic-agent/pkg/agent/application/managed_mode.go
Cherry-pick of PR #18318 to 7.x branch. Original message: 
To make sure we use the v2 templates we must send on bulk request the
params `prefer_v2_templates=true` if not it will default to v1 and will
not try to use the v2 template at all.
Reference: elastic/beats#17809
-
=> Cherry-pick #18318 to 7.x: [Elastic Agent] Add params `prefer_v2_templates=true` on the ES output

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
DO NOT MERGE UNTIL RELEASE DAY.
=> Bump docs version for 6.8.9

x-pack/elastic-agent/pkg/agent/application/fleet_acker.go
Cherry-pick of PR #18396 to 7.8 branch. Original message: 
Small typo in the ACK message
Fixes: #18145
-
=> Cherry-pick #18396 to 7.8: [Elastic Agent] fix a typo in the ACK message.

x-pack/elastic-agent/pkg/agent/application/fleet_acker.go
Small typo in the ACK message
Fixes: #18145
(cherry picked from commit 5b1927eb5b47bde13b8fe744f10eba512d6c03ef)
-
=> [Elastic Agent] fix a typo in the ACK message. (#18396)

libbeat/docs/communitybeats.asciidoc
Cherry-pick of PR #18470 to 7.8 branch. Original message: 
-
=> Cherry-pick #18470 to 7.8: Update communitybeats.asciidoc

libbeat/docs/communitybeats.asciidoc
Cherry-pick of PR #18470 to 7.x branch. Original message: 
-
=> Cherry-pick #18470 to 7.x: Update communitybeats.asciidoc

libbeat/esleg/eslegclient/bulkapi.go, libbeat/esleg/eslegclient/bulkapi_mock_test.go
Cherry-pick of PR #18393 to 7.x branch. Original message: 
This PR add additionnal test over the usager of the `parameters` options
in the Elasticsearch output:
- When preconfigured params are set without local params
- When preconfigured params are set with local params
- When no preconfigured params are configured but local are.
- When no preconfigured or local params are set.
The merge is also done close to the actual calls and will not be
executed if anything fails before the bulk request.
The test assertion is now more solid and take into consideration any
errors.
See discussion in #18318 and #18326
-
=> Cherry-pick #18393 to 7.x: [Libbeat] Add more complete tests for opt parameters in ES output

x-pack/filebeat/input/s3/input.go
This is a very small fix for adding error message into log message and also fix a small typo.
=> [Filebeat] Add error message into log and fix a typo

x-pack/filebeat/input/s3/input.go
Cherry-pick of PR #18543 to 7.8 branch. Original message: 
This is a very small fix for adding error message into log message and also fix a small typo.
=> Cherry-pick #18543 to 7.8: [Filebeat] Add error message into log and fix a typo

x-pack/filebeat/input/s3/input.go
Cherry-pick of PR #18543 to 7.x branch. Original message: 
This is a very small fix for adding error message into log message and also fix a small typo.
=> Cherry-pick #18543 to 7.x: [Filebeat] Add error message into log and fix a typo

x-pack/filebeat/input/s3/input.go
Cherry-pick of PR #18543 to 7.7 branch. Original message: 
This is a very small fix for adding error message into log message and also fix a small typo.
=> Cherry-pick #18543 to 7.7: [Filebeat] Add error message into log and fix a typo

.github/comment.yml, .github/relabel.yml
We are updating the descriptors of the two bots that we use to provide support for pull requests alongside to issues.
- probot-require-label: adds the `needs_team` label when an issue/PR does not contain a `Team:*` label
- probot-add-comment: adds a comment in an issue/PR if the `needs_team` label is present (used in combination with above)
- probot-add-comment: adds a comment in an issue if the `request-discuss` label is present
We want to automate some parts of the triage process, making it easy to identify what to work on next.
~~- [ ] I have made corresponding change to the default …
=> Update bots descriptors to include pull request support

Jenkinsfile
MacOSX workers do require some cleanup after using them
Keep our infra in a good shape
=> ci: clean workspaces in static workers

CHANGELOG.next.asciidoc
Add missing changelog entry for #12905
=> Add changelog entry for #12905

Jenkinsfile
- ci: clean workspaces in static workers (#18606)
=> Cherry-pick #18606 to 7.x: [ci] clean workspaces in static workers

libbeat/esleg/eslegclient/bulkapi.go, libbeat/esleg/eslegclient/bulkapi_mock_test.go
Cherry-pick of PR #18393 to 7.8 branch. Original message: 
This PR add additionnal test over the usager of the `parameters` options
in the Elasticsearch output:
- When preconfigured params are set without local params
- When preconfigured params are set with local params
- When no preconfigured params are configured but local are.
- When no preconfigured or local params are set.
The merge is also done close to the actual calls and will not be
executed if anything fails before the bulk request.
The test assertion is now more solid and take into consideration any
errors.
See discussion in #18318 and #18326
-
=> Cherry-pick #18393 to 7.8: [Libbeat] Add more complete tests for opt parameters in ES output

.github/paths-labeller.yml
We are using botelastic (a probot) to do it on every PR submission affecting the paths defined in the descriptor
PR triage will be easier, with less manual work
=> chore: add Team Ingest Management label to PRs automatically

.github/paths-labeller.yml
It fixes the name of the labels, as I unescaped whitespaces wrong
=> Fix label names

libbeat/outputs/logstash/docs/logstash.asciidoc
Fixes broken links in https://github.com/elastic/stack-docs/pull/1099
=> [docs] Update links to the Logstash getting started

CHANGELOG.next.asciidoc, libbeat/esleg/eslegclient/connection.go
Cherry-pick of PR #18607 to 7.8 branch. Original message:
=> Cherry-pick #18607 to 7.8: Add TLS dialer to Kerberos transport as well

CHANGELOG.next.asciidoc, libbeat/esleg/eslegclient/connection.go
Cherry-pick of PR #18607 to 7.x branch. Original message:
=> Cherry-pick #18607 to 7.x: Add TLS dialer to Kerberos transport as well

x-pack/metricbeat/module/googlecloud/stackdriver/_meta/docs.asciidoc
This PR is to update stackdriver metricset documentation to include the full list of metric types and aggregation aligners.
=> [Metricbeat] Update googlecloud stackdriver metricset documentation

x-pack/filebeat/input/s3/input.go
Cherry-pick of PR #18824 to 7.x branch. Original message: 
This PR is to improve error messages in S3 input Filebeat to capture more information such as the S3 bucket name and log file name.
=> Cherry-pick #18824 to 7.x: Improve error messages in s3 input

x-pack/filebeat/input/s3/input.go
Cherry-pick of PR #18824 to 7.8 branch. Original message: 
This PR is to improve error messages in S3 input Filebeat to capture more information such as the S3 bucket name and log file name.
=> Cherry-pick #18824 to 7.8: Improve error messages in s3 input

x-pack/filebeat/input/s3/input.go
Cherry-pick of PR #18824 to 7.7 branch. Original message: 
This PR is to improve error messages in S3 input Filebeat to capture more information such as the S3 bucket name and log file name.
=> Cherry-pick #18824 to 7.7: Improve error messages in s3 input

testing/environments/latest.yml
Update latest testing environment to the 7.7.0 release.
=> Update latest.yml testing env to 7.7.0

.ci/jobs/build-it-docker-images.yml
Fix the YAML file for the job definition.
JJBB cannot process the file because has two file delimiters
```
16:28:27 yaml.composer.ComposerError: expected a single document in the stream
16:28:27 but found another document
16:28:27   in ".ci/jobs/package-registry.yml", line 2, column 1
16:28:27 Build step 'Execute shell' marked build as failure
```
- ~[ ] My code follows the style guidelines of this project~
- ~[ ] I have commented my code, particularly in hard-to-understand areas~
- ~[ ] I have added tests that prove my fix is effective or that my feature works~
- ~[ ] I have added an entry in `CHANGELOG.next.asciidoc` or …
=> fix: rename yaml file and remove extra separator

filebeat/docs/modules/auditd.asciidoc, filebeat/module/auditd/_meta/docs.asciidoc
- [WIP] Clarify capabilities of the Filebeat auditd module (#17068)
=> [7.x] Clarify capabilities of the Filebeat auditd module (#17068)

filebeat/docs/modules/auditd.asciidoc, filebeat/module/auditd/_meta/docs.asciidoc
- [WIP] Clarify capabilities of the Filebeat auditd module (#17068)
=> [7.7] Clarify capabilities of the Filebeat auditd module (#17068)

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
DO NOT MERGE UNTIL RELEASE DAY.
=> Bump docs version for 6.8.10

x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
This adds some configuration examples to the documentation for the Filebeat httpjson input
and adds some more detail to the configuration options.
Good reference docs are important for understanding how to use the input.
=> [Filebeat] Add details/examples to the httpjson docs

CHANGELOG.next.asciidoc
This is just a PR to fix changelog.
=> Move Tomcat dashboard changelog from breaking change to added change

CHANGELOG.asciidoc
Technical edits driven by the need to:
- Make descriptions consistent
- Describe the affect on the end user (when possible), instead of the code change
- Avoid talking about implementation details unless users need to know about them
- Be succinct, but don't leave out important words
- Use consistent capitalization and formatting for names (modules, metricsets, filesets, etc)
- Include articles (a, an, the) if leaving them out makes the sentence choppy
(Capturing this list here ^^ so I can look back on it when I write guidelines.)
=> Edit changelog for 7.7.1

libbeat/common/kubernetes/util.go
Cherry-pick of PR elastic/beats#18964 to 7.x branch. Original message: 
This PR fixes https://github.com/elastic/beats/issues/18961, by implementing client configuration creation on Beats side in order to avoid the annoying warning logs of `client-go`. 
This happens by replacing https://github.com/elastic/beats/blob/0ef20cc5cbe2142650c7cf21c2aeacc401adc9bc/libbeat/common/kubernetes/util.go#L52 call with a call to a method of ours which implements the same logic without the logging.
In order to avoid the annoying warning logs of `client-go`.
Closes https://github.com/elastic/beats/issues/18961
=> Cherry-pick #18964 to 7.x: Flatten BuildConfigFromFlags to avoid warning logs on k8s client creation

Jenkinsfile
- [CI] Set MODULE per relevant stage (#18777)
=> Cherry-pick #18777 to 7.x: [CI] Set MODULE per relevant stage

filebeat/docs/inputs/input-kafka.asciidoc
- Add compatibility info (#18929)
=> [7.x] Add compatibility info (#18929)

x-pack/elastic-agent/docs/elastic-agent.asciidoc
Cherry-pick of PR #19030 to 7.8 branch. Original message:
Introduces basic elastic agent related documentation
For user to know how to use and what to expect from agent
Fixes: #18720 
Fixes: #18721
=> Cherry-pick #19030 to 7.8:  Basic Elastic Agent documentation 

x-pack/elastic-agent/docs/elastic-agent.asciidoc
Cherry-pick of PR #19030 to 7.x branch. Original message:
Introduces basic elastic agent related documentation
For user to know how to use and what to expect from agent
Fixes: #18720 
Fixes: #18721
=> Cherry-pick #19030 to 7.x: Basic Elastic Agent documentation 

x-pack/elastic-agent/docs/elastic-agent-command-line.asciidoc, x-pack/elastic-agent/docs/elastic-agent-configuration-example.asciidoc, x-pack/elastic-agent/docs/elastic-agent-configuration.asciidoc, x-pack/elastic-agent/docs/elastic-agent.asciidoc, x-pack/elastic-agent/docs/install-elastic-agent.asciidoc, x-pack/elastic-agent/docs/run-elastic-agent.asciidoc
- Edit Elastic Agent docs (#19146)
=> [7.x] Edit Elastic Agent docs (#19146)

x-pack/elastic-agent/docs/elastic-agent-command-line.asciidoc, x-pack/elastic-agent/docs/elastic-agent-configuration-example.asciidoc, x-pack/elastic-agent/docs/elastic-agent-configuration.asciidoc, x-pack/elastic-agent/docs/elastic-agent.asciidoc, x-pack/elastic-agent/docs/install-elastic-agent.asciidoc, x-pack/elastic-agent/docs/run-elastic-agent.asciidoc
Backports the following commits to 7.8:
- Edit Elastic Agent docs (#19146)
=> [7.8] Edit Elastic Agent docs (#19146)

.ci/jobs/beats-windows-mbp.yml, .ci/windows.groovy
- Fix the JJBB
- Run the windows pipeline even when there are only docs
Help to run the CI pipeline always without the need of need a commit with changes.
=> [jjbb]: fix jjbb and run always

filebeat/beater/crawler.go
Cherry-pick of PR #19219 to 7.8 branch. Original message: 
None
=> Cherry-pick #19219 to 7.8: Fix message formatting when starting filebeat input

filebeat/docs/modules/haproxy.asciidoc, filebeat/module/haproxy/_meta/docs.asciidoc
=> Add tested versions to HAProxy module in Filebeat and Metricbeat

filebeat/beater/crawler.go
Cherry-pick of PR elastic/beats#19219 to 7.x branch. Original message: 
None
=> Cherry-pick #19219 to 7.x: Fix message formatting when starting filebeat input

filebeat/docs/modules/haproxy.asciidoc, filebeat/module/haproxy/_meta/docs.asciidoc
Cherry-pick of PR #19217 to 7.x branch. Original message: 
Closes elastic/beats#14793
=> Cherry-pick #19217 to 7.x: Add tested versions to HAProxy module in Filebeat and Metricbeat

.ci/build-docker-images.groovy, .ci/jobs/build-it-docker-images.yml
It allows using a branch/PR/tag/commit reference to build the docker images for ITs
In some cases we need to test changes in the pipeline this is the way to check the PR on regular pipelines.
- ~[ ] I have commented my code, particularly in hard-to-understand areas~
- ~[ ] I have added tests that prove my fix is effective or that my feature works~
- ~[ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-de veloper.next.asciidoc`.~
=> feat: allow to run it for other branches/PR/tags

x-pack/elastic-agent/docs/elastic-agent-command-line.asciidoc, x-pack/elastic-agent/docs/elastic-agent-configuration-example.asciidoc, x-pack/elastic-agent/docs/elastic-agent-configuration.asciidoc, x-pack/elastic-agent/docs/elastic-agent.asciidoc, x-pack/elastic-agent/docs/install-elastic-agent.asciidoc, x-pack/elastic-agent/docs/run-elastic-agent.asciidoc
- [DOCS] Fix problems in Elastic Agent docs found during doc testing (#19252)
=> [7.x] [DOCS] Fix problems in Elastic Agent docs found during doc testing (#19252)

x-pack/elastic-agent/docs/elastic-agent-command-line.asciidoc, x-pack/elastic-agent/docs/elastic-agent-configuration-example.asciidoc, x-pack/elastic-agent/docs/elastic-agent-configuration.asciidoc, x-pack/elastic-agent/docs/elastic-agent.asciidoc, x-pack/elastic-agent/docs/install-elastic-agent.asciidoc, x-pack/elastic-agent/docs/run-elastic-agent.asciidoc
Backports the following commits to 7.8:
- [DOCS] Fix problems in Elastic Agent docs found during doc testing (#19252)
=> [7.8] [DOCS] Fix problems in Elastic Agent docs found during doc testing (#19252)

CHANGELOG.next.asciidoc, journalbeat/reader/fields.go, journalbeat/reader/journal.go, journalbeat/reader/journal_test.go
Add ECS 1.5 fields to journalbeat.
- Closes https://github.com/elastic/beats/issues/18269
=> [Journalbeat] Add ECS fields to journalbeat

libbeat/docs/release-notes/breaking/breaking-7.8.asciidoc, libbeat/outputs/kafka/docs/kafka.asciidoc
This is a known issue in 7.7.1 and 7.8.0.
Related PR: https://github.com/elastic/beats/issues/19216
=> [DOCS] Describe known problem with kafka output

Jenkinsfile
Cherry-pick of PR #19256 to 7.x branch. Original message:
=> Cherry-pick #19256 to 7.x: Enable macOS tests

x-pack/elastic-agent/pkg/agent/application/fleet_gateway.go, x-pack/elastic-agent/pkg/kibana/client.go
This PR is interestingly simple, i love that. What this changes is some timeouts and retries in case something goes wrong. Only one file affected thanks to our modular design.
Tested with nicolases branch from this PR https://github.com/elastic/kibana/pull/68922
Updates flow
=> [Ingest Manager] Agent longpoll

CHANGELOG.next.asciidoc, x-pack/functionbeat/provider/aws/aws/transformer/transformer.go, x-pack/functionbeat/provider/aws/aws/transformer/transformer_test.go, x-pack/functionbeat/provider/gcp/gcp/transformer.go
Adds ECS categorization fields and some basic ECS fields that were missing.
- Closes https://github.com/elastic/beats/issues/18268
=> [Functionbeat] Add ECS categorization fields

libbeat/docs/release-notes/breaking/breaking-7.8.asciidoc, libbeat/outputs/kafka/docs/kafka.asciidoc
Changed as requested by @ChrsMark and @urso.
This probably warrants a terminology discussion, though. My main case for using "problem" over "issue" is translation. The word "problem" has fewer meanings in English. But since "issue" maps to what's used in GitHub, maybe it's a better choice.
Anyhow, here you go!
=> [DOCS] Minor change to wording for known issues

libbeat/docs/release-notes/breaking/breaking-7.7.asciidoc, libbeat/outputs/kafka/docs/kafka.asciidoc
Backports #19259 to 7.7 plus changes the version info.
=> [7.7] [DOCS] Describe known issue with kafka output

Jenkinsfile
Add some docs regarding what are the standards in the agents/labels convention to be used when setting a new stage.
Being explicit regarding the CI infrastructure.
=> [CI] Docs the labels/agents

metricbeat/docs/modules/kubernetes.asciidoc, metricbeat/module/kubernetes/_meta/docs.asciidoc
Updates compatibility note for Kubernetes module based on the versions we currently test on the CI at https://github.com/elastic/beats/blob/d5e9623c25c71fee4924f33633319ed462845c13/Jenkinsfile#L777
=> Update compatibility note for Kubernetes module

go.sum, x-pack/elastic-agent/CHANGELOG.asciidoc
Adds a changelog entry for PR #19360 
To make change more visible
=> [Ingest Manager]  Missing Changelog for 19360 - input.type change

go.sum, x-pack/elastic-agent/pkg/fleetapi/checkin_cmd.go
removes debug messages
to not leak any sensitive information
=> [Ingest Manager] Removed unwanted Println's

libbeat/cmd/instance/beat.go, libbeat/docs/command-reference.asciidoc, libbeat/docs/shared-docker.asciidoc, libbeat/docs/shared-license-statement.asciidoc
=> [7.x][DOCS] Fixes license management link

libbeat/docs/release-notes/breaking/breaking-7.7.asciidoc, libbeat/docs/shared-systemd.asciidoc
Backports #19224 to 7.x branch.
=> [7.x][docs] Add breaking change note about logging (#19224)

libbeat/docs/release-notes/breaking/breaking-7.7.asciidoc, libbeat/docs/shared-systemd.asciidoc
Backports #19224 to 7.8 branch.
=> [7.8][docs] Add breaking change note about logging (#19224)

libbeat/docs/release-notes/breaking/breaking-7.7.asciidoc, libbeat/docs/shared-systemd.asciidoc
Backports #19224 to 7.7 branch.
=> [7.7][docs] Add breaking change note about logging (#19224)

x-pack/filebeat/module/checkpoint/firewall/ingest/pipeline.yml
A new argument has been added to the set processor to replace null check values, this PR only replaces if conditions with this new argument, no new feature or changes are introduced in this PR.
Removing if conditions reduces script compilations during ingestion.
All nosetests passing after change
Relates to #19407
=> updated checkpoint module to use new nullcheck in set processors

filebeat/module/kibana/log/ingest/pipeline.yml
A new argument has been added to the set processor to replace null check values, this PR only replaces if conditions with this new argument, no new feature or changes are introduced in this PR.
Removing if conditions reduces script compilations during ingestion.
All nosetests passing after change
Relates to #19407
=> updated kibana module to use new nullcheck in set processors

filebeat/module/system/auth/ingest/pipeline.yml
A new argument has been added to the set processor to replace null check values, this PR only replaces if conditions with this new argument, no new feature or changes are introduced in this PR.
Removing if conditions reduces script compilations during ingestion.
All nosetests passing after change
Relates to #19407
=> updated system module to use new nullcheck in set processors

x-pack/filebeat/module/aws/cloudtrail/ingest/pipeline.yml, x-pack/filebeat/module/aws/elb/ingest/pipeline.yml, x-pack/filebeat/module/aws/s3access/ingest/pipeline.yml, x-pack/filebeat/module/aws/vpcflow/ingest/pipeline.yml
A new argument has been added to the set processor to replace null check values, this PR only replaces if conditions with this new argument, no new feature or changes are introduced in this PR.
Removing if conditions reduces script compilations during ingestion.
All nosetests passing after change
Relates to #19407
=> updated aws module to use new nullcheck in set processors

libbeat/docs/command-reference.asciidoc, libbeat/docs/shared-docker.asciidoc, libbeat/docs/shared-license-statement.asciidoc, libbeat/docs/step-configure-credentials.asciidoc
=> [7.8][DOCS] Fixes license management link

dev-tools/module_committers
- [dev-tools] Script to find recent top committers for a module (#19053)
=> [7.x] [dev-tools] Script to find recent top committers for a module (#19053)

x-pack/elastic-agent/CHANGELOG.asciidoc
Add entry into changelog for breaking the fleet.yml structure.
To document that it was a breaking change.
=> [Elastic Agent] Add changelog for breaking change in fleet.yml

x-pack/elastic-agent/CHANGELOG.asciidoc
Cherry-pick of PR #19495 to 7.x branch. Original message: 
Add entry into changelog for breaking the fleet.yml structure.
To document that it was a breaking change.
=> Cherry-pick #19495 to 7.x: [Elastic Agent] Add changelog for breaking change in fleet.yml

libbeat/cmd/instance/beat.go, libbeat/docs/command-reference.asciidoc, libbeat/docs/shared-docker.asciidoc, libbeat/docs/shared-license-statement.asciidoc, libbeat/docs/step-configure-credentials.asciidoc
=> [7.7][DOCS] Fixes license management link

libbeat/cmd/instance/beat.go, libbeat/docs/command-reference.asciidoc, libbeat/docs/shared-docker.asciidoc, libbeat/docs/shared-license-statement.asciidoc, libbeat/docs/step-configure-credentials.asciidoc
=> [7.6][DOCS] Fixes license management link

libbeat/docs/command-reference.asciidoc, libbeat/docs/security/securing-beats.asciidoc, libbeat/docs/shared-docker.asciidoc, libbeat/docs/shared-license-statement.asciidoc, libbeat/docs/step-configure-credentials.asciidoc
=> [7.5][DOCS] Fixes license management link

.ci/packaging.groovy
* Change to use withMageEnv
* Disable upstream trigger on PRs
* Disable macOS sign packages is a bottleneck
This PR fixes the queue-boom occasioned by the upstream trigger on PRs.
=> ci: disable upstream trigger on PRs for the packaging job

.ci/jobs/packaging.yml
=> ci: enable packaging job

CHANGELOG.next.asciidoc
#19423 I consider `aws_partition` as a new feature instead of a bug fix. This PR is to fix the changelog for this PR.
=> change #19423 changelog from bug to add

.ci/packaging.groovy
it puts a filter in place to avoid allocate and agent if the build is not triggered by a comment or a user.
it avoids waste resources.
=> ci: trigger packages builds only manually or with a comment

.ci/jobs/apm-beats-update.yml, .ci/jobs/beats.yml, .ci/jobs/build-it-docker-images.yml, .ci/jobs/defaults.yml, .ci/jobs/packaging.yml
* Remove periodic repos scan fro multibranch jobs
* Filter branches to detect for apm-server-update, beats new job, and package jobs `'(master|7\.[x789]|8\.\d+|PR-.*)'`
* Skip initial build on apm-server-update and package jobs
* Ignore tags older than 30 days on apm-server-update and package jobs (the flag is inverted in JJB)
* Enable SCM triggering on apm-server-update to allow registry the comment trigger.
* Remove Github initial notification on package job
These changes will reduce the number os GitHub API calls, also will limit the branches build to the proper ones, tags, and PRs.
- …
=> ci: some jjbb improvements

.ci/packaging.groovy
* Allows the packaging job to be triggered by an upstream job.
This will trigger and run the packaging job on merges on the principal branches.
-
=> ci: enable upstream triggering on the packaging job

journalbeat/pkg/journalread/reader.go
- Fix
Remove dependency in journalbeat from `filebeat/input/v2`
The dependency has been introduced by accident and should be removed.
=> fix journalbeat depending on filebeat v2

winlogbeat/docs/winlogbeat-options.asciidoc
While looking up some config info for winlogbeat, I came across this *whitelist/blacklist* section.
I submit this PR because black lives matter, racism is evil, and we should all help out to make the world a tiny bit better for our brothers and sisters of color ✊🏾
Updates wording of the documentation.
Because it is hurtful to people.
-
=> Updated wording to avoid use of racially-charged language

.backportrc.json
It adds the configuration to use [backport](https://www.npmjs.com/package/backport)  tool to easy backport changes between branches.
With this tool backport a PR or commit is a matter of 2 min. The following PRs are examples of the PR created with backport tool:
https://github.com/elastic/beats/pulls?q=is%3Apr+author%3A%40me+is%3Aclosed+label%3Abackport
To backport a PR you only have to [install and configure backport](https://www.npmjs.com/package/backport#install) and execute the following command
```
backport --pr PR_NUMBER  --label "Team:Automation"
```
or
```
backport --sha COMMIT_SHA1  --label "Team:Automation"
```
- ~~[ ] I have made …
=> ci: add backport tool configuration

.ci/packaging.groovy
It moves the deleteDir step before of the mage installation.
In the current position, the deleteDir delete the mage installation made by withMageEnv
-
=> ci: do not delete mage installation

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc
=> Close changelog for 6.8.11

Makefile, dev-tools/mage/dashboard.go
Cherry-pick of PR #19557 to 7.x branch. Original message: 
None
=> Cherry-pick #19557 to 7.x: Remove outdated references to vendor folder

testing/environments/latest.yml, testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
=> Update testing env 6.8.11

filebeat/inputsource/common/listener.go
Cherry-pick of PR #19515 to 7.x branch. Original message: 
- Enhancement
Export a Run method from the common listener inputsource. The Run method supports context.Context for cancellation, in addition to the Stop call.
Network based inputs using the v2 API require Run to be implemented.
~~- [ ] I have commented my code, particularly in hard-to-understand areas~~~~
-
=> Cherry-pick #19515 to 7.x: Export Run from common listener inputsource

metricbeat/module/prometheus/_meta/config.epr.yml
This PR adds `config.epr.yml` for package migration of Prometheus module.
Related to https://github.com/elastic/integrations/pull/114
=> Add config.epr for Prometheus module

.ci/jobs/apm-beats-update.yml, .ci/jobs/beats.yml, .ci/jobs/packaging.yml
* enable the multibranch pipeline job that it is in the beats repo
* add a filter to create jobs also for tags
This move all the pipeline job configurations to the beats repo.
-
=> feat: move the multibranch pipeline job to the beats repo

x-pack/elastic-agent/pkg/agent/transpiler/rules_test.go
Fixes test from config change. 
Green builds
=> [Ingest Manager] Fix serialization test

x-pack/elastic-agent/pkg/agent/application/enroll_cmd_test.go, x-pack/elastic-agent/pkg/agent/operation/common_test.go, x-pack/elastic-agent/pkg/reporter/log/reporter_test.go
Some tests are invalid, this PR fixes them
=> [Ingest Manager] Fixed tests across agent

x-pack/elastic-agent/pkg/core/server/server_test.go
Cherry-pick of PR #19894 to 7.x branch. Original message: 
Fixes test failure from data race issue.
So all tests pass.
=> Cherry-pick #19894 to 7.x: [Elastic Agent] Fix data race issue in tests.

x-pack/elastic-agent/pkg/agent/application/action_store_test.go
Cherry-pick of PR #19920 to 7.x branch. Original message: 
See https://github.com/elastic/beats/issues/19919
-
=> Cherry-pick #19920 to 7.x: [Elastic Agent] Skip windows TestActionStore failure

dev-tools/packaging/packages.yml, dev-tools/packaging/templates/linux/systemd.unit.tmpl, dev-tools/packaging/templates/windows/install-service.ps1.tmpl, libbeat/logp/configure/logging.go, x-pack/elastic-agent/pkg/agent/application/global_config.go, x-pack/elastic-agent/pkg/agent/application/info/agent_id.go, x-pack/elastic-agent/pkg/agent/application/paths/paths.go, x-pack/elastic-agent/pkg/agent/cmd/common.go
Fixes Elastic Agent installation from .deb and .rpm.
So installing Elastic Agent from packaging on Ubuntu and CentOS works.
- Relates #19946
=> [Elastic Agent] Fix RPM and DEB packaging for Elastic Agent

dev-tools/packaging/packages.yml, dev-tools/packaging/templates/linux/systemd.unit.tmpl, dev-tools/packaging/templates/windows/install-service.ps1.tmpl, libbeat/logp/configure/logging.go, x-pack/elastic-agent/pkg/agent/application/global_config.go, x-pack/elastic-agent/pkg/agent/application/info/agent_id.go, x-pack/elastic-agent/pkg/agent/application/paths/paths.go, x-pack/elastic-agent/pkg/agent/cmd/common.go
Cherry-pick of PR #19959 to 7.x branch. Original message: 
Fixes Elastic Agent installation from .deb and .rpm.
So installing Elastic Agent from packaging on Ubuntu and CentOS works.
- Relates #19946
=> Cherry-pick #19959 to 7.x: [Elastic Agent] Fix RPM and DEB packaging for Elastic Agent

dev-tools/packaging/packages.yml, dev-tools/packaging/templates/linux/systemd.unit.tmpl, dev-tools/packaging/templates/windows/install-service.ps1.tmpl, libbeat/logp/configure/logging.go, x-pack/elastic-agent/pkg/agent/application/global_config.go, x-pack/elastic-agent/pkg/agent/application/info/agent_id.go, x-pack/elastic-agent/pkg/agent/application/paths/paths.go, x-pack/elastic-agent/pkg/agent/cmd/common.go
Cherry-pick of PR #19959 to 7.9 branch. Original message: 
Fixes Elastic Agent installation from .deb and .rpm.
So installing Elastic Agent from packaging on Ubuntu and CentOS works.
- Relates #19946
=> Cherry-pick #19959 to 7.9: [Elastic Agent] Fix RPM and DEB packaging for Elastic Agent

.backportrc.json
=> add 7.9 to .backportrc.json

testing/environments/latest.yml, testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
Update test environments versions.
-
=> test: Update testing env 7.8.1

CHANGELOG.next.asciidoc, metricbeat/module/mysql/_meta/kibana/7/dashboard/Metricbeat-mysql-overview.json
Update MySQL dashboard with the metrics merged in https://github.com/elastic/beats/pull/19844
- Implements https://github.com/elastic/beats/issues/16955
=> [Metricbeat] Update MySQL dashboard

Jenkinsfile
- [CI] fix MODULE variable cornercases (#19985)
=> Cherry-pick to 7.9: [CI] fix MODULE variable cornercases (#19985)

Jenkinsfile
- [CI] fix MODULE variable cornercases (#19985)
=> Cherry-pick to 7.x: [CI] fix MODULE variable cornercases (#19985)

Jenkinsfile
- [CI] run everything for branches/tags (#20057)
=> Cherry-pick to 7.x: [CI] run everything for branches/tags (#20057)

Jenkinsfile
- [CI] run everything for branches/tags (#20057)
=> Cherry-pick to 7.9: [CI] run everything for branches/tags (#20057)

filebeat/docs/filebeat-options.asciidoc, x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc, x-pack/filebeat/docs/inputs/input-awscloudwatch.asciidoc
This PR is to fix mistake introduced in https://github.com/elastic/beats/pull/19973.
=> Fix Filebeat input order and title name

.ci/scripts/report-codecov.sh, Jenkinsfile
- [CI]: retry with sleep (#20065)
=> Cherry-pick to 7.9: [CI]: retry with sleep (#20065)

auditbeat/docs/configuring-howto.asciidoc, filebeat/docs/configuring-howto.asciidoc, heartbeat/docs/configuring-howto.asciidoc, journalbeat/docs/configuring-howto.asciidoc, libbeat/docs/shared-instrumentation.asciidoc, metricbeat/docs/configuring-howto.asciidoc, packetbeat/docs/configuring-howto.asciidoc, winlogbeat/docs/configuring-howto.asciidoc, x-pack/functionbeat/docs/configuring-howto.asciidoc
- docs: Instrumentation configuration (#19765)
=> Cherry-pick to 7.x: docs: Instrumentation configuration (#19765)

auditbeat/docs/configuring-howto.asciidoc, filebeat/docs/configuring-howto.asciidoc, heartbeat/docs/configuring-howto.asciidoc, journalbeat/docs/configuring-howto.asciidoc, libbeat/docs/shared-instrumentation.asciidoc, metricbeat/docs/configuring-howto.asciidoc, packetbeat/docs/configuring-howto.asciidoc, winlogbeat/docs/configuring-howto.asciidoc, x-pack/functionbeat/docs/configuring-howto.asciidoc
- docs: Instrumentation configuration (#19765)
=> Cherry-pick to 7.9: docs: Instrumentation configuration (#19765)

auditbeat/docs/running-on-kubernetes.asciidoc, filebeat/docs/running-on-kubernetes.asciidoc, metricbeat/docs/running-on-kubernetes.asciidoc
- [docs] Add ECK doc links to Beats (#19966)
=> Cherry-pick to 7.x: [docs] Add ECK doc links to Beats (#19966)

x-pack/elastic-agent/CHANGELOG.asciidoc, x-pack/elastic-agent/pkg/agent/operation/monitoring.go, x-pack/elastic-agent/pkg/agent/program/testdata/constraints_config-filebeat.yml, x-pack/elastic-agent/pkg/agent/program/testdata/enabled_output_true-filebeat.yml, x-pack/elastic-agent/pkg/agent/program/testdata/enabled_true-filebeat.yml, x-pack/elastic-agent/pkg/agent/program/testdata/single_config-filebeat.yml, x-pack/elastic-agent/pkg/agent/program/testdata/single_config-metricbeat.yml, x-pack/elastic-agent/pkg/agent/transpiler/rules.go
Cherry-pick of PR #20076 to 7.x branch. Original message: 
Adds `event.dataset` to match the same as `dataset.name` from the event. This is done on all configurations, even the sidecar monitoring beats.
So published events do not prevent other features from working in Kibana and ML.
Run `elastic-agent` ensure that all events published to elasticsearch have `event.dataset` that matches the `dataset.name`.
- Closes #20009
=> Cherry-pick #20076 to 7.x: [Elastic Agent] Add event.dataset to all events

x-pack/elastic-agent/docs/elastic-agent.asciidoc, x-pack/elastic-agent/docs/stop-elastic-agent.asciidoc
Adds info about how to stop Elastic Agent.
=> [docs] Add topic about stopping Elastic Agent

x-pack/elastic-agent/docs/elastic-agent.asciidoc, x-pack/elastic-agent/docs/stop-elastic-agent.asciidoc
- [docs] Add topic about stopping Elastic Agent (#19971)
=> Cherry-pick to 7.9: [docs] Add topic about stopping Elastic Agent (#19971)

x-pack/elastic-agent/docs/elastic-agent.asciidoc, x-pack/elastic-agent/docs/stop-elastic-agent.asciidoc
Backports the following commits to 7.8:
- [docs] Add topic about stopping Elastic Agent (#19971)
=> Cherry-pick to 7.8: [docs] Add topic about stopping Elastic Agent (#19971)

x-pack/elastic-agent/docs/elastic-agent.asciidoc, x-pack/elastic-agent/docs/stop-elastic-agent.asciidoc
- [docs] Add topic about stopping Elastic Agent (#19971)
=> Cherry-pick to 7.x: [docs] Add topic about stopping Elastic Agent (#19971)

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 7.8.1. Merge before the final Release build.
=> docs: update docs versions 7.8.1

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, metricbeat/docker-compose.yml, metricbeat/module/logstash/docker-compose.yml, testing/environments/latest.yml, testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml, x-pack/metricbeat/docker-compose.yml
=> test: Update test environments

.ci/apm-beats-update.groovy
Fixes the pipeline errors
```
10:48:49  WorkflowScript: 33: Unknown stage section "stage". Starting with version 0.5, steps in a stage must be in a ‘steps’ block. @ line 33, column 5.
10:48:49         stage('Filter build') {
10:48:49         ^
10:48:49  
10:48:49  WorkflowScript: 33: Multiple occurrences of the stage section @ line 33, column 5.
10:48:49         stage('Filter build') {
```
Otherwise it won't be built.
=> [CI] fix apm-beats-update.groovy pipeline with missing stages

filebeat/docs/modules/gsuite.asciidoc, x-pack/filebeat/filebeat.reference.yml, x-pack/filebeat/module/gsuite/_meta/config.yml, x-pack/filebeat/module/gsuite/_meta/docs.asciidoc, x-pack/filebeat/modules.d/gsuite.yml.disabled
Cherry-pick of PR #19981 to 7.9 branch. Original message: 
After reading Gsuite docs for 7.9 I thought some things might benefit of a bit more info.
Docs need to be as clear as possible for people who sets up the module.
=> Cherry-pick #19981 to 7.9: [Filebeat][Gsuite] Make GSuite docs more clear

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc, libbeat/tests/system/requirements.txt
this should be merge before the release
=> docs: update docs version 6.8.11

.ci/apm-beats-update.groovy
- [CI] fix apm-beats-update.groovy pipeline with missing stages (#20238)
=> Cherry-pick to 7.x: [CI] fix apm-beats-update.groovy pipeline with missing stages (#20238)

dev-tools/mage/dockerbuilder.go, go.sum
Fix building docker images, error sometimes cause docker to end packaging prematurely.
=> [Ingest Manager] Fix docker build for agent

.ci/apm-beats-update.groovy, .ci/packaging.groovy
Use the production MBP upstream -> https://github.com/elastic/beats/blob/master/.ci/jobs/beats.yml#L3
Otherwise the pipelines won't be kicked out
=> [CI] Change upstream reference

.ci/apm-beats-update.groovy, .ci/packaging.groovy
- [CI] Change upstream reference (#20296)
=> Cherry-pick to 7.9: [CI] Change upstream reference (#20296)

CHANGELOG.asciidoc, libbeat/docs/release.asciidoc
Sync the changelog between branches
All branches should have a changelog in sync each other
- Relates https://github.com/elastic/beats/issues/19884
=> docs: update changelog on master 7.x

.ci/apm-beats-update.groovy, .ci/packaging.groovy
- [CI] Change upstream reference (#20296)
=> Cherry-pick to 7.x: [CI] Change upstream reference (#20296)

journalbeat/Makefile, journalbeat/input/input.go, journalbeat/tests/system/input/test.registry, journalbeat/tests/system/test_base.py, libbeat/tests/system/beat/beat.py
Cherry-pick of PR elastic/beats#20140 to 7.x branch. Original message:
=> Cherry-pick #20140 to 7.x: Enable and fix Journalbeat integration tests

journalbeat/Makefile, journalbeat/input/input.go, journalbeat/tests/system/input/test.registry, journalbeat/tests/system/test_base.py, libbeat/tests/system/beat/beat.py
Cherry-pick of PR #20140 to 7.9 branch. Original message:
=> Cherry-pick #20140 to 7.9: Enable and fix Journalbeat integration tests

.ci/apm-beats-update.groovy
- [CI] fix apm-beats-update.groovy pipeline with missing stages (#20238)
=> Cherry-pick to 7.9: [CI] fix apm-beats-update.groovy pipeline with missing stages (#20238)

Jenkinsfile, README.md
- [CI] MacOS stages for branches/tags and PRs when certain conditions (#20069)
- [CI] fix null string with contains (#20182)
=> Cherry-pick to 7.9: [CI] MacOS stages for branches/tags and PRs when certain conditions (#20069)

CHANGELOG.next.asciidoc, x-pack/metricbeat/module/azure/app_insights/_meta/docs.asciidoc
Cherry-pick of PR #20185 to 7.x branch. Original message: 
Updates documentation
Offers example config
=> Cherry-pick #20185 to 7.x: Modify doc in app_insights metricset

CHANGELOG.asciidoc, filebeat/input/syslog/parser.go, filebeat/input/syslog/parser_test.go, filebeat/input/syslog/syslog_rfc3164.rl
Cherry-pick of PR #13278 to 7.x branch. Original message: 
Fixes elastic/beats#13269
=> Cherry-pick #13278 to 7.x: Allow space or time sync character before timestamp

libbeat/autodiscover/providers/docker/docker_integration_test.go
Cherry-pick of PR #20361 to 7.9 branch. Original message: 
- Flaky Test
Skip TestDocker start test.
The test is failing in evry CI run the last days on master and 7.x/9
- Relates #20360
=> Cherry-pick #20361 to 7.9: Skip TestDockerStart

x-pack/elastic-agent/docs/elastic-agent-command-line.asciidoc, x-pack/elastic-agent/docs/elastic-agent-configuration-example.asciidoc, x-pack/elastic-agent/docs/elastic-agent-configuration.asciidoc, x-pack/elastic-agent/docs/elastic-agent.asciidoc, x-pack/elastic-agent/docs/install-elastic-agent.asciidoc, x-pack/elastic-agent/docs/run-elastic-agent.asciidoc, x-pack/elastic-agent/docs/stop-elastic-agent.asciidoc
Promote ingest management docs to beta in preparation in 7.9
=> [docs] Promote ingest management to beta

x-pack/elastic-agent/docs/elastic-agent-command-line.asciidoc, x-pack/elastic-agent/docs/elastic-agent.asciidoc, x-pack/elastic-agent/docs/install-elastic-agent.asciidoc, x-pack/elastic-agent/docs/run-elastic-agent.asciidoc, x-pack/elastic-agent/docs/stop-elastic-agent.asciidoc, x-pack/elastic-agent/docs/tab-widgets/code.asciidoc, x-pack/elastic-agent/docs/tab-widgets/enroll-widget.asciidoc, x-pack/elastic-agent/docs/tab-widgets/enroll.asciidoc, x-pack/elastic-agent/docs/tab-widgets/install-widget.asciidoc, x-pack/elastic-agent/docs/tab-widgets/install.asciidoc, x-pack/elastic-agent/docs/tab-widgets/run-standalone-widget.asciidoc, x-pack/elastic-agent/docs/tab-widgets/run-widget.asciidoc, x-pack/elastic-agent/docs/tab-widgets/run.asciidoc, x-pack/elastic-agent/docs/tab-widgets/stop-widget.asciidoc, x-pack/elastic-agent/docs/tab-widgets/stop.asciidoc, x-pack/elastic-agent/docs/unenroll-elastic-agent.asciidoc
- [docs] Add Elastic Agent doc changes for 7.9 (#20437)
=> Cherry-pick to 7.x: [docs] Add Elastic Agent doc changes for 7.9 (#20437)

Jenkinsfile
Retry with sleep the python installation
If something bad happened with the choco installation, then let's try again with some pause.
=> [CI] add more resilience

Jenkinsfile
- [CI] runbld project name (#20466)
=> Cherry-pick to 7.9: [CI] runbld project name (#20466)

Jenkinsfile
- [CI] runbld project name (#20466)
=> Cherry-pick to 7.x: [CI] runbld project name (#20466)

Jenkinsfile
- More stages in parallel rather than sequentially when they are OS specific based.
- Reuse worker in some of the stages.
More parallel builds will ideally reduce the overall build time.
=> [CI] more parallel stages and less provisioned workers

x-pack/elastic-agent/docs/elastic-agent-configuration.asciidoc
Fix typo to correctly resolve attribute.
=> [docs] Fix minor typo

CHANGELOG.asciidoc
Cherry-pick of PR #20597 to 7.9 branch. Original message:
=> Cherry-pick #20597 to 7.9: Fix broken elements in the changelog for 7.9

CHANGELOG.next.asciidoc
Cherry-pick of PR #20597 to 7.x branch. Original message:
=> Cherry-pick #20597 to 7.x: Fix broken elements in the changelog for 7.9

Jenkinsfile
Add when condition in the CI stage
To run only when it's required
Relates #20569
=> [CI] Fix missing when for Packetbeat

CHANGELOG.next.asciidoc
#20540 was merged into master without a changelog entry
=> Add missing changelog entry for #20540

libbeat/docs/release-notes/whats-new.asciidoc
Adds what's new content for beats 7.9.
=> [docs] Update what's new for 7.9

libbeat/docs/release-notes/breaking/breaking-7.9.asciidoc, libbeat/docs/release-notes/breaking/breaking.asciidoc
Adds breaking change about Okta module.
=> [docs] Add breaking changes for 7.9

libbeat/docs/release-notes/whats-new.asciidoc
Backports #20618 to 7.9 branch.
=> [7.9][docs] Update what's new for 7.9

libbeat/docs/release-notes/whats-new.asciidoc
Uncomment links to release notes and breaking changes.
Also remove content to appear in the tagged region so it shows up in the stack install/upgrade docs.
=> [docs] Activate links and tagged regions in what's new topic

heartbeat/docs/autodiscover-hints.asciidoc
Corrects the spelling of `healthz` in the Heartbeat autodiscover hints documentation 
Ensures the reference material aligns with common conventions and 
-
=> Fix healthz spelling in autodiscover-hints

libbeat/docs/version.asciidoc
Sets the release state to released for 7.8.
=> [docs] Set release state to released 7.8

libbeat/docs/version.asciidoc
Sets the release state to released for 7.7.
=> [docs] Set release state to released 7.7

x-pack/heartbeat/heartbeat.reference.yml
This PR is to rerun `mage fmt update` for x-pack/heartbeat after https://github.com/elastic/beats/pull/20357.
=> Run mage fmt update to fix heartbeat.reference.yml

CHANGELOG.asciidoc
Adds edits already reviewed in https://github.com/elastic/beats/pull/20619
=> [7.9][docs] Edit 7.9 release notes

x-pack/elastic-agent/docs/install-elastic-agent.asciidoc, x-pack/elastic-agent/docs/tab-widgets/run.asciidoc
Fixes https://github.com/elastic/observability-docs/issues/95.
=> [docs] Add steps for making agent persistent on macos

x-pack/elastic-agent/pkg/agent/operation/common_test.go, x-pack/elastic-agent/pkg/agent/operation/monitoring_test.go, x-pack/elastic-agent/pkg/core/server/server.go, x-pack/elastic-agent/pkg/core/server/server_test.go
Fixes the tests to listen only on localhost.
Prevents showing allow/deny modals on Mac OS X, and generally a good idea anyway.
- Closes #20743
=> [Elastic Agent] Fix tests to use localhost

x-pack/elastic-agent/docs/elastic-agent-configuration.asciidoc
- [docs] Update settings doc to indicate that they are configurable through the UI (#20741)
=> Cherry-pick to 7.x: [docs] Update settings doc to indicate that they are configurable through the UI (#20741)

x-pack/elastic-agent/magefile.go
The elastic agent used to be in his own repository and didn't have
access to the beats toolchains and setup like testings. This PR move the
custom mage test:unit implement to use the devtools' implementations.
This changes will allow CI to correctly generates reports for failures.
Fixes: #19822
-
=> [Elastic Agent] improve CI reporting

x-pack/elastic-agent/docs/elastic-agent-configuration.asciidoc
- [docs] Update settings doc to indicate that they are configurable through the UI (#20741)
=> Cherry-pick to 7.9: [docs] Update settings doc to indicate that they are configurable through the UI (#20741)

x-pack/elastic-agent/magefile.go
Cherry-pick of PR #20780 to 7.x branch. Original message: 
The elastic agent used to be in his own repository and didn't have
access to the beats toolchains and setup like testings. This PR move the
custom mage test:unit implement to use the devtools' implementations.
This changes will allow CI to correctly generates reports for failures.
Fixes: #19822
-
=> Cherry-pick #20780 to 7.x: [Elastic Agent] improve CI reporting

filebeat/input/v2/input-cursor/clean.go, go.mod, go.sum
Cherry-pick of PR #20590 to 7.x branch. Original message: 
- Dependency Update
Update go-concert to v0.0.4
Make use of improvements in Beats.
=> Cherry-pick #20590 to 7.x: Update go-concert to v0.0.4

x-pack/elastic-agent/magefile.go
Cherry-pick of PR #20780 to 7.9 branch. Original message: 
The elastic agent used to be in his own repository and didn't have
access to the beats toolchains and setup like testings. This PR move the
custom mage test:unit implement to use the devtools' implementations.
This changes will allow CI to correctly generates reports for failures.
Fixes: #19822
-
=> Cherry-pick #20780 to 7.9: [Elastic Agent] improve CI reporting

x-pack/elastic-agent/CHANGELOG.asciidoc, x-pack/elastic-agent/CHANGELOG.next.asciidoc
Cherry-pick of PR #20787 to 7.x branch. Original message: 
Clean the changelog of the Elastic Agent to correctly reflect the
changes going into a specific releases. This uses the same strategy as
beats with CHANGELOG.asciidoc and CHANGELOG.next.asciidoc.
Ref: #20715
-
=> Cherry-pick #20787 to 7.x: [Elastic Agent] Fix the changelog

x-pack/elastic-agent/CHANGELOG.asciidoc, x-pack/elastic-agent/CHANGELOG.next.asciidoc
Cherry-pick of PR #20787 to 7.8 branch. Original message: 
Clean the changelog of the Elastic Agent to correctly reflect the
changes going into a specific releases. This uses the same strategy as
beats with CHANGELOG.asciidoc and CHANGELOG.next.asciidoc.
Ref: #20715
-
=> Cherry-pick #20787 to 7.8: [Elastic Agent] Fix the changelog

x-pack/elastic-agent/CHANGELOG.asciidoc, x-pack/elastic-agent/CHANGELOG.next.asciidoc
Cherry-pick of PR #20787 to 7.9 branch. Original message: 
Clean the changelog of the Elastic Agent to correctly reflect the
changes going into a specific releases. This uses the same strategy as
beats with CHANGELOG.asciidoc and CHANGELOG.next.asciidoc.
Ref: #20715
-
=> Cherry-pick #20787 to 7.9: [Elastic Agent] Fix the changelog

metricbeat/docker-compose.yml, metricbeat/module/elasticsearch/index/index_test.go, metricbeat/module/logstash/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
This PR is to update ES/Kibana/Logstash to 7.9.
=> Update to latest version

filebeat/docs/autodiscover-hints.asciidoc
Cherry-pick of PR #20447 to 7.9 branch. Original message:
=> Cherry-pick #20447 to 7.9: Fix path and reference to metadata in hints docs

libbeat/docs/communitybeats.asciidoc
Signed-off-by: Ravi Raju <toravir@yahoo.com>
- Enhancement
Adds new custom beat to the community of beats.
So that people who need this can benefit from it
- [NA] I have commented my code, particularly in hard-to-understand areas
- [NA] I have made corresponding changes to the documentation
- [NA] I have made corresponding change to the default configuration files
- [NA] I have added tests that prove my fix is effective or that my feature works
- [NA] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.
This is just a doc update. testing is not applicable - except to see if the doc uses the correct tags.
None
NA
NA
NA
=> Adding cborbeat to community beats

x-pack/elastic-agent/docs/run-elastic-agent.asciidoc
Closes https://github.com/elastic/observability-docs/issues/121
Related PR: https://github.com/elastic/observability-docs/pull/122
(The docs CI for this PR will fail until https://github.com/elastic/observability-docs/pull/122 is merged)
=> Document how to set the ES host and Kibana URLs in Ingest Manager

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, metricbeat/docker-compose.yml, metricbeat/module/logstash/docker-compose.yml, x-pack/metricbeat/docker-compose.yml
Update missing test environment files
=> fix: update test environment 7.9.1

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml
follow up of https://github.com/elastic/beats/pull/20934 after running `make update`, it reverts some changes to pass the `make check`
=> fix: make update revert some changes

metricbeat/docker-compose.yml, metricbeat/module/logstash/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
=> fix: update test environments

.ci/apm-beats-update.groovy
* Enable the Jenkins instance as a worker for the default checkout.
* Disable default checkout on the checkout stage.
* Use Ubuntu-18 workers.
The latest update changed something in the behavior of the checkout and now it does not work if you do not make the default checkout in the roo pipeline agent.
closes …
=> [CI]fix: APM Beats Update job

x-pack/elastic-agent/pkg/agent/operation/operator_test.go
Cherry-pick of PR #20400 to 7.x branch. Original message:
- Relates #20836
=> Cherry-pick #20400 to 7.x: Flaky TestConfigurableService disable test (#20840)

CHANGELOG.next.asciidoc, metricbeat/mb/module/wrapper.go, x-pack/metricbeat/module/oracle/performance/_meta/cache_data.json, x-pack/metricbeat/module/oracle/performance/_meta/cursor_by_username_and_machine_data.json, x-pack/metricbeat/module/oracle/performance/_meta/data.json, x-pack/metricbeat/module/oracle/performance/metricset.go, x-pack/metricbeat/module/oracle/tablespace/_meta/data.json, x-pack/metricbeat/module/oracle/tablespace/metricset.go
Cherry-pick of PR #21022 to 7.x branch. Original message: 
This PR sanitizes the `event.host` not to leak any credentials. It fixes also a bug related to a defined but not used host parser.
It's a security threat.
- [x I have commented my code, particularly in hard-to-understand areas
- Closes https://github.com/elastic/integrations/issues/257
=> Cherry-pick #21022 to 7.x: Sanitize event.host in Metricbeat

x-pack/elastic-agent/CHANGELOG.next.asciidoc
Adds missing changelog entry for #20994 
So new feature is documented in changelog.
=> [Elastic Agent] Add changelog entry for EQL based condition

x-pack/elastic-agent/pkg/kibana/config.go
Increased timeout as per https://github.com/elastic/beats/issues/21025
Fixes: https://github.com/elastic/beats/issues/21025
=> [Ingest Manager] Increase kibana client timeout to 5 minutes

filebeat/docs/modules/zeek.asciidoc, libbeat/docs/communitybeats.asciidoc, libbeat/docs/shared-faq.asciidoc, packetbeat/docs/packetbeat-options.asciidoc, x-pack/filebeat/module/zeek/_meta/docs.asciidoc
Closes #20765 
Fixes external links that 404. Used the Internet Archive to get the closest links I could find.
=> Fix broken links to external websites

libbeat/docs/security/users.asciidoc
=> Update users.asciidoc (#20802)

filebeat/docs/inputs/input-log.asciidoc
Update input-log.asciidoc (#20965)
=> Cherry-pick to master: Update input-log.asciidoc (#20965)

filebeat/docs/modules/logstash.asciidoc, filebeat/module/logstash/_meta/docs.asciidoc
=> [docs] typo

libbeat/docs/communitybeats.asciidoc
Added a link to phishbeat developed by Stric-co
=> Added a link to phishbeat

.ci/beats-tester.groovy, .ci/jobs/beats-tester.yml, README.md
- [JJBB][CI] Run beats-tester on master and release branches (#21169)
=> Cherry-pick to 7.x: [JJBB][CI] Run beats-tester on master and release branches (#21169)

CHANGELOG.next.asciidoc, x-pack/libbeat/common/cloudfoundry/events.go, x-pack/libbeat/common/cloudfoundry/events_test.go, x-pack/libbeat/processors/add_cloudfoundry_metadata/_meta/fields.yml, x-pack/metricbeat/module/cloudfoundry/container/_meta/data.json, x-pack/metricbeat/module/cloudfoundry/container/container_integration_test.go, x-pack/metricbeat/module/cloudfoundry/counter/_meta/data.json, x-pack/metricbeat/module/cloudfoundry/counter/counter_integration_test.go, x-pack/metricbeat/module/cloudfoundry/mtest/config.go, x-pack/metricbeat/module/cloudfoundry/value/_meta/data.json, x-pack/metricbeat/module/cloudfoundry/value/value_integration_test.go
Collect tags from Cloud Foundry events.
They can contain information relevant to the event.
- Related to #16520
=> Add cloudfoundry tags to events

x-pack/filebeat/processors/decode_cef/docs/decode_cef.asciidoc
The table of options has got the rows intermingled.
-
=> [Docs] Typo in table syntax

docs/devguide/modules-dev-guide.asciidoc
Fixes an inconsistent step of testing process of Filebeat.
=> Fix dev guide test command

docs/devguide/modules-dev-guide.asciidoc
Cherry-pick of PR #21254 to 7.x branch. Original message: 
Fixes an inconsistent step of testing process of Filebeat.
=> Cherry-pick #21254 to 7.x: Fix dev guide test command

libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc
=> Kerberos typo

heartbeat/docs/autodiscover-hints.asciidoc
Cherry-pick of PR #20640 to 7.x branch. Original message: 
Corrects the spelling of `healthz` in the Heartbeat autodiscover hints documentation 
Ensures the reference material aligns with common conventions and 
-
=> Cherry-pick #20640 to 7.x: Fix healthz spelling in autodiscover-hints

.ci/scripts/generate_build_table.py, .ci/scripts/get-vendor-dependencies.sh, .ci/scripts/install-tools.sh, Jenkinsfile, Jenkinsfile.yml, README.md, auditbeat/Jenkinsfile.yml, deploy/kubernetes/Jenkinsfile.yml, filebeat/Jenkinsfile.yml, generator/Jenkinsfile.yml, heartbeat/Jenkinsfile.yml, journalbeat/Jenkinsfile.yml, libbeat/Jenkinsfile.yml, metricbeat/Jenkinsfile.yml, packetbeat/Jenkinsfile.yml, winlogbeat/Jenkinsfile.yml, x-pack/auditbeat/Jenkinsfile.yml, x-pack/dockerlogbeat/Jenkinsfile.yml, x-pack/elastic-agent/Jenkinsfile.yml, x-pack/filebeat/Jenkinsfile.yml, x-pack/functionbeat/Jenkinsfile.yml, x-pack/libbeat/Jenkinsfile.yml, x-pack/metricbeat/Jenkinsfile.yml, x-pack/packetbeat/Jenkinsfile.yml, x-pack/winlogbeat/Jenkinsfile.yml
- [CI] Pipeline 2.0 for monorepos (#20104)
=> Cherry-pick to 7.x: [CI] Pipeline 2.0 for monorepos (#20104)

Jenkinsfile
Cherry pick https://github.com/elastic/beats/pull/20891
https://github.com/elastic/beats/pull/20104  did not pick it.
=> [CI] cherry-pick #20891

Jenkinsfile
- [CI] refactor runbld post build action (#21256)
=> Cherry-pick to 7.x: [CI] refactor runbld post build action (#21256)

Jenkinsfile
- [CI] refactor runbld post build action (#21256)
=> Cherry-pick to 7.9: [CI] refactor runbld post build action (#21256)

Jenkinsfile
- [CI] Archive build reasons (#21347)
=> Cherry-pick to 7.9: [CI] Archive build reasons (#21347)

Jenkinsfile
- [CI] Archive build reasons (#21347)
=> Cherry-pick to 7.x: [CI] Archive build reasons (#21347)

libbeat/docs/release.asciidoc
it adds a link to release notes for 7.9.2
=> docs: add a link to release notes for 7.9.2

.ci/jobs/beats-release-changelog.yml
It automates the changelog generation process.
=> ci: pipeline to generate the changelog

.ci/jobs/apm-beats-update.yml, .ci/jobs/beats-tester.yml, .ci/jobs/beats-windows-mbp.yml, .ci/jobs/beats.yml, .ci/jobs/golang-crossbuild-mbp.yml, .ci/jobs/packaging.yml
=> Revert "[JJBB] Set shallow cloning to 10"

metricbeat/docs/modules/sql.asciidoc, x-pack/metricbeat/module/sql/_meta/docs.asciidoc, x-pack/metricbeat/module/sql/query/_meta/docs.asciidoc
- Edit SQL module docs and fix broken doc structure (#21233)
=> Cherry-pick to 7.x: Edit SQL module docs and fix broken doc structure (#21233)

metricbeat/docs/modules/sql.asciidoc, x-pack/metricbeat/module/sql/_meta/docs.asciidoc, x-pack/metricbeat/module/sql/query/_meta/docs.asciidoc
- Edit SQL module docs and fix broken doc structure (#21233)
=> Cherry-pick to 7.9: Edit SQL module docs and fix broken doc structure (#21233)

.ci/jobs/apm-beats-update.yml, .ci/jobs/beats-tester.yml, .ci/jobs/beats-windows-mbp.yml, .ci/jobs/beats.yml, .ci/jobs/golang-crossbuild-mbp.yml, .ci/jobs/packaging.yml
Reverts elastic/beats#21447
Build corruption was caused by something else
=> Revert "Revert "[JJBB] Set shallow cloning to 10""

metricbeat/docs/running-on-kubernetes.asciidoc
Removes deployment part from example since it's not valid any more. Leftover from https://github.com/elastic/beats/pull/20601
=> [docs] [Kubernetes] Fix leftover deployment example

CHANGELOG.next.asciidoc
Adds a missing Changelog entry belonging to #21504
=> [Filebeat][cisco] Add missing changelog entry for cisco umbrella

Jenkinsfile
- [CI] Setup git config globally (#21562)
=> Cherry-pick to 7.x: [CI] Setup git config globally (#21562)

Jenkinsfile
- [CI] Setup git config globally (#21562)
=> Cherry-pick to 7.9: [CI] Setup git config globally (#21562)

Jenkinsfile
Change the slack channel and notify the build status always for branches and tags
Notify build status and trends.
=> [CI] Change notification channel

Jenkinsfile
- [CI] cherry-pick #20891 (#21314)
=> Cherry-pick to 7.x: [CI] cherry-pick #20891 (#21314)

Jenkinsfile
- [CI] Change notification channel (#21559)
=> Cherry-pick to 7.x: [CI] Change notification channel (#21559)

x-pack/filebeat/module/cyberark/corepas/ingest/pipeline.yml, x-pack/filebeat/module/cyberark/corepas/test/generated.log-expected.json
Fixes an error in the cyberark pipeline
=> [Filebeat][Cyberark] Fix cyberark/corepas pipeline

Jenkinsfile
- [CI] Change notification channel (#21559)
=> Cherry-pick to 7.9: [CI] Change notification channel (#21559)

Jenkinsfile
- [CI] Change notification channel (#21559)
=> Cherry-pick to 7.10: [CI] Change notification channel (#21559)

x-pack/filebeat/module/cyberark/corepas/ingest/pipeline.yml, x-pack/filebeat/module/cyberark/corepas/test/generated.log-expected.json
Cherry-pick of PR #21643 to 7.x branch. Original message: 
Fixes an error in the cyberark pipeline
=> Cherry-pick #21643 to 7.x: [Filebeat][Cyberark] Fix cyberark/corepas pipeline

x-pack/filebeat/module/cyberark/corepas/ingest/pipeline.yml, x-pack/filebeat/module/cyberark/corepas/test/generated.log-expected.json
Cherry-pick of PR #21643 to 7.10 branch. Original message: 
Fixes an error in the cyberark pipeline
=> Cherry-pick #21643 to 7.10: [Filebeat][Cyberark] Fix cyberark/corepas pipeline

.ci/jobs/apm-beats-update.yml, .ci/jobs/beats.yml, .ci/jobs/packaging.yml
add the versions 7.1x to the beats pipeline
=> chore: add versions 7.1x

Jenkinsfile
- [CI] Setup git config globally (#21562)
=> Cherry-pick to 7.10: [CI] Setup git config globally (#21562)

.ci/packaging.groovy
It uses the renamed name for the e2e test suite: from "ingest-manager" to "fleet"
Otherwise, no test suite will be triggered
- Relates #348
=> fix: update fleet test suite name

x-pack/filebeat/input/s3/collector.go
Cherry-pick of PR #21732 to 7.x branch. Original message: 
This PR adds a check for `context.DeadlineExceeded ` error and reports an INFO level log message instead.
=> Cherry-pick #21732 to 7.x: [Filebeat] Add check for context.DeadlineExceeded error

dev-tools/packaging/packages.yml, x-pack/elastic-agent/CHANGELOG.next.asciidoc, x-pack/elastic-agent/magefile.go
Cherry-pick of PR #21602 to 7.x branch. Original message: 
This keeps most of the changes in https://github.com/elastic/beats/pull/20488 but un-bundles heartbeat since it's not ready for prime time yet. We may as well keep the work that has been done already, but keep it somewhat out of the way and undocumented / unsupported for now. We will open a separate issue for removing the package.
=> Cherry-pick #21602 to 7.x: [Agent] Remove heartbeat from bundled beats in agent.

x-pack/elastic-agent/docs/install-elastic-agent.asciidoc, x-pack/elastic-agent/docs/tab-widgets/run.asciidoc
Closes https://github.com/elastic/observability-docs/issues/130.
Related to https://github.com/elastic/observability-docs/pull/160 (the Beats build won't pass until 160 is merged).
=> Update endpoint-related terminology in Elastic Agent docs

Jenkinsfile, Jenkinsfile.yml
- [CI] Support skip-ci label (#21377)
=> Cherry-pick to 7.10: [CI] Support skip-ci label (#21377)

libbeat/docs/security/users.asciidoc
- Update users.asciidoc (#21802)
=> Cherry-pick to 7.10: Update users.asciidoc (#21802)

libbeat/docs/security/users.asciidoc
- Update users.asciidoc (#21802)
=> Cherry-pick to 7.x: Update users.asciidoc (#21802)

.ci/scripts/install-go.sh, Jenkinsfile, auditbeat/Jenkinsfile.yml, filebeat/Jenkinsfile.yml, heartbeat/Jenkinsfile.yml, journalbeat/Jenkinsfile.yml, libbeat/Jenkinsfile.yml, packetbeat/Jenkinsfile.yml, x-pack/auditbeat/Jenkinsfile.yml, x-pack/elastic-agent/Jenkinsfile.yml, x-pack/filebeat/Jenkinsfile.yml, x-pack/functionbeat/Jenkinsfile.yml, x-pack/libbeat/Jenkinsfile.yml
- [CI] Enable build stage for arm architecture (#21284)
=> Cherry-pick to 7.10: [CI] Enable build stage for arm architecture (#21284)

libbeat/docs/shared-autodiscover.asciidoc
Trivial fix in Autodiscover docs.
=> [docs] Remove extra word in autodiscover docs

Jenkinsfile
Temporary workaround to add more visibility to what beat failed when the step is the same.
Easy to debug errors with the GitHub PR comment
See https://github.com/elastic/apm-pipeline-library/issues/554
=> [CI] Add stage name in the step

Jenkinsfile
- [CI] Add stage name in the step (#21887)
=> Cherry-pick to 7.10: [CI] Add stage name in the step (#21887)

Jenkinsfile
- [CI] Add stage name in the step (#21887)
=> Cherry-pick to 7.x: [CI] Add stage name in the step (#21887)

Jenkinsfile
- [CI] Add stage name in the step (#21887)
=> Cherry-pick to 7.9: [CI] Add stage name in the step (#21887)

Jenkinsfile
- [CI] kind setup fails sometimes (#21857)
=> Cherry-pick to 7.x: [CI] kind setup fails sometimes (#21857)

Jenkinsfile
- [CI] kind setup fails sometimes (#21857)
=> Cherry-pick to 7.10: [CI] kind setup fails sometimes (#21857)

Jenkinsfile
- [CI] kind setup fails sometimes (#21857)
=> Cherry-pick to 7.9: [CI] kind setup fails sometimes (#21857)

x-pack/metricbeat/module/istio/proxy/_meta/docs.asciidoc
Follow up of https://github.com/elastic/beats/pull/21751 to fix docs example.
See https://github.com/elastic/beats/pull/21834#discussion_r505419342
=> Update istio proxy docs example

Jenkinsfile
Avoid storing data in the Jenkins instance but use Google Storage for that 
> 91% disk
=> [CI] Use google storage to keep artifacts

generator/_templates/beat/{beat}/tests/system/{beat}.py, generator/common/beatgen/beatgen.go
Closes https://github.com/elastic/beats/issues/21898
=> Fix the order of imports in the generated Python test

libbeat/autodiscover/providers/docker/docker_integration_test.go, libbeat/tests/docker/docker.go
Cherry-pick of PR #21681 to 7.x branch. Original message: 
Some changes are done to give more resilience to the test:
* Wait till image pull is finished, and retry in case of failure.
* Checked events are filtered by container id instead of image name,
so tests are not affected by other containers that may be running
in the system.
* Check timeout is for all events now, instead of being reset after an
event is received.
* Container is removed after test is finished.
Fixes #20360.
=> Cherry-pick #21681 to 7.x: Fix TestDockerStart flaky test

CHANGELOG.asciidoc
- [docs] Edit 7.9 release notes (#20619)
=> Cherry-pick to 7.10: [docs] Edit 7.9 release notes (#20619)

CHANGELOG.asciidoc
- [docs] Edit 7.9 release notes (#20619)
=> Cherry-pick to 7.x: [docs] Edit 7.9 release notes (#20619)

metricbeat/docs/modules/istio.asciidoc, x-pack/metricbeat/module/istio/_meta/docs.asciidoc
=> Fix Istio docs

metricbeat/docs/modules/istio.asciidoc, x-pack/metricbeat/module/istio/_meta/docs.asciidoc
Cherry-pick of PR #22019 to 7.x branch. Original message: 
Fixes some small typo issues
=> Cherry-pick #22019 to 7.x: Fix Istio docs

libbeat/docs/getting-started.asciidoc, libbeat/docs/howto/load-dashboards.asciidoc, libbeat/docs/overview.asciidoc
=> Cherry-pick to 7.10: Update links (#22012)

libbeat/docs/getting-started.asciidoc, libbeat/docs/howto/load-dashboards.asciidoc, libbeat/docs/overview.asciidoc
=> Cherry-pick to 7.x: Update links (#22012)

Jenkinsfile, libbeat/tests/system/requirements.txt
- ci: configure retries on tests (#20891)
=> Cherry-pick to 7.10: ci: configure retries on tests (#20891)

libbeat/docs/shared-faq.asciidoc
- [DOC] Add firewall as possible troubleshooting issue (#21743)
=> Cherry-pick to 7.10: [DOC] Add firewall as possible troubleshooting issue (#21743)

libbeat/docs/shared-faq.asciidoc
- [DOC] Add firewall as possible troubleshooting issue (#21743)
=> Cherry-pick to 7.x: [DOC] Add firewall as possible troubleshooting issue (#21743)

Makefile
- Bug
Updates the url of reviewdog.
related to https://github.com/elastic/beats/issues/21976
It looks that Go tries to install the reviewdog from [github.com/haya14busa/reviewdog](github.com/haya14busa/reviewdog), but the reviewdog was moved to [reviewdog organization](https://github.com/reviewdog/).
New url of the reviewdog is [github.com/reviewdog/reviewdog](github.com/reviewdog/reviewdog).
-
=> fix the url of reviewdog

Makefile
Cherry-pick of PR #21981 to 7.10 branch. Original message: 
- Bug
Updates the url of reviewdog.
related to https://github.com/elastic/beats/issues/21976
It looks that Go tries to install the reviewdog from [github.com/haya14busa/reviewdog](github.com/haya14busa/reviewdog), but the reviewdog was moved to [reviewdog organization](https://github.com/reviewdog/).
New url of the reviewdog is [github.com/reviewdog/reviewdog](github.com/reviewdog/reviewdog).
-
=> Cherry-pick #21981 to 7.10: fix the url of reviewdog

Makefile
Cherry-pick of PR #21981 to 7.9 branch. Original message: 
- Bug
Updates the url of reviewdog.
related to https://github.com/elastic/beats/issues/21976
It looks that Go tries to install the reviewdog from [github.com/haya14busa/reviewdog](github.com/haya14busa/reviewdog), but the reviewdog was moved to [reviewdog organization](https://github.com/reviewdog/).
New url of the reviewdog is [github.com/reviewdog/reviewdog](github.com/reviewdog/reviewdog).
-
=> Cherry-pick #21981 to 7.9: fix the url of reviewdog

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 7.9.3

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 6.8.13

dev-tools/mage/dockerbuilder.go, x-pack/elastic-agent/magefile.go
- [build][packaging] Add resilience when docker build (#22050)
=> Cherry-pick to 7.10: [build][packaging] Add resilience when docker build (#22050)

.ci/packaging.groovy
It uses a more specific label when selecting the Jenkins agent
To use the right build agent
- Discovered while reviewing #22076 #22078
=> chore: use ubuntu 18 as linux agent

x-pack/auditbeat/module/system/package/rpm_linux.go
- re-order imports
- fix capitalization in error string
code quality
- Relates #21936
- Relates #19287
=> [Auditbeat] Incorporate librpm fix feedback

CHANGELOG.asciidoc
Very minor fix (does not require review). Normally wouldn't create a commit for such a minor change, but went ahead since I need to backport this to master anyhow.
=> Edit 6.8.13 release notes

x-pack/elastic-agent/docs/run-elastic-agent.asciidoc
Adds image that was previously commented out in #21549
=> Add fleet settings image

Jenkinsfile.yml, winlogbeat/Jenkinsfile.yml
=> [CI] Enable winlogbeat

x-pack/auditbeat/module/system/package/rpm_linux.go
Cherry-pick of PR #22098 to 7.x branch. Original message: 
- re-order imports
- fix capitalization in error string
code quality
- Relates #21936
- Relates #19287
=> Cherry-pick #22098 to 7.x: [Auditbeat] Incorporate librpm fix feedback

Jenkinsfile.yml, auditbeat/Jenkinsfile.yml, filebeat/Jenkinsfile.yml, heartbeat/Jenkinsfile.yml, metricbeat/Jenkinsfile.yml, packetbeat/Jenkinsfile.yml, winlogbeat/Jenkinsfile.yml, x-pack/auditbeat/Jenkinsfile.yml, x-pack/elastic-agent/Jenkinsfile.yml, x-pack/filebeat/Jenkinsfile.yml, x-pack/functionbeat/Jenkinsfile.yml, x-pack/metricbeat/Jenkinsfile.yml, x-pack/packetbeat/Jenkinsfile.yml, x-pack/winlogbeat/Jenkinsfile.yml
- [CI] support windows-10 (#19804)
- 97d7324690326e2b3eb1e6014bee4a191daf732c
=> Cherry-pick to 7.10: [CI] support windows-10 (#19804)

CHANGELOG.next.asciidoc, docs/devguide/create-metricset.asciidoc
The code snippet explaining how to update a custom metricbeat module/metricset was outdated.
This came up in a discord issue, so we should fix it.
=> [Docs] Update custom beat docs

Jenkinsfile, filebeat/Jenkinsfile.yml
- [CI][flaky] reporting for PRs in GitHub (#21853)
=> Cherry-pick to 7.x: [CI][flaky] reporting for PRs in GitHub (#21853)

Jenkinsfile, filebeat/Jenkinsfile.yml
- [CI][flaky] reporting for PRs in GitHub (#21853)
=> Cherry-pick to 7.10: [CI][flaky] reporting for PRs in GitHub (#21853)

Jenkinsfile
- [CI][flaky] Support 7.x branches and PRs (#22197)
=> Cherry-pick to 7.x: [CI][flaky] Support 7.x branches and PRs (#22197)

Jenkinsfile
- [CI][flaky] Support 7.x branches and PRs (#22197)
=> Cherry-pick to 7.10: [CI][flaky] Support 7.x branches and PRs (#22197)

Jenkinsfile
- [CI] archive only if failed steps (#22220)
=> Cherry-pick to 7.10: [CI] archive only if failed steps (#22220)

Jenkinsfile
- [CI] archive only if failed steps (#22220)
=> Cherry-pick to 7.x: [CI] archive only if failed steps (#22220)

Jenkinsfile.yml
Leftover from https://github.com/elastic/beats/pull/21979
To run in the CI
=> [CI] enable x-pack/packetbeat in the CI

auditbeat/Jenkinsfile.yml, filebeat/Jenkinsfile.yml, heartbeat/Jenkinsfile.yml, metricbeat/Jenkinsfile.yml, packetbeat/Jenkinsfile.yml, winlogbeat/Jenkinsfile.yml, x-pack/auditbeat/Jenkinsfile.yml, x-pack/elastic-agent/Jenkinsfile.yml, x-pack/filebeat/Jenkinsfile.yml, x-pack/functionbeat/Jenkinsfile.yml, x-pack/metricbeat/Jenkinsfile.yml, x-pack/packetbeat/Jenkinsfile.yml, x-pack/winlogbeat/Jenkinsfile.yml
- [CI] support windows-2008-r2 (#19791)
=> Cherry-pick to 7.x: [CI] support windows-2008-r2 (#19791)

auditbeat/Jenkinsfile.yml, filebeat/Jenkinsfile.yml, heartbeat/Jenkinsfile.yml, metricbeat/Jenkinsfile.yml, packetbeat/Jenkinsfile.yml, winlogbeat/Jenkinsfile.yml, x-pack/auditbeat/Jenkinsfile.yml, x-pack/elastic-agent/Jenkinsfile.yml, x-pack/filebeat/Jenkinsfile.yml, x-pack/functionbeat/Jenkinsfile.yml, x-pack/metricbeat/Jenkinsfile.yml, x-pack/packetbeat/Jenkinsfile.yml, x-pack/winlogbeat/Jenkinsfile.yml
- [CI] support windows-2008-r2 (#19791)
=> Cherry-pick to 7.10: [CI] support windows-2008-r2 (#19791)

x-pack/filebeat/input/s3/collector.go
Remove these debug messages I commit by mistake...
=> Remove debug messages

x-pack/filebeat/input/s3/collector.go
Cherry-pick of PR #22282 to 7.10 branch. Original message: 
Remove these debug messages I commit by mistake...
=> Cherry-pick #22282 to 7.10: Remove debug messages

x-pack/filebeat/input/s3/collector.go
Cherry-pick of PR #22282 to 7.x branch. Original message: 
Remove these debug messages I commit by mistake...
=> Cherry-pick #22282 to 7.x: Remove debug messages

x-pack/elastic-agent/docs/elastic-agent-configuration.asciidoc, x-pack/elastic-agent/docs/tab-widgets/enroll-widget.asciidoc, x-pack/elastic-agent/docs/tab-widgets/enroll.asciidoc, x-pack/elastic-agent/docs/tab-widgets/install-widget.asciidoc, x-pack/elastic-agent/docs/tab-widgets/install.asciidoc
- Update commands used in the quick start (#22248)
=> Cherry-pick to 7.x: Update commands used in the quick start (#22248)

x-pack/elastic-agent/docs/elastic-agent-configuration.asciidoc, x-pack/elastic-agent/docs/tab-widgets/enroll-widget.asciidoc, x-pack/elastic-agent/docs/tab-widgets/enroll.asciidoc, x-pack/elastic-agent/docs/tab-widgets/install-widget.asciidoc, x-pack/elastic-agent/docs/tab-widgets/install.asciidoc
- Update commands used in the quick start (#22248)
=> Cherry-pick to 7.10: Update commands used in the quick start (#22248)

filebeat/docs/modules/cisco.asciidoc, x-pack/filebeat/filebeat.reference.yml, x-pack/filebeat/module/cisco/_meta/config.yml, x-pack/filebeat/module/cisco/_meta/docs.asciidoc, x-pack/filebeat/module/cisco/umbrella/config/input.yml, x-pack/filebeat/module/cisco/umbrella/manifest.yml, x-pack/filebeat/modules.d/cisco.yml.disabled
Cherry-pick of PR #22295 to 7.10 branch. Original message: 
This fixes missing config items for Cisco Umbrella, might have been missing from the start or been removed during a merge.
Umbrella fileset needs the config parameters to function.
=> Cherry-pick #22295 to 7.10: [Filebeat][Cisco Umbrella module] Adding missing timeout options and fixing module config.yml

filebeat/docs/modules/cisco.asciidoc, x-pack/filebeat/filebeat.reference.yml, x-pack/filebeat/module/cisco/_meta/config.yml, x-pack/filebeat/module/cisco/_meta/docs.asciidoc, x-pack/filebeat/module/cisco/umbrella/config/input.yml, x-pack/filebeat/module/cisco/umbrella/manifest.yml, x-pack/filebeat/modules.d/cisco.yml.disabled
Cherry-pick of PR #22295 to 7.x branch. Original message: 
This fixes missing config items for Cisco Umbrella, might have been missing from the start or been removed during a merge.
Umbrella fileset needs the config parameters to function.
=> Cherry-pick #22295 to 7.x: [Filebeat][Cisco Umbrella module] Adding missing timeout options and fixing module config.yml

Jenkinsfile
- [CI] Report error in the catch section (#22297)
=> Cherry-pick to 7.10: [CI] Report error in the catch section (#22297)

auditbeat/Jenkinsfile.yml, filebeat/Jenkinsfile.yml, heartbeat/Jenkinsfile.yml, metricbeat/Jenkinsfile.yml, packetbeat/Jenkinsfile.yml, winlogbeat/Jenkinsfile.yml, x-pack/auditbeat/Jenkinsfile.yml, x-pack/elastic-agent/Jenkinsfile.yml, x-pack/filebeat/Jenkinsfile.yml, x-pack/functionbeat/Jenkinsfile.yml, x-pack/metricbeat/Jenkinsfile.yml, x-pack/packetbeat/Jenkinsfile.yml, x-pack/winlogbeat/Jenkinsfile.yml
- [CI] Support Windows-8 (#22307)
=> Cherry-pick to 7.x: [CI] Support Windows-8 (#22307)

auditbeat/Jenkinsfile.yml, filebeat/Jenkinsfile.yml, heartbeat/Jenkinsfile.yml, metricbeat/Jenkinsfile.yml, packetbeat/Jenkinsfile.yml, winlogbeat/Jenkinsfile.yml, x-pack/auditbeat/Jenkinsfile.yml, x-pack/elastic-agent/Jenkinsfile.yml, x-pack/filebeat/Jenkinsfile.yml, x-pack/functionbeat/Jenkinsfile.yml, x-pack/metricbeat/Jenkinsfile.yml, x-pack/packetbeat/Jenkinsfile.yml, x-pack/winlogbeat/Jenkinsfile.yml
- [CI] Support Windows-8 (#22307)
=> Cherry-pick to 7.10: [CI] Support Windows-8 (#22307)

auditbeat/Jenkinsfile.yml, filebeat/Jenkinsfile.yml, heartbeat/Jenkinsfile.yml, metricbeat/Jenkinsfile.yml, packetbeat/Jenkinsfile.yml, winlogbeat/Jenkinsfile.yml, x-pack/auditbeat/Jenkinsfile.yml, x-pack/elastic-agent/Jenkinsfile.yml, x-pack/filebeat/Jenkinsfile.yml, x-pack/functionbeat/Jenkinsfile.yml, x-pack/metricbeat/Jenkinsfile.yml, x-pack/packetbeat/Jenkinsfile.yml, x-pack/winlogbeat/Jenkinsfile.yml
- [CI] support windows-7 (#19803)
=> Cherry-pick to 7.x: [CI] support windows-7 (#19803)

deploy/kubernetes/Jenkinsfile.yml
adds a check fro changes on the deploy/kubernetes pipeline
right now it not checking if there are changes or not
=> ci: add a check for changes to deploy/kubernetes pipeline

deploy/kubernetes/Jenkinsfile.yml
- ci: add a check for changes to deploy/kubernetes pipeline (#22249)
=> Cherry-pick to 7.10: ci: add a check for changes to deploy/kubernetes pipeline (#22249)

deploy/kubernetes/Jenkinsfile.yml
- ci: add a check for changes to deploy/kubernetes pipeline (#22249)
=> Cherry-pick to 7.9: ci: add a check for changes to deploy/kubernetes pipeline (#22249)

deploy/kubernetes/Jenkinsfile.yml
Backports the following commits to 6.8:
- ci: add a check for changes to deploy/kubernetes pipeline (#22249)
=> Cherry-pick to 6.8: ci: add a check for changes to deploy/kubernetes pipeline (#22249)

filebeat/docs/modules/azure.asciidoc, x-pack/filebeat/module/azure/_meta/docs.asciidoc
- remove working in progress comment (#22367)
=> Cherry-pick to 7.10: remove working in progress comment (#22367)

filebeat/docs/modules/azure.asciidoc, x-pack/filebeat/module/azure/_meta/docs.asciidoc
- remove working in progress comment (#22367)
=> Cherry-pick to 7.x: remove working in progress comment (#22367)

filebeat/docs/modules/azure.asciidoc, x-pack/filebeat/module/azure/_meta/docs.asciidoc
Forward ports the following commit to master:
remove working in progress comment (#22367)
=> Cherry-pick to master: remove working in progress comment (#22367)

filebeat/docs/filebeat-options.asciidoc, filebeat/docs/inputs/input-filestream-file-options.asciidoc, filebeat/docs/inputs/input-filestream-reader-options.asciidoc, filebeat/docs/inputs/input-filestream.asciidoc
Cherry-pick of PR #21615 to 7.x branch. Original message:
=> Cherry-pick #21615 to 7.x: Add documentation of filestream input

filebeat/docs/filebeat-options.asciidoc, filebeat/docs/inputs/input-filestream-file-options.asciidoc, filebeat/docs/inputs/input-filestream-reader-options.asciidoc, filebeat/docs/inputs/input-filestream.asciidoc
Cherry-pick of PR #21615 to 7.10 branch. Original message:
=> Cherry-pick #21615 to 7.10: Add documentation of filestream input

CHANGELOG.next.asciidoc, x-pack/functionbeat/_meta/config/beat.reference.yml.tmpl, x-pack/functionbeat/_meta/config/beat.yml.tmpl, x-pack/functionbeat/docs/config-options-aws.asciidoc, x-pack/functionbeat/functionbeat.reference.yml, x-pack/functionbeat/functionbeat.yml, x-pack/functionbeat/provider/aws/aws/kinesis.go, x-pack/functionbeat/provider/aws/aws/kinesis_test.go
Cherry-pick of PR #20727 to 7.10 branch. Original message: 
This PR adds the ability to add the parallelization factor configuration to functionbeat when reading from Kinesis streams. 
https://aws.amazon.com/about-aws/whats-new/2019/11/aws-lambda-supports-parallelization-factor-for-kinesis-and-dynamodb-event-sources/
This configuration allows you to process one shard of a Kinesis or DynamoDB data stream with more than one Lambda invocation simultaneously.
- Closes https://github.com/elastic/beats/issues/16901
=> Cherry-pick #20727 to 7.10: feature - parallelization factor kinesis functionbeat config

.ci/beats-tester-bc.groovy, .ci/jobs/beats-tester-bc.yml
Fix the script path setting on the JJBB definition
add the BRANCH_REFERENCE parameter
=> ci: set script-path to .ci/beats-tester-bc.groovy

.ci/beats-tester.groovy, .ci/jobs/beats-tester.yml, .ci/packaging.groovy, Jenkinsfile, Makefile
- [packaging][beats-tester] use commit id binaries (#22027)
=> Cherry-pick to 7.x: [packaging][beats-tester] use commit id binaries (#22027)

.ci/beats-tester.groovy, .ci/jobs/beats-tester.yml, .ci/packaging.groovy, Jenkinsfile, Makefile
- [packaging][beats-tester] use commit id binaries (#22027)
=> Cherry-pick to 7.10: [packaging][beats-tester] use commit id binaries (#22027)

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc
Fix some typos in the issue/pull references
=> Fix typo in the changelog pull/issue formats

docs/devguide/newdashboards.asciidoc
=> Removed duplicate sentence in documentation on metricbeat import

docs/devguide/newdashboards.asciidoc
- Deleted duplicate sentence (#22480)
=> Cherry-pick to master: Deleted duplicate sentence (#22480)

auditbeat/module/file_integrity/metricset_test.go
- Flaky Test
- Setup files/environment before running the test
- reduce chance of races, especially with very slow/overloaded CI workers
- fix t.Fatal being called from spawned go-routine (big NO NO)
- collect all found paths into a dictionary and assert wanted vs. found
paths after
- now checks for expected files that have not been found (semantic change)
- assert will now print a 'diff' with missing/unknown paths on error
The changes hopefully stabilize the flaky test (although the failure rate seems to be quite low already).
The failed will now print a diff if expected vs. seen files. Maybes this helps to better understand the failure in the future.
~~- [ ] I have made corresponding changes to the …
=> Try to stabilize TestIncludesExcludes

auditbeat/module/file_integrity/metricset_test.go
- Flaky Test
Skip TestActions test in auditbeat.
Test seems to be flaky on Windows.
- Relates #22518
=> Skip flaky TestActions on Windows

heartbeat/docs/monitors/monitor-icmp.asciidoc
This improves the documentation for the wait option, making its purpose more clear.
=> [Heartbeat] Improve docs for ICMP wait in heartbeat

.ci/packaging.groovy
- Bug
Add a `deleteDir` early in the packaging pipeline to fix the installation of go dependencies.
Packaging jobs in 7.x are currently broken because mage can't be installed. The problem is a leftover `go.mod` file in the current working directory, which is also set to `$GOPATH`.
-
=> Add missing deleteDir to packaging pipeline

.backportrc.json
Remove obsoleted branches
Tidy up what's not used anymore
=> [backport] Remove obsoleted branches

x-pack/elastic-agent/docs/install-elastic-agent.asciidoc, x-pack/elastic-agent/docs/tab-widgets/install.asciidoc, x-pack/elastic-agent/docs/uninstall-elastic-agent.asciidoc
Fixes usability issues and bugs found during testing.
I have more changes to make, but it might be good to get these merged because I found some weird stuff.
=> Fix problems in agent docs found during testing

x-pack/elastic-agent/docs/install-elastic-agent.asciidoc, x-pack/elastic-agent/docs/tab-widgets/install.asciidoc, x-pack/elastic-agent/docs/uninstall-elastic-agent.asciidoc
- Fix problems found during testing (#22562)
=> Cherry-pick to 7.10: Fix problems found during testing (#22562)

Jenkinsfile
Force one-shot workers approach
Certain builds are failing when configuring the worker with the `install tools` step. I've got my feeling that it happens normally when there is a peak of load, and could be caused when the windows workers are reused, although I'm not 100% sure if that's the reason yet.
```
[2020-11-12T23:45:34.275Z] C:\Users\jenkins\workspace\Beats_beats_master\src\github.com\elastic\beats>.ci/scripts/install-tools.bat
[2020-11-12T23:45:34.275Z] 
[2020-11-12T23:45:34.275Z] C:\Users\jenkins\workspace\Beats_beats_master\src\github.com\elastic\beats>set GOPATH=C:\Users\jenkins\workspace\Beats_beats_master 
[2020-11-12T23:45:34.275Z] 
[2020-11-12T23:45:34.275Z] C:\Users\jenkins\workspace\Beats_beats_master\src\github.com\elastic\beats>set …
```
=> [CI] ensure one shot-worker

x-pack/elastic-agent/docs/install-elastic-agent.asciidoc, x-pack/elastic-agent/docs/tab-widgets/install.asciidoc, x-pack/elastic-agent/docs/uninstall-elastic-agent.asciidoc
- Fix problems found during testing (#22562)
=> Cherry-pick to 7.x: Fix problems found during testing (#22562)

Jenkinsfile
=> Revert "Cherry-pick to 7.10: [CI] ensure one shot-worker (#22588)"

Jenkinsfile
=> Revert "Cherry-pick to 7.x: [CI] ensure one shot-worker (#22588)"
