Jenkinsfile
Somehow is not working 100% of the times and some workers are not provisioned. 
Revert:
- https://github.com/elastic/beats/pull/22588
- https://github.com/elastic/beats/pull/22607
=> [ci] revert one shot-workers

auditbeat/Jenkinsfile.yml, deploy/kubernetes/Jenkinsfile.yml, dev-tools/Jenkinsfile.yml, filebeat/Jenkinsfile.yml, generator/Jenkinsfile.yml, heartbeat/Jenkinsfile.yml, journalbeat/Jenkinsfile.yml, libbeat/Jenkinsfile.yml, metricbeat/Jenkinsfile.yml, packetbeat/Jenkinsfile.yml, winlogbeat/Jenkinsfile.yml, x-pack/auditbeat/Jenkinsfile.yml, x-pack/dockerlogbeat/Jenkinsfile.yml, x-pack/elastic-agent/Jenkinsfile.yml, x-pack/filebeat/Jenkinsfile.yml, x-pack/functionbeat/Jenkinsfile.yml, x-pack/libbeat/Jenkinsfile.yml, x-pack/metricbeat/Jenkinsfile.yml, x-pack/packetbeat/Jenkinsfile.yml, x-pack/winlogbeat/Jenkinsfile.yml
Use the right ephemeral word for the immutable workers.
Avoid issues if any when using labels that could potentially match a static worker
=> [CI] Use immutable labels

auditbeat/Jenkinsfile.yml, deploy/kubernetes/Jenkinsfile.yml, dev-tools/Jenkinsfile.yml, filebeat/Jenkinsfile.yml, generator/Jenkinsfile.yml, heartbeat/Jenkinsfile.yml, journalbeat/Jenkinsfile.yml, libbeat/Jenkinsfile.yml, metricbeat/Jenkinsfile.yml, packetbeat/Jenkinsfile.yml, winlogbeat/Jenkinsfile.yml, x-pack/auditbeat/Jenkinsfile.yml, x-pack/dockerlogbeat/Jenkinsfile.yml, x-pack/elastic-agent/Jenkinsfile.yml, x-pack/filebeat/Jenkinsfile.yml, x-pack/functionbeat/Jenkinsfile.yml, x-pack/libbeat/Jenkinsfile.yml, x-pack/metricbeat/Jenkinsfile.yml, x-pack/packetbeat/Jenkinsfile.yml, x-pack/winlogbeat/Jenkinsfile.yml
- [CI] Use immutable labels (#22628)
=> Cherry-pick to 7.x: [CI] Use immutable labels (#22628)

libbeat/docs/http-endpoint.asciidoc
Highlight the `pretty` option and use `cURL`
To visualise easily the option.
=> [docs][cosmetic] Highlight the pretty option in URL and cURL

testing/environments/latest.yml, testing/environments/snapshot.yml
This PR is to increase `cache_max_size` for Elasticsearch in order to fix the issue https://github.com/elastic/beats/issues/22561.
=> Increase ES cache size

Jenkinsfile
Archive more logs for tracking purposes
Help with the flakiness test analysis
=> [CI] log rotation

libbeat/docs/http-endpoint.asciidoc
- [docs][cosmetic] Highlight the pretty option in URL and cURL (#22681)
=> Cherry-pick to 7.10: [docs][cosmetic] Highlight the pretty option in URL and cURL (#22681)

x-pack/elastic-agent/docs/elastic-agent-configuration.asciidoc, x-pack/elastic-agent/docs/elastic-agent.asciidoc, x-pack/elastic-agent/docs/install-elastic-agent.asciidoc, x-pack/elastic-agent/docs/run-elastic-agent-standalone.asciidoc, x-pack/elastic-agent/docs/tab-widgets/install-layout.asciidoc, x-pack/elastic-agent/docs/tab-widgets/install.asciidoc, x-pack/elastic-agent/docs/tab-widgets/run-standalone.asciidoc, x-pack/elastic-agent/docs/tab-widgets/uninstall.asciidoc, x-pack/elastic-agent/docs/uninstall-elastic-agent.asciidoc
Fixes a few minor issues found during testing. 
Also adds `sudo` to the command examples to be explicit.
Please respond to any questions flagged with //REVIEWERS.
=> Add fixes from testing on deb/rpm

x-pack/elastic-agent/docs/elastic-agent-configuration.asciidoc, x-pack/elastic-agent/docs/elastic-agent.asciidoc, x-pack/elastic-agent/docs/install-elastic-agent.asciidoc, x-pack/elastic-agent/docs/run-elastic-agent-standalone.asciidoc, x-pack/elastic-agent/docs/tab-widgets/install-layout.asciidoc, x-pack/elastic-agent/docs/tab-widgets/install.asciidoc, x-pack/elastic-agent/docs/tab-widgets/run-standalone.asciidoc, x-pack/elastic-agent/docs/uninstall-elastic-agent.asciidoc
- Add fixes from testing on deb/rpm (#22667)
=> Cherry-pick to 7.x: Add fixes from testing on deb/rpm (#22667)

x-pack/elastic-agent/docs/elastic-agent-configuration.asciidoc, x-pack/elastic-agent/docs/elastic-agent.asciidoc, x-pack/elastic-agent/docs/install-elastic-agent.asciidoc, x-pack/elastic-agent/docs/run-elastic-agent-standalone.asciidoc, x-pack/elastic-agent/docs/tab-widgets/install-layout.asciidoc, x-pack/elastic-agent/docs/tab-widgets/install.asciidoc, x-pack/elastic-agent/docs/tab-widgets/run-standalone.asciidoc, x-pack/elastic-agent/docs/uninstall-elastic-agent.asciidoc
- Add fixes from testing on deb/rpm (#22667)
=> Cherry-pick to 7.10: Add fixes from testing on deb/rpm (#22667)

libbeat/docs/http-endpoint.asciidoc
- [docs][cosmetic] Highlight the pretty option in URL and cURL (#22681)
=> Cherry-pick to 7.x: [docs][cosmetic] Highlight the pretty option in URL and cURL (#22681)

filebeat/docs/howto/howto.asciidoc
=> Missing `>`

winlogbeat/tests/system/test_wineventlog.py
- Flaky Test
Skip `winlogbeat.tests.system.test_wineventlog.Test.test_query_ignore_older` on Windows 7.
Test fails constantly.
- Relates #22753
=> Skip flaky winlogbeat test on Windows-7

filebeat/tests/system/test_udp.py
Follow-up issue: https://github.com/elastic/beats/issues/22809
=> Skip somewhat flaky UDP system test on Windows

filebeat/tests/system/test_udp.py
Cherry-pick of PR #22810 to 7.10 branch. Original message: 
Follow-up issue: https://github.com/elastic/beats/issues/22809
=> Cherry-pick #22810 to 7.10: Skip somewhat flaky UDP system test on Windows

winlogbeat/tests/system/test_wineventlog.py
Cherry-pick of PR #22754 to 7.x branch. Original message: 
- Flaky Test
Skip `winlogbeat.tests.system.test_wineventlog.Test.test_query_ignore_older` on Windows 7.
Test fails constantly.
- Relates #22753
=> Cherry-pick #22754 to 7.x: Skip flaky winlogbeat test on Windows-7

x-pack/elastic-agent/docs/elastic-agent-functions.asciidoc
=> substract->subtract

libbeat/docs/processors-using.asciidoc
=> fix: missing colon in yaml example

.ci/scripts/install-tools.bat, Jenkinsfile
- [CI] prepare windows tooling (#22661)
=> Cherry-pick to 7.10: [CI] prepare windows tooling (#22661)

x-pack/elastic-agent/docs/elastic-agent-functions.asciidoc
Cherry-pick of PR #22841 to 7.10 branch. Original message: 
Small typo
-
=> Cherry-pick #22841 to 7.10: substract->subtract

x-pack/elastic-agent/docs/elastic-agent-functions.asciidoc
Cherry-pick of PR #22841 to 7.x branch. Original message: 
Small typo
-
=> Cherry-pick #22841 to 7.x: substract->subtract

.ci/scripts/generate_build_table.py
Simplify the stage table docs generation with just mandatory or optional when
Easy to read, details are in each Jenkinsfile.yml anyway
=> [CI][docs] generate stages table reference

Jenkinsfile
- [CI] runbld is now deprecated (#22862)
=> Cherry-pick to 7.10: [CI] runbld is now deprecated (#22862)

.ci/scripts/generate_build_table.py
- [CI][docs] generate stages table reference (#22884)
=> Cherry-pick to 7.x: [CI][docs] generate stages table reference (#22884)

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc
(cherry picked from commit 79e4e1e1425bcf740db4308da0d2259182422f43)
=> Fix changelog.next in preparation for 7.10.1 (#22923)

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Close changelog for 7.10.1

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
(cherry picked from commit 16fca728df737a73f5888f44c0589a1125b906b7)
=> docs: Close changelog for 7.10.1 (#22929)

CHANGELOG.next.asciidoc
Add missing changelog for #22137.
=> Add changelog for #22137

CHANGELOG.next.asciidoc, dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl, dev-tools/packaging/templates/docker/Dockerfile.tmpl
Cherry-pick of PR #22137 to 7.x branch. Original message: 
🚧 **Work in progress**, there's probably more to come
This PR introduces init system (`tini` - ref: https://github.com/krallin/tini) for reaping zombie processes and proper signal forwarding. It also enables running processes with non-default UID/GID.  
-
=> Cherry-pick #22137 to 7.x: Introduce proper init system (/bin/tini) to Docker container

x-pack/filebeat/input/httpjson/internal/v2/input.go
Force initial trigger before interval on httpjson v2 input
For big intervals might be confusing for users if they have to wait for all the period while testing or setting up a new config.
-~ [ ] I have made corresponding changes to the documentation~
-~ [ ] I have added tests that prove my fix is effective or that my feature works~
=> [Filebeat][httpjson] Force initial trigger before interval on httpjson v2

CHANGELOG.next.asciidoc, x-pack/filebeat/module/microsoft/m365_defender/config/defender.yml, x-pack/filebeat/module/microsoft/m365_defender/manifest.yml
Uses httpjson v2 for m365 defender
=> [Filebeat] Migrate m365_defender to httpjson v2

x-pack/filebeat/input/httpjson/internal/v2/input.go
Cherry-pick of PR #23025 to 7.x branch. Original message: 
Force initial trigger before interval on httpjson v2 input
For big intervals might be confusing for users if they have to wait for all the period while testing or setting up a new config.
-~ [ ] I have made corresponding changes to the documentation~
-~ [ ] I have added tests that prove my fix is effective or that my feature works~
=> Cherry-pick #23025 to 7.x: [Filebeat][httpjson] Force initial trigger before interval on httpjson v2

CHANGELOG.next.asciidoc, x-pack/filebeat/module/okta/system/config/input.yml, x-pack/filebeat/module/okta/system/manifest.yml
=> [Filebeat] Migrate okta to httpjson v2 config

x-pack/elastic-agent/CHANGELOG.next.asciidoc
Adds changelog entry for the #22793 pull request
So the changelog is correct.
=> [Elastic Agent] Add changelog entry for metrics collection

x-pack/elastic-agent/docs/install-elastic-agent.asciidoc
Fixes link to quick start topic.
=> Fix link to quick start

libbeat/scripts/generate_fields_docs.py
Fixes the logic to assign ✅ to ECS fields in APM Server docs.
This produces exactly this diff: https://github.com/elastic/apm-server/compare/master...jalvz:fixed-ecs-badges
https://github.com/elastic/apm-server/issues/4554
=> Fix ECS badges in fields for apm server docs

libbeat/scripts/generate_fields_docs.py
- fix ECS badges in fields for apm server docs (#23188)
=> Cherry-pick to 7.x: fix ECS badges in fields for apm server docs (#23188)

libbeat/scripts/generate_fields_docs.py
- fix ECS badges in fields for apm server docs (#23188)
=> Cherry-pick to 7.10: fix ECS badges in fields for apm server docs (#23188)

libbeat/docs/monitoring/monitoring-metricbeat.asciidoc
- Update monitoring-metricbeat.asciidoc (#21863)
=> Cherry-pick to 7.11: Update monitoring-metricbeat.asciidoc (#21863)

libbeat/docs/monitoring/monitoring-metricbeat.asciidoc
- Update monitoring-metricbeat.asciidoc (#21863)
=> Cherry-pick to 7.10: Update monitoring-metricbeat.asciidoc (#21863)

libbeat/docs/monitoring/monitoring-metricbeat.asciidoc
- Update monitoring-metricbeat.asciidoc (#21863)
=> Cherry-pick to 7.x: Update monitoring-metricbeat.asciidoc (#21863)

filebeat/docs/modules/google_workspace.asciidoc, x-pack/filebeat/module/google_workspace/_meta/docs.asciidoc
Remove unused option docs and add missing ones from google_workspace docs.
=> [Filebeat] Remove unused option and add missing one in google_workspace docs

filebeat/docs/modules/google_workspace.asciidoc, x-pack/filebeat/module/google_workspace/_meta/docs.asciidoc
Cherry-pick of PR #23278 to 7.x branch. Original message: 
Remove unused option docs and add missing ones from google_workspace docs.
=> Cherry-pick #23278 to 7.x: [Filebeat] Remove unused option and add missing one in google_workspace docs

auditbeat/module/file_integrity/metricset_test.go
Cherry-pick of PR #22514 to 7.x branch. Original message: 
- Flaky Test
- Setup files/environment before running the test
- reduce chance of races, especially with very slow/overloaded CI workers
- fix t.Fatal being called from spawned go-routine (big NO NO)
- collect all found paths into a dictionary and assert wanted vs. found
paths after
- now checks for expected files that have not been found (semantic change)
- assert will now print a 'diff' with missing/unknown paths on error
The changes hopefully stabilize the flaky test (although the failure rate seems to be quite low already).
The failed will now print a diff if expected vs. seen files. Maybes this helps to better understand the failure in the future. …
=> Cherry-pick #22514 to 7.x: Try to stabilize TestIncludesExcludes

deploy/kubernetes/heartbeat-kubernetes.yaml
=> Fix hearbeat version in kubernetes manifests in 7.10 branch

libbeat/autodiscover/autodiscover_test.go
=> Skip flaky TestAutodiscoverWithMutlipleEntries test

filebeat/docs/modules/okta.asciidoc, x-pack/filebeat/module/okta/_meta/docs.asciidoc
Cherry-pick of PR #23065 to 7.x branch. Original message: 
PR updates documentation. 
For people new to Beats and sometimes YAML, correct configuration reference is important. 
- [ x] I have made corresponding changes to the documentation
-
=> Cherry-pick #23065 to 7.x: Fix YAML syntax in module instantiation example

filebeat/docs/modules/okta.asciidoc, x-pack/filebeat/module/okta/_meta/docs.asciidoc
Cherry-pick of PR #23065 to 7.11 branch. Original message: 
PR updates documentation. 
For people new to Beats and sometimes YAML, correct configuration reference is important. 
- [ x] I have made corresponding changes to the documentation
-
=> Cherry-pick #23065 to 7.11: Fix YAML syntax in module instantiation example

CHANGELOG-developer.next.asciidoc, CHANGELOG.next.asciidoc
- Changelog
Move changelog entry to developer changelog.
The original PR did introduce an internal API for adding custom HTTP handler, but no user-visible feature.
=> Move changelog entry to correct file

filebeat/docs/modules/okta.asciidoc, x-pack/filebeat/module/okta/_meta/docs.asciidoc
Cherry-pick of PR #23065 to 7.10 branch. Original message: 
PR updates documentation. 
For people new to Beats and sometimes YAML, correct configuration reference is important. 
- [ x] I have made corresponding changes to the documentation
-
=> Cherry-pick #23065 to 7.10: Fix YAML syntax in module instantiation example

libbeat/publisher/pipeline/output_test.go
Cherry-pick of PR #20366 to 7.x branch. Original message: 
- Flaky test
Add some more debug testing to check where events get lost in the test.
-
=> Cherry-pick #20366 to 7.x: Pipeline client test log progress

x-pack/filebeat/module/mysqlenterprise/audit/ingest/pipeline.yml, x-pack/filebeat/module/mysqlenterprise/audit/test/mysql_audit_test.log-expected.json
Fixes a flaky test due to issues with date format in ingest pipeline
Resolves flaky tests from master
=> [Filebeat] Fixing test logs for mysqlenterprise and changing date format

libbeat/docs/monitoring/monitoring-metricbeat.asciidoc
=> Update monitoring-metricbeat.asciidoc (#21863)

Jenkinsfile, dev-tools/packaging/templates/docker/Dockerfile.tmpl
Fix heartbeat build and launch packaging jobs when packaging files
change to detect these issues.
Packaging jobs should be launched for this change.
=> Fix heartbeat build

CHANGELOG.next.asciidoc, metricbeat/module/windows/_meta/config.yml, metricbeat/modules.d/windows.yml.disabled
Update default config in `windows.yml` file
Updates default config in `windows.yml`, previous config is invalid
- Closes https://github.com/elastic/beats/issues/23027
=> Update default config in windows.yml

CHANGELOG.next.asciidoc, x-pack/functionbeat/config/config.go, x-pack/functionbeat/config/config_test.go, x-pack/functionbeat/manager/aws/template_builder.go
Cherry-pick of PR #21065 to 7.x branch. Original message: 
This PR adds support for deploying functionbeat in multiple regions. 
Teams can deploy the functionbeat in multiple regions and 
- Closes #16935
=> Cherry-pick #21065 to 7.x: add support for multiple regions

CHANGELOG.asciidoc, libbeat/docs/release.asciidoc
* docs: Close changelog for 7.10.2
* Apply suggestions from code review
Co-authored-by: Brandon Morelli <brandon.morelli@elastic.co>
* Remove empty sections
Co-authored-by: Andres Rodriguez <andres.rodriguez@elastic.co>
Co-authored-by: Brandon Morelli <brandon.morelli@elastic.co>
Co-authored-by: Andres Rodriguez <andresrc@gmail.com>
(cherry picked from commit 2de6d8a7364d1e5dd5b37d9dd2b34eababe76f0d)
-
=> Forward port 7.10.2 changelog to 7.x

CHANGELOG.next.asciidoc, metricbeat/module/windows/_meta/config.yml, metricbeat/modules.d/windows.yml.disabled
Cherry-pick of PR #23327 to 7.x branch. Original message: 
Update default config in `windows.yml` file
Updates default config in `windows.yml`, previous config is invalid
- Closes https://github.com/elastic/beats/issues/23027
=> Cherry-pick #23327 to 7.x: Update default config in windows.yml

CHANGELOG.next.asciidoc, metricbeat/module/windows/_meta/config.yml, metricbeat/modules.d/windows.yml.disabled
Cherry-pick of PR #23327 to 7.11 branch. Original message: 
Update default config in `windows.yml` file
Updates default config in `windows.yml`, previous config is invalid
- Closes https://github.com/elastic/beats/issues/23027
=> Cherry-pick #23327 to 7.11: Update default config in windows.yml

metricbeat/Jenkinsfile.yml
- Closes https://github.com/elastic/beats/issues/19800
=> Fix flaky tests for Metricbeat on Windows 2008 R2

x-pack/metricbeat/module/awsfargate/task_stats/_meta/docs.asciidoc
This PR is to improve `awsfargate` documentation with the new CloudFormation template, AWS CLI command and Kibana dashboard screenshot.
=> Update awsfargate documentation

x-pack/metricbeat/module/awsfargate/task_stats/_meta/docs.asciidoc
Cherry-pick of PR #23468 to 7.x branch. Original message: 
This PR is to improve `awsfargate` documentation with the new CloudFormation template, AWS CLI command and Kibana dashboard screenshot.
=> Cherry-pick #23468 to 7.x: Update awsfargate documentation

x-pack/metricbeat/module/awsfargate/task_stats/_meta/docs.asciidoc
Cherry-pick of PR #23468 to 7.11 branch. Original message: 
This PR is to improve `awsfargate` documentation with the new CloudFormation template, AWS CLI command and Kibana dashboard screenshot.
=> Cherry-pick #23468 to 7.11: Update awsfargate documentation

CHANGELOG.asciidoc, libbeat/docs/release.asciidoc
=> Forward port 7.10.2 changelog to master

metricbeat/Jenkinsfile.yml
Cherry-pick of PR #23490 to 7.x branch. Original message: 
- Closes https://github.com/elastic/beats/issues/19800
=> Cherry-pick #23490 to 7.x: Fix flaky tests for Metricbeat on Windows 2008 R2

metricbeat/Jenkinsfile.yml
Cherry-pick of PR #23490 to 7.11 branch. Original message: 
- Closes https://github.com/elastic/beats/issues/19800
=> Cherry-pick #23490 to 7.11: Fix flaky tests for Metricbeat on Windows 2008 R2

Jenkinsfile
- [CI] Run make notice linting (#23553)
=> Cherry-pick to 7.x: [CI] Run make notice linting (#23553)

x-pack/metricbeat/module/cloudfoundry/v1.go
Subscriptions to events and events are managed in the same loop in
the same goroutine, so when doing black box testing of the metricset
it is not possible to know if the subscription is configured before starting
to dispatch events. If an event is handled before its subscription is
configured, the event is lost, what leads to flakiness with failures like this one:
```
=== RUN   TestMetricSet
counter_test.go:58: 
Error Trace:	counter_test.go:58
Error:      	Should NOT be empty, but was []
Test:       	TestMetricSet
--- FAIL: TestMetricSet (10.00s)
```
This change ensures that the subscription is configured before starting
the event loop, so all events are handled.
=> Start doppler consumer loop only after a subscription is configured

x-pack/elastic-agent/CHANGELOG.next.asciidoc, x-pack/elastic-agent/pkg/core/server/server.go
Cherry-pick of PR #23568 to 7.x branch. Original message: 
Increase the checkin grace period from 2 seconds to 30 seconds.
Because the grace period is 2 seconds, it is possible that on a system that has enough load that between Agent and Endpoint checking in, it's possible that the grace period is not enough. Increasing the grace period doesn't really cause a negative effect, so its better to increase it so on systems with load degraded does not occur just because the process missed check-in by 2 seconds.
- ~~[ ] I have added tests that prove my fix is effective or that my …
=> Cherry-pick #23568 to 7.x: [Elastic Agent] Increase checkin grace period.

x-pack/elastic-agent/CHANGELOG.next.asciidoc, x-pack/elastic-agent/pkg/core/server/server.go
Cherry-pick of PR #23568 to 7.11 branch. Original message: 
Increase the checkin grace period from 2 seconds to 30 seconds.
Because the grace period is 2 seconds, it is possible that on a system that has enough load that between Agent and Endpoint checking in, it's possible that the grace period is not enough. Increasing the grace period doesn't really cause a negative effect, so its better to increase it so on systems with load degraded does not occur just because the process missed check-in by 2 seconds.
- ~~[ ] I have added tests that prove my fix is effective or that …
=> Cherry-pick #23568 to 7.11: [Elastic Agent] Increase checkin grace period.

metricbeat/docker-compose.yml, metricbeat/module/logstash/docker-compose.yml, testing/environments/latest.yml, testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml, x-pack/metricbeat/docker-compose.yml
Update test environments to next minor 7.12.0.
Merge after create the new release branch.
=> chore: update test env next minor 7.12.0

CHANGELOG.next.asciidoc, metricbeat/docs/modules/elasticsearch.asciidoc, metricbeat/module/elasticsearch/_meta/docs.asciidoc
Backports https://github.com/elastic/beats/pull/23286
=> [7.x][DOCS] Re-add Stack Monitoring section in elasticsearch module (#23286)

x-pack/elastic-agent/pkg/agent/operation/operator_test.go
Issue: https://github.com/elastic/beats/issues/23607
=> Skip flaky TestConfigurableService in agent

x-pack/metricbeat/module/cloudfoundry/v1.go
Cherry-pick of PR #23584 to 7.x branch. Original message: 
Subscriptions to events and events are managed in the same loop in
the same goroutine, so when doing black box testing of the metricset
it is not possible to know if the subscription is configured before starting
to dispatch events. If an event is handled before its subscription is
configured, the event is lost, what leads to flakiness with failures like this one:
```
=== RUN   TestMetricSet
counter_test.go:58: 
Error Trace:	counter_test.go:58
Error:      	Should NOT be empty, but was []
Test:       	TestMetricSet
--- FAIL: TestMetricSet (10.00s)
```
This change ensures that the subscription is configured before starting
the event loop, so all events are handled.
=> Cherry-pick #23584 to 7.x: Start doppler consumer loop only after a subscription is configured

x-pack/metricbeat/module/cloudfoundry/v1.go
Cherry-pick of PR #23584 to 7.11 branch. Original message: 
Subscriptions to events and events are managed in the same loop in
the same goroutine, so when doing black box testing of the metricset
it is not possible to know if the subscription is configured before starting
to dispatch events. If an event is handled before its subscription is
configured, the event is lost, what leads to flakiness with failures like this one:
```
=== RUN   TestMetricSet
counter_test.go:58: 
Error Trace:	counter_test.go:58
Error:      	Should NOT be empty, but was []
Test:       	TestMetricSet
--- FAIL: TestMetricSet (10.00s)
```
This change ensures that the subscription is configured before starting
the event loop, so all events are handled.
=> Cherry-pick #23584 to 7.11: Start doppler consumer loop only after a subscription is configured

metricbeat/module/windows/perfmon/data_test.go
=> Fix for data_test in perfmon

metricbeat/module/windows/perfmon/data_test.go
Cherry-pick of PR #23617 to 7.x branch. Original message:
=> Cherry-pick #23617 to 7.x: Fix for data_test in perfmon

.ci/packaging.groovy
It always sets to true the boolean parameter used to trigger the E2E tests from the packaging job.
We want to use them for PRs and for merges to branches, otherwise a merge-to-branch commit will trigger the tests and instead of consuming the artifacts generated by the Beats commit, will use the published snapshot, which could not be up-to-date.
=> [CI] chore: always use CI snapshots

x-pack/filebeat/module/cisco/asa/test/additional_messages.log-expected.json, x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml
Cherry-pick of PR #23092 to 7.x branch. Original message: 
cisco/add adding message id 302023
This PR will add parsing for cisco asa message id 302023.
This will add a common message for cisco asa clusters
- 
 
--
%ASA-6-302022: Built backup stub TCP connection for INTERNET:1.1.1.1/57475 (1.1.1.1/57475) to INTERN:1.2.3.4/443 (1.2.3.4/443)
  |  
=> Cherry-pick #23092 to 7.x: [Filebeat] Add Cisco ASA message '302023' parsing

x-pack/packetbeat/packetbeat.reference.yml, x-pack/packetbeat/packetbeat.yml
Fixes broken build caused by out-of-date config files from https://github.com/elastic/beats/pull/22584.
- Relates https://github.com/elastic/beats/pull/22584
=> Update X-Pack Packetbeat config

filebeat/docs/running-on-kubernetes.asciidoc, libbeat/docs/howto/load-dashboards.asciidoc, libbeat/docs/shared-cloudfoundry.asciidoc, libbeat/docs/tab-widgets/load-dashboards-logstash-widget.asciidoc, libbeat/docs/tab-widgets/load-dashboards-logstash.asciidoc, libbeat/docs/tab-widgets/load-dashboards-widget.asciidoc, libbeat/docs/tab-widgets/load-dashboards.asciidoc, metricbeat/docs/running-on-kubernetes.asciidoc
- [DOCS] Add setup content to Kubernetes and Cloud Foundry docs (#23580)
=> Cherry-pick to 7.10: [DOCS] Add setup content to Kubernetes and Cloud Foundry docs (#23580)

filebeat/docs/running-on-kubernetes.asciidoc, libbeat/docs/howto/load-dashboards.asciidoc, libbeat/docs/shared-cloudfoundry.asciidoc, libbeat/docs/tab-widgets/load-dashboards-logstash-widget.asciidoc, libbeat/docs/tab-widgets/load-dashboards-logstash.asciidoc, libbeat/docs/tab-widgets/load-dashboards-widget.asciidoc, libbeat/docs/tab-widgets/load-dashboards.asciidoc, metricbeat/docs/running-on-kubernetes.asciidoc
- [DOCS] Add setup content to Kubernetes and Cloud Foundry docs (#23580)
=> Cherry-pick to 7.11: [DOCS] Add setup content to Kubernetes and Cloud Foundry docs (#23580)

.ci/scripts/generate_build_table.py, auditbeat/Jenkinsfile.yml, filebeat/Jenkinsfile.yml, heartbeat/Jenkinsfile.yml, metricbeat/Jenkinsfile.yml, packetbeat/Jenkinsfile.yml, winlogbeat/Jenkinsfile.yml, x-pack/auditbeat/Jenkinsfile.yml, x-pack/elastic-agent/Jenkinsfile.yml, x-pack/filebeat/Jenkinsfile.yml, x-pack/functionbeat/Jenkinsfile.yml, x-pack/metricbeat/Jenkinsfile.yml, x-pack/packetbeat/Jenkinsfile.yml, x-pack/winlogbeat/Jenkinsfile.yml
- [CI] Mandatory windows support for all the versions (#23615)
=> Cherry-pick to 7.11: [CI] Mandatory windows support for all the versions (#23615)

.ci/scripts/generate_build_table.py, auditbeat/Jenkinsfile.yml, filebeat/Jenkinsfile.yml, heartbeat/Jenkinsfile.yml, metricbeat/Jenkinsfile.yml, packetbeat/Jenkinsfile.yml, winlogbeat/Jenkinsfile.yml, x-pack/auditbeat/Jenkinsfile.yml, x-pack/elastic-agent/Jenkinsfile.yml, x-pack/filebeat/Jenkinsfile.yml, x-pack/functionbeat/Jenkinsfile.yml, x-pack/metricbeat/Jenkinsfile.yml, x-pack/packetbeat/Jenkinsfile.yml, x-pack/winlogbeat/Jenkinsfile.yml
- [CI] Mandatory windows support for all the versions (#23615)
=> Cherry-pick to 7.10: [CI] Mandatory windows support for all the versions (#23615)

.ci/scripts/generate_build_table.py, auditbeat/Jenkinsfile.yml, filebeat/Jenkinsfile.yml, heartbeat/Jenkinsfile.yml, metricbeat/Jenkinsfile.yml, packetbeat/Jenkinsfile.yml, winlogbeat/Jenkinsfile.yml, x-pack/auditbeat/Jenkinsfile.yml, x-pack/elastic-agent/Jenkinsfile.yml, x-pack/filebeat/Jenkinsfile.yml, x-pack/functionbeat/Jenkinsfile.yml, x-pack/metricbeat/Jenkinsfile.yml, x-pack/packetbeat/Jenkinsfile.yml, x-pack/winlogbeat/Jenkinsfile.yml
- [CI] Mandatory windows support for all the versions (#23615)
=> Cherry-pick to 7.x: [CI] Mandatory windows support for all the versions (#23615)

heartbeat/docs/getting-started.asciidoc, metricbeat/docs/modules/kubernetes.asciidoc, metricbeat/module/kubernetes/_meta/docs.asciidoc
=> Cherry-pick to 7.x: Minor updates (#23712)

heartbeat/docs/getting-started.asciidoc, metricbeat/docs/modules/kubernetes.asciidoc, metricbeat/module/kubernetes/_meta/docs.asciidoc
=> Cherry-pick to 7.10: Minor updates (#23712)

heartbeat/docs/getting-started.asciidoc, metricbeat/docs/modules/kubernetes.asciidoc, metricbeat/module/kubernetes/_meta/docs.asciidoc
=> Cherry-pick to 7.11: Minor updates (#23712)

x-pack/elastic-agent/pkg/core/plugin/process/start.go
=> [7.x][Fleet] support log level warning for beat (#23769)

x-pack/elastic-agent/pkg/core/plugin/process/start.go
=> [7.11][Fleet] support log level warning for beat (#23769)

libbeat/processors/actions/docs/truncate_fields.asciidoc
Added indentation to the fields from `fields:`.
`fields`, `max_characters`, ... in the the example should have more indentation to prevent an error similar to `Exiting: error initializing processors: each processor must have exactly one action, but found 3 actions (max_characters,truncate_fields,fields)`
-
=> fixed indentation in the example

metricbeat/docs/modules/system.asciidoc, metricbeat/module/system/_meta/docs.asciidoc
- Update system.asciidoc (#23322)
=> Cherry-pick to master: Update system.asciidoc (#23322)

x-pack/filebeat/module/google_workspace/admin/config/config.yml, x-pack/filebeat/module/google_workspace/drive/config/config.yml, x-pack/filebeat/module/google_workspace/groups/config/config.yml, x-pack/filebeat/module/google_workspace/login/config/config.yml, x-pack/filebeat/module/google_workspace/saml/config/config.yml, x-pack/filebeat/module/google_workspace/user_accounts/config/config.yml
[fix] Google_workplace api call fails. #23851
[fix] Google_workspace config validation fails #23853
- ~~[] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~
Closes #23851
Closes #23853
=> [fix] Google_workplace api call fails. #23851

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 7.11.0

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
* docs: Close changelog for 7.11.0
* Revert changes not included in BC
* Remove empty sections
* Apply suggestions from code review
Co-authored-by: Brandon Morelli <brandon.morelli@elastic.co>
* Apply suggestions from code review
Co-authored-by: Brandon Morelli <brandon.morelli@elastic.co>
Co-authored-by: Andres Rodriguez <andresrc@gmail.com>
Co-authored-by: Andres Rodriguez <andres.rodriguez@elastic.co>
Co-authored-by: Brandon Morelli <brandon.morelli@elastic.co>
(cherry picked from commit beea82d459d36421946f03727a03aa26441d4f01)
-
=> Forward-port 7.11.0 changelog to 7.x

x-pack/filebeat/module/google_workspace/admin/config/config.yml, x-pack/filebeat/module/google_workspace/drive/config/config.yml, x-pack/filebeat/module/google_workspace/groups/config/config.yml, x-pack/filebeat/module/google_workspace/login/config/config.yml, x-pack/filebeat/module/google_workspace/saml/config/config.yml, x-pack/filebeat/module/google_workspace/user_accounts/config/config.yml
Cherry-pick of PR #23855 to 7.x branch. Original message: 
[fix] Google_workplace api call fails. #23851
[fix] Google_workspace config validation fails #23853
- ~~[] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~
Closes #23851
Closes #23853
=> Cherry-pick #23855 to 7.x: [fix] Google_workplace api call fails. #23851

x-pack/filebeat/module/google_workspace/admin/config/config.yml, x-pack/filebeat/module/google_workspace/drive/config/config.yml, x-pack/filebeat/module/google_workspace/groups/config/config.yml, x-pack/filebeat/module/google_workspace/login/config/config.yml, x-pack/filebeat/module/google_workspace/saml/config/config.yml, x-pack/filebeat/module/google_workspace/user_accounts/config/config.yml
Cherry-pick of PR #23855 to 7.11 branch. Original message: 
[fix] Google_workplace api call fails. #23851
[fix] Google_workspace config validation fails #23853
- ~~[] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~
Closes #23851
Closes #23853
=> Cherry-pick #23855 to 7.11: [fix] Google_workplace api call fails. #23851

libbeat/processors/script/docs/script.asciidoc
There's a bracket missing for the event object.
Fix example code
Want to remove friction for new comers.
-
=> Missing bracket in test function

libbeat/docs/release-notes/breaking/breaking-7.11.asciidoc, libbeat/docs/release-notes/breaking/breaking.asciidoc
Closes #23942
Let me know if there are any BCs that we want to highlight in this file. Usually we highlight BCs that are likely to affect customers who are upgrading. This info gets percolated up into the upgrade docs for the stack.
=> Add breaking changes file for 7.11

metricbeat/docs/modules/appsearch.asciidoc, x-pack/metricbeat/module/appsearch/_meta/docs.asciidoc
=> Cherry-pick to 7.x: Add note (#23935)

metricbeat/docs/modules/appsearch.asciidoc, x-pack/metricbeat/module/appsearch/_meta/docs.asciidoc
=> Cherry-pick to 7.10: Add note (#23935)

metricbeat/docs/modules/appsearch.asciidoc, x-pack/metricbeat/module/appsearch/_meta/docs.asciidoc
=> Cherry-pick to 7.11: Add note (#23935)

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 6.8.14.
=> docs: update docs versions 6.8.14

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 7.11.1

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
cherry-picks: 965da41d3d1a0b37c99f34524ac6dd0d3c4ba8db
=> docs: Forward port Changelog for 7.11.1 to 7.x (#24010)

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
cherry-picks: 965da41d3d1a0b37c99f34524ac6dd0d3c4ba8db
=> docs: Forward port Changelog for 7.11.1 to master (#24010)

CHANGELOG.next.asciidoc, x-pack/filebeat/module/okta/system/config/input.yml
Cherry-pick of PR #24025 to 7.11 branch. Original message: 
Fixes #24018
=> Cherry-pick #24025 to 7.11: [fix][filebeat] Fix okta default date in module config

CHANGELOG.next.asciidoc, x-pack/filebeat/module/okta/system/config/input.yml
Cherry-pick of PR #24025 to 7.x branch. Original message: 
Fixes #24018
=> Cherry-pick #24025 to 7.x: [fix][filebeat] Fix okta default date in module config

.backportrc.json
Merge after the release 7.11.1.
=> backport: remove 7.10 branch 

x-pack/elastic-agent/magefile.go
Cherry-pick of PR #24060 to 7.x branch. Original message:
=> Cherry-pick #24060 to 7.x: Only build targz and zip versions of Beats if PACKAGES is set in agent

x-pack/filebeat/module/threatintel/anomali/config/config.yml, x-pack/filebeat/module/threatintel/anomali/manifest.yml, x-pack/filebeat/module/threatintel/anomali/test/anomali_limo.ndjson.log-expected.json, x-pack/filebeat/module/threatintel/misp/config/config.yml, x-pack/filebeat/module/threatintel/otx/config/config.yml, x-pack/filebeat/module/threatintel/otx/manifest.yml
Fixes some issues with manifest and config templates for certain threatintel modules.
Fixes some issues with manifest and config templates for certain threatintel modules.
=> updating manifest files for filebeat threatintel module

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 7.11.1.
=> docs: update docs versions 7.11.1

.ci/scripts/install-docker-compose.sh
- [CI] install docker-compose with retry (#24069)
=> Cherry-pick to 7.x: [CI] install docker-compose with retry (#24069)

.backportrc.json
Merge after the release 7.12.0.
=> backport: Add 7.12 branch

filebeat/docs/modules/threatintel.asciidoc, x-pack/filebeat/filebeat.reference.yml, x-pack/filebeat/module/threatintel/_meta/config.yml, x-pack/filebeat/module/threatintel/_meta/docs.asciidoc, x-pack/filebeat/module/threatintel/abusemalware/config/config.yml, x-pack/filebeat/module/threatintel/abusemalware/test/abusechmalware.ndjson.log-expected.json, x-pack/filebeat/module/threatintel/abuseurl/config/config.yml, x-pack/filebeat/module/threatintel/abuseurl/test/abusechurl.ndjson.log-expected.json, x-pack/filebeat/module/threatintel/anomali/config/config.yml, x-pack/filebeat/module/threatintel/anomali/ingest/pipeline.yml, x-pack/filebeat/module/threatintel/anomali/test/anomali_limo.ndjson.log-expected.json, x-pack/filebeat/module/threatintel/misp/config/config.yml, x-pack/filebeat/module/threatintel/misp/ingest/pipeline.yml, x-pack/filebeat/module/threatintel/misp/test/misp_sample.ndjson.log-expected.json, x-pack/filebeat/module/threatintel/otx/config/config.yml, x-pack/filebeat/module/threatintel/otx/ingest/pipeline.yml, x-pack/filebeat/module/threatintel/otx/manifest.yml, x-pack/filebeat/module/threatintel/otx/test/otx_sample.ndjson.log-expected.json, x-pack/filebeat/modules.d/threatintel.yml.disabled
Cherry-pick of PR #24133 to 7.x branch. Original message: 
Cleaning up the TI module based on feedback after testing the BC runs.
Cleaning up the TI module based on feedback after testing the BC runs.
=> Cherry-pick #24133 to 7.x: [Filebeat] Adding fixes to the TI module

filebeat/docs/modules/threatintel.asciidoc, x-pack/filebeat/filebeat.reference.yml, x-pack/filebeat/module/threatintel/_meta/config.yml, x-pack/filebeat/module/threatintel/_meta/docs.asciidoc, x-pack/filebeat/module/threatintel/abusemalware/config/config.yml, x-pack/filebeat/module/threatintel/abusemalware/test/abusechmalware.ndjson.log-expected.json, x-pack/filebeat/module/threatintel/abuseurl/config/config.yml, x-pack/filebeat/module/threatintel/abuseurl/test/abusechurl.ndjson.log-expected.json, x-pack/filebeat/module/threatintel/anomali/config/config.yml, x-pack/filebeat/module/threatintel/anomali/ingest/pipeline.yml, x-pack/filebeat/module/threatintel/anomali/test/anomali_limo.ndjson.log-expected.json, x-pack/filebeat/module/threatintel/misp/config/config.yml, x-pack/filebeat/module/threatintel/misp/ingest/pipeline.yml, x-pack/filebeat/module/threatintel/misp/test/misp_sample.ndjson.log-expected.json, x-pack/filebeat/module/threatintel/otx/config/config.yml, x-pack/filebeat/module/threatintel/otx/ingest/pipeline.yml, x-pack/filebeat/module/threatintel/otx/manifest.yml, x-pack/filebeat/module/threatintel/otx/test/otx_sample.ndjson.log-expected.json, x-pack/filebeat/modules.d/threatintel.yml.disabled
Cherry-pick of PR #24133 to 7.12 branch. Original message: 
Cleaning up the TI module based on feedback after testing the BC runs.
Cleaning up the TI module based on feedback after testing the BC runs.
=> Cherry-pick #24133 to 7.12: [Filebeat] Adding fixes to the TI module

Jenkinsfile, auditbeat/Jenkinsfile.yml, filebeat/Jenkinsfile.yml, heartbeat/Jenkinsfile.yml, journalbeat/Jenkinsfile.yml, metricbeat/Jenkinsfile.yml, packetbeat/Jenkinsfile.yml, x-pack/auditbeat/Jenkinsfile.yml, x-pack/dockerlogbeat/Jenkinsfile.yml, x-pack/elastic-agent/Jenkinsfile.yml, x-pack/filebeat/Jenkinsfile.yml, x-pack/heartbeat/Jenkinsfile.yml, x-pack/metricbeat/Jenkinsfile.yml, x-pack/packetbeat/Jenkinsfile.yml
- [CI] Add ARM packaging (#24041)
=> Cherry-pick to 7.12: [CI] Add ARM packaging (#24041)

x-pack/libbeat/docs/aws-credentials-config.asciidoc
This PR is to improve documentation on running aws module on docker.
closes: https://github.com/elastic/beats/issues/24073
=> Add running aws module on docker doc

filebeat/docs/modules/threatintel.asciidoc, x-pack/filebeat/module/threatintel/_meta/docs.asciidoc
Spotted several formatting issues while browsing the docs.
=> [Filebeat] Format and spell check Threat Intel module docs

x-pack/metricbeat/module/cockroachdb/_meta/kibana/7/dashboard/Metricbeat-cockroachdb-overview.json, x-pack/metricbeat/module/cockroachdb/_meta/kibana/7/dashboard/Metricbeat-cockroachdb-sql.json
In CockroachDB Metricbeat module:
- Clean / Improve visualization titles in "Overall" dashboard.
- Create new "SQL" dashboard
- Remove Cluster filter that wasn't often used.
Checks:
- ~~[x] I have added tests that prove my fix is effective or that my feature works~~
@sorantis you might want to quickly take a look at the screenshots
- Closes https://github.com/elastic/beats/issues/22981
=> [Metricbeat] Update Cockroachdb Overview and add SQL dashboard

filebeat/docs/modules/threatintel.asciidoc, x-pack/filebeat/module/threatintel/_meta/docs.asciidoc
Cherry-pick of PR #24140 to 7.x branch. Original message: 
Spotted several formatting issues while browsing the docs.
=> Cherry-pick #24140 to 7.x: [Filebeat] Format and spell check Threat Intel module docs

.ci/packaging.groovy
It simplifies the usage of the E2E after elastic/e2e-testing#849, renaming ELASTIC_AGENT_VERSION and METRICBEAT_VERSION to simply BEAT_VERSION.
KISS
- Depends on elastic/e2e-testing#849
=> chore(ci): rename variable for E2E tests

x-pack/metricbeat/Jenkinsfile.yml
This PR disables the Windows 7 32 bit builder.
The builder continuously fails building with `panic: Not enough storage is available to process this command.`
- https://github.com/elastic/beats/issues/24337
=> x-pack/metricbeat: Disable Windows 7 32 bit builder

CHANGELOG.next.asciidoc, heartbeat/monitors/factory.go, heartbeat/monitors/factory_test.go, heartbeat/monitors/stdfields/unnest.go, heartbeat/monitors/stdfields/unnest_test.go, libbeat/processors/add_data_stream_index/add_data_stream_index.go, libbeat/processors/add_data_stream_index/add_data_stream_index_test.go, libbeat/processors/add_data_stream_index/datastream.go, x-pack/heartbeat/monitors/browser/synthexec/enrich.go, x-pack/heartbeat/sample-synthetics-config/heartbeat.yml
- [Heartbeat] Handle data streams (#24223)
=> Cherry-pick to 7.x: [Heartbeat] Handle data streams (#24223)

x-pack/elastic-agent/pkg/agent/cmd/container.go
Cherry-pick of PR #24319 to 7.x branch. Original message: 
Fixes an issue with the new `container` sub-command. It was not handling the naming of the enrollment tokens correctly and when not running without Fleet Server the `api_key` is not returned in the listing, requiring a detailed fetch to retrieve it.
So usage of the Elastic Agent container on 7.13 works.
- Closes #24310
=> Cherry-pick #24319 to 7.x: [Elastic Agent] Fix issues with enrollment key fetching

x-pack/elastic-agent/pkg/agent/cmd/container.go
* fix fallback ENV vars for Elasticsearch
~* remove typo for --fleet-server--insecure-http~ fixed in https://github.com/elastic/beats/pull/24386
fixes #24383
=> [docker][elastic-agent] minor fixes for setup

x-pack/elastic-agent/pkg/agent/cmd/container.go
- [docker][elastic-agent] minor fixes for setup (#24384)
=> Cherry-pick to 7.x: [docker][elastic-agent] minor fixes for setup (#24384)

filebeat/docs/modules/pensando.asciidoc, filebeat/module/pensando/_meta/docs.asciidoc, filebeat/module/pensando/_meta/kibana/7/dashboard/pensando-dfw-overview.json
Removes TODO statement from docs and fixes a visualization from Pensando's dashboard.
=> [Filebeat] Fix pensando viz

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 7.11.2

filebeat/docs/modules/pensando.asciidoc, filebeat/module/pensando/_meta/docs.asciidoc, filebeat/module/pensando/_meta/kibana/7/dashboard/pensando-dfw-overview.json
Cherry-pick of PR #24275 to 7.x branch. Original message: 
Removes TODO statement from docs and fixes a visualization from Pensando's dashboard.
=> Cherry-pick #24275 to 7.x: [Filebeat] Fix pensando viz

filebeat/docs/modules/pensando.asciidoc, filebeat/module/pensando/_meta/docs.asciidoc, filebeat/module/pensando/_meta/kibana/7/dashboard/pensando-dfw-overview.json
Cherry-pick of PR #24275 to 7.12 branch. Original message: 
Removes TODO statement from docs and fixes a visualization from Pensando's dashboard.
=> Cherry-pick #24275 to 7.12: [Filebeat] Fix pensando viz

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 7.11.2.
=> docs: update docs versions 7.11.2

libbeat/docs/loggingconfig.asciidoc
Add syntax for multiple selector logging
=> Add syntax for multiple selector logging

x-pack/metricbeat/Jenkinsfile.yml
Cherry-pick of PR #24339 to 7.x branch. Original message: 
This PR disables the Windows 7 32 bit builder.
The builder continuously fails building with `panic: Not enough storage is available to process this command.`
- https://github.com/elastic/beats/issues/24337
=> Cherry-pick #24339 to 7.x: x-pack/metricbeat: Disable Windows 7 32 bit builder

.ci/packaging.groovy
It does not pass the BEAT_VERSION with the `pr-ID` for PRs, always passing the current value of the `BEAT_VERSION` variable.
Keep code consistent with the e2e, as they moved from a `pr-` based approach to a commit-based one.
- Requires elastic/e2e-testing#866
=> chore(ci): use beat_version instead of PR version

libbeat/docs/shared-ilm.asciidoc
Cherry-pick of PR #24129 to 7.x branch. Original message: 
Clarify docs about `setup.ilm.pattern` to make it clear that just changing the pattern and reloading the policy is not enough for the new pattern to take effect.
To avoid misunderstandings about how to modify the ILM pattern.
- Closes elastic/beats#24111
**Before:**
------
**After (this PR):**
=> Cherry-pick #24129 to 7.x: [ILM][Docs] Clarify how to change setup.ilm.pattern

.github/paths-labeller.yml
This remove the action to tag with "Team:ingest-management" any PR touching the `x-pack/elastic-agent`
directory.
-
=> Do not assign team:ingest-management on x-pack/elastic-agent files

filebeat/input/filestream/environment_test.go
Cherry-pick of PR #24469 to 7.x branch. Original message: 
This PR adds all helper function required by the filestream integration tests.
To have a cleaner test code.
=> Cherry-pick #24469 to 7.x: Add helper functions for filestream integration tests

.ci/scripts/install-tools.bat, Jenkinsfile
- [CI] Add resilience when installing required tooling (#24542)
=> Cherry-pick to 7.11: [CI] Add resilience when installing required tooling (#24542)

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
Forgotten when 7.11.2 was released
=> Forward-port 7.11.2 changelog to 7.12

CHANGELOG.next.asciidoc, x-pack/filebeat/module/google_workspace/admin/config/config.yml, x-pack/filebeat/module/google_workspace/drive/config/config.yml, x-pack/filebeat/module/google_workspace/groups/config/config.yml, x-pack/filebeat/module/google_workspace/login/config/config.yml, x-pack/filebeat/module/google_workspace/saml/config/config.yml, x-pack/filebeat/module/google_workspace/user_accounts/config/config.yml
Fixes date formatting for google workspace pagination.
To properly paginate without errors.
=> Fix Google Workspace pagination

filebeat/input/filestream/input_integration_test.go
=> Increase scan interval to stabilize TestFilestreamCloseRenamed

x-pack/elastic-agent/pkg/agent/application/handler_action_policy_reassign.go, x-pack/elastic-agent/pkg/agent/application/managed_mode.go, x-pack/elastic-agent/pkg/fleetapi/action.go
=> [Fleet] Handle POLICY_REASSIGN action (#24616)

CHANGELOG.next.asciidoc
=> Add missing PR ref to changelog

CHANGELOG.next.asciidoc, x-pack/filebeat/module/google_workspace/admin/config/config.yml, x-pack/filebeat/module/google_workspace/drive/config/config.yml, x-pack/filebeat/module/google_workspace/groups/config/config.yml, x-pack/filebeat/module/google_workspace/login/config/config.yml, x-pack/filebeat/module/google_workspace/saml/config/config.yml, x-pack/filebeat/module/google_workspace/user_accounts/config/config.yml
Cherry-pick of PR #24668 to 7.12 branch. Original message: 
Fixes date formatting for google workspace pagination.
To properly paginate without errors.
=> Cherry-pick #24668 to 7.12: Fix Google Workspace pagination

CHANGELOG.next.asciidoc, x-pack/filebeat/module/google_workspace/admin/config/config.yml, x-pack/filebeat/module/google_workspace/drive/config/config.yml, x-pack/filebeat/module/google_workspace/groups/config/config.yml, x-pack/filebeat/module/google_workspace/login/config/config.yml, x-pack/filebeat/module/google_workspace/saml/config/config.yml, x-pack/filebeat/module/google_workspace/user_accounts/config/config.yml
Cherry-pick of PR #24668 to 7.x branch. Original message: 
Fixes date formatting for google workspace pagination.
To properly paginate without errors.
=> Cherry-pick #24668 to 7.x: Fix Google Workspace pagination

x-pack/elastic-agent/magefile.go, x-pack/elastic-agent/pkg/agent/cmd/container.go
- elastic-agent: add elastic cloud support to docker image (#24558)
=> Cherry-pick to 7.x: elastic-agent: add elastic cloud support to docker image (#24558)

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 6.8.15.
=> docs: update docs versions 6.8.15

Jenkinsfile
* It adds a login to DockerHub on a node that supports Docker.
We start to see `quota rate limit` errors accessing to DockerHub registry, this change forced CI to use an account to access to DockerHub.
=> fix: login on DockerHub to avoid quota rate limits

x-pack/elastic-agent/CHANGELOG.next.asciidoc, x-pack/elastic-agent/pkg/agent/program/testdata/single_config.yml, x-pack/elastic-agent/pkg/agent/transpiler/ast.go
This PR guards against a nil items which are part of the list. Fn call then casues agent to panic.
Fixes: #23734
=> [Ingest Manager] Fix nil pointer for nil list item

metricbeat/module/kubernetes/_meta/terraform/eks/requirements.txt
This PR upgrades lib testing dependencies for Kubernetes module
=> Upgrade k8s testing requirements.txt

filebeat/input/filestream/input_integration_test.go
Cherry-pick of PR #24634 to 7.x branch. Original message: 
Closes #24623
=> Cherry-pick #24634 to 7.x: Increase scan interval to stabilize TestFilestreamCloseRenamed

filebeat/docs/modules/postgresql.asciidoc, filebeat/module/postgresql/_meta/docs.asciidoc, metricbeat/docs/modules/postgresql.asciidoc, metricbeat/metricbeat.reference.yml, metricbeat/module/postgresql/_meta/config.reference.yml, metricbeat/module/postgresql/statement/_meta/docs.asciidoc, x-pack/metricbeat/metricbeat.reference.yml
Cherry-pick of PR #24588 to 7.x branch. Original message: 
Add documentation in PostgreSQL modules about recommended configuration.
To better leverage PostgreSQL modules.
- Closes #14337.
- Related to #20321.
- Part of elastic/integrations#366.
=> Cherry-pick #24588 to 7.x: Add docs about PostgreSQL monitoring

filebeat/docs/modules/threatintel.asciidoc, x-pack/filebeat/module/threatintel/_meta/docs.asciidoc
Fixes a typo in the documentation example configuration for threatintel module.
Fixes a typo in the documentation example configuration for threatintel module.
=> [Filebeat] Update example config documentation for threatintel

metricbeat/module/logstash/logstash_integration_test.go
This test seems to be flaky, but is difficult to reproduce locally.
Reduce the use of requirements and separate metricsets in different
tests so more assertions are executed. Print also the problematic event
to have more information next time it happens.
Related to https://github.com/elastic/beats/issues/24822.
=> Add more info to logstash TestXPackEnabled test

filebeat/docs/modules/threatintel.asciidoc, x-pack/filebeat/module/threatintel/_meta/docs.asciidoc
Cherry-pick of PR #24824 to 7.x branch. Original message: 
Fixes a typo in the documentation example configuration for threatintel module.
Fixes a typo in the documentation example configuration for threatintel module.
=> Cherry-pick #24824 to 7.x: [Filebeat] Update example config documentation for threatintel

metricbeat/module/logstash/logstash_integration_test.go
Cherry-pick of PR #24823 to 7.x branch. Original message: 
This test seems to be flaky, but is difficult to reproduce locally.
Reduce the use of requirements and separate metricsets in different
tests so more assertions are executed. Print also the problematic event
to have more information next time it happens.
Related to https://github.com/elastic/beats/issues/24822.
=> Cherry-pick #24823 to 7.x: Add more info to logstash TestXPackEnabled test

filebeat/input/filestream/input_integration_test.go
This PR ports the following tests from Python to Golang to use the `filestream` input:
* `test_close_inactive`
* `test_close_inactive_file_removal`
* `test_close_inactive_file_rotation_and_removal`
* `test_close_inactive_file_rotation_and_removal2`
Port existing knowledge from Python tests to Golang.
=> Port close_inactive* tests from test_input.py

libbeat/docs/processors-list.asciidoc
`decode_xml` was not in order.
=> Sort processor list in docs

libbeat/docs/processors-list.asciidoc
Cherry-pick of PR #24874 to 7.12 branch. Original message: 
`decode_xml` was not in order.
=> Cherry-pick #24874 to 7.12: Sort processor list in docs

Jenkinsfile
- feat: stage execution cache (#24780)
=> Cherry-pick to 7.11: feat: stage execution cache (#24780)

Jenkinsfile
- feat: stage execution cache (#24780)
=> Cherry-pick to 7.12: feat: stage execution cache (#24780)

.ci/beats-tester.groovy, .ci/build-docker-images.groovy
Use ubuntu-20 version instead the alias
Use the same approach as done with some other pipelines
=> CI: use ubuntu-20

Jenkinsfile
- [CI] enable one shoot workers (#24435)
=> Cherry-pick to 7.11: [CI] enable one shoot workers (#24435)

x-pack/elastic-agent/pkg/agent/cmd/container.go
- [Elastic Agent] Cloud container legacy apm files. (#24896)
=> Cherry-pick to 7.x: [Elastic Agent] Cloud container legacy apm files. (#24896)

x-pack/elastic-agent/CHANGELOG.next.asciidoc
This PR adds changelog entry for https://github.com/elastic/beats/pull/24913
=> Add changelog entry for leaderelection on Agent

CHANGELOG.next.asciidoc, filebeat/docs/modules/threatintel.asciidoc, x-pack/filebeat/module/misp/_meta/kibana/7/dashboard/Filebeat-MISP-Overview.json, x-pack/filebeat/module/threatintel/_meta/docs.asciidoc, x-pack/filebeat/module/threatintel/_meta/kibana/7/dashboard/Filebeat-threatintel-misp.json
Spelling Change
MISP was misspelled
-  [ ] ~~My code follows the style guidelines of this project ~~
-  [ ] ~~I have commented my code, particularly in hard-to-understand areas ~~
-  [ ] ~~I have made corresponding change to the default configuration files ~~
-  [ ] ~~I have added tests that prove my fix is effective or that my feature works ~~
=> [Filebeat][Docs][7.12] Fix a Incorrect Spelling on Threat Intel Module

CHANGELOG.next.asciidoc
Fixes bad changelog entries on a backport https://github.com/elastic/beats/pull/25046
=> Fix stray changelog entries

CHANGELOG.next.asciidoc
Fixes changelog reference for PR #25066
=> Fix changelog

.backportrc.json
Merge after the release 7.13.0.
=> backport: Add 7.13 branch

libbeat/processors/actions/docs/decode_json_fields.asciidoc
- Update decode_json_fields.asciidoc (#25056)
=> Cherry-pick to 7.13: Update decode_json_fields.asciidoc (#25056)

x-pack/osquerybeat/beater/osquerybeat.go
Serializes queries execution over osqueryd socket.
Addresses the issue: https://github.com/elastic/beats/issues/25297
In this particular case the two schedules queries were executed at the same time on the same socket that caused the problems such as:
```
osquery failed: write unix ->/var/run/642722736/osquery.sock: write: broken pipe
```
```
: *osquery.ExtensionResponse error reading struct: error reading field 0: read unix ->/var/run/404419649/osquery.sock: i/o timeout
```
Currently the queries are scheduled by osquerybeat. Going forwards the handling of the scheduled queries will move into osqueryd for 7.14.
Fixed the problem in 7.13 release as described in https://github.com/elastic/beats/issues/25297
- Steps to Reproduce: 
1. Add osquery manager integration to the policy
2. Enroll …
=> Serialize queries execution over osqueryd socket

libbeat/processors/add_kubernetes_metadata/docs/add_kubernetes_metadata.asciidoc
- Update add_kubernetes_metadata.asciidoc (#25054)
=> Cherry-pick to 7.x: Update add_kubernetes_metadata.asciidoc (#25054)

libbeat/processors/add_kubernetes_metadata/docs/add_kubernetes_metadata.asciidoc
- Update add_kubernetes_metadata.asciidoc (#25054)
=> Cherry-pick to 7.13: Update add_kubernetes_metadata.asciidoc (#25054)

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 7.12.1

x-pack/heartbeat/monitors/browser/browser.go
We are now in beta, let's reflect it in our startup warning.
Fixes #25287
=> [Heartbeat] Update synthetics warning message form experimental -> beta

.ci/bump-stack-version.sh
Create the branch with the base branch to avoid any clashes.
=> [automation] create branch with the base branch suffix when bumping the elastic stack version

x-pack/filebeat/filebeat.reference.yml, x-pack/filebeat/module/threatintel/_meta/config.yml, x-pack/filebeat/modules.d/threatintel.yml.disabled
=> [filebeat] Fix config ti 7.x

x-pack/filebeat/filebeat.reference.yml, x-pack/filebeat/module/threatintel/_meta/config.yml, x-pack/filebeat/modules.d/threatintel.yml.disabled
=> [filebeat] Fix threatintel config

auditbeat/docs/getting-started.asciidoc, filebeat/docs/getting-started.asciidoc, heartbeat/docs/getting-started.asciidoc, journalbeat/docs/getting-started.asciidoc, libbeat/docs/howto/load-index-templates.asciidoc, libbeat/docs/template-config.asciidoc, libbeat/docs/upgrading.asciidoc, metricbeat/docs/getting-started.asciidoc, packetbeat/docs/getting-started.asciidoc, winlogbeat/docs/getting-started.asciidoc, x-pack/functionbeat/docs/getting-started.asciidoc
- docs: fix out of date es ref (#25413)
=> Cherry-pick to 7.13: docs: fix out of date es ref (#25413)

auditbeat/docs/getting-started.asciidoc, filebeat/docs/getting-started.asciidoc, heartbeat/docs/getting-started.asciidoc, journalbeat/docs/getting-started.asciidoc, libbeat/docs/howto/load-index-templates.asciidoc, libbeat/docs/template-config.asciidoc, libbeat/docs/upgrading.asciidoc, metricbeat/docs/getting-started.asciidoc, packetbeat/docs/getting-started.asciidoc, winlogbeat/docs/getting-started.asciidoc, x-pack/functionbeat/docs/getting-started.asciidoc
- docs: fix out of date es ref (#25413)
=> Cherry-pick to 7.x: docs: fix out of date es ref (#25413)

libbeat/tests/system/requirements.txt, metricbeat/module/kubernetes/_meta/terraform/eks/requirements.txt
Update pytest, py and rsa python dependencies used in testing and
development scenarios.
Co-Authored-By: Christos Markou <chrismarkou92@gmail.com>
=> Update python dependencies

CHANGELOG.next.asciidoc, filebeat/docs/inputs/input-filestream.asciidoc, filebeat/input/filestream/input.go
This PR marks `filestream` input beta.
The input has matured a lot over the last months. It has better test coverage and got a little bit of testing. Also, it supports all features that `log` input does.
It encourages people to adopt it so they can benefit from the improvements.
=> Mark filestream input Beta

filebeat/docs/inputs/input-filestream-file-options.asciidoc, filebeat/docs/inputs/input-filestream-reader-options.asciidoc, filebeat/docs/inputs/input-filestream.asciidoc
Leftover review updates from https://github.com/elastic/beats/pull/25303
=> docs: `filestream` input review updates

dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl, dev-tools/packaging/templates/docker/Dockerfile.tmpl
This package is failing to be updated in ARM packaging builds.
Try to fix broken ARM builds.
=> Don't update bind-license in ARM docker build

CHANGELOG.next.asciidoc, metricbeat/module/jolokia/jmx/config.go, metricbeat/module/jolokia/jmx/config_test.go
This PR fixes https://github.com/elastic/beats/issues/25630
The mBeanName.Canonicalize(...) fails to sort the properties correctly if there're properties which are prefixes of other properties. e.g.; 
after the fix, the metricbeat will be able to parse the solr specific mbeans exposed under the "solr" domain, e.g.
solr:dom1=jvm,name=used,name0=memory,name1=total
the new test in `config_test - TestCanonicalizeMbeanName` should pass
- Closes #25630
- Relates #25630
=> [Metricbeat] In jolokia jmx mbean canonization the keys should be sorted first

x-pack/elastic-agent/README.md, x-pack/elastic-agent/docs/README.md
I had this as a local note and used it often. I thought it maybe worth sharing.
=> [Elastic Agent] Add hint on how to build and test the container for Elastic Agent

x-pack/osquerybeat/ext/osquery-extension/main.go
Updates the license header for osquery-extention main.go file.
=> Fix license header for osquery-extension

filebeat/input/filestream/internal/input-logfile/harvester_test.go
Disable flaky filesteam harvester test.
- Relates #25805
=> Disable flaky filesteam harvester test

libbeat/docs/release-notes/breaking/breaking-7.13.asciidoc
Adds breaking change related to licensing that some users might encounter.
=> Add breaking change around licensing

Jenkinsfile
There is an ongoing problem with builds wherein Windows workers [seem to lose their connection to Jenkins immediately after downloading large files](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats/detail/master/680/pipeline/13660). 
We hypothesize that we may be able to reduce the frequency of these failures by decreasing the size of the archive which workers download from GCE. Upon inspection of the bundle, we discovered that it is ~1.2GB uncompressed, of which, only 200MB is actual source code and ~1GB is simply git history.
This change attempts to reduce the size of that bundle by doing a simple checkout instead of using our `gitCheckout` step which has the side-effect of doing a `git fetch`, which we believe to be largely responsible for the overall size of the …
=> [Jenkins] Light checkout

heartbeat/monitors/active/http/http_test.go, heartbeat/monitors/active/tcp/tls_test.go, metricbeat/module/golang/test_golang.py
Disable flakey tests in Windows 7 32 bit for Heartbeat, and windows 10 for metricbeat
- Relates #25857
- Relates #25858
=> Disable heartbeat and metricbeat tests

x-pack/filebeat/module/crowdstrike/falcon/test/falcon-sample.log, x-pack/filebeat/module/crowdstrike/falcon/test/falcon-sample.log-expected.json
=> Clean up fixture files

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 7.13.1

x-pack/filebeat/module/coredns/log/config/coredns.yml
=> [Filebeat] updating coredns to ecs 1.10.0

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 6.8.16.
=> docs: update docs versions 6.8.16

x-pack/filebeat/module/snyk/audit/config/config.yml, x-pack/filebeat/module/snyk/vulnerabilities/config/config.yml
=> [Filebeat] updating snyk to ecs 1.10.0

x-pack/filebeat/module/zoom/webhook/config/webhook.yml
=> [Filebeat] updating zoom to ecs 1.10.0

x-pack/filebeat/module/checkpoint/firewall/config/firewall.yml
=> [Filebeat] updating checkpoint to ecs 1.10.0

filebeat/module/system/auth/config/auth.yml, filebeat/module/system/syslog/config/syslog.yml
=> [Filebeat] updating system to ecs 1.10.0

filebeat/module/traefik/access/config/traefik-access.yml
=> [Filebeat] updating traefik to ecs 1.10.0

auditbeat/cmd/root.go
=> [Auditbeat] updating auditbeat to ecs 1.10.0

heartbeat/cmd/root.go
=> [Heartbeat] updating heartbeat to ecs 1.10.0

filebeat/module/apache/access/config/access.yml, filebeat/module/apache/error/config/error.yml
=> [Filebeat] updating apache to ecs 1.10.0

filebeat/module/icinga/debug/config/debug.yml, filebeat/module/icinga/main/config/main.yml, filebeat/module/icinga/startup/config/startup.yml
=> [Filebeat] updating icinga to ecs 1.10.0

filebeat/module/kibana/audit/config/audit.yml, filebeat/module/kibana/log/config/log.yml
=> [Filebeat] updating kibana to ecs 1.10.0

filebeat/module/nginx/access/config/nginx-access.yml, filebeat/module/nginx/error/config/nginx-error.yml, filebeat/module/nginx/ingress_controller/config/ingress_controller.yml
=> [Filebeat] updating nginx to ecs 1.10.0

metricbeat/tests/system/test_lightmodules.py
This PR is to disable test processors system test for windows 10 in master branch.
Relates #26181
=> Disable test processors system test for windows 10

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 7.13.2.
=> docs: update docs versions 7.13.2

filebeat/docs/modules/iis.asciidoc, filebeat/module/iis/_meta/docs.asciidoc
=> Cherry-pick to 7.13: Add support note (#26283)

.ci/packaging.groovy, x-pack/elastic-agent/Jenkinsfile.yml, x-pack/elastic-agent/magefile.go
Avoids overwriting Platforms expression in init of agent magefile.
Make build work correctly
Ref: #26239
=> Updated filter expression for filtering 86 artifacts

x-pack/filebeat/module/envoyproxy/log/config/envoyproxy.yml
=> [Envoyproxy] Update envoyproxy ECS version

CHANGELOG.next.asciidoc, x-pack/filebeat/input/httpjson/internal/v2/input_test.go, x-pack/filebeat/input/httpjson/internal/v2/request.go, x-pack/filebeat/input/httpjson/internal/v2/request_test.go, x-pack/filebeat/input/httpjson/internal/v2/transform.go
Fixes a bug in httpjson input that prevented first_event to get updated.
=> [filebeat] Fix httpjson first_event

metricbeat/module/prometheus/collector/collector.go, metricbeat/module/prometheus/collector/data.go, metricbeat/module/prometheus/query/data.go, metricbeat/module/prometheus/remote_write/remote_write.go
Cherry-pick of PR elastic/beats#25726 to 7.x branch. Original message: 
Fix the annotation's irregular and typo on prometheus module.
=> Cherry-pick #25726 to 7.x: [metric beat] Fix the annotation's irregular and typo on prometheus module.

CHANGELOG.next.asciidoc
=> Add missing changelog entry for #26224

.backportrc.json, .mergify.yml
Merge after the release 7.14.0.
=> backport: Add 7.14 branch

libbeat/tests/system/requirements.txt
(cherry picked from commit 2f873a23467b10c2ec1d173ae74308d9ef53c6ee)
=> Cherry-pick of: Update urllib to 1.26.5. (#26380)

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 7.13.3.
=> docs: update docs versions 7.13.3

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 6.8.17.
=> docs: update docs versions 6.8.17

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> Forward port changelog for 7.13.3 (#26731) to master

dev-tools/packaging/templates/docker/Dockerfile.tmpl
+ fix #26863
+ testing for this is done in Synthetics agent - https://github.com/elastic/synthetics/pull/347/
=> [Heartbeat]: update Node.js version for synthetics

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> Forward Port 7.13.4 changelog to 7.14

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> Forward port 7.13.4 changelog to 7.x

go.mod, go.sum
This PR updates the version of `github.com/miekg/dns` package to more recent one.
=> Update github.com/miekg/dns version

CHANGELOG.asciidoc, libbeat/docs/release.asciidoc, x-pack/osquerybeat/internal/ecs/mapping.go, x-pack/osquerybeat/internal/ecs/mapping_test.go
=> No changelog for 8.0.0-alpha1

go.mod, go.sum
This PR updates the version of go.elastic.co/apm package to more recent one.
=> Update go.elastic.co/apm version

deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
This is backport of pull request #27098.
Automatic one didn't work: https://github.com/elastic/beats/pull/27100
=> [7.x](backport #27098) Fix version placeholder for elastic-agent k8s manifest

libbeat/docs/http-endpoint.asciidoc
Replaces https://github.com/elastic/beats/pull/26463.
=> docs: fix example

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 7.13.4.
=> docs: update docs versions 7.13.4

filebeat/docs/modules/awsfargate.asciidoc, x-pack/filebeat/module/awsfargate/_meta/docs.asciidoc
Typo fix in Filebeat awsfargate module.
=> Fix awsfargate documentation

x-pack/osquerybeat/internal/ecs/mapping.go, x-pack/osquerybeat/internal/ecs/mapping_test.go
The header fix in https://github.com/elastic/beats/pull/27063 should have been a separate PR and backported.
Fixes the build.
-
=> Add missing headers

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 6.8.18.
=> docs: update docs versions 6.8.18

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
See https://github.com/elastic/beats/pull/27150
See https://github.com/elastic/beats/pull/27198
Part of 7.14.0 release
=> Forward port 7.14.0 changelog to master

x-pack/osquerybeat/internal/distro/distro.go, x-pack/osquerybeat/internal/tar/tar.go
Upgrade osquery to include 4.9.0 version into distribution
Picking up the latest osquery fixes and enhancements
=> Osquerybeat: Upgrade osquery to 4.9.0

filebeat/docs/filebeat-options.asciidoc
As reported on Twitter: https://twitter.com/theshalvah/status/1425476263544770560
=> Add filestream to the list of inputs in the "Configure inputs" section of the docs

CHANGELOG.next.asciidoc
I once again forgot to add a changelog when I merged #27242 . This just adds that.
=> Add changelog for cgroupsV2

libbeat/docs/shared-kerberos-config.asciidoc
Fixes minor formatting nit and use correct variable to resolve the beat name.
=> Fix formatting of Filebeat name

CHANGELOG.next.asciidoc
I added them accidentally in #27398
=> Remove unnecessary changelog entries from 7.x

metricbeat/module/prometheus/query/_meta/docs.asciidoc
This PR fixes a small typo on the word "Prometheus".
Correctness of documentation
=> Docs - Fix small typo "promtheus" -> "prometheus"

libbeat/docs/shared-kibana-config.asciidoc, libbeat/docs/shared-ssl-config.asciidoc
- [DOCS] Remove PKI mentions (#27422)
=> Cherry-pick to 7.x: [DOCS] Remove PKI mentions (#27422)

libbeat/docs/shared-kibana-config.asciidoc, libbeat/docs/shared-ssl-config.asciidoc
Backports the following commits to 7.15:
- [DOCS] Remove PKI mentions (#27422)
=> Cherry-pick to 7.15: [DOCS] Remove PKI mentions (#27422)

libbeat/docs/howto/change-index-name.asciidoc
- Update change-index-name.asciidoc (#26703)
=> Cherry-pick to 7.14: Update change-index-name.asciidoc (#26703)

libbeat/docs/howto/change-index-name.asciidoc
- Update change-index-name.asciidoc (#26703)
=> Cherry-pick to 7.x: Update change-index-name.asciidoc (#26703)

libbeat/docs/howto/change-index-name.asciidoc
Backports the following commits to 7.15:
- Update change-index-name.asciidoc (#26703)
=> Cherry-pick to 7.15: Update change-index-name.asciidoc (#26703)

filebeat/docs/modules/aws.asciidoc, x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc, x-pack/filebeat/module/aws/_meta/docs.asciidoc
- Docs
Corrects `var.bucket` to `var.bucket_arn` in docs
While in the examples `var.bucket_arn` is used the var list states `var.bucket` as variable to use, this is wrong.
-
=> var.bucket renamed to var.bucket_arn in docs

CHANGELOG.next.asciidoc, auditbeat/auditbeat.reference.yml, filebeat/filebeat.reference.yml, heartbeat/heartbeat.reference.yml, journalbeat/journalbeat.reference.yml, libbeat/_meta/config/general.reference.yml.tmpl, libbeat/docs/queueconfig.asciidoc, libbeat/publisher/queue/diskqueue/queue.go, metricbeat/metricbeat.reference.yml, packetbeat/packetbeat.reference.yml, winlogbeat/winlogbeat.reference.yml, x-pack/auditbeat/auditbeat.reference.yml, x-pack/filebeat/filebeat.reference.yml, x-pack/functionbeat/functionbeat.reference.yml, x-pack/heartbeat/heartbeat.reference.yml, x-pack/metricbeat/metricbeat.reference.yml, x-pack/osquerybeat/osquerybeat.reference.yml, x-pack/packetbeat/packetbeat.reference.yml, x-pack/winlogbeat/winlogbeat.reference.yml
Update the documentation, reference configurations, and log messages to remove the beta warnings on the disk queue.
=> [libbeat] Mark disk queue as GA

x-pack/osquerybeat/beater/action_handler.go, x-pack/osquerybeat/beater/osquerybeat.go, x-pack/osquerybeat/internal/action/action.go, x-pack/osquerybeat/internal/action/action_test.go
* Improves unit test coverage.
* Consolidate ECS mapping, reduce allocation.
Unit tests coverage and code improvements
=> Osquerybeat: Improve unit test coverage. Consolidate ECS mapping.

libbeat/docs/howto/change-index-name.asciidoc
- Update change-index-name.asciidoc (#26703)
=> Cherry-pick to master: Update change-index-name.asciidoc (#26703)

x-pack/osquerybeat/internal/osqd/osqueryd.go
Lock down flagfile, prevent global defaults, otherwise the osqueryi and osqueryd processes try to load defaults from 
osquery.flags.defaults file from OSQUERY_HOME locations:
https://github.com/osquery/osquery/blob/2cd5b42c8f8fa52c6d251c6537595c7c59c90f4c/osquery/utils/config/default_paths.h
and can potentially mess with configuration if it was not specified by us via the command line flags.
This could be considered a bug or a feature, for example without this change you can create 
/var/osquery/osquery.flags.defaults on Mac with content 
```--disable_tables=users```
and this will prevent any osquery instance (including ours) from querying this table. 
This change prevents global osquery defaults flagfile from affecting our osquery instance configuration.
Empty osquery.flags file is …
=> Osquerybeat: lock down flagfile, prevent global defaults

docs/devguide/newdashboards.asciidoc
This PR adds more info about the recent changes in dashboard exporting.
Let people know what is going on.
=> Add documentation about -folder flag to dashboard exporting

Jenkinsfile
Create a GH check when the cloud stage started rather than when running the tests.
Help to identify the failures easily.
Discovered in https://github.com/elastic/beats/pull/27491
=> CI: notify GH check status in cloud stages

libbeat/docs/release.asciidoc
Fix incomplete conflict resolution at https://github.com/elastic/beats/pull/27975
=> Fix wrong merge conflict resolution

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 7.14.2.
=> docs: update docs versions 7.14.2

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 6.8.19.
=> docs: update docs versions 6.8.19

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 7.15.0

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
See #28033. Part of 7.15.0 release.
=> Forward port 7.15.0 changelog to 7.x

CHANGELOG.asciidoc
=> Add changelog edit

CHANGELOG.asciidoc
(cherry picked from commit 4709f8593c9010f38050a42d88d26fba62d4ddd2)
=> Forward port changelog edit (#28043)

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
See #28033. Part of 7.15.0 release.
=> Forward port 7.15.0 changelog to master

x-pack/metricbeat/module/ibmmq/docker-compose.yml
This PR bumps up the service Docker image for IBM MQ.
The previous one has suddenly disappeared...
9.1.5.0-r2-amd64 is available: https://hub.docker.com/layers/ibmcom/mq/9.1.5.0-r2-amd64/images/sha256-9bcee09b99b596610e7d660d597b76d9c395ed9bb6bdb970b8975ac6a3c0217e?context=explore
I guess I have to backport it everywhere?
The CI will test it.
-
=> IBM MQ: Bump up the service Docker image

libbeat/docs/release-notes/breaking/breaking-7.15.asciidoc
Adds missing details to the 7.15 breaking changes document .
Users need to know about these changes before they migrate.
=> Add missing details to the 7.15 breaking changes

x-pack/osquerybeat/beater/osquery_runner_test.go, x-pack/osquerybeat/internal/action/action_test.go, x-pack/osquerybeat/internal/config/watcher.go, x-pack/osquerybeat/internal/pub/publisher_test.go
Fix headers formatting, fix a wrong dependency import
To follow the established practices
=> Osquerybeat: Fix headers formatting, fix a wrong dependency import

Jenkinsfile
It uses `build` instead of `$BASE_DIR`
We are seeing this error message on CI:
>/var/lib/jenkins/workspace/PR-28153-1-fd80cbcd-cedb-4e89-9468-a638883a8933/src/github.com/elastic/beats/src/github.com/elastic/beats does not exist.
- Completes #28129
=> fix(ci): use the right parent directory for uploading GoIntegTests artifacts

metricbeat/docs/modules/linux/memory.asciidoc
Fixes https://github.com/elastic/beats/pull/28136#issuecomment-928241441
=> Fix build with lint change

Jenkinsfile.yml
Generator tests are currently failing, skip them.
More context in:
* https://github.com/elastic/beats/pull/28723
* https://github.com/elastic/beats/pull/28579#issuecomment-954705440
To be merged if https://github.com/elastic/beats/pull/28723 is not enough.
=> Skip generator tests

CHANGELOG.next.asciidoc
=> Remove multiline entries (8.0)

CHANGELOG.next.asciidoc
=> Remove multiline entries (master)

CHANGELOG.next.asciidoc
=> Remove multiline entries (7.16)

CHANGELOG.next.asciidoc
Followup to #28729 in the 7.15 branch, which is still alive.
=> Cleanup CHANGELOG.next.asciidoc (7.15)

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 7.15.2

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
Part of 7.15.2 release. See #28866
=> Forward-port 7.15.2 changelog to 7.16

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
Part of 7.15.2 release. See #28866 and #28871
=> Forward port 7.15.2 changelog to 8.0

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
- No changelog for 8.0.0-beta1 (#28728)
- Forward port 7.15.2 changelog to 8.0 (#28879)
=> Forward port 8.0.0-beta 1 and 7.15.2 changelogs to master

filebeat/_meta/test/docs/01_playground/filebeat.yaml, filebeat/_meta/test/docs/testing.md, metricbeat/docs/autodiscover-hints.asciidoc, metricbeat/docs/autodiscover-kubernetes-config.asciidoc, metricbeat/module/kubernetes/_meta/test/docs/01_playground/ek_stack.yaml, metricbeat/module/kubernetes/_meta/test/docs/README.md
This PR adds instructions on how to test filebeat on Kubernetes locally , similar to https://github.com/elastic/beats/pull/26643
-
=> Add how to for testing filebeat on kubernetes; minor docs adjustments

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 7.15.2.
=> docs: update docs versions 7.15.2

.ci/schedule-daily.groovy, .ci/schedule-weekly.groovy
Update jobs
7.15 is not an active branch
=> ci: daily/weekly jobs

x-pack/elastic-agent/README.md
This PR adds instructions on how to test elastic agent on Kubernetes locally.
-
=> Add how-to for testing elastic-agent on k8s

x-pack/elastic-agent/pkg/agent/cmd/watch.go
This PR adds a missing format specifier in a `log.Debugf()` format string.
a) the underlying error isn't logged
b) if hit, there will be an ugly hint at the end of the logged string
- [-] I have commented my code, particularly in hard-to-understand areas
- [-] I have made corresponding changes to the documentation
- [-] I have made corresponding change to the default configuration files
- [-] I have added tests that prove my fix is effective or that my feature works
- [-] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.
-
=> Add missing format specifier in watchCmd()

auditbeat/Jenkinsfile.yml, deploy/kubernetes/Jenkinsfile.yml, filebeat/Jenkinsfile.yml, generator/Jenkinsfile.yml, heartbeat/Jenkinsfile.yml, journalbeat/Jenkinsfile.yml, libbeat/Jenkinsfile.yml, metricbeat/Jenkinsfile.yml, packetbeat/Jenkinsfile.yml, winlogbeat/Jenkinsfile.yml, x-pack/auditbeat/Jenkinsfile.yml, x-pack/filebeat/Jenkinsfile.yml, x-pack/functionbeat/Jenkinsfile.yml, x-pack/libbeat/Jenkinsfile.yml, x-pack/metricbeat/Jenkinsfile.yml, x-pack/packetbeat/Jenkinsfile.yml
Use `ubuntu-18`
EOL for `ubuntu-16`
=> [ci] use ubuntu-18

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
Part of 7.16.0 release, see #29245
=> Forward port 7.16.0 changelog to 8.0

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 6.8.21.
=> docs: update docs versions 6.8.21

CHANGELOG.asciidoc
Applied some consistency edits while I was in the file fixing a typo and a couple broken links. Just a quick job and not very thorough.
=> Apply consistency edits to changelog for 7.16.0

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
Part of 7.16.1 release (see #29404 )
=> Forward port 7.16.1 changelog to 8.0

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
Part of 7.16.1 release (see #29404 )
=> Forward port 7.16.1 changelog to master

CHANGELOG.next.asciidoc
=> Cleanup breaking changes section

CHANGELOG.next.asciidoc
=> Cleanup breaking changes section (#29490)

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 7.16.2.
=> docs: update docs versions 7.16.2

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 6.8.22.
=> docs: update docs versions 6.8.22

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 7.16.2

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
- docs: Prepare Changelog for 7.16.2 (#29521)
- Additional cleanup
=> Forward port 7.16.2 changelog to 8.0 and additional cleanup

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
- Forward port 7.16.2 changelog to 8.0 and additional cleanup (#29530)
- Additional cleanup
=> Forward port 7.16.2 changelog to master and cleanup

.ci/jobs/beats.yml
7.17 branch is now available. I also enabled 7.18 and 7.19, just in case
=> jjbb: enable 7.17 (and 7.18/19)

Jenkinsfile
Update e2e-testing main branch
=> update e2e-testing main branch

.ci/jobs/beats-release-changelog.yml, .ci/jobs/beats-release-minor-major.yml, .ci/jobs/beats-release-patch.yml
ingest-dev is gonna be `main` branch based soon
=> update ingest-dev main branch

libbeat/docs/monitoring/monitoring-internal-collection.asciidoc
Manual forward port of #27624 into master.
=> Update monitoring-internal-collection.asciidoc (#27624)

libbeat/docs/monitoring/monitoring-internal-collection.asciidoc
Manual backport of #27624 into 7.17 branch
=> [7.17] Update monitoring-internal-collection.asciidoc (#27624)

libbeat/docs/monitoring/monitoring-internal-collection.asciidoc
Manual backport of #27624 into 7.16 branch
=> [7.16] Update monitoring-internal-collection.asciidoc (#27624)

libbeat/docs/monitoring/monitoring-internal-collection.asciidoc
Manual backport of #27624 to 7.15 branch
=> [7.15] Update monitoring-internal-collection.asciidoc (#27624)

CHANGELOG.next.asciidoc, metricbeat/module/kibana/stats/_meta/data.json, metricbeat/module/kibana/stats/data.go
Extracts the correct `index` property from the kibana.stats API call
=> kibana.stats: extract correct index property

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 7.16.3.
=> docs: update docs versions 7.16.3

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 6.8.23.
=> docs: update docs versions 6.8.23

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> Forward port changelog for 7.16.3 to 7.17

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> Forward port 7.16.3 changelog to 8.0

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> Forward port 7.16.3 changelog to master

.ci/jobs/apm-beats-update.yml, .ci/jobs/beats-tester.yml, .ci/jobs/beats.yml, .ci/jobs/packaging.yml
Remove obsoleted branches from the Multibranch Pipelines
Tidy up branches
=> jjbb: remove obsoleted branches (<7.16)

NOTICE.txt, go.mod, go.sum
This PR update containerd dependency so as to resolve the dependant bot alert.
=> Update containerd library

NOTICE.txt, go.mod, go.sum
The github repository at `apoydence/eachers` doesn't exist anymore, the
new location of the code is now at `poy/eachers`. The dependency is an
indirect dependency included by https://github.com/cloudfoundry/noaa/blob/5ce49363dfa666c00fc716cb5f8c2f99462b41ef/consumer/token_refresher_test.go#L11
which is used for our cloudfoundry code.
Note the eachers dependency s used while testing the nooa package, but as of today `go mod` is including
these dependency.
-
=> Replace location of apoydence/eachers to poy/eachers

libbeat/tests/system/requirements_aix.txt
Update version of jinja2 library.
=> Update version of jinja2

auditbeat/auditbeat.reference.yml, filebeat/filebeat.reference.yml, heartbeat/heartbeat.reference.yml, libbeat/_meta/config/output-elasticsearch.reference.yml.tmpl, libbeat/_meta/config/setup.ilm.reference.yml.tmpl, libbeat/docs/howto/change-index-name.asciidoc, libbeat/docs/howto/load-index-templates.asciidoc, libbeat/docs/shared-ilm.asciidoc, metricbeat/metricbeat.reference.yml, packetbeat/packetbeat.reference.yml, winlogbeat/winlogbeat.reference.yml, x-pack/auditbeat/auditbeat.reference.yml, x-pack/filebeat/filebeat.reference.yml, x-pack/functionbeat/functionbeat.reference.yml, x-pack/heartbeat/heartbeat.reference.yml, x-pack/metricbeat/metricbeat.reference.yml, x-pack/osquerybeat/osquerybeat.reference.yml, x-pack/packetbeat/packetbeat.reference.yml, x-pack/winlogbeat/winlogbeat.reference.yml
This PR follows up the changes to data storage in Beats in the documentation. Now it talks about data streams and no longer mention outdated configuration options.
Avoid user confusion.
Closes #29802
=> Follow up changes in documentation about data streams

x-pack/elastic-agent/docs/fleet-server-bootstrap.asciidoc
Adds developer documentation on how the Elastic Agent bootstraps the Fleet Server under the Elastic Agent.
To help other engineers on the team to understand the process.
=> [Elastic Agent] Add doc on how Fleet Server is bootstrapped.

filebeat/docs/modules/azure.asciidoc, x-pack/filebeat/module/azure/_meta/docs.asciidoc
=> Add links to azure docs

CHANGELOG.next.asciidoc, x-pack/metricbeat/module/gcp/_meta/kibana/7/dashboard/1ae960c0-f9f8-11eb-bc38-79936db7c106.json
Provide fixes to the Metricbeat GCP GKE Overview dashboard.
In the GKE Overview dashboard there were some leftover queries targeting
a cluster name that existed only in the test environment when the
dashboard has been developed.
Use metricbeat to gather data from a project with GKE clusters and observe the dashboard. All
widgets should be filled.
- Related to #29815
=> [Metricbeat] gcp.gke: fix overview dashboard

metricbeat/docs/modules/istio.asciidoc, x-pack/metricbeat/metricbeat.reference.yml, x-pack/metricbeat/module/istio/_meta/config.reference.yml, x-pack/metricbeat/module/istio/_meta/config.yml, x-pack/metricbeat/module/istio/_meta/docs.asciidoc, x-pack/metricbeat/modules.d/istio.yml.disabled
Clarify docs. Co written with @ChrsMark .
Prevent misunderstandings
-
=> [Documentation] Istio Module documentation clarification

.ci/scripts/install-tools.bat
Fail if the installation of the tools failed
Fix the issue with failing fast
Closes https://github.com/elastic/beats/issues/29998
=> ci: fail fast when installing the windows tools

CHANGELOG.next.asciidoc, dev-tools/mage/pkgtypes.go, x-pack/elastic-agent/magefile.go, x-pack/elastic-agent/pkg/artifact/artifact.go, x-pack/elastic-agent/pkg/artifact/download/http/elastic_test.go
=> Revert "Packaging: rename arm64 suffix to aarch64 in the tar.gz artifacts ONLY"

CHANGELOG.next.asciidoc, libbeat/processors/actions/docs/add_fields.asciidoc
Added information that the processor can overwrite fields if the field already exists. The code already exists to do this, as its built in, but the documentation doesnt reflect this.
-
=> Added info about ability to overwrite

libbeat/processors/actions/docs/add_fields.asciidoc
=> [8.0] Added info about ability to overwrite (#29944)

libbeat/processors/actions/docs/add_fields.asciidoc
=> [7.17] Added info about ability to overwrite (#29944)

libbeat/processors/actions/docs/add_fields.asciidoc
Forward ports #29944 to master.
=> [master] Added info about ability to overwrite (#29944)

CHANGELOG.asciidoc, libbeat/docs/release.asciidoc
=> 8.0.0-rc2 Changelog

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> Forward port 7.17.0 changelog to 8.0

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> Forward port 7.17.0 and 8.0.0-rc2 changelogs to master

libbeat/docs/release-notes/breaking/breaking-7.17.asciidoc, libbeat/docs/release-notes/breaking/breaking.asciidoc
Closes https://github.com/elastic/beats/issues/30114
=> Add Beats breaking changes for 7.17

dev-tools/mage/crossbuild.go, x-pack/auditbeat/magefile.go
=> Revert "[7.17](backport #23872) [packaging] Bump golang-crossbuild version debian8"

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc
=> Fix 7.17 changelog: 30077 was there

metricbeat/docker-compose.yml, metricbeat/module/logstash/docker-compose.yml, testing/environments/latest.yml, testing/environments/prev-minor.yml, x-pack/metricbeat/docker-compose.yml
Merge when green after the 7.17.0 release.
=> [Release] Update test environments after 7.17.0 release

metricbeat/module/logstash/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
This PR changes the latest environment to 7.17, as 8.0 has not been released yet.
All 8.1 backports fail without this.
=> Change images to last released version: 7.17

CHANGELOG.next.asciidoc, x-pack/auditbeat/module/system/socket/socket_linux.go, x-pack/auditbeat/module/system/socket/state.go, x-pack/auditbeat/tests/system/test_system_socket.py
This add entity_id to the process fields of socket events.
This helps identify processes involved in network activity events.
- Closes #30230.
=> x-pack/auditbeat/module/system/socket: add process.entity_id capture for socket events

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> Forward port 8.0.0 changelog to 8.1

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> Forward port 8.0.0 changelog to main

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Update the docs for next minor 8.2.0.
Merge after the release branch for 8.0.0 is created.
=> [Release] Update docs for the 8.2.0 release

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Update the docs for next minor 8.1.0.
Merge after the release branch for 7.15.1 is created.
=> [Release] Update docs for the 8.1.0 release

x-pack/elastic-agent/CHANGELOG.next.asciidoc
Adjust the working used on the changelog for #29650 
[Concurrency is not parallelism](https://www.youtube.com/watch?v=PAAkCSZUG1c&t=3m42s) and vice versa.
=> [Elastic Agent] Adjust next changelog wording

CHANGELOG.next.asciidoc, metricbeat/module/docker/_meta/kibana/7/visualization/Docker-Network-IO-ecs.json, metricbeat/module/docker/_meta/kibana/7/visualization/Docker-containers-ecs.json
This PR fixed deprecated fields present on Kibana dashboards for the Docker module.
- Closes https://github.com/elastic/beats/issues/30413
=> Fix Docker module: rename fields on dashboards

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 8.0.1

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 7.17.1.
=> docs: update docs versions 7.17.1

winlogbeat/beater/winlogbeat.go, winlogbeat/eventlog/factory.go, winlogbeat/eventlog/wineventlog.go, winlogbeat/module/pipeline.go, winlogbeat/sys/wineventlog/renderer.go, winlogbeat/sys/wineventlog/wineventlog_windows.go
This removes lint including fixing one bug in the use of `binary.Write`.
Code maintainability and correctness.
-
=> {,x-pack/}winlogbeat: fix lint

auditbeat/module/file_integrity/action.go, auditbeat/module/file_integrity/eventreader_fsevents.go, auditbeat/module/file_integrity/eventreader_test.go, auditbeat/scripts/mage/package.go
This fixes lint in auditbeat, leaving ST1005, but including ST1017 which can cause confusion in some readers.
Improving maintainability.
-
=> {,x-pack/}auditbeat: fix lint

packetbeat/decoder/util.go, packetbeat/flows/worker.go, packetbeat/npcap/npcap.go, packetbeat/procs/procs.go, packetbeat/protos/amqp/amqp.go, packetbeat/protos/dns/names.go, packetbeat/protos/icmp/message.go, packetbeat/protos/memcache/plugin_tcp.go, packetbeat/protos/mongodb/mongodb_structs.go, packetbeat/protos/mysql/mysql.go, packetbeat/protos/sip/plugin.go, packetbeat/protos/tls/parse.go, packetbeat/protos/udp/udp.go, packetbeat/scripts/mage/package.go
This cleans up remaining (non-style) staticcheck lint and fixes spelling. The remaining flagged lint is mainly [ST1005](https://staticcheck.io/docs/checks/#ST1005), with default off checks [ST1000](https://staticcheck.io/docs/checks/#ST1000) and a couple of [ST1003](https://staticcheck.io/docs/checks/#ST1003).
Lint for maintainability and spelling for presentation in most cases, but for documentation correctness in one.
-
=> {,x-pack/}packetbeat: fix staticcheck lint and spelling

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 7.17.1

libbeat/docs/release-notes/breaking/breaking-8.0.asciidoc
Forward ports #30565 to main branch.
=> Update breaking-8.0.asciidoc (#30565)

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 8.1.0

libbeat/processors/add_kubernetes_metadata/docs/indexers_and_matchers.asciidoc
It fixes documentation issue:
replaced: *`container`
with: * `container`
The two possible resource_type weren't clearly highlighted. resource_type `container` appeared to be a sub value for resource_type `pod`
N/A
=> Page formatting issue

CHANGELOG.next.asciidoc
Remove changelog entries added by https://github.com/elastic/beats/pull/30449
=> Remove incorrect changelog entries

NOTICE.txt, go.mod, go.sum
The changes is required because if you try download the dependencies it
will fails on the distributions module with a checksum error.
Recently they have moved the distributions package outside of the
docker organization and Dependabot detected a issues with the released
version.
How to reproduce the issue
1. Take the master branch
2. Clean your Golang module cache.
3. GO111MODULE=on GOPROXY=direct go mod -v
4. Apply this changes with remove the error.
Closes: #30716
-
=> Update to distribution/distribution 2.8.1

filebeat/tests/system/test_crawler.py
Attempt to fix the flaky test_file_no_permission filebeat unit test.
The test is skipped on Windows, but before skipping the test it calls
chmod to remove all permissions. The suspicion is that this leaves the
file in the filesystem at the end of test without enough permissions to
be removed.
Change the logic to skip the test before any of the test logic is
executed.
See https://github.com/elastic/beats/issues/30811 for an example failure and the stack trace.
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have added tests that prove my fix is effective or …
=> Attempt to fix the flaky test_file_no_permission test filebeat test.

metricbeat/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
Updates test environments for 8.1.1.
=> [Release] Update test environments for 8.1.1

metricbeat/docs/modules/gcp.asciidoc, x-pack/metricbeat/metricbeat.reference.yml, x-pack/metricbeat/module/gcp/_meta/config.yml, x-pack/metricbeat/modules.d/gcp.yml.disabled
Update `gcp` module default configuration documentation to use `gke` metricset.
In https://github.com/elastic/beats/issues/29815 was showcased an issue
partially born out of a wrong default configuration.
GKE metrics can be pulled from GCP Cloud Monitoring using the `gke`
metricset instead of using the generic `metrics` metricset.
This is not causing issues but there is no reason why the default
documentation should provide the hard way to do it instead of the easy
one.
-
=> [Metricbeat] gcp: update gke example documentation

CHANGELOG.next.asciidoc, metricbeat/module/windows/perfmon/perfmon.go, metricbeat/module/windows/perfmon/perfmon_test.go, metricbeat/module/windows/perfmon/reader.go, metricbeat/module/windows/perfmon/reader_integration_test.go, x-pack/metricbeat/module/iis/application_pool/reader.go
- adjusts pdhcollectquerydataex collecting interval, definition was confusing, between sample interval and wait interval
- reuse event to collect data
- fixes delay in ingestion
cc @adriansr 
Closes https://github.com/elastic/beats/issues/30686
=> Adjust pdhcollectquerydataex sample interval

libbeat/docs/shared-autodiscover.asciidoc, libbeat/processors/add_kubernetes_metadata/docs/add_kubernetes_metadata.asciidoc, metricbeat/docs/modules/kubernetes.asciidoc, metricbeat/metricbeat.reference.yml, metricbeat/module/kubernetes/_meta/config.reference.yml, x-pack/metricbeat/metricbeat.reference.yml
- align `add_resource_metadata` documentations
- add missing `cronjob` parameter
- add `include_labels`, `exclude_labels` and `include_annotations` to the documentation
- Closes #https://github.com/elastic/beats/issues/20651
=> Align `add_resource_metadata` documentation

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> Forward port 8.1.1 changelog to main

metricbeat/module/elasticsearch/_meta/README.md
Adds a README.md to the elasticsearch module https://github.com/elastic/kibana/issues/127209
-
=> Add README to elasticsearch module

metricbeat/docs/modules/kubernetes.asciidoc, metricbeat/module/kubernetes/_meta/docs.asciidoc, metricbeat/module/kubernetes/_meta/kibana/7/dashboard/e0381d10-e4a6-11eb-9d53-3b3d1d47c519.json, metricbeat/module/kubernetes/_meta/kibana/7/visualization/022a54c0-2bf5-11e7-859b-f78b612cde28-ecs.json, metricbeat/module/kubernetes/_meta/kibana/7/visualization/16fa4470-2bfd-11e7-859b-f78b612cde28-ecs.json, metricbeat/module/kubernetes/_meta/kibana/7/visualization/174a6ad0-30e0-11e7-8df8-6d3604a72912-ecs.json, metricbeat/module/kubernetes/_meta/kibana/7/visualization/294546b0-30d6-11e7-8df8-6d3604a72912-ecs.json, metricbeat/module/kubernetes/_meta/kibana/7/visualization/408fccf0-30d6-11e7-8df8-6d3604a72912-ecs.json, metricbeat/module/kubernetes/_meta/kibana/7/visualization/44f12b40-2bf4-11e7-859b-f78b612cde28-ecs.json, metricbeat/module/kubernetes/_meta/kibana/7/visualization/58e644f0-30d6-11e7-8df8-6d3604a72912-ecs.json, metricbeat/module/kubernetes/_meta/kibana/7/visualization/7aac4fd0-30e0-11e7-8df8-6d3604a72912-ecs.json, metricbeat/module/kubernetes/_meta/kibana/7/visualization/a4c9d360-30df-11e7-8df8-6d3604a72912-ecs.json, metricbeat/module/kubernetes/_meta/kibana/7/visualization/cd059410-2bfb-11e7-859b-f78b612cde28-ecs.json, metricbeat/module/kubernetes/_meta/kibana/7/visualization/d54c65f0-e4a6-11eb-9d53-3b3d1d47c519.json, metricbeat/module/kubernetes/_meta/kibana/7/visualization/d6564360-2bfc-11e7-859b-f78b612cde28-ecs.json, metricbeat/module/kubernetes/_meta/kibana/7/visualization/da1ff7c0-30ed-11e7-b9e5-2b5b07213ab3-ecs.json, metricbeat/module/kubernetes/_meta/kibana/7/visualization/e1018b90-2bfb-11e7-859b-f78b612cde28-ecs.json
Follow up of https://github.com/elastic/beats/pull/30913
=> Fix k8s dashboard to use proper timerange

metricbeat/module/logstash/_meta/README.md
Provides a basic overview document for the logstash metricbeat module
So new developers can have a basic understanding of what the module does and how it works.
Stretch:
- ~~Of the documents and fields that we store, how many are queried by the Kibana app? How many are never queried?~~
- ~~Of the documents and fields queried, which are used for which graphs and charts and tables etc in the UI?~~
N/A
- Closes https://github.com/elastic/kibana/issues/127808
N/A
N/A
N/A
=> [Stack Monitoring] Readme for logstash module

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 7.17.2.
=> docs: update docs versions 7.17.2

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 8.1.2.
=> docs: update docs versions 8.1.2

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 8.1.2

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 7.17.2

libbeat/docs/communitybeats.asciidoc
Added link to the free timebeat.app beat.
=> Added Link to timebeat

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> Forward port 8.1.2 changelog to 8.2

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> Forward port 8.1.2 changelog to main

.ci/packaging.groovy
=> Skip branch 7.17

filebeat/docs/modules/osquery.asciidoc, filebeat/module/osquery/_meta/docs.asciidoc
Replaces https://github.com/elastic/beats/pull/30762
=> Fix typo in it-compliance pack name

filebeat/docs/modules/juniper.asciidoc, x-pack/filebeat/module/juniper/_meta/docs.asciidoc
Fix typo for Juniper module / Junos fileset example
=> [DOC] Typo for Juniper module / Junos fileset example

.github/workflows/qa-labels.yml
We were using wrong type from issueId, it should have been an `ID` instead of a `String`
-
=> Update qa-labels.yml to fix type mismatch

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 7.17.3.
=> docs: update docs versions 7.17.3

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 7.17.3

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 8.1.3

CHANGELOG.next.asciidoc, x-pack/winlogbeat/module/powershell/ingest/powershell.yml, x-pack/winlogbeat/module/powershell/ingest/powershell_operational.yml, x-pack/winlogbeat/module/security/ingest/security.yml, x-pack/winlogbeat/module/sysmon/ingest/sysmon.yml
This fixes the missing event.module field in winlogbeat documents.
This is a commonly used field and removal was a regression.
- Closes #31330
=> x-pack/winlogbeat: set event.module to module name

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> Forward port 8.1.3 changelog to 8.2

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> Forward port 8.1.3 changelog to main

CHANGELOG.next.asciidoc
Adds missing PR number for #31331.
Documentation is important.
- Relates #31331.
=> changelog: fix missed pr number

CHANGELOG.next.asciidoc, x-pack/filebeat/input/netflow/convert.go, x-pack/filebeat/input/netflow/testdata/golden/ipfix_cisco.pcap.golden.json
This replaces an invalid field value.
This ensures that the integration and the filebeat module have matching behaviours.
- Relates integrations#3096
- Relates integrations#3047
=> x-pack/filebeat/input/netflow: replace invalid field value

CHANGELOG.next.asciidoc, x-pack/filebeat/module/google_workspace/admin/config/config.yml, x-pack/filebeat/module/google_workspace/drive/config/config.yml, x-pack/filebeat/module/google_workspace/groups/config/config.yml, x-pack/filebeat/module/google_workspace/login/config/config.yml, x-pack/filebeat/module/google_workspace/saml/config/config.yml, x-pack/filebeat/module/google_workspace/user_accounts/config/config.yml
Fixes the module config to prevent skipping events by using incorrect startDate values on pagination.
Skipped events when more than one page is present.
~- [] My code follows the style guidelines of this project~
~- [] I have commented my code, particularly in hard-to-understand areas~
~- [] I have made corresponding changes to the documentation~
~- [] I have added tests that prove my fix is effective or that my feature works~
=> [filebeat] Fix pagination bug that skipped events when more than one page is present

libbeat/docs/communitybeats.asciidoc
... the way it was written read as though the user can't develop custom beats. The actual fact is that custom beat generator was deprecated (i.e the tool/script that generated the beats)
-
=> correction on custom beat generator

libbeat/docs/release-notes/breaking/breaking-8.2.asciidoc, libbeat/docs/release-notes/breaking/breaking.asciidoc
Adds Beats 8.2 breaking changes page. Let me know if there are any BCs that I've missed. 
The stack upgrade guide requires this file.
=> Add breaking changes for Beats 8.2

x-pack/metricbeat/module/cockroachdb/status/_meta/data.json
The data.json file is blank. Added an example document.
- Closes #22951
=> Example document added to data.json file

Jenkinsfile, x-pack/filebeat/input/awss3/_meta/terraform/main.tf, x-pack/filebeat/input/awss3/_meta/terraform/variables.tf, x-pack/metricbeat/module/aws/terraform.tf, x-pack/metricbeat/module/aws/variables.tf
Standardise the below tags/labels in the terraform resources for AWS/GCP:
- `environment` => static value
- `repo`.              => static value
- `branch`           => dynamic value
- `build`              => dynamic value 
- `created_date` => dynamic value
Bump the aws terraform version to https://github.com/hashicorp/terraform-provider-aws/blob/v3.33.0/CHANGELOG.md 
In addition, I refactored the cloud stage to use one node rather than two, since it created the context in one node and then run the tests in another node
Help with tearing down any of the ephemeral resources which were not successfully removed as part of the system tests.
* Those tag/labels are lowercase based to be [GCP](https://cloud.google.com/resource-manager/docs/creating-managing-labels#requirements)/[AWS](https://docs …
=> [ci][terraform] tags with metadata

Jenkinsfile
Partially backport https://github.com/elastic/beats/pull/30907/commits/4820498241c82690837d53900dbc49e86b3f59d0 to help with the merge conflicts
Allow stage level customisation to configure GCP
=> [7.17] ci: configure GCP at the stage level

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 8.2.0

x-pack/elastic-agent/CHANGELOG.next.asciidoc, x-pack/elastic-agent/pkg/agent/application/upgrade/step_download.go, x-pack/elastic-agent/pkg/artifact/config.go, x-pack/elastic-agent/pkg/artifact/download/http/downloader.go, x-pack/elastic-agent/pkg/artifact/download/http/downloader_test.go, x-pack/elastic-agent/pkg/artifact/download/http/elastic_test.go, x-pack/elastic-agent/pkg/artifact/download/localremote/downloader.go, x-pack/elastic-agent/pkg/artifact/download/snapshot/downloader.go
Backports https://github.com/elastic/elastic-agent/pull/308
=> Backport elastic/elastic-agent #308

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
Adds a missing documentation for the delegated_account option for Google Oauth2
=> [filebeat][httpjson] Add missing docs for the delegated_account option

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> Forward port 8.2.0 changelog to main

CHANGELOG.next.asciidoc, libbeat/common/encoding/xml/decode.go, libbeat/processors/decode_xml/decode_xml_test.go
This change allows the xml decoder to attempt to decode text that claims to be other
than UTF-8. This allows us to decode documents that have been transformed from other
encodings but have not had their encoding declaration updated to match.
In the case that the text is not UTF-8 we only change the behaviour slightly by
altering the error message from e.g. 'encoding "utf-16" declared but
Decoder.CharsetReader is nil' to e.g. 'XML syntax error on line 1: invalid UTF-8'.
Currently we reject text that claims to be another encoding even if it is actually UTF-8. We will still fail on non-UTF-8 text, but with a slightly different error.
- Closes #31395
=> libbeat/common/encoding/xml: ignore encoding declarations in proc inst

CHANGELOG.next.asciidoc, packetbeat/_meta/sample_outputs/sip.json, packetbeat/protos/sip/README.md, packetbeat/protos/sip/plugin.go, packetbeat/tests/system/golden/sip-expected.json, packetbeat/tests/system/golden/sip_authenticated_register-expected.json
- Relates elastic/integrations#3329
=> packetbeat: move "protocol" term from event.category to event.type in SIP events

packetbeat/docs/packetbeat-options.asciidoc
This fixes the formatting of the `internal_networks` heading which currently looks like this.
Currently incorrectly formatted.
-
=> packetbeat: fix doc formatting

CHANGELOG.next.asciidoc, dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl, dev-tools/packaging/templates/docker/Dockerfile.tmpl
We've been on an old node version for a while, this is the latest LTS version.
=> [Heartbeat] Update agent-complete node version to 16.15.0

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 8.2.1

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 7.17.4

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 7.17.4.
=> docs: update docs versions 7.17.4

metricbeat/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
Updates test environments for 8.2.2.
=> [Release] Update test environments for 8.2.2

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 8.2.2

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> Forward-port 8.2.2 changelog to main

CHANGELOG.asciidoc
=> Remove entries that are for 8.3

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 8.2.2.
=> docs: update docs versions 8.2.2

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Update the docs for next minor 8.4.0.
Merge after the release branch for 8.2.1 is created.
=> [Release] Update docs for the 8.4.0 release

dev-tools/mage/target/integtest/integtest.go
This fixes the comment referring to the new integration targets.
The existing comment was missed and can cause confusion.
-
=> dev-tools/mage/target/integtest: fix comment

.ci/packaging.groovy
it adds a parameter to allow disabling the e2e test on the packaging job.
This is a workaround to unblock other teams to have beats binaries in the DRA process, it should be only used as the last resource. This workaround will generate broken/buggy binaries. The tests broken should be fixed, or removed, or whatever action that proceeded instead of using this workaround.
- ~~[ ] I have added an entry in `CHANGELOG.next.asciidoc` …
=> chore: allow disable e2e test on the package job

x-pack/libbeat/management/manager.go
This commit fixes a logging bug and follows Go's convention for naming
error variables.
It fixes a bug.
~~## Logs~~
=> libbeat: fix logging bug

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 8.2.3.
=> docs: update docs versions 8.2.3

metricbeat/module/kibana/settings/_meta/docs.asciidoc, metricbeat/module/kibana/stats/_meta/docs.asciidoc
Fixes broken structure reported in the discussion here: https://github.com/elastic/cloud/issues/103125#issuecomment-1150467643
=> Add float tags to fix broken topic structure

x-pack/metricbeat/module/istio/proxy/_meta/docs.asciidoc
=> Update docs.asciidoc (#31769)

libbeat/outputs/kafka/docs/kafka.asciidoc
Fixes attributes used plus a comma splice.
=> [DOCS] Use correct attribute for beat name in Kafka output docs

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 8.2.3

libbeat/metric/system/cgroup/reader.go
This is a quasi-backport of https://github.com/elastic/elastic-agent-system-metrics/pull/26 into 7.17
This fixes a bug where certain hybrid cgroups processes would not correctly report root IDs.
=> Fix root cgroups behavior

x-pack/winlogbeat/module/powershell/ingest/powershell.yml, x-pack/winlogbeat/module/powershell/ingest/powershell_operational.yml, x-pack/winlogbeat/module/routing/ingest/routing.yml, x-pack/winlogbeat/module/security/ingest/security.yml, x-pack/winlogbeat/module/sysmon/ingest/sysmon.yml
This moves setting `event.ingested` from individual pipelines to the routing pipeline.
The change allows enrichment of events with `event.ingested` from outside the four existing pipelines.
- Closes #30516.
- Requires #30406.
=> x-pack/winlogbeat: move event.ingested setting to routing

filebeat/input/filestream/input_integration_test.go
This PR ports the test `test_rotating_close_inactive_larger_write_rate` to Golang for `filestream` input.
Decrease the amount of low value E2E tests. Also, check `filestream` against corner cases.
=> Port `test_rotating_close_inactive_larger_write_rate` to Golang

libbeat/docs/release-notes/breaking/breaking-8.3.asciidoc, libbeat/docs/release-notes/breaking/breaking.asciidoc
Please add a comment to this PR if there are any breaking changes in 8.3.
=> Add Beats breaking changes for 8.3

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 8.3.0

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
See https://github.com/elastic/beats/pull/32130 and https://github.com/elastic/beats/pull/32131
=> Forward port 8.2.3 and 8.3 change logs

x-pack/filebeat/input/httpjson/rate_limiter.go
This replaces the use of a `time.Ticker` with a `time.Timer` for a single-shot wait.
It uses a more appropriate type for the task.
-
=> x-pack/filebeat/input/httpjson: use timer instead of ticker for singleshot

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 8.3.1

libbeat/docs/template-config.asciidoc
Add missing quotation marks for `setup.template.json.name`
-
=> [DOCS] Add missing quotation marks for setup.template.json.name

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 8.3.2.
=> docs: update docs versions 8.3.2

CHANGELOG.next.asciidoc, x-pack/filebeat/module/o365/audit/config/pipeline.js
Types added from
https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema#enum-auditlogrecordtype---type-edmint32
This adds missing event type mappings for o365 Audit events.
It brings it into line with the types supported by the o365 integration.
- Relates elastic/integrations#3380
- Relates elastic/integrations#3588
=> x-pack/filebeat/module/o365: add record types beyond 66

filebeat/docs/inputs/input-container.asciidoc, filebeat/docs/running-on-kubernetes.asciidoc
Fixes Filebeat doc build error.
Replaces https://github.com/elastic/beats/pull/32306
=> Fix build error

libbeat/docs/monitoring/monitoring-metricbeat.asciidoc
Forward-ports #31795 to main branch.
=> Update monitoring-metricbeat.asciidoc (#31795)

Jenkinsfile
No GitHub issues if aborted
As requested in https://github.com/elastic/beats/issues/32428#issuecomment-1191448686
=> ci: avoid creating github issues when aborted

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 8.3.3.
=> docs: update docs versions 8.3.3

metricbeat/docs/modules/aws.asciidoc, x-pack/metricbeat/module/aws/_meta/docs.asciidoc, x-pack/metricbeat/module/aws/cloudwatch/_meta/docs.asciidoc
Update AWS docs to clarify tag filtering configuration
https://github.com/elastic/beats/pull/32358
https://github.com/elastic/beats/pull/32408
=> Update AWS docs to clarify tag filtering configuration

CHANGELOG.next.asciidoc
#32480 was merged with extra changelog entries.
=> Fix CHANGELOG in 8.3 branch

CHANGELOG.next.asciidoc
add changelog for https://github.com/elastic/beats/pull/32170
=> add changelog for gcp distribution pr

CHANGELOG.next.asciidoc, winlogbeat/Jenkinsfile.yml, winlogbeat/sys/wineventlog/bookmark.go, winlogbeat/sys/wineventlog/format_message.go, winlogbeat/sys/wineventlog/iterator.go, winlogbeat/sys/wineventlog/iterator_test.go, winlogbeat/sys/wineventlog/metadata_store.go, winlogbeat/sys/wineventlog/metadata_store_test.go, winlogbeat/sys/wineventlog/publisher_metadata.go, winlogbeat/sys/wineventlog/renderer.go, winlogbeat/sys/wineventlog/syscall_windows.go, winlogbeat/sys/wineventlog/template.go, winlogbeat/sys/wineventlog/wineventlog_windows.go, x-pack/winlogbeat/Jenkinsfile.yml
This fixes two issues in winlogbeat that cause CI to fail on Windows 11.
Previously the build was disabled on that version, reducing coverage.
- Fixes #32468
- Fixes #32469
=> winlogbeat: fix testing on windows 11 and re-enable

libbeat/tests/system/beat/beat.py
Changes beats python tests to use a unique working directory.  The last 5 working directories for each test are kept.
A random number between 0 - 999 is added to the working directory name.  It is small because we are already very close to the 260 path character limit in Windows.
In CI we have seen errors where something causes a test to fail (usually resource being unavailable) and then when CI tries to re-run the test we get errors where a working directory can not be deleted because of a `filebeat.lock` file being in use.  This error doesn't happen in the original test that had the issue.
Giving each run of the test it's own working directory gets around this issue.
~~- [ ] I have made corresponding change to the default …
=> unique working dir for python system_tests

packetbeat/flows/worker.go
This replaces the GCD algorithm used in packetbeat/flows with the canonical algorithm which is simpler, and faster in the majority of cases.
The previous code was unnecessarily complex.
- Relates #32654.
=> packetbeat/flows: use canonical GCD algorithm

packetbeat/procs/procs.go
This removes an unnecessary assignment.
It simplifies the code base.
- Relates #32654
=> packetbeat/procs: don't unnecessarily set localAddrs

CHANGELOG.next.asciidoc, winlogbeat/eventlog/wineventlog.go
Previously a failure to salvage a message for a Windows logging event would be
logged as an error. This can cause unnecessary concern, so log as a warning. Also
log the event ID/qualifier and the creation time so that lost-message events can
be more easily found in indexed documents for confirmation.
The presence of an error in the logs causes undue concern in users.
-
=> winlogbeat/eventlog: reduce severity of message salvage failure logging

CHANGELOG.next.asciidoc, packetbeat/protos/tcp/tcp.go
This fixes the formatting of the port map in NewTCP which was caused by
incorrectly calling debugf with a selector. The debugf function value
was being constructed by the deprecated logp.MakeDebug. So instead use
logp.Debug with a selector in all places where debugf was used.
Not a serious bug, so not backporting.
It improves product perception.
-
=> packetbeat/protos/tcp: fix formatting of debug logs

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 7.17.6.
=> docs: update docs versions 7.17.6

packetbeat/procs/procs_windows.go, packetbeat/procs/procs_windows_test.go
This simplifies the retrieval of IPv4 and port numbers from the memory obtained from the Windows API.
It reduces the complexity of the code base.
Checkout the first commit in the PR and test that on a Windows machine to confirm that the tests agree with the existing behaviour.
- Relates #32654
=> packetbeat/procs: simplify construction of port and IPv4 values

libbeat/docs/release-notes/breaking/breaking-8.4.asciidoc, libbeat/docs/release-notes/breaking/breaking.asciidoc
Adds breaking changes document for 8.4.
Required by the stack installation/upgrade guide
=> Add Beats breaking changes for 8.4

dev-tools/packaging/templates/ironbank/elastic-agent/hardening_manifest.yaml
Update the product name for the Ironbank releases for `elastic-agent`
Similar to https://github.com/elastic/elastic-agent/pull/1009 but in this case `elastic/beats.git` is the one with the source code for elastic-agent 7.17
=> elastic agent ironbank product name

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 8.4.1

heartbeat/docs/running-on-docker.asciidoc, heartbeat/docs/running-on-kubernetes.asciidoc, libbeat/docs/shared-docker.asciidoc
Update HB public documentation to register capability requirements for Docker and K8s setups.
We've had instances where this requirement was not met and it generated confusion.
- Build documentation locally following [docs guide](https://github.com/elastic/docs) and check new content is available.
=> Add cap_net_raw requirements to heartbeat docs

metricbeat/docs/modules/gcp.asciidoc, x-pack/metricbeat/module/gcp/_meta/docs.asciidoc, x-pack/metricbeat/module/gcp/metrics/_meta/docs.asciidoc
Updates `gcp` module docs to fix required permissions list.
Updated `gcp.metrics` metricset docs to remove example for collecting set of metrics starting with prefix.
The first because without that permissions compute information cannot be retrieved.
The second because we do not support that use case so the configuration is misleading.
-
=> [GCP] update permissions and remove wrong config example

x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
The example URLs do not need to be followable and in some cases include syntax
for demonstration purposes that is not valid for a URL and causes the AsciiDoc
to be incorrectly rendered. So make sure that the example URLs are not touched.
The documentation is currently made unclear by mis-rendering.
- Updates #32321
=> x-pack/filebeat/docs/inputs/input-httpjson: don't linkify example URLs

Jenkinsfile
to [support MacOS M1](https://discuss.hashicorp.com/t/mac-m1-terraform-versions-missing-from-repo/35677)
Unblocks https://github.com/elastic/beats/pull/32173
=> bump terraform version

x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml
This cleans up the grok pattern naming so that the name matches the target.
It improves code clarity.
- Relates #elastic/integrations#3507
=> x-pack/filebeat/module/cisco/{asa,ftd}: rename syslog priority grok pattern SYSLOGFACILITY=>SYSPRIORITY

.ci/jobs/beats-release-minor-major-project.yml, .ci/jobs/beats-release-patch-project.yml
Create JJBB for the new jobs to drive the release for specific projects.
Simplify the release for all the observability projects or similar ones that were onboarded with the automation we built
=> jjbb: create project type

CHANGELOG.next.asciidoc, x-pack/filebeat/module/cisco/asa/test/additional_messages.log-expected.json, x-pack/filebeat/module/cisco/asa/test/non-canonical.log-expected.json, x-pack/filebeat/module/cisco/asa/test/sample.log-expected.json, x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml
This fixes handling of Cisco 302020 messages that were previously miscategorised as flow-termination events rather than flow-creation events.
Miscategorisations can impact on security analysis.
- Updates elastic/integrations#4199
=> x-pack/filebeat/module/cisco: fix handling of 302020 messages

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 8.4.2.
=> docs: update docs versions 8.4.2

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 8.4.2

packetbeat/beater/packetbeat.go, packetbeat/beater/processor.go, packetbeat/config/agent.go, packetbeat/config/agent_test.go, packetbeat/config/config.go, packetbeat/config/config_test.go, packetbeat/sniffer/sniffer.go
Currently only the first interface is used, retaining the existing behaviour. If
command line arguments are provided the existing behaviour is kept with the first
interface having options from the command line replacing being placed in that
config as defaults, replaced by the options in the config file.
This is required for allowing multiple interfaces to be specified.
- For #31905
=> packetbeat/config: allow multiple interfaces to be specified in the config

packetbeat/beater/packetbeat.go, packetbeat/config/agent.go, packetbeat/config/config.go, packetbeat/config/config_test.go, packetbeat/sniffer/sniffer.go
This cleans up a name.
Code clarity
- For #31905
=> packetbeat/config: rename InterfaceConfigs => InterfaceConfig

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Update the docs for next minor 8.6.0.
Merge after the release branch for 8.4.2 is created.
=> [Release] Update docs for the 8.6.0 release

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 8.4.3.
=> docs: update docs versions 8.4.3

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 8.4.3

filebeat/input/log/harvester.go, filebeat/input/log/input.go
Signed-off-by: Florian Lehner <florian.lehner@elastic.co>
This PR fixes bugs of incorrect checks.
no relevant code changes
no relevant code changes
no relevant code changes
existing tests cover the relevant changes
no relevant code changes
=> filebeat: fix check against nil

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 7.17.7.
=> docs: update docs versions 7.17.7

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 8.5.0

x-pack/osquerybeat/internal/distro/distro.go
Upgrade to osquery 5.5.1.
Picking up the latest osquery release.
=> Osquerybeat: Upgrade to osquery 5.5.1

CHANGELOG.next.asciidoc
Removes duplicated auditbeat and filebeat sections in "added" and "bugfixes". These appear to have been added in 68872a0e7f8.
-
=> changelog: remove duplicate auditbeat and filebeat headings

docs/devguide/metricset-details.asciidoc, metricbeat/module/elasticsearch/node/_meta/docs.asciidoc, metricbeat/module/elasticsearch/node_stats/_meta/docs.asciidoc
Backports https://github.com/elastic/beats/pull/33319 to 6.1 branch.
=> [DOCS] Fix hard-coded mapping type doc link

metricbeat/module/elasticsearch/node/_meta/docs.asciidoc, metricbeat/module/elasticsearch/node_stats/_meta/docs.asciidoc
=> [DOCS] Fix hard-coded mapping type doc link (#33491)

docs/devguide/metricset-details.asciidoc, metricbeat/module/elasticsearch/node/_meta/docs.asciidoc, metricbeat/module/elasticsearch/node_stats/_meta/docs.asciidoc
=> [8.2][DOCS] Fix hard-coded mapping type doc link

docs/devguide/metricset-details.asciidoc, metricbeat/module/elasticsearch/node/_meta/docs.asciidoc, metricbeat/module/elasticsearch/node_stats/_meta/docs.asciidoc
=> [8.1][DOCS] Fix hard-coded mapping type doc link

docs/devguide/metricset-details.asciidoc, metricbeat/module/elasticsearch/node/_meta/docs.asciidoc, metricbeat/module/elasticsearch/node_stats/_meta/docs.asciidoc
=> [8.0][DOCS] Fix hard-coded mapping type doc link

docs/devguide/metricset-details.asciidoc, metricbeat/module/elasticsearch/node/_meta/docs.asciidoc, metricbeat/module/elasticsearch/node_stats/_meta/docs.asciidoc
=> [7.1][DOCS] Fix hard-coded mapping type doc link

docs/devguide/metricset-details.asciidoc, metricbeat/module/elasticsearch/node/_meta/docs.asciidoc, metricbeat/module/elasticsearch/node_stats/_meta/docs.asciidoc
=> [7.3][DOCS] Fix hard-coded mapping type doc link

docs/devguide/metricset-details.asciidoc, metricbeat/module/elasticsearch/node/_meta/docs.asciidoc, metricbeat/module/elasticsearch/node_stats/_meta/docs.asciidoc
=> [7.4][DOCS] Fix hard-coded mapping type doc link

docs/devguide/metricset-details.asciidoc, metricbeat/module/elasticsearch/node/_meta/docs.asciidoc, metricbeat/module/elasticsearch/node_stats/_meta/docs.asciidoc
=> [7.5][DOCS] Fix hard-coded mapping type doc link

docs/devguide/metricset-details.asciidoc, metricbeat/module/elasticsearch/node/_meta/docs.asciidoc, metricbeat/module/elasticsearch/node_stats/_meta/docs.asciidoc
=> [7.2][DOCS] Fix hard-coded mapping type doc link

docs/devguide/metricset-details.asciidoc, metricbeat/module/elasticsearch/node/_meta/docs.asciidoc, metricbeat/module/elasticsearch/node_stats/_meta/docs.asciidoc
=> [7.0][DOCS] Fix hard-coded mapping type doc link

docs/devguide/metricset-details.asciidoc, metricbeat/module/elasticsearch/node/_meta/docs.asciidoc, metricbeat/module/elasticsearch/node_stats/_meta/docs.asciidoc
=> [7.17][DOCS] Fix hard-coded mapping type doc link

CHANGELOG.asciidoc
See https://github.com/elastic/observability-docs/issues/2306.
=> docs: add known issue for 8.5.0

docs/devguide/metricset-details.asciidoc, metricbeat/module/elasticsearch/node/_meta/docs.asciidoc, metricbeat/module/elasticsearch/node_stats/_meta/docs.asciidoc
=> [6.3][DOCS] Fix hard-coded mapping type doc link

docs/devguide/metricset-details.asciidoc, metricbeat/module/elasticsearch/node/_meta/docs.asciidoc, metricbeat/module/elasticsearch/node_stats/_meta/docs.asciidoc
=> [6.5][DOCS] Fix hard-coded mapping type doc link

docs/devguide/metricset-details.asciidoc, metricbeat/module/elasticsearch/node/_meta/docs.asciidoc, metricbeat/module/elasticsearch/node_stats/_meta/docs.asciidoc
=> [6.4][DOCS] Fix hard-coded mapping type doc link

docs/devguide/metricset-details.asciidoc, metricbeat/module/elasticsearch/node/_meta/docs.asciidoc, metricbeat/module/elasticsearch/node_stats/_meta/docs.asciidoc
=> [6.6][DOCS] Fix hard-coded mapping type doc link

docs/devguide/metricset-details.asciidoc, metricbeat/module/elasticsearch/node/_meta/docs.asciidoc, metricbeat/module/elasticsearch/node_stats/_meta/docs.asciidoc
=> [6.7][DOCS] Fix hard-coded mapping type doc link

docs/devguide/metricset-details.asciidoc, metricbeat/module/elasticsearch/node/_meta/docs.asciidoc, metricbeat/module/elasticsearch/node_stats/_meta/docs.asciidoc
=> [7.7][DOCS] Fix hard-coded mapping type doc link

docs/devguide/metricset-details.asciidoc, metricbeat/module/elasticsearch/node/_meta/docs.asciidoc, metricbeat/module/elasticsearch/node_stats/_meta/docs.asciidoc
=> [7.16][DOCS] Fix hard-coded mapping type doc link

docs/devguide/metricset-details.asciidoc, metricbeat/module/elasticsearch/node/_meta/docs.asciidoc, metricbeat/module/elasticsearch/node_stats/_meta/docs.asciidoc
=> [7.15][DOCS] Fix hard-coded mapping type doc link

docs/devguide/metricset-details.asciidoc, metricbeat/module/elasticsearch/node/_meta/docs.asciidoc, metricbeat/module/elasticsearch/node_stats/_meta/docs.asciidoc
=> [7.14][DOCS] Fix hard-coded mapping type doc link

docs/devguide/metricset-details.asciidoc, metricbeat/module/elasticsearch/node/_meta/docs.asciidoc, metricbeat/module/elasticsearch/node_stats/_meta/docs.asciidoc
=> [7.12][DOCS] Fix hard-coded mapping type doc link

docs/devguide/metricset-details.asciidoc, metricbeat/module/elasticsearch/node/_meta/docs.asciidoc, metricbeat/module/elasticsearch/node_stats/_meta/docs.asciidoc
=> [7.10][DOCS] Fix hard-coded mapping type doc link

docs/devguide/metricset-details.asciidoc, metricbeat/module/elasticsearch/node/_meta/docs.asciidoc, metricbeat/module/elasticsearch/node_stats/_meta/docs.asciidoc
=> [7.11][DOCS] Fix hard-coded mapping type doc link

docs/devguide/metricset-details.asciidoc, metricbeat/module/elasticsearch/node/_meta/docs.asciidoc, metricbeat/module/elasticsearch/node_stats/_meta/docs.asciidoc
=> [7.9][DOCS] Fix hard-coded mapping type doc link

docs/devguide/metricset-details.asciidoc, metricbeat/module/elasticsearch/node/_meta/docs.asciidoc, metricbeat/module/elasticsearch/node_stats/_meta/docs.asciidoc
=> [7.8][DOCS] Fix hard-coded mapping type doc link

docs/devguide/metricset-details.asciidoc, metricbeat/module/elasticsearch/node/_meta/docs.asciidoc, metricbeat/module/elasticsearch/node_stats/_meta/docs.asciidoc
=> [7.6][DOCS] Fix hard-coded mapping type doc link

docs/devguide/metricset-details.asciidoc, metricbeat/module/elasticsearch/node/_meta/docs.asciidoc, metricbeat/module/elasticsearch/node_stats/_meta/docs.asciidoc
=> [6.8][DOCS] Fix hard-coded mapping type doc link

CHANGELOG.asciidoc
For reference https://discuss.elastic.co/t/heartbeat-8-5-0-parsing-errors/318031
=> [Heartbeat] add known issue - states mapping

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-httpjson.asciidoc, x-pack/filebeat/input/httpjson/client_other.go, x-pack/filebeat/input/httpjson/client_windows.go, x-pack/filebeat/input/httpjson/input.go, x-pack/filebeat/input/httpjson/request_chain_helper.go, x-pack/filebeat/input/httpjson/request_chain_helper_test.go
This adds support for requests to endpoints over Unix sockets and Windows named pipes using the `https?+(unix|npipe)` schemes. No testing at this stage since httpjson test infrastructure assumes a TCP transport.
From #33571
> This would be used connect to internal services that are only exposed locally. Services like [Beats HTTP monitoring endpoint](https://www.elastic.co/guide/en/beats/filebeat/current/http-endpoint.html) and Docker have APIs that listen on unix sockets. It would be useful if httpjson (and any future inputs that also monitor arbitrary HTTP services) could monitor data from these local APIs.
- Closes #33571
=> x-pack/filebeat/input/httpjson: add support for http+{unix,npipe} schemes

libbeat/processors/actions/docs/decompress_gzip_field.asciidoc
Looks like the content here was copy/pasted and not updated correctly.
=> [DOCS] Fix copy/paste errors

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 8.5.2.
=> docs: update docs versions 8.5.2

metricbeat/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
Updates test environments for 8.5.2.
=> [Release] Update test environments for 8.5.2

x-pack/filebeat/input/http_endpoint/input.go, x-pack/filebeat/input/http_endpoint/input_test.go
Configs may be run in arbitrary order during tests, so make sure that the formatted error is rendered in a canonicalised way. This has no impact on the logic of the input in production with the exception of how the user will see the error rendered in logs when the input is misconfigured.
This fixes a logic race that causes a flakey test failure.
Note that this is not robust against tests that include configurations with inconsistency and more than two server configurations (i.e. with more than one inconsistent pair). This should not be a problem, but should be noted in the case that such a test is added.
Although the race does not cause production issues, the test is expected to fail 50% of the time causing CI noise.
Details of before and after fix.
```
../input/http_endpoint [master] ❯❯❯ …
```
=> x-pack/filebeat/input/http_endpoint: canonicalise tls consistency error

x-pack/libbeat/processors/add_nomad_metadata/docs/add_nomad_metadata.asciidoc
=> [DOCS] Fix typo in add_nomad_metadata processor

.ci/ironbank-validation.groovy, .ci/packaging.groovy, Jenkinsfile
Change the slack channel as requested where to send notifications.
=> ci: change slack channel

NOTICE.txt, go.mod, go.sum
Updated elastic-agent-client to latest version fixing casing in reported unit state
=> Updated elastic-agent-client to v7.0.2-0.20221129150247-15881a8e64ef

filebeat/docs/filebeat-options.asciidoc, x-pack/filebeat/docs/inputs/input-cel.asciidoc
This links the CEL input documentation from the filebeat inputs configuration page.
It was missing.
-
=> filebeat/docs: link cel input documentation into inputs page

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 8.5.3

dev-tools/packaging/templates/ironbank/heartbeat/hardening_manifest.yaml
Signed-off-by: Adrien Mannocci <adrien.mannocci@elastic.co>
* Correct hardening manifest for ironbank assets.
* Switch to `dl.rockylinux.org` mirror to download dependencies.
* Correct ironbank releases
=> Correct hardening manifest for ironbank

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 7.17.8

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 7.17.8.
=> docs: update docs versions 7.17.8

CHANGELOG.asciidoc
Adds known issue for 8.5.3 related to https://github.com/elastic/integrations/issues/4735
=> [Heartbeat] add known issue for 8.5.3

NOTICE.txt, metricbeat/module/prometheus/collector/_meta/docs.asciidoc, metricbeat/module/prometheus/remote_write/_meta/docs.asciidoc
Add details regarding prometheus federation API - it return metrics untyped, rate metrics can't be calculated for metrics of type counter.
Add info how to filter metrics before sending them to remote endpoint in remote_write.
-
=> Prometheus documentation regarding federation API

.github/CODEOWNERS
Add @elastic/obs-cloudnative-monitoring as a codeowner for some beats modules
-
=> Add elastic/obs-cloudnative-monitoring as a codeowner for some beats modules

dev-tools/packaging/templates/ironbank/auditbeat/Dockerfile, dev-tools/packaging/templates/ironbank/auditbeat/hardening_manifest.yaml, dev-tools/packaging/templates/ironbank/filebeat/Dockerfile, dev-tools/packaging/templates/ironbank/filebeat/hardening_manifest.yaml, dev-tools/packaging/templates/ironbank/heartbeat/Dockerfile, dev-tools/packaging/templates/ironbank/heartbeat/hardening_manifest.yaml, dev-tools/packaging/templates/ironbank/metricbeat/Dockerfile, dev-tools/packaging/templates/ironbank/metricbeat/hardening_manifest.yaml, dev-tools/packaging/templates/ironbank/packetbeat/Dockerfile, dev-tools/packaging/templates/ironbank/packetbeat/hardening_manifest.yaml
Signed-off-by: Adrien Mannocci <adrien.mannocci@elastic.co>
* Update ironbank base image to ubi 8.7
* We need to use the latest ubi 8.x base image available.
Validation: https://beats-ci.elastic.co/job/Beats/job/ironbank-validation-mbp/view/change-requests/job/PR-34124/
=> Update ironbank base image to ubi 8.7

NOTICE.txt
Updating notice so automation PRs don't fail
=> Updated notice to contain proper year

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 8.6.0

x-pack/libbeat/management/managerV2.go
Follow up to https://github.com/elastic/beats/pull/34346 where the check step didn't block the merge.
=> Run make check and commit the changes.

x-pack/filebeat/input/azureblobstorage/input_test.go, x-pack/filebeat/input/gcs/input_test.go
##Type of change
- Bug
Disables flaky tests for the moment
builds were failing due to some flaky tests
- Relates #34332
=> disabling flaky tests for now

metricbeat/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
Updates test environments for 8.6.1.
=> [Release] Update test environments for 8.6.1

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 8.6.1

filebeat/docs/running-on-kubernetes.asciidoc
=> Fixingcontainerdocs

x-pack/elastic-agent/pkg/artifact/download/snapshot/downloader.go
Backport of elastic agent upgrade to snapshot version fixed in elastic agent 8.6 with PR [elastic/elastic-agent#1791](https://github.com/elastic/elastic-agent/pull/1791)
This ensures that elastic agents in version 7.17.9 and newer can be upgraded to a recent snapshot version.
=> Backport elastic agent 8.6.0 fix for upgrading to snapshots

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 7.17.9.
=> docs: update docs versions 7.17.9

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 7.17.9

x-pack/osquerybeat/internal/distro/distro.go
Upgrade to osquery 5.7.0.
Picking up the latest osquery release.
=> Osquerybeat: Upgrade to osquery 5.7.0

x-pack/filebeat/input/cel/config.go
Fixes a misleading error message.
The current message is incorrect and confusing.
-
=> x-pack/filebeat/input/cel: fix incorrect error message

packetbeat/decoder/decoder.go, packetbeat/procs/procs.go, packetbeat/protos/amqp/amqp.go, packetbeat/protos/cassandra/cassandra.go, packetbeat/protos/cassandra/internal/gocql/frame.go, packetbeat/protos/dns/dns.go, packetbeat/protos/dns/dns_udp.go, packetbeat/protos/http/http.go, packetbeat/protos/memcache/plugin_tcp.go, packetbeat/protos/memcache/plugin_udp.go, packetbeat/protos/mongodb/mongodb.go, packetbeat/protos/mysql/mysql.go, packetbeat/protos/nfs/rpc.go, packetbeat/protos/pgsql/pgsql.go, packetbeat/protos/redis/redis.go, packetbeat/protos/sip/plugin.go, packetbeat/protos/tcp/tcp.go, packetbeat/protos/thrift/thrift.go, packetbeat/protos/tls/buffer.go, packetbeat/protos/tls/parse.go, packetbeat/protos/tls/tls.go
It is generally not a good idea to recover from arbitrary panics and continue operating. Unhandled panic are recovered and logged with termination at the beats level.
In a couple of cases, the plugin uses panic/recover for flow control, this is retained, but tightened up so that original panics are logged and incidental panics that could leave the program in an invalid state are re-panicked.
Makes code more robust and improves debuggability.
-
=> packetbeat/{decoder,protos/...}: remove logp.Recover uses and tighten recovers

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 8.6.2

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 8.6.2.
=> docs: update docs versions 8.6.2

CHANGELOG.next.asciidoc, x-pack/filebeat/module/fortinet/firewall/ingest/pipeline.yml, x-pack/filebeat/module/fortinet/firewall/test/event.log-expected.json, x-pack/filebeat/module/fortinet/firewall/test/traffic.log-expected.json
Adds `{source,destination}.nat.ip` and `fortinet.firewall.{ip,assignip,tunnelip}` to `related.ip` array.
These addresses satisfy the definition for `related.ip`.
- Fixes #34640
=> x-pack/filebeat/module/fortinet: include NAT and firewall IPs in related.ip

dev-tools/notice/rules.json
This PR added support for Unlicense go packages.
Cloudbeat has a go dependency https://github.com/aquasecurity/tml/blob/master/LICENSE with that kind of license.
It seems like that license is very permissive and should be on our allow list. 
-
=> Support Unlicense go dependencies

docs/devguide/create-module.asciidoc
Related to [#3357](https://github.com/elastic/beats/issues/33577)
Fixes links in preparation for switching branch name to main.
=> [DOCS] Remove hard coded master link

CHANGELOG.next.asciidoc
Fixes errors in the changelog.
-
=> CHANGELOG: fix up pull entries

CHANGELOG.next.asciidoc, metricbeat/module/elasticsearch/ccr/data.go
Add `remote_cluster` property to ccr documents. This property is expected by Stack Monitoring when querying for ccr read exceptions
_Testing steps for Stack monitoring will be listed here https://github.com/elastic/kibana/pull/153888_
- setup ccr and trigger operations between indices
- enable elasticsearch module with `xpack.enabled: true`
- `elasticsearch.ccr.remote_cluster` is populated in `metricset.name: ccr` documents
- Related https://github.com/elastic/kibana/issues/153298
=> [elasticsearch] ingest ccr remote_cluster

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 8.7.0

filebeat/docs/inputs/input-tcp.asciidoc, filebeat/docs/inputs/input-udp.asciidoc
Fixes typos in documentation.
Image.
-
=> filebeat/input/{tcp,udp}: fix doc typos

metricbeat/module/vsphere/_meta/Dockerfile, metricbeat/module/vsphere/docker-compose.yml
It's used for metricbeat integration tests. The existing installation command stopped working because some Go compiler errors.
Our builds are failing https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats/detail/main/1398/pipeline/
In metricbeat:
```sh
mage pythonintegtest
```
=> Use go install for the vCenter and ESXi API based simulator

dev-tools/notice/overrides.json
Removes a license override for a personal repository that was used during development.
To avoid using personal repositories.
=> Removes unnecessary license override

x-pack/filebeat/docs/inputs/input-netflow.asciidoc
Fixes a docs bug introduced today.
Breaks docs build.
-
=> x-pack/filebeat/docs/inputs: fix netflow block id

libbeat/processors/processor.go
This is just a short cleanup to remove a helper function that is no longer used.
=> (Cleanup) Remove unused processor helper

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 8.7.1

x-pack/filebeat/input/cel/input_test.go, x-pack/filebeat/input/httpjson/input_test.go
Cleans up tempdir handling logic in tests.
Clarity/separation of test table from test logic and removal of impinging conflict diff for another PR that is pending.
-
=> x-pack/filebeat/input/{cel,httpjson}: clean up tempdir handling in tests

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
Prepare Changelog for 7.17.10.
=> docs: Prepare Changelog for 7.17.10

testing/environments/snapshot.yml
<Actions>
<action id="495f02861bc9edcb47bc44f57de6041a0e807e469978df237eaca185f79ac128">
</details>
</action>
<action id="d6ae724b1aa435f7902ad1e8e4d4713d4e1ed691d13b8d492c92c33383cb6d8c">
</details>
</action>
</Actions>
---
<ul>
<li>If …
=> [updatecli] update elastic stack version for testing 8.8.0-1fcea9ba

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 7.17.10.
=> docs: update docs versions 7.17.10

heartbeat/docs/monitors/monitor-icmp.asciidoc
We really only test against / have confirmed this working well with `setcap`. This PR updates the docs to reflect our recommended usage.
=> [Heartbeat] Fix docs around ICMP sysctl settings

NOTICE.txt, go.mod, go.sum
upgraded elastic-agent-client to v7.1.1 for pprof fix
Improves ability to debug
- Relates elastic/elastic-agent-client#69
- Relates elastic/elastic-agent#2530
=> upgrade elastic-agent-client to 7.1.1 for pprof fix

testing/environments/snapshot.yml
<Actions>
<action id="3ec1d356da5ef1e0016cbbcc8574670367bea867ab83a50dfbba973c8a88c74d">
</details>
</action>
<action id="bd85ba31537fb3d1985c62b753e26929ca4158c93bde6c6d00789b4cde8e5610">
</details>
</action>
</Actions>
---
<ul>
<li>If …
=> [updatecli] update elastic stack version for testing 8.8.0-97faefbe

.ci/packaging.groovy
Retry `release-manager` integration for the DRA if it failed
Temporarily workaround the existing issue with the release manager when running and returns:
```
Cannot invoke "String.length()" because "value" is null
```
This will run up to `3 times` regardless of the failure with some `sleep * factor`, see https://github.com/elastic/apm-pipeline-library/blob/main/vars/retryWithSleep.txt
Caveat, if there are some other errors then it will try again... I didn't want to get a complex algorithm so it could detect when to run based on the error in the logs since Jenkins is gonna be decommissioned in the future.
=> ci: retry release manager if it failed

metricbeat/helper/prometheus/ptest/ptest.go, metricbeat/module/etcd/metrics/metrics_test.go, metricbeat/module/kubernetes/apiserver/apiserver_test.go, metricbeat/module/kubernetes/controllermanager/controllermanager_test.go, x-pack/libbeat/common/proc/job_unix.go
This PR fixes the linter errors reported as part of https://github.com/elastic/beats/pull/35218
To keep the code clean/readable + to reduce linter noise from https://github.com/elastic/beats/pull/35218, hopefully making it easier to review.
- Pre-requisite for https://github.com/elastic/beats/pull/35218
=> Pre-cleanup for #35218

dev-tools/packaging/templates/docker/Dockerfile.tmpl
=> [Heartbeat] Bump node to 18.16.0

testing/environments/snapshot.yml
<Actions>
<action id="6fc49ab2bcf8627dcac34872ec14089a70ff3fc8b3a9a16d3fbb55983199f151">
</details>
</action>
<action id="bc9482451cdf388fc9bd41ddf67f18f03e64d25616770783588435710c3a6cfe">
</details>
</action>
</Actions>
---
<ul>
<li>If …
=> [updatecli] update elastic stack version for testing 8.8.0-4abaa07c

testing/environments/snapshot.yml
<Actions>
<action id="5dc37a049f62cbfc29a6eacadbc0e8f7da510b37e2b2d93c35a3e917a620953d">
</details>
</action>
<action id="62206b57acf87ce9c25927cfc489f84f5ba9b3f692d67cb0091c644242c09fca">
</details>
</action>
<action id="6d8744fc1ec07a3adac77344035f3cd19a3f0f7fa2798d7751df23fc84b30def">
<summary>Update …
=> [updatecli] update elastic stack version for testing 8.9.0-554074dc

CHANGELOG.next.asciidoc, metricbeat/docs/modules/activemq.asciidoc, x-pack/metricbeat/module/activemq/_meta/docs.asciidoc
- Bug
Install Activemq metricbeat module and verify the metrics getting processed.
Check for the documentation fix getting reflected
Closes #35113
=> Activemq metricbeat - Updated documentation to add space between words

x-pack/filebeat/docs/inputs/input-cel.asciidoc
Brings docs back into sync with the imported version.
- For #35572
=> x-pack/filebeat/docs/inputs/cel: update for mito@v1.2.0

CHANGELOG.next.asciidoc
Add the changelog for https://github.com/elastic/beats/issues/31767
This impact the users, therefore must have a changelog
- Relates #31767
=> Add changelog for #31767

auditbeat/Jenkinsfile.yml, packetbeat/Jenkinsfile.yml, x-pack/auditbeat/Jenkinsfile.yml, x-pack/packetbeat/Jenkinsfile.yml
Add config for Auditbeat and Packetbeat unit tests to be run on RHEL9, using [this image](https://github.com/elastic/infra/pull/38959).
I set these as `stage: mandatory` in order to have them run regularly without being manually activated. Please let me know if this is not the right use of that setting.
RHEL9 was released last May. We need to add support to our CI test matrix for Auditbeat/Packetbeat for the latest RHEL release to ensure we're testing this on a regular basis, and then we can add it to our support matrix.
e.g. [Build&Test / auditbeat-rhel-9-rhel-9](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-35634/detail/PR-35634/6/pipeline/1918), [Build&Test / x-pack/auditbeat-rhel-9-rhel-9](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats% …
=> CI: unit testing of Auditbeat and Packetbeat on RHEL9

CHANGELOG.next.asciidoc, x-pack/filebeat/input/gcs/input.go, x-pack/filebeat/input/gcs/input_stateless.go, x-pack/filebeat/input/gcs/scheduler.go
- Enhancement
1. Adds debug logs to critical sections.
2. Removes context from struct params and passes it as a function param.  
Addition of these debug logs will help debugging in future. The context param change is made with the intention of 
improving code standards.
~~- [] I have made corresponding changes to the documentation~~
=> [filebeat][gcs] - Enhanced context passing and added scheduler debug logs

testing/environments/snapshot.yml
<Actions>
<action id="0572b6eb733940b2b7a07e6cf5806598a3f9e0779b60f0dc80c565ef70a6d97e">
</details>
</action>
<action id="131bb1b662f77fe4952b54200727865f96a90b2819e40387f7ecf9f389530ed1">
</details>
</action>
<action id="253cff9d4b583f0672ad894a7ea0cfd532402821f7a56d1820343bd08110a995">
<summary>Update …
=> [updatecli] update elastic stack version for testing 8.9.0-b4b9b632

CHANGELOG.next.asciidoc, filebeat/input/tcp/input.go, filebeat/input/udp/input.go, filebeat/tests/system/test_tcp.py, filebeat/tests/system/test_udp.py, libbeat/tests/system/config/libbeat.yml.j2
The call incorrectly uses the IPv4 address list to populate the IPv6 unspecified address list. This will result in a panic when more IPv6 addresses than IPv4 addresses appear in the the hosts IP list as returned by net.LookupIP().
The current code crashes Filebeat under the conditions described.
- Fixes #35064
=> filebeat/input/tcp: fix call to get unspecified IPv6 addresses

x-pack/filebeat/docs/inputs/input-http-endpoint.asciidoc
Clarifies config requirements when using the CRC options.
Improve UX.
- Related to https://github.com/elastic/beats/pull/35604#discussion_r1213724829
=> x-pack/filebeat/docs/inputs/http_endpoint: Note that `crc.secret` is required in http_endpoint docs

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> [Release] Prepare Changelog for 8.8.1

x-pack/filebeat/input/httpjson/input_test.go, x-pack/filebeat/input/httpjson/metrics_test.go
The addition of metrics broke benchmarks due to thre repeated re-registration of the same ID. So make a new ID for each iteration of the benchmark.
Benchmarks otherwise panic.
-
=> x-pack/filebeat/input/httpjson: fix benchmarks

testing/environments/snapshot.yml
<Actions>
<action id="3951c2309de39497f86c12074614d2f2e395e3bd865e39ca61602c76003fd1a7">
</details>
</action>
<action id="b7778a0a318dd4b32f3bf91cb174bd7bb167469f166dce6bd9427b3a01983c86">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p> …
=> [updatecli] update elastic stack version for testing 8.8.2-0c8e2646

testing/environments/snapshot.yml
<Actions>
<action id="22c3169c35fb445fe040970b834348daaa2811218eab2a9aee70dc235058ab06">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 7.17.11-6470dfa7

CHANGELOG.next.asciidoc, NOTICE.txt, go.mod, go.sum, x-pack/filebeat/docs/inputs/input-cel.asciidoc
Updates the mito version for the CEL input.
Fixes a bug in JSON marshalling.
- Fixes #35763
=> x-pack/filebeat/input/cel: update mito version to v1.4.0

libbeat/docs/shared-autodiscover.asciidoc
Fixes https://github.com/elastic/beats/issues/35741
=> Fix condition matching note for kubernetes autodiscovery

testing/environments/snapshot.yml
<Actions>
<action id="6f103f95dea777685e14433521a6e00cead0b228286c0d168aa90f2c0dd21098">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 7.17.11-4433090a

testing/environments/snapshot.yml
<Actions>
<action id="061ca4545f73310be131a88e3ec7ac784e5a4aef2d169816397dd3dc1bf2e46a">
</details>
</action>
<action id="10b7a556e3abd3c2c4d1b35c6c96ac0876fa9aefc9399bd7495a03ed2fe2d9af">
</details>
</action>
<action id="3c295054bf6a3bd0313d8f60e6239c90f1dfab85f8dd6f557a23a75374a9908f">
<summary>Update …
=> [updatecli] update elastic stack version for testing 8.9.0-9ee1e6fb

testing/environments/snapshot.yml
<Actions>
<action id="82dfa4cdf2c94bed4655c6767e14d68c03eef1ffd57b153dc275c00112b463ab">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.8.2-6bda6fd3

testing/environments/snapshot.yml
<Actions>
<action id="59fbb117f39c394b2449f3f5d629f7373ae973e515efdf0cdcdf6717f85562d3">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 7.17.11-8753e430

testing/environments/snapshot.yml
<Actions>
<action id="33cb4211e1038bc15eec04144b1bf0f8edaf50f30723e96cb31192a7d0ae7b3a">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.8.2-c9f8756a

testing/environments/snapshot.yml
<Actions>
<action id="e29ec942eebfe717a70651eed92c1a3d6c698fd5c0ca3bb07364665aac6ae194">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.8.2-363ffebd

testing/environments/snapshot.yml
<Actions>
<action id="648b0cb39a658cb1e8795e56758d7376c6b19403ad3f9b398c135efd35aab154">
</details>
</action>
<action id="acb5060ba67e4ee753f9ca6abfcb53de04a71dbde17c4e4c4883c54b61ef20fc">
</details>
</action>
</Actions>
---
<table>
<tr>
</td> …
=> [updatecli] update elastic stack version for testing 8.9.0-46e5f4bc

testing/environments/snapshot.yml
<Actions>
<action id="2eda45df0e9def0db4efdcb20316ff13753eb979cbad1efb325562d8f1655d81">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.8.2-652417ba

testing/environments/snapshot.yml
<Actions>
<action id="b53714537352e1f16b39be31c70148a1f024f735be029ab4cfea68f2ac39fafe">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.8.2-33f1abe8

testing/environments/snapshot.yml
<Actions>
<action id="63906eea2f5dc86ce870cd7af43645810fb0236dc75a92f80c78e8dd908c139c">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 7.17.11-ee6563d4

testing/environments/snapshot.yml
<Actions>
<action id="5b25e3c8f5567595b2cbc1ee340a2d012e2dda65481844b74a847672128d723d">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.9.0-0be0aa36

testing/environments/snapshot.yml
<Actions>
<action id="d5771a921d07a18be34ae4f98ccf96184ceea1919cab558102ca2433a38eabbf">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.8.2-438a24ff

testing/environments/snapshot.yml
<Actions>
<action id="ac52139d5451c176dbe6fd060adb5f22031ef9aad217bee992cc63953ba33067">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.9.0-efd868fc

filebeat/Dockerfile, filebeat/magefile.go, libbeat/Dockerfile, x-pack/filebeat/magefile.go, x-pack/libbeat/Dockerfile
So, we don't have security reports from Snyk.
=> Update Docker images that are not included in the automation

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 8.8.2.
=> docs: update docs versions 8.8.2

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
Prepare Changelog for 7.17.11.
=> docs: Prepare Changelog for 7.17.11

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 7.17.11.
=> docs: update docs versions 7.17.11

testing/environments/snapshot.yml
<Actions>
<action id="0c016c7634f2a445c830e8b88ed2816e4c89fef6eaa3468b75b50edeedd89395">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.8.2-41f17f3c

testing/environments/snapshot.yml
<Actions>
<action id="cd27745f3890e18be99f1ac8c8950b4abe9df77c5badc120bc0b04c799efff86">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 7.17.11-670b6a4a

testing/environments/snapshot.yml
<Actions>
<action id="765d0a77ba2a35448ba4919371c7726822fdb09fa74aaefcd529039d4906cab5">
</details>
</action>
<action id="d67b90c6b950c76ddcc9a27d6e5fba70774b90363fafcc561dea6c357db01760">
</details>
</action>
</Actions>
---
<table>
<tr>
</td> …
=> [updatecli] update elastic stack version for testing 8.9.0-dd1f0db2

testing/environments/snapshot.yml
<Actions>
<action id="799159ee6f7be9b0db579e56281aed7d57ab103b63c8f12fc02fd3fe32f2ce2b">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.8.2-ba369b11

testing/environments/snapshot.yml
<Actions>
<action id="68697b3399fe25b88c77f0139bbc3c3c9065282f23e667e28f1012d6401f23f7">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.8.3-1f4ea904

testing/environments/snapshot.yml
<Actions>
<action id="b0986090c92aa3b32a9c0e18a1b36c8ddc6e7c34b758050371c4c19fb7da1eab">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.9.0-024bad78

testing/environments/snapshot.yml
<Actions>
<action id="286806048b22f7eb159e2f02ae5d4bb617ac098895b9523075003678e98eed49">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.8.3-dcc440f7

testing/environments/snapshot.yml
<Actions>
<action id="821cc6e487425c7876466a17e2a8427636189f3b608640a17210c3edaf26a667">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.9.0-872b2eab

testing/environments/snapshot.yml
<Actions>
<action id="02cead1627df610a7db192f121862e383906f498be2bdd62dc99eeba9ec0dd81">
</details>
</action>
<action id="42fa24f96791ac67ed9bbdbbd7aba3cec5fc32d671cebd8e7223019587d05fd9">
</details>
</action>
<action …
=> [updatecli] update elastic stack version for testing 8.10.0-18649b44

testing/environments/snapshot.yml
<Actions>
<action id="9f6b2eb1f0f03cc7f97b0d3a48a5f237f2ce888d3a30d68b646fbdb14e063d4d">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.9.0-55dfeb9a

x-pack/filebeat/docs/inputs/input-cel.asciidoc
Fixes a copy/paste error in the documentation.
The current documentation is confusing.
-
=> x-pack/filebeat/docs/inputs: fix copy paste error

testing/environments/snapshot.yml
<Actions>
<action id="6dbc9d87a78c71c326f207cab7510f075dacf312418fd64ed967ef203186d036">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.8.3-9428e7c2

testing/environments/snapshot.yml
<Actions>
<action id="8f51fa41b4dd8ed7d3129b3d09f0cf22a727fccaa4d909d167967aeee54e4696">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.10.0-0d099cfb

testing/environments/snapshot.yml
<Actions>
<action id="667417f2c945be460be2ba50fec77c67c26a643b4eaaf2943bb685581e1c86e3">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 7.17.12-a5bf8147

testing/environments/snapshot.yml
<Actions>
<action id="f3f67f0abb89c9b14d4ee177be5539785bf4a2f836889480ab0eaa881670c6cf">
</details>
</action>
<action id="f5ce9b184091423d75e8155a77aabaa2ea29d354a580cf8caa8c08e38b4eb894">
</details>
</action>
</Actions>
---
<table>
<tr>
</td> …
=> [updatecli] update elastic stack version for testing 8.8.3-b2365b79

testing/environments/snapshot.yml
<Actions>
<action id="9f86969d29765804cbdfc54e7a2c0dac7acbc7bb4d046ff0bb1a6b04def633df">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.9.0-a302929e

testing/environments/snapshot.yml
<Actions>
<action id="2278f9f94f464cdcedb56b8729a5c836057677b1b2bb819943d6d13e57f0d6e3">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 7.17.12-18dff279

testing/environments/snapshot.yml
<Actions>
<action id="088a560fd3292e186369595373781eab774ef4478edb80d344158970523f2d73">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 7.17.12-3f1ad8e1

testing/environments/snapshot.yml
<Actions>
<action id="1a1f5200180e9b824ccdf6e3d76a6039d69a7ebb9a9b422bb4554e6e473d96ac">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.9.0-53fadbe2

testing/environments/snapshot.yml
<Actions>
<action id="c8b89d88fb8f9ca6e4ccaf61eba284bcbc7eae14315e5dc7d92b157c4898b6c6">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.9.0-905e99b1

testing/environments/snapshot.yml
<Actions>
<action id="f27c96bfede97972464635f0ac7878bdcb248a4ccf4c3f41cc84ce8db03c8d92">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 7.17.12-c78d45be

x-pack/filebeat/docs/inputs/input-cel.asciidoc
Fixes incorrect documentation.
- Closes #36061
=> x-pack/filebeat/docs/inputs/cel: fix copy paste error

testing/environments/snapshot.yml
<Actions>
<action id="04ae217252efeb2b0e296bdbbbf14058ad4591c22ac613878f1f280c6c3ca56c">
</details>
</action>
<action id="08fc465924504b9908d2e6182e8afbda3064b38e9f1d5d030c10520c02b78cc7">
</details>
</action>
<action …
=> [updatecli] update elastic stack version for testing 8.10.0-464beb1d

testing/environments/snapshot.yml
<Actions>
<action id="b069b41f03cc422e8d2add420ede4a423f44fad85208a09bd8c5bb1f788ac8fb">
</details>
</action>
<action id="c78b137b012e0d850fb44cb4746759e3718fd48a6ab531cd6971a3087e52747a">
</details>
</action>
</Actions>
---
<table>
<tr>
</td> …
=> [updatecli] update elastic stack version for testing 8.9.0-446d2070

testing/environments/snapshot.yml
<Actions>
<action id="20d35bc344c854020dd95ef26617eda5eaa07359c75eb5bdcf5f76284332ea85">
</details>
</action>
<action id="965d21082cedd7ef5efb3b41fb8e30349925897823aa912e7d6ea8894e245cda">
</details>
</action>
</Actions>
---
<table>
<tr>
</td> …
=> [updatecli] update elastic stack version for testing 7.17.12-d37f924b

testing/environments/snapshot.yml
<Actions>
<action id="58f1a0149220f865a20fc7f85864b0b32a7ad19fdf571a655a53322dc9448f55">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.9.0-164e5e60

testing/environments/snapshot.yml
<Actions>
<action id="433d72b0f6fa9a722223d1745faf4225d72b572f076e4b252cb911285ccf9200">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.9.0-5732cdbc

testing/environments/snapshot.yml
<Actions>
<action id="a49af3c2810d1f8f68dc27d9bc996f77af166a760819abfe81a91250aeb0add0">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 7.17.12-4a94a841

testing/environments/snapshot.yml
<Actions>
<action id="a0c3c35d2682e712604f5077c9652c8d663a061baa21e517424ecd69aca20fb8">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 7.17.12-5a5017c5

CHANGELOG.asciidoc, libbeat/docs/release.asciidoc
Close https://github.com/elastic/beats/issues/35580
-
=> Adding 8.6.2 changelog to 8.7 branch

testing/environments/snapshot.yml
<Actions>
<action id="d24fe7b0acf1fd7b60c563f00069216f68349e7051bf083c9a954333d19ec14a">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 7.17.12-624c085e
