deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
This PR fixes the version placeholder within manifests for managed elastic-agent.
=> Fix version placeholder for elastic-agent k8s manifest

x-pack/elastic-agent/pkg/agent/operation/monitoring.go
This PR sets `close.on_state_change.inactive` to 5 minutes, so every monitored file is closed after 5 minutes of inactivity. If the log file is updated, it will be picked up in 10 seconds because of the default value of `prospector.scanner.check_interval`.
Filebeat keeps log files open indefinitely by default. However, on Windows, log files cannot be cleaned up if Filebeat keeps the handles. This prevented Endpoint from cleaning up its own logs on Windows. Not anymore.
The original issue comes from Endpoint, however, it makes sense to enable this option for all log files of Agent as they are following the same log writing and log rotation method: adding the date to the end of the log file name.
~~- [ ] I have …
=> Close monitored files after 5 minutes of inactivity

Jenkinsfile
Use try/catch to avoid setting the build to abort
I see several aborted builds recently and somehow I thing the catchError + timeout is not doing what it should be.
In addition a put https://beats-ci.elastic.co/computer/worker-c07c6107jyw0/ offline
=> [CI] use try to avoid a global abort

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 28 Jul 2021 16:25:28 GMT, release_branch:7.14, prefix:, end_time:Wed, 28 Jul 2021 22:19:35 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.14, build_id:7.14.0-9fdd79d4, build_duration_seconds:21247]
=> [automation] update elastic stack version for testing 7.14.0-9fdd79d4

libbeat/processors/decode_xml/decode_xml.go, libbeat/processors/decode_xml/docs/decode_xml.asciidoc
Removes experimental flags from the decode_xml processor.
The processor is already in a state that is safe to move to GA so users can use with with confidence.
=> [libbeat] Remove experimental flags from decode_xml processor

deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
Sets `KIBANA_FLEET_PASSWORD` value to `changeme` instead of `""` in `elastic-agent-managed-daemonset.yaml`.
This is the default value according to [documentation](https://www.elastic.co/guide/en/fleet/current/agent-environment-variables.html)
=> Set the default value for KIBANA_FLEET_PASSWORD in elastic-agent-managed-daemonset

auditbeat/Jenkinsfile.yml, filebeat/Jenkinsfile.yml, heartbeat/Jenkinsfile.yml, libbeat/Jenkinsfile.yml, packetbeat/Jenkinsfile.yml, x-pack/dockerlogbeat/Jenkinsfile.yml, x-pack/elastic-agent/Jenkinsfile.yml, x-pack/filebeat/Jenkinsfile.yml, x-pack/functionbeat/Jenkinsfile.yml, x-pack/heartbeat/Jenkinsfile.yml, x-pack/libbeat/Jenkinsfile.yml, x-pack/osquerybeat/Jenkinsfile.yml, x-pack/packetbeat/Jenkinsfile.yml
We are keeping Pipeline2.0-consistency across Beats calling the Python system-tests, using OSS metricbeat's as the canonical reference: run unit tests, then Go integration tests, and finally Python integration tests when needed. This change applies to filebeat and metricbeat in both OSS and xpack flavours.
I finally revisited each Beat and made sure all of them run the unit, goInteg and pythonInteg tests in a consistent manner: instead of calling the obscure mage test command, we separate it in three different stages when needed: mage unitTest, mage goIntegTest and mage pythonIntegTest. I've verified one by one that each of those three commands is present in the build for the related Beat, adding or removing them from the CI descriptor (Jenkinsfile.yml) when/if needed, creating the …
=> chore: decouple unit and integration tests on CI

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 29 Jul 2021 12:14:57 GMT, release_branch:7.14, prefix:, end_time:Thu, 29 Jul 2021 17:35:26 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.14, build_id:7.14.0-56a8365b, build_duration_seconds:19229]
=> [automation] update elastic stack version for testing 7.14.0-56a8365b

CHANGELOG.next.asciidoc, dev-tools/mage/pkgtypes.go, dev-tools/mage/settings.go, dev-tools/packaging/package_test.go
Adds sha256 digests to RPM packages.
```
filebeat-8.0.0-SNAPSHOT-x86_64.rpm:
Header SHA256 digest: OK
Header SHA1 digest: OK
Payload SHA256 digest: OK
MD5 digest: OK
```
Fixes #23670
This allows the RPMs to be installed on RHEL8 without any additional flags to disable digest checks. RHEL8 no longer trust the sha1 and md5 we were adding.
- Closes #23670
- Requires https://github.com/elastic/golang-crossbuild/pull/118
=> Add sha256 digests to RPM packages

x-pack/elastic-agent/CHANGELOG.next.asciidoc, x-pack/elastic-agent/pkg/agent/application/paths/files.go, x-pack/elastic-agent/pkg/agent/cmd/enroll.go, x-pack/elastic-agent/pkg/agent/cmd/enroll_cmd.go, x-pack/elastic-agent/pkg/agent/cmd/enroll_cmd_test.go, x-pack/elastic-agent/pkg/agent/cmd/install.go, x-pack/elastic-agent/pkg/agent/cmd/run.go, x-pack/elastic-agent/pkg/fleetapi/enroll_cmd.go, x-pack/elastic-agent/pkg/fleetapi/enroll_cmd_test.go
This adds support for the `--delay-enroll` flag for the `install` and `enroll` command. On next start of the Elastic Agent service the Elastic Agent will enroll before running in managed mode.
This supports the use-case for setting up a golden image, sysprep, or VDI image that will enroll into Fleet on first start.
- Closes #26667
=> [Elastic Agent] Add support for the --delay-enroll command flag.

libbeat/docs/http-endpoint.asciidoc
=> Cherry-pick to 7.14: docs: fix example (#27117)

libbeat/docs/http-endpoint.asciidoc
=> Cherry-pick to 7.13: docs: fix example (#27117)

heartbeat/hbtest/hbtestutil.go, heartbeat/monitors/active/http/http_test.go, heartbeat/monitors/active/tcp/tls_test.go
Provides a better fix than https://github.com/elastic/beats/pull/25859 , re-enabled win32 TLS tests, using a less precise cipher match.
fixes https://github.com/elastic/beats/issues/25857
=> [Heartbeat] Re-enable windows 32 bit TLS tests

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Sun, 1 Aug 2021 12:24:00 GMT, release_branch:7.14, prefix:, end_time:Sun, 1 Aug 2021 18:03:20 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.14, build_id:7.14.0-8d3ee29d, build_duration_seconds:20360]
=> [automation] update elastic stack version for testing 7.14.0-8d3ee29d

CHANGELOG.next.asciidoc, metricbeat/module/nginx/_meta/Dockerfile, metricbeat/module/nginx/_meta/config.yml, metricbeat/module/nginx/_meta/nginx.conf, metricbeat/module/nginx/stubstatus/stubstatus.go, metricbeat/modules.d/nginx.yml.disabled
Fixes the default path for the nginx module from `server-status` to `nginx_status`
If set by default the endpoint will return a 404
=> [fix][metricbeat] Change default value for server_status_path in nginx module

CHANGELOG.next.asciidoc, x-pack/filebeat/processors/decode_cef/cef/types.go, x-pack/filebeat/processors/decode_cef/cef/types_test.go
Accept MAC addresses that do not contain separators (i.e. `000D60AF1B61`).
Fixes #27050
Some log sources do not comply with the CEF spec and send valid MACs but without separators. The processor should identify these and accept them.
- Closes #27050
=> [Filebeat] decode_cef - allow MACs without separators

x-pack/osquerybeat/beater/config_plugin.go, x-pack/osquerybeat/beater/config_plugin_test.go, x-pack/osquerybeat/beater/osquerybeat.go, x-pack/osquerybeat/internal/config/config.go, x-pack/osquerybeat/internal/ecs/mapping.go, x-pack/osquerybeat/internal/ecs/mapping_test.go
Changes the format of ECS mapping configuration for the queries:
1. The mapping keys are the ECS key path
2. The mapping value is an object that allows to define the static value or the field which is the name of the osquery result column.
Improves test coverage for configuration plugin.
Current format example:
```
"ecs_mapping": {
"user.custom.shoeSize": {
"value": 45
},
"user.id": {
"field": "uid"
},
"user.name": {
"field": "username"
}
}
```
ECS mapping support for Osquerybeat
- Requires https://github.com/elastic/integrations/pull/1360
The fragment of the document showing and example of the ECS fields mapped:
=> Osquerybeat: Update ECS mapping implementation based on the latest developers feedback

x-pack/elastic-agent/pkg/agent/operation/operator.go
WHen monitors were enabled monitoring of simple filebeat and metricbeat was configured and should not.
This resulted in socket not found because metricbeat was told to keep an eye on metricbeat.sock but it was not available as simple metricbeat was not running.
This PR does not configure monitoring beat to watch for simple beat if simple beat is not actually running
Fixes: https://github.com/elastic/beats/issues/27127
=> [Elastic Agent] Do not watch monitors

x-pack/elastic-agent/pkg/agent/operation/operator.go
This is an automatic backport of pull request #27192 done by [Mergify](https://mergify.io).
---
<details>
<summary>Mergify commands and options</summary>
<br />
More conditions and actions can be found in the [documentation](https://docs.mergify.io/).
You can also trigger Mergify actions by commenting on this pull request:
- `@Mergifyio refresh` will re-evaluate the rules
- `@Mergifyio rebase` will rebase this PR on its base branch
- `@Mergifyio update` will merge the base branch into this PR
- `@Mergifyio backport <destination>` will backport this PR on `<destination>` branch
Additionally, on Mergify [dashboard](https://dashboard.mergify.io/) you can:
- look at your merge queues
- generate the Mergify configuration with the config editor.
Finally, you can contact us on …
=> [7.x](backport #27192) [Elastic Agent] Do not watch monitors

x-pack/elastic-agent/pkg/agent/operation/operator.go
This PR guards `HandleConfig` func with filter resulting in ignoring `context.Canceled` errors.
Ignoring does not have any functional impact but it avoids spamming logs with false failures. 
Fixes: https://github.com/elastic/beats/issues/27057
=> Ignore context cancelled in operator

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 3 Aug 2021 00:26:44 GMT, release_branch:master, prefix:, end_time:Tue, 3 Aug 2021 05:39:32 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-0c340354, build_duration_seconds:18768]
=> [automation] update elastic stack version for testing 8.0.0-0c340354

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 3 Aug 2021 05:14:18 GMT, release_branch:7.14, prefix:, end_time:Tue, 3 Aug 2021 10:32:43 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.14, build_id:7.14.0-1738ccc6, build_duration_seconds:19105]
=> [automation] update elastic stack version for testing 7.14.0-1738ccc6

x-pack/metricbeat/module/gcp/metrics/metricset.go
Add an error log statement reporting metrics for which GCP Monitoring APIs report no metric descriptors.
Before metric collection, the `gcp` module request metric descriptors for all metrics specified in the fields file.
Is possible that the GCP Monitoring API return an empty metric descriptor set, upon request. The most probable reason is due to the metric being not found.
The current behaviour for these occurrences is to ignore the metric and proceed. This silently discard a requested metric without any visible output to the developer/operator, and I consider it a bad developer experience.
I don't consider this behaviour a fatal error, but surely worthy to be reported as error in the logs.
- Requires #26960
```
Scenario: silent wrong code implementation
As a gcp module metricbeat …
```
=> [Metricbeat] gcp: log metrics without descriptors

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-httpjson.asciidoc, x-pack/filebeat/input/httpjson/internal/v2/value_tpl.go, x-pack/filebeat/input/httpjson/internal/v2/value_tpl_test.go
Adds a `[[hmac "sha256" "secret" "string1" (formatDate (now) "RFC1123")]]` function that can be used to calculate hmac signatures for API authentication.
A lot of APIs use an HMAC signature to authenticate API calls.  These signatures need to be generated at runtime, usually comprised of elements of the call. See https://docs.fireeye.com/iSight/index.html#/authentication as an example. Also https://elasticstack.slack.com/archives/CNEDGGJQ3/p1627286354468400
Run the integration tests located at x-pack/filebeat/input/httpjson/internal/v2/value_tpl_test.go
- 
https://docs.fireeye.com/iSight/index.html#/authentication
=> [Filebeat] Add HMAC template function for httpjson input

CHANGELOG.next.asciidoc, x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go, x-pack/metricbeat/module/aws/utils.go
When a CloudWatch data point lands on the start time or end time, it gets collected twice. This PR is to fix this bug by moving the start time by one second so the end time of the first collection period does not overlap with the start time of the second collection period.
- Closes https://github.com/elastic/beats/issues/19126
=> Fix cloudwatch metricset collecting duplicate data points

libbeat/common/transport/httpcommon/httpcommon.go, libbeat/common/transport/httpcommon/proxy.go, libbeat/common/transport/httpcommon/proxy_headers.go, libbeat/common/transport/httpcommon/proxy_headers_test.go, libbeat/common/transport/httpcommon/proxy_uri.go, libbeat/common/transport/httpcommon/proxy_uri_test.go, libbeat/esleg/eslegclient/connection.go, libbeat/esleg/eslegclient/connection_integration_test.go, libbeat/outputs/elasticsearch/client_proxy_test.go, x-pack/elastic-agent/pkg/agent/cmd/enroll_cmd.go
This PR makes sure proxy URI is serialized as string as it is expected to be a string when unpacking value from config
Fixes: https://github.com/elastic/beats/issues/27187
=> Fix serialization/deserialization of proxy URI

x-pack/osquerybeat/beater/osquerybeat.go
Adds event.module into the result data
Addresses https://github.com/elastic/security-team/issues/1555
- Closes https://github.com/elastic/security-team/issues/1555
=> Osquerybeat: Add event.module into the result data

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 5 Aug 2021 12:15:13 GMT, release_branch:7.14, prefix:, end_time:Thu, 5 Aug 2021 17:29:19 GMT, manifest_version:2.0.0, version:7.14.1-SNAPSHOT, branch:7.14, build_id:7.14.1-22366df8, build_duration_seconds:18846]
=> [automation] update elastic stack version for testing 7.14.1-22366df8

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Sun, 8 Aug 2021 12:14:46 GMT, release_branch:7.14, prefix:, end_time:Sun, 8 Aug 2021 17:43:13 GMT, manifest_version:2.0.0, version:7.14.1-SNAPSHOT, branch:7.14, build_id:7.14.1-8dd23e93, build_duration_seconds:19707]
=> [automation] update elastic stack version for testing 7.14.1-8dd23e93

x-pack/osquerybeat/beater/config_plugin.go, x-pack/osquerybeat/beater/config_plugin_test.go, x-pack/osquerybeat/internal/config/config.go
Add support for input/integration level osquery platform/version/discovery configuration.
This allows to map the integration configuration to the osquery packs 1:1.
The ```platform``` and ```version``` constraints at the input level had to have a different name currently in order to avoid these values to be injected in every stream instead, that's why the names are ```iplatform``` and ```iversion``` as abbreviation for the ```input platform``` and the ```input version```.
This change requires the updated osquery_manager integration https://github.com/elastic/integrations/pull/1441
and is also couple of more fixes on kibana side:
1. kibana needs to be able to create integration configuration with empty vars, currently it returns error when you try to add updated osquery_manager integration …
=> Osquerybeat: Add support for input/integration level osquery platform/version/discovery configuration

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 9 Aug 2021 05:16:05 GMT, release_branch:7.14, prefix:, end_time:Mon, 9 Aug 2021 10:33:32 GMT, manifest_version:2.0.0, version:7.14.1-SNAPSHOT, branch:7.14, build_id:7.14.1-899a999b, build_duration_seconds:19047]
=> [automation] update elastic stack version for testing 7.14.1-899a999b

CHANGELOG.next.asciidoc, x-pack/filebeat/module/threatintel/anomali/ingest/pipeline.yml, x-pack/filebeat/module/threatintel/anomali/test/anomali_limo.ndjson.log-expected.json
Populates the `tags` field the same way the MISP dataset is populated and populates the `threatintel.indicator.provider` field like the Abuse URL dataset.
Standardizes the Threat Intel datasets
```
cd beats/x-pack/filebeat
TESTING_FILEBEAT_MODULES=threatintel TESTING_FILEBEAT_FILESETS=anomali mage -v pythonIntegTest
```
- Closes #24746
=> [Filebeat] Update Threatinteal Anomali pipeline

x-pack/elastic-agent/pkg/agent/application/application.go
Passes the correct config file into local mode.
PR https://github.com/elastic/beats/pull/27118 changed how path is retrieved in `run.go`
and went from 
`pathConfigFile := paths.ConfigFile()`
to 
`pathConfigFile := paths.AgentConfigFile()`
while `ConfigFile()` checks for config file defined using `-c` and if not found it falls back to `elastic-agent.yml` 
`AgentConfigFile()` just retrieves an absolute path to `fleet.yml`
in this PR i pass result of `paths.ConfigFile()` into standalone code path so it behaves like it was before.
As standalone agent needs to read `elastic-agent.yml` because this is where the config is, `fleet.yml` is still created and it contains agent.id 
Possible workaround is to COPY config into `fleet.yml`. renaming will lead to agent failing on initial config load. …
=> Pass correct config to standalone

filebeat/docs/index.asciidoc, libbeat/docs/redirects.asciidoc, metricbeat/docs/index.asciidoc
Adds a redirect page to send Beats central management users to Elastic Agent and Fleet docs.
Adds redirect pages to the Metricbeat and Filebeat docs
Beats central management is no longer supported. We want users to know about Fleet as a good replacement.
=> Add redirect pages for removed central management docs

heartbeat/docs/monitors/monitor-browser.asciidoc
Fixes #27217 and also improves the ordering of documentation here, putting the most used options first, and the least used last.
=> [Uptime] Document `params` browser option, fix docs hierarchy.

filebeat/docs/index.asciidoc, libbeat/docs/redirects.asciidoc, metricbeat/docs/index.asciidoc
- Add redirect pages for removed central management docs (#27239)
=> Cherry-pick to 7.x: Add redirect pages for removed central management docs (#27239)

filebeat/docs/index.asciidoc, libbeat/docs/redirects.asciidoc, metricbeat/docs/index.asciidoc
- Add redirect pages for removed central management docs (#27239)
=> Cherry-pick to 7.14: Add redirect pages for removed central management docs (#27239)

heartbeat/beater/heartbeat.go, heartbeat/config/config.go, heartbeat/monitors/task.go, heartbeat/scheduler/scheduler.go, heartbeat/scheduler/scheduler_test.go
=> [Heartbeat]: limit parallelization of tasks by jobtype

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 10 Aug 2021 12:14:34 GMT, release_branch:7.14, prefix:, end_time:Tue, 10 Aug 2021 17:41:24 GMT, manifest_version:2.0.0, version:7.14.1-SNAPSHOT, branch:7.14, build_id:7.14.1-a5e22cba, build_duration_seconds:19610]
=> [automation] update elastic stack version for testing 7.14.1-a5e22cba

CHANGELOG.next.asciidoc, metricbeat/helper/windows/pdh/pdh_query_windows.go
Fix flaky test `TestAddCounterInvalidArgWhenQueryClosed`
- Closes https://github.com/elastic/beats/issues/27312
=> Fix flaky test `TestAddCounterInvalidArgWhenQueryClosed`

x-pack/osquerybeat/beater/osquerybeat.go, x-pack/osquerybeat/internal/osqdcli/client.go
This addresses the issue observed on linux platforms, where after running osquerybeat for some time the osqueryd client gets the "broken pipe" error from the osqueryd domain socket client:
"Osquerybeat: osquery failed: write unix ->/var/run/642722736/osquery.sock: write: broken pipe
https://github.com/elastic/beats/issues/25297"
Before the change the osqueryd client was connected once at the start of osquerybeat, after the change the client reconnects to osqueryd upon receiving the error.
Addresses:
"Osquerybeat: osquery failed: write unix ->/var/run/642722736/osquery.sock: write: broken pipe"
https://github.com/elastic/beats/issues/25297
This issue is difficult to reproduce. The only way I was able to reproduce it at the moment is to leave the agent with osquerybeat running overnight. …
=> Osquerybeat: Add osquery client reconnect on broken pipe error

CHANGELOG.next.asciidoc, metricbeat/helper/windows/pdh/pdh_query_windows.go
Cherry-pick of PR #27313 to 7.x branch. Original message: 
Fix flaky test `TestAddCounterInvalidArgWhenQueryClosed`
- Closes https://github.com/elastic/beats/issues/27312
=> Cherry-pick #27313 to 7.x: Fix flaky test `TestAddCounterInvalidArgWhenQueryClosed`

dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl, dev-tools/packaging/templates/docker/Dockerfile.tmpl
Upgrades node to the latest LTS version for security. This is a major version bump but we should be fine pending manual tests.
=> [Synthetics] Upgrade node to latest LTS

x-pack/metricbeat/module/gcp/metrics/metricset.go, x-pack/metricbeat/module/gcp/metrics/metricset_test.go, x-pack/metricbeat/module/gcp/metrics/response_parser.go, x-pack/metricbeat/module/gcp/metrics/response_parser_test.go
Fixes a bug introduced with #26960 
#26960 was a partial implementation of the feature: it was missing a code change to use `ServiceMetricPrefix` in `incomingFieldExtractor`.
Run `go test -v ./module/gcp/metrics/`
-
=> [Metricbeat] gcp: use ServiceMetrixPrefix in field extractor too

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 12 Aug 2021 05:15:12 GMT, release_branch:7.x, prefix:, end_time:Thu, 12 Aug 2021 10:46:24 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.x, build_id:7.15.0-ba42231a, build_duration_seconds:19872]
=> [automation] update elastic stack version for testing 7.15.0-ba42231a

filebeat/input/mqtt/client_mocked.go, go.mod, go.sum
Bump mqtt version to 1.3.5, avoid package conflict.
For the user who integrated beats with other library use mqtt client v1.3.x, they will build error because the `*mockedToken` doesnot implement `mqtt.Token`, missing Done method.
=> [file beat] Bump mqtt version to 1.3.5, avoid package conflict

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 12 Aug 2021 12:13:53 GMT, release_branch:7.14, prefix:, end_time:Thu, 12 Aug 2021 17:35:37 GMT, manifest_version:2.0.0, version:7.14.1-SNAPSHOT, branch:7.14, build_id:7.14.1-3af02427, build_duration_seconds:19304]
=> [automation] update elastic stack version for testing 7.14.1-3af02427

CHANGELOG.next.asciidoc, x-pack/filebeat/filebeat.reference.yml, x-pack/filebeat/module/snyk/_meta/config.yml, x-pack/filebeat/module/snyk/audit/config/config.yml, x-pack/filebeat/module/snyk/vulnerabilities/config/config.yml, x-pack/filebeat/module/snyk/vulnerabilities/manifest.yml, x-pack/filebeat/modules.d/snyk.yml.disabled
This adds fixes for certain API changes for the Snyk module, moving to another way of paginating, and some of the filters have been adjusted.
Required for the module to continue working with the new API changes.
- Closes #27292 
- Closes #27293 
Tests has been done against our own Snyk account to confirm changes is working as intended
=> [Filebeat] Fixes for Snyk API changes

x-pack/elastic-agent/pkg/core/plugin/process/app.go
This PR handles the cases in windows where there's different behaviour in Wait and Signal commands.
Wait-kill commands in Stop func were replaced by existing gracefullKill functionality which handles OS differences already.
This needs to be backported to 7.14 as well and released together with the cancellation fixes 
https://github.com/elastic/beats/issues/27259
=> Fix application.Stop on windows

CHANGELOG.next.asciidoc, auditbeat/auditbeat.reference.yml, filebeat/filebeat.reference.yml, heartbeat/heartbeat.reference.yml, journalbeat/journalbeat.reference.yml, libbeat/_meta/config/general.reference.yml.tmpl, libbeat/_meta/config/logging.reference.yml.tmpl, libbeat/docs/loggingconfig.asciidoc, libbeat/monitoring/report/log/config.go, libbeat/monitoring/report/log/log.go, libbeat/monitoring/report/log/log_test.go, libbeat/processors/dns/resolver.go, libbeat/tests/system/test_base.py, metricbeat/metricbeat.reference.yml, packetbeat/packetbeat.reference.yml, winlogbeat/winlogbeat.reference.yml, x-pack/auditbeat/auditbeat.reference.yml, x-pack/filebeat/filebeat.reference.yml, x-pack/functionbeat/functionbeat.reference.yml, x-pack/heartbeat/heartbeat.reference.yml, x-pack/metricbeat/metricbeat.reference.yml, x-pack/osquerybeat/osquerybeat.reference.yml, x-pack/packetbeat/packetbeat.reference.yml, x-pack/winlogbeat/winlogbeat.reference.yml
This adds periodic reporting of "dataset" metrics to the logs. This can be disabled by configuring `logging.metrics.namespaces`. These are the same metrics available from the HTTP monitoring endpoint under the /dataset path. This primarily improves visibility of Filebeat and Metricbeat because they make use of the "dataset" namespace for input and metricset instance metrics.
Prior to 7.10 the Filebeat input metrics were reported in the logged metrics, but this was lost when the metrics moved to the "dataset" namespace. It was a useful feature to have for remote debugging.
- Relates https://github.com/elastic/beats/pull/19977
- Relates https://github.com/elastic/beats/pull/6836
```
2021-05-16T14:20:17.885-0400    INFO    [monitoring]    log/log.go:183  Non-zero metrics in the last 30s …
```
=> Report dataset metrics in monitoring log reporter

x-pack/elastic-agent/pkg/agent/application/upgrade/step_mark.go
The LoadMarker method comment indicates that it should return a nil error when
the file does not exist, but it did return the os.ErrNotExist in this case. So I changed
it to return a nil error when the file does not exist.
This should squelch the benign warnings shown to users like
16:04:40.160 elastic_agent [elastic_agent][warn] failed to ack update open /opt/Elastic/Agent/data/.update-marker: no such file or directory
The warning causes unnecessary alarm for users.
=> [Agent] Fix os.ErrNotExist handling for Agent upgrade marker

libbeat/docs/shared-kerberos-config.asciidoc
- Fix formatting of Filebeat name (#27328)
=> Cherry-pick to 7.12: Fix formatting of Filebeat name (#27328)

libbeat/docs/shared-kerberos-config.asciidoc
- Fix formatting of Filebeat name (#27328)
=> Cherry-pick to 7.13: Fix formatting of Filebeat name (#27328)

libbeat/docs/shared-kerberos-config.asciidoc
- Fix formatting of Filebeat name (#27328)
=> Cherry-pick to 7.14: Fix formatting of Filebeat name (#27328)

libbeat/docs/shared-kerberos-config.asciidoc
- Fix formatting of Filebeat name (#27328)
=> Cherry-pick to 7.x: Fix formatting of Filebeat name (#27328)

dev-tools/packaging/packages.yml, dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
We've discussed internally that 'complete' is more appropriate than 'offline' in terms of naming for the new image. This makes that simple change.
=> [elastic-agent] Rename 'offline' image to 'complete'

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Fri, 13 Aug 2021 12:14:55 GMT, release_branch:7.14, prefix:, end_time:Fri, 13 Aug 2021 17:40:22 GMT, manifest_version:2.0.0, version:7.14.1-SNAPSHOT, branch:7.14, build_id:7.14.1-c6219279, build_duration_seconds:19527]
=> [automation] update elastic stack version for testing 7.14.1-c6219279

.ci/apm-beats-update.groovy
`go mod tidy` should be executed after custom modifications of `go.mod`
to avoid problems due to missing entries in `go.sum`.
This should solve failures like this one:
```
[2021-08-15T13:03:19.235Z] go: github.com/elastic/beats/v7@v7.0.0-alpha2.0.20210812232037-f144f63593df requires
[2021-08-15T13:03:19.235Z] 	github.com/eclipse/paho.mqtt.golang@v1.3.5: missing go.sum entry; to add it:
[2021-08-15T13:03:19.235Z] 	go mod download github.com/eclipse/paho.mqtt.golang
[2021-08-15T13:03:19.235Z] /var/lib/jenkins/workspace/Beats_apm-beats-update_master/.gvm/versions/go1.16.6.linux.amd64/bin/go build -o build/linux/bin/mage github.com/magefile/mage
[2021-08-15T13:03:19.235Z] go: github.com/elastic/beats/v7@v7.0.0-alpha2.0.20210812232037-f144f63593df requires
[2021-08-15T13:03:19.235Z] …
```
=> Fix go mod in apm beats update CI job

CHANGELOG.next.asciidoc, metricbeat/docs/modules/aws.asciidoc, x-pack/metricbeat/module/aws/_meta/docs.asciidoc, x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go, x-pack/metricbeat/module/aws/utils.go
This PR is to change startTime and endTime of `GetMetricData` API in `cloudwatch` metricbeat to be only one collection period apart. Bug in previous code is:
- First Metricbeat collection cycle: startTime = 06:50:35 endTime = 07:00:35 -> cloudwatch metric timestamp = 06:55:00
- Second Metricbeat collection cycle: startTime = 06:55:35 endTime = 07:05:35 -> cloudwatch metric timestamp = 06:55:00
The problem is caused by the startTime and endTime parameters in AWS CloudWatch GetMetricData API only look at the hour and minute (e.g: 06:50 and 07:00) in a timestamp. And also the gap between startTime and endTime is double the period, which causes more than one data point gets returned.  
This PR is to first round the timestamps to ignore seconds. Then change startTime to be one collection …
=> Change to use one period between start and end time

heartbeat/docs/heartbeat-options.asciidoc, heartbeat/docs/heartbeat-scheduler.asciidoc, heartbeat/docs/monitors/monitor-browser.asciidoc
+ Adds docs for the new scheduled job limit option that is added via https://github.com/elastic/beats/pull/27160/
+ Also added new browser monitor options `filter_journeys` that is added here - https://github.com/elastic/beats/pull/27347
=> Heartbeat: add browser monitor docs

dev-tools/mage/dockerbuilder.go
Backport of #27399 to 7.x
Previously `complete` images were named `elastic-agent:8.0.0-complete`, this changes them to `elastic-agent-complete:8.0.0` to be compatible with our release process.
=> [elastic-agent] Use -complete in docker image name, not tag

CHANGELOG.next.asciidoc, x-pack/metricbeat/module/gcp/metrics/compute/metadata.go
Refresh instance metadata for each incoming response by updating the `s.computeMetadata` field in the `metadataCollector` struct.
The code was applying a sort of caching to the `computeMetadata`, but in the wrong place. Most probably it was a leftover, as a proper caching for instance metadata is implemented in the `instance` function on line 146.
Due to this check `computeMetadata` were not refreshed for each response.
`metadataCollector` is instanciated only once for the entire module.
Thus by not overriding `computeMetadata` the metadata of the first response handled was used for all subsequent events.
Removing the check make the code update the `s.computeMetadata` property for each new response. With this update the correct metadata based on the instance ID reported in the response …
=> [Metricbeat] gcp: fix instance machineType reporting

metricbeat/docker-compose.yml, x-pack/metricbeat/docker-compose.yml
Update CI docker images to 7.14.0
7.12.0 (currently in use for testing Metricbeat) is old and unsupported.
- Blocks https://github.com/elastic/beats/pull/26824
=> [Metricbeat] CI: update stack to 7.14

x-pack/elastic-agent/CHANGELOG.next.asciidoc, x-pack/elastic-agent/pkg/agent/application/fleet_server_bootstrap.go
=> Disable monitoring during fleetserver bootstrap process (backport #27222)

CHANGELOG-developer.next.asciidoc, libbeat/logp/core.go, libbeat/logp/core_test.go
Remove the `event.dataset` ECS attribute from `libbeat.logp`.
`event.dataset` key is appearing twice in documents sent by filebeat running under the elastic-agent. Once is the correct `elastic_agent.X` value, the other is an array that contains the log name.
- [] ~~I have made corresponding changes to the documentation~~
Build + run agent and ensure that log entries only have a single `event.dataset` key set to `elastic_agent.X`
- Closes #27404
=> Remove event.dataset from logp ecs attributes

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 17 Aug 2021 12:14:25 GMT, release_branch:7.14, prefix:, end_time:Tue, 17 Aug 2021 18:00:45 GMT, manifest_version:2.0.0, version:7.14.1-SNAPSHOT, branch:7.14, build_id:7.14.1-904a8260, build_duration_seconds:20780]
=> [automation] update elastic stack version for testing 7.14.1-904a8260

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 17 Aug 2021 12:14:32 GMT, release_branch:7.x, prefix:, end_time:Tue, 17 Aug 2021 17:52:06 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.x, build_id:7.15.0-4b8a78a4, build_duration_seconds:20254]
=> [automation] update elastic stack version for testing 7.15.0-4b8a78a4

libbeat/docs/shared-kibana-config.asciidoc, libbeat/docs/shared-ssl-config.asciidoc
In https://github.com/elastic/kibana/pull/82817, the support for PKI auth against Kibana APIs was removed. This PR updates content by removing all mentions of PKI and also provides a link to the Kibana API authentication documentation. 
@mbarretta Apologies for letting this slip through the net. 
**Metricbeat**:
- https://beats_27422.docs-preview.app.elstc.co/guide/en/beats/metricbeat/master/configuration-ssl.html
- https://beats_27422.docs-preview.app.elstc.co/guide/en/beats/metricbeat/master/setup-kibana-endpoint.html
**Filebeat**:
- https://beats_27422.docs-preview.app.elstc.co/guide/en/beats/filebeat/master/configuration-ssl.html
- https://beats_27422.docs-preview.app.elstc.co/guide/en/beats/filebeat/master/setup-kibana-endpoint.html
Closes …
=> [DOCS] Remove PKI mentions

filebeat/docs/modules/aws.asciidoc, x-pack/filebeat/filebeat.reference.yml, x-pack/filebeat/input/awss3/acker.go, x-pack/filebeat/input/awss3/config.go, x-pack/filebeat/input/awss3/config_test.go, x-pack/filebeat/input/awss3/input.go, x-pack/filebeat/input/awss3/input_benchmark_test.go, x-pack/filebeat/input/awss3/input_integration_test.go, x-pack/filebeat/input/awss3/s3.go, x-pack/filebeat/input/awss3/s3_objects.go, x-pack/filebeat/input/awss3/s3_test.go, x-pack/filebeat/module/aws/_meta/config.yml, x-pack/filebeat/module/aws/_meta/docs.asciidoc, x-pack/filebeat/module/aws/cloudtrail/config/aws-s3.yml, x-pack/filebeat/module/aws/cloudtrail/manifest.yml, x-pack/filebeat/module/aws/cloudwatch/config/aws-s3.yml, x-pack/filebeat/module/aws/cloudwatch/manifest.yml, x-pack/filebeat/module/aws/ec2/config/aws-s3.yml, x-pack/filebeat/module/aws/ec2/manifest.yml, x-pack/filebeat/module/aws/elb/config/aws-s3.yml, x-pack/filebeat/module/aws/elb/manifest.yml, x-pack/filebeat/module/aws/s3access/config/aws-s3.yml, x-pack/filebeat/module/aws/s3access/manifest.yml, x-pack/filebeat/module/aws/vpcflow/config/input.yml, x-pack/filebeat/module/aws/vpcflow/manifest.yml, x-pack/filebeat/modules.d/aws.yml.disabled
Adds new variables introduced in https://github.com/elastic/beats/pull/26056 to `aws.yml.disabled`
It also adds missing/faulty metadata (bucket, region in s3 url) for the event when using S3 bucket listing directly
In order to give visibility to the users about the availability of the new variables.
-
=> Add vars in modules.d/aws.yml.disabled

.backportrc.json, .mergify.yml
Merge as soon as 7.15 branch was created. Auto-merge is not yet supported, see https://github.com/Mergifyio/mergify-engine/discussions/2821
=> backport: Add 7.15 branch

libbeat/kibana/client.go, metricbeat/tests/system/test_base.py, testing/environments/latest.yml
This PR sets the minimum required version for Kibana to 7.14 for using the Saved Objects API. The change lets module developers use the last released version for exporting dashboards.
The PR also updates the testing environment to 7.14, so dashboard exporting and importing can be tested using e2e tests.
Support module developers and run e2e tests to catch issues.
Requires https://github.com/elastic/beats/pull/27424
=> Be more lenient when checking for Saved Objects API in Kibana

x-pack/libbeat/docs/aws-credentials-config.asciidoc
@bmorelli25:
> The AWS module documentation shows up in the metricbeat, filebeat, and heartbeat docs, but always refers to metricbeat config. See the filebeat docs for an example: https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-module-aws.html#_supported_formats_2.
@kaiyan-sheng:
> Yes this is by design. Because for all AWS related modules, no matter it's in Metricbeat, Filebeat or Functionbeat, it's all using the same credential options for authentication with AWS. Maybe under the Supported Formats section, we should remove the metricbeat.modules: line so it's less confusing? Thank you!
@kaiyan-sheng, how do you feel about this solution? There are a lot of references to Metricbeat, so I'm not sure I want to remove the metricbeat.modules line. This PR adds a note at the top …
=> docs: add note about aws creds

CHANGELOG.next.asciidoc, x-pack/filebeat/input/http_endpoint/handler.go, x-pack/filebeat/input/http_endpoint/handler_test.go
This adds a necessary transform to the output of http_endpoint so that numeric values are encoded as such instead of as a string.
After a refactor of the input, numeric values in the original input were being encoded as a string in the output event.
Fixes #27382
=> Transform json.Number values from http_endpoint

x-pack/osquerybeat/beater/action_handler.go, x-pack/osquerybeat/beater/action_handler_test.go
Adds ECS Mapping support for ad-hoc/live queries for osquerybeat.
Support the use case where the customer can run/test the live query results with ECS mapping applied.
Example of action with ecs_mapping:
```
POST .fleet-actions/_doc/
{
"action_id": "214f219d-d67c-4744-8eb1-0a812594263f",
"@timestamp": "2021-07-20T19:15:31.124Z",
"expiration": "2021-12-25T00:36:30Z",
"type" : "INPUT_ACTION",
"input_type": "osquery",
"timeout": 60,
"agents": [
"9c149708-54b6-4a5b-b818-ecadfd583e95"
],
"data" : {
"query" : "select * from users limit 2",
"ecs_mapping" : {
"user.custom.shoeSize": {
"value": 48
},
"user.id": {
"field": "uid"
},
"user.name": {
"field": "username"
}
}
},
"user_id": "user-aleksmaus"
}
```
Part of the result document for the action above with ECS mapping applied:
=> Osquerybeat: Add ECS Mapping support for ad-hoc/live queries

x-pack/elastic-agent/pkg/agent/program/testdata/enabled_output_true-filebeat.yml, x-pack/elastic-agent/pkg/agent/program/testdata/enabled_true-filebeat.yml, x-pack/elastic-agent/pkg/agent/program/testdata/fleet_server-fleet-server.yml, x-pack/elastic-agent/pkg/agent/program/testdata/namespace-filebeat.yml, x-pack/elastic-agent/pkg/agent/program/testdata/namespace-fleet-server.yml, x-pack/elastic-agent/pkg/agent/program/testdata/namespace-metricbeat.yml, x-pack/elastic-agent/pkg/agent/program/testdata/single_config-filebeat.yml, x-pack/elastic-agent/pkg/agent/program/testdata/single_config-fleet-server.yml, x-pack/elastic-agent/pkg/agent/program/testdata/single_config-metricbeat.yml, x-pack/elastic-agent/pkg/agent/transpiler/rules.go, x-pack/elastic-agent/pkg/agent/transpiler/rules_test.go
Fix the `inject_headers` transpiler rule that adds fleet enrollment metadata into the http headers of resulting beats clients. The rule attempted (and silently failed) to inject the headers into the configuration under the `outputs` node, but at the rule application stage configurations are normalized to use an `output` node instead.
=> [agent] fix the inject_headers transpiler rule

x-pack/libbeat/docs/aws-credentials-config.asciidoc
Backports the following commits to 7.15:
- docs: add note about aws creds (#27434)
=> Cherry-pick to 7.15: docs: add note about aws creds (#27434)

x-pack/libbeat/docs/aws-credentials-config.asciidoc
- docs: add note about aws creds (#27434)
=> Cherry-pick to 7.14: docs: add note about aws creds (#27434)

x-pack/libbeat/docs/aws-credentials-config.asciidoc
- docs: add note about aws creds (#27434)
=> Cherry-pick to 7.x: docs: add note about aws creds (#27434)

libbeat/docs/shared-kibana-config.asciidoc, libbeat/docs/shared-ssl-config.asciidoc
- [DOCS] Remove PKI mentions (#27422)
=> Cherry-pick to 7.14: [DOCS] Remove PKI mentions (#27422)

filebeat/docs/modules/azure.asciidoc, x-pack/filebeat/module/azure/_meta/docs.asciidoc
When we only put one default eventhub settings in this reference, the user might be confused they can use a single eventhub for all event types even the field mappings and parsing logic are different. Let's add all default settings with the notes that the user needs to understand each log type has different fields, expicitly.
The user could use one single eventhub and having trouble when the logs are parsed from Elasticsearch side.
=> Add default evenhub settings for each log type

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 19 Aug 2021 17:21:47 GMT, release_branch:7.15, prefix:, end_time:Thu, 19 Aug 2021 23:10:40 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.15, build_id:7.15.0-e06b4078, build_duration_seconds:20933]
=> [automation] update elastic stack version for testing 7.15.0-e06b4078

libbeat/metric/system/cgroup/util.go, libbeat/metric/system/process/process.go
This fixes two issues with the logging in system/process. Based on @jsoriano 's feedback, I've changed the logging level for the hybrid cgroup warning message. We may want to do something to further pair down this log line, but the `debug` level is already so full of stuff that this feels like we're not adding _too_ much. This also fixes a big with an unrelated log line.
- Pull down
- Run `system/process` with debug-level logging, insure that the `Process name does not matches the provided regex` log message is formatted correctly
=> Fix logging in cgroup/process code

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Sun, 22 Aug 2021 17:24:20 GMT, release_branch:7.15, prefix:, end_time:Sun, 22 Aug 2021 23:11:16 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.15, build_id:7.15.0-a7c04a10, build_duration_seconds:20816]
=> [automation] update elastic stack version for testing 7.15.0-a7c04a10

filebeat/docs/modules/azure.asciidoc, x-pack/filebeat/module/azure/_meta/docs.asciidoc
- Add default evenhub settings for each log type (#27459)
=> Cherry-pick to master: Add default evenhub settings for each log type (#27459)

filebeat/docs/modules/azure.asciidoc, x-pack/filebeat/module/azure/_meta/docs.asciidoc
Backports the following commits to 7.15:
- Add default evenhub settings for each log type (#27459)
=> Cherry-pick to 7.15: Add default evenhub settings for each log type (#27459)

filebeat/docs/modules/azure.asciidoc, x-pack/filebeat/module/azure/_meta/docs.asciidoc
- Add default evenhub settings for each log type (#27459)
=> Cherry-pick to 7.x: Add default evenhub settings for each log type (#27459)

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 18 Aug 2021 12:15:22 GMT, release_branch:7.14, prefix:, end_time:Wed, 18 Aug 2021 17:41:57 GMT, manifest_version:2.0.0, version:7.14.1-SNAPSHOT, branch:7.14, build_id:7.14.1-a6cb01c7, build_duration_seconds:19595]
=> [automation] update elastic stack version for testing 7.14.1-a6cb01c7

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 23 Aug 2021 17:24:10 GMT, release_branch:7.15, prefix:, end_time:Mon, 23 Aug 2021 23:16:17 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.15, build_id:7.15.0-ab91276c, build_duration_seconds:21127]
=> [automation] update elastic stack version for testing 7.15.0-ab91276c

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 23 Aug 2021 05:15:50 GMT, release_branch:7.x, prefix:, end_time:Mon, 23 Aug 2021 11:11:54 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-c3b80e7b, build_duration_seconds:21364]
=> [automation] update elastic stack version for testing 7.16.0-c3b80e7b

CHANGELOG.next.asciidoc, filebeat/docs/modules/azure.asciidoc, x-pack/filebeat/module/azure/_meta/docs.asciidoc
Cherry-pick of PR #26604 to 7.x branch. Original message: 
Fix YAML indenting for module configuration example
The example given was invalid
=> Cherry-pick #26604 to 7.x: Indenting correction for module configuration example

CHANGELOG.next.asciidoc, libbeat/docs/shared-ilm.asciidoc, libbeat/idxmgmt/ilm/ilm_test.go, libbeat/idxmgmt/ilm/std.go
Previously, if both `setup.ilm.check_exists` and `setup.ilm.overwrite` was disabled, Beats would still believe that the alias and/or the ILM policy has to be loaded.
This might be a breaking change, but from now on if `check_exists` is disabled, `overwrite` is ignored. But I think it is acceptable because people would only disable `check_exists` if the user connecting to ES does not have the required permissions. Thus, if the user does not have read permission for ILM components, it means that it does not have enough permission to load ILM components. Thus, trying to overwrite anything when `check_exists` is disabled makes no sense. If this is not good enough reasoning, the solution can be changed to still not load anything with the weird settings.
Without this change Beats will try to …
=> Do not try to load ILM if check_exists if false

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 24 Aug 2021 00:14:42 GMT, release_branch:7.15, prefix:, end_time:Tue, 24 Aug 2021 05:51:05 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.15, build_id:7.15.0-b20b12b2, build_duration_seconds:20183]
=> [automation] update elastic stack version for testing 7.15.0-b20b12b2

dev-tools/mage/dockerbuilder.go, dev-tools/mage/pkgtypes.go
This interpolates the `variant` into the format string for .tar.gz docker artifacts. In also correctly handles the case where the format string is used in contexts without variant present, such as darwin. We still need an empty value for the templating language not to error.
Fixes https://github.com/elastic/beats/issues/27608
=> [elastic-agent] Fix docker tar.gz generation for complete image

CHANGELOG.next.asciidoc, filebeat/module/auditd/_meta/kibana/7/visualization/5ebdbe50-0a0f-11e7-825f-6748cda7d858-ecs.json
Updates a Kibana visualization provided by Filebeat's auditd module so that it filters on the lowercase value `execve` instead of uppercase.
For a long time the module has been lowercasing the value of the ECS event.action field, but the dashboard wasn't updated.
=> Filebeat auditd: Fix Top Exec Commands dashboard visualization

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 30 Aug 2021 05:19:03 GMT, release_branch:7.x, prefix:, end_time:Mon, 30 Aug 2021 11:58:36 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-978c8c33, build_duration_seconds:23973]
=> [automation] update elastic stack version for testing 7.16.0-978c8c33

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 30 Aug 2021 17:25:41 GMT, release_branch:7.15, prefix:, end_time:Tue, 31 Aug 2021 00:03:23 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.15, build_id:7.15.0-1649f9c1, build_duration_seconds:23862]
=> [automation] update elastic stack version for testing 7.15.0-1649f9c1

dev-tools/mage/kibana.go, libbeat/dashboards/importer.go, libbeat/dashboards/kibana_loader.go, libbeat/kibana/client.go, libbeat/kibana/client_test.go
This PR changes the dashboard loading by first loading its references and then loading the dashboards.
If the assets are not loaded in the proper order, the import can fail with unknown references.
=> Import the references of dashboard assets using the Saved Objects API

x-pack/osquerybeat/beater/action_handler.go, x-pack/osquerybeat/beater/action_handler_test.go, x-pack/osquerybeat/beater/config_plugin.go, x-pack/osquerybeat/beater/osquerybeat.go, x-pack/osquerybeat/internal/pub/publisher.go, x-pack/osquerybeat/internal/pub/publisher_test.go
Improves testability and unit test coverage
* Refactor action handler for testability, decouple from beats and
osquery client details.
* Cleanup lint warnings in config_plugin
* Refactor and encapsulate events publishing details into
pub/publisher.go
Better tested code
=> Osquerybeat: Improve testability and unit test coverage

filebeat/module/auditd/_meta/kibana/7/visualization/5ebdbe50-0a0f-11e7-825f-6748cda7d858-ecs.json
Re-applies the fix introduced by #27646, as it's been reverted in #27636. This is caused by merging PRs in a different order than in master.
=> Re-apply fix for auditd dashboard

libbeat/dashboards/kibana_loader.go, libbeat/dashboards/modify_json.go, libbeat/dashboards/modify_json_test.go
This PR addresses 3 minor issues in dashboard loading:
1. Everything should be loaded once
2. Some fields have to be strings that were objects before
3. Replacing index names in dashboards is no longer an NDJSON
This prevented setup from working properly.
=> Addressing multiple dashboard issues: deps loading once, field conversion, etc.

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 31 Aug 2021 05:24:19 GMT, release_branch:7.x, prefix:, end_time:Tue, 31 Aug 2021 12:00:51 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-8a18fe34, build_duration_seconds:23792]
=> [automation] update elastic stack version for testing 7.16.0-8a18fe34

CHANGELOG.next.asciidoc, filebeat/input/filestream/input.go, libbeat/reader/readfile/metafields.go, libbeat/reader/readfile/metafields_test.go
This PR fixes the `FileMetaReader` that previously only added the size of the message to `log.offset` field, instead of the offset in the file. It does not impact the log input, only the filestream.
An incorrect value was stored in the `log.offset` field in filestream. It was reported in https://discuss.elastic.co/t/filebeat-7-14-0-filestream-input-field-log-offset-is-character-count-of-the-line/282956/2
=> Store offset in log.offset field of events from the filestream input

x-pack/elastic-agent/pkg/agent/operation/operation.go, x-pack/elastic-agent/pkg/agent/operation/operator.go, x-pack/elastic-agent/pkg/core/plugin/process/app.go, x-pack/elastic-agent/pkg/core/plugin/service/app.go, x-pack/elastic-agent/pkg/core/state/state.go, x-pack/elastic-agent/pkg/core/status/reporter.go, x-pack/libbeat/management/manager.go
Followup to https://github.com/elastic/beats/pull/27210
This PR reduces context cancelled from status reporting including cases when process itself reports failure due to context cancelled. 
Result is that two messages described in a comment linked below will disappear.
These does not alter behaviour and occur just at the time of restarting. But it may look like there's something wrong with process, operator or agent itself as failures propagate up.
Fixes: https://github.com/elastic/beats/issues/27062#issuecomment-908108760
=> Ignore context cancell in status reporting

metricbeat/docker-compose.yml, metricbeat/module/logstash/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
Merge after the release 7.14.1.
=> chore: Update test environments 7.14.2

metricbeat/docs/modules/gcp.asciidoc, metricbeat/docs/modules/gcp/gke.asciidoc, metricbeat/docs/modules_list.asciidoc, x-pack/metricbeat/metricbeat.reference.yml, x-pack/metricbeat/module/gcp/_meta/config.yml, x-pack/metricbeat/module/gcp/_meta/docs.asciidoc, x-pack/metricbeat/module/gcp/gke/_meta/docs.asciidoc, x-pack/metricbeat/module/gcp/metrics/_meta/docs.asciidoc, x-pack/metricbeat/modules.d/gcp.yml.disabled
Provide documentation for GKE metricset.
Metricset documentation was not present in #26824.
- Required for #27532
=> [Metricbeat] gcp: add gke metricset documentation

x-pack/elastic-agent/CHANGELOG.next.asciidoc, x-pack/elastic-agent/pkg/agent/cmd/enroll_cmd.go, x-pack/elastic-agent/pkg/agent/configuration/fleet_server.go
Rename the output.elasticsearch.proxy_disabled flag to proxy_disable as
that is what the flag appears as under all other settings including
fleet.
fleet-server expects the setting to be named proxy_disable
- [] ~~I have commented my code, particularly in hard-to-understand areas
- [] ~~I have made corresponding changes to the documentation
- Closes #27670
=> Fix output.elasticsearch.proxy_disable flag

metricbeat/module/system/process/process.go
So, a while ago @axw added support for `LIBBEAT_MONITORING_CGROUPS_HIERARCHY_OVERRIDE` in libbeat monitoring. However, it wasn't added to system/process. I'm going to assume it was just overlooked, and there wasn't a reason to exclude it, so this adds it, so we get proper cgroup metrics from a container.
This is kind of a bug, as we properly report cgroup metrics within libbeat monitoring, but not within metricbeat.
- Pull down and build
- Run metricbeat inside a container, make sure cgroup metrics are correctly reported from within `system/process`
=> Add LIBBEAT_MONITORING_CGROUPS_HIERARCHY_OVERRIDE to system/process

CHANGELOG.next.asciidoc, x-pack/filebeat/module/crowdstrike/falcon/ingest/pipeline.yml
fix process fields that were being created as flattened fields
This fix the process fields that were being created as flatenned fields instead of nested.
Mixing flattened fields and nested fields with similar name is confusing and could lead to errors when running queries or automated processes that expects the nested fields.
- Closes #27622
=> [filebeat] fix crowdstrike ingest pipeline

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-httpjson.asciidoc, x-pack/filebeat/input/httpjson/internal/v2/value_tpl.go, x-pack/filebeat/input/httpjson/internal/v2/value_tpl_test.go
This adds base64encode functionality for value templates in httpjson input.
Adds new functionality to httpjson input.
Adding possibility for `.request` and `.header` comes in a separate PR.
- Closes #27610
=> [Filebeat] adding base64encode func to value template

x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc, x-pack/filebeat/input/awss3/input.go, x-pack/filebeat/input/awss3/input_integration_test.go, x-pack/filebeat/input/awss3/states.go
Enhancement
Allows to ingest logs from aws-s3 bucket listing input regardless of the region used in the aws profile
https://github.com/elastic/observability-test-plans/issues/232#issuecomment-910333796
-
=> Override region according to bucket location

CHANGELOG.next.asciidoc, libbeat/processors/add_kubernetes_metadata/kubernetes.go, libbeat/processors/add_kubernetes_metadata/kubernetes_test.go
This PR prevents `add_kubernetes_metadata` processor from running in cases kubernetes metadata are already present in an event.
This change prevents metadata being overridden by the processor.
Also In cases where the processor is run by `elastic-agent` (enabled by default) it fails since the matchers are not properly configured (see https://github.com/elastic/beats/issues/27216).
1. Run filebeat on kubernetes with kubernetes autodiscover provider enabled [(doc)](https://www.elastic.co/guide/en/beats/filebeat/master/configuration-autodiscover.html, the provider adds the metadata) and also `add_kubernetes_metadata`  processor enabled.
Check in the logs that the processor is being skipped.
2. Run filebeat on kubernetes with input of type container …
=> Skip add_kubernetes_metadata processor if kubernetes metadata are aleady there

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-httpjson.asciidoc, x-pack/filebeat/input/httpjson/internal/v2/value_tpl.go, x-pack/filebeat/input/httpjson/internal/v2/value_tpl_test.go
- Adds `join` and `sprintf` functions.
=> [httpjson] Add new join and sprintf functions

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-httpjson.asciidoc, x-pack/filebeat/input/httpjson/internal/v2/input_test.go, x-pack/filebeat/input/httpjson/internal/v2/rate_limiter.go, x-pack/filebeat/input/httpjson/internal/v2/rate_limiter_test.go
- Fixes the rate limit processing. Previously it was reading the value from `.headers` but it was expected from the documentation to be accessed through `.last_response.headers`
- Fixes several documentation errors
Users were not getting rate limit data when they were using the feature as documented.
The documentation was not accurate about data access contexts.
Closes #23023
=> [httpjson] Fix httpjson rate limit processing and documentation

libbeat/service/service_unix.go, libbeat/service/service_windows.go, x-pack/elastic-agent/pkg/agent/cmd/run.go
The problem is described in issue: https://github.com/elastic/beats/issues/27527
When user wants to stop the service using service manager, error is returned about unexpected termination and agent is restarted.
Reason for this is that agent won't send `stopped` state to service manager before termination. 
In our codebase we use `NotifyTermination` provided by libbeat on exit. This closes channel and exits the state loop running in a separate goroutine which then should send the `stopped` state to service manager.
The problem is when we exit right after this call and too quickly. In this case goroutine wont reach the point where `stopped` is sent and service manager gets the impression we crashed. 
To fix this we just need to make sure that `svc.Run` in …
=> [Elastic Agent] Await execution finish on windows

filebeat/input/filestream/environment_test.go, filebeat/input/filestream/input_integration_test.go
This PR initializes the input manager for filestream in the integration tests. The recent changes in the update merging process requires one last state update before the manager shuts down. Previously, there was nothing to shut down, because the manager was not initialized.
The lack of initialization caused flakiness in most filestream tests as sometimes there was not enough time for all state updates to be serialized before the input was shut down.
~~- [ ] I have added an entry in …
=> Fix flakyness of TestFilestreamEmptyLine

CHANGELOG.next.asciidoc, filebeat/docs/inputs/input-syslog.asciidoc, filebeat/docs/modules/cef.asciidoc, filebeat/input/syslog/config.go, filebeat/input/syslog/input.go, go.mod, go.sum, libbeat/common/cfgtype/timezone.go, libbeat/common/cfgtype/timezone_test.go, libbeat/common/datetime.go, libbeat/processors/timestamp/config.go, libbeat/processors/timestamp/docs/timestamp.asciidoc, libbeat/processors/timestamp/timestamp.go, libbeat/processors/timestamp/timestamp_test.go, x-pack/filebeat/module/cef/_meta/docs.asciidoc, x-pack/filebeat/module/cef/log/config/input.yml, x-pack/filebeat/module/cef/log/manifest.yml, x-pack/filebeat/processors/decode_cef/cef/cef.go, x-pack/filebeat/processors/decode_cef/cef/cef_test.go, x-pack/filebeat/processors/decode_cef/cef/option.go, x-pack/filebeat/processors/decode_cef/cef/types.go, x-pack/filebeat/processors/decode_cef/cef/types_test.go, x-pack/filebeat/processors/decode_cef/config.go, x-pack/filebeat/processors/decode_cef/decode_cef.go, x-pack/filebeat/processors/decode_cef/docs/decode_cef.asciidoc
CEF messages that contain timestamps without a timezone were parsed as UTC. The time zone was not
configurable. This adds a `timezone` option to the decode_cef processor and cef module to allow the
time zone to be specified when a timestamp does not contain an offset or zone.
CEF:0|Aruba Networks|ClearPass|6.8.7.120583|2002|RADIUS Accounting|1|rt=Aug 04 2021 11:31:15
This also replaces the deprecated `import "4d63.com/tz"` with Go's relatively new built-in
`time/tzdata` package. The `timestamp` processor was updated.
While I was adding the a timezone config type I made the syslog input's timezone configurable too.
Fixes #27232
Timestamps were being interpreted incorrectly.
- Closes #27232 …
=> [Filebeat] Add timezone config option to decode_cef and syslog input

CHANGELOG.next.asciidoc, filebeat/input/syslog/parser/syslog_rfc3164.rl, filebeat/input/syslog/rfc3164_parser.go, filebeat/input/syslog/rfc3164_test.go
This makes the RFC3164 parser accept dates with a leading 0. This makes the parser a little more liberal than the spec.
From RFC3164 https://datatracker.ietf.org/doc/html/rfc3164#section-4.1.2
> If the day of the month is less than 10, then it MUST be represented as a space and then the number. For example, the 7th day of August would be represented as "Aug 7", with two spaces between the "g" and the "7".
So now it will accept both `Sep 01` and `Sep  1`.
=> [Filebeat] Accept syslog dates with leading 0

x-pack/elastic-agent/CHANGELOG.next.asciidoc, x-pack/elastic-agent/pkg/agent/cmd/enroll.go, x-pack/elastic-agent/pkg/agent/cmd/install.go
Adds validation to the `install` and `enroll` command to ensure that certificate paths are absolute paths.
If absolute paths are not used then that can affect the ability for the Elastic Agent to pass paths to Fleet Server.
- Closes #27677
=> [Elastic Agent] Add validation to ensure certificate paths are absolute.

libbeat/cmd/instance/beat_test.go
This is arguably a bug fix.
This change ensures that the test config is owner-exclusive write before running the test. It also adds checks to currently ineffective error assignments.
Git does not store r/w permissions, instead depending on the host system's umask. On some systems the default umask is 0o002, meaning that the test config file is checked out with g+w permission, causing the test to fail.
Run `go test` in github.com/elastic/beats/libbeat/cmd/instance. …
=> libbeat/cmd/instance: ensure test config file has appropriate permissions

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 7 Sep 2021 00:24:48 GMT, release_branch:7.15, prefix:, end_time:Tue, 7 Sep 2021 06:30:43 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.15, build_id:7.15.0-b8b8307a, build_duration_seconds:21955]
=> [automation] update elastic stack version for testing 7.15.0-b8b8307a

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Sat, 4 Sep 2021 05:24:03 GMT, release_branch:7.x, prefix:, end_time:Sat, 4 Sep 2021 11:48:38 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-a96d8aa5, build_duration_seconds:23075]
=> [automation] update elastic stack version for testing 7.16.0-a96d8aa5

CHANGELOG.next.asciidoc, filebeat/fileset/compatibility.go, filebeat/fileset/compatibility_test.go
Update Filebeat compatibility function to remove processor description field on ES < 7.9.0
Users with new versions of Filebeat and ES versions < 7.9.0 will run into errors when loading module ingest pipelines.  See https://discuss.elastic.co/t/filebeat-v7-14-0-error-in-loading-pipeline/283407
=> [Filebeat] Update compatibility function to remove processor description on ES < 7.9.0

x-pack/osquerybeat/beater/logger_plugin.go
Fixes the osquery logger plugin log severity level mapping. For example 0 severity was mapped to error and was logged as "error" in osquerybeat logs instead of "info" level.
Log level correctness
Osquerybeat log before the change, showing "error" level log:
```
{"log.level":"error","@timestamp":"2021-09-07T21:36:56.248-0400","log.logger":"osquerybeat","log.origin":{"file.name":"beater/logger_plugin.go","file.line":69},"message":"Calling configure for logger osq_logger","service.name":    "osquerybeat","ctx":"logger","osquery.log_type":"status","osquery.severity":0,"osquery.filename":"config.cpp","osquery.line":891,"osquery.cal_time":"Wed Sep  8 01:36:53 2021 UTC","osquery.time":1631065013,"ecs.version":"1.6.0"}
```
Osquerybeat log after the change, showing the correct "info" level log: …
=> Osquerybeat: Fix osquery logger plugin severy levels mapping

libbeat/docs/shared-docker.asciidoc
- Docs
Simplify the file permission change in referenced Dockerfile by using `COPY --chown` argument.
See the Dockerfile documentation: https://docs.docker.com/engine/reference/builder/#copy
The one-step file copy with the right permissions allows to reduce the number of layers in resulting docker image and simplifies the code. See also the article explaining how the multi-step COPY + chown doubles the image size: https://blog.mornati.net/docker-images-and-files-chown
-
=> docs: simplify permissions for Dockerfile COPY

CHANGELOG.next.asciidoc, libbeat/reader/readfile/bench_test.go, libbeat/reader/readfile/line.go
Previously, the `LineReader` would allocate a []byte of size `config.BufferSize` before decoding each line. The underlying array's size allocation is fixed, so `outBuffer.Append` retains all of it even when the appended bytes are much shorter.
With this change, we store a single `tempBuffer []byte` which is reused across lines anywhere we need temporary storage. Converting to `outBuffer.Write` forces the buffer to copy data out of tempBuffer, but is able to only allocate space for the written bytes.
In our production environment, we run beats with k8s-enforced memory limits and are trying to resolve OOMs. The LineReader code path contributes a significant amount of memory allocation. The benchmarks added in bench_test.go show this reduces the memory profile with various line lengths:
``` …
```
=> LineReader: Reuse temporary buffer to reduce per-line allocation

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 8 Sep 2021 00:26:05 GMT, release_branch:7.15, prefix:, end_time:Wed, 8 Sep 2021 07:05:07 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.15, build_id:7.15.0-f15c4154, build_duration_seconds:23942]
=> [automation] update elastic stack version for testing 7.15.0-f15c4154

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 8 Sep 2021 05:16:11 GMT, release_branch:7.x, prefix:, end_time:Wed, 8 Sep 2021 11:43:49 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-468522bc, build_duration_seconds:23258]
=> [automation] update elastic stack version for testing 7.16.0-468522bc

.ci/packaging.groovy
It removes a Jenkins param from the packaging job, used to trigger the E2E tests
Keep consistency
-
=> chore(ci): remove not used param when triggering e2e tests

CHANGELOG.next.asciidoc, auditbeat/module/file_integrity/metricset_test.go, auditbeat/module/file_integrity/scanner.go
In auditbeat scanner:
- If included_files is set and file name does not match included_files then it is
skipped
- directories are included even if they don't match included_files
because the contents might
All files were being scanned in first scan unless listed in `exclude_files`
`mage goUnitTest`
- Closes #27273
=> [Auditbeat] scanner honor include_files

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 8 Sep 2021 17:12:18 GMT, release_branch:6.8, prefix:, end_time:Wed, 8 Sep 2021 22:03:42 GMT, manifest_version:2.0.0, version:6.8.19-SNAPSHOT, branch:6.8, build_id:6.8.19-1dd02041, build_duration_seconds:17484]
=> [automation] update elastic stack version for testing 6.8.19-1dd02041

x-pack/elastic-agent/CHANGELOG.next.asciidoc, x-pack/elastic-agent/pkg/agent/application/application.go, x-pack/elastic-agent/pkg/agent/application/pipeline/actions/handlers/handler_action_settings.go, x-pack/elastic-agent/pkg/agent/application/pipeline/actions/handlers/handler_action_upgrade.go, x-pack/elastic-agent/pkg/agent/application/reexec/manager.go, x-pack/elastic-agent/pkg/agent/application/upgrade/upgrade.go, x-pack/elastic-agent/pkg/agent/application/upgrade/upgrade_test.go, x-pack/elastic-agent/pkg/agent/cmd/run.go, x-pack/elastic-agent/pkg/agent/control/server/server.go, x-pack/elastic-agent/pkg/release/version.go
This PR adds a shutdown callback called by Reexec manager once everything is shutdown.
This callback is then used to migrate state (located in `paths.home/run/defualt/*`) of running processes from stale version path to new version path. these paths are unique for each version of the process.
e2e needs to be added
Without this state of the processes is not migrated which may result in duplicate events.
Fixes: https://github.com/elastic/beats/issues/27773
=> Elastic Agent: Migrate state on upgrade

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 9 Sep 2021 17:25:55 GMT, release_branch:7.15, prefix:, end_time:Thu, 9 Sep 2021 23:54:49 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.15, build_id:7.15.0-4efca5cc, build_duration_seconds:23334]
=> [automation] update elastic stack version for testing 7.15.0-4efca5cc

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 9 Sep 2021 17:14:54 GMT, release_branch:6.8, prefix:, end_time:Thu, 9 Sep 2021 22:08:49 GMT, manifest_version:2.0.0, version:6.8.19-SNAPSHOT, branch:6.8, build_id:6.8.19-bc1f1f3a, build_duration_seconds:17635]
=> [automation] update elastic stack version for testing 6.8.19-bc1f1f3a

CHANGELOG.next.asciidoc, libbeat/reader/readfile/metafields.go, libbeat/reader/readfile/metafields_test.go
The PR renames `log.path` to `log.file.path` in filestream input events.
The old `log.path` is not ECS compliant and inconsistent with the old log input.
Closes #27776
=> Rename log.path field to log.file.path to be ECS complicant

x-pack/osquerybeat/beater/osquerybeat.go
Fixes the issue reported on windows, where our extension server client fails to connect to the osqueryd named pipe.
```
[elastic_agent.osquerybeat][error] Failed to run osqueryd: dialing pipe '\\.\pipe\elastic\osquery\d4501c4e-98f2-454c-8e46-e61b4f9a898d': open \\.\pipe\elastic\osquery\d4501c4e-98f2-454c-8e46-e61b4f9a898d: The system cannot find the file specified.
```
The issue is due to the change on July 8th, where the sequence of the osqueryd startup was changed. This changed the sequence back to:
1. start osqueryd
2. connect the osquery client to osqueryd (with retires)
3. start extensions server for our own config and logging plugins
The osquery client connection with retries  before starting the extensions server guarantees that the osqueryd is running with the given named pipe. …
=> Osquerybeat: Fix 7.15 extension start failure on windows

x-pack/elastic-agent/CHANGELOG.next.asciidoc, x-pack/elastic-agent/pkg/agent/cmd/status.go, x-pack/elastic-agent/pkg/agent/cmd/status_test.go, x-pack/elastic-agent/pkg/agent/operation/operator.go
Add '_monitoring' suffix to monitoring process names so that they can be
distinguished from other processes. This is relevant for the status
command where the beat instances appear the same in output. Changed the
output format of the human readable option to better align text with the
longer names.
Allows users to determine if the monitoring instances, or "regular" beats instances are healthy.
- [] ~~I have made corresponding changes to the documentation~~
run `elastic-agent status`
- Closes #25449
Example of the new output:
```
bash-4.2$ elastic-agent …
```
=> Add '_monitoring' suffix to monitoring process names

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Sun, 12 Sep 2021 05:15:44 GMT, release_branch:7.x, prefix:, end_time:Sun, 12 Sep 2021 11:42:48 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-fbd5fab2, build_duration_seconds:23224]
=> [automation] update elastic stack version for testing 7.16.0-fbd5fab2

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Sun, 12 Sep 2021 17:13:27 GMT, release_branch:6.8, prefix:, end_time:Sun, 12 Sep 2021 21:51:40 GMT, manifest_version:2.0.0, version:6.8.19-SNAPSHOT, branch:6.8, build_id:6.8.19-fac6e556, build_duration_seconds:16693]
=> [automation] update elastic stack version for testing 6.8.19-fac6e556

filebeat/input/filestream/input.go, libbeat/reader/message.go, libbeat/reader/message_test.go
This PR moves the function that creates an event from the Filestream input to libbeat, so becomes reusable.
With this change, we can avoid duplicating conversion functions in the codebase.
=> Generalize creating a beat.Event from a reader.Message

CHANGELOG-developer.next.asciidoc, CHANGELOG.next.asciidoc, metricbeat/mb/module/wrapper.go
Until now errors in the metric sets were only reported as INFO. If someone configures metricbeat to only write a log file on error, issues like `cannot connect to Elasticsearch 404, 400 Bad request` could be missed.
* Easier debugging
* If metricbeat cannot connect it is an `error` and should be classified as such a thing.
- Closes #27799
- Had some issues with Git in this one https://github.com/elastic/beats/pull/27803
=> Metricbeat, fix metricsets log level behavior

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 13 Sep 2021 17:26:11 GMT, release_branch:7.15, prefix:, end_time:Mon, 13 Sep 2021 23:23:34 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.15, build_id:7.15.0-d48cd6f3, build_duration_seconds:21443]
=> [automation] update elastic stack version for testing 7.15.0-d48cd6f3

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 13 Sep 2021 05:14:31 GMT, release_branch:7.x, prefix:, end_time:Mon, 13 Sep 2021 11:50:59 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-f4fa0a64, build_duration_seconds:23788]
=> [automation] update elastic stack version for testing 7.16.0-f4fa0a64

deploy/kubernetes/metricbeat-kubernetes.yaml, deploy/kubernetes/metricbeat/metricbeat-daemonset-configmap.yaml
Add a comment in metricbeat daemonset configmap to avoid setting `unique:true` in case of large kubernetes clusters. 
Enabling leader election on Kubernetes means that only the one daemonset instance holding a lease will request cluster wide metrics from `kube-state-metrics`. In very large clusters this can cause performance issues. 
In [documentation](https://www.elastic.co/guide/en/beats/metricbeat/current/running-on-kubernetes.html#_deploying_metricbeat_to_collect_cluster_level_metrics_in_large_clusters) there is a suggestion for working around this kind of problems. 
It would be nice to add that also in the proposed configmap so that users can notice it more easily.
=> Add comment in metricbeat configmap to avoid leader election in large  k8s clusters

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-httpjson.asciidoc, x-pack/filebeat/input/httpjson/internal/v2/config_response.go, x-pack/filebeat/input/httpjson/internal/v2/split.go, x-pack/filebeat/input/httpjson/internal/v2/split_test.go
This adds a configuration option "ignore_error" that allows a split processor chain to continue if a target field is present but empty.
This is required to address #26008 by allowing multiple splits on an input (see https://github.com/elastic/beats/issues/26008#issuecomment-915875217).
~~- [ ] I have made corresponding change to the default configuration files~~ Defaults to existing behaviour.
Standard testing.
- Relates #26008
See related issue.
N/A
N/A
=> x-pack/filebeat/input/httpjson/internal/v2: allow split chains to continue past empty targets

testing/environments/docker/kafka/Dockerfile, testing/environments/docker/kafka/healthcheck.sh
The Kafka Docker container's healthcheck script had a typo that caused it to create an infinite number of garbage topics, which added noise when testing configurations with this container. This PR fixes the script, and adjusts its timeout settings to be a little lower frequency and a little less patient with consistent errors.
=> Make the Kafka container healthcheck less noisy

x-pack/elastic-agent/CHANGELOG.next.asciidoc, x-pack/elastic-agent/pkg/artifact/download/snapshot/downloader.go
Change the HTTP client from the standard library client to one built
from the http settings supplied to the artifact downloader
(`agent.download` in fleet.yml) so that proxy settings are used for the
initial request to find the artifact location as well as the subsequent
download.
Allows agent to upgrade to snapshot versions when agents are behind an Internet proxy.
- [] ~~I have made corresponding changes to the documentation~~
1. Deploy agent behind an Internet proxy.
2. Add a `agent.download.proxy_url` setting to `fleet.yml`.
3. Trigger an upgrade to a …
=> Elastic-agent snapshot lookup will use proxy settings

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 14 Sep 2021 00:25:37 GMT, release_branch:7.15, prefix:, end_time:Tue, 14 Sep 2021 06:05:15 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.15, build_id:7.15.0-4d52e36a, build_duration_seconds:20378]
=> [automation] update elastic stack version for testing 7.15.0-4d52e36a

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 14 Sep 2021 05:24:03 GMT, release_branch:7.x, prefix:, end_time:Tue, 14 Sep 2021 11:48:41 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-b40a7e80, build_duration_seconds:23078]
=> [automation] update elastic stack version for testing 7.16.0-b40a7e80

filebeat/input/filestream/parsers_integration_test.go
Skip filestream flaky tests:
* https://github.com/elastic/beats/issues/27893
* https://github.com/elastic/beats/issues/27894
* https://github.com/elastic/beats/issues/27085
=> Skip filestream flaky tests

filebeat/docs/modules/sophos.asciidoc, x-pack/filebeat/module/sophos/_meta/docs.asciidoc
**Syslog options**
Setting the correct syslog output option in Sophos is mandatory for the filebeat module to work.
There are two possible settings inside Sophos:
1. `Device Standard Format`
2. `Central Reporting Format`
When using `Device Standard Format` weird parsing error, timestamp issues and more occur frequently. I suggest to change it to `Central Reporting Format`. With the `Central reporting format` no parsing issues where detected.
**Version update**
I am currently running the module successfully against version 18.5, so I suggest to bump the supported version in the docs.
With the wrong syslog format set in sending from Sophos to Filebeat, the module will not work properly. Anyone using this module expects clear guidance on what to configure on both sides.
=> Filebeat module sophos documentation fixes

CHANGELOG.next.asciidoc, libbeat/common/encoding/xml/decode.go, libbeat/common/encoding/xml/decode_test.go, libbeat/processors/decode_xml/decode_xml_test.go
Arrays were not being merged properly when the element name was mixed-case and `to_lower: true` was set in the config (the default).
For lists of elements, if the XML element name was mixed-cased then it would drop elements rather than appending them to the array.
=> [libbeat] Fix decode_xml array handling when lowercasing keys

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-httpjson.asciidoc, x-pack/filebeat/input/httpjson/internal/v2/pagination.go, x-pack/filebeat/input/httpjson/internal/v2/request.go, x-pack/filebeat/input/httpjson/internal/v2/transform_set.go, x-pack/filebeat/input/httpjson/internal/v2/transform_set_test.go, x-pack/filebeat/input/httpjson/internal/v2/transform_test.go
Adds write access to url.value from the request.transforms context.
Some use cases require to set the url for the next request from a previously stored value.
=> [filebeat] Add write access to 'url.value' from 'request.transforms'.

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 15 Sep 2021 17:21:52 GMT, release_branch:7.15, prefix:, end_time:Wed, 15 Sep 2021 23:16:49 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.15, build_id:7.15.0-1bab4292, build_duration_seconds:21297]
=> [automation] update elastic stack version for testing 7.15.0-1bab4292

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 15 Sep 2021 05:25:24 GMT, release_branch:7.x, prefix:, end_time:Wed, 15 Sep 2021 11:39:10 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-63cdb007, build_duration_seconds:22426]
=> [automation] update elastic stack version for testing 7.16.0-63cdb007

dev-tools/vagrant_scripts/winProvision.ps1
Fixes the volume path in vagrant windows script.
The symlink was pointing to an unexisting folder due to the wrong path.
=> Fix path in vagrant windows script

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
See #27953. Part of 7.14.2 release.
=> Forward port 7.14.2 changelog to 7.15

x-pack/elastic-agent/CHANGELOG.next.asciidoc, x-pack/elastic-agent/pkg/agent/cmd/enroll_cmd.go
Propogates the `--insecure` flag to the Fleet Server process, so it can communicate with elasticsearch insecurely.
Previously it was not possible to instruct Fleet Server to communicate insecurely with elasticsearch. Now if you are bootstrapping a Fleet Server and using `--insecure` it will also make communication with elasticsearch insecure.
- Closes #27956
=> Fix issue where --insecure didn't propogate to Fleet Server ES connection

x-pack/filebeat/input/awss3/sqs_s3_event.go
It should have used `Warnw` instead of `Warn` because it included structured data.
The makes the formatting of log messages better and easier to read.
=> [Filebeat] Fix logger statement in aws-s3 input

x-pack/heartbeat/monitors/browser/synthexec/synthexec.go
- [Heartbeat] use --params flag for synthetics (#26674)
=> Cherry-pick to 7.x: [Heartbeat] use --params flag for synthetics (#26674)

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 16 Sep 2021 17:17:01 GMT, release_branch:7.15, prefix:, end_time:Thu, 16 Sep 2021 22:55:35 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.15, build_id:7.15.0-353cd7d4, build_duration_seconds:20314]
=> [automation] update elastic stack version for testing 7.15.0-353cd7d4

CHANGELOG.next.asciidoc, go.mod, go.sum, libbeat/common/seccomp/policy_linux_arm64.go
This change adds a default seccomp policy for GOOS=linux GOARCH=arm64.
Arm64 is an increasingly important target, so adding seccomp protection to that arch is a valuable addition.
Note that unlike GOARCH!=arm64 arm64 does not have fork or vfork syscalls. However, Go's fork exec does not use fork(2) from what I can see, rather using clone(2) https://linux.die.net/man/2/clone. Perhaps clone should be added to this and the arm policy? (It's worth noting that clone is in the whitelist for amd64 and 386).
Standard testing.
N/A
N/A
N/A
N/A
=> libbeat/common/seccomp: provide default policy for linux arm64

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Sun, 19 Sep 2021 17:25:11 GMT, release_branch:7.15, prefix:, end_time:Sun, 19 Sep 2021 23:15:42 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.15, build_id:7.15.0-bc82566e, build_duration_seconds:21031]
=> [automation] update elastic stack version for testing 7.15.0-bc82566e

x-pack/filebeat/docs/inputs/input-httpjson.asciidoc, x-pack/filebeat/input/httpjson/internal/v2/value_tpl.go, x-pack/filebeat/input/httpjson/internal/v2/value_tpl_test.go
Enhances the httpjson template function `join` to accept any slice type instead of just `[]string`
Since it will be commonly used with unamrshaled response bodies, most of `[]string` will be represented as `[]interface{}` at the time of being used. We need to be able to treat them or any slice a user might want to join.
~- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~ Not yet released
=> [filebeat] httpjson join improvement

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 20 Sep 2021 17:24:33 GMT, release_branch:7.15, prefix:, end_time:Mon, 20 Sep 2021 23:19:14 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.15, build_id:7.15.0-5ab1fe99, build_duration_seconds:21281]
=> [automation] update elastic stack version for testing 7.15.0-5ab1fe99

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 20 Sep 2021 17:21:54 GMT, release_branch:6.8, prefix:, end_time:Mon, 20 Sep 2021 21:19:51 GMT, manifest_version:2.0.0, version:6.8.19-SNAPSHOT, branch:6.8, build_id:6.8.19-6502ef2b, build_duration_seconds:14277]
=> [automation] update elastic stack version for testing 6.8.19-6502ef2b

.ci/apm-beats-update.groovy, Jenkinsfile
Use https://github.com/elastic/apm-pipeline-library/blob/master/vars/obltGitHubComments.txt
Avoid hardcoded strings and easy to normalise the GitHub comments in all the oblt projects
=> [CI] use obltGitHubComments

.backportrc.json, .mergify.yml
1. Tidy up old branches.
2. Notify PR contributors about the backport policy.
This policy will notify what are the different backport options and tag the PR with the `backport-skip`.
See https://github.com/elastic/apm-pipeline-library/pull/1281#issuecomment-922766344 and https://github.com/elastic/apm-pipeline-library/pull/1281#event-5327050151
=> [mergify] notify if no backport labels on the PRs targeting the master branch

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 22 Sep 2021 21:27:32 GMT, release_branch:7.15, prefix:, end_time:Thu, 23 Sep 2021 03:39:09 GMT, manifest_version:2.0.0, version:7.15.1-SNAPSHOT, branch:7.15, build_id:7.15.1-f9f656c4, build_duration_seconds:22297]
=> [automation] update elastic stack version for testing 7.15.1-f9f656c4

filebeat/input/filestream/parsers_integration_test.go
Disabling flaky test
Issue reported: https://github.com/elastic/beats/issues/28088
cc @kvch I assigned reported issue to you
=> Disable TestParsersMultilineMaxBytes

filebeat/input/filestream/input_integration_test.go, filebeat/input/filestream/parsers_integration_test.go
Disabling flaky test
Issue reported: 
- https://github.com/elastic/beats/issues/28088
- https://github.com/elastic/beats/issues/27085
cc @kvch I assigned reported issue to you
=> Disable TestParsersMultilineMaxBytes and TestFilestreamTruncateBlockedOutput

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 22 Sep 2021 17:22:22 GMT, release_branch:6.8, prefix:, end_time:Wed, 22 Sep 2021 22:17:19 GMT, manifest_version:2.0.0, version:6.8.20-SNAPSHOT, branch:6.8, build_id:6.8.20-27f20cc8, build_duration_seconds:17697]
=> [automation] update elastic stack version for testing 6.8.20-27f20cc8

libbeat/docs/faq-refresh-index.asciidoc
I'm working on updating the kibana docs to account for the rename of kibana index patterns to data views. I've created a redirect but this is insufficient for named anchor tags. The easiest way forward is to remove the anchor tag for now and replace it once the data view docs have been committed, otherwise the new docs will never pass CI.
=> [docs] index-patterns.html#reload-fields => index-patterns.html

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 23 Sep 2021 17:23:03 GMT, release_branch:7.15, prefix:, end_time:Fri, 24 Sep 2021 00:14:59 GMT, manifest_version:2.0.0, version:7.15.1-SNAPSHOT, branch:7.15, build_id:7.15.1-de1fe33e, build_duration_seconds:24716]
=> [automation] update elastic stack version for testing 7.15.1-de1fe33e

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Sun, 26 Sep 2021 17:24:52 GMT, release_branch:7.15, prefix:, end_time:Sun, 26 Sep 2021 23:07:42 GMT, manifest_version:2.0.0, version:7.15.1-SNAPSHOT, branch:7.15, build_id:7.15.1-5f9d0364, build_duration_seconds:20570]
=> [automation] update elastic stack version for testing 7.15.1-5f9d0364

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 27 Sep 2021 22:17:58 GMT, release_branch:7.15, prefix:, end_time:Tue, 28 Sep 2021 04:57:19 GMT, manifest_version:2.0.0, version:7.15.1-SNAPSHOT, branch:7.15, build_id:7.15.1-34ec300e, build_duration_seconds:23961]
=> [automation] update elastic stack version for testing 7.15.1-34ec300e

CHANGELOG.next.asciidoc, libbeat/processors/add_kubernetes_metadata/config.go, libbeat/processors/add_kubernetes_metadata/config_test.go, libbeat/processors/add_kubernetes_metadata/docs/add_kubernetes_metadata.asciidoc, libbeat/processors/add_kubernetes_metadata/kubernetes.go
Enhancement
Given that we now have ability to do autodiscover at cluster scope. We should also be able to do metadata enrichment at cluster scope. This PR adds support for the same. 
Feature parity
Add `scope: cluster` to an existing add_kubernetes_metadata config and it should sync all pods from the entire cluster.
=> Add cluster level add_kubernetes_metadata support for centralized enrichment

x-pack/osquerybeat/_meta/config/beat.docker.yml.tmpl, x-pack/osquerybeat/_meta/config/beat.reference.yml.tmpl, x-pack/osquerybeat/_meta/config/beat.yml.tmpl, x-pack/osquerybeat/beater/config_plugin.go, x-pack/osquerybeat/beater/install.go, x-pack/osquerybeat/internal/distro/distro.go, x-pack/osquerybeat/internal/install/install.go, x-pack/osquerybeat/internal/osqd/osqueryd.go, x-pack/osquerybeat/osquerybeat.reference.yml, x-pack/osquerybeat/osquerybeat.yml, x-pack/osquerybeat/scripts/mage/distro.go
* Upgrades osquery to version 5.0.1
* Adjusts to the changed packaging for MacOS and Linux official osquery
distros. The MacOS osquery official distro now contains the application bundle osquery.app to support entitlement-based features. The paths to osqueryd are changed on linux and darwin in version 5.0.1.
* Corrects the osquerybeat reference configuration to reflect the
latest changes. It was not up to date since 7.14.
Picking up the latest release of osquery
Result of ad-hoc query reflects the version of osquery as 5.0.1
=> Osquerybeat: Upgrade osquery to version 5.0.1

Jenkinsfile
Instead of using a glob pattern to list the `system-tests-*.tar.gz` files to upload to the GCP bucket, it limits the `ls` command to the parent dir (`build`).
With the previous command, we have noticed errors in the Groovy execution when there are no files matching the glob pattern, causing to fail the upload step.
- Relates https://github.com/elastic/beats/pull/22220
- Relates https://github.com/elastic/beats/pull/27069
- Relates https://github.com/elastic/beats/pull/27295
From CI build: https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats/detail/PR-28124/2/pipeline/
>[2021-09-27T01:06:36.137Z] + ls -l src/github.com/elastic/beats/build/system-tests-*.tar.gz
[2021-09-27T01:06:36.137Z] ls: cannot access 'src/github.com/elastic/beats/build/system-tests-*.tar.gz': No such …
=> fix(ci): list files in the directory without glob pattern

libbeat/outputs/logstash/docs/logstash.asciidoc
Clarifies time units for `ttl` setting in Beats, as asked on https://discuss.elastic.co/t/filebeat-ttl-value-is-it-seconds-milliseconds/138646
Makes the setting easier to use.
=> [DOC] Clarify time units in ttl

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 28 Sep 2021 17:19:42 GMT, release_branch:7.15, prefix:, end_time:Tue, 28 Sep 2021 23:12:42 GMT, manifest_version:2.0.0, version:7.15.1-SNAPSHOT, branch:7.15, build_id:7.15.1-56129787, build_duration_seconds:21180]
=> [automation] update elastic stack version for testing 7.15.1-56129787

CHANGELOG.next.asciidoc, metricbeat/module/beat/beat.go, metricbeat/module/beat/beat_test.go
Support `basepath` in the beat module, as per the documentation
This is expected behavior, and it's documented as being supported.
- closes https://github.com/elastic/beats/issues/28159
=> [metricbeat] support basepath in beat module

filebeat/docs/modules/aws.asciidoc, metricbeat/docs/modules/aws.asciidoc, x-pack/filebeat/module/aws/_meta/docs.asciidoc, x-pack/metricbeat/module/aws/_meta/docs.asciidoc
This is a small fix in Filebeat doc to sync the definition of api_timeout config between aws-s3 input and the aws module.
=> Update Filebeat aws module doc

testing/environments/snapshot.yml
The default format of the /api/status output is changing so update our
check. We'll use v8format=true so that checks against older images will
pass too.
Relates https://github.com/elastic/kibana/pull/110830
Allows tests to execute under newer Kibana versions.
Old format:
```json
{
"name": "fd1c727b700f",
"uuid": "903de1b1-9d8b-4db6-9932-00c8ccd26bbc",
"version": {
"number": "8.0.0",
"build_hash": "b1f38f459f9b5f259e9f99ad9d02f67e90505830",
"build_number": 45390,
"build_snapshot": true
},
"status": {
"overall": {
"since": "2021-09-29T13:46:24.658Z",
"state": "yellow",
"title": "Yellow",
"nickname": "I'll be back",
"icon": "warning",
"uiColor": "warning"
},
```
New format:
```json
{
"name": "7d1500db67ba",
"uuid": "d55b6d6c-0b87-4364-915f-cc92af242a67",
"version": {
"number": "8.0.0", …
```
=> Use v8format=true for Kibana health check

.ci/packaging.groovy
Remove `linux` and `arm` input parameters.
Simplify the logic, since the e2e pipeline uses both architectures.
Rather than adding more logic to the e2e pipeline in case a packaging build was triggered through the UI in Jenkins. Let's enforce the rule to build docker images for both architectures.
Maybe the granularity could be done on a beats level, since the current bottleneck happens with the `x-pack/elastic-agent` module. But that's something that could be anyway solved if we use the `packaging` and `e2e` within the default/main CI pipeline that already provides those particular stages.
=> [packaging][ci] simplify input parameters

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 27 Sep 2021 05:21:40 GMT, release_branch:7.x, prefix:, end_time:Mon, 27 Sep 2021 11:15:20 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-25009c74, build_duration_seconds:21220]
=> [automation] update elastic stack version for testing 7.16.0-25009c74

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 29 Sep 2021 05:24:06 GMT, release_branch:7.x, prefix:, end_time:Wed, 29 Sep 2021 11:17:22 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-f67263fd, build_duration_seconds:21196]
=> [automation] update elastic stack version for testing 7.16.0-f67263fd

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 30 Sep 2021 00:15:06 GMT, release_branch:7.15, prefix:, end_time:Thu, 30 Sep 2021 06:33:47 GMT, manifest_version:2.0.0, version:7.15.1-SNAPSHOT, branch:7.15, build_id:7.15.1-a28dd8b0, build_duration_seconds:22721]
=> [automation] update elastic stack version for testing 7.15.1-a28dd8b0

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 30 Sep 2021 05:14:08 GMT, release_branch:7.x, prefix:, end_time:Thu, 30 Sep 2021 11:20:18 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-806be5a9, build_duration_seconds:21970]
=> [automation] update elastic stack version for testing 7.16.0-806be5a9

CHANGELOG.next.asciidoc, filebeat/docs/fields.asciidoc, x-pack/filebeat/module/coredns/_meta/fields.yml, x-pack/filebeat/module/coredns/fields.go, x-pack/filebeat/module/coredns/log/ingest/pipeline-entry.yml, x-pack/filebeat/module/coredns/log/test/coredns-json.log-expected.json, x-pack/filebeat/module/coredns/log/test/coredns.log-expected.json
This removes the non-ECS fields from the coredns module.
Listed in  #19039.
`TESTING_FILEBEAT_MODULES=coredns MODULES_PATH=module mage -v pythonIntegTest`
- Relates #19039
N/A
N/A
=> Remove deprecated coredns fields for 8.0

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Sun, 3 Oct 2021 05:24:19 GMT, release_branch:7.x, prefix:, end_time:Sun, 3 Oct 2021 11:11:48 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-76e5f71e, build_duration_seconds:20849]
=> [automation] update elastic stack version for testing 7.16.0-76e5f71e

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Sat, 2 Oct 2021 00:15:07 GMT, release_branch:7.15, prefix:, end_time:Sat, 2 Oct 2021 06:05:12 GMT, manifest_version:2.0.0, version:7.15.1-SNAPSHOT, branch:7.15, build_id:7.15.1-3517e2e9, build_duration_seconds:21005]
=> [automation] update elastic stack version for testing 7.15.1-3517e2e9

x-pack/filebeat/input/awscloudwatch/input.go
This fix is supposed to be a part of https://github.com/elastic/beats/pull/27007 to fix the hardcoded "cloudwatchlogs" service name for aws-cloudwatch input.
=> Remove overwriting AWS config with endpoint in aws-cloudwatch input

.mergify.yml
Remove `backport-skip` label when the backport labels have been added.
Keep tidy the GItHub labels
https://github.com/v1v/poc-bump-automation/pull/13
=> [mergify] remove backport-skip if added a backport label

deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml, x-pack/elastic-agent/pkg/composable/providers/kubernetes/config.go, x-pack/elastic-agent/pkg/composable/providers/kubernetes/kubernetes.go, x-pack/elastic-agent/pkg/composable/providers/kubernetes/node.go, x-pack/elastic-agent/pkg/composable/providers/kubernetes/pod.go, x-pack/elastic-agent/pkg/composable/providers/kubernetes/service.go
Small followup fix related to https://github.com/elastic/beats/pull/27691:
- Fix proposed manifest's condition from `kubernetes.pod.labels.app == redis` to ``kubernetes.labels.app == redis`
- Port `IncludeAnnotations`
- Handle start/stop of watchers properly
Using the following redis Pod:
```
apiVersion: v1
kind: Pod
metadata:
name: redis
labels:
role: main
app: redis
annotations:
level: production
spec:
hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet
containers:
- name: redis
image: redis:latest
ports:
- name: web
containerPort: 6379
protocol: TCP
```
Test the following scenarios:
1.  Check Pod's annotation is added as metadata
```
providers.kubernetes:
scope: node
kube_config: /Users/chrismark/.kube/config
node: "kind-control-plane"
cleanup_timeout: 360s
include_annotations: …
```
=> Port IncludeAnnotations setting to Agent and small manifest fix

x-pack/metricbeat/module/airflow/statsd/data_test.go
- Bug
Fix flaky test for airflow metricset
Flaky test consume developers time waiting for CI to be green.
-
=> use 0s ttl

libbeat/docs/upgrading.asciidoc
Renames _Fleet User Guide_ to _Fleet and Elastic Agent Guide_
Required because the book is being renamed.
- Relates https://github.com/elastic/observability-docs/issues/1104
=> Rename Fleet User Guide

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 5 Oct 2021 17:22:39 GMT, release_branch:6.8, prefix:, end_time:Tue, 5 Oct 2021 22:14:33 GMT, manifest_version:2.0.0, version:6.8.20-SNAPSHOT, branch:6.8, build_id:6.8.20-431ef06e, build_duration_seconds:17514]
=> [automation] update elastic stack version for testing 6.8.20-431ef06e

x-pack/elastic-agent/CHANGELOG.next.asciidoc, x-pack/elastic-agent/pkg/core/monitoring/server/process.go, x-pack/elastic-agent/pkg/core/monitoring/server/process_linux_test.go, x-pack/elastic-agent/pkg/core/monitoring/server/process_test.go, x-pack/elastic-agent/pkg/core/monitoring/server/server.go
proxy requests to the exposed subprocess for gathering metrics.
in order for libbeat services, such as apm-server, to be easily scraped and displayed in the stack monitoring ui, both the `/stats` and `/state` endpoints are necessary. exposing both of these makes it easy to use the `beat` module in metricbeat, as well.
- start the elastic-agent
- verify that requests to a subprocess are proxied to its metrics endpoints:
```
[
"beat",
"hostname",
"name",
"uuid",
"version"
]
[
"beat",
"host",
"management",
"module",
"output",
"outputs",
"queue",
"service"
]
[
"beat",
"libbeat",
"metricbeat",
"system"
]
```
=> [elastic-agent] proxy requests to subprocesses to their metrics endpoints

CHANGELOG.next.asciidoc, filebeat/input/winlog/input.go, winlogbeat/beater/eventlogger.go, winlogbeat/eventlog/errors_unix.go, winlogbeat/eventlog/errors_windows.go, winlogbeat/eventlog/eventlog.go, winlogbeat/sys/wineventlog/syscall_windows.go
- Added a retry mechanism to winlog/input and winlogbeat to reopen a
session to Windows Event Log when certain error conditions are encountered.
- This applies when opening a session to Windows Event Log and
also when reading from Windows Event Log.
- Filebeat/winlogbeat should be able to tolerate disruptions with the Windows Event Log service without having to be manually restarted by the user.
- Run filebeat (with winlog input) or winlogbeat on Windows system. The channel subscription doesn't
matter, it can be `Security` or other channels. Make sure debug logging …
=> [Winlogbeat] Tolerate faults when Windows Event Log session is interrupted

CHANGELOG.next.asciidoc, filebeat/beater/filebeat.go, filebeat/fileset/modules.go, libbeat/beat/beat.go, libbeat/cmd/instance/beat.go, libbeat/cmd/setup.go, libbeat/docs/command-reference.asciidoc, libbeat/ml-importer/importer.go
This PR adds a check before loading ML assets to make sure, Beats are loading those to ES 7.x. If someone tries to load ML into ES 8.x, they are told to use the Machine Learning UI in Kibana.
This PR is opened against 7.x.
This work is part of the forward compatibility effort. We have to make sure users rely on the better solution for loading ML in Kibana, instead of the deprecated `setup --machine-learning` subcommand.
~~- [ ] I have added tests that prove my fix is effective or that my feature works~~ it will come in a follow up PR
=> Do not load ML jobs to 8.x from 7.x releases

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Sun, 31 Oct 2021 17:30:04 GMT, release_branch:7.15, prefix:, end_time:Sun, 31 Oct 2021 23:30:29 GMT, manifest_version:2.0.0, version:7.15.2-SNAPSHOT, branch:7.15, build_id:7.15.2-fecae5f4, build_duration_seconds:21625]
=> [automation] update elastic stack version for testing 7.15.2-fecae5f4

CHANGELOG.asciidoc, libbeat/docs/release.asciidoc
Part 8.0.0-beta1 release. Needs to forward-ported to `master`.
=> No changelog for 8.0.0-beta1

heartbeat/docs/monitors/monitor-browser.asciidoc, heartbeat/docs/monitors/monitor-http.asciidoc
Fixes two docs formatting bugs:
1. Use ASCIIDOC link syntax instead of markdown in monitor-http.asciidoc
2. Remove extra brackets in monitor-browser.asciidoc
=> [heartbeat][docs] Fix markdown bugs in browser/http docs

x-pack/elastic-agent/pkg/remote/client.go, x-pack/elastic-agent/pkg/remote/client_test.go
Adds the "X-Request-ID" header to HTTP transactions with Fleet Server. 
This allows tracking of the transaction through the cloud proxy and into Fleet Server.  The request Id can be aligned across log entries.
- [x ] My code follows the style guidelines of this project
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have added tests that prove my fix is effective or that my feature works
=> Add request id to HTTP transactions to allow tracking.

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 1 Nov 2021 00:15:49 GMT, release_branch:7.15, prefix:, end_time:Mon, 1 Nov 2021 06:32:25 GMT, manifest_version:2.0.0, version:7.15.2-SNAPSHOT, branch:7.15, build_id:7.15.2-5325c15b, build_duration_seconds:22596]
=> [automation] update elastic stack version for testing 7.15.2-5325c15b

.ci/packaging.groovy, Jenkinsfile
This PR comments out the execution of the E2E tests for Fleet at the CI pipelines level. For that we are logging a message instead of the exeuction.
After recent changes in Kibana, Package Registry and Elastic Package, we are forced to disable the E2E tests as they are always going to fail because the stack is not going to start, causing the test scenarios to drastically fail.
I will be adding links to this list once I capture all parts in place (Kibana, package registry, elastic-package, E2E tests...)
-
=> chore(ci): disable E2E tests in Beats

CHANGELOG.next.asciidoc, libbeat/processors/fingerprint/docs/fingerprint.asciidoc, libbeat/processors/fingerprint/errors.go, libbeat/processors/fingerprint/fingerprint.go, libbeat/processors/fingerprint/fingerprint_test.go
Use `beat.Event.GetValue` so that @timestamp and @metadata are accessible to
be hashed.
Also clarify the documentation to explain how the value being hashed is constructed.
Fixes #28683
Allows for the `@timestamp` value to be incorporated into fingerprints.
- Closes #28683
=> [libbeat] Allow fingerprint processor to read @timestamp

CHANGELOG.next.asciidoc, x-pack/heartbeat/monitors/browser/synthexec/synthexec.go
This change causes heartbeat to no longer log parameter values, instead
interpolating an opaque string.
Fixes #28771
We now create logs like:
```
2021-11-02T17:25:27.804-0500    INFO    synthexec/synthexec.go:148      Running command: /tmp/elastic-synthetics-unzip-714880603/node_modules/.bin/elastic-synthetics /tmp/elastic-synthetics-unzip-714880603/node_modules/.bin/elastic-synthetics /tmp/elastic-synthetics-unzip-714880603 --screenshots on --rich-events --params "{1 hidden params}" in directory: '/tmp/elastic-synthetics-unzip-714880603'
```
Tested with https://github.com/elastic/synthetics-demo/blob/main/heartbeat/monitors.d/todos-zipurl.yml
=> [Heartbeat] Stop logging sensitive params

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 2 Nov 2021 00:16:04 GMT, release_branch:7.15, prefix:, end_time:Tue, 2 Nov 2021 06:07:31 GMT, manifest_version:2.0.0, version:7.15.2-SNAPSHOT, branch:7.15, build_id:7.15.2-54cb1d1b, build_duration_seconds:21087]
=> [automation] update elastic stack version for testing 7.15.2-54cb1d1b

libbeat/common/kubernetes/metadata/pod.go
This PR removes a not needed comment from libbeat  GenerateK8s method which enriches an event with kubernetes metadata
=> Fixup to remove uneeded 8.0 comment from GenerateK8s metadata

libbeat/dashboards/modify_json.go
This PR converts attributes not only on the top level, but in embeddedConfig objects as well.
Without this, we cannot load all dashboards to Kibana since beta1.
Closes https://github.com/elastic/beats/issues/28773
=> Convert required fields to string in embeddedConfig recursively

CHANGELOG.next.asciidoc, filebeat/_meta/config/filebeat.inputs.reference.yml.tmpl, filebeat/_meta/config/filebeat.inputs.yml.tmpl, filebeat/docs/inputs/input-log.asciidoc, filebeat/filebeat.reference.yml, filebeat/filebeat.yml, filebeat/input/log/input.go, filebeat/input/stdin/input.go, x-pack/filebeat/filebeat.reference.yml, x-pack/filebeat/filebeat.yml
This PR marks the log input as deprecated. As we are not in a hurry to remove the input because it possibly impacts lots of users, I omitted the version to remove from the log message. Our goal is to let users who are satisfied with the input use it as long as they would like to. However, if it is no longer working or found any issues in the input, we are asking them to move to filestream input.
Everyone should move to filestream input because it is a great improvement over the old log input.
=> Deprecate log input in favour of filestream

filebeat/beater/filebeat.go, filebeat/fileset/modules.go
Since #27526 and #27762, Filebeat will have all filesets disabled by default. To prevent user confusion, a warning message to alert the user of a configured module without any enabled filesets was added. However, due to Filebeat internals, this message will only appear for modules configured from the command-line (--modules flag).
This updates the code to ensure it works also for modules configured via modules.d directory and turns the warning into an error that prevents startup.
Helps users figure out configuration problems earlier.
- ~~[ ] I have added an entry …
=> Filebeat: Error on startup for unconfigured module

auditbeat/auditbeat.reference.yml, filebeat/filebeat.reference.yml, heartbeat/heartbeat.reference.yml, journalbeat/journalbeat.reference.yml, libbeat/_meta/config/logging.reference.yml.tmpl, libbeat/docs/loggingconfig.asciidoc, metricbeat/metricbeat.reference.yml, packetbeat/packetbeat.reference.yml, winlogbeat/winlogbeat.reference.yml, x-pack/auditbeat/auditbeat.reference.yml, x-pack/filebeat/filebeat.reference.yml, x-pack/functionbeat/functionbeat.reference.yml, x-pack/heartbeat/heartbeat.reference.yml, x-pack/metricbeat/metricbeat.reference.yml, x-pack/osquerybeat/osquerybeat.reference.yml, x-pack/packetbeat/packetbeat.reference.yml, x-pack/winlogbeat/winlogbeat.reference.yml
Mark `logging.ecs` and `logging.json` as deprecated for the `v7.16.0` release.
These attributes will no longer be used in 8.0.
These settings will be removed for 8.0 as part of the work to get all components producing ECS logs by default.
The PR is https://github.com/elastic/beats/pull/28573
- [] ~~My code follows the style guidelines of this project~~
- [] ~~I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~
- Relates #15544
=> Mark logging.ecs and json as deprecated

x-pack/osquerybeat/beater/osquery_runner.go
Fixes the oquery flags update defect.
The issue is reproducible with the following steps:
1. Apply bad config flag
```
{
"options": {
"disable_events": false,
"enable_file_events": true
"enable_ntfs_publisher": true
}
}
```
2. Osquery stops with error
```
[elastic_agent.osquerybeat][error] process exited with error: ERROR: unknown command line flag 'enable_ntfs_publisher': exit status 1
```
3. Remove ```enable_ntfs_publisher``` option.
4. The osquery uses old flags to (visible in debug log) and fails.
Expected result, the new flags are used and osquery becomes usable (can issue ad-hoc queries for example)
This is a minimal change to fix this for 7.16 next RC is on 11/10.
If I get time before 11/10, will revisit the osquery runner one more time.
If not will leave it for 8.0 to improve. …
=> Osquerybeat: Fix restart flags after previously bad config

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 4 Nov 2021 17:16:56 GMT, release_branch:7.15, prefix:, end_time:Thu, 4 Nov 2021 23:18:51 GMT, manifest_version:2.0.0, version:7.15.2-SNAPSHOT, branch:7.15, build_id:7.15.2-e203d324, build_duration_seconds:21715]
=> [automation] update elastic stack version for testing 7.15.2-e203d324

NOTICE.txt, go.mod, go.sum
Version 1.12.0 seems to have changed, producing a verification error.
``````
verifying github.com/google/flatbuffers@v1.12.0: checksum mismatch
downloaded: h1:N8EguYFm2wwdpoNcpchQY0tPs85vOJkboFb2dPxmixo=
go.sum:     h1:/PtAHvnBY4Kqnx/xCQ3OIV9uYcSFGScBsWI3Oogeh6w=
SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
``````
As 1.12.1 is available, upgrading the module.
Prevent an error when building `x-pack/metricbeat`
Run `mage build` in `x-pack/metricbeat`
-
=> [Metricbeat] upgrade flatbuffers to 1.12.1

CHANGELOG-developer.next.asciidoc, docs/devguide/creating-beat-from-metricbeat.asciidoc, docs/devguide/newbeat.asciidoc, generator/common/beatgen/beatgen.go, libbeat/docs/communitybeats.asciidoc
This PR adds a warning to users who are generating their own Beats. From 8.0.0, it is not going to be supported.
To manage users' expectations.
=> Deprecate generating custom Beats

.ci/packaging.groovy, Jenkinsfile
This reverts commit a83e883fbde46de14013b9fb7bbdedd53d1bbad3.
We think it's safe to enable the E2E tests again, with the same schedule than in the past.
- Reverts #28715
=> Revert "chore(ci): disable E2E tests in Beats (#28715)"

Jenkinsfile
This PR does two things:
1. it forces the CMD command for `mage packageSystemTests` to return 0 even though an error occurred.
1. it uploads to Google only when the list of files has entries.
For the return status, we are preventing the catchError pipeline block to continue on failures. And for the google upload step, protected by an IF clause, we are preventing trying to upload when there aren't files to upload.
- Relates #27295
=> chore: upload files to Google Storage when they exist

x-pack/osquerybeat/internal/osqd/args.go, x-pack/osquerybeat/internal/osqdcli/client.go, x-pack/osquerybeat/internal/osqdcli/retry.go, x-pack/osquerybeat/internal/osqdcli/retry_test.go
Fixes code logic in osquery connect with retries.
The error not correctly propagated from this line: 
https://github.com/elastic/beats/blame/20d637e1afc7104e7a1f24532cd491e59ad6b245/x-pack/osquerybeat/internal/osqdcli/client.go#L138
when the context was cancelled while waiting next retry.
This doesn't cause an issue, but is not the correct behavior and could be potentially be misleading when logging 
```
osquery client is connected
```
when the connection attempt was cancelled via context.
This PR also updates the config refresh interval from 10 seconds to 60 seconds. 
This is the interval how often ```osqueryd``` polls our configuration plugin (implemented in osquerybeat) over local RPC (osquery domain socket or pipe). The reasoning for that is explained in the added comment:
```
// …
```
=> Osquerybeat: Improve osquery client connect code. Update config_refresh to 60 seconds.

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Sun, 7 Nov 2021 17:25:50 GMT, release_branch:7.15, prefix:, end_time:Sun, 7 Nov 2021 23:22:40 GMT, manifest_version:2.0.0, version:7.15.2-SNAPSHOT, branch:7.15, build_id:7.15.2-616feb9e, build_duration_seconds:21410]
=> [automation] update elastic stack version for testing 7.15.2-616feb9e

heartbeat/hbtest/hbtestutil.go, heartbeat/monitors/active/http/http_test.go, heartbeat/monitors/active/http/simple_transp.go
Resolves https://github.com/elastic/beats/issues/28303
This patch will cause Heartbeat to decode `gzip`-encoded content when the `Content-Encoding` header specifies `gzip` as its value.
On the linked issue there is discussion about always detecting if content is `gzip` and decoding it automatically. This change does not yet account for that.
There have been confusing results for customers where the content indexed into Elasticsearch does not correlate to what they expect to see. Almost never should Heartbeat be shipping `gzip`-encoded content for search/storage.
If users want to index the response body, they'll need this feature to decode it if it's compressed. Today, there's no way to decode compressed bodies because of this bug.
The linked issue has an associated SDH that includes …
=> [Heartbeat] Decode gzip content when content encoding header is specified

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 8 Nov 2021 00:15:07 GMT, release_branch:7.15, prefix:, end_time:Mon, 8 Nov 2021 16:28:02 GMT, manifest_version:2.0.0, version:7.15.2-SNAPSHOT, branch:7.15, build_id:7.15.2-dab700a8, build_duration_seconds:58375]
=> [automation] update elastic stack version for testing 7.15.2-dab700a8

Jenkinsfile
It fixes how array lengths are calculated when retrieving the files to be uploaded to GC storage.
Intead of using `.length()` as a method, which is incorrect, it uses `.length` as an attribute. As an alternative we could use `.size()` method.
We are seeing this failure in the pipeline:
```
groovy.lang.MissingMethodException: No signature of method: [Lorg.jenkinsci.plugins.pipeline.utility.steps.fs.FileWrapper;.length() is applicable for argument types: () values: []
Possible solutions: last(), init(), getAt(groovy.lang.EmptyRange), getAt(java.util.Collection), getAt(groovy.lang.Range), getAt(java.lang.Integer)
```
- Caused by #28836
=> fix: use array length properly

README.md
The PR removes broken reference to building your own Beat from the Contributing section of the README.md. It was missing from my previous PR that removed Beat generator code and reference. If anyone wants see the docs now, they have to set the version to 7.16.
Clean up.
=> Remove reference to Beat generators from README.md

CHANGELOG.next.asciidoc, dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl, dev-tools/packaging/templates/docker/Dockerfile.tmpl
We currently install cups mistakenly, it's not needed to support
chromium browsers.
=> [heartbeat][agent] Remove unnecessary cups dependency

CHANGELOG.next.asciidoc, x-pack/auditbeat/tracing/decoder.go
Previously the copy for the raw case converted the unsafe pointer to a concrete
array of 2048 bytes due to an unnecessary pointer dereference. This invalidly
spans beyond the end of the struct allocation. This is identified either with a
build using the race detector or with `-gcflags=all=-d=checkptr`.
This removes invalid unsafe behaviour.
N/A
Standard testing.
- Relates #17165
N/A
N/A
N/A
=> x-pack/auditbeat/tracing: fix invalid span in array punning

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 9 Nov 2021 17:16:42 GMT, release_branch:7.15, prefix:, end_time:Wed, 10 Nov 2021 00:52:00 GMT, manifest_version:2.0.0, version:7.15.2-SNAPSHOT, branch:7.15, build_id:7.15.2-f9b0a84b, build_duration_seconds:27318]
=> [automation] update elastic stack version for testing 7.15.2-f9b0a84b

.ci/jobs/beats.yml
Restricts the branches that we display in the Jenkins UI.
Closes https://github.com/elastic/beats/issues/28867
=> Limit MBP branch discovery

metricbeat/docker-compose.yml, metricbeat/module/logstash/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
Part of 7.15.2 release. To merge once the release is available (and the PR is green).
Automation failed, created manually. See https://github.com/elastic/beats/pull/28342 as a reference.
=> chore: Update test enviroments after 7.15.2 release

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Sun, 14 Nov 2021 17:25:09 GMT, release_branch:7.15, prefix:, end_time:Sun, 14 Nov 2021 23:22:39 GMT, manifest_version:2.0.0, version:7.15.3-SNAPSHOT, branch:7.15, build_id:7.15.3-b30acc1a, build_duration_seconds:21450]
=> [automation] update elastic stack version for testing 7.15.3-b30acc1a

CHANGELOG.next.asciidoc, x-pack/metricbeat/module/aws/rds/manifest.yml
Bug
use the proper `to` value `aws.rds.write.iops` instead of `aws.rds.write_iops` for rename processor in rds metricset
Fields were renamed in https://github.com/elastic/beats/pull/28350.
A typo in the rename processor for `aws.rds.write.iops` slipped through CR.
The processor is ingesting the data in the wrong field.
-
=> typo in aws.rds.write_iops field in processor

CHANGELOG-developer.next.asciidoc, libbeat/common/fmtstr/formatevents_test.go, libbeat/common/fmtstr/formattimestamp_test.go
Some timestamp formatting tests were failing because the input time
was set in the local timezone, which affects the final value when
formatting as string.
Now all imput values are set to UTC, so there will be no difference
between the set time and the final string formatting.
It fixes some flaky tests on `libbeat/common/fmtstr`
All unit tests pass regardless of the machine's timezone
Run the unit tests on `libbeat/common/fmtstr` on a machine whose timezone is offset from UTC, all tests …
=> Fix failing tests on libbeat/common/fmtstr

CHANGELOG.next.asciidoc, auditbeat/auditbeat.reference.yml, filebeat/filebeat.reference.yml, heartbeat/heartbeat.reference.yml, journalbeat/journalbeat.reference.yml, libbeat/_meta/config/http.reference.yml.tmpl, libbeat/api/routes.go, libbeat/cmd/instance/beat.go, libbeat/docs/http-endpoint.asciidoc, libbeat/tests/system/test_http.py, libbeat/tests/system/test_http_pprof.py, metricbeat/metricbeat.reference.yml, packetbeat/packetbeat.reference.yml, winlogbeat/winlogbeat.reference.yml, x-pack/auditbeat/auditbeat.reference.yml, x-pack/filebeat/filebeat.reference.yml, x-pack/functionbeat/functionbeat.reference.yml, x-pack/heartbeat/heartbeat.reference.yml, x-pack/metricbeat/metricbeat.reference.yml, x-pack/osquerybeat/osquerybeat.reference.yml, x-pack/packetbeat/packetbeat.reference.yml, x-pack/winlogbeat/winlogbeat.reference.yml
Add a config option to attach `/debug/pprof/` endpoints to the stats handler enabled via `http.enabled`.
Currently pprof endpoints are only enabled when the `-httpprof` flag is used; these endpoints are bound to a **different socket** then the stats endpoint. We would like to serve these endpoints on the same socket in order to unify calls from external processes.
Enable http and pprof when running a beat via `-E http.enabled=true -E http.pprof.enabled=true`.
Check the `/debug/pprof/` endpoint via curl
- Relates #21965
=> Add config option to attach pprof endpoints to http socket

CHANGELOG.next.asciidoc, docs/devguide/fields-yml.asciidoc, libbeat/mapping/field.go, libbeat/mapping/field_test.go, libbeat/template/load_test.go, libbeat/template/processor.go, libbeat/template/processor_test.go, libbeat/template/template.go, libbeat/template/template_test.go, libbeat/tests/system/template/template.go
This adds support for defining custom text analyzers in fields.yml files. For example:
```
- key: powershell
title: PowerShell module
description: >
These are the event fields specific to the module for the Microsoft-Windows-PowerShell/Operational and Windows PowerShell logs.
release: beta
analyzer:
powershell_script_analyzer:
type: pattern
pattern: "[\\W&&[^-]]+"
fields:
...
```
Not being able to define custom analyzers is a blocker for processing some documents containing syntactically meaningful non-standard token structures (for example captured script text as shown above).
No specific recommendations.
Running `go test` in the relevant packages tests this change.
- Closes #28540
- Relates #28483
- Relates …
=> libbeat: add support for defining analyzers in-line in fields.yml files

heartbeat/docs/monitors/monitor-browser.asciidoc
Browser monitors are in beta, but this page doesn't indicate that.
=> Add beta label to browser monitors

CHANGELOG.next.asciidoc, libbeat/cmd/instance/beat.go, libbeat/cmd/instance/beat_integration_test.go, libbeat/cmd/instance/testdata/mockbeat.yml, libbeat/mock/mockbeat.go
Initialise beat early so all required information for monitoring and
state endpoint are available when the state registry is populated.
Fixes #27755
On any beat, enable the "HTTP endpoint" by adding this at the end of your beat yaml:
```yml
http:
enabled: true
host: 0.0.0.0
port: 5066
```
Start your beat and make a request to `5066/state`:
```sh
curl 127.0.0.1:5066/state | jq
```
- Closes #27755
=> Initialise beat early

.mergify.yml
Filter those PRs that are still open
Sometimes mergify evaluates some rules and apply the notification. Let's avoid this
=> [mergify] notify the backport policy for open PRs

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 16 Nov 2021 17:10:55 GMT, release_branch:6.8, prefix:, end_time:Tue, 16 Nov 2021 21:44:12 GMT, manifest_version:2.0.0, version:6.8.21-SNAPSHOT, branch:6.8, build_id:6.8.21-89aea7c7, build_duration_seconds:16397]
=> [automation] update elastic stack version for testing 6.8.21-89aea7c7

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 17 Nov 2021 17:11:34 GMT, release_branch:6.8, prefix:, end_time:Wed, 17 Nov 2021 22:00:41 GMT, manifest_version:2.0.0, version:6.8.21-SNAPSHOT, branch:6.8, build_id:6.8.21-40a8ccf4, build_duration_seconds:17347]
=> [automation] update elastic stack version for testing 6.8.21-40a8ccf4

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 17 Nov 2021 17:22:18 GMT, release_branch:7.15, prefix:, end_time:Thu, 18 Nov 2021 00:01:50 GMT, manifest_version:2.0.0, version:7.15.3-SNAPSHOT, branch:7.15, build_id:7.15.3-a2dc0d3c, build_duration_seconds:23972]
=> [automation] update elastic stack version for testing 7.15.3-a2dc0d3c

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 18 Nov 2021 17:14:25 GMT, release_branch:7.15, prefix:, end_time:Thu, 18 Nov 2021 23:13:33 GMT, manifest_version:2.0.0, version:7.15.3-SNAPSHOT, branch:7.15, build_id:7.15.3-d16f4bc8, build_duration_seconds:21548]
=> [automation] update elastic stack version for testing 7.15.3-d16f4bc8

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 18 Nov 2021 17:11:09 GMT, release_branch:6.8, prefix:, end_time:Thu, 18 Nov 2021 22:00:26 GMT, manifest_version:2.0.0, version:6.8.21-SNAPSHOT, branch:6.8, build_id:6.8.21-ff3c5676, build_duration_seconds:17357]
=> [automation] update elastic stack version for testing 6.8.21-ff3c5676

CHANGELOG.next.asciidoc, x-pack/winlogbeat/module/security/config/winlogbeat-security.js
- According to MS documentation examples AccessList contains a space
separated list of access masks and AccessMask contains an integer.
- Retain old behavior if AccessMask contains a space separated
list of access masks
- Add new code to parse AccessList as space separated list of
access masks
- Add new code to parse AccessMask if an integer
Sometimes AccessList and AccessMask were parsed incorrectly
``` bash
cd x-pack\winlogbeat\module\security\test
go test -v
```
- Relates elastic/integrations#2156
=> [Winlogbeat] Fix AccessList & AccessMask processing in security data_stream

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Sun, 21 Nov 2021 17:11:20 GMT, release_branch:6.8, prefix:, end_time:Sun, 21 Nov 2021 21:49:24 GMT, manifest_version:2.0.0, version:6.8.21-SNAPSHOT, branch:6.8, build_id:6.8.21-92088553, build_duration_seconds:16684]
=> [automation] update elastic stack version for testing 6.8.21-92088553

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Sun, 21 Nov 2021 17:22:39 GMT, release_branch:7.15, prefix:, end_time:Sun, 21 Nov 2021 23:37:11 GMT, manifest_version:2.0.0, version:7.15.3-SNAPSHOT, branch:7.15, build_id:7.15.3-2ab3d0ac, build_duration_seconds:22472]
=> [automation] update elastic stack version for testing 7.15.3-2ab3d0ac

CHANGELOG.next.asciidoc, filebeat/_meta/config/filebeat.inputs.reference.yml.tmpl, filebeat/filebeat.reference.yml, libbeat/reader/readfile/line_terminator.go, x-pack/filebeat/filebeat.reference.yml
Add null (`\u0000`) as a valid line terminator called `null_terminator`.
Closes: #27061
1. Download [null-terminated-log.txt](https://github.com/elastic/beats/files/7547789/null-terminated-log.txt).
2. Configure filebeat to use filestream and read the file you downloaded.
3. Start filebeat.
4. Check that the log file as been correctly ingested.
- Closes 27061
=> Add null (`\u0000`) as a valid line terminator

libbeat/cmd/instance/metrics/metrics.go, metricbeat/module/system/system.go
This fixes yet another issue with how `hostfs` is being set under agent. Agent needs its own logic for setting the environment variables used by upstream libraries for an alternate hostfs--the user needs to be able to change these values arbitrarily, and we need to deal with the fact that this is a case where per-metricset settings are trying to set a global variable, so we need logic to deal with the fact that not every metricset will want to set `hostfs`. I've tested this, and it works, and I'm not sure we can do much better without making breaking changes in various parts of metricbeat.
Without this, user-supplied `hostfs` settings will change some metricsets, and not others.
This is a nightmare to test. Anything that requires agent and docker is just a pain. Here's some steps using …
=> Fix environmental var setup under agent

x-pack/metricbeat/module/aws/kinesis/kinesis_integration_test.go
This PR is to remove TestFetch from `kinesis` metricset because this metricset is directly using `cloudwatch` as an input and is already been tested in `cloudwatch` metricset.
=> Remove TestFetch from kinesis metricset

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 22 Nov 2021 17:14:15 GMT, release_branch:7.15, prefix:, end_time:Mon, 22 Nov 2021 23:30:29 GMT, manifest_version:2.0.0, version:7.15.3-SNAPSHOT, branch:7.15, build_id:7.15.3-4c145d2b, build_duration_seconds:22574]
=> [automation] update elastic stack version for testing 7.15.3-4c145d2b

heartbeat/Jenkinsfile.yml
remove w2008 in the CI for heartbeat
- Win2k8 was already old when heartbeat was created
- It's quite unusual to put heartbeat on a 'legacy' machine
- We've never heard of anyone using heartbeat+win2k8
- The win2k8 tests are flaky
=> heartbeat: remove w2008 in the CI

libbeat/docs/template-config.asciidoc, libbeat/idxmgmt/std.go, libbeat/template/config.go, libbeat/tests/system/config/mockbeat.yml.j2, libbeat/tests/system/test_template.py
If JSON template is configured for loading, Filebeat should still default to legacy index template formats to avoid breaking existing template configurations. It also adds a warning to let users know that they have to migrate from legacy format.
Minimizes the breaking changes of moving from legacy templates to composable templates.
=> Default to legacy format if JSON template is loaded

filebeat/_meta/config/filebeat.global.reference.yml.tmpl, filebeat/filebeat.reference.yml, x-pack/filebeat/filebeat.reference.yml
As per https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-configuration-reloading.html#load-module-config, the default value of `filebeat.config.modules.enabled` is `true`. 
Having it as `false` in `filebeat.reference.yml` is confusing.
=> Change "filebeat.config.modules.enabled" to "true"

CHANGELOG.next.asciidoc, metricbeat/helper/server/udp/udp.go, x-pack/metricbeat/module/statsd/server/server.go
Enhancement
It adds `Host()` implementation for statsd metricset
`Host()` returns the hostname or other module specific value that identifies a specific host or service instance from which to collect metrics.
In the `BaseMetricSet` implementation it uses the `hosts` field from config of the metricset.
`statsd` rather use `host` and `port`,  so a different implementation is needed to report relevant information
- 
```
{"log.level":"debug","@timestamp":"2021-11-23T18:44:13.426+0100","log.logger":"module","log.origin":{"file.name":"module/wrapper.go","file.line":189},"messag …
```
=> override host on statsd metricset

.mergify.yml
Notify only if the PR is still open
Avoid notifications when PRs are closed or merged. Sometimes the reevaluation of the mergify rules can happen, no idea how, and then notifications are sent.
=> [mergify]: notify conflicts in PRs that are still open

x-pack/metricbeat/module/aws/billing/billing_integration_test.go, x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_integration_test.go, x-pack/metricbeat/module/aws/ec2/ec2_integration_test.go, x-pack/metricbeat/module/aws/kinesis/kinesis_integration_test.go, x-pack/metricbeat/module/aws/rds/rds_integration_test.go, x-pack/metricbeat/module/aws/sqs/sqs_integration_test.go
This PR is to re-enable the tests in AWS after https://github.com/elastic/beats/pull/28528 got merged.
=> Re-enable tests in aws module

CHANGELOG.next.asciidoc, x-pack/metricbeat/module/aws/cloudwatch/metadata/rds/rds.go
This PR is to fix rds identifier overwriting each other in cloudwatch metricset. 
After fixing the bug:
Before fixing the bug:
=> Fix rds metadata in cloudwatch metricset

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 24 Nov 2021 17:22:58 GMT, release_branch:7.15, prefix:, end_time:Wed, 24 Nov 2021 23:40:01 GMT, manifest_version:2.0.0, version:7.15.3-SNAPSHOT, branch:7.15, build_id:7.15.3-ba00df8f, build_duration_seconds:22623]
=> [automation] update elastic stack version for testing 7.15.3-ba00df8f

journalbeat/docs/page_header.html
Updating banner for 7.15 because it is the last version of Journalbeat that will be published.
=> Indicate in banner that Journalbeat has been removed in 7.16

.github/workflows/macos-build.yml
This is workflow file for builds on macos on github.
It adds workflow file for builds on macos on github.
It should be installed in order to run it from PRs.
[PR-28906](https://github.com/elastic/beats/pull/28906)
=> Added workflow file for builds with macos

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 25 Nov 2021 17:11:02 GMT, release_branch:6.8, prefix:, end_time:Thu, 25 Nov 2021 21:26:38 GMT, manifest_version:2.0.0, version:6.8.21-SNAPSHOT, branch:6.8, build_id:6.8.21-f133bac8, build_duration_seconds:15336]
=> [automation] update elastic stack version for testing 6.8.21-f133bac8

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 25 Nov 2021 17:16:20 GMT, release_branch:7.15, prefix:, end_time:Thu, 25 Nov 2021 23:06:05 GMT, manifest_version:2.0.0, version:7.15.3-SNAPSHOT, branch:7.15, build_id:7.15.3-57b973bf, build_duration_seconds:20985]
=> [automation] update elastic stack version for testing 7.15.3-57b973bf

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Sun, 28 Nov 2021 17:14:57 GMT, release_branch:7.15, prefix:, end_time:Sun, 28 Nov 2021 23:15:11 GMT, manifest_version:2.0.0, version:7.15.3-SNAPSHOT, branch:7.15, build_id:7.15.3-e51e78d3, build_duration_seconds:21614]
=> [automation] update elastic stack version for testing 7.15.3-e51e78d3

CHANGELOG.next.asciidoc, libbeat/processors/actions/decode_json_fields.go, libbeat/processors/actions/decode_json_fields_test.go
When the `decode_json_fields` processor encountered an error while
decoding the JSON it was not always respecting the `add_error_key`
configuration.
This commit fixes it.
Errors from `decode_json_fields` processor are now clearly reported
Add the following to you filebeat configuration:
```yaml
processors:
- decode_json_fields:
fields: ["my_json_key"]
process_array: false
max_depth: 1
target: "json_object"
add_error_key: true
```
Make sure the `my_json_key` field of the event is an invalid JSON.
=> Fix `decode_json_fields` processor to always add error key

docs/devguide/create-metricset.asciidoc, docs/devguide/generator-support-note.asciidoc, docs/devguide/modules-dev-guide.asciidoc
Adds note to Beats Developer Guide in places where we talk about code for generating Beats, metricsets, modules, or filesets.
Questions:
The beats generator is old and will be deprecated in 8.0
- Closes #28426
=> Add note that there is no warranty or support for generator code

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 29 Nov 2021 17:15:48 GMT, release_branch:6.8, prefix:, end_time:Mon, 29 Nov 2021 21:35:51 GMT, manifest_version:2.0.0, version:6.8.21-SNAPSHOT, branch:6.8, build_id:6.8.21-fa5fd3ab, build_duration_seconds:15603]
=> [automation] update elastic stack version for testing 6.8.21-fa5fd3ab

winlogbeat/sys/winevent/event_test.go, winlogbeat/sys/winevent/maputil.go
Replace logic required to check whether a value is zero with the standard library method.
Reduces line count. The previous logic was needed as it was added prior to the reflect IsZero method's addition, but now it is not.
No specific checks.
Run `go test` in github.com/elastic/beats/v7/winlogbeat/sys/winevent.
N/A
N/A
N/A
=> winlogbeat/sys/winevent: use reflect IsZero method

x-pack/elastic-agent/GUIDELINES.md
We don't have a good place yet to document expectations around services run by Elastic Agent. I'm starting this document to have a place to add more content to it but I expect long term we need to figure out a better place.
This guideline comes out of recent issues we had in Cloud and local setups of fleet-server (https://github.com/elastic/fleet-server/pull/883). We never set clear guidlines on what the expectation is of a service run by Elastic Agent and Elastic Agent itself.
This PR is kick off the discussion.
=> [Elastic Agent] Add process error handling guidelines

x-pack/elastic-agent/CHANGELOG.next.asciidoc, x-pack/elastic-agent/_meta/config/common.p2.yml.tmpl, x-pack/elastic-agent/_meta/config/common.reference.p2.yml.tmpl, x-pack/elastic-agent/_meta/config/elastic-agent.docker.yml.tmpl, x-pack/elastic-agent/elastic-agent.docker.yml, x-pack/elastic-agent/elastic-agent.reference.yml, x-pack/elastic-agent/elastic-agent.yml, x-pack/elastic-agent/pkg/core/monitoring/beats/beats_monitor.go, x-pack/elastic-agent/pkg/core/monitoring/config/config.go
Change agent.monitoring.pprof to false, allow it to toggle beat
behaviour as well as the agent's.
- Closes #29108 
- Relates #21965
=> Change elastic-agent pprof default to false

CHANGELOG.next.asciidoc, libbeat/common/config.go, libbeat/processors/actions/add_labels.go, libbeat/processors/actions/add_labels_test.go
The processor was not working as described in the [docs](https://www.elastic.co/guide/en/beats/winlogbeat/current/add-labels.html). For example:
```yaml
processors:
- add_labels:
labels:
number: 1
with.dots: test
nested:
with.dots: nested
array:
- do
- re
- with.field: mi
```
```json
{
"labels": {
"array": [
"do",
"re",
{
"with": {
"field": "mi"
}
}
],
"nested.with.dots": "nested",
"number": 1,
"with.dots": "test"
}
```
```json
{
"labels": {
"number": 1,
"with.dots": "test",
"nested.with.dots": "nested",
"array.0": "do",
"array.1": "re",
"array.2.with.field": "mi"
}
}
```
The generated values to not align with the docs or how `labels` is described in ECS.
=> [libbeat] Fix add_labels flattening of arrays values

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 30 Nov 2021 17:11:44 GMT, release_branch:6.8, prefix:, end_time:Tue, 30 Nov 2021 21:41:23 GMT, manifest_version:2.0.0, version:6.8.21-SNAPSHOT, branch:6.8, build_id:6.8.21-b740aea0, build_duration_seconds:16179]
=> [automation] update elastic stack version for testing 6.8.21-b740aea0

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 30 Nov 2021 17:22:06 GMT, release_branch:7.15, prefix:, end_time:Tue, 30 Nov 2021 23:20:38 GMT, manifest_version:2.0.0, version:7.15.3-SNAPSHOT, branch:7.15, build_id:7.15.3-ac0a2edb, build_duration_seconds:21512]
=> [automation] update elastic stack version for testing 7.15.3-ac0a2edb

.mergify.yml
It changes  merge action to queue in .mergify.yml
The configuration uses the deprecated strict mode of the merge action.
A brownout is planned for the whole December 6th, 2021 day.
This option will be removed on January 10th, 2022.
For more information: https://blog.mergify.io/strict-mode-deprecation/
=> Mergify.yml merge to queue

CHANGELOG.next.asciidoc, libbeat/outputs/kafka/docs/kafka.asciidoc
Remove the beta warning in the documentation for SASL/SCRAM on Kafka now that it's included in the end-to-end tests.
=> Remove beta warning for SASL/SCRAM on Kafka GA

dev-tools/packaging/packages.yml, x-pack/elastic-agent/magefile.go
Adds osquerybeat to resulting agent artifact
The team Security Assets Management need help from #infra to have Osquerybeat packaged with Elastic Agent for 7.16 release.
=> [Elastic Agent] Include osquerybeat in builds

libbeat/esleg/eslegclient/connection.go, libbeat/esleg/eslegclient/connection_test.go
Currently libbeat output always sets an `Accept` header and a `Content-Type` header when sending a body. When users configure http headers for the ES output, this leads to invalid requests as multiple `Accept` header or `Content-Type` information is set. 
With this PR the headers are only set if not configured by the user. 
This is important so that users can configure ES `7.x` compatibility headers throughout the `8.x` lifecycle when still running a `7.x` beat. 
While the change is important for `7.16`, it still makes sense to merge into `master` branch to minimize differences and keep backports easy, and because the changes are not specific to these compatibility headers. 
* Start ES and Kibana 8.0.0-SNAPSHOT
* Configure compatibility headers for ES output
```
output.elasticsearch: …
```
=> Allow Accept and Content-Type headers to be set

CHANGELOG.next.asciidoc, winlogbeat/_meta/config/header.yml.tmpl, winlogbeat/beater/winlogbeat.go, winlogbeat/checkpoint/checkpoint.go, winlogbeat/checkpoint/checkpoint_test.go, winlogbeat/config/config.go, winlogbeat/docs/winlogbeat-options.asciidoc, winlogbeat/winlogbeat.reference.yml, x-pack/winlogbeat/winlogbeat.reference.yml
- Added a new option ("winlogbeat.registry_flush") for configuring the
timeout for writting registry entries to disk. The previously hard-coded
value of 5 seconds is now the default value.
The value is currently hard-coded and environments that have lots of event activity will cause unnecessary CPU usage due to excessive flushing/writing. By tuning this value, the flush interval can be adjusted to reduce CPU churn.
- Add the option to the configuration file (`winlogbeat.yml`):
```
winlogbeat.registry_flush: 30s
```
Default is `5s`. Value should be a duration value (i.e., `5s`, `1m`)
- Closes #29001
=> [Winlogbeat] Add configuration for registry file flush timeout

metricbeat/module/mongodb/replstatus/replstatus_integration_test.go
This PR is to disable mongodb flaky test `TestFetch` in `replstatus_integration_test.go`.
- Relates https://github.com/elastic/beats/issues/29208
=> Disable mongodb TestFetch in replstatus_integration_test.go

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 1 Dec 2021 00:15:49 GMT, release_branch:7.15, prefix:, end_time:Wed, 1 Dec 2021 07:11:13 GMT, manifest_version:2.0.0, version:7.15.3-SNAPSHOT, branch:7.15, build_id:7.15.3-1d3806ef, build_duration_seconds:24924]
=> [automation] update elastic stack version for testing 7.15.3-1d3806ef

CHANGELOG.next.asciidoc, x-pack/auditbeat/module/system/socket/events.go, x-pack/auditbeat/module/system/socket/kprobes.go, x-pack/auditbeat/module/system/socket/state.go, x-pack/auditbeat/module/system/socket/state_test.go, x-pack/auditbeat/module/system/socket/template.go, x-pack/auditbeat/tracing/perfevent.go
This PR adds some fixes to Auditbeat's system/socket dataset in order to improve the process/flow correlation. During  testing, the following issues have been identified.
- Process forks were not tracked. This was an oversight that would trigger async process information fetch
- Receiving a new socket via `accept` was not handled properly. This was a major cause of process misattribution as the new flow could be associated to the previous process using the socket.
-  Fixes wrong client/server identification in some scenarios.
It had been reported that the dataset could provide incorrect process information, associating flows with the wrong process, and could also mismatch the origin of a connection, assigning the server side as the client.
- ~~[ ] I have made corresponding changes to the …
=> Auditbeat: Fix processes misattribution in system/socket dataset

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-httpjson.asciidoc, x-pack/filebeat/input/httpjson/config_auth.go, x-pack/filebeat/input/httpjson/config_test.go
- Enhancement
Current httpjson doesn’t have grant_type: password.
This PR contains the codebase for the authentication mechanism for httpjson input which is a part of the Salesforce connector.
Authentication Details:
Added grant_type: password in existing method with configurations.
if auth.oauth2.user and auth.oauth2.password parameter are mentioned in oauth2 configuration, code will automatically uses grant_type as password and create client accordingly.
- Current httpjson only support one grant_type.
- Some APIs need multiple kinds of grant_type.
- salesforce connector also need grant_type password for authentication.
- 
Configuration Example:
```
- type: httpjson
auth.oauth2:
client.id: 12345678901234567890abcdef
client.secret: abcdef12345678901234567890
token_url: …
```
=> [Filebeat][httpjson] httpjson oauth2 authentication mechanism for salesforce events

Makefile
Fixes python environment activation. The fix is being tested as part of #29245 , where the issue was detected. This PR is to isolate the fix in an independent change.
In #29245 builds have started failing. It seems that some change in the workers have make this issue surface.
To be tested with a CI build.
-
=> Fix Python environment activation

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 2 Dec 2021 17:14:52 GMT, release_branch:6.8, prefix:, end_time:Thu, 2 Dec 2021 22:25:29 GMT, manifest_version:2.0.0, version:6.8.21-SNAPSHOT, branch:6.8, build_id:6.8.21-008e8297, build_duration_seconds:18637]
=> [automation] update elastic stack version for testing 6.8.21-008e8297

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Sun, 5 Dec 2021 17:12:37 GMT, release_branch:6.8, prefix:, end_time:Sun, 5 Dec 2021 21:32:21 GMT, manifest_version:2.0.0, version:6.8.21-SNAPSHOT, branch:6.8, build_id:6.8.21-476f5843, build_duration_seconds:15584]
=> [automation] update elastic stack version for testing 6.8.21-476f5843

CHANGELOG.next.asciidoc, Makefile
It changes the way to check if the Python virtual environment is valid, not it check for the activation script instead of check only the existence of the folder.
For some reason, the folder exists in the CI and it is empty, this forces to recreate it in case the activation script is not there.
- ~[ ] I have commented my code, particularly in hard-to-understand areas~
- ~[ ] I have added tests that prove my fix is effective or that my feature works~
- ~[ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~
=> fix: check the activation script exists on Python virtual environments

CHANGELOG.next.asciidoc, NOTICE.txt, go.mod, go.sum, libbeat/common/flowhash/communityid_test.go, libbeat/common/seccomp/seccomp-profiler-allow.txt, packetbeat/beater/worker.go, packetbeat/decoder/decoder.go, packetbeat/decoder/decoder_test.go, packetbeat/decoder/util.go, packetbeat/protos/icmp/icmp.go, packetbeat/protos/icmp/icmp_test.go, packetbeat/protos/icmp/message.go, packetbeat/protos/icmp/message_test.go, packetbeat/protos/icmp/transaction_test.go, packetbeat/protos/tcp/tcp.go, packetbeat/protos/tcp/tcp_test.go, packetbeat/sniffer/afpacket_linux.go, packetbeat/sniffer/afpacket_nonlinux.go, packetbeat/sniffer/device.go, packetbeat/sniffer/device_test.go, packetbeat/sniffer/file.go, packetbeat/sniffer/sniffer.go, packetbeat/tests/system/test_0050_icmp.py, x-pack/filebeat/input/netflow/netflow_test.go
This unifies and updates the gopacket dependencies for network traffic analysis.
Currently the project depends on three forks of the gopacket library. This complicates dependency management, and with many of the fixes now merged upstream it needlessly prevent us having access to new features of gopacket (though note the intention to make a canonical [elastic/gopacket](https://github.com/elastic/gopacket) fork and elastic/gopacket#3 — hopefully in the long term merging changes back upstream.)
No specific checks.
standard testing.
- Relates elastic/integrations#2132
- Relates #29112
- Depends #29017
- Depends elastic/gopacket#3
N/A
N/A
N/A
=> libbeat,packetbeat,x-pack/filebeat/input/netflow: unify gopacket dependencies

x-pack/osquerybeat/internal/config/osquery.go
Adds missing osquery top-level configuration properties for auto_table_construction, yara, prometheus_targets.
Immediate defect was reported when people were trying to use ```auto_table_construction``` and the configuration was not applied properly. There were two more top-level configuration properties that were ignored as well.
Here is an example configuration for auto_table_construction:
```
{
"auto_table_construction": {
"chrome_history": {
"path": "\\Users\\%\\AppData\\Local\\Google\\Chrome\\User\\ Data\\Default\\History",
"columns": [
"last_visited",
"url",
"title",
"visit_count"
],
"query": "SELECT datetime(last_visit_time/1000000-11644473600, \"unixepoch\") as last_visited, url, title, visit_count FROM urls"
}
}
}
```
Before this change the ```auto_table_construction``` was …
=> Osquerybeat: Add missing osquery top-level configuration properties for auto_table_construction, yara, prometheus_targets

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Sun, 5 Dec 2021 17:25:40 GMT, release_branch:7.15, prefix:, end_time:Sun, 5 Dec 2021 23:29:23 GMT, manifest_version:2.0.0, version:7.15.3-SNAPSHOT, branch:7.15, build_id:7.15.3-70c2e21f, build_duration_seconds:21823]
=> [automation] update elastic stack version for testing 7.15.3-70c2e21f

CHANGELOG.next.asciidoc, auditbeat/auditbeat.reference.yml, filebeat/filebeat.reference.yml, heartbeat/heartbeat.reference.yml, libbeat/_meta/config/ssl.reference.yml.tmpl, libbeat/common/transport/tlscommon/config.go, libbeat/common/transport/tlscommon/tls_config.go, libbeat/common/transport/tlscommon/types.go, libbeat/docs/shared-ssl-config.asciidoc, metricbeat/metricbeat.reference.yml, packetbeat/packetbeat.reference.yml, winlogbeat/winlogbeat.reference.yml, x-pack/auditbeat/auditbeat.reference.yml, x-pack/filebeat/filebeat.reference.yml, x-pack/functionbeat/functionbeat.reference.yml, x-pack/heartbeat/heartbeat.reference.yml, x-pack/metricbeat/metricbeat.reference.yml, x-pack/osquerybeat/osquerybeat.reference.yml, x-pack/packetbeat/packetbeat.reference.yml, x-pack/winlogbeat/winlogbeat.reference.yml
Adds `ssl.ca_trusted_fingerprint` option, if set to a HEX fingerprint of a root CA certificate, this certificate is added to
the trusted CAs (as if it was defined on `ssl.certificate_authorities`), then the SSL validation continues as normal.
This happens during the SSL handshake.
1. Run an Elasticsearch 8.0 Instance with self signed certs
2. Edit the Elasticsearch output configuration from your beat:
```
output.elasticsearch:
hosts: ["https://<your IP address>:9200"]
username: "elastic"
password: "<your elastic use password>"
ssl.ca_trusted_fingerprint: "<ES CA certificate fingerprint>"
```
3. Run your Beat
=> Support self-signed certificate on outputs

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 6 Dec 2021 17:11:13 GMT, release_branch:6.8, prefix:, end_time:Mon, 6 Dec 2021 21:46:52 GMT, manifest_version:2.0.0, version:6.8.21-SNAPSHOT, branch:6.8, build_id:6.8.21-220689e5, build_duration_seconds:16539]
=> [automation] update elastic stack version for testing 6.8.21-220689e5

x-pack/elastic-agent/pkg/agent/cmd/container.go
removes syncing of the `ingest` folder in the apm tarball. Starting in 8.0, the tarball no longer includes an
ingest folder.
=> [elastic-agent] stop syncing apm ingest folder

libbeat/common/transport/tlscommon/tls_config.go
This PR adds logs to clearly show when Beats is trusting a self-signed certificate through a fingerprint provided by `ssl.ca_trusted_fingerprint`.
If there is any issue connecting to an output (the main use case is ES >= 8.0) using a self-signed certificate it will be easier to debug/understand what is happening.
1. Run an Elasticsearch 8.0 Instance with self signed certs
2. Edit the Elasticsearch output configuration from your beat:
```
output.elasticsearch:
hosts: …
```
=> Add logs for ca_trusted_fingerprint workflow

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 6 Dec 2021 17:23:14 GMT, release_branch:7.15, prefix:, end_time:Mon, 6 Dec 2021 23:34:19 GMT, manifest_version:2.0.0, version:7.15.3-SNAPSHOT, branch:7.15, build_id:7.15.3-9e171938, build_duration_seconds:22265]
=> [automation] update elastic stack version for testing 7.15.3-9e171938

libbeat/docs/release-notes/breaking/breaking-7.16.asciidoc, libbeat/docs/release-notes/breaking/breaking.asciidoc
Adds breaking changes that we want to highlight in 7.16. Remember that these are the highlights that get pulled into the stack upgrade docs.
Preview link: https://beats_29300.docs-preview.app.elstc.co/guide/en/beats/libbeat/master/breaking-changes-7.16.html
Users need to be aware of these changes.
- Closes https://github.com/elastic/observability-docs/issues/1291
=> Add 7.16 breaking changes

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 7 Dec 2021 17:11:36 GMT, release_branch:6.8, prefix:, end_time:Tue, 7 Dec 2021 21:23:16 GMT, manifest_version:2.0.0, version:6.8.21-SNAPSHOT, branch:6.8, build_id:6.8.21-783223fd, build_duration_seconds:15100]
=> [automation] update elastic stack version for testing 6.8.21-783223fd

CHANGELOG.next.asciidoc, x-pack/filebeat/input/awss3/s3_objects.go, x-pack/filebeat/input/awss3/sqs.go, x-pack/filebeat/input/awss3/sqs_s3_event.go
This adds elapsed_time_ns into S3 object read errors and SQS processing warning log messages. This gives context about how long it took to fail. Extended times could be an indicator of a blocked output.
It also adds the number of S3 records contained in the SQS notification to error messages. This gives context about how many S3 objects were being processed when a failure occurs.
This helps give more context around errors.
`failed to get s3 object (elasped_time_ns=16284): fake connectivity failure`
`failed processing SQS message (it will return to queue after visibility …
=> [Filebeat] Add info to aws-s3 log messages

libbeat/autodiscover/providers/kubernetes/config.go, libbeat/common/kubernetes/metadata/metadata.go, libbeat/processors/add_kubernetes_metadata/config.go, x-pack/elastic-agent/pkg/composable/providers/kubernetes/config.go
Fix regression introduced at https://github.com/elastic/beats/pull/29133
=> Fix k8s metadata regression

CHANGELOG.next.asciidoc, libbeat/dashboards/modify_json.go, libbeat/dashboards/modify_json_test.go
After the changes in the dashboard and index template format, custom names were only updated in dashboards, but not in index templates. This PR adjust index template support.
Type assertions were removed because the index template is always a `common.MapStr`.
Without this change, custom index names cannot be supported.
Closes #28571
=> Overwrite index name in index template correctly

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 7 Dec 2021 17:14:23 GMT, release_branch:7.15, prefix:, end_time:Tue, 7 Dec 2021 23:18:27 GMT, manifest_version:2.0.0, version:7.15.3-SNAPSHOT, branch:7.15, build_id:7.15.3-984b6e42, build_duration_seconds:21844]
=> [automation] update elastic stack version for testing 7.15.3-984b6e42

CHANGELOG.next.asciidoc, x-pack/filebeat/processors/decode_cef/cef/cef.go, x-pack/filebeat/processors/decode_cef/cef/cef.rl, x-pack/filebeat/processors/decode_cef/cef/cef_test.go, x-pack/filebeat/processors/decode_cef/cef/parser.go
Escaped LF and CR were not handled inside of CEF extension value.
Those characters are now accepted and replaced with their unescaped
equivalents.
Fixes #16995
CEF decoding was broken by presence of `\n` or `\r` in extension values.
- Closes #16995
=> Fix decode_cef handling of escaped LF and CR

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 8 Dec 2021 00:13:53 GMT, release_branch:8.0, prefix:, end_time:Wed, 8 Dec 2021 06:32:48 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-fa37006f, build_duration_seconds:22735]
=> [automation] update elastic stack version for testing 8.0.0-fa37006f

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 8 Dec 2021 17:14:42 GMT, release_branch:7.15, prefix:, end_time:Wed, 8 Dec 2021 23:35:19 GMT, manifest_version:2.0.0, version:7.15.3-SNAPSHOT, branch:7.15, build_id:7.15.3-67d7b6ce, build_duration_seconds:22837]
=> [automation] update elastic stack version for testing 7.15.3-67d7b6ce

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 8 Dec 2021 05:15:14 GMT, release_branch:7.16, prefix:, end_time:Wed, 8 Dec 2021 11:17:04 GMT, manifest_version:2.0.0, version:7.16.1-SNAPSHOT, branch:7.16, build_id:7.16.1-53c0de77, build_duration_seconds:21710]
=> [automation] update elastic stack version for testing 7.16.1-53c0de77

x-pack/elastic-agent/CHANGELOG.next.asciidoc, x-pack/elastic-agent/pkg/agent/application/application.go, x-pack/elastic-agent/pkg/agent/application/application_test.go, x-pack/elastic-agent/pkg/agent/cmd/run.go
Elastic agent configuration options were overwritten by fleet default configuration options, even in standalone mode.
undesired behavior.
- Closes https://github.com/elastic/elastic-agent-client/issues/28
=> Agent configuration overridden by default fleet config

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 8 Dec 2021 17:14:41 GMT, release_branch:6.8, prefix:, end_time:Wed, 8 Dec 2021 21:42:51 GMT, manifest_version:2.0.0, version:6.8.21-SNAPSHOT, branch:6.8, build_id:6.8.21-df489e18, build_duration_seconds:16090]
=> [automation] update elastic stack version for testing 6.8.21-df489e18

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 9 Dec 2021 21:39:50 GMT, release_branch:7.16, prefix:, end_time:Fri, 10 Dec 2021 03:52:15 GMT, manifest_version:2.0.0, version:7.16.1-SNAPSHOT, branch:7.16, build_id:7.16.1-1d21f78b, build_duration_seconds:22345]
=> [automation] update elastic stack version for testing 7.16.1-1d21f78b

metricbeat/docker-compose.yml, metricbeat/module/logstash/docker-compose.yml, testing/environments/latest.yml, testing/environments/prev-minor.yml, x-pack/metricbeat/docker-compose.yml
Merge after the release 7.16.0.
=> chore: Update test environments 7.16.1

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Fri, 10 Dec 2021 12:22:25 GMT, release_branch:master, prefix:, end_time:Fri, 10 Dec 2021 18:38:42 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:master, build_id:8.1.0-b6e7e1f3, build_duration_seconds:22577]
=> [automation] update elastic stack version for testing 8.1.0-b6e7e1f3

CHANGELOG.asciidoc
Fixing changelog issue after 7.16.0 release - 8.0 branch.
=> Fix entry for #27689

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 13 Dec 2021 19:09:12 GMT, release_branch:6.8, prefix:, end_time:Mon, 13 Dec 2021 23:36:16 GMT, manifest_version:2.0.0, version:6.8.22-SNAPSHOT, branch:6.8, build_id:6.8.22-8f813436, build_duration_seconds:16024]
=> [automation] update elastic stack version for testing 6.8.22-8f813436

.mergify.yml
Standardise the backports to be always from the `master`/`main` branch into `7.x`/`8.x` branches. Then use `forwardport-{branch}` to backport from `7.x`/`8.x` branches into the `{branch}` branch
This should avoid any misleading with the labels semantic.
=> [mergify]: forwardport into the master branch

libbeat/template/load.go
This PR removes the usage of the cat API.
The cat API is not intended to be used in production. Hence, it has to be removed from Beats prod code.
=> Do not use cat API when checking for templates

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 14 Dec 2021 17:11:48 GMT, release_branch:6.8, prefix:, end_time:Tue, 14 Dec 2021 21:45:04 GMT, manifest_version:2.0.0, version:6.8.22-SNAPSHOT, branch:6.8, build_id:6.8.22-0e8cff19, build_duration_seconds:16396]
=> [automation] update elastic stack version for testing 6.8.22-0e8cff19

CHANGELOG.next.asciidoc, filebeat/docs/modules/aws.asciidoc, x-pack/filebeat/filebeat.reference.yml, x-pack/filebeat/module/aws/_meta/config.yml, x-pack/filebeat/module/aws/_meta/docs.asciidoc, x-pack/filebeat/module/aws/cloudtrail/config/aws-s3.yml, x-pack/filebeat/module/aws/cloudtrail/manifest.yml, x-pack/filebeat/module/aws/cloudwatch/config/aws-s3.yml, x-pack/filebeat/module/aws/cloudwatch/manifest.yml, x-pack/filebeat/module/aws/ec2/config/aws-s3.yml, x-pack/filebeat/module/aws/ec2/manifest.yml, x-pack/filebeat/module/aws/elb/config/aws-s3.yml, x-pack/filebeat/module/aws/elb/manifest.yml, x-pack/filebeat/module/aws/s3access/config/aws-s3.yml, x-pack/filebeat/module/aws/s3access/manifest.yml, x-pack/filebeat/module/aws/vpcflow/config/input.yml, x-pack/filebeat/module/aws/vpcflow/manifest.yml, x-pack/filebeat/module/awsfargate/log/config/aws-cloudwatch.yml, x-pack/filebeat/module/awsfargate/log/manifest.yml, x-pack/filebeat/modules.d/aws.yml.disabled, x-pack/libbeat/common/aws/credentials.go, x-pack/libbeat/common/aws/credentials_test.go, x-pack/libbeat/docs/aws-credentials-config.asciidoc
Adds a new config to the AWS common module `deafult_region`.  
This is to resolve issues as discussed in https://discuss.elastic.co/t/input-aws-s3-failed-with-failed-to-initialize-s3-poller/288130.  Currently the module uses the us-east-1 region as the default anytime there isn't another item overriding it, like to query the location of a S3 bucket.  As shown in the forum, that doesn't always work and should have a way to change the default like with the AWS CLI.
Run unit/integration tests for the AWS common module
-
=> Add default region config to AWS

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 15 Dec 2021 00:17:01 GMT, release_branch:master, prefix:, end_time:Wed, 15 Dec 2021 06:11:02 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:master, build_id:8.1.0-d8a3a806, build_duration_seconds:21241]
=> [automation] update elastic stack version for testing 8.1.0-d8a3a806

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 15 Dec 2021 00:16:46 GMT, release_branch:8.0, prefix:, end_time:Wed, 15 Dec 2021 06:47:06 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-9fb1bbae, build_duration_seconds:23420]
=> [automation] update elastic stack version for testing 8.0.0-9fb1bbae

CHANGELOG.next.asciidoc, winlogbeat/_meta/config/header.yml.tmpl, winlogbeat/docs/winlogbeat-options.asciidoc, winlogbeat/eventlog/factory.go, winlogbeat/eventlog/wineventlog.go, winlogbeat/eventlog/wineventlog_experimental.go, winlogbeat/eventlog/wineventlog_test.go, winlogbeat/winlogbeat.reference.yml, winlogbeat/winlogbeat.yml, x-pack/winlogbeat/winlogbeat.reference.yml, x-pack/winlogbeat/winlogbeat.yml
- Added new configuration field (xml_query) to support custom XML queries
- This new configuration item will conflict with existing simple
query configuration items (ignore_older, event_id, level, provider)
- Validator has been updated to check for key conflicts and XML syntax,
but does not check for correctness of XML schema.
The existing filtering options for Winlogbeat don't provide enough control when trying to filter out unwanted events. A user may want to include multiple channels in the same query or filter out certain SIDs. Custom XML queries provide a very powerful mechanism for fine tuning what events should be searched.
- A quick way to generate XML queries is to create a custom view in Event Viewer and export the XML. This can be pasted as-is into a winlogbeat config:
```yaml …
```
=> [Winlogbeat] Add support for custom XML queries

CHANGELOG-developer.next.asciidoc, libbeat/outputs/elasticsearch/client.go, libbeat/outputs/elasticsearch/client_test.go
To prevent infinite loops when having `http.max_content_length` set
too low or `bulk_max_size` too high we now handle this status code
separately and drop the whole event batch producing a detailed error
message on the console.
Because without this change beats are forever stuck once they get the first 413 response from Elasticsearch.
~I have made corresponding changes to the documentation~
~I have made corresponding change to the default configuration files~
1. Run Elastisearch locally with its default configuration
2. Prepare a configuration file for filebeat that ingests a log file:
`your_filebeat.yml`
```yaml
filebeat:
inputs:
- type: log
paths:
- /path/to/your/file.log
output:
elasticsearch:
hosts: ["localhost:9200"]
```
**Notice, the filename must be changed to your location**
3. …
=> Drop event batch when get HTTP status 413 from ES

CHANGELOG.next.asciidoc, libbeat/common/kubernetes/types.go, metricbeat/module/kubernetes/event/event.go
Enhance filter check in k8s event metricset by checking `eventTime` field if `lastTimestamp` is not a valid one.
Based on research made on https://github.com/elastic/beats/issues/28923 `lastTimestamp` is possible to be null and hence we need to fallback to checking `eventTime` in order to filter older events. If both fields are null we cannot apply filtering and hence the `skip_older: false` should be used.
cc: @MichaelKatsoulis
=> Enhance filter check in k8s event metricset

Jenkinsfile, auditbeat/Jenkinsfile.yml, filebeat/Jenkinsfile.yml, heartbeat/Jenkinsfile.yml, metricbeat/Jenkinsfile.yml, packetbeat/Jenkinsfile.yml, x-pack/auditbeat/Jenkinsfile.yml, x-pack/auditbeat/tests/system/test_metricsets.py, x-pack/elastic-agent/Jenkinsfile.yml, x-pack/filebeat/Jenkinsfile.yml, x-pack/functionbeat/Jenkinsfile.yml, x-pack/heartbeat/Jenkinsfile.yml, x-pack/metricbeat/Jenkinsfile.yml, x-pack/osquerybeat/Jenkinsfile.yml, x-pack/packetbeat/Jenkinsfile.yml
Enable MacOSX ephemeral workers
Validate we can use the MacOSX ephemeral workers. 
Already verified in:
- https://github.com/elastic/beats/pull/29372
- https://github.com/elastic/beats/pull/29371
- https://github.com/elastic/beats/pull/29345
=> ci: enable orka

CHANGELOG.next.asciidoc, x-pack/filebeat/input/awss3/sqs_s3_event.go, x-pack/filebeat/input/awss3/sqs_s3_event_test.go
This reduced log noise and unnecessary API calls from the aws-s3 input.
- Stop the keepalive goroutine after ErrCodeReceiptHandleIsInvalid is returned by ChangeMessageVisibility.
- Add `message_receipt_time` to log messages associated with processing of a given SQS message.
- Fix incorrect error being wrapped when ApproximateReceiveCount threshold is reached.
ReceiptHandleIsInvalid warnings become very noisy in Filebeat logs.
=> [Filebeat] aws-s3: Stop calling ChangeMessageVisibility after ReceiptHandleIsInvalid

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 16 Dec 2021 17:21:41 GMT, release_branch:6.8, prefix:, end_time:Thu, 16 Dec 2021 21:16:55 GMT, manifest_version:2.0.0, version:6.8.22-SNAPSHOT, branch:6.8, build_id:6.8.22-9c313d58, build_duration_seconds:14114]
=> [automation] update elastic stack version for testing 6.8.22-9c313d58

.mergify.yml
=> Add backport rule for 7.17 branch

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 16 Dec 2021 05:13:19 GMT, release_branch:7.16, prefix:, end_time:Thu, 16 Dec 2021 10:49:50 GMT, manifest_version:2.0.0, version:7.16.2-SNAPSHOT, branch:7.16, build_id:7.16.2-682993ae, build_duration_seconds:20191]
=> [automation] update elastic stack version for testing 7.16.2-682993ae

CHANGELOG.next.asciidoc
=> Cleanup breaking changes section (8.0)

metricbeat/helper/elastic/elastic.go, metricbeat/helper/elastic/elastic_test.go
Before 8.x, metricbeat's monitoring packages used to index events with a legacy schema when `xpack.enabled: true` setting was activated. This logic is gone in 8.x and only serves to [target a specific index format](https://github.com/elastic/beats/blob/master/metricbeat/module/elasticsearch/shard/data.go#L136-L139). Since we now index events with a different schema we also need new mappings for the Stack monitoring UI to be compatible.
[These new mappings](https://github.com/elastic/elasticsearch/pull/81744) can't conflict with the current one so they target a version 8 of the `.monitoring-{product}-{version}` pattern. This change bumps the version to target those.
Additional context https://github.com/elastic/kibana/issues/121251
=> bump index name version

metricbeat/module/kibana/stats/data.go
`elasticsearch.cluster.id` property is currently written to the kibana `ModuleFields` when it should be a top-level field
=> Write to rootfields instead of modulefields

filebeat/module/nginx/ingress_controller/ingest/pipeline.yml, x-pack/filebeat/module/checkpoint/firewall/ingest/pipeline.yml
This PR changes renaming `@timestamp` fields in Ingest pipelines to copying them. 
Filebeat sends events to data streams now. However, data streams require `@timestamp` fields in every event. Some Ingest pipelines either get rid of or on failure `@timestamp` is missing from events. This is a problem and the event cannot be indexed.
=> Change renaming `@timestamp` to copying values in Ingest pipelines

filebeat/docs/filebeat-general-options.asciidoc, filebeat/docs/howto/override-config-settings.asciidoc, libbeat/docs/loggingconfig.asciidoc
Resolves (#20584)
Changes implemented in the (#14119) made all Beats-created files and folders apply an `umask of 0027` (on POSIX systems). 
According to the @ycombinator comment available at the [discuss.elastic: rotated-log-files-have-incorrect-permissions](https://discuss.elastic.co/t/rotated-log-files-have-incorrect-permissions/244623)
> This is a security measure. Any files/folders created by Beats get a umask of 0027. This means any files will have at most 0640 permissions and any folders will have at most 0750 permissions. Essentially, we deliberately don't want any Beats-created files/folders to be world-readable.
This PR updates the following document files to reflect the latest changes (regarding the `umask 0027`):
* `loggingconfig.asciidoc` which is included in the:
* …
=> [Docs] Update logging.files.permissions documentation to consider umask (#20584)

CHANGELOG.next.asciidoc, x-pack/filebeat/module/aws/cloudtrail/config/aws-s3.yml
Fixes typo from #29415, here https://github.com/elastic/beats/pull/29415#discussion_r769624185.
Re-add the endpoint config
-
=> [Filebeat] Fix Cloudtrail Config

CHANGELOG.next.asciidoc, heartbeat/monitors/wrappers/wrappers.go, heartbeat/monitors/wrappers/wrappers_test.go
Fixes https://github.com/elastic/beats/issues/26325
we now only add monitor status to summary events for browsers. Additionally, this renames the poorly renamed `wrappers/monitor*` to `wrappers/wrappers*`
`monitor.status` should really only be set on unique components of events that constitute a full check. For lightweight checks that means checking an individual IP etc. A step represents progress toward a check, not the check itself. Hence this change.
We'll want to check that this doesn't break any features in the synthetics UI as well. I'd index to kibana and check that nothing breaks.
=> [heartbeat] Only add monitor.status to browser summary events

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc
All entries that were merged in previous release have been removed. They will be put in an `attic` file in `master` in case we need to fix previous changelogs.
=> Cleanup of CHANGELOG.next for 7.16

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
- Cleanup breaking changes section (#29489)
- Cleanup of CHANGELOG.next for 7.16 (#29506)
- docs: Prepare Changelog for 7.16.2 (#29521)
- Additional cleanup
=> Forward-port 7.16.2 changelog to 7.17 and additional cleanup

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Fri, 17 Dec 2021 17:10:55 GMT, release_branch:6.8, prefix:, end_time:Fri, 17 Dec 2021 21:02:40 GMT, manifest_version:2.0.0, version:6.8.22-SNAPSHOT, branch:6.8, build_id:6.8.22-0bc81dc8, build_duration_seconds:13905]
=> [automation] update elastic stack version for testing 6.8.22-0bc81dc8

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Fri, 17 Dec 2021 00:14:40 GMT, release_branch:master, prefix:, end_time:Fri, 17 Dec 2021 06:44:14 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:master, build_id:8.1.0-befff95a, build_duration_seconds:23374]
=> [automation] update elastic stack version for testing 8.1.0-befff95a

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Fri, 17 Dec 2021 02:10:53 GMT, release_branch:7.17, prefix:, end_time:Fri, 17 Dec 2021 14:49:30 GMT, manifest_version:2.0.0, version:7.17.0-SNAPSHOT, branch:7.17, build_id:7.17.0-872523de, build_duration_seconds:45517]
=> [automation] update elastic stack version for testing 7.17.0-872523de

.mergify.yml
Close obsoleted PRs that are related to the automated bumps when they are in conflict.
For instance: https://github.com/elastic/beats/pull/29385
Therefore, it's not needed to be resolved but wait for the more up-to-date PRs to be merged.
=> [mergify]: keep the house clean for conflicts in automated bumps

metricbeat/docker-compose.yml, metricbeat/module/logstash/docker-compose.yml, testing/environments/latest.yml, testing/environments/prev-minor.yml, x-pack/metricbeat/docker-compose.yml
Merge only after the release of 7.16.2.
=> [Release] Update test environments for 7.16.3

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 20 Dec 2021 00:16:05 GMT, release_branch:8.0, prefix:, end_time:Mon, 20 Dec 2021 06:16:43 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-7b79b556, build_duration_seconds:21638]
=> [automation] update elastic stack version for testing 8.0.0-7b79b556

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 20 Dec 2021 15:03:58 GMT, release_branch:7.17, prefix:, end_time:Mon, 20 Dec 2021 20:35:40 GMT, manifest_version:2.0.0, version:7.17.0-SNAPSHOT, branch:7.17, build_id:7.17.0-8aa59db1, build_duration_seconds:19902]
=> [automation] update elastic stack version for testing 7.17.0-8aa59db1

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 21 Dec 2021 00:13:09 GMT, release_branch:7.17, prefix:, end_time:Tue, 21 Dec 2021 05:41:05 GMT, manifest_version:2.0.0, version:7.17.0-SNAPSHOT, branch:7.17, build_id:7.17.0-aa797a6c, build_duration_seconds:19676]
=> [automation] update elastic stack version for testing 7.17.0-aa797a6c

Jenkinsfile, dev-tools/mage/integtest_docker.go, dev-tools/mage/target/common/package.go
Captures and preserves the docker-compose logs after running integration or system tests. Allows auditing service logs for issues, in particular it enables auditing the Elasticsearch logs for deprecation warnings after test runs.
We need to ensure we aren't using any soon to be deprecated Elasticsearch APIs.
- [ x ] I have commented my code, particularly in hard-to-understand areas
After running `mage goIntegTest` …
=> Save docker-compose logs from integration tests.

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 22 Dec 2021 00:13:31 GMT, release_branch:7.17, prefix:, end_time:Wed, 22 Dec 2021 05:48:01 GMT, manifest_version:2.0.0, version:7.17.0-SNAPSHOT, branch:7.17, build_id:7.17.0-e76712ab, build_duration_seconds:20070]
=> [automation] update elastic stack version for testing 7.17.0-e76712ab

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 22 Dec 2021 00:19:48 GMT, release_branch:8.0, prefix:, end_time:Wed, 22 Dec 2021 13:21:20 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-52f8db06, build_duration_seconds:46892]
=> [automation] update elastic stack version for testing 8.0.0-52f8db06

.ci/scripts/kind-setup.sh, CHANGELOG.next.asciidoc, deploy/kubernetes/Jenkinsfile.yml, metricbeat/docs/modules/kubernetes.asciidoc, metricbeat/module/kubernetes/_meta/docs.asciidoc, metricbeat/module/kubernetes/test/integration.go
This PR adds support for latest k8s versions, v1.22 and v1.23.
We also need to consider dropping support for older versions that k8s does not support based on https://endoflife.date/kubernetes and https://kubernetes.io/releases/.
@MichaelKatsoulis @tetianakravchenko @jsoriano  I would love your thoughts on this one. I can create follow up issues for this to discuss it there instead of blocking this one.
This came up after dealing with failures at https://github.com/elastic/beats/pull/29572 since the `Cronjob` API move to `batch/v1` at 1.21 and hence tests are failing for k8s version pior to 1.20.
elastic-package: https://github.com/elastic/elastic-package/pull/634
integrations: https://github.com/elastic/integrations/pull/2372
=> Add support for latest k8s versions

metricbeat/module/elasticsearch/index_recovery/index_recovery.go, metricbeat/module/elasticsearch/ml_job/_meta/data.json, metricbeat/module/elasticsearch/ml_job/data.go, metricbeat/module/elasticsearch/shard/_meta/data.json, metricbeat/module/elasticsearch/shard/data.go
- Fix drifts from 7.16 in elasticsearch module's documents when `xpack.enabled` is set.
- Fix incomplete `node` property for `ml_job` and `shard` metricsets
- Fix shard's cluster state property path to be consistent with [cluster_stats](https://github.com/elastic/beats/blob/master/metricbeat/module/elasticsearch/cluster_stats/_meta/data.json#L102)
=> elasticsearch module - xpack enabled parity

deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml
In kubernetes package were added some data-streams configuration adjustments. This PR backports those changes to elastic-agent standalone manifest.
- Closes https://github.com/elastic/beats/issues/29565
=> Align elastic-agent-standalone manifest with the kubernetes package changes

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Sun, 26 Dec 2021 17:11:11 GMT, release_branch:6.8, prefix:, end_time:Sun, 26 Dec 2021 20:57:19 GMT, manifest_version:2.0.0, version:6.8.23-SNAPSHOT, branch:6.8, build_id:6.8.23-93b27cd7, build_duration_seconds:13568]
=> [automation] update elastic stack version for testing 6.8.23-93b27cd7

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Sun, 26 Dec 2021 00:15:54 GMT, release_branch:8.0, prefix:, end_time:Sun, 26 Dec 2021 06:46:39 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-fde13a9d, build_duration_seconds:23445]
=> [automation] update elastic stack version for testing 8.0.0-fde13a9d

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Sun, 26 Dec 2021 00:18:52 GMT, release_branch:7.17, prefix:, end_time:Sun, 26 Dec 2021 05:38:23 GMT, manifest_version:2.0.0, version:7.17.0-SNAPSHOT, branch:7.17, build_id:7.17.0-6e4bbd35, build_duration_seconds:19171]
=> [automation] update elastic stack version for testing 7.17.0-6e4bbd35

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 27 Dec 2021 17:11:02 GMT, release_branch:6.8, prefix:, end_time:Mon, 27 Dec 2021 20:55:16 GMT, manifest_version:2.0.0, version:6.8.23-SNAPSHOT, branch:6.8, build_id:6.8.23-e9640948, build_duration_seconds:13454]
=> [automation] update elastic stack version for testing 6.8.23-e9640948

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 27 Dec 2021 12:15:46 GMT, release_branch:master, prefix:, end_time:Mon, 27 Dec 2021 18:04:25 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:master, build_id:8.1.0-b989cb5c, build_duration_seconds:20919]
=> [automation] update elastic stack version for testing 8.1.0-b989cb5c

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 27 Dec 2021 00:15:34 GMT, release_branch:7.17, prefix:, end_time:Mon, 27 Dec 2021 05:53:19 GMT, manifest_version:2.0.0, version:7.17.0-SNAPSHOT, branch:7.17, build_id:7.17.0-09b71949, build_duration_seconds:20265]
=> [automation] update elastic stack version for testing 7.17.0-09b71949

CHANGELOG.next.asciidoc, x-pack/metricbeat/module/gcp/metrics/metrics_requester.go, x-pack/metricbeat/module/gcp/metrics/metricset.go
Type of change
- Bug
* Each aligner is applied to all metric types, that will incur more Google monitoring API calls and more costs.
* There are many unnecessary metrics with wrong aligner in MetricBeat events.
see issue #29513
- Closes #29513  
It works as expected. There are only two metrics in events.
=> Fix gcp metrics metricset apply aligner to all metric_types (#29513)

.ci/schedule-daily.groovy, .ci/schedule-weekly.groovy
Enable 7.17 branch on daily and weekly builds
7.17 was created but it was not enabled
=> ci: enable 7.17 branch

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 28 Dec 2021 17:11:09 GMT, release_branch:6.8, prefix:, end_time:Tue, 28 Dec 2021 20:58:50 GMT, manifest_version:2.0.0, version:6.8.23-SNAPSHOT, branch:6.8, build_id:6.8.23-87af1467, build_duration_seconds:13661]
=> [automation] update elastic stack version for testing 6.8.23-87af1467

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 28 Dec 2021 00:16:28 GMT, release_branch:8.0, prefix:, end_time:Tue, 28 Dec 2021 06:19:38 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-b0d1c470, build_duration_seconds:21790]
=> [automation] update elastic stack version for testing 8.0.0-b0d1c470

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 28 Dec 2021 12:13:30 GMT, release_branch:master, prefix:, end_time:Tue, 28 Dec 2021 18:13:23 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:master, build_id:8.1.0-c1a942c7, build_duration_seconds:21593]
=> [automation] update elastic stack version for testing 8.1.0-c1a942c7

CHANGELOG.next.asciidoc, libbeat/template/processor.go, libbeat/template/processor_test.go
Fixes the construction of the index template's `default_field` list so that fields of type _match_only_text_ and _wildcard_ can be added to it.
Since support for _match_only_text_ type was introduced in Beats, important fields where missing from the `default_field` index template setting. This affected the `message` field among others.
Note: this PR only completely fixes the issue for the 7.16 branch,  as another (unrelated) feature in 8.0/master also broke `default_field`. See #29633.
- Relates #29633
=> Ensure that match_only_text and wildcard fields can be added to default_field list

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 29 Dec 2021 17:11:36 GMT, release_branch:6.8, prefix:, end_time:Wed, 29 Dec 2021 21:00:04 GMT, manifest_version:2.0.0, version:6.8.23-SNAPSHOT, branch:6.8, build_id:6.8.23-f93d50e0, build_duration_seconds:13708]
=> [automation] update elastic stack version for testing 6.8.23-f93d50e0

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 29 Dec 2021 00:13:56 GMT, release_branch:8.0, prefix:, end_time:Wed, 29 Dec 2021 06:21:40 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-d1bb7d2c, build_duration_seconds:22064]
=> [automation] update elastic stack version for testing 8.0.0-d1bb7d2c

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 29 Dec 2021 00:13:14 GMT, release_branch:7.17, prefix:, end_time:Wed, 29 Dec 2021 06:07:26 GMT, manifest_version:2.0.0, version:7.17.0-SNAPSHOT, branch:7.17, build_id:7.17.0-a34e30fc, build_duration_seconds:21252]
=> [automation] update elastic stack version for testing 7.17.0-a34e30fc

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 30 Dec 2021 17:11:30 GMT, release_branch:6.8, prefix:, end_time:Thu, 30 Dec 2021 21:00:05 GMT, manifest_version:2.0.0, version:6.8.23-SNAPSHOT, branch:6.8, build_id:6.8.23-e700545e, build_duration_seconds:13715]
=> [automation] update elastic stack version for testing 6.8.23-e700545e

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 30 Dec 2021 00:15:58 GMT, release_branch:8.0, prefix:, end_time:Thu, 30 Dec 2021 06:23:30 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-d3289c33, build_duration_seconds:22052]
=> [automation] update elastic stack version for testing 8.0.0-d3289c33

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 30 Dec 2021 00:15:51 GMT, release_branch:7.17, prefix:, end_time:Thu, 30 Dec 2021 06:54:12 GMT, manifest_version:2.0.0, version:7.17.0-SNAPSHOT, branch:7.17, build_id:7.17.0-53d9a9d2, build_duration_seconds:23901]
=> [automation] update elastic stack version for testing 7.17.0-53d9a9d2

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Sun, 2 Jan 2022 17:10:54 GMT, release_branch:6.8, prefix:, end_time:Sun, 2 Jan 2022 20:54:56 GMT, manifest_version:2.0.0, version:6.8.23-SNAPSHOT, branch:6.8, build_id:6.8.23-147f9e5f, build_duration_seconds:13442]
=> [automation] update elastic stack version for testing 6.8.23-147f9e5f

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 3 Jan 2022 17:10:53 GMT, release_branch:6.8, prefix:, end_time:Mon, 3 Jan 2022 20:58:20 GMT, manifest_version:2.0.0, version:6.8.23-SNAPSHOT, branch:6.8, build_id:6.8.23-9608d49e, build_duration_seconds:13647]
=> [automation] update elastic stack version for testing 6.8.23-9608d49e

x-pack/elastic-agent/Jenkinsfile.yml
Remove `goIntegTest` for the `x-pack/elastic-agent`
It returns https://github.com/elastic/beats/blob/76bf18b0c2be4c8adf1f2a0f9168aadcd04e8593/dev-tools/mage/target/integtest/notests/integtest.go#L27-L30
https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats/detail/8.0/186/pipeline/7115#step-14750-log-2
=> ci: elastic-agent goIntegTest is not available

CHANGELOG.next.asciidoc, libbeat/common/kubernetes/metadata/pod_test.go, libbeat/common/kubernetes/metadata/resource.go
This PR adds kubernetes.job.name in Pods' metadata.
It enriches the documents of pods belonging to Jobs with the Job name.
Similar issue where metadata was added for daemonsets https://github.com/elastic/beats/pull/26808
=> Add kubernetes job name as the controller

x-pack/functionbeat/function/beater/functionbeat.go, x-pack/functionbeat/manager/beater/functionbeat.go, x-pack/functionbeat/manager/cmd/root.go
This PR adds a deprecation warning to Functionbeat.
The Beat is going to be removed in the future, in favour of https://github.com/elastic/elastic-serverless-forwarder
=> Add warning about removing Functionbeat

filebeat/docs/filebeat-modules-options.asciidoc, filebeat/docs/getting-started.asciidoc, libbeat/docs/tab-widgets/start.asciidoc, metricbeat/docs/getting-started.asciidoc
=> Fix example command to avoid showing system module under windows

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 4 Jan 2022 12:13:39 GMT, release_branch:master, prefix:, end_time:Tue, 4 Jan 2022 17:59:19 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:master, build_id:8.1.0-1f83f9c5, build_duration_seconds:20740]
=> [automation] update elastic stack version for testing 8.1.0-1f83f9c5

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 4 Jan 2022 00:16:08 GMT, release_branch:8.0, prefix:, end_time:Tue, 4 Jan 2022 06:13:44 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-f6fa8fcc, build_duration_seconds:21456]
=> [automation] update elastic stack version for testing 8.0.0-f6fa8fcc

NOTICE.txt
Update copyright year
Otherwise ` make check-default` fails with 
```
[2022-01-05T03:40:50.014Z] diff --git a/NOTICE.txt b/NOTICE.txt
[2022-01-05T03:40:50.014Z] index 070c3c55b..bc566be38 100644
[2022-01-05T03:40:50.014Z] --- a/NOTICE.txt
[2022-01-05T03:40:50.014Z] +++ b/NOTICE.txt
[2022-01-05T03:40:50.014Z] @@ -1,5 +1,5 @@
[2022-01-05T03:40:50.014Z]  Elastic Beats
[2022-01-05T03:40:50.014Z] -Copyright 2014-2021 Elasticsearch BV
[2022-01-05T03:40:50.014Z] +Copyright 2014-2022 Elasticsearch BV
[2022-01-05T03:40:50.014Z]  
[2022-01-05T03:40:50.014Z]  This product includes software developed by The Apache Software 
[2022-01-05T03:40:50.014Z]  Foundation (http://www.apache.org/).
[2022-01-05T03:40:50.953Z] NOTICE.txt: needs update
[2022-01-05T03:40:50.953Z] Makefile:123: recipe for target …
```
=> notice: update copyright year

x-pack/elastic-agent/CHANGELOG.next.asciidoc, x-pack/elastic-agent/pkg/agent/cmd/container.go, x-pack/elastic-agent/pkg/agent/cmd/setup_config.go
Allow the agent to use basic auth defined by env vars to retrieve a
service token from Elasticsearch and inject it into the config used for
the agent and fleet.
Allow the agent started in a container to use basic auth to contact Elasticsearch and generate a `service_token`.
This should fix the tests which rely on docker-compose.
- Closes #29603
=> Allow elastic agent in containers to use basic auth to get service token

libbeat/docs/shared-autodiscover.asciidoc
/label Enhancement
Improve readability of kubernetes provider section of autodiscover functionality.
I could not comprehend what are the configuration settings for kubernetes type of autodiscovery provider.
It seemd to me the only option to limit filebeat on namespace is using template.
=> docs: reorder kubernetes provider section

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 5 Jan 2022 12:13:57 GMT, release_branch:master, prefix:, end_time:Wed, 5 Jan 2022 19:16:40 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:master, build_id:8.1.0-af114d16, build_duration_seconds:25363]
=> [automation] update elastic stack version for testing 8.1.0-af114d16

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 5 Jan 2022 00:15:29 GMT, release_branch:8.0, prefix:, end_time:Wed, 5 Jan 2022 06:18:31 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-37ccb579, build_duration_seconds:21782]
=> [automation] update elastic stack version for testing 8.0.0-37ccb579

CHANGELOG.next.asciidoc, metricbeat/module/elasticsearch/cluster_stats/data.go, metricbeat/module/elasticsearch/test_elasticsearch.py
Fixes `elasticsearch/cluster_stats` metricset not recording license expiration date correctly. This was initially implemented in https://github.com/elastic/beats/pull/14591 but was removed when getting rid of the xpack logic path.
- added back the integration test covering this logic
- without this fix the Stack monitoring UI won't load with a `basic` license. Verified it now loads and displays correct data
=> cluster_stats: use correct license value

CHANGELOG.next.asciidoc, heartbeat/monitors/active/http/task.go, heartbeat/monitors/active/http/task_test.go, x-pack/heartbeat/heartbeat.yml
This is an attempt to fix the race reported in #29580 by instantiating a separate http request per HTTP task. The theory being that the HTTP library modifies the headers and that the req object is not safe to share.
This has passed manual testing using `mode: all` against endpoints with multiple A records. 
Tests are not included here due to the tricky nature of testing here, but we will do so in a follow-up
=> [Heartbeat] Separate http req per task

heartbeat/scheduler/timerqueue/queue.go
Undoes https://github.com/elastic/beats/pull/27006/files (while preserving the new test), and also cleaning up the syntax using `time.Until`.
The tests introduced in the previous PR should confirm this is now good. There is no adjustment to the CHANGELOG since there is no user-facing effect.
=> [Heartbeat] Use timer.reset now that golang has been updated

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 6 Jan 2022 17:10:48 GMT, release_branch:6.8, prefix:, end_time:Thu, 6 Jan 2022 21:38:35 GMT, manifest_version:2.0.0, version:6.8.23-SNAPSHOT, branch:6.8, build_id:6.8.23-7c0fa232, build_duration_seconds:16067]
=> [automation] update elastic stack version for testing 6.8.23-7c0fa232

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 6 Jan 2022 12:13:22 GMT, release_branch:master, prefix:, end_time:Thu, 6 Jan 2022 18:02:53 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:master, build_id:8.1.0-5e490954, build_duration_seconds:20971]
=> [automation] update elastic stack version for testing 8.1.0-5e490954

libbeat/common/cfgwarn/cfgwarn.go
This PR changes the message emitted by `cfgwarn.Deprecate` if the version is not specified. Previously, if version was not specified, still the `"Will be removed:"` message was added. A few deprecated features in Beats are never going to be removed. Thus, the version is empty. However, with the "Will be removed" addition the message can be misleading.
Avoid user confusion. Some features are deprecated, but will never be removed. For example, we deprecated the `log` input in favour of filestream. But we do not intend to remove the outdated input.
~~- [ ] I have …
=> Do not mention removal if version is not specified in `cfgwarn` messages

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 6 Jan 2022 00:15:44 GMT, release_branch:8.0, prefix:, end_time:Thu, 6 Jan 2022 07:21:30 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-fd4587f2, build_duration_seconds:25546]
=> [automation] update elastic stack version for testing 8.0.0-fd4587f2

CHANGELOG.next.asciidoc, x-pack/auditbeat/module/system/socket/template.go
Updates the `system/socket` dataset to support kernels 5.10+ where the `do_fork` kernel method is replaced by `kernel_clone`.
Lack of support for this method is preventing startup in newer kernels.
- Closes #29607
=> System/socket: Support kernel_clone() replacement for _do_fork()

CHANGELOG.next.asciidoc, libbeat/cmd/instance/beat.go
This PR adds a warning message when users connect to older versions of Elasticsearch. From 8.1, connecting to older versions than the Beat version will be disabled by default.
Manage users' expectations.
Related #29264
=> Warn users when connecting to older Elasticsearch instances

.ci/schedule-daily.groovy, .ci/schedule-weekly.groovy
Use aliases and support current minor release branch and next minor release branch for the two major releases.
We don't need to worry about maintaining those schedule jobs anymore
Requires https://github.com/elastic/apm-pipeline-library/pull/1488
Relies on https://github.com/elastic/apm-pipeline-library/blob/main/vars/bumpUtils.txt
=> ci: uses aliases for the branches

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 10 Jan 2022 00:13:26 GMT, release_branch:7.17, prefix:, end_time:Mon, 10 Jan 2022 06:09:18 GMT, manifest_version:2.0.0, version:7.17.0-SNAPSHOT, branch:7.17, build_id:7.17.0-9b8314f9, build_duration_seconds:21352]
=> [automation] update elastic stack version for testing 7.17.0-9b8314f9

libbeat/beat/events/util.go, libbeat/idxmgmt/std.go, libbeat/idxmgmt/std_test.go
When `@meta.index` is set, Beats no longer concatenates datetime to the end of the index name. Adding the extra suffix is not needed because data streams take care of index naming and maintenance for us.
This change was missing from the original PR. This will probably fix the issue in Stack Monitoring.
Closes #29657
=> Do not add date to index if `@meta.index` is set

filebeat/tests/system/test_modules.py, x-pack/filebeat/module/ibmmq/errorlog/ingest/pipeline.yml, x-pack/filebeat/module/ibmmq/errorlog/test/AMQERR01.log-expected.json, x-pack/filebeat/module/ibmmq/errorlog/test/AMQERR01_QM1.log-expected.json, x-pack/filebeat/module/ibmmq/errorlog/test/AMQERR01_QM2.log-expected.json
Fixes the `@timestamp` parsing in Filebeat's ibmmq module. It had a the following problems:
- Date processor format definition was broken (extra `a` character), which caused the processor to always fail.
- The header date format in some logs was unsupported (`dd.MM.yyyy`).
- The Time() field, with correct TZ and higher precision, was ignored.
Now it will correctly parse the header timestamp for all logs, and use the better Time() field if available.
For proper parsing of dates.
=> ibmmq: Fix timestamp parsing

CHANGELOG.next.asciidoc, libbeat/common/kubernetes/metadata/pod_test.go, libbeat/common/kubernetes/metadata/resource.go
Cherry-pick of PR #28954 to 7.17 branch. Original message: 
This PR adds kubernetes.job.name in Pods' metadata.
It enriches the documents of pods belonging to Jobs with the Job name.
Similar issue where metadata was added for daemonsets https://github.com/elastic/beats/pull/26808
=> Cherry-pick #28954 to 7.17: Add kubernetes job name as the controller

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 10 Jan 2022 00:13:42 GMT, release_branch:8.0, prefix:, end_time:Mon, 10 Jan 2022 06:23:51 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-ed041828, build_duration_seconds:22209]
=> [automation] update elastic stack version for testing 8.0.0-ed041828

CHANGELOG.next.asciidoc, metricbeat/module/kubernetes/_meta/kibana/7/visualization/174a6ad0-30e0-11e7-8df8-6d3604a72912-ecs.json, metricbeat/module/kubernetes/_meta/kibana/7/visualization/da1ff7c0-30ed-11e7-b9e5-2b5b07213ab3-ecs.json, metricbeat/module/kubernetes/_meta/kibana/7/visualization/e1018b90-2bfb-11e7-859b-f78b612cde28-ecs.json
align visualisations with changes in https://github.com/elastic/integrations/pull/2151
align metricbeat kibana visualisation with changes made in https://github.com/elastic/integrations/pull/2151
As described here https://github.com/elastic/kibana/issues/121684 since 7.15 there was a problem due to a misplaced migration causing some visualizations to switch off the "drop last bucket" setting without intention (the default switched from true to false). This can cause visualizations to not show any data even though there is data available. in the case of the usage of the "override index pattern" it is not possible to migrate the "drop series last bucket" setting of the series with overridden index pattern without potentially …
=> Remove overriding of index pattern on the Kubernetes overview dashboard

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 10 Jan 2022 16:00:12 GMT, release_branch:master, prefix:, end_time:Mon, 10 Jan 2022 21:43:47 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:master, build_id:8.1.0-7004acda, build_duration_seconds:20615]
=> [automation] update elastic stack version for testing 8.1.0-7004acda

CHANGELOG.next.asciidoc, libbeat/processors/add_process_metadata/add_process_metadata.go, libbeat/processors/add_process_metadata/cache.go, libbeat/processors/add_process_metadata/cache_test.go
The eviction policy implemented here guarantees a hard limit to the number of entries
in the cache and provides a downward force on the number of entries over time with an
exponential decay on the fraction of entries that are older than the cache expiration
duration.
This fixes a memory leak in auditbeat on systems with high `kernel.pid_max`.
N/A
Run `go test` in libbeat/processors/add_process_metadata.
- Closes #24890.
N/A
N/A
N/A
=> libbeat/processors/add_process_metadata: implement a process cache eviction policy

.ci/packer_cache.sh, CHANGELOG.next.asciidoc, auditbeat/Dockerfile, dev-tools/packaging/packages.yml, dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl, dev-tools/packaging/templates/docker/Dockerfile.tmpl, filebeat/Dockerfile, heartbeat/Dockerfile, libbeat/Dockerfile, metricbeat/Dockerfile, packetbeat/Dockerfile, x-pack/functionbeat/Dockerfile, x-pack/libbeat/Dockerfile
Change the docker image from CentOS 7 to Ubuntu 20.04.
Note: Takes over from where pull #29374 left off. 
Closes #29255
- Closes #29255
=> Change docker image from CentOS 7 to Ubuntu 20.04

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 11 Jan 2022 17:11:50 GMT, release_branch:6.8, prefix:, end_time:Tue, 11 Jan 2022 21:33:06 GMT, manifest_version:2.0.0, version:6.8.23-SNAPSHOT, branch:6.8, build_id:6.8.23-d234ee69, build_duration_seconds:15676]
=> [automation] update elastic stack version for testing 6.8.23-d234ee69

CHANGELOG.next.asciidoc, libbeat/README.md, x-pack/heartbeat/monitors/browser/synthexec/enrich.go, x-pack/heartbeat/monitors/browser/synthexec/enrich_test.go, x-pack/heartbeat/monitors/browser/synthexec/execmultiplexer.go, x-pack/heartbeat/monitors/browser/synthexec/execmultiplexer_test.go, x-pack/heartbeat/monitors/browser/synthexec/synthexec.go
Fixes #28770.
This PR ensures that Heartbeat will add a summary to journeys in which the `node` subprocess for [the `synthetics` runner](https://github.com/elastic/synthetics) crashes before emitting a `journey:end` event.
This change will ensure that _all_ journeys will contain a summary, even the ones which cause the runner itself to exit earlier.
To better understand how Heartbeat interfaces with the `synthetics` runner, and thus understand this fix, see the section below.
Before I explain how to test this PR, it's worth explaining how Heartbeat and the Synthetics runner work together.
Currently, `heartbeat` will use the `elastic-synthetics` executable, which comes from [the `synthetics` runner project](https://github.com/elastic/synthetics), to run `inline` journeys (like the ones you …
=> Add summary to journeys which don't emit journey:end (early node subprocess exits)

CHANGELOG.next.asciidoc, x-pack/winlogbeat/module/routing/ingest/routing.yml
- Added the two provider names currently supported by the Security pipeline
to the conditional check in the routing pipeline. These two providers are
`Microsoft-Windows-Eventlog` and `Microsoft-Windows-Security-Auditing`.
- This will prevent unsupported providers such as "AD FS" from being
enriched with incorrect information.
- Different log providers may use the same event ID. When a pipeline handles an event and blindly acts on the event ID without considering the provider, the event may be enriched with the wrong metadata.
- ~~[ ] I have added tests that prove my fix is …
=> [Winlogbeat] Add provider name to Security routing pipeline check

x-pack/elastic-agent/pkg/agent/cmd/container.go
Fixes #29799.
It was always calling `ensureServiceToken` but that should only be done in the case that Fleet Server is enabled for the container.
Otherwise its not possible to start the container without it trying to communicate with Kibana.
Build the container:
```
$ PLATFORMS="linux/amd64" mage dev:package
$ docker run -it docker.elastic.co/beats/elastic-agent:8.1.0
```
- Closes #29799
=> [Elastic Agent] Fix issue with ensureServiceToken.

CHANGELOG.next.asciidoc, auditbeat/auditbeat.reference.yml, filebeat/Jenkinsfile.yml, filebeat/filebeat.reference.yml, filebeat/tests/system/test_modules.py, heartbeat/heartbeat.reference.yml, libbeat/_meta/config/output-elasticsearch.reference.yml.tmpl, libbeat/cmd/instance/beat.go, libbeat/outputs/elasticsearch/client.go, libbeat/outputs/elasticsearch/config.go, libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc, libbeat/tests/system/config/mockbeat.yml.j2, metricbeat/metricbeat.reference.yml, packetbeat/packetbeat.reference.yml, winlogbeat/winlogbeat.reference.yml, x-pack/auditbeat/auditbeat.reference.yml, x-pack/filebeat/Jenkinsfile.yml, x-pack/filebeat/filebeat.reference.yml, x-pack/functionbeat/functionbeat.reference.yml, x-pack/heartbeat/heartbeat.reference.yml, x-pack/metricbeat/metricbeat.reference.yml, x-pack/osquerybeat/osquerybeat.reference.yml, x-pack/packetbeat/packetbeat.reference.yml, x-pack/winlogbeat/winlogbeat.reference.yml
This PR adds a new callback to all Elasticsearch connections to check if the version is at least the same as the Beat. The check can be disabled by setting the new option `output.elasticsearch.allow_older_versions` to true.
By restricting the Elasticsearch versions we can provide optimal experience. 
Closes https://github.com/elastic/beats/issues/29264
=> Only connect to Elasticsearch instances with the same version or newer

CHANGELOG.next.asciidoc, libbeat/common/kubernetes/metadata/metadata.go, libbeat/common/kubernetes/metadata/node_test.go, libbeat/common/kubernetes/metadata/pod.go, libbeat/common/kubernetes/metadata/pod_test.go, libbeat/common/kubernetes/metadata/service_test.go
node annotations enrichment doesn't work, with the config:
```
add_resource_metadata:
node:
include_annotations: ["test.annotation"]
```
events were not enriched with nodes annotation metadata
1. Create a kind kubernetes cluster.
2. run metricbeat ([how-to](https://github.com/elastic/beats/blob/master/metricbeat/module/kubernetes/_meta/test/docs/README.md)) with k8s configuration:
```
kubernetes.yml: |-
- module: kubernetes
metricsets:
- node
- system
- pod
- container
- volume
add_resource_metadata:
node:
include_annotations: ["another.annotation", "example.annotation"]
period: 10s
host: ${NODE_NAME}
hosts: ["https://${NODE_NAME}:10250"]
bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token …
```
=> Fix annotation enrichment

CHANGELOG.next.asciidoc, x-pack/filebeat/input/awscloudwatch/input.go
Remove the old `awscloudwatch` name for `aws-cloudwatch` Filebeat input.
=> Remove deprecated old name for aws cloudwatch input

heartbeat/docs/monitors/monitor-browser.asciidoc
We mention that you need the container in the synthetics guide, but not on this page, this is a bit cleaner.
=> Add note on docker container as a requirement for browser monitors

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 13 Jan 2022 00:12:24 GMT, release_branch:7.17, prefix:, end_time:Thu, 13 Jan 2022 05:42:43 GMT, manifest_version:2.0.0, version:7.17.0-SNAPSHOT, branch:7.17, build_id:7.17.0-560490e9, build_duration_seconds:19819]
=> [automation] update elastic stack version for testing 7.17.0-560490e9

libbeat/docs/howto/load-index-templates.asciidoc, libbeat/docs/upgrading.asciidoc
This PR updates the documentation for loading index templates manually. The endpoint used in the documentation was outdated. That lead to some confusion.
To let our users copy-paste calls and end up with the desired effects.
=> Update Index template loading guide to use the correct endpoint

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 17 Jan 2022 12:13:20 GMT, release_branch:master, prefix:, end_time:Mon, 17 Jan 2022 16:56:45 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:master, build_id:8.1.0-677b9ef0, build_duration_seconds:17005]
=> [automation] update elastic stack version for testing 8.1.0-677b9ef0

x-pack/elastic-agent/pkg/agent/application/gateway/fleet/fleet_gateway.go, x-pack/elastic-agent/pkg/agent/application/info/agent_id.go, x-pack/elastic-agent/pkg/agent/application/upgrade/rollback.go, x-pack/elastic-agent/pkg/agent/cmd/enroll_cmd.go, x-pack/elastic-agent/pkg/agent/cmd/install.go, x-pack/elastic-agent/pkg/cli/confirm.go, x-pack/elastic-agent/pkg/cli/input.go, x-pack/elastic-agent/pkg/core/backoff/backoff.go, x-pack/elastic-agent/pkg/core/backoff/backoff_test.go, x-pack/elastic-agent/pkg/core/backoff/equal_jitter.go, x-pack/elastic-agent/pkg/core/backoff/exponential.go, x-pack/elastic-agent/pkg/core/retry/retrystrategy.go, x-pack/elastic-agent/pkg/core/retry/retrystrategy_test.go
Small helpers are copied to Agent:
* `github.com/elastic/beats/v7/libbeat/common/backoff`
* `github.com/elastic/beats/v7/libbeat/common/cli`
We are preparing for moving Agent out of this repository. Hence, we have to end the dependency on Libbeat.
Little copying is better than little dependency. In that vein, I am copying several small helpers from Libbeat to Agent to reduce the dependency on Beats.  …
=> Copy small helpers to Elastic Agent from Beats to reduce dependency on Libbeat

libbeat/processors/dissect/docs/dissect.asciidoc
Improves documentation for the filebeat `dissect` processor.
The `dissect` processor has only 1 example of configuration with (possibly) an error in the suggested syntax.
I came across it while trying to setup a filebeat instance.
https://www.elastic.co/guide/en/beats/filebeat/current/dissect.html#dissect-example
Deos the changelog need to be updated for doc-only changes?
=> doc: update filebeat dissect processor field tokenization example

CHANGELOG.next.asciidoc, libbeat/esleg/eslegclient/bulkapi.go, libbeat/idxmgmt/std.go, libbeat/outputs/elasticsearch/client.go, libbeat/outputs/elasticsearch/client_integration_test.go, libbeat/outputs/elasticsearch/client_test.go, libbeat/outputs/elasticsearch/death_letter_selector.go, libbeat/outputs/outil/select.go, libbeat/outputs/output_reg.go
This PR adds support for requiring alias when using ILM. From now on a `Selector` can tell Elasticsearch client if the target we are shipping events to is an alias or an index. By default, we consider everything an index, and only consider a target an alias when ILM is enabled.
The feature is only supported since ES 7.10, so if the user tries to connect to an older version, we cannot help them with this parameter.
We see issues around ILM sometimes where users have deleted their write alias causing running beats instances to auto-create an index where the write alias should (with auto-mappings to boot, since the template won't be applied). To a …
=> Enable require_alias for Bulk requests for all actions when target is a write alias

filebeat/docs/getting-started.asciidoc
This PR clarifies that all filesets are disabled in module configuration files by default.
Enabling filesets manually is a breaking change in 8.0. We should tell users about the change, so they can adopt.
=> Note that filesets are disabled by default in Filebeat documentation

dev-tools/mage/common.go
This adds a check for 0 when determining the concurrency limit used by mage during a build.
`docker info -f '{{ json .}}'` exits with 0 even if there was an error, so the check for `err == nil` doesn't catch errors, and the default int value of 0 is used when trying to read `info.NCPU`. This leads to the confusing behaviour where the build stops and hangs forever with no errors and no indication that anything has gone wrong unless you build with --verbose.
Stop the docker daemon `systemctl stop docker` and ensure you don't have it set to automatically start up, either by disabling the socket or masking the service.
Ensure you haven't exported `MAX_PARALLEL` in your shell.
Test to make sure the daemon isn't running by executing `docker info -f '{{ json .}}'` and validating that the output …
=> Check that `info.NCPU` is not zero

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Sun, 16 Jan 2022 00:18:34 GMT, release_branch:7.17, prefix:, end_time:Sun, 16 Jan 2022 06:05:07 GMT, manifest_version:2.0.0, version:7.17.0-SNAPSHOT, branch:7.17, build_id:7.17.0-079761a0, build_duration_seconds:20793]
=> [automation] update elastic stack version for testing 7.17.0-079761a0

filebeat/docs/inputs/input-filestream-reader-options.asciidoc
Type of change: Docs
The indentation is incorrect in the `filestream` `parsers` example snippets — filebeat expects each `parsers` array item to be an object with a single key containing an object of parameters, but the examples show each `parsers` array item as an object with multiple keys.  The existing syntax causes filebeat to fail to start.  This MR fixes the documentation to produce the YAML structure that filebeat expects, so that the snippets can be successfully used in filebeat.
The existing documentation is inaccurate, causing confusion about what YAML structure filebeat actually expects.
- ~~[ ] I have made corresponding change to the …
=> Fix YAML indentation in `parsers` examples

CHANGELOG.next.asciidoc, heartbeat/tests/system/test_icmp.py
Fixes broken macos python e2e test
This test is broken in `master`.
`mage pythonUnitTests`
=> [Heartbeat] Fix broken macOS ICMP test

CHANGELOG.next.asciidoc, x-pack/auditbeat/module/system/process/namepace_linux.go, x-pack/auditbeat/module/system/process/namepace_other.go, x-pack/auditbeat/module/system/process/process.go
This change prevents fruitless attempts to hash files in mnt namespaces that differ from the running auditbeat process.
See linked related issues.
N/A
`mage test`
- Relates #25777
- Relates #29678
See linked issues.
N/A
N/A
=> x-pack/auditbeat/module/system/process: don't try to hash files in other namespaces

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 18 Jan 2022 17:39:32 GMT, release_branch:7.17, prefix:, end_time:Tue, 18 Jan 2022 22:05:30 GMT, manifest_version:2.0.0, version:7.17.0-SNAPSHOT, branch:7.17, build_id:7.17.0-68da5d12, build_duration_seconds:15958]
=> [automation] update elastic stack version for testing 7.17.0-68da5d12

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 18 Jan 2022 00:19:31 GMT, release_branch:master, prefix:, end_time:Tue, 18 Jan 2022 05:11:55 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:master, build_id:8.1.0-f5a18001, build_duration_seconds:17544]
=> [automation] update elastic stack version for testing 8.1.0-f5a18001

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 18 Jan 2022 22:48:03 GMT, release_branch:8.0, prefix:, end_time:Wed, 19 Jan 2022 03:31:00 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-129ef708, build_duration_seconds:16977]
=> [automation] update elastic stack version for testing 8.0.0-129ef708

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 19 Jan 2022 20:27:43 GMT, release_branch:6.8, prefix:, end_time:Thu, 20 Jan 2022 00:55:02 GMT, manifest_version:2.0.0, version:6.8.24-SNAPSHOT, branch:6.8, build_id:6.8.24-7dcce198, build_duration_seconds:16039]
=> [automation] update elastic stack version for testing 6.8.24-7dcce198

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 19 Jan 2022 03:44:12 GMT, release_branch:8.0, prefix:, end_time:Wed, 19 Jan 2022 22:42:15 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-f196e060, build_duration_seconds:68283]
=> [automation] update elastic stack version for testing 8.0.0-f196e060

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 20 Jan 2022 00:13:49 GMT, release_branch:7.17, prefix:, end_time:Thu, 20 Jan 2022 04:46:05 GMT, manifest_version:2.0.0, version:7.17.0-SNAPSHOT, branch:7.17, build_id:7.17.0-e1efbe3a, build_duration_seconds:16336]
=> [automation] update elastic stack version for testing 7.17.0-e1efbe3a

metricbeat/docs/modules/istio.asciidoc, x-pack/metricbeat/module/istio/_meta/docs.asciidoc
Small correction about default metricsets. There are no default metricsets in `istio` module.
Wait until https://github.com/elastic/beats/pull/29873 is merged.
=> Fix istio docs regarding default metricsets

x-pack/elastic-agent/CHANGELOG.next.asciidoc, x-pack/elastic-agent/pkg/agent/cmd/setup_config.go
Allow elastic-agent container to read KIBANA_USERNAME/KIBANA_PASSWORD as
credentials to use to generate a service_token as the env vars were
erroniously removed.
Be consistent with the Elastic Stack env vars.
- [] ~~I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~
Use `KIBANA_USERNAME`/`KIBANA_PASSWORD` env vars in container
=> Re add the ability for container commands to access kibana env vars

x-pack/elastic-agent/pkg/agent/cmd/container.go
Fixes issue where service token creating was being running when the container was setup to only enroll.
Service token should only be created in the case that Fleet in Kibana is getting bootstrapped or a Fleet Server is being bootstrapped by the Elastic Agent.
- Closes #29921
=> [Elastic Agent] Change to check for fleet server enable not fleet enrollment for ensureServiceToken

x-pack/elastic-agent/CHANGELOG.next.asciidoc, x-pack/elastic-agent/pkg/agent/cmd/diagnostics.go
Add the configs that are output from elastic-agent inspect output to the
bundle generated by elastic-agent diagnostics collect. Files are named
as ProcID_RouteKey.
Include the config that's sent from the agent to underlying processes in the diagnostic bundles to allow us to more easily debug config errors.
Start an agent.
Run `elastic-agent diagnostics collect` once the agent is healthy
Inspect archive's config files.
- Closes #29898
=> Add beat/process config to elastic agent diagnostics collect

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 20 Jan 2022 17:12:05 GMT, release_branch:6.8, prefix:, end_time:Thu, 20 Jan 2022 21:06:57 GMT, manifest_version:2.0.0, version:6.8.24-SNAPSHOT, branch:6.8, build_id:6.8.24-98b58fc7, build_duration_seconds:14092]
=> [automation] update elastic stack version for testing 6.8.24-98b58fc7

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Fri, 21 Jan 2022 00:13:13 GMT, release_branch:7.17, prefix:, end_time:Fri, 21 Jan 2022 04:40:52 GMT, manifest_version:2.0.0, version:7.17.0-SNAPSHOT, branch:7.17, build_id:7.17.0-1bd58b32, build_duration_seconds:16059]
=> [automation] update elastic stack version for testing 7.17.0-1bd58b32

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Sun, 23 Jan 2022 17:11:25 GMT, release_branch:6.8, prefix:, end_time:Sun, 23 Jan 2022 21:37:40 GMT, manifest_version:2.0.0, version:6.8.24-SNAPSHOT, branch:6.8, build_id:6.8.24-249d8e5f, build_duration_seconds:15975]
=> [automation] update elastic stack version for testing 6.8.24-249d8e5f

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 24 Jan 2022 00:15:35 GMT, release_branch:8.0, prefix:, end_time:Mon, 24 Jan 2022 04:55:37 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-6ce456eb, build_duration_seconds:16802]
=> [automation] update elastic stack version for testing 8.0.0-6ce456eb

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Sun, 23 Jan 2022 00:12:41 GMT, release_branch:7.17, prefix:, end_time:Sun, 23 Jan 2022 04:42:39 GMT, manifest_version:2.0.0, version:7.17.0-SNAPSHOT, branch:7.17, build_id:7.17.0-ab4975a2, build_duration_seconds:16198]
=> [automation] update elastic stack version for testing 7.17.0-ab4975a2

metricbeat/docker-compose.yml, metricbeat/module/logstash/docker-compose.yml, testing/environments/latest.yml, testing/environments/prev-minor.yml, x-pack/metricbeat/docker-compose.yml
Merge only after the release of 7.16.3.
=> [Release] Update test environments for 7.16.4

.ci/packaging.groovy
Run `docker login` earlier than when pushing
To allow pulling from a different docker registry
- Relates https://github.com/elastic/golang-crossbuild/pull/149/files#
=> ci: docker login for pulling

CHANGELOG.next.asciidoc, libbeat/autodiscover/providers/kubernetes/config.go, libbeat/autodiscover/providers/kubernetes/pod.go, libbeat/processors/add_kubernetes_metadata/config.go, libbeat/processors/add_kubernetes_metadata/kubernetes.go, metricbeat/docs/modules/kubernetes.asciidoc, metricbeat/metricbeat.reference.yml, metricbeat/module/kubernetes/_meta/config.reference.yml, metricbeat/module/kubernetes/_meta/config.yml, metricbeat/module/kubernetes/util/kubernetes.go, metricbeat/modules.d/kubernetes.yml.disabled, x-pack/metricbeat/metricbeat.reference.yml
This PR adds `namespace` and moves `host` to `node` settings under the `kubernetes` module. 
In order to have alignment between the metadata configurations.
Closes https://github.com/elastic/beats/issues/29132
=> Allign k8s configuration settings

x-pack/elastic-agent/pkg/core/plugin/common.go
Check the constant condition and exit early from IsRestartNeeded()
if not set.
Avoids unneeded processing (and IMO increases readability).
=> Return early from IsRestartNeeded()

CHANGELOG.next.asciidoc, x-pack/filebeat/input/awss3/s3_objects.go
Directly check the byte stream for the gzip magic number and deflate
compression type. Avoid using http.DetectContentType because it returns
the first match it finds while checking many signatures.
Closes #29968
Incorrect content type detection can result in garbage data being ingested.
- Closes #29968
=> [Filebeat] Improve aws-s3 gzip file detection to avoid false negatives

CHANGELOG.next.asciidoc, heartbeat/monitors/active/icmp/stdloop.go
Just change size of ICMP packet for Heartbeat. The recommanded size for a valid ICMP packet is 64 byte (with headers)
Some hosts don't respond with a small ICMP packet
Compile & configure an ICMP monitor an check packet size with tcpdump
=> [Heartbeat] Change size of data on ICMP packet

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Fri, 21 Jan 2022 05:15:54 GMT, release_branch:7.16, prefix:, end_time:Fri, 21 Jan 2022 10:50:26 GMT, manifest_version:2.0.0, version:7.16.4-SNAPSHOT, branch:7.16, build_id:7.16.4-206b88b5, build_duration_seconds:20072]
=> [automation] update elastic stack version for testing 7.16.4-206b88b5

dev-tools/mage/crossbuild.go, libbeat/common/backoff/equal_jitter.go, libbeat/logp/configure/logging.go, libbeat/logp/core.go, x-pack/elastic-agent/magefile.go, x-pack/elastic-agent/pkg/agent/application/gateway/fleet/fleet_gateway.go, x-pack/elastic-agent/pkg/agent/application/pipeline/pipeline.go, x-pack/elastic-agent/pkg/agent/application/reexec/manager.go, x-pack/elastic-agent/pkg/core/server/server.go, x-pack/elastic-agent/pkg/core/status/reporter.go
It fixes some typos and Go conventions on the code's comments.
To keep consistent with the standard English.
=> [Elastic Agent] Fix some typos

libbeat/docs/dashboardsconfig.asciidoc
This PR adds clarifications about the behaviour of dashboard loading in Beats.
Previously, it was not clearly communicated in the documentation that dashboard loading is automatically enabled if any of the settings under `setup.dashboards` is configured. To avoid further confusion, I am adding a similar note to SSL settings: https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-ssl.html#enabled …
=> Add note to documentation about dashboard loading in Beats

auditbeat/module/file_integrity/metricset_test.go
Issue: https://github.com/elastic/beats/issues/29992
Use `CI=true` to skip the test. It looks like `BUILD_ID` is not being set in [this](https://github.com/elastic/beats/runs/4885891319?check_suite_focus=true) execution.
=> [auditbeat] Flaky: use CI=true to skip test

libbeat/common/productorigin/productorigin.go, libbeat/esleg/eslegclient/connection.go, libbeat/esleg/eslegclient/connection_test.go, metricbeat/module/elasticsearch/metricset.go, metricbeat/module/kibana/settings/settings.go, metricbeat/module/kibana/stats/stats.go, metricbeat/module/kibana/status/status.go
Adds the x-elastic-product-origin header when communicating with Elasticsearch or Kibana.
If Elasticsearch deprecates an API we use in the future, this header will prevent Kibana from presenting the warning to the user. It will also tag the Elasticsearch deprecation log message with the header value to more easily attribute deprecated API usage to products
Note that there is no known usage of deprecated Elasticsearch APIs in beats currently.
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have added tests that prove my fix is effective or that my feature …
=> Add the Elastic product origin header when talking to Elasticsearch or Kibana.

dev-tools/mage/crossbuild.go
Revert changes introduced in #29890 that prevented all the artifacts to
be build.
-
=> Revert changes in the artifact build from #29890

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 25 Jan 2022 17:11:44 GMT, release_branch:6.8, prefix:, end_time:Tue, 25 Jan 2022 21:11:03 GMT, manifest_version:2.0.0, version:6.8.24-SNAPSHOT, branch:6.8, build_id:6.8.24-3c1da3a7, build_duration_seconds:14359]
=> [automation] update elastic stack version for testing 6.8.24-3c1da3a7

dev-tools/mage/build.go
When the agent is built for development it keeps the debug symbols, do not inline nor optimize so it's possible to debug using delve.
It also fixes a typo.
Improves developer experience by making it ready for debug when building for development.
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] I have made corresponding change to the default configuration files
Build with `DEV=true`, then run it with delve and connect to remote debug
Using GoLand, you can …
=> [Elastic Agent] Keep debug symbols, no inline and no optimisations for dev builds

CHANGELOG-developer.next.asciidoc, x-pack/metricbeat/module/gcp/billing/billing.go, x-pack/metricbeat/module/gcp/metrics/metricset.go
Adds support for `credentials_json` metricset configuration parameter to `gcp.billing` and `gcp.metrics` metricset.
This change is required to support at metricset level this parameter that is already supported in Kibana Integration UI.
Filebeat `gcp` inputs support this parameter and due to the [limitations in Kibana](https://github.com/elastic/kibana/issues/112272) is not possible to use input level variables but globals are required. This PR fixes this in order to prevent having a configuration parameter in the UI that is not used by inputs.
1. Build `x-pack/metricbeat`
2. Configure `gcp` module with:
```
- module: gcp
metricsets:
- billing
zone: "eu-"
project_id: "..."
credentials_json: '' # add your GCP SA …
```
=> [Metricbeat] support credentials_json in gcp module

testing/environments/prev-minor.yml
This PR updates the `prev-minor.yml` environment to the latest 8.0.0 release on master. Master is at the moment 8.1, hence the previous minor is 8.0.0.
Without this lots of module tests fail. Also, the name implies previous minor version. But in reality it was set to 7.15 which is not the previous minor.
=> Update prev-minor testing environment to 8.0 on master (8.1)

libbeat/outputs/kafka/docs/kafka.asciidoc
Adds an important note to the Kafka output documentation.
Some customers find the default behavior when using Kafka outputs
unexpected.There are 2 possible options:
1. Message timestamp to be assigned on event creation (in beats), when the actual event was emitted and then propagated to Kafka
2. Message timestamp to be assigned when Kafka actually receives the
message
Since beats always set the message timestamp for Kafka version 0.10.0.0+ it's
worth to document how to switch between the 2 options in Kafka
configuration using the `log.message.timestamp.type` parameter.
=> Document how timestamps set in Kafka messages affect retention

dev-tools/mage/crossbuild.go
Fixed creating an empty array way breaking check down the stack.
See
https://github.com/elastic/beats/blob/6b417428d30971c75469651419cf39874189f268/dev-tools/mage/pkg.go#L121
-
=> Correctly fixe how selected packages are defined

CHANGELOG.next.asciidoc, x-pack/filebeat/processors/decode_cef/cef/cef.go, x-pack/filebeat/processors/decode_cef/cef/cef.rl, x-pack/filebeat/processors/decode_cef/cef/cef_test.go, x-pack/filebeat/processors/decode_cef/cef/parser.go
When recovering from an invalid extension value the escape sequence state was
not cleared. This caused the parser to attempt to unescape the next extension which
resulted in invalid data or a panic.
Fixes #30010
The parser could panic.
- Fixes #30010
=> [Filebeat] Fix panic in decode_cef when recovering from invalid data

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 26 Jan 2022 05:13:33 GMT, release_branch:7.16, prefix:, end_time:Wed, 26 Jan 2022 10:51:23 GMT, manifest_version:2.0.0, version:7.16.4-SNAPSHOT, branch:7.16, build_id:7.16.4-1b320a84, build_duration_seconds:20270]
=> [automation] update elastic stack version for testing 7.16.4-1b320a84

CHANGELOG.next.asciidoc, metricbeat/docs/modules/enterprisesearch.asciidoc, metricbeat/helper/elastic/elastic.go, x-pack/metricbeat/metricbeat.reference.yml, x-pack/metricbeat/module/enterprisesearch/_meta/config-xpack.yml, x-pack/metricbeat/module/enterprisesearch/_meta/docs.asciidoc, x-pack/metricbeat/module/enterprisesearch/docker-compose.yml, x-pack/metricbeat/module/enterprisesearch/health/data.go, x-pack/metricbeat/module/enterprisesearch/health/health.go, x-pack/metricbeat/module/enterprisesearch/stats/data.go, x-pack/metricbeat/module/enterprisesearch/stats/stats.go, x-pack/metricbeat/module/enterprisesearch/test_enterprisesearch.py, x-pack/metricbeat/modules.d/enterprisesearch-xpack.yml.disabled, x-pack/metricbeat/modules.d/enterprisesearch.yml.disabled
Add `xpack.enabled` support for Enterprise Search Metricbeat module.
This allows metrics retrieved to be available in Stack Monitoring Kibana plugin, as this plugin changes the indices retrieved from `.metricbeat-*` to `.monitoring-*`. `xpack.enabled: true` allows changing the index to be used to .monitoring-*, as already implemented for Elasticsearch, Kibana and Logstash modules.
This change is needed to allow Enterprise Search Metricbeat module to produce metrics that can be consumed by Stack Monitoring Kibana plugin. Stack Monitoring won't display Enterprise Search metrics otherwise.
- Relates https://github.com/elastic/kibana/issues/121975
- Relates https://github.com/elastic/enterprise-search-team/issues/987
=> Metricbeat enterprise search module: add xpack.enabled support

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 27 Jan 2022 00:16:25 GMT, release_branch:8.0, prefix:, end_time:Thu, 27 Jan 2022 04:56:04 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-e2e78bad, build_duration_seconds:16779]
=> [automation] update elastic stack version for testing 8.0.0-e2e78bad

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 27 Jan 2022 00:13:53 GMT, release_branch:7.17, prefix:, end_time:Thu, 27 Jan 2022 04:39:56 GMT, manifest_version:2.0.0, version:7.17.0-SNAPSHOT, branch:7.17, build_id:7.17.0-b9de125e, build_duration_seconds:15963]
=> [automation] update elastic stack version for testing 7.17.0-b9de125e

.github/stale.yml
Update when to update to stale any issues or PRs. 
Ignore whether they are assigned to any given project.
Tidy up
https://github.com/probot/stale
=> probot: update stale dates

CHANGELOG.next.asciidoc, auditbeat/module/auditd/audit_linux.go
Auditbeat adds `event.original` when there is a parse failure, but it wasn't
including the error message. Having the error helps you understand what
went wrong.
Example output:
`{"@timestamp":"2022-01-26T00:15:20.241Z","@metadata":{"beat":"auditbeat","type":"_doc","version":"8.1.0"},"error":{"message":"missing syscall message in compound event"},"event":{"original":["type=UNKNOWN[1333] msg=audit(1643156118.179:545): op=freq old=36792303616000 new=-176298262528000","type=UNKNOWN[1333] msg=audit(1643156118.179:545): op=tick old=9977 new=10000"],"module":"auditd"},"service":{"type":"auditd"},"host":{"name":"ubuntu-impish"},"agent":{"version":"8.1.0","ephemeral_id":"a6dd5138-f1b2-437a-8b83-324ec09bbaa3","id":"c127e0a1-be4b-4f9f-a5e4-97496699f75e","name":"ubuntu-impish","type":"auditbeat"},"ecs …
=> [Auditbeat] Include the error message with auditd module events

filebeat/generator/fields/fields.go
- bug
Picks up an `err` variable that was being dropped in `filebeat/generator/fields`.
Dropped errors create inexplicable hard-to-find bugs.
-
=> filebeat/generator/fields: fix dropped error

x-pack/osquerybeat/magefile.go
Removes the workaround that was put in place to install msitools on the build docker image during windows build.
Using the newer docker image for the builds with msitools preinstalled.
Closes https://github.com/elastic/beats/issues/29826
- Closes https://github.com/elastic/beats/issues/29826
=> Remove msitools install for windows build, using the latest docker image with msitools preinstalled

filebeat/docs/redirects.asciidoc
Adds a redirect for the [GSuite module](https://www.elastic.co/guide/en/beats/filebeat/7.17/filebeat-module-gsuite.html) page, which has been removed in 8.0+.
https://beats_30034.docs-preview.app.elstc.co/guide/en/beats/filebeat/master/filebeat-module-gsuite.html
We saw this missing page create several broken links in https://github.com/elastic/docs/pull/2312. I've opened https://github.com/elastic/security-docs/pull/1441 to update those links. This adds a redirect for anyone who otherwise lands on the page.
=> [DOCS] Add redirect for GSuite module

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 27 Jan 2022 17:11:11 GMT, release_branch:6.8, prefix:, end_time:Thu, 27 Jan 2022 21:02:06 GMT, manifest_version:2.0.0, version:6.8.24-SNAPSHOT, branch:6.8, build_id:6.8.24-8cc6db42, build_duration_seconds:13855]
=> [automation] update elastic stack version for testing 6.8.24-8cc6db42

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 27 Jan 2022 05:13:38 GMT, release_branch:7.16, prefix:, end_time:Thu, 27 Jan 2022 10:50:41 GMT, manifest_version:2.0.0, version:7.16.4-SNAPSHOT, branch:7.16, build_id:7.16.4-42a1f428, build_duration_seconds:20223]
=> [automation] update elastic stack version for testing 7.16.4-42a1f428

.github/stale.yml
Skip issues/prs with the `flaky-test` label from the stale automation
Issues with flaky test might be idling for some time but they should not be automatically closed.
https://github.com/probot/stale
=> probot[stale]: ignore issues with the tag flaky-test

libbeat/reader/message.go, libbeat/reader/message_test.go
`Message.ToEvent` was not copying the `Message.Privage` field when
converting a Message to `beat.Event`. This commit fixes it.
Fixes: #30031
It fixes the journald input
Use journald input and console output, the events outputted should look like the one described on #30031
- Fixes: #30031
~~## Logs~~
=> libbeat/reader: Fix messge conversion to beat.Event

CHANGELOG.next.asciidoc, libbeat/common/transport/tlscommon/versions_default.go, libbeat/common/transport/tlscommon/versions_legacy.go, libbeat/common/transport/tlscommon/versions_test.go, libbeat/docs/shared-ssl-config.asciidoc, packetbeat/docs/packetbeat-options.asciidoc
Remove SSLv3 as an option in libbeat configurations and update the minimum version in the code and documentation.
SSL3 is old, deprecated, and should not be used for secure communication.
=> Remove SSL3 support from libbeat and its documentation.

filebeat/input/journald/config.go, filebeat/input/journald/config_test.go, filebeat/input/journald/input.go
To make transitioning from 7.x/8.0 to 8.1 easier allow the old format to continue working
by translating it internally to the new format. This logs a deprecation warning when the
old config format is detected.
This will make it easier for Agent users to migrate from 7.x/8.0 to 8.1. There will be time window
when integrations with the old format are running with the new Agent.
- Relates https://github.com/elastic/integrations/issues/2602
- Relates https://github.com/elastic/beats/pull/29294#issuecomment-995311920
```json
{
"@timestamp": "2022-01-26T17:26:47.443Z",
"ecs.version": "1.6.0",
"log.level": "warn",
"log.logger": "cfgwarn",
"file.line": 97,
"file.name": "journald/config.go"
},
"message": "DEPRECATED: Please migrate your journald input's include_matches config to …
```
=> [Filebeat] journald: Make include_matches backwards compatible with 7.x config

CHANGELOG.next.asciidoc, libbeat/processors/add_process_metadata/add_process_metadata.go, libbeat/processors/add_process_metadata/add_process_metadata_test.go, libbeat/processors/add_process_metadata/config.go, libbeat/processors/add_process_metadata/docs/add_process_metadata.asciidoc
This replays the additions in libbeat/processors/add_process_metadata and related
changes from dde7a1f.
This is intended to ease user transition to 8.0 when `process.ppid` will no longer exist.
- Closes #30070.
=> libbeat/processors/add_process_metadata: backport process.parent.pid field from 8.0

.github/stale.yml
Resolves https://github.com/elastic/beats/issues/30081
Update stale config to mark issues as staled after 365 days and close them 180 days later.
It will help us keep an up to date repository.
-
=> Update stale config following

x-pack/filebeat/module/barracuda/spamfirewall/config/liblogparser.js, x-pack/filebeat/module/barracuda/waf/config/liblogparser.js, x-pack/filebeat/module/bluecoat/director/config/liblogparser.js, x-pack/filebeat/module/cisco/meraki/config/liblogparser.js, x-pack/filebeat/module/cisco/nexus/config/liblogparser.js, x-pack/filebeat/module/cylance/protect/config/liblogparser.js, x-pack/filebeat/module/f5/bigipafm/config/liblogparser.js, x-pack/filebeat/module/f5/bigipapm/config/liblogparser.js, x-pack/filebeat/module/fortinet/clientendpoint/config/liblogparser.js, x-pack/filebeat/module/fortinet/fortimail/config/liblogparser.js, x-pack/filebeat/module/fortinet/fortimanager/config/liblogparser.js, x-pack/filebeat/module/imperva/securesphere/config/liblogparser.js, x-pack/filebeat/module/infoblox/nios/config/liblogparser.js, x-pack/filebeat/module/juniper/junos/config/liblogparser.js, x-pack/filebeat/module/juniper/netscreen/config/liblogparser.js, x-pack/filebeat/module/microsoft/dhcp/config/liblogparser.js, x-pack/filebeat/module/netscout/sightline/config/liblogparser.js, x-pack/filebeat/module/proofpoint/emailsecurity/config/liblogparser.js, x-pack/filebeat/module/radware/defensepro/config/liblogparser.js, x-pack/filebeat/module/snort/log/config/liblogparser.js, x-pack/filebeat/module/sonicwall/firewall/config/liblogparser.js, x-pack/filebeat/module/sophos/utm/config/liblogparser.js, x-pack/filebeat/module/squid/log/config/liblogparser.js, x-pack/filebeat/module/tomcat/log/config/liblogparser.js, x-pack/filebeat/module/zscaler/zia/config/liblogparser.js
Rsa parsers support different functions for extracting components from an URL in order to populate internal fields. Until now, if this operation resulted in an empty field because the given component didn't exist, or the URL was invalid, an error message would be printed to the log.
Due to some parsers' sloppy use of these functions, it's better to turn the error message into a debug log, to avoid generating too many unnecessary logs.
- ~~[ ] I have added an entry in …
=> rsa2elk: fix unnecessarily noisy error message

CHANGELOG.next.asciidoc, metricbeat/module/rabbitmq/connection/connection.go, metricbeat/module/rabbitmq/connection/data.go, metricbeat/module/rabbitmq/exchange/data.go, metricbeat/module/rabbitmq/exchange/exchange.go, metricbeat/module/rabbitmq/node/data.go, metricbeat/module/rabbitmq/node/node.go, metricbeat/module/rabbitmq/queue/data.go, metricbeat/module/rabbitmq/queue/queue.go
RabbitMQ uses strict parsing for fields. If a single field is missing, the entire event is discarded, regardless of having another 100 found fields in there. 
This PR removes this strict checking, allowing partial events of RabbitMQ.
=> [Metricbeat] Remove strict parsing on RabbitMQ module

CHANGELOG.next.asciidoc, libbeat/beat/event.go, libbeat/beat/event_test.go, libbeat/processors/actions/add_fields.go, libbeat/processors/actions/add_fields_test.go, libbeat/processors/actions/add_labels_test.go, libbeat/processors/actions/add_tags_test.go, libbeat/processors/actions/common_test.go
We have a couple of special cases when we set fields on the event
based on target field keys:
1. `@timestamp` must be set directly to the `Timestamp` property of
the event
2. `@metadata.*` must be put in the `Meta` map instead of `Fields`
3. The rest is put in `Fields`
Currently the `Event` struct has the `PutValue` function to account for
these special cases, however, some of the processors use
`event.Fields.DeepUpdate` which would not handle the special cases.
To make it easier to migrate those processors, the new function
`event.DeepUpdate` (that can be safely used with the
special cases) is introduced.
As an example, the `add_fields` processor is migrated to using this
new function and its tests have been updated to assert the correct behaviour.
**It's a partial solution just to demo …
=> Implement `DeepUpdate` on event and use it in `add_fields` processor

CHANGELOG-developer.next.asciidoc, filebeat/tests/system/test_modules.py, libbeat/tests/system/beat/beat.py
Provides a few improvements to the filebeat ingest pytests. 
- Include which file failed the "wait for docs" step
- Support TESTING_FILEBEAT_FILEPATTERN to ingest a single file
- Include the full event in the "not documented" case
Makes it easier to write and maintain filebeat pytests
- ~I have commented my code, particularly in hard-to-understand areas~
- ~I have made corresponding change to the default configuration files~
- ~I have added tests that prove my fix is effective or that my feature works~
```
❯ cd filebeat
❯ make update filebeat.test
❯ make python-env
❯ source ./build/python-env/bin/activate
❯ INTEGRATION_TESTS=1 BEAT_STRICT_PERMS=false TESTING_FILEBEAT_MODULES=elasticsearch TESTING_FILEBEAT_FILESETS=slowlog TESTING_FILEBEAT_FILEPATTERN=es_indexing_slowlog.800.log …
```
=> Filebeat pytest improvements

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 1 Feb 2022 00:14:42 GMT, release_branch:8.0, prefix:, end_time:Tue, 1 Feb 2022 04:58:46 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-09bea260, build_duration_seconds:17044]
=> [automation] update elastic stack version for testing 8.0.0-09bea260

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 7.17.0

heartbeat/docs/monitors/monitor-browser.asciidoc
Fixes typo in word.
Improves the docs.
Will need backports to only 7.16, labelled accordingly.
=> [docs] fix minor typo

filebeat/module/apache/access/ingest/pipeline.yml, filebeat/module/elasticsearch/server/ingest/pipeline.yml, filebeat/module/iis/access/ingest/pipeline.yml, filebeat/module/iis/error/ingest/pipeline.yml, filebeat/module/kafka/log/ingest/pipeline.yml, filebeat/module/kibana/audit/ingest/pipeline.yml, filebeat/module/kibana/log/ingest/pipeline.yml, filebeat/module/logstash/log/ingest/pipeline.yml, filebeat/module/logstash/slowlog/ingest/pipeline.yml, filebeat/module/mongodb/log/ingest/pipeline.yml, filebeat/module/mysql/error/ingest/pipeline.yml, filebeat/module/nats/log/ingest/pipeline.yml, filebeat/module/nginx/access/ingest/pipeline.yml, filebeat/module/nginx/error/ingest/pipeline.yml, filebeat/module/osquery/result/ingest/pipeline.json, filebeat/module/redis/log/ingest/pipeline.yml, filebeat/module/santa/log/test/santa.log-expected.json, filebeat/module/traefik/access/ingest/pipeline.yml, x-pack/filebeat/module/zookeeper/audit/ingest/pipeline.yml, x-pack/filebeat/module/zookeeper/log/ingest/pipeline.yml
In this PR I changed renaming `@timestamp` field to copying it to a new field in all of our existing modules.
Since 8.0, Beats is sending events to data streams. Data streams require that all events have `@timestamp` fields. Beats always add `@timestamp` field to events. However, we sometimes have problems in Ingest pipelines. Renaming or later processors might fail during ingest, leaving the event without `@timestamp` field. If that field is missing the event cannot be indexed and Beats drop them. To avoid such cases, we have to make sure we always have the field.
~~- [ ] I have made …
=> Copy `@timestamp` to make sure we always have a timestamp in the event

docs/devguide/contributing.asciidoc, docs/devguide/index.asciidoc, docs/devguide/modules-dev-guide.asciidoc, docs/devguide/new_protocol.asciidoc, docs/devguide/testing.asciidoc
filebeat fails (hangs) on 8.0 due to `Elasticsearch is too old.` so updating to 8.1 as well as fixing up expectations around authentication and ssl.
I've also included a little extra information about how to run the tests, look for logs, and some options (including one that will be added by https://github.com/elastic/beats/pull/30103)
Rel: https://github.com/elastic/beats/issues/29880
=> Updated dev guide instructions to work with master

metricbeat/docs/modules/mssql.asciidoc, x-pack/metricbeat/module/mssql/_meta/docs.asciidoc
This PR is a update for MSSQL module document with additional information like permission required for the list of tables.
These information are needed for the users to know about prerequisites.
- [NA]
NA
- Closes  #12267.
=> mssql-doc updated with the list of tables which should have permission

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 1 Feb 2022 21:32:28 GMT, release_branch:7.17, prefix:, end_time:Wed, 2 Feb 2022 01:59:53 GMT, manifest_version:2.0.0, version:7.17.1-SNAPSHOT, branch:7.17, build_id:7.17.1-7ef8bcb5, build_duration_seconds:16045]
=> [automation] update elastic stack version for testing 7.17.1-7ef8bcb5

x-pack/elastic-agent/pkg/agent/application/local_mode.go
In https://github.com/elastic/beats/pull/30087 we introduced loading inputs configuration from external folders in Agent. This PR changes the path to the external configuration files from relative to absolute.
Using absolute path makes the solution bit more stable. The feature works even without this change unless the user change `path.config` or the folder. But having this in covers all "cases". …
=> Use absolute path in external config glob when looking for external configuration files in Elastic Agent

.mergify.yml
Merge as soon as 8.1 branch was created. Auto-merge is not yet supported, see https://github.com/Mergifyio/mergify-engine/discussions/2821
=> backport: Add 8.1 branch

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 2 Feb 2022 05:16:21 GMT, release_branch:7.17, prefix:, end_time:Wed, 2 Feb 2022 09:47:17 GMT, manifest_version:2.0.0, version:7.17.1-SNAPSHOT, branch:7.17, build_id:7.17.1-aa300c4a, build_duration_seconds:16256]
=> [automation] update elastic stack version for testing 7.17.1-aa300c4a

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 2 Feb 2022 00:14:16 GMT, release_branch:8.0, prefix:, end_time:Thu, 3 Feb 2022 01:20:03 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-56a14b95, build_duration_seconds:90347]
=> [automation] update elastic stack version for testing 8.0.0-56a14b95

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 3 Feb 2022 01:32:54 GMT, release_branch:8.0, prefix:, end_time:Thu, 3 Feb 2022 06:27:23 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-1018d5a4, build_duration_seconds:17669]
=> [automation] update elastic stack version for testing 8.0.0-1018d5a4

x-pack/filebeat/module/threatintel/_meta/kibana/7/dashboard/Filebeat-threatintel-recordedfuture.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/037e2af0-df50-11eb-8f2b-753caedf727d.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/06744e90-df52-11eb-8f2b-753caedf727d.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/139c7da0-df51-11eb-8f2b-753caedf727d.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/176bf800-df58-11eb-8f2b-753caedf727d.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/2d365f10-8479-11ec-8aa9-11bf914a1ef2.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/3c996410-df52-11eb-8f2b-753caedf727d.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/4bcc4cb0-df50-11eb-8f2b-753caedf727d.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/5e76ef90-df51-11eb-8f2b-753caedf727d.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/6b33edb0-8478-11ec-8aa9-11bf914a1ef2.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/739274d0-8479-11ec-8aa9-11bf914a1ef2.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/790cd040-df51-11eb-8f2b-753caedf727d.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/7ed4ce00-df52-11eb-8f2b-753caedf727d.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/82fa7420-df58-11eb-8f2b-753caedf727d.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/8fb01a00-df51-11eb-8f2b-753caedf727d.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/a0a31740-df51-11eb-8f2b-753caedf727d.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/b0837690-df52-11eb-8f2b-753caedf727d.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/c2a5c180-df51-11eb-8f2b-753caedf727d.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/c6079390-8478-11ec-8aa9-11bf914a1ef2.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/dd4a3da0-df50-11eb-8f2b-753caedf727d.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/f37f8350-df50-11eb-8f2b-753caedf727d.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/tag/d6ef8f20-70a9-11eb-a3e3-b3cc7c78a70f.json
Updates the existing Recorded Future dashboard in the Threat Intel module.
After the integration was rewritten, the dashboard needs adjustment because some fields have changed.
Relates #30030
=> Updated dashboard for new Recorded Future integration

CHANGELOG.next.asciidoc, filebeat/autodiscover/builder/hints/logs.go, filebeat/docs/autodiscover-hints.asciidoc
This PR adds `co.elastic.logs/pipeline` hint to Filebeat's hints list. This setting sets the pipelineID to be used for the events.
Closes https://github.com/elastic/beats/issues/20722
=> Add pipeline in FB's supported hints

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Sun, 6 Feb 2022 17:10:58 GMT, release_branch:6.8, prefix:, end_time:Sun, 6 Feb 2022 21:40:02 GMT, manifest_version:2.0.0, version:6.8.24-SNAPSHOT, branch:6.8, build_id:6.8.24-873158e7, build_duration_seconds:16144]
=> [automation] update elastic stack version for testing 6.8.24-873158e7

CHANGELOG.next.asciidoc, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml, deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, deploy/kubernetes/metricbeat/metricbeat-daemonset-configmap.yaml, deploy/kubernetes/metricbeat/metricbeat-daemonset.yaml, metricbeat/docs/running-on-kubernetes.asciidoc
- metricbeat documentation: add kubernetes.proxy config for openshift setup
- add comments related to the openshift installation for metricbeat and elastic-agent standalone
- Related https://github.com/elastic/integrations/issues/2065
- Closes https://github.com/elastic/beats/issues/17863
=> Update openshift documentation, manifests for metricbeat and elastic-agent standalone

libbeat/processors/script/docs/script.asciidoc
Fixes `script` processor examples in docs. The docs show `id` but the field is named `tag`.
Examples should be correct.
=> [libbeat] Fix script processor examples in docs

CHANGELOG.next.asciidoc, x-pack/functionbeat/manager/aws/cli_manager.go
This PR fixes the problem when deploying Lambdas using the Functionbeat manager. Previously, the region was not passed correctly to the AWS client, so the Lambda couldn't be deployed.
Without the fix Functionbeat manager does not work. Lambdas can only be deployed manually.
Closes #28520
=> Do not pass empty region configuration when deploying Lambdas using Functionbeat manager

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 7 Feb 2022 17:12:28 GMT, release_branch:6.8, prefix:, end_time:Mon, 7 Feb 2022 21:48:39 GMT, manifest_version:2.0.0, version:6.8.24-SNAPSHOT, branch:6.8, build_id:6.8.24-1e7d7419, build_duration_seconds:16571]
=> [automation] update elastic stack version for testing 6.8.24-1e7d7419

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
Empty sections will be cleaned up after initial review and before merge.
=> docs: Prepare Changelog for 8.0.0

.mergify.yml
Auto-assign the PR owner if the PR is not assigned yet
See https://docs.mergify.com/actions/assign/
See https://github.com/elastic/beats/discussions/29991
A similar implementation was done sometime ago -> https://github.com/elastic/apm-pipeline-library/blob/ff50b3b5f4fab47b89d61183f1f3d1bb58b8795a/.mergify.yml#L49-L57 for another project
=> mergify: auto-assign PR owner

libbeat/docs/config-file-format.asciidoc
Beats config files must be UTF-8, if they're not UTF-8 there will be
problems with special characters.
It clarifies our documentation
- Closes #30053
~~## Logs~~
=> docs: add statement about config file encoding

libbeat/docs/shared-env-vars.asciidoc
Update doc to reflect that $ can used as a general escape char, not just to escape `$`.
Existing doc suggests only ${ can e escaped with a $ - this reduces confusion.
=> Update doc with use of $ as escape char

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 8 Feb 2022 12:17:02 GMT, release_branch:master, prefix:, end_time:Tue, 8 Feb 2022 18:05:51 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-ff5ac1e4, build_duration_seconds:20929]
=> [automation] update elastic stack version for testing 8.2.0-ff5ac1e4

dev-tools/mage/build.go
Signed-off-by: Florian Lehner <florian.lehner@elastic.co>
Remove file system paths from the compiled executable. This results in
slimmer executable and makes it easier to compare stack traces.
BEFORE:
```
$ cd x-pack/elastic-agent/
$ mage clean
$ mage build
$ strings build/elastic-agent | grep github
/home/foobar/src/github.com/elastic/beats/libbeat/conditions/not.go
/home/foobar/src/github.com/elastic/beats/libbeat/conditions/equals.go
/home/foobar/src/github.com/elastic/beats/libbeat/conditions/extractors.go
/home/foobar/src/github.com/elastic/beats/libbeat/conditions/fields.go
/home/foobar/src/github.com/elastic/beats/libbeat/conditions/has_fields.go
/home/foobar/src/github.com/elastic/beats/libbeat/conditions/matcher.go
[...]
```
AFTER:
```
$ cd x-pack/elastic-agent/
$ mage clean
$ …
```
=> mage: add -trimpath flag to build process

x-pack/filebeat/input/httpjson/request.go
httpClient.do now reads the whole response.Body into memory and
replaces it with the in-memory copy. This brings some advantages:
* We can easily ensure the response.Body is always closed
* We read the response as quick as possible, releasing the connection
to be reused and avoiding possible timeouts or other errors caused
by keeping the connection open and blocked.
This came as a improvement on #29816, however I believe it can be merged on its own.
It helps to ensure the correctness of the code and to avoid leaking open sockets.
- ~~[ ] I have added an entry in …
=> filebeat/input/httpjson: drain and close response.Body

CHANGELOG.next.asciidoc, libbeat/common/transport/tls.go
This reverts commit e208c22507890eb3633d55f1ba7d388f3076b2d6.
This commit caused the agent to crash on startup on Windows with a nil
pointer dereference.
- Relates #30315)
=> Revert "libbeat/common/transport: fix log message about TLS (#30063)"

libbeat/docs/release-notes/breaking/breaking-8.0.asciidoc
Adds notable 8.0 breaking changes. 
Typically we also list field changes. If someone can give me a list, I'll add them.
This content gets sucked into the upgrade guide where it's more prominent for users who are upgrading the stack.
- Relates TBD
=> Add notable Breaking Changes for 8.0

x-pack/filebeat/module/threatintel/_meta/kibana/7/dashboard/Filebeat-threatintel-recordedfuture.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/037e2af0-df50-11eb-8f2b-753caedf727d.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/06744e90-df52-11eb-8f2b-753caedf727d.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/139c7da0-df51-11eb-8f2b-753caedf727d.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/176bf800-df58-11eb-8f2b-753caedf727d.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/2d365f10-8479-11ec-8aa9-11bf914a1ef2.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/3c996410-df52-11eb-8f2b-753caedf727d.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/4bcc4cb0-df50-11eb-8f2b-753caedf727d.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/5e76ef90-df51-11eb-8f2b-753caedf727d.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/6b33edb0-8478-11ec-8aa9-11bf914a1ef2.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/739274d0-8479-11ec-8aa9-11bf914a1ef2.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/790cd040-df51-11eb-8f2b-753caedf727d.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/7ed4ce00-df52-11eb-8f2b-753caedf727d.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/82fa7420-df58-11eb-8f2b-753caedf727d.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/8fb01a00-df51-11eb-8f2b-753caedf727d.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/949bc180-df52-11eb-8f2b-753caedf727d.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/a0a31740-df51-11eb-8f2b-753caedf727d.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/b0837690-df52-11eb-8f2b-753caedf727d.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/c2a5c180-df51-11eb-8f2b-753caedf727d.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/c6079390-8478-11ec-8aa9-11bf914a1ef2.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/dd4a3da0-df50-11eb-8f2b-753caedf727d.json, x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/f37f8350-df50-11eb-8f2b-753caedf727d.json
This updates the new Recorded Future dashboard to align with a recent change (https://github.com/elastic/kibana/pull/123894) in Kibana 8.1 that affects how the Lens visualisations are serialised.
The dashboard had been exported using an incompatible snapshot version of Kibana 8.1, and wouldn't work in newer versions. All visualisations would show _"Field Records not found"._
This fix is not necessary for other dashboards as those were exported with an older Kibana version. In this case, the older `Records` field placeholder is automatically translated to the new `___records___` by Kibana.
=> Fix new Recorded Future dashboard

filebeat/input/filestream/parsers_integration_test.go
This PR reenables previous flaky tests. The problem was that we did not leave enough time for the multiline parser to aggregate log lines into a single message. So we ended up with incomplete events, saving unexpected offsets to the registry.
The fix is to increase the timeout of the multiline parser. The default value is 5 seconds, but I set it to 3, so we still save some time during testing.
Run existing tests to make sure we do not introduce regressions.
~~- [ ] I have added an entry in …
=> Give more time to multiline parser to aggregate logs into events during testing

CHANGELOG.next.asciidoc, libbeat/common/transport/tlscommon/tls_config.go
This PR fixes a race condition on hostname/IP validation for TLS
certificates. We were relying on a field on TLSConfig, but this struct
is shared between different hosts. Now we pass the server name as a
parameter, thus avoiding any race condition.
The error seen in the logs looks like this:
```
Get "https://bitbucket.corp.internal/status": x509: certificate is valid for bitbucket.corp.internal, not jira.corp.internal
```
Where both hostnames are used together on a output (like ES, Logstash, etc), a monitor in Heartbeat, etc). See the testing section for a more detailed example.
It fixes a bug.
- ~~[ ] I have added tests that prove my fix is …
=> tlscommon: fix race condition on TLS hostname validation

CHANGELOG.next.asciidoc, libbeat/common/transport/tls.go
This commit fixes the log message issued by the `test output` command.
Our current TLS verification relies on more than the value of
`tlsConfig.InsecureSkipVerify`, so the previous implementation would
log that TLS was disabled when it was not.
This commit fixes it by checking the value of `config.Verification`.
It fixes a logging issue
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.
#30315
#30314
To test using Filebeat, set the `ssl.verification_mode` on any Beat …
=> libbeat/common/transport: fix log message about TLS

x-pack/heartbeat/monitors/browser/synthexec/enrich.go, x-pack/heartbeat/monitors/browser/synthexec/enrich_test.go, x-pack/heartbeat/monitors/browser/synthexec/synthtypes.go
+ When there are syntax errors in the monitor script, the `journey/start` never fires as the Synthetics runner cannot register the journeys and node runs to completion with exit status 1.
+ In these cases, determining the duration between start/end event would be tricky and since the journeys never run in the first place, Its good to set the duration to `0` instead of setting false positive values. 
+ Added extensive test cases for summary event creation for various scenarios 
```yaml
heartbeat.run_once: true
heartbeat.monitors:
- type: browser
id: my-monitor
name: My Monitor
source:
inline:
script: step("load homepage", async () => {);
schedule: "@every 1m"
output.console: ~
``
=> Heartbeat: set duration to zero for syntax errors

filebeat/beater/crawler.go, x-pack/filebeat/input/httpjson/encoding.go
Add message to the debug log indicating which encoder/decoder is being registered instead of only logging the error (nil or not) returned.
A log message `<nil>` is unclear.
- [x ] My code follows the style guidelines of this project
Current behaviour
```
Jan 26, 2022 @ 07:03:24.636 | debug | <nil> | filebeat
```
After changes:
```
Jan 26, 2022 @ 07:03:24.636 | debug | registering encoder …
```
=> [Filebeat] Add message to register encode/decode debug logs

.ci/jobs/beats.yml
Disable 6.x branches in the CI
6 major branch reached EOL
=> jjbb: 6 major branch reached EOL

CHANGELOG.next.asciidoc, libbeat/outputs/kafka/client.go, libbeat/outputs/kafka/config.go, libbeat/outputs/kafka/docs/kafka.asciidoc, libbeat/outputs/kafka/kafka_integration_test.go
According to the Kafka documentation, header keys are not supposed to
be unique, therefore we must support the headers in the same way.
Also, documented the headers configuration, so customers can start using it.
This is a follow up to https://github.com/elastic/beats/pull/29940
Initially, it was a community PR hence for someone this functionality is important. This PR brings the implementation closer to the original Kafka feature as the documentation states:
> A [Header](https://kafka.apache.org/20/javadoc/org/apache/kafka/connect/header/Header.html) is a key-value pair, and multiple headers can be included with the key, value, and timestamp in each Kafka message.
source https://kafka.apache.org/20/javadoc/index.html?org/apache/kafka/connect/header/Header.html
~~- [ ] I have made …
=> Add support for non-unique keys in Kafka output headers

Jenkinsfile
When the lint stage is not reported for some reason and the CI success you can not merge the PR because the lint check is required. Due to we have a cache in place the stage is never reported as a GitHub check if there are no changes in code. By changing the order of the GitHub check, it is always returned.
=> fix: report GitHub Check before the cache

auditbeat/Jenkinsfile.yml, filebeat/Jenkinsfile.yml, heartbeat/Jenkinsfile.yml, metricbeat/Jenkinsfile.yml, packetbeat/Jenkinsfile.yml, winlogbeat/Jenkinsfile.yml, x-pack/auditbeat/Jenkinsfile.yml, x-pack/elastic-agent/Jenkinsfile.yml, x-pack/filebeat/Jenkinsfile.yml, x-pack/functionbeat/Jenkinsfile.yml, x-pack/heartbeat/Jenkinsfile.yml, x-pack/metricbeat/Jenkinsfile.yml, x-pack/osquerybeat/Jenkinsfile.yml, x-pack/packetbeat/Jenkinsfile.yml, x-pack/winlogbeat/Jenkinsfile.yml
Remove `windows-7`, `windows-7-32` and `windows-2008-r2` from the matrix support in the CI
>= 8.0 don't support those versions anymore.
=> update windows matrix support

CHANGELOG.next.asciidoc, packetbeat/beater/packetbeat.go, packetbeat/beater/processor.go
Previously installNpcap was run after Create, which depends on having interfaces up
to establish sniffers, and so was too late. So move the call to the front of Create
to ensure that the library is installed by the time that it is needed.
This fixes a required feature.
-
=> packetbeat/beater: make sure Npcap installation runs before interfaces are needed

.ci/schedule-daily.groovy, .ci/schedule-weekly.groovy
Support for the next patch fro the 8 major.
And refactor code with a shared library step
Support for 8.1 branch 
Requires https://github.com/elastic/apm-pipeline-library/pull/1548
=> ci: use getBranchesFromAliases and support next-patch-8

filebeat/docs/autodiscover-hints.asciidoc, heartbeat/docs/autodiscover-hints.asciidoc, metricbeat/docs/autodiscover-hints.asciidoc
Adds documentation to state that it's possible to use [autodiscover templating](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover.html) + [hints based autodiscover](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover-hints.html) together in a single Filebeat (and others) configuration.
Closes https://github.com/elastic/beats/issues/26397
=> Add docs about hints and templates autodiscovery priority

dev-tools/mage/crossbuild.go, dev-tools/mage/pkg.go
- document SelectedPackageTypes meaning
- simplify isPackageTypeSelected
It documents the meaning of `devtools.SelectedPackageTypes` and simplify the implementation of `isPackageTypeSelected` accordingly.
The current implementation of `isPackageTypeSelected` is unclear and threats an empty slice and nil slice differently whereas they should be equivalent.
Build the beats ot the elastic-agent, it should preserve the current behaviour.
=> Clarify SelectedPackageTypes meaning and improve its usage

CHANGELOG.next.asciidoc, libbeat/reader/readfile/metafields.go, libbeat/reader/readfile/metafields_test.go
This PR fixes the offset reported in `log.offset` field. Previously, it reported the offset of the end of the line. However, the field documentation says that it should be the start offset of the line. Ref: https://www.elastic.co/guide/en/beats/filebeat/current/exported-fields-log.html
Filebeat should comply with ECS.
=> Set `log.offset` to the start of the reported line in filestream

filebeat/fileset/modules_test.go
Fixes flaky unit test _TestNewModuleRegistry._
Filesets must be sorted before comparing them, as they are originally populated by iterating on a map, which returns the keys in random order.
So tests pass.
```
modules_test.go:104: 
Error Trace:	modules_test.go:104
Error:      	Not equal: 
expected: []string{"error", "access"}
actual  : []string{"access", "error"}
Diff:
--- Expected
+++ Actual
@@ -1,4 +1,4 @@
([]string) (len=2) {
- (string) (len=5) "error",
- (string) (len=6) "access"
+ (string) (len=6) "access",
+ (string) (len=5) "error"
}
Test:       	TestNewModuleRegistry
--- FAIL: TestNewModuleRegistry (0.02s)
```
=> Fix TestNewModuleRegistry flaky test

CHANGELOG.next.asciidoc, dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl, dev-tools/packaging/templates/docker/Dockerfile.tmpl
Fixes an issue where the `docker-entrypoint` inside of the beats containers no longer worked the same as it did before the switch to Ubuntu 20.04 as the base image in 7.17.0.
This is because Ubuntu ships with `mawk` instead of `gawk`. This change switches the container back to using `gawk`.
Allows the `docker-entrypoint` to provide the same behavior that was provided in <7.16.x in 7.17.1+. Switch to `gawk` also ensures that any one that uses `awk` in a derived container with one of the beats as a base the same awk commands will work.
`setup` should now be executed, …
=> Install gawk as a replacement for mawk in Docker containers.

libbeat/docs/release-notes/breaking/breaking-8.0.asciidoc
Mention in Breaking Changes docs that Homebrew installation method no longer works.
This change is breaking for users who rely on Homebrew as part of their deployment strategy.
https://github.com/elastic/observability-docs/issues/1544
=> Add BC about Homebrew no longer being available in 8.0

CHANGELOG.next.asciidoc, packetbeat/beater/packetbeat.go, packetbeat/beater/processor.go
This is a second attempt to ensure that Npcap is correctly installed; running
packetbeat managed by elastic-agent appears to have a different code path to
that when running vanilla packetbeat and does not execute Create in time (at
all?) to have the installer run. So move the installNpcap call to the earliest
time we have all the needed information to ensure that the library is installed
by the time that it is needed.
This fixes a required feature.
Local testing requires setting up a managed windows host under fleet.
- Relates #30396
=> packetbeat/beater: make sure Npcap installation runs before interfaces are needed in all cases

docs/devguide/modules-dev-guide.asciidoc
Fixes doc spelling 
Amusingly enough docker only errors out if the image hasn't been pulled already.
So I'd been running and ineffective `--pull allways` and only noticed once I'd cleaned out a bunch of old docker images.
=> Spelling fix

CHANGELOG.next.asciidoc, packetbeat/beater/install_npcap.go, packetbeat/npcap/npcap.go, packetbeat/npcap/npcap_other.go, packetbeat/npcap/npcap_windows.go
This makes installation of the OEM Npcap library on windows conditional on its absence or version.
Without this packetbeat startup fails every second time due to the Npcap removal for installation forcing all applications to be killed (see https://npcap.com/guide/npcap-users-guide.html#npcap-installation-uninstall-options section on \no_kill). ~~The longer term fix required for actual upgrade operations requires that the DLL be unloaded prior to upgrade. That change will come in another PR.~~ Included here.
- Relates #30493
=> packetbeat/beater: don't attempt to install npcap when already installed

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> Forward-port 8.0.1 changelog to 8.1

auditbeat/tests/system/test_file_integrity.py
This test had a `BUILD_ID` skip that I'm fairly certain is jenkins-specific. You can see it running and failing a fair bit on https://github.com/elastic/beats/actions/workflows/macos-auditbeat.yml?query=is%3Afailure
I've replaced it with `CI` since that seems like a good generic option and [provided by github actions](https://docs.github.com/en/actions/learn-github-actions/environment-variables). I'm unclear on if jenkins will provide it or not. Hoping @andrewkroh or @v1v can confirm before merge.
The tests are running but flakey, causing error messages and (at best) wasted investigation cycles or (at worst) tendency to ignore test suite failures.
- ~~My code follows the style guidelines of this project~~
- ~~I have …
=> Switch skip to use `CI`

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> Forward-port 8.0.1 changelog to main

CHANGELOG.next.asciidoc, metricbeat/docs/modules/kubernetes.asciidoc, metricbeat/module/kubernetes/_meta/docs.asciidoc
Extend documentation regarding `orchestrator.cluster` fields.
- Closes https://github.com/elastic/beats/issues/30229
=> extend documentation about setting orchestrator.cluster fields

filebeat/_meta/config/filebeat.inputs.reference.yml.tmpl, filebeat/filebeat.reference.yml, x-pack/filebeat/filebeat.reference.yml
This PR adds the missing `parsers` sections to the reference configuration of Filebeat.
One recurring issue in filestream is users misconfiguring parsers. The documentation is somewhat detailed on the topic. However, `parsers` were missing from the reference configuration. I am adding more `parser` examples to ease adoption of filestream and decrease user frustration/confusion.
=> Add `parsers` examples to `filestream` reference configuration

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 16 Feb 2022 12:16:36 GMT, release_branch:master, prefix:, end_time:Wed, 16 Feb 2022 17:17:56 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-74785f8b, build_duration_seconds:18080]
=> [automation] update elastic stack version for testing 8.2.0-74785f8b

auditbeat/module/file_integrity/eventreader_test.go, x-pack/auditbeat/module/system/package/rpm_common_test.go, x-pack/auditbeat/module/system/socket/dns/afpacket/config.go, x-pack/auditbeat/module/system/socket/guess/creds.go, x-pack/auditbeat/module/system/user/config.go
This removes the majority of unused identified by running:
staticcheck -checks 'U*' ./{,x-pack/}auditbeat/...
Care has been taken to not remove platform-specific code and mage-required code.
This is the auditbeat part of #30483.
Deadcode reduces code base maintainability.
- Relates #30483.
=> {,x-pack/}auditbeat: remove unused fields and params and mark platform-specific code

CHANGELOG.next.asciidoc, winlogbeat/beater/winlogbeat.go, winlogbeat/checkpoint/checkpoint.go
If the registry file is invalid for some reason the error can be ambiguous given that
the config file is also in YAML. So give the errors more context. This is an example
of the ambiguous error:
Exiting: yaml: control characters are not allowed
The original error message was confusing.
=> [Winlogbeat] Improve registry error message

packetbeat/beater/install_npcap.go
The installer bytes are released in the install case but this was accidentally removed in #30048. This frees ~1MB of runtime memory after start up has been completed.
The change is not critical, but it would be nice to have in 8.1.
Reduces memory footprint of the beat.
https://github.com/elastic/beats/blob/d74e7aae6da99145fffc550c25f1117041c56318/packetbeat/beater/install_npcap.go#L70-L77
-
=> packetbeat/beater: help the GC clean up the Npcap installer if it's not used

filebeat/docs/inputs/input-filestream-file-options.asciidoc, filebeat/input/filestream/config.go
This PR cleans up the backoff section of filestream documentation. The information was outdated in a few places. It stated that filestream backs of linearly, however, it does backoff exponentially.
References to `scan_frequency` was updated to `prospector.scanner.check_interval`.
The default value of `backoff.init` is set to 2s, so Filebeat can really back off exponentially.
Address confusion, update docs. …
=> Adjust the documentation of `backoff` options in filestream input

CHANGELOG.next.asciidoc, x-pack/elastic-agent/pkg/fleetapi/ack_cmd.go, x-pack/elastic-agent/pkg/fleetapi/acker/fleet/fleet_acker.go, x-pack/elastic-agent/pkg/fleetapi/acker/fleet/fleet_acker_test.go
Populates input_type for the .fleet-actions-results. This allows to use kibana transformations on .fleet-actions-results for specific integration without a need to correlate them to the original .fleet-actions (via the action_id)
Allows to use kibana transformations on .fleet-actions-results for specific integration without a need to correlate them to the original .fleet-actions (via the action_id)
One of the ways to test is with osquery integration, with corresponding change in fleet-server and elasticsearch fleet mapping. The .fleet-actions-results document should have the new field ```input_type```.
=> Agent: populate action_input_type for the .fleet-actions-results

CHANGELOG.next.asciidoc, x-pack/auditbeat/module/system/socket/events.go
This change defends against a bounds panic when execve has been called with an argv with zero arguments; exexve can have a zero-length argv so fall back to using /proc/comm, or path base.
It is possible for a zero argument execve call to result in a bounds check error when attempting to get the process name for the exec'd process, panicking and bringing down the auditbeat process.
- Closes #30585.
=> x-pack/auditbeat/module/system/socket: defend against exec with zero arguments

.github/CODEOWNERS
Set @elastic/infra-monitoring-ui team as code owners for Stack Monitoring related modules
=> Add infra-monitoring-ui team as codeowner

CHANGELOG.next.asciidoc, x-pack/filebeat/module/mysqlenterprise/audit/manifest.yml
Adds a default value to the manifest.yml, this is needed to run pipeline setup commands, as it ignores user input.
Fixes a bug when using filebeats setup command for this specific module
=> [MySQL Enterprise] Adding default paths values to manifest.yml

metricbeat/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
Applies https://github.com/elastic/beats/pull/28659 changes to main and 8.1 branches
=> bump test environments versions

metricbeat/docker-compose.yml, metricbeat/module/logstash/docker-compose.yml, testing/environments/latest.yml, testing/environments/prev-minor.yml, x-pack/metricbeat/docker-compose.yml
Merge only after the release of 7.17.1.
=> [Release] Update test environments for 7.17.2

.ci/schedule-daily.groovy
Disable the nightly/daily builds that trigger `MacOS` workers.
Orka VMs are not correctly provisioned, the CI Systems team is talking to the provider. Let's remove this as builds are failing for some timeout systematically
=> [ci][daily]: disable builds as long as Orka VMs are not provisioned

.github/CODEOWNERS
Alert elastic agent control team of `elastic-agent` directory changes. Will help us monitor any changes to the directory that will take place before/after switching to the new `elastic-agent` repo.
This directory will be removed in the future.
=> Alert elastic agent control team of elastic-agent changes

deploy/kubernetes/Jenkinsfile.yml, metricbeat/docs/modules/kubernetes.asciidoc, metricbeat/module/kubernetes/_meta/docs.asciidoc
This PR keep only actively maintained versions in testing. This doesn't mean that we drop support for older ones but mostly that focus testing on newer ones.
Closes https://github.com/elastic/beats/issues/29604
=> Curate k8s testing versions to only keep the actively maintained

auditbeat/Jenkinsfile.yml, filebeat/Jenkinsfile.yml, heartbeat/Jenkinsfile.yml, metricbeat/Jenkinsfile.yml, packetbeat/Jenkinsfile.yml, winlogbeat/Jenkinsfile.yml, x-pack/auditbeat/Jenkinsfile.yml, x-pack/elastic-agent/Jenkinsfile.yml, x-pack/filebeat/Jenkinsfile.yml, x-pack/functionbeat/Jenkinsfile.yml, x-pack/metricbeat/Jenkinsfile.yml, x-pack/osquerybeat/Jenkinsfile.yml, x-pack/packetbeat/Jenkinsfile.yml, x-pack/winlogbeat/Jenkinsfile.yml
Add windows-2022 support in the extended meta-stage.
Extended meta-stage is the one that runs after the mandatory stage.
Windows-2022 is supported in `8.x`
https://github.com/elastic/beats/pull/30622 is the one for Winlogbeat since there are test failures already reported in https://github.com/elastic/beats/issues/30621
=> ci: add windows-2022 in the extended meta-stage

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 1 Mar 2022 12:17:14 GMT, release_branch:master, prefix:, end_time:Tue, 1 Mar 2022 17:42:51 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-43df679f, build_duration_seconds:19537]
=> [automation] update elastic stack version for testing 8.2.0-43df679f

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 1 Mar 2022 05:13:40 GMT, release_branch:7.17, prefix:, end_time:Tue, 1 Mar 2022 09:46:35 GMT, manifest_version:2.0.0, version:7.17.2-SNAPSHOT, branch:7.17, build_id:7.17.2-3e73f87b, build_duration_seconds:16375]
=> [automation] update elastic stack version for testing 7.17.2-3e73f87b

filebeat/_meta/config/filebeat.inputs.reference.yml.tmpl, filebeat/_meta/config/filebeat.inputs.yml.tmpl, filebeat/docs/inputs/input-filestream-file-options.asciidoc, filebeat/docs/inputs/input-filestream.asciidoc, filebeat/filebeat.reference.yml, filebeat/filebeat.yml, filebeat/input/filestream/internal/input-logfile/manager.go, x-pack/filebeat/filebeat.reference.yml, x-pack/filebeat/filebeat.yml
It adds documentation and log warning when filestream inputs are used without IDs.
When using multiple filestream inputs without IDs, when Filebeat is restarted all the files are read from the beginning,
this PR adds documentation and warning about this issue.
The final issue will be fixed in a later PR.
- Setup a filestream input without an ID
- Start Filebeat
- You should see a log warning
Input configuration example:
```yaml
enabled: true
paths:
- /tmp//first.log
```
Log message:
```
{"log.level":"warn","@timestamp":"2022-02-21T19:56:17.494+0100","log.logger":"input","log.origin":{"file.name":"input-logfile/manager.go","file.line":173},"messa …
```
=> input/filestream: filestream input ID is required

.ci/packaging.groovy
Refactor packaging to use the shared library step:
- https://github.com/elastic/apm-pipeline-library/pull/1549
Uses the repo name for the folder matching. Consumers should know this change (e2e-testing)
DRY, and in addition shared library steps are covered with UTs :)
=> ci: refactor packaging with a new step

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 2 Mar 2022 12:14:27 GMT, release_branch:master, prefix:, end_time:Wed, 2 Mar 2022 17:25:05 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-fdde08ec, build_duration_seconds:18638]
=> [automation] update elastic stack version for testing 8.2.0-fdde08ec

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 2 Mar 2022 12:13:59 GMT, release_branch:8.1, prefix:, end_time:Wed, 2 Mar 2022 17:03:11 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:8.1, build_id:8.1.0-fbfb1f9e, build_duration_seconds:17352]
=> [automation] update elastic stack version for testing 8.1.0-fbfb1f9e

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 2 Mar 2022 05:13:39 GMT, release_branch:7.17, prefix:, end_time:Wed, 2 Mar 2022 09:41:01 GMT, manifest_version:2.0.0, version:7.17.2-SNAPSHOT, branch:7.17, build_id:7.17.2-e8098595, build_duration_seconds:16042]
=> [automation] update elastic stack version for testing 7.17.2-e8098595

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 3 Mar 2022 00:14:05 GMT, release_branch:8.0, prefix:, end_time:Thu, 3 Mar 2022 04:52:31 GMT, manifest_version:2.0.0, version:8.0.2-SNAPSHOT, branch:8.0, build_id:8.0.2-ae36dda7, build_duration_seconds:16706]
=> [automation] update elastic stack version for testing 8.0.2-ae36dda7

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 3 Mar 2022 00:14:11 GMT, release_branch:8.1, prefix:, end_time:Thu, 3 Mar 2022 06:01:44 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:8.1, build_id:8.1.0-5eb67818, build_duration_seconds:20853]
=> [automation] update elastic stack version for testing 8.1.0-5eb67818

CHANGELOG.next.asciidoc, filebeat/input/filestream/internal/input-logfile/harvester.go, filebeat/input/log/logger.go
Renames the `source` field used in some log messages to `source_file`
This makes Filebeat compatible with ECS
Run Filebeat in a docker container with docker autodiscover enabled, Filebeat should be able to
ship its own logs to ES without any issues.
Configuration example
```yaml
filebeat.autodiscover:
providers:
- type: docker
templates:
- condition:
regexp:
docker.container.image: ".*"
config:
- type: container
paths:
- /var/lib/docker/containers/${data.docker.container.id}/*.log …
```
=> filebeat: rename `source` log key to `source_file`

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Fri, 4 Mar 2022 12:15:04 GMT, release_branch:8.0, prefix:, end_time:Fri, 4 Mar 2022 16:57:23 GMT, manifest_version:2.0.0, version:8.0.2-SNAPSHOT, branch:8.0, build_id:8.0.2-901e2b50, build_duration_seconds:16939]
=> [automation] update elastic stack version for testing 8.0.2-901e2b50

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Fri, 4 Mar 2022 12:13:26 GMT, release_branch:8.1, prefix:, end_time:Fri, 4 Mar 2022 17:11:44 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:8.1, build_id:8.1.0-52a8d1d4, build_duration_seconds:17898]
=> [automation] update elastic stack version for testing 8.1.0-52a8d1d4

CHANGELOG-developer.next.asciidoc, CHANGELOG.next.asciidoc, libbeat/template/processor.go, libbeat/template/processor_test.go
Modifies libbeat's template processor to stop hardcoding a default `ignore_above` limit of 1024 on wildcard fields. This behavior was inherited from keyword fields.
From the Beats users point of view, I've considered this a bugfix. (Bugfix under Affecting All Beats in CHANGELOG).
From the community Beat developers point of view, I consider this a breaking change as someone may be relying on the previous default behavior (Breaking under Affecting all Beats in CHANGELOG-developer).
Some important ECS wildcard fields are not being indexed properly. See related issue.
Closes #30096
=> libbeat: Don't force an ignore_above limit on wildcard fields

libbeat/tests/system/requirements.txt, metricbeat/module/prometheus/docker-compose.yml
Updates the `docker` and `docker-compose` to support newer versions of
the docker-compose file and newer docker-compose features like profiles.
To allow tests in projects that depend on beats, like APM Server to use more up-to-date versions of Docker Compose and leverage new docker-compose features.
N/A.
Ensure that `pip -r libbeat/tests/system/requirements.txt` works in a venv.
Unblocks elastic/apm-server#7453
Use [`docker-compose --profile`](https://docs.docker.com/compose/profiles/) to enable docker-compose files to have disabled services by default, yet allow them to be spun up by specifying a profile.
=> testing: Update docker and docker-compose versions

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Fri, 4 Mar 2022 14:54:03 GMT, release_branch:master, prefix:, end_time:Fri, 4 Mar 2022 20:48:39 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-a12f7069, build_duration_seconds:21276]
=> [automation] update elastic stack version for testing 8.2.0-a12f7069

libbeat/processors/add_kubernetes_metadata/docs/indexers_and_matchers.asciidoc
Cherrypicks https://github.com/elastic/beats/pull/30709 to `main`.
=> Page formatting issue (#30709)

libbeat/docs/release-notes/breaking/breaking-8.1.asciidoc, libbeat/docs/release-notes/breaking/breaking.asciidoc
Adds breaking changes page for 8.1.
Let me know if you want me to describe https://github.com/elastic/beats/pull/30564 here. I didn't think it qualified as an "important" breaking change since the dataset wasn't working correctly and not likely to be used.
=> Add 8.1 Beats breaking changes

CHANGELOG.next.asciidoc, libbeat/processors/add_process_metadata/add_process_metadata.go, libbeat/processors/add_process_metadata/add_process_metadata_test.go, libbeat/processors/add_process_metadata/config.go
This changes the mapping for parent process information to reflect the ECS, so that the current output
```
"process": {
"parent": {
"process": {
"pid": "1234"
"name": "parent_process",
[...]
}
}
}
```
would now be
```
"process": {
"parent": {
"pid": "1234"
"name": "parent_process",
[...]
}
}
```
This is a breaking change.
It brings the document output into line with the ECS.
- Closes #29874.
=> libbeat/processors/add_process_metadata: place parent process information directly in parent object

Jenkinsfile, deploy/kubernetes/Jenkinsfile.yml
Upgrade `kind` version to the latest one.
=> Upgrade kind version used for k8s testing

filebeat/input/filestream/fswatch.go
Improve filebeat file scanning performance when symlinks is enabled
On my machine, because it is a log server, the target file will reach tens of thousands or even millions. 
After filebeat is started, the CPU has been very high. 
Through golang pprof, most of the time is consumed in the scan->getFiles->os.SameFile function. 
(Symlinks is enabled in my configuration file)
I looked at the code carefully and found that there is an O(n2) performance loss when traversing `paths`.
On my machine, there are millions of files, and it takes more than 1 hour to run once here
#28328
=> improve filebeat scan performance when symlinks is enabled

CHANGELOG.next.asciidoc, filebeat/processor/add_kubernetes_metadata/matchers.go, filebeat/processor/add_kubernetes_metadata/matchers_test.go
According to https://www.elastic.co/guide/en/beats/filebeat/current/file-log-rotation.html#file-log-rotation, there might be cases when we need to read rotated log files:
```
Make sure Filebeat is configured to read from all rotated logs
```
This PR add possibility to get pod uid for the rotated log files when `resource_type` is set to `pod`.
- https://discuss.elastic.co/t/filebeat-add-kubernetes-metadata-pod-uid-matcher-doesnt-match-poduid-for-rotated-file-on-aks/298938
Context:
According to [[kubernetes documentation](https://kubernetes.io/docs/concepts/cluster-administration/logging/#logging-at-the-node-level)]:
> Kubernetes is not responsible for rotating logs, but rather a deployment tool should set up a solution to …
=> Fix add_kubernetes_metadata matcher: support rotated logs when 'resource_type: pod'

testing/environments/snapshot.yml
In https://github.com/elastic/beats/pull/15568 the testing of Logstash was changed to a specific hash because of some temporary issues with Logstash. Instead testing should happen against the SNAPSHOT releases like for Elasticsearch and Kibana.
=> Update testing to test agains Snapshot Logstash version

CHANGELOG.next.asciidoc, libbeat/cmd/instance/beat.go, libbeat/common/version.go, libbeat/common/version_test.go
In https://github.com/elastic/beats/pull/29683 we introduced a check to make sure we are not sending events to Elasticsearch instances that might be incompatible with Beats. However, the current check is too strict. Patch versions should not be considered during version checks. Beats 8.1.1 should be able to connect to Elasticsearch 8.1.0.
The check is too strict. This is not what we agreed on in the original issue. Furthermore, it interferes with our own release process.
https://github.com/elastic/beats/pull/30157
=> Ignore bugfix version when running version compatibility check against Elasticsearch

Jenkinsfile, metricbeat/Jenkinsfile.yml
Add support for installing `kind/k8s` only if running the metricbeat goIngTest stage.
**NOTE**: `kind/k8s` is only needed when testing the k8s module, so it might be installed for other modules, but this is the approach we can without much complexity in the CI.
The k8s module is tested in two places:
1) https://github.com/elastic/beats/blob/9e6536d964f0135940b9c416bcb1c0a41af99478/deploy/kubernetes/Jenkinsfile.yml#L20-L22 and https://github.com/elastic/beats/blob/9e6536d964f0135940b9c416bcb1c0a41af99478/Jenkinsfile#L323
2) https://github.com/elastic/beats/blob/9e6536d964f0135940b9c416bcb1c0a41af99478/metricbeat/Jenkinsfile.yml#L27-L30
Only `1` is in charge to install the given Kind and K8s versions. but `2` requires those tools. Those tools are installed in the CI workers as part of the …
=> ci: configure kind/k8s for k8s in metricbeat only

metricbeat/docs/modules/docker.asciidoc, metricbeat/metricbeat.reference.yml, metricbeat/module/docker/_meta/config.reference.yml, metricbeat/module/docker/_meta/config.yml, metricbeat/module/docker/diskio/_meta/data.json, metricbeat/module/docker/diskio/diskio.go, metricbeat/module/docker/diskio/diskio_test.go, metricbeat/module/docker/diskio/helper.go, metricbeat/modules.d/docker.yml.disabled, x-pack/metricbeat/metricbeat.reference.yml
This fixes: https://github.com/elastic/beats/issues/19766
Basically, the `diskio` metricset was blindly summing read/write counts for all the devices reported by the docker stat API. This can produce incorrect results on systems where There's disks manage various child disks, and will sum the metrics from its children. For example, on a system running linux software RAID, we'll end up summing the metrics from both the raid device, and the metrics of the disks in the RAID array, effectively doubling the metrics. This Adds a "disks to skip" list, set to `9` and `253` (md raid devices and `device-mapper`) based on the major device number.
I added this as a configurable value out of paranoia, as this _technically_ changes how metrics are reported, and users may want to change it, or only skip …
=> Fix double-counted metrics in docker/diskio

CHANGELOG.next.asciidoc, filebeat/docs/autodiscover-hints.asciidoc
Extend documentation about hints for list and map data structures
- Closes https://github.com/elastic/beats/issues/19684
=> Documentation about the hints annotation for processors

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
Updates documentation for accessing `last_response.url.params` in httpjson input.
Previous documentation had `params` as a map which wasn't correct and lead to confusion about accessing the values in the `params`.
- Relates #30477
=> [Filebeat] httpjson update docs

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Fri, 11 Mar 2022 00:14:19 GMT, release_branch:8.1, prefix:, end_time:Fri, 11 Mar 2022 04:57:23 GMT, manifest_version:2.0.0, version:8.1.1-SNAPSHOT, branch:8.1, build_id:8.1.1-b9a6c108, build_duration_seconds:16984]
=> [automation] update elastic stack version for testing 8.1.1-b9a6c108

testing/environments/snapshot.yml
[start_time:Thu, 10 Mar 2022 18:52:36 GMT, release_branch:master, prefix:, end_time:Thu, 10 Mar 2022 23:38:30 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-63265ec9, build_duration_seconds:17154]
=> [automation] update elastic stack version for testing 8.2.0-63265ec9

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Sun, 13 Mar 2022 12:16:42 GMT, release_branch:8.1, prefix:, end_time:Sun, 13 Mar 2022 17:20:33 GMT, manifest_version:2.0.0, version:8.1.1-SNAPSHOT, branch:8.1, build_id:8.1.1-da392dcd, build_duration_seconds:18231]
=> [automation] update elastic stack version for testing 8.1.1-da392dcd

testing/environments/snapshot.yml
[start_time:Sun, 13 Mar 2022 12:16:37 GMT, release_branch:master, prefix:, end_time:Sun, 13 Mar 2022 17:22:42 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-d02c907a, build_duration_seconds:18365]
=> [automation] update elastic stack version for testing 8.2.0-d02c907a

filebeat/Jenkinsfile.yml, x-pack/filebeat/Jenkinsfile.yml
The 8.1 builds did not work as the compatibilty check was too narrow for beats including bugfix releases. Because of this, the temporary fix to skip the check was introduced. This removes this temporary fix again.
=> Remove temporary "Allow older" for 8.1

libbeat/docs/shared-faq.asciidoc
Fixes #https://github.com/elastic/beats/issues/28921
Related to Kibana change: https://github.com/elastic/kibana/pull/92540
- Docs update removing mention to the manual update of index pattern.
=> Update doc following 7.11 change on index pattern.

libbeat/docs/shared-ssl-config.asciidoc
Docs-only: update the documentation to clarify the real behavior of the `cipher_suites` parameter.
Fixes https://github.com/elastic/beats/issues/28791.
=> [Docs] Clarify cipher_suites parameter in TLS 1.3

testing/environments/snapshot.yml
[start_time:Mon, 14 Mar 2022 00:16:35 GMT, release_branch:master, prefix:, end_time:Mon, 14 Mar 2022 05:21:24 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-fee3b8d2, build_duration_seconds:18289]
=> [automation] update elastic stack version for testing 8.2.0-fee3b8d2

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 14 Mar 2022 12:13:26 GMT, release_branch:8.1, prefix:, end_time:Mon, 14 Mar 2022 16:59:13 GMT, manifest_version:2.0.0, version:8.1.1-SNAPSHOT, branch:8.1, build_id:8.1.1-2d188131, build_duration_seconds:17147]
=> [automation] update elastic stack version for testing 8.1.1-2d188131

Jenkinsfile, auditbeat/Jenkinsfile.yml, filebeat/Jenkinsfile.yml, heartbeat/Jenkinsfile.yml, metricbeat/Jenkinsfile.yml, packetbeat/Jenkinsfile.yml, winlogbeat/Jenkinsfile.yml, x-pack/auditbeat/Jenkinsfile.yml, x-pack/elastic-agent/Jenkinsfile.yml, x-pack/filebeat/Jenkinsfile.yml, x-pack/functionbeat/Jenkinsfile.yml, x-pack/heartbeat/Jenkinsfile.yml, x-pack/metricbeat/Jenkinsfile.yml, x-pack/osquerybeat/Jenkinsfile.yml, x-pack/packetbeat/Jenkinsfile.yml, x-pack/winlogbeat/Jenkinsfile.yml
Split the Windows OS build/test stages in two meta-stages:
- Mandatory for `windows-2022` and `windows-2016`. This is mandatory for all the builds in the CI (PRs, branches, tags)
- Extended support for other windows versions. This is only available for branches or UI interactions with the parameter `runAllStages`)
`Windows-2019` is not anymore the default OS but `windows-2022` and `windows-2016`
Removed tag event builds, every commit in this project is validated in the CI, so there is no need to run a build for tags.
Move the `arm` stages to mandatory.
Mandatory stages run always. But extended support for other windows versions only run for branches.
Faster builds on a PR basis since the extended meta-stage has been simplified a bit by moving some stages to the `mandatory` meta-stage or …
=> ci: split windows in mandatory and ext_win stages

CHANGELOG.next.asciidoc, auditbeat/scripts/mage/package.go, dev-tools/packaging/package_test.go, x-pack/auditbeat/auditbeat.elastic-agent.yml
Add a config file specifically for use by Elastic Agent. The default config file shipped
with Auditbeat enables several modules with example configs, but in Elastic Agent
we want Auditbeat to start without any modules enabled.
I think the cleanest approach is to ship an empty config that is specifically for Agent.
If we need to set Agent specific settings we can do that using this file in the future.
Another option I considered was to make Agent start Auditbeat with CLI flags
that disable the modules, but you have to do this per module (e.g. `-E auditbeat.modules.0.enabled=false`,
`-E auditbeat.modules.1.enabled=false`) and that is brittle given that the number of
modules varies by OS and someone could unknowingly change the default
config file.
Verification
```
$ tar tfv …
```
=> [Auditbeat] Add auditbeat.elastic-agent.yml config

libbeat/docs/shared-docker.asciidoc
Replaces https://github.com/elastic/beats/pull/30152.
Co-Authored-By: Dmitry <tevcef@gmail.com>
=> docs: correct example of --strict.perms usage

CHANGELOG.next.asciidoc, packetbeat/beater/install_npcap.go, packetbeat/beater/packetbeat.go, packetbeat/beater/processor.go, packetbeat/npcap/npcap.go, x-pack/packetbeat/magefile.go, x-pack/packetbeat/tests/system/app_test.go
This fixes a crash on Windows 10 when running Packetbeat.
The bug block all functionality on that platform.
This needs to be tested on a Windows 10 machine. I used StefanScherer/windows_10 with the beats Vagrantfile. Build x-pack/packetbeat with `go build` and run with `.\packetbeat -e -d *`. Check `C:\Program Files` for the presence of the Npcap installation directory. Without this fix, no install will result; after this fix a new installation will be present on exit (packetbeat will still exit with an error unless a network interface is setup on the VM).
- Closes #30820.
=> packetbeat/{beater,npcap}: prevent panic when querying Npcap version and perform install before all other work

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 15 Mar 2022 12:14:02 GMT, release_branch:8.1, prefix:, end_time:Tue, 15 Mar 2022 17:12:05 GMT, manifest_version:2.0.0, version:8.1.1-SNAPSHOT, branch:8.1, build_id:8.1.1-31faf00b, build_duration_seconds:17883]
=> [automation] update elastic stack version for testing 8.1.1-31faf00b

CHANGELOG.next.asciidoc, x-pack/metricbeat/module/gcp/metrics/compute/metadata.go
- Enhancement
details in #30153
- Closes #30153
=> [Metricbeat] improve efficiency of quering instance metadata in GCP metrics

Jenkinsfile
Apply https://github.com/elastic/beats/pull/30414 in the main pipeline.
`Packaging` pipeline is aimed to run on merge commits, while `main` pipeline runs on a PR basis too. Let's align the implementation since the scripts are not anymore available in Beats but in the apm-pipeline-library (see https://github.com/elastic/apm-pipeline-library/pull/1550)
I committed https://github.com/elastic/beats/pull/30795/commits/9aa8d3046187cc34f0c618a18285b8d348c947f4 to be able to trigger the package stage in the main pipeline:
and it worked:
https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats/detail/PR-30795/4/pipeline/33261#step-34606-log-1
I'll revert those changes now
=> ci: refactor pushDockerImages main pipeline

Jenkinsfile
Apply https://github.com/elastic/beats/pull/30409 in the main pipeline.
`Packaging` pipeline is aimed to run on merge commits, while `main` pipeline runs on a PR basis too. Let's use the same implementation (see https://github.com/elastic/apm-pipeline-library/pull/1549)
I committed https://github.com/elastic/beats/pull/30796/commits/209979fd45d6122d5a931cc6ed7aca583cc9e3b0 to be able to trigger the package stage in the main pipeline:
=> ci: refactor publishPackages main pipeline

x-pack/osquerybeat/ext/osquery-extension/pkg/proc/cmdline.go, x-pack/osquerybeat/ext/osquery-extension/pkg/proc/cmdline_test.go, x-pack/osquerybeat/ext/osquery-extension/pkg/proc/io.go, x-pack/osquerybeat/ext/osquery-extension/pkg/proc/io_test.go, x-pack/osquerybeat/ext/osquery-extension/pkg/proc/link.go, x-pack/osquerybeat/ext/osquery-extension/pkg/proc/list.go, x-pack/osquerybeat/ext/osquery-extension/pkg/proc/list_test.go, x-pack/osquerybeat/ext/osquery-extension/pkg/proc/stat.go, x-pack/osquerybeat/ext/osquery-extension/pkg/proc/stat_test.go, x-pack/osquerybeat/ext/osquery-extension/pkg/proc/uptime.go, x-pack/osquerybeat/ext/osquery-extension/pkg/proc/uptime_test.go
This PR enhance the functionality of the `procfs` so it can also support file system injection. 
This change is important for two reasons:
1. It let the user expose only a part of his file system/give a relative path.
2. It enhances the functionality such that a developer can use an in-memory file system such as [`fstest`](https://pkg.go.dev/testing/fstest)
This change is required by the @elastic/cloud-posture-security, since we are using this extension and would like to write test using `fstest`.
- Relates [#3263](https://github.com/elastic/security-team/issues/3263)
- Closes: https://github.com/elastic/security-team/issues/3320
=> refactor code to support fsFS

metricbeat/module/kubernetes/test/integration.go
Align testing with https://github.com/elastic/beats/pull/26729 after default k8s version for integration test was updated at https://github.com/elastic/beats/pull/30747.
Actually this is due to https://github.com/elastic/infra/pull/35111, because for `goInteg` tests `kind` is a requirement and is actually installed by default on the workers by https://github.com/elastic/infra/pull/35111.
=> Fix scheduler and controllermanager k8s tests

testing/environments/snapshot.yml
[start_time:Wed, 16 Mar 2022 15:50:14 GMT, release_branch:master, prefix:, end_time:Wed, 16 Mar 2022 23:01:34 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-ff67d7b8, build_duration_seconds:25880]
=> [automation] update elastic stack version for testing 8.2.0-ff67d7b8

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 16 Mar 2022 05:13:53 GMT, release_branch:7.17, prefix:, end_time:Wed, 16 Mar 2022 13:13:06 GMT, manifest_version:2.0.0, version:7.17.2-SNAPSHOT, branch:7.17, build_id:7.17.2-8f7db3a8, build_duration_seconds:28753]
=> [automation] update elastic stack version for testing 7.17.2-8f7db3a8

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 16 Mar 2022 15:42:35 GMT, release_branch:8.1, prefix:, end_time:Wed, 16 Mar 2022 22:24:13 GMT, manifest_version:2.0.0, version:8.1.1-SNAPSHOT, branch:8.1, build_id:8.1.1-9bb65a23, build_duration_seconds:24098]
=> [automation] update elastic stack version for testing 8.1.1-9bb65a23

filebeat/_meta/config/filebeat.inputs.reference.yml.tmpl, filebeat/docs/inputs/input-filestream-file-options.asciidoc, filebeat/filebeat.reference.yml, x-pack/filebeat/filebeat.reference.yml
This PR fixes the name of the option that tells filestream input to close files after reaching EOF. The incorrect name was `close.reader.eof`. Now the correct name `close.reader.on_eof` is used in documentation and reference configuration.
Misleading information is removed from docs.
=> Fix the name `close.reader.on_eof` in reference configuration and documentation

auditbeat/Jenkinsfile.yml, filebeat/Jenkinsfile.yml, heartbeat/Jenkinsfile.yml, libbeat/Jenkinsfile.yml, metricbeat/Jenkinsfile.yml, packetbeat/Jenkinsfile.yml, x-pack/auditbeat/Jenkinsfile.yml, x-pack/elastic-agent/Jenkinsfile.yml, x-pack/filebeat/Jenkinsfile.yml, x-pack/functionbeat/Jenkinsfile.yml, x-pack/packetbeat/Jenkinsfile.yml, x-pack/winlogbeat/Jenkinsfile.yml
Use the right meta-stages for the ARM and windows workers
Ensure we can cope with the build capacities by reducing what we run in parallel:
1) Mandatory is linux and windows-2022/windows-2016
2) Extended is ARM
3) Extended-Win is the one for all the remaining windows versions.
Used to be:
And
=> ci: extended meta-stage for ARM and extended_win for Windows-2019

CHANGELOG.next.asciidoc, x-pack/heartbeat/monitors/browser/synthexec/enrich_test.go, x-pack/heartbeat/monitors/browser/synthexec/synthexec.go, x-pack/heartbeat/monitors/browser/synthexec/synthexec_test.go
This PR fixes #30729 by always emitting `heartbeat/summary` documents when a command exits without `journey/end`.
These documents have the following message:
> journey did not finish executing, X steps ran
Such a change will cause the Uptime UI to be able to display correct results even if a journey execution exits successfully but doesn't manage to write a `journey/end` event to the desired descriptor. Such a situation could happen when the synthetics runner buffer was full and wasn't emptied on time before the command's exit, as described in https://github.com/elastic/synthetics/issues/446 and fixed in https://github.com/elastic/synthetics/pull/465
I've done so myself, but would like reviewers to verify the following:
To test this PR locally you must have a version of the `synthetics` …
=> Emit summaries when synthetics exits without emitting journey/end [#30729]

x-pack/osquerybeat/internal/distro/distro.go
Upgrades osquery to 5.2.2. 
* Updates to the latest release of osquery.
* Picks up our contribution to osquery that was included in this release of osquery:
```
Add windows_firewall_rules table for windows
```
* Install the agent with osquery manager added to the policy, issue ```select * from windows_firewall_rules``` live query, observe result from this new table.
- Relates https://github.com/elastic/security-team/issues/3302
=> Upgrade osquery to 5.2.2

CHANGELOG.next.asciidoc, packetbeat/sniffer/afpacket_linux.go, packetbeat/sniffer/afpacket_nonlinux.go, packetbeat/sniffer/sniffer.go
Previously we were using github.com/tsg/gopacket, an older fork of github.com/google/gopacket
with additions that were necessary to support functionality that we needed. In 274ccac we
changed over to a more recent fork of github.com/google/gopacket porting forward some of the
changes that we had made to a collection of forks. A significant difference between the tsg
fork and the google package, not found until now was in how poll calls are handled in the
afpacket package; in the tsg fork, a zero poll event count was returned as EINTR
func (h *TPacket) pollForFirstPacket(hdr header) error {
for hdr.getStatus()&C.TP_STATUS_USER == 0 {
h.pollset.fd = h.fd
h.pollset.events = C.POLLIN
h.pollset.revents = 0
timeout := C.int(h.opts.timeout / time.Millisecond)
n, err := C.poll(&h.pollset, 1, …
=> packetbeat/sniffer: update error check to match github.com/google/gopacket/afpacket API

testing/environments/snapshot.yml
[start_time:Fri, 18 Mar 2022 00:16:30 GMT, release_branch:master, prefix:, end_time:Fri, 18 Mar 2022 04:22:19 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-82b803a1, build_duration_seconds:14749]
=> [automation] update elastic stack version for testing 8.2.0-82b803a1

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 17 Mar 2022 05:13:20 GMT, release_branch:7.17, prefix:, end_time:Thu, 17 Mar 2022 19:23:04 GMT, manifest_version:2.0.0, version:7.17.2-SNAPSHOT, branch:7.17, build_id:7.17.2-15b5bc7a, build_duration_seconds:50984]
=> [automation] update elastic stack version for testing 7.17.2-15b5bc7a

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 17 Mar 2022 12:13:54 GMT, release_branch:8.1, prefix:, end_time:Thu, 17 Mar 2022 17:04:13 GMT, manifest_version:2.0.0, version:8.1.1-SNAPSHOT, branch:8.1, build_id:8.1.1-da22c151, build_duration_seconds:17419]
=> [automation] update elastic stack version for testing 8.1.1-da22c151

testing/environments/snapshot.yml
[start_time:Mon, 21 Mar 2022 00:15:35 GMT, release_branch:master, prefix:, end_time:Mon, 21 Mar 2022 04:55:24 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-5cc993c1, build_duration_seconds:16789]
=> [automation] update elastic stack version for testing 8.2.0-5cc993c1
