elastic/beats

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Sun, 20 Mar 2022 05:13:32 GMT, release_branch:7.17, prefix:, end_time:Sun, 20 Mar 2022 09:40:07 GMT, manifest_version:2.0.0, version:7.17.2-SNAPSHOT, branch:7.17, build_id:7.17.2-3b3b663d, build_duration_seconds:15995]

[automation] update elastic stack version for testing 7.17.2-3b3b663d

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Sun, 20 Mar 2022 00:16:27 GMT, release_branch:8.1, prefix:, end_time:Sun, 20 Mar 2022 04:55:02 GMT, manifest_version:2.0.0, version:8.1.1-SNAPSHOT, branch:8.1, build_id:8.1.1-0d572bb7, build_duration_seconds:16715]

[automation] update elastic stack version for testing 8.1.1-0d572bb7

---

.ci/packaging.groovy

Combine linux and arm stages in one stage
Remove macos packaging support (it has not never been enabled, and the MacOS static worker is gone 😢 )
Faster builds with more parallel stages
See [build](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fpackaging/detail/PR-30904/7/pipeline)

ci: packaging speed up

---

x-pack/osquerybeat/dev-tools/packaging/packages.yml
x-pack/osquerybeat/internal/distro/distro.go

Adds support for osquerybeat darwin/arm64 packaging
Fixes the issue with Apple M1 build https://github.com/elastic/elastic-agent/pull/203
- Relates https://github.com/elastic/elastic-agent/pull/203

Osquerybeat: Add darwin/arm64 packaging support

---

testing/environments/snapshot.yml

[start_time:Tue, 22 Mar 2022 00:14:32 GMT, release_branch:master, prefix:, end_time:Tue, 22 Mar 2022 04:41:52 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-63942b4d, build_duration_seconds:16040]

[automation] update elastic stack version for testing 8.2.0-63942b4d

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Mon, 21 Mar 2022 05:13:35 GMT, release_branch:7.17, prefix:, end_time:Mon, 21 Mar 2022 09:40:36 GMT, manifest_version:2.0.0, version:7.17.2-SNAPSHOT, branch:7.17, build_id:7.17.2-81597e21, build_duration_seconds:16021]

[automation] update elastic stack version for testing 7.17.2-81597e21

---

Jenkinsfile
libbeat/tests/system/requirements.txt
libbeat/tests/system/requirements_aix.txt

Uses [pytes-otel](https://pypi.org/project/pytest-otel/) to report OpenTelemetry data related to Python tests 
The OpenTelemetry spans send will be used to analyze the test results.
- ~[ ] I have commented my code, particularly in hard-to-understand areas~
- ~[ ] I have added tests that prove my fix is effective or that my feature works~
- ~[ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~

feat: report Otel data on Python tests

---

CHANGELOG.next.asciidoc
metricbeat/module/kubernetes/_meta/kibana/7/dashboard/e0381d10-e4a6-11eb-9d53-3b3d1d47c519.json
metricbeat/module/kubernetes/_meta/kibana/7/visualization/022a54c0-2bf5-11e7-859b-f78b612cde28-ecs.json
metricbeat/module/kubernetes/_meta/kibana/7/visualization/16fa4470-2bfd-11e7-859b-f78b612cde28-ecs.json
metricbeat/module/kubernetes/_meta/kibana/7/visualization/174a6ad0-30e0-11e7-8df8-6d3604a72912-ecs.json
metricbeat/module/kubernetes/_meta/kibana/7/visualization/294546b0-30d6-11e7-8df8-6d3604a72912-ecs.json
metricbeat/module/kubernetes/_meta/kibana/7/visualization/408fccf0-30d6-11e7-8df8-6d3604a72912-ecs.json
metricbeat/module/kubernetes/_meta/kibana/7/visualization/44f12b40-2bf4-11e7-859b-f78b612cde28-ecs.json
metricbeat/module/kubernetes/_meta/kibana/7/visualization/58e644f0-30d6-11e7-8df8-6d3604a72912-ecs.json
metricbeat/module/kubernetes/_meta/kibana/7/visualization/7aac4fd0-30e0-11e7-8df8-6d3604a72912-ecs.json
metricbeat/module/kubernetes/_meta/kibana/7/visualization/a4c9d360-30df-11e7-8df8-6d3604a72912-ecs.json
metricbeat/module/kubernetes/_meta/kibana/7/visualization/cd059410-2bfb-11e7-859b-f78b612cde28-ecs.json
metricbeat/module/kubernetes/_meta/kibana/7/visualization/d54c65f0-e4a6-11eb-9d53-3b3d1d47c519.json
metricbeat/module/kubernetes/_meta/kibana/7/visualization/d6564360-2bfc-11e7-859b-f78b612cde28-ecs.json
metricbeat/module/kubernetes/_meta/kibana/7/visualization/da1ff7c0-30ed-11e7-b9e5-2b5b07213ab3-ecs.json
metricbeat/module/kubernetes/_meta/kibana/7/visualization/e1018b90-2bfb-11e7-859b-f78b612cde28-ecs.json

This PR leverages https://github.com/elastic/kibana/pull/126015 in order to solve https://github.com/elastic/integrations/issues/2159
At the moment the k8s Dashboard can be showing inconsistent values in the views for the "Desired", "Available" and "Unavailable" Pods. The reason is described at https://github.com/elastic/integrations/issues/2159. With this chance we aim to improve the situation so as the views to be showing correct values by using the proper aggregations.
- Relates https://github.com/elastic/integrations/issues/2159
Changing the time range of the dashboard was giving inconsistent values in the views. Below find attached the consistent views with different time ranges:

Improve k8s dashboard

---

dev-tools/cmd/dashboards/export_dashboards.go
metricbeat/magefile.go

This PR adds `ExportDashboard` target in magefile of Metricbeat and fixes username+password defaults order in `dev-tools/cmd/dashboards/export_dashboards.go`
So as to make it possible to export Metricbeat dashboards with a command like `KIBANA_URL=http://elastic:changeme@0.0.0.0:5601 MODULE=kubernetes ID=e0381d10-e4a6-11eb-9d53-3b3d1d47c519 mage ExportDashboard`
Related to https://github.com/elastic/beats/pull/30913

Fix export dashboards scripts

---

testing/environments/snapshot.yml

[start_time:Wed, 23 Mar 2022 00:14:15 GMT, release_branch:master, prefix:, end_time:Wed, 23 Mar 2022 04:33:22 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-4509f321, build_duration_seconds:15547]

[automation] update elastic stack version for testing 8.2.0-4509f321

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Tue, 22 Mar 2022 05:13:52 GMT, release_branch:7.17, prefix:, end_time:Tue, 22 Mar 2022 09:41:23 GMT, manifest_version:2.0.0, version:7.17.2-SNAPSHOT, branch:7.17, build_id:7.17.2-70a05b08, build_duration_seconds:16051]

[automation] update elastic stack version for testing 7.17.2-70a05b08

---

.ci/packaging.groovy
auditbeat/magefile.go
dev-tools/mage/common.go
dev-tools/mage/crossbuild.go
dev-tools/mage/pkg.go
dev-tools/mage/pkgtypes.go
dev-tools/mage/platforms.go
dev-tools/mage/settings.go
dev-tools/mage/target/build/build.go
filebeat/magefile.go
libbeat/magefile.go
packetbeat/magefile.go
x-pack/auditbeat/magefile.go
x-pack/dockerlogbeat/magefile.go
x-pack/filebeat/magefile.go
x-pack/functionbeat/magefile.go
x-pack/libbeat/magefile.go
x-pack/metricbeat/magefile.go
x-pack/osquerybeat/dev-tools/packaging/packages.yml
x-pack/osquerybeat/internal/distro/distro.go
x-pack/osquerybeat/magefile.go
x-pack/packetbeat/magefile.go

It enables the Elastic-Agent and Beats to be built for `darwin/arm64` and generates a universal binary (`darwin/universal`).
The [universal binary](https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary) is the merge of the `darwin/arm64` with `darwin/amd64`. Therefore it requires to first build the  `darwin/arm64` and `darwin/amd64` and them _"merge"_ them together into the `darwin/universal`. Also `darwin/universal` isn't a valid platform or OS/ARCH pair, therefore it isn't recognised by the Go compiler. Given that, the choice was to add `darwin/arm64` as a new platform for the Elastic-Agent and when ever both platforms (`darwin/arm64` and `darwin/amd64`) are built, also generate and package the universal binary.
Even though  it's ~quite~ an implicit …

[Beats] Build darwin/arm64 and universal binary

---

metricbeat/module/system/memory/memory.go

- Bug
This fixes a dropped `err` variable in `metricbeat/module/system/memory`.

metricbeat/module/system/memory: fix dropped error

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Thu, 24 Mar 2022 00:13:50 GMT, release_branch:8.1, prefix:, end_time:Thu, 24 Mar 2022 04:54:25 GMT, manifest_version:2.0.0, version:8.1.2-SNAPSHOT, branch:8.1, build_id:8.1.2-2393b0c1, build_duration_seconds:16835]

[automation] update elastic stack version for testing 8.1.2-2393b0c1

---

.github/workflows/golangci-lint.yml
CHANGELOG-developer.next.asciidoc
Jenkinsfile

Now the linting issues will be displayed in the PR diff on Github and
one can see the issues inline during the review.
After getting some feedback related to https://github.com/elastic/beats/pull/30896
and some testing of the Github action in https://github.com/elastic/elastic-agent-libs/pull/30 the solution how to make this setup reliable was found and now we can switch to the Github action.

Move linting to a Github action for better integration

---

libbeat/tests/system/requirements.txt

Update to the latest 2.11.x release. Matches what is used on AIX.

Update Jinja2 version used in tests to 2.11.3.

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Wed, 23 Mar 2022 05:17:15 GMT, release_branch:7.17, prefix:, end_time:Wed, 23 Mar 2022 09:45:14 GMT, manifest_version:2.0.0, version:7.17.2-SNAPSHOT, branch:7.17, build_id:7.17.2-1941719d, build_duration_seconds:16079]

[automation] update elastic stack version for testing 7.17.2-1941719d

---

metricbeat/module/kubernetes/scheduler/scheduler_integration_test.go
metricbeat/module/kubernetes/scheduler/scheduler_test.go

https://github.com/elastic/beats/issues/30973
https://github.com/elastic/beats/pull/30990 skipped the wrong test in the affected package.

Disable the failing k8s scheduler integration test.

---

metricbeat/module/linux/memory/data.go

This fixes a dropped `err` variable in `metricbeat/module/linux/memory`.

metricbeat/module/linux/memory: fix dropped error

---

testing/environments/snapshot.yml

[start_time:Thu, 24 Mar 2022 14:05:21 GMT, release_branch:master, prefix:, end_time:Thu, 24 Mar 2022 18:23:25 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-dcff22d7, build_duration_seconds:15484]

[automation] update elastic stack version for testing 8.2.0-dcff22d7

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Fri, 25 Mar 2022 00:16:28 GMT, release_branch:8.1, prefix:, end_time:Fri, 25 Mar 2022 04:59:50 GMT, manifest_version:2.0.0, version:8.1.2-SNAPSHOT, branch:8.1, build_id:8.1.2-5d446358, build_duration_seconds:17002]

[automation] update elastic stack version for testing 8.1.2-5d446358

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Sat, 26 Mar 2022 05:16:10 GMT, release_branch:7.17, prefix:, end_time:Sat, 26 Mar 2022 09:42:10 GMT, manifest_version:2.0.0, version:7.17.2-SNAPSHOT, branch:7.17, build_id:7.17.2-cf7cf1eb, build_duration_seconds:15960]

[automation] update elastic stack version for testing 7.17.2-cf7cf1eb

---

libbeat/cmd/instance/metrics/metrics.go

This is a continuation of https://github.com/elastic/beats/pull/30228
Although as @jlind23 mentioned, we initially didn't want to backport this as we don't have much testing in this area, however it's still filling up log files for people, so this is a conservative "backport" that just gives us the change that should eliminate the error when running under certain container schemes.
This fixes a source of log spam for user running certain container setups.

Add workaround to cgroups self-monitoring error messages in 7.17 releases

---

auditbeat/main_test.go
packetbeat/main.go
packetbeat/main_test.go
winlogbeat/main_test.go
x-pack/auditbeat/main_test.go
x-pack/filebeat/input/httpjson/config_auth.go
x-pack/filebeat/input/httpjson/config_request.go
x-pack/filebeat/input/httpjson/encoding.go
x-pack/filebeat/input/httpjson/input_cursor.go
x-pack/filebeat/input/httpjson/input_stateless.go
x-pack/filebeat/input/httpjson/input_test.go
x-pack/filebeat/input/httpjson/pagination.go
x-pack/filebeat/input/httpjson/rate_limiter.go
x-pack/filebeat/input/httpjson/rate_limiter_test.go
x-pack/filebeat/input/httpjson/request.go
x-pack/filebeat/input/httpjson/response.go
x-pack/filebeat/input/httpjson/split.go
x-pack/filebeat/input/httpjson/transform.go
x-pack/filebeat/input/httpjson/transform_append.go
x-pack/filebeat/input/httpjson/transform_append_test.go
x-pack/filebeat/input/httpjson/transform_delete.go
x-pack/filebeat/input/httpjson/transform_delete_test.go
x-pack/filebeat/input/httpjson/transform_set.go
x-pack/filebeat/input/httpjson/transform_set_test.go
x-pack/filebeat/input/httpjson/transform_test.go
x-pack/filebeat/input/httpjson/value_tpl.go
x-pack/winlogbeat/main_test.go

Fixes lint or suppresses linter complaints depending on issue.
This will remove the need to include irrelevant diff noise in future PRs forced by the linter.
-

{,x-pack/}{auditbeat,packetbeat,winlogbeat,filebeat/input/httpjson}: fix lint and silence linters

---

CHANGELOG.next.asciidoc
x-pack/filebeat/input/httpjson/request.go
x-pack/filebeat/input/httpjson/response.go

This change ensures that request interval data is not cleared after a request has begun.
Although extremely unlikely, there is otherwise no happens before relationship between the clearing of request interval data and the processing of the obtained data. If the interval data has been cleared during a request, spurious default first and last event, and last response values in the transform context can be set in the resulting published event.
The conditions for this to happen are that the request manages to progress at least one page of the pagination iterator before the call to `trCtx.clearIntervalData()` can complete. The chances of this happening are vanishingly small. However...
```
[2022-02-27T03:07:14.640Z] === Failed
[2022-02-27T03:07:14.640Z] === FAIL: x-pack/filebeat/input/httpjson …
```

x-pack/filebeat/input/httpjson: make sure interval data clearing happens before processing

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Mon, 28 Mar 2022 05:13:42 GMT, release_branch:7.17, prefix:, end_time:Mon, 28 Mar 2022 09:41:14 GMT, manifest_version:2.0.0, version:7.17.2-SNAPSHOT, branch:7.17, build_id:7.17.2-99f889e2, build_duration_seconds:16052]

[automation] update elastic stack version for testing 7.17.2-99f889e2

---

.github/CODEOWNERS

The following is a detailed update of the codeowners file for the different teams. Each top level directory is listed with the team that owns it. In some cases like modules more specific details were added. Every time we see some specific directories belong to a team, the Codeowners file should be updated.
The goal of this PR is to have alignment across all the teams on ownership.
Few additional notes:
* The robots team is not an owner of any files / directories. This is by design as the final ownership of the build is with the data plane team.
* Modules are owned by default by the integrations team. More details must be added here.
* system tests are not covered in details

[Discuss] Update Codeowners file

---

CHANGELOG.next.asciidoc
filebeat/input/filestream/internal/input-logfile/store.go
filebeat/input/filestream/internal/input-logfile/store_test.go

The mutex of the resource was mistakenly overwritten with a new one
and then unlocking this new mutex caused it to panic.
Our customers faced this issue and it crashes filebeat.
1. Create a folder, e.g. `/home/user/input`
2. Create this configuration file e.g. `/home/filebeat_lock_panic.yml`:
```yaml
logging:
level: debug
output.console:
enabled: true
paths:
- "/home/user/input/input/pattern1.log*"
rotation.external.strategy.copytruncate:
suffix_regex: '\.\d+$'
paths:
- "/home/user/input/pattern2.log*" …
```

Fix panic in the filestream harvester

---

libbeat/docs/security/users.asciidoc

This PR updates the required priviledges of Beats during setup and publishing phase.
Beats do not load ML jobs since 8.0, so ML priviledges are unnecessary. Also, Beats do not use aliases, so there is no need for access to them. Instead we load a data stream, so the reason for `manage` priviledge is updated.

Update the list of required priviledges during setup and publishing

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Tue, 29 Mar 2022 05:14:03 GMT, release_branch:7.17, prefix:, end_time:Tue, 29 Mar 2022 09:39:22 GMT, manifest_version:2.0.0, version:7.17.2-SNAPSHOT, branch:7.17, build_id:7.17.2-a218ac35, build_duration_seconds:15919]

[automation] update elastic stack version for testing 7.17.2-a218ac35

---

.github/CODEOWNERS

The CODEOWNERS file contained too many comments and it become complex on where to add entries as entries were grouped by teams. Instead the list is now simplified and sorted alphabetically.
No changers were made to the file except the monitors.d directory was removed as it does not exist anymore.

Sort content of CODEOWNERS file

---

.mergify.yml

Merge as soon as 8.2 branch was created. Auto-merge is not yet supported, see https://github.com/Mergifyio/mergify-engine/discussions/2821

backport: Add 8.2 branch

---

libbeat/docs/howto/load-index-templates.asciidoc

This PR adds the one more extra step required for template loading since 8.0. As we are using data streams, it has to be created in advance, so publisher users do not need extra permissions.
Without loading the data stream, the publisher user needs unnecessary permissions. It is better to add the data stream in advance, after loading the index template.

Add data stream loading step to manual index loading guide

---

metricbeat/docker-compose.yml
metricbeat/module/logstash/docker-compose.yml
testing/environments/latest.yml
x-pack/metricbeat/docker-compose.yml

Merge only after the release of 7.17.2.

[Release] Update test environments for 7.17.3

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Thu, 31 Mar 2022 23:59:41 GMT, release_branch:7.17, prefix:, end_time:Fri, 1 Apr 2022 04:14:55 GMT, manifest_version:2.0.0, version:7.17.3-SNAPSHOT, branch:7.17, build_id:7.17.3-22be2d34, build_duration_seconds:15314]

[automation] update elastic stack version for testing 7.17.3-22be2d34

---

.github/CODEOWNERS

This takes the changes applied to the 8.x CODEOWNERS file and applies the change to 7.17. The only difference is the addtion of the elastic-agent directory for the control plane team.

Update CODEOWNERS file for 7.17

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Thu, 31 Mar 2022 05:14:06 GMT, release_branch:8.1, prefix:, end_time:Thu, 31 Mar 2022 10:03:46 GMT, manifest_version:2.0.0, version:8.1.2-SNAPSHOT, branch:8.1, build_id:8.1.2-ed029c28, build_duration_seconds:17380]

[automation] update elastic stack version for testing 8.1.2-ed029c28

---

deploy/kubernetes/Jenkinsfile.yml
metricbeat/module/kubernetes/scheduler/scheduler_integration_test.go
metricbeat/module/kubernetes/test/integration.go

Enable back k8s scheduler integration test.
Closes https://github.com/elastic/beats/issues/30973

Enable k8s scheduler test

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Sun, 3 Apr 2022 05:15:58 GMT, release_branch:7.17, prefix:, end_time:Sun, 3 Apr 2022 09:36:08 GMT, manifest_version:2.0.0, version:7.17.3-SNAPSHOT, branch:7.17, build_id:7.17.3-42e5086c, build_duration_seconds:15610]

[automation] update elastic stack version for testing 7.17.3-42e5086c

---

testing/environments/snapshot.yml

[start_time:Thu, 31 Mar 2022 12:15:08 GMT, release_branch:master, prefix:, end_time:Fri, 1 Apr 2022 02:36:15 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-1ecd9720, build_duration_seconds:51667]

[automation] update elastic stack version for testing 8.3.0-1ecd9720

---

.ci/packaging.groovy
.ci/scripts/prepare-release-manager.sh

- Enable `snapshot` workflow for `main` and release branches. Stage `DRA Snapshot`
- Enable `staging` workflow for release branches. Stage `DRA Staging`
- Use the same node where the specific packages are generated for each beat, and run first the `snapshot` and then `staging` (aka SNAPSHOT=false)
- `staging` artifacts are uploaded to the `staginig` subfolder in the Google Bucket while `snapshot` artifacts are uploaded to the `commits` folder (this is the default behaviour we had in place)
See [job](https://beats-ci.elastic.co/job/Beats/job/packaging/view/change-requests/job/PR-31092/)
Produced:
- snapshot -> https://artifacts-snapshot.elastic.co/beats/8.3.0-c1154f51/summary-8.3.0-SNAPSHOT.html
- staging -> https://artifacts-staging.elastic.co/beats/8.3.0-7fb50dba/summary-8.3.0.html

DRA: support for staging

---

.ci/packaging.groovy

Fail the build if the e2e-testing failed
Otherwise the `DRA` stages are triggered regardless and therefore the staging or snapshot artifacts are uploaded. While the `e2e-testing` is the quality gate keeper

ci: e2e-testing should fail the build

---

metricbeat/docker-compose.yml
testing/environments/latest.yml
x-pack/metricbeat/docker-compose.yml

This updates the test environments to next minor release which is 8.3.0.

[Release] Update test environment to 8.3.0

---

x-pack/functionbeat/manager/cmd/root.go

Missed in a previous commit removing a log message: https://github.com/elastic/beats/pull/31133
Causing CI to fail for main on the `mage check` target.

Remove the unused "fmt" import.

---

x-pack/auditbeat/docker-compose.yml

_This is a test to see if it fixes CI._
Make sure /etc/machine-id is present in containers that are
running system tests to ensure that the host ID is available for
computing entity_id values for events.
Fixes tests that are failing on CI due to a change to the debian:bullseye base image to remove /etc/machine-id.
this PR will be tested by the reviewer: commands, dependencies, steps, etc.
There were warnings in the Auditbeat output. And you can see that the the `host.id` is missing from the "Host info" log message.
```
{
"log.level": "info",
"@timestamp": "2022-03-30T23:53:33.670Z",
"log.logger": "beat",
"file.name": "instance/beat.go",
"file.line": 1079
},
"message": "Host info",
"service.name": "auditbeat",
"system_info": {
"host": {
"architecture": "x86_64", …
```

[Auditbeat] Mount /etc/machine-id in auditbeat test container

---

testing/environments/snapshot.yml

[start_time:Mon, 4 Apr 2022 15:09:13 GMT, release_branch:master, prefix:, end_time:Mon, 4 Apr 2022 21:39:53 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-657f2d50, build_duration_seconds:23440]

[automation] update elastic stack version for testing 8.3.0-657f2d50

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Mon, 4 Apr 2022 05:13:27 GMT, release_branch:7.17, prefix:, end_time:Mon, 4 Apr 2022 09:40:51 GMT, manifest_version:2.0.0, version:7.17.3-SNAPSHOT, branch:7.17, build_id:7.17.3-206df1ed, build_duration_seconds:16044]

[automation] update elastic stack version for testing 7.17.3-206df1ed

---

metricbeat/module/docker/container/container.go
metricbeat/module/docker/container/data.go
metricbeat/module/kubernetes/apiserver/metricset.go
metricbeat/module/kubernetes/container/container.go
metricbeat/module/kubernetes/container/container_test.go
metricbeat/module/kubernetes/container/data.go
metricbeat/module/kubernetes/event/event.go
metricbeat/module/kubernetes/event/event_test.go
metricbeat/module/kubernetes/kubernetes.go
metricbeat/module/kubernetes/node/data.go
metricbeat/module/kubernetes/node/node.go
metricbeat/module/kubernetes/node/node_test.go
metricbeat/module/kubernetes/pod/data.go
metricbeat/module/kubernetes/pod/pod.go
metricbeat/module/kubernetes/pod/pod_test.go
metricbeat/module/kubernetes/state_container/state_container.go
metricbeat/module/kubernetes/system/data.go
metricbeat/module/kubernetes/system/system.go
metricbeat/module/kubernetes/system/system_test.go
metricbeat/module/kubernetes/util/kubernetes.go
metricbeat/module/kubernetes/util/kubernetes_test.go
metricbeat/module/kubernetes/volume/data.go
metricbeat/module/kubernetes/volume/volume.go
metricbeat/module/kubernetes/volume/volume_test.go

Improve error handling in the Kubernetes module. This PR introduces error handling for optional fields in MapStr structs by logging the error with Debug level. Thus removing linter errors.
We want to improve the quality of our code and make it compliant with golang-ci linter
cd metricbeat
mage unitTest
- Closes [#31067](https://github.com/elastic/beats/issues/31067)

wrap all optional mapStr.Put in kuberntes module with debug logs

---

.github/stale.yml

This makes the issue stale message friendlier and consistent with the message we use
for PRs.
We had some cases when external contributors got very frustrated with
the stale message in old issues. It might sound like we completely
dismiss the effort.

Make the stale message for issues more friendly

---

libbeat/kibana/client_test.go
libbeat/tests/system/test_dashboard.py

Cleans up the dashboard system tests by removing a broken test, and related tests that do not provide any valuable test coverage.
At some point in the past (during 8.0) the `test_dev_tool_export_dashboard_by_id_from_space` broke. The reason it broke is that we upload the same dashboards multiple times as part of the test, and there must have been a change in Kibana to ensure that all dashboards have unique `id` fields by generating a UUID on conflict. This made it so that we could not export the dashboard using the original ID anymore, breaking the test.
Previously the affected dashboard would always have root attributes like this:
```json
"type": "dashboard",
"id": "Metricbeat-system-overview",
"namespaces": [
"foo-bar"
],
```
At some point it changed so that uploading a dashboard with …

Fix export dashboards

---

.github/workflows/elastic-agent-project-board.yml

Automation was removed when we move Elastic Agent out of Beats. The aim of this PR is to create it again.

Add automation for project board

---

CHANGELOG.next.asciidoc
x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
x-pack/filebeat/input/httpjson/value_tpl.go
x-pack/filebeat/input/httpjson/value_tpl_test.go

Add URL Encode tempalte function for httpjson input
When manually constructing the `url.value` if there are values that need to be URL encoded.
- Relates elastic/integrations#2715

[Filebeat] Add URL Encode template function for httpjson input

---

testing/environments/snapshot.yml

[start_time:Tue, 5 Apr 2022 22:51:10 GMT, release_branch:master, prefix:, end_time:Wed, 6 Apr 2022 02:52:40 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-00f4f855, build_duration_seconds:14490]

[automation] update elastic stack version for testing 8.3.0-00f4f855

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Tue, 5 Apr 2022 05:14:45 GMT, release_branch:7.17, prefix:, end_time:Tue, 5 Apr 2022 10:51:34 GMT, manifest_version:2.0.0, version:7.17.3-SNAPSHOT, branch:7.17, build_id:7.17.3-60b577ee, build_duration_seconds:20209]

[automation] update elastic stack version for testing 7.17.3-60b577ee

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Tue, 5 Apr 2022 05:17:15 GMT, release_branch:8.1, prefix:, end_time:Tue, 5 Apr 2022 11:40:01 GMT, manifest_version:2.0.0, version:8.1.3-SNAPSHOT, branch:8.1, build_id:8.1.3-c3f4b7e6, build_duration_seconds:22966]

[automation] update elastic stack version for testing 8.1.3-c3f4b7e6

---

CHANGELOG.next.asciidoc
x-pack/libbeat/common/aws/credentials.go

Set up the `AssumeRoleProvider` after the AWS region value from Filebeat settings is applied to the AWS SDK configuration.
When Filebeat uses a role ARN, it sets up `AssumeRoleProvider` before evaluating the region value from its settings.
If the AWS SDK configuration loaded from `~/.aws/config` does not contain a region, the error described in #30999 happens.
Requirements:
- A SQS queue (in this example, `https://sqs.eu-west-1.amazonaws.com/000123456789/elastic-cloudtrail-logs`),
- an IAM role ARN (in this example, `arn:aws:iam::000123456789:role/elastic-agent-role`)
Configure the IAM Role as EC2 instance role with the following trust relationship:
```json
{
"Version": "2012-10-17",
"Statement": [
{
"Effect": "Allow",
"Principal": {
"Service": "ec2.amazonaws.com"
},
"Action": …
```

[libbeat][aws] Fix AWS config initialization issue when using a role

---

libbeat/tests/system/beat/beat.py

We have often timeout failures in our builds related to this short
timeout of 10 seconds.
For example, https://github.com/elastic/beats/runs/5849692789

Extend wait timeout in python tests

---

testing/environments/snapshot.yml

[start_time:Wed, 6 Apr 2022 00:18:20 GMT, release_branch:8.2, prefix:, end_time:Wed, 6 Apr 2022 04:10:23 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-fdfc79e3, build_duration_seconds:13923]

[automation] update elastic stack version for testing 8.2.0-fdfc79e3

---

testing/environments/snapshot.yml

[start_time:Thu, 7 Apr 2022 00:14:34 GMT, release_branch:master, prefix:, end_time:Thu, 7 Apr 2022 04:42:19 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-5bb6f468, build_duration_seconds:16065]

[automation] update elastic stack version for testing 8.3.0-5bb6f468

---

testing/environments/snapshot.yml

[start_time:Thu, 7 Apr 2022 00:14:27 GMT, release_branch:8.2, prefix:, end_time:Thu, 7 Apr 2022 04:19:11 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-c56d8262, build_duration_seconds:14684]

[automation] update elastic stack version for testing 8.2.0-c56d8262

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Wed, 6 Apr 2022 05:13:42 GMT, release_branch:7.17, prefix:, end_time:Wed, 6 Apr 2022 10:15:41 GMT, manifest_version:2.0.0, version:7.17.3-SNAPSHOT, branch:7.17, build_id:7.17.3-0bbada2a, build_duration_seconds:18119]

[automation] update elastic stack version for testing 7.17.3-0bbada2a

---

metricbeat/docs/modules/oracle.asciidoc
x-pack/metricbeat/metricbeat.reference.yml
x-pack/metricbeat/module/oracle/_meta/config.yml
x-pack/metricbeat/modules.d/oracle.yml.disabled

Example connection string doesn't work with ":" as separator.
Proper example can safe time for those who are not familiar with Oracle

Docs: Adjust connection string

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Wed, 6 Apr 2022 17:14:24 GMT, release_branch:8.1, prefix:, end_time:Wed, 6 Apr 2022 23:18:37 GMT, manifest_version:2.0.0, version:8.1.3-SNAPSHOT, branch:8.1, build_id:8.1.3-6f211282, build_duration_seconds:21853]

[automation] update elastic stack version for testing 8.1.3-6f211282

---

CHANGELOG.asciidoc

This PR adds an entry about a known issue fixed in 8.2: https://github.com/elastic/beats/pull/31048

Add known issue entry to changelog about Beats not loading data streams correctly in 8.1

---

CHANGELOG.asciidoc

This PR adds an entry about a known issue fixed in 8.2: https://github.com/elastic/beats/pull/31048

Add known issue entry to changelog about Beats not loading data streams correctly in 8.0

---

x-pack/elastic-agent/CHANGELOG.next.asciidoc
x-pack/elastic-agent/pkg/agent/application/upgrade/step_download.go
x-pack/elastic-agent/pkg/agent/operation/common_test.go
x-pack/elastic-agent/pkg/agent/operation/operation_verify.go
x-pack/elastic-agent/pkg/artifact/download/composed/verifier.go
x-pack/elastic-agent/pkg/artifact/download/composed/verifier_test.go
x-pack/elastic-agent/pkg/artifact/download/fs/verifier.go
x-pack/elastic-agent/pkg/artifact/download/fs/verifier_test.go
x-pack/elastic-agent/pkg/artifact/download/http/elastic_test.go
x-pack/elastic-agent/pkg/artifact/download/http/verifier.go
x-pack/elastic-agent/pkg/artifact/download/verifier.go

Backport of https://github.com/elastic/elastic-agent/pull/255 to 8.1.x release
- Closes https://github.com/elastic/elastic-agent/issues/275

Backport elastic-agent/pull/255

---

testing/environments/snapshot.yml

[start_time:Thu, 7 Apr 2022 12:14:18 GMT, release_branch:master, prefix:, end_time:Thu, 7 Apr 2022 16:41:59 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-76e0128f, build_duration_seconds:16061]

[automation] update elastic stack version for testing 8.3.0-76e0128f

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Thu, 7 Apr 2022 05:13:51 GMT, release_branch:7.17, prefix:, end_time:Thu, 7 Apr 2022 09:37:56 GMT, manifest_version:2.0.0, version:7.17.3-SNAPSHOT, branch:7.17, build_id:7.17.3-2d046908, build_duration_seconds:15845]

[automation] update elastic stack version for testing 7.17.3-2d046908

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Thu, 7 Apr 2022 17:14:25 GMT, release_branch:8.1, prefix:, end_time:Thu, 7 Apr 2022 22:02:39 GMT, manifest_version:2.0.0, version:8.1.3-SNAPSHOT, branch:8.1, build_id:8.1.3-25093d2a, build_duration_seconds:17294]

[automation] update elastic stack version for testing 8.1.3-25093d2a

---

testing/environments/snapshot.yml

[start_time:Mon, 11 Apr 2022 00:14:24 GMT, release_branch:8.2, prefix:, end_time:Mon, 11 Apr 2022 04:46:29 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-bcbc1a13, build_duration_seconds:16325]

[automation] update elastic stack version for testing 8.2.0-bcbc1a13

---

testing/environments/snapshot.yml

[start_time:Mon, 11 Apr 2022 00:14:22 GMT, release_branch:master, prefix:, end_time:Mon, 11 Apr 2022 04:44:10 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-8d19ff01, build_duration_seconds:16188]

[automation] update elastic stack version for testing 8.3.0-8d19ff01

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Sun, 10 Apr 2022 05:13:28 GMT, release_branch:7.17, prefix:, end_time:Sun, 10 Apr 2022 09:48:25 GMT, manifest_version:2.0.0, version:7.17.3-SNAPSHOT, branch:7.17, build_id:7.17.3-4c0e3956, build_duration_seconds:16497]

[automation] update elastic stack version for testing 7.17.3-4c0e3956

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Sun, 10 Apr 2022 05:14:33 GMT, release_branch:8.1, prefix:, end_time:Sun, 10 Apr 2022 10:14:05 GMT, manifest_version:2.0.0, version:8.1.3-SNAPSHOT, branch:8.1, build_id:8.1.3-91a16370, build_duration_seconds:17972]

[automation] update elastic stack version for testing 8.1.3-91a16370

---

filebeat/docs/inputs/input-filestream-reader-options.asciidoc

Fixes a documentation example
It fixes a documentation example
~~## Logs~~

doc: fix multiline examples in documentation

---

Jenkinsfile

Who can run in the CI is done implicitly in the `gitcheckout` step therefore, the cancelPreviousBuild should happen afterwards.
Avoid killing valid builds in the CI if the comment is not coming from the right set of users
Otherwise

ci: cancel after gitCheckout to avoid DoS

---

CHANGELOG.next.asciidoc
filebeat/input/filestream/internal/input-logfile/store.go

When new filestream inputs are created, we try to migrate registry
entries from inputs that did not have an ID set to their newly set
ID. Using a normal mutex lock can create a situation where the
registry entry is locked and the input will never finish being
created.
This PR fixes this by using a TryLock and just skipping entries that
are already locked.
It fixes filestream inputs being stuck while being created.
- Closes …

filestream: use try lock instead of lock when migrating identifiers

---

testing/environments/snapshot.yml

[start_time:Mon, 11 Apr 2022 12:19:48 GMT, release_branch:master, prefix:, end_time:Mon, 11 Apr 2022 17:10:40 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-2c8f9574, build_duration_seconds:17452]

[automation] update elastic stack version for testing 8.3.0-2c8f9574

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Mon, 11 Apr 2022 17:16:15 GMT, release_branch:8.1, prefix:, end_time:Mon, 11 Apr 2022 22:18:25 GMT, manifest_version:2.0.0, version:8.1.3-SNAPSHOT, branch:8.1, build_id:8.1.3-9689383f, build_duration_seconds:18130]

[automation] update elastic stack version for testing 8.1.3-9689383f

---

libbeat/docs/upgrading.asciidoc

Goes hand in hand with https://github.com/elastic/kibana/pull/129312 . 
Currently, when upgrading the stack, users who have a settings saved object will not see new heartbeat data in typical situations due to their index pattern being stuck on `heartbeat-7*`.

[heartbeat][docs] Add note about ensuring correct index settings for uptime

---

libbeat/common/transport/proxy.go
libbeat/esleg/eslegclient/connection.go
libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc
libbeat/outputs/elasticsearch/elasticsearch.go

Fixes the documentation regarding Elasticsearch output `proxy_url`
configuration format.
Debug logs are added with the breakdown of `proxy_url`.
Our documentation did not mach the way `proxy_url` is parsed for Elasticsearch output.
Add the `proxy_url` setting to any output that supports it, start a Beat with log debug, look for the log message breaking down the proxy URL that look like this:
```
{"log.level":"debug","@timestamp":"2022-04-04T18:05:42.644+0200","log.logger":"elasticsearch","log.origin":{"file.name":"elasticsearch/elasticsearch.go","file.line":68},"message":"breaking down proxy URL. Scheme: 'https', host[:port]: 'my-proxy.proxy:8888', path: '/proxy/path'","service.name":"filebeat","ecs.version":"1.6.0"} …
```

libbeat: log debug for `proxy_url` and fixed docs

---

testing/environments/snapshot.yml

[start_time:Tue, 12 Apr 2022 13:46:39 GMT, release_branch:8.2, prefix:, end_time:Tue, 12 Apr 2022 18:03:38 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-a99722cc, build_duration_seconds:15419]

[automation] update elastic stack version for testing 8.2.0-a99722cc

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Tue, 12 Apr 2022 05:14:19 GMT, release_branch:7.17, prefix:, end_time:Tue, 12 Apr 2022 09:40:43 GMT, manifest_version:2.0.0, version:7.17.3-SNAPSHOT, branch:7.17, build_id:7.17.3-b688e1c0, build_duration_seconds:15984]

[automation] update elastic stack version for testing 7.17.3-b688e1c0

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Tue, 12 Apr 2022 17:15:08 GMT, release_branch:8.1, prefix:, end_time:Tue, 12 Apr 2022 22:06:07 GMT, manifest_version:2.0.0, version:8.1.3-SNAPSHOT, branch:8.1, build_id:8.1.3-f8a17b61, build_duration_seconds:17459]

[automation] update elastic stack version for testing 8.1.3-f8a17b61

---

libbeat/common/transport/tlscommon/types.go

A quick cleanup to `tlsClientAuth.Unpack`.
Fixes https://github.com/elastic/beats/issues/12602.

Simplify TLS config deserialization

---

filebeat/input/filestream/fswatch.go

Remove the info log, because this were generating unnecessary logs.
That generate a big number of log who can distract of the real problem.
check in the watch logs there is not showing the "Start Next Scan" log
- Closes #30394
Scenario: Your Watch get a Event 
When the Watcher have new Event
Then the Watcher will not create a log with "Start Next Scan" in every event

removing info log

---

CHANGELOG.next.asciidoc
x-pack/winlogbeat/module/routing/ingest/routing.yml

x-pack/winlogbeat/module/routing/ingest: fix typo for channel name

---

testing/environments/snapshot.yml

[start_time:Thu, 14 Apr 2022 00:15:10 GMT, release_branch:8.2, prefix:, end_time:Thu, 14 Apr 2022 04:33:43 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-39d3fe7f, build_duration_seconds:15513]

[automation] update elastic stack version for testing 8.2.0-39d3fe7f

---

testing/environments/snapshot.yml

[start_time:Thu, 14 Apr 2022 00:14:21 GMT, release_branch:master, prefix:, end_time:Thu, 14 Apr 2022 04:44:55 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-4be61f32, build_duration_seconds:16234]

[automation] update elastic stack version for testing 8.3.0-4be61f32

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Wed, 13 Apr 2022 05:18:04 GMT, release_branch:7.17, prefix:, end_time:Wed, 13 Apr 2022 09:40:55 GMT, manifest_version:2.0.0, version:7.17.3-SNAPSHOT, branch:7.17, build_id:7.17.3-d599ee07, build_duration_seconds:15771]

[automation] update elastic stack version for testing 7.17.3-d599ee07

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Wed, 13 Apr 2022 17:14:22 GMT, release_branch:8.1, prefix:, end_time:Wed, 13 Apr 2022 22:07:19 GMT, manifest_version:2.0.0, version:8.1.3-SNAPSHOT, branch:8.1, build_id:8.1.3-bb164e02, build_duration_seconds:17577]

[automation] update elastic stack version for testing 8.1.3-bb164e02

---

metricbeat/module/kibana/_meta/README.md

Provides a basic overview document for the kibana metricbeat module
So new developers can have a basic understanding of what the module does and how it works.
Stretch:
- ~~Of the documents and fields that we store, how many are queried by the Kibana app? How many are never queried?~~
- ~~Of the documents and fields queried, which are used for which graphs and charts and tables etc in the UI?~~
N/A
- Closes https://github.com/elastic/kibana/issues/127807
N/A
N/A
N/A

[Stack Monitoring] Readme for kibana module

---

testing/environments/snapshot.yml

[start_time:Fri, 15 Apr 2022 00:14:33 GMT, release_branch:master, prefix:, end_time:Fri, 15 Apr 2022 04:50:37 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-55ba6f37, build_duration_seconds:16564]

[automation] update elastic stack version for testing 8.3.0-55ba6f37

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Thu, 14 Apr 2022 05:13:25 GMT, release_branch:7.17, prefix:, end_time:Thu, 14 Apr 2022 09:41:47 GMT, manifest_version:2.0.0, version:7.17.3-SNAPSHOT, branch:7.17, build_id:7.17.3-a0d290fb, build_duration_seconds:16102]

[automation] update elastic stack version for testing 7.17.3-a0d290fb

---

testing/environments/snapshot.yml

[start_time:Fri, 15 Apr 2022 00:14:25 GMT, release_branch:8.2, prefix:, end_time:Fri, 15 Apr 2022 04:41:47 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-edf55ea1, build_duration_seconds:16042]

[automation] update elastic stack version for testing 8.2.0-edf55ea1

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Thu, 14 Apr 2022 17:14:17 GMT, release_branch:8.1, prefix:, end_time:Thu, 14 Apr 2022 22:27:58 GMT, manifest_version:2.0.0, version:8.1.3-SNAPSHOT, branch:8.1, build_id:8.1.3-5c80e943, build_duration_seconds:18821]

[automation] update elastic stack version for testing 8.1.3-5c80e943

---

CHANGELOG.next.asciidoc
libbeat/reader/syslog/docs/syslog.asciidoc
libbeat/reader/syslog/parser/common.rl
libbeat/reader/syslog/rfc3164_gen.go
libbeat/reader/syslog/rfc3164_test.go

This change relaxes the RFC3164 timestamp grammar to allow dates with a leading
zero to be parsed as valid syslog timestamps, bringing the parser's behaviour into
line with the parser in filebeat/input/syslog.
There are non-standard syslog generating implementations that we were previously unable to consume. With this change we also gain the possibility of reducing the number of syslog parser implementations that we have.
`go test github.com/elastic/beats/v7/libbeat/reader/syslog`
- Relates #16824
- Relates #31246

libbeat/reader/syslog: relax timestamp parsing to allow leading zero

---

testing/environments/snapshot.yml

[start_time:Sun, 17 Apr 2022 00:14:24 GMT, release_branch:8.2, prefix:, end_time:Sun, 17 Apr 2022 03:54:27 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-c65cb8e3, build_duration_seconds:13203]

[automation] update elastic stack version for testing 8.2.0-c65cb8e3

---

testing/environments/snapshot.yml

[start_time:Mon, 18 Apr 2022 00:16:09 GMT, release_branch:master, prefix:, end_time:Mon, 18 Apr 2022 04:26:43 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-c655cda8, build_duration_seconds:15034]

[automation] update elastic stack version for testing 8.3.0-c655cda8

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Sun, 17 Apr 2022 05:15:36 GMT, release_branch:7.17, prefix:, end_time:Sun, 17 Apr 2022 09:36:49 GMT, manifest_version:2.0.0, version:7.17.3-SNAPSHOT, branch:7.17, build_id:7.17.3-feda78d8, build_duration_seconds:15673]

[automation] update elastic stack version for testing 7.17.3-feda78d8

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Sun, 17 Apr 2022 05:15:42 GMT, release_branch:8.1, prefix:, end_time:Sun, 17 Apr 2022 09:59:44 GMT, manifest_version:2.0.0, version:8.1.3-SNAPSHOT, branch:8.1, build_id:8.1.3-28740185, build_duration_seconds:17042]

[automation] update elastic stack version for testing 8.1.3-28740185

---

testing/environments/snapshot.yml

[start_time:Tue, 19 Apr 2022 00:14:07 GMT, release_branch:8.2, prefix:, end_time:Tue, 19 Apr 2022 04:50:58 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-3a7e2f99, build_duration_seconds:16611]

[automation] update elastic stack version for testing 8.2.0-3a7e2f99

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Mon, 18 Apr 2022 17:13:56 GMT, release_branch:8.1, prefix:, end_time:Mon, 18 Apr 2022 22:15:30 GMT, manifest_version:2.0.0, version:8.1.3-SNAPSHOT, branch:8.1, build_id:8.1.3-2a8b1f31, build_duration_seconds:18094]

[automation] update elastic stack version for testing 8.1.3-2a8b1f31

---

CHANGELOG.next.asciidoc
x-pack/filebeat/filebeat.reference.yml
x-pack/filebeat/input/azureeventhub/config.go
x-pack/filebeat/module/azure/_meta/config.yml
x-pack/filebeat/module/azure/activitylogs/config/azure-eventhub.yml
x-pack/filebeat/module/azure/activitylogs/manifest.yml
x-pack/filebeat/module/azure/auditlogs/config/azure-eventhub.yml
x-pack/filebeat/module/azure/auditlogs/manifest.yml
x-pack/filebeat/module/azure/platformlogs/config/azure-eventhub.yml
x-pack/filebeat/module/azure/platformlogs/manifest.yml
x-pack/filebeat/module/azure/signinlogs/config/azure-eventhub.yml
x-pack/filebeat/module/azure/signinlogs/manifest.yml
x-pack/filebeat/modules.d/azure.yml.disabled

Add a new `storage_account_container` configuration option for Azure logs. 
End users can now customize the storage account container name to support edge cases not covered by the default naming convention.
For example, SA container name for activity logs is built using `filebeat-activitylogs-{{ .eventhub }}`: event hub name allows `_` (underscore) character, but unfortunately the storage account container [does not](https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#container-names).
Run Filebeat with the following command line:
```text
-e
-v
-d
*
--strict.perms=false
--path.home
/Users/zmoog/code/projects/zmoog/beats/x-pack/filebeat
-E
cloud.id=<redacted>
-E
cloud.auth=<redacted>
-E
gc_percent=100
-E
setup.ilm.enabled=false …
```

Azure: add storage_account_container config option

---

dev-tools/mage/crossbuild.go

It updates the golang-crossbuild Docker images used to build beats to Debian 10 for some architectures.
We have dropped support for Debian <9 on the golang crossbuildDocker images for the architectures mips, PPC, and s390x
depends on https://github.com/elastic/golang-crossbuild/pull/175
-

fix: use Debian 10 for mips, ppc, and s390x

---

testing/environments/snapshot.yml

[start_time:Wed, 20 Apr 2022 00:15:12 GMT, release_branch:8.2, prefix:, end_time:Wed, 20 Apr 2022 04:28:47 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-a7e9513d, build_duration_seconds:15215]

[automation] update elastic stack version for testing 8.2.0-a7e9513d

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Tue, 19 Apr 2022 05:13:48 GMT, release_branch:7.17, prefix:, end_time:Tue, 19 Apr 2022 09:34:18 GMT, manifest_version:2.0.0, version:7.17.3-SNAPSHOT, branch:7.17, build_id:7.17.3-b148b9ca, build_duration_seconds:15630]

[automation] update elastic stack version for testing 7.17.3-b148b9ca

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Tue, 19 Apr 2022 05:14:50 GMT, release_branch:8.1, prefix:, end_time:Tue, 19 Apr 2022 10:13:34 GMT, manifest_version:2.0.0, version:8.1.3-SNAPSHOT, branch:8.1, build_id:8.1.3-0c4e7b42, build_duration_seconds:17924]

[automation] update elastic stack version for testing 8.1.3-0c4e7b42

---

CHANGELOG.next.asciidoc
metricbeat/module/kubernetes/event/event.go

This PR adds ECS orchestrator fields for k8s events. This is not happening at the moment because events are being collected through "watchers" and the metadata generators are not applicable due to the nature of these objects. However we can directly add orchestrator metadata about the cluster.
In order to be able to filter out events per cluster on Dashboards.
Closes https://github.com/elastic/integrations/issues/3114
Sample ES event:
```json
{
"@timestamp": "2022-04-19T08:40:34.347Z",
"@metadata": {
"beat": "metricbeat",
"type": "_doc",
"version": "8.3.0"
},
"ecs": {
"version": "8.0.0"
},
"host": {
"name": "kind-control-plane"
},
"agent": {
"type": "metricbeat",
"version": "8.3.0",
"ephemeral_id": "118c830a-fc6a-46f2-b99a-b7cd29d53350",
"id": "b210221a-9944-4f3d-8920-6fa617f66a24", …
```

Add orchestrator cluster ECS fields in k8s events

---

testing/environments/snapshot.yml

[start_time:Wed, 20 Apr 2022 12:14:52 GMT, release_branch:8.2, prefix:, end_time:Wed, 20 Apr 2022 17:25:38 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-000e1c18, build_duration_seconds:18646]

[automation] update elastic stack version for testing 8.2.0-000e1c18

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Wed, 20 Apr 2022 05:14:24 GMT, release_branch:7.17, prefix:, end_time:Wed, 20 Apr 2022 09:46:03 GMT, manifest_version:2.0.0, version:7.17.3-SNAPSHOT, branch:7.17, build_id:7.17.3-e9aee937, build_duration_seconds:16299]

[automation] update elastic stack version for testing 7.17.3-e9aee937

---

testing/environments/snapshot.yml

[start_time:Fri, 22 Apr 2022 00:17:53 GMT, release_branch:8.2, prefix:, end_time:Fri, 22 Apr 2022 04:06:59 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-c47183cf, build_duration_seconds:13746]

[automation] update elastic stack version for testing 8.2.0-c47183cf

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Thu, 21 Apr 2022 13:49:29 GMT, release_branch:7.17, prefix:, end_time:Thu, 21 Apr 2022 18:20:44 GMT, manifest_version:2.0.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-51efa5cc, build_duration_seconds:16275]

[automation] update elastic stack version for testing 7.17.4-51efa5cc

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Thu, 21 Apr 2022 17:14:13 GMT, release_branch:8.1, prefix:, end_time:Thu, 21 Apr 2022 22:02:49 GMT, manifest_version:2.0.0, version:8.1.4-SNAPSHOT, branch:8.1, build_id:8.1.4-4911e5d4, build_duration_seconds:17316]

[automation] update elastic stack version for testing 8.1.4-4911e5d4

---

testing/environments/snapshot.yml

[start_time:Mon, 25 Apr 2022 00:16:18 GMT, release_branch:8.2, prefix:, end_time:Mon, 25 Apr 2022 04:48:40 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-14a8abdc, build_duration_seconds:16342]

[automation] update elastic stack version for testing 8.2.0-14a8abdc

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Sat, 23 Apr 2022 05:15:49 GMT, release_branch:7.17, prefix:, end_time:Sat, 23 Apr 2022 09:43:50 GMT, manifest_version:2.0.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-4d7a6e74, build_duration_seconds:16081]

[automation] update elastic stack version for testing 7.17.4-4d7a6e74

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Sun, 24 Apr 2022 05:16:18 GMT, release_branch:8.1, prefix:, end_time:Sun, 24 Apr 2022 10:04:19 GMT, manifest_version:2.0.0, version:8.1.4-SNAPSHOT, branch:8.1, build_id:8.1.4-bc369beb, build_duration_seconds:17281]

[automation] update elastic stack version for testing 8.1.4-bc369beb

---

CHANGELOG.next.asciidoc
dev-tools/packaging/templates/docker/docker-entrypoint.elastic-agent.tmpl
heartbeat/security/security.go
libbeat/paths/paths.go

Since it's a bugfix, I'm including `elastic-agent` changes to be backported to `8.2` and I will create a separate PR on `elastic-agent` repo for `8.3`.
This PR:
- Includes group write permission in runtime directories, 
- adapts `umask` on docker containers,
- restricts heartbeat `setuid` to containerized instances.
This PR works in tandem with elastic/elastic-agent#202.
Heartbeat comes with `setuid` functionality to be able to run `npm` as a non-root user during synthetics checks inside an `elastic-agent` container. Without it, `npm` would complain when executed as root.
When `elastic-agent` is executed as root, all beats (filebeat, metricbeat, ...) run as `root` and `heartbeat` will run as user specified on `BEAT_SETUID_AS` env variable, `elastic-agent` by default. This user needs …

[Heartbeat] Enable Heartbeat to run when elastic-agent container is executed as root

---

testing/environments/snapshot.yml

[start_time:Tue, 26 Apr 2022 00:14:18 GMT, release_branch:8.2, prefix:, end_time:Tue, 26 Apr 2022 04:06:52 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-63f66f47, build_duration_seconds:13954]

[automation] update elastic stack version for testing 8.2.0-63f66f47

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Mon, 25 Apr 2022 18:54:34 GMT, release_branch:7.17, prefix:, end_time:Mon, 25 Apr 2022 23:36:22 GMT, manifest_version:2.0.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-073e030e, build_duration_seconds:16908]

[automation] update elastic stack version for testing 7.17.4-073e030e

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Mon, 25 Apr 2022 17:13:58 GMT, release_branch:8.1, prefix:, end_time:Mon, 25 Apr 2022 23:03:47 GMT, manifest_version:2.0.0, version:8.1.4-SNAPSHOT, branch:8.1, build_id:8.1.4-96de35ab, build_duration_seconds:20989]

[automation] update elastic stack version for testing 8.1.4-96de35ab

---

.github/CODEOWNERS

This should prevent the data plane team from being added as a reviewer
every time a changelog entry is added regardless of if they own the code
in the rest of the review.

List the CHANGELOG files without code owners.

---

libbeat/docker-compose.yml
metricbeat/docker-compose.yml
metricbeat/module/logstash/docker-compose.yml
testing/environments/latest.yml
testing/environments/snapshot.yml
x-pack/libbeat/docker-compose.yml

[start_time:Tue, 26 Apr 2022 00:25:14 GMT, release_branch:master, prefix:, end_time:Tue, 26 Apr 2022 04:35:41 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-ed7759bd, build_duration_seconds:15027]

[automation] update elastic stack version for testing 8.3.0-ed7759bd

---

testing/environments/snapshot.yml

[start_time:Tue, 26 Apr 2022 12:14:51 GMT, release_branch:8.2, prefix:, end_time:Tue, 26 Apr 2022 16:38:24 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-bdd1c93d, build_duration_seconds:15813]

[automation] update elastic stack version for testing 8.2.0-bdd1c93d

---

testing/environments/snapshot.yml

[start_time:Tue, 26 Apr 2022 12:13:43 GMT, release_branch:master, prefix:, end_time:Tue, 26 Apr 2022 16:20:43 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-6b041601, build_duration_seconds:14820]

[automation] update elastic stack version for testing 8.3.0-6b041601

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Tue, 26 Apr 2022 05:13:44 GMT, release_branch:7.17, prefix:, end_time:Tue, 26 Apr 2022 09:41:06 GMT, manifest_version:2.0.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-a30db1f9, build_duration_seconds:16042]

[automation] update elastic stack version for testing 7.17.4-a30db1f9

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Tue, 26 Apr 2022 05:14:12 GMT, release_branch:8.1, prefix:, end_time:Tue, 26 Apr 2022 10:33:45 GMT, manifest_version:2.0.0, version:8.1.4-SNAPSHOT, branch:8.1, build_id:8.1.4-483e60fd, build_duration_seconds:19173]

[automation] update elastic stack version for testing 8.1.4-483e60fd

---

README.md

This PR updates the Go Report badge since it does not appear correctly now.
It would be nice to show the current status.
N/A
- 
N/A

fix Go Report badge

---

.golangci.yml
dev-tools/templates/.golangci.yml

This PR adjusts the linter configuration, so we get less noise. The two impacted linters are `godox` and `forbidigo`.
`godox` is used to track down TODO, FIXME, etc. comments. Instead developers should open tickets in their issue trackers. Beats code is full of such comments without actual issues to back them up. I think the comments are valuable when we are debugging. But let's be honest, we are not going to fix all of the problems. Also, we cannot really open a valuable follow-up issue for such comments because we lack the required context.
`forbidigo` forbids us to use `fmt.Print*`. In the product code it makes sense. However, in `mage` we constantly print to stdout to give feedback to the developer. In mage targets and mage files, using `fmt.Print*` is the standard and should be …

Linters: remove `godox` and add exclude rule for `forbidigo` in mage files

---

heartbeat/hbtest/hbtestutil.go
heartbeat/look/look.go
heartbeat/look/look_test.go
heartbeat/monitors/active/http/http_test.go
heartbeat/monitors/active/tcp/socks5_test.go
heartbeat/monitors/active/tcp/tcp_test.go
heartbeat/monitors/logger/logger.go
heartbeat/monitors/logger/logger_test.go
heartbeat/monitors/mocks_test.go
heartbeat/monitors/wrappers/wrappers.go
heartbeat/monitors/wrappers/wrappers_test.go
x-pack/heartbeat/monitors/browser/synthexec/enrich.go
x-pack/heartbeat/monitors/browser/synthexec/enrich_test.go
x-pack/heartbeat/monitors/browser/synthexec/synthtypes.go

> ⚠️ Please see the related linter issue here if you're curious about the linting comments: https://github.com/elastic/beats/issues/31407
This PR is an alternative implementation to https://github.com/elastic/beats/issues/30433: **it adds structured logging for us to collect data about how many steps browser monitors contain and how long monitors in general took to run**.
If merged, it supersedes https://github.com/elastic/beats/pull/31398.
It's necessary so that we have relevant stats in the telemetry cluster to analyse the service's behaviour.
Not sure on what tests to add here since this just updates logging.
Please confirm whether you'd like to include this PR or https://github.com/elastic/beats/pull/31398.
This PR has everything we need to solve …

Add heartbeat telemetry logs (step count and duration)

---

CHANGELOG.next.asciidoc
x-pack/filebeat/input/azureeventhub/config.go
x-pack/filebeat/input/azureeventhub/config_test.go

Sanitize the SA container name when users configure the `azureeventhub` input using an Event Hub name with underscores (_).
When a user specifies an event hub name in the input settings, the configuration uses it to compose the storage account (SA) container name. For example, with an event hub name of `<EVENT-HUB-NAME>`, the used SA container name becomes `filebeat-<DATA-STREAM>-<EVENT-HUB-NAME>` (e.g., `filebeat-auditlogs-eventhub00`).
The event hub allows names with underscores (_) characters, but unfortunately, the SA container does not permit them.
So instead of throwing an error to the user, we [decided](https://github.com/elastic/integrations/issues/3006#issuecomment-1102753497) to replace the (_) characters with hyphens (-).
- Related elastic/integrations#3006

[azureeventhub] SA container: replace underscores(_) with hyphens(-)

---

CHANGELOG.next.asciidoc
libbeat/processors/syslog/syslog_test.go
libbeat/reader/syslog/message.go
libbeat/reader/syslog/message_test.go
libbeat/reader/syslog/rfc3164_test.go
libbeat/reader/syslog/rfc5424_test.go
libbeat/reader/syslog/syslog_test.go

The `log.syslog.version` field in ECS expects the value to be a keyword (string). This PR changes how we store the value of this field, from an int to a string.
System tests fail due to type mismatch. This PR aligns the type with what ECS expects.
```
go test github.com/elastic/beats/v7/libbeat/reader/syslog
go test github.com/elastic/beats/v7/libbeat/processors/syslog
```
Error raised by system test:
```
panw/panos udp:
[0] parsing field value failed: field "log.syslog.version"'s Go type, float64, does not match the expected field type: keyword (field value: 1)
```

[libbeat] Store syslog version as string 

---

libbeat/common/file/helper_aix.go
libbeat/common/file/helper_other.go
libbeat/common/file/helper_windows.go
x-pack/elastic-agent/pkg/agent/storage/disk_store.go
x-pack/elastic-agent/pkg/agent/storage/replace_store.go

Improve sync handling and errors
Improve sync handling and errors
Related to https://github.com/elastic/elastic-agent/issues/98
Will update https://github.com/elastic/elastic-agent/blob/main/internal/pkg/agent/storage/replace_store.go#L44 by adding `SyncParent` once it's available in the repo.
- Relates https://github.com/elastic/elastic-agent/pull/312 https://github.com/elastic/elastic-agent-libs/pull/36  https://github.com/elastic/elastic-agent/issues/98

[7.17](backport #312) Improve sync handling and errors

---

Jenkinsfile

Partially backport https://github.com/elastic/beats/pull/30907/commits/4820498241c82690837d53900dbc49e86b3f59d0 to help with the merge conflicts
Allow stage level customisation to configure GCP

[8.2] ci: configure GCP at the stage level

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Thu, 28 Apr 2022 10:32:38 GMT, release_branch:7.17, prefix:, end_time:Thu, 28 Apr 2022 15:33:56 GMT, manifest_version:2.0.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-40d3b33d, build_duration_seconds:18078]

[automation] update elastic stack version for testing 7.17.4-40d3b33d

---

testing/environments/snapshot.yml

[start_time:Thu, 28 Apr 2022 12:14:16 GMT, release_branch:8.2, prefix:, end_time:Thu, 28 Apr 2022 16:53:35 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-2c25c9de, build_duration_seconds:16759]

[automation] update elastic stack version for testing 8.2.0-2c25c9de

---

testing/environments/snapshot.yml

[start_time:Fri, 29 Apr 2022 00:14:22 GMT, release_branch:master, prefix:, end_time:Fri, 29 Apr 2022 04:24:25 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-194e3512, build_duration_seconds:15003]

[automation] update elastic stack version for testing 8.3.0-194e3512

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Sat, 30 Apr 2022 05:17:17 GMT, release_branch:7.17, prefix:, end_time:Sat, 30 Apr 2022 09:48:12 GMT, manifest_version:2.0.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-ed667030, build_duration_seconds:16255]

[automation] update elastic stack version for testing 7.17.4-ed667030

---

testing/environments/snapshot.yml

[start_time:Mon, 2 May 2022 00:16:36 GMT, release_branch:8.2, prefix:, end_time:Mon, 2 May 2022 04:26:56 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-e7ad9ef0, build_duration_seconds:15020]

[automation] update elastic stack version for testing 8.2.0-e7ad9ef0

---

testing/environments/snapshot.yml

[start_time:Mon, 2 May 2022 00:16:33 GMT, release_branch:master, prefix:, end_time:Mon, 2 May 2022 04:42:36 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-eb27d7ab, build_duration_seconds:15963]

[automation] update elastic stack version for testing 8.3.0-eb27d7ab

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Sun, 1 May 2022 17:14:24 GMT, release_branch:8.1, prefix:, end_time:Sun, 1 May 2022 21:57:49 GMT, manifest_version:2.0.0, version:8.1.4-SNAPSHOT, branch:8.1, build_id:8.1.4-76569f3d, build_duration_seconds:17005]

[automation] update elastic stack version for testing 8.1.4-76569f3d

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Mon, 2 May 2022 05:13:36 GMT, release_branch:7.17, prefix:, end_time:Mon, 2 May 2022 20:26:46 GMT, manifest_version:2.0.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-9ca33e9a, build_duration_seconds:54790]

[automation] update elastic stack version for testing 7.17.4-9ca33e9a

---

testing/environments/snapshot.yml

[start_time:Mon, 2 May 2022 21:05:06 GMT, release_branch:master, prefix:, end_time:Tue, 3 May 2022 01:18:58 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-0b6ea9f2, build_duration_seconds:15232]

[automation] update elastic stack version for testing 8.3.0-0b6ea9f2

---

testing/environments/snapshot.yml

[start_time:Tue, 3 May 2022 00:14:07 GMT, release_branch:8.2, prefix:, end_time:Tue, 3 May 2022 04:22:51 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-56396fd0, build_duration_seconds:14924]

[automation] update elastic stack version for testing 8.2.0-56396fd0

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Mon, 2 May 2022 17:14:27 GMT, release_branch:8.1, prefix:, end_time:Mon, 2 May 2022 22:11:28 GMT, manifest_version:2.0.0, version:8.1.4-SNAPSHOT, branch:8.1, build_id:8.1.4-1cdc80b6, build_duration_seconds:17821]

[automation] update elastic stack version for testing 8.1.4-1cdc80b6

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Tue, 3 May 2022 05:13:25 GMT, release_branch:7.17, prefix:, end_time:Tue, 3 May 2022 09:36:33 GMT, manifest_version:2.0.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-cd92752d, build_duration_seconds:15788]

[automation] update elastic stack version for testing 7.17.4-cd92752d

---

testing/environments/snapshot.yml

[start_time:Wed, 4 May 2022 00:14:21 GMT, release_branch:master, prefix:, end_time:Wed, 4 May 2022 04:11:39 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-7f585873, build_duration_seconds:14238]

[automation] update elastic stack version for testing 8.3.0-7f585873

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Tue, 3 May 2022 17:14:34 GMT, release_branch:8.1, prefix:, end_time:Tue, 3 May 2022 21:52:16 GMT, manifest_version:2.0.0, version:8.1.4-SNAPSHOT, branch:8.1, build_id:8.1.4-86899ed7, build_duration_seconds:16662]

[automation] update elastic stack version for testing 8.1.4-86899ed7

---

CHANGELOG.next.asciidoc
NOTICE.txt
go.mod
go.sum

Updated the go-libaudit library version to v2.3.0. This refreshes the syscall
names for Linux and adds ECS categorizations for more audit anomaly events.
https://github.com/elastic/go-libaudit/releases/tag/v2.3.0
This refreshes the lookup tables to handle new syscalls in Linux.

[Auditbeat] Update to go-libaudit v2.3.0

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Wed, 4 May 2022 05:13:32 GMT, release_branch:7.17, prefix:, end_time:Wed, 4 May 2022 09:43:47 GMT, manifest_version:2.0.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-c570579f, build_duration_seconds:16215]

[automation] update elastic stack version for testing 7.17.4-c570579f

---

testing/environments/snapshot.yml

[start_time:Thu, 5 May 2022 00:15:22 GMT, release_branch:master, prefix:, end_time:Thu, 5 May 2022 04:24:20 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-a1c5cfff, build_duration_seconds:14938]

[automation] update elastic stack version for testing 8.3.0-a1c5cfff

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Thu, 5 May 2022 05:15:38 GMT, release_branch:7.17, prefix:, end_time:Thu, 5 May 2022 09:50:15 GMT, manifest_version:2.0.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-2fe5353f, build_duration_seconds:16477]

[automation] update elastic stack version for testing 7.17.4-2fe5353f

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Thu, 5 May 2022 05:15:40 GMT, release_branch:8.1, prefix:, end_time:Thu, 5 May 2022 10:14:39 GMT, manifest_version:2.0.0, version:8.1.4-SNAPSHOT, branch:8.1, build_id:8.1.4-6c818705, build_duration_seconds:17939]

[automation] update elastic stack version for testing 8.1.4-6c818705

---

testing/environments/snapshot.yml

[start_time:Fri, 6 May 2022 00:14:54 GMT, release_branch:master, prefix:, end_time:Fri, 6 May 2022 04:20:36 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-6ba9f710, build_duration_seconds:14742]

[automation] update elastic stack version for testing 8.3.0-6ba9f710

---

CHANGELOG.next.asciidoc
heartbeat/autodiscover/builder/hints/monitors.go
heartbeat/autodiscover/builder/hints/monitors_test.go
heartbeat/monitors/active/icmp/stdloop.go
heartbeat/monitors/factory.go
heartbeat/monitors/logger/logger.go
heartbeat/monitors/monitor.go
heartbeat/scheduler/schedjob.go

We mostly use the global logp.{warn,err,etc.} functions throughout heartbeat, which is deprecated.
Some parts of heartbeat incorrectly attempt to use 'logger =
logp.NewLogger' at the top of a file, which just creates a noop logger.
The correct way to do things, apparently, is to create a single logger
with the correct options at the root of your program and pass it
everywhere. IMHO this adds a ton of unncessary boilerplate, and is a
major painful change.
This PR fixes the short term issue of incorrectly using a noop logger by
using logp.L() to grab a non-deprecated global logger.
Use the following monitor config in `monitors.d` that is missing a `hosts` config. Without this patch it will silently fail to log any errors (they will appear in the Uptime UI though). With it you will see: `job …

[Heartbeat] Fix unintentional use of no-op logger

---

CHANGELOG.next.asciidoc
auditbeat/module/auditd/show_linux.go

Now that go-libaudit support [backlog_wait_time_actual](https://github.com/torvalds/linux/commit/b43870c74f3fdf0cd06bf5f1b7a5ed70a2cd4ed2) this field
can be output from the show-status command on Linux 5.9+ kernels.
There were no tests for this code so I did a quick manual smoke test
on 5.10.
Relates #31519
To make it easier to reliably track degraded performance to backlog waiting.
- Relates #31519

[auditbeat] Add backlog_wait_time_actual to show-status output

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Sat, 7 May 2022 05:15:45 GMT, release_branch:7.17, prefix:, end_time:Sat, 7 May 2022 09:42:44 GMT, manifest_version:2.1.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-1ffd290e, build_duration_seconds:16019]

[automation] update elastic stack version for testing 7.17.4-1ffd290e

---

CHANGELOG.next.asciidoc
packetbeat/procs/procs.go
packetbeat/procs/procs_linux.go
packetbeat/procs/procs_other.go
packetbeat/procs/procs_windows.go

This changes the behaviour of process name recovery for linux hosts so that `/proc/<pid>/comm` is used unless it cannot be guaranteed to be a complete name.
Also do a little de-linting.
The first argument of a command line is under the control of the invoker and so is more easily spoofed.
- Relates elastic/integrations#2720

packetbeat/procs: be more careful in recovering process names on linux

---

.ci/packaging.groovy

Avoid fail if e2e-testing fails
Unblock the 8.2.1-SNAPSHOT temporarily
https://github.com/elastic/e2e-testing/pull/2501 will fix the issue with the versioning mismatch.

packaging: avoid propagate and wait for the e2e-testing

---

CHANGELOG.next.asciidoc
winlogbeat/eventlog/wineventlog.go

This adds value caching in winlogbeat for event meta data. It is a reduced version of the caching that is done in wineventlog in the Renderer type.
It reduces syscall load.
- Relates https://github.com/elastic/beats/pull/31464#pullrequestreview-957219961

winlogbeat/eventlog: cache winevent.WinMeta values

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Mon, 9 May 2022 05:13:19 GMT, release_branch:7.17, prefix:, end_time:Mon, 9 May 2022 09:41:04 GMT, manifest_version:2.1.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-37e626ca, build_duration_seconds:16065]

[automation] update elastic stack version for testing 7.17.4-37e626ca

---

testing/environments/snapshot.yml

[start_time:Tue, 10 May 2022 00:14:30 GMT, release_branch:8.2, prefix:, end_time:Tue, 10 May 2022 03:56:53 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-d6d75d75, build_duration_seconds:13343]

[automation] update elastic stack version for testing 8.2.1-d6d75d75

---

testing/environments/snapshot.yml

[start_time:Tue, 10 May 2022 00:14:18 GMT, release_branch:master, prefix:, end_time:Tue, 10 May 2022 04:17:54 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-d380914f, build_duration_seconds:14616]

[automation] update elastic stack version for testing 8.3.0-d380914f

---

.github/CODEOWNERS

This avoids having to maintain the correct codeowner for the entire docs
tree, which is assignee that data plane team as reviewers for changes to
code they do not own.
The documentation for inputs and modules is frequently changed along with
their code, so in practice a reasonable owner is assigned the majority of the time.
When changes are made exclusively to these docs without any code change
a reviewer will have to be manually assigned.

List individual beat docs without a CODEOWNER.

---

.ci/packaging.groovy

It passes the name of a profile that will be used to add/retire specific tests from the e2e test suite when it's called from Beats pipeline.
We'd like to remove scenarios that the team consider flaky while they are investigating them, to avoid adding noise to the rest of pull-requests.
I personally don't like to skip a test without further investigation because it's easily forgotten to be re-added. On the other hand, I understand that this PR would improve the reliability of the tests, therefore the team would work more smoothly and with more confidence in the CI system.
Requires https://github.com/elastic/e2e-testing/pull/2482

chore: use a different e2e profile for running them from Beats

---

CHANGELOG.next.asciidoc
x-pack/winlogbeat/module/sysmon/ingest/sysmon.yml

Updates Winlogbeat's sysmon ingest pipeline with changes from the integrations package:
- https://github.com/elastic/integrations/pull/2962 (enhancement)
- https://github.com/elastic/integrations/pull/3283  (bug)
Keeps Beats & integrations in sync.
Note that there's currently no automated test in place for the ingest pipelines in Winlogbeat, but the pipeline is tested in the integrations repo. See https://github.com/elastic/beats/issues/30406
- Closes https://github.com/elastic/beats/issues/31528

[Winlogbeat] Update sysmon pipeline with latest changes from integration

---

filebeat/docs/modules/threatintel.asciidoc
x-pack/filebeat/module/threatintel/_meta/docs.asciidoc
x-pack/filebeat/module/threatintel/_meta/kibana/7/visualization/f13f5650-df5b-11eb-8f2b-753caedf727d.json
x-pack/filebeat/module/threatintel/module.yml

Fixes the `threatintel` module docs and Overview Dashboard to remove references to the now-removed Recorded Future dataset and add a missing link to ThreatQ.
Avoids misleading users.

threatintel: Correct references to Recorded Future and ThreatQ in docs and dashboards

---

testing/environments/snapshot.yml

[start_time:Tue, 10 May 2022 12:14:03 GMT, release_branch:8.2, prefix:, end_time:Tue, 10 May 2022 17:09:44 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-2eb01953, build_duration_seconds:17741]

[automation] update elastic stack version for testing 8.2.1-2eb01953

---

testing/environments/snapshot.yml

[start_time:Tue, 10 May 2022 12:14:28 GMT, release_branch:master, prefix:, end_time:Tue, 10 May 2022 19:41:55 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-53513548, build_duration_seconds:26847]

[automation] update elastic stack version for testing 8.3.0-53513548

---

.ci/packaging.groovy

The file name was missing the `.`
- Caused by #31531
- Backport #31573 is pending because of this

fix: proper file name

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Wed, 11 May 2022 05:13:17 GMT, release_branch:7.17, prefix:, end_time:Wed, 11 May 2022 09:41:40 GMT, manifest_version:2.1.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-6a00b8d7, build_duration_seconds:16103]

[automation] update elastic stack version for testing 7.17.4-6a00b8d7

---

testing/environments/snapshot.yml

[start_time:Wed, 11 May 2022 12:17:18 GMT, release_branch:8.2, prefix:, end_time:Wed, 11 May 2022 16:33:31 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-91d7a53f, build_duration_seconds:15373]

[automation] update elastic stack version for testing 8.2.1-91d7a53f

---

filebeat/docs/howto/howto.asciidoc
filebeat/docs/howto/migrate-to-filestream.asciidoc

This PR adds a new how to guide to help users migrate from log input configurations to filestream.
Help users with existing configuration.

Add How to guide for migrating to filestream input

---

CHANGELOG.next.asciidoc
deploy/kubernetes/metricbeat-kubernetes.yaml
deploy/kubernetes/metricbeat/metricbeat-role.yaml
libbeat/common/kubernetes/informer.go
libbeat/common/kubernetes/types.go
metricbeat/module/kubernetes/_meta/test/docs/01_playground/metricbeat.yaml
metricbeat/module/kubernetes/event/event.go
metricbeat/module/kubernetes/state_container/_meta/test/ksm.v2.0.0.expected
metricbeat/module/kubernetes/state_daemonset/state_daemonset.go
metricbeat/module/kubernetes/state_persistentvolume/_meta/test/ksm.unit.v1.8.0.expected
metricbeat/module/kubernetes/state_persistentvolume/_meta/test/ksm.v1.8.0.expected
metricbeat/module/kubernetes/state_persistentvolume/_meta/test/ksm.v2.0.0.expected
metricbeat/module/kubernetes/state_persistentvolume/state_persistentvolume.go
metricbeat/module/kubernetes/state_persistentvolumeclaim/_meta/test/ksm.unit.v1.8.0.expected
metricbeat/module/kubernetes/state_persistentvolumeclaim/_meta/test/ksm.v1.8.0.expected
metricbeat/module/kubernetes/state_persistentvolumeclaim/_meta/test/ksm.v2.0.0.expected
metricbeat/module/kubernetes/state_persistentvolumeclaim/state_persistentvolumeclaim.go
metricbeat/module/kubernetes/util/kubernetes.go
metricbeat/module/kubernetes/volume/volume.go

Adds metadata for metricsets that were missing. For `volume` we can only add orchestrator related metadata since it's not an actual k8s object.
To better filter objects in dashboards and visualisations.

Add metadata for missing k8s resources/metricsets

---

libbeat/metric/system/process/helpers.go
libbeat/metric/system/process/process.go
libbeat/metric/system/process/process_aix.go
libbeat/metric/system/process/process_darwin.go
libbeat/metric/system/process/process_linux_common.go
libbeat/metric/system/process/process_test.go
libbeat/metric/system/process/process_types.go
libbeat/metric/system/process/process_windows.go

This PR fixes a bug results in the `top_n` filtering options not being applied in `system/process`, as well as refactors a bunch of components to make the new linter happy.
This is an actual bug. 
Pull down and build, make sure the `include_top_n` flags work in metricbeat.

Fix bug in filtering, cleanup

---

x-pack/osquerybeat/cmd/root.go

Populates host.name field in the beats output documents.
Addresses: https://github.com/elastic/security-team/issues/3572
1. Enroll the agent with osquery_manager integration added to the policy
2. Run live query, for example ```select * from osquery_info``` 
3. Verify that the host.name field exists and is populated with value
- Closes https://github.com/elastic/security-team/issues/3572

Osquerybeat: Populate host.name field

---

testing/environments/snapshot.yml

[start_time:Fri, 13 May 2022 00:14:17 GMT, release_branch:8.2, prefix:, end_time:Fri, 13 May 2022 04:35:01 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-05a5ca87, build_duration_seconds:15644]

[automation] update elastic stack version for testing 8.2.1-05a5ca87

---

testing/environments/snapshot.yml

[start_time:Thu, 12 May 2022 12:14:39 GMT, release_branch:master, prefix:, end_time:Thu, 12 May 2022 20:54:06 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-b85385ff, build_duration_seconds:31167]

[automation] update elastic stack version for testing 8.3.0-b85385ff

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Thu, 12 May 2022 05:13:48 GMT, release_branch:7.17, prefix:, end_time:Thu, 12 May 2022 09:49:56 GMT, manifest_version:2.1.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-153c53bf, build_duration_seconds:16568]

[automation] update elastic stack version for testing 7.17.4-153c53bf

---

CHANGELOG.next.asciidoc
x-pack/filebeat/module/cisco/asa/test/sample.log
x-pack/filebeat/module/cisco/asa/test/sample.log-expected.json
x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml

This PR adds parsing for Cisco ASA 434001 and 434003 using the precise style currently used for parsing Cisco ASA 434002.
We need parsing for ASA 434001, 434002, and 434003; right now only 434002 is supported, despite the others being substantially similar dissections.
The PR uses the patterns specified here: https://www.cisco.com/c/en/us/td/docs/security/asa/syslog/b_syslog/syslog-messages-400000-to-450001.html#con_7199521.
For testing the actual messages, these are sample logs:
For 434001:
<13>Apr 26 2022 10:24:37: %ASA-4-434001: SFR card not up and fail-close mode used, dropping TCP packet from outside:54.239.28.85/443 to Inside:10.12.128.89/57388
For 434003:
<13>May 30 2019 09:18:59: %ASA-4-434003: SFR requested to reset TCP connection from outside:54.239.28.85/443 to …

Add parsing for 434001 and 434003

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Sun, 15 May 2022 05:16:19 GMT, release_branch:7.17, prefix:, end_time:Sun, 15 May 2022 09:41:05 GMT, manifest_version:2.1.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-191b5600, build_duration_seconds:15886]

[automation] update elastic stack version for testing 7.17.4-191b5600

---

testing/environments/snapshot.yml

[start_time:Mon, 16 May 2022 00:17:45 GMT, release_branch:8.2, prefix:, end_time:Mon, 16 May 2022 04:48:36 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-3d12787c, build_duration_seconds:16251]

[automation] update elastic stack version for testing 8.2.1-3d12787c

---

testing/environments/snapshot.yml

[start_time:Mon, 16 May 2022 00:17:33 GMT, release_branch:master, prefix:, end_time:Mon, 16 May 2022 04:25:53 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-19aba912, build_duration_seconds:14900]

[automation] update elastic stack version for testing 8.3.0-19aba912

---

CHANGELOG.next.asciidoc
x-pack/filebeat/module/cisco/asa/test/sample.log-expected.json
x-pack/filebeat/module/cisco/ftd/test/sample.log-expected.json
x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml

This prevents "monitored" from being written into event.outcome which
does not allow this value according to ECS.
This brings the generated documents into conformance with ECS.
- Relates elastic/integrations#3344

x-pack/filebeat/module/cisco: remove invalid values from ECS fields

---

libbeat/processors/actions/docs/drop_fields.asciidoc

I've added a description in docs for the regexp functionality from #31424

Add ascii documentation for regexp support in drop_fields processor

---

CHANGELOG.next.asciidoc
libbeat/common/datetime.go
libbeat/common/datetime_test.go
libbeat/common/dtfmt/builder.go
libbeat/common/dtfmt/ctx.go
libbeat/common/dtfmt/doc.go
libbeat/common/dtfmt/dtfmt_test.go
libbeat/common/dtfmt/elems.go
libbeat/common/dtfmt/fields.go
libbeat/common/dtfmt/fmt.go
libbeat/common/dtfmt/prog.go
libbeat/common/dtfmt/util.go
libbeat/outputs/codec/common.go
libbeat/outputs/logstash/logstash_integration_test.go
packetbeat/tests/system/test_0032_dns.py
packetbeat/tests/system/test_0050_icmp.py
packetbeat/tests/system/test_0060_flows.py
packetbeat/tests/system/test_0062_cassandra.py
x-pack/filebeat/module/gcp/audit/test/audit-log-entries.json.log-expected.json
x-pack/filebeat/module/gcp/firewall/test/rare.log-expected.json
x-pack/filebeat/module/gcp/firewall/test/test.log-expected.json
x-pack/filebeat/module/gcp/vpcflow/test/vpc-flow-log-entries.json.log-expected.json
x-pack/filebeat/module/suricata/eve/test/eve-6.0.log-expected.json
x-pack/filebeat/module/suricata/eve/test/eve-alerts.log-expected.json
x-pack/filebeat/module/suricata/eve/test/eve-dns-4.1.4.log-expected.json
x-pack/filebeat/module/suricata/eve/test/eve-metadata.log-expected.json
x-pack/filebeat/module/suricata/eve/test/eve-small.log-expected.json

This PR adds support for nanosecond precision timestamps in Beats. It is the updated version of https://github.com/elastic/beats/pull/15872
When events come faster then milliseconds, ingested events might have the same `@timestamp` field. So there is no way to order them correctly. By making the timestamp more precise we can avoid such problems.
Closes https://github.com/elastic/beats/issues/15871

Add support for nanosecond precision timestamps

---

testing/environments/snapshot.yml

[start_time:Tue, 17 May 2022 00:14:25 GMT, release_branch:8.2, prefix:, end_time:Tue, 17 May 2022 04:25:16 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-736d131e, build_duration_seconds:15051]

[automation] update elastic stack version for testing 8.2.1-736d131e

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Mon, 16 May 2022 05:15:27 GMT, release_branch:7.17, prefix:, end_time:Mon, 16 May 2022 09:47:14 GMT, manifest_version:2.1.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-16fc7c23, build_duration_seconds:16307]

[automation] update elastic stack version for testing 7.17.4-16fc7c23

---

testing/environments/snapshot.yml

[start_time:Mon, 16 May 2022 12:14:04 GMT, release_branch:master, prefix:, end_time:Mon, 16 May 2022 16:39:55 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-4149272f, build_duration_seconds:15951]

[automation] update elastic stack version for testing 8.3.0-4149272f

---

libbeat/docs/communitybeats.asciidoc

Closes https://github.com/elastic/observability-docs/issues/1444
Also replaced "Beats" with "{beats}" because the linter will flag it if we decide to run it against these docs someday.

Make Beat generator deprecation and removal more obvious in the docs

---

CHANGELOG.asciidoc
CHANGELOG.next.asciidoc

Closes https://github.com/elastic/observability-docs/issues/876
@andresrc Let me know if I need to change this someplace else. I am very out of the loop wrt to the current relnotes process.

Fix View Commit links in Beats relnotes

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Tue, 17 May 2022 05:13:44 GMT, release_branch:7.17, prefix:, end_time:Tue, 17 May 2022 09:44:39 GMT, manifest_version:2.1.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-3585da41, build_duration_seconds:16255]

[automation] update elastic stack version for testing 7.17.4-3585da41

---

testing/environments/snapshot.yml

[start_time:Wed, 18 May 2022 00:13:55 GMT, release_branch:master, prefix:, end_time:Wed, 18 May 2022 04:22:31 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-e4aa1f83, build_duration_seconds:14916]

[automation] update elastic stack version for testing 8.3.0-e4aa1f83

---

testing/environments/snapshot.yml

[start_time:Tue, 17 May 2022 12:16:05 GMT, release_branch:8.2, prefix:, end_time:Tue, 17 May 2022 19:10:52 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-8d9ffca9, build_duration_seconds:24887]

[automation] update elastic stack version for testing 8.2.1-8d9ffca9

---

CHANGELOG.next.asciidoc
winlogbeat/checkpoint/checkpoint.go
winlogbeat/checkpoint/checkpoint_test.go

Fixes the logic handling Winlogbeat's checkpoint timeout (`winlogbeat.registry_flush`).
Also took the opportunity to refactor the handling of the timeout timer a little so it's only started when it needs to.
A mistake was causing the registry to be flushed to disk at each update, causing a lot of disk I/O.
- Closes #31666

Fix Winlogbeat registry flush not working

---

testing/environments/snapshot.yml

[start_time:Wed, 18 May 2022 00:14:22 GMT, release_branch:8.2, prefix:, end_time:Wed, 18 May 2022 09:50:13 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-93582d09, build_duration_seconds:34551]

[automation] update elastic stack version for testing 8.2.1-93582d09

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Thu, 19 May 2022 05:13:11 GMT, release_branch:7.17, prefix:, end_time:Thu, 19 May 2022 09:41:16 GMT, manifest_version:2.1.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-60cd01b1, build_duration_seconds:16085]

[automation] update elastic stack version for testing 7.17.4-60cd01b1

---

testing/environments/snapshot.yml

[start_time:Thu, 19 May 2022 12:14:10 GMT, release_branch:master, prefix:, end_time:Thu, 19 May 2022 16:51:05 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-d754f94f, build_duration_seconds:16615]

[automation] update elastic stack version for testing 8.3.0-d754f94f

---

testing/environments/snapshot.yml

[start_time:Thu, 19 May 2022 12:14:07 GMT, release_branch:8.2, prefix:, end_time:Thu, 19 May 2022 16:42:43 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-54274789, build_duration_seconds:16116]

[automation] update elastic stack version for testing 8.2.1-54274789

---

.ci/bump-go-release-version.sh
.golangci.yml

Updates the script used to automatically bump the Go version with a sed command to update the Go version used by the linters.
There is a `mage:updateGoVersion` command but I'm not sure the CI worker used to run this script has Go installed. It definitely doesn't have mage installed, see related failure from https://github.com/elastic/elastic-agent-shipper/pull/39
```
12:22:29  [Pipeline] sh (Prepare changes for elastic-agent-shipper)
12:22:30  + .ci/bump-go-release-version.sh 1.18.2
12:22:30  Update go version 1.18.2
12:22:30  .ci/bump-go-release-version.sh: line 27: mage: command not found
12:22:30  [Pipeline] }
```
The Go version of our linters needs to be kept in sync with our build.
~- [ ] I have commented my code, …

Automatically update the golangci-lint Go versions

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Fri, 20 May 2022 05:13:43 GMT, release_branch:7.17, prefix:, end_time:Fri, 20 May 2022 09:41:34 GMT, manifest_version:2.1.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-1170b674, build_duration_seconds:16071]

[automation] update elastic stack version for testing 7.17.4-1170b674

---

testing/environments/snapshot.yml

[start_time:Fri, 20 May 2022 00:14:54 GMT, release_branch:8.2, prefix:, end_time:Fri, 20 May 2022 05:17:46 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-539cf6f5, build_duration_seconds:18172]

[automation] update elastic stack version for testing 8.2.1-539cf6f5

---

testing/environments/snapshot.yml

[start_time:Fri, 20 May 2022 00:14:18 GMT, release_branch:master, prefix:, end_time:Fri, 20 May 2022 05:06:28 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-3a5a0cd2, build_duration_seconds:17530]

[automation] update elastic stack version for testing 8.3.0-3a5a0cd2

---

CHANGELOG.next.asciidoc
auditbeat/auditbeat.reference.yml
filebeat/filebeat.reference.yml
filebeat/tests/system/config/filebeat_modules.yml.j2
heartbeat/heartbeat.reference.yml
libbeat/_meta/config.yml.tmpl
libbeat/_meta/config/general.reference.yml.tmpl
libbeat/cmd/instance/beat.go
libbeat/common/datetime.go
libbeat/common/datetime_test.go
libbeat/docs/generalconfig.asciidoc
libbeat/outputs/codec/common.go
metricbeat/metricbeat.reference.yml
packetbeat/packetbeat.reference.yml
packetbeat/tests/system/config/packetbeat.yml.j2
packetbeat/tests/system/test_0032_dns.py
packetbeat/tests/system/test_0050_icmp.py
packetbeat/tests/system/test_0062_cassandra.py
winlogbeat/winlogbeat.reference.yml
x-pack/auditbeat/auditbeat.reference.yml
x-pack/filebeat/filebeat.reference.yml
x-pack/filebeat/tests/system/config/filebeat_modules.yml.j2
x-pack/functionbeat/functionbeat.reference.yml
x-pack/heartbeat/heartbeat.reference.yml
x-pack/metricbeat/metricbeat.reference.yml
x-pack/osquerybeat/osquerybeat.reference.yml
x-pack/packetbeat/packetbeat.reference.yml
x-pack/winlogbeat/winlogbeat.reference.yml

This PR makes timestamp precision configurable. A new config option is added called `timestamp.precision`. Available options are `millisecond` `microseconds` and `nanosecond`. Default value is `millisecond`.
We made nanosecond support default in https://github.com/elastic/beats/pull/31553. But such timestamps require more storage. Thus, we are making it opt-in.

New option `timestamp.precision` to control timestamp precision

---

.ci/packaging.groovy

Publish docker images to the internal docker registry as they are only snapshot based.
https://github.com/elastic/beats/pull/31092 introduced a change and the env variable was removed, therefore docker images are not published but only GCP artifacts
versus

ci: publish docker images in the internal docker registry

---

testing/environments/snapshot.yml

[start_time:Mon, 23 May 2022 20:52:44 GMT, release_branch:8.2, prefix:, end_time:Tue, 24 May 2022 01:04:12 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-e97da867, build_duration_seconds:15088]

[automation] update elastic stack version for testing 8.2.1-e97da867

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Mon, 23 May 2022 12:01:37 GMT, release_branch:7.17, prefix:, end_time:Mon, 23 May 2022 17:12:48 GMT, manifest_version:2.1.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-1572020b, build_duration_seconds:18671]

[automation] update elastic stack version for testing 7.17.4-1572020b

---

CHANGELOG.next.asciidoc
heartbeat/docs/monitors/monitor-browser.asciidoc
x-pack/heartbeat/monitors/browser/config.go
x-pack/heartbeat/monitors/browser/project.go
x-pack/heartbeat/monitors/browser/project_test.go

Fixes https://github.com/elastic/beats/issues/28197
Adds the new `playwright_options` browser option.
Tested with the following config manually:
```yaml
- type: browser
enabled: true
id: browser-inline
name: browser-inline
ignoreHTTPSErrors: true
throttling:
download: 1.6
upload: 0.75
latency: 150
source:
inline:
script:
step("load homepage", async () => {
await page.goto('https://www.elastic.co');
});
step("hover over products menu", async () => {
await page.hover('css=[data-nav-item=products]');
});
step("failme", async () => {
await page.hhover('css=[data-nav-item=products]');
});
schedule: "@every 1m"
```

[Heartbeat] Add 'playwright_options' browser option

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Tue, 24 May 2022 05:13:32 GMT, release_branch:7.17, prefix:, end_time:Tue, 24 May 2022 09:52:11 GMT, manifest_version:2.1.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-d3844d00, build_duration_seconds:16719]

[automation] update elastic stack version for testing 7.17.4-d3844d00

---

metricbeat/docker-compose.yml
testing/environments/latest.yml
x-pack/metricbeat/docker-compose.yml

Merge only after the release of 8.2.1.

[Release] Update test environments for 8.2.2

---

metricbeat/docker-compose.yml
metricbeat/module/logstash/docker-compose.yml
testing/environments/latest.yml
x-pack/metricbeat/docker-compose.yml

Merge only after the release of 7.17.4.

[Release] Update test environments for 7.17.5

---

.mergify.yml

Merge as soon as 8.3 branch was created. Auto-merge is not yet supported, see https://github.com/Mergifyio/mergify-engine/discussions/2821

backport: Add 8.3 branch

---

CHANGELOG.asciidoc

Replaces https://github.com/elastic/beats/pull/31652.

Fix broken view commit links

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Thu, 26 May 2022 13:05:02 GMT, release_branch:7.17, prefix:, end_time:Thu, 26 May 2022 17:51:56 GMT, manifest_version:2.1.0, version:7.17.5-SNAPSHOT, branch:7.17, build_id:7.17.5-18de74ad, build_duration_seconds:17214]

[automation] update elastic stack version for testing 7.17.5-18de74ad

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Sun, 29 May 2022 05:17:48 GMT, release_branch:7.17, prefix:, end_time:Sun, 29 May 2022 09:52:46 GMT, manifest_version:2.1.0, version:7.17.5-SNAPSHOT, branch:7.17, build_id:7.17.5-5c3baac2, build_duration_seconds:16498]

[automation] update elastic stack version for testing 7.17.5-5c3baac2

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Mon, 30 May 2022 05:13:42 GMT, release_branch:7.17, prefix:, end_time:Mon, 30 May 2022 09:57:56 GMT, manifest_version:2.1.0, version:7.17.5-SNAPSHOT, branch:7.17, build_id:7.17.5-366dc66d, build_duration_seconds:17054]

[automation] update elastic stack version for testing 7.17.5-366dc66d

---

x-pack/osquerybeat/beater/action_handler_test.go
x-pack/osquerybeat/beater/config_plugin.go
x-pack/osquerybeat/beater/config_plugin_test.go
x-pack/osquerybeat/beater/osquery_runner_test.go
x-pack/osquerybeat/beater/osquerybeat.go
x-pack/osquerybeat/ext/osquery-extension/main.go
x-pack/osquerybeat/ext/osquery-extension/pkg/proc/list.go
x-pack/osquerybeat/ext/osquery-extension/pkg/tables/host_processes.go
x-pack/osquerybeat/internal/action/action.go
x-pack/osquerybeat/internal/command/command.go
x-pack/osquerybeat/internal/config/watcher.go
x-pack/osquerybeat/internal/ecs/mapping.go
x-pack/osquerybeat/internal/fileutil/fileutil.go
x-pack/osquerybeat/internal/install/verify.go
x-pack/osquerybeat/internal/install/verify_test.go
x-pack/osquerybeat/internal/osqdcli/client.go
x-pack/osquerybeat/internal/osqdcli/retry_test.go
x-pack/osquerybeat/internal/tar/tar.go
x-pack/osquerybeat/main_test.go

Address all the new linter complains as of today. 
1. Makes the code up to date with the linter requirements
2. Reduces the scope of future PRs when one change in the file would require the author of PR to delintify the whole file.

Osquerybeat: Address all the new linter complains as of today

---

libbeat/idxmgmt/ilm/config.go
libbeat/tests/system/idxmgmt.py
libbeat/tests/system/test_ilm.py

Based on change from https://github.com/elastic/elasticsearch/pull/69995
Users are having a hard time to have the "right sized shards" (~50gb),
but they also need to adjust the number of primaries to keep up with the
ingest load. This doesn't well with the `max_size` option but it should
work nicely with the newly introduced `max_primary_shard_size`.
This change the default ILM policy shipped with beats.
-

Use max_primary_shard_size instead of max_size

---

dev-tools/mage/integtest_docker.go
filebeat/magefile.go
filebeat/tests/system/test_pipeline.py
libbeat/tests/system/config/libbeat.yml.j2

Still waiting for 8.4.0 snapshot to be produced, in the meantime the beats version has been bumped to 8.4.0 and the filebeat system tests are all failing trying to connect to the 8.3.0 version of Elasticsearch.
As far as I can tell only the filebeat tests are failing with this problem which is interesting because all the beats should implement the same behaviour connecting to elasticsearch. Likely most of ES interaction is tested in the libbeat system tests using mockbeat that is set to allow older versions by default.

Let filebeat tests connect to older ES versions.

---

x-pack/dockerlogbeat/Dockerfile.tmpl

This is a quick fix for https://github.com/elastic/beats/issues/29468 
This is a bug, the plugin cannot otherwise initialize itself.

Update packages in dockerfile for the Dockerlogbeat

---

testing/environments/snapshot.yml

[start_time:Wed, 1 Jun 2022 00:14:15 GMT, release_branch:8.2, prefix:, end_time:Wed, 1 Jun 2022 04:41:56 GMT, manifest_version:2.1.0, version:8.2.3-SNAPSHOT, branch:8.2, build_id:8.2.3-e78add13, build_duration_seconds:16061]

[automation] update elastic stack version for testing 8.2.3-e78add13

---

testing/environments/snapshot.yml

[start_time:Tue, 31 May 2022 14:03:59 GMT, release_branch:master, prefix:, end_time:Tue, 31 May 2022 21:51:22 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-481759a3, build_duration_seconds:28043]

[automation] update elastic stack version for testing 8.4.0-481759a3

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Tue, 31 May 2022 05:14:09 GMT, release_branch:7.17, prefix:, end_time:Tue, 31 May 2022 09:49:43 GMT, manifest_version:2.1.0, version:7.17.5-SNAPSHOT, branch:7.17, build_id:7.17.5-7c990f83, build_duration_seconds:16534]

[automation] update elastic stack version for testing 7.17.5-7c990f83

---

testing/environments/snapshot.yml

[start_time:Wed, 1 Jun 2022 12:15:15 GMT, release_branch:8.2, prefix:, end_time:Wed, 1 Jun 2022 17:06:27 GMT, manifest_version:2.1.0, version:8.2.3-SNAPSHOT, branch:8.2, build_id:8.2.3-656a5d89, build_duration_seconds:17472]

[automation] update elastic stack version for testing 8.2.3-656a5d89

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Wed, 1 Jun 2022 05:17:20 GMT, release_branch:7.17, prefix:, end_time:Wed, 1 Jun 2022 10:05:38 GMT, manifest_version:2.1.0, version:7.17.5-SNAPSHOT, branch:7.17, build_id:7.17.5-a303ce60, build_duration_seconds:17298]

[automation] update elastic stack version for testing 7.17.5-a303ce60

---

testing/environments/snapshot.yml

[start_time:Thu, 2 Jun 2022 00:14:17 GMT, release_branch:master, prefix:, end_time:Thu, 2 Jun 2022 04:55:25 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-df27a645, build_duration_seconds:16868]

[automation] update elastic stack version for testing 8.4.0-df27a645

---

Jenkinsfile
deploy/kubernetes/Jenkinsfile.yml
metricbeat/docs/modules/kubernetes.asciidoc
metricbeat/module/kubernetes/_meta/docs.asciidoc

Adds the new version of `v1.24.0` in the list of the supported/tested versions.
Part of https://github.com/elastic/observability-dev/issues/2178.

Add v1.24 k8s version in testing list

---

testing/environments/snapshot.yml

[start_time:Thu, 2 Jun 2022 12:14:55 GMT, release_branch:master, prefix:, end_time:Thu, 2 Jun 2022 16:37:25 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-3525aaf7, build_duration_seconds:15750]

[automation] update elastic stack version for testing 8.4.0-3525aaf7

---

testing/environments/snapshot.yml

[start_time:Thu, 2 Jun 2022 17:14:59 GMT, release_branch:8.2, prefix:, end_time:Thu, 2 Jun 2022 21:30:17 GMT, manifest_version:2.1.0, version:8.2.3-SNAPSHOT, branch:8.2, build_id:8.2.3-f986a1ff, build_duration_seconds:15318]

[automation] update elastic stack version for testing 8.2.3-f986a1ff

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Thu, 2 Jun 2022 05:14:06 GMT, release_branch:7.17, prefix:, end_time:Thu, 2 Jun 2022 10:20:43 GMT, manifest_version:2.1.0, version:7.17.5-SNAPSHOT, branch:7.17, build_id:7.17.5-f01fee6a, build_duration_seconds:18397]

[automation] update elastic stack version for testing 7.17.5-f01fee6a

---

dev-tools/mage/crossbuild.go

Remove a workaround added to force to use ARM Docker images on ARM architectures to build ARM binaries.
This workaround is no longer need on the golang-crossbuild Docker images, we publish multiarch Docker images for the arm flavor.
- ~~[] I have commented my code, particularly in hard-to-understand areas~~
on an ARM64 machine run the command `PLATFORMS="linux/arm64" mage package` on any beat.
- Related to https://github.com/elastic/golang-crossbuild/issues/153

fix: use multiarch ARM Docker images on any architecture

---

libbeat/publisher/queue/memqueue/broker.go
libbeat/publisher/queue/queue.go

The only consumer of the queue metrics is currently the shipper, which is using the `opt` type out of `elastic-agent-libs`. This fixes the import to use the correct type.
Theoretically, the `libbeat/opt` should be removed, but this is currently blocking https://github.com/elastic/elastic-agent-shipper/pull/47, so I'd like to unblock that before we go and clean up the rest of the codebase.

Change library used by libbeat queue metrics

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Sun, 5 Jun 2022 05:13:10 GMT, release_branch:7.17, prefix:, end_time:Sun, 5 Jun 2022 10:05:27 GMT, manifest_version:2.1.0, version:7.17.5-SNAPSHOT, branch:7.17, build_id:7.17.5-572a2baf, build_duration_seconds:17537]

[automation] update elastic stack version for testing 7.17.5-572a2baf

---

testing/environments/snapshot.yml

[start_time:Sun, 5 Jun 2022 05:14:10 GMT, release_branch:8.2, prefix:, end_time:Sun, 5 Jun 2022 09:13:20 GMT, manifest_version:2.1.0, version:8.2.3-SNAPSHOT, branch:8.2, build_id:8.2.3-def79f93, build_duration_seconds:14350]

[automation] update elastic stack version for testing 8.2.3-def79f93

---

testing/environments/snapshot.yml

[start_time:Sun, 5 Jun 2022 12:14:04 GMT, release_branch:master, prefix:, end_time:Sun, 5 Jun 2022 16:34:07 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-42ce0eef, build_duration_seconds:15603]

[automation] update elastic stack version for testing 8.4.0-42ce0eef

---

NOTICE.txt
go.mod
go.sum

Update to go-sysinfo v1.8.0 https://github.com/elastic/go-sysinfo/releases/tag/v1.8.0.
- The boot time value for Windows is now rounded to the nearest second to provide a more stable value.
- Added the Oracle Linux ("ol") platform to the "redhat" OS family.
- Added the Linux Mint ("linuxmint") platform to the "debian" OS family.
- Fix handling of environment variables without values on macOS.
- Fix build tags on AIX provider such that CGO is required.

Update to go-sysinfo v1.8.0

---

libbeat/common/datetime.go

The sub-tests are not independent because `common.SetTimestampPrecision`
modifies a global. So this modifies `SetTimestampPrecision` to provide
a way to reset the global value to its default. Now each test
sets the global before executing.
There error was:
```
=== RUN   TestTimeString/empty_config
datetime_test.go:158:
Error Trace:	datetime_test.go:158
Error:      	Not equal:
expected: "2015-03-01T11:19:05.000Z"
actual  : "2015-03-01T11:19:05.000001Z"
```
The test was flaky.
You can reproduce the original failure with:
```
go test -count=1000 -run TestTimeString -race ./libbeat/common
```

[libbeat] Fix flaky TestTimeString/empty_config

---

libbeat/api/npipe/listener_windows.go

Remove the dependency on user.Current(). It fetches more information than
is required to configure the named pipe. This only needs to know the SID
in order to build the SDDL.
This avoids the possibility of lengthy delays fetching the unnecessary
metadata about the current user.
Relates #31810
On Windows, if the "TCP/IP NetBIOS Helper" is disabled then `calling user.Current()` can take up to 60 seconds.
This allows the process to initialize more quickly, and in the case of Agent, the Beat can respond to API requests earlier.
- Relates #31810

[libbeat] Modify npipe to get directly get the user SID

---

CHANGELOG.next.asciidoc
libbeat/cmd/instance/beat.go

This refactors the Beat initialization code to consolidate the metric registration into a
helper method and changes the call to lookup user info (`user.Current()`) to be 
asynchronous from the main initialization goroutine. This prevents the lookup from blocking
the process initialization and delaying the `StartServiceCtrlDispatcher` call that is required
by Windows services within a particular time period.
The user.Current() call can take up to 60 sec in some cases which causes Windows to
timeout the service and kill the process.
Relates #31810
It allows Beats to start as a Windows service.
- Relates #31810

[libbeat] Register uid/gid monitoring metrics asychronously

---

metricbeat/docker-compose.yml
testing/environments/snapshot.yml

[start_time:Thu, 2 Jun 2022 00:14:27 GMT, release_branch:8.3, prefix:, end_time:Thu, 2 Jun 2022 04:37:36 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-17c7e5c0, build_duration_seconds:15789]

[automation] update elastic stack version for testing 8.3.0-17c7e5c0

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Mon, 6 Jun 2022 05:14:44 GMT, release_branch:7.17, prefix:, end_time:Mon, 6 Jun 2022 09:55:53 GMT, manifest_version:2.1.0, version:7.17.5-SNAPSHOT, branch:7.17, build_id:7.17.5-1c762894, build_duration_seconds:16869]

[automation] update elastic stack version for testing 7.17.5-1c762894

---

libbeat/reader/readfile/line.go
libbeat/reader/readfile/line_test.go

Newlines also need to be recorded in the skipped characters
The skipped newline character is not recorded in the registry when the `max_bytes`(maximum limit of a single line) is exceeded. as the number of long lines increases, it will cause repeated reading problems
The relevant PR is #28352

[Filebeat] keep track of bytes read when max_bytes exceeded

---

testing/environments/snapshot.yml

[start_time:Tue, 7 Jun 2022 00:16:17 GMT, release_branch:master, prefix:, end_time:Tue, 7 Jun 2022 04:21:27 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-b8fce3f8, build_duration_seconds:14710]

[automation] update elastic stack version for testing 8.4.0-b8fce3f8

---

testing/environments/snapshot.yml

[start_time:Tue, 7 Jun 2022 17:18:50 GMT, release_branch:8.2, prefix:, end_time:Tue, 7 Jun 2022 21:10:54 GMT, manifest_version:2.1.0, version:8.2.3-SNAPSHOT, branch:8.2, build_id:8.2.3-7def4c60, build_duration_seconds:13924]

[automation] update elastic stack version for testing 8.2.3-7def4c60

---

testing/environments/snapshot.yml

[start_time:Wed, 8 Jun 2022 00:14:39 GMT, release_branch:8.3, prefix:, end_time:Wed, 8 Jun 2022 04:53:32 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-f13a89b4, build_duration_seconds:16733]

[automation] update elastic stack version for testing 8.3.0-f13a89b4

---

testing/environments/snapshot.yml

[start_time:Wed, 8 Jun 2022 17:14:46 GMT, release_branch:8.2, prefix:, end_time:Wed, 8 Jun 2022 21:22:41 GMT, manifest_version:2.1.0, version:8.2.3-SNAPSHOT, branch:8.2, build_id:8.2.3-a46e98e9, build_duration_seconds:14875]

[automation] update elastic stack version for testing 8.2.3-a46e98e9

---

testing/environments/snapshot.yml

[start_time:Thu, 9 Jun 2022 00:14:24 GMT, release_branch:8.3, prefix:, end_time:Thu, 9 Jun 2022 04:38:16 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-3c22a7f7, build_duration_seconds:15832]

[automation] update elastic stack version for testing 8.3.0-3c22a7f7

---

libbeat/reader/readfile/line.go
libbeat/reader/readfile/line_test.go

fix this issue #31863 
When the last line exceeds the maximum number of bytes, the text will be skipped directly, and then EOF will be returned, but the length of discarded bytes will not be returned, which will result in not being recorded in the registry, further causing repeated reading problems

[Filebeat] keep track of bytes read when max_bytes exceeded in last line

---

testing/environments/snapshot.yml

[start_time:Fri, 10 Jun 2022 00:19:05 GMT, release_branch:8.3, prefix:, end_time:Fri, 10 Jun 2022 04:08:13 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-158b3cba, build_duration_seconds:13748]

[automation] update elastic stack version for testing 8.3.0-158b3cba

---

testing/environments/snapshot.yml

[start_time:Sun, 12 Jun 2022 17:15:28 GMT, release_branch:8.2, prefix:, end_time:Sun, 12 Jun 2022 21:10:17 GMT, manifest_version:2.1.0, version:8.2.3-SNAPSHOT, branch:8.2, build_id:8.2.3-4b95b897, build_duration_seconds:14089]

[automation] update elastic stack version for testing 8.2.3-4b95b897

---

testing/environments/snapshot.yml

[start_time:Mon, 13 Jun 2022 00:14:44 GMT, release_branch:8.3, prefix:, end_time:Mon, 13 Jun 2022 04:40:53 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-db012561, build_duration_seconds:15969]

[automation] update elastic stack version for testing 8.3.0-db012561

---

CHANGELOG-developer.next.asciidoc
libbeat/publisher/pipeline/ttl_batch.go
libbeat/publisher/queue/diskqueue/benchmark_test.go
libbeat/publisher/queue/diskqueue/consumer.go
libbeat/publisher/queue/memqueue/ackloop.go
libbeat/publisher/queue/memqueue/broker.go
libbeat/publisher/queue/memqueue/eventloop.go
libbeat/publisher/queue/memqueue/internal_api.go
libbeat/publisher/queue/memqueue/queue_test.go
libbeat/publisher/queue/queue.go
libbeat/publisher/queue/queuetest/producer_cancel.go
libbeat/publisher/queue/queuetest/queuetest.go

Rename the `ACK` function in the `queue.Batch` interface to `Done`. This function is the only way to finish handling a batch, and must be called regardless of whether the events were acked or not. Its only effect is to inform the queue that the events can be discarded (and to trigger any associated callbacks).
`queue.Batch.ACK` is used in the vicinity of actual ACK handling, which can make it confusing to follow the side effects of various similarly-named functions. `Done` more clearly separates ACK handling from general event cleanup.

rename queue.Batch.ACK -> queue.Batch.Done

---

testing/environments/snapshot.yml

[start_time:Tue, 14 Jun 2022 00:18:07 GMT, release_branch:8.3, prefix:, end_time:Tue, 14 Jun 2022 04:30:39 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-e4e76686, build_duration_seconds:15152]

[automation] update elastic stack version for testing 8.3.0-e4e76686

---

testing/environments/snapshot.yml

[start_time:Mon, 13 Jun 2022 17:14:28 GMT, release_branch:8.2, prefix:, end_time:Mon, 13 Jun 2022 21:21:31 GMT, manifest_version:2.1.0, version:8.2.3-SNAPSHOT, branch:8.2, build_id:8.2.3-b55b20b5, build_duration_seconds:14823]

[automation] update elastic stack version for testing 8.2.3-b55b20b5

---

testing/environments/snapshot.yml

[start_time:Tue, 14 Jun 2022 00:14:26 GMT, release_branch:master, prefix:, end_time:Tue, 14 Jun 2022 04:50:43 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-7e67f5d9, build_duration_seconds:16577]

[automation] update elastic stack version for testing 8.4.0-7e67f5d9

---

metricbeat/docker-compose.yml
testing/environments/latest.yml
x-pack/metricbeat/docker-compose.yml

Merge only after the release of 8.2.3.

[Release] Update test environments for 8.2.4

---

x-pack/osquerybeat/beater/osquerybeat.go
x-pack/osquerybeat/beater/watcher.go
x-pack/osquerybeat/internal/osqd/osqueryd_unix.go

Added a parent process watcher to osquerybeat that:
1. Initialized when the osquerybeat start with the parent process ID.
2. Starts checking PPID every 10 seconds(hardcoded) when the beater.Stop is called.
3. Exits osquerybeat process if the PPID doesn't match with the original process ID.
This addresses the issue where the Osquerybeat process is left running orphaned when the Agent is uninstalled.
This a workaround to the original issue with libeat, beats managements and beats shutdown, see the link for more details:
https://github.com/elastic/elastic-agent/issues/556
This workaround allows for a fallback for osquerybeat if something gets broken in the shutdown logic up the stack. 
This problem is important to get solved for 8.3 release for osquerybeat.
1. Install the agent normally for …

Osquerybeat: Exit osquerybeat process if orphaned

---

testing/environments/snapshot.yml

[start_time:Wed, 15 Jun 2022 00:13:58 GMT, release_branch:master, prefix:, end_time:Wed, 15 Jun 2022 04:40:55 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-40cff009, build_duration_seconds:16017]

[automation] update elastic stack version for testing 8.4.0-40cff009

---

x-pack/osquerybeat/ext/osquery-extension/pkg/proc/namespace.go
x-pack/osquerybeat/ext/osquery-extension/pkg/proc/namespace_test.go

Implements namespace info as a part of our osquery_extension for processes.
The expectation is that the /proc is available in the container under /hostfs as: /hostfs/proc.
Initial code fetches the namespace inode number.
Addresses:
- https://github.com/elastic/security-team/issues/3532#issuecomment-1115805066
I've added local unit tests (`namespace_test.go`) for the parsing functionality.
```
Running tool: /usr/local/go/bin/go test -timeout 30s -run ^TestNamespaceFS$ github.com/elastic/beats/v7/x-pack/osquerybeat/ext/osquery-extension/pkg/proc
=== RUN   TestNamespaceFS
--- PASS: TestNamespaceFS (0.00s)
PASS
ok      github.com/elastic/beats/v7/x-pack/osquerybeat/ext/osquery-extension/pkg/proc   0.675s
> Test run finished at 6/13/2022, 11:18:39 PM <
```
Relates …

Osquerybeat: Implement namespace info as a part of proc osquery_extension

---

metricbeat/module/mongodb/replstatus/replstatus_integration_test.go

This test is failing regularly and blocking multiple PRs now. I'm skipping it until we can make it pass reliably. This test seems to be cursed, it has been flaky through multiple implementation changes now.
- Relates https://github.com/elastic/beats/issues/31768

Skip metricbeat/module/mongodb/replstatus.TestFetch

---

testing/environments/snapshot.yml

[start_time:Wed, 15 Jun 2022 12:14:33 GMT, release_branch:8.3, prefix:, end_time:Wed, 15 Jun 2022 16:52:58 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-fe62331f, build_duration_seconds:16705]

[automation] update elastic stack version for testing 8.3.0-fe62331f

---

testing/environments/snapshot.yml

[start_time:Thu, 16 Jun 2022 00:14:47 GMT, release_branch:master, prefix:, end_time:Thu, 16 Jun 2022 04:24:56 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-5e6770b1, build_duration_seconds:15009]

[automation] update elastic stack version for testing 8.4.0-5e6770b1

---

testing/environments/snapshot.yml

[start_time:Thu, 16 Jun 2022 05:14:05 GMT, release_branch:8.2, prefix:, end_time:Thu, 16 Jun 2022 09:18:56 GMT, manifest_version:2.1.0, version:8.2.4-SNAPSHOT, branch:8.2, build_id:8.2.4-4cc4fbfd, build_duration_seconds:14691]

[automation] update elastic stack version for testing 8.2.4-4cc4fbfd

---

CHANGELOG.next.asciidoc
libbeat/publisher/queue/diskqueue/writer_loop.go

Improves speed and lowers allocations
Improves speed and lowers allocations in disk queue by coalescing writes.
lowers performance cost of using disk queue.
Tested with `libbeat/publisher/queue/diskqueue/benchmark_test.go`
before change
`go test -bench=. -benchtime 1x -count 10 -timeout 120m -benchmem > baseline.txt`
after change
`go test -bench=. -benchtime 1x -count 10 -timeout 120m -benchmem > gather_w.txt`
```
benchstat baseline.txt gather_w.txt
name       old time/op    new time/op    delta
1M_10-16      38.7s ± 2%     21.8s ± 0%  -43.58%  (p=0.000 n=10+7)
1M_100-16     38.7s ± 1%     21.8s ± 1%  -43.74%  (p=0.000 n=10+10)
1M_1k-16      38.6s …
```

improve disk queue performance by coalescing writes

---

testing/environments/snapshot.yml

[start_time:Thu, 16 Jun 2022 17:19:33 GMT, release_branch:8.2, prefix:, end_time:Thu, 16 Jun 2022 21:15:53 GMT, manifest_version:2.1.0, version:8.2.4-SNAPSHOT, branch:8.2, build_id:8.2.4-01ccaf06, build_duration_seconds:14180]

[automation] update elastic stack version for testing 8.2.4-01ccaf06

---

testing/environments/snapshot.yml

[start_time:Fri, 17 Jun 2022 00:14:23 GMT, release_branch:master, prefix:, end_time:Fri, 17 Jun 2022 04:19:18 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-da5a1c6d, build_duration_seconds:14695]

[automation] update elastic stack version for testing 8.4.0-da5a1c6d

---

Jenkinsfile

Create a GitHub issue:
* As soon as a build is failing an issue should be created
* It should be assigned to Elastic Agent Data Plane team (it relies on the GitHub labels to do so)
Use GitHub to drive the on-call process when the CI fails
https://github.com/elastic/beats/issues/31958 was created automatically
Requires https://github.com/elastic/apm-pipeline-library/pull/1731

ci: create GitHub issue if build failure

---

CHANGELOG-developer.next.asciidoc
dev-tools/mage/build.go

Fix the flags used when the environmet varialbe DEV=true is set. This
allows to generate binaries without code optmisation and debug
symbols.
It allows us to easily generate binaries for debugging.
~~## Logs~~

Fix flags for dev build

---

metricbeat/docs/modules/oracle.asciidoc
x-pack/metricbeat/metricbeat.reference.yml
x-pack/metricbeat/module/oracle/_meta/config.yml
x-pack/metricbeat/modules.d/oracle.yml.disabled

This is breaking the docs build as the referenced URL does not exist
yet. I suspect it might only exist after this module has been published
at least once.
Broken in https://github.com/elastic/beats/pull/31368

Remove broken link from Oracle module docs.

---

testing/environments/snapshot.yml

[start_time:Sun, 19 Jun 2022 17:14:23 GMT, release_branch:8.2, prefix:, end_time:Sun, 19 Jun 2022 21:07:17 GMT, manifest_version:2.1.0, version:8.2.4-SNAPSHOT, branch:8.2, build_id:8.2.4-698e06ec, build_duration_seconds:13974]

[automation] update elastic stack version for testing 8.2.4-698e06ec

---

testing/environments/snapshot.yml

[start_time:Mon, 20 Jun 2022 00:14:27 GMT, release_branch:master, prefix:, end_time:Mon, 20 Jun 2022 04:17:38 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-b13123ee, build_duration_seconds:14591]

[automation] update elastic stack version for testing 8.4.0-b13123ee

---

metricbeat/module/logstash/node/data.go

This PR closes https://github.com/elastic/beats/issues/31739.
This PR stops multiple errors being logged when using Logstash with multiple pipelines.
⚠️ **Please see the fields / mapping inconsistency section I've added in this description, because whilst this PR fixes the logging issue, there are some questions.** ⚠️ 
The Logs are noisy.
- Follow the docs to setup your environment to build Beats (here: https://www.elastic.co/guide/en/beats/devguide/current/beats-contributing.html#setting-up-dev-environment)
- Checkout this branch, and then`cd metricbeat`, and then `mage build`.
- Make a Metricbeat config file that contains the following (change the credentials):
```yml
http.enabled: true
- module: system
- module: logstash
xpack.enabled: true
period: 10s
hosts: [ …
```

[Metricbeat] Stop continual error with multiple Logstash pipelines

---

testing/environments/snapshot.yml

[start_time:Mon, 20 Jun 2022 17:14:26 GMT, release_branch:8.2, prefix:, end_time:Mon, 20 Jun 2022 21:08:40 GMT, manifest_version:2.1.0, version:8.2.4-SNAPSHOT, branch:8.2, build_id:8.2.4-b657c8f5, build_duration_seconds:14054]

[automation] update elastic stack version for testing 8.2.4-b657c8f5

---

CHANGELOG.next.asciidoc
filebeat/docs/inputs/input-filestream-file-options.asciidoc
filebeat/input/filestream/copytruncate_prospector_test.go
filebeat/input/filestream/prospector.go
filebeat/input/filestream/prospector_test.go

This PR saves the size of the ignored files. Thus, if the file is updated, `filestream` input only reads the new log lines, not the whole file.
The PR also fixes a minor logging problem. Previously, resetting the cursor due to truncation was always logged at an error level. Not it is only logged if the cursor is not reset properly.
Now `filestream` input starts to read from the beginning of the file. This is not what we promise in the documentation:
> For files which were never seen before, the offset state is set to the end of the file... If a file is updated again later, reading continues at the set offset position.
1. Create a `test.log` file with the following contents:
```
ignored line
ignored line
ignored …
```

Save file size to registry of ignored files

---

CHANGELOG.next.asciidoc
libbeat/common/jsontransform/expand.go
libbeat/common/jsontransform/jsonhelper.go
libbeat/processors/actions/decode_json_fields.go
libbeat/processors/actions/decode_json_fields_test.go

This PR applies the settings in `expand_keys` to the event even if the target is not empty. 
Previously, if target was set to anything besides `""`, `expand_keys` did not work. So you could not expand the keys of the parsed JSON if you wanted to put it under a custom field.
Config:
```yaml
id: my-filestream-id
paths:
- test.log
processors:
- decode_json_fields:
target: "my_target"
expand_fields: true
fields: ["message"]
output.console:
enabled: true
```
Example input file:
```
{"my.field": "interesting value"}
```
Check if the keys are expanded in the published event:
```json
{
"message": "{\"my.field\": …
```

Expand fields in `decode_json_fields` if target is set

---

testing/environments/snapshot.yml

[start_time:Tue, 21 Jun 2022 05:17:37 GMT, release_branch:8.2, prefix:, end_time:Tue, 21 Jun 2022 14:49:50 GMT, manifest_version:2.1.0, version:8.2.4-SNAPSHOT, branch:8.2, build_id:8.2.4-589bdf37, build_duration_seconds:34333]

[automation] update elastic stack version for testing 8.2.4-589bdf37

---

testing/environments/snapshot.yml

[start_time:Tue, 21 Jun 2022 12:14:37 GMT, release_branch:8.3, prefix:, end_time:Tue, 21 Jun 2022 17:33:10 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-e0057e17, build_duration_seconds:19113]

[automation] update elastic stack version for testing 8.3.0-e0057e17

---

libbeat/publisher/queue/diskqueue/benchmark_test.go
libbeat/publisher/queue/diskqueue/config.go
libbeat/publisher/queue/diskqueue/core_loop.go
libbeat/publisher/queue/diskqueue/core_loop_test.go
libbeat/publisher/queue/diskqueue/docs/Makefile
libbeat/publisher/queue/diskqueue/docs/frameV0.pic
libbeat/publisher/queue/diskqueue/docs/frameV0.svg
libbeat/publisher/queue/diskqueue/docs/frameV1.pic
libbeat/publisher/queue/diskqueue/docs/frameV1.svg
libbeat/publisher/queue/diskqueue/docs/frameV2.pic
libbeat/publisher/queue/diskqueue/docs/frameV2.svg
libbeat/publisher/queue/diskqueue/docs/on-disk-structures.md
libbeat/publisher/queue/diskqueue/docs/schemaV0.pic
libbeat/publisher/queue/diskqueue/docs/schemaV0.svg
libbeat/publisher/queue/diskqueue/docs/schemaV1.pic
libbeat/publisher/queue/diskqueue/docs/schemaV1.svg
libbeat/publisher/queue/diskqueue/docs/schemaV2.pic
libbeat/publisher/queue/diskqueue/docs/schemaV2.svg
libbeat/publisher/queue/diskqueue/encryption.go
libbeat/publisher/queue/diskqueue/encryption_test.go
libbeat/publisher/queue/diskqueue/reader_loop.go
libbeat/publisher/queue/diskqueue/segments.go
libbeat/publisher/queue/diskqueue/segments_test.go
libbeat/publisher/queue/diskqueue/serialize.go
libbeat/publisher/queue/diskqueue/writer_loop.go

Adds support for AES 128 CTR encryption to disk queue.
Necessary for endpoint running under elastic-agent
```
go test -bench=1M -benchtime 1x -count 10 -timeout 600m -benchmem > results.txt
benchstat results.txt
name               time/op
Async1M-16          22.0s ± 1%
EncryptAsync1M-16   20.5s ± 1%
Sync1M-16           25.2s ± 1%
EncryptSync1M-16    27.5s ± 0%
name               alloc/op
Async1M-16         3.43GB ± 0%
EncryptAsync1M-16  3.43GB ± 0%
Sync1M-16          3.42GB ± 0%
EncryptSync1M-16   3.42GB ± 0%
name               allocs/op
Async1M-16          40.6M ± 0%
EncryptAsync1M-16   40.5M ± 0%
Sync1M-16           39.5M ± 0%
EncryptSync1M-16    40.1M ± 0%
```
- Relates elastic-agent-shipper#33
- Relates …

Add encryption to diskqueue

---

filebeat/docs/multiline.asciidoc

This PR adds `filestream` `parser` configuration to multiline examples.
Avoid user confusion.
Closes https://github.com/elastic/beats/issues/31578

Extend multiline documentation with filestream syntax

---

libbeat/outputs/kafka/docs/kafka.asciidoc

Remove the outdated `worker` setting in the Kafka output documentation.
Set this setting does not have any effect.
- Relates #4492: Before this PR, the `worker` setting was used to create multiple `sarama.AsyncProducer`. After it, the `worker` setting only makes [`hosts` entries duplicated](https://github.com/elastic/beats/blob/7102be4e5594f158c2b80ff075246d5eab94bebe/libbeat/outputs/hosts.go#L43-L43) for [calling `sarama.NewAsyncProducer`](https://github.com/elastic/beats/blob/7102be4e5594f158c2b80ff075246d5eab94bebe/libbeat/outputs/kafka/client.go#L123-L123), which does not have any positive effect, but a little overhead for [metadata refresh](https://github.com/Shopify/sarama/blob/30b9203a2d27a1d723a223093753453436084e73/client.go#L891-L891).

Remove outdated setting in Kafka output documentation

---

x-pack/elastic-agent/CHANGELOG.next.asciidoc
x-pack/elastic-agent/pkg/agent/cmd/diagnostics.go

Backport https://github.com/elastic/elastic-agent/pull/570
* Add filemod times to contents of diagnostics collect command
Add filemod times to the files and directories in the zip archive.
Log files (and sub dirs) will use the modtime returned by the fileinfo
for the source. Others will use the timestamp from when the zip is
created.
* Fix linter

[7.17](backport elastic/elastic-agent#570) Add filemod times to contents of diagnostics collect command

---

CHANGELOG.asciidoc

https://github.com/elastic/beats/pull/31185 is not in the 8.2 branch, but in 8.3. Fixing the changelog.

Remove invalid entry

---

auditbeat/tests/system/requirements.txt
dev-tools/requirements.txt
heartbeat/tests/system/requirements.txt
libbeat/tests/system/requirements.txt
metricbeat/module/kubernetes/_meta/terraform/eks/requirements.txt
metricbeat/tests/system/requirements.txt
packetbeat/tests/system/gen/memcache/requirements.txt
x-pack/functionbeat/tests/system/requirements.txt

Same problem as https://github.com/elastic/e2e-testing/pull/2569
All the Python system tests for every beat fail to run because `pip install` is failing trying to install transitive protobuf dependencies.

Pin the protobuf version in system tests.

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Wed, 22 Jun 2022 05:13:37 GMT, release_branch:7.17, prefix:, end_time:Wed, 22 Jun 2022 09:57:15 GMT, manifest_version:2.1.0, version:7.17.5-SNAPSHOT, branch:7.17, build_id:7.17.5-8d9f50d0, build_duration_seconds:17018]

[automation] update elastic stack version for testing 7.17.5-8d9f50d0

---

testing/environments/snapshot.yml

[start_time:Wed, 22 Jun 2022 12:14:08 GMT, release_branch:8.3, prefix:, end_time:Wed, 22 Jun 2022 17:26:40 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-47d97929, build_duration_seconds:18752]

[automation] update elastic stack version for testing 8.3.0-47d97929

---

testing/environments/snapshot.yml

[start_time:Wed, 22 Jun 2022 12:16:38 GMT, release_branch:master, prefix:, end_time:Wed, 22 Jun 2022 18:05:34 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-2e32a640, build_duration_seconds:20936]

[automation] update elastic stack version for testing 8.4.0-2e32a640

---

libbeat/reader/parser/parser_test.go

This PR ports existing Python tests of `log` input to `filesteam`. The PR contains the test cases for `test_type_in_message`. Thus, the tests in Python can be disabled/removed.
Decrease the amount of low-quality E2E tests.

Port `test_type_in_message` to filestream Golang tests

---

filebeat/input/filestream/environment_test.go
filebeat/input/filestream/input_integration_test.go

This PR ports the test `test_rotating_close_inactive_low_write_rate` to Golang for `filestream` input.
Decrease the amount of low value E2E tests. Also, check `filestream` against corner cases.

Port `test_rotating_close_inactive_low_write_rate` to Golang

---

.ci/packaging.groovy

This reverts commit 2241413626b9bdd87245c4dbd29675cee6400358.
Allow the E2E tests to keep running but do not have them fail the build when they do not pass.
Part of https://github.com/elastic/beats/issues/32076. The E2E tests are not reliable enough to act as a quality gate for the DRA process yet. The team doesn't have the capacity to improve the tests fast enough. We previously went 2+ weeks without publishing a beats snapshot image.

Revert "ci: e2e-testing should fail the build (#31135)"

---

CHANGELOG.next.asciidoc
heartbeat/docs/monitors/monitor-common-options.asciidoc
heartbeat/monitors/factory.go
heartbeat/monitors/factory_test.go

A frequent UX issue for our users is wanting to set different retention periods for network / screenshot data. Our default settings for browser monitors really hurt here since we lump them all into a `heartbeat` data stream unless users are using fleet. This addresses this issue by defaulting browser monitors to use `synthetics*` data streams which breaks them out by type.
We can't do this in any sort of simple way with the 'heartbeat' prefix. This shouldn't be a practical issue for most users since in 8.x all kibana clusters have synthetics templates pre-installed. Users who have explicitly set their kibana index pattern to only `heartbeat-*` with no `synthetics-*` will be affected. Given that we are in beta this potential breakage is worth it for the long term benefits to users.
This …

[Heartbeat] Always use synthetics data streams for browser

---

libbeat/docs/tab-widgets/spinup-stack.asciidoc

Updates the cross references to info about self-managed installs.
We're retiring the Stack GS guide in favor of the new onboarding content introduced in 8.2.

[DOCS] Removed reference to the Stack GS

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Thu, 23 Jun 2022 05:13:50 GMT, release_branch:7.17, prefix:, end_time:Thu, 23 Jun 2022 10:01:15 GMT, manifest_version:2.1.0, version:7.17.5-SNAPSHOT, branch:7.17, build_id:7.17.5-781a81f2, build_duration_seconds:17245]

[automation] update elastic stack version for testing 7.17.5-781a81f2

---

testing/environments/snapshot.yml

[start_time:Fri, 24 Jun 2022 00:14:40 GMT, release_branch:8.3, prefix:, end_time:Fri, 24 Jun 2022 04:58:09 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-3b390c7b, build_duration_seconds:17009]

[automation] update elastic stack version for testing 8.3.0-3b390c7b

---

testing/environments/snapshot.yml

[start_time:Thu, 23 Jun 2022 12:14:12 GMT, release_branch:master, prefix:, end_time:Thu, 23 Jun 2022 16:35:54 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-722a7d79, build_duration_seconds:15702]

[automation] update elastic stack version for testing 8.4.0-722a7d79

---

CHANGELOG.next.asciidoc
heartbeat/ecserr/ecserr.go
heartbeat/ecserr/ecserr_test.go
heartbeat/monitors/wrappers/wrappers.go
heartbeat/monitors/wrappers/wrappers_test.go
x-pack/heartbeat/monitors/browser/synthexec/enrich.go
x-pack/heartbeat/monitors/browser/synthexec/enrich_test.go
x-pack/heartbeat/monitors/browser/synthexec/synthexec.go
x-pack/heartbeat/monitors/browser/synthexec/synthexec_test.go
x-pack/heartbeat/monitors/browser/synthexec/synthtypes.go
x-pack/heartbeat/monitors/browser/synthexec/synthtypes_test.go
x-pack/heartbeat/monitors/browser/synthexec/testcmd/main.go

Fixes #30170 by taking a slightly different approach than previously thought.
We apparently suffered a regression in two places simultaneously:
1. Kibana stopped rendering components like [console output event list](https://github.com/elastic/kibana/blob/main/x-pack/plugins/synthetics/public/legacy_uptime/components/synthetics/console_output_event_list.tsx)
2. Heartbeat didn't really report these in a way that made sense in its schema, choosing between a final `cmd/status` and `summary` event.
This PR fixes the dilemma by always outputting a final summary event, and, in the case of an exit code `> 0` for the synthetics agent, adding a special error to that summary event. When we fix the UI regression we can look for that special error. That being said, I think this is somewhat overkill, …

[Heartbeat] Include cmd/status errs , add ECS Errs

---

CHANGELOG.next.asciidoc
x-pack/heartbeat/monitors/browser/synthexec/enrich.go
x-pack/heartbeat/monitors/browser/synthexec/enrich_test.go

As part of https://github.com/elastic/beats/pull/31877/files#diff-b6c88c98d3a0073b9edf475ef0c1e713ba39dccff126a1b99ac107cafea863edR92
a regression was introduced where we write both a dotted (non-nested) key `event.type` when we meant to create an `event` object with an inner `type` key.
This was a mistake in the aforementioned PR.
Interestingly, this is hard to test with lookslike, which equivocates those two conditions in the name of simplifying test syntax.
To test this you'll want to manually run heartbeat with a browser
monitor and check that the correct object is set.
From my own testing using the console output:
```
mage build && env ELASTIC_SYNTHETICS_CAPABLE=true ./heartbeat -e | jq '{st: .synthetics.type, et: .event, ett: .["event.type"]}'
{
"st": "journey/start",
"et": { …
```

[Heartbeat] 'event.type: foo' should be 'event: {type: foo}' for browser

---

testing/environments/snapshot.yml

[start_time:Sat, 25 Jun 2022 00:18:11 GMT, release_branch:8.3, prefix:, end_time:Sat, 25 Jun 2022 04:28:19 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-fdf97a2e, build_duration_seconds:15008]

[automation] update elastic stack version for testing 8.3.0-fdf97a2e

---

testing/environments/snapshot.yml

[start_time:Fri, 24 Jun 2022 12:15:00 GMT, release_branch:master, prefix:, end_time:Fri, 24 Jun 2022 16:42:38 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-210dd487, build_duration_seconds:16058]

[automation] update elastic stack version for testing 8.4.0-210dd487

---

CHANGELOG.next.asciidoc
filebeat/_meta/config/filebeat.inputs.reference.yml.tmpl
filebeat/_meta/config/filebeat.inputs.yml.tmpl
filebeat/docs/inputs/input-filestream-reader-options.asciidoc
filebeat/filebeat.reference.yml
filebeat/filebeat.yml
libbeat/reader/filter/filter.go
libbeat/reader/filter/filter_test.go
libbeat/reader/parser/parser.go
x-pack/filebeat/filebeat.reference.yml
x-pack/filebeat/filebeat.yml

This PR adds a new parser to filter messages. If a message matches one of the patterns from the list, it is passed on to the next parser, otherwise it is dropped.
The existing `include_lines` and `exlcude_lines` filtering runs after the `parsers` pipeline, so it is not possible to select messages before parsing them.
Closes https://github.com/elastic/beats/issues/31794

Add new `parser` called `include_message` to filter messages

---

NOTICE.txt
go.mod
go.sum
libbeat/publisher/queue/diskqueue/benchmark_test.go
libbeat/publisher/queue/diskqueue/compression.go
libbeat/publisher/queue/diskqueue/compression_test.go
libbeat/publisher/queue/diskqueue/config.go
libbeat/publisher/queue/diskqueue/docs/on-disk-structures.md
libbeat/publisher/queue/diskqueue/enc_compress_test.go
libbeat/publisher/queue/diskqueue/segments.go
libbeat/publisher/queue/diskqueue/segments_test.go

Adds option for compression to beats disk queue.  Works with or without encryption.
For certain workloads this can dramatically reduce the amount of data written to disk reducing both encryption overhead and disk I/O
```
go test -bench=1M -benchtime 1x -count 10 -timeout 600m -benchmem > results.txt
benchstat results.txt
name                       time/op
Async1M-16                  21.9s ± 1%
EncryptAsync1M-16           20.9s ± 1%
CompressAsync1M-16          12.4s ± 0%
EncryptCompressAsync1M-16   12.4s ± 1%
Sync1M-16                   25.0s ± 1%
EncryptSync1M-16            27.3s ± 0%
CompressSync1M-16           14.2s ± 0%
EncryptCompressSync1M-16    14.2s ± 0%
name                       alloc/op
Async1M-16 …
```

Add compression to disk queue

---

libbeat/docs/tab-widgets/spinup-stack.asciidoc

We're retiring the Stack Getting Started guide in favor of the new onboarding content introduced in 8.2. (Cherry-picked from master...)

[DOCS] Removed reference to the Stack GS (#32083)

---

testing/environments/snapshot.yml

[start_time:Mon, 27 Jun 2022 17:14:43 GMT, release_branch:8.2, prefix:, end_time:Mon, 27 Jun 2022 21:31:15 GMT, manifest_version:2.1.0, version:8.2.4-SNAPSHOT, branch:8.2, build_id:8.2.4-9b981623, build_duration_seconds:15392]

[automation] update elastic stack version for testing 8.2.4-9b981623

---

testing/environments/snapshot.yml

[start_time:Tue, 28 Jun 2022 00:14:46 GMT, release_branch:master, prefix:, end_time:Tue, 28 Jun 2022 04:37:57 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-a6aa9f3b, build_duration_seconds:15791]

[automation] update elastic stack version for testing 8.4.0-a6aa9f3b

---

CHANGELOG.next.asciidoc
NOTICE.txt
go.mod
go.sum

This brings in a fix in go-libaudit that fixes parsing of audit status messages that do not include fields beyond the feature bit map in the message.
Without this fix some versions of linux that we support are unable to run auditbeat.
- Closes #31616

auditbeat: update version of go-libaudit

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Tue, 28 Jun 2022 05:13:46 GMT, release_branch:7.17, prefix:, end_time:Tue, 28 Jun 2022 10:18:28 GMT, manifest_version:2.1.0, version:7.17.5-SNAPSHOT, branch:7.17, build_id:7.17.5-b5794350, build_duration_seconds:18282]

[automation] update elastic stack version for testing 7.17.5-b5794350

---

testing/environments/snapshot.yml

[start_time:Tue, 28 Jun 2022 17:19:31 GMT, release_branch:8.2, prefix:, end_time:Tue, 28 Jun 2022 21:17:35 GMT, manifest_version:2.1.0, version:8.2.4-SNAPSHOT, branch:8.2, build_id:8.2.4-62f5ece5, build_duration_seconds:14284]

[automation] update elastic stack version for testing 8.2.4-62f5ece5

---

testing/environments/snapshot.yml

[start_time:Tue, 28 Jun 2022 12:14:21 GMT, release_branch:8.3, prefix:, end_time:Tue, 28 Jun 2022 16:47:11 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-729c5564, build_duration_seconds:16370]

[automation] update elastic stack version for testing 8.3.0-729c5564

---

testing/environments/snapshot.yml

[start_time:Wed, 29 Jun 2022 00:15:16 GMT, release_branch:master, prefix:, end_time:Wed, 29 Jun 2022 04:20:44 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-4ec2d3b3, build_duration_seconds:14728]

[automation] update elastic stack version for testing 8.4.0-4ec2d3b3

---

testing/environments/snapshot.yml

[start_time:Wed, 29 Jun 2022 05:14:48 GMT, release_branch:8.2, prefix:, end_time:Wed, 29 Jun 2022 09:39:00 GMT, manifest_version:2.1.0, version:8.2.4-SNAPSHOT, branch:8.2, build_id:8.2.4-e7c42e26, build_duration_seconds:15852]

[automation] update elastic stack version for testing 8.2.4-e7c42e26

---

testing/environments/snapshot.yml

[start_time:Wed, 29 Jun 2022 10:00:17 GMT, release_branch:8.3, prefix:, end_time:Wed, 29 Jun 2022 17:35:55 GMT, manifest_version:2.1.0, version:8.3.1-SNAPSHOT, branch:8.3, build_id:8.3.1-b95de5e6, build_duration_seconds:27338]

[automation] update elastic stack version for testing 8.3.1-b95de5e6

---

CHANGELOG.next.asciidoc
packetbeat/_meta/config/beat.reference.yml.tmpl
packetbeat/_meta/config/beat.yml.tmpl
packetbeat/config/agent.go
packetbeat/docs/packetbeat-options.asciidoc
packetbeat/packetbeat.reference.yml
packetbeat/packetbeat.yml
packetbeat/scripts/mage/config.go
packetbeat/sniffer/device.go
packetbeat/tests/system/config/packetbeat.yml.j2
x-pack/packetbeat/packetbeat.reference.yml
x-pack/packetbeat/packetbeat.yml

This allows users to specify sniffing on the default route interface for all platforms rather than having to specify a hard-coded interface or interface index on non-linux platforms.
This makes setting up large installations more robust for non-linux hosts as the interface identities do not need to be known during configuration.
- Depends #31914 
- Updates #31905

packetbeat: wire default interface selection into config

---

testing/environments/snapshot.yml

[start_time:Thu, 30 Jun 2022 12:14:14 GMT, release_branch:master, prefix:, end_time:Thu, 30 Jun 2022 16:33:00 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-3d206b5d, build_duration_seconds:15526]

[automation] update elastic stack version for testing 8.4.0-3d206b5d

---

testing/environments/snapshot.yml

[start_time:Mon, 4 Jul 2022 00:15:23 GMT, release_branch:master, prefix:, end_time:Mon, 4 Jul 2022 04:37:22 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-3ad82aa8, build_duration_seconds:15719]

[automation] update elastic stack version for testing 8.4.0-3ad82aa8

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Fri, 1 Jul 2022 05:17:49 GMT, release_branch:7.17, prefix:, end_time:Fri, 1 Jul 2022 10:09:57 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-63d4a205, build_duration_seconds:17528]

[automation] update elastic stack version for testing 7.17.6-63d4a205

---

libbeat/processors/fingerprint/docs/fingerprint.asciidoc

This PR documents how to create a fingerprint from nested fields. I spent a short while figuring out the pattern whilst trying to migrate from the logstash format of `[log][path][file]`
Hopefully developers spend less time implementing config changes
Configure a filebeat fingerprint processor with a nested field
n/a
n/a
n/a
n/a

Document nested fields support for fingerprints

---

testing/environments/snapshot.yml

[start_time:Tue, 5 Jul 2022 00:14:19 GMT, release_branch:8.3, prefix:, end_time:Tue, 5 Jul 2022 04:22:13 GMT, manifest_version:2.1.0, version:8.3.2-SNAPSHOT, branch:8.3, build_id:8.3.2-d34285fd, build_duration_seconds:14874]

[automation] update elastic stack version for testing 8.3.2-d34285fd

---

testing/environments/snapshot.yml

[start_time:Mon, 4 Jul 2022 12:16:14 GMT, release_branch:master, prefix:, end_time:Mon, 4 Jul 2022 17:02:59 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-03bd6f3f, build_duration_seconds:17205]

[automation] update elastic stack version for testing 8.4.0-03bd6f3f

---

CHANGELOG.next.asciidoc
NOTICE.txt
go.mod
go.sum

Upgrade the elastic-agent-system-metrics version to pick up https://github.com/elastic/elastic-agent-system-metrics/pull/37
The JSON structure of the beat metrics report was unintentionally broken as part of refactoring the system metrics packages into their own repositories. This restores it to what it was before .
This upgrade also picks up another minor change adding support displaying uninterruptible sleeps CPU states.

Update system metrics

---

CHANGELOG.asciidoc
winlogbeat/eventlog/errors_windows.go

This marks ERROR_EVT_QUERY_RESULT_STALE as a recoverable error that can be handled by closing and requerying.
In some cases, it is possible for a query to go stale between making the query and obtaining the log message. This currently results in a fatal error and termination of the beat. This change allows the beat to retry.
- Closes #32168

winlogbeat/eventlog: allow attempts at recovery from ERROR_EVT_QUERY_RESULT_STALE

---

testing/environments/snapshot.yml

[start_time:Wed, 6 Jul 2022 00:15:45 GMT, release_branch:8.3, prefix:, end_time:Wed, 6 Jul 2022 04:35:35 GMT, manifest_version:2.1.0, version:8.3.2-SNAPSHOT, branch:8.3, build_id:8.3.2-56253b46, build_duration_seconds:15590]

[automation] update elastic stack version for testing 8.3.2-56253b46

---

filebeat/input/filestream/prospector.go

Fixes typo in log message: harverster -> harvester, e.g.:
2022-07-06T10:23:57.578+0200	ERROR	[input.filestream]	filestream/prospector.go:291	Error while stopping **harverster** group: task failures
Error might be skipped if someone searches by "harvester" term.
2022-07-06T10:23:57.578+0200	ERROR	[input.filestream]	filestream/prospector.go:291	Error while stopping **harverster** group: task failures

Fix typo in log message

---

NOTICE.txt
go.mod
go.sum
packetbeat/route/route_windows.go

This uses the now-available x/sys/windows functions to obtain the information that we previously used locally defined calls for.
This reduces maintenance burden.
-

packetbeat/route: make use of newly added GetBestInterfaceEx in x/sys/windows

---

testing/environments/snapshot.yml

[start_time:Wed, 6 Jul 2022 00:15:11 GMT, release_branch:master, prefix:, end_time:Wed, 6 Jul 2022 05:19:25 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-d0a4da44, build_duration_seconds:18254]

[automation] update elastic stack version for testing 8.4.0-d0a4da44

---

testing/environments/snapshot.yml

[start_time:Wed, 6 Jul 2022 12:14:54 GMT, release_branch:8.3, prefix:, end_time:Wed, 6 Jul 2022 17:32:26 GMT, manifest_version:2.1.0, version:8.3.2-SNAPSHOT, branch:8.3, build_id:8.3.2-97fdd78b, build_duration_seconds:19052]

[automation] update elastic stack version for testing 8.3.2-97fdd78b

---

CHANGELOG-developer.next.asciidoc
dev-tools/mage/build.go

This reverts commit a7871690d2b1559c7dd06240cd23d94069d64d76.
This change unexpectedly breaks the packaging step on Mac. Reverting until we can find a cross-platform solution or just make these flags a Linux only option.

Revert "Fix flags for dev build (#31955)"

---

CHANGELOG.asciidoc
CHANGELOG.next.asciidoc
libbeat/docs/release.asciidoc

docs: Prepare Changelog for 8.3.2

---

.github/workflows/macos-xpack-osquerybeat.yml
.github/workflows/macos-xpack-packetbeat.yml
.github/workflows/opentelemetry.yml

Export GitHub actions execution as OpenTelemetry traces
This will help to gather insights and contribute to the GitHub action that empowers this functionality.
I also additionally, fixed some cosmetic changes in a couple of MacOS GitHub actions regarding their name and folder where to run the tests
Similar to https://github.com/elastic/apm-agent-nodejs/pull/2805
To ingest the test-data in a follow up. Since all the GitHub actions together won't work

github-action: export github actions telemetry traces

---

heartbeat/monitors/stdfields/unnest.go
heartbeat/monitors/stdfields/unnest_test.go
x-pack/heartbeat/monitors/browser/synthexec/enrich.go

Fixes https://github.com/elastic/beats/issues/32224 by using the nested stream ID when stream 'origin' field is present. This distinguishes between monitor management monitors and original fleet integration monitors.
This also cleans up the nests for the unnest code, covering more and making them easier to parse.
No changelog since this is only an internal feature related to monitor management
Use the following config in a file in `monitors.d`. Run with the below command
`mage build && env ELASTIC_SYNTHETICS_CAPABLE=true ./heartbeat -e`
```yaml
---
- id: root1
name: 2f629490-fd30-11ec-b3ce-af45fd6132f0-1
revision: 1
type: synthetics/http
use_output: default
meta:
package:
name: synthetics
version: 0.9.10
data_stream:
namespace: default
streams:
- id: stream1
name: Nest Test Root
type: …
```

[Heartbeat] Use stream ID for monitors with origin

---

CHANGELOG-developer.next.asciidoc
dev-tools/mage/build.go
dev-tools/mage/crossbuild.go

This is a work around for https://github.com/elastic/golang-crossbuild/issues/217 where the package target is broken when setting `DEV=1` with the Go 1.17.11 crossbuild image.
I have also un-reverted the change for https://github.com/elastic/beats/pull/31955 since it was not actually the root cause. It does not cause any issues when tested locally using the Go 1.17.10 image that is known to work.

Force DEV=0 when cross-compiling to darwin/amd64

---

testing/environments/snapshot.yml

[start_time:Mon, 11 Jul 2022 00:15:20 GMT, release_branch:8.3, prefix:, end_time:Mon, 11 Jul 2022 04:59:34 GMT, manifest_version:2.1.0, version:8.3.3-SNAPSHOT, branch:8.3, build_id:8.3.3-385d4fdb, build_duration_seconds:17054]

[automation] update elastic stack version for testing 8.3.3-385d4fdb

---

testing/environments/snapshot.yml

[start_time:Sun, 10 Jul 2022 12:14:29 GMT, release_branch:master, prefix:, end_time:Sun, 10 Jul 2022 16:52:30 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-dd98ded4, build_duration_seconds:16681]

[automation] update elastic stack version for testing 8.4.0-dd98ded4

---

x-pack/filebeat/input/default-inputs/inputs.go

This is currently breaking the 7.17 build with filebeat refusing to start for some tests.
This appears to have been introduced in https://github.com/elastic/beats/commit/d593a21503aa3e1dafb0c5a01d3991065db2b22a, I suspect a bad conflict resolution during the backport.
It seems filebeat deadlocks when it tries to panic and report the error in this case, hiding the cause of the issue:
https://github.com/elastic/beats/blob/cad3c7f951e55221712b96a2b32461c09c426e27/filebeat/beater/filebeat.go#L288-L290
I'll open a separate issue for that problem if I can't find the root cause.

Remove extra s3 input registration from x-pack/filebeat default inputs.

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Mon, 11 Jul 2022 05:13:45 GMT, release_branch:7.17, prefix:, end_time:Mon, 11 Jul 2022 10:06:34 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-cff0caa9, build_duration_seconds:17569]

[automation] update elastic stack version for testing 7.17.6-cff0caa9

---

testing/environments/snapshot.yml

[start_time:Tue, 12 Jul 2022 00:14:47 GMT, release_branch:8.3, prefix:, end_time:Tue, 12 Jul 2022 04:33:00 GMT, manifest_version:2.1.0, version:8.3.3-SNAPSHOT, branch:8.3, build_id:8.3.3-46b07667, build_duration_seconds:15493]

[automation] update elastic stack version for testing 8.3.3-46b07667

---

testing/environments/snapshot.yml

[start_time:Mon, 11 Jul 2022 12:15:42 GMT, release_branch:master, prefix:, end_time:Mon, 11 Jul 2022 16:53:35 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-164d9a10, build_duration_seconds:16673]

[automation] update elastic stack version for testing 8.4.0-164d9a10

---

libbeat/tests/system/beat/beat.py

This PR is to add the missing `WaitTimeoutError` class definition in beat.py.

[7.17] Add missing WaitTimeoutError definition

---

CHANGELOG.next.asciidoc
filebeat/input/filestream/internal/input-logfile/input.go
filebeat/input/filestream/internal/input-logfile/manager.go
filebeat/input/v2/compat/compat.go
filebeat/tests/system/test_reload_inputs.py
libbeat/cfgfile/list.go

This PR fixes three race conditions:
1. When reloading inputs the Reload method would not wait for the
runner to stop before starting a new input.
2. The runner's Start method was not incrementing the WaitGroup, hence
Stop would finish before the runner had stopped.
3. The input manager that keeps track of filestream input IDs did not
syncronise access to the IDs map, allowing for some race conditions
when issuing the log error about possible data duplucation.
Some log messages have been modified to contain more details like the
filestream ID.
It fixes some bugs.
- Relates …

fix race condition when stopping inputs filestream ID bookkeeper

---

testing/environments/snapshot.yml

[start_time:Tue, 12 Jul 2022 12:14:45 GMT, release_branch:master, prefix:, end_time:Tue, 12 Jul 2022 16:51:42 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-00048b66, build_duration_seconds:16617]

[automation] update elastic stack version for testing 8.4.0-00048b66

---

testing/environments/snapshot.yml

[start_time:Thu, 14 Jul 2022 00:14:48 GMT, release_branch:8.3, prefix:, end_time:Thu, 14 Jul 2022 04:31:09 GMT, manifest_version:2.1.0, version:8.3.3-SNAPSHOT, branch:8.3, build_id:8.3.3-fba30f71, build_duration_seconds:15381]

[automation] update elastic stack version for testing 8.3.3-fba30f71

---

x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
x-pack/filebeat/input/httpjson/chain.go
x-pack/filebeat/input/httpjson/config.go
x-pack/filebeat/input/httpjson/config_request.go
x-pack/filebeat/input/httpjson/input.go
x-pack/filebeat/input/httpjson/policy.go
x-pack/filebeat/input/httpjson/policy_test.go
x-pack/filebeat/input/httpjson/request.go
x-pack/filebeat/input/httpjson/request_chain_helper.go
x-pack/filebeat/input/httpjson/request_chain_helper_test.go
x-pack/filebeat/input/httpjson/request_test.go
x-pack/filebeat/input/httpjson/response.go
x-pack/filebeat/input/httpjson/value_tpl.go

1.  Introduced new request chain step **'while'** to tackle scenarios as reported in this ticket : #29959 
2.  Added support for creation of of new http client per step in the request chain , thereby enabling individual steps to 
take advantage of unique auth's per step if required and access to all request parameters. This also helps solve the issue 
in the ticket : #31117. 
**[Note] : if an auth per step is not defined , the steps shall inherit  any auth that is used in the root request call.**
3.  Added an improvement which now removes the requirement for **request.retry.wait_max** field to be specified everywhere 
even when it is not required. Now you can simply specify **request.retry.wait_min** for the retry config and the wait will occur. 
You can still specify both fields ..when …

[elastic/beats] [HttpJson] - Improves request chaining with new 'while' step & client creation per step 

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Wed, 13 Jul 2022 05:14:06 GMT, release_branch:7.17, prefix:, end_time:Wed, 13 Jul 2022 10:08:24 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-a62286d6, build_duration_seconds:17658]

[automation] update elastic stack version for testing 7.17.6-a62286d6

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Thu, 14 Jul 2022 05:13:59 GMT, release_branch:7.17, prefix:, end_time:Thu, 14 Jul 2022 10:07:25 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-75df96d4, build_duration_seconds:17606]

[automation] update elastic stack version for testing 7.17.6-75df96d4

---

testing/environments/snapshot.yml

[start_time:Thu, 14 Jul 2022 12:18:37 GMT, release_branch:8.3, prefix:, end_time:Thu, 14 Jul 2022 17:06:49 GMT, manifest_version:2.1.0, version:8.3.3-SNAPSHOT, branch:8.3, build_id:8.3.3-f93ba5f4, build_duration_seconds:17292]

[automation] update elastic stack version for testing 8.3.3-f93ba5f4

---

testing/environments/snapshot.yml

[start_time:Mon, 18 Jul 2022 00:14:58 GMT, release_branch:master, prefix:, end_time:Mon, 18 Jul 2022 05:00:16 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-a324b98b, build_duration_seconds:17118]

[automation] update elastic stack version for testing 8.4.0-a324b98b

---

testing/environments/snapshot.yml

[start_time:Mon, 18 Jul 2022 00:14:17 GMT, release_branch:8.3, prefix:, end_time:Mon, 18 Jul 2022 04:33:35 GMT, manifest_version:2.1.0, version:8.3.3-SNAPSHOT, branch:8.3, build_id:8.3.3-99553f72, build_duration_seconds:15558]

[automation] update elastic stack version for testing 8.3.3-99553f72

---

metricbeat/Jenkinsfile.yml
packetbeat/Jenkinsfile.yml
winlogbeat/Jenkinsfile.yml
x-pack/auditbeat/Jenkinsfile.yml
x-pack/elastic-agent/Jenkinsfile.yml
x-pack/filebeat/Jenkinsfile.yml
x-pack/functionbeat/Jenkinsfile.yml
x-pack/metricbeat/Jenkinsfile.yml
x-pack/osquerybeat/Jenkinsfile.yml
x-pack/packetbeat/Jenkinsfile.yml
x-pack/winlogbeat/Jenkinsfile.yml

Disable windows-2008-r2 builds as they fail setup, example: https://github.com/elastic/beats/issues/32327. We haven't had a successful 7.17 build in weeks.
Windows 2008 R2 is EOL, and is the same underlying OS as Windows 7 which for some reason still works.
Removing it from the build while we work out how to fix the setup issues. Ideally we would remove EOL releases from the support matrix but that can't be done as quickly as removing it from the test targets. Windows 2008 was already disabled for several beats.
It is highly unlikely someone is still using this Windows version and submitting support cases. Product telemetry shows zero Windows 7 users for example.

Disable the EOL Windows 2008 r2 in 7.17 to fix build

---

testing/environments/snapshot.yml

[start_time:Mon, 18 Jul 2022 12:14:36 GMT, release_branch:8.3, prefix:, end_time:Mon, 18 Jul 2022 16:38:07 GMT, manifest_version:2.1.0, version:8.3.3-SNAPSHOT, branch:8.3, build_id:8.3.3-302be7c1, build_duration_seconds:15811]

[automation] update elastic stack version for testing 8.3.3-302be7c1

---

testing/environments/snapshot.yml

[start_time:Tue, 19 Jul 2022 00:18:08 GMT, release_branch:master, prefix:, end_time:Tue, 19 Jul 2022 04:40:25 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-31315ca3, build_duration_seconds:15737]

[automation] update elastic stack version for testing 8.4.0-31315ca3

---

CHANGELOG.next.asciidoc
auditbeat/docs/modules/auditd.asciidoc
auditbeat/module/auditd/_meta/docs.asciidoc
auditbeat/module/auditd/audit_linux.go
auditbeat/module/auditd/audit_linux_test.go
auditbeat/module/auditd/config_linux.go
auditbeat/module/auditd/config_linux_test.go
auditbeat/module/auditd/golden_files_test.go
auditbeat/module/auditd/mock_linux_test.go

Adds the immutable option to lock the audit config.
Closes #8352

[auditbeat] Add the immutable option to auditd module

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Tue, 19 Jul 2022 05:14:41 GMT, release_branch:7.17, prefix:, end_time:Tue, 19 Jul 2022 10:01:59 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-0f95e383, build_duration_seconds:17238]

[automation] update elastic stack version for testing 7.17.6-0f95e383

---

testing/environments/snapshot.yml

[start_time:Wed, 20 Jul 2022 00:15:17 GMT, release_branch:8.3, prefix:, end_time:Wed, 20 Jul 2022 04:42:43 GMT, manifest_version:2.1.0, version:8.3.3-SNAPSHOT, branch:8.3, build_id:8.3.3-e5bc7e69, build_duration_seconds:16046]

[automation] update elastic stack version for testing 8.3.3-e5bc7e69

---

testing/environments/snapshot.yml

[start_time:Tue, 19 Jul 2022 12:14:18 GMT, release_branch:master, prefix:, end_time:Tue, 19 Jul 2022 16:59:58 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-31269fd2, build_duration_seconds:17140]

[automation] update elastic stack version for testing 8.4.0-31269fd2

---

auditbeat/Jenkinsfile.yml
filebeat/Jenkinsfile.yml
heartbeat/Jenkinsfile.yml
metricbeat/Jenkinsfile.yml
packetbeat/Jenkinsfile.yml
x-pack/auditbeat/Jenkinsfile.yml
x-pack/filebeat/Jenkinsfile.yml
x-pack/functionbeat/Jenkinsfile.yml
x-pack/heartbeat/Jenkinsfile.yml
x-pack/metricbeat/Jenkinsfile.yml
x-pack/osquerybeat/Jenkinsfile.yml
x-pack/packetbeat/Jenkinsfile.yml

No more `poc` labels and use `macos12`

ci: use monterey orka labels

---

filebeat/docs/include/cisco-log-level.asciidoc
filebeat/docs/modules-overview.asciidoc
filebeat/docs/modules/cisco.asciidoc
x-pack/filebeat/module/cisco/_meta/docs.asciidoc

Filebeat module documentation now make it clear that ingest pipelines
are not automatically reloaded automatically.
The Cisco module documentation is also updated making it explicity the
log level filtering is done in the ingest pipeline.
It makes the current behaviour more clear
1. Clone [bea](https://github.com/elastic/beats) and [docs](https://github.com/elastic/docs) on the same folder
2. Change the directory to …

Update Filebeat modules documentation

---

x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go

Fix AWS cloudwatch metricset `readCloudwatchConfig` function to construct resource types with tags.

[AWS] Fix CloudWatch readCloudwatchConfig function

---

CHANGELOG.next.asciidoc
filebeat/docs/modules/system.asciidoc
filebeat/module/system/_meta/docs.asciidoc
filebeat/module/system/auth/config/auth.yml
filebeat/module/system/auth/ingest/pipeline.yml
filebeat/module/system/auth/manifest.yml
filebeat/module/system/auth/test/auth-ubuntu1204.log-expected.json
filebeat/module/system/auth/test/secure-rhel7.log-expected.json
filebeat/module/system/auth/test/test.log-expected.json

Sync the pipeline for the system.auth dataset with the Fleet integration
from https://github.com/elastic/integrations/pull/3705.
This removes the event.type authentication_failed and authentication_success
values which are not allowed as per ECS. You can use event.category: authentication
and event.outcome: success/failure to query instead.
This should make the pipeline more efficient and it aligns the event.type field to ECS.
- Relates [#123](https://github.com/elastic/integrations/pull/3705)

system.auth - sync pipeline with Fleet integration

---

CHANGELOG.next.asciidoc
NOTICE.txt
go.mod
go.sum

Upgraded github.com/elastic/go-libaudit/v2 v2.3.1-0.20220629014624-b10731ae427c => v2.3.1
See https://github.com/elastic/go-libaudit/releases/tag/v2.3.1.
Fixes issues in Auditbeat.
- auditd module: Fix parsing of audit rules where arguments are quoted (like file paths containing spaces).
- auditd module: Fix minimum AuditStatus length so that library can support kernels from 2.6.32.

[Auditbeat] Upgrade to go-libaudit v2.3.1

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Wed, 20 Jul 2022 05:13:57 GMT, release_branch:7.17, prefix:, end_time:Wed, 20 Jul 2022 10:01:26 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-7ad6b445, build_duration_seconds:17249]

[automation] update elastic stack version for testing 7.17.6-7ad6b445

---

CHANGELOG.next.asciidoc
libbeat/autodiscover/autodiscover_test.go
libbeat/cfgfile/list.go

This commit fixes the race condition introduced by
f3d1010029d436807c9cc90234c79e724cfe3f39 that aimed to fix some race
conditions.
A test has its logging updated to use t.Log, so it only logs when
verbosity is on and test line issuing the log is also shown.
Some t.Helper() calls are also added.
It fixes a bug
~~- [x] I have made corresponding changes to the documentation~~
~~- [x] I have made corresponding change to the default configuration files~~
~~- [x] I have added tests that prove my fix is effective or that my feature works~~
`TestAutodiscoverWithMutlipleEntries` from `libbeat/autodiscover/autodiscover_test.go` fails intermittently if the bug is not fixed. A set of 5 consecutive runs always triggered the bug for me. So to verify the fix, just run that …

Fix race condition when reloading configuration

---

packetbeat/Jenkinsfile.yml
x-pack/packetbeat/Jenkinsfile.yml

Enable Windows-11 for Packetbeat from 8.3+
See https://github.com/elastic/beats/pull/32237#issuecomment-1180545472

ci: add support for windows-11 in packetbeat

---

filebeat/docs/filebeat-options.asciidoc
filebeat/docs/inputs/input-filestream.asciidoc

I noticed looking at the filebeat documentation that we can improve how we guide users to the filestream input, and also further improve the callouts noting that filestream input IDs are mandatory.
I switched the default filestream example inputs [here](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-filebeat-options.html) from `log` to `filestream` and also added a note on the `log` input link that it is deprecated.
I also added some more warnings and notes about filestream IDs being required in the first locations users are likely to see a filestream configuration.

Add warning about filestream duplication without unique IDs in documentation

---

.github/workflows/macos-auditbeat.yml
.github/workflows/macos-filebeat.yml
.github/workflows/macos-heartbeat.yml
.github/workflows/macos-metricbeat.yml
.github/workflows/macos-packetbeat.yml
.github/workflows/macos-xpack-auditbeat.yml
.github/workflows/macos-xpack-filebeat.yml
.github/workflows/macos-xpack-functionbeat.yml
.github/workflows/macos-xpack-heartbeat.yml
.github/workflows/macos-xpack-metricbeat.yml
.github/workflows/macos-xpack-osquerybeat.yml
.github/workflows/macos-xpack-packetbeat.yml

Report test results as opentelemetry traces.
This is the last part after merging https://github.com/elastic/beats/pull/32256
With this proposal there will be as many spans as executed tests under the `Run test` span

actions: report test result as opentelemetry traces

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Thu, 21 Jul 2022 05:14:05 GMT, release_branch:7.17, prefix:, end_time:Thu, 21 Jul 2022 10:07:27 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-9675035b, build_duration_seconds:17602]

[automation] update elastic stack version for testing 7.17.6-9675035b

---

dev-tools/packaging/templates/ironbank/elastic-agent/Dockerfile
dev-tools/packaging/templates/ironbank/elastic-agent/README.md
dev-tools/packaging/templates/ironbank/elastic-agent/hardening_manifest.yaml
x-pack/elastic-agent/magefile.go

Automate the ironbank docker context generation so the Unified RElease process can consume it.
Follow up https://github.com/elastic/elastic-agent/pull/679 and https://github.com/elastic/beats/pull/32251

ironbank: support for elastic-agent in 7.17

---

auditbeat/auditbeat.reference.yml
filebeat/filebeat.reference.yml
heartbeat/heartbeat.reference.yml
libbeat/_meta/config/output-kafka.reference.yml.tmpl
metricbeat/metricbeat.reference.yml
packetbeat/packetbeat.reference.yml
winlogbeat/winlogbeat.reference.yml
x-pack/auditbeat/auditbeat.reference.yml
x-pack/filebeat/filebeat.reference.yml
x-pack/heartbeat/heartbeat.reference.yml
x-pack/metricbeat/metricbeat.reference.yml
x-pack/packetbeat/packetbeat.reference.yml
x-pack/winlogbeat/winlogbeat.reference.yml

Follow up from https://github.com/elastic/beats/pull/31978 where the worker documentation was removed but the setting was not removed from the reference configuration file.
Quoting the original reasoning for removing this:
> - Relates #4492: Before this PR, the `worker` setting was used to create multiple `sarama.AsyncProducer`. After it, the `worker` setting only makes [`hosts` entries duplicated](https://github.com/elastic/beats/blob/7102be4e5594f158c2b80ff075246d5eab94bebe/libbeat/outputs/hosts.go#L43-L43) for [calling `sarama.NewAsyncProducer`](https://github.com/elastic/beats/blob/7102be4e5594f158c2b80ff075246d5eab94bebe/libbeat/outputs/kafka/client.go#L123-L123), which does not have any positive effect, but a little overhead for [metadata …

Remove Kafka worker from reference config.

---

CHANGELOG.next.asciidoc
libbeat/processors/decode_xml_wineventlog/docs/decode_xml_wineventlog.asciidoc

Documents the field mappings for the `decode_xml_wineventlog` processor.
Needed so users will know what fields will be populated so they can filter on them in Conditionals or Logstash.

document how decode_xml_wineventlog maps fields

---

NOTICE.txt
go.mod
go.sum

https://github.com/elastic/beats/issues/32467 was introduced in v0.4.3. This removes the problematic code from beats while we work on a fix in the system metrics package.

Downgrade elastic-agent-system-metrics to v0.4.2.

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Sun, 24 Jul 2022 05:13:46 GMT, release_branch:7.17, prefix:, end_time:Sun, 24 Jul 2022 10:09:03 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-964edfea, build_duration_seconds:17717]

[automation] update elastic stack version for testing 7.17.6-964edfea

---

CHANGELOG.next.asciidoc
x-pack/auditbeat/module/system/socket/helper/linkedlist.go
x-pack/auditbeat/module/system/socket/helper/linkedlist_test.go
x-pack/auditbeat/module/system/socket/state.go
x-pack/auditbeat/module/system/socket/state_test.go

This PR modifies the socket dataset so that it is affected by output backpressure.
Originally, it operated as two separate goroutines. One would read kernel tracing events as fast as possible and maintain a view of the open sockets/flows on the system. Once a flow is deemed terminated, it would be stored on a linked list (`done`) for it to be published to the output.
A separate goroutine consumes that linked list and publishes the flows.
Under heavy network load, it can generate flows faster than the output is able to accept. Due to the linked list being unbounded, it would store more and more flows, causing Auditbeat's memory usage to grow over time.
This PR simplifies flow publication in such a way that if the output blocks, the main reader goroutine will block too, preventing the …

system/socket: propagate backpressure from output

---

testing/environments/snapshot.yml

[start_time:Tue, 26 Jul 2022 00:14:32 GMT, release_branch:8.3, prefix:, end_time:Tue, 26 Jul 2022 04:44:23 GMT, manifest_version:2.1.0, version:8.3.3-SNAPSHOT, branch:8.3, build_id:8.3.3-d520d440, build_duration_seconds:16191]

[automation] update elastic stack version for testing 8.3.3-d520d440

---

x-pack/auditbeat/module/system/socket/helper/linkedlist.go
x-pack/auditbeat/module/system/socket/helper/linkedlist_test.go

Sets Go's build flags in Auditbeat's system/socket dataset linked-list test so that it only runs under Linux (as the rest of the dataset).
The linkedlist zero-allocation checks are failing under Win10 & Win11 because one allocation is being reported.
- Closes #32483

Auditbeat socket: Do not run socket allocation tests under Windows

---

x-pack/auditbeat/Jenkinsfile.yml

As long as there are test failures for windows-10 and windows-11 in the x-pack/auditbeat then let's disable to use them
Temporary fix until the team fixes the real issue with the windows-10/windows-11
Test failure tracked https://github.com/elastic/beats/issues/32499

ci: disable windows-10/windows-11 for x-pack/auditbeat

---

x-pack/auditbeat/Jenkinsfile.yml

This reverts commit 95238c88c2f06bddcc65d70411c9cdba6b72f58e (#32500).
It's not necessary to disable win10/11 for x-pack/auditbeat as the underlying issue was fixed in #32501.

Revert "ci: disable windows-10/windows-11 for x-pack/auditbeat (#32500)"

---

auditbeat/docs/modules/auditd.asciidoc
auditbeat/module/auditd/_meta/docs.asciidoc
auditbeat/module/auditd/audit_linux.go
auditbeat/module/auditd/audit_linux_test.go
auditbeat/module/auditd/golden_files_test.go

If auditd config is locked and the immutable option is set, all the configuration setup is ignored to be able to resume events processing onces the pid is changed.
This way auditbeat can be stopped and restarted without requiring a system restart as far as the configuration does not need to change.
Chnagelog not added since this is modifying a feature added for 8.4 that is still not released.

[auditbeat] Make auditbeat resumeable when config is locked and immutable is set

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Tue, 26 Jul 2022 05:13:59 GMT, release_branch:7.17, prefix:, end_time:Tue, 26 Jul 2022 10:06:22 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-3f4b9bc6, build_duration_seconds:17543]

[automation] update elastic stack version for testing 7.17.6-3f4b9bc6

---

testing/environments/snapshot.yml

[start_time:Wed, 27 Jul 2022 07:02:31 GMT, release_branch:master, prefix:, end_time:Wed, 27 Jul 2022 12:07:51 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-60171339, build_duration_seconds:18320]

[automation] update elastic stack version for testing 8.4.0-60171339

---

testing/environments/snapshot.yml

[start_time:Wed, 27 Jul 2022 07:09:19 GMT, release_branch:8.3, prefix:, end_time:Wed, 27 Jul 2022 13:37:37 GMT, manifest_version:2.1.0, version:8.3.3-SNAPSHOT, branch:8.3, build_id:8.3.3-8631d33c, build_duration_seconds:23298]

[automation] update elastic stack version for testing 8.3.3-8631d33c

---

metricbeat/docker-compose.yml
testing/environments/latest.yml
x-pack/metricbeat/docker-compose.yml

Merge only after the release of 8.3.3.

[Release] Update test environments for 8.3.4

---

CHANGELOG.next.asciidoc
NOTICE.txt
go.mod
go.sum
x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
x-pack/filebeat/input/httpjson/config_request.go
x-pack/filebeat/input/httpjson/input.go
x-pack/filebeat/input/httpjson/internal/httplog/roundtripper.go
x-pack/filebeat/input/httpjson/rate_limiter.go
x-pack/filebeat/input/httpjson/request.go

x-pack/filebeat/input/httpjson: add transaction tracer

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Thu, 28 Jul 2022 05:15:40 GMT, release_branch:7.17, prefix:, end_time:Thu, 28 Jul 2022 10:19:37 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-b64de485, build_duration_seconds:18237]

[automation] update elastic stack version for testing 7.17.6-b64de485

---

testing/environments/snapshot.yml

[start_time:Thu, 28 Jul 2022 00:16:16 GMT, release_branch:8.3, prefix:, end_time:Thu, 28 Jul 2022 10:10:15 GMT, manifest_version:2.1.0, version:8.3.3-SNAPSHOT, branch:8.3, build_id:8.3.3-326db639, build_duration_seconds:35639]

[automation] update elastic stack version for testing 8.3.3-326db639

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Fri, 29 Jul 2022 05:15:28 GMT, release_branch:7.17, prefix:, end_time:Fri, 29 Jul 2022 10:17:24 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-74b6df3e, build_duration_seconds:18116]

[automation] update elastic stack version for testing 7.17.6-74b6df3e

---

x-pack/osquerybeat/internal/config/config.go
x-pack/osquerybeat/internal/pub/publisher.go

Adds the ```add_data_stream``` processors that appends the ```data_stream``` fields to the events. This enabled better compatibility with the logstash configuration allowing it to figure out the destination datastream for the results of the osquery.
Better support osquery with logstash as the output.
Here is an example logstash pipeline configuration that was not working before this change:
```
input {
elastic_agent {
port => 5044
ssl => true
ssl_certificate_authorities => ["certs/ca/ca.crt"]
ssl_certificate => "certs/logstash.crt"
ssl_key =>  "certs/logstash.pkcs8.key"
ssl_verify_mode => "force_peer"
}
}
filter {
mutate {
rename => ["_host", "host" ]
}
}
output {
elasticsearch {
hosts => "https://<redacted>.us-west2.gcp.elastic-cloud.com:443"
data_stream => true
ssl => true
user => …
```

Osquerybeat: Add missing data_stream to events in order to support logstash configuration better

---

x-pack/osquerybeat/internal/distro/distro.go

Upgrade osquery to version 5.4.0.
Pick up the latest updates and fixes implemented in osquery 5.4.0. 
Specifically this release addressed the issue we had to work around:
- Fix thrift server shutting down when dropping privileges ([#7639](https://github.com/osquery/osquery/pull/7639))
And has the new table that we implemented awhile ago:
- New Table: `windows_update_history` ([#7407](https://github.com/osquery/osquery/pull/7407))
- Closes https://github.com/elastic/security-team/issues/4191
Running osquery 5.4.0 on MacOS:

Osquerybeat: Upgrade osquery to version 5.4.0

---

CHANGELOG.next.asciidoc
heartbeat/config/config.go
heartbeat/scheduler/schedjob_test.go
heartbeat/scheduler/scheduler.go
heartbeat/scheduler/scheduler_test.go

Fixes #32082 by limiting browser jobs to 2. Users can still override this with the global `heartbeat.jobs.browser.limit: 42`.
This also fixes a previously unknown bug, where changing the `heartbeat.jobs.*.limit` values would cause heartbeat to crash with a panic. This appears to be a bug in`go-ucfg`. The workaround this PR adds is moving from `map[string]JobLimit` to `map[string]*JobLimit`, which doesn't trigger the same reflection issues.
The new log message should help confirm this works. It's kind of hard to test perfectly otherwise, but we don't need to add new tests for the job limit system.

[Heartbeat] Limit browser jobs to 2 by default

---

Jenkinsfile

It uses Beats profile when running the E2E test
The Beats profile in the E2E only runs those scenarios that are related to changes in Beats, like running the agent in top of filebeat/metricbeat, to name one.
- Discovered while testing https://github.com/elastic/beats/pull/32528

fix: use beats profile when running the e2e for Beats PRs

---

testing/environments/snapshot.yml

[start_time:Mon, 1 Aug 2022 12:16:15 GMT, release_branch:master, prefix:, end_time:Mon, 1 Aug 2022 17:55:48 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-c54c3404, build_duration_seconds:20373]

[automation] update elastic stack version for testing 8.5.0-c54c3404

---

testing/environments/snapshot.yml

[start_time:Tue, 2 Aug 2022 00:18:09 GMT, release_branch:8.3, prefix:, end_time:Tue, 2 Aug 2022 04:56:14 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-9c50d4cb, build_duration_seconds:16685]

[automation] update elastic stack version for testing 8.3.4-9c50d4cb

---

testing/environments/snapshot.yml

[start_time:Tue, 2 Aug 2022 00:15:42 GMT, release_branch:master, prefix:, end_time:Tue, 2 Aug 2022 05:41:40 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-7dbc10f8, build_duration_seconds:19558]

[automation] update elastic stack version for testing 8.5.0-7dbc10f8

---

CHANGELOG.next.asciidoc
NOTICE.txt
go.mod
go.sum

Signed-off-by: Florian Lehner <florian.lehner@elastic.co>
Update the dependency `elastic/go-structform` from `v0.0.9` to `v0.0.10`.
The dependency `elastic/go-structform` is used indirectly by the beats via `elastic/beats/libbeat`. [v0.0.10](https://github.com/elastic/go-structform/commit/54c82b302f9adce354ec9b51abe9cef3bd4245ca) of `elastic/go-structform` includes changes to reduce the memory footprint and so does have an positive effect also on all beats.
PR does not introduce code changes.
PR does not introduce code changes.
PR does not introduce code changes.
No configuration changes with this PR.
PR does not introduce code changes.

update dependency elastic/go-structform from v0.0.9 to v0.0.10

---

CHANGELOG.next.asciidoc
dev-tools/mage/crossbuild.go

After a considerable amount of googling and `strace` yesterday, I learned that there's a bug in certain older versions of `apt-get` in debian, where it'll try to iterate through all possible FDs as set by internal linux system limits. This results in some amusing `strace` output:
```
fcntl(337334262, F_SETFD, FD_CLOEXEC)    = -1 EBADF (Bad file descriptor)
```
This only happens on certain docker installs where the docker daemon won't set the `NOFILE` ulimit in its containers. 
This fix just adds a `ulimit` flag to the docker invocation when needed.
On systems that hit this bug, `mage package` on filebeat can take up to an hour, purely due to the `apt-get update` operation.

Add ulimit setting to debian containers in mage build

---

dev-tools/mage/crossbuild.go

Follow-up of #32580 
Note to self: if you're going to change something, test it, and then change something else, test it again.

Fix string used to check image name in crossbuild

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml
x-pack/elastic-agent/pkg/artifact/download/http/downloader_test.go

[start_time:Tue, 2 Aug 2022 15:16:53 GMT, release_branch:7.17, prefix:, end_time:Tue, 2 Aug 2022 20:05:56 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-02b91d00, build_duration_seconds:17343]

[automation] update elastic stack version for testing 7.17.6-02b91d00

---

filebeat/docs/getting-started.asciidoc
filebeat/docs/include/configuring-intro.asciidoc
libbeat/docs/release-notes/breaking/breaking-8.0.asciidoc

* Edit the explanation about enabling datasets. Changes the term "dataset" to "fileset" to be consistent with terminology used throughout the Filebeat Reference. If "dataset" is prefered over "fileset," we must change it across all the Filebeat docs.
* Update the wording to match https://github.com/elastic/observability-docs/pull/2053. I'm trying to be explicit here so users know that they must enable at least one fileset.
* Update shared text so that the docs about configuring each module indicate that users must enable at least one module.
Related to https://github.com/elastic/observability-docs/issues/1043.

Clarify that at least one fileset must be enabled in a filebeat

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Wed, 3 Aug 2022 05:15:11 GMT, release_branch:7.17, prefix:, end_time:Wed, 3 Aug 2022 10:41:27 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-308858b9, build_duration_seconds:19576]

[automation] update elastic stack version for testing 7.17.6-308858b9

---

testing/environments/snapshot.yml

[start_time:Wed, 3 Aug 2022 12:18:18 GMT, release_branch:8.3, prefix:, end_time:Wed, 3 Aug 2022 16:32:35 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-ce266bfe, build_duration_seconds:15257]

[automation] update elastic stack version for testing 8.3.4-ce266bfe

---

metricbeat/docker-compose.yml
testing/environments/snapshot.yml

[start_time:Mon, 1 Aug 2022 00:17:44 GMT, release_branch:8.4, prefix:, end_time:Mon, 1 Aug 2022 05:27:02 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-5954f776, build_duration_seconds:18558]
- Closes #32525

[automation] update elastic stack version for testing 8.4.0-5954f776

---

NOTICE.txt
go.mod
go.sum

auditd: Reduce allocations when converting bytes to strings for received messages. [#116](https://github.com/elastic/go-libaudit/pull/116)

[Auditbeat] Upgrade go-libaudit@f8f7d5c

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Thu, 4 Aug 2022 05:15:39 GMT, release_branch:7.17, prefix:, end_time:Thu, 4 Aug 2022 10:00:06 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-39f8da8e, build_duration_seconds:17067]

[automation] update elastic stack version for testing 7.17.6-39f8da8e

---

testing/environments/snapshot.yml

[start_time:Thu, 4 Aug 2022 12:15:38 GMT, release_branch:8.4, prefix:, end_time:Thu, 4 Aug 2022 17:41:18 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-43c061d1, build_duration_seconds:19540]

[automation] update elastic stack version for testing 8.4.0-43c061d1

---

testing/environments/snapshot.yml

[start_time:Thu, 4 Aug 2022 12:16:07 GMT, release_branch:8.3, prefix:, end_time:Thu, 4 Aug 2022 16:32:47 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-73c9af3c, build_duration_seconds:15400]

[automation] update elastic stack version for testing 8.3.4-73c9af3c

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Sat, 6 Aug 2022 05:15:07 GMT, release_branch:7.17, prefix:, end_time:Sat, 6 Aug 2022 10:06:25 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-49d2f2df, build_duration_seconds:17478]

[automation] update elastic stack version for testing 7.17.6-49d2f2df

---

testing/environments/snapshot.yml

[start_time:Sun, 7 Aug 2022 00:17:42 GMT, release_branch:8.4, prefix:, end_time:Sun, 7 Aug 2022 05:40:11 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-4b3e8f6e, build_duration_seconds:19349]

[automation] update elastic stack version for testing 8.4.0-4b3e8f6e

---

testing/environments/snapshot.yml

[start_time:Tue, 9 Aug 2022 00:16:04 GMT, release_branch:8.3, prefix:, end_time:Tue, 9 Aug 2022 04:43:07 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-fd43be48, build_duration_seconds:16023]

[automation] update elastic stack version for testing 8.3.4-fd43be48

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Mon, 8 Aug 2022 05:14:50 GMT, release_branch:7.17, prefix:, end_time:Mon, 8 Aug 2022 10:09:06 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-a65acb36, build_duration_seconds:17656]

[automation] update elastic stack version for testing 7.17.6-a65acb36

---

testing/environments/snapshot.yml

[start_time:Mon, 8 Aug 2022 12:15:06 GMT, release_branch:8.4, prefix:, end_time:Mon, 8 Aug 2022 17:58:03 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-96568c7b, build_duration_seconds:20577]

[automation] update elastic stack version for testing 8.4.0-96568c7b

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Tue, 9 Aug 2022 05:14:44 GMT, release_branch:7.17, prefix:, end_time:Tue, 9 Aug 2022 09:46:29 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-e11a9305, build_duration_seconds:16305]

[automation] update elastic stack version for testing 7.17.6-e11a9305

---

testing/environments/snapshot.yml

[start_time:Tue, 9 Aug 2022 12:15:41 GMT, release_branch:8.3, prefix:, end_time:Tue, 9 Aug 2022 17:00:53 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-b4aa6143, build_duration_seconds:17112]

[automation] update elastic stack version for testing 8.3.4-b4aa6143

---

testing/environments/snapshot.yml

[start_time:Tue, 9 Aug 2022 12:15:59 GMT, release_branch:master, prefix:, end_time:Tue, 9 Aug 2022 18:53:08 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-41aadc32, build_duration_seconds:23829]

[automation] update elastic stack version for testing 8.5.0-41aadc32

---

testing/environments/snapshot.yml

[start_time:Tue, 9 Aug 2022 12:17:46 GMT, release_branch:8.4, prefix:, end_time:Tue, 9 Aug 2022 17:58:06 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-9adc8090, build_duration_seconds:20420]

[automation] update elastic stack version for testing 8.4.0-9adc8090

---

dev-tools/kubernetes/Tiltfile
dev-tools/kubernetes/filebeat/Dockerfile.debug
dev-tools/kubernetes/filebeat/manifest.debug.yaml
dev-tools/kubernetes/metricbeat/Dockerfile.debug
dev-tools/kubernetes/metricbeat/manifest.debug.multi.yaml
dev-tools/kubernetes/metricbeat/manifest.debug.yaml

Remove memory limits on the pod metricbeat-debugger that caused the pod to crash. Also uses pod affinity to schedule the debugger on a specific node
We want to run multiple Metricbeat instances in normal run mode (oner per worker node), plus having a node that run a Metricbeat instance in debugger mode.
1. Run elastic stack locally with elastic-package stack up
2. Create a multinode Kind cluster with at least 2 worker nodes
3. Run `kubectl taint nodes <node_name> debugger=yes:NoSchedule` on one of the nodes
4. run `kubectl label nodes <name of node1> debugger=ok` 
5. From the folder dev-tools/kubernetes run tilt up to deploy Metricbeat in a multi node k8s cluster
6. Connect from your IDE to the remote debugger
7. Observer N metricbeat instances in Elastic correctly running and keep …

Fix debug mode for dev-tools/kubernetes

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Wed, 10 Aug 2022 05:14:53 GMT, release_branch:7.17, prefix:, end_time:Wed, 10 Aug 2022 10:13:18 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-9b06d311, build_duration_seconds:17905]

[automation] update elastic stack version for testing 7.17.6-9b06d311

---

testing/environments/snapshot.yml

[start_time:Wed, 10 Aug 2022 12:15:43 GMT, release_branch:8.4, prefix:, end_time:Wed, 10 Aug 2022 17:19:16 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-c17572db, build_duration_seconds:18213]

[automation] update elastic stack version for testing 8.4.0-c17572db

---

testing/environments/snapshot.yml

[start_time:Thu, 11 Aug 2022 00:18:58 GMT, release_branch:8.3, prefix:, end_time:Thu, 11 Aug 2022 04:58:12 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-a5e24e15, build_duration_seconds:16754]

[automation] update elastic stack version for testing 8.3.4-a5e24e15

---

testing/environments/snapshot.yml

[start_time:Wed, 10 Aug 2022 12:17:48 GMT, release_branch:master, prefix:, end_time:Wed, 10 Aug 2022 18:36:28 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-60a4c029, build_duration_seconds:22720]

[automation] update elastic stack version for testing 8.5.0-60a4c029

---

testing/environments/snapshot.yml

[start_time:Thu, 11 Aug 2022 12:17:23 GMT, release_branch:8.3, prefix:, end_time:Thu, 11 Aug 2022 16:55:27 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-adc3e57f, build_duration_seconds:16684]

[automation] update elastic stack version for testing 8.3.4-adc3e57f

---

packetbeat/beater/processor.go
packetbeat/sniffer/sniffer.go

This removes an unnecessary alway-nil error return on the `Sniffer.Stop` method. The method is not needed to satisfy an interface.
The code is not needed and adds complexity to the code base.
- Relates #32654

packetbeat/sniffer: remove unused error return on Sniffer.Stop

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Fri, 12 Aug 2022 05:14:52 GMT, release_branch:7.17, prefix:, end_time:Fri, 12 Aug 2022 10:07:22 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-efe703c7, build_duration_seconds:17550]

[automation] update elastic stack version for testing 7.17.6-efe703c7

---

testing/environments/snapshot.yml

[start_time:Sun, 14 Aug 2022 12:15:35 GMT, release_branch:8.4, prefix:, end_time:Sun, 14 Aug 2022 17:35:57 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-fea9abbe, build_duration_seconds:19222]

[automation] update elastic stack version for testing 8.4.0-fea9abbe

---

testing/environments/snapshot.yml

[start_time:Sun, 14 Aug 2022 12:23:06 GMT, release_branch:8.3, prefix:, end_time:Sun, 14 Aug 2022 18:07:08 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-6d6eaf28, build_duration_seconds:20642]

[automation] update elastic stack version for testing 8.3.4-6d6eaf28

---

metricbeat/module/kubernetes/util/metrics_repo_test.go

Fix a failing test for metrics_repo_test.go in the Kubernetes module
Fix a failing unit test
- Closes https://github.com/elastic/beats/issues/32671

fix bug for tests in metrics_repo_test.go

---

.mergify.yml

Add support to mergify to create 8.0.0 and 8.1.0 PRs 
PRs for backport for versions 8.0.0 and 8.1.0 are not created automaically

Update .mergify.yml with missing 8.1.0 backport

---

filebeat/beater/filebeat.go
libbeat/common/reload/reload.go
libbeat/common/reload/reload_test.go
metricbeat/beater/metricbeat.go

This change is related to https://github.com/elastic/beats/pull/32673
That PR is already fairly large, so this is an attempt to break it up by just doing the "make linter happy" changes in a separate PR, and then rebase the V2 support PR.

Run linter across some files that Will deal with the V2 agent update

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Mon, 15 Aug 2022 05:15:02 GMT, release_branch:7.17, prefix:, end_time:Mon, 15 Aug 2022 10:08:14 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-03b746cb, build_duration_seconds:17592]

[automation] update elastic stack version for testing 7.17.6-03b746cb

---

testing/environments/snapshot.yml

[start_time:Mon, 15 Aug 2022 00:15:30 GMT, release_branch:8.3, prefix:, end_time:Mon, 15 Aug 2022 05:10:35 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-58ddca7b, build_duration_seconds:17705]

[automation] update elastic stack version for testing 8.3.4-58ddca7b

---

testing/environments/snapshot.yml

[start_time:Mon, 15 Aug 2022 12:18:10 GMT, release_branch:8.4, prefix:, end_time:Mon, 15 Aug 2022 18:08:58 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-9bd354a1, build_duration_seconds:21048]

[automation] update elastic stack version for testing 8.4.0-9bd354a1

---

.mergify.yml

Reverts elastic/beats#32689
Non active branches should not have automated backports, so if it's required to backport any PRs, then it should be done manually or through the Mergify command, https://docs.mergify.com/commands/#backport
This was agreed sometime ago, when accidentally PRs were backported to old branches and those PRs were new features.

Revert "Update .mergify.yml with missing 8.1.0 backport"

---

.mergify.yml

Add a specific message so the backport policy is public available.
https://github.com/elastic/beats/pull/31104 remove the backport notification by default, but the backport policy is not explained and therefore https://github.com/elastic/beats/pull/32689 was created as a consequence.
Thanks @gsantoro for pointing about this

mergify: backport policy

---

CHANGELOG.next.asciidoc
x-pack/filebeat/input/gcppubsub/_meta/Dockerfile
x-pack/filebeat/input/gcppubsub/_meta/supported-versions.yml
x-pack/filebeat/input/gcppubsub/docker-compose.yml
x-pack/filebeat/input/gcppubsub/input.go

This modifies the gcp-pubsub input in Filebeat to include its own retry loop
rather than being entirely dependent upon the pub/sub client SDK to retry requests.
The input will only exit when the shutdown is triggered by Filebeat. Any errors
generated by the pub/sub client will be logged and then the input will restart the
pub/sub client. It will throttle restarts to once per 30s.
Fixes #32550
This improves the reliability of the pub/sub input by handling errors that are not retried by the pub/sub SDK.
- Fixes #32550
- Relates https://github.com/elastic/beats/pull/32713 (fixes linter issues)
```json
{
"log.level": "info",
"@timestamp": "2022-08-16T12:09:40.107-0400",
"log.logger": "gcp.pubsub",
"file.name": "gcppubsub/input.go",
"file.line": 142
},
"message": "Pub/Sub input …
```

[Filebeat] gcp-pubsub: Restart Pub/Sub client on errors

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Tue, 16 Aug 2022 05:16:47 GMT, release_branch:7.17, prefix:, end_time:Tue, 16 Aug 2022 11:09:30 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-202119fd, build_duration_seconds:21163]

[automation] update elastic stack version for testing 7.17.6-202119fd

---

x-pack/filebeat/input/gcppubsub/input.go

Remove github.com/pkg/errors from gcp-pubsub.  Use stdlib instead.
Also fixes two other linter issues.
```
Error: Error return value of `event.PutValue` is not checked (errcheck)
Error: SA1019: grpc.WithInsecure is deprecated: use WithTransportCredentials and insecure.NewCredentials() instead. Will be supported throughout 1.x.  (staticcheck)
```
The package is no longer maintained.

[Filebeat] gcp-pubsub: Remove github.com/pkg/errors

---

.mergify.yml

Remove support for automated backports to `8.2` using GitHub labels. It's still possible to use `@mergifyio backport 8.2` if needed
avoid accident backports

mergify remove 8.2 backports

---

testing/environments/snapshot.yml

[start_time:Wed, 17 Aug 2022 12:16:21 GMT, release_branch:8.3, prefix:, end_time:Wed, 17 Aug 2022 17:48:01 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-e23a59c6, build_duration_seconds:19900]

[automation] update elastic stack version for testing 8.3.4-e23a59c6

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Wed, 17 Aug 2022 05:15:42 GMT, release_branch:7.17, prefix:, end_time:Wed, 17 Aug 2022 10:13:30 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-091e6fb1, build_duration_seconds:17868]

[automation] update elastic stack version for testing 7.17.6-091e6fb1

---

testing/environments/snapshot.yml

[start_time:Wed, 17 Aug 2022 00:15:47 GMT, release_branch:8.4, prefix:, end_time:Wed, 17 Aug 2022 05:18:36 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-b95305c2, build_duration_seconds:18169]

[automation] update elastic stack version for testing 8.4.0-b95305c2

---

testing/environments/snapshot.yml

[start_time:Wed, 17 Aug 2022 12:18:02 GMT, release_branch:master, prefix:, end_time:Wed, 17 Aug 2022 20:19:44 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-6b9f92c0, build_duration_seconds:28902]

[automation] update elastic stack version for testing 8.5.0-6b9f92c0

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Sun, 21 Aug 2022 05:18:55 GMT, release_branch:7.17, prefix:, end_time:Sun, 21 Aug 2022 10:08:51 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-b8ca5a33, build_duration_seconds:17396]

[automation] update elastic stack version for testing 7.17.6-b8ca5a33

---

testing/environments/snapshot.yml

[start_time:Sun, 21 Aug 2022 00:18:06 GMT, release_branch:8.3, prefix:, end_time:Sun, 21 Aug 2022 05:20:42 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-70c0b53c, build_duration_seconds:18156]

[automation] update elastic stack version for testing 8.3.4-70c0b53c

---

testing/environments/snapshot.yml

[start_time:Sat, 20 Aug 2022 00:15:57 GMT, release_branch:master, prefix:, end_time:Sat, 20 Aug 2022 05:58:58 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-0616acda, build_duration_seconds:20581]

[automation] update elastic stack version for testing 8.5.0-0616acda

---

.github/workflows/check-packetbeat.yml
.github/workflows/check-xpack-packetbeat.yml
.github/workflows/opentelemetry.yml
packetbeat/Jenkinsfile.yml
x-pack/packetbeat/Jenkinsfile.yml

Use GitHub actions to run the `check stage` for `packetbeat` and `x-pack/packetbeat`
What's the `check stage`?
- `make check`
- `make update`
- `make check-no-changes`
- `mage check`
- `mage update`
Faster build by running linting/checks outside of the main CI Pipeline.
The existing checks in Jenkins are replaced with GitHub checks,  hence the union of these 2 new Github workflows substitutes each former check. Therefore, the same commands will run for the same scenarios.
`pcap.h: No such file or directory` 
```
Error: ../../../../go/pkg/mod/github.com/elastic/gopacket@v1.1.20-0.20211202005954-d412fca7f83a/pcap/pcap_unix.go:[34](https://github.com/elastic/beats/runs/7875203008?check_suite_focus=true#step:5:35):10: fatal error: pcap.h: No such file or directory
34 | #include <pcap.h>
| …
```

actions: run check for x-pack/packetbeat and packebeat

---

testing/environments/snapshot.yml

[start_time:Sun, 21 Aug 2022 12:22:02 GMT, release_branch:8.4, prefix:, end_time:Sun, 21 Aug 2022 17:48:21 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-910fe5e1, build_duration_seconds:19579]

[automation] update elastic stack version for testing 8.4.0-910fe5e1

---

CHANGELOG.next.asciidoc
libbeat/processors/util/netinfo.go
libbeat/processors/util/netinfo_test.go

This alters the syntax of hardware addresses to match the syntax that is [specified in ECS](https://www.elastic.co/guide/en/ecs/current/ecs-host.html#field-host-mac).
Currently it does not match the spec and this leaks out to integrations and modules in ways that are irritating to fix in ingest pipelines.
- Closes #32264

libbeat/processors/util: make mac address rendering conform to ECS

---

testing/environments/snapshot.yml

[start_time:Tue, 23 Aug 2022 00:15:33 GMT, release_branch:8.3, prefix:, end_time:Tue, 23 Aug 2022 04:46:48 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-45336fec, build_duration_seconds:16275]

[automation] update elastic stack version for testing 8.3.4-45336fec

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Mon, 22 Aug 2022 05:14:59 GMT, release_branch:7.17, prefix:, end_time:Mon, 22 Aug 2022 10:05:44 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-a9c53531, build_duration_seconds:17445]

[automation] update elastic stack version for testing 7.17.6-a9c53531

---

testing/environments/snapshot.yml

[start_time:Mon, 22 Aug 2022 12:16:01 GMT, release_branch:8.4, prefix:, end_time:Mon, 22 Aug 2022 17:06:07 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-7f4eb04b, build_duration_seconds:17406]

[automation] update elastic stack version for testing 8.4.0-7f4eb04b

---

testing/environments/snapshot.yml

[start_time:Mon, 22 Aug 2022 12:16:45 GMT, release_branch:master, prefix:, end_time:Mon, 22 Aug 2022 17:41:17 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-dd6f2bb0, build_duration_seconds:19472]

[automation] update elastic stack version for testing 8.5.0-dd6f2bb0

---

.github/CODEOWNERS

Adding explicit code owners for the new Lumberjack input and a few AWS inputs I've seen come up in SDHs but have been unclear on who the owner should be.

Add codeowners for S3, CloudWatch, and Lumberjack.

---

NOTICE.txt
go.mod
go.sum
libbeat/outputs/shipper/api/shipper_mock.go
libbeat/outputs/shipper/config.go
libbeat/outputs/shipper/shipper.go
libbeat/outputs/shipper/shipper_test.go

Now the shipper output is able to receive acknowledgement of the
persisted events from the shipper server.
Also, added the UUID verification in case the client is reconnected to
a different server.
To avoid data loss.
- Closes #32329

Add persistence acknowledgement support for shipper

---

CHANGELOG.next.asciidoc
x-pack/filebeat/input/awss3/input.go
x-pack/filebeat/input/awss3/input_test.go

Now that Cloudflare R2 is out of closed beta, this adds their domain to the provider list to automatically detect and set the provider field.
-

[Filebeat] Add Cloudflare R2 to provider list

---

testing/environments/snapshot.yml

[start_time:Tue, 23 Aug 2022 12:15:44 GMT, release_branch:8.3, prefix:, end_time:Tue, 23 Aug 2022 16:47:14 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-97a7bb79, build_duration_seconds:16290]

[automation] update elastic stack version for testing 8.3.4-97a7bb79

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Tue, 23 Aug 2022 05:16:12 GMT, release_branch:7.17, prefix:, end_time:Tue, 23 Aug 2022 10:04:03 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-4816e9ef, build_duration_seconds:17271]

[automation] update elastic stack version for testing 7.17.6-4816e9ef

---

testing/environments/snapshot.yml

[start_time:Tue, 23 Aug 2022 12:17:54 GMT, release_branch:master, prefix:, end_time:Tue, 23 Aug 2022 18:36:47 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-feb644de, build_duration_seconds:22733]

[automation] update elastic stack version for testing 8.5.0-feb644de

---

testing/environments/snapshot.yml

[start_time:Tue, 23 Aug 2022 12:16:12 GMT, release_branch:8.4, prefix:, end_time:Tue, 23 Aug 2022 18:23:50 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-fa661330, build_duration_seconds:22058]

[automation] update elastic stack version for testing 8.4.0-fa661330

---

.github/workflows/check-default.yml
.github/workflows/check-docs.yml
.github/workflows/check-packetbeat.yml
.github/workflows/check-xpack-packetbeat.yml
.github/workflows/macos-build.yml

Use v3 versions and use mage version from go.sum
Already reported in some other actions, this is just an update.

actions: use v3 and mage install

---

.github/workflows/check-xpack-osquerybeat.yml
.github/workflows/opentelemetry.yml
x-pack/osquerybeat/Jenkinsfile.yml

Use GitHub actions to run the `check stage` for `x-pack/osquerybeat`
What's the `check stage`?
- `mage check`
- `mage update`
Faster builds by running linting/checks outside of the main CI Pipeline.
The existing checks in Jenkins are replaced with GitHub checks,  hence the union of these 2 new Github workflows substitutes each former check. Therefore, the same commands will run for the same scenarios.
Nearly 10 minutes since they build was triggered in Jenkins and still waiting for workers to be assigned, while the new GitHub checks finished relatively much faster
Similar to https://github.com/elastic/beats/pull/32711

action: checks for x-pack/osquerybeat

---

Jenkinsfile
heartbeat/Jenkinsfile.yml
x-pack/heartbeat/Jenkinsfile.yml

So, we'd want our CI boxes that run the unit tests for `x-pack/heartbeat` to:
1. Have node available
2. Have `npm i -g @elastic/synthetics` installed
3. Have the `ELASTIC_SYNTHETICS_CAPABLE` flag set to `true` to signal that it can run these tests.
With https://github.com/elastic/beats/pull/32542 we now have improved testing of browser based monitors in heartbeat. We don't, however, have a good way to run these tests using the actual synthetics node package. Heartbeat fork/execs the `elastic-synthetics` binary provided by `npm i -g @elastic/synthetics` to run browser monitors. 
The [first build](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-32710/1/) ran the below steps:
**NOTE**: As requested it will not run on `heartbeat` but `x-pack/heartbeat` only.
This …

ci: enable synthetics tests for heartbeats

---

CHANGELOG.next.asciidoc
NOTICE.txt
go.mod
go.sum

Update to go-libaudit v2.3.2.
https://github.com/elastic/go-libaudit/releases/tag/v2.3.2
Fixes a bug with the Auditbeat auditd module where data is
corrupted because it was not copied before the byte slice was
reused.
Fixes #32818
- Relates #32818

Upgrade to go-libaudit v2.3.2

---

CHANGELOG.next.asciidoc
x-pack/filebeat/module/cisco/asa/test/additional_messages.log
x-pack/filebeat/module/cisco/asa/test/additional_messages.log-expected.json
x-pack/filebeat/module/cisco/asa/test/non-canonical.log
x-pack/filebeat/module/cisco/asa/test/non-canonical.log-expected.json
x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml

This reflects changes in the cisco_asa package added in v2.7.0 and v2.7.1.
It brings funtionality in to line with the integration and fixes a user issue.
- Closes #32257

x-pack/filebeat/module/cisco/asa: add handling of AAA operations and non-canonical log formats

---

deploy/kubernetes/heartbeat-kubernetes.yaml
deploy/kubernetes/heartbeat/heartbeat-deployment.yaml

Updates heartbeat k8s deployment templates to fix memory metric name to <Mi> , instead of <mi>.
K8S fails to deploy template, unable to process <mi>.
Copy template from `deploy/kubernetes/heartbeat-kubernetes.yaml` and deploy it:
````bash
> kubetctl apply -f heartbeat-kubernetes.yaml
configmap/heartbeat-deployment-config created
deployment.apps/heartbeat created
clusterrolebinding.rbac.authorization.k8s.io/heartbeat created
rolebinding.rbac.authorization.k8s.io/heartbeat created
rolebinding.rbac.authorization.k8s.io/heartbeat-kubeadm-config created
clusterrole.rbac.authorization.k8s.io/heartbeat created
role.rbac.authorization.k8s.io/heartbeat created
role.rbac.authorization.k8s.io/heartbeat-kubeadm-config created
serviceaccount/heartbeat created
````

Update HB k8s template to use <Mi> metric

---

dev-tools/packaging/templates/ironbank/auditbeat/hardening_manifest.yaml
dev-tools/packaging/templates/ironbank/filebeat/hardening_manifest.yaml
dev-tools/packaging/templates/ironbank/metricbeat/hardening_manifest.yaml
dev-tools/packaging/templates/ironbank/packetbeat/hardening_manifest.yaml

This PR updates the image product name in the ironbank labels.
This is required to automate the creation of the ironbank merge requests as the ubireleaser is using this field to compute the elastic-agent artifact url. 
For example, it is now trying to retrieve https://artifacts.elastic.co/downloads/beats/filebeat-8.4.0-linux-x86_64.tar.gz instead of https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.4.0-linux-x86_64.tar.gz
Relates to https://github.com/elastic/apm-server/pull/8959 and https://github.com/elastic/elastic-agent/pull/1009

update ironbank image product name

---

metricbeat/module/ceph/test_ceph.py

I can't figure out why these tests don't work anymore after a quick investigation, so I'm just skipping them to fix the beats build.
It appears something change in the Docker environment recently causing the ceph tests to fail across all branches without an obvious explanation.
- https://github.com/elastic/beats/issues/32898
- https://github.com/elastic/beats/issues/32891

Skip broken ceph tests.

---

metricbeat/docker-compose.yml
metricbeat/module/logstash/docker-compose.yml
testing/environments/latest.yml
x-pack/metricbeat/docker-compose.yml

Merge only after the release of 7.17.6.

[Release] Update test environments for 7.17.7

---

testing/environments/snapshot.yml

[start_time:Mon, 29 Aug 2022 12:16:25 GMT, release_branch:master, prefix:, end_time:Mon, 29 Aug 2022 17:59:37 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-440e0896, build_duration_seconds:20592]

[automation] update elastic stack version for testing 8.5.0-440e0896

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Mon, 29 Aug 2022 05:15:01 GMT, release_branch:7.17, prefix:, end_time:Mon, 29 Aug 2022 09:43:17 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-18723602, build_duration_seconds:16096]

[automation] update elastic stack version for testing 7.17.7-18723602

---

testing/environments/snapshot.yml

[start_time:Mon, 29 Aug 2022 12:15:48 GMT, release_branch:8.4, prefix:, end_time:Mon, 29 Aug 2022 16:57:06 GMT, manifest_version:2.1.0, version:8.4.1-SNAPSHOT, branch:8.4, build_id:8.4.1-b72ec52c, build_duration_seconds:16878]

[automation] update elastic stack version for testing 8.4.1-b72ec52c

---

libbeat/template/load_integration_test.go
x-pack/filebeat/input/httpjson/transform_registry.go

Preallocating memory reduces the load Go needs to handle and track allocated memory regions. This also reduces GC load.
While Go takes care of memory operations, like allocating, resizing and freeing, it is a good style to let Go know in advance the final required size to reduce the load of these operations.

Preallocate memory to reduce GC load

---

x-pack/libbeat/processors/add_cloudfoundry_metadata/_meta/fields.yml

Fix conflict in a file, a leftover from https://github.com/elastic/beats/pull/21223/files

conflict 7.17

---

testing/environments/snapshot.yml

[start_time:Tue, 30 Aug 2022 12:16:13 GMT, release_branch:master, prefix:, end_time:Tue, 30 Aug 2022 17:32:20 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-fedc3e60, build_duration_seconds:18967]

[automation] update elastic stack version for testing 8.5.0-fedc3e60

---

testing/environments/snapshot.yml

[start_time:Tue, 30 Aug 2022 00:16:33 GMT, release_branch:8.4, prefix:, end_time:Tue, 30 Aug 2022 05:46:34 GMT, manifest_version:2.1.0, version:8.4.1-SNAPSHOT, branch:8.4, build_id:8.4.1-65181fd0, build_duration_seconds:19801]

[automation] update elastic stack version for testing 8.4.1-65181fd0

---

x-pack/heartbeat/import.go
x-pack/heartbeat/main.go
x-pack/heartbeat/monitors/browser/browser.go
x-pack/heartbeat/monitors/browser/config.go
x-pack/heartbeat/monitors/browser/config_test.go
x-pack/heartbeat/monitors/browser/project.go
x-pack/heartbeat/monitors/browser/project_test.go
x-pack/heartbeat/monitors/browser/source/source.go
x-pack/heartbeat/monitors/browser/source/source_test.go
x-pack/heartbeat/monitors/browser/synthexec/enrich.go
x-pack/heartbeat/monitors/browser/synthexec/enrich_test.go
x-pack/heartbeat/monitors/browser/synthexec/execmultiplexer.go
x-pack/heartbeat/monitors/browser/synthexec/execmultiplexer_test.go
x-pack/heartbeat/monitors/browser/synthexec/synthexec.go
x-pack/heartbeat/monitors/browser/synthexec/synthexec_linux.go
x-pack/heartbeat/monitors/browser/synthexec/synthexec_test.go
x-pack/heartbeat/monitors/browser/synthexec/synthtypes.go
x-pack/heartbeat/monitors/browser/synthexec/synthtypes_test.go
x-pack/heartbeat/monitors/browser/synthexec/testcmd/main.go

None of this is supported or works there, so we should just disable it.
Fixes https://github.com/elastic/beats/pull/32937
No release notes necessary since there are no user facing changes

[heartbeat] disable browser code on windows via build tags

---

x-pack/libbeat/common/aws/credentials.go
x-pack/libbeat/common/aws/credentials_test.go

Bug
Quick hotfix for having main working properly around https://github.com/elastic/beats/issues/32888
The proper refactoring to be released is taking place at https://github.com/elastic/beats/pull/32921
-

apply a quick hotfix for having main working properly

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Wed, 31 Aug 2022 21:49:47 GMT, release_branch:7.17, prefix:, end_time:Thu, 1 Sep 2022 03:04:09 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-cf1ac8b8, build_duration_seconds:18862]

[automation] update elastic stack version for testing 7.17.7-cf1ac8b8

---

testing/environments/snapshot.yml

[start_time:Wed, 31 Aug 2022 21:50:45 GMT, release_branch:8.4, prefix:, end_time:Thu, 1 Sep 2022 04:12:18 GMT, manifest_version:2.1.0, version:8.4.2-SNAPSHOT, branch:8.4, build_id:8.4.2-30e0a703, build_duration_seconds:22893]

[automation] update elastic stack version for testing 8.4.2-30e0a703

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Thu, 1 Sep 2022 05:16:19 GMT, release_branch:7.17, prefix:, end_time:Thu, 1 Sep 2022 10:21:19 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-b0c2ed0e, build_duration_seconds:18300]

[automation] update elastic stack version for testing 7.17.7-b0c2ed0e

---

testing/environments/snapshot.yml

[start_time:Thu, 1 Sep 2022 12:16:07 GMT, release_branch:master, prefix:, end_time:Thu, 1 Sep 2022 18:48:19 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-de69302b, build_duration_seconds:23532]

[automation] update elastic stack version for testing 8.5.0-de69302b

---

testing/environments/snapshot.yml

[start_time:Thu, 1 Sep 2022 12:15:39 GMT, release_branch:8.4, prefix:, end_time:Thu, 1 Sep 2022 17:55:24 GMT, manifest_version:2.1.0, version:8.4.2-SNAPSHOT, branch:8.4, build_id:8.4.2-48cedf17, build_duration_seconds:20385]

[automation] update elastic stack version for testing 8.4.2-48cedf17

---

testing/environments/snapshot.yml

[start_time:Sun, 4 Sep 2022 12:16:03 GMT, release_branch:8.4, prefix:, end_time:Sun, 4 Sep 2022 17:44:19 GMT, manifest_version:2.1.0, version:8.4.2-SNAPSHOT, branch:8.4, build_id:8.4.2-c37a1f37, build_duration_seconds:19696]

[automation] update elastic stack version for testing 8.4.2-c37a1f37

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Sun, 4 Sep 2022 05:14:57 GMT, release_branch:7.17, prefix:, end_time:Sun, 4 Sep 2022 10:02:53 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-d187f943, build_duration_seconds:17276]

[automation] update elastic stack version for testing 7.17.7-d187f943

---

testing/environments/snapshot.yml

[start_time:Sun, 4 Sep 2022 12:15:33 GMT, release_branch:master, prefix:, end_time:Sun, 4 Sep 2022 18:22:39 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-1bd77fc1, build_duration_seconds:22026]

[automation] update elastic stack version for testing 8.5.0-1bd77fc1

---

testing/environments/snapshot.yml

[start_time:Mon, 5 Sep 2022 12:15:52 GMT, release_branch:master, prefix:, end_time:Mon, 5 Sep 2022 20:01:59 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-167dfc80, build_duration_seconds:27967]

[automation] update elastic stack version for testing 8.5.0-167dfc80

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Mon, 5 Sep 2022 05:19:36 GMT, release_branch:7.17, prefix:, end_time:Mon, 5 Sep 2022 09:50:02 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-9bf11b3d, build_duration_seconds:16226]

[automation] update elastic stack version for testing 7.17.7-9bf11b3d

---

.ci/bump-go-release-version.sh

Bump the `go` version in `go.mod`, hence https://github.com/elastic/beats/pull/32940/files is not needed anymore
One less manual step to be done, so the golang autobump for minor versions will be the one in charge.
There is no need to run any other actions since the PR created with the changes will be validated. Otherwise the `golang` autobump will be much more complex and we wanna leave the logic to the projects that are onboarded to the autobump.
`.ci/bump-go-release-version.sh 1.19.0` produced
```diff
diff --git a/.go-version b/.go-version
index 8e8b0a9335..815d5ca06d 100644
--- a/.go-version
+++ b/.go-version
@@ -1 +1 @@
-1.18.5
+1.19.0
diff --git a/.golangci.yml b/.golangci.yml
index 763ed2bc2e..6c32807314 100755
--- a/.golangci.yml
+++ b/.golangci.yml
@@ -102,7 +102,7 @@ …
```

bump go version in go.mod

---

.ci/jobs/ironbank-validation.yml

Create Jenkins Multibranch Pipeline for the Validate Ironbank docker context which will run periodically.
https://github.com/elastic/beats/pull/32954 was recently merged, though the docker context validation is not part of the docker context generation.
The validation will run periodically to validate if the manifest has changed, that was agreed in a private GitHub issue
This PR won't be tested in the CI, except whether the JJBB is correct as part of the `pre-commit` validation.
The implementation will be done in a follow up

jjbb: multibranch pipeline to validate ironbank docker context

---

heartbeat/docs/monitors/monitor-http.asciidoc
heartbeat/monitors/active/http/config.go
heartbeat/tests/system/config/heartbeat.yml.j2
heartbeat/tests/system/heartbeat.py
heartbeat/tests/system/test_monitor.py
libbeat/docs/tab-widgets/spinup-stack.asciidoc

According to this issue:
https://github.com/elastic/beats/issues/32457
We're looking for a way to support url check with OPTIONS method.
With this change, heartbeat could do the url check with OPTIONS without any more response message.
- [*] My code follows the style guidelines of this project
- [*] I have commented my code, particularly in hard-to-understand areas
- [*] I have made corresponding changes to the documentation
- [] I have made corresponding change to the default configuration files
- [*] I have added tests that prove my fix is effective or that my feature works
- [] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.
```
mage update
mage pythonUnitTest 
```
https://github.com/elastic/beats/issues/32457
```
new options for check …
```

Heartbeat support options for lightweight checks

---

heartbeat/docs/monitors/monitor-common-options.asciidoc

Fix the rendering of the documentation page where data_stream link is empty thus not displayed
Attempt to fix missing link in the heartbeat doc rendering
Clarity of the page
before: 
after:

heartbeat docfix

---

CHANGELOG.next.asciidoc
metricbeat/docs/modules/aws.asciidoc
x-pack/metricbeat/module/aws/_meta/docs.asciidoc
x-pack/metricbeat/module/aws/aws.go
x-pack/metricbeat/module/aws/aws_test.go
x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
x-pack/metricbeat/module/aws/ec2/_meta/docs.asciidoc

When filtering tags from the AWS Metricbeat module, it is not possible to specify more than one value associated to a particular key. This PR allows for that.
A practical example of this would be filtering for more than one development environment (among others) on a single instance of Metricbeat.
Try loading the following AWS module config into Metricbeat:
```
aws.yml: |-
- module: aws
period: 1m
regions: us-east-2
metricsets:
- cloudwatch
metrics:
- namespace: AWS/ApiGateway
resource_type: apigateway
- namespace: AWS/Lambda
resource_type: lambda
tags_filter:
- key: "amwell:environment-name"
value: "dev-next"
- key: …
```

fix: Tag filters only allow single values per key

---

testing/environments/snapshot.yml

[start_time:Tue, 6 Sep 2022 12:16:15 GMT, release_branch:8.4, prefix:, end_time:Tue, 6 Sep 2022 17:44:35 GMT, manifest_version:2.1.0, version:8.4.2-SNAPSHOT, branch:8.4, build_id:8.4.2-b244ddfa, build_duration_seconds:19700]

[automation] update elastic stack version for testing 8.4.2-b244ddfa

---

testing/environments/snapshot.yml

[start_time:Tue, 6 Sep 2022 12:18:14 GMT, release_branch:master, prefix:, end_time:Tue, 6 Sep 2022 18:55:27 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-6b7dda2d, build_duration_seconds:23833]

[automation] update elastic stack version for testing 8.5.0-6b7dda2d

---

.ci/schedule-daily.groovy

Run the ironbank validation pipeline for the active branches on a daily basis.
As agreed with the teams
Requires https://github.com/elastic/beats/pull/32976 and the one with the pipeline https://github.com/elastic/beats/pull/32982

ci: run daily the ironbank validations

---

filebeat/input/file/glob_test.go
filebeat/input/syslog/rfc3164_test.go

Signed-off-by: Abirdcfly <fp544037857@gmail.com>
- Cleanup
-

[Filebeat] fix minor unreachable code

---

testing/environments/snapshot.yml

[start_time:Wed, 7 Sep 2022 12:16:13 GMT, release_branch:master, prefix:, end_time:Wed, 7 Sep 2022 17:38:55 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-4140365c, build_duration_seconds:19362]

[automation] update elastic stack version for testing 8.5.0-4140365c

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Wed, 7 Sep 2022 05:15:32 GMT, release_branch:7.17, prefix:, end_time:Wed, 7 Sep 2022 10:04:39 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-2f72b236, build_duration_seconds:17347]

[automation] update elastic stack version for testing 7.17.7-2f72b236

---

CHANGELOG.next.asciidoc
metricbeat/module/kubernetes/apiserver/_meta/test/metrics.2.0.expected
metricbeat/module/kubernetes/apiserver/apiserver.go
metricbeat/module/kubernetes/apiserver/metricset.go
metricbeat/module/kubernetes/controllermanager/_meta/test/metrics.1.20.expected
metricbeat/module/kubernetes/controllermanager/controllermanager.go
metricbeat/module/kubernetes/proxy/_meta/test/metrics.proxy.1.14.expected
metricbeat/module/kubernetes/proxy/proxy.go
metricbeat/module/kubernetes/scheduler/_meta/test/metrics.scheduler.1.14.expected
metricbeat/module/kubernetes/scheduler/_meta/test/metrics.scheduler.1.17.expected
metricbeat/module/kubernetes/scheduler/scheduler.go
metricbeat/module/kubernetes/system/system.go
metricbeat/module/kubernetes/util/kubernetes.go
metricbeat/module/kubernetes/util/prometheus.go
metricbeat/module/kubernetes/volume/volume.go

Add `orchestrator.cluster.name` and `orchestrator.cluster.ip` fields to the datasets: `proxy`, `system`, `apiserver`, `scheduler` and `controllermanager`.
`orchestrator.cluster.name` is used for kubernetes dashboards
- Related https://github.com/elastic/beats/issues/30425

Add missing cluster metadata to multiple k8s metricsests

---

CHANGELOG.next.asciidoc
x-pack/metricbeat/module/azure/billing/billing.go
x-pack/metricbeat/module/azure/billing/billing_test.go
x-pack/metricbeat/module/azure/billing/client.go
x-pack/metricbeat/module/azure/billing/client_test.go
x-pack/metricbeat/module/azure/billing/data.go
x-pack/metricbeat/module/azure/billing/data_test.go
x-pack/metricbeat/module/azure/billing/mock_service.go
x-pack/metricbeat/module/azure/billing/service.go
x-pack/metricbeat/module/azure/client.go

Switch the fetching of forecast data from the Azure [Consumption API](https://docs.microsoft.com/en-us/rest/api/consumption/) to the [Cost Management API](https://docs.microsoft.com/en-us/rest/api/cost-management/forecast).
The previous forecast endpoint from Consumption API [is no longer maintained](https://github.com/Azure/azure-sdk-for-go/blob/8fb416f409c8e1250e4e397b51a724c268d24c0b/services/consumption/mgmt/2019-10-01/consumption/forecasts.go#L34-L36) and does not support scope.
The Consumption API version of the forecast endpoint was simple: it offered a simple filter with limited options. Instead, the Cost Management API version is a much [richer endpoint with a dozen of options](https://docs.microsoft.com/en-us/rest/api/cost-management/forecast/usage?tabs=HTTP#request-body). The …

[Azure Billing] Switch to Cost Management API for forecast data

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Thu, 8 Sep 2022 05:15:21 GMT, release_branch:7.17, prefix:, end_time:Thu, 8 Sep 2022 10:04:30 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-e363ab2a, build_duration_seconds:17349]

[automation] update elastic stack version for testing 7.17.7-e363ab2a

---

testing/environments/snapshot.yml

[start_time:Thu, 8 Sep 2022 00:15:33 GMT, release_branch:master, prefix:, end_time:Thu, 8 Sep 2022 05:22:17 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-8e906f9f, build_duration_seconds:18404]

[automation] update elastic stack version for testing 8.5.0-8e906f9f

---

testing/environments/snapshot.yml

[start_time:Thu, 8 Sep 2022 12:15:56 GMT, release_branch:8.4, prefix:, end_time:Thu, 8 Sep 2022 17:53:42 GMT, manifest_version:2.1.0, version:8.4.2-SNAPSHOT, branch:8.4, build_id:8.4.2-7c2154f4, build_duration_seconds:20266]

[automation] update elastic stack version for testing 8.4.2-7c2154f4

---

testing/environments/snapshot.yml

[start_time:Sun, 11 Sep 2022 12:16:35 GMT, release_branch:8.4, prefix:, end_time:Sun, 11 Sep 2022 18:01:26 GMT, manifest_version:2.1.0, version:8.4.2-SNAPSHOT, branch:8.4, build_id:8.4.2-879a435a, build_duration_seconds:20691]

[automation] update elastic stack version for testing 8.4.2-879a435a

---

testing/environments/snapshot.yml

[start_time:Sun, 11 Sep 2022 00:15:47 GMT, release_branch:master, prefix:, end_time:Sun, 11 Sep 2022 06:16:32 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-589a4a10, build_duration_seconds:21645]

[automation] update elastic stack version for testing 8.5.0-589a4a10

---

Jenkinsfile
deploy/kubernetes/Jenkinsfile.yml
metricbeat/docs/modules/kubernetes.asciidoc
metricbeat/module/kubernetes/_meta/docs.asciidoc
metricbeat/module/kubernetes/kubernetes.yml

Adds the new version of v1.25.0 in the list of the supported/tested versions.
Part of https://github.com/elastic/observability-dev/issues/2195

Adding support for v1.25.0 k8s

---

CHANGELOG.asciidoc

Adds Beats docs related to https://github.com/elastic/observability-docs/issues/2164.
Related Elastic Agent PR: https://github.com/elastic/observability-docs/pull/2168
@aspacca @kaiyan-sheng Please review this PR, too. I am pretty sure I am not fully understanding all the details here, but wanted to get a PR up so we can discuss. Thanks!

Add Beats known issue caused by credentials error with S3+SQS

---

CHANGELOG.next.asciidoc
filebeat/module/elasticsearch/server/config/log.yml

Fix filebeat sending gc.log even if gc fileset is disabled
gc.log is verbose and unnecessarily fills filebeat indices/data streams
Install filebeat and elasticsearch locally, only enable server fileset (disable gc fileset) and check in filebeat indices there is no more gc logs.
- Closes #30995

[Filebeat][module][elastisearch] exclude gc and audit log from server fileset

---

CHANGELOG.next.asciidoc
x-pack/filebeat/module/fortinet/_meta/kibana/8/dashboard/fortinet_firewall-a89fcb21-ccbb-49d1-a992-380049e6abf7.json

This adds a dashboard for the Fortinet Firewall module imported from the fortinet_fortigate integration.
- For #19810

filebeat/module/fortinet: import dashboard from fortigate integration

---

CHANGELOG.next.asciidoc
packetbeat/_meta/config/beat.yml.tmpl
packetbeat/beater/packetbeat.go
packetbeat/config/config.go
packetbeat/packetbeat.yml
packetbeat/sniffer/device.go
packetbeat/sniffer/sniffer.go
x-pack/packetbeat/packetbeat.yml

Rather than attempting to append new sniffer device data to an established dump,
file, dump files are rolled when a new device is used. The alternative would
require keeping a track of link type and *pcapgo.Writer between calls to sniff
to ensure that the dump file is not truncated and that the header is
appropriately written.
If the user needs to have a single pcap file for the session, they can be merged
using either wireshark or mergecap.
This makes packetbeat more useful on non-linux platforms that do not allow sniffing on the "any" device.
Make the following change and run packetbeat locally with `packetbeat run -e`.
```diff
diff --git a/packetbeat/packetbeat.yml b/packetbeat/packetbeat.yml
index ace50f29d3..18d30247ce 100644
--- a/packetbeat/packetbeat.yml
+++ …
```

packetbeat: add option to allow sniffer to change device when default route changes

---

testing/environments/snapshot.yml

[start_time:Mon, 12 Sep 2022 12:16:31 GMT, release_branch:8.4, prefix:, end_time:Mon, 12 Sep 2022 19:04:16 GMT, manifest_version:2.1.0, version:8.4.2-SNAPSHOT, branch:8.4, build_id:8.4.2-fda47f6e, build_duration_seconds:24465]

[automation] update elastic stack version for testing 8.4.2-fda47f6e

---

testing/environments/snapshot.yml

[start_time:Mon, 12 Sep 2022 00:15:39 GMT, release_branch:master, prefix:, end_time:Mon, 12 Sep 2022 13:52:02 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-37418cf3, build_duration_seconds:48983]

[automation] update elastic stack version for testing 8.5.0-37418cf3

---

.ci/packaging.groovy

Cosmetic change in the name of the stage in the `packaging` pipeline
Add more context about the scope of the stage, since it will be skipped for the `main` branch
similar to https://github.com/elastic/fleet-server/pull/1840

ci: rename stage for DRA staging

---

metricbeat/module/elasticsearch/enrich/data.go

A subset of documents from the `elasticsearch.enrich` metricset did not respect the `xpack.enabled` flag and are currently routed to `.monitoring-es-8-mb` data stream regardless of the setting value. We should only overwrite the indice destination when the setting is true. (see [example](https://github.com/elastic/beats/blob/main/metricbeat/module/elasticsearch/node_stats/data.go#L409))
Fixes https://github.com/elastic/kibana/issues/140039
- Start metricbeat with elasticsearch module and enrich metricset enabled
```
- module: elasticsearch
period: 10s
hosts: [ "https://localhost:9200" ]
username: "elastic"
password: "changeme"
ssl.verification_mode: none
metricsets:
- enrich
```
- Verify that documents are routed to `metricbeat-*` when `xpack.enabled: false` and …

[elasticsearch] add isXpack branch in enrich metricset

---

x-pack/filebeat/input/lumberjack/server.go

Move the batch processing logic contained with the lumberjack server into its own method. 
The closure passed to `newBatchACKTracker` referenced the loop variable (line 84) whose value would change on each iteration. This resulted in incorrect ACKing behavior. This is a fix for a new unreleased input targeting v8.5.0 hence no changelog or backport.
https://github.com/elastic/beats/blob/c293fbd5283f1b211d5dcbe96676366deb9ed2a3/x-pack/filebeat/input/lumberjack/server.go#L70-L84
Any concurrent batch processing can result in incorrect behavior or panics.
Unit testing didn't expose this since it requires multiple concurrent batches. My test strategy was to run three filebeats. One receiving data on 5044. And two others sending batches and exiting.
-  ./filebeat -e -c ./filebeat.lumberjack.yml …

[Filebeat] lumberjack - refactor loop logic into method

---

testing/environments/snapshot.yml

[start_time:Wed, 14 Sep 2022 00:16:00 GMT, release_branch:8.4, prefix:, end_time:Wed, 14 Sep 2022 04:59:09 GMT, manifest_version:2.1.0, version:8.4.2-SNAPSHOT, branch:8.4, build_id:8.4.2-4457f478, build_duration_seconds:16989]

[automation] update elastic stack version for testing 8.4.2-4457f478

---

testing/environments/snapshot.yml

[start_time:Tue, 13 Sep 2022 12:16:13 GMT, release_branch:master, prefix:, end_time:Tue, 13 Sep 2022 22:10:24 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-fcf3d4c2, build_duration_seconds:35651]

[automation] update elastic stack version for testing 8.5.0-fcf3d4c2

---

.github/CODEOWNERS
x-pack/osquerybeat/beater/action_handler.go
x-pack/osquerybeat/beater/action_handler_test.go
x-pack/osquerybeat/beater/config_plugin.go
x-pack/osquerybeat/beater/config_plugin_test.go
x-pack/osquerybeat/beater/logger_plugin.go
x-pack/osquerybeat/beater/logger_plugin_test.go
x-pack/osquerybeat/beater/osquerybeat.go
x-pack/osquerybeat/internal/config/osquery.go
x-pack/osquerybeat/internal/osqd/args.go
x-pack/osquerybeat/internal/pub/publisher.go
x-pack/osquerybeat/internal/pub/publisher_test.go

Enables support for configurable differential queries. The results documents have a new ```osquery_meta``` property that has additional properties from the query run, the ```type``` of the query snapshot vs diff, and the optional ```action```  that is set to either ```added``` or ```removed```
We will need to update the ```osquery_manager``` intengration package as well in order define the proper mapping for ```osquery_meta```.
If you have suggestions for better naming or the location of this new addition to the document let me know.
This capability was asked about by one of our users, that wanted to monitor the new events in particular instead of getting the snapshot results.
Currently in order to try the differential results (we always force snapshots by default) the user would have to …

Osquerybeat: support differential query results

---

Jenkinsfile
Makefile
dev-tools/common.bash
dev-tools/make/mage-install.mk

go1.18 changed where the packages are installed when using `go install`
Run the same command in the CI pipeline
The UR for 7.17 is broken for the last 5 days.
```
Installing mage v1.13.0.
make[3]: Leaving directory '/var/lib/jenkins/workspace/elastic+unified-release+master+snapshot-beats-7.17/cd/release/release-manager/project-configs/7.17/build/projects/gopath/src/github.com/elastic/beats/libbeat'
bash: mage: command not found
make[3]: [../dev-tools/make/mage-install.mk:11: mage] Error 127 (ignored)
bash: mage: command not found
make[3]: *** [scripts/Makefile:33
```
```bash
echo  1.17.10 > .go-version
./dev-tools/run_with_go_ver make test-mage 
...
GOOS             = darwin
GOARCH           = amd64
GOARM            = 
Platform         = darwin/amd64
BinaryExt        = 
XPackDir         = …
```

fix: mage installation with go1.18

---

testing/environments/snapshot.yml

[start_time:Wed, 14 Sep 2022 00:16:17 GMT, release_branch:master, prefix:, end_time:Wed, 14 Sep 2022 06:39:05 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-c7913db3, build_duration_seconds:22968]

[automation] update elastic stack version for testing 8.5.0-c7913db3

---

testing/environments/snapshot.yml

[start_time:Thu, 15 Sep 2022 00:16:21 GMT, release_branch:8.4, prefix:, end_time:Thu, 15 Sep 2022 04:55:32 GMT, manifest_version:2.1.0, version:8.4.2-SNAPSHOT, branch:8.4, build_id:8.4.2-36096067, build_duration_seconds:16751]

[automation] update elastic stack version for testing 8.4.2-36096067

---

testing/environments/snapshot.yml

[start_time:Sun, 18 Sep 2022 00:15:56 GMT, release_branch:8.4, prefix:, end_time:Sun, 18 Sep 2022 04:51:52 GMT, manifest_version:2.1.0, version:8.4.2-SNAPSHOT, branch:8.4, build_id:8.4.2-b98b12f1, build_duration_seconds:16556]

[automation] update elastic stack version for testing 8.4.2-b98b12f1

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Sun, 18 Sep 2022 05:15:14 GMT, release_branch:7.17, prefix:, end_time:Sun, 18 Sep 2022 10:24:38 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-377031d2, build_duration_seconds:18564]

[automation] update elastic stack version for testing 7.17.7-377031d2

---

CHANGELOG.next.asciidoc
packetbeat/_meta/config/beat.yml.tmpl
packetbeat/packetbeat.yml
packetbeat/sniffer/sniffer.go
x-pack/packetbeat/packetbeat.yml

This runs multiple sniffers for each Sniffer, each handling default route
polling as needed independently. All sniffers terminate if any
individual terminates.
This allows multiple network devices to be followed.
- Relates #31905

packetbeat/sniffer: allow multiple interface devices to be followed

---

testing/environments/snapshot.yml

[start_time:Mon, 19 Sep 2022 12:15:58 GMT, release_branch:master, prefix:, end_time:Mon, 19 Sep 2022 17:15:30 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-56d2c52d, build_duration_seconds:17972]

[automation] update elastic stack version for testing 8.5.0-56d2c52d

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Mon, 19 Sep 2022 05:16:08 GMT, release_branch:7.17, prefix:, end_time:Mon, 19 Sep 2022 09:54:04 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-73e6ed48, build_duration_seconds:16676]

[automation] update elastic stack version for testing 7.17.7-73e6ed48

---

metricbeat/docker-compose.yml
testing/environments/latest.yml
x-pack/metricbeat/docker-compose.yml

Merge only after the release of 8.4.2.

[Release] Update test environments for 8.4.3

---

CHANGELOG.next.asciidoc
filebeat/autodiscover/builder/hints/logs.go
filebeat/beater/filebeat.go
filebeat/docs/howto/load-ingest-pipelines.asciidoc
filebeat/fileset/factory.go
filebeat/fileset/modules.go
filebeat/fileset/modules_integration_test.go
filebeat/fileset/modules_test.go
filebeat/fileset/setup.go
libbeat/cmd/instance/beat.go
libbeat/cmd/setup.go
libbeat/docs/command-reference.asciidoc

Add a new flag `--enable-all-filesets` to the `setup` command.  This
results in all modules and filesets being enabled.  
This is useful when used with the `--pipelines` flag to enable loading
of all ingest pipelines.
1. Configure the output
2. Run setup without any modules enabled (no pipelines loaded)
``` bash
.\filebeat -e setup --pipelines
```
3. Run setup with new flag and no modules enabled (all pipelines loaded)
``` bash
.\filebeat -e setup --pipelines --enable-all-filesets
```
- Closes #30916
Useful if you want to load all ingest pipelines without having to
configuring all the modules and filesets.

add `enable-all-filesets` flag to setup command

---

testing/environments/snapshot.yml

[start_time:Tue, 20 Sep 2022 22:44:15 GMT, release_branch:8.4, prefix:, end_time:Wed, 21 Sep 2022 03:19:03 GMT, manifest_version:2.1.0, version:8.4.3-SNAPSHOT, branch:8.4, build_id:8.4.3-c8bcc0ff, build_duration_seconds:16488]

[automation] update elastic stack version for testing 8.4.3-c8bcc0ff

---

testing/environments/snapshot.yml

[start_time:Tue, 20 Sep 2022 12:16:54 GMT, release_branch:master, prefix:, end_time:Tue, 20 Sep 2022 18:40:35 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-7dc445a0, build_duration_seconds:23021]

[automation] update elastic stack version for testing 8.5.0-7dc445a0

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Tue, 20 Sep 2022 05:15:03 GMT, release_branch:7.17, prefix:, end_time:Tue, 20 Sep 2022 09:54:47 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-a2d4ea28, build_duration_seconds:16784]

[automation] update elastic stack version for testing 7.17.7-a2d4ea28

---

metricbeat/docker-compose.yml
testing/environments/latest.yml
x-pack/metricbeat/docker-compose.yml

This updates the test environments to next minor release which is 8.6.0.

[Release] Update test environment to 8.6.0

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Wed, 21 Sep 2022 05:20:29 GMT, release_branch:7.17, prefix:, end_time:Wed, 21 Sep 2022 10:25:35 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-86b6ff03, build_duration_seconds:18306]

[automation] update elastic stack version for testing 7.17.7-86b6ff03

---

testing/environments/snapshot.yml

[start_time:Thu, 22 Sep 2022 00:16:04 GMT, release_branch:8.4, prefix:, end_time:Thu, 22 Sep 2022 04:44:16 GMT, manifest_version:2.1.0, version:8.4.3-SNAPSHOT, branch:8.4, build_id:8.4.3-72a0900d, build_duration_seconds:16092]

[automation] update elastic stack version for testing 8.4.3-72a0900d

---

testing/environments/snapshot.yml

[start_time:Fri, 23 Sep 2022 00:15:40 GMT, release_branch:8.4, prefix:, end_time:Fri, 23 Sep 2022 04:56:22 GMT, manifest_version:2.1.0, version:8.4.3-SNAPSHOT, branch:8.4, build_id:8.4.3-24191b6e, build_duration_seconds:16842]

[automation] update elastic stack version for testing 8.4.3-24191b6e

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Thu, 22 Sep 2022 05:24:41 GMT, release_branch:7.17, prefix:, end_time:Thu, 22 Sep 2022 10:23:35 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-f08d978f, build_duration_seconds:17934]

[automation] update elastic stack version for testing 7.17.7-f08d978f

---

testing/environments/snapshot.yml

[start_time:Sun, 25 Sep 2022 00:16:20 GMT, release_branch:master, prefix:, end_time:Sun, 25 Sep 2022 04:42:27 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-21651da3, build_duration_seconds:15967]

[automation] update elastic stack version for testing 8.6.0-21651da3

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Sun, 25 Sep 2022 05:17:08 GMT, release_branch:7.17, prefix:, end_time:Sun, 25 Sep 2022 10:07:40 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-a7e2fef6, build_duration_seconds:17432]

[automation] update elastic stack version for testing 7.17.7-a7e2fef6

---

testing/environments/snapshot.yml

[start_time:Sun, 25 Sep 2022 12:16:28 GMT, release_branch:8.4, prefix:, end_time:Sun, 25 Sep 2022 17:07:38 GMT, manifest_version:2.1.0, version:8.4.3-SNAPSHOT, branch:8.4, build_id:8.4.3-f2e1ac46, build_duration_seconds:17470]

[automation] update elastic stack version for testing 8.4.3-f2e1ac46

---

.ci/ironbank-validation.groovy
x-pack/heartbeat/ironbank/Makefile

Retry a few times
HA for the docker registry is not in place, so this will avoid the overhead to analyse failures related to timeouts or networking with the docker registry.
The downside is related with genuine failures, since they will be retried a few times... although I don't expect any problems since the existing pipeline in  based on a timer so it will not affect anything else

ironbank: validate with retry

---

testing/environments/snapshot.yml

[start_time:Mon, 26 Sep 2022 00:18:40 GMT, release_branch:8.4, prefix:, end_time:Mon, 26 Sep 2022 06:27:02 GMT, manifest_version:2.1.0, version:8.4.3-SNAPSHOT, branch:8.4, build_id:8.4.3-3f1f47b9, build_duration_seconds:22102]

[automation] update elastic stack version for testing 8.4.3-3f1f47b9

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Mon, 26 Sep 2022 05:15:14 GMT, release_branch:7.17, prefix:, end_time:Mon, 26 Sep 2022 09:55:02 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-3d172834, build_duration_seconds:16788]

[automation] update elastic stack version for testing 7.17.7-3d172834

---

testing/environments/snapshot.yml

[start_time:Mon, 26 Sep 2022 12:16:45 GMT, release_branch:master, prefix:, end_time:Mon, 26 Sep 2022 16:24:21 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-326f84b0, build_duration_seconds:14856]

[automation] update elastic stack version for testing 8.6.0-326f84b0

---

testing/environments/snapshot.yml

[start_time:Tue, 27 Sep 2022 12:16:05 GMT, release_branch:master, prefix:, end_time:Tue, 27 Sep 2022 17:13:08 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-df00693f, build_duration_seconds:17823]

[automation] update elastic stack version for testing 8.6.0-df00693f

---

testing/environments/snapshot.yml

[start_time:Tue, 27 Sep 2022 12:15:32 GMT, release_branch:8.4, prefix:, end_time:Tue, 27 Sep 2022 17:14:03 GMT, manifest_version:2.1.0, version:8.4.3-SNAPSHOT, branch:8.4, build_id:8.4.3-e8645b30, build_duration_seconds:17911]

[automation] update elastic stack version for testing 8.4.3-e8645b30

---

.ci/scripts/terraform-cleanup.sh

I'm seeing this terraform clean up error in 2 different PRs:
https://github.com/elastic/beats/pull/33105 and https://github.com/elastic/beats/pull/33143
```
[2022-09-28T17:52:04.645Z] + .ci/scripts/terraform-cleanup.sh x-pack/filebeat
[2022-09-28T17:52:04.645Z] + DIRECTORY=x-pack/filebeat
[2022-09-28T17:52:04.645Z] + FAILED=0
[2022-09-28T17:52:04.645Z] ++ find x-pack/filebeat -name terraform.tfstate
[2022-09-28T17:52:04.747Z] + for tfstate in $(find $DIRECTORY -name terraform.tfstate)
[2022-09-28T17:52:04.747Z] ++ dirname x-pack/filebeat/input/awss3/_meta/terraform/terraform.tfstate
[2022-09-28T17:52:04.747Z] + cd x-pack/filebeat/input/awss3/_meta/terraform
[2022-09-28T17:52:04.747Z] + terraform destroy -auto-approve
[2022-09-28T17:52:05.550Z] [31m╷[0m[0m
[2022-09-28T17:52:05.550Z] …
```

Fix terraform cleanup error

---

testing/environments/snapshot.yml

[start_time:Wed, 28 Sep 2022 13:23:03 GMT, release_branch:master, prefix:, end_time:Wed, 28 Sep 2022 18:07:55 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-a2f4f140, build_duration_seconds:17092]

[automation] update elastic stack version for testing 8.6.0-a2f4f140

---

testing/environments/snapshot.yml

[start_time:Thu, 29 Sep 2022 00:19:36 GMT, release_branch:8.4, prefix:, end_time:Thu, 29 Sep 2022 06:25:42 GMT, manifest_version:2.1.0, version:8.4.3-SNAPSHOT, branch:8.4, build_id:8.4.3-0900b129, build_duration_seconds:21966]

[automation] update elastic stack version for testing 8.4.3-0900b129

---

testing/environments/snapshot.yml

[start_time:Fri, 30 Sep 2022 00:15:45 GMT, release_branch:master, prefix:, end_time:Fri, 30 Sep 2022 04:40:25 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-158a13db, build_duration_seconds:15880]

[automation] update elastic stack version for testing 8.6.0-158a13db

---

testing/environments/snapshot.yml

[start_time:Thu, 29 Sep 2022 00:15:42 GMT, release_branch:8.5, prefix:, end_time:Thu, 29 Sep 2022 05:36:58 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-b22c068f, build_duration_seconds:19276]

[automation] update elastic stack version for testing 8.5.0-b22c068f

---

testing/environments/snapshot.yml

[start_time:Mon, 3 Oct 2022 12:16:03 GMT, release_branch:8.4, prefix:, end_time:Mon, 3 Oct 2022 17:19:22 GMT, manifest_version:2.1.0, version:8.4.3-SNAPSHOT, branch:8.4, build_id:8.4.3-5e0dd488, build_duration_seconds:18199]

[automation] update elastic stack version for testing 8.4.3-5e0dd488

---

testing/environments/snapshot.yml

[start_time:Mon, 3 Oct 2022 16:39:13 GMT, release_branch:8.5, prefix:, end_time:Mon, 3 Oct 2022 21:30:10 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-49b2dce3, build_duration_seconds:17457]

[automation] update elastic stack version for testing 8.5.0-49b2dce3

---

testing/environments/snapshot.yml

[start_time:Wed, 5 Oct 2022 00:15:55 GMT, release_branch:master, prefix:, end_time:Wed, 5 Oct 2022 04:46:47 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-0fca2953, build_duration_seconds:16252]

[automation] update elastic stack version for testing 8.6.0-0fca2953

---

testing/environments/snapshot.yml

[start_time:Tue, 4 Oct 2022 12:15:44 GMT, release_branch:8.4, prefix:, end_time:Tue, 4 Oct 2022 17:28:31 GMT, manifest_version:2.1.0, version:8.4.3-SNAPSHOT, branch:8.4, build_id:8.4.3-ff95b7c5, build_duration_seconds:18767]

[automation] update elastic stack version for testing 8.4.3-ff95b7c5

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Tue, 4 Oct 2022 05:15:08 GMT, release_branch:7.17, prefix:, end_time:Tue, 4 Oct 2022 10:09:11 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-70d4ef7d, build_duration_seconds:17643]

[automation] update elastic stack version for testing 7.17.7-70d4ef7d

---

testing/environments/snapshot.yml

[start_time:Thu, 6 Oct 2022 00:27:13 GMT, release_branch:master, prefix:, end_time:Thu, 6 Oct 2022 04:59:12 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-e4c15f15, build_duration_seconds:16319]

[automation] update elastic stack version for testing 8.6.0-e4c15f15

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Wed, 5 Oct 2022 05:20:17 GMT, release_branch:7.17, prefix:, end_time:Wed, 5 Oct 2022 10:06:08 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-a343880e, build_duration_seconds:17151]

[automation] update elastic stack version for testing 7.17.7-a343880e

---

testing/environments/snapshot.yml

[start_time:Wed, 5 Oct 2022 00:15:52 GMT, release_branch:8.5, prefix:, end_time:Wed, 5 Oct 2022 06:28:22 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-58624073, build_duration_seconds:22350]

[automation] update elastic stack version for testing 8.5.0-58624073

---

metricbeat/docker-compose.yml
testing/environments/latest.yml
x-pack/metricbeat/docker-compose.yml

Merge only after the release of 8.4.3.

[Release] Update test environments for 8.4.4

---

CHANGELOG.next.asciidoc
x-pack/filebeat/input/awscloudwatch/metrics.go
x-pack/filebeat/input/awss3/metrics.go
x-pack/filebeat/input/awss3/metrics_test.go
x-pack/filebeat/input/lumberjack/metrics.go

Filebeat inputs for aws-s3, aws-cloudwatch, and lumberjack register metrics in the "dataset" namespace. They use the ID of the Filebeat input as a key in the monitoring registry. The monitoring registry will panic if you attempt to register an ID that already exists in the registry.
The aws-s3 input was observed to panic under Agent when configuration was modified. The root cause was that input's metrics were not unregistered when the input closed. This was due to a bug where the metrics were removed from the wrong monitoring registry instance. A test was added to aws-s3 to verify the fix and similar code was found and fixed in aws-cloudwatch and lumberjack.
This observed panic from Filebeat 8.4.2 under Agent was:
```
panic: name cloudfront_logs-decbb626-7967-4188-b39e-f7b20ff88f42 …
```

[Filebeat] Fix input metrics not being unregistered for aws-s3, aws-cloudwatch, lumberjack

---

testing/environments/snapshot.yml

[start_time:Thu, 6 Oct 2022 12:15:40 GMT, release_branch:8.4, prefix:, end_time:Thu, 6 Oct 2022 17:02:10 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-ac374c4b, build_duration_seconds:17190]

[automation] update elastic stack version for testing 8.4.4-ac374c4b

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Thu, 6 Oct 2022 05:19:34 GMT, release_branch:7.17, prefix:, end_time:Thu, 6 Oct 2022 10:04:50 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-f9849b81, build_duration_seconds:17116]

[automation] update elastic stack version for testing 7.17.7-f9849b81

---

testing/environments/snapshot.yml

[start_time:Thu, 6 Oct 2022 17:18:51 GMT, release_branch:8.5, prefix:, end_time:Thu, 6 Oct 2022 23:40:40 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-c52257ee, build_duration_seconds:22909]

[automation] update elastic stack version for testing 8.5.0-c52257ee

---

packetbeat/decoder/decoder.go

The current logic for multilayer use means that sucessive packets in the stream
from the sniffer can end up as parts of the multilayer although they are not
related layers. The documentation for the type says it is provided to allow
"switching between multiple layers to remember outer layer results", but
successive packet in the sniffer stream do not have this relationship.
For #33012

packetbeat/decoder: reset multilayer decoding layers for each sniffed packet

---

testing/environments/snapshot.yml

[start_time:Sun, 9 Oct 2022 12:16:02 GMT, release_branch:8.4, prefix:, end_time:Sun, 9 Oct 2022 17:16:03 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-17ce02d0, build_duration_seconds:18001]

[automation] update elastic stack version for testing 8.4.4-17ce02d0

---

testing/environments/snapshot.yml

[start_time:Sun, 9 Oct 2022 00:15:56 GMT, release_branch:8.5, prefix:, end_time:Sun, 9 Oct 2022 06:04:00 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-7d416dc4, build_duration_seconds:20884]

[automation] update elastic stack version for testing 8.5.0-7d416dc4

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Sun, 9 Oct 2022 05:15:03 GMT, release_branch:7.17, prefix:, end_time:Sun, 9 Oct 2022 09:34:40 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-3947c049, build_duration_seconds:15577]

[automation] update elastic stack version for testing 7.17.7-3947c049

---

testing/environments/snapshot.yml

[start_time:Sun, 9 Oct 2022 00:16:22 GMT, release_branch:master, prefix:, end_time:Sun, 9 Oct 2022 05:40:47 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-7c9f25a9, build_duration_seconds:19465]

[automation] update elastic stack version for testing 8.6.0-7c9f25a9

---

CHANGELOG.next.asciidoc
heartbeat/monitors/factory.go
heartbeat/monitors/factory_test.go

Fixes usage of Enabled incase of data streams !!
Fix https://github.com/elastic/beats/issues/33270
Example to test
```
- id: >-
synthetics/browser-synthetics-e1a84561-a0df-49a1-b61f-0c09e0e4f25f-elastic-agent-managed-ep-default
name: My first monitor-Test private location-default
revision: 3
type: synthetics/browser
use_output: default
meta:
package:
name: synthetics
version: 0.11.0
data_stream:
namespace: default
package_policy_id: e1a84561-a0df-49a1-b61f-0c09e0e4f25f-elastic-agent-managed-ep-default
streams:
- id: >-
synthetics/browser-browser.screenshot-e1a84561-a0df-49a1-b61f-0c09e0e4f25f-elastic-agent-managed-ep-default
data_stream:
dataset: browser.screenshot
type: synthetics
processors:
- add_observer_metadata:
geo:
name: Fleet managed
- add_fields:
fields:
monitor.fleet_managed: …
```

[Heartbeat] Fix enabled flag usage in case of streams

---

testing/environments/snapshot.yml

[start_time:Mon, 10 Oct 2022 12:16:20 GMT, release_branch:8.4, prefix:, end_time:Mon, 10 Oct 2022 17:57:12 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-221d2ff4, build_duration_seconds:20452]

[automation] update elastic stack version for testing 8.4.4-221d2ff4

---

testing/environments/snapshot.yml

[start_time:Mon, 10 Oct 2022 18:58:59 GMT, release_branch:master, prefix:, end_time:Mon, 10 Oct 2022 23:29:50 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-c49fac70, build_duration_seconds:16251]

[automation] update elastic stack version for testing 8.6.0-c49fac70

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Mon, 10 Oct 2022 05:19:17 GMT, release_branch:7.17, prefix:, end_time:Mon, 10 Oct 2022 09:38:59 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-32fc38cc, build_duration_seconds:15582]

[automation] update elastic stack version for testing 7.17.7-32fc38cc

---

testing/environments/snapshot.yml

[start_time:Mon, 10 Oct 2022 00:15:23 GMT, release_branch:8.5, prefix:, end_time:Mon, 10 Oct 2022 05:23:06 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-4f4df9f4, build_duration_seconds:18463]

[automation] update elastic stack version for testing 8.5.0-4f4df9f4

---

deploy/kubernetes/heartbeat-kubernetes.yaml
deploy/kubernetes/heartbeat/heartbeat-configmap.yaml

With our previous example uncommenting multiple providers would break, since our yaml parser just picks the last present `providers` key.

[Heartbeat] Only use one provider list in k8s configmap example

---

heartbeat/ecserr/ecserr.go
heartbeat/monitors/monitor.go
heartbeat/monitors/wrappers/wrappers.go
heartbeat/monitors/wrappers/wrappers_test.go
x-pack/heartbeat/monitors/browser/browser.go

Fixes https://github.com/elastic/beats/issues/32694  by making sure we use the lightweight wrapper code always when monitors cannot be initialized.
This also fixes an unrelated bug, where errors attached to non-summary events would not be indexed.
Create an inline monitor with a non-docker heartbeat, sending the results to ES. Kibana should show the error in the screenshot.

Fix errors for non-synth capable instances

---

testing/environments/snapshot.yml

[start_time:Wed, 12 Oct 2022 00:16:08 GMT, release_branch:8.4, prefix:, end_time:Wed, 12 Oct 2022 04:58:52 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-5fbb5bd0, build_duration_seconds:16964]

[automation] update elastic stack version for testing 8.4.4-5fbb5bd0

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Tue, 11 Oct 2022 05:15:43 GMT, release_branch:7.17, prefix:, end_time:Tue, 11 Oct 2022 09:56:33 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-8081bbcb, build_duration_seconds:16850]

[automation] update elastic stack version for testing 7.17.7-8081bbcb

---

testing/environments/snapshot.yml

[start_time:Tue, 11 Oct 2022 00:20:39 GMT, release_branch:master, prefix:, end_time:Tue, 11 Oct 2022 06:28:26 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-5a8d757d, build_duration_seconds:22067]

[automation] update elastic stack version for testing 8.6.0-5a8d757d

---

filebeat/docs/filebeat-log-rotation.asciidoc

Troubleshooting guide for logs rotation contains a sample configuration with `enabled: false`. I guess this configuration shouldn't be disabled. Enable it, and migrate it from `log` input to `filestream`.
These are the sample configurations in https://www.elastic.co/guide/en/beats/filebeat/8.4/file-log-rotation.html#log-rotate-example

Fix sample config in log rotation docs

---

x-pack/functionbeat/docs/page_header.html

Adds banner to encourage users to use the Elastic Serverless Forwarder instead of Functionbeat.
Starting in 8.5, Functionbeat is deprecated. Users should prepare for the migration to Elastic Serverless Forwarder now.
- Closes https://github.com/elastic/observability-docs/issues/2225

[DOCS] Add banner to encourage Functionbeat users to move to ESF

---

packetbeat/protos/dns/dns.go
packetbeat/protos/dns/dns_tcp.go
packetbeat/protos/dns/dns_test.go
packetbeat/protos/dns/dns_udp.go
packetbeat/protos/dns/names.go
packetbeat/protos/dns/names_test.go

Clean up of packetbeat/protos/dns for #33012.
* use logp.Debug in place of deprecated logp.MakeDebug
* avoid magic numbers
* fix hashableDNSTuple size and offsets
* avoid use of String and Error methods in formatted print calls
* remove redundant conversions
* quieten linter
Improves the clarity of the code.
- For #33012

packetbeat/protos/dns: clean up package

---

testing/environments/snapshot.yml

[start_time:Wed, 12 Oct 2022 00:16:08 GMT, release_branch:8.5, prefix:, end_time:Wed, 12 Oct 2022 05:39:36 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-fe2e6147, build_duration_seconds:19408]

[automation] update elastic stack version for testing 8.5.0-fe2e6147

---

testing/environments/snapshot.yml

[start_time:Wed, 12 Oct 2022 12:15:59 GMT, release_branch:8.4, prefix:, end_time:Wed, 12 Oct 2022 17:17:33 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-1129f33b, build_duration_seconds:18094]

[automation] update elastic stack version for testing 8.4.4-1129f33b

---

testing/environments/snapshot.yml

[start_time:Wed, 12 Oct 2022 12:16:08 GMT, release_branch:master, prefix:, end_time:Wed, 12 Oct 2022 16:34:46 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-40086bc7, build_duration_seconds:15518]

[automation] update elastic stack version for testing 8.6.0-40086bc7

---

NOTICE.txt
dev-tools/make/mage-install.mk
go.mod
go.sum

For some reason during the dependency installation mage gets updated v1.13.0->v1.14.0 which breaks the previously installed mage (on the previous step).

Update mage to fix the CI

---

x-pack/libbeat/management/generate.go

Closes https://github.com/elastic/beats/issues/33168 By adding a small check to make sure we don't add a blank stream ID.

Fix unchecked stream_id

---

x-pack/elastic-agent/CHANGELOG.next.asciidoc
x-pack/elastic-agent/pkg/composable/providers/docker/docker.go
x-pack/elastic-agent/pkg/composable/providers/docker/docker_test.go

This is a backport PR for: https://github.com/elastic/elastic-agent/pull/1420
The Docker provider was using a wrong key when defining the `add_fields` processor, this causes Filebeat not to start the input and stay on a unhealthy state. This processor seems to be defined every time a variable like `${docker}` is used on a input configuration.
This commit fixes it.
It fixes a bug on Docker auto discovery provider
1. Make sure you have Docker installed and running
1. Deploy Elastic Stack
1. Start a container that will generate logs (e.g: `docker run --rm --name flog -d mingrammer/flog /bin/flog -s1 -d1 -l -f rfc3164`).
2. Create a standalone Elastic-Agent policy [using Kibana as suggested in the documentation](https://www.elastic.co/guide/en/fleet/current/create-standalone-agent-policy.html# …

Fix docker provider add_fields processors

---

testing/environments/snapshot.yml

[start_time:Thu, 13 Oct 2022 15:19:07 GMT, release_branch:master, prefix:, end_time:Thu, 13 Oct 2022 19:29:42 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-233dc5d4, build_duration_seconds:15035]

[automation] update elastic stack version for testing 8.6.0-233dc5d4

---

testing/environments/snapshot.yml

[start_time:Thu, 13 Oct 2022 12:16:41 GMT, release_branch:8.4, prefix:, end_time:Thu, 13 Oct 2022 17:40:37 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-fdf1902b, build_duration_seconds:19436]

[automation] update elastic stack version for testing 8.4.4-fdf1902b

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Thu, 13 Oct 2022 05:16:44 GMT, release_branch:7.17, prefix:, end_time:Thu, 13 Oct 2022 10:00:38 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-40d7eba9, build_duration_seconds:17034]

[automation] update elastic stack version for testing 7.17.7-40d7eba9

---

testing/environments/snapshot.yml

[start_time:Thu, 13 Oct 2022 00:18:58 GMT, release_branch:8.5, prefix:, end_time:Thu, 13 Oct 2022 05:33:07 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-976bca07, build_duration_seconds:18849]

[automation] update elastic stack version for testing 8.5.0-976bca07

---

testing/environments/snapshot.yml

[start_time:Sun, 16 Oct 2022 00:15:37 GMT, release_branch:8.5, prefix:, end_time:Sun, 16 Oct 2022 05:34:22 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-f8c98e5d, build_duration_seconds:19125]

[automation] update elastic stack version for testing 8.5.0-f8c98e5d

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Sun, 16 Oct 2022 05:16:04 GMT, release_branch:7.17, prefix:, end_time:Sun, 16 Oct 2022 09:52:19 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-e7a47621, build_duration_seconds:16575]

[automation] update elastic stack version for testing 7.17.7-e7a47621

---

testing/environments/snapshot.yml

[start_time:Sun, 16 Oct 2022 12:16:14 GMT, release_branch:8.4, prefix:, end_time:Sun, 16 Oct 2022 17:02:55 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-2db0c963, build_duration_seconds:17201]

[automation] update elastic stack version for testing 8.4.4-2db0c963

---

testing/environments/snapshot.yml

[start_time:Sun, 16 Oct 2022 12:15:58 GMT, release_branch:master, prefix:, end_time:Sun, 16 Oct 2022 16:04:15 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-54a302f0, build_duration_seconds:13697]

[automation] update elastic stack version for testing 8.6.0-54a302f0

---

.ci/schedule-daily.groovy
.ci/schedule-weekly.groovy

Next minor alias was not enabled.
`8.5` branch is not enabled for the daily/weekly.

ci: enable next minor for daily and weekly automation

---

metricbeat/module/elasticsearch/node_stats/data.go

Fixes [#143337](https://github.com/elastic/kibana/issues/143337)
The field `elasticsearch.node.stats.os.cgroup.cpu.stat.time_throttled.ns` (aliased under `node_stats.os.cgroup.cpu.stat.time_throttled_nanos`) was not being reported in the `node_stats` metricset of the Elasticsearch module. 
This is due to it not being part of the schema that is used to copy data from the `_nodes/stats` API response to the Metricbeat event.
Get the changes: `git fetch git@github.com:miltonhultgren/beats.git 143337-missing-cpu-quota-data:143337-missing-cpu-quota-data && git switch 143337-missing-cpu-quota-data`
I suggest running two single-node Elasticsearch clusters, one that is monitored with Metricbeat and one that is the monitoring cluster which Kibana connects to. 
For the "monitoring" cluster just set …

[Metricbeat] Add time_throttled in ES node_stats metricset (#143337)

---

x-pack/elastic-agent/Jenkinsfile.yml

Remove e2e-testing from the main pipeline
e2e-testing requires more components to be built such as metricbeat, hence the packaging with `e2e-testing` for the `x-pack/elastic-agent` won't work since it requires metricbeat to be packaged.

ci: remove e2e-testing in the main pipeline for elastic-agent

---

dev-tools/packaging/templates/docker/Dockerfile.tmpl

Fixes https://github.com/elastic/beats/issues/31732
Always use the `stack_release` label for `npm i`
No changelog necessary since there are no user-visible changes
This lets us ensure we've carefully reviewed and labeled the version of the `@elastic/synthetics` NPM library that's bundled in docker images

[Heartbeat] Use stack_release label for synthetics npm install

---

testing/environments/snapshot.yml

[start_time:Mon, 17 Oct 2022 12:16:19 GMT, release_branch:master, prefix:, end_time:Mon, 17 Oct 2022 16:11:30 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-cae815eb, build_duration_seconds:14111]

[automation] update elastic stack version for testing 8.6.0-cae815eb

---

testing/environments/snapshot.yml

[start_time:Mon, 17 Oct 2022 12:16:24 GMT, release_branch:8.4, prefix:, end_time:Mon, 17 Oct 2022 17:30:17 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-93b2bfdf, build_duration_seconds:18833]

[automation] update elastic stack version for testing 8.4.4-93b2bfdf

---

testing/environments/snapshot.yml

[start_time:Mon, 17 Oct 2022 00:17:28 GMT, release_branch:8.5, prefix:, end_time:Mon, 17 Oct 2022 05:59:35 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-7c74e950, build_duration_seconds:20527]

[automation] update elastic stack version for testing 8.5.0-7c74e950

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Mon, 17 Oct 2022 05:15:13 GMT, release_branch:7.17, prefix:, end_time:Mon, 17 Oct 2022 09:50:51 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-f82fb944, build_duration_seconds:16538]

[automation] update elastic stack version for testing 7.17.7-f82fb944

---

testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

[start_time:Tue, 18 Oct 2022 05:15:27 GMT, release_branch:7.17, prefix:, end_time:Tue, 18 Oct 2022 09:55:30 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-c42c4e01, build_duration_seconds:16803]

[automation] update elastic stack version for testing 7.17.7-c42c4e01

---

testing/environments/snapshot.yml

[start_time:Tue, 18 Oct 2022 00:16:10 GMT, release_branch:8.5, prefix:, end_time:Tue, 18 Oct 2022 05:44:24 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-792499b4, build_duration_seconds:19694]

[automation] update elastic stack version for testing 8.5.0-792499b4

---

testing/environments/snapshot.yml

[start_time:Tue, 18 Oct 2022 12:20:09 GMT, release_branch:master, prefix:, end_time:Wed, 19 Oct 2022 01:59:14 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-6545f2df, build_duration_seconds:49145]

[automation] update elastic stack version for testing 8.6.0-6545f2df

---

testing/environments/snapshot.yml

[start_time:Tue, 18 Oct 2022 00:15:53 GMT, release_branch:8.4, prefix:, end_time:Tue, 18 Oct 2022 06:14:56 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-e97ba82f, build_duration_seconds:21543]

[automation] update elastic stack version for testing 8.4.4-e97ba82f
