elastic/beats

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-httpjson.asciidoc, x-pack/filebeat/input/httpjson/input_test.go, x-pack/filebeat/input/httpjson/pagination.go, x-pack/filebeat/input/httpjson/request_test.go
Fixes an issue with the page number of `.last_response.page` that was making page numbers inconsistent between intervals.
First interval page numbers would go as: 0,1,2..., Subsequent calls would always be 1,2,3... instead, which caused issues when using conditions based on this value for some configurations.
This sets the defined behavior as 0,1,2... for all intervals and documents it as such, since is the assumption that was made in all affected integrations.
Fixes pagination errors for Google Workspace integrations and others.
- Closes #32364
=> [filebeat] Fix httpjson page number initialization and docs

heartbeat/monitors/wrappers/monitorstate/monitorstate.go
Fixes #33393 , per @shahzad31 's suggestion, there's no need to interpolate the monitor ID in the state ID, queries will always scope by `monitor.id` anyway. No tests need to change here.
=> [Heartbeat] Remove monitor ID from state ID

testing/environments/snapshot.yml
[start_time:Wed, 19 Oct 2022 12:15:40 GMT, release_branch:master, prefix:, end_time:Wed, 19 Oct 2022 17:04:17 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-055acc83, build_duration_seconds:17317]
=> [automation] update elastic stack version for testing 8.6.0-055acc83

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 19 Oct 2022 05:14:59 GMT, release_branch:7.17, prefix:, end_time:Wed, 19 Oct 2022 10:00:21 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-55166c00, build_duration_seconds:17122]
=> [automation] update elastic stack version for testing 7.17.7-55166c00

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 20 Oct 2022 05:14:45 GMT, release_branch:7.17, prefix:, end_time:Thu, 20 Oct 2022 10:18:24 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-60386d02, build_duration_seconds:18219]
=> [automation] update elastic stack version for testing 7.17.7-60386d02

testing/environments/snapshot.yml
[start_time:Thu, 20 Oct 2022 13:32:18 GMT, release_branch:8.5, prefix:, end_time:Thu, 20 Oct 2022 20:19:57 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-754ef325, build_duration_seconds:24459]
=> [automation] update elastic stack version for testing 8.5.0-754ef325

testing/environments/snapshot.yml
[start_time:Fri, 21 Oct 2022 00:15:47 GMT, release_branch:master, prefix:, end_time:Fri, 21 Oct 2022 04:31:51 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-baf193e8, build_duration_seconds:15364]
=> [automation] update elastic stack version for testing 8.6.0-baf193e8

testing/environments/snapshot.yml
[start_time:Thu, 20 Oct 2022 12:15:32 GMT, release_branch:8.4, prefix:, end_time:Thu, 20 Oct 2022 18:55:40 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-4edb5c6b, build_duration_seconds:24008]
=> [automation] update elastic stack version for testing 8.4.4-4edb5c6b

testing/environments/snapshot.yml
[start_time:Sun, 23 Oct 2022 12:16:00 GMT, release_branch:8.4, prefix:, end_time:Sun, 23 Oct 2022 18:09:57 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-9b801d60, build_duration_seconds:21237]
=> [automation] update elastic stack version for testing 8.4.4-9b801d60

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Sat, 22 Oct 2022 05:15:49 GMT, release_branch:7.17, prefix:, end_time:Sat, 22 Oct 2022 09:55:39 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-e6ce36d2, build_duration_seconds:16790]
=> [automation] update elastic stack version for testing 7.17.7-e6ce36d2

testing/environments/snapshot.yml
[start_time:Sat, 22 Oct 2022 00:18:19 GMT, release_branch:8.5, prefix:, end_time:Sat, 22 Oct 2022 06:25:34 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-d7b01592, build_duration_seconds:22035]
=> [automation] update elastic stack version for testing 8.5.0-d7b01592

testing/environments/snapshot.yml
[start_time:Sun, 23 Oct 2022 12:16:04 GMT, release_branch:master, prefix:, end_time:Sun, 23 Oct 2022 16:44:33 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-22d60ec9, build_duration_seconds:16109]
=> [automation] update elastic stack version for testing 8.6.0-22d60ec9

filebeat/docs/running-on-kubernetes.asciidoc
Update docs to remove reference to /var/lib/docker/containers as default location for container logs. Default location is `/var/log/containers` instead
Update out of date docs
-
=> update docs to remove reference to /var/lib/docker/containers

x-pack/osquerybeat/internal/osqdcli/client.go
Fixes the typo that was causing the osquerybeat to use the wrong logger that was logging into stderr output.
Fixes the wrong logging
=> Osquerybeat: Fix the logging  with the wrong logger

CHANGELOG.next.asciidoc, auditbeat/docs/modules/file_integrity.asciidoc, auditbeat/module/file_integrity/_meta/docs.asciidoc, auditbeat/module/file_integrity/config.go, auditbeat/module/file_integrity/metricset.go, auditbeat/module/file_integrity/scanner.go
This clarifies the behaviour of the auditbeat file integrity module in its handling of symlinks and ensures that the current documented behaviour of resolving path to their absolute path where possible is honored.
The current documentation has been confusing for some users because is does not specify the behaviour wrt the handling of symlinks, and the current documented behaviour is not honored wrt absolute path resolution.
-
=> auditbeat/module/file_integrity: improve documentation and ensure paths are absolute

testing/environments/snapshot.yml
[start_time:Mon, 24 Oct 2022 12:15:56 GMT, release_branch:master, prefix:, end_time:Mon, 24 Oct 2022 16:17:06 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-b8b35931, build_duration_seconds:14470]
=> [automation] update elastic stack version for testing 8.6.0-b8b35931

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 24 Oct 2022 05:14:57 GMT, release_branch:7.17, prefix:, end_time:Mon, 24 Oct 2022 10:06:02 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-0a02d958, build_duration_seconds:17465]
=> [automation] update elastic stack version for testing 7.17.7-0a02d958

testing/environments/snapshot.yml
[start_time:Mon, 24 Oct 2022 00:18:19 GMT, release_branch:8.4, prefix:, end_time:Mon, 24 Oct 2022 08:07:26 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-46f2f222, build_duration_seconds:28147]
=> [automation] update elastic stack version for testing 8.4.4-46f2f222

metricbeat/docker-compose.yml, metricbeat/module/logstash/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
Merge only after the release of 7.17.7.
=> [Release] Update test environments for 7.17.8

testing/environments/snapshot.yml
[start_time:Tue, 25 Oct 2022 00:16:03 GMT, release_branch:8.5, prefix:, end_time:Tue, 25 Oct 2022 08:36:17 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-bdb74671, build_duration_seconds:30014]
=> [automation] update elastic stack version for testing 8.5.0-bdb74671

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-http-endpoint.asciidoc, x-pack/filebeat/input/http_endpoint/handler_test.go, x-pack/filebeat/input/http_endpoint/input.go, x-pack/filebeat/input/http_endpoint/input_test.go
This change adds a pool of http servers that share listening addresses and ports but respond to different mux endpoints.
This reduces configuration complexity and port exposure in filebeat agents.
The tests can be run using the `go test` command in `x-pack/filebeat/input/http_endpoint`.
- Closes #32578
=> x-pack/filebeat/input/http_endpoint: allow http_endpoint instances to share ports

testing/environments/snapshot.yml
[start_time:Wed, 26 Oct 2022 15:48:54 GMT, release_branch:8.4, prefix:, end_time:Wed, 26 Oct 2022 21:02:19 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-d66e996a, build_duration_seconds:18805]
=> [automation] update elastic stack version for testing 8.4.4-d66e996a

testing/environments/snapshot.yml
[start_time:Wed, 26 Oct 2022 15:48:54 GMT, release_branch:master, prefix:, end_time:Wed, 26 Oct 2022 21:14:19 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-a892f234, build_duration_seconds:19525]
=> [automation] update elastic stack version for testing 8.6.0-a892f234

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-httpjson.asciidoc, x-pack/filebeat/input/httpjson/input_test.go
This adds documentation explaining the expected behaviour when an httpjson split processor is invoked on an empty value and adds tests to ensure this behaviour is retained.
Testing changes allow local specification of response bodies and add testing of extra unexpected events when no-event is expected from a test.
The current documentation does not explain the expected behaviour.
-
=> x-pack/filebeat/input/httpjson: test and document empty split behaviour

testing/environments/snapshot.yml
[start_time:Thu, 27 Oct 2022 21:30:37 GMT, release_branch:8.5, prefix:, end_time:Fri, 28 Oct 2022 04:13:48 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-4028b295, build_duration_seconds:24191]
=> [automation] update elastic stack version for testing 8.5.0-4028b295

testing/environments/snapshot.yml
[start_time:Thu, 27 Oct 2022 12:15:57 GMT, release_branch:master, prefix:, end_time:Thu, 27 Oct 2022 21:32:41 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-89d224d2, build_duration_seconds:33404]
=> [automation] update elastic stack version for testing 8.6.0-89d224d2

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 27 Oct 2022 05:15:13 GMT, release_branch:7.17, prefix:, end_time:Thu, 27 Oct 2022 10:58:23 GMT, manifest_version:2.1.0, version:7.17.8-SNAPSHOT, branch:7.17, build_id:7.17.8-d89bf16d, build_duration_seconds:20590]
=> [automation] update elastic stack version for testing 7.17.8-d89bf16d

testing/environments/snapshot.yml
[start_time:Thu, 27 Oct 2022 13:12:21 GMT, release_branch:8.4, prefix:, end_time:Thu, 27 Oct 2022 17:47:34 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-6eb63640, build_duration_seconds:16513]
=> [automation] update elastic stack version for testing 8.4.4-6eb63640

testing/environments/snapshot.yml
[start_time:Sat, 29 Oct 2022 12:15:30 GMT, release_branch:master, prefix:, end_time:Sat, 29 Oct 2022 16:00:26 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-949a38d2, build_duration_seconds:13496]
=> [automation] update elastic stack version for testing 8.6.0-949a38d2

testing/environments/snapshot.yml
[start_time:Sat, 29 Oct 2022 04:07:22 GMT, release_branch:8.5, prefix:, end_time:Sat, 29 Oct 2022 09:13:48 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-f48cdca0, build_duration_seconds:18386]
=> [automation] update elastic stack version for testing 8.5.0-f48cdca0

testing/environments/snapshot.yml
[start_time:Sat, 29 Oct 2022 12:15:37 GMT, release_branch:8.4, prefix:, end_time:Sat, 29 Oct 2022 17:42:22 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-f3b8851a, build_duration_seconds:19605]
=> [automation] update elastic stack version for testing 8.4.4-f3b8851a

CHANGELOG.next.asciidoc, dev-tools/packaging/templates/docker/Dockerfile.tmpl
This puts us on to the latest LTS release of node. I like to just modify [run.sh](https://github.com/elastic/synthetics-dev/tree/main/heartbeat-testing/run-current) from here.
=> [Heartbeat] Update node to v18.12.0 in container image

testing/environments/snapshot.yml
[start_time:Mon, 31 Oct 2022 14:45:15 GMT, release_branch:master, prefix:, end_time:Mon, 31 Oct 2022 19:08:41 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-26dc1164, build_duration_seconds:15806]
=> [automation] update elastic stack version for testing 8.6.0-26dc1164

testing/environments/snapshot.yml
[start_time:Mon, 31 Oct 2022 12:16:05 GMT, release_branch:8.4, prefix:, end_time:Mon, 31 Oct 2022 18:30:49 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-55734bd7, build_duration_seconds:22484]
=> [automation] update elastic stack version for testing 8.4.4-55734bd7

CHANGELOG.next.asciidoc, x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go, x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
Check if the identifier includes dimensionSeparator `,` before the event is initialized. With this change, tags will be added into events when the target identifier is a subset of the whole string. For example: without this PR, tags will be added to only identifier `database-1`. With this PR, tags will be added to not only `database-1`, but also `WRITER,database-1`.
=> [AWS] Add tags to events based on parsed identifier

metricbeat/module/elasticsearch/node/_meta/docs.asciidoc, metricbeat/module/elasticsearch/node_stats/_meta/docs.asciidoc
Specifically fixes links that were missed in https://github.com/elastic/beats/pull/33487.
=> [8.3][DOCS] Fix hard-coded mapping type doc link

NOTICE.txt, go.mod, go.sum
This update the deps for elastic-agent-client so we can take advantage of support for diagnostics in V2.
=> Update V2 elastic-agent-client dependency

docs/devguide/metricset-details.asciidoc, metricbeat/module/elasticsearch/node/_meta/docs.asciidoc, metricbeat/module/elasticsearch/node_stats/_meta/docs.asciidoc
=> [7.13][DOCS] Fix hard-coded mapping type doc link

testing/environments/snapshot.yml
[start_time:Wed, 2 Nov 2022 12:17:07 GMT, release_branch:master, prefix:, end_time:Wed, 2 Nov 2022 16:53:57 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-8a615646, build_duration_seconds:16610]
=> [automation] update elastic stack version for testing 8.6.0-8a615646

testing/environments/snapshot.yml
[start_time:Wed, 2 Nov 2022 00:16:22 GMT, release_branch:8.4, prefix:, end_time:Wed, 2 Nov 2022 05:57:50 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-dcd4a95f, build_duration_seconds:20488]
=> [automation] update elastic stack version for testing 8.4.4-dcd4a95f

testing/environments/snapshot.yml
[start_time:Thu, 3 Nov 2022 12:16:03 GMT, release_branch:master, prefix:, end_time:Thu, 3 Nov 2022 16:45:36 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-3f5f98b7, build_duration_seconds:16173]
=> [automation] update elastic stack version for testing 8.6.0-3f5f98b7

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 3 Nov 2022 05:15:37 GMT, release_branch:7.17, prefix:, end_time:Thu, 3 Nov 2022 09:59:11 GMT, manifest_version:2.1.0, version:7.17.8-SNAPSHOT, branch:7.17, build_id:7.17.8-1d146f89, build_duration_seconds:17014]
=> [automation] update elastic stack version for testing 7.17.8-1d146f89

testing/environments/snapshot.yml
[start_time:Thu, 3 Nov 2022 21:35:24 GMT, release_branch:8.5, prefix:, end_time:Fri, 4 Nov 2022 02:17:02 GMT, manifest_version:2.1.0, version:8.5.1-SNAPSHOT, branch:8.5, build_id:8.5.1-7fd6ffae, build_duration_seconds:16898]
=> [automation] update elastic stack version for testing 8.5.1-7fd6ffae

filebeat/_meta/config/filebeat.inputs.reference.yml.tmpl, filebeat/filebeat.reference.yml, x-pack/filebeat/filebeat.reference.yml
Current config is not valid as it contains example values which aren't commented out.
Results in error: `Exiting: error loading config file: yaml: line xxx: did not find expected key`
Reference `filebeat.yml` isn't valid YAML
=> Fix missing comment in filebeat.reference.yml

testing/environments/snapshot.yml
[start_time:Sun, 6 Nov 2022 12:15:33 GMT, release_branch:8.5, prefix:, end_time:Sun, 6 Nov 2022 17:43:52 GMT, manifest_version:2.1.0, version:8.5.1-SNAPSHOT, branch:8.5, build_id:8.5.1-2ceb7fad, build_duration_seconds:19699]
=> [automation] update elastic stack version for testing 8.5.1-2ceb7fad

testing/environments/snapshot.yml
[start_time:Fri, 4 Nov 2022 14:42:08 GMT, release_branch:master, prefix:, end_time:Fri, 4 Nov 2022 22:58:50 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-f20b7179, build_duration_seconds:29802]
=> [automation] update elastic stack version for testing 8.6.0-f20b7179

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Fri, 4 Nov 2022 13:53:36 GMT, release_branch:7.17, prefix:, end_time:Fri, 4 Nov 2022 20:38:56 GMT, manifest_version:2.1.0, version:7.17.8-SNAPSHOT, branch:7.17, build_id:7.17.8-a281a566, build_duration_seconds:24320]
=> [automation] update elastic stack version for testing 7.17.8-a281a566

x-pack/osquerybeat/internal/osqdcli/client.go, x-pack/osquerybeat/internal/osqdcli/client_test.go
Preserve the field original value in the result even if it osquerybeat the type conversion in the case where the column value type doesn't match the actual value type.
For more detailed information refer to the 
https://github.com/elastic/beats/issues/33586
Fixes the issue with missing column value in the query results. In this particular case the queries that use ```group_concat``` function are affected.
Run query 
```
SELECT group_concat(DISTINCT port) as data FROM listening_ports
```
Verify the one result is returned
- Closes https://github.com/elastic/beats/issues/33586
Verified it's working after the change
=> Osquerybeat: Fix missing result values when the value can not be converted into expected type

CHANGELOG.next.asciidoc, filebeat/beater/filebeat.go, libbeat/monitoring/report/log/log.go, libbeat/publisher/pipeline/monitoring.go
The monitoring log reporting applies serial differencing to the filebeat.events.active value. But this value is used as a gauge by Filebeat so it can increase and decrease. So by reporting `current - prev` this can result in negative values that are not as useful as knowing the full amount of active events.
This metric is [decremented](https://github.com/elastic/beats/blob/cab8871124af7a6855a482e62a416bbd979fb542/filebeat/beater/channels.go#L101) when an event is ACked.
It helps when analyzing logs that contain "Non-zero metrics in the last 30s".
=> [Filebeat] Treat filebeat.events.active as gauge in monitoring log reporter

testing/environments/snapshot.yml
[start_time:Tue, 8 Nov 2022 12:16:08 GMT, release_branch:8.5, prefix:, end_time:Wed, 9 Nov 2022 04:55:08 GMT, manifest_version:2.1.0, version:8.5.1-SNAPSHOT, branch:8.5, build_id:8.5.1-2041424b, build_duration_seconds:59940]
=> [automation] update elastic stack version for testing 8.5.1-2041424b

testing/environments/snapshot.yml
[start_time:Tue, 8 Nov 2022 12:16:12 GMT, release_branch:master, prefix:, end_time:Tue, 8 Nov 2022 19:54:15 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-da453972, build_duration_seconds:27483]
=> [automation] update elastic stack version for testing 8.6.0-da453972

Jenkinsfile, Makefile, dev-tools/make/mage-install.mk
Original PR https://github.com/elastic/beats/pull/33083
=> [backport 8.5] Fix installation of mage with go 1.18

.ci/packaging.groovy, CHANGELOG.next.asciidoc
reduce the size of the Beats and Agent release artifacts, possible significantly. It should also lead to a small increase in efficiency.
Setting DEV=true includes debug symbols in the released binary and disabled most build optimizations. Unrequired for releases
=> packaging: staging artifacts with DEV=false

testing/environments/snapshot.yml
[start_time:Thu, 10 Nov 2022 00:15:49 GMT, release_branch:8.5, prefix:, end_time:Thu, 10 Nov 2022 04:24:22 GMT, manifest_version:2.1.0, version:8.5.1-SNAPSHOT, branch:8.5, build_id:8.5.1-6bdef2c7, build_duration_seconds:14913]
=> [automation] update elastic stack version for testing 8.5.1-6bdef2c7

testing/environments/snapshot.yml
[start_time:Wed, 9 Nov 2022 00:18:40 GMT, release_branch:master, prefix:, end_time:Wed, 9 Nov 2022 05:07:05 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-c9d1a5e9, build_duration_seconds:17305]
=> [automation] update elastic stack version for testing 8.6.0-c9d1a5e9

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 9 Nov 2022 05:16:53 GMT, release_branch:7.17, prefix:, end_time:Wed, 9 Nov 2022 10:44:22 GMT, manifest_version:2.1.0, version:7.17.8-SNAPSHOT, branch:7.17, build_id:7.17.8-e6d29314, build_duration_seconds:19649]
=> [automation] update elastic stack version for testing 7.17.8-e6d29314

CHANGELOG.next.asciidoc, x-pack/filebeat/input/httpjson/split.go, x-pack/filebeat/input/httpjson/split_test.go
This is an alternative proposal for #30368, it adds support for splitting arrays of arrays and arrays of strings. It takes the tests written by @legoguy1000 from #30368 with minor modification.
This is a requested feature from a number of users, see #30345, and the behaviour appears from the documentation to be allowed.
- Fixes #30345
- Closes #30368
=> x-pack/filebeat/input/httpjson: fix handling of array of string/array

CHANGELOG.next.asciidoc, metricbeat/module/system/filesystem/filesystem.go, metricbeat/module/system/fsstat/fsstat.go
This fixes two bugs:
- the `system.filesystem` metricset will hard-fail if it encounters a filesystem it can't fetch stats for, instead of merely skipping the given filesystem
- `system.fsstat` had a bad logging statement.
These are both bugs.
=> Fix loop in filesystemn reporting and debug statement in fsstat

testing/environments/snapshot.yml
[start_time:Thu, 10 Nov 2022 12:15:45 GMT, release_branch:8.5, prefix:, end_time:Thu, 10 Nov 2022 17:34:17 GMT, manifest_version:2.1.0, version:8.5.1-SNAPSHOT, branch:8.5, build_id:8.5.1-1f91140d, build_duration_seconds:19112]
=> [automation] update elastic stack version for testing 8.5.1-1f91140d

testing/environments/snapshot.yml
[start_time:Thu, 10 Nov 2022 17:51:20 GMT, release_branch:master, prefix:, end_time:Thu, 10 Nov 2022 23:34:33 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-62908926, build_duration_seconds:20593]
=> [automation] update elastic stack version for testing 8.6.0-62908926

testing/environments/snapshot.yml
[start_time:Mon, 14 Nov 2022 00:15:30 GMT, release_branch:8.5, prefix:, end_time:Mon, 14 Nov 2022 04:51:59 GMT, manifest_version:2.1.0, version:8.5.1-SNAPSHOT, branch:8.5, build_id:8.5.1-d7343c55, build_duration_seconds:16589]
=> [automation] update elastic stack version for testing 8.5.1-d7343c55

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Sun, 13 Nov 2022 05:15:09 GMT, release_branch:7.17, prefix:, end_time:Sun, 13 Nov 2022 11:12:07 GMT, manifest_version:2.1.0, version:7.17.8-SNAPSHOT, branch:7.17, build_id:7.17.8-8be7042c, build_duration_seconds:21418]
=> [automation] update elastic stack version for testing 7.17.8-8be7042c

dev-tools/packaging/templates/ironbank/heartbeat/hardening_manifest.yaml
`llvm-libs-13.0.1-1.module+el8.6.0+14118+d530a951.x86_64.rpm` is not accessible so let's use `llvm-libs-13.0.1-1.module+el8.6.0+825+7e27476a.x86_64.rpm` from  https://rockylinux-distro.1gservers.com/
fixes
```
[2022-11-11T02:32:37.272Z] Downloading https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi8/8/x86_64/appstream/os/Packages/l/llvm-libs-13.0.1-1.module+el8.6.0+14118+d530a951.x86_64.rpm
[2022-11-11T02:32:37.975Z] curl: (22) The requested URL returned error: 404 Not Found
```
=> ironbank: update URL for llvm-libs

.ci/packaging.groovy
Prepare the CI workspace so it can reuse the same worker for packaigng staging artifacts
The packaging for `elastic-agent` generates files with different permissions hence it's not possible to delete them and run the packaging again
=> ci: fix permissions when reusing workspace to package staging

CHANGELOG.next.asciidoc, x-pack/filebeat/module/google_workspace/admin/config/config.yml, x-pack/filebeat/module/google_workspace/config/common.js, x-pack/filebeat/module/google_workspace/drive/config/config.yml, x-pack/filebeat/module/google_workspace/groups/config/config.yml, x-pack/filebeat/module/google_workspace/login/config/config.yml, x-pack/filebeat/module/google_workspace/saml/config/config.yml, x-pack/filebeat/module/google_workspace/user_accounts/config/config.yml, x-pack/filebeat/module/google_workspace/user_accounts/config/pipeline.js
Backports fixes made in the google workspace integration.
Closes https://github.com/elastic/beats/issues/33636
=> [Filebeat][Google workspace] Backport integration fixes

.github/workflows/golangci-lint.yml, .golangci.yml
This PR enables CGO in the github actions linter. We need this as right now, with CGO disabled, the `typecheck` sublinter will choke on any imported function or type that's constrained to cgo. This is a source of frequent headaches in the system module, which frequently imports cgo code.
However, there's another problem: if we enable cgo, the `typecheck` linter fails in a different way, particularly it can't seem to handle embedded struct fields or certain kinds of imports. To add insult to injury, we can't actually disable `typecheck`, since it's not actually a linter, and just a frontend for the go compiler that reports any compile errors. However, we have the rest of the CI to deal with compiler-level errors, rendering this unnecessary, even though we can't disable it. As a workaround, …
=> Enable cgo and fix typecheck linter for github linter

CHANGELOG-developer.next.asciidoc, libbeat/beat/pipeline.go, libbeat/publisher/processing/default.go, libbeat/publisher/processing/default_test.go
Control over the addition of the "generalizeEvent" processor into the publishing pipeline was only available at the Beat level. This adds a new option that can be set by input's when they create their beat.Client.
This allows inputs to override the Beat's default behavior. My expected use case it to disable event normalization for inputs that are known to only produce beat.Events containing the standard data types expected by the processors and outputs (i.e. map[string]interface{} containing primitives, slices, or other map[string]interface{}).
Inputs would want to disable the event normalization processor if they can because it adds unnecessary processing (recurses over the fields and often allocates).
An example usage:
```go
// Create client for publishing events and receive …
```
=> [libbeat] Allow per beat.Client control of event normalization

CHANGELOG.next.asciidoc, NOTICE.txt, go.mod, go.sum, x-pack/filebeat/docs/inputs/input-cel.asciidoc, x-pack/filebeat/input/cel/config.go, x-pack/filebeat/input/cel/config_auth.go, x-pack/filebeat/input/cel/config_test.go, x-pack/filebeat/input/cel/input.go, x-pack/filebeat/input/cel/input_manager.go, x-pack/filebeat/input/cel/input_test.go, x-pack/filebeat/input/cel/testdata/corrupted-log-1.ndjson, x-pack/filebeat/input/cel/testdata/credentials.json, x-pack/filebeat/input/cel/testdata/invalid_credentials.json, x-pack/filebeat/input/cel/testdata/log-1.ndjson, x-pack/filebeat/input/default-inputs/inputs_other.go
This adds a new input to filebeat that allows processing of datastreams using the Common Expression Language.
It provides a consistent framework for generalised input processing.
-
=> x-pack/filebeat/input/cel: new input

testing/environments/snapshot.yml
[start_time:Mon, 14 Nov 2022 12:15:55 GMT, release_branch:8.5, prefix:, end_time:Mon, 14 Nov 2022 16:21:00 GMT, manifest_version:2.1.0, version:8.5.1-SNAPSHOT, branch:8.5, build_id:8.5.1-49e04c16, build_duration_seconds:14705]
=> [automation] update elastic stack version for testing 8.5.1-49e04c16

testing/environments/snapshot.yml
[start_time:Mon, 14 Nov 2022 13:02:15 GMT, release_branch:master, prefix:, end_time:Mon, 14 Nov 2022 17:48:03 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-0c44a3fc, build_duration_seconds:17148]
=> [automation] update elastic stack version for testing 8.6.0-0c44a3fc

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 14 Nov 2022 05:15:11 GMT, release_branch:7.17, prefix:, end_time:Mon, 14 Nov 2022 11:11:46 GMT, manifest_version:2.1.0, version:7.17.8-SNAPSHOT, branch:7.17, build_id:7.17.8-581ea684, build_duration_seconds:21395]
=> [automation] update elastic stack version for testing 7.17.8-581ea684

CHANGELOG.next.asciidoc, x-pack/filebeat/input/awss3/input.go
Disable event normalization for the aws-s3 input to reduce allocations when processing events. The input only produces basic types in its events. Either it puts a string into the `message` field or it decodes json into a map[string]interface with encoding/json. Both of those should be fine for the downstream processors and outputs.
Relates #33657
It makes Filebeat more efficient.
- Relates #33657
=> [Filebeat] aws-s3 - Disable event normalization processing

libbeat/docs/shared-ssl-config.asciidoc
This commit adds an example of how to extract the HEX encoded SHA-256 fingerprint from a CA certificate using openssl, awk and sed. Those tools should be available on most Unix-like systems.
It helps users to get the HEX encoded SHA-256 fingerprint in the correct format to be used as `ssl.ca_trusted_fingerprint`
You will need to have Docker installed to build the …
=> docs: add example to extract HEX encoded fingerprint from certificate

.ci/packaging.groovy
Disable DRA for `7.17`
The packaging pipeline with DRA should support 8.2+
=> release: DRA for 7.17 is not available

.golangci.yml
This issue was found as part of https://github.com/elastic/beats/pull/31233 , where it looks like they ran into another error condition of `typecheck` that I hadn't before. This adds another rule to hopefully fix that.
=> Add another rule for typecheck linter under cgo

testing/environments/snapshot.yml
[start_time:Tue, 15 Nov 2022 05:40:39 GMT, release_branch:master, prefix:, end_time:Tue, 15 Nov 2022 13:07:48 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-9a0f87a9, build_duration_seconds:26829]
=> [automation] update elastic stack version for testing 8.6.0-9a0f87a9

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 15 Nov 2022 05:15:13 GMT, release_branch:7.17, prefix:, end_time:Tue, 15 Nov 2022 10:45:07 GMT, manifest_version:2.1.0, version:7.17.8-SNAPSHOT, branch:7.17, build_id:7.17.8-e4279e1a, build_duration_seconds:19794]
=> [automation] update elastic stack version for testing 7.17.8-e4279e1a

CHANGELOG.next.asciidoc, filebeat/processor/add_kubernetes_metadata/matchers.go
This was happening due to the error level logging when the log path matcher detected a `log.file.path` that does not start with a standard Docker container log folder `/var/lib/docker/containers` because AKS dropped support for Docker in September 2022 and switched to containerd.
It looks like this message was not supposed to be on the error level in the first place since it just means that the matcher didn't match and it's not an error. But it was mistakenly promoted from the debug level in https://github.com/elastic/beats/pull/16866 most likely because the message started with `Error` and looked confusing.
This a partial fix to unblock our customers, but we still need to come up with the full AKS/containerd support in a follow up change.
There is [a lot feedback from …
=> Fix error spam on AKS

testing/environments/snapshot.yml
[start_time:Wed, 16 Nov 2022 03:20:38 GMT, release_branch:master, prefix:, end_time:Wed, 16 Nov 2022 14:41:29 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-41eabcfc, build_duration_seconds:40851]
=> [automation] update elastic stack version for testing 8.6.0-41eabcfc

testing/environments/snapshot.yml
[start_time:Fri, 18 Nov 2022 00:14:42 GMT, release_branch:master, prefix:, end_time:Fri, 18 Nov 2022 04:38:35 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-eb092238, build_duration_seconds:15833]
=> [automation] update elastic stack version for testing 8.7.0-eb092238

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 17 Nov 2022 05:15:21 GMT, release_branch:7.17, prefix:, end_time:Thu, 17 Nov 2022 11:15:49 GMT, manifest_version:2.1.0, version:7.17.8-SNAPSHOT, branch:7.17, build_id:7.17.8-ca244ec8, build_duration_seconds:21628]
=> [automation] update elastic stack version for testing 7.17.8-ca244ec8

testing/environments/snapshot.yml
[start_time:Thu, 17 Nov 2022 12:21:14 GMT, release_branch:8.5, prefix:, end_time:Thu, 17 Nov 2022 16:55:27 GMT, manifest_version:2.1.0, version:8.5.2-SNAPSHOT, branch:8.5, build_id:8.5.2-733d317b, build_duration_seconds:16453]
=> [automation] update elastic stack version for testing 8.5.2-733d317b

.github/CODEOWNERS, CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-cel.asciidoc, x-pack/filebeat/input/cel/input.go, x-pack/filebeat/input/cel/transport_other.go, x-pack/filebeat/input/cel/transport_windows.go
This adds support for requests to endpoints over Unix sockets and Windows named pipes using the `https?+(unix|npipe)` schemes. No testing at this stage since cel test infrastructure assumes a TCP transport.
It also marks the cel input as owned by SEI to avoid troubling agent-data-plane in the future.
From #33571
> This would be used connect to internal services that are only exposed locally. Services like [Beats HTTP monitoring endpoint](https://www.elastic.co/guide/en/beats/filebeat/current/http-endpoint.html) and Docker have APIs that listen on unix sockets. It would be useful if httpjson (and any future inputs that also monitor arbitrary HTTP services) could monitor data from these local APIs.
- Relates #33571
=> x-pack/filebeat/input/cel: add support for http+{unix,npipe} schemes

libbeat/processors/add_observer_metadata/docs/add_observer_metadata.asciidoc
Looks like this processor was renamed or someone made a copy/paste mistake.
=> [DOCS] Fix incorrect processor name in add_observer_metadata processor docs

metricbeat/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
This updates the test environments to next minor release which is 8.7.0.
=> [Release] Update test environment to 8.7.0

.github/workflows/check-docs.yml, NOTICE.txt, go.mod, go.sum, metricbeat/docs/modules/apache.asciidoc, metricbeat/docs/modules/nginx.asciidoc, metricbeat/module/apache/_meta/Dockerfile, metricbeat/module/apache/_meta/docs.asciidoc, metricbeat/module/apache/_meta/httpd.conf, metricbeat/module/apache/_meta/supported-versions.yml, metricbeat/module/apache/docker-compose.yml, metricbeat/module/logstash/logstash_integration_test.go, metricbeat/module/mongodb/_meta/Dockerfile, metricbeat/module/mongodb/docker-compose.yml, metricbeat/module/nginx/_meta/Dockerfile, metricbeat/module/nginx/_meta/docs.asciidoc, metricbeat/module/nginx/docker-compose.yml
The old tests were based on Debian Jessie released in April 2015 (end-of-life on June 30, 2020).
We started having problems with expired GPG keys when installing dependencies in our Docker files.
Our CI is currently failing with:
```
[2022-11-23T02:15:50.651Z] W: GPG error: http://security.debian.org/ jessie/updates InRelease: The following signatures were invalid: KEYEXPIRED 1668892417 The following signatures couldn't be verified because the public key is not available: NO_PUBKEY AA8E81B4331F7F50
[2022-11-23T02:15:50.651Z] W: GPG error: http://nginx.org/ jessie InRelease: The following signatures were invalid: KEYEXPIRED 1471427554
[2022-11-23T02:15:50.651Z] W: GPG error: http://httpredir.debian.org/ jessie Release: The following signatures were invalid: KEYEXPIRED 1668891673
```
- …
=> Update test versions of NGINX, Apache and MongoDB

docs/devguide/create-module.asciidoc
Backports https://github.com/elastic/beats/pull/33318
This PR fixes the following hard-coded link, which will fail when we move away from "master" URLs:
> 17:07:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/devguide/8.5/creating-metricbeat-module.html contains broken links to:
17:07:03 INFO:build_docs:   - en/beats/metricbeat/master/metricbeat-module-mysql.html
(cherry picked from commit b8b87c3ff91d35082cac23039521e086dc0a343a)
=> [7.16](backport #33318)[DOCS] Fix hard-coded documentation link (#33318)

script/build_docs.sh
This makes sure that the `make docs` target is able to find index.asciidoc files on systems where GOPATH has not been set.
GOPATH is not a requirement for a functional go install, so having a failure in this case is a friction for contributors.
-
=> scripts/build_docs: don't assume GOPATH is set

libbeat/monitoring/inputmon/input.go, x-pack/filebeat/input/awscloudwatch/cloudwatch.go, x-pack/filebeat/input/awscloudwatch/input.go, x-pack/filebeat/input/awscloudwatch/metrics.go, x-pack/filebeat/input/awscloudwatch/processor.go, x-pack/filebeat/input/awss3/input.go, x-pack/filebeat/input/awss3/input_benchmark_test.go, x-pack/filebeat/input/awss3/metrics.go, x-pack/filebeat/input/awss3/metrics_test.go, x-pack/filebeat/input/awss3/s3.go, x-pack/filebeat/input/awss3/s3_objects.go, x-pack/filebeat/input/awss3/sqs.go, x-pack/filebeat/input/awss3/sqs_s3_event.go, x-pack/filebeat/input/cel/input.go, x-pack/filebeat/input/lumberjack/input.go, x-pack/filebeat/input/lumberjack/metrics.go, x-pack/filebeat/input/lumberjack/server.go
Add a helper package to ensure that input metrics are registered in a consistent manner.
This helps to ensure that metrics for inputs are registered consistently with an `input` and an `id`. Plus it will scrub dots (`.`) from the monitoring namespace key for the input to prevent nesting.
=> [Filebeat] Add inputmon package to unify input metrics

testing/environments/snapshot.yml
[start_time:Wed, 30 Nov 2022 00:14:37 GMT, release_branch:8.6, prefix:, end_time:Wed, 30 Nov 2022 03:40:29 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-ecfefdaf, build_duration_seconds:12352]
=> [automation] update elastic stack version for testing 8.6.0-ecfefdaf

CHANGELOG.next.asciidoc, NOTICE.txt, go.mod, go.sum
Update to https://github.com/elastic/go-sysinfo/releases/tag/v1.9.0
Various fixes. Some related to OS metadata collection.
=> Update to github.com/elastic/go-sysinfo v1.9.0

testing/environments/snapshot.yml
[start_time:Mon, 28 Nov 2022 00:15:35 GMT, release_branch:8.5, prefix:, end_time:Mon, 28 Nov 2022 04:44:32 GMT, manifest_version:2.1.0, version:8.5.3-SNAPSHOT, branch:8.5, build_id:8.5.3-a0b682b9, build_duration_seconds:16137]
=> [automation] update elastic stack version for testing 8.5.3-a0b682b9

dev-tools/mage/pkgdeps.go
Older versions of Debian have expired GPG keys. In this case `-y` is not enough and `apt-get` requires an additional `--force-yes`.
Packaging jobs fail on 7.17 due to this flag missing https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fpackaging/detail/PR-33843/4/pipeline/150/
~- [ ] I have made corresponding change to the default configuration files`
=> Enforce "yes" when install debian packages in packaging

dev-tools/packaging/package_test.go
Adds support for excluded paths when testing the packaging.
After an update in heartbeat we have have a path like `usr/share/heartbeat/.node/node/lib/node_modules/@elastic/synthetics/templates/lightweight/heartbeat.yml` which matches the `configFilePattern` which causes a permission check which the file does not satisfy. It has nothing to do with the actual heartbeat configuration file.
See the failure here https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fpackaging/detail/PR-33843/4/pipeline/150/
~- [ ] I have added tests that prove my fix is effective or that my …
=> Add support for excluded paths in packaging

CHANGELOG.next.asciidoc, packetbeat/procs/procs_linux.go
This reduces the logging level of ENOENT errors when attempting to map sockets to processes.
When processes are short lived this spams the logs with unhelpful log lines.
- Fixes #33793
=> packetbeat/procs: don't log at ERROR for file not found

testing/environments/snapshot.yml
[start_time:Thu, 1 Dec 2022 00:15:48 GMT, release_branch:8.5, prefix:, end_time:Thu, 1 Dec 2022 05:00:21 GMT, manifest_version:2.1.0, version:8.5.3-SNAPSHOT, branch:8.5, build_id:8.5.3-268167d7, build_duration_seconds:17073]
=> [automation] update elastic stack version for testing 8.5.3-268167d7

testing/environments/snapshot.yml
[start_time:Thu, 1 Dec 2022 00:14:50 GMT, release_branch:8.6, prefix:, end_time:Thu, 1 Dec 2022 04:12:49 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-87c26073, build_duration_seconds:14279]
=> [automation] update elastic stack version for testing 8.6.0-87c26073

x-pack/auditbeat/magefile.go
It's using Debian Wheezy which has expired GPG keys, we need additional flags in order to package auditbeat now.
So, the packaging job would not fail like this one https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fpackaging/detail/PR-33843/10/pipeline/141/
=> Add workaround for expried GPG keys for auditbeat packaging

CHANGELOG.next.asciidoc, filebeat/docs/inputs/input-udp.asciidoc, filebeat/input/udp/input.go, filebeat/inputsource/common/dgram/handler.go
This adds metrics for UDP packet count and total bytes, and histograms for time required to process UDP packets prior to acking from a publication and time between UDP packet arrivals.
This allows us to help users configure their systems to match the requirements that they have.
=> filebeat/input/udp: add initial UDP metrics support

filebeat/input/udp/input.go
This fixes an incorrect nil check that resulted from an incomplete test inversion during development.
The current code causes a panic in the case that a metric is closed and reused.
-
=> filebeat/input/udp: fix inverted nil check logic

testing/environments/snapshot.yml
[start_time:Thu, 1 Dec 2022 20:00:57 GMT, release_branch:8.6, prefix:, end_time:Fri, 2 Dec 2022 01:32:22 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-f96862e0, build_duration_seconds:19885]
=> [automation] update elastic stack version for testing 8.6.0-f96862e0

testing/environments/snapshot.yml
[start_time:Fri, 2 Dec 2022 00:15:08 GMT, release_branch:master, prefix:, end_time:Fri, 2 Dec 2022 04:30:28 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-1b0dc867, build_duration_seconds:15320]
=> [automation] update elastic stack version for testing 8.7.0-1b0dc867

testing/environments/snapshot.yml
[start_time:Thu, 1 Dec 2022 12:15:51 GMT, release_branch:8.5, prefix:, end_time:Thu, 1 Dec 2022 16:11:54 GMT, manifest_version:2.1.0, version:8.5.3-SNAPSHOT, branch:8.5, build_id:8.5.3-1625ae9f, build_duration_seconds:14163]
=> [automation] update elastic stack version for testing 8.5.3-1625ae9f

CHANGELOG.next.asciidoc, x-pack/filebeat/module/panw/panos/ingest/pipeline.yml
This allows the ingest pipeline to attempt to process a message that has already had its event.original set (most likely by logstash with the ecs_compatibily mode set to true), but notes this with a warning in error.message in case there is a failure later in the pipeline, and to prompt the user to check the cause for the field being set.
The alternative approach of using on_failure was not used for performance reasons since that would depend on an exceptiø mechanism. Noted here for history
- rename:
field: message
target_field: event.original
on_failure:
- append: field: error.message value: 'event.original is set before start of ingest pipeline'
The top-level on_error handler is changed to an append to allow the error message set here to survive other errors.
Currently the module can …
=> x-pack/filebeat/module/panw: work around already set event.original field

CHANGELOG.next.asciidoc, packetbeat/protos/memcache/memcache.go, packetbeat/protos/memcache/plugin_udp.go
When a *transaction is constructed from a UDP stream, but has no request and no response, onTransaction is handed a nil *transaction, resulting in a panic in Event when the *transaction.Notes field is accessed. The panic is not recovered by ParseUDP's recover because the panic happens in a separate goroutine. So be more careful with pointer dereferencing in this path and put a separate recover in the time.AfterFunc-called closure.
The panic causes loss of packetbeat service in some situations.
- Fixes #33852
=> packetbeat/protos/memcache: don't panic when a transaction is empty

testing/environments/snapshot.yml
[start_time:Mon, 5 Dec 2022 00:14:47 GMT, release_branch:8.6, prefix:, end_time:Mon, 5 Dec 2022 03:44:34 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-368aeeae, build_duration_seconds:12587]
=> [automation] update elastic stack version for testing 8.6.0-368aeeae

testing/environments/snapshot.yml
[start_time:Mon, 5 Dec 2022 00:15:25 GMT, release_branch:8.5, prefix:, end_time:Mon, 5 Dec 2022 04:43:34 GMT, manifest_version:2.1.0, version:8.5.3-SNAPSHOT, branch:8.5, build_id:8.5.3-0a7c209d, build_duration_seconds:16089]
=> [automation] update elastic stack version for testing 8.5.3-0a7c209d

testing/environments/snapshot.yml
[start_time:Sun, 4 Dec 2022 12:15:05 GMT, release_branch:master, prefix:, end_time:Sun, 4 Dec 2022 16:28:20 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-1fff43d4, build_duration_seconds:15195]
=> [automation] update elastic stack version for testing 8.7.0-1fff43d4

testing/environments/snapshot.yml
[start_time:Mon, 5 Dec 2022 12:14:24 GMT, release_branch:master, prefix:, end_time:Mon, 5 Dec 2022 16:03:39 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-7fe23b13, build_duration_seconds:13755]
=> [automation] update elastic stack version for testing 8.7.0-7fe23b13

testing/environments/snapshot.yml
[start_time:Mon, 5 Dec 2022 12:15:33 GMT, release_branch:8.5, prefix:, end_time:Mon, 5 Dec 2022 16:55:18 GMT, manifest_version:2.1.0, version:8.5.3-SNAPSHOT, branch:8.5, build_id:8.5.3-55d94167, build_duration_seconds:16785]
=> [automation] update elastic stack version for testing 8.5.3-55d94167

CHANGELOG.next.asciidoc, x-pack/filebeat/input/cel/input.go
Currently, the HTTP client requests do not make use of context.Context so cancellation errors are swallowed without being handed back to the cel event loop, resulting in inability to cancel the input. So check for cancellation at the start of each event loop iteration unconditionally. The mito/lib.HTTP extension will also be altered to include context passing, but this is an optimisation that will reduce delay between SIGINT and event loop cancellation rather than correctness of the cancellation logic.
Currently cannot cancel running filebeat with a CEL input that is blocked in an HTTP request.
- Fixes #33962
=> x-pack/filebeat/input/cel: fix handling of cancellation

testing/environments/snapshot.yml
[start_time:Tue, 6 Dec 2022 12:16:04 GMT, release_branch:8.5, prefix:, end_time:Tue, 6 Dec 2022 16:48:24 GMT, manifest_version:2.1.0, version:8.5.3-SNAPSHOT, branch:8.5, build_id:8.5.3-e63a0e72, build_duration_seconds:16340]
=> [automation] update elastic stack version for testing 8.5.3-e63a0e72

testing/environments/snapshot.yml
[start_time:Tue, 6 Dec 2022 12:14:42 GMT, release_branch:master, prefix:, end_time:Tue, 6 Dec 2022 15:55:56 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-2c7c2bad, build_duration_seconds:13274]
=> [automation] update elastic stack version for testing 8.7.0-2c7c2bad

CHANGELOG.next.asciidoc, NOTICE.txt, go.mod, go.sum, x-pack/filebeat/docs/inputs/input-cel.asciidoc, x-pack/filebeat/input/cel/config.go, x-pack/filebeat/input/cel/input.go
This brings in improvments in the collection extension behaviour and support for context.Context in the HTTP extension.
elastic/mito@2f0f2875 lib: add HTTPWithContext cel.EnvOption
elastic/mito@fa5b7a0f lib: allow specification of dotted path elements in collate and drop
These are optimisations for cancellation and improvements to handling JSON paths.
- For #33962
=> mod,x-pack/filebeat/input/cel: update mito dependency

testing/environments/snapshot.yml
[start_time:Thu, 8 Dec 2022 00:14:56 GMT, release_branch:8.6, prefix:, end_time:Thu, 8 Dec 2022 04:09:41 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-7c9fd7a8, build_duration_seconds:14085]
=> [automation] update elastic stack version for testing 8.6.0-7c9fd7a8

CHANGELOG.next.asciidoc, x-pack/filebeat/input/cel/input.go
Previously, when an error in evaluation or result deserialisation occurred, the entire input activation container was returned instead of a valid state. The result of this was that the state would nest on each iteration of the eval event loop. In cases where errors can happen frequently, this can result in unbounded memory use.
Also improve the robustness of the want_more flag; the old code would continue with the loop if state["want_more"] was unset since any(nil) does not equal false.
Unbounded memory use.
- Fixes #33992
=> x-pack/filebeat/input/cel: fix eval state return on error

CHANGELOG.next.asciidoc, x-pack/filebeat/input/cel/input.go, x-pack/filebeat/input/cel/input_test.go
Previously, non-200/non-429 status codes would cause an immediate retry, resulting in spamming the server. Treat these responses as an error and wait until the next event period.
- Fixes #33999
=> x-pack/filebeat/input/cel: fix handling of non-200/non-429 status codes

testing/environments/snapshot.yml
[start_time:Fri, 9 Dec 2022 00:14:54 GMT, release_branch:8.6, prefix:, end_time:Fri, 9 Dec 2022 04:22:16 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-3bb8e729, build_duration_seconds:14842]
=> [automation] update elastic stack version for testing 8.6.0-3bb8e729

testing/environments/snapshot.yml
[start_time:Fri, 9 Dec 2022 00:15:07 GMT, release_branch:master, prefix:, end_time:Fri, 9 Dec 2022 03:47:13 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-59d5589a, build_duration_seconds:12726]
=> [automation] update elastic stack version for testing 8.7.0-59d5589a

testing/environments/snapshot.yml
[start_time:Thu, 8 Dec 2022 00:15:29 GMT, release_branch:8.5, prefix:, end_time:Thu, 8 Dec 2022 05:18:52 GMT, manifest_version:2.1.0, version:8.5.3-SNAPSHOT, branch:8.5, build_id:8.5.3-91bdfab4, build_duration_seconds:18203]
=> [automation] update elastic stack version for testing 8.5.3-91bdfab4

testing/environments/snapshot.yml
[start_time:Sun, 11 Dec 2022 00:17:33 GMT, release_branch:8.6, prefix:, end_time:Sun, 11 Dec 2022 05:26:16 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-febebae1, build_duration_seconds:18523]
=> [automation] update elastic stack version for testing 8.6.0-febebae1

testing/environments/snapshot.yml
[start_time:Sun, 11 Dec 2022 12:15:20 GMT, release_branch:master, prefix:, end_time:Sun, 11 Dec 2022 15:47:46 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-e9833f49, build_duration_seconds:12746]
=> [automation] update elastic stack version for testing 8.7.0-e9833f49

CHANGELOG.next.asciidoc, packetbeat/sniffer/sniffer.go
This simplifies the shutdown logic and ensures that blocking calls all receive the signal to terminate when the Sniffer Stop method has been called.
Previously, the sniffer done chan was not shared, meaning that it was not closed and would not have had any effect if it were. The context that was being passed around was not a cancellation context and so never had a chance to terminate sniffHandle.
The current behaviour does not allow correct termination of the beat.
- For https://github.com/elastic/beats/issues/33962#issuecomment-1339963007
=> packetbeat/sniffer: fix shutdown logic

x-pack/libbeat/management/generate.go, x-pack/libbeat/management/managerV2.go
This is part of https://github.com/elastic/elastic-agent/issues/1800 
This makes config parsing a little more defensive in some spots, including erroring out if we get a output config with no `type` field set.
This can produce some ugly and hard to understand error messages.
=> Fix issues with bare fields in expected config

testing/environments/snapshot.yml
[start_time:Tue, 13 Dec 2022 00:15:02 GMT, release_branch:8.6, prefix:, end_time:Tue, 13 Dec 2022 04:17:34 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-6538107d, build_duration_seconds:14552]
=> [automation] update elastic stack version for testing 8.6.0-6538107d

metricbeat/docker-compose.yml, metricbeat/module/logstash/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
Merge only after the release of 7.17.8.
=> [Release] Update test environments for 7.17.9

testing/environments/snapshot.yml
[start_time:Wed, 14 Dec 2022 00:16:09 GMT, release_branch:8.6, prefix:, end_time:Wed, 14 Dec 2022 04:17:14 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-6aa72183, build_duration_seconds:14465]
=> [automation] update elastic stack version for testing 8.6.0-6aa72183

testing/environments/snapshot.yml
[start_time:Thu, 15 Dec 2022 00:16:06 GMT, release_branch:master, prefix:, end_time:Thu, 15 Dec 2022 04:09:50 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-4441fcfd, build_duration_seconds:14024]
=> [automation] update elastic stack version for testing 8.7.0-4441fcfd

testing/environments/snapshot.yml
[start_time:Thu, 15 Dec 2022 00:15:00 GMT, release_branch:8.6, prefix:, end_time:Thu, 15 Dec 2022 03:29:53 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-919399a0, build_duration_seconds:11693]
=> [automation] update elastic stack version for testing 8.6.0-919399a0

CHANGELOG.next.asciidoc, x-pack/filebeat/input/httpjson/encoding.go, x-pack/filebeat/input/httpjson/encoding_test.go
The httpjson input will report filenames for application/zip events in the response.
We have a [bug](https://github.com/elastic/integrations/issues/4764) for an integration that utilizes the filename to determine a `log_type` field as the field is in the name.  For example, `filename="delivery_20160705162902600.log"` -> `log_type: delivery`. When utilizing `compress: true`, the filename is instead a random guid and so the `log_type` can't be derived, example `filename="8578FCFC-A305-4D9A-99CB-F4D5ECEFE297.zip"`. 
Closes https://github.com/elastic/beats/issues/33952
=> Adding filenames from the zip to the response for httpjson

testing/environments/snapshot.yml
[start_time:Fri, 16 Dec 2022 00:15:04 GMT, release_branch:master, prefix:, end_time:Fri, 16 Dec 2022 03:52:36 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-319a9bee, build_duration_seconds:13052]
=> [automation] update elastic stack version for testing 8.7.0-319a9bee

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 15 Dec 2022 20:06:21 GMT, release_branch:7.17, prefix:, end_time:Fri, 16 Dec 2022 03:36:03 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-90a80afe, build_duration_seconds:26982]
=> [automation] update elastic stack version for testing 7.17.9-90a80afe

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-cel.asciidoc, x-pack/filebeat/docs/inputs/input-httpjson.asciidoc, x-pack/filebeat/input/cel/config.go, x-pack/filebeat/input/cel/config_test.go, x-pack/filebeat/input/cel/input.go, x-pack/filebeat/input/httpjson/config_request.go, x-pack/filebeat/input/httpjson/config_test.go, x-pack/filebeat/input/httpjson/input.go, x-pack/filebeat/input/httpjson/request_chain_helper.go
This makes it possible for users to configure idle connection keep-alive behaviour. The behaviour defaults to the old behaviour, but exposes the full set of httpcommon.WithKeepaliveSettings configuration options.
Keep-alive behaviour can have a performance and API-limit impact in some cases.
- Closes #33951
=> x-pack/filebeat/input/{cel,httpjson}: make transport keep-alives configurable

x-pack/heartbeat/cmd/root.go
Part of the fixes for https://github.com/elastic/elastic-agent/issues/1931 , although this might be the final component. 
This PR mostly bypasses all the config transformations for heartbeat, as the the heartbeat launcher will handle beat config itself (see `monitors/factory.go`),  and the default transformations were breaking heartbeat's own built-in config handling.  This PR is basically what was proposed here: https://github.com/elastic/elastic-agent/issues/1931#issuecomment-1351833489
=> Change heartbeat config formatting

testing/environments/snapshot.yml
[start_time:Fri, 16 Dec 2022 00:17:39 GMT, release_branch:8.6, prefix:, end_time:Fri, 16 Dec 2022 06:05:25 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-d5c0a6be, build_duration_seconds:20866]
=> [automation] update elastic stack version for testing 8.6.0-d5c0a6be

CHANGELOG.next.asciidoc, filebeat/docs/inputs/input-udp.asciidoc, filebeat/input/udp/input.go
This adds polling support for getting system UDP stats.
We have recently seen an issue where the user was losing UDP packets. Diagnosing this would have been very much easier if we had metrics not only for the UDP packet handling within Filebeat, but on the OS side as well, so this adds that.
- Relates #33870.
=> filebeat/input/udp: add support for /proc/net/udp metrics

CHANGELOG.next.asciidoc, metricbeat/docs/modules/aws.asciidoc, x-pack/metricbeat/module/aws/_meta/docs.asciidoc, x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go, x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
This PR modifies the AWS Cloudwatch module to call ListMetrics API only once per region, instead of once per namespace. Any namespaces that are part of ListMetrics API's response, but not configured to be queried, are removed in code.
ListMetrics API is billed per number of calls, so reducing the total number of calls lead to cost savings for users of the AWS Cloudwatch module.
References:
- https://github.com/elastic/beats/issues/33134
- https://github.com/elastic/integrations/issues/2913
- Closes #33134
=> [AWS Cloudwatch] Changed module to call ListMetrics API only once per region

x-pack/libbeat/management/generate.go, x-pack/libbeat/management/generate_test.go
Fix for https://github.com/elastic/elastic-agent/issues/1943
This looks for processors in the root global config, and injects them into the streams where they are forwarded to individual beat streams.
=> Fix global processors in beats agent client

testing/environments/snapshot.yml
[start_time:Mon, 19 Dec 2022 22:55:35 GMT, release_branch:master, prefix:, end_time:Tue, 20 Dec 2022 03:27:00 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-bb19a9d1, build_duration_seconds:16285]
=> [automation] update elastic stack version for testing 8.7.0-bb19a9d1

testing/environments/snapshot.yml
[start_time:Mon, 19 Dec 2022 16:18:03 GMT, release_branch:8.5, prefix:, end_time:Mon, 19 Dec 2022 20:31:22 GMT, manifest_version:2.1.0, version:8.5.4-SNAPSHOT, branch:8.5, build_id:8.5.4-9a613070, build_duration_seconds:15199]
=> [automation] update elastic stack version for testing 8.5.4-9a613070

testing/environments/snapshot.yml
[start_time:Tue, 20 Dec 2022 12:18:01 GMT, release_branch:master, prefix:, end_time:Tue, 20 Dec 2022 19:53:27 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-19f30181, build_duration_seconds:27326]
=> [automation] update elastic stack version for testing 8.7.0-19f30181

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 20 Dec 2022 05:16:47 GMT, release_branch:7.17, prefix:, end_time:Tue, 20 Dec 2022 09:46:47 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-ab98c430, build_duration_seconds:16200]
=> [automation] update elastic stack version for testing 7.17.9-ab98c430

testing/environments/snapshot.yml
[start_time:Wed, 21 Dec 2022 00:17:09 GMT, release_branch:8.6, prefix:, end_time:Wed, 21 Dec 2022 04:18:42 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-734df845, build_duration_seconds:14493]
=> [automation] update elastic stack version for testing 8.6.0-734df845

testing/environments/snapshot.yml
[start_time:Thu, 22 Dec 2022 00:16:50 GMT, release_branch:8.5, prefix:, end_time:Thu, 22 Dec 2022 04:16:35 GMT, manifest_version:2.1.0, version:8.5.4-SNAPSHOT, branch:8.5, build_id:8.5.4-880022a5, build_duration_seconds:14385]
=> [automation] update elastic stack version for testing 8.5.4-880022a5

testing/environments/snapshot.yml
[start_time:Thu, 22 Dec 2022 01:27:43 GMT, release_branch:8.6, prefix:, end_time:Thu, 22 Dec 2022 04:36:36 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-55d181cf, build_duration_seconds:11333]
=> [automation] update elastic stack version for testing 8.6.0-55d181cf

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 21 Dec 2022 05:17:15 GMT, release_branch:7.17, prefix:, end_time:Wed, 21 Dec 2022 10:12:17 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-dea3eaf3, build_duration_seconds:17702]
=> [automation] update elastic stack version for testing 7.17.9-dea3eaf3

CHANGELOG.next.asciidoc, x-pack/filebeat/input/azureeventhub/eph.go, x-pack/filebeat/input/azureeventhub/eph_test.go, x-pack/filebeat/input/azureeventhub/input.go, x-pack/filebeat/input/azureeventhub/input_test.go, x-pack/libbeat/management/generate_test.go
Update the `azure-eventhub` input to switch the run mode of the [Event Processor Host (EPH)](https://github.com/Azure/azure-event-hubs-go#event-processor-host) from blocking to non-blocking.
With the changes in the PR, the first call to the input `Start()` method will set up and start the EPH worker in a non-blocking fashion. The EPH worker will continue until the Filebeat calls the `Stop()` method to tear it down for live reloading. 
Since 8.3.3, the input Runner [changed its behavior](https://github.com/elastic/beats/commit/2f69f8647780f2225b3bfd9819068f6544fa8415#diff-55d635dc8516b02782b025d565e2191b6e5b559aedc21fd9437610aabaf739fa) during the [live reload](https://github.com/elastic/beats/blob/5fd004137864d356ef5ad33d0e8687e5192e651a/libbeat/cfgfile/list.go#L55):
- `< 8.3.3`: the …
=> [azure-eventhub input] Switch the run EPH run mode to non-blocking

testing/environments/snapshot.yml
[start_time:Thu, 22 Dec 2022 12:15:47 GMT, release_branch:8.5, prefix:, end_time:Thu, 22 Dec 2022 16:21:04 GMT, manifest_version:2.1.0, version:8.5.4-SNAPSHOT, branch:8.5, build_id:8.5.4-9612e66a, build_duration_seconds:14717]
=> [automation] update elastic stack version for testing 8.5.4-9612e66a

testing/environments/snapshot.yml
[start_time:Thu, 22 Dec 2022 21:51:59 GMT, release_branch:8.6, prefix:, end_time:Fri, 23 Dec 2022 01:28:33 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-33529ee6, build_duration_seconds:12994]
=> [automation] update elastic stack version for testing 8.6.0-33529ee6

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 22 Dec 2022 05:16:35 GMT, release_branch:7.17, prefix:, end_time:Thu, 22 Dec 2022 10:06:58 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-89f6cb7d, build_duration_seconds:17423]
=> [automation] update elastic stack version for testing 7.17.9-89f6cb7d

CHANGELOG.next.asciidoc, libbeat/common/kubernetes/metadata/config.go, libbeat/common/kubernetes/metadata/pod.go, libbeat/docs/shared-autodiscover.asciidoc
This is a "backport" of https://github.com/elastic/beats/pull/28521 so as to support disabling of Deployment metadata enrichment in Pod events. 
This will allow us to disable the enrichment that in large clusters can cost a lot and push the k8s API server.
@gizas @tetianakravchenko what do you think?
=> Add option to disable pod events enrichment with deployment name

metricbeat/module/elasticsearch/ccr/ccr.go
We're currently only collecting `ccr` metricset if the ES license is `trial` or `platinum` but the `enterprise` license [is also supported](https://www.elastic.co/subscriptions)
- created cloud cluster
- verified local metricbeat was storing ccr documents
=> [elasticsearch] ccr supports enterprise license

testing/environments/snapshot.yml
[start_time:Sun, 25 Dec 2022 12:18:04 GMT, release_branch:master, prefix:, end_time:Sun, 25 Dec 2022 15:22:59 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-0f74a2e9, build_duration_seconds:11095]
=> [automation] update elastic stack version for testing 8.7.0-0f74a2e9

testing/environments/snapshot.yml
[start_time:Mon, 26 Dec 2022 00:15:42 GMT, release_branch:8.5, prefix:, end_time:Mon, 26 Dec 2022 04:59:16 GMT, manifest_version:2.1.0, version:8.5.4-SNAPSHOT, branch:8.5, build_id:8.5.4-09ced402, build_duration_seconds:17014]
=> [automation] update elastic stack version for testing 8.5.4-09ced402

testing/environments/snapshot.yml
[start_time:Mon, 26 Dec 2022 00:17:39 GMT, release_branch:8.6, prefix:, end_time:Mon, 26 Dec 2022 04:28:15 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-f6d7d537, build_duration_seconds:15036]
=> [automation] update elastic stack version for testing 8.6.0-f6d7d537

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Sun, 25 Dec 2022 05:17:01 GMT, release_branch:7.17, prefix:, end_time:Sun, 25 Dec 2022 10:11:23 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-917139ef, build_duration_seconds:17662]
=> [automation] update elastic stack version for testing 7.17.9-917139ef

testing/environments/snapshot.yml
[start_time:Tue, 27 Dec 2022 00:17:52 GMT, release_branch:8.6, prefix:, end_time:Tue, 27 Dec 2022 03:33:58 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-a026c2fe, build_duration_seconds:11766]
=> [automation] update elastic stack version for testing 8.6.0-a026c2fe

testing/environments/snapshot.yml
[start_time:Tue, 27 Dec 2022 00:16:05 GMT, release_branch:8.5, prefix:, end_time:Tue, 27 Dec 2022 04:42:49 GMT, manifest_version:2.1.0, version:8.5.4-SNAPSHOT, branch:8.5, build_id:8.5.4-53cae6e0, build_duration_seconds:16004]
=> [automation] update elastic stack version for testing 8.5.4-53cae6e0

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Mon, 26 Dec 2022 05:17:03 GMT, release_branch:7.17, prefix:, end_time:Mon, 26 Dec 2022 10:12:29 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-0c41c515, build_duration_seconds:17726]
=> [automation] update elastic stack version for testing 7.17.9-0c41c515

CHANGELOG.next.asciidoc, x-pack/filebeat/input/httpjson/request.go
- Bug
Adds a safety check to response.Body.Close to avoid unnecessary panics
Improves stability, removing edge-case panics
~~- [ ]~~ I have made corresponding changes to the documentation
~~- [ ]~~ I have made corresponding change to the default configuration files
- Closes #34126
=> [filebeat][httpjson]- improved error handling during pagination with chaining & split processor

testing/environments/snapshot.yml
[start_time:Tue, 27 Dec 2022 12:17:19 GMT, release_branch:master, prefix:, end_time:Tue, 27 Dec 2022 15:53:15 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-b3da67ae, build_duration_seconds:12956]
=> [automation] update elastic stack version for testing 8.7.0-b3da67ae

testing/environments/snapshot.yml
[start_time:Tue, 27 Dec 2022 12:20:45 GMT, release_branch:8.5, prefix:, end_time:Tue, 27 Dec 2022 16:20:38 GMT, manifest_version:2.1.0, version:8.5.4-SNAPSHOT, branch:8.5, build_id:8.5.4-b44284e8, build_duration_seconds:14393]
=> [automation] update elastic stack version for testing 8.5.4-b44284e8

testing/environments/snapshot.yml
[start_time:Wed, 28 Dec 2022 00:17:28 GMT, release_branch:8.6, prefix:, end_time:Wed, 28 Dec 2022 04:40:37 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-7e55dcb1, build_duration_seconds:15789]
=> [automation] update elastic stack version for testing 8.6.0-7e55dcb1

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 27 Dec 2022 05:16:51 GMT, release_branch:7.17, prefix:, end_time:Tue, 27 Dec 2022 09:54:24 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-590749d6, build_duration_seconds:16653]
=> [automation] update elastic stack version for testing 7.17.9-590749d6

testing/environments/snapshot.yml
[start_time:Thu, 29 Dec 2022 00:16:26 GMT, release_branch:8.5, prefix:, end_time:Thu, 29 Dec 2022 04:51:03 GMT, manifest_version:2.1.0, version:8.5.4-SNAPSHOT, branch:8.5, build_id:8.5.4-63dd32c9, build_duration_seconds:16477]
=> [automation] update elastic stack version for testing 8.5.4-63dd32c9

testing/environments/snapshot.yml
[start_time:Thu, 29 Dec 2022 00:17:11 GMT, release_branch:8.6, prefix:, end_time:Thu, 29 Dec 2022 04:01:07 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-08909b84, build_duration_seconds:13436]
=> [automation] update elastic stack version for testing 8.6.0-08909b84

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 28 Dec 2022 05:16:23 GMT, release_branch:7.17, prefix:, end_time:Wed, 28 Dec 2022 09:45:25 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-fb6ed84b, build_duration_seconds:16142]
=> [automation] update elastic stack version for testing 7.17.9-fb6ed84b

Makefile, dev-tools/mage/clean.go
Fixes `make clean`
`make clean` was failing, thus not cleaning the project what might lead to an old build of the beats being used when the elastic-agent package process looks for local beats packages.
Run `make clean`, it must succeed
N/A
=> Fix make clean

Makefile, dev-tools/mage/clean.go
Fixes `make clean`
`make clean` was failing, thus not cleaning the project what might lead to an old build of the beats being used when the elastic-agent package process looks for local beats packages.
Run `make clean`, it must succeed
N/A
=> Fix make clean (#34134)

testing/environments/snapshot.yml
[start_time:Fri, 30 Dec 2022 00:22:46 GMT, release_branch:master, prefix:, end_time:Fri, 30 Dec 2022 04:16:19 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-d6e7f5ec, build_duration_seconds:14013]
=> [automation] update elastic stack version for testing 8.7.0-d6e7f5ec

testing/environments/snapshot.yml
[start_time:Fri, 30 Dec 2022 00:18:05 GMT, release_branch:8.6, prefix:, end_time:Fri, 30 Dec 2022 03:48:37 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-2d1af9b1, build_duration_seconds:12632]
=> [automation] update elastic stack version for testing 8.6.0-2d1af9b1

testing/environments/snapshot.yml
[start_time:Thu, 29 Dec 2022 12:15:52 GMT, release_branch:8.5, prefix:, end_time:Thu, 29 Dec 2022 16:14:33 GMT, manifest_version:2.1.0, version:8.5.4-SNAPSHOT, branch:8.5, build_id:8.5.4-2ce7df52, build_duration_seconds:14321]
=> [automation] update elastic stack version for testing 8.5.4-2ce7df52

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 29 Dec 2022 05:16:31 GMT, release_branch:7.17, prefix:, end_time:Thu, 29 Dec 2022 10:06:25 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-9b93f6c8, build_duration_seconds:17394]
=> [automation] update elastic stack version for testing 7.17.9-9b93f6c8

libbeat/cmd/instance/locks/lock.go
- Bug
Correct a typo in an error message
`Dec 20 11:48:14 hostname filebeat[107249]: Exiting: cannot obtain lockfile: connot start, data directory belongs to process with pid 1473
`
Error messages should be correct
n/a
n/a
=> Correct typo in error message

NOTICE.txt, libbeat/cmd/instance/beat.go
Disables seccomp filter for osquerybeat. 
It was disabled before V2 with osquerybeat.yml config
https://github.com/elastic/beats/blob/7cf873fd340172c33f294500ccfec948afd7a47c/x-pack/osquerybeat/osquerybeat.yml#L16
There is probably a better place for this, but this works for this release deadline.
Somebody more familiar with that area of the agent feel free to chime in. We can move it later in 8.7.0.
Osquerybeat fails to run without this change with error:
```
"Exiting: fork/exec /usr/share/elastic-agent/data/elastic-agent-362d2b/components/osqueryd: operation not permitted"
```
Osquery works with this change
=> Disable seccomp filter for osquerybeat

testing/environments/snapshot.yml
[start_time:Thu, 5 Jan 2023 12:17:19 GMT, release_branch:master, prefix:, end_time:Thu, 5 Jan 2023 23:02:49 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-129a645f, build_duration_seconds:38730]
=> [automation] update elastic stack version for testing 8.7.0-129a645f

testing/environments/snapshot.yml
[start_time:Fri, 6 Jan 2023 00:18:00 GMT, release_branch:8.6, prefix:, end_time:Fri, 6 Jan 2023 04:51:07 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-08ebeaf7, build_duration_seconds:16387]
=> [automation] update elastic stack version for testing 8.6.0-08ebeaf7

testing/environments/snapshot.yml
[start_time:Mon, 9 Jan 2023 00:17:13 GMT, release_branch:master, prefix:, end_time:Mon, 9 Jan 2023 03:41:46 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-df9bb536, build_duration_seconds:12273]
=> [automation] update elastic stack version for testing 8.7.0-df9bb536

testing/environments/snapshot.yml
[start_time:Mon, 9 Jan 2023 00:17:57 GMT, release_branch:8.6, prefix:, end_time:Mon, 9 Jan 2023 04:46:04 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-9105192d, build_duration_seconds:16087]
=> [automation] update elastic stack version for testing 8.6.0-9105192d

metricbeat/module/kubernetes/_meta/kibana/7/dashboard/2ec26ce0-f5f1-11ec-8853-8b596bddf5f9.json, metricbeat/module/kubernetes/_meta/kibana/7/dashboard/5e649d60-9901-11e9-ba57-b7ab4e2d4b58.json, metricbeat/module/kubernetes/_meta/kibana/7/dashboard/f5ab5510-9c94-11e9-94fd-c91206cd5249.json
Regarding https://github.com/elastic/beats/pull/34161, some of the visualizations on Proxy and Scheduler dashboard were using `kubernetes.controllermanager.*` metrics leading to empty visualizations. The only change is switching those metrics to either `kubernetes.scheduler.*` for Scheduler dashboard and to `kubernetes.proxy.*` for Proxy dashboard.
Also updated the remaining area charts to line charts. Example:
A visualization like the one on the right, will be similar to the one on the left in case of a rate change.
- Relates https://github.com/elastic/beats/pull/34161
=> [Metricbeat][Kubernetes] Fix scheduler and proxy dashboard

testing/environments/snapshot.yml
[start_time:Mon, 9 Jan 2023 12:17:52 GMT, release_branch:master, prefix:, end_time:Mon, 9 Jan 2023 15:56:00 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-61c35791, build_duration_seconds:13088]
=> [automation] update elastic stack version for testing 8.7.0-61c35791

dev-tools/mage/build.go
Fix the issue with the `CVE-2022-24765`, so the workspace is set as safe
Otherwise, it will fail with:
```
[2023-01-11T09:58:36.531Z] >> Building using: cmd='build/mage-linux-amd64 golangCrossBuild', env=[CC=o64-clang, CXX=o64-clang++, GOARCH=amd64, GOARM=, GOOS=darwin, PLATFORM_ID=darwin-amd64]
[2023-01-11T09:58:36.632Z] fatal: detected dubious ownership in repository at '/go/src/github.com/elastic/beats'
```
=> Set beats dir as safe for crossbuild

metricbeat/module/kubernetes/_meta/kibana/7/dashboard/2ec26ce0-f5f1-11ec-8853-8b596bddf5f9.json, metricbeat/module/kubernetes/_meta/kibana/7/dashboard/5e649d60-9901-11e9-ba57-b7ab4e2d4b58.json, metricbeat/module/kubernetes/_meta/kibana/7/dashboard/f5ab5510-9c94-11e9-94fd-c91206cd5249.json
Following the comments on https://github.com/elastic/integrations/pull/4948, dashboards were updated:
- Visualization for resident memory use now average instead of rate
- `[Metricbeat Kubernetes]` was removed from all titles
- Relates  to https://github.com/elastic/integrations/pull/4948
=> [Metricbeat][Kubernetes] Update proxy, scheduler and controller manager dashboards

dev-tools/kubernetes/Tiltfile, dev-tools/kubernetes/heartbeat/Dockerfile.debug, dev-tools/kubernetes/heartbeat/Dockerfile.run, dev-tools/kubernetes/heartbeat/manifest.debug.yaml, dev-tools/kubernetes/heartbeat/manifest.run.yaml
Changes to Tiltfile + dockerfile + manifests to remote debug Heartbeat similarly to how it works already for Metricbeat and Filebeat.
I found absolutely necessity to be able to remote debug heartbeat and similar beats to investigate bugs
None of the below applies since it is a dev tool
Instructions at https://github.com/elastic/beats/pull/32326
- Relates https://github.com/elastic/beats/pull/32326
- Used by issue https://github.com/elastic/beats/issues/34214
=> Remote debug heartbeat

NOTICE.txt, go.mod, go.sum
Removes a debug log that could print certificate private keys.
=> Upgrade elastic-agent-libs to v0.2.16.

CHANGELOG.next.asciidoc, x-pack/osquerybeat/cmd/root.go
Fixes the values for the ```data_stream```: ```type``` and```dataset```. 
The 8.6.0 has wrong values set after switching to using the V2 libbeat ```management.CreateInputsFromStreams``` implementation that is inserting the policy processor:
```
processors:
- add_fields:
fields:
dataset: generic
namespace: default
type: osquery
target: data_stream
```
resulting in these ```data_stream``` properties.
```
"data_stream": {
"namespace": "default",
"type": "osquery",
"dataset": "generic"
},
```
This PR sets the expected default values on the datastream before the configuration transformation takes place thus setting the values back to what it was before 8.6.0:
```
"data_stream": {
"namespace": "default",
"type": "logs",
"dataset": "osquery_manager.result"
},
```
These fields are mapped as the …
=> Osquerybeat: Fix data_stream configuration, enforce the default values used before 8.6.0

testing/environments/snapshot.yml
[start_time:Mon, 16 Jan 2023 00:17:31 GMT, release_branch:8.6, prefix:, end_time:Mon, 16 Jan 2023 04:30:38 GMT, manifest_version:2.1.0, version:8.6.1-SNAPSHOT, branch:8.6, build_id:8.6.1-436ca0d1, build_duration_seconds:15187]
=> [automation] update elastic stack version for testing 8.6.1-436ca0d1

.github/workflows/opentelemetry.yml
Use https://github.com/elastic/apm-pipeline-library/tree/main/.github/actions/opentelemetry
Use the reusable action.
Service matching the repo name rather than the Workflow name.
=> action: use composite action

testing/environments/snapshot.yml
[start_time:Tue, 17 Jan 2023 00:18:02 GMT, release_branch:8.6, prefix:, end_time:Tue, 17 Jan 2023 04:19:06 GMT, manifest_version:2.1.0, version:8.6.1-SNAPSHOT, branch:8.6, build_id:8.6.1-cc0796ca, build_duration_seconds:14464]
=> [automation] update elastic stack version for testing 8.6.1-cc0796ca

CHANGELOG.next.asciidoc, filebeat/module/auditd/log/ingest/pipeline.yml, filebeat/module/auditd/log/test/audit-rhel7_2.log, filebeat/module/auditd/log/test/audit-rhel7_2.log-expected.json
This allows parsing auditd messages that inclued quoted spaces
Currently these messages cannot be processed.
- Fixes #22587
=> filebeat/module/auditd: teach kv about quoted spaces

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Tue, 17 Jan 2023 05:16:58 GMT, release_branch:7.17, prefix:, end_time:Tue, 17 Jan 2023 10:05:39 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-a4381da5, build_duration_seconds:17321]
=> [automation] update elastic stack version for testing 7.17.9-a4381da5

CHANGELOG.next.asciidoc, x-pack/winlogbeat/module/security/ingest/security.yml, x-pack/winlogbeat/module/security/test/testdata/collection/4778.evtx.golden.json, x-pack/winlogbeat/module/security/test/testdata/collection/4779.evtx.golden.json, x-pack/winlogbeat/module/security/test/testdata/ingest/4778.golden.json, x-pack/winlogbeat/module/security/test/testdata/ingest/4779.golden.json
Some security events contain a source IP address of "LOCAL" or "Unknown" which are not valid IP addresses. This PR will correct the processing of events containing one of those values. 
This bug causes mapping exceptions and prevents these events from being ingested. 
-fixes #19627
=> Validate Source IP "LOCAL" or "Unknown" in Windows Security Logs

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 18 Jan 2023 05:17:17 GMT, release_branch:7.17, prefix:, end_time:Wed, 18 Jan 2023 10:04:14 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-62814092, build_duration_seconds:17217]
=> [automation] update elastic stack version for testing 7.17.9-62814092

CHANGELOG.next.asciidoc, filebeat/input/filestream/config.go
- Bug
According to the documentation, the `close.on_state_change.inactive` value in the filebeat filestream module is supposed to be 5 minutes but it was set to 0 by default in the code.
This PR correctly sets the default value to 5 minutes.
The default behaviour now is to keep the file open forever, which might cause confusion as it contradicts the documentation.
- Closes #34234
=> `close.on_state_change.inactive` default value changed to 5m

CHANGELOG.next.asciidoc, x-pack/filebeat/input/httpjson/input_test.go, x-pack/filebeat/input/httpjson/split.go
This allows documents to be retained when a split would be empty, if `keep_parent` and `ignore_empty_value` are true.
Currently splits will drop these split documents.
-
=> x-pack/filebeat/input/httpjson: fix handling of null or empty arrays during split

testing/environments/snapshot.yml
[start_time:Sun, 22 Jan 2023 00:17:11 GMT, release_branch:8.6, prefix:, end_time:Sun, 22 Jan 2023 05:03:17 GMT, manifest_version:2.1.0, version:8.6.1-SNAPSHOT, branch:8.6, build_id:8.6.1-8f6887b9, build_duration_seconds:17166]
=> [automation] update elastic stack version for testing 8.6.1-8f6887b9

CHANGELOG.next.asciidoc, x-pack/libbeat/management/managerV2.go
Improved the `managerV2` to not perform reloading of the output or inputs if the configuration has not changed.
Before this change any change in a single unit (including state and log level) would result in all units being reloaded even if that units configuration didn't change. To make it worse when `stopOnEmptyUnits` is true any little change, like log level would cause the entire beat to restart.
- Closes #34178
=> Add checks to ensure reloading of units if the configuration actually changed.

CHANGELOG.next.asciidoc
The changelog had extra entries which were not supposed to be added by https://github.com/elastic/beats/pull/34338
Also, the section was wrong, it's `Added` not `Fixed`.
=> Fix changelog after a bad backport

CHANGELOG.next.asciidoc, packetbeat/protos/tcp/tcp.go, packetbeat/protos/tcp/tcp_test.go, packetbeat/protos/udp/udp.go, packetbeat/protos/udp/udp_test.go
Metrics are registered in a namspace derived solely from the id parameter of inputmon.NewInputRegistry, while packetbeat does not provide per-proto IDs. This means that when more that one sniffer is active on the same NIC there will be a namespace collision. To prevent this, construct an ID from the packetbeat ID, the proto and the list of ports that are being sniffed in a canonical syntax, and the NIC's name.
Also make the testing of metric namespace collision more rigorous within the packages themselves, leaving a relaxed testing mode for external packages.
Currently registering multiple sniffers will cause packetbeat to panic.
- Fixes elastic/cloud-on-k8s#6346
=> packetbeat/protos/{tcp,udp}: prevent metric namespace collision

.ci/apm-beats-update.groovy, .ci/beats-tester.groovy, .ci/build-docker-images.groovy, .ci/heartbeat-synthetics.groovy, .ci/ironbank-validation.groovy, .ci/packaging.groovy, Jenkinsfile, auditbeat/Jenkinsfile.yml, deploy/kubernetes/Jenkinsfile.yml, filebeat/Jenkinsfile.yml, heartbeat/Jenkinsfile.yml, libbeat/Jenkinsfile.yml, metricbeat/Jenkinsfile.yml, packetbeat/Jenkinsfile.yml, winlogbeat/Jenkinsfile.yml, x-pack/auditbeat/Jenkinsfile.yml, x-pack/dockerlogbeat/Jenkinsfile.yml, x-pack/filebeat/Jenkinsfile.yml, x-pack/functionbeat/Jenkinsfile.yml, x-pack/heartbeat/Jenkinsfile.yml, x-pack/libbeat/Jenkinsfile.yml, x-pack/metricbeat/Jenkinsfile.yml, x-pack/osquerybeat/Jenkinsfile.yml, x-pack/packetbeat/Jenkinsfile.yml, x-pack/winlogbeat/Jenkinsfile.yml
Use ubuntu:22 workers in the CI
Ubuntu 18 is a kind of old
See https://github.com/elastic/beats/pull/34303#issuecomment-1396662254
Superseedes https://github.com/elastic/beats/pull/34314
=> ci: use ubuntu:22 workers

auditbeat/Jenkinsfile.yml, filebeat/Jenkinsfile.yml, heartbeat/Jenkinsfile.yml, libbeat/Jenkinsfile.yml, metricbeat/Jenkinsfile.yml, packetbeat/Jenkinsfile.yml, x-pack/auditbeat/Jenkinsfile.yml, x-pack/dockerlogbeat/Jenkinsfile.yml, x-pack/filebeat/Jenkinsfile.yml, x-pack/functionbeat/Jenkinsfile.yml, x-pack/heartbeat/Jenkinsfile.yml, x-pack/libbeat/Jenkinsfile.yml, x-pack/metricbeat/Jenkinsfile.yml, x-pack/packetbeat/Jenkinsfile.yml
Use ubuntu-22 for the aarch64 workers
Leftover from https://github.com/elastic/beats/pull/34315
Unfortunately the default behaviour with the CI builds on PRs don't trigger `arm` but only with merge commits, though you can use `arm` label to enable the those specific stages... I somehow missed that particular feature :/
=> ci: use ubuntu-22 for the aarch64 workers

CHANGELOG.next.asciidoc, heartbeat/monitors/wrappers/monitorstate/esloader_test.go, heartbeat/monitors/wrappers/monitorstate/monitorstate.go
Changes marshalling of states duration to string-encoded int64, per recommendation. Fixes #34218.
When `duration_ms` gets long enough, it starts being marshalled in **float** format, which is incompatible with int64 type. It then prevents states from being recovered from ES, generating a new one every ~20min.
=> Marshal heartbeat duration as int64,string to prevent int64 -> float conversion

CHANGELOG.next.asciidoc, x-pack/filebeat/input/azureblobstorage/input.go
- Enhancement
updates log field names so that it does not clash with ecs field names.
It important that ecs field names are not used as general log field names.
=> fixed log naming syntax to not clash with ecs field names

metricbeat/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
Merge only after the release of 8.6.1.
=> [Release] Update test environments for 8.6.2

CHANGELOG.next.asciidoc, x-pack/filebeat/input/azureblobstorage/input.go
=> Revert "[8.6](backport #34403) fixed log naming syntax to not clash with ecs field names"

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-cel.asciidoc, x-pack/filebeat/input/cel/config.go, x-pack/filebeat/input/cel/input.go, x-pack/filebeat/input/cel/input_test.go
This add logic, configuration and documentation for redacting parts of pre- and post-processing CEL state when logging state to debug logs. The configuration allows users to specify fields that should not be entered into logs and whether these fields should be masked or deleted from the logged object.
Leaking secrets to debug logs is a significant attack surface.
-
=> x-pack/filebeat/input/cel: allow users to redact state fields in logs

testing/environments/snapshot.yml
[start_time:Sat, 28 Jan 2023 00:18:13 GMT, release_branch:8.6, prefix:, end_time:Sat, 28 Jan 2023 03:39:29 GMT, manifest_version:2.1.0, version:8.6.2-SNAPSHOT, branch:8.6, build_id:8.6.2-a887b34c, build_duration_seconds:12076]
=> [automation] update elastic stack version for testing 8.6.2-a887b34c

libbeat/docs/shared-autodiscover.asciidoc
Following changes in https://github.com/elastic/beats/pull/33240 this PR updates kubernetes autodiscover provider documentation.
It adds a note in kubernetes autodiscover provider about the correct usage of kubernetes pod labels in autodiscover conditions.
=> Clarify usage of kubernetes pod labels in condition matching in kubernetes autodiscover provider documentation

CHANGELOG.next.asciidoc, x-pack/filebeat/input/azureblobstorage/job.go
Adding a failsafe for when content encoding headers might be nil, especially for system tests.
Required for Agent integration package system tests
When creating system tests for elastic-package, we use the Azure Blob Storage emulator: https://hub.docker.com/_/microsoft-azure-storage-azurite
Unfortunately the emulator itself does not return a `ContentEncoding` header, while the Cloud API will always ensure at least a default `octet-stream` is added if value is nil, we need to add the possibility for the Encoding Header to not be present to be able to continue the system tests.
Steps to reproduce:
1. Start up the emulator: `docker run -p 10000:10000 mcr.microsoft.com/azure-storage/azurite azurite-blob --blobHost 0.0.0.0`
2. Download stream and run `go build` : …
=> [Azure Blob Storage] Allowing empty content encoding headers for system tests

CHANGELOG.next.asciidoc, x-pack/filebeat/input/gcs/client.go, x-pack/filebeat/input/gcs/config.go
This adds the `alternative_host` option, which is a field only used for internal testing. By default the input only reaches out to the public cloud GCS API, and this allows us to override this and instead point it to our own emulator running locally for system tests.
Required for adding system tests for elastic-agent integration packages.
1. Start up the local GCS emulator: `docker run -p 4443:4443 fsouza/fake-gcs-server -host="0.0.0.0" -public-host=localhost -port=4443 -scheme=http`
2. Download stream and run `go build` : `https://github.com/elastic/stream`
3. Create a local file for testing, for example `test.json`, add a JSON object on a single line, like `{ "testmessage" : "success" }`
4. Populate the emulator with the testdata using `stream`: `./stream log --retry=30 …
=> [Google Cloud Storage] Add support for alternative_host for system tests

.ci/packaging.groovy
Use ubuntu-22 for the `aarch64` workers
Leftover from https://github.com/elastic/beats/pull/34315 and https://github.com/elastic/beats/pull/34383
=> packaging: use ubuntu-22 for the aarch64 workers

testing/environments/snapshot.yml
[start_time:Mon, 30 Jan 2023 00:18:06 GMT, release_branch:8.6, prefix:, end_time:Mon, 30 Jan 2023 17:25:42 GMT, manifest_version:2.1.0, version:8.6.2-SNAPSHOT, branch:8.6, build_id:8.6.2-6e25dbb4, build_duration_seconds:61656]
=> [automation] update elastic stack version for testing 8.6.2-6e25dbb4

CHANGELOG.next.asciidoc, x-pack/auditbeat/module/system/package/package.go, x-pack/auditbeat/module/system/package/package_homebrew.go, x-pack/auditbeat/module/system/package/package_homebrew_test.go, x-pack/auditbeat/module/system/package/package_test.go
- Enhancement
Adds support for detecting homebrew packages on macs with apple silicon chips.
Previously packages were not being detected on macs with m1 chips.
- Closes #34043 
- Relates  #33765
=> added mac m1 support for auditbeat system/package

x-pack/filebeat/input/azureblobstorage/job.go
Event.kind was set to wrong values (not conforming with ECS), and should really be set in ingest pipelines based on the output of the actual event.
Required for the input to respect ECS, and to pass system tests.
Just run any system test with `--generate` and see if the resulting output does not have event.kind
=> [Azure blob storage] removing wrong event.kind from input

x-pack/filebeat/input/gcs/job.go
Similar to https://github.com/elastic/beats/pull/34439, we remove the hardcoded event.kind, as it does not follow the ECS field definition, and should be set based on the event itself
Required for system tests to pass.
Just run any system test with --generate and see if the resulting output does not have event.kind
- Relates #34439
=> [Google Cloud Storage] Remove event kind from input

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Wed, 1 Feb 2023 05:18:05 GMT, release_branch:7.17, prefix:, end_time:Wed, 1 Feb 2023 10:41:37 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-663e90b2, build_duration_seconds:19412]
=> [automation] update elastic stack version for testing 7.17.9-663e90b2

.ci/beats-tester.groovy, .ci/packaging.groovy
Configure where the snapshots are stored since there is a nested folder with the project name.
The new folder layout was not reflected in this project.
Originally implemented in https://github.com/elastic/apm-pipeline-library/pull/1549
=> ci: fix google bucket location

metricbeat/docker-compose.yml, metricbeat/module/logstash/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
Merge only after the release of 7.17.9.
=> [Release] Update test environments for 7.17.10

CHANGELOG.next.asciidoc, packetbeat/_meta/config/beat.reference.yml.tmpl, packetbeat/_meta/config/beat.yml.tmpl, packetbeat/_meta/config/windows_npcap.yml.tmpl, packetbeat/beater/install_npcap.go, packetbeat/docs/packetbeat-options.asciidoc
Allow user to prevent Npcap installation on Windows.
Some users depend on software that uses Npcap pinned to other versions.
Test locally on a windows machine with no npcap installed, and running with `.\packetbeat -e -d '*'` (binary must have been built with npcap installer asset in place) with the following packetbeat.yml.
```
packetbeat.interfaces.device: default_route
packetbeat.npcap:
never_install: true
packetbeat.interfaces.poll_default_route: 1m
packetbeat.interfaces.internal_networks:
- private
packetbeat.flows:
timeout: 30s
period: 10s
packetbeat.protocols:
- type: icmp
enabled: true
output.file:
path: "./"
filename: packetbeat-test
```
You will see the following two lines in the output
```
{"log.level":"warn","@timestamp":"2023-01-30T23:11:39.642-0800","log.logger":"npcap_instal …
```
=> packetbeat: allow user to prevent Npcap installation on Windows

testing/environments/snapshot.yml
[start_time:Thu, 2 Feb 2023 12:17:48 GMT, release_branch:8.6, prefix:, end_time:Thu, 2 Feb 2023 18:02:14 GMT, manifest_version:2.1.0, version:8.6.2-SNAPSHOT, branch:8.6, build_id:8.6.2-b5f10a44, build_duration_seconds:20666]
=> [automation] update elastic stack version for testing 8.6.2-b5f10a44

testing/environments/snapshot-oss.yml, testing/environments/snapshot.yml
[start_time:Thu, 2 Feb 2023 05:16:54 GMT, release_branch:7.17, prefix:, end_time:Thu, 2 Feb 2023 10:36:17 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-f3ee8926, build_duration_seconds:19163]
=> [automation] update elastic stack version for testing 7.17.9-f3ee8926

CHANGELOG.next.asciidoc, filebeat/docs/modules/checkpoint.asciidoc, x-pack/filebeat/filebeat.reference.yml, x-pack/filebeat/module/checkpoint/_meta/config.yml, x-pack/filebeat/module/checkpoint/_meta/docs.asciidoc, x-pack/filebeat/module/checkpoint/firewall/config/firewall.yml, x-pack/filebeat/module/checkpoint/firewall/ingest/pipeline.yml, x-pack/filebeat/module/checkpoint/firewall/manifest.yml, x-pack/filebeat/module/checkpoint/firewall/test/R80.X.log-expected.json, x-pack/filebeat/module/checkpoint/firewall/test/R81.X.log-expected.json, x-pack/filebeat/module/checkpoint/firewall/test/checkpoint.log-expected.json, x-pack/filebeat/module/checkpoint/firewall/test/checkpoint_with_time.log-expected.json, x-pack/filebeat/module/checkpoint/firewall/test/trailing-space.log-expected.json, x-pack/filebeat/modules.d/checkpoint.yml.disabled
Allows users to configure timezone for Checkpoint module.
See related issue. elastic/integrations#5126
- Closes elastic/integrations#5126
=> x-pack/filebeat/module/checkpoint: allow configuration of time zones

CHANGELOG.next.asciidoc, x-pack/filebeat/module/azure/signinlogs/ingest/pipeline.yml
Replace the `foreach` + `set` processors combo with a single `script` processor in the ingest pipeline for Azure AD sign-in logs.
The `set` processor expands the dots contained in the field name into subfields.
Sometimes attributes contained in `authentication_processing_details` have dots, for example:
{"key": "a.b.c", "value": true}
In such cases, the `set` processor would turn it into:
{
"a": {
"b": {
"c": true
}
}
}
Instead of:
{"a.b.c": True}
- Closes #34330
=> [Azure Logs] Replace foreach+set combo with a script processor

CHANGELOG.next.asciidoc, x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go, x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go, x-pack/metricbeat/module/aws/cloudwatch/metadata/ec2/ec2.go, x-pack/metricbeat/module/aws/cloudwatch/metadata/rds/rds.go, x-pack/metricbeat/module/aws/cloudwatch/metadata/sqs/sqs.go
Bug
https://github.com/elastic/beats/pull/33166 introduced support for granularity in cloudwatch metrics API calls.
we collect events identified by an ID: different metrics are merged in a single event according to the ID of the event
the mentioned PR refactored the way the ID was generated, introducing a bug that prevented different metrics to be merged in a single event.
changing the event ID also prevented the ec2 add metadata to match the metadata of an instance to a given event, losing the enrichment of an event with such metadata
we fix the ID generation, still suffixing it with the dimension of the given granularity, so that we are able to merge different metrics on the same event
we refactored the ID matching logic in the ec2 add metadata to ignore the granularity dimension suffix …
=> Fix aws cloudwatch event identifiers

testing/environments/snapshot.yml
[start_time:Wed, 8 Feb 2023 00:17:50 GMT, release_branch:8.6, prefix:, end_time:Wed, 8 Feb 2023 03:25:29 GMT, manifest_version:2.1.0, version:8.6.2-SNAPSHOT, branch:8.6, build_id:8.6.2-7c4539d9, build_duration_seconds:11259]
=> [automation] update elastic stack version for testing 8.6.2-7c4539d9

metricbeat/module/beat/stats/stats.go
Related https://github.com/elastic/beats/issues/34217
Reduce log noise when failing to get the cluster uuid from a beats state.
If the issue surfaced by this log is persistent it would already be highlighted by higher severity entries in the logs.
=> [beats] reduce log noise

metricbeat/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
This updates the test environments to next minor release which is 8.8.0.
=> [Release] Update test environment to 8.8.0

.github/workflows/notify-stalled-snapshots.yml
Bump automation should run independently for each active release branch
=> action: avoid failing fast

.github/workflows/bump-elastic-stack-snapshot.yml
Run each branch independent
Otherwise if a snapshot is not ready for any release branch, as today with `8.7` then the bump won't work
=> action: avoid fail fast for bump-elastic-stack-snapshot

.github/workflows/bump-elastic-stack-snapshot.yml, .github/workflows/bump-golang.yml
Use GitHub composite action
Reuse code and solve the existing issue with Workflows won't be enabled for PRs created on behalf of `GitHub actions [bot]`, see https://github.com/elastic/ecs-logging-java/pull/200
Similar to https://github.com/elastic/ecs-logging-java/pull/201
Requires https://github.com/elastic/apm-pipeline-library/pull/2076
=> action: use composite updatecli

CHANGELOG.next.asciidoc, winlogbeat/sys/winevent/event_test.go, winlogbeat/sys/winevent/maputil.go
In some locales, Windows abbreviates event data keys with dots. This happens in Spanish for example where the English 'ID' is rendered as 'Id.' When using `mapstr.Put`, this dot is interpreted as a path separator, breaking the structure of the document and ultimately leading to an ingest failure. So use opaque key map insertion.
Breaks data ingestion in some lacales.
- Fixes #34345
=> winlogbeat/sys/winevent: do not interpret dots as JSON path separators

libbeat/outputs/console/docs/console.asciidoc, libbeat/outputs/fileout/docs/fileout.asciidoc, libbeat/outputs/kafka/docs/kafka.asciidoc, libbeat/outputs/logstash/docs/logstash.asciidoc, libbeat/outputs/redis/docs/redis.asciidoc
**This PR only impacts the APM Server documentation.**
This PR adds a section on configuring the Kibana endpoint to all non-elasticsearch output configuration documentation.
Do not merge before https://github.com/elastic/apm-server/pull/10248.
=> docs: Add Kibana endpoint config to non-ES outputs

dev-tools/mage/build.go
Backport of https://github.com/elastic/elastic-agent/pull/2093
Fix the issue with the `CVE-2022-24765`, so the workspace is set as safe
Otherwise, it will fail with:
```
[2023-01-11T09:58:36.531Z] >> Building using: cmd='build/mage-linux-amd64 golangCrossBuild', env=[CC=o64-clang, CXX=o64-clang++, GOARCH=amd64, GOARM=, GOOS=darwin, PLATFORM_ID=darwin-amd64]
[2023-01-11T09:58:36.632Z] fatal: detected dubious ownership in repository at '/go/src/github.com/elastic/beats'
```
=> [7.17] backport: Add beats directory into git safe dirs

CHANGELOG.next.asciidoc, libbeat/cmd/instance/beat.go, libbeat/cmd/instance/beat_test.go
The `Host info` log entry is ingested to Elasticsearch by the monitoring toolkit when running under Elastic Agent.
The monitoring events are ingested into a data
stream created out of the `logs` index template which is partially defined by the `data-streams-mappings` component template.
The `data-streams-mappings` component template defines auto-mapping for every field named `ip` to have the `ip` field type which does not tolerate having a netmask as the IP address suffix.
This results in dropping events created out of this `Host info` log entry.
This is to trim the netmasks and make sure that IP addresses we're sending are valid, so the event is not dropped.
~~- [ ] I have made corresponding change to the default …
=> Make `Host info` IPs valid

x-pack/elastic-agent/pkg/agent/cmd/upgrade.go
Agent upgrades are not experimental in the latest 7.17.x releases.
=> Remove the experimental upgrade warning.

CHANGELOG.asciidoc
This PR fixes the CHANGELOG.asciidoc to render the list of bugfixes as a list
This PR improves the readability of the release notes in v. 8.6.2
-
=> Update CHANGELOG.asciidoc to render Filebeat/Heartbeat bugfixes as lists

CHANGELOG.asciidoc
Follow-up to https://github.com/elastic/beats/pull/34612. Fixes list formatting problem.
@fearful-symmetry  An empty line is required between text and a bulleted list. Is there a bug in the changelog tool? Also can you update the release checklist to remind folks to preview the changelog to make sure it looks right in HTML?
BTW, when/how do you get the latest 8.x changes into main? I know that backporting changelogs is fraught with problems (hence the need for fragments and the changelog tool). Do you just update main manually from time to time? (I don't think it's super important because no one should be looking at main, but it is confusing to folks who haven't worked on Beats release notes before.)
UPDATED: I see now that forward porting the release notes is in the release checklist for …
=> Fix list formatting problem

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-cel.asciidoc
This extension set is intentionally not included.
It removes an incorrectly included reference to the CEL ext extension package which is not part of the built system.
The documentation currently will confuse users.
- Updates #34610
=> x-pack/filebeat/docs/inputs/cel: remove reference to ext package

CHANGELOG.next.asciidoc, x-pack/filebeat/input/gcs/job.go
- Bug
Enhances error logs with a more structured logging approach.
Removes incorrect formats which were present in the log output.
~~- [] I have made corresponding changes to the documentation~~
~~- [] I have added tests that prove my fix is effective or that my feature works~~
- Closes #34492
=> [filebeat][gcs] - Fixed log format issues

CHANGELOG.next.asciidoc, libbeat/processors/registry.go, libbeat/processors/safe_processor.go, libbeat/processors/safe_processor_test.go
Each processor might end up in multiple processor groups. Every group has its own `Close` that calls `Close` on each processor of that group which leads to multiple `Close` calls on the same processor.
If the `SafeProcessor` wrapper was not used,
the processor would have to handle multiple `Close` calls with adding `sync.Once` in its `Close` function.
We make it easer for processor developers and take care of it in the processor registry instead.
Our customers could see panics in logs which makes it noisy.
Also, there are reports of higher impact:
* https://github.com/elastic/beats/issues/34219#issuecomment-1440078007
* https://github.com/elastic/integrations/issues/5348#issuecomment-1441400841
~~- [ ] I have made …
=> Add `SafeProcessor` wrapper

CHANGELOG-developer.next.asciidoc, libbeat/metric/system/cgroup/cgv2/io_helper_linux.go
On mips family platforms this field is uint32, so convert to uint64 in all cases.
This is a minimal replay of elastic/elastic-agent-system-metrics#71 to allow 7.17 branch beats to build on mips family platforms.
Currently will not build.
-
=> libbeat/metric/system/cgroup/cgv2: explicitly convert Stat_t.Rdev to uint64

CHANGELOG.next.asciidoc, NOTICE.txt, go.mod, go.sum
This updates the version of elastic-agent-system-metrics to v0.4.6.
A bug in previous versions of the library prevents builds on mips family GOARCHs.
-
=> mod: update version of elastic-agent-system-metrics to v0.4.6

CHANGELOG.next.asciidoc, heartbeat/monitors/active/http/http.go
Fixes panics when http url is not parseable:
```
"[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x560c665b2eef]"
"goroutine 58 [running]:"
"github.com/elastic/beats/v7/heartbeat/monitors/wrappers.URLFields(0x0)"
"github.com/elastic/beats/v7/heartbeat/monitors/wrappers/util.go:56 +0x2f"
```
Configure an http monitor with `urls: [" "]`
=> [Heartbeat] Fix tracking http url parsing error

NOTICE.txt, go.mod, go.sum
This updates the dependency for the elastic-agent-shipper -client. Should be merged after or or at the same time as https://github.com/elastic/elastic-agent-shipper/pull/270
=> update shipper client dependency

CHANGELOG.next.asciidoc, metricbeat/docs/modules/sql.asciidoc, metricbeat/docs/modules/sql/query.asciidoc, metricbeat/docs/modules_list.asciidoc, x-pack/metricbeat/module/sql/_meta/docs.html, x-pack/metricbeat/module/sql/_meta/fields.yml, x-pack/metricbeat/module/sql/fields.go, x-pack/metricbeat/module/sql/query/_meta/fields.yml, x-pack/metricbeat/module/sql/query/query.go
Upgrade SQL Metricbeat to GA
Removes Beta tags
https://github.com/elastic/beats/issues/34623 
NA
- Closes [#34623](https://github.com/elastic/beats/issues/34623)
=> Make SQL Metricbeat GA.

metricbeat/module/elasticsearch/node_stats/data.go
Related issue: https://github.com/elastic/kibana/issues/151818
In order to display the roles of each node in the SM UI, we need to extend the collection to also collect the role data. This is exposed by the same endpoint the node_stats metricset is pulling from and the mappings were already added when the ingest metricset was added so we're only extending the event with the roles data.
Related PR: https://github.com/elastic/kibana/pull/152127
=> [elasticsearch] Collect node roles as part of node_stats metricset

CHANGELOG.next.asciidoc, winlogbeat/docs/winlogbeat-options.asciidoc
Adjusts unclear documentation and removes a link to a now-404ing page.
The page linked to in the docs is now a 404 suggeesting that the issue has been fixed. The only currently noted limitations on XPath are described at https://learn.microsoft.com/en-us/windows/win32/wes/consuming-events#xpath-10-limitations
The existing documentation is confusing.
-
=> winlogbeat/docs: adjust XPath query term limit warning

.ci/bump-golang.yml, .mergify.yml
Set the default branch name for the bump automation in charge of the golang.
Update branch names in the mergify rules
Help with debugging what's the branch for, otherwise the hash/sha value is not providing much information
Help with the auto-merge/closing old branches done with Mergify
=> updatecli: force name of the branch for the bump golang version and update mergify

CHANGELOG.next.asciidoc, filebeat/channel/runner.go, libbeat/processors/safe_processor.go
After introducing the `SafeProcessor` wrapper in
https://github.com/elastic/beats/pull/34647 we started returning errors when a processor is being used after its `Close` function has been called.
This led to dropped events and error spam in logs but also confirmed that the root cause of the problem was not just a race condition on `Close` but re-used processors somewhere.
After a long investigation such code that's re-using processors was finally found.
This is the change that removes re-using the processors and instantiates them on each input restart.
Fixes dropped events, panics and error spam in logs.
~~- [] My code follows the style guidelines of this project~~
~~- [ ] I have made corresponding changes to the …
=> Stop re-using processors defined in the config

.github/workflows/check-docs.yml, .github/workflows/check-filebeat.yml, .github/workflows/check-libbeat.yml, .github/workflows/check-packetbeat.yml, .github/workflows/check-xpack-auditbeat.yml, .github/workflows/check-xpack-filebeat.yml, .github/workflows/check-xpack-packetbeat.yml
Run apt-get update before running apt-get install in GitHub actions to ensure the package lists for mirrors are always up to date.
Attempt to fix https://github.com/elastic/beats/actions/runs/4363453232/jobs/7630072199
```
The following NEW packages will be installed:
libsystemd-dev
0 upgraded, 1 newly installed, 0 to remove and 13 not upgraded.
Need to get 306 kB of archives.
After this operation, [11](https://github.com/elastic/beats/actions/runs/4363453232/jobs/7630072199#step:4:12)94 kB of additional disk space will be used.
Err:1 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libsystemd-dev amd64 249.11-0ubuntu3.6
404  Not Found [IP: 40.81.[13](https://github.com/elastic/beats/actions/runs/4363453232/jobs/7630072199#step:4:14).82 80]
E: Failed to fetch …
```
=> Run apt-get update before running apt-get install in GitHub actions

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-httpjson.asciidoc, x-pack/filebeat/input/httpjson/config.go, x-pack/filebeat/input/httpjson/input.go, x-pack/filebeat/input/httpjson/internal/v2/config_request.go, x-pack/filebeat/input/httpjson/internal/v2/config_test.go, x-pack/filebeat/input/httpjson/internal/v2/input.go
This is a manual backport of elastic/beats#34014 tailored to 7.17.
Keep-alive options are provided for both v1 and v2 HTTPJSON, so to simplify the change the keep-alive logic is put in v2 and exported for use by v1.
Customer request.
- Relates #34014
- Relates #33951
=> x-pack/filebeat/input/httpjson: backport configurable keep-alives

heartbeat/autodiscover/builder/hints/monitors_test.go
Manual backport of hint autodiscovery tests flakiness here: https://github.com/elastic/beats/pull/34307
With [#34759](https://github.com/elastic/beats/pull/34307/files#diff-a051d69f4bebe8212813e94b6996485b5ad67726d9b63d1cc339e97633faa89eL99), same test flakiness (which was fixed later on 8.X) has been introduced into 7.17, this manual backport addresses that.
=> [Manual backport][Heartbeat] Fix hint generator test

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-cel.asciidoc
Improves documentation for the Filebeat CEL input.
Improves clarity and adds docs for configuration fields that were omitted.
-
=> x-pack/filebeat/input/cel: improve user docs

x-pack/metricbeat/module/stan/channels/channels_integration_test.go, x-pack/metricbeat/module/stan/stats/stats_integration_test.go, x-pack/metricbeat/module/stan/subscriptions/subscriptions_integration_test.go, x-pack/metricbeat/module/stan/test_stan.py
This PR skips the integration and system tests for the x-pack metricbeat `stan` module.
Currently, these tests are [consistently failing on `main`](https://github.com/elastic/beats/issues/34844) and blocking PRs from being merged (as their builds are failing as well on the same tests).  They are also failing on `8.7`, `8.6`, and `7.17` branches.
=> Skip integration and system tests for stan module

.golangci.yml
The old linter definitions required no space at the beginning of a `nolint` comment line, but in 1.19 `gofmt` always inserts a space there, making the linter requirements incompatible with the `make check` requirements. This PR removes that requirement so the new `gofmt` behavior passes.
=> Make linter requirements compatible with gofmt in 1.19

libbeat/docs/newbeat.asciidoc
ports https://github.com/elastic/beats/pull/34827 to 1.3 branch.
=> [DOCS] Remove hard coded links to master branch

x-pack/filebeat/docs/inputs/input-cel.asciidoc
Flattens and fixes sidebar entry indentations.
- For https://github.com/elastic/integrations/pull/5539#discussion_r1142649796
=> x-pack/filebeat/input/cel: fix doc entry title indentation

CHANGELOG.next.asciidoc, x-pack/filebeat/input/httpjson/value_tpl.go, x-pack/filebeat/input/httpjson/value_tpl_test.go
Previously the regular expression required a space separating the "rel" tag from previous text. While the examples in RFC5988 show a separating space, the ABNF does not indicate a requirement; the space that does exist in the examples is allowed by RFC2616 because of the implied *LWS rule for token separation.
The new regular expression also more carefully considers quoting for rel parameters and semicolon requirements.
The existing code rejects valid links.
- Fixes #34603
=> x-pack/filebeat/input/httpjson: fix relation parameter handling in getRFC5988Link

libbeat/processors/safe_processor.go, libbeat/processors/safe_processor_test.go
This will make the wrapping more efficient and will reduce unnecessary overhead.
It's a follow up to https://github.com/elastic/beats/pull/34647
To maintain better performance of the processing pipeline.
The change is covered with a unit test.
- Relates https://github.com/elastic/beats/pull/34647
=> Don't safe-wrap processors that don't have `Close`

filebeat/channel/runner.go, filebeat/channel/runner_mock_test.go, filebeat/channel/runner_test.go
It's a follow-up to https://github.com/elastic/beats/pull/34761
This test makes sure that none of the critical configuration fields are re-used between instances of the pipeline client.
So, we don't have regressions in the future.
I reverted the change made in https://github.com/elastic/beats/pull/34761 and saw the new test failing:
- Relates https://github.com/elastic/beats/pull/34761
- Closes https://github.com/elastic/beats/issues/34783
=> Add test for the processor re-use issue

winlogbeat/eventlog/wineventlog.go
Identify the Windows event log readers as input type `winlog` in metrics published through the /inputs/ API.
Fixes #34885
This gives the input a consistent type name in the [`/inputs/` API](https://www.elastic.co/guide/en/beats/filebeat/master/http-endpoint.html#_inputs) data.
=> winlogbeat metrics - Set input type as "winlog"

libbeat/monitoring/inputmon/httphandler.go, libbeat/monitoring/inputmon/httphandler_test.go
This filters metrics from the /inputs/ endpoint for entities that lack an input `name` and `id`.
This is needed because we continued to use the "dataset" namespace in the monitoring registry instead of using a new one like "inputs". Originally I planned to use to new namespace but I stayed with `dataset` because I wanted to prevent a breaking change for existing users of the /dataset API endpoint. This meant that metrics from the log input (and possibly others) that don't yet follow the conventions need to be filtered.
The data being produced from the [`/inputs/` API](https://www.elastic.co/guide/en/beats/filebeat/master/http-endpoint.html#_inputs) is different than what we expected.
- Relates #33859
Prior to this change when using the `log` input you would get data like this from the …
=> libbeat/monitoring/inputmon - Ignore dataset metrics without name and id

libbeat/pprof/pprof.go
Several pprof routes were returning 404. The route matching behavior changed due an earlier API server modification.
- Relates #33859
=> [libbeat] Register missing /debug/pprof/ routes in beat HTTP API server

CHANGELOG.next.asciidoc, x-pack/heartbeat/monitors/browser/source/project.go
Using the internet and performing other checks is unnecessary in this context, and just slows down what should be fast. Will need to be manually tested to ensure that no internet connection is needed in airgapped envs
=> [Heartbeat] Don't use inet / be silent  when setting up projects

CHANGELOG.next.asciidoc, winlogbeat/docs/winlogbeat-options.asciidoc
This introduces the concept of event log names earlier in the documentation and provides the preferred PowerShell cmdlet first before showing the fallback cmdlet if the preferred option is not available.
Links to the Microsoft documentation for the cmdlets are also added.
This improves user on-boarding experience.
- Relates elastic/integrations#5673
=> winlogbeat/docs: improve event_logs.name docs

filebeat/scripts/mage/build.go
The golang-crossbuild images contain the journald development dependencies so
the build steps do not need make changes to the environment before building.
Fixes #34938
~Packaging builds are failing.~ (see https://github.com/elastic/beats/issues/34938#issuecomment-1485646966)
`cd filebeat; SNAPSHOT=true mage -v package`
- Fixes #34938
=> filebeat/scripts/mage - Remove installation of journald deps from crossBuild

.golangci.yml
The `golangci` linter's `typecheck` test has a broken check: it will flag packages as "imported and not used" when the package is only imported for its types rather than its functions. We have a rule in the config to disable the check, however it used the string "imported but not used" and the current linter message has changed slightly; this PR updates the config to detect the new text.
=> Fix linter typecheck rule

x-pack/libbeat/management/tests/fbtest/filebeat_v2_test.go, x-pack/libbeat/management/tests/init.go, x-pack/libbeat/management/tests/mbtest/metricbeat_v2_test.go, x-pack/libbeat/management/tests/mock_server.go, x-pack/libbeat/management/tests/output_read.go
A quick fix for some issues that @faec ran into
This changes how the V2 manager integration tests work. Instead of relying on a timeout to tell us when to shut down, it waits until a condition is met, in this case, the tests will now wait until they have enough data to test against.
This was a source of test failures.
=> Remove timeouts v2 manager integration tests

NOTICE.txt, go.mod, go.sum, libbeat/cmd/instance/beat.go, libbeat/processors/add_host_metadata/add_host_metadata.go, libbeat/processors/add_host_metadata/add_host_metadata_test.go
This PR fixes a bug wherein a Beat would fail to start if the FQDN lookup failed.
FQDN lookup is "best effort".  As such, if the lookup fails for some reason, we should not fail to start a Beat or halt execution otherwise.  Instead, we should fallback to the OS-provided hostname and continue execution.
1. Build Filebeat (or any other Beat) with this PR.
```sh
cd beats/filebeat
mage clean build
```
2. Set hostname to something that wouldn't resolve via DNS.  On MacOS this can be done via:
```sh
orig_hostname=$(hostname -f)
sudo scutil --set HostName cowchicken
```
3. Run `filebeat version`.  This command should report the version as usual and NOT fail with an FQDN-related error (as reported in #34910)
```sh
./filebeat version
```
```
filebeat version 8.8.0 (arm64), libbeat 8.8.0 …
```
=> Log any FQDN lookup errors and fallback to OS-reported hostname

auditbeat/auditbeat.reference.yml, filebeat/filebeat.reference.yml, heartbeat/heartbeat.reference.yml, libbeat/_meta/config/output-elasticsearch.reference.yml.tmpl, libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc, metricbeat/metricbeat.reference.yml, packetbeat/packetbeat.reference.yml, winlogbeat/winlogbeat.reference.yml, x-pack/auditbeat/auditbeat.reference.yml, x-pack/filebeat/filebeat.reference.yml, x-pack/functionbeat/functionbeat.reference.yml, x-pack/heartbeat/heartbeat.reference.yml, x-pack/metricbeat/metricbeat.reference.yml, x-pack/osquerybeat/osquerybeat.reference.yml, x-pack/packetbeat/packetbeat.reference.yml, x-pack/winlogbeat/winlogbeat.reference.yml
Document the undocumented default value on `output.elasticsearch.loadbalance`.
The default is `true` on `output.redis.loadbalance` but `false` on `output.logstash.loadbalance`.
So, the default is not guessable on `output.elasticsearch.loadbalance`; people must read the code to know the default.
Tested by the following `docker-compose.yml`.
<details>
<summary>Metricbeat -> 2x separate Elasticsearch clusters</summary>
```
version: "3.9"
services:
elasticsearch1:
image: docker.elastic.co/elasticsearch/elasticsearch:8.5.2
environment:
- discovery.type=single-node
- xpack.security.enabled=false
- ES_JAVA_OPTS=-Xms1g -Xmx1g
elasticsearch2:
image: docker.elastic.co/elasticsearch/elasticsearch:8.5.2
environment:
- discovery.type=single-node
- xpack.security.enabled=false
- ES_JAVA_OPTS=-Xms1g …
```
=> Add docs about output.elasticsearch.loadbalance

filebeat/docs/howto/migrate-to-filestream.asciidoc
- Docs change
Highlights `take_over` is in beta
The warning is in the `take_over` option itself, on a separate page https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-filestream.html#filebeat-input-filestream-take-over
Sets expectations for users.
=> Highlight Take over is in beta

filebeat/tests/system/test_input.py, libbeat/outputs/shipper/shipper_test.go, x-pack/filebeat/input/cometd/input_test.go, x-pack/metricbeat/module/sql/query/test_sql_oracle.py
Skip all unreliable tests from the path month. The tests can be fixed and then reenabled separately.
- Relates https://github.com/elastic/beats/issues/34993
- Relates https://github.com/elastic/beats/issues/34982
- Relates https://github.com/elastic/beats/issues/34984
- Relates https://github.com/elastic/beats/issues/34956
=> Skip all unreliable tests from the past month.

libbeat/docs/shared-feature-flags.asciidoc
This updates the Beats [Feature flags page and the FQDN setting](https://www.elastic.co/guide/en/beats/metricbeat/master/configuration-feature-flags.html). I thought we needed to add new docs, but they were added already via https://github.com/elastic/beats/pull/34456, so this is just to provide a bit more info.
The additions here are based on discussion in [this similar PR](https://github.com/elastic/observability-docs/pull/2817) for the Elastic Agent docs.
Rel: https://github.com/elastic/ingest-dev/issues/1641
**Preview** (showing Metricbeat but all Beats are updated):
=> Add detail for fqdn feature docs

CHANGELOG.next.asciidoc, winlogbeat/docs/winlogbeat-options.asciidoc
- Added note in documentation about a situation where the event ID clause limit is lower than the claimed 22 clause limit.
- Closes #35048
=> [Winlogbeat] Document 21 Event ID clause limit under certain situations

libbeat/docs/output-cloud.asciidoc
This PR closes [Issue 27237](https://github.com/elastic/beats/issues/27237).
It adds a link to the **Configure Beats and Logstash with Cloud ID** page in the Elastic Cloud docs.
Users have had issues finding this information in the past.
=> [Docs] add link to cloud docs on configuring Cloud ID

CHANGELOG.next.asciidoc, filebeat/input/tcp/input.go, filebeat/input/tcp/input_test.go, filebeat/input/tcp/testdata/proc_net_tcp.txt, filebeat/input/udp/input.go
A panic occurred while parsing /proc/net/tcp and reaching the final empty line. This occurred on Linux when the desired socket was not found in the list.
Fixes #35064
The panic causes Filebeat to exit.
- Fixes #35064
- Relates #35068
=> filebeat/input/tcp - Fix panic in linux input metrics (#35068)

x-pack/metricbeat/module/sql/query/test_sql_oracle.py
`x-pack.metricbeat.module.sql.query.test_sql_oracle.Test` is broken (https://github.com/elastic/beats/issues/34993) and a PR was submitted to disable it last week (https://github.com/elastic/beats/pull/35030) however it's still [running and failing on active PRs](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-35078/10/testReport/junit/x-pack.metricbeat.module.sql.query.test_sql_oracle/Test/Extended___x_pack_metricbeat_cloudAWS___test_query/), presumably because the `@unittest.skip` directives didn't stack correctly in the unittest api. This PR removes the conflicting directive so the test will be skipped for real.
=> Disable flaky test (x-pack.metricbeat.module.sql.query.test_sql_oracle.Test)

CHANGELOG.next.asciidoc, packetbeat/_meta/config/beat.reference.yml.tmpl, packetbeat/_meta/config/beat.yml.tmpl, packetbeat/packetbeat.reference.yml, packetbeat/packetbeat.yml, packetbeat/tests/system/config/packetbeat.yml.j2, x-pack/packetbeat/packetbeat.reference.yml, x-pack/packetbeat/packetbeat.yml
This fixes documentation that misdirects users to use "-1" as a sentinel. This value causes packetbeat to fail to configure.
See https://github.com/elastic/beats/blob/25acf60399e2c56f544f4f76cb76611a28847cdf/packetbeat/flows/flows.go#L49-L66 and https://play.golang.com/p/Z7Si8WEzDAL.
The current documentation misleads users to use an invalid value.
- For elastic/integrations#5771
=> {,x-pack/}packetbeat: fix documentation for flows period

x-pack/filebeat/docs/inputs/input-http-endpoint.asciidoc
Based on https://github.com/elastic/beats/blob/e6d97ce62e54a9c914fdfc5c336e44f452f199a6/x-pack/filebeat/input/http_endpoint/config.go#L48, the value of `prefix` defaults to `json` but the public facing documentation doesn't include this. The aim of this PR is to make this clear.
Make it clear what the default value of `prefix` is.
=> Adding default value for prefix

x-pack/metricbeat/module/sql/query/test_sql_oracle.py
I figured out the real reason this test was still causing CI failures despite [repeated](https://github.com/elastic/beats/pull/35030) [attempts](https://github.com/elastic/beats/pull/35083) to disable it: the failure was happening in the class setup, so even though the only individual test case was disabled, it was still causing an exception when the class itself couldn't bring up the support containers.
This PR disables the test class instead of just the method, which should prevent failures like [this](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-35078/15/testReport/x-pack.metricbeat.module.sql.query.test_sql_oracle/Test/Extended___x_pack_metricbeat_cloudAWS___test_query/) at head.
=> Correctly disable flaky test

CHANGELOG.next.asciidoc, x-pack/filebeat/_meta/config/filebeat.inputs.reference.xpack.yml.tmpl, x-pack/filebeat/docs/inputs/input-netflow.asciidoc, x-pack/filebeat/filebeat.reference.yml, x-pack/filebeat/input/netflow/config.go, x-pack/filebeat/input/netflow/decoder/config/config.go, x-pack/filebeat/input/netflow/decoder/ipfix/ipfix_test.go, x-pack/filebeat/input/netflow/decoder/v9/session.go, x-pack/filebeat/input/netflow/decoder/v9/session_test.go, x-pack/filebeat/input/netflow/decoder/v9/v9.go, x-pack/filebeat/input/netflow/decoder/v9/v9_test.go, x-pack/filebeat/input/netflow/input.go
This adds an option to allow users to specify sharing of v9 and ipfix templates within a session without regard to the template/flow origin.
This behaviour is the default option in logstash and the current filebeat behaviour is blocking users migrating from logstash.
-
=> x-pack/filebeat/input/netflow: allow v9 template sharing

.github/CODEOWNERS
Adding `elastic/security-external-integrations` as the explicit owner for `gcs` and `azureblobstorage` inputs.
=> Add codeowners for `gcs`, `azureblobstorage` inputs

libbeat/tests/resources/goroutines.go, libbeat/tests/resources/goroutines_test.go
Make all GoroutinesChecker methods be on a pointer receiver
It's not recommended to mix methods on the same type having a pointer and a non-pointer receiver.
N/A
N/A
=> Make all GoroutinesChecker methods be on a pointer receiver

CHANGELOG.next.asciidoc, x-pack/filebeat/module/cef/log/test/fp-ngfw-smc.log-expected.json, x-pack/filebeat/processors/decode_cef/keys.ecs.go, x-pack/filebeat/processors/decode_cef/testdata/samples.log.golden.json
Fix the ECS output format by making [`observer.ip`](https://www.elastic.co/guide/en/ecs/current/ecs-observer.html#field-observer-ip) into an array of strings instead of string.
Fixes #35140
Filebeat should follow the ECS definition precisely.
- Closes #35140
`cd x-pack/filebeat && PYTEST_ADDOPTS="-k test_xpack_modules" TESTING_FILEBEAT_MODULES=cef GENERATE=true mage -v pythonIntegTest`
=> x-pack/filebeat/processors/decode_cef - Fix ECS observer.ip

CHANGELOG.next.asciidoc, x-pack/filebeat/module/mysqlenterprise/audit/ingest/pipeline.yml
MySQL send its audit logs as parts of an infinitely long JSON array and so separates each line of the logs with a comma. We don't know that we are in an array since the first line of the log may not have been sent to us, so remove the trailing comma to treat each element of the partial array object as an object in a JSON stream.
Strict parsing has broken audit log ingest
-
=> x-pack/filebeat/module/mysqlenterprise: fix handling of streaming data sent as partial array object

.github/CODEOWNERS, CHANGELOG.next.asciidoc, x-pack/filebeat/input/entityanalytics/provider/azuread/authenticator/oauth2/oauth2.go, x-pack/filebeat/input/entityanalytics/provider/azuread/authenticator/oauth2/oauth2_test.go, x-pack/filebeat/input/entityanalytics/provider/azuread/azure.go
- In both the full sync and incremental update functions in Azure AD, a defer statement was always overriding the error value from the function. If an error occurred during the sync/update operation, it would be overwritten by the defer.
- Since the error value produced in the defer was not used elsewhere, it is now stored in its own variable
- Added additional error information for OAuth2 response
- Added test case for error OAuth2 response
- Add SEI as codeowner of entityanalytics input
- Errors are being squelched.
- Added unit test in `oauth2_test` to test propagation of error values from OAuth2 response
- Testing with expired token is also …
=> [Filebeat] entityanalytics_azure - Fix accidental error overwrite in defer statement

.ci/packaging.groovy
Disable upstream integration with the packaging and the build/test workflows
For simplicity, every single workflow has been defined independently and the `upstream` section is the one orchestrating them. Somehow, `DRA` is not needed to run for a short period of time.
=> ci: disable upstream integration

.ci/bump-golang.yml
Filter the regex to match the one with the `go-version`
otherwise the one with the stack will be changed, see https://github.com/elastic/beats/pull/35041/commits/badafce5ad8ae168c189c4ca6822db20f3f9efb4
I used this changeset in addition to:
```diff
diff --git a/.ci/bump-golang.yml b/.ci/bump-golang.yml
index 9b98297991..1e8ce4334b 100644
--- a/.ci/bump-golang.yml
+++ b/.ci/bump-golang.yml
@@ -55,7 +55,8 @@ sources:
username: '{{ requiredEnv "GIT_USER" }}'
versionfilter:
kind: regex
-        pattern: go1\.{{ source "minor" }}\.(\d*)$
+        #pattern: go1\.{{ source "minor" }}\.(\d*)$
+        pattern: go1\.20\.(\d*)$
gomod:
dependson:
```
and when I ran `GIT_USER=foo@gmail.com GIT_EMAIL=foo@gmail.com updatecli diff --config .ci/bump-golang.yml` it produced
```
update-version.asciidoc …
```
=> fix: updatecli to change go_version only

x-pack/metricbeat/module/cockroachdb/_meta/Dockerfile, x-pack/metricbeat/module/cockroachdb/docker-compose.yml
Updating cocroachdb/cockroach docker image for CI due to issues like this: 
```
[2023-04-25T06:11:20.938Z] Service 'cockroachdb' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y curl' returned a non-zero code: 100
[2023-04-25T06:11:20.938Z]     status_integration_test.go:32: failed to start service 'cockroachdb: exit status 1
```
Fixes: #35211
=> Fix cockroachdb/cockroach Docker image for CI

metricbeat/module/kafka/_meta/Dockerfile, x-pack/filebeat/input/gcppubsub/_meta/Dockerfile
[Debian stretch was moved to archive](https://lists.debian.org/debian-devel-announce/2023/03/msg00006.html) which means Docker images are failing when trying to curl security.debian.org
This PR adds a workaround for that to unblock builds. 
Owners of integration should consider moving to newer base
Failure example: https://github.com/elastic/beats/pull/35196
=> Workaround for debian stretch

testing/environments/snapshot.yml
<Actions>
<action id="d6ae724b1aa435f7902ad1e8e4d4713d4e1ed691d13b8d492c92c33383cb6d8c">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 8.8.0-ebff07ec

testing/environments/snapshot.yml
<Actions>
<action id="291374c726eebd493358c6ec6bcb8da6db2c2ed7ab89d5a23db4a80a37722db1">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 8.9.0-a2c79020

metricbeat/docker-compose.yml, metricbeat/module/logstash/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
Merge only after the release of 7.17.10.
=> [Release] Update test environments for 7.17.11

libbeat/outputs/output_reg.go
Comment-only cleanup: during the review of https://github.com/elastic/beats/pull/35118, a particular field was changed from using a settings object to using a factory, but the associated comment didn't get updated so the checked-in code still reflects the now-nonexistent settings field.
=> Fix a comment that wasn't properly updated in previous PR

filebeat/docs/filebeat-general-options.asciidoc, libbeat/docs/loggingconfig.asciidoc
It updates the logging.files.permissions documentation to consider umask as previously done in https://github.com/elastic/beats/pull/28347, but for some reason isn't present in the current docs. The correct is [7.16](https://www.elastic.co/guide/en/beats/filebeat/7.16/configuration-logging.html#_logging_files_permissions), but the other versions do not have it. See [7.17](https://www.elastic.co/guide/en/beats/filebeat/7.17/configuration-logging.html#_logging_files_permissions), [8.1](https://www.elastic.co/guide/en/beats/filebeat/8.1/configuration-logging.html#_logging_files_permissions), [main](https://www.elastic.co/guide/en/beats/filebeat/master/configuration-logging.html#_logging_files_permissions)
Avoid confusion due to missing documentation
N/A
- Closes #35256
=> [Docs] Update logging.files.permissions documentation to consider umask

.golangci.yml, filebeat/input/filestream/copytruncate_prospector.go, filebeat/input/filestream/filestream.go, filebeat/input/filestream/filestream_test.go, filebeat/input/filestream/identifier_inode_deviceid.go, filebeat/input/filestream/internal/input-logfile/clean.go, filebeat/input/filestream/internal/input-logfile/publish.go, filebeat/input/filestream/internal/input-logfile/publish_test.go, filebeat/input/filestream/internal/input-logfile/store.go, filebeat/input/filestream/internal/input-logfile/store_test.go, filebeat/input/filestream/internal/input-logfile/update_writer.go, filebeat/input/filestream/prospector.go, filebeat/input/filestream/prospector_test.go
So, we have no more old issues highlighted on our PRs.
Also removed deprecated linters.
It increased the quality of the code, uncovers some previously hidden errors and makes it more welcoming for external contributors who decide to open a PR to the `filestream` package.
run
```sh
golangci-lint run ./...
```
in `./filebeat/input/filestream`
- Closes https://github.com/elastic/beats/issues/35212
=> Resolve all linter issues for the `filestream` package

testing/environments/snapshot.yml
<Actions>
<action id="9df5b00f2c65b077ac21d434a49d6761590730c3c4304c3d1cd4cd8fa6d36da3">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 8.7.1-2ea32c14

.github/workflows/notify-stalled-snapshots.yml
Create one thread per branch
Avoid issues when similar emails for different branches are not shown in an unique thread in Google groups
=> notify: add date to avoid google group issues with similar subjects

NOTICE.txt, filebeat/docs/filebeat-general-options.asciidoc, libbeat/docs/loggingconfig.asciidoc
manual backport of https://github.com/elastic/beats/pull/35257
=> [8.2](backport #35257) [Docs] Update logging.files.permissions documentation to consider umask

testing/environments/snapshot.yml
<Actions>
<action id="95e591f352fd6467fb0891d8842bfc4401f96b13c5b13130e793aea03738ead4">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 8.9.0-5c23b5b2

dev-tools/packaging/templates/docker/Dockerfile.tmpl
See 
https://github.com/elastic/cloud-on-k8s/pull/6688#issuecomment-1514363649
and
https://github.com/elastic/cloud-on-k8s/issues/6740
Similar change was recently merged into [elasticsearch](https://github.com/elastic/elasticsearch/pull/95390) for the same issue.
This change will allow the beats container in Kubernetes to be ran with runAsNonRoot as it checks against the numeric UID, and not a name.
Without this change you encounter the following error:
```
state:                                                                                                                                                                                                                                                                                                               │
│       waiting: …
```
=> Use UID for dockerfile to allow runasNonRoot to be used.

CHANGELOG.next.asciidoc, packetbeat/beater/packetbeat.go
In some circumstances when a managed instance of packetbeat is restarted Stop will panic with close of closed channel. This appears to be happening because on reload the sniffer may have returned an error, closing `pb.done`. If the packetbeat instance is then stopped done is closed a second time. So ensure that all closes are protected by `pb.stopOnce`.
The current situation leads to contamination of the logs with useless fatal error lines. These do no indicate a failure since they are happening when packetbeat is shutting down, but are a debugging distraction.
-
=> packetbeat/beater: prevent double close of pb.done

CHANGELOG.next.asciidoc, libbeat/processors/add_cloud_metadata/provider_google_gce.go, libbeat/processors/add_cloud_metadata/provider_google_gce_test.go
Add cloud.region field to GCE cloud provider
To align with other cloud providers
- 
Before:
After:
=> [add_cloud_metadata processor] add cloud.region field to GCE cloud provider

testing/environments/snapshot.yml
<Actions>
<action id="eef07119a8dcd944a889226661806126d9eed2508e8f46fff9bc730e5999920b">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 8.9.0-23370c3a

filebeat/beater/channels.go, libbeat/beat/pipeline.go, libbeat/publisher/pipeline/client.go
Remove the `FilteredOut` callback from the `ClientListener` interface. This callback was redundant with the `EventListener.AddEvent(_, false)` callback, which is called under identical circumstances and at the same time, however unlike `AddEvent` no current listener implementations perform any actions in `FilteredOut`, nor is it documented anywhere outside its interface definition. This PR is just a cleanup, it doesn't change any behavior.
=> Remove unused pipeline callback ClientListener.FilteredOut

CHANGELOG.next.asciidoc, heartbeat/beater/heartbeat.go, heartbeat/hbtestllext/isdefs.go, heartbeat/monitors/factory.go, heartbeat/monitors/wrappers/monitorstate/esloader.go, heartbeat/monitors/wrappers/monitorstate/monitorstate.go, heartbeat/monitors/wrappers/monitorstate/tracker.go, x-pack/heartbeat/heartbeat.yml, x-pack/heartbeat/scenarios/basics_test.go
The states loader currently does not correctly read the location from the `heartbeat.run_from.id` config option. It's currently only applied to the `observer.*` fields. This patch fixes that. It also makes the logs more clear.
Note that we now log on each __initial__ state for a monitor. This means one more log line, but only on the first exec of that monitor.
Enable a monitor, either lightweight or browser, and set in your hearbeat config:
```
heartbeat.run_once: true
heartbeat.run_from:
id: minneapolis
```
Then run with
```
mage build && ./heartbeat -e -E cloud.id=$CLOUD_ID -E cloud.auth=$CLOUD_AUTH -E output.elasticsearch.allow_older_versions=
true 2>&1 | jq .message
```
Look for the output:
```
"no previous state found for monitor my-monitor-aoeuncoaeuc in Elasticsearch …
```
=> [Heartbeat] Fix run from location in states loader

.ci/bump-golang.yml, .github/workflows/bump-golang.yml
Remove the non-dependency with elastic/golang-crossbuild and use the `elastic/golang-crossbuild` to search for the releases rather than `golang/go`
Remove 
In favour of using the latest known release from https://github.com/elastic/golang-crossbuild/releases
The existing automation in `elastic/golang-crossbuild` is in charge of `auto-merge` (see https://github.com/elastic/golang-crossbuild/blob/30b8ae9b4f6c7904b702e767d8ac630823b82ba7/.mergify.yml#L57-L66)
=> updatecli: use golang-crossbuild repository

testing/environments/snapshot.yml
<Actions>
<action id="26b9cc016c1d13bc0ceaee509d64d1199cb3aa162a542e874248726fee27dca8">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 8.8.0-8d0a4918

testing/environments/snapshot.yml
<Actions>
<action id="db84aae128594f69a62faf3325c3074da9535ab8a470856b328b66af214a59d6">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 7.17.11-47c70080

testing/environments/snapshot.yml
<Actions>
<action id="0e03c06698122665b76fd1dc8cbfc42751f0334cdae3d9590568f12382016661">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 8.9.0-c595c7d9

testing/environments/snapshot.yml
<Actions>
<action id="f831ee411b92d9a1bb631cb29ca3aa4728ab2a596a8dcffdd56aaa35302e5d5c">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 7.17.11-4961dcd0

heartbeat/monitors/factory.go, heartbeat/monitors/factory_test.go
we incorrectly always read from the beat location which may be null, this fixes that.
No changelog since this bug has never been released.
Test by reloading via file the following config: with the `run_from` field present and not
```
- type: http
id: treload
name: treload
urls: "https://blog.andrewvc.com"
schedule: "@every 15s"
run_from:
id: testid
geo:
name: htnoeu
```
=> [Heartbeat] Fix NPE on reloads with run_from

CHANGELOG.next.asciidoc, filebeat/docs/modules/zoom.asciidoc, libbeat/common/jsontransform/jsonhelper.go, x-pack/filebeat/docs/inputs/input-http-endpoint.asciidoc, x-pack/filebeat/input/http_endpoint/config.go, x-pack/filebeat/input/http_endpoint/crc.go, x-pack/filebeat/input/http_endpoint/crc_test.go, x-pack/filebeat/input/http_endpoint/handler.go, x-pack/filebeat/input/http_endpoint/handler_test.go, x-pack/filebeat/input/http_endpoint/input.go, x-pack/filebeat/input/http_endpoint/validate.go, x-pack/filebeat/module/zoom/_meta/docs.asciidoc
Added support to process CRC requests in the filebeat's http_endpoint input.
Currently, the only module that we support with CRC webhook validation is Zoom, so it has been added the procedure to process Zoom CRC requests according to [its documentation](https://developers.zoom.us/docs/api/rest/webhook-reference/#validate-your-webhook-endpoint).
It has been added a new setting `crc.provider` to the `http_endpoint` configuration to choose the webhook provider in case the list of supported services is in the future.
Currently, the HTTP endpoint can only send static responses. Some use cases such as the CRC validation require dynamic responses based on the content of the request or other data.
For now, the only allowed provider for CRC requests is …
=> x-pack/filebeat/input/http_endpoint: Add CRC validation for webhooks

testing/environments/snapshot.yml
<Actions>
<action id="f2ad8761007153d6df94e8a7d5f5f36101a7723b3bb5ac70699da6c78e957c82">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 8.7.2-9848dc50

testing/environments/snapshot.yml
<Actions>
<action id="59393142deea1b8352777236e75c2d41167cd6ec38d266ce44cf09ea741aa2e8">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 8.8.0-c26f78b8

heartbeat/monitors/wrappers/monitorstate/monitorstate.go, heartbeat/monitors/wrappers/monitorstate/monitorstate_test.go
We currently allow any chars in state location names, this normalizes them to [A-Za-z0-9_-_] for easier handling.
No changelog since no released version affected
=> [Heartbeat] Normalize state location names

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-cel.asciidoc, x-pack/filebeat/input/cel/config.go, x-pack/filebeat/input/cel/input.go
This adds two features to improve user experience. The first is a guard rail to prevent users unwittingly constructing a CEL program that enters an infinite loop and blocking further processing. While CEL is not Turing complete, there is a Turing escape hatch in the form of the want_more field. If a user sets want_more to true and returns an event the inner execution loop will be re-run. If an error in the CEL program results in non-progress, this would result in an infinite loop. By providing a bound on the number of executions each periodic invocation can run, and warning when the budget is exceeded, this is mitigated.
The second is a change to the look-up table for MIME types. While the documentation says that CSV MIME types are accessed via the name "text/csv; header=absent" and …
=> x-pack/filebeat/input/cel: add execution budget and relax CSV mime name

libbeat/monitoring/inputmon/input.go, libbeat/monitoring/inputmon/input_test.go
Add a defensive check to prevent metrics from being registered into the global 'dataset' namespace when the ID or input type are empty.
This is not in response to any known problem. There was already a similar check on HTTP `/inputs/` endpoint that would have prevented metrics from inputs with an ID or input type from being exposed. This pushes that check earlier and in effect "null routes" those metrics an a manner that is transparent to the callers.
I would consider an empty input type to be a developer mistake whereas an the ID is user controllable. So you could conceive of having a hard error (like a panic) if input type were empty. At the moment I'm taking a softer approach in the defense.
Relates #35354
- Relates #35354
=> libbeat/monitoring/inputmon - Add defensive check for empty ID or input type

filebeat/input/filestream/internal/input-logfile/harvester.go
The log line remove by this commit is unnecessary, it is not an actual
error in the sense something will not work. It only means the
harvester is already running for this file so another one does not
need to be started. Keeping this log line will only spam our log files
and make users worried.
It was spamming our logs and would make our uses worry for no good reason
Run Filebeat with the `filestream` input enabled, you should not see log …
=> Remove unnecessary logging

CHANGELOG.next.asciidoc, heartbeat/beater/heartbeat.go, heartbeat/tracer/tracer.go
Fixes the formatting issue when the socket tracing connection cannot be established within the configured timeout.
=> [Heartbeat]: fix error formatting on socktrace timeout

CHANGELOG.next.asciidoc, heartbeat/docs/monitors/monitor-browser.asciidoc, x-pack/heartbeat/monitors/browser/browser.go
Remove beta references inside heartbeat docs and remove synthetics beta label: 
```
Synthetic browser monitor detected! Please note synthetic monitors are a beta feature!
```
=> [Heartbeat] remove Synthetics beta label

CHANGELOG.next.asciidoc, winlogbeat/sys/wineventlog/wineventlog_windows.go
EvtFormatMessage appears to sometimes claim that more buffer was used during a rendering call than was or exists, so do not use this value except in the query to get the needed buffer size.
It is a subset of the change in #34005. The remainder of the removal of the passed buffer is left for later work.
Winlogbeat will sometimes panic due to a bounds error.
-
=> winlogbeat/sys/wineventlog: don't use claimed buffer use value

metricbeat/docs/modules/aws.asciidoc, x-pack/metricbeat/module/aws/_meta/docs.asciidoc
Add documentation about the `tags_filter` feature. 
This feature has been backported but it is not present in the [documentation](https://www.elastic.co/guide/en/beats/metricbeat/7.17/metricbeat-module-aws.html). We had a related SDH, where the user thought that the tags processor is doing what `tags_filter` is doing. As a result, this generated a large bill because they were not aware that API calls are still made for all resources regardless of the tags.
=> Metricbeat AWS Module Docs Fix - Cherry picked from 96f67e8

CHANGELOG.next.asciidoc, winlogbeat/eventlog/wineventlog_experimental.go, winlogbeat/sys/wineventlog/iterator.go, winlogbeat/sys/wineventlog/renderer.go
In the case that an experimental API EventLog has been opened against a non-available log channel, the EventLog will be closed. This unconditionally closes the EventIterator and Renderer that the EventLog hold. The EventIterator is only valid after a successful call to Open and so may be nil when a valid EventLog is closed, resulting in a nil-deref [panic](https://github.com/elastic/beats/issues/33966#issuecomment-1542526853).
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xc33574]
goroutine 96 [running]:
github.com/elastic/beats/v7/winlogbeat/sys/wineventlog.(*EventIterator).Close(0x0)
github.com/elastic/beats/v7/winlogbeat/sys/wineventlog/iterator.go:199 +0x34
github.com/elastic/beats/v7/winlogbeat/eventlog.(*winEventLogEx …
=> winlogbeat/sys/wineventlog: don't panic on nil iterator/renderer close

filebeat/input/filestream/internal/input-logfile/publish.go, filebeat/input/v2/input-cursor/publish.go
Logs the error when Filebeat fails to set a state into the persistent store (registry)
Currently we only know the operation failed and the entry that failed, however we do not know why it failed.
~~## Logs~~
=> Log error when setting data into the persistent store fails

packetbeat/sniffer/afpacket.go, packetbeat/sniffer/afpacket_linux.go, packetbeat/sniffer/afpacket_nonlinux.go, packetbeat/sniffer/device.go, packetbeat/sniffer/file.go, packetbeat/sniffer/sniffer.go
This is some minor maintenance to the Packetbeat sniffer package. Changes include:
- Replace deprecated logger calls with a named per-instance logger. All log statements from the package will name contain log.logger=sniffer.
- Fix a few nits in the godoc and comments.
- Correct errors that used capitalized error strings.
- Replace unused params with underscore.
- Remove unused receiver in methods.
- Remove two extremely verbose logging statements from the sniffer hot path ("timed out" and "Packet number: %d").
Code quality.
=> packetbeat/sniffer - Use non-deprecated logger statements

CHANGELOG.next.asciidoc, x-pack/filebeat/input/azureblobstorage/state.go
If the input is run and loads a cursor state with no partially processed data, the CheckPoint.PartiallyProcessed map may be left nil. This results in a nil-map assignment panic when updates are made to the internal checkpoint. Currently the only other place PartiallyProcessed is set is on CheckPoint value construction, so ensure that it is also done here.
The current behaviour is a crash.
-
=> x-pack/filebeat/input/azureblobstorage: ensure checkpoint is valid after cursor filling

.github/CODEOWNERS
So, the code reviews are assigned properly.
According to @jlind23 the cloud metadata processor belongs to @elastic/obs-cloud-monitoring
and the Kubernetes metadata processors belongs to @elastic/obs-cloudnative-monitoring
I occasionally see PRs that are assigned to the data plane team but they're about internals of these two processors. I think it would be better if the owning teams review them.
I might be wrong about this ownership, if so, please leave a comment.
=> Add `elastic/obs-cloud-monitoring` to own cloud-related processors

metricbeat/module/kubernetes/util/kubernetes.go
Fixes https://github.com/elastic/beats/issues/35439
At https://github.com/elastic/beats/issues/35439, it has been reported that Metricbeat is facing a crucial memory leak that leads to multiple restarts each time Metricbeat Pod gets `OOMKilled`.
This is happening even in very basic clusters with even just the `kubernetes` module enabled with very few metricsets.
First we tried to relate it with https://github.com/elastic/beats/issues/33307 and https://github.com/elastic/elastic-agent-autodiscover/issues/31 however it didn't look to be the same since the related known "workaround"(`add_resource_metadata.deployment: false`) had no effect.
At the same time it was reported that adding the `add_metadata: false` was solving the issue but with the cost of losing all the k8s metadata for the …
=> Safely start k8s watchers to avoid memory leak

testing/environments/snapshot.yml
<Actions>
<action id="763cdbcbcf154c6e2e800287e022bde24c40f17ef207fabec30b18d0165aa42b">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 8.7.2-7653c06b

libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc, libbeat/outputs/logstash/docs/logstash.asciidoc, libbeat/outputs/redis/docs/redis.asciidoc
Clarify / fix some inaccuracies that had gotten into the `loadbalance` documentation, particularly:
- Beats will still send data to configured outputs as long as they can connect to _any_ of them, regardless of `loadbalance` settings
- The `ttl` setting is specific to the `logstash` output and shouldn't be referenced in documentation for the `elasticsearch` and `redis` outputs.
=> Update docs for loadbalance settings in Beats outputs

auditbeat/module/file_integrity/fileorigin_test.go
Instead of sharing the same file while handle is open across sub-tests, create a new temp file for each sub-test and close it after creating it.
I couldn't reproduce the flaky test case, but I figured it can't hurt to further isolate each sub-test with separate files. The tests are each modifying the file extended attributes (so maybe there is some race related to the filesystem extended attributes?).
Relates #33033
Flaky tests degrade developer experience.
- Relates #33033
=> auditbeat/module/file_integrity/fileorigin_test.go - Create file per sub-test

CHANGELOG.next.asciidoc, x-pack/metricbeat/module/aws/aws.go, x-pack/metricbeat/module/aws/utils.go
This PR adds a time-limit to each AWS API call that is used in `metricbeat`
Two main reasons:
* If we encounter a failure in any API we call, we should fail fast.
* Some non-blocking APIs (e.g `GetResourceTags`) might not work in specific environments (e.g private subnets) and may delay or block the data collection.
- Closes https://github.com/elastic/integrations/issues/6137
=> Add time-bounded contexts to AWS API calls

CHANGELOG.next.asciidoc, packetbeat/_meta/config/beat.reference.yml.tmpl, packetbeat/config/config.go, packetbeat/config/config_test.go, packetbeat/docs/packetbeat-options.asciidoc, packetbeat/packetbeat.reference.yml, packetbeat/sniffer/afpacket.go, packetbeat/sniffer/afpacket_linux.go, packetbeat/sniffer/afpacket_nonlinux.go, packetbeat/sniffer/sniffer.go, x-pack/packetbeat/packetbeat.reference.yml
To scale processing across multiple Packetbeat processes, a fanout group
identifier can be specified. When `fanout_group` is used the Linux kernel splits
packets across Packetbeat instances in the same group by using a flow hash. It
computes the flow hash modulo with the number of Packetbeat processes in order
to consistently route flows to the same Packetbeat instance.
The value must be between 0 and 65535. By default, no value is set.
This is only available on Linux and requires using `type: af_packet`. Each process
must be running in same network namespace. All processes must use the same
interface settings. You must take responsibility for running multiple instances of
Packetbeat.
Closes #35451
Gives advanced users a means of scaling packet capture across Packetbeat processes on …
=> [Packetbeat] Add support for af_packet fanout group

testing/environments/snapshot.yml
<Actions>
<action id="08397a79f4109acc088fd7057fde881cc5f744e3aecc89c76e612a6608cc95e7">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 8.7.2-581e1396

testing/environments/snapshot.yml
<Actions>
<action id="e6fcd9fddd5c4bdf039155eca03edf8ef2b11800280c62093992f37f682ddcfc">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 8.8.0-9e4f7a5d

testing/environments/snapshot.yml
<Actions>
<action id="5213870796bdb904cecfa5bf58c03e2071f6c84f7abd09ebe2fc3f55f24a068b">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 7.17.11-31efa078

CHANGELOG.next.asciidoc, winlogbeat/beater/eventlogger.go
Currently, if winlogbeat is attempting to open a channel that is not available because it is not found or there is a recoverable error, it will loop and retry. Since signals have been sent to notification handlers by this point, cancellation of the loop is not possible without agreement. So add a cancellation select at the head of the retry loop to allow termination.
The current behaviour requires heroic user intervention when attempting to bring down a running winlogbeat that has not been able to get its input channels.
-
=> winlogbeat: allow termination while attempting to open channels

CHANGELOG.next.asciidoc, packetbeat/sniffer/sniffer.go
- Ensures that the BPF filter setting is applied to sniffers
BPF filters were not being applied to pcap and af_packet sniffers and were processing packets that were supposed to be filtered out.
- Configure packetbeat to sniff an interface with either the `pcap` or `af_packet` (Linux only) type and configure a BPF filter. Turning on debug logging will either show packets being handled or the sniffer timing out. If you configured the BPF filter to handle traffic known to not exist, then you …
=> [Packetbeat] Fix BPF filter setting not being applied to sniffers

testing/environments/snapshot.yml
<Actions>
<action id="347b1e36e6fb7378034f26af73b63afdeae5ff0ae8c872ec057c1a16e409c782">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 8.8.0-49c28bdb

testing/environments/snapshot.yml
<Actions>
<action id="8a2e7fa0b475d58003d12792105070aadc74ffe2d5b1c01fca5e2910296e9715">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 8.7.2-99e4ac2a

testing/environments/snapshot.yml
<Actions>
<action id="caaef26a53fd3987ed1335c66c37f5ed9f7659881e8fe036951d74fed8d84ba3">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 7.17.11-53c77961

testing/environments/snapshot.yml
<Actions>
<action id="1d4f7dd0717805180ab54b89c006af9ffe2600655447ab3e66a7fdb6660d2431">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 8.7.2-738acb99

testing/environments/snapshot.yml
<Actions>
<action id="cc62f8f6dd94e48146e392aa9ea3a5da6878ba10dba9f558afb06c2575d9f64d">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 8.8.0-cc834a5d

testing/environments/snapshot.yml
<Actions>
<action id="7cf809e071276a23baa46ca7b5cfa6d981d54c8373cfaf36ab870dca92381e3d">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 7.17.11-874490f1

CHANGELOG.next.asciidoc, x-pack/winlogbeat/module/routing/ingest/routing.yml
Sets `host.os.type` and `host.os.family` in forwarded events.
These fields are used in detection rules.
- For elastic/integrations#6162
=> x-pack/winlogbeat/module/routing: set host.os.type and host.os.family in forwarded events

testing/environments/snapshot.yml
<Actions>
<action id="f62577cfe26a1daf85f055fd061bf6a7a9235cd7ef58758d7e10b26e5ac6153d">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 7.17.11-b843b253

testing/environments/snapshot.yml
<Actions>
<action id="fd4310c8401c2cffe403ae349116729116b8d8540be036ed885f720157310eea">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 7.17.11-0c2fb1a0

.github/dependabot.yml
This enables the GitHub dependabot which will open PRs to keep the `go.mod` file updated when new releases are made for the project's dependencies.
This configures it to watch the go.mod file and update it when an Elastic project is released (`github.com/elastic/*`). I wanted to keep the scope small to start with, but this `allow` filter can be removed or expanded in the future.
This will help to ensure the project stays updated with the latest changes and bugfixes from other elastic projects.
=> Enable dependabot for Go modules

.github/dependabot.yml, .github/workflows/post-dependabot.yml
In elastic/beats, any changes to dependencies contained in go.mod requires the change to be reflected in the NOTICE.txt file. When dependabot creates a branch for a go_modules change this will update the NOTICE.txt file for that change.
Relates #35525
It avoids having dependabot PRs immediately fail to pass CI checks because of an out-of-date NOTICE.txt file. This saves a developer from having to manually update dependabot PRs.
Another option here would be to not commit the NOTICE.txt file to the repo. The file only needs to be included in distributions of the product. So as long as we continue to verify that the file can be generated without error during CI checks then I think it could be replaced by a static version like elastic/elasticsearch's …
=> Add post-dependabot GH action to update NOTICE.txt

testing/environments/snapshot.yml
<Actions>
<action id="0f7dd176c0b9da6c37dcadca13d8ab739a3aa498363cabd5d92d78947a326293">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 8.7.2-3ff44d96

testing/environments/snapshot.yml
<Actions>
<action id="6414b47ca70801b02af321539c339226d3accc3dceba0f06c984cd9ff9b893cc">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 7.17.11-835d340b

.github/workflows/post-dependabot.yml
Fix invalid job name.
```
Invalid workflow file: .github/workflows/post-dependabot.yml#L13
The workflow is not valid. .github/workflows/post-dependabot.yml (Line: 13, Col: 3): The
identifier 'update-notice.txt' is invalid. IDs may only contain alphanumeric characters,
'_', and '-'. IDs must start with a letter or '_' and and must be less than 100 characters.
```
Relates: #35538
=> .github/workflows/post-dependabot.yml - Fix invalid job name

.github/workflows/post-dependabot.yml
Adding `permissions.contents: write` for this job because it needs to be able to write the updated NOTICE.txt to the affected branch.
Fixes "remote: Permission to elastic/beats.git denied to github-actions[bot]." ([link](https://github.com/elastic/beats/actions/runs/5060030033/jobs/9082385088?pr=35537#step:6:12))
Relates: #35538 
References:
- https://github.com/stefanzweifel/git-auto-commit-action#usage (says `contents: write` is required to push)
- https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/ (I assumed elastic/beats had default read-only tokens, but I have confirmed that the setting is on "Read and write permissions". So I'm less sure that this will fix the issue.)
=> .github/workflows/post-dependabot.yml - Allow write contents

x-pack/filebeat/input/awss3/metrics.go, x-pack/filebeat/input/awss3/s3.go, x-pack/filebeat/input/awss3/s3_objects.go, x-pack/filebeat/input/awss3/sqs.go, x-pack/filebeat/input/awss3/sqs_s3_event.go
A few internal (i.e. non-exported) constructors accept `nil *inputMetrics` arguments for when the caller is not concerned with the collection of metrics. Add a comment to clarify within the constructor that it builds a stub.
Relates #35354
Code clarity.
=> x-pack/filebeat/input/awss3 - Add clarifying comment on optional inputMetrics

CHANGELOG.next.asciidoc, packetbeat/beater/install_npcap.go, packetbeat/beater/install_npcap_test.go, packetbeat/npcap/npcap.go
Previously, the config option for blocking Npcap DLL installation on Windows under fleet was not properly handled due to differences in the shape of the configs by the time the decision is made for the action. This adds a tested helper to ensure that fleet configurations are properly handled.
Also add some logging at the beginning of the install process and a note when a previously installed Npcap is disabled.
The current behaviour does not respect user configurations.
Run `go test` in packetbeat/beater.
-
=> packetbeat: fix handling of npcap.never_install configuration options from fleet

dev-tools/mage/pytest.go, dev-tools/vagrant_scripts/winProvision.ps1
changes method used to upgrade pip for python test framework
Occasionally in CI we would see errors like:
```
[2023-05-05T17:59:04.678Z] ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'C:\\Users\\jenkins\\AppData\\Local\\Temp\\pip-uninstall-x4fgjn5h\\pip.exe'
[2023-05-05T17:59:04.679Z] Consider using the `--user` option or check the permissions.
[2023-05-05T17:59:04.679Z] 
[2023-05-05T17:59:14.319Z] warn: failed to upgrade pip (ignoring): running "null\build\ve\windows\Scripts\pip install -U pip" failed with exit code 1ERROR: Exception:
[2023-05-05T17:59:14.320Z] Traceback (most recent call last):
```
Windows can have permission issues with binaries that upgrade themselves.  This is the "officially recommended" way to update pip from …
=> retry pip upgrade

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 8.8.0

testing/environments/snapshot.yml
<Actions>
<action id="d4d490bdf54d169f7f8851904c5cb334aaa8c6e15686ed599dbac600471dc25e">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 8.8.0-b66548ac

.ci/packaging.groovy
In this proposal I use a new ephemeral worker for the whole run regarding the DRA (that only runs for main and release branches) **NOTE**: so it's not possible to test this section on a PR
https://github.com/elastic/beats/pull/35410  was an attempt to fix temporary the issue with ephemeral tokens but it seems there are some other issues when reusing the workspace, somehow it gets corrupted.
=> ci: retry DRA in a new CI runner

libbeat/processors/add_host_metadata/add_host_metadata_test.go
For `add_host_metadata` FQDN tests, this change resets the `FQDNLookupFailed` metric after every run.  Without this the order of the tests could cause the comparison of the metrics to fail.
Also changed to the RFC 6761 reserved name "example.com" for testing lookups.
Make `add_host_metadata` FQDN unit tests deterministic.
```bash
cd libbeat/processors/add_host_metadata
while go test -count 1 -run TestFQDN; do; done
```
- Closes #35528
=> make test fqdn lookup deterministic

filebeat/input/filestream/internal/input-logfile/harvester_test.go
In the TestDefaultHarvesterGroup unit test, added waiting for RunCount to be one before checking if added to bookkeeper, without this RunCount could be 0, so harvester wasn't stopped before check.
deterministic unit tests
```bash
cd filebeat/input/filestream/internal/input-logfile
while go test -v -count 1 -run TestDefaultHarvesterGroup/assert_a_harvester_can_be_stopped_and_removed_from_bookkeeper; do :; done …
```
=> make TestDefaultHarvesterGroup test deterministic

testing/environments/snapshot.yml
<Actions>
<action id="2cb60765813896ca539555d6c6d8df70dc00937b1a86339ae6bdcd454d8bb5a3">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 8.7.2-1098350b

testing/environments/snapshot.yml
<Actions>
<action id="418a535d200d7695f20b6322c28464c828ccb37b2db3fa6c6b7a56068fda7fdf">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 7.17.11-97b4b531

CHANGELOG.next.asciidoc
Remove extra entries from the changelog. I merged the backport PR https://github.com/elastic/beats/pull/35586 without fixing the changelog entries left over by the automatic cherry-picking, my bad.
We need to keep the changelog tidy with only the relevant entries.
=> Remove extra changelog entries

CHANGELOG.next.asciidoc, filebeat/module/system/auth/ingest/pipeline.yml, filebeat/module/system/auth/test/secure-rhel7.log-expected.json, filebeat/module/system/auth/test/test.log, filebeat/module/system/auth/test/test.log-expected.json
Syncs the Filebeat system/auth dataset with version 1.29.0 of the system integration.
- consistent parsing of auth events between Filebeat and Agent
- fixes bug where hostnames were incorrectly being copied to `source.ip`, which caused indexing errors because the hostname didn't satisfy the type requirements of `ip`.
```bash
cd filebeat
TESTING_FILEBEAT_MODULES=system TESTING_FILEBEAT_FILESETS=auth mage -v pythonIntegTest
```
- Relates elastic/integrations#6256
=> sync filebeat system auth dataset with system integration

libbeat/docs/shared-autodiscover.asciidoc
Manual backport of #34406 to 8.6
It was reported to the Docs team that the note added via #34406 to the [Kubernetes section](https://www.elastic.co/guide/en/beats/filebeat/8.7/configuration-autodiscover.html#_kubernetes) of the Autodiscover docs page references `8.6`, but the note appears only in `8.7` and later docs versions. So, this backports the change into the `8.6` branch. 
CC @jeanfabrice @MichaelKatsoulis
=> [Backport] [8.6] [34406] Clarify usage of kubernetes pod labels

testing/environments/snapshot.yml
<Actions>
<action id="b0bef16548d681381bbe60d9fe6fbcddbf3b20ae8ca3805e0c89d2d558fdc010">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 8.7.2-81170f47

testing/environments/snapshot.yml
<Actions>
<action id="95604b1f72aa8ae5bd806db2be8563d6dc45ad860c068e62e65357c28ceeca83">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 7.17.11-6ec6183f

testing/environments/snapshot.yml
<Actions>
<action id="b6dc936a179659f6c14c90499c6f322e724e85b732ee75e6091a712a70625cde">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 8.8.1-8b995292

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-cel.asciidoc, x-pack/filebeat/input/cel/config.go, x-pack/filebeat/input/cel/input.go, x-pack/filebeat/input/cel/input_test.go
This addition makes use of the mito XML library to allow users to decode XML responses with type hints.
Also clean up some CEL input documentation.
This is a blocker for an integration.
- For #34438
- Depends #35235 (this is the second in a chain).
=> x-pack/filebeat/input/cel: provide XML decoding functionality

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-cel.asciidoc, x-pack/filebeat/input/cel/input.go
Marks the CEL input as GA.
Milestone plan item.
- Depends #35372
=> x-pack/filebeat/input/cel: mark as GA

testing/environments/snapshot.yml
<Actions>
<action id="57ba69b0ad71256655f22079453c23d533cf40d66a61a896d2d788f57f7d03f8">
</details>
</action>
<action id="ca4359045d6b87a8d20b80c2b209bfcc652473a37f70123dff9934abd5cbe55c">
</details>
</action>
</Actions>
---
<ul>
<li>If …
=> [updatecli] update elastic stack version for testing 7.17.11-a516d267

CHANGELOG-developer.next.asciidoc, libbeat/monitoring/inputmon/input.go
This notes under "metric_registry" all inputmon-handled metric registration and deregistration, linking register and deregister operations by use of a unique ID unrelated to the request.
We have had a number of cases where metric registrations have been duplicated, this addition allows us to identify pairs of registration/deregistration and correlate with prior un-deregistered registrations with the same name. The logging at INFO level speeds recovery of the information with minimal additional log load.
-
=> libbeat/monitoring/inputmon: log key, id and input type when registering/deregistering metrics

CHANGELOG.next.asciidoc, libbeat/reader/parser/parser.go, libbeat/reader/parser/parser_test.go
It adds the `include_message` parser to `parser.NewConfig` validation logic.
This parser could not be used before, Filebeat would fail to start
1. Create a Filebeat configuration that uses the `include_message` parser:
```
paths:
- /tmp/test.log
parsers:
- include_message:
patterns: ["^A", "^B"]
```
2. Run Filebeat
3. It should start and only include messages matching the reg exps.
- Fixes #35440
~~## Logs~~
=> Add `include_message` to the parser config validation

.github/CODEOWNERS
We have found the Elastic Agent team is being required to review PRs exclusively because we are the maintainers of go.mod and related files. To avoid making us the bottleneck for these changes, we've created the [Beats Tech Leads](https://github.com/orgs/elastic/teams/beats-tech-leads) team so that we can share ownership of these files and unblock our own teams faster. 
The alternative is to mark these files as unowned, but since go.mod updates can be critical to product security I don't want to leave these files ownerless. I will also make this group the owner of the CODEOWNER file itself.
=> Make  Beats tech leads the owners of go.mod.

testing/environments/snapshot.yml
<Actions>
<action id="3b189080d072babfc33ac029b47d1509c0d51424ed6ba67d14ac4bc00c9b5b93">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 7.17.11-50dd0ed0

CHANGELOG-developer.next.asciidoc, x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/okta.go, x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/okta_test.go
This adds a new package for accessing the Okta user API.
It is necessary for adding the Okta entity analytics input.
Obtain an Okta dev account and set up an auth token, then you can run the tests in x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta with
```
OKTA_HOST=<oktadomain> OKTA_TOKEN=<token> go test -v -log_user_response
```
- For elastic/security-team#5100
=> x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta: new package

testing/environments/snapshot.yml
<Actions>
<action id="3f47ca2fd9ad26ad3b28c5ecbf171f534c81736135e533a71c580a3453bbaaee">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 8.9.0-f5346fd1

CHANGELOG.next.asciidoc, libbeat/publisher/processing/default.go, libbeat/publisher/processing/default_test.go
Closes #35635.
Related to #35031.
TL;DR: We are seeing segfaults when running `elastic-agent diagnostics` on heartbeat policies. Traced back to a nested `nil` access. AFAIK, there're other beats affected by the same problem.
- Add `nil` check to diagnostics processor serializer.
- Build agent locally.
- Enroll an agent in a synthetics policy.
- Run `elastic-agent diagnostics`.
-  Check no segfault error is reported and `.zip` contains parsed synthetic policies.
#
=> [Heartbeat] Add nil check to diagnostics processor serializer

metricbeat/module/postgresql/docker-compose.yml
Adds a healthcheck to the docker-compose.yml file used for metricbeat integration tests.
occasionally in CI we get errors like:
```
[2023-05-17T21:49:46.861Z] === FAIL: metricbeat/module/postgresql/activity TestFetch (27.09s)
[2023-05-17T21:49:46.861Z]     activity_integration_test.go:40: Expected 0 error, had 1. [error in QueryStats: failed to obtain a connection with the database: pq: the database system is starting up]
```
adding the healthcheck means that postgresql will be "ready" before the test continues.
~~- [ ] I have made corresponding change to the default configuration …
=> [metricbeat] add healthcheck to docker-compose for integ tests

testing/environments/snapshot.yml
<Actions>
<action id="ef451f504797a46979e5e9c96862ca73a83638d42bf4e0f20cd77b2cb49827fb">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 8.8.1-e731bb3f

testing/environments/snapshot.yml
<Actions>
<action id="1f14f29223e8e44f15aeb0fa5dafcf81268617434b38640a71f93fb764750ebb">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 7.17.11-ba9a7d5f

heartbeat/beater/heartbeat.go, heartbeat/tracer/tracer.go, heartbeat/tracer/tracer_test.go
This change modifies the internal trace to send a message on a run_once abort due to a broken ES connection.
It also improves testing and cleans up the code by using methods instead of freeform strings for consistency.
This also moves logging to the trace library itself to make calling cleaner, since all a caller would do is log anyway.
No changelog since this is not a user facing change.
=> [Heartbeat] Add abort to internal trace

CHANGELOG-developer.next.asciidoc, x-pack/filebeat/input/httpjson/input_test.go
This adds benchmarking for the HTTPJSON input as a prelude to a refactor and revision. It also refactors the structure of the testing code to separate the test table from the test function; this is partly to allow sharing of test cases between the tests and benchmarks, and partly for clarity.
Test names are altered to reduce stutter and make direct copy/paste of the name in terminal output from `go test` findable in the Go source.
This is needed to allow a comparison between HTTPJSON and the new CEL input (the original reason), to guard against perf regressions in an upcoming revision, and to allow us to direct performance improvement work based on evidence. The formatting changes in the test table are QoL.
Run `go test` in x-pack/filebeat/input/httpjson, optionally with `-bench .` and …
=> x-pack/filebeat/input/httpjson: add benchmarks

CHANGELOG-developer.next.asciidoc, CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc, x-pack/filebeat/input/awss3/config.go, x-pack/filebeat/input/awss3/config_test.go, x-pack/filebeat/input/awss3/input.go, x-pack/filebeat/input/awss3/input_test.go
Currently, the queue_url option is used to obtain the region name for the SQS receiver. This prevents pointing the input at other sources for testing, so add a region_name option to provide an alternative way to provide the region name for non-AWS endpoints.
To avoid confusion, log a warning if the user configures the region option in conjunction with amazonaws.com endpoints such that they disagree.
This is needed for supporting tests of inputs using s3.
- Closes #35496
=> x-pack/filebeat/input/awss3: relax queue_url constraints for non-standard endpoints

x-pack/libbeat/common/aws/credentials.go
Update a debug log message to use the right AWS credentials provider name.
Use the actual provider name to avoid confusion in logs readers.
=> [AWS] Fix provider name in debug log message

testing/environments/snapshot.yml
<Actions>
<action id="7d804aa18bf75fc0ea6cc638410332a617359b38436e171a293be53e57762940">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 8.8.1-d9afcd4f

.github/CODEOWNERS, .github/dependabot.yml
Segment the dependabot config based on the responsible GitHub team in order to make it more clear who is responsible for approving the change.
The idea is that the repsonsible team is in the best position to know if the dependency should be updated, whether it should be backported, and what should be listed in the changelog.
=> dependabot - Segment by responsible team

dev-tools/mage/settings.go, libbeat/docs/version.asciidoc
Fixes the docs for the `main` branch
Because the links on elastic.co are broken:
>doesn't work: https://www.elastic.co/guide/en/beats/metricbeat/main/metricbeat-module-consul.html
>works:        https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-module-consul.html
N/A
N/A
=> Add doc-site-branch to version.asciidoc

CHANGELOG.next.asciidoc, x-pack/filebeat/input/gcs/scheduler.go
- Bug
A small code error got introduced with the PR: https://github.com/elastic/beats/pull/35605, it went unnoticed in the PR reviews because how small and similar that change was. It's not an error as such but can cause logical issues because of how the config is parsed. This has been fixed in the back-ports of the previous pr manually.
The max worker count being used from the config directly creates a scenario where it only used the global config values
and not the bucket level config values stored in the source object.
-
=> [filebeat][gcs] - Fixed the source of max workers in scheduler

testing/environments/snapshot.yml
<Actions>
<action id="ecd028ff97cd363433d5a1039a666b400daf776b0eddfcd6a82e2c803bf15b54">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 8.8.2-3ed30946

testing/environments/snapshot.yml
<Actions>
<action id="05f6c78db412053552984afe136dfa974d42d936c3e79b03abfcfede9a3b6a72">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 7.17.11-777002b0

CHANGELOG.next.asciidoc, x-pack/winlogbeat/module/sysmon/ingest/sysmon.yml, x-pack/winlogbeat/module/sysmon/test/testdata/collection/sysmon-no-evtx.evtx.golden.json, x-pack/winlogbeat/module/sysmon/test/testdata/ingest/sysmon-10.2-dns.golden.json, x-pack/winlogbeat/module/sysmon/test/testdata/ingest/sysmon-11-filedelete.golden.json, x-pack/winlogbeat/module/sysmon/test/testdata/ingest/sysmon-11-filedeletedetected.golden.json, x-pack/winlogbeat/module/sysmon/test/testdata/ingest/sysmon-11-registry.golden.json, x-pack/winlogbeat/module/sysmon/test/testdata/ingest/sysmon-12-loadimage.golden.json, x-pack/winlogbeat/module/sysmon/test/testdata/ingest/sysmon-12-processcreate.golden.json, x-pack/winlogbeat/module/sysmon/test/testdata/ingest/sysmon-13-clipboardchange.golden.json, x-pack/winlogbeat/module/sysmon/test/testdata/ingest/sysmon-13-processtampering.golden.json, x-pack/winlogbeat/module/sysmon/test/testdata/ingest/sysmon-9.01.golden.json, x-pack/winlogbeat/module/sysmon/test/testdata/ingest/sysmon-no-evtx.golden.json, x-pack/winlogbeat/module/testing.go
Makes the sysmon pipeline handle DNS records with blank data, for example `<Data Name='QueryResults'>type:  33 ;type:  33 ;<some ip v6>;<some ip v4>;</Data>`.
I encountered such data - I am not sure how it was produced, it might have been an issue with the network configuration. Nonetheless, I did not want to drop the records, so I edited the pipeline a bit, and figured this might be useful to others. If you don't want this, it's also fine.
=> Handle empty sysmon DNS answer data

CHANGELOG.next.asciidoc, x-pack/filebeat/tests/integration/framework_test.go, x-pack/filebeat/tests/integration/managerV2_test.go, x-pack/libbeat/management/managerV2.go, x-pack/libbeat/management/managerV2_test.go
It fixes the status reporting when the output fails to start under Elastic-Agent and also prevents some deadlock conditions on inputs that will block its initialisation when the output is not ready.
- Fixes https://github.com/elastic/elastic-agent/issues/2554
- https://github.com/elastic/elastic-agent/issues/2554
~~## Logs~~
=> Set the unit unhealthy if output fails to start

testing/environments/snapshot.yml
<Actions>
<action id="981383719e4a3441d0ffdbe6df0ac9bae4004b050fd1ed118653546d0b0cbdd7">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
=> [updatecli] update elastic stack version for testing 7.17.11-e46e5ca7

heartbeat/scheduler/scheduler_test.go
Closes #35464.
Closes #35627.
Fixes race condition on scheduler unit tests.
=> [Heartbeat] Fix race condition in scheduler tests

.buildkite/pipeline.yml, .buildkite/pull-requests.json, catalog-info.yaml
This PR onboards this repository into Buildkite and creates the skeleton for the main pipeline.
-
=> Onboard repository in Buildkite

CHANGELOG.next.asciidoc, x-pack/filebeat/input/gcppubsub/input.go
The current code registers metrics and defers closing them in the input constructor meaning that the metrics are not registered by the time the input is running. Delay registering the metrics until the input is started and close the metrics when the input is stopped.
Currently the metrics are not registered during operation.
-
=> x-pack/filebeat/input/gcppubsub: make metric collection persist beyond construction

CHANGELOG.next.asciidoc, libbeat/publisher/queue/diskqueue/config.go
In disk queue configuration, it seems like the `MaxRetryInterval` is read from the wrong field, which leads to a panic when `RetryInterval` is not provided.
Also, `MaxRetryInterval` doesn't seem configurable at all as it is. 
So `MaxRetryInterval` can be configured
- ~~I have made corresponding changes to the documentation~~
```
{"panic": "runtime error: invalid memory address or nil pointer dereference", "stack": "github.com/elastic/beats/v7/libbeat/cmd/instance.Run.func1.1\n\t/go/src/github.com/elastic/beats/libbeat/cmd/instance/beat.go:170\nruntime.gopanic\n\t/us …
```
=> Fix panic when MaxRetryInterval is specified, but RetryInterval is not

x-pack/metricbeat/module/activemq/test_activemq.py
Skip the activemq test suite until we can determine why the tests are failing. 
- Relates https://github.com/elastic/beats/issues/35851
=> Disable failing activemq tests

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-entity-analytics.asciidoc, x-pack/filebeat/input/entityanalytics/provider/azuread/azure.go, x-pack/filebeat/input/entityanalytics/provider/azuread/azure_test.go, x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/device.go, x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/device_test.go, x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/fetcher.go, x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/graph/graph.go, x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/graph/graph_test.go, x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/group.go, x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/mock/mock.go, x-pack/filebeat/input/entityanalytics/provider/azuread/statestore.go, x-pack/filebeat/input/entityanalytics/provider/azuread/statestore_test.go
Adds device support to the Azure AD entity analytics input provider.
Milestone task needed for security solution.
-
=> x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher: add device handling

metricbeat/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
This updates the test environments to next minor release which is 8.10.0.
=> [Release] Update test environment to 8.10.0

dev-tools/Jenkinsfile.yml, generator/Jenkinsfile.yml, x-pack/elastic-agent/Jenkinsfile.yml
The 7.17 build is failing, seemingly related to the backport of https://github.com/elastic/beats/pull/34355. It turns out there are three additional references to the old version `ubuntu-18` that are not present in the 8.x branches, and thus weren't updated. This PR fixes them.
=> Update references to ubuntu-18 in 7.x

auditbeat/Jenkinsfile.yml, filebeat/Jenkinsfile.yml, heartbeat/Jenkinsfile.yml, libbeat/Jenkinsfile.yml, metricbeat/Jenkinsfile.yml, packetbeat/Jenkinsfile.yml, x-pack/auditbeat/Jenkinsfile.yml, x-pack/dockerlogbeat/Jenkinsfile.yml, x-pack/elastic-agent/Jenkinsfile.yml, x-pack/filebeat/Jenkinsfile.yml, x-pack/functionbeat/Jenkinsfile.yml, x-pack/heartbeat/Jenkinsfile.yml, x-pack/libbeat/Jenkinsfile.yml, x-pack/metricbeat/Jenkinsfile.yml, x-pack/packetbeat/Jenkinsfile.yml
Manual backport of https://github.com/elastic/beats/pull/34383 to 7.17 to fix the 7.17 ARM packaging stages.
=> Update renaming arm labels

filebeat/docs/inputs/input-journald.asciidoc, filebeat/input/journald/input_filtering_test.go
The cursor_seek_fallback option was missing from the documentation. And there was no test associated with the seek mode so I added it.
Through the test I discovered that the documented behavior of the tail seek mode was wrong so I corrected the docs.
The documentation should be complete and accurate.
=> filebeat/inputs/journald - Document cursor_seek_fallback, add seek test

testing/environments/snapshot.yml
<Actions>
<action id="d3d2e472bef8de6d1566db556230db4a0d11165f78aafbd8cc8d41e1ba75597f">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.8.2-c7e9ae2e

CHANGELOG.next.asciidoc, x-pack/filebeat/input/http_endpoint/input.go, x-pack/filebeat/input/http_endpoint/input_test.go
Previously the server address registry was not updated when the server was cancelled, leaving invalid state in the registry and preventing reconfiguration of servers. Ensure that the server address entry is deleted from the pool when the server is cancelled.
Current bugged state prevents server reconfiguration.
- Fixes #35899
=> x-pack/filebeat/input/http_endpoint: make sure address is removed on server closure

dev-tools/kubernetes/filebeat/Dockerfile.debug, dev-tools/kubernetes/heartbeat/Dockerfile.debug, dev-tools/kubernetes/metricbeat/Dockerfile.debug, metricbeat/module/http/_meta/Dockerfile, metricbeat/module/nats/_meta/Dockerfile, metricbeat/module/vsphere/_meta/Dockerfile, x-pack/metricbeat/module/stan/_meta/Dockerfile
We have update CLI that takes care of Docker image updates. In order to cover all the images we need to make them consistent first.
If we keep these images at older versions, we'll be constantly receiving CVE notifications, so it's easier to automate these updates even though these images are internal and are never released to the public.
It's a preparation step for another PR that will come later and will update the update CLI configuration to include all these paths.
I ran `docker build --no-cache .` on each changed Dockerfile.
=> Make all docker images consistent for future updates

.golangci.yml
Adding the `prealloc` linter rule:
https://github.com/alexkohler/prealloc
This will help us identify possible performance optimizations
=> Adding prealloc linter rule

.ci/packaging.groovy
Enable DRA publish for `7.17`
⚠️ Should be merged after https://github.com/elastic/infra/pull/39300
=> Enable `7.x` DRA builds

.ci/bump-golang.yml
So, we can avoid vulnerability reports from Snyk for the outdated images.
Quite a few issues reported by Snyk have to do with the Docker images that we have for testing and development, so we should include them into updates to avoid extra reports from Snyk.
It's a follow up to https://github.com/elastic/beats/pull/35919
=> Include all Dockerfiles that use Golang into the bump job

.ci/bump-golang-7.17.yml, .github/workflows/bump-golang.yml
Due to some differences between main and 7.17 we need this second job to account for it and have better automation.
=> Add separate Golan Bump job for 7.17

CHANGELOG.next.asciidoc, x-pack/filebeat/input/cel/input.go
This replaces the conversion to a structpb.Struct-serialisation-deserialisation path that was being used to a direct conversion to a structpb.Struct type which can then be used to obtain a map[string]any directly.
Using the test suite as a set of benchmarks shows good performance improvements almost across the board, with almost no regression. See elastic/beats#35139 for details of the benchmarks. Note that the benchmark results shown here are at that commit or that commit plus the change here. No substantive change has been made to the package to invalidate the comparison.
```
goos: darwin
goarch: amd64
pkg: github.com/elastic/beats/v7/x-pack/filebeat/input/cel cpu: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
│   cel.bench   │             cel-new.bench             │
│    sec/op     │ …
```
=> x-pack/filebeat/input/cel: use structpb.Struct as intermediate type

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 8.8.2

NOTICE.txt, go.mod, go.sum
Pre 1.29.1 versions of protobuf package are vulnerable to Out-of-bounds Read such that parsing a text-format message which contains a potential number consisting of a minus sign, one or more characters of whitespace, and no further input will cause a panic.
=> Updated protobuf to 1.29.1

metricbeat/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
Merge only after the release of 8.8.2.
=> [Release] Update test environments for 8.8.3

metricbeat/docker-compose.yml, metricbeat/module/logstash/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
Merge only after the release of 7.17.11.
=> [Release] Update test environments for 7.17.12

libbeat/docs/output-cloud.asciidoc
Remove a NOTE section telling the `cloud.id` does not explicitly specify a port because it does specify a port nowadays.
This PR fixes a small doc glitch that the NOTE section to be removed is no longer valid.
The doc should stay as accurate as possbile.
https://github.com/elastic/apm-server/pull/11100
=> Remove NOTE about port in Cloud ID

CHANGELOG.next.asciidoc, filebeat/input/filestream/internal/input-logfile/input.go, filebeat/input/filestream/internal/input-logfile/manager.go
- If a duplicate ID was used for filestream, set the ID for metrics to an empty string to prevent a panic.
- A valid metrics instance will still be generated, but collection of metrics will not occur.
Fixes a panic that can occur when a duplicate ID is used.
Create a config with duplicate IDs, such as:
```yaml
filebeat:
inputs:
id: foo
paths:
- /tmp/foo
id: foo
paths:
- /tmp/foo2
output:
file:
enabled: true
```
Run filebeat. The first instance should …
=> [filebeat] Check for duplicate ID for filestream metrics

x-pack/elastic-agent/pkg/agent/application/upgrade/step_download.go, x-pack/elastic-agent/pkg/agent/application/upgrade/step_download_test.go
Backport of https://github.com/elastic/elastic-agent/pull/2980
This PRs adds a fallback to a downloader. When downloadArtifact is called, it appends a fallback key into a passed keys collection.
This key is used as a last resort for signature verification of downloaded packages and is useful when embedded key is no longer used. 
This option is used regardless of mode in which ugprade was triggered let it be standalone CLI trigger or managed action. 
Option to support older agents when keys are rotated.
- temper embedded key
- build agent locally
- install built agent (managed)
- try to upgrade 
- should pass (first verification with embedded key fails, fallback should be fine)
=> Added verification fallback to https://artifacts.elastic.co/GPG-KEY-elastic-agent

filebeat/docs/inputs/input-common-udp-options.asciidoc
This PR includes default values for the Filebeat [UDP input](https://www.elastic.co/guide/en/beats/filebeat/8.8/filebeat-input-udp.html?edit=true). It includes the `timeout` default, which is specified in the [code](https://github.com/elastic/beats/blob/8597ca78aba6742961d4e235a565d87b7d21fc67/filebeat/input/udp/input.go#L74) but not in the docs. It also includes an explanation for the `read_buffer`, which will be provided by the OS.
Docs should contain this to assure users without the need to look at the code.
~~- [ ] I have added tests that prove my fix is effective or …
=> [doc] Add defaults for filebeat udp input.

CHANGELOG.next.asciidoc, x-pack/libbeat/management/managerV2.go
Closes https://github.com/elastic/beats/issues/36005
A simple one-liner fix that checks to see if we have a context-canceled error before printing an error message. Done to prevent log spam that happens during restart/shutdown operations:
```
elastic-agent-client error: rpc error: code = Canceled desc = context canceled
```
Removes a source a log spam.
=> Do not print context canceled errors

CHANGELOG.next.asciidoc, filebeat/input/tcp/input.go, filebeat/input/udp/input.go
Use correct address list in udp input metric collection.
Also add a check in the common path to check that the addr slice is the same length as the undefined addr slice, returning an error on mismatch rather than allowing the panic.
Prevents a panic.
-
=> filebeat/input/{tcp,udp}: use correct address list in udp

.ci/scripts/kind-setup.sh, Jenkinsfile, deploy/kubernetes/Jenkinsfile.yml, metricbeat/docs/modules/kubernetes.asciidoc, metricbeat/module/kubernetes/_meta/docs.asciidoc, metricbeat/module/kubernetes/test/integration.go
Possible fix for https://github.com/elastic/beats/issues/35901.
Partially backported from https://github.com/elastic/beats/pull/29575.
=> Fix k8s test versions

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-cel.asciidoc, x-pack/filebeat/input/cel/config.go, x-pack/filebeat/input/cel/config_test.go, x-pack/filebeat/input/cel/input_test.go
This detects when a user has not configured the redact options in the CEL input for filebeat and logs it as missing with a link to the documentation.
Ideally this would be a hard requirement, but that would be a breaking change, so just log at WARN if the configuration is missing.
By design the CEL input can log the entire input state and its evaluation during debug logging. This may leak secrets, so we provide an option to allow users to specify fields that are sensitive to be redacted or deleted. If the user is not aware of this behaviour or the option to redact they may put themselves at risk. The change here it designed to help them identify this risk.
Backported to 8.9 despite being an enhancement because of risk.
-
=> x-pack/filebeat/input/cel: make redact configuration recommended

metricbeat/internal/sysinit/init.go
Something small I recently noticed. The `cfgwarn.Deprecate()` message for `--system.hostfs` is still there, despite the config flag still existing. It was tagged as 8.0.0, which has long since been released, so...I figured it makes the most sense to just remove the message. If anyone has any other ideas for how this should be handled, please tell me.
This is a `Deprecate` message for something that was never depreciated, which is a bit odd.
=> Remove deprecate message for flag that wasn't deprecated

filebeat/input/filestream/fswatch.go, filebeat/input/filestream/fswatch_test.go
By using a buffer of the fingerprint's size. This descreases the amount of syscalls for reading the file.
Also added the benchmark for tracking the function's performance.
```
BenchmarkToFileDescriptor
BenchmarkToFileDescriptor-10               49345             23316 ns/op
BenchmarkToFileDescriptor-10               49766             23090 ns/op
BenchmarkToFileDescriptor-10               50439             22641 ns/op
BenchmarkToFileDescriptor-10               53368             22672 ns/op
BenchmarkToFileDescriptor-10               51948             22865 ns/op
```
```
BenchmarkToFileDescriptor
BenchmarkToFileDescriptor-10               68728             15549 ns/op
BenchmarkToFileDescriptor-10               75000             15558 ns/op
BenchmarkToFileDescriptor-10               73772 …
```
=> Make fingerprinting faster

CHANGELOG.next.asciidoc, filebeat/input/filestream/fswatch_test.go, filebeat/input/filestream/identifier.go, filebeat/input/filestream/identifier_fingerprint.go, filebeat/input/filestream/identifier_inode_deviceid.go, filebeat/input/filestream/input.go, filebeat/input/filestream/prospector_test.go, libbeat/reader/readfile/fs_metafields_other.go, libbeat/reader/readfile/fs_metafields_windows.go, libbeat/reader/readfile/metafields.go, libbeat/reader/readfile/metafields_other_test.go, libbeat/reader/readfile/metafields_test.go, libbeat/reader/readfile/metafields_windows_test.go
This includes:
* Unix-like:
* device
* inode
* Windows:
* idxlo
* idxhi
* vol
* All:
* Fingerprint (if the fingerprint mode is enabled)
This was requested by some customers and it makes it easier for us to troubleshoot.
1. Run Filebeat with the following configuration:
```yaml
id: my-filestream-id
enabled: true
paths:
- "/path/to/your/logs/*.log"
prospector.scanner.check_interval: 5s
prospector.scanner.fingerprint.enabled: true
path.data: "/path/to/your/data"
logging:
level: debug
output.console:
enabled: true
```
Note that you need to replace the path placeholders.
2. Create a file suitable for ingestion in your …
=> Add file system information to each event

filebeat/input/filestream/fswatch_test.go
So, we can compare how much slower the fingerprinting mode against using `device` and `inode` in the scanner.
Our customers would want to know the performance impact.
Git HEAD at a755bbc632
Average ~33194198,2 ns/op
```
BenchmarkGetFiles
BenchmarkGetFiles-10    	      31	  33275968 ns/op
BenchmarkGetFiles-10    	      31	  32648550 ns/op
BenchmarkGetFiles-10    	      31	  32753038 ns/op
BenchmarkGetFiles-10    	      30	  33802444 ns/op
BenchmarkGetFiles-10    	      34	  33490991 ns/op
```
Git HEAD at 061cb88e68e29f5869bb2571c490c5c507ee6958
Average ~5398583 ns/op
```
BenchmarkGetFiles
BenchmarkGetFiles-10                   	     206	   5424156 ns/op
BenchmarkGetFiles-10                   	     210	   5317834 ns/op
BenchmarkGetFiles-10                   	     210	   5396120 ns/op …
```
=> Add benchmarks for scanning files

CHANGELOG-developer.next.asciidoc, libbeat/tests/system/requirements.txt, libbeat/tests/system/requirements_aix.txt, metricbeat/Dockerfile, metricbeat/module/kubernetes/_meta/terraform/eks/requirements.txt
CPython 3.0 was released recently which has introduced a regression that leads to failures when installing PyYAML (and perhaps other packages too). This is a temporary fix and this commits needs to be reverted when a proper fix is available.
If we don't fix it CI would keep failing.
- https://github.com/yaml/pyyaml/issues/601
- https://github.com/yaml/pyyaml/pull/702
- https://github.com/cds-snc/notification-utils/pull/227#issue-1808380492
=> Pin PyYAML version to 5.3.1 to avoid CI errors temporarily

CHANGELOG.next.asciidoc, x-pack/filebeat/input/awss3/input.go, x-pack/filebeat/input/awss3/input_test.go
The code currently prioritises the region configuration, even when it is not provided, [against the claims of the documentation](https://www.elastic.co/guide/en/beats/filebeat/8.9/filebeat-input-aws-s3.html#_region). Make a check whether it is empty before claiming a conflict and using it.
The behaviour disagrees with the documentation.
-
=> x-pack/filebeat/input/awss3: fix priority of region name configurations

metricbeat/docs/running-on-docker.asciidoc
This adds a few lines to the `Monitor the host machine` documentation section in beats in order to document the steps needed to get the `system/users` and `system/service` metricsets to work inside a container. In particular, this requires an extra bindmount, and setting an environment variable.
Note that I'm having trouble actually testing this, as `make doc` just fails with a permissions error:
```
INFO:build_docs:mkdir /out/metricbeat: Permission denied at /usr/share/perl5/Path/Class/Dir.pm line 154.
Error: running "/home/alexk/go/src/github.com/elastic/beats/build/elastic_docs_repo/build_docs --asciidoctor --respect_edit_url_overrides --chunk=1 --doc /home/alexk/go/src/github.com/elastic/beats/metricbeat/docs/index.asciidoc --out …
```
=> Update docker documentation example for dbus in system metrics

libbeat/processors/add_cloud_metadata/provider_aws_ec2_test.go
This PR is to set `providers` parameter in config to `aws` for `provider_aws_ec2_test.go`. This will make sure `add_cloud_meta` collects metadata from the right provider. This is also the workaround for this processor when seeing wrong cloud provider information is detected.
For example, we are seeing `gcp` related metadata is collected when running `provider_aws_ec2_test.go` is run:
```
=== RUN   TestRetrieveAWSMetadataEC2/only_cloud.provider_pre-informed,_no_overwrite
{"log.level":"debug","@timestamp":"2023-06-08T18:07:59.591Z","log.logger":"add_cloud_metadata","log.origin":{"file.name":"add_cloud_metadata/providers.go","file.line":130},"message":"add_cloud_metadata: starting to fetch metadata, timeout=3s","ecs.version":"1.6.0"} …
```
=> Set providers parameter in config to aws for provider_aws_ec2_test.go

CHANGELOG.next.asciidoc, x-pack/filebeat/processors/decode_cef/cef/cef_test.go, x-pack/filebeat/processors/decode_cef/cef/keys.go
Relax the width of in and out fields from integer to long to allow values greater beyond 2GiB.
2GiB is unreasonably small.
- Closes #36100
=> x-pack/filebeat/processors/decode_def/cef: relax size constraint on network bytes

CHANGELOG.next.asciidoc, dev-tools/mage/build.go
There are `beats` that aren't part of the `beats` repository code-base.
`Cloudbeat` for example:
- https://github.com/elastic/cloudbeat
When calling the `mage package` that is based on the `beats` `mage` flows we are getting a failure:
```bash
Found Elastic Beats dir at /go/pkg/mod/github.com/elastic/beats/v7@v7.0.0-alpha2.0.20230718065235-46adbacfb5a8
exec: git "config" "--global" "--add" "safe.directory" "/go/pkg/mod/github.com/elastic/beats/v7@v7.0.0-alpha2.0.20230718065235-46adbacfb5a8"
>> build: Building cloudbeat-linux-amd64
exec: git "rev-parse" "HEAD"
fatal: detected dubious ownership in repository at '/go/src/github.com/elastic/cloudbeat'
To add an exception for this directory, call:
git config --global --add safe.directory /go/src/github.com/elastic/cloudbeat
>>> Fixing file …
```
=> Support build of projects outside of beats directory

CHANGELOG-developer.next.asciidoc, CHANGELOG.next.asciidoc, libbeat/reader/parser/parser_test.go, libbeat/reader/readjson/json.go
Stores the JSON fields in a nested way if the `target` of the ndjson parser contains a dotted key, e.g.
the following config:
```
parsers:
- ndjson:
add_error_key: true
target: kubernetes.audit
```
leads to this result:
```
"kubernetes": {
"audit": {
"userAgent": ...,
```
instead of this:
```
"kubernetes.audit": {
"userAgent": ...
...
}
```
Fixes unexpected behavior. 
Tested with a unit test.
- Closes #29395
=> Fix ndjson parser to store JSON fields correctly under `target`

CHANGELOG.next.asciidoc, x-pack/filebeat/input/cel/input.go, x-pack/filebeat/input/cel/input_test.go
Previously `now` was static for the life of the program, which corresponded to the life of the input. This could lead to incorrect and surprising times being provided when the global was used. Obtain a `now` value before starting each evaluation and use it to shadow the CEL `now` global (and share it with the Go logging to allow correlation between these).
`now` gave a potentially invalid time.
-
=> x-pack/filebeat/input/cel: make now global static per evaluation

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-entity-analytics.asciidoc, x-pack/filebeat/input/entityanalytics/provider/azuread/azure.go, x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/device.go, x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/device_test.go, x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/graph/graph.go, x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/graph/graph_test.go
Add support for including registered owner and registered user data to device documents.
Part of the entity analytics roadmap.
-
=> x-pack/filebeat/input/entityanalytics/provider/azuread: add registered owner/user handling

metricbeat/docker-compose.yml, metricbeat/module/logstash/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
Merge only after the release of 7.17.12.
=> [Release] Update test environments for 7.17.13

.github/CODEOWNERS
This PR adds CODEOWNER for the salesforce module.
Current code owner after update for salesforce is `obs-infraobs-integrations`
- https://github.com/elastic/beats/pull/35938
=> [Filebeat][Salesforce] Add CODEOWNER for salesforce as obs-infraobs-integrations

.github/PULL_REQUEST_TEMPLATE.md
Add a new item in the checklist about commit title and message that should be explanatory.
Ensure that we pay attention to our commit message and title.
-
=> Update PULL_REQUEST_TEMPLATE.md - Update checklist

.github/dependabot.yml, CHANGELOG-developer.next.asciidoc
See title.
Autoupdates fail to bring required docs updates.
-
=> dependabot: skip github.com/elastic/mito auto updates

CHANGELOG.next.asciidoc, x-pack/winlogbeat/module/powershell/ingest/powershell.yml, x-pack/winlogbeat/module/powershell/ingest/powershell_operational.yml
The details regexp pattern for the powershell data stream was improved in the windows integration in elastic/integrations#6154 to reduce backtracking costs that caused regexp costs to exceed the set runtime limits. The same pattern on other data streams and in winlogbeat was not updated. This change brings winlogbeat up to date with the change.
- For elastic/integrations#7174
=> x-pack/winlogbeat/module/powershell: improve details regexp pattern performance

CHANGELOG.next.asciidoc, packetbeat/_meta/config/windows_npcap.yml.tmpl, packetbeat/beater/install_npcap.go, packetbeat/beater/install_npcap_test.go, packetbeat/beater/packetbeat.go, packetbeat/beater/processor.go, packetbeat/docs/packetbeat-options.asciidoc
Defer installation until we have a valid config with streams configured so that we can determine whether the user has blocked install and whether we need the DLL.
In the fleet-managed case New is called without a complete config, which means that we have no stream to tell us not to install the Npcap DLL.
-
=> packetbeat/beater: make Npcap installation lazy

metricbeat/module/postgresql/docker-compose.yml, metricbeat/module/postgresql/statement/statement_integration_test.go
Improve healthcheck for Postgres to reduce the flakiness in integration tests.
Flaky tests lead to instability of CI and could lead to unnecessary blocking of PRs and unreliable tests. In my opinion, `start_period` and reason mentioned in https://github.com/peter-evans/docker-compose-healthcheck/issues/16#issuecomment-1420377736 is something that could help us as this improves healthcheck.
Also bumped the fallback version for the image to the latest minor of the same major release to avoid any issues. Currently, my latest major is 15 and currently, I've set the fallback version to 13.11 so that it doesn't change the major.
As the flaky tests are not reproducible, we'll do a soak testing i.e., soak it for some time to see if it really reduced the flakiness of integration tests or not.
- …
=> metricbeat/module/postgresql: Improve healthcheck for Postgres

filebeat/docs/modules.asciidoc
Adds a note to [Modules](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-modules.html) to advise users to migrate to Elastic Agent.
Preview: [Modules](https://beats_36157.docs-preview.app.elstc.co/guide/en/beats/filebeat/master/filebeat-modules.html)
While Filebeat modules are still supported, we do not typically apply bug fixes or enhancements to these modules, or ship any new modules. Our focus is now entirely on Elastic Agent integrations.
~~- [ ] I have commented my code, particularly in hard-to-understand areas~~ N/A
~~- [ ] I have made corresponding change to the default configuration files~~ N/A
~~- [ ] I have added tests that prove my fix is effective or that my feature works~~ N/A …
=> [DOCS] Advise users to migrate from Filebeat to Elastic Agent

.github/workflows/bump-golang.yml
Add on.[workflow_dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) to allow manually triggering the golang version bump action, in addition to running it on a fixed schedule.
=> Allow manually triggering the golang bump

.github/PULL_REQUEST_TEMPLATE.md
To improve the quality of commit messages in the revision history, indicate that the commit message will be part of the PR review process and integrate the WHAT and WHY questions in the change explanation.
Remove the checklist item for PR title and description as it becomes redundant with this new text.
Included in the text above.
-
=> github: unify PR description and commit message

CHANGELOG.next.asciidoc, libbeat/cfgfile/list.go, libbeat/common/reload/reload.go, x-pack/libbeat/management/input_reload_test.go, x-pack/libbeat/management/managerV2.go, x-pack/libbeat/management/managerV2_test.go
This PR updates the ManagerV2 to set status per Unit based on its inputs. If any input on a Unit returns an error when starting the whole Unit is set as failed. If multiple inputs return an error, all errors are reported in the `Message` field.
If the output unit returns an error when starting, only the output Unit is set as failed. All other input unit states are not modified (this was the behaviour before this PR).
It allow users to better understand which unit has failed and which ones are working.
1. Build a development version of the Elastic-Agent
2. Build Filebeat from this PR (from the `x-pack` folder)
3. Replace …
=> Report status per unit

libbeat/docs/release.asciidoc
We forgot to modify `libbeat/docs/release.asciidoc` we added changelog on the 8.8 branch.
The changelog content was already present.
- Relates https://github.com/elastic/beats/issues/35580
=> Changelog: adding 8.7.0 and 8.7.1 to release-notes.html

CHANGELOG.next.asciidoc, dev-tools/packaging/files/linux/systemd-daemon-reload.sh, dev-tools/packaging/packages.yml, dev-tools/packaging/templates/deb/postinstall.sh.tmpl
This commit restarts the Beat after the deb package is installed. When upgrading a Beat via deb packages this is required for the new version to start running.
The post install script checks whether the Beat is running, if so, then it restarts the service.
- Closes https://github.com/elastic/beats/issues/34089
1. Get a Debian box (like the `debian10` vagrant VM on this repo)
2. Download and install any deb package from Filebeat < 8.10.0
3. Get a Stack deployment …
=> Restart Beat after install on deb package

CHANGELOG.next.asciidoc, dev-tools/packaging/templates/docker/Dockerfile.tmpl
Fizes https://github.com/elastic/beats/issues/36117. Add default TZ value to fix synthetic journeys for timezone-triggered errors.
Unspecified timezone values can cause navigation errors on synthetics journeys.
1. Build heartbeat docker image locally.
2. Create a journey that navigates to a Kibana URL.
3. Wait for Kibana login page to load properly.
=> [Heartbeat] Add default TZ to heartbeat docker images

.ci/bump-golang-7.17.yml, .ci/bump-golang.yml
Use the [dockerfile resource type](https://www.updatecli.io/docs/plugins/resource/dockerfile/) to ensure we can parse and update Dockerfiles that use multistage builds.
We need to handle FROM golang:x.x.x AS yyyyy in addition to the simple FROM golang:x.x.x case.
The dockerfile resource type unfortunately doesn't support of list of files so there is now significantly more duplication, but it works and will keep working.
I used this configuration to create https://github.com/elastic/beats/pull/36233 by manually running updatecli with my changes.
=> Fix bump-golang job failing to update Dockerfiles.

.ci/bump-golang-7.17.yml
Need to quote 7.17 so it is interpreted as a string and not a float.
=> Fix the 7.17 Go version bump script.

libbeat/tests/integration/framework.go, libbeat/tests/integration/template_test.go
fixes flaky TestTemplateDefault and TestTemplateDisabled integration tests
- tests assumed 1 event published, could be multiple
- added LogMatch function to framework to allow use of regexp
- added some more debug info when tests fail, useful in CI where we don't always get the directory contents
croissants should be flaky, not tests
```
cd libbeat
mage goIntegTest
```
- Closes #36177
```
=== Failed
=== FAIL: libbeat/tests/integration TestTemplateDefault (22.19s) …
```
=> fix flaky integration tests

CHANGELOG.next.asciidoc, filebeat/input/filestream/fswatch.go, filebeat/input/filestream/fswatch_test.go
Multiple globs can resolve in duplicate filenames. These duplicates must be filtered out even before they reach the creation of file descriptors and additional checks, otherwise this causes a flood of warning messages in logs.
These warnings should catch only the cases when symlinks are resolved in known filenames.
The new test was failing before the fix with this message:
- Fixes #36253
=> Filter out duplicate paths resolved from matching globs

CHANGELOG.next.asciidoc, libbeat/docs/shared-autodiscover.asciidoc, x-pack/libbeat/autodiscover/providers/aws/elb/provider.go
Adds deprecation notice to aws_elb provider:
```
DEPRECATED: aws_elb autodiscover is now deprecated and will be removed in a future release.
```
Closes #29782.
1. Set up aws_elb provider:
```
heartbeat.autodiscover:
providers:
- type: aws_elb
period: 1m
regions: ["us-east-1", "us-east-2"]
access_key_id: my-access-key
secret_access_key: my-secret-access-key
templates:
- condition:
equals.port: 8080
config:
- type: tcp
hosts: ["${data.host}:${data.port}"]
schedule: "@every 5s"
timeout: 1s
```
2. Look for deprecation notice:
```
{"log.level":"warn","@timestamp":"2023-08-01T11:16:19.092+0200","log.logger":"cfgwarn","log.origin":{"file.name":"elb/provider.go","file.line":47},"message":"DEPRECATED: aws_elb …
```
=> [Heartbeat] Deprecate aws_elb provider

CHANGELOG.next.asciidoc, libbeat/processors/translate_sid/docs/translate_sid.asciidoc
The `translate_sid` processor is marked as a beta feature. It has been thoroughly tested through many deployments so mark it as GA.
- Closes #36279
=> libbeat/processors/translate_sid: mark as generally available

CHANGELOG-developer.next.asciidoc, x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/okta.go, x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/okta_test.go
This adds support for device entities to the Okta API entity analytics provider.
Milestone task.
1. Sign up for an Okta developer account at https://developer.okta.com/signup/
2. Add Fastpass for Okta Verify in the Authenticators section of the admin dashboard, selecting appropriate verification options (I selected all three).
3. Sign in the the Okta domain with another device (I used phone).
4. In the Security > API section of the Okta admin dashboard, create a new API token.
5. In x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta, run `OKTA_HOST=dev-<nnnnnnn>-admin.okta.com OKTA_TOKEN=<token> go test -log_response -v  -run Test/device` using your Okta domain and API token.
You should see something like this (details sanitised here):
```
=== RUN   Test
=== RUN …
```
=> x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta: add device handling

CHANGELOG.next.asciidoc, metricbeat/docs/modules/sql.asciidoc, metricbeat/helper/sql/sql.go, x-pack/metricbeat/module/sql/_meta/docs.asciidoc, x-pack/metricbeat/module/sql/docker-compose.yml, x-pack/metricbeat/module/sql/query/query.go, x-pack/metricbeat/module/sql/query/test_sql_mssql.py
Add support for executing a set of given queries for all databases present in a server. Currently, this feature is only supported for mssql driver.
It expects a field `fetch_from_all_databases` in the configuration to be set to `true` in order to enable the feature. This feature executes queries agnostic of database names (i.e., where database names are not already part of the query) for all databases in a server. On every call to `Fetch`, the database names are refreshed and to fire the given set of queries for a particular database, `USE @command` statement is used by prefixing the same to each query when iterating over database names.
`merge_results` feature merges results per database basis and not merging all results from all databases.
Please read the comments (`NOTE`) in between …
=> x-pack/metricbeat/module/sql: Add option to execute SQL queries for all databases

CHANGELOG.next.asciidoc, filebeat/input/internal/procnet/procnet.go, filebeat/input/internal/procnet/procnet_test.go, filebeat/input/tcp/input.go, filebeat/input/tcp/input_test.go, filebeat/input/udp/input.go, filebeat/input/udp/input_test.go
The net package may return IPv4 addresses as an `IPv6len` `net.IP` value with a ::ffff: prefix before the four IPv4 octets[1]. This means that we may incorrectly assign all addresses to the IPv6 class rather than to the IPv4 class that is expected. This results in loss of metrics for the input and confusing warnings complaining about an absent address in /proc/net/{tcp,udp}6.
Fix this by using the `To4` and `To16` methods which are guaranteed to return a `net.IP` that is the expected length for the class and compare against that length.
[1]https://cs.opensource.google/go/go/+/refs/tags/go1.21.0:src/net/ip.go;l=62
- Relates #35064
=> filebeat/input/{tcp,udp}: fix resolution of device address during metric initialisation

filebeat/input/filestream/fswatch_test.go, filebeat/input/filestream/identifier.go, filebeat/input/filestream/identifier_fingerprint.go, filebeat/input/filestream/identifier_inode_deviceid.go, filebeat/input/filestream/prospector_test.go
In https://github.com/elastic/beats/pull/36065 a few fields were renamed in order to clarify their purpose. Unfortunately, this rename was a part of a new feature PR which was not supposed to be backported to 7.17.
However, backporting some other changes related to this code has now become challenging and results in build failures (note the fixing commits):
- https://github.com/elastic/beats/pull/36095
- https://github.com/elastic/beats/pull/36264
This PR makes the naming consistent with the main branch, so we can easily backport changes.
=> Make naming consistent with the main branch

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-entity-analytics.asciidoc, x-pack/filebeat/input/entityanalytics/provider/okta/conf.go, x-pack/filebeat/input/entityanalytics/provider/okta/okta.go, x-pack/filebeat/input/entityanalytics/provider/okta/okta_test.go, x-pack/filebeat/input/entityanalytics/provider/okta/statestore.go, x-pack/filebeat/input/entityanalytics/provider/okta/statestore_test.go
This adds support for device entities to the Okta API entity analytics provider.
Milestone task.
- For elastic/security-team#6908
- Needs #35980
=> x-pack/filebeat/input/entityanalytics/provider/okta: add device handling

CHANGELOG.next.asciidoc, x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml
Fix Grok pattern in Cisco shared ingest pipeline.
1) Users have observed the following warning messages in Elasticsearch:
```
[2023-08-14T11:09:30,093][WARN ][o.e.i.c.GrokProcessor    ] [ES-NODE] character class has '-' without escape
```
2) The above warning message reports a problem with a pattern defined in a grok processor where a hyphen character is used as a literal character in a character class `[ .... ]` but the hyphen character is not escaped.
1) Download Filebeat, configure it to connect to an Elasticsearch cluster and run `filebeat setup -e`. Wait for all the Filebeat assets (dashboards, ingest pipelines, etc.) to be loaded.
2) Check the Elasticsearch logs and observe the above warning message.
3) Delete all the ingest pipelines related to Filebeat (can be done in batch …
=> x-pack/filebeat/module/cisco Fix Cisco module Grok pattern

.github/dependabot.yml
Dependabot does not allow multiple configurations for a given Go module. So this reverts the change to segment the configuration along team boundaries with explicit team-based reviewer requirements. It was complaining about
```
The property '#/updates/1' is a duplicate. Update configs must have a unique combination of 'package-ecosystem', 'directory', and 'target-branch'
The property '#/updates/2' is a duplicate. Update configs must have a unique combination of 'package-ecosystem', 'directory', and 'target-branch'
```
as pointed out in https://github.com/elastic/beats/pull/36158#issuecomment-1665700688.
=> .github/dependabot.yml - Revert team based segmentation

libbeat/esleg/eslegclient/enc.go
Nit linting error fix.
This commit fixes a linting error with the `esleg/enc.go`, submitted separately from the PR that I noticed it in order to keep the original PR clean of such changes.
This should not have any side-effect on the codebase, it just removes the golangci-lint validation error.
```
enc.go:218:23: ST1016: methods on the same type should have the same receiver name (seen 1x "g", 6x "b") (stylecheck)
```
=> Fix linting error with receiver names

CHANGELOG.next.asciidoc, NOTICE.txt, auditbeat/module/file_integrity/event.go, auditbeat/module/file_integrity/event_test.go, auditbeat/module/file_integrity/fileinfo_posix.go, auditbeat/module/file_integrity/flatbuffers.go, auditbeat/module/file_integrity/schema.fbs, auditbeat/module/file_integrity/schema/Metadata.go, go.mod, go.sum
In environments where SELinux is employed then it is useful to monitor file metadata for changes to SELinux labels. A change to labeling can impact security posture. Similarly in environments where file ACLs are used (e.g. getfacl, setfacl) it is useful to monitor for changes to these ACLs (just like it is useful to monitor permissions in the file mode). So add support for the filesystem extended attributes (xattrs) named security.selinux and system.posix_acl_access that detail these.
- For #36265
Sample event:
```json
{
"@metadata": {
"beat": "auditbeat",
"type": "_doc",
"version": "8.10.0"
},
"@timestamp": "2023-08-16T14:30:29.388Z",
"agent": {
"ephemeral_id": "b7d1b2b6-712a-48d7-8de2-b419afd46d75",
"id": "1681fe91-1cc8-460e-9e7e-fb1fe9b29348",
"name": "linux",
"type": "auditbeat", …
```
=> auditbeat/module/file_integrity: add support for selinux and posix_acl_access xattrs

x-pack/filebeat/input/azureblobstorage/input_test.go
The 3000 workers test case is unreasonably high; there is no real justification for this many workers operating on a network-bound system and there is some reason to believe that on some systems this may be causing system i/o resource depletion and failure of unrelated tests. The issue that is being tested here is uncovered by as few as 100 workers. So remove the largest case.
Potentially related failure
```
=== Failed
=== FAIL: x-pack/filebeat/input/azureblobstorage Test_Concurrency/TestConcurrency_3000_Workers (100.30s)
input_test.go:463: timed out waiting for 10000 events
input_test.go:470: failed to get all events: got:3103 want:10000
=== FAIL: x-pack/filebeat/input/azureblobstorage Test_Concurrency (129.25s)
=== FAIL: x-pack/filebeat/input/cel TestInput/date_cursor (1.04s) …
```
=> x-pack/filebeat/input/azureblobstorage: reduce tested maximum worker load

.github/CODEOWNERS, metricbeat/helper/kubernetes/ktest/ktest.go, metricbeat/module/kubernetes/controllermanager/controllermanager_test.go, metricbeat/module/kubernetes/proxy/proxy_test.go, metricbeat/module/kubernetes/scheduler/scheduler_test.go, metricbeat/module/kubernetes/state_container/state_container_test.go, metricbeat/module/kubernetes/state_cronjob/state_cronjob_test.go, metricbeat/module/kubernetes/state_daemonset/state_daemonset_test.go, metricbeat/module/kubernetes/state_deployment/state_deployment_test.go, metricbeat/module/kubernetes/state_job/state_job_test.go, metricbeat/module/kubernetes/state_node/state_node_test.go, metricbeat/module/kubernetes/state_persistentvolume/state_persistentvolume_test.go, metricbeat/module/kubernetes/state_persistentvolumeclaim/state_persistentvolumeclaim_test.go, metricbeat/module/kubernetes/state_pod/state_pod_test.go, metricbeat/module/kubernetes/state_replicaset/state_replicaset_test.go, metricbeat/module/kubernetes/state_resourcequota/state_resourcequota_test.go, metricbeat/module/kubernetes/state_service/state_service_test.go, metricbeat/module/kubernetes/state_statefulset/state_statefulset_test.go, metricbeat/module/kubernetes/state_storageclass/state_storageclass_test.go
Currently, all `state_*` metricsets have a test that runs `TestStateMetricsFamily` in the testing file. However, controller manager, scheduler and proxy metricsets were missing that. This PR fixes that. 
This testing function was first introduced [in this PR](https://github.com/elastic/beats/pull/34448).
=> [Metricbeat][Kubernetes] Add test metrics family to scheduler, proxy and controller manager

metricbeat/docker-compose.yml, x-pack/metricbeat/docker-compose.yml
For metricbeat tests, update stack test version to 8.9.1 which is the latest GA release version. Tests are failing on the 8.10 branch.
> Build&Test / x-pack/metricbeat-pythonIntegTest / x-pack.metricbeat.tests.system.test_xpack_base.Test.test_start_stop (from pytest) 
>
> failed on setup with "Exception: Timeout while waiting for healthy docker-compose services: elasticsearch,kibana"
- https://beats-ci.elastic.co/job/Beats/job/beats/job/8.10/5/testReport/junit/x-pack.metricbeat.tests.system.test_xpack_base/
=> metricbeat - Update stack test version to 8.9.1

CHANGELOG.next.asciidoc, x-pack/filebeat/input/cel/input.go, x-pack/filebeat/input/cel/input_test.go
The redaction code currently panics when the redact option is not specified. It is recommended that this not be used unspecified, and we did initially consider erroring in this case, but decided against it. So fix the panic.
- Fixes #36387
=> x-pack/filebeat/input/cel: don't panic when redact option is not specified

CHANGELOG.next.asciidoc, x-pack/libbeat/management/generate.go, x-pack/libbeat/management/simple_input_config_test.go
Simplify the input configuration when running under Elastic-Agent by allowing units without the `streams` key. When they do not have a `streams` key, all the input configuration is ready from the unit's root level.
This case is only supported for the `filestream` input.
1. Get a stack deployment (elastic-package, cloud, etc)
1. Build Filebeat from the x-pack directory
2. Get a compatible version of the Elastic-Agent (or edit `libbeat/version/version.go` before building Filebeat)
3. Replace the Filebeat binary that came with Elastic Agent by the one you build
4. Run Elastic-Agent standalone with the following input …
=> Simplify input configuration under Elastic-Agent

CHANGELOG.next.asciidoc, libbeat/processors/dns/cache.go, libbeat/processors/dns/cache_test.go, libbeat/processors/dns/config.go, libbeat/processors/dns/dns.go, libbeat/processors/dns/dns_test.go, libbeat/processors/dns/doc.go, libbeat/processors/dns/docs/dns.asciidoc, libbeat/processors/dns/resolver.go, libbeat/processors/dns/resolver_test.go
The dns processor previously supported only reverse DNS lookups.
This adds support for performing A, AAAA, and TXT record queries.
The `response.ptr.histogram` metric was renamed to `request_duration.histogram`.
This naming allows the metric to represent the duration of the DNS request
for all query types.
Closes https://github.com/elastic/beats/issues/11416
- Closes #11416
`filebeat.yml`:
```yaml
---
- type: cel
publisher_pipeline:
disable_host: true
interval: 1m
resource:
url: not_used_1
redact:
fields: ~
program: |
{
'want_more': false,
'events': [
{
'message': 'newyork.weather',
}
],
}
processors:
- dns:
type: TXT
nameservers: ['dns.toys']
fields:
message: weather
- type: cel
publisher_pipeline:
disable_host: true
interval: 1m
resource:
url: not_used_2
redact:
fields: …
```
=> dns processor - Add A, AAAA, and TXT query support 

CHANGELOG.next.asciidoc, libbeat/processors/syslog/docs/syslog.asciidoc
- Removed the experimental tag for the syslog processor to mark processor as GA.
- Improve documentation of the syslog processor to note that it does not directly handle receiving external messages.
- Closes #36416
=> Mark syslog processor as GA and improve documentation

.github/CODEOWNERS
Assign ownership of the httplog and httpmon packages to SEI as these are shared packages used by the CEL and HTTPJSON packages which belong to SEI.
-
=> CODEOWNERS: assign ownership of x-pack/filebeat/input/internal packages

CHANGELOG.next.asciidoc, x-pack/metricbeat/module/azure/billing/data.go, x-pack/metricbeat/module/azure/billing/data_test.go
With this change, we are adding support for Azure resource tags from the response from the [Usage Details API](https://learn.microsoft.com/en-us/rest/api/consumption/usage-details/list?tabs=HTTP). Both legacy and modern usage details data formats include tags from resources.
We take tag values from the usage details response and store them in the event as `azure.resource.tags` field. We can leverage the existing [module level mapping](https://github.com/elastic/beats/blob/3d55242556cb2a535c4f81d1b42a459eea322c97/x-pack/metricbeat/module/azure/_meta/fields.yml#L31-L36) for these field.
Multiple users asked for including resource tags to make the most of usage details data.
- Closes https://github.com/elastic/beats/issues/36373
=> [Azure] [Billing] Add Azure resource tags from Usage Details API

filebeat/docs/modules/sonicwall.asciidoc, x-pack/filebeat/module/sonicwall/_meta/docs.asciidoc
On this [Beats docs page](http://localhost:8000/guide/filebeat-module-sonicwall.html) the `Elastic integrations documentation` link should point to:
`https://docs.elastic.co/en/integrations/sonicwall_firewall`
rather than to:
`https://docs.elastic.co/en/integrations/sonicwall` (which gives a 404 error)
Closes: https://github.com/elastic/ingest-docs/issues/440
=> Fix link to SonicWall Firewall integration docs

.golangci.yml
A `logp.TestingSetup` call can only fail when no `logp.ToObserverOutput()` option has been provided and one of syslog, file or event log output has been selected. There is no case in the code base where this is true. So disable the errcheck linter for this function.
The only way that the function can return an error is when a user makes use of a custom `logp.Option` function since none of the provided `Option`s alter the logp.Config to cause output to failable destinations.
-
=> golangci.yml: silence invalid linter complaints on use of logp.TestingSetup

CHANGELOG.next.asciidoc, x-pack/filebeat/input/httpjson/encoding.go, x-pack/filebeat/input/httpjson/encoding_test.go
The default rendering of errors from the json, csv and xml decoders can be a little terse, but the error values themselves contain information that allows the text context of the error to be constructed and returned. It is a common problem that users are unable to decipher the error messages, so add this text context to help.
-
=> x-pack/filebeat/input/httpjson: make response body decoding errors more informative

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-entity-analytics.asciidoc, x-pack/filebeat/input/entityanalytics/provider/okta/conf.go, x-pack/filebeat/input/entityanalytics/provider/okta/okta.go, x-pack/filebeat/input/entityanalytics/provider/okta/okta_test.go
This adds support for specifying which of users/devices to collect from the Okta API endpoints in order to reduce network costs for users who do not need a full set of entities.
The current change does not change the behaviour of device collection of registered owners and registered users; when the "devices" dataset is selected there user entities will still be collected as they are considered here as an attribute of the device, rather than a component of the users dataset.
- For #36440
=> x-pack/filebeat/input/entityanalytics/provider/okta: allow fine-grain control of API requests

CHANGELOG.next.asciidoc, libbeat/processors/add_process_metadata/add_process_metadata_test.go, libbeat/processors/add_process_metadata/gosysinfo_provider.go
Previously, the go-sysinfo types.Process was not being queried for its environment value if it existed. This is conditionally available depending on platform, so check and add it if it is.
- Fixes #36469
=> libbeat/processors/add_process_metadata: fix environment collection

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 8.9.2

x-pack/metricbeat/Jenkinsfile.yml
Skip the Metricbeat cloudAWS test until a further solution is found. 
- Relates #36425
=> Ignore Metricbeat cloudAWS test

CHANGELOG.next.asciidoc, filebeat/input/winlog/input.go, winlogbeat/beater/eventlogger.go, winlogbeat/eventlog/eventlog.go, winlogbeat/eventlog/wineventlog.go, winlogbeat/eventlog/wineventlog_experimental.go
When winlogbeat's event loggers encounter recoverable errors they handle this by closing and reopening the channel. This causes the metric collection for the beat and dependent winlog filebeat input to lose metric collection as metric registration only occurs on configuration. So add a soft-close method, Reset, that only closes the channel and leaves the event logger valid, leaving the metrics in tact, and use this for recovering from errors.
- Fixes #36479
- Closes #36482
=> winlogbeat/eventlog: ensure event loggers retain metric collection when handling recoverable errors

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-entity-analytics.asciidoc, x-pack/filebeat/input/entityanalytics/provider/azuread/azure.go, x-pack/filebeat/input/entityanalytics/provider/azuread/azure_test.go, x-pack/filebeat/input/entityanalytics/provider/azuread/conf.go, x-pack/filebeat/input/entityanalytics/provider/azuread/conf_test.go
This adds support for specifying which of users/devices to collect from the AzureAD API endpoints in order to reduce network costs for users who do not need a full set of entities.
The current change does not change the behaviour of device collection of registered owners and registered users; when the "devices" dataset is selected there user entities will still be collected as they are considered here as an attribute of the device, rather than a component of the users dataset.
- For #36440
=> x-pack/filebeat/input/entityanalytics/provider/azuread: allow fine-grain control of API requests

CHANGELOG.next.asciidoc, filebeat/docs/modules/aws.asciidoc, x-pack/filebeat/module/aws/_meta/docs.asciidoc, x-pack/libbeat/common/aws/credentials.go, x-pack/libbeat/docs/aws-credentials-config.asciidoc
=> x-pack/libbeat/common/aws: add support for external IDs

CHANGELOG.next.asciidoc, packetbeat/protos/http/http.go, packetbeat/protos/http/http_test.go
Previously, extractHostHeader would panic if the host part of header was empty. Avoid this by using standard library functions to do splits and clean up IPv6 addresses.
Add tests to confirm old behaviour and test to cover panic case.
Counter proposal to #36498.
- Fixes #36497
- Closes #36498
=> packetbeat/protos/http: don't panic when host is empty

libbeat/tests/integration/framework.go, x-pack/filebeat/tests/integration/shipper_test.go
Add filebeat shipper input/output integration test
```sh
mage goUnitTest
```
```sh
mage docker:composeUp
go test ./tests/integration -count 1 -tags integration -run TestShipperInputOutput
```
- Relates elastic/elastic-agent-shipper#290
=> add filebeat integration test for shipper input/output

x-pack/filebeat/input/httpjson/cursor.go, x-pack/filebeat/input/httpjson/input.go, x-pack/filebeat/input/httpjson/input_cursor.go, x-pack/filebeat/input/httpjson/pagination.go, x-pack/filebeat/input/httpjson/rate_limiter.go, x-pack/filebeat/input/httpjson/request.go, x-pack/filebeat/input/httpjson/response.go, x-pack/filebeat/input/httpjson/split.go, x-pack/filebeat/input/httpjson/split_test.go, x-pack/filebeat/input/httpjson/transform.go, x-pack/filebeat/input/httpjson/transform_append.go, x-pack/filebeat/input/httpjson/transform_set.go
This change makes largely non-semantic changes to the package to clarify the behaviour of the components, but also makes some minor optimisations to reduce allocations.
- For #35432
=> x-pack/filebeat/input/httpjson: post-refactor clean-up

CHANGELOG-developer.next.asciidoc, x-pack/filebeat/input/httpjson/input_test.go
With the change from concurrent to sequential processing this test is no longer flakey. This is confirmed by re-applying a delay to the publication of the first event in a set of events. This change causes the concurrent code to fail consistently, but the current sequential code passes.
The test change used to test the flake is
```diff
diff --git a/x-pack/filebeat/input/httpjson/request.go b/x-pack/filebeat/input/httpjson/request.go index 6a1d926ab4..3ed904f16d 100644
--- a/x-pack/filebeat/input/httpjson/request.go
+++ b/x-pack/filebeat/input/httpjson/request.go
@@ -16,6 +16,7 @@ import (
"reflect"
"strconv"
"strings"
+       "time"
"github.com/PaesslerAG/jsonpath"
@@ -741,6 +742,10 @@ func newPublisher(trCtx *transformContext, pub inputcursor.Publisher, publish bo
}
func (p *publisher) …
```
=> x-pack/filebeat/input/httpjson: re-enable previously flakey first_event test

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-cel.asciidoc, x-pack/filebeat/input/cel/config_auth.go, x-pack/filebeat/input/cel/config_okta_auth.go, x-pack/filebeat/input/cel/config_test.go
- Enhancement
- Docs
Added support for Okta as a separate OAuth2 provider. This is required because specific use cases
require access tokens with okta.* scopes, which involves a specific 2 step auth mechanism using a private
RSA JWK to generate a JWT which is in turn used to fetch an access token. Standard client_id & client_secrets don't
work in this scenario. It is a similar implementation to the httpjson PR: https://github.com/elastic/beats/pull/36273. This implementation for CEL ensures feature parity with the httpjson input.
- Closes #36336
=> [Filebeat][CEL] - Added support for Okta Oauth2 provider

CHANGELOG.next.asciidoc, x-pack/filebeat/input/internal/httplog/roundtripper.go
The request and response bodies are included twice in request tracer messages. The body appears in both the event.original and http.{request,response}.body.content. This removes the body from the event.original. It should help reduce the log message sizes for large responses.
The motivation is to allow larger responses to fit into the request tracer log. When a log message exceeds the max size of a log (default 1 MiB) then the message is dropped and a warning is logged by zap to stderr.
=> [Filebeat] httplog - reduce duplication to shrink log message size

metricbeat/tests/system/test_lightmodules.py
metricbeat/tests/system/test_lightmodules.py was failing, it seems we had a custom class with the name starting in 'Test' and that was confusing pytest. This commit fixes the issue by renaming the class.
- Fixes https://github.com/elastic/beats/issues/36515
~~## Logs~~
=> Fix class name in Python Tests

CHANGELOG.next.asciidoc, x-pack/libbeat/management/generate.go, x-pack/libbeat/management/generate_test.go, x-pack/libbeat/management/managerV2_test.go
When an input configuration comes from Elastic-Agent the data_stream.* fields sometimes are flattened (e.g: data_stream.dataset: mystuff), this was not supported by Beats.
This commit enables support for it.
Configure a standalone Elastic-Agent with a flattened `data_stream` field, like this:
```yaml
inputs:
id: unique-id-per-input
data_stream.dataset: mystuff
paths:
- /var/log/my-file/my.log*
```
Run the Elastic-Agent and assert that the dataset from the events is `mystuff`.
- Closes https://github.com/elastic/elastic-agent/issues/3191
~~## Logs~~
=> Support flattened data_stream.* fields under Elastic-Agent

CHANGELOG.next.asciidoc, x-pack/filebeat/input/httpjson/request.go, x-pack/filebeat/input/httpjson/request_test.go
Improves the friendliness and utility of error logging in the HTTPJSON input by
* making errors relate to behaviour rather than implementation
* removing duplicated wrapping
* making use of `textContextError` for JSON decoding failures
* improving consistency of error formatting and typography
- For #35432
=> x-pack/filebeat/input/httpjson: improve error logging

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-http-endpoint.asciidoc, x-pack/filebeat/input/http_endpoint/handler.go, x-pack/filebeat/input/http_endpoint/handler_test.go, x-pack/filebeat/input/http_endpoint/input.go, x-pack/filebeat/input/http_endpoint/input_test.go
=> x-pack/filebeat/input/http_endpoint: add input metrics

libbeat/docs/tab-widgets/install.asciidoc
**Problem:**
The current Windows installation docs use the Windows zip archive. The docs link to the generic download page, which also contains an msi file for Windows. If a user accidentally downloads the msi file instead, they can't complete the install using the instructions in the docs.
**Solution:**
Update the docs to link specifically to the Windows zip archive.
Closes https://github.com/elastic/beats/issues/36552
=> [DOCS] Link to ZIP archive in Windows install docs

NOTICE.txt, filebeat/channel/runner.go, go.mod, libbeat/beat/pipeline.go, x-pack/filebeat/input/shipper/input.go, x-pack/filebeat/tests/integration/shipper_test.go
add document equivalency check to filebeat as shipper process integration test
```
mage goUnitTest
```
```
mage docker:composeUp
go test ./tests/integration -count 1 -tags integration -run TestShipperInputOutput
```
- Closes elastic/elastic-agent-shipper#290
=> add equiv check to filebeat as shipper test

libbeat/docs/shared-docker.asciidoc
**Problem:**
The Beats Docker docs ([example](https://www.elastic.co/guide/en/beats/auditbeat/8.9/running-on-docker.html)) include an x-ref to the Elasticsearch docs for image verification. I recently removed this section as part of https://github.com/elastic/elasticsearch/pull/99371.
**Solution:**
Replace the x-ref with info about image verification.
Also:
- Removes unneeded `ifeval` tags
- Aligns notes for upcoming releases with those in the Elasticsearch docs
=> [DOCS] Remove Cosign x-ref from Docker docs

x-pack/filebeat/Jenkinsfile.yml
Skip the failing tests until a fix is found.
~~## Checklist~~
- Closes: https://github.com/elastic/beats/issues/36548
- Relates: https://github.com/elastic/beats/issues/36425
~~## Logs~~
=> Skip flaky Filebeat cloudAWS tests

libbeat/tests/system/test_cmd_completion.py
It looks like the output of the autocompletion script for zsh has
changed, hence the tests are failing. This commit fixes it.
The autocompletion is generated by an external
package (github.com/spf13/cobra), so this commit just updates the test
with the current output.
- Fixes https://github.com/elastic/beats/issues/36550
- Fixes …
=> Fix zsh autocompletion failing tests

filebeat/docs/inputs/input-filestream-file-options.asciidoc
Filestream docs mentioned `clean.on_state_change.removed` and `close_removed`, however those are not the correct configuration keys. This commit fixes that.
~~## Logs~~
=> Fix filestream configuration keys in docs

CHANGELOG.next.asciidoc, metricbeat/docs/modules/airflow.asciidoc, x-pack/metricbeat/module/airflow/_meta/docs.asciidoc, x-pack/metricbeat/module/statsd/server/server.go
This commit adds a log error when the statsd server fails to start, it
also improves the Airflow module documentation to make extra clear
that the module will start a statsd server.
1. Create the following `metricbeat.yml`:
```yaml
- module: airflow
host: "1.2.3.4" # Any IP that does not belong to the host running Metricbeat
port: "9102"
ttl: "10s"
period: 5s
metricsets: [ 'statsd' ]
output.console:
enabled: true
```
2. Start Metricbeat
3. After a few seconds you should see a log error like this:
```json …
```
=> Log error when statsd server fails to start and fix airflow docs

CHANGELOG.next.asciidoc, filebeat/beater/filebeat.go, filebeat/beater/filebeat_test.go, filebeat/input/filestream/takeover/takeover.go, filebeat/input/filestream/takeover/takeover_test.go
The take-over mode didn't take into account external configuration files. Now it's reading the merged configuration that contains the externally defined inputs too.
1. Create a directory with 2 YAML files, let's say it's `/test/config/inputs.d`:
`filebeat-before.yml`
```yaml
- type: log
paths:
- "/test/logs/error2.log"
- type: log
paths:
- "/test/logs/error3.log"
```
`filebeat-after.yml.disabled`
```yaml
id: my-filestream-id-2
take_over: true
paths:
- "/test/logs/error2.log"
id: my-filestream-id-3
take_over: true
paths:
- "/test/logs/error3.log"
```
2. Create the main config file in `/test/config/filebeat.yml` …
=> Fix ignoring external input configuration in `take_over: true` mode

metricbeat/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
Merge only after the release of 8.10.1.
=> [Release] Update test environments for 8.10.2

x-pack/filebeat/docs/inputs/input-entity-analytics.asciidoc
=> x-pack/filebeat/docs/inputs/entity-analytics: add missing provider link

CHANGELOG.next.asciidoc, packetbeat/protos/tcp/tcp.go, packetbeat/protos/tcp/tcp_test.go, packetbeat/protos/udp/udp.go, packetbeat/protos/udp/udp_test.go, packetbeat/sniffer/decoders.go, packetbeat/sniffer/sniffer.go
Configurations from fleet may contain multiple identical interfaces, when the sniffers for each of these are constructed, they will attempt to register under the same ID in the metrics collection namespace. This results in a panic. So give each interface an internally unique index to decollide them.
- For #36574
=> packetbeat/sniffer,packetbeat/protos/{tcp,udp}: prevent identical interfaces from colliding in metric namespace

.ci/bump-elastic-stack-snapshot.yml, .github/workflows/bump-elastic-stack-snapshot.yml, .github/workflows/bump-golang.yml
This should help with notifying when the `updatecli` failed in slack.
`oblt-robots` receive the notification and might get lost. Since this is now under the ingest team, let's change the team to be notified and the slack channel where the message should be sent so messages are not lost and team can act accordingly.
Requires https://github.com/elastic/apm-pipeline-library/pull/2361
=> updatecli: notify someone else in slack

CHANGELOG.next.asciidoc, packetbeat/beater/processor.go
When a config is provided by fleet, it will contain multiple definitions
of the same interface, and in future we may allow individual datastreams
to specify their own interface, so allow multiple distinct interfaces,
but ensure that no interfaces have the same configuration by removing
duplicates.
- For #36574
- Depends #36575
=> packetbeat/beater: deduplicate interface configs

metricbeat/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
Merge only after the release of 8.10.2.
=> [Release] Update test environments for 8.10.3

auditbeat/docs/getting-started.asciidoc, filebeat/docs/getting-started.asciidoc, heartbeat/docs/getting-started.asciidoc, metricbeat/docs/getting-started.asciidoc, packetbeat/docs/getting-started.asciidoc, x-pack/functionbeat/docs/getting-started.asciidoc
This adds a note to the Beats install instructions to note that ARM packages are available in addition to what's shown on the UI. Updates the guides for Filebeat, Metricbeat, Packetbeat, Auditbeat, Heartbeat, and Functionbeat.
Rel: https://github.com/elastic/beats/issues/33042
---
=> Update Beats install docs to mention ARM binaries

CHANGELOG.next.asciidoc, filebeat/beater/filebeat.go
This message is being logged excessively when running under Elastic Agent. It's not relevant because Fleet manages pipelines. So disable it.
Filebeat is unable to load the ingest pipelines for the configured modules because the Elasticsearch output is not configured/enabled. If you have already loaded the ingest pipelines or are using Logstash pipelines, you can ignore this warning.
(Yes, there are problems in that deployment and Filebeat is restarting a lot, but this message doesn't need to be logged.)
=> filebeat - stop warning under elastic-agent

CHANGELOG-developer.next.asciidoc, winlogbeat/sys/wineventlog/format_message.go, winlogbeat/sys/wineventlog/renderer.go, winlogbeat/sys/wineventlog/syscall_windows.go, winlogbeat/sys/wineventlog/wineventlog_windows.go, winlogbeat/sys/wineventlog/zsyscall_windows.go
Fix the use of pointer to uintptr conversions to comply with the unsafe.Pointer
rules. In particular, the code previously was not making conversions from a *T
to uintptr in the call expression as required by rule (4) Conversion of a
Pointer to a uintptr when calling syscall.Syscall[1].
[1]https://pkg.go.dev/unsafe#Pointer
-
=> winlogbeat/sys/wineventlog: fix unsafe pointer use

CHANGELOG.next.asciidoc, NOTICE.txt, go.mod, go.sum, x-pack/filebeat/docs/inputs/input-cel.asciidoc
=> x-pack/filebeat/input/cel: update mito version to v1.6.0

CHANGELOG.next.asciidoc, x-pack/packetbeat/LICENSE-Npcap.txt, x-pack/packetbeat/magefile.go, x-pack/packetbeat/npcap/installer/LICENSE, x-pack/packetbeat/tests/system/app_test.go
See title.
~Depends on go version being bumped.~
- Closes #36539
- Depends elastic/golang-crossbuild#315
- Fixes #36405
=> x-pack/packetbeat: bump npcap version to v1.76

libbeat/processors/ratelimit/docs/rate_limit.asciidoc
=> Remove Beta banner from filebeat ratelimit function

CHANGELOG-developer.next.asciidoc, libbeat/processors/cache/cache.go, libbeat/processors/cache/cache_test.go, libbeat/processors/cache/config.go, libbeat/processors/cache/config_test.go, libbeat/processors/cache/docs/cache.asciidoc, libbeat/processors/cache/file_store.go, libbeat/processors/cache/file_store_test.go, libbeat/processors/cache/mem_store.go, libbeat/processors/cache/mem_store_test.go
See title.
- For elastic/integrations#2816
=> libbeat/processors/cache: add file-backed cache

CHANGELOG.next.asciidoc, x-pack/filebeat/input/httpjson/cursor.go, x-pack/filebeat/input/httpjson/input_test.go, x-pack/filebeat/input/httpjson/rate_limiter.go, x-pack/filebeat/input/httpjson/request.go, x-pack/filebeat/input/httpjson/value_tpl.go, x-pack/filebeat/input/httpjson/value_tpl_test.go
This adds valuable missing context to the debug logging emitted for template evaluation. Previously, only the final result was printed to the log, which failed to provide the information required to be able to determine why any given template was being executed. So add the target name to the logs.
- For #35432
=> x-pack/filebeat/input/httpjson: improve template evaluation logging

CHANGELOG.next.asciidoc, libbeat/reader/readfile/fs_metafields_other.go, libbeat/reader/readfile/fs_metafields_windows.go, libbeat/reader/readfile/metafields_other_test.go, libbeat/reader/readfile/metafields_windows_test.go
To better align with ECS and better store the values in Elasticsearch.
See steps in https://github.com/elastic/beats/pull/36065
- Closes https://github.com/elastic/beats/issues/36695
- Relates https://github.com/elastic/integrations/pull/7716
=> Make file system metadata values strings

CHANGELOG.next.asciidoc, auditbeat/auditbeat.reference.yml, filebeat/filebeat.reference.yml, heartbeat/heartbeat.reference.yml, libbeat/_meta/config/output-elasticsearch.reference.yml.tmpl, libbeat/outputs/elasticsearch/config.go, libbeat/outputs/elasticsearch/config_test.go, libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc, metricbeat/metricbeat.reference.yml, packetbeat/packetbeat.reference.yml, winlogbeat/winlogbeat.reference.yml, x-pack/auditbeat/auditbeat.reference.yml, x-pack/filebeat/filebeat.reference.yml, x-pack/functionbeat/functionbeat.reference.yml, x-pack/heartbeat/heartbeat.reference.yml, x-pack/metricbeat/metricbeat.reference.yml, x-pack/osquerybeat/osquerybeat.reference.yml, x-pack/packetbeat/packetbeat.reference.yml, x-pack/winlogbeat/winlogbeat.reference.yml
Change the default compression level for the Elasticsearch output from 0 to 1. Part of https://github.com/elastic/ingest-dev/issues/2458
The benchmarks evaluating this change were run by @alexsapran and discussed in https://github.com/elastic/ingest-dev/issues/2399. In summary we expect this to have the following effects on "typical" ingestion:
- ~70-80% reduction in data volume
- 20-25% CPU increase
- ~10% ingestion delay
The exact numbers depend on the specific configuration and the type of data being ingested. The CPU and ingestion changes were fairly stable in tests, and anything noticeably outside that range should be flagged for evaluation if it arises during testing.
=> Enable compression by default for Elasticsearch outputs

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-cel.asciidoc, x-pack/filebeat/input/cel/config.go, x-pack/filebeat/input/cel/input.go, x-pack/filebeat/input/cel/input_test.go
See title.
Run `go test -v -run TestInput/debug` in the cel package. You should see the logs for the test, including a line like so
```
{"log.level":"debug", ... ,"log.logger":"cel_test.cel_debug"," ... ,"message":"DEBUG", ... ,"tag":"partial sum","value":5, ...}
```
for the happy path test and like so
```
{"log.level":"debug", ... ,"log.logger":"cel_test.cel_debug", ... ,"message":"ERROR", ... ,"tag":"divide by zero","error":{"message":"division by zero"}, ...}
```
for the error path test.
The surprising field rename from "value" to "error" that is not explainable from the code in this change is undocumented pixie dust from zap. I guess it's OK.
- Depends #36651
=> x-pack/filebeat/input/cel: add support for partial evaluation debug logging

CHANGELOG-developer.next.asciidoc, x-pack/filebeat/docs/inputs/input-azure-blob-storage.asciidoc, x-pack/filebeat/input/azureblobstorage/job.go
- Bug
- Docs
There was a minor logical error and a documentation error for the PR: https://github.com/elastic/beats/pull/36690,
which was discovered after the merge. This PR aims to fix those.
- Relates #36690
=> [filebeat][azure-blob-storage] - Cleaned up documentation errors & fixed a minor bug.

CHANGELOG.next.asciidoc, packetbeat/protos/amqp/amqp_structs.go, packetbeat/protos/protos.go
The transaction hash size is currently calculated as 2⊕16 (18) which is most likely not what was intended. The code entered the code base in the initial import which does not have an associated review. However, the symbol ^ signifies exponent in other languages, and XOR is almost never what someone would use for defining a constant like this, so it is very likely that the original author intended a 64Ki cache size.
-
=> packetbeat/protos{,/amqp}: fix transaction hash size constant

CHANGELOG.next.asciidoc, filebeat/input/filestream/fswatch.go, filebeat/input/filestream/fswatch_test.go
This dramatically drops the memory usage, particularly on large amount of files.
```sh
Before
BenchmarkToFileDescriptor-10   764442     15849 ns/op   2688 B/op    12 allocs/op
After
BenchmarkToFileDescriptor-10   758116     15171 ns/op   416 B/op      8 allocs/op
```
```sh
go test -run=none -bench=".*ToFileDescriptor.*" -benchmem -benchtime=10s -memprofile profile.bin
go tool pprof -http localhost:9999 profile.bin
```
- Relates #35734
=> Re-use buffers to optimise memory allocation in fingerprint

.github/CODEOWNERS
Updated osquerybeat codeowners after conversation with @kevinlog.
The codeowners team that was there before does not longer exist and developers are working on the different projects/teams. So it was not adequately reflecting the people would need to approve PR in order to unblock it.
=> Update osquerybeat codeowners

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-http-endpoint.asciidoc, x-pack/filebeat/input/http_endpoint/config.go, x-pack/filebeat/input/http_endpoint/input.go, x-pack/filebeat/input/http_endpoint/input_test.go
See title.
- For elastic/integrations#8066
=> x-pack/filebeat/input/http_endpoint: allow endpoint to receive PUT and PATCH requests

x-pack/filebeat/docs/inputs/input-cel.asciidoc
The documentation shows the type of `redact.fields` as a scalar. This is not correct; it should be an array.
-
=> x-pack/filebeat/docs/inputs/input-cel: fix docs for redact

CHANGELOG.next.asciidoc, heartbeat/monitors/logger/logger.go, heartbeat/monitors/logger/logger_test.go, heartbeat/monitors/wrappers/wrappers_test.go
Closes [#35706.](https://github.com/elastic/beats/issues/36017)
capture and log the individual connection metrics for all the lightweight monitors. The new information will be under the key `network_info`. The properties will keep their original name. Doing so will give us the chance to read the details in HB documentation in case of any doubt about their significance, etc.
1. Build heartbeat locally.
2. Set up a lightweight monitor
3. Run HB
This is one example with a http monitor:
```
heartbeat.monitors:
- type: http
enabled: true
id: my-monitor
name: My Monitor
urls: ["https://www.australia.gov.au/"]
schedule: '@every 30s'
```
**Log Sample**:
`{"log.level":"info","@timestamp":"2023-10-03T19:50:10.252+0200","log.origin":{"file.name":"logger/logger.go","file.line":168},"message":"Monitor …
=> [Heartbeat] log the individual connection metrics for all the lightweight monitors

CHANGELOG.next.asciidoc, libbeat/processors/syslog/syslog.go
Fix the ability to use `when` conditions with the syslog processor. Previously the config would be rejected.
Fixes #36762
- Closes #36762
```yaml
---
- type: cel
publisher_pipeline:
disable_host: true
interval: 1m
resource:
url: not_used_1
redact:
fields: ~
program: |
{
'want_more': false,
'events': [
{
'message': '<30>1 2023-09-28T12:10:12.175599+02:00 test.lab.com systemd 153589 - - Stopped target',
},
{
'message': 'Not syslog.',
}
],
}
processors:
#
#}
#{
#}
- syslog:
when.regexp.message: '^<\d+>\d '
field: message
output.console.pretty: true
```
=> [syslog processor] Fix 'when' conditions

metricbeat/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
This updates the test environments to next minor release which is 8.12.0.
=> [Release] Update test environment to 8.12.0

auditbeat/auditbeat.reference.yml, filebeat/filebeat.reference.yml, heartbeat/heartbeat.reference.yml, libbeat/_meta/config/setup.dsl.reference.yml.tmpl, metricbeat/metricbeat.reference.yml, packetbeat/packetbeat.reference.yml, winlogbeat/winlogbeat.reference.yml, x-pack/auditbeat/auditbeat.reference.yml, x-pack/filebeat/filebeat.reference.yml, x-pack/functionbeat/functionbeat.reference.yml, x-pack/heartbeat/heartbeat.reference.yml, x-pack/metricbeat/metricbeat.reference.yml, x-pack/osquerybeat/osquerybeat.reference.yml, x-pack/packetbeat/packetbeat.reference.yml, x-pack/winlogbeat/winlogbeat.reference.yml
manual backport of #36750 because I accidentally closed the PR, which deleted the branch, and the mergify bot can't or won't create a new PR on a new branch.
=> backport of improve dsl docs (#36750)

CHANGELOG.next.asciidoc, x-pack/filebeat/input/entityanalytics/provider/azuread/azure.go, x-pack/filebeat/input/entityanalytics/provider/azuread/conf.go
During full sync the provider may have state from a previous dataset. So in the case that the user has changed dataset from users to devices or vice versa the provider may publish already existing state in the entity graph. This change adds conditional checks to ensure that unwanted dataset records are not published.
-
=> x-pack/filebeat/input/entityanalytics/provider/azuread: avoid work on unwanted datasets

CHANGELOG.next.asciidoc, x-pack/filebeat/input/entityanalytics/provider/okta/conf.go, x-pack/filebeat/input/entityanalytics/provider/okta/okta.go
During full sync the provider may have state from a previous dataset. So in the case that the user has changed dataset from users to devices or vice versa the provider may publish already existing state in the entity graph. This change adds conditional checks to ensure that unwanted dataset records are not published.
-
=> x-pack/filebeat/input/entityanalytics/provider/okta: avoid work on unwanted datasets

CHANGELOG.next.asciidoc, x-pack/filebeat/input/http_endpoint/config.go, x-pack/filebeat/input/http_endpoint/config_test.go
Integrations using the `http_endpoint` input that fails with a panic due to a misconfiguration. Validation added and a user-friendly log is added.
- Closes #36772
=> x-pack/filebeat/input/http_endpoint: Add validation for empty URL config

libbeat/idxmgmt/lifecycle/es_client_handler.go, libbeat/idxmgmt/lifecycle/es_client_test.go
This fixes an issue where a nil config can cause a panic,  and adds a variety of tests to make sure we don't run into this again.
=> Improve nil handling, add tests to serverless implementation

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/auditbeat/auditbeat-role.yaml
Update the Auditbeat Kubernetes cluster role to add read permissions on jobs/cronjobs. These permissions were added to other Cluster Role permissions previously, but was missed on auditbeat.
- ~~[] I have commented my code, particularly in hard-to-understand areas~~
- ~~[] I have made corresponding changes to the documentation~~
This was tested by running the auditbeat daemonset on a GKE cluster with a cronjob running. The original `failed to list *v1.Job: jobs.batch is forbidden` error was not seen in auditbeat logs, and auditbeat process events were enriched with orchatrator information:
```
{
"_index": …
```
=> Give Auditbeat k8s Clusterrole job permissions

metricbeat/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
Merge only after the release of 8.10.4.
=> [Release] Update test environments for 8.10.5

x-pack/functionbeat/docs/page_header.html
Update functionbeat doc to clearly state that from now on this is deprecated.
=> Update functionbeat doc according to functionbeat deprecation planning

libbeat/outputs/logstash/docs/logstash.asciidoc
The default `loadbalance` setting for Logstash output should be documented as `false`. Discussion is [here](https://github.com/elastic/beats/issues/12567#issuecomment-1769188098).
PREVIEW
---
=> Update default loadbalance setting for Logstash to 'false'

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6576547382
---
<Actions>
<action id="d38f09b2268c8975540d4badaedc8f676d8014bc49989f4fa7c5cdf1dbc196c1">
<p>1 file(s) updated with &#34;$1:8.11.0-64ca6348-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.0-64ca6348

CHANGELOG.next.asciidoc, x-pack/metricbeat/module/azure/database_account/manifest.yml
Move the `CassandraConnectionClosures` metric name from the always-available list of metrics to the Cassandra-focused list of metrics.
Metric names not always available should be listed in a section marked with the [ignore_unsupported](https://www.elastic.co/guide/en/beats/metricbeat/8.6/metricbeat-metricset-azure-monitor.html) setting set to `true`.
The integration works if the subscription has at least one Cassandra cluster available but fails otherwise.
- Related elastic/integrations#5453
=> [Azure Metrics] Fix CassandraConnectionClosures metric configuration

CHANGELOG.next.asciidoc, x-pack/winlogbeat/module/routing/ingest/routing.yml
Apparently some events from Windows servers and workstations in Security channel have a lowercase channel name. This has not been observed in other channels, but defensively apply the same care there.
- Closes #36670
=> x-pack/winlogbeat/module/routing: make pipeline routing robust to channel letter case

libbeat/idxmgmt/index_support.go
Closes https://github.com/elastic/beats/issues/36732
This adds an extra bit of logic so the setup verification method reports instructions specific to either ILM or DSL setup.
=> Serverless user messages

libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc
This commit documents the `_bulk` API usage by the Elasticsearch output and how different status codes are handled.
Assuming `beats` and `docs` are both in `$GIT_HOME`, build the docs:
```sh
$GIT_HOME/docs/build_docs --respect_edit_url_overrides --doc $GIT_HOME/beats/filebeat/docs/index.asciidoc --resource=$GIT_HOME/beats/x-pack/filebeat/docs --chunk 1 --open
```
A …
=> Document ES output API usage

CHANGELOG.next.asciidoc, x-pack/filebeat/input/internal/httplog/roundtripper.go
=> x-pack/filebeat/input/internal/httplog: fix incorrect append source

CHANGELOG.next.asciidoc, auditbeat/auditbeat.reference.yml, filebeat/filebeat.reference.yml, heartbeat/heartbeat.reference.yml, libbeat/_meta/config/output-elasticsearch.reference.yml.tmpl, libbeat/outputs/elasticsearch/client.go, libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc, libbeat/outputs/elasticsearch/elasticsearch.go, metricbeat/metricbeat.reference.yml, packetbeat/packetbeat.reference.yml, winlogbeat/winlogbeat.reference.yml, x-pack/auditbeat/auditbeat.reference.yml, x-pack/filebeat/filebeat.reference.yml, x-pack/functionbeat/functionbeat.reference.yml, x-pack/heartbeat/heartbeat.reference.yml, x-pack/metricbeat/metricbeat.reference.yml, x-pack/osquerybeat/osquerybeat.reference.yml, x-pack/packetbeat/packetbeat.reference.yml, x-pack/winlogbeat/winlogbeat.reference.yml
add support for `idle_connection_timeout` for ES output. This allows connections to be closed if they aren't being used.
1. Add `idle_connection_timeout` to elasticsearch output config
```
output.elasticsearch:
idle_connection_timeout: 10s
```
2. Start beat, and send some events to elasticsearch
3. observer network connection with `netstat -an`
4. wait timeout time, and observer that network connection is being closed
- Relates #35615
=> Add support for idle_connection_timeout to elasticsearch output

CHANGELOG.next.asciidoc, NOTICE.txt, go.mod, go.sum
=> mod: update version of github.com/elastic/go-libaudit to v2.4.0

auditbeat/docs/modules/file_integrity.asciidoc, auditbeat/module/auditd/audit_linux.go, auditbeat/module/file_integrity/_meta/docs.asciidoc, auditbeat/module/file_integrity/action.go, auditbeat/module/file_integrity/config.go, auditbeat/module/file_integrity/event.go, auditbeat/module/file_integrity/file_parsers.go, auditbeat/module/file_integrity/fileorigin_darwin.go, auditbeat/module/file_integrity/metricset.go
Really minor fixes to docs and comments in auditbeat/modules. As I was reading the code I was applying some changes, so I figured I should contribute them.
=> auditbeat/module - docs and comment nits

filebeat/fileset/pipelines.go
closes https://github.com/elastic/beats/issues/36965
This is a fairly simple fix, since the `PipelineLoader` is already backed by ES, so we just needed to expand the interface.
I have tested this under serverless, but I'm not too familiar with pipeline setup, so I would prefer that someone with more knowledge of filebeat setup also look at this. My understanding is that serverless has no API for plugins or ingest processors, so there's no need for us to perform this check under serverless.
=> Fix pipeline setup under serverless

CHANGELOG.next.asciidoc, metricbeat/beater/metricbeat.go, metricbeat/mb/builders.go, metricbeat/mb/mb.go
Make metrics published by "inputs" available through the /inputs/ route on the HTTP monitoring endpoint of Auditbeat and Metricbeat.
For Agent, include a snapshot of those metrics within the Agent diagnostics bundle as "input_metrics.json".
When running under Agent, each module instance is configured with only a single metricset. That module is given a unique `id`. That ID is what will be used as the `id` within the /inputs/ data. And that `id` will also be added as context to the logger that is passed into every metricset so that any log messages from a metricset can be associated back to the agent stream ID).
Relates: #36945
- Relates #36945
AFAICT no MetricSet implementations in Metricbeat or Auditbeat register any metrics so for now you can only use this to see what instances are …
=> Auditbeat,Metricbeat - add /inputs/ to HTTP monitoring endpoint

CHANGELOG.next.asciidoc, auditbeat/docs/modules/auditd.asciidoc, auditbeat/module/auditd/_meta/docs.asciidoc, auditbeat/module/auditd/config.go, auditbeat/module/auditd/config_test.go
Setting ignore_errors to true allows incompletely valid rule sets to be
used in a configuration. This is equivalent to the -i flag of auditctl.
In auditbeat/module/auditd, run `go test -v -run TestConfig/ValidateWithError`. Both tests should pass and the second should emit a warning log line similar to this
```
{"log.level":"warn","@timestamp":"2023-10-16T09:41:28.941+1030","log.logger":"auditd","log.origin":{"file.name":"auditd/config.go","file.line":232},"message":"errors loading rules: 3 errors: at (audit_rules at auditbeat.yml):1: failed to parse rule '-x bad -F flag': flag provided but not defined: -x; at (audit_rules at auditbeat.yml):2: failed to parse rule '-a always,exit -w /etc/passwd': mutually exclusive flags uses together (file watch [-w|-p] and audit rule [-a|-A|-S|-C|-F]); …
```
=> auditbeat/module/auditd: add ignore_errors config option

CHANGELOG-developer.next.asciidoc, CHANGELOG.next.asciidoc, x-pack/auditbeat/tracing/int_aligned.go
Fix copy arguments for strict aligned architectures
Small typo on copy arguments. In practice only affects arm32 and arm64 as I doubt there are users
of other architectures around.
Without this fix, Auditbeat would incorrectly decode ktrace events in non i386/amd64.
=> Fix copy arguments for strict aligned architectures

libbeat/docs/shared-ssl-config.asciidoc
The docs didn't show where to put issuer certificate in the context of TLS servers. This explains how to build up a PEM certificate bundle
=> docs - Clarify how to use 'certificate' for servers

CHANGELOG.next.asciidoc, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/filebeat/filebeat-configmap.yaml, filebeat/autodiscover/builder/hints/config.go, filebeat/autodiscover/builder/hints/logs.go, filebeat/autodiscover/builder/hints/logs_test.go, filebeat/docs/autodiscover-hints.asciidoc, filebeat/docs/inputs/input-filestream-reader-options.asciidoc, filebeat/harvester/util.go
This PR is the code resolution of https://github.com/elastic/beats/issues/35984 issue.
1. It updates filebeat hints autodiscover config and the proposed filebeat k8s manifest(`filebeat-kubernetes.yml`) to use `filestream` input instead of `container` input for the `hints.default_config`
2. It allows to continue to use the same co.elastic.logs/* hints inside pods' annotations by
- mapping `co.elastic.logs/json*` hints to the ndjson parser in case of filestream.
- mapping `co.elastic.logs/multiline*` hints to the multiline parser in case of filestream.
User can still choose `container` input in `hints.default_config`. Everything will work as they used to in that case.
User has the following filebeat.yml configuration with hints autodiscover enabled and filestream set as hints.default_config …
=> Use filestream input as default for hints autodiscover. 

CHANGELOG.next.asciidoc, libbeat/cmd/instance/beat_test.go, libbeat/docs/queueconfig.asciidoc, libbeat/outputs/elasticsearch/config.go, libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc, libbeat/publisher/queue/memqueue/config.go
Apply the remaining config defaults changes in https://github.com/elastic/ingest-dev/issues/2399, following the conclusion of the benchmark tests of the new values under varying input loads. Full discussion of the changes and associated benchmarks are in that issue. All changes are neutral or positive on all tests, both individually and in combination. The `bulk_max_size` change in particular gives a significant reduction in CPU use, while the timeout changes reduce average connection count for many use cases.
The full changes from this PR are:
Queue:
- `queue.mem.events`: `4096` -> `3200`
- `queue.mem.flush.min_events`: `2048` -> `1600`
- `queue.mem.flush.timeout`: `1s` -> `10s`
ES output:
- `output.elasticsearch.bulk_max_size`: `50` -> `1600`
- …
=> Update queue / ES connection defaults

x-pack/metricbeat/module/gcp/billing/billing.go
Add an error message when the metricset finds no tables.
Not finding any dataset > table is an error state for this metricset. It can happen because the user made a mistake in the configuration file or the service account lacks the needed permissions [^1].
Regardless of the origin, it's a condition that we should report to the user and give hints for troubleshooting.
- Closes #36687
[^1]: The API to list the datasets returns an empty list an no error if the service account does not have enough permissions. 
[^2]: I don't think this is worth mentioning in a changelog.
=> [GCP] [Billing] Log an error message when the metricset finds no tables

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6746879203
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.10.5-952c31ce-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.10.5-952c31ce

.ci/packaging.groovy, Jenkinsfile, dev-tools/dependencies-report, dev-tools/packaging/packages.yml, dev-tools/packaging/templates/docker/Dockerfile.tmpl, dev-tools/packaging/templates/ironbank/auditbeat/Dockerfile, dev-tools/packaging/templates/ironbank/auditbeat/hardening_manifest.yaml, dev-tools/packaging/templates/ironbank/filebeat/Dockerfile, dev-tools/packaging/templates/ironbank/filebeat/hardening_manifest.yaml, dev-tools/packaging/templates/ironbank/heartbeat/Dockerfile, dev-tools/packaging/templates/ironbank/heartbeat/hardening_manifest.yaml, dev-tools/packaging/templates/ironbank/metricbeat/Dockerfile, dev-tools/packaging/templates/ironbank/metricbeat/hardening_manifest.yaml, dev-tools/packaging/templates/ironbank/packetbeat/Dockerfile, dev-tools/packaging/templates/ironbank/packetbeat/hardening_manifest.yaml, x-pack/heartbeat/ironbank/Makefile
> ⚠️ when merged then there are some changes required in the Unified Release, there is already an open PR, and a link to this one should be visible within this PR. Backports are also required. This is a chicken/egg, so DRA will fail until changes are in both systems.
https://github.com/elastic/beats/pull/36797 partially changed the `ubi` version to `ubi9` but there were some other changes required in the packaging itself and the base docker images.
-
=> ironbank: move to ubi9

x-pack/functionbeat/docs/overview.asciidoc
As part of deprecating the Functionbeat documentation we should add a notice referring users to the Elasticsearch Service Forwarder.
Rel: https://github.com/elastic/ingest-docs/issues/608
---
=> Mark Functionbeat documentation as deprecated; point to ESF docs

libbeat/docs/queueconfig.asciidoc, libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc, libbeat/outputs/logstash/docs/logstash.asciidoc, libbeat/outputs/redis/docs/redis.asciidoc
Update the Beats documentation to more clearly explain how `flush.min_events` works and how it interacts with the output's `bulk_max_size` parameter.
=> Clarify the role of flush.min_events and bulk_max_size in docs

libbeat/docs/shared-docker.asciidoc
Docker install docs should include volume mount for the registry. See issue for details.
Closes: #22586
---
=> Update Docker install docs with volume mount for registry files

libbeat/docs/shared-docker.asciidoc
Fixes a typo that I introduced in https://github.com/elastic/beats/pull/37043
=> Fix typo in Docker registry volume mount step

CHANGELOG.next.asciidoc, heartbeat/beater/heartbeat.go, heartbeat/beater/heartbeat_test.go
Closes https://github.com/elastic/beats/issues/36676
Decreases the ES default timeout (which is 90s) to 10s for the load monitor state requests. Please, see the issue for additional details.
**First:**
To reproduce the timeout when loading the monitor state, I created a Node.js server with "slow-response" endpoints:
```
const app3 = express()
const port3 = 3005
app3.use(cors())
app3.use(express.static('./'))
app3.get("*", (req, res) => {
setTimeout(() => {
res.end("hello fake ES")
}, 45000)
})
app3.post("*", (req, res) => {
setTimeout(() => {
res.end("hello fake ES")
}, 45000)
})
app3.listen(port3, () => {
console.log(`Example app listening at http://localhost:${port3}`)
});
```
**Second:**
I added these two lines at the very beginning of …
=> [Heartbeat] Decreases the ES default timeout to 10 for the load monitor state requests

libbeat/docs/getting-started.asciidoc
This removes the Functionbeat entry from the [Get started with Beats](https://www.elastic.co/guide/en/beats/libbeat/current/getting-started.html) page. This is part of deprecating the Functionbeat docs in favour of Elastic Serverless Forwarder.
Rel: https://github.com/elastic/ingest-docs/issues/608
=> Remove Functionbeat from 'Get started with Beats'

auditbeat/helper/hasher/hasher_test.go, auditbeat/module/auditd/audit_linux_test.go, auditbeat/module/auditd/config_test.go, auditbeat/module/auditd/golden_files_test.go, auditbeat/module/file_integrity/event_test.go, auditbeat/module/file_integrity/eventreader_test.go, auditbeat/module/file_integrity/fileinfo_test.go, auditbeat/module/file_integrity/fileinfo_windows_test.go, auditbeat/module/file_integrity/metricset_test.go, auditbeat/module/file_integrity/mime_test.go, auditbeat/module/file_integrity/monitor/monitor_test.go, auditbeat/module/file_integrity/scanner_test.go, auditbeat/module/file_integrity/security_windows_test.go, auditbeat/testing/setup.go
As per https://pkg.go.dev/io/ioutil, packages `io` and `os` should be preferred to `io/ioutil`
=> [auditbeat] replace deprecated io/ioutil package

CHANGELOG.next.asciidoc, x-pack/filebeat/input/cel/config.go, x-pack/filebeat/input/cel/input.go, x-pack/filebeat/input/internal/httplog/roundtripper.go
Emit a previous transaction ID before starting CEL evaluation and the final ID after completing the work. Also write transaction IDs to CEL debug log call if available.
Run `go test -v -run TestInput/tracer_filename_sanitization` in the cel package to see transaction IDs in the log.
- Closes #37064
=> x-pack/filebeat/input/cel: log transaction ID in CEL evaluations

CHANGELOG.next.asciidoc, packetbeat/docs/protocol-metrics-packetbeat.asciidoc, packetbeat/protos/tcp/tcp.go
=> packetbeat/protos/tcp: add metrics for TCP header flags

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-http-endpoint.asciidoc, x-pack/filebeat/input/http_endpoint/.gitignore, x-pack/filebeat/input/http_endpoint/config.go, x-pack/filebeat/input/http_endpoint/handler.go, x-pack/filebeat/input/http_endpoint/handler_test.go, x-pack/filebeat/input/http_endpoint/input.go, x-pack/filebeat/input/http_endpoint/validate.go, x-pack/filebeat/input/internal/httplog/roundtripper.go
See title.
Run `go test -log-traces` in x-pack/filebeat/input/http_endpoint` and then check the resulting ndjson files in the trace_logs directory.
- Closes #36951
- Depends #36956
=> x-pack/filebeat/input/http_endpoint: add support for request trace logging

CHANGELOG-developer.next.asciidoc, packetbeat/beater/processor.go, packetbeat/protos/protos.go, packetbeat/sniffer/sniffer.go
Previously the protocols association was held in a *protocols.ProtocolStruct in
common for all interfaces. This prevented individual interfaces that were only
associated with a subset of the protocols that were being captured from working
specifically on that subset. The new code moves the construction of the protocols
sets into setupSniffer where they are associated with the interface that will be
capturing them. They are then assigned to child sniffers in sniffer.New based on
the interface.
This change has no effect on the behaviour of packetbeat as it stands as configs
from packetbeat and from agent are only able to express the existence of a single
interface. Changes to configuration format/shape will enable multiple interfaces
to be enabled in packetbeat and within a single agent …
=> packetbeat/{beater,protos,sniffer}: allow assignment of protocols to interfaces

CHANGELOG.next.asciidoc, x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/okta.go
- Ref elastic/integrations#8468
=> x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta: handle empty responses gracefully

CHANGELOG.next.asciidoc, libbeat/publisher/queue/memqueue/produce.go, libbeat/publisher/queue/memqueue/queue_test.go
There was a case when openState.publish could get stuck and ignore its shutdown signal, effectively preventing a Beat (confirmed with Filebeat) from gracefully terminating.
This commit fixes this by ensuring every channel read/write also checks for the shutdown signal.
1. Create a server that will reply with logs. I used [my fork from flog](https://github.com/belimawr/flog)
Build/install and run with `flog -t http -f json`, this will start an HTTP server on `:3000`
2. Build Filebeat from the `x-pack` folder
4. Use the following `filebeat.yml`
<details><summary>filebeat.yml</summary>
<p>
```yaml
- type: …
```
=> Fix memqueue getting stuck on shutdown

CHANGELOG.next.asciidoc, x-pack/filebeat/input/http_endpoint/gzip.go
See title.
- Ref https://github.com/elastic/beats/pull/36957#discussion_r1390288513
=> x-pack/filebeat/input/http_endpoint: ensure request body is closed when content is gzipped

metricbeat/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
Merge only after the release of 8.11.1.
=> [Release] Update test environments for 8.11.2

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
Prepare Changelog for 7.17.15.
=> docs: Prepare Changelog for 7.17.15

libbeat/docs/howto/change-index-name.asciidoc
This adds a correction to the "[Change the index name](https://www.elastic.co/guide/en/beats/filebeat/current/change-index-name.html)" docs page.
Closes: #37117 
---
**Original:**
---
**Fixed by this PR:**
=> Update example command to change an index name

CHANGELOG.next.asciidoc, Jenkinsfile, NOTICE.txt, go.mod, go.sum, metricbeat/module/system/test_system.py
Update elastic-agent-system-metrics to v0.8.1 to enable collecting
memory and CPU metrics from privileged process on Windows.
Fix python test to ensure the `cmdLine` is found in at least one
process instead of them all because we cannot fetch the `cmdLine` from
privileged process on Windows.
1. Install Elastic-Agent with Elastic-Defend integration enabled
2. Run Metricbeat (from this PR) as administrator with process metrics enabled
3. Ensure events from `elastic-endpoint.exe` contain CPU …
=> Update elastic-agent-system-metrics to v0.8.1

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-gcs.asciidoc, x-pack/filebeat/input/gcs/input.go
- Enhancement
- Docs
Made GCS input GA and updated the docs as necessary.
- Relates https://github.com/elastic/integrations/issues/8157
=> [filebeat][GCS] - Made input GA and updated the docs accordingly

dev-tools/packaging/packages.yml, dev-tools/packaging/templates/ironbank/auditbeat/Dockerfile, dev-tools/packaging/templates/ironbank/auditbeat/hardening_manifest.yaml, dev-tools/packaging/templates/ironbank/filebeat/Dockerfile, dev-tools/packaging/templates/ironbank/filebeat/hardening_manifest.yaml, dev-tools/packaging/templates/ironbank/heartbeat/Dockerfile, dev-tools/packaging/templates/ironbank/heartbeat/hardening_manifest.yaml, dev-tools/packaging/templates/ironbank/metricbeat/Dockerfile, dev-tools/packaging/templates/ironbank/metricbeat/hardening_manifest.yaml, dev-tools/packaging/templates/ironbank/packetbeat/Dockerfile, dev-tools/packaging/templates/ironbank/packetbeat/hardening_manifest.yaml
Bump the `ubi:9` version to `9.3` as requested
-
=> ironbank: use ubi:9.3

CHANGELOG.next.asciidoc, NOTICE.txt, go.mod, go.sum
upgrade elastic-agent-system-metrics to v0.8.2
This is to fix a memory leak on Windows platform where process snapshots were not being freed.
1. Install metricbeat 8.11.0 on Windows, collect process metrics
2. notice memory consumption continues to climb (~30 min is required to see) in Task Manager
3. rebuild with this PR
4. test again, memory consumption will go up and down
- Closes #37142
=> upgrade elastic-agent-system-metrics to v0.8.2

CHANGELOG.next.asciidoc, x-pack/filebeat/input/cel/input.go, x-pack/filebeat/input/cel/input_test.go
The retryablehttp.Client will return an error based on the ErrorHandler field when the number of requests exceeds the maximum configuration. In the case that the field is nil, this is a non-nil error that causes issues with some APIs and does not allow the CEL code to evaluate the HTTP response status. So add a retryablehttp.ErrorHandler that will log the failure, but return the response unaltered and a nil error.
-
=> x-pack/filebeat/input/cel: suppress and log max http request retry errors

CHANGELOG.next.asciidoc, auditbeat/docs/modules/auditd.asciidoc, auditbeat/module/auditd/_meta/docs.asciidoc
The documentation incorrectly states that socket selection of multicast that cannot be satisfied will fall back to unicast. So remove this claim.
- Fixes #37174
=> auditbeat/docs/modules: remove incorrect advice in documentation

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-cel.asciidoc, x-pack/filebeat/input/cel/input.go
The logic for want_more is that there must be at least one event
published for a true want_more field to result in an additional loop of
evaluation. This condition can currently be true in the case that the
evaluation fails. In the failure case it is likely that we do not want
to re-eval, so set want_more to false in this situation.
-
=> x-pack/filebeat/input/cel: do not request more work after an eval failure

x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
Copy-pasting these examples would lead to `step: null`.
=> Fix incorrect indentation in YAML examples

metricbeat/module/kibana/cluster_actions/data.go, metricbeat/module/kibana/cluster_rules/data.go, metricbeat/module/kibana/node_actions/data.go, metricbeat/module/kibana/node_rules/data.go, metricbeat/module/kibana/stats/data.go
This change ensures all kibana metricsets set a unique `service.address` value. This is necessary for TSDB migration as we want to use this field as a dimension
- ingest kibana data
```
- module: kibana
xpack.enabled: true
period: 10s
hosts: ["http://localhost:5601"]
username: "elastic"
password: "changeme"
```
- verify kibana metricsets publish the same unique value for `service.address`
- Closes https://github.com/elastic/beats/issues/37167
=> [kibana] pass unique `service.address` value

.ci/packaging.groovy, Jenkinsfile, dev-tools/packaging/packages.yml
> https://github.com/elastic/elastic-agent/pull/3790 will need to be merged when this one is merged to help with the changes in the DRA (elastic/infra)
Rename docker images from `ubi9` to `ubi` from `8.12` onwards and `7.17.16`
-
=> ironbank: rename ubi9 to ubi image

CHANGELOG.next.asciidoc, x-pack/auditbeat/module/system/socket/guess/creds.go, x-pack/auditbeat/seccomp_linux.go
In kernel commit [981ee95c](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit?h=981ee95cc1f5905ae4936b0dd501085909cdc14f) (into v6.3) calls to access_override_creds
were gated behind a test for the requirement for the call. This change
results in non-execution of prepare_creds and so failure of the guess.
An alternative has been identified that does not exhibit this behaviour,
mq_open which calls dentry_open with creds in the third parameter. So
replace the sys_access trigger with sys_mq_open and add the probe to
dentry_open with P3 for the address.
- Fixes #36905
=> x-pack/auditbeat/module/socket/guess: fix creds trigger for newer kernels

CHANGELOG.next.asciidoc, x-pack/metricbeat/module/azure/azure.go, x-pack/metricbeat/module/azure/client.go, x-pack/metricbeat/module/azure/client_test.go
Due to the use of `time.Now()` to set the value of the reference time used to decide if collect the value of the metric, the metricset may skip a metric collection.
Made two changes to the Azure Monitor metricset:
- moved `referenceTime` into the `Fetch()` and truncated its value to seconds to have a more predictable reference time for comparison.
- Updated the `MetricRegistry.NeedsUpdate()` method to use `referenceTime` vs. using "now" to compare with the time grain duration.
Current tests seem fine, with PT5M time grain and collection periods of 300s and 60s.
I am also adding some structured logging messages to track registry decisions at the debug log level.
Here's how to parse the structured logs to get a nice table view:
```shell
$ cat metricbeat.log.json | grep "MetricRegistry" | jq …
```
=> Fix unintended skip in metric collection on Azure Monitor

libbeat/docs/command-reference.asciidoc
This updates the Filebeat [command reference](https://www.elastic.co/guide/en/beats/filebeat/current/command-line-options.html) page as shown:
Closes: #31416
=> [DOCS] Note that '--once' is not supported with filestream input

CHANGELOG.next.asciidoc, NOTICE.txt, go.mod, go.sum
Bump the following package versions to patch the Consumption SDK 1.1.0:
- Bump `armconsumption` package version from 1.0.0+patch to 1.1.0+patch
- Bump `azcore` package version from 1.4.0 to 1.9.0 to use the URL encoder helper used in the Azure SDK
The Consumption SDK does not correctly handle query parameters in the 'next link' when the dataset in Azure requires pagination. See https://github.com/elastic/integrations/issues/7478#issuecomment-1819391736 for more details.
We manage the [patches](https://github.com/elastic/azure-sdk-for-go/commits/sdk/resourcemanager/consumption/armconsumption/v1.1.0-elastic) to the Azure SDK for Go in the repository fork. To learn more about the patches and the fork, see https://github.com/elastic/beats/issues/37151
Our Azure accounts does not have enough …
=> [Azure] [Billing] Switch to Consumption API 1.1.0 with patches

libbeat/outputs/elasticsearch/client.go
This commit fixes a warn log entry that was missing the section stating that log level debug contains more detailed information like the raw event and cause for the error.
Follow the steps described on https://github.com/elastic/beats/pull/37229
~~## Logs~~
=> Fix log entry

metricbeat/helper/kubernetes/ktest/ktest.go
Please explain:
- WHAT: Fix the lint error on pre allocating the variables `files`.
- WHY:  I forgot to address [this comment](https://github.com/elastic/beats/pull/37240#discussion_r1415073493) on the related PR. This is the fix for that.
=> [Kubernetes Test] Fix lint error on ktest.go

.mergify.yml
Merge as soon as 8.12 branch was created. Auto-merge is not yet supported, see https://github.com/Mergifyio/mergify-engine/discussions/2821
=> backport: Add 8.12 branch

filebeat/input/filestream/input_test.go
Now we can quickly compare performance metrics when we make changes to the filestream implementation without running the whole Filebeat.
```sh
go test -run=none -bench='BenchmarkFilestream/filestream_default_throughput.*' -benchmem -benchtime=100x
```
On my machine I've got the following results:
```
BenchmarkFilestream/filestream_default_throughput-10
100          10703028 ns/op        13576607 B/op     181225 allocs/op
```
```sh
cd …
```
=> Add benchmark for filestream input

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 8.11.2

libbeat/processors/script/javascript/session.go
Remove event fields from error log when the script processor panics. This is an unlikely situation to happen as the Javascript runtime we use should not panic on any error while executing Javascript code, hence the event fields are just removed.
~~## Logs~~
=> Remove event fields from error log.

filebeat/input/filestream/copytruncate_prospector.go, filebeat/input/filestream/environment_test.go, filebeat/input/filestream/fswatch.go, filebeat/input/filestream/fswatch_test.go, filebeat/input/filestream/identifier.go, filebeat/input/filestream/identifier_inode_deviceid.go, filebeat/input/filestream/identifier_test.go, filebeat/input/filestream/internal/input-logfile/fswatch.go, filebeat/input/filestream/logger.go, filebeat/input/filestream/prospector_test.go, libbeat/common/file/file_info.go, libbeat/common/file/file_other.go, libbeat/common/file/file_windows.go, libbeat/reader/readfile/fs_metafields_other.go, libbeat/reader/readfile/metafields.go, libbeat/reader/readfile/metafields_other_test.go, libbeat/reader/readfile/metafields_windows_test.go
Adding additional file system metadata caused additional system calls that degraded the file reading performance.
Run this on `main` and this branch to compare:
```sh
go test -v -run=none -bench='BenchmarkFilestream/default.*' -benchmem -benchtime=100x -cpuprofile=main-cpu-profile.bin -memprofile=main-mem-profile.bin
```
In my case the results are:
```
BenchmarkFilestream/filestream_default_throughput-8
100          16212108 ns/op        13964860 B/op          230522 allocs/op
BenchmarkFilestream/filestream_default_throughput-8
100          13216628 ns/op        13805361 B/op          200519 allocs/op
```
The CPU …
=> Fix the performance regression when ingesting files on Windows

heartbeat/beater/heartbeat.go, x-pack/heartbeat/monitors/browser/source/project.go
+ Fix the formatting of the logs on HB for project monitors. 
```
Running %s in %s/usr/share/heartbeat/.node/node/bin/npm install --no-audit --no-update-notifier --no-fund --package-lock=false --progress=false/tmp/elastic-synthetics-unzip-4066455738
```
=> fix: format log message correctly for heartbeat

CHANGELOG.asciidoc
This PR documents the Windows-only memory leak affecting all Beats when collecting memory-related metrics.  The wording for the note is taken from https://www.elastic.co/guide/en/fleet/8.11/release-notes-8.11.0.html.
=> [Docs] Document memory leak in `8.11.0` and `8.11.1` release notes

metricbeat/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
This updates the test environments to next minor release which is 8.13.0.
=> [Release] Update test environment to 8.13.0
