elastic/beats

testing/environments/snapshot.yml
<Actions>
<action id="5ddffb4b28effae486e933ec577c536edfa7fc91cb13a8a5f20634b8f3ab52ab">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.9.0-911df49b

x-pack/filebeat/docs/inputs/input-cel.asciidoc
Makes use of asciidoc attributes to simplify updates of the CEL input documentation.
This reduces code touch when mito is updated.
Direct link to docs build (ephemeral) https://beats_36139.docs-preview.app.elstc.co/guide/en/beats/filebeat/master/filebeat-input-cel.html
-
=> x-pack/filebeat/docs/inputs/cel: use attributes for mito doc links

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 7.17.12.
=> docs: update docs versions 7.17.12

CHANGELOG.next.asciidoc, NOTICE.txt, go.mod, go.sum, x-pack/filebeat/docs/inputs/input-cel.asciidoc
Updates the CEL input extension library to v1.5.0.
This brings performance improvements and a new [object construction helper](https://pkg.go.dev/github.com/elastic/mito@v1.5.0/lib#hdr-Zip).
-
=> x-pack/filebeat/input/cel: update mito version to v1.5.0

x-pack/filebeat/docs/inputs/input-cel.asciidoc
Adds an example for an API with a non-JSON response.
Help users understand the input.
-
=> x-pack/filebeat/docs/inputs/cel: add a text API example

testing/environments/snapshot.yml
<Actions>
<action id="12e239b9c3c652cb99557d8970dc7f730402e769dec86281b3fbf5fd17d325f6">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.9.0-6b15bb32

metricbeat/module/postgresql/statement/statement_integration_test.go
Relates to https://github.com/elastic/beats/issues/35995
This test is currently flaky and needs to be fixed.
-
=> Skip TestFetch as Flaky

testing/environments/snapshot.yml
<Actions>
<action id="6d68fe635e19a3748e1f0edcd228cc4a5a35b03220bcedf5abbc7c69c0bbd3e2">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.9.1-44a814f0

testing/environments/snapshot.yml
<Actions>
<action id="51718d605d16209e21e6112485cffabfe9a0833a7ee3ee215229826209498a35">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.9.1-877ad540

testing/environments/snapshot.yml
<Actions>
<action id="64a18c711e365b7463da1de4c2c00f7ac966917a903e61ccb5cfb64781890c69">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 7.17.13-7f46ddb9

testing/environments/snapshot.yml
<Actions>
<action id="9311a923dffdbc7c5a0decdaac26096f09e86f40fda5591c10a9f998e347d23d">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 7.17.13-f0591b59

testing/environments/snapshot.yml
<Actions>
<action id="99585f3dc644bf62d507a3087757d7feb3e4e9dd073c77b42452ca5358fe3daf">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.9.1-40dca293

testing/environments/snapshot.yml
<Actions>
<action id="0126af359518d62125f0b1cf3727ed6e634e33cb9a52c04e424b3546397be900">
</details>
</action>
<action id="117f2a5f55269c91e7acc7a90dbfe13324ba2d1d97f3be7096163cf313b5e007">
</details>
</action>
<action …
=> [updatecli] update elastic stack version for testing 8.10.0-ed2e01b4

x-pack/filebeat/processors/decode_cef/docs/decode_cef.asciidoc
Document the source material used to implement the `decode_cef` processor and add an example CEF message.
=> x-pack/filebeat/processors/decode_cef - Improve docs

testing/environments/snapshot.yml
<Actions>
<action id="6aa12307b984d4d049c8763d60051655d41fa75f5df8683b0b826ca9b142aa26">
</details>
</action>
<action id="d38d66ce0bfaff6509f1099befc3042a7b0c8d6ece7cb6c6e7d7e45f8f3a5c2c">
</details>
</action>
</Actions>
---
<table>
<tr>
</td> …
=> [updatecli] update elastic stack version for testing 8.9.1-6c14de65

heartbeat/Jenkinsfile.yml, x-pack/heartbeat/Jenkinsfile.yml
Enable RHEL 9 stage on CI for Heartbeat.
=> [Heartbeat] enable rhel9 on ci 

testing/environments/snapshot.yml
<Actions>
<action id="e7815c61f7f84cf143f0bb1c51c2907cafe6b33bf32ee9afeefcff932755bebd">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.9.1-d46182aa

.ci/packaging.groovy
As we removed our old e2e tests solution, we should remove this step from packaging.
-
=> Removing e2e tests from packaging as it has been removed

x-pack/filebeat/input/cel/input.go
There appears to be a test flakiness in the cel package tests that cause the HTTP-
dependent tests to fail after the retry_failure test, with url is unreachable. To
help identify the cause of the failure, improve the error reporting from the Test
method which is the path that is failing.
-
=> x-pack/filebeat/input/cel: improve error reporting from Test run

CHANGELOG.next.asciidoc, dev-tools/packaging/files/linux/systemd-daemon-reload.sh, dev-tools/packaging/packages.yml, dev-tools/packaging/templates/deb/postinstall.sh.tmpl
Reverts elastic/beats#36201 as @belimawr is not available to investigation why it's causing some failure: https://github.com/elastic/beats/issues/34089
=> Revert "Restart Beat after install on deb package"

testing/environments/snapshot.yml
<Actions>
<action id="a4641f403c363e63ec4508c8ee530d6b86a465b96d17f6ce86ff45e3ae9d2b22">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.9.1-ef89186d

CHANGELOG.next.asciidoc, dev-tools/packaging/templates/rpm/elastic-agent.init.sh.tmpl, dev-tools/packaging/templates/rpm/init.sh.tmpl
On RHEL9, the functions script is no longer present resulting in failure when init-script based service management commands are used. We still support at least one distribution that provides init-script based service management, so we need to retain these scripts, but provide a warning to users on systems where these will not work pointing to the new approach.
Improve UX.
- For #35708
=> dev-tools/packaging/templates/rpm: add warning when /etc/rc.d/init.d/functions is missing

testing/environments/snapshot.yml
<Actions>
<action id="8428ce3eab8946cc9ab32aaf3ba7e9241ec5f35ee038ebdee2c45b08a63b577e">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.9.1-afb401d4

testing/environments/snapshot.yml
<Actions>
<action id="e24a99187c5e3f27a2f005f5637f57052fbfe5a97c61d19ba7cbf5d71b8197f8">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.9.1-975bdf3e

NOTICE.txt, go.mod, go.sum
So, we can use new GOMAXPROCS settings,
for details see https://github.com/elastic/elastic-agent-client/pull/83
- Relates https://github.com/elastic/elastic-agent-client/pull/83
- Relates https://github.com/elastic/elastic-agent/pull/3179
=> Update elastic-agent-client to 7.3.0

filebeat/input/filestream/fswatch_test.go
The values are coming from a map, so the order is not deterministic. This change sorts the events based on their filename and compares them afterwards.
- Closes #36292
=> Fix flaky fswatch test due to non-deterministic order

testing/environments/snapshot.yml
<Actions>
<action id="7f59da05aba14121032e2ce76e5cf6fa812c00afe82767ade6dcbe4d42a8cc0c">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 7.17.13-1b4d0dba

testing/environments/snapshot.yml
<Actions>
<action id="f44cbcc62ac83b27d11deaf1be12f11a242e12ea867299da015f0ac36c44c330">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.9.1-456ef5ad

testing/environments/snapshot.yml
<Actions>
<action id="409f520519f4ff5669659066232badcd1fbf72cbf89aa5ba3d4547c20e410b88">
</details>
</action>
<action id="7893232eba15fde05ce73f6c036537070ff0fb4d7180da41d9c2b14c4031fded">
</details>
</action>
<action …
=> [updatecli] update elastic stack version for testing 8.10.0-0aabd193

winlogbeat/eventlog/wineventlog.go, winlogbeat/eventlog/wineventlog_experimental.go
Bookmarks will be stale for forwarded events so don't set up the subscription to fail for forwarded events.
- For #36020
=> winlogbeat/sys/wineventlog: don't use strict mode for forwarded events

testing/environments/snapshot.yml
<Actions>
<action id="1c6d7bdb0f6e03f4110367d613ed989906cad1e703310dae5d10a703c18dae47">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.9.1-162a595c

testing/environments/snapshot.yml
<Actions>
<action id="4a9f9bf7161f53a0322dc159c7c992679b024578da928757b653e265f2dd213c">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 7.17.13-7c96d528

testing/environments/snapshot.yml
<Actions>
<action id="03b278ccdad5d15416cdda8ee168180909fda168944d0fcab9038d1eb7a2d245">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.9.1-39dfdc3b

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Update the docs for next minor 8.11.0.
Merge after the release branch for 8.9.2 is created.
=> [Release] Update docs for the 8.11.0 release

auditbeat/module/file_integrity/event.go, auditbeat/module/file_integrity/fileinfo_posix.go, auditbeat/module/file_integrity/flatbuffers.go, auditbeat/module/file_integrity/schema.fbs, auditbeat/module/file_integrity/schema/Metadata.go
When encoded as a string, the logic within the module works correctly, but the logged data is passed through the JSON serialisation logic which will ensure that all the unicode code points are valid. It is not necessarily true that all the bytes in the data for this field are valid (almost guaranteed not to be given that invalid qualifiers are represented by 0xffffffff).
So use a []byte to hold this data. This has the additional advantage that the representation in the logs will be almost exactly what getfattr shows for this; the only difference being a "0s" prefix added by getfattr.
- For #36310.
=> auditbeat/module/file_integrity: encode POSIXACLAccess as []byte

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 8.9.1

testing/environments/snapshot.yml
<Actions>
<action id="2eb98ef7b2e72663be60433654a3b639126686cfcac366cb54809b30122c80f4">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.9.1-f33bc992

testing/environments/snapshot.yml
<Actions>
<action id="4fb40abd1df6cbae0a984c87d722ad436c51eaa44c81adddb869dba0fa949c76">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 7.17.13-dde9c3ba

testing/environments/snapshot.yml
<Actions>
<action id="4cb1d5f093a510c220ac7ab3b713113c09269fa67c2845bf7e579e11d44bda41">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 7.17.13-23b69bf5

testing/environments/snapshot.yml
<Actions>
<action id="3102e7987bcb5691d203b9841d909608d1ec8d4a9c887efb55fb1a75137eb7ff">
</details>
</action>
<action id="765df94134c48f8a4557e5e4e1a48b9658eafa9e7216c3280936508f4371ba9c">
</details>
</action>
</Actions>
---
<table>
<tr>
</td> …
=> [updatecli] update elastic stack version for testing 8.9.2-a6da2234

testing/environments/snapshot.yml
<Actions>
<action id="3cb7d73ab81abd417eb6b6cf4ecfbdd8d9f703fec3b11f2366bb337a93ab2294">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 7.17.13-7e207efe

testing/environments/snapshot.yml
<Actions>
<action id="b707e9d970ebe2fdbb10d4ccb5cee09df5f18ff7201227fc7d87360ba42a6c96">
</details>
</action>
<action id="f8380e6e1894337d95f6214eb89881c55958e1fd5327290e4d2cdf49dadc09e6">
</details>
</action>
</Actions>
---
<table>
<tr>
</td> …
=> [updatecli] update elastic stack version for testing 8.10.0-6bf877e8

testing/environments/snapshot.yml
<Actions>
<action id="181188c91395d8436941ecdcf24f6f2bd0de0841b181700b1aef97bbfcafcba7">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.10.0-322e3ef7

testing/environments/snapshot.yml
<Actions>
<action id="a3f00e6c53a82e8e280d9fb6b9adfcc57461d800c8fd757509a5aaf09b84fc76">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.9.2-8eb52857

testing/environments/snapshot.yml
<Actions>
<action id="ac5514337ccdc10ab133f371f1b75d5f16a29968d9d27f324ca779bb4c37bcfa">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.9.2-1a569074

testing/environments/snapshot.yml
<Actions>
<action id="b17b64f37a51a887d1d7ea75287b3563a6777d1b45d462b927be6c99cabee838">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.10.0-edf31268

testing/environments/snapshot.yml
<Actions>
<action id="e2040b39c4a396471c8a574988d1cbd77f980eb3ccf00689bc325b2ca991b00f">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 7.17.13-f0d1f9e1

testing/environments/snapshot.yml
<Actions>
<action id="2a4043b30e8f92532b4c40edf3cb7fff5b4383a5b5044d3e9a03337a545b2867">
</details>
</action>
<action id="54a043b7bdbb51698ab9e65828119bd39dad8fdd614bab65c2a61c2034d87b08">
</details>
</action>
<action …
=> [updatecli] update elastic stack version for testing 8.11.0-76b03348

.ci/bump-golang.yml, .devcontainer/devcontainer.json
Adds `.devcontainer`, a standard way to describe development containers. See the [VSCode](https://code.visualstudio.com/docs/devcontainers/containers) documentation and the [.devcontainer spec](https://containers.dev/) for more info. You can use devcontainers with other IDEs like `intellij`, see [supported tools](https://containers.dev/supporting) for more info.  If you haven't used dev containers before, they're simple to get started. If this file is present in your container VSCode will ask you on opening the project whether you want to use the container. If so, it will build the container and you can go from there.
This file can be ignored by those who wish to develop on their native system, but is highly useful for those (like myself) who occasionally:
1. Need to develop linux …
=> Add .devcontainer

NOTICE.txt, go.mod, go.sum
Upgrade elastic-agent-libs to v0.3.13
~~## Checklist~~
~~## Logs~~
=> Upgrade elastic-agent-libs to v0.3.13

testing/environments/snapshot.yml
<Actions>
<action id="1bd090f7dd24129c9fb64c89ee82f6c77a3e4feafc7724f0a56053ff65b8a870">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.9.2-fe004c3f

testing/environments/snapshot.yml
<Actions>
<action id="c976ae0679bb632b098b120979e241896565eeb383e653719b86baa70ec27912">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.11.0-ba1a8c0f

filebeat/input/internal/procnet/procnet_test.go
Copy/paste errors in test error messages are confusing, so fix them.
-
=> filebeat/input/internal/procnet: fix typos in test error messages

testing/environments/snapshot.yml
<Actions>
<action id="2f783f305b118f4e1005b84eec33c4aaf933c952b5f86bc897dda5ac9a2ad902">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.11.0-16180d4a

testing/environments/snapshot.yml
<Actions>
<action id="95f669a91b9834b3fefb582b0f464f609b9dff44f1774c4a607f3d38b1894d84">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.9.2-a804d52d

testing/environments/snapshot.yml
<Actions>
<action id="7a562ecb6995962b21b4a6fed4869f991387647a06ebfe9846e3374014e612a7">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 7.17.13-1c18dee3

testing/environments/snapshot.yml
<Actions>
<action id="25be53ca54928fa23d964f7fb559681cb3da2cbb263eaa94a3600f01ffbb5b20">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.10.0-e4344f1d

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 8.9.2.
=> docs: update docs versions 8.9.2

testing/environments/snapshot.yml
<Actions>
<action id="06c3f25e52f6fd16335cc930aafe5688c9e180c7f44c649278c8a2a088bee297">
<p>1 file(s) updated with &#34;$1:8.10.0-c5be8c13-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.10.0-c5be8c13

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 8.10.0

testing/environments/snapshot.yml
<Actions>
<action id="9b3771c985fa99accac2189c04a1b6010c3f096372a05613f37c2d9f299e29b7">
<p>1 file(s) updated with &#34;$1:8.10.0-516050d7-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.10.0-516050d7

testing/environments/snapshot.yml
<Actions>
<action id="968d531eef080bc80fcd405d8dba46f303ea4e4dbb051ccde84d8c1d4b3f404d">
<p>1 file(s) updated with &#34;$1:8.11.0-7dab12da-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 8.11.0-7dab12da

filebeat/input/filestream/fswatch_test.go
One of the TestFileWatcher substests expects to get two FS events, one
for each file it creates, however, at least on Windows, those events
can come on any order. This commit fixes the test by looking for any
of the events and ensuring we get only the two expected events.
~~## Checklist~~
This issue is caused by a race condition, so run the tests multiple times and make sure they all pass.
We only experienced issues on Windows, so it's better to test this PR on Windows. Also you might need to adjust the file path separator.
```shell
cd filebeat/input/filestream
go test -count=100 -run=TestFileWatcher
```
There should be no test failures failures.
- Fixes: https://github.com/elastic/beats/issues/36400
~~## …
=> Fix race condition on TestFileWatcher

testing/environments/snapshot.yml
<Actions>
<action id="aed52ab415d737d50a9aa33efe30f0e7ad3c9774e7a3f10542a50c5b4029a780">
<p>1 file(s) updated with &#34;$1:7.17.14-f6f6170a-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 7.17.14-f6f6170a

testing/environments/snapshot.yml
<Actions>
<action id="f1024ac0eefb1521ead38c82681e6476a13f87fb30bcc7dfca9a447d0ee52783">
<p>1 file(s) updated with &#34;$1:7.17.14-f1d9b80b-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 7.17.14-f1d9b80b

testing/environments/snapshot.yml
<Actions>
<action id="5fd5907671825f9113a616ac8eda0b69cf1baf918f754794f031f425f4a05e7c">
<p>1 file(s) updated with &#34;$1:8.11.0-f9ab12e0-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
<action id="7f75ee0801e061cb67f8fc586da6a738cbd203515b1256937cf01ffe0f3c3f93">
<p>1 file(s) updated with &#34;$1:8.11.0-58bca18d-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action> …
=> [updatecli] update elastic stack version for testing 8.11.0-2b227d89

dev-tools/packaging/templates/ironbank/elastic-agent/Dockerfile, dev-tools/packaging/templates/ironbank/elastic-agent/hardening_manifest.yaml
The backport didn't work since Elastic Agent is not anymore in 8.x
See https://repo1.dso.mil/dsop/elastic/beats/7.x/elastic-agent/-/commit/8d42a44163bd6c38de44565a2d75d016a9ac679f so this should avoid those changes to be done manually by the Ironbank team
-
=> ironbank: use ubi8:8.7 in ElasticAgent

testing/environments/snapshot.yml
<Actions>
<action id="122b9ebbce3563e4686b6fd2731719f415b00f06c6d9fe2fc921fc5c877fdb76">
<p>1 file(s) updated with &#34;$1:7.17.14-55a4d733-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
=> [updatecli] update elastic stack version for testing 7.17.14-55a4d733

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 8.10.2.
=> docs: update docs versions 8.10.2

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6275924725
---
<Actions>
<action id="b4c808fe79f1add18a385533441f6bc152d8e66631ed2c9e524d233a6b45f74f">
<p>1 file(s) updated with &#34;$1:7.17.14-ca136f74-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.14-ca136f74

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6301222277
---
<Actions>
<action id="0b6933740d32ac0c5cd1cbb1934446ca99d7eb1f85087238d1d255a3acf3aca7">
<p>1 file(s) updated with &#34;$1:8.10.3-aa09190a-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.10.3-aa09190a

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6301222277
---
<Actions>
<action id="6fc374112bed94897b1b1162baebfc09573e59cc3cfaaa16b040ad442bb14935">
<p>1 file(s) updated with &#34;$1:7.17.14-583a60c9-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.14-583a60c9

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6327822448
---
<Actions>
<action id="136f95254d2871c599e99da56bdcec85cd68a15cae6b8f9896f4011a58a48c88">
<p>1 file(s) updated with &#34;$1:7.17.14-ca772d6f-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
<action id="6c408ec5622f9b6b299e8bebc194c10ada3f0a753e120f94d6d9401aef29be42"> …
=> [updatecli] update elastic stack version for testing 7.17.14-061f74c6

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6327822448
---
<Actions>
<action id="7fa9391197a5c394c004f0375c1700ff15c8dc0a530acc79ec2db99db1955406">
<p>1 file(s) updated with &#34;$1:8.10.3-a4520544-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
<action id="c6d6ac5f0d063a17efdcd097fd6a4c3012cf49178334932c25d81dcd6dbb91d1"> …
=> [updatecli] update elastic stack version for testing 8.10.3-a4520544

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6327822448
---
<Actions>
<action id="102ae07e42e485558a6f18a68e0f82219b7459f456a0169d4bde3d087c97c535">
<p>1 file(s) updated with &#34;$1:8.11.0-b2ac6b4d-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
<action id="93ed68b0485a2dea39dd2293498a773228bef92b8b39cb6887ba82e4a50126e9"> …
=> [updatecli] update elastic stack version for testing 8.11.0-b2ac6b4d

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6340736195
---
<Actions>
<action id="f6e3e5bac2f9fc70bffd0518de508ab8a747eaee8eaf325c81655c0b421b2f9d">
<p>1 file(s) updated with &#34;$1:8.10.3-8e865fb7-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.10.3-8e865fb7

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6340736195
---
<Actions>
<action id="481833d88b73085247c047211dd1eaaa9936526b8948562e4cbf63e1edc17899">
<p>1 file(s) updated with &#34;$1:7.17.14-a1357ca2-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.14-a1357ca2

libbeat/processors/cache/config.go, libbeat/processors/cache/docs/cache.asciidoc
See title.
- For elastic/integrations#2816
=> libbeat/processors/cache: document capacity configuration

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6353419667
---
<Actions>
<action id="accc0bcf5deabfd2e7fd3d617eaec2caa4242b7b29ea287a371268450d2607c7">
<p>1 file(s) updated with &#34;$1:8.10.3-0a467303-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.10.3-0a467303

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6353419667
---
<Actions>
<action id="2248f649ee92bd3eea081d5f4255abfb4be3b9dfc009237d018877e97da14752">
<p>1 file(s) updated with &#34;$1:8.11.0-4d413233-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
<action id="2fce7f79681f152bf757cf191ee7afb4d1165639a4162d405f19bac8f33fc043"> …
=> [updatecli] update elastic stack version for testing 8.11.0-4d413233

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6381895570
---
<Actions>
<action id="a81fcc2326c7ef633b8122aae92335d7e1ff277563c3ca887fe03e421f7d029c">
<p>1 file(s) updated with &#34;$1:8.10.3-57d6bd70-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.10.3-57d6bd70

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6394830676
---
<Actions>
<action id="a101a9e336d72ff539dd12f6d6f960c8ea076f85872e8baedb452c39ff534d2f">
<p>1 file(s) updated with &#34;$1:8.10.3-75e0d7cb-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.10.3-75e0d7cb

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6394830676
---
<Actions>
<action id="17e8dd13427a660400c549b3a54da5823159191ca38fec49a601f2bf6e9dba95">
<p>1 file(s) updated with &#34;$1:7.17.14-78860399-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.14-78860399

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6394830676
---
<Actions>
<action id="b1e9a50be06b3638227def6778fbe2df7da11ca75d12b4b4d8f396ce87b768ad">
<p>1 file(s) updated with &#34;$1:8.11.0-75636e12-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
<action id="ce5afb0c563cf5cd87b1bbf113651d7a35ca2244a4a143d69b363085c0d95f28"> …
=> [updatecli] update elastic stack version for testing 8.11.0-4e7ff248

dev-tools/packaging/templates/ironbank/elastic-agent/Dockerfile, dev-tools/packaging/templates/ironbank/elastic-agent/hardening_manifest.yaml
=> Ironbank ubi update to 8.8

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6420872109
---
<Actions>
<action id="0e60948d6fe44af0550e2be4b43b623a489827669f64a2358486fe89ceb6eb02">
<p>1 file(s) updated with &#34;$1:8.10.3-42560206-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.10.3-42560206

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6420872109
---
<Actions>
<action id="4555229bf4d1f51ff20004f049a0c3ff07fdda2b19c1b81df03aab9e34d54656">
<p>1 file(s) updated with &#34;$1:7.17.14-89b2ef0f-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.14-89b2ef0f

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6420872109
---
<Actions>
<action id="0d19da247424ad23b2e72fb62f73a107b1924ca6f1df3ece0f6058ddb1cfcdf8">
<p>1 file(s) updated with &#34;$1:8.11.0-867cd584-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.0-867cd584

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6433300782
---
<Actions>
<action id="698b2c99bb59c7d5b3960f60660865216c24cb468164e8e3436dbfa960327dd9">
<p>1 file(s) updated with &#34;$1:8.10.3-17f9519a-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.10.3-17f9519a

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6433300782
---
<Actions>
<action id="e6b74be10a37007d468551702c1e07cf2e7767e54005f54e6a382d2a354ee34a">
<p>1 file(s) updated with &#34;$1:7.17.14-a522fb9c-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.14-a522fb9c

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6433300782
---
<Actions>
<action id="73f22134a2b7e2f3a1ee9d6837d4ce1802e8c50650bf3d37435d4e30a031aebc">
<p>1 file(s) updated with &#34;$1:8.11.0-dfefa400-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.0-dfefa400

CHANGELOG.next.asciidoc, filebeat/cmd/root.go
See title.
- For elastic/integrations#2816
=> filebeat/cmd: import cache processor

dev-tools/packaging/templates/ironbank/auditbeat/Dockerfile, dev-tools/packaging/templates/ironbank/auditbeat/hardening_manifest.yaml, dev-tools/packaging/templates/ironbank/filebeat/Dockerfile, dev-tools/packaging/templates/ironbank/filebeat/hardening_manifest.yaml, dev-tools/packaging/templates/ironbank/heartbeat/Dockerfile, dev-tools/packaging/templates/ironbank/heartbeat/hardening_manifest.yaml, dev-tools/packaging/templates/ironbank/metricbeat/Dockerfile, dev-tools/packaging/templates/ironbank/metricbeat/hardening_manifest.yaml, dev-tools/packaging/templates/ironbank/packetbeat/Dockerfile, dev-tools/packaging/templates/ironbank/packetbeat/hardening_manifest.yaml
=> Update Ironbank images with ubi 8.8

dev-tools/packaging/templates/ironbank/elastic-agent/Dockerfile, dev-tools/packaging/templates/ironbank/elastic-agent/hardening_manifest.yaml
=> update ubi version for base image

dev-tools/packaging/templates/ironbank/auditbeat/Dockerfile, dev-tools/packaging/templates/ironbank/auditbeat/hardening_manifest.yaml, dev-tools/packaging/templates/ironbank/filebeat/Dockerfile, dev-tools/packaging/templates/ironbank/filebeat/hardening_manifest.yaml, dev-tools/packaging/templates/ironbank/heartbeat/Dockerfile, dev-tools/packaging/templates/ironbank/heartbeat/hardening_manifest.yaml, dev-tools/packaging/templates/ironbank/metricbeat/Dockerfile, dev-tools/packaging/templates/ironbank/metricbeat/hardening_manifest.yaml, dev-tools/packaging/templates/ironbank/packetbeat/Dockerfile, dev-tools/packaging/templates/ironbank/packetbeat/hardening_manifest.yaml
Change ubi base image as per ironbank requirement
=> change base image to ubi 9.2

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6458415295
---
<Actions>
<action id="2b672f14aab3846f7fcf4f96692a0f6fa1bdbc5c6ddaa75e10ead08e5d0a8e0e">
<p>1 file(s) updated with &#34;$1:8.10.3-61debe57-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.10.3-61debe57

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 8.10.3

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 7.17.14.
=> docs: update docs versions 7.17.14

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 8.10.3.
=> docs: update docs versions 8.10.3

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6484404965
---
<Actions>
<action id="140a1f002243e119b6d00a71edd5541a519bb6819c1b830e79a9c97ab3527e89">
<p>1 file(s) updated with &#34;$1:8.11.0-4acbdbb1-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.0-4acbdbb1

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6484404965
---
<Actions>
<action id="4e95dbfc2e4c1277da33dec233c36956a7deae4d08bed7bb0804d662f1d441a4">
<p>1 file(s) updated with &#34;$1:8.10.3-35c43be1-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.10.3-35c43be1

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6484404965
---
<Actions>
<action id="839eccb8667134f5ec76abe5a43e58e7caa44d546a71355fb5551e97786bbbf2">
<p>1 file(s) updated with &#34;$1:7.17.15-e89ddad5-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.15-e89ddad5

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6497452562
---
<Actions>
<action id="f2d280e5a092d0d7be880f53a1f1885f37d60ba9c58f3c237e33a273210b0956">
<p>1 file(s) updated with &#34;$1:7.17.15-687e01db-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.15-687e01db

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6497452562
---
<Actions>
<action id="54d7a9336e69db2a5b0a7d6292e70a84d37ed2ccfae0a6f362757191cd8e9330">
<p>1 file(s) updated with &#34;$1:8.11.0-60b804d4-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.0-60b804d4

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6497452562
---
<Actions>
<action id="788936c4fe6cdfb1ae38977a4d0604bbdd472cd8a5efa0abe29bccda2ffff634">
<p>1 file(s) updated with &#34;$1:8.12.0-1a1295ff-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.0-1a1295ff

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6509884312
---
<Actions>
<action id="2606fe640d29829445da6abe605d2d325de17bee5027e88ca8c85127e6777112">
<p>1 file(s) updated with &#34;$1:8.10.4-df8d75ce-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
<action id="bb9c168c799c8a74ba64aacf154d1fb1fc895a04e40203ab8af97dedc4699154"> …
=> [updatecli] update elastic stack version for testing 8.10.4-df8d75ce

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6509884312
---
<Actions>
<action id="180e067ec246d603a38793fcda35d8120a03dd6ccd89076c84d69c2b57804912">
<p>1 file(s) updated with &#34;$1:8.11.0-820fdcd6-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.0-820fdcd6

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6509884312
---
<Actions>
<action id="2839d5de333eba47c0f7bf74e70edbd8740159fa38bdee545c581f1afa1e8e3b">
<p>1 file(s) updated with &#34;$1:7.17.15-a0c3fd00-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.15-a0c3fd00

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6509884312
---
<Actions>
<action id="a05aff8439187c9e2a538e119b42bf8402a1e4eb2405db0f79fa5884d13589d7">
<p>1 file(s) updated with &#34;$1:8.12.0-cb808527-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.0-cb808527

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 8.10.4.
=> docs: update docs versions 8.10.4

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6549129259
---
<Actions>
<action id="19e9224c3057cab558cbe1a59dedd47317af435f0122bb5480e3e7b694af3918">
<p>1 file(s) updated with &#34;$1:7.17.15-264995c6-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.15-264995c6

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6562812678
---
<Actions>
<action id="84577dbc35c5b55fa3506173e305db877fadb99db9908ed4550296f20ddc1ad8">
<p>1 file(s) updated with &#34;$1:7.17.15-310ac563-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.15-310ac563

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6562812678
---
<Actions>
<action id="ae358e7f01782877438d51f1d8a8a87d853b180a78f25771c9b0765ca639cee2">
<p>1 file(s) updated with &#34;$1:8.10.5-fede41a8-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.10.5-fede41a8

CHANGELOG.next.asciidoc, NOTICE.txt, go.mod, go.sum
upgrade elastic-agent-libs to v0.6.0
allows beat running as a windows service to receive more than one
change request.  Without this the Beat can become unresponsive to
Windows Service Manager requests (Interrogate/Shutdown/Restart).
1. Install Beat as a Windows Service
2. Start PowerShell
3. Interrogate service with 3 calls to `Get-WmiObject -Class Win32_Service -Filter "name='Beat Name Here'"`
4. Try to Restart Service with Services control panel
Without this PR Restart should fail, with PR it should succeed
- Closes #33361
=> upgrade elastic-agent-libs to v0.6.0

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6576547382
---
<Actions>
<action id="a7655fbf5d006659ccd671bc0620da71e6033a7f0c9a31c66352af9a24333a69">
<p>1 file(s) updated with &#34;$1:8.10.5-69d64a75-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.10.5-69d64a75

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6576547382
---
<Actions>
<action id="b15b280fa27a1d4adb9ba3302aad2a63ec1cf43514bfe03a20bf7885937c53d2">
<p>1 file(s) updated with &#34;$1:7.17.15-ae1f480c-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.15-ae1f480c

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6589444646
---
<Actions>
<action id="48385ac5956d8c059075d7ad2419d03276eff05b618ad0b31e658ea00df198a0">
<p>1 file(s) updated with &#34;$1:8.10.5-0028f476-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.10.5-0028f476

x-pack/filebeat/docs/inputs/input-cel.asciidoc
The previous example refers to the httpjson mechanism.
-
=> x-pack/filebeat/docs/inputs/cel: fix basic auth example

filebeat/input/file/file.go
Cleanup only (no behavior changes), removing a type that is no longer used
=> [Cleanup] Remove unused type

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6615164205
---
<Actions>
<action id="ba1ccd452309c735c7c39a9fb701e8cf3fefa09e6d75fd88e61d9272056cd721">
<p>1 file(s) updated with &#34;$1:8.11.0-f8ea8c6e-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.0-f8ea8c6e

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6615164205
---
<Actions>
<action id="283c29da0d498ba89e679c6da43c28df1376b69e976adf152b1718e77befd57e">
<p>1 file(s) updated with &#34;$1:8.10.5-b919c0d9-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.10.5-b919c0d9

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6615164205
---
<Actions>
<action id="0fd3bb52baaed1bdf13c10efc23316b16603f6ebfec488fdad8903038f20d5a4">
<p>1 file(s) updated with &#34;$1:7.17.15-2d46ac23-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.15-2d46ac23

CHANGELOG.next.asciidoc, NOTICE.txt, go.mod, go.sum, x-pack/filebeat/docs/inputs/input-cel.asciidoc, x-pack/filebeat/input/cel/config_auth.go, x-pack/filebeat/input/cel/config_test.go, x-pack/filebeat/input/cel/input.go, x-pack/filebeat/input/cel/input_test.go
See title.
In x-pack/filebeat/input/cel, run `go test -run_remote`.
- Closes #35514
=> x-pack/filebeat/input/cel: add support for digest authentication

libbeat/beat/event.go, libbeat/beat/event_test.go, libbeat/processors/add_id/add_id_test.go
* Added tests with full coverage
* Standardized the behavior with `mapstr.M`.
=> Refactor `Event` type and add more test coverage

CHANGELOG-developer.next.asciidoc, x-pack/filebeat/input/cel/input.go, x-pack/filebeat/input/httpjson/input.go
=> x-pack/filebeat/input/{cel,httpjson}: elide unneeded retryable HTTP client construction

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6628766308
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.0-26e5e008-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.0-26e5e008

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6628766308
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.15-75139b44-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.15-75139b44

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6656040302
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.0-6c3c780b-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.0-6c3c780b

NOTICE.txt, go.mod, go.sum
Move to release tag instead of release candidate.
https://github.com/apache/arrow/releases/tag/go%2Fv12.0.1
Closes #36949
- Closes #36949
=> go.mod - Use github.com/apache/arrow/go/v12 v12.0.1

packetbeat/docs/packetbeat-options.asciidoc
Fix packetbeat docs https://www.elastic.co/guide/en/beats/packetbeat/current/configuration-interfaces.html#_windows_npcap_installation_options to avoid that the unresolved variable `{beatname}` is shown instead of Packetbeat.
-
=> [Docs] Update packetbeat-options.asciidoc to use right beatname_uc variable

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6668925446
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.10.5-602db7b7-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.10.5-602db7b7

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6668925446
---
<Actions>
<action id="31eb85ff6a0e2ceca6eec98625b643466d20fc4e5f51edfdd5fff0bf5949993f">
<p>1 file(s) updated with &#34;$1:8.12.0-ac05de1e-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action> …
=> [updatecli] update elastic stack version for testing 8.12.0-fa958a90

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6694718230
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-bb5042c3-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.0-bb5042c3

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6694718230
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.0-052083ba-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.0-052083ba

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6708433468
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.0-0752993e-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.0-0752993e

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6708433468
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.10.5-7673c4c2-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.10.5-7673c4c2

CHANGELOG.next.asciidoc, dev-tools/packaging/templates/docker/Dockerfile.tmpl
Bump NodeJS version bundled with Heartbeat to `18.18.2`.
1. Build `mage package` locally.
2. Run a container with the generated image.
3. Execute the following command and test version matches 18.17.1:
```
docker run --rm --entrypoint /bin/bash docker.elastic.co/beats/heartbeat:<version> -c "node --version"
v18.18.2
```
=> [Heartbeat] Bump nodejs minor version

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6708433468
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-0fcb9daf-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.0-0fcb9daf

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6721368657
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.10.5-2cbba330-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.10.5-2cbba330

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6721368657
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.0-2f2c6d79-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.0-2f2c6d79

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6708433468
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.15-c46e14f4-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.15-c46e14f4

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6734418247
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.10.5-d6b719a1-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.10.5-d6b719a1

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6734418247
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.0-d4bb1214-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.0-d4bb1214

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6746879203
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.15-982e299a-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.15-982e299a

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6772590358
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.10.5-5c458ac8-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.10.5-5c458ac8

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6772590358
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.0-c2c48f8b-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.0-c2c48f8b

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6772590358
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.15-3dc13f24-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.15-3dc13f24

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6786359868
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.15-82adb10b-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.15-82adb10b

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6786359868
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.10.5-b9ae0cc2-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.10.5-b9ae0cc2

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 8.11.0

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6800081152
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.15-e209a10a-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.15-e209a10a

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6800081152
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-cf2c16a7-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.0-cf2c16a7

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6813603230
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.15-af34bce7-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.15-af34bce7

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6813603230
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-8aa43f2a-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.0-8aa43f2a

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6826430940
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.1-c8848943-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.1-c8848943

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6826430940
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.15-0438005b-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.15-0438005b

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6826430940
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-0ee5847c-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.0-0ee5847c

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Update the docs for next minor 8.12.0.
Merge after the release branch for 8.10.2 is created.
=> [Release] Update docs for the 8.12.0 release

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 7.17.15.
=> docs: update docs versions 7.17.15

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6851793890
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.1-2f6a8ab6-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/6851793890">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.1-2f6a8ab6

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6851793890
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.15-aad9f113-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/6851793890">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.15-aad9f113

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6879067042
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.2-a8fca3bd-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/6879067042">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.2-a8fca3bd

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6879067042
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-82c28a25-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/6879067042">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.0-82c28a25

x-pack/elastic-agent/pkg/core/retry/retrystrategy.go, x-pack/elastic-agent/pkg/core/retry/retrystrategy_test.go
The test for this code was flaky.
- Closes #37078
=> Remove unused code

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6892573596
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.2-e0eeeb99-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/6892573596">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.2-e0eeeb99

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6892573596
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-c18d0d89-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/6892573596">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.0-c18d0d89

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6892573596
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.16-95c51018-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/6892573596">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.16-95c51018

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6905649084
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.2-dc2c1eb6-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/6905649084">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.2-dc2c1eb6

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6905649084
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.16-b2590ce9-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/6905649084">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.16-b2590ce9

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6905649084
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-35e3b343-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/6905649084">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.0-35e3b343

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-azure-blob-storage.asciidoc, x-pack/filebeat/input/azureblobstorage/input.go
- Enhancement
- Docs
Made Azure Blob Storage input GA and updated the docs as necessary.
- Relates https://github.com/elastic/integrations/issues/8156
=> [filebeat][azure-blob-storage] - Made input GA and updated logs accordingly

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6931928902
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.16-641039af-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/6931928902">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.16-641039af

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6931928902
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-7521d760-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/6931928902">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.0-7521d760

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6931928902
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.2-b3ae3a61-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/6931928902">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.2-b3ae3a61

CHANGELOG.next.asciidoc, x-pack/filebeat/input/cel/input.go
`now()` and the mito `now` global both evaluate as times in UTC. The per-period `now` global of the input should as well.
-
=> x-pack/filebeat/input/cel: make now evaluate to a time in UTC

CHANGELOG-developer.next.asciidoc, x-pack/filebeat/input/httpjson/internal/v2/input_test.go
See title.
- Closes #37146
- Ref #34929
=> x-pack/filebeat/input/httpjson/internal/v2: skip flakey test

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6945667109
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.2-01f6d366-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/6945667109">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.2-01f6d366

CHANGELOG.next.asciidoc, NOTICE.txt, go.mod, go.sum, x-pack/filebeat/docs/inputs/input-cel.asciidoc, x-pack/filebeat/input/cel/input.go, x-pack/filebeat/input/cel/input_test.go
=> x-pack/filebeat/input/cel: update mito version to v1.7.0 and enable optional types

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6971401884
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.2-2c7cf905-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/6971401884">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.2-2c7cf905

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6971401884
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.16-03cd24d7-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/6971401884">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.16-03cd24d7

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/6982282905
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.16-456fee42-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/6982282905">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.16-456fee42

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7006857941
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.2-a6202097-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7006857941">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.2-a6202097

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7020664443
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.2-8c8386ee-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7020664443">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.2-8c8386ee

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7020664443
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.16-36c2b6c2-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7020664443">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.16-36c2b6c2

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7020664443
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-d6c4164b-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7020664443">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.0-d6c4164b

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7034477022
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.16-922f8875-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7034477022">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.16-922f8875

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7034477022
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-ec4853e4-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7034477022">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.0-ec4853e4

dev-tools/kubernetes/filebeat/Dockerfile.debug, dev-tools/kubernetes/heartbeat/Dockerfile.debug, dev-tools/kubernetes/metricbeat/Dockerfile.debug
Upgrade go-delve version 1.9.0 -> 1.21.2 to fix this Error:
```
Version of Delve is too old for Go version 1.20.8 (maximum supported version 1.19, suppress this error with --check-go-version=false)
```
-
=> Upgrade go-delve version 1.9.0 -> 1.21.2

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7048326298
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.2-078bc9ad-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7048326298">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.2-078bc9ad

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7061673807
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.2-8ec5d9e2-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7061673807">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.2-8ec5d9e2

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7061673807
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-db26fd8b-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7061673807">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.0-db26fd8b

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7088472610
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.16-460da4c1-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7088472610">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.16-460da4c1

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7088472610
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.2-851afa34-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7088472610">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.2-851afa34

dev-tools/packaging/templates/ironbank/auditbeat/Dockerfile, dev-tools/packaging/templates/ironbank/filebeat/Dockerfile, dev-tools/packaging/templates/ironbank/heartbeat/Dockerfile, dev-tools/packaging/templates/ironbank/metricbeat/Dockerfile, dev-tools/packaging/templates/ironbank/packetbeat/Dockerfile
Create symlink to `/usr/bin/tini` in the ironbank docker images.
`ironbank` images can be used in ECK.
-
=> ironbank: enable /usr/bin/tini

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7102604979
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.16-9916f602-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7102604979">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.16-9916f602

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7102604979
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-33e8d7e1-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7102604979">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.0-33e8d7e1

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7116331471
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.2-5d5f3e59-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7116331471">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.2-5d5f3e59

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Update the docs for next minor 8.13.0.
Merge after the release branch for v8.11.1 is created.
=> [Release] Update docs for the 8.13.0 release

filebeat/input/filestream/input_test.go
* Now the initialization time is not included in the actual benchmark timer
* The filestream runner is more re-usable now and can be used later for regular tests not just benchmarks
```sh
go test -run=none -bench='BenchmarkFilestream/filestream_.*_throughput.*' -benchmem -benchtime=100x
```
Before
```
BenchmarkFilestream/filestream_default_throughput-10
100          10454563 ns/op        13576216 B/op     181225 allocs/op
BenchmarkFilestream/filestream_fingerprint_throughput-10
100          13427490 ns/op …
```
=> Make filestream benchmark more precise and more re-usable

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7130023345
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.16-e5429648-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7130023345">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.16-e29c45be

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7169341878
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.16-0c224de5-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7169341878">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.16-0c224de5

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7169341878
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.3-dce3355e-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7169341878">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.3-dce3355e

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 7.17.16.
=> docs: update docs versions 7.17.16

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 8.11.3.
=> docs: update docs versions 8.11.3

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
Prepare Changelog for 7.17.16.
=> docs: Prepare Changelog for 7.17.16

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7183329350
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.16-cf899701-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7183329350">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.16-cf899701

CHANGELOG.asciidoc
=> Add security notice to Beats 8.11.3 Release Notes

CHANGELOG.asciidoc, libbeat/docs/release.asciidoc
=> Fixing 8.12 docs

CHANGELOG.asciidoc
=> Add security notice to Beats 8.11.2 release notes

CHANGELOG.asciidoc
=> Add security notice to Beats 7.17.16 release notes

winlogbeat/docs/metrics-winlogbeat.asciidoc
=> [winlogbeat] Adding nanoseconds time unit to docs for `source_lag_time`, `batch_read_period`

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7210702415
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-3faaf80d-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7210702415">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.0-3faaf80d

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7223686876
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-bde01754-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7223686876">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.0-bde01754

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7249908369
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.17-c7717eb7-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7249908369">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.17-c7717eb7

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7249908369
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-0d7c3f79-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7249908369">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.0-0d7c3f79

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7249908369
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-h30gube9-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7249908369">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.0-h30gube9

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7263650677
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.17-7f0b87e8-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7263650677">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.17-7f0b87e8

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7263650677
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.4-d6b1ea5a-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7263650677">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.4-d6b1ea5a

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7263650677
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-ubdkmnyz-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7263650677">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.0-ubdkmnyz

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7263650677
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-83badc78-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7263650677">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.0-83badc78

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7277158120
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.4-baca29c6-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7277158120">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.4-baca29c6

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7277158120
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.17-b3d55566-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7277158120">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.17-b3d55566

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7277158120
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-9amqxdis-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7277158120">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.0-9amqxdis

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7277158120
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-152634ef-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7277158120">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.0-152634ef

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7289804393
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.4-eb79a552-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7289804393">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.4-eb79a552

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7289804393
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.17-13e2edc2-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7289804393">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.17-13e2edc2

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7289804393
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-yufkxnwm-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7289804393">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.0-yufkxnwm

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7289804393
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-cf3c9e0f-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7289804393">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.0-cf3c9e0f

.github/CODEOWNERS, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/filebeat/filebeat-configmap.yaml, dev-tools/kubernetes/Tiltfile, dev-tools/kubernetes/filebeat/manifest.debug.yaml, dev-tools/kubernetes/filebeat/manifest.run.yaml, dev-tools/kubernetes/metricbeat/manifest.debug.multi.yaml, dev-tools/kubernetes/metricbeat/manifest.debug.yaml, dev-tools/kubernetes/metricbeat/manifest.run.yaml
Updated k8s manifest for filebeat and metricbeat to match manifests under deploy. Some minor changes include using filestream for filebeat inputs instead of container. Some other changes are just reordering the list of k8s resources
-
=> Update k8s manifests for filebeat and metricbeat in dev-tools

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7301225254
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.4-8b9cf48f-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7301225254">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.4-8b9cf48f

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7301225254
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.17-f615e8a5-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7301225254">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.17-f615e8a5

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7301225254
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-vqaxdghw-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7301225254">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.0-vqaxdghw

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7301225254
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-67b59f94-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7301225254">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.0-67b59f94

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7322619554
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.4-e0baf42b-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7322619554">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.4-e0baf42b

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7322619554
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.17-6c067840-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7322619554">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.17-6c067840

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7322619554
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-fab43f98-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7322619554">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.0-fab43f98

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7330545989
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.4-4f9102a1-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7330545989">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.4-4f9102a1

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7330545989
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.17-514f2280-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7330545989">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.17-514f2280

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7330545989
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-01443900-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7330545989">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.0-01443900

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7339480511
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.4-b057e528-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7339480511">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.4-b057e528

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7339480511
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.17-ae5188ce-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7339480511">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.17-ae5188ce

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7339480511
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-e8c03076-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7339480511">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.0-e8c03076

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7348801017
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.4-33860d30-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7348801017">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.4-33860d30

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7348801017
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-2df616a6-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7348801017">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.0-2df616a6

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7357688093
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.4-c3b12837-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7357688093">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.4-c3b12837

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7357688093
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.17-c6804173-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7357688093">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.17-c6804173

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7357688093
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-32d47279-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7357688093">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.0-32d47279

NOTICE.txt
It is not 2024. Put that in the notice file.
=> Update notice year to 2024.

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7449248991
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.4-8881462e-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7449248991">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.4-8881462e

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7449248991
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.17-95dddbc3-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7449248991">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.17-95dddbc3

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7462853046
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.4-3f013fd4-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7462853046">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.4-3f013fd4

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7462853046
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-8upz6ftd-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7462853046">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.0-8upz6ftd

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7476802504
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.4-16bb5361-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7476802504">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.11.4-16bb5361

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7476802504
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.17-011d453a-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7476802504">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.17-011d453a

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 8.11.4.
=> docs: update docs versions 8.11.4

NOTICE.txt, go.mod, go.sum
Type of change
- Enhancement
Bump github.com/aws/aws-lambda-go from v1.13.3 to v1.44.0
Upgrade version to be able to use AWS Lambda runtime  'Custom runtime on Amazon Linux 2' 
- [x ] My code follows the style guidelines of this project
- [x ] I have made corresponding changes to the documentation
- [x ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.
- 
Currently functionbeat does not work on AWS Lambda "Custom runtime on Amazon Linux 2". 
Upgrading the aws-lambda-go to the latest version will make it work.
=> Add compatibility with AWS Lambda runtime "Custom runtime on Amazon Linux 2"

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 8.11.4

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7503871472
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.17-0b4d6d87-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7503871472">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.17-9b7d64cf

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7503871472
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-9yo2ylny-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7503871472">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.0-9yo2ylny

.buildkite/auditbeat/auditbeat-pipeline.yml, .buildkite/deploy/kubernetes/deploy-k8s-pipeline.yml, .buildkite/heartbeat/heartbeat-pipeline.yml, .buildkite/pull-requests.json, catalog-info.yaml
Added Auditbeat, Heartbeat & K8S Deploy Buildkite pipelines infrastructure
- Relates [1693](https://github.com/elastic/ingest-dev/issues/1693)
=> Buildkite infra for Auditbeat, Heartbeat & K8S Deploy

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7530675523
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.17-1107dfdb-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7530675523">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.17-1107dfdb

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7530675523
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-07re5v7e-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7530675523">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.0-07re5v7e

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7543505664
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.17-f603656b-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7543505664">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.17-f603656b

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7543505664
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-k08v7bga-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7543505664">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.0-k08v7bga

x-pack/metricbeat/modules.d/enterprisesearch-xpack.yml.disabled
This commit adds a missing file generated when running `make update` from the project's root directory.
Run `make update` from the root of the project. No un-tracked files should appear.
~~## Logs~~
=> Add missing generated files (make update)

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7557662072
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.17-66d75d96-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7557662072">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.17-66d75d96

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 8.12.0

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7571916941
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.17-bf0a38e4-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7571916941">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.17-bf0a38e4

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7585511212
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.17-36eb4463-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7585511212">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.17-36eb4463

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7585511212
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-pitatttq-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7585511212">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.0-pitatttq

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
Prepare Changelog for 7.17.17.
=> docs: Prepare Changelog for 7.17.17

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 7.17.17.
=> docs: update docs versions 7.17.17

x-pack/filebeat/input/awscloudwatch/_meta/terraform/variables.tf
Add terraform variables for filebeat awscloudwatch input.
=> add terraform variables

x-pack/filebeat/input/awscloudwatch/_meta/terraform/main.tf, x-pack/filebeat/input/awscloudwatch/_meta/terraform/variables.tf, x-pack/filebeat/input/awss3/_meta/terraform/main.tf, x-pack/metricbeat/module/aws/terraform.tf
- Relates https://github.com/elastic/beats/issues/37037
=> [8.12] Add required tags to create AWS instances for CI

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7669744212
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-l5snflwr-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7669744212">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.0-l5snflwr

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7669744212
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.1-viuu0igj-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7669744212">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.1-viuu0igj

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7698100804
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.18-1cc388da-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7698100804">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.18-1cc388da

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7698100804
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-yil7wib0-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7698100804">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.0-yil7wib0

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7698100804
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.1-mg2y3klg-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7698100804">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.1-mg2y3klg

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7713157790
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.18-8136c1b9-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7713157790">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.18-8136c1b9

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7713157790
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.1-lipljxnp-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7713157790">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.1-lipljxnp

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7728054544
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.18-b8c750dd-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7728054544">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.18-b8c750dd

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7728054544
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.1-3x3y2wtd-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7728054544">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.1-3x3y2wtd

x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
=> x-pack/filebeat/docs/input: advise to use CEL over HTTPJSON for new projects

.buildkite/pull-requests.json
Corrected elastic-agent buildkite pipeline slug
=> Fixed elastic-agent buildkite pipeline slug

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7743288762
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.18-84f8556d-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7743288762">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.18-84f8556d

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7743288762
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.1-jqpgs5zc-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7743288762">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.1-jqpgs5zc

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7757754278
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.1-6a15fcef-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7757754278">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.1-6a15fcef

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7757754278
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-c876301f-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7757754278">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.0-c876301f

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7786496083
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.1-f611ca6e-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7786496083">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.1-f611ca6e

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7801722861
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-f56d9bd5-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7801722861">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.0-f56d9bd5

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 7.17.18.
=> docs: update docs versions 7.17.18

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7816817755
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.1-135756ae-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7816817755">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.1-135756ae

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7816817755
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-c6fcd738-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7816817755">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.0-c6fcd738

.buildkite/auditbeat/auditbeat-pipeline.yml, .buildkite/auditbeat/scripts/package-step.sh, .buildkite/filebeat/filebeat-pipeline.yml, .buildkite/filebeat/scripts/package-step.sh, .buildkite/heartbeat/heartbeat-pipeline.yml, .buildkite/heartbeat/scripts/package-step.sh
Migration of beats to Buildkite - fixed dynamic step upload for packaging step
Links to BK builds:
Filebeat: https://buildkite.com/elastic/filebeat/builds?branch=oakrizan%3Apackaging-step-fix
Heartbeat: https://buildkite.com/elastic/heartbeat/builds?branch=oakrizan%3Apackaging-step-fix
Auditbeat: https://buildkite.com/elastic/auditbeat/builds?branch=oakrizan%3Apackaging-step-fix
-
=> Fix packaging dynamic step upload

catalog-info.yaml
Update the configuration for already migrated pipelines in the catalog-info
=> update catalog-ingo for migrated pipelines

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7845796894
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.2-ae12c9ba-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7845796894">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.2-ae12c9ba

CHANGELOG.next.asciidoc
Adds a changelog entry for https://github.com/elastic/elastic-stack-installers/pull/240
=> Add changelog for MSI installer helper script.

CHANGELOG.next.asciidoc
=> changelog: add missing pr number

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7888478975
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.2-5f8ffc93-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7888478975">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.2-5f8ffc93

catalog-info.yaml
Fixed the wrong repository setting for elastic-agent in catalog-info.yml
=> Fixed repository for elastic-agent in catalog-info

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7917958455
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-772867d3-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7917958455">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.0-772867d3

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7932404992
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.2-4fee8a94-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7932404992">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.2-4fee8a94

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7961561465
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.2-7bd62d94-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7961561465">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.2-7bd62d94

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7975560506
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.19-fc9da510-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7975560506">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.19-fc9da510

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 8.12.2.
=> docs: update docs versions 8.12.2

NOTICE.txt, go.mod, go.sum
=> Update go.mod to add an exclusion that was present since 8.3

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7991147227
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.2-bf518ba4-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7991147227">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.2-bf518ba4

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/7991147227
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-466f28cb-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/7991147227">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.0-466f28cb

.buildkite/auditbeat/scripts/package-step.sh, .buildkite/filebeat/scripts/package-step.sh, .buildkite/heartbeat/scripts/package-step.sh
Fix errors in 7.17:
https://buildkite.com/elastic/auditbeat/builds/1848#018dcc3d-c30d-49a6-87af-7dc2643bf087/340-402
https://buildkite.com/elastic/filebeat/builds/3176#018dcc40-20e5-4f4e-ac2f-184be9b07ab2/339-403
https://buildkite.com/elastic/heartbeat/builds/1837#018dcc3e-983e-40ba-8015-292aa9b167f1/340-401
=> remove darwin-arm64 packaging

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8006570319
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.2-43bf608d-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8006570319">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.2-43bf608d

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8006570319
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-c44bedb9-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8006570319">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.0-c44bedb9

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8006570319
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-74a79bf3-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8006570319">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.14.0-74a79bf3

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8066862096
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.2-5482c56d-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8066862096">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.3-4ac1d971

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8082505426
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.3-47841fb2-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8082505426">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.3-47841fb2

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8082505426
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-6775ba34-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8082505426">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.0-3e853527

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8098124938
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.19-28c9bc23-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8098124938">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.19-28c9bc23

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8098124938
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-b395a473-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8098124938">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.0-b395a473

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8098124938
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.3-c580c40e-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8098124938">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.3-c580c40e

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8113121011
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.19-471911c1-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8113121011">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.19-471911c1

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8113121011
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.3-3f627ed1-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8113121011">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.3-3f627ed1

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8142370089
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.19-49b3533b-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8142370089">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.19-49b3533b

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8142370089
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.3-4d8adddd-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8142370089">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.3-4d8adddd

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8142370089
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-34a49bd9-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8142370089">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.0-34a49bd9

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8158443359
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.19-f76d6d2f-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8158443359">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.19-f76d6d2f

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8158443359
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-8279d17d-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8158443359">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.0-8279d17d

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8158443359
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.3-b03f626a-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8158443359">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.3-b03f626a

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8174208746
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.19-f29cf3a2-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8174208746">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.19-f29cf3a2

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8190283411
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.19-542eded5-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8190283411">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.19-542eded5

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8205150084
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.19-1b83f14d-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8205150084">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.19-1b83f14d

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8205150084
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.3-50b2cd56-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8205150084">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.3-50b2cd56

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8235069466
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.3-00a3f705-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8235069466">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.3-00a3f705

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8235069466
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-6815ad42-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8235069466">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.0-6815ad42

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8251123840
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.19-cd4b6257-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8251123840">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.19-cd4b6257

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8251123840
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.3-98aa2390-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8251123840">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.3-98aa2390

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8251123840
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-72b525a7-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8251123840">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.0-72b525a7

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8266915801
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.19-0b4cdbdc-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8266915801">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.19-0b4cdbdc

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8266915801
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.3-530f08ed-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8266915801">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.3-530f08ed

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8266915801
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-e56dde0a-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8266915801">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.0-e56dde0a

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8282968204
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.19-176a9dfa-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8282968204">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.19-176a9dfa

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8282968204
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.3-fec1a044-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8282968204">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.3-fec1a044

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8282968204
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-bd8c2be5-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8282968204">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.14.0-bd8c2be5

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8298258788
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.19-023068fa-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8298258788">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.19-023068fa

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8298258788
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-099ad3d3-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8298258788">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.0-099ad3d3

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8298258788
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.3-068eda6a-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8298258788">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.3-068eda6a

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8328883690
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.19-a2ab9cd7-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8328883690">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.19-a2ab9cd7

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8328883690
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-a9fbad89-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8328883690">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.0-a9fbad89

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8328883690
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.3-38b17954-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8328883690">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.3-38b17954

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8345372754
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.19-b8d7cdf4-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8345372754">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.19-b8d7cdf4

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8345372754
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.3-ef3d6214-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8345372754">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.3-ef3d6214

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8345372754
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-de4951fb-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8345372754">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.0-de4951fb

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8361187504
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-32b2aea6-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8361187504">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.0-32b2aea6

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8361187504
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.3-f215049e-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8361187504">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.12.3-f215049e

.buildkite/hooks/pre-command, .buildkite/scripts/common.sh, .buildkite/scripts/generate_xpack_osquerybeat_pipeline.sh, .buildkite/x-pack/pipeline.xpack.osquerybeat.yml
Migrate `x-pack osquerybeat` pipeline
Example of the pipeline:
https://buildkite.com/elastic/beats-xpack-osquerybeat/builds/292
=> migrate x-pack/osquerybeat pipeline

.github/CODEOWNERS
Add CODEOWNERS entry for Aerospike.
-
=> Add CODEOWNERS entry for Aerospike

catalog-info.yaml
This commit disables PR comments while the migration is ongoing.
Relates: https://github.com/elastic/ingest-dev/issues/3001#issuecomment-2015048515
=> Disable Buildkite PR comments

x-pack/filebeat/docs/inputs/input-http-endpoint.asciidoc
=> x-pack/filebeat/docs/input/http_endpoint: fix word salad

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
Prepare Changelog for 7.17.19.
=> docs: Prepare Changelog for 7.17.19

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, libbeat/docs/release.asciidoc
=> docs: Prepare Changelog for 8.13.0

.github/CODEOWNERS
See title.
- Relates https://github.com/elastic/beats/pull/37331
=> x-pack/filebeat: Update CODEOWNERS for the new Salesforce's filebeat input

.buildkite/scripts/common.sh, .buildkite/x-pack/pipeline.xpack.heartbeat.yml
This PR fixes the x-pack heartbeat buildkite pipeline
=> Fix the dynamic step for pipeline upload on the x-pack Heartbeat

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8602380103
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.2-948b05e8-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8602380103">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.2-948b05e8

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 8.13.2.
=> docs: update docs versions 8.13.2

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, filebeat/docs/fields.asciidoc, libbeat/docs/version.asciidoc
Updates docs versions to 7.17.20.
=> docs: update docs versions 7.17.20

.buildkite/metricbeat/pipeline.yml, .buildkite/packetbeat/pipeline.packetbeat.yml, .buildkite/scripts/generate_metricbeat_pipeline.sh, .buildkite/scripts/generate_packetbeat_pipeline.sh, .buildkite/scripts/generate_winlogbeat_pipeline.sh, .buildkite/scripts/generate_xpack_auditbeat_pipeline.sh, .buildkite/scripts/generate_xpack_dockerlogbeat_pipeline.sh, .buildkite/scripts/generate_xpack_filebeat_pipeline.sh, .buildkite/scripts/generate_xpack_heartbeat_pipeline.sh, .buildkite/scripts/generate_xpack_libbeat_pipeline.sh, .buildkite/scripts/generate_xpack_metricbeat_pipeline.sh, .buildkite/scripts/generate_xpack_osquerybeat_pipeline.sh, .buildkite/scripts/generate_xpack_packetbeat_pipeline.sh, .buildkite/scripts/generate_xpack_winlogbeat_pipeline.sh
Split Windows step.
Example of the pipelines:
Examples of the affected pipelines:
=> Split windows steps

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8633510759
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-3c0002e4-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8633510759">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.14.0-3c0002e4

.buildkite/x-pack/elastic-agent/pipeline.xpack.elastic-agent.package.yml, .buildkite/x-pack/elastic-agent/scripts/steps/package.sh, dev-tools/mage/settings.go, x-pack/elastic-agent/magefile.go
Rename "ManifestUrl" environment variable to "MANIFEST_URL" to align it to elastic-agent v8.X repository
-
=> rename ManifestUrl env var to MANIFEST_URL

catalog-info.yaml
Angentbeat packaging and publishing pipeline entity
* Runs on push to `main` and release branches starting from `8.14`
* Not triggered by pull requests
* Can be triggered from Buildkite UI
- Relates https://github.com/elastic/ingest-dev/issues/3151
=> [CI] Agentbeat package pipeline resource

catalog-info.yaml
This is something that we would want to enable especially if we wanto to have steps conditionally be triggered if labels are defined or not.
=> Set Buildkite to trigger builds with labels

.buildkite/pipeline.yml
This way, if any change under the script folder, which is what most CI projects use to run their steps, is broken, we will know about it.
=> Add scripts folder to trigger all projects

.buildkite/pipeline.yml
This way, if any change under the script folder, which is what most CI projects use to run their steps, is broken, we will know about it.
<hr>This is an automatic backport of pull request #38883 done by [Mergify](https://mergify.com).
=> [7.17](backport #38883) Add scripts folder to trigger all projects

.github/CODEOWNERS
Correct a typo in the catalog-info codeowners config
=> catalog-info codeowners fix

.buildkite/deploy/kubernetes/deploy-k8s-pipeline.yml, .buildkite/env-scripts/util.sh, .buildkite/heartbeat/heartbeat-pipeline.yml, .buildkite/pipeline.yml
In scope of https://github.com/elastic/ingest-dev/issues/3072:
- added notifications for pipeline steps
- removed top level notifications for pipelines
- added BK hooks script to changeset checks
- removed BEATS_PROJECT_NAME env var from auditbeat and heartbeat
BK Builds: https://buildkite.com/elastic/beats/builds/5305
-
=> Buildkite pipeline unification fixes

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8691480410
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.3-19734ad9-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8691480410">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.3-19734ad9

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8707979029
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-918a815f-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8707979029">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.14.0-918a815f

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8707979029
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.3-b68daf90-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8707979029">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.3-b68daf90

x-pack/agentbeat/magefile.go
Added `ironbank` target for agentbeat. It does nothing to the artifacts because agentbeat is not subscribed to the IronBank releases. Like auditbeat.
- Relates https://github.com/elastic/ingest-dev/issues/3151
=> Added an empty ironbank target to agentbeat

.ci/packaging.groovy, Jenkinsfile
=> Fix msitools installation for packaging pipeline

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8724260597
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.21-e9b73307-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8724260597">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.21-e9b73307

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8724260597
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-799c1dc0-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8724260597">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.14.0-799c1dc0

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8724260597
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.3-3dc31fcb-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8724260597">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.3-3dc31fcb

x-pack/agentbeat/agentbeat.spec.yml
Add missing command name in the command specification in `agentbeat.spec.yml`.
Without this defined in the specification file the Elastic Agent keeps the binary name as `agentbeat` but really it should be `filebeat`. 
- Closes #39025
=> Add missing command name for filebeat.

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8740277405
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.21-53490780-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8740277405">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.21-53490780

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8740277405
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.3-c9047748-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8740277405">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.3-c9047748

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8755684533
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.21-587bbe3b-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8755684533">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.21-587bbe3b

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8755684533
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.3-c3270b70-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8755684533">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.3-c3270b70

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8786359478
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.21-5d83bb4d-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8786359478">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.21-5d83bb4d

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8786359478
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.3-22bed9d1-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8786359478">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.3-22bed9d1

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8802729993
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.21-5339d087-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8802729993">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.21-5339d087

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8802729993
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.3-94d3b00c-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8802729993">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.3-94d3b00c

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8818792800
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.21-75fbaabb-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8818792800">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.21-75fbaabb

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8818792800
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.3-6596e7ab-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8818792800">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.3-6596e7ab

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8818792800
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-f50da2d9-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8818792800">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.15.0-f50da2d9

.buildkite/packaging.pipeline.yml
This commit fixes the error
"interpolating remaining fields: Expected identifier to start with a letter, got /"
=> Fix BK DRA pipeline

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8834965698
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.21-93c6e368-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8834965698">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.21-93c6e368

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8834965698
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-055b54fd-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8834965698">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.14.0-055b54fd

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8850321990
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.21-b7eaea35-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8850321990">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.21-b7eaea35

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8850321990
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-32f53a5b-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8850321990">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.14.0-32f53a5b

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8850321990
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-053650c4-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8850321990">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.15.0-053650c4

catalog-info.yaml
This commits changes the settings of the packaging pipeline to make it execute only on the selected branches which currently is only main.
=> Update the Beats packaging pipeline settings

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8880869417
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.21-90452d6c-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8880869417">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.21-90452d6c

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8880869417
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-81021969-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8880869417">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.15.0-81021969

CHANGELOG.next.asciidoc
Add the missed changelog from a [previous PR](https://github.com/elastic/beats/pull/39131)
=> Add change log for S3 fix

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8897108213
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-b1148041-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8897108213">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.14.0-b1148041

catalog-info.yaml
This commit allows everyone under the Elastic org to be able to trigger builds in Buildkite.
=> Allow everyone in Elastic to build Beats

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8911036085
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.21-48567783-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8911036085">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.21-48567783

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8911036085
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.3-dae2338c-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8911036085">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.3-dae2338c

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8911036085
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-aa640648-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8911036085">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.15.0-aa640648

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 8.13.3.
=> docs: update docs versions 8.13.3

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 7.17.21.
=> docs: update docs versions 7.17.21

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8926091674
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.21-86bc1e1e-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8926091674">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.21-86bc1e1e

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8926091674
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-7f8575f3-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8926091674">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.15.0-7f8575f3

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8926091674
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.3-6dd01262-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8926091674">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.3-6dd01262

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8941002999
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.21-4f451c48-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8941002999">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.21-4f451c48

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8941002999
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-3eefdcff-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8941002999">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.15.0-3eefdcff

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8941002999
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.3-76ce1a63-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8941002999">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.3-76ce1a63

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8941002999
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-ef3549bd-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8941002999">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.14.0-ba404a5d

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8971312078
---
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.22-3712b6ed-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8971312078">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.22-3712b6ed

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8971312078
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-c743e4c8-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8971312078">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.14.0-c743e4c8

.buildkite/x-pack/pipeline.xpack.heartbeat.yml
In scope of https://github.com/elastic/ingest-dev/issues/3254 - updated x-pack/heartbeat pipeline to match same steps & commands as in Jenkins.
Jenkins vs. Buildkite comparison: https://gist.github.com/oakrizan/ad3b982cd59e42d25d80f664a194998b
BK builds: https://buildkite.com/elastic/beats-xpack-heartbeat/builds?branch=oakrizan%3Axpack-heartbeat-fixes
-
=> Update x-pack/heartbeat pipeline to match Jenkins

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8987727596
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-6d69ee76-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8987727596">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.14.0-6d69ee76

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8987727596
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-177234da-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8987727596">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.15.0-177234da

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8987727596
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.4-cc6fca83-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8987727596">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.4-cc6fca83

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Updates docs versions to 8.13.4.
=> docs: update docs versions 8.13.4

Jenkinsfile
Buildkite is now the production CI system; therefore, let's remove the GitHub comment notifications to avoid spamming people or even the GitHub issue creation if there is any flakiness in the main/release branches.
-
=> ci(jenkins): remove post-build notifications

.buildkite/pull-requests.json
This commit updates the pull-requests.json file for the BK PR Bot from main. It's not consulted in any way, but it reduces conflicts with backports that include it.
=> Update pull-requests.json from main

testing/environments/snapshot.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.22-f8bdfabc-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/9097395723">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.22-f8bdfabc

catalog-info.yaml
Deleted the old agentbeat packaging pipeline catalog-info entry. It's not needed anymore because it's being published by `beats-packaging-pipeline`
-
=> Deleted old Agentbeat packaging pipeline

testing/environments/snapshot.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.22-cc1e0082-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/9130303221">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 7.17.22-cc1e0082

testing/environments/snapshot.yml
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-1a872dbc-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/9081700585">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.15.0-1a872dbc

testing/environments/snapshot.yml
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-f5ce0819-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/9130303221">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.14.0-f5ce0819

.buildkite/libbeat/pipeline.libbeat.yml
Updated libbeat pipeline to match same steps and commands as was done on Jenkins on 7.17 branch
Jenkins vs. Buildkite comparison: https://gist.github.com/oakrizan/ec5a5255ec00aca4102895819d275eaa
- Relates https://github.com/elastic/ingest-dev/issues/3254
BK builds: https://buildkite.com/elastic/beats-libbeat/builds?branch=oakrizan%3Alibbeat-postmigration-fixes-for-7-17
=> Update libbeat pipeline to match Jenkins on 7.17 branch

testing/environments/snapshot.yml
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-ede8ab2b-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/9176910341">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.14.0-ede8ab2b

testing/environments/snapshot.yml
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-9bce1e63-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/9176910341">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.15.0-9bce1e63

.buildkite/x-pack/pipeline.xpack.auditbeat.yml
Updated x-pack/auditbeat pipeline to match same steps/commands as in Jenkins and to apply same naming style as in other BK pipelines for beats.
Jenkins vs. Buildkite comparison: https://gist.github.com/oakrizan/2d1d1669626f94e49b019c99973d145f
Buildkite builds: https://buildkite.com/elastic/beats-xpack-auditbeat/builds?branch=oakrizan%3Axpack-auditbeat-postmigration-fixes
=> Update x-pack/auditbeat pipeline to match Jenkins

.github/workflows/bump-elastic-stack-snapshot.yml, .github/workflows/bump-golang.yml, .github/workflows/notify-stalled-snapshots.yml
Use the GitHub secrets for the Slack bot rather than access the Vault secrets.
Remove the need for using the apm-pipeline-library and use the actions in charge of updatecli and slack notifications.
Use the GitHub token for the workflow with write permissions for creating content and PRs - Buildkite will test those PRs anyway.
GitHub secrets have been created, there is a linked PR to a private repository in this PR - in case someone wanna see this.
-
=> github-actions: use GitHub secrets for the slack bot and the ephemeral GitHub token

CHANGELOG-developer.next.asciidoc, x-pack/filebeat/input/httpjson/metrics_test.go
=> x-pack/filebeat/input/httpjson: skip flakey test on windows

.buildkite/x-pack/pipeline.xpack.auditbeat.yml
Fixed x-pack/auditbeat pipeline agent, step and notification naming according to general standard.
Should be backported to 8.13 and 8.14 branches only since 7.17 styling is fixed within https://github.com/elastic/beats/pull/39658
BK builds: https://buildkite.com/elastic/beats-xpack-auditbeat/builds?branch=oakrizan%3Axpack-auditbeat-postmigration-style-fixes
=> Style fixes for Buildkite xpack/auditbeat pipeline

.buildkite/x-pack/pipeline.xpack.libbeat.yml
Updated x-pack/libbeat pipeline to match same steps/commands as in Jenkins and to apply same naming style as in other BK pipelines for beats.
Jenkins vs. Buildkite comparison: https://gist.github.com/oakrizan/18047e163ab57c3f9a3796a17ea08ce4
- Relates https://github.com/elastic/ingest-dev/issues/3254
BK builds: https://buildkite.com/elastic/beats-xpack-libbeat/builds?branch=oakrizan%3Axpack-libbeat-postmigration-fixes
=> Update xpack/libbeat pipeline to match Jenkins

.buildkite/pipeline.yml
Updated main beats pipeline:
- unify label styling
- updated watch path for x-pack/osquerybeat (so that build could be triggered when `pipeline.xpack.osquerybeat.yml` is changed)
BK builds: https://buildkite.com/elastic/beats/builds?branch=oakrizan%3Aupdate-main-beats-pipeline
=> Update main beats pipeline

packetbeat/route/route_test.go
Skip Flaky test - packetbeat/route TestDefault
-
=> Skip Flaky test - packetbeat/route TestDefault

.buildkite/x-pack/pipeline.xpack.filebeat.yml
Removed condition from mandatory Linux arm64 unit test step in x-pack/filebeat pipeline.
BK builds: https://buildkite.com/elastic/beats-xpack-filebeat/builds?branch=oakrizan%3Aupdate-xpack-filebeat-pipleine
=> Updated xpack/filebeat to match 7.17

.buildkite/x-pack/pipeline.xpack.osquerybeat.yml
Fixed x-pack/osquerybeat pipeline agent, step and notification naming according to general standard.
BK builds: https://buildkite.com/elastic/beats-xpack-osquerybeat/builds?branch=oakrizan%3Axpack-osquerybeat-postmigration-fixes
=> Update x-pack/osquerybeat pipeline to match Jenkins 

.buildkite/x-pack/pipeline.xpack.osquerybeat.yml
Aligned x-pack/osquerybeat to match steps from Jenkins on 7.17 branch.
BK builds: https://buildkite.com/elastic/beats-xpack-osquerybeat/builds?branch=oakrizan%3Axpack-osquerybeat-postmigration-fixes-7-17
=> Update x-pack/osquerybeat to match steps from Jenkins 7.17 branch

.buildkite/x-pack/pipeline.xpack.packetbeat.yml
Updated x-pack/packetbeat step labels and GH notifications to match general style used within beats in Buildkite
- Relats: https://github.com/elastic/ingest-dev/issues/3254
=> Update x-pack/packetbeat pipeline to match common styling

dev-tools/packaging/templates/docker/Dockerfile.tmpl
This change isn't actually necessary, the existing `apt` commands take care of it. The latest 8.14.0-SNAPSHOT for example is at the latest version without this PR being merged:
```
❯ docker run -it --entrypoint /bin/bash docker.elastic.co/beats/filebeat:8.14.0-SNAPSHOT
filebeat@f5cd68dd8c0a:~$ apt show nghttp2
Package: nghttp2
Version: 1.40.0-1ubuntu0.3
```
This command makes an existing container up to date if you run it directly in the container, but simply rebuilding the container is enough to pick up this change without any specific directive.
This reverts commit 809e00139db7225d18eac26186493e6b79b4a039.
-
=> Revert "Dockerfile: keep nghttp2 up to date. (#39694)"

.buildkite/x-pack/pipeline.xpack.winlogbeat.yml
Updated x-pack/winlogbeat pipeline to match same steps and step grouping as in Jenkins on 7.17 branch.
Updated step naming to match common style.
BK builds: https://buildkite.com/elastic/beats-xpack-winlogbeat/builds?branch=oakrizan%3Axpack-winlogbeat-postmigration-fixes-7-17
=> Update x-pack/winlogbeat pipeline to match steps from 7.17

.buildkite/x-pack/pipeline.xpack.winlogbeat.yml
Updated x-pack/winlogbeat pipeline step labels & namings to match common styling.
BK builds:
=> Update x-pack/winlogbeat step naming to match common style

CHANGELOG-developer.next.asciidoc, x-pack/filebeat/input/cel/input.go, x-pack/filebeat/input/httpjson/input.go
See title.
- Ref https://github.com/elastic/beats/pull/39821#discussion_r1631546180
=> x-pack/filebeat/input/{cel,httpjson}: fix typo in minimum log length

.buildkite/deploy/docker/docker-compose.yml
Updated localstack version to align content of .buidlkite folder on 8.14 with main.
Tests are not executed since `.buildkite/deploy/docker/docker-compose.yml` is not in the changeset (will be added in separate PR).
- Relates: https://github.com/elastic/ingest-dev/issues/3385
=> Update localstack version on 8.14 as on main branch

.buildkite/x-pack/pipeline.xpack.osquerybeat.yml
Migrate github checks to buildkite for x-pack/osquerybeat
- https://github.com/elastic/ingest-dev/issues/3380
=> Migrate github checks to buildkite for x-pack/osquerybeat

.buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml
Migrate github checks for x-pack/dockerlogbeat
- https://github.com/elastic/ingest-dev/issues/3380
=> Migrate github checks for x-pack/dockerlogbeat

x-pack/packetbeat/magefile.go
Removed `obs-ci-cache` bucket usage. It was used only in Jenkins
- Closes https://github.com/elastic/ingest-dev/issues/3006
=> [CI] Removed obs-ci-cache bucket usage

.buildkite/metricbeat/pipeline.yml
Updated metricbeat pipeline to match common styling && steps from Jenkins.
Removed unnecessary kind setup, since it's already pre-intalled on base Linux images (https://github.com/elastic/ingest-dev/issues/3238)
macOS arm64 tests remain disabled, since https://github.com/elastic/beats/issues/33035 is still actual.
Jenkins vs. Buildkite: https://gist.github.com/oakrizan/e3eaa28cb7848710ff1f1cb7f4a189a7
BK build: https://buildkite.com/elastic/beats-metricbeat/builds?branch=oakrizan%3Ametricbeat-postmigration-fixes
=> Update metricbeat to match common styling && Jenkins steps

.buildkite/winlogbeat/pipeline.winlogbeat.yml
Updated winlogbeat pipeline to match common styling and steps from Jenkins on 7.17 branch.
BK builds: https://buildkite.com/elastic/beats-winlogbeat/builds?branch=oakrizan%3Awinlogbeat-postmigration-fixes-7-17
=> Update winlogbeat pipeline to match styling and Jenkins 7.17

.buildkite/winlogbeat/pipeline.winlogbeat.yml
Updated winlogbeat pipeline to match common styling.
BK builds: https://buildkite.com/elastic/beats-winlogbeat/builds?branch=oakrizan%3Awinlogbeat-postmigration-fixes
=> Update winlogbeat pipeline to match common styling

.buildkite/auditbeat/auditbeat-pipeline.yml, .buildkite/filebeat/filebeat-pipeline.yml, .buildkite/heartbeat/heartbeat-pipeline.yml, .buildkite/libbeat/pipeline.libbeat.yml, .buildkite/metricbeat/pipeline.yml, .buildkite/packetbeat/pipeline.packetbeat.yml, .buildkite/winlogbeat/pipeline.winlogbeat.yml, .buildkite/x-pack/pipeline.xpack.auditbeat.yml, .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml, .buildkite/x-pack/pipeline.xpack.filebeat.yml, .buildkite/x-pack/pipeline.xpack.heartbeat.yml, .buildkite/x-pack/pipeline.xpack.libbeat.yml, .buildkite/x-pack/pipeline.xpack.metricbeat.yml, .buildkite/x-pack/pipeline.xpack.osquerybeat.yml, .buildkite/x-pack/pipeline.xpack.packetbeat.yml, .buildkite/x-pack/pipeline.xpack.winlogbeat.yml
Add "set -eo pipefail" to return error if any of commands will fail.
- https://github.com/elastic/ingest-dev/issues/3380
=> Update pipelines for beats with pipefail

.buildkite/packetbeat/pipeline.packetbeat.yml
Updated packetbeat pipeline to match common styling.
Jenkins vs. Buildkite: https://gist.github.com/oakrizan/b3b1a1f0de1dc19041475b2696cae82a
BK builds: https://buildkite.com/elastic/beats-packetbeat/builds?branch=oakrizan%3Apacketbeat-postmigration-fixes
=> Update packetbeat to match common styling

.buildkite/packetbeat/pipeline.packetbeat.yml
Updated packetbeat pipeline to match common styling && steps from Jenkins on 7.17 branch.
Jenkins vs. Buildkite: https://gist.github.com/oakrizan/b3b1a1f0de1dc19041475b2696cae82a
BK builds: https://buildkite.com/elastic/beats-packetbeat/builds?branch=oakrizan%3Apacketbeat-postmigration-fixes-7-17
=> Update packetbeat to match common styling && steps from Jenkins 7.17

CHANGELOG.next.asciidoc, x-pack/filebeat/input/cel/input.go
The protobuf.Value.AsInterface method [encodes +Inf as "Infinity"](https://github.com/protocolbuffers/protobuf-go/blob/ec47fd138f9221b19a2afd6570b3c39ede9df3dc/types/known/structpb/struct.pb.go#L392-L413) so ensure that we accept that string.
- For elastic/integrations#10185
=> x-pack/filebeat/input/cel: fix handling of infinite values in rates

dev-tools/packaging/templates/ironbank/auditbeat/Dockerfile, dev-tools/packaging/templates/ironbank/filebeat/Dockerfile, dev-tools/packaging/templates/ironbank/heartbeat/Dockerfile, dev-tools/packaging/templates/ironbank/metricbeat/Dockerfile, dev-tools/packaging/templates/ironbank/packetbeat/Dockerfile
Change ubi base image from 9.3 to 9.4 used in Ironbank Docker images for all 8.X Beats
=> Update Ironbank Dockerfile to ubi 9.4

x-pack/filebeat/input/entityanalytics/provider/okta/okta_test.go
=> x-pack/filebeat/input/entityanalytics/provider/okta: fix typo

.buildkite/pipeline.yml, .buildkite/pull-requests.json
Trigger elastic agent builds from the root pipeline instead of `pull-requests.json`
-
=> [CI] Trigger elastic agent builds from the root pipeline

.buildkite/pull-requests.json
Removes elastic-agent entry from `pull-requests.json`. This [PR](https://github.com/elastic/beats/pull/40024) makes it being triggered by the root pipeline instead.
-
=> [CI] Remove elastic-agent trigger from pull-requests.json

CHANGELOG.next.asciidoc, NOTICE.txt, go.mod, go.sum, x-pack/filebeat/docs/inputs/input-cel.asciidoc
=> mod: update elastic/mito to version v1.13.0

testing/environments/docker/elasticsearch_kerberos/Dockerfile, testing/environments/docker/elasticsearch_kerberos/config/kdc.conf.template, testing/environments/docker/elasticsearch_kerberos/scripts/addprincs.sh, testing/environments/docker/elasticsearch_kerberos/scripts/installkdc.sh
Updated ES image to latest 7.17.22, which is based on Ubuntu 20, instead of previous 7.7.0 that was based on CentOS 7. Updated related scripts to run on Ubuntu and adjusted KDC config.
This changes make elasticsearch-kerberos build successful and fixes problem with [failing libbeat Integration tests on 7.17](https://github.com/elastic/beats/pull/40051).
Run `docker build .` from `beats/testing/environments/docker/elasticsearch_kerberos`
- Relates: https://github.com/elastic/ingest-dev/issues/3520
BK builds: https://buildkite.com/elastic/beats/builds?branch=oakrizan%3Acentos-fix-for-libbeat
=> Bypass EOLed mirrorlist.centos.org in elasticsearch_kerberos Dockerfile

.buildkite/pull-requests.json
Add vault github plugin to allowed list
=> Add vault github plugin to allowed list

.buildkite/deploy/kubernetes/deploy-k8s-pipeline.yml
Updated Kubernetes version to he latest available kind tag per major version of Kubernetes release.
- Relates: https://github.com/elastic/ingest-dev/issues/3519
BK Builds: https://buildkite.com/elastic/deploy-k8s/builds?branch=oakrizan%3Aupdate-k8s-versions-main
=> Updated Kubernetes versions in deploy/k8s pipeline

.buildkite/deploy/kubernetes/deploy-k8s-pipeline.yml, .buildkite/pipeline.yml
To ensure `deploy/k8s` pipeline is triggered on changes related to k8s and not forgotten:
- removed tag requirement - if changes done in a changeset, no `kubernetes` tag would be required on MR to trigger pipeline
- updated changesets, to trigger pipeline if changes done on metricbeat/module/kubernetes side as well
- Relates: https://github.com/elastic/ingest-dev/issues/3519
BK builds: https://buildkite.com/elastic/deploy-k8s/builds?branch=oakrizan%3Aremove-tag-condition
=> Update deploy/kubernetes pipeline execution conditions

x-pack/filebeat/tests/integration/managerV2_test.go
:warning: **Auto-merge is enabled** :warning:
TestRecoverFromInvalidOutputConfiguration was failing due to a closed channel being closed again. Since 0e9c9de was introduced the Filestream input is reporting its status, which leads Filebeat to make more CheckIn calls to the Elastic-Agent. The test could not handle the extra calls.
A boolean atomic flag has been introduced to indicate the channel has already been closed.
None, this PR only fixes a broken test
Run the test that was failing: 
```
mage clean …
```
=> Fix integration tests TestRecoverFromInvalidOutputConfiguration

.buildkite/pipeline.yml
Updated changesets for x-pack/* beats in main pipeline, so that those would be triggered as well, when the correlated beat was changed.
- Relates: https://github.com/elastic/ingest-dev/issues/3565
=> Updated changesets in main beats pipeline for x-pack's

catalog-info.yaml
Updated url for `beats-pipeline-scheduler` pipeline
- Relates: https://github.com/elastic/ingest-dev/issues/3571
BK builds: https://buildkite.com/elastic/beats/builds?branch=oakrizan%3Abeats-daily-url-fix
=> Update URL for beats-pipeline-scheduler

.buildkite/scripts/initCloudEnv.sh
=> [CI] New AWS credentials

.buildkite/deploy/kubernetes/deploy-k8s-pipeline.yml, metricbeat/module/kubernetes/kubernetes.yml
Tests are failing on deploy/k8s pipeline after k8s api was changed. In order to fix pipeline execution updated Kubernetes version to the latest available kind tag per major version of Kubernetes release.
- Relates: https://github.com/elastic/ingest-dev/issues/3519
- Relates: https://github.com/elastic/ingest-dev/issues/3549
BK builds: https://buildkite.com/elastic/deploy-k8s/builds?branch=oakrizan%3Aupdate-k8s-versions
=> Updated kubernetes versions in deploy/k8s pipeline 7.17

.buildkite/aws-tests-pipeline.yml
On 7.17 AWS tests are triggered by different command - aligned it to match original as was on Jenkins
- Relates: https://github.com/elastic/ingest-dev/issues/3403
=> Updated step commands in AWS pipeline on 7.17

CHANGELOG.next.asciidoc, NOTICE.txt, go.mod, go.sum, x-pack/filebeat/docs/inputs/input-cel.asciidoc, x-pack/filebeat/input/cel/input_test.go, x-pack/filebeat/input/cel/integration_test.go
Fixes error reporting for as macros and error messages containing fmt verbs.
---
https://github.com/elastic/mito/compare/v1.13.0...v1.13.1
- Ref #40294
=> mod: update elastic/mito to version v1.13.1

CHANGELOG.next.asciidoc
add changelog for #40096
- Relates #40096
=> add changelog for #40096

.buildkite/pipeline.yml
Makes agentbeat pipelinne be triggered on push to `main` and release branches
-
=> [CI] Package Agentbeat on main and release branches

dev-tools/packaging/templates/ironbank/auditbeat/hardening_manifest.yaml, dev-tools/packaging/templates/ironbank/filebeat/hardening_manifest.yaml, dev-tools/packaging/templates/ironbank/heartbeat/hardening_manifest.yaml, dev-tools/packaging/templates/ironbank/metricbeat/hardening_manifest.yaml, dev-tools/packaging/templates/ironbank/packetbeat/hardening_manifest.yaml
Bump the ubi:9 version to 9.4 in the hardening files
https://github.com/elastic/beats/pull/39988 bumped the version but there are some references for the former version. I don't know if this one has a higher precedence instead.
-
=> ironbank: use 9.4 version

x-pack/filebeat/docs/inputs/input-entity-analytics.asciidoc
=> x-pack/filebeat/docs/input: document activedirectory ad_paging_size

.buildkite/x-pack/pipeline.xpack.metricbeat.yml
Updated issue id in skip condition, since issue was moved to beats repo.
- Relates: https://github.com/elastic/ingest-dev/issues/3637
=> x-pack/metricbeat: updated macOS arm step skip related issue id

.github/workflows/updatecli.d/bump-elastic-stack-snapshot.yml, .github/workflows/updatecli.d/bump-golang-7.17.yml, .github/workflows/updatecli.d/bump-golang.yml
Fix updatecli when accessing the repositories since the `username` is required now.
Similarly resolved in https://github.com/elastic/golang-crossbuild/pull/429
-
=> updatecli: set username

CHANGELOG.asciidoc
Update the Release notes to include known issue
- https://github.com/elastic/beats/issues/40608
- https://github.com/elastic/beats/pull/40609
=> [RELEASE NOTES] Known issue azure-eventhub in Windows / 8.15

filebeat/cmd/root.go, filebeat/fileset/factory.go, filebeat/main.go, filebeat/main_test.go, metricbeat/cmd/root.go, metricbeat/mb/module/runner.go, x-pack/filebeat/cmd/root.go, x-pack/metricbeat/cmd/root.go
refactor filebeat and metric module namespace
This change makes it possible to configure filebeat and metricbeat so
the module namespaces don't collide.  This is necessary so you can
have filebeat and metricbeat in the same process.
The default is unchanged of "module" for both.
There should be zero user impact.
Run:
`mage test` for each beat
- Relates #40110
=> refactor filebeat and metric module namespace

CHANGELOG.next.asciidoc, x-pack/filebeat/input/gcs/client.go
=> x-pack/filebeat/input/gcs: fix handling of default credentials when getting client

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-entity-analytics.asciidoc, x-pack/filebeat/input/entityanalytics/provider/activedirectory/activedirectory.go, x-pack/filebeat/input/entityanalytics/provider/activedirectory/conf.go, x-pack/filebeat/input/entityanalytics/provider/activedirectory/internal/activedirectory/activedirectory.go, x-pack/filebeat/input/entityanalytics/provider/activedirectory/internal/activedirectory/activedirectory_test.go
In cases where there are large numbers of users, the complete set of results may be unreasonably large. This change allows a configuration to be tuned to only include attributes that are required by the user.
- Closes #40482
=> x-pack/filebeat/entityanalytics/provider/activedirectory: allow attribute selection

x-pack/elastic-agent/pkg/agent/application/upgrade/step_download.go
This is a manual backport of https://github.com/elastic/elastic-agent/pull/3682 
The main purpose is to avoid calling the composite downloader when a `--source-uri=file://..`  option has been specified for an `elastic-agent update` command, in favor of using only the `fs.Downloader` implementation
Only the essentials have been backported ignoring features like parsed agent version or download retries which are part of other PRs that have not been backported onto elastic-agent 7.17
-
=> Manual backport of elastic-agent PR #3682 - Use only fs.NewDownloader for file://

.github/workflows/updatecli.d/values.d/ironbank.yml
https://github.com/elastic/beats/pull/40524 removed the need to update `dev-tools/packaging/packages.yml`
-
=> updatecli: ironbank images are not anymore in the package file

CHANGELOG.next.asciidoc
=> add changelog entries for new meraki and panw metricbeat modules

CHANGELOG.next.asciidoc
This PR fixes some issues with CHANGELOG entries introduced by #40868 
-
=> Fix entries in CHANGELOG.next.asciidoc

.buildkite/packaging.pipeline.yml
=> Chore: update packaging pipeline to run automatically on 8.x branch

x-pack/agentbeat/agentbeat.spec.yml
=> add agentbeat spec sections for new meraki and panw modules

NOTICE.txt, go.mod, go.sum
switch from `github.com/adriansr/fsnotify` to `github.com/elastic/fsnotify` to satisfy the custom fsnotify changes needed for Auditbeat.  This is done so an elastic team can be responsible for updating the fork.
run integration tests
-
=> switch to elastic fsnotify fork

.buildkite/x-pack/pipeline.xpack.agentbeat.yml
Added pre-commit check to beats pipelines to validate if no merge-conflicts exist.
- Relates: https://github.com/elastic/beats/pull/40560
BK Builds: https://buildkite.com/elastic/beats-xpack-agentbeat/builds?branch=oakrizan%3Apre-commit-xpack-agentbeat
=> Add pre-commit to x-pack/agentbeat

CHANGELOG.asciidoc
See title
- Documents: https://github.com/elastic/beats/issues/41118
~~## Logs~~
=> Add a known issue entry for 8.15.0 and 8.15.2 referencing https://github.com/elastic/beats/issues/41118

heartbeat/monitors/monitor.go, heartbeat/monitors/monitor_test.go
Fix linting issues introduced by auto-merge of #41077.
- [x ] My code follows the style guidelines of this project
=> [Heartbeat] Fix linting issues introduced by auto-merge #41077

CHANGELOG.next.asciidoc, x-pack/filebeat/input/gcs/scheduler.go, x-pack/filebeat/input/gcs/state.go
- Bug
In cases where GCS reports an error, we were logging the error but not
otherwise making use of the information. When GCS was reporting that a
requested object does not exist this was causing unnecessary log-spam and
not updating the set of failed jobs to remove the object, resulting in future
futile re-attempts to collect the object. When any other error was reported,
the set of failed jobs was not being updated, resulting in continued
re-attempts, even past the maximum retry count.
This fixes both cases by differentiating the two situations, logging only at
debug level when the object is reported to be missing and removing the object
from the failed rework set, and logging at error and increasing the failure
count for all other error cases.
-
=> [filebeat][GCS] - Fixed failed job handling and removed false-positive error logs

.buildkite/auditbeat/auditbeat-pipeline.yml, .buildkite/filebeat/filebeat-pipeline.yml, .buildkite/heartbeat/heartbeat-pipeline.yml, .buildkite/hooks/pre-command, .buildkite/libbeat/pipeline.libbeat.yml, .buildkite/metricbeat/pipeline.yml, .buildkite/packetbeat/pipeline.packetbeat.yml, .buildkite/winlogbeat/pipeline.winlogbeat.yml, .buildkite/x-pack/pipeline.xpack.agentbeat.yml, .buildkite/x-pack/pipeline.xpack.auditbeat.yml, .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml, .buildkite/x-pack/pipeline.xpack.filebeat.yml, .buildkite/x-pack/pipeline.xpack.heartbeat.yml, .buildkite/x-pack/pipeline.xpack.libbeat.yml, .buildkite/x-pack/pipeline.xpack.metricbeat.yml, .buildkite/x-pack/pipeline.xpack.osquerybeat.yml, .buildkite/x-pack/pipeline.xpack.packetbeat.yml, .buildkite/x-pack/pipeline.xpack.winlogbeat.yml
=> Revert "Add test collector for the Beats projects"

.buildkite/auditbeat/auditbeat-pipeline.yml, .buildkite/filebeat/filebeat-pipeline.yml, .buildkite/hooks/pre-command, .buildkite/libbeat/pipeline.libbeat.yml, .buildkite/metricbeat/pipeline.yml, .buildkite/packetbeat/pipeline.packetbeat.yml, .buildkite/x-pack/pipeline.xpack.agentbeat.yml, .buildkite/x-pack/pipeline.xpack.auditbeat.yml, .buildkite/x-pack/pipeline.xpack.filebeat.yml, .buildkite/x-pack/pipeline.xpack.heartbeat.yml, .buildkite/x-pack/pipeline.xpack.metricbeat.yml, .buildkite/x-pack/pipeline.xpack.osquerybeat.yml, .buildkite/x-pack/pipeline.xpack.packetbeat.yml, .buildkite/x-pack/pipeline.xpack.winlogbeat.yml
It is the same as #41172, but this only onboard the projects without an issue.
closes: https://github.com/elastic/ingest-dev/issues/3914
=> Add Filebeat and libbeat in the Beats test collector project

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, libbeat/docs/version.asciidoc
Update the docs for next minor 8.17.0.
Merge after the release branch for 8.16.0 is created.
=> [Release] Update docs for the 8.17.0 release

CHANGELOG.next.asciidoc, x-pack/filebeat/input/streaming/websocket.go
=> x-pack/filebeat/input/streaming: log websocket bad handshake details

CHANGELOG.asciidoc
h/t @lhirlimann
Reviewer please add correct backport labels
=> [DOCS] Fix typo in changelog

CHANGELOG.asciidoc
- Relates https://github.com/elastic/beats/issues/41355
See https://github.com/elastic/beats/issues/41355 for the complete description and mitigation.
=> Document 8.15 memory usage regression as a known issue.

CHANGELOG.asciidoc
h/t @lhirlimann
**For Reviewer:** Not sure how far this needs to be backported
=> [DOCS] Fix typo in changelog 

x-pack/filebeat/input/entityanalytics/provider/jamf/internal/jamf/jamf.go
=> x-pack/filebeat/input/entityanalytics/provider/internal/jamf: remove incorrect comments

.buildkite/hooks/pre-command, catalog-info.yaml
Enabled Slack failure notifications for macOS weekly pipeline
Fiixed BK analytics failure
- Relates: https://github.com/elastic/ingest-dev/issues/3271
=> Adjust weekly macOS pipeline

.buildkite/auditbeat/auditbeat-pipeline.yml, .buildkite/filebeat/filebeat-pipeline.yml, .buildkite/heartbeat/heartbeat-pipeline.yml, .buildkite/metricbeat/pipeline.yml, .buildkite/packetbeat/pipeline.packetbeat.yml, .buildkite/x-pack/pipeline.xpack.auditbeat.yml, .buildkite/x-pack/pipeline.xpack.filebeat.yml, .buildkite/x-pack/pipeline.xpack.heartbeat.yml, .buildkite/x-pack/pipeline.xpack.metricbeat.yml, .buildkite/x-pack/pipeline.xpack.osquerybeat.yml, .buildkite/x-pack/pipeline.xpack.packetbeat.yml
Added concurrency group for all macOS related steps in order to limit orka load.
Only 10 agents can be used simultaneously, while other builds will wait in a queue.
- Relates: https://github.com/elastic/ingest-dev/issues/4337
Buildkite builds: https://buildkite.com/elastic/beats/builds/15093
=> Add concurrency groups for macOS steps

CHANGELOG.next.asciidoc, NOTICE.txt, go.mod, go.sum, x-pack/filebeat/docs/inputs/input-cel.asciidoc, x-pack/filebeat/input/cel/input.go, x-pack/filebeat/input/cel/input_test.go
This brings string formatting and DX improvements.
* sprintf for string formatting
* evaluation failure state dumping
* test coverage support
Wiring for failure dumps and test coverage will come in future changes.
-
=> mod: update elastic/mito to version v1.16.0

libbeat/docs/security/users.asciidoc
adding link to elasticsearch docs for ILM to explain what ILM is based on feedback https://github.com/elastic/docs-feedback/issues/126
=> Update users page to link to ILM where applicable

CHANGELOG.asciidoc
This commit adds known issues for 8.14.x releases
- Documentation for https://github.com/elastic/beats/issues/40178
~~## Logs~~
=> Add known issues for Filebeat 8.14.0

.github/CODEOWNERS
Re-assign the component ownership from `elastic/obs-cloud-monitoring` to `elastic/obs-ds-hosted-services`.
The practical reason is the old `elastic/obs-cloud-monitoring` team only includes a subset of the current `elastic/obs-ds-hosted-services`. So if the person who approves a PR is not included in `elastic/obs-cloud-monitoring`, I have to ping an additional person.
=> Reassign components ownership from obs-cloud-monitoring to obs-ds-hosted-services

.github/CODEOWNERS
=> Update CODEOWNERS according to k8s ownership transfer plan

NOTICE.txt, go.mod, go.sum
Update elastic-agent-libs to v0.17.5
- ~~My code follows the style guidelines of this project~~
- ~~I have made corresponding changes to the documentation~~
N/A
=> Update elastic-agent-libs to v0.17.5

x-pack/agentbeat/agentbeat.spec.yml, x-pack/filebeat/input/unifiedlogs/config.go, x-pack/filebeat/input/unifiedlogs/config_test.go, x-pack/filebeat/input/unifiedlogs/input.go, x-pack/filebeat/input/unifiedlogs/input_test.go
Add some more tests and do necessary changes to include the new input in elastic-agent
=> [filebeat] Add unifiedlogs input to agent

NOTICE.txt, go.mod, go.sum
Update to latest github.com/elastic/elastic-agent-system-metrics
=> [chore] update go.mod

NOTICE.txt
=> [chore] update notice

.github/workflows/mergify-labels-copier.yml
Trying to solve the below statement:
> Currently all merges will have the needs_team label, so trying to find non-triaged PR's gets a bit bloated
Requires https://github.com/elastic/oblt-actions/pull/207
=> github-actions: support for copying the backport labels

.github/workflows/bump-elastic-stack-snapshot.yml, .github/workflows/bump-golang.yml, .github/workflows/notify-stalled-snapshots.yml, .github/workflows/updatecli-compose.yml
https://github.com/elastic/beats/pull/42293 introduced a breaking change.
However, we can use https://github.com/elastic/oblt-actions/tree/main/slack/send if we want to avoid maintaining the thrid-party version. With https://github.com/elastic/oblt-actions we aim to keep backward compatibility 
-
=> github-actions: fix slack inputs

.github/workflows/bump-elastic-stack-snapshot.yml, .github/workflows/bump-golang.yml, .github/workflows/notify-stalled-snapshots.yml, .github/workflows/updatecli-compose.yml
=> Revert "[8.x](backport #42359) github-actions: fix slack inputs"

.pre-commit-config.yaml
Exclude false-positive with `NOTICE.txt`, see See https://github.com/elastic/beats/pull/42377#issuecomment-2605641426
Unfortunately, it seems https://github.com/godror/godror/blob/a95e3761f8141296e98fa9e30fe0ee6f6641f742/LICENSE.md?plain=1#L1-L3 is causing that false positive. I searched for similar `^=======` patterns in `elastic/apm-server`, `elastic/elastic-agent` and `elastic/fleet-server`, but I cannot find it, it's just in the `NOTICE.txt` file in this repository.
I've just raised https://github.com/godror/godror/pull/357 to fix the false positive so we can enable back the NOTICE.txt file
=> pre-commit(merge-conflict): exclude NOTICE.txt

.github/workflows/bump-elastic-stack-snapshot.yml, .github/workflows/bump-golang.yml, .github/workflows/notify-stalled-snapshots.yml, .github/workflows/updatecli-compose.yml
=> Revert "Revert "[8.x](backport #42359) github-actions: fix slack inputs""

x-pack/filebeat/tests/integration/managerV2_test.go
```
!(state == proto.State_HEALTHY || state != proto.State_CONFIGURING || state == proto.State_STARTING
```
can only be true when
```
state == proto.State_CONFIGURING
```
which is probably not the intention around this test.
This PR changes the code to a `Contains()` call.
=> managerV2_test: Fix code smell around state check

x-pack/agentbeat/agentbeat.spec.yml
Adds component files as defined in https://github.com/elastic/elastic-agent/pull/6542
=> Updated spec file for agentbeat to reflect new binary distribution

dev-tools/packaging/templates/docker/Dockerfile.tmpl
Upgrade HB Nodejs to latest LTS version (v18.20.6).
=> [Heartbeat] Upgrade Node to LTS v18.20.6

catalog-info.yaml
This commit updates branch_configuration and branch filters in CI pipeline definitions to support the new 9.* branches.
Can only tested by BK after it gets merged.
=> Update branch filters to include/exclude 9.*

winlogbeat/sys/wineventlog/metadata_store.go
Add nil check since default metadata can be null for some event types
- Relates https://github.com/elastic/beats/issues/42625
=> [winlogbeat] add check for possible null metadata

.buildkite/auditbeat/auditbeat-pipeline.yml, .buildkite/filebeat/filebeat-pipeline.yml, .buildkite/heartbeat/heartbeat-pipeline.yml, .buildkite/metricbeat/pipeline.yml, .buildkite/packetbeat/pipeline.packetbeat.yml, .buildkite/winlogbeat/pipeline.winlogbeat.yml, .buildkite/x-pack/pipeline.xpack.auditbeat.yml, .buildkite/x-pack/pipeline.xpack.filebeat.yml, .buildkite/x-pack/pipeline.xpack.heartbeat.yml, .buildkite/x-pack/pipeline.xpack.libbeat.yml, .buildkite/x-pack/pipeline.xpack.metricbeat.yml, .buildkite/x-pack/pipeline.xpack.osquerybeat.yml, .buildkite/x-pack/pipeline.xpack.packetbeat.yml, .buildkite/x-pack/pipeline.xpack.winlogbeat.yml
=> Revert "ci: remove win 2019 and win 2016 pipelines"

CHANGELOG.next.asciidoc, x-pack/filebeat/input/etw/input.go
Add fallback to the etw input to attach to a session that already exists.
=> [filebeat] Add fallback to attach if session exists

CHANGELOG.next.asciidoc, NOTICE.txt, go.mod, go.sum, x-pack/filebeat/docs/inputs/input-cel.asciidoc, x-pack/filebeat/input/cel/input_test.go
This adds:
- two parameter tail function and its conjugate (elastic/mito#81)
- array sum function (elastic/mito#82)
See title.
-
=> mod: update elastic/mito to version v1.17.0

.buildkite/hooks/pre-command, .buildkite/pipeline.yml
Set "interpolation" to false for buildkite monorepo plugin.
It can cause error in pipelines when "buildkite upload command used.
-
=> Disable interpolation for monorepo plugin

CHANGELOG.next.asciidoc, filebeat/input/winlog/input.go, winlogbeat/beater/eventlogger.go, winlogbeat/eventlog/runner.go
Report status to elastic-agent
=> [filebeat] Winlog input reports status to elastic-agent

metricbeat/module/windows/perfmon/data_test.go
Counters is a map and when checking the last assertions order is not guaranteed. This fixes it.
=> [metricbeat] Fix perfmon test

filebeat/testing/integration/sample_test.go, libbeat/testing/integration/integration.go, libbeat/testing/integration/run_beat.go
* Add `PrintConfigOnFail` option
* Fix config file permissions
* Fix printing expected exit code
* Fix typo
=> Improve integration test framework

x-pack/metricbeat/module/mssql/test_mssql.py, x-pack/metricbeat/module/sql/query/test_sql_mssql.py
Skip the flaky tests in https://github.com/elastic/beats/issues/43100 and https://github.com/elastic/beats/issues/43099.
=> Disable flaky mssql tests

CHANGELOG.next.asciidoc, x-pack/filebeat/input/azureblobstorage/client.go
=> x-pack/filebeat/input/azureblobstorage: prevent key logging in fetch operation

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-http-endpoint.asciidoc, x-pack/filebeat/input/http_endpoint/config.go, x-pack/filebeat/input/http_endpoint/input.go, x-pack/filebeat/input/http_endpoint/validate.go
=> x-pack/filebeat/input/http_endpoint: allow limiting body size

.github/workflows/check-dev-tools.yml
This commit is a forward port of the change introduced in 8.x (and earlier) via https://github.com/elastic/beats/pull/43090 to help reduce potential conflicts with future backports.
Can only be tested in CI
=> Align setup-python action with prior branches

.buildkite/pipeline.yml
Adds a trigger to `Serverless beats tests`, which are located in the elastic-agent repository. 
Note: This PR is tightly coupled with https://github.com/elastic/elastic-agent/pull/7184. The https://github.com/elastic/elastic-agent/pull/7184 must be merged first.
The `Serverless beats tests` will be triggered by pushes to main/release branches. 
-
=> [CI] Trigger Serverless beats tests in the agent repo

metricbeat/module/kafka/broker/broker_integration_test.go, metricbeat/module/kafka/consumer/consumer_integration_test.go, metricbeat/module/kafka/consumergroup/consumergroup_integration_test.go, metricbeat/module/kafka/partition/partition_integration_test.go, metricbeat/module/kafka/producer/producer_integration_test.go
https://github.com/elastic/beats/issues/42808
-
=> Skip flaky kafka module test

.buildkite/winlogbeat/pipeline.winlogbeat.yml, .buildkite/x-pack/pipeline.xpack.winlogbeat.yml
Add win2025 to winlogbeat CI
Closes https://github.com/elastic/beats/issues/43244
=> [ci] Add win2025 to winlogbeat CI

x-pack/agentbeat/agentbeat.spec.yml
Add entry for aerospike/metrics input in agentbeat spec
This should not have disruptive impact on users
- https://github.com/elastic/integrations/issues/9344
Monitor Aerospike via Elastic Agent, create an (experimental) Aerospike integration
=> Add aerospike input in agentbaet-spec.yml

.buildkite/packaging.pipeline.yml
Enable DRA for creating the packaging for `darwin/arm64` on arm64.
A follow up from https://github.com/elastic/beats/pull/43280
-
=> bk(dra): split arm64 for linux and darwin from amd64

CHANGELOG.next.asciidoc, packetbeat/protos/tls/tls.go, packetbeat/protos/tls/tls_test.go, packetbeat/tests/system/golden/established_tls-expected.json, packetbeat/tests/system/golden/tls_1_3-expected.json, packetbeat/tests/system/golden/tls_all_options-expected.json, packetbeat/tests/system/golden/tls_no_certs-expected.json, packetbeat/tests/system/golden/tls_not_detailed-expected.json
Export `tls.server.ja3s` as advertised by the Network Traffic integration.
=> Set server ja3s

.github/workflows/updatecli.d/bump-golang.yml
https://github.com/elastic/beats/pull/42705 removed the golang-version in `.golangci.yml` but the `bump-golang.yml` updatecli pipeline was not updated.
This will fix the issues with https://github.com/elastic/beats/actions/runs/13929961921
Eventually, 8.x might be the future `7.17`... hence, I decided to backport it too.
-
=> updatecli: remove .golangci.yml from bump-golang.yml

x-pack/filebeat/input/streaming/crowdstrike.go
=> x-pack/filebeat/input/streaming: add debug logging for stream refresh and requests

metricbeat/module/system/process/process_test.go
```
fix metricbeat/module/system/process TestFetchDegradeOnPartial
metricbeat/module/system/process TestFetchDegradeOnPartial is not platform specific. 
Therefore it does not need to run on every possible platform.
Skip the test when running on:
- CI on windows: it runs as admin and no error is returned
- unix-like as root: it does not return any error
```
- N/A
Run the test several time as root on non-windows or on Windows as admin
```
❯ go test -run …
```
=> [Flaky Test] Fix metricbeat/module/system/process TestFetchDegradeOnPartial

.github/workflows/xpack-auditbeat-macos-unit-tests.yml
Updated workflow filename in paths section.
- Relates: https://github.com/elastic/beats/issues/43439
=> xpack/auditbeat: update push paths

CHANGELOG.next.asciidoc, metricbeat/module/vsphere/_meta/docs.asciidoc
=> [metricbeat][vsphere] update list of supported vSphere versions

CHANGELOG.next.asciidoc, dev-tools/packaging/templates/docker/Dockerfile.tmpl
=> Restore maintainer label to container images

.github/workflows/golangci-lint.yml, NOTICE.txt, go.mod, go.sum
Update elastic-agent-libs to `v0.19.0` to update the golangci-lint version and pin the full commit hash for the GitHub action.
```
mage llc
```
- https://github.com/elastic/elastic-agent-libs/pull/299
~~##Logs~~
=> Update elastic-agent-libs to `v0.19.0`

metricbeat/module/windows/service/service_integration_test.go
The function signature of NewReader was changed recently. This PR updates the integration test to pass the testing logger.
=> [windows/service] Fix integration test

.github/workflows/auditbeat-macos-unit-tests.yml, .github/workflows/filebeat-macos-unit-tests.yml, .github/workflows/heartbeat-macos-unit-tests.yml, .github/workflows/metricbeat-macos-unit-tests.yml, .github/workflows/packetbeat-macos-unit-tests.yml, .github/workflows/xpack-auditbeat-macos-unit-tests.yml, .github/workflows/xpack-filebeat-macos-unit-tests.yml, .github/workflows/xpack-heartbeat-macos-unit-tests.yml, .github/workflows/xpack-metricbeat-macos-unit-tests.yml, .github/workflows/xpack-osquerybeat-macos-unit-tests.yml, .github/workflows/xpack-packetbeat-macos-unit-tests.yml, x-pack/filebeat/input/unifiedlogs/input_test.go
Updated paths for macOS wokrflows to trigger those correctly when files changed.
- Closes: https://github.com/elastic/beats/issues/43775
=> Fix paths for macOS GH Workflows

docs/extend/community-beats.md
=> Revert "docs: test automation"

.github/CODEOWNERS
Change code owners for the docs folder to have @elastic/ingest-docs as reviewer.
-
=> CODEOWNERS: change code owner for docs folder

docs/extend/testing.md
```
improve docs on how to run integration tests
```
- N/A
- N/A
=> Improve docs on how to run integration tests

.buildkite/filebeat/filebeat-pipeline.yml, .buildkite/heartbeat/heartbeat-pipeline.yml, .buildkite/libbeat/pipeline.libbeat.yml, .buildkite/metricbeat/pipeline.yml, .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml, .buildkite/x-pack/pipeline.xpack.filebeat.yml, .buildkite/x-pack/pipeline.xpack.heartbeat.yml, .buildkite/x-pack/pipeline.xpack.libbeat.yml, .buildkite/x-pack/pipeline.xpack.metricbeat.yml, .buildkite/x-pack/pipeline.xpack.osquerybeat.yml
```
CI: collect integration test failures folders for all beats
```
- N/A
- check a [previous build](https://buildkite.com/elastic/beats-xpack-filebeat/builds/13542/steps?jid=01961f33-2bdb-4286-b9e4-7ee4241130e4) with a testing failing on purpose
- N/A
=> Collect integration test failures folders for all beats

CHANGELOG.next.asciidoc, docs/reference/filebeat/filebeat-input-entity-analytics.md, x-pack/filebeat/input/entityanalytics/provider/okta/conf.go, x-pack/filebeat/input/entityanalytics/provider/okta/okta.go
=> x-pack/filebeat/input/entityanalytics/provider/okta: add support for pagination batch size

docs/reference/filebeat/file-identity.md, docs/reference/filebeat/filebeat-input-unifiedlogs.md, docs/reference/metricbeat/_metricsets_70.md, docs/reference/metricbeat/exported-fields-benchmark.md, docs/reference/metricbeat/exported-fields-openai.md, docs/reference/metricbeat/metricbeat-metricset-benchmark-info.md, docs/reference/metricbeat/metricbeat-metricset-openai-usage.md, docs/reference/metricbeat/metricbeat-metricset-windows-wmi.md, docs/reference/metricbeat/metricbeat-module-benchmark.md, docs/reference/metricbeat/metricbeat-module-openai.md, docs/release-notes/index.md
Updates `mapped_pages` to be compatible with the _View previous version_ link.
=> [docs] Update mapped_pages

docs/reference/auditbeat/auditbeat-installation-configuration.md, docs/reference/auditbeat/configuration-instrumentation.md, docs/reference/filebeat/configuration-instrumentation.md, docs/reference/filebeat/filebeat-installation-configuration.md, docs/reference/heartbeat/configuration-heartbeat-options.md, docs/reference/heartbeat/configuration-instrumentation.md, docs/reference/heartbeat/heartbeat-installation-configuration.md, docs/reference/libbeat/upgrading.md, docs/reference/metricbeat/configuration-instrumentation.md, docs/reference/metricbeat/metricbeat-installation-configuration.md, docs/reference/packetbeat/configuration-instrumentation.md, docs/reference/packetbeat/packetbeat-installation-configuration.md, docs/reference/winlogbeat/configuration-instrumentation.md, docs/reference/winlogbeat/winlogbeat-installation-configuration.md
Related to https://github.com/elastic/docs-content/pull/1069
Updates links to APM, Synthetics, and Uptime pages in elastic/docs-content.
=> [docs] Update APM, Synthetics, Uptime links

CHANGELOG.next.asciidoc, NOTICE.txt, docs/reference/filebeat/filebeat-input-cel.md, go.mod, go.sum, x-pack/filebeat/input/cel/config.go, x-pack/filebeat/input/cel/input.go, x-pack/filebeat/input/cel/input_test.go
```
mod,x-pack/filebeat/input/cel: bump mito version to v1.18.0
This adds support for:
- global header configuration
- maximum response body size checks
```
-
=> mod,x-pack/filebeat/input/cel: bump mito version to v1.18.0

docs/release-notes/deprecations.md, docs/release-notes/known-issues.md
- Specifies no known issue and deprecations for 9.0.0
- Adds short description to known issues page
=> [DOCS] Specifies no deprecations and known issues for 9.0.0

docs/release-notes/index.md
Closes https://github.com/elastic/docs-content/issues/1120
-
=> Set navigation title for release notes

filebeat/input/filestream/internal/task/group_test.go, filebeat/module/apache/access/test/test-vhost.log-expected.json, filebeat/module/apache/access/test/test.log-expected.json, filebeat/module/apache/access/test/ubuntu-2.2.22.log-expected.json, filebeat/module/iis/access/test/test-x-forward-for-extended.log-expected.json, filebeat/module/iis/access/test/test.log-expected.json, filebeat/module/nginx/access/test/access.log-expected.json, filebeat/module/nginx/access/test/test-with-host.log-expected.json, filebeat/module/nginx/access/test/test.log-expected.json, filebeat/module/nginx/ingress_controller/test/test.log-expected.json, filebeat/tests/system/test_modules.py, libbeat/tests/integration/dashboard_test.go, testing/environments/docker/logstash/pipeline-xpack/default.conf, testing/environments/docker/logstash/pipeline/default.conf, testing/environments/snapshot.yml, x-pack/filebeat/module/aws/cloudtrail/test/console-login-json.log-expected.json, x-pack/filebeat/module/fortinet/firewall/test/utm.log-expected.json, x-pack/filebeat/module/gcp/audit/test/audit-log-entries.json.log-expected.json, x-pack/filebeat/module/o365/audit/test/04-sharepoint.log-expected.json, x-pack/filebeat/module/o365/audit/test/06-sharepointfileop.log-expected.json, x-pack/filebeat/module/o365/audit/test/14-sp-sharing-op.log-expected.json, x-pack/filebeat/module/o365/audit/test/15-azuread-sts-logon.log-expected.json, x-pack/filebeat/module/o365/audit/test/25-ms-teams-groups.log-expected.json, x-pack/filebeat/module/okta/system/test/okta-system-test.json.log-expected.json, x-pack/filebeat/module/sophos/xg/test/firewall.log-expected.json, x-pack/filebeat/module/suricata/eve/test/eve-small.log-expected.json
Reverts elastic/beats#43916
I missed to change the stack version to 8.x
=> Revert "[8.x](backport #43711) Fix filebeat module golden files and update elastic stack version for testing"

NOTICE.txt, go.mod, go.sum
Upgrade `sdk/messaging/azeventhubs` to 1.3.1 to get the following benefit:
> Remove a memory leak that could occur when the ConsumerClient was unable to open a partition.
To learn more, see:
https://github.com/Azure/azure-sdk-for-go/blob/sdk/messaging/azeventhubs/v1.3.1/sdk/messaging/azeventhubs/CHANGELOG.md#131-2025-03-11
=> [azure-eventhub] Bump sdk/messaging/azeventhubs to 1.3.1

.buildkite/pipeline.yml, catalog-info.yaml
Fixes a regression https://github.com/elastic/beats/pull/44019/files
-
=> catalog-info: add missing scheduler id and validate catalog in the CI

metricbeat/module/windows/perfmon/perfmon_test.go, metricbeat/module/windows/perfmon/reader_integration_test.go
Adds testing logger to the metricbeat perfmon tests.  This is necessary because the signature for NewReader changed in #43973
None, change to integration test
Run Windows integration tests
- Relates #43973
=> add testing logger to perfmon_test.go

docs/release-notes/known-issues.md, winlogbeat/eventlog/config.go, winlogbeat/eventlog/wineventlog.go, winlogbeat/eventlog/wineventlog_test.go
Add known issue related to windows server 2025 and its workaround
=> Add ws2025 known issue and workaround

filebeat/input/filestream/environment_test.go
This commit improves Filestream's inputTestingEnvironment:
1. Use an in-memory logger instead of a global one
2. On failure, the logs are saved on a temporary folder for easy of debugging
3. Fixing all lint warnings
```
cd filestream
mage BuildSystemTestBinary
go test -count=1 -tags=integration ./filestream/...
```
- Splits from https://github.com/elastic/beats/pull/43978
~~## Logs~~
=> Filestream integration test improvements

CHANGELOG.next.asciidoc, filebeat/input/filestream/input.go
Under certain circumstances this message becomes too frequent.
Closes https://github.com/elastic/beats/issues/35022
=> Log the reader closed message at a lower level

CHANGELOG.next.asciidoc, x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/okta.go
```
x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta: fix endpoint
A typo introduced an error in the endpoint used by GetGroupRoles, this
repairs that. Also fix documentation references.
This function is currently not used by any beats code.
```
-
=> x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta: fix endpoint

.github/workflows/updatecli.d/bump-golang-7.17.yml
https://github.com/elastic/beats/pull/43362 removed the golang-version in `.golangci.yml` but the `bump-golang-7.17.yml` updatecli pipeline was not updated.
This will fix the issues with https://github.com/elastic/beats/actions/runs/13929961921
Eventually, 8.x might be the future `7.17`... hence, I decided to backport it too.
- Similarly solved for main at https://github.com/elastic/beats/pull/43362
- Caused by https://github.com/elastic/beats/pull/43362
=> updatecli: remove .golangci.yml from bump-golang-7.17.yml

deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, docs/release-notes/deprecations.md, libbeat/docs/version.asciidoc
Updates docs versions to 9.0.1.
=> docs: update docs version 9.0.1

.buildkite/aws-tests-pipeline.yml, .buildkite/scripts/initCloudEnv.sh, .buildkite/x-pack/pipeline.xpack.filebeat.yml, .buildkite/x-pack/pipeline.xpack.metricbeat.yml
Avoid using service accounts and use the Keyless/OIDC approach
Uses https://github.com/elastic/oblt-aws-auth-buildkite-plugin
ONLY IN THE CI
- See [AWS Tests build](https://buildkite.com/elastic/beats-aws-tests/builds/3009)
- See [x-pack/metricbeat AWS step](https://buildkite.com/elastic/beats-xpack-metricbeat/builds/15605#0196a073-42d9-4081-ada6-649267d3ce68)
-
=> bk: use OIDC to create AWS cloud resources

CHANGELOG.next.asciidoc, x-pack/filebeat/input/entityanalytics/provider/activedirectory/activedirectory.go, x-pack/filebeat/input/entityanalytics/provider/activedirectory/conf.go, x-pack/filebeat/input/entityanalytics/provider/activedirectory/internal/activedirectory/activedirectory.go, x-pack/filebeat/input/entityanalytics/provider/activedirectory/internal/activedirectory/activedirectory_test.go, x-pack/filebeat/input/entityanalytics/provider/activedirectory/statestore.go
See title.
> [!NOTE]
> Best reviewed commit-wise.
- For elastic/integrations#12950
- Closes elastic/integrations#13914
=> x-pack/filebeat/input/entityanalytic/provider/activedirectory: add support for device entities

.buildkite/x-pack/pipeline.xpack.libbeat.yml
Bump check/update step disk size to 40 GB. The default 10GB are not enough
-
=> [CI] x-pack/libbeat: Bump check/update step disk size

CHANGELOG.next.asciidoc, x-pack/filebeat/input/lumberjack/input.go, x-pack/filebeat/input/lumberjack/server.go, x-pack/filebeat/input/lumberjack/server_test.go
=> x-pack/filebeat/input/lumberjack: add fleet status update functionality

CHANGELOG.next.asciidoc, x-pack/filebeat/input/http_endpoint/handler.go, x-pack/filebeat/input/http_endpoint/handler_test.go, x-pack/filebeat/input/http_endpoint/input.go
=> x-pack/filebeat/input/http_endpoint: add fleet input status updating

CHANGELOG.next.asciidoc, x-pack/filebeat/input/streaming/crowdstrike.go, x-pack/filebeat/input/streaming/crowdstrike_test.go, x-pack/filebeat/input/streaming/input.go, x-pack/filebeat/input/streaming/websocket.go
=> x-pack/filebeat/input/streaming: add fleet status update functionality

CHANGELOG.next.asciidoc, x-pack/filebeat/input/gcppubsub/input.go
=> x-pack/filebeat/input/gcppubsub: add status updating

CHANGELOG.next.asciidoc, x-pack/filebeat/input/gcs/decoding_test.go, x-pack/filebeat/input/gcs/input.go, x-pack/filebeat/input/gcs/input_stateless.go, x-pack/filebeat/input/gcs/job.go, x-pack/filebeat/input/gcs/scheduler.go
=> x-pack/filebeat/input/gcs: add status updating

.buildkite/pipeline.yml
Always run the builds if changes are made to the file called `.go-version`.
-
=> bk: run always if changes in the .go-version

CHANGELOG.next.asciidoc, x-pack/filebeat/input/entityanalytics/provider/okta/okta_test.go, x-pack/filebeat/input/entityanalytics/provider/okta/statestore.go
See title.
- For elastic/integrations#12658
- Ref #42737
=> x-pack/filebeat/input/entityanalytics/provider/okta: publish DEPROVISIONED entities

.buildkite/auditbeat/auditbeat-pipeline.yml, .buildkite/filebeat/filebeat-pipeline.yml, .buildkite/heartbeat/heartbeat-pipeline.yml, .buildkite/libbeat/pipeline.libbeat.yml, .buildkite/metricbeat/pipeline.yml, .buildkite/packaging.pipeline.yml, .buildkite/packetbeat/pipeline.packetbeat.yml, .buildkite/winlogbeat/pipeline.winlogbeat.yml, .buildkite/x-pack/elastic-agent/pipeline.xpack.elastic-agent.package.yml, .buildkite/x-pack/elastic-agent/scripts/steps/setenv.sh, .buildkite/x-pack/pipeline.xpack.auditbeat.yml, .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml, .buildkite/x-pack/pipeline.xpack.filebeat.yml, .buildkite/x-pack/pipeline.xpack.heartbeat.yml, .buildkite/x-pack/pipeline.xpack.metricbeat.yml, .buildkite/x-pack/pipeline.xpack.osquerybeat.yml, .buildkite/x-pack/pipeline.xpack.packetbeat.yml, .buildkite/x-pack/pipeline.xpack.winlogbeat.yml, .github/workflows/golangci-lint.yml, .golangci.yml, dev-tools/mage/crossbuild.go
This is an amalgamated commit of the following backports that were missing from 7.17:
- https://github.com/elastic/beats/pull/43026
- https://github.com/elastic/beats/pull/43280
- https://github.com/elastic/beats/pull/43387
- https://github.com/elastic/beats/pull/43406
- https://github.com/elastic/beats/pull/42705
=> fix: amalgamated commit with missing buildkite backports

CHANGELOG.next.asciidoc, docs/reference/filebeat/filebeat-input-httpjson.md, x-pack/filebeat/input/httpjson/config_request.go, x-pack/filebeat/input/httpjson/config_response.go, x-pack/filebeat/input/httpjson/cursor.go, x-pack/filebeat/input/httpjson/cursor_test.go, x-pack/filebeat/input/httpjson/input.go, x-pack/filebeat/input/httpjson/pagination.go, x-pack/filebeat/input/httpjson/policy.go, x-pack/filebeat/input/httpjson/policy_test.go, x-pack/filebeat/input/httpjson/rate_limiter.go, x-pack/filebeat/input/httpjson/rate_limiter_test.go, x-pack/filebeat/input/httpjson/request.go, x-pack/filebeat/input/httpjson/request_test.go, x-pack/filebeat/input/httpjson/response.go, x-pack/filebeat/input/httpjson/split.go, x-pack/filebeat/input/httpjson/split_test.go, x-pack/filebeat/input/httpjson/transform.go, x-pack/filebeat/input/httpjson/transform_append.go, x-pack/filebeat/input/httpjson/transform_append_test.go, x-pack/filebeat/input/httpjson/transform_delete.go, x-pack/filebeat/input/httpjson/transform_delete_test.go, x-pack/filebeat/input/httpjson/transform_registry.go, x-pack/filebeat/input/httpjson/transform_set.go, x-pack/filebeat/input/httpjson/transform_set_test.go, x-pack/filebeat/input/httpjson/transform_test.go, x-pack/filebeat/input/httpjson/value_tpl.go, x-pack/filebeat/input/httpjson/value_tpl_test.go
=> x-pack/filebeat/input/httpjson: add fleet input status updating

docs/release-notes/index.md
Ports https://github.com/elastic/beats/pull/44971 to Markdown / Release notes.
=> [docs] Add 9.0.3 release notes

metricbeat/module/windows/wmi/wmi.go
Make sure we return the instance class
- This is a tiny extract of: https://github.com/elastic/beats/pull/44579
=> [Metricbeat][WMI]Make sure we differentiate between instance class and query class

x-pack/filebeat/fbreceiver/receiver_test.go
Relates https://github.com/elastic/beats/issues/45057
=> [fbreceiver] - Skip flaky TestReceiverDegraded

.github/CODEOWNERS
For some reason the precedence is not correct here :/
-
=> codeowners: update .github folder

dev-tools/packaging/templates/ironbank/auditbeat/Dockerfile, dev-tools/packaging/templates/ironbank/filebeat/Dockerfile, dev-tools/packaging/templates/ironbank/heartbeat/Dockerfile, dev-tools/packaging/templates/ironbank/metricbeat/Dockerfile, dev-tools/packaging/templates/ironbank/packetbeat/Dockerfile
=> [8.18] Bump ironbank 9.6 

docs/reference/filebeat/filebeat-input-cel.md
```
docs/reference/filebeat/cel: improve documentation
* make use of variable substitution for mito version
* add missing version to AWS helpers
* use ASE spelling in user-facing documentation
* add applies_to tags to language API and config fields to make use of
cumulative documentation
```
> [!NOTE]
> I have slightly mixed application here; I have a global 8.6.0 applies_to that is intended to apply to all the page, but I have also added essentially redundant 8.6.0 applies_to tags to each of the language API headers purely to bring that closer to the reader. I have not put any applies_to on code examples on the basis that the tagged headings already indicate that.
>
> ~For all the existing functionality I have marked the first version as the 8.x.y version rather than the 9.x.y version …
=> docs/reference/filebeat/cel: improve documentation

docs/reference/auditbeat/auditbeat-installation-configuration.md, docs/reference/auditbeat/auditbeat-starting.md, docs/reference/filebeat/filebeat-installation-configuration.md, docs/reference/filebeat/filebeat-starting.md, docs/reference/heartbeat/heartbeat-installation-configuration.md, docs/reference/metricbeat/metricbeat-installation-configuration.md, docs/reference/metricbeat/metricbeat-starting.md, docs/reference/packetbeat/packetbeat-installation-configuration.md, docs/reference/packetbeat/packetbeat-starting.md, docs/reference/winlogbeat/configuration-logging.md, docs/reference/winlogbeat/configuration-winlogbeat-options.md, docs/reference/winlogbeat/winlogbeat-installation-configuration.md, docs/reference/winlogbeat/winlogbeat-starting.md
Related: https://github.com/elastic/docs-content-internal/issues/68
Closes: https://github.com/elastic/docs-content-internal/issues/92
=> Doc: Add applies_to label for 9.1 content

.github/CODEOWNERS
Otherwise they can become a blocker.
So, I prefer we only have one CI team as blocker
-
=> Update CODEOWNERS: remove ci-contractors

auditbeat/module/file_integrity/kprobes/monitor_test.go
See title
```
go test -count=1 -v -run=Test_Monitor/TestNew ./auditbeat/module/file_integrity/kprobes 
```
Make sure the test is skipped.
- Flaky Test https://github.com/elastic/beats/issues/45827
~~## Logs~~
=> Skip Auditbeat flaky test Test_Monitor/TestNew

docs/reference/index.md
Follow-up to fix link format error in #46104
=> Correct link to beats overview pages

CHANGELOG.next.asciidoc
See title
- Changelog for https://github.com/elastic/beats/pull/45881
~~## Logs~~
=> Add changelog for PR #45881

x-pack/dockerlogbeat/readme.md
This PR aims to add few missing steps from current documentation on how to build elastic-logging plugin from source code
=> Add more info to dockerlogbeat README

CHANGELOG.next.asciidoc, x-pack/osquerybeat/internal/distro/distro.go
=> [osquerybeat] Upgrade osquery to 5.18.1

x-pack/libbeat/management/simple_input_config_test.go
```
It can happen that the manager only finishes to shutdown after the test has finished, that is somehow expected because ManagerV2.Stop does not block. However this can cause a panic if the logger passed to the manager is backed by t.Log.
This commit fixes it by using a noop logger.
```
-
=> Use noop logger instead of logger backed by t.Log

.github/CODEOWNERS
Robots team don't own those files.
-
=> CODEOWNERS: ci robots team don't own those files

.github/workflows/fragment-in-pr.yml
=> [DO NOT MERGE BEFORE 9.2 FF] New CI check to verify if a changelog fragment is in the PR
