.github/workflows/bump-golang.yml
Separate the `auto-bump` in two different jobs so that if one of them fails then it's possible to re-run it.
Run daily so if the golang-crossbuild generated the release earlier there is no need to wait for up to 6 days until it's there
-
=> ci(action): auto-bump daily and split in two jobs

CHANGELOG.asciidoc
Reverts https://github.com/elastic/beats/pull/37407
The notice should apply to 8.11.3 only.
=> Revert 37407 to remove security notice in 8.11.2 RN

CHANGELOG.next.asciidoc, heartbeat/monitors/active/icmp/stdloop.go, heartbeat/monitors/monitor.go, heartbeat/monitors/task.go, heartbeat/monitors/wrappers/monitorstate/esloader.go, heartbeat/monitors/wrappers/monitorstate/tracker.go, x-pack/heartbeat/monitors/browser/sourcejob.go, x-pack/heartbeat/monitors/browser/synthexec/synthexec.go, x-pack/heartbeat/monitors/browser/synthexec/synthtypes.go
+ Fix the formatting of the logs on HB for state loader and monitor wrappers. 
```
could not load prior state from elasticsearch after %d attempts, will create new state for monitor: %s3test-monitor-id
```
=> fix: adjust formatting for heartbeat monitor and state loader

CHANGELOG.next.asciidoc, heartbeat/security/policy_linux_arm64.go
Duplicate `pwrte64` syscall is preventing the filter from being installed.
1. Build `arm` HB locally and execute.
- Closes https://github.com/elastic/beats/issues/37367
=> [Heartbeat] Remove duplicate seccomp syscalls

filebeat/input/filestream/input.go, filebeat/input/filestream/input_test.go
Before it was only testing for a single file not the tests support many files.
During test runs with the race detector a data race was found and fixed.
This script will generate PDFs with CPU and memory profiles for each test case:
```sh
go test -v -run=none -bench='BenchmarkFilestream/single_file/inode_throughput' -benchmem -benchtime=100x -cpuprofile=single-inode-cpu-profile.bin -memprofile=single-inode-mem-profile.bin
go tool pprof -pdf single-inode-cpu-profile.bin > single-inode-cpu-profile.pdf
go tool pprof -pdf …
```
=> Add filestream benchmarks for many files case, fix data race

CHANGELOG.next.asciidoc, dev-tools/packaging/templates/windows/install-service.ps1.tmpl
If the user install winlogbeat accordingly the [official documentation](https://www.elastic.co/guide/en/beats/winlogbeat/current/winlogbeat-installation-configuration.html#installation) (executing install-service-winlogbeat.ps1), winlogbeat service will search for the keystore file into ProgramData (C:\ProgramData\winlogbeat), but, to create a keystore, it is expected to execute `winlogbeat.exe keystore add` inside Program Files, so, winlogbeat put the keystore into `.\data` `(C:\Program Files\data)`
Setting keystore path to `$workdir` `(c:\program files)` for any beats running as Windows Services solves this problem and don't affect users who do not use a keystore.
Version:
winlogbeat version 8.11.1 (amd64), libbeat 8.11.1
O.S: Windows
Related to issue …
=> Winlogbeat/Windows Services: changed default keystore path to program files

deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/filebeat/filebeat-configmap.yaml, dev-tools/kubernetes/filebeat/manifest.debug.yaml, dev-tools/kubernetes/filebeat/manifest.run.yaml
This PR is a fix to a bug introduced in https://github.com/elastic/beats/pull/37401.
Defining the `id` as
```yaml
id: kubernetes-container-logs-${data.kubernetes.pod.name}-${data.kubernetes.container.id}
```
Causes the error:
```logs
{"log.level":"error","@timestamp":"2024-01-04T13:13:02.933Z","log.origin":{"file.name":"instance/beat.go","file.line":1307},"message":"Exiting: failed to read input configuration: failed to unpack input configuration: missing field accessing 'filebeat.inputs.0.id' (source:'/etc/filebeat.yml')","service.name":"filebeat","ecs.version":"1.6.0"}
Exiting: failed to read input configuration: failed to unpack input configuration: missing field accessing 'filebeat.inputs.0.id' (source:'/etc/filebeat.yml')
```
We need to remove the fields `${data.*}` in the `id` to …
=> [Filebeat] Fix id for config map 

libbeat/publisher/pipeline/client_test.go
There were some instances of this code producing infinite loops. Now there is a test case for the processing pipeline covering this.
```sh
cd ./libbeat/publisher/pipeline
go test -run '.*TestClient.*/.*infinite.*'
```
- Relates #34792
=> Add test for handling processing errors while publishing events

metricbeat/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
Merge only after the release of 8.11.4.
=> [Release] Update test environments for 8.11.5

CHANGELOG.next.asciidoc, x-pack/filebeat/input/httpjson/request.go, x-pack/filebeat/input/httpjson/request_test.go
```
x-pack/filebeat/input/httpjson: Fix basic auth nil pointer deref (#37591)
For chained requests, setting user and password values for basic
authentication via a pointer to a requestFactory struct was done before
the struct was initialized, resulting in a nil pointer dereference and
runtime panic. Moving it to after the initialization resolved the issue.
```
For manual testing, there's a `filebeat.yml` file below that will trigger the issue. The input fails before any requests are made.
Run `./filebeat -c filebeat.yml -v` and check the logs for the error. When the requests are successfully made they can be seen on [that webhook's page](https://webhook.site/#!/8d8e2d6d-4a79-4b9c-8b8d-f6641588ac52/684e1c06-a38b-4564-9aa5-0f6c0f891d1a).
```yaml
- type: httpjson
id: …
```
=> x-pack/filebeat/input/httpjson: Fix nil pointer deref

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-httpjson.asciidoc, x-pack/filebeat/input/httpjson/input_test.go, x-pack/filebeat/input/httpjson/request.go
See title.
- Closes elastic/integrations#8676
=> x-pack/filebeat/input/httpjson: provide an approach to use complete URL replacements

.github/CODEOWNERS
Explicitly assign the ownership of AWS, Azure and GCP metricsets to the owning team.
Previously, `/x-pack/metricbeat/module/` was assigned to @elastic/integrations, allowing our team to work on these modules independently.
As a side-effect of a recent [change](https://github.com/elastic/beats/commit/8fe2f53bf1613bf6c0566a7e8e7afda785c51770#diff-3d36a1bf06148bc6ba1ce2ed3d19de32ea708d955fed212c0d27c536f0bd4da7L180), the CODEOWNERS now [falls back](https://github.com/elastic/beats/blob/95f0f85a3edd45799b9928ee48fe00be49e09431/.github/CODEOWNERS#L176C1-L176C1) the AWS, Azure and GCP metricsets to the @elastic/elastic-agent-data-plane.
This change avoids involving additional teams when we only need to update the metricset internals. For example, see …
=> Update CODEOWNERS to update cloud metrics ownership

CHANGELOG.next.asciidoc, x-pack/metricbeat/module/azure/data.go, x-pack/metricbeat/module/azure/data_test.go
Fix mapping of metric values from `Metric` to `KeyValuePoint`. Unfortunately, I didn't notice the code for `min` and `max` aggregations picked up the value from the `avg` field. This is a silly mistake with nasty consequences.
I added a basic unit test to check the expected behavior. 
Set up the Azure Monitor metricset with the following Metricbeat module configuration:
```
- module: azure
metricsets:
- monitor
enabled: true
period: 300s
client_id: '...'
client_secret: '...'
tenant_id: '...'
subscription_id: '...'
refresh_list_interval: 600s
resources:
- resource_query: resourceType eq 'Microsoft.Cache/redis'
metrics:
- dimensions:
- name: ShardId
value: '*'
- name: Port
value: '*'
- name: Primary
value: '*'
ignore_unsupported: true
name:
- allcachehits
- allcachemisses
- allcacheRead
- …
```
=> Fix value mapping for min and max aggregation type in Azure Monitor

CHANGELOG.next.asciidoc
This update obsoletes support for Windows 8.1.
=> Move Go 1.21 update to breaking changes section of the release notes.

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-entity-analytics.asciidoc, x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/graph/graph.go, x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/graph/graph_test.go
The `$select` optional queries were previously hardcoded. Make these accessible via a configuration group at the root level.
-
=> x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/graph: add support for user-defined query selection

catalog-info.yaml
fix the pipeline initialisation - https://buildkite.com/elastic/beats-packetbeat/builds/1#018d36a9-d0ff-47a9-8f23-5cc47472366e
changed the pipeline name
=> fix the packetbeat bk pipeline init config

auditbeat/tests/system/requirements.txt, dev-tools/requirements.txt, heartbeat/tests/system/requirements.txt, metricbeat/module/kubernetes/_meta/terraform/eks/requirements.txt, metricbeat/tests/system/requirements.txt, packetbeat/tests/system/gen/memcache/requirements.txt, x-pack/functionbeat/tests/system/requirements.txt
A previous dependabot update for Python missed updating the requirements.txt files of each individual beat, creating a dependency conflict on the protobuf package.
=> Fix 'make beats-dashboards' target

dev-tools/packaging/package_test.go
Modify TestDocker such that it can read both the original docker image layout and the OCI Image Layout. This works by reading the config and layer file names from the manifest.yml instead of assuming their names.
Fixes #37726
Need to run it on a machine with an older docker and a new docker.
`PLATFORMS=linux/amd64 SNAPSHOT=true mage -v package`
- Fixes #37726
This is how the manifest.json looks under a docker export from Docker Engine 20.10.22.
```json
[
{
"Config": "9c3a1c54bb292142bd87ab9710574289daf66725b924d6d2d7d2522abfa6c5e8.json",
"RepoTags": [
"docker.elastic.co/beats/auditbeat-oss:8.13.0-SNAPSHOT"
],
"Layers": [
"3889013043c4cd6303c1845ca9fe8ae182b4b4893f0a91f2830b9d42f8a84e3e/layer.tar",
"17c0b5e4c288157c300ed8179ee331b164c8a8fe05a0122bdaab2bb74d36daaa/layer.tar", …
```
=> package_test.go - Support OCI Image Layout

CHANGELOG.next.asciidoc, NOTICE.txt, go.mod, go.sum, x-pack/filebeat/docs/inputs/input-cel.asciidoc, x-pack/filebeat/input/cel/config.go, x-pack/filebeat/input/cel/input.go, x-pack/filebeat/input/cel/input_test.go
This change adds support for runtime error location reporting.
- Closes #37304
=> x-pack/filebeat/input/cel: update mito version to v1.8.0

CHANGELOG.next.asciidoc, filebeat/input/tcp/input.go, filebeat/input/udp/input.go
The previous logic required that if an address is present according to net.LookupIP, then it must be present in the /proc/net entries. This may not the case when a tcp/udp listener is created without specifying tcp4/udp4 for an IPv4 host address and there is an expectation of finding the socket in the /proc/net/{tcp,udp} table. So only complain if the entry has ever been found and never skip storing a metric even when there is a legitimate reason to expect its presence — because it has been seen in the past. This second part is an extension to reduce the loss of metric data, even if it is only partial.
Also fix the parse base of the receive queue which was incorrectly thought to be decimal from an incorrect reading of the kernel source.
-
=> filebeat/input/{tcp,udp}: relax requirements that proc entries be present when an address is

CHANGELOG.asciidoc
Adds a known issue for the AWS S3 performance regression described in https://github.com/elastic/beats/issues/37754
This is a port of the agent changelog entry in https://github.com/elastic/ingest-docs/pull/865
=> Add a known issue for the AWS S3 input with SQS notifications

.buildkite/pull-requests.json, .buildkite/xpack/elastic-agent/pipeline.xpack.elastic-agent.yml, catalog-info.yaml
Initial buildkite configuration for `xpack/elastic-agent`
It requires `catalog-info.yml`, `pull-requests.json` and a sample pipeline to be merged to the destination branch `7.17`
=> Initial buildkite configuration for elastic-agent

CHANGELOG.next.asciidoc, metricbeat/docs/modules/oracle.asciidoc, metricbeat/docs/modules/sql.asciidoc, x-pack/metricbeat/module/oracle/_meta/docs.asciidoc, x-pack/metricbeat/module/sql/_meta/docs.asciidoc
```
Update SQL and Oracle module docs regarding Oracle DSNs (#37590)
- Add 'oracle://' URL format.
- Add note about encoding of special characters in URLs.
- Align the SQL module and the Oracle module documentation.
```
The SQL and Oracle modules both use the [GO DRiver for ORacle DB](https://github.com/godror/godror) to parse Oracle DSNs. I tested the parsing of the DSN formats with the following script.
<details>
<summary>DSN parsing script</summary>
Script:
```go
package main
import (
"fmt"
"github.com/godror/godror"
)
func main() {
params, err := godror.ParseDSN("oracle://user:pa%20ss@0.0.0.0:1521/ORCLPDB1.localdomain?sysdba=1") // ok
// params, err := godror.ParseDSN("user/pa%20ss@0.0.0.0:1521/ORCLPDB1.localdomain?sysdba=1") // not ok
// params, err := …
```
=> Update SQL and Oracle module docs regarding Oracle DSNs

.buildkite/pull-requests.json, .buildkite/xpack/elastic-agent/pipeline.xpack.elastic-agent.yml, catalog-info.yaml
Moved `xpack/elastic-agent` 7.17 buildkite pipeline metadata to `main`. Because backstage is configured to read only the `main` branch.  
Initial pipeline configuration should be merged to `main`. Then further `xpack/elastic-agent` pipeline migration will be possible
=> Move Elastic agent pipeline config to main

CHANGELOG.next.asciidoc, heartbeat/security/security.go
Removed `isContainerized` from `setuid` check, as it fails to detect containers running under `cgroups v2` and prevents switching users when running as root.
=> [Heartbeat] Remove containerized check from setuid logic

packetbeat/docs/howto/howto.asciidoc, packetbeat/docs/howto/load-ingest-pipelines.asciidoc, packetbeat/docs/modules.asciidoc, packetbeat/docs/packetbeat-options.asciidoc, winlogbeat/docs/howto/load-ingest-pipelines.asciidoc
Follow up for #37291 addressing https://github.com/elastic/beats/pull/37291#pullrequestreview-1840158798.
See commit.
-
=> packetbeat/docs: add documentation for ingest pipelines

CHANGELOG.next.asciidoc, libbeat/autodiscover/template/config.go
When unpacking a config while applying the autodiscover config template, sometimes a configuration template cannot be resolved at that moment but will be resolved at a later stage. This commit brings the logging level of this error back to debug as it can become too verbose and not always means the config is invalid.
1. Build Filebeat
2. Deploy it on Kubernetes using the following autodiscover configuration
```yaml
filebeat.autodiscover:
providers:
- type: …
```
=> Lower logging level when unpacking config in autodiscover (revert #36919)

CHANGELOG.next.asciidoc, NOTICE.txt, go.mod, go.sum, libbeat/cmd/instance/beat.go, libbeat/processors/add_host_metadata/add_host_metadata.go
This PR improves the FQDN lookup function calls by passing a context with a 1 minute timeout, thus preventing the calls from blocking indefinitely due to DNS issues and such.
Depends on: https://github.com/elastic/go-sysinfo/pull/199 and a new release of that library.
=> Pass context with timeout to FQDN lookup

CHANGELOG.next.asciidoc, x-pack/filebeat/input/cel/input.go, x-pack/filebeat/input/http_endpoint/handler.go, x-pack/filebeat/input/httpjson/input.go, x-pack/filebeat/input/internal/httplog/roundtripper.go
The lumberjack logger drops lines that are longer than the max size, so truncate bodies that are near the limit to ensure that at least some logging data is retained. Also truncate requests that are too long, including in http_endpoint.
- Closes #37826
=> x-pack/filebeat/input/{cel,httpjson,http_endpoint}: prevent complete loss of long request trace data

metricbeat/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
Merge only after the release of 8.12.1.
=> [Release] Update test environments for 8.12.2

metricbeat/docker-compose.yml, metricbeat/module/logstash/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
Merge only after the release of 7.17.18.
=> [Release] Update test environments for 7.17.19

CHANGELOG.asciidoc
Add the change made in https://github.com/elastic/elastic-stack-installers/pull/209 to stop using C:\ProgramData as a breaking change for the MSI installers.
=> Add MSI installer change to 8.12 release notes.

CHANGELOG.next.asciidoc, x-pack/filebeat/module/threatintel/misp/config/config.yml
Update the Filebeat Threat Intel module's `misp` fileset with fixes from the [MISP integration](https://docs.elastic.co/en/integrations/ti_misp).
```
[filebeat][threatintel] MISP pagination fixes (#)
Update the HTTP JSON input configuration for the Threat Intel module's
misp fileset with pagination fixes that were done earlier in the
Agent-based MISP integration, in these PRs:
- Fix timestamp format sent to API
https://github.com/elastic/integrations/pull/6482
- Fix duplicate requests for page 1
https://github.com/elastic/integrations/pull/6495
- Keep the same timestamp for later pages
https://github.com/elastic/integrations/pull/6649
- Pagination fixes
https://github.com/elastic/integrations/pull/9073
```
To run existing tests for the Threat Intel module:
```
mage …
```
=> [filebeat][threatintel] MISP pagination fixes

.buildkite/scripts/generate_packetbeat_pipeline.sh
Packetbeat packaging fix
Exclude darwin/arm64 package from the build because this platform is unsupported
Example of the error:
https://buildkite.com/elastic/beats-packetbeat/builds/1197#018d8e8a-c9cc-4f5f-8e2a-f26fc94ccc7c/421-511
```
>> Building using: cmd='build/mage-linux-amd64 buildGoDaemon', env=[CC=gcc, CXX=g++, GOARCH=amd64, GOARM=, GOOS=linux, PLATFORM_ID=linux-amd64]
--
  | /tmp/ccgSaqPI.o: In function `main':
  | adb73258c8ab: Pull complete
  | Digest: sha256:b28467475b52ee1a5ea108c4bf7041c562b0cea9c065813dac587988a5f36437
  | Status: Downloaded newer image for docker.elastic.co/beats-dev/golang-crossbuild:1.21.7-darwin-debian10
  | >> Building using: cmd='build/mage-linux-amd64 golangCrossBuild', env=[CC=o64-clang, CXX=o64-clang++, …
```
=> fix packetbeat dynamic pipeline

libbeat/management/agent.go, libbeat/outputs/kafka/kafka.go, libbeat/outputs/kafka/kafka_test.go, libbeat/outputs/util.go, libbeat/processors/actions/append.go, libbeat/processors/actions/copy_fields.go, libbeat/processors/actions/decode_base64_field.go, libbeat/processors/actions/decompress_gzip_field.go, libbeat/processors/actions/rename.go, libbeat/processors/actions/replace.go, libbeat/processors/urldecode/urldecode.go, libbeat/publisher/processing/default.go, libbeat/publisher/processing/processors.go, x-pack/libbeat/management/managerV2.go
This commit disables the dynamic topic selection for the Kafka output
when running under Elastic-Agent. The key `topics` is ignored and the
`topic` is treated as a constant string.
I did some refactoring to move `libbeat/publisher/agent.go` to `libbeat/management/agent.go`. Effectively moving functions like `LogWithTrace` and `UnderAgent`. There are two core commits in this PR:
- Just the refactoring: https://github.com/elastic/beats/pull/37902/commits/65cdcdd1354be11dd25063e401976b138516418f
- The actual change/feature: https://github.com/elastic/beats/pull/37902/commits/b6de96c4dae23649e32dc44bf4d7893c57587a1e
- The other commits are a fix in the refactoring that does not affect this feature and fixing lint errors.
The links should land you in the review page for each commit if you …
=> [Kafka output] Disable dynamic topic selection under Elastic-Agent 

catalog-info.yaml
Fix the issue: https://buildkite.com/elastic/terrazzo/builds/41476#018d9cb3-327f-458f-9b38-16c7516ecf7b/42-433
change the option in the `catalog-info`. 
```
provider_settings:
trigger_mode: none 
```
=> change trigger_mode for all pipelines except the main pipeline

CHANGELOG-developer.next.asciidoc, NOTICE.txt, go.mod, go.sum, x-pack/filebeat/input/entityanalytics/provider/activedirectory/internal/activedirectory/activedirectory.go, x-pack/filebeat/input/entityanalytics/provider/activedirectory/internal/activedirectory/activedirectory_test.go
The activedirectory package provides a query interface to Active Directory user and group entities. Queries can be either a complete pull of the directory, or a subset of entries since a checkpoint time.
Partial test output from the directory of the test server.
```
=== RUN   Test/full
activedirectory_test.go:81: user: [
{
"id": "CN=Administrator,CN=Users,DC=testserver,DC=local",
"user": {
"accountExpires": "2185-07-21T23:34:33.709551516Z",
"adminCount": "1",
"badPasswordTime": "133517595269561536",
"badPwdCount": "0",
"cn": "Administrator",
"codePage": "0",
"countryCode": "0",
"dSCorePropagationData": [
"2024-01-22T06:52:50Z",
"2024-01-22T06:52:50Z",
"2024-01-22T06:37:40Z",
"1601-01-01T18:12:16Z"
],
"description": "Built-in account for administering the computer/domain", …
```
=> x-pack/filebeat/input/entityanalytics/provider/activedirectory/internal/activedirectory: new package

x-pack/filebeat/input/websocket/config_test.go
- Bug
A particular config test was flakey in nature and went unnoticed due to its flakeyness but ultimately caused build failures in the ci pipelines - https://github.com/elastic/beats/issues/37970. This error happened as there were 2 invalid regexes in a config map and either one would fail causing 2 different errors. To fix this only one deterministic path of failure now exists by keeping one regex valid and the other invalid.
- Relates #37970
=> [filebeat][websocket] - Fixed flakey regex test

CHANGELOG.next.asciidoc, filebeat/input/filestream/input.go
Files were not closed properly in some rare error cases.
The existing tests should make sure that the existing functionality is not broken.
- Relates to https://github.com/elastic/beats/pull/37814
=> Fix file handle leak when handling errors in filestream

x-pack/filebeat/input/cometd/input_test.go
Skip flaky test for the Filebeat cometd input.
Relates #37987
=> x-pack/filebeat/input/cometd - Skip flaky TestInputStop_Wait

.mergify.yml
Merge as soon as 8.13 branch was created. Auto-merge is not yet supported, see https://github.com/Mergifyio/mergify-engine/discussions/2821
=> backport: Add 8.13 branch

metricbeat/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
This updates the test environments to next minor release which is 8.14.0.
=> [Release] Update test environment to 8.14.0

CHANGELOG.next.asciidoc, libbeat/processors/cache/file_store.go
=> libbeat/processors/cache: add logging for file read/write

CHANGELOG.asciidoc
Fix per https://github.com/elastic/beats/pull/37915#issuecomment-1947726977, I expected the first section to be the "Affecting All Beats" section but missed that it was missing.
=> Fix MSI breaking change release note to apply to all Beats

x-pack/filebeat/input/etw/input.go, x-pack/filebeat/input/etw/input_test.go, x-pack/libbeat/reader/etw/session.go
Use errgroup to wait on the ETW consumer routine.
Use sync.OnceFunc to wrap the Close() func for the ETW session.
Clarify a few log messages (follow-up to 36915)
- https://github.com/elastic/beats/pull/36915#discussion_r1486467260
- https://github.com/elastic/beats/pull/36915#discussion_r1486467260
=> [Filebeat] ETW input - use errgroup

CHANGELOG.next.asciidoc, heartbeat/monitors/wrappers/monitorstate/esloader.go, heartbeat/monitors/wrappers/monitorstate/esloader_test.go, heartbeat/monitors/wrappers/monitorstate/testutil.go, heartbeat/monitors/wrappers/monitorstate/tracker.go, heartbeat/monitors/wrappers/monitorstate/tracker_test.go
Closes https://github.com/elastic/beats/issues/37424
From now on, the state loader will just retry for failed requests (such as a 500 status code) and not for 4xx.
- If the query is valid and returns zero results, there will not be any retry, this was working this way already
- If the API key is invalid, the query will fail returning a 4xx error (this was working this way already), as just can see in the screenshot below:
=> [Heartbeat] Adjust State loader to only retry for failed requests and not for 4xx

CHANGELOG.next.asciidoc, x-pack/filebeat/input/awss3/s3.go, x-pack/filebeat/input/awss3/s3_test.go
Remove `url.QueryUnescape()` from aws-s3 input in polling mode because it is not required.
We [introduced](https://github.com/elastic/beats/pull/18370) the `url.QueryUnescape()` function to unescape object keys from S3 notifications in SQS messages when the input runs in SQS. We also used it for object keys from the S3 list objects when the input runs in polling mode. However, the object keys in the S3 list object responses (polling mode) do [not require unescape](https://github.com/elastic/beats/issues/38012#issuecomment-1946440453).
We must remove the unescape to avoid unintended changes to the S3 object key.
```
go test -v ./x-pack/filebeat/input/awss3/... -run TestS3Poller
```
- Closes https://github.com/elastic/beats/issues/38012
=> [AWS] [S3] Remove url.QueryUnescape() from aws-s3 input in polling mode

catalog-info.yaml
fix the issue https://buildkite.com/elastic/beats-xpack-metricbeat/builds/459#018df478-5ada-4edc-91ef-a844244217da/956-10365
by increasing the maximum timeout for x-pack/metricbeat pipeline
=> increase the maximum timeout for x-pack-metricbeat

CHANGELOG.next.asciidoc, x-pack/filebeat/input/cel/config_test.go, x-pack/filebeat/input/cel/input.go, x-pack/filebeat/input/websocket/cel.go, x-pack/filebeat/input/websocket/config_test.go
In the case of cel, the extension was always being added, and then was conditionally added when a pattern was configured, resulting in a failed configuration. In the case of websocket the conditional addition was not being performed, so no failure occured, but additional look-up load was being added. So unify the approaches to the correct conditional addition.
-
=> x-pack/filebeat/input/{cel,websocket}: prevent addition of regexp extension when no patterns are provided

.github/workflows/macos-xpack-heartbeat.yml
- WHAT: install the required dependency for running the UTs
- WHY:  there is a dependency to have installed the `elastic/synthetics` dependency and the mage build system just uses it.
- Similarly resolved in Jenkins with https://github.com/elastic/beats/pull/32710 back in the days
=> github-action: install synthetics for running the UTs in x-pack/heartbeat

x-pack/filebeat/docs/inputs/input-etw.asciidoc, x-pack/filebeat/input/etw/input.go, x-pack/filebeat/input/etw/input_test.go
Add input metrics to for ETW.
Remove the very verbose debug message that was in the hot path for
processing each event.
I think more metrics taken from the ETW session itself should be added
separately (e.g. events lost, buffers lost). This lays the ground work needed
to expose those metrics.
Closes https://github.com/elastic/beats/issues/38007
```json
[
{
"arrival_period": {
"histogram": {
"count": 174046,
"max": 35801500,
"mean": 51979.00390625,
"median": 900,
"min": 0,
"p75": 2300,
"p95": 10775,
"p99": 136950,
"p999": 35187342.50000056,
"stddev": 1172792.9385769565
}
},
"discarded_events_total": 0,
"errors_total": 0,
"id": "win32k",
"input": "etw",
"processing_time": {
"histogram": {
"count": 174047,
"max": 203593000,
"mean": 461956.8359375,
"median": 0,
"min": 0,
"p75": 0,
"p95": …
```
=> [Filebeat] ETW input - add basic metrics

x-pack/filebeat/input/httpjson/rate_limiter.go, x-pack/filebeat/input/httpjson/rate_limiter_test.go, x-pack/filebeat/input/httpjson/request.go
I didn't find a solution to the failing `request_honors_rate_limit` test. The context is okay when processing the first response, and remains okay after the wait time is applied, then it appears as cancelled after the retry request is run (that is, after [this line](https://github.com/chrisberkhout/elastic-beats/blob/23b974983b113318371dff52222cbc326ff69c69/x-pack/filebeat/input/httpjson/rate_limiter.go#L43)).
```
x-pack/filebeat/input/httpjson: Apply rate limiting to all responses (#)
- Drain the body before rate limiting.
- Apply rate limiting to all responses, waiting immediately. Retry if
the response was not successful and there was a rate limit wait (even
if immediately expired), otherwise return.
- Improve names of variables `epoch` and `activeLimit`.
```
- Closes #36207
=> x-pack/filebeat/input/httpjson: Apply rate limiting to all responses

testing/environments/snapshot.yml
Generated automatically with https://github.com/elastic/beats/actions/runs/8205150084
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-07946972-SNAPSHOT&#34;:&#xA;&#x9;* testing/environments/snapshot.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/beats/actions/runs/8205150084">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] update elastic stack version for testing 8.13.0-07946972

CHANGELOG.next.asciidoc, libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc, libbeat/outputs/hosts.go, libbeat/outputs/hosts_test.go, libbeat/outputs/logstash/docs/logstash.asciidoc, libbeat/outputs/redis/docs/redis.asciidoc
This PR allows outputs that support a configurable number of workers, e.g. the elasticsearch output, to accept that number via either the `worker` or `workers` setting.  
Before this PR, users could only specify the `worker` setting but occasionally, due to typos, users sometimes specified `workers` and were confused when the value of this setting did not take effect.  
- Relates: https://github.com/elastic/kibana/pull/178329#issuecomment-1988771515
=> libbeat outputs: support `worker` or `workers` settings

.github/CODEOWNERS, .github/dependabot.yml
- WHAT: dependabot: for GitHub actions
- WHY:  keep the CI secured
Run weekly and produce up to 5 PRs that can be grouped - this will help the noise of several PRs but knowing those dependencies upgrade will be requested to be reviewed at the beginning of the week
-
=> dependabot: for GitHub actions

CHANGELOG.next.asciidoc
See title.
- For #36207
- For #38161
=> changelog: add missing entry for httpjson rate-limit enhancement

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-http-endpoint.asciidoc, x-pack/filebeat/input/http_endpoint/config.go, x-pack/filebeat/input/http_endpoint/handler.go, x-pack/filebeat/input/http_endpoint/handler_test.go, x-pack/filebeat/input/http_endpoint/input.go
Allow users to handle events where multiple events are provided via single JSON objects in an array field. This is enabled by providing an optional CEL program with only minimal support for CEL evaluations; no extensions from the mito lib extensions are made available.
- Closes #37910
=> x-pack/filebeat/input/http_endpoint: generalise event path using CEL

.buildkite/hooks/post-checkout, .buildkite/pull-requests.json
After merging #38305 we've hit an issue with the commit that Buildkite PR Bot uses.
e.g. using #38316 we see it's still using:
```
git fetch -v --prune -- origin refs/pull/38316/head
```
rather than the merge commit.
Reverting for now, until a fix[^1] in the Buildkite PR bot has been merged.
[^1]: https://github.com/elastic/buildkite-pr-bot/pull/12
=> Revert "Use native BK-pr-bot support for merge commits"

metricbeat/docs/modules/mysql.asciidoc, metricbeat/metricbeat.reference.yml, metricbeat/module/mysql/_meta/config.reference.yml, x-pack/metricbeat/metricbeat.reference.yml
This hopefully will fix several docs build errors due to an unterminated block in [metricbeat/docs/modules/mysql.asciidoc](https://github.com/elastic/beats/pull/37997/files#diff-664b0a2cdf45536df5e40ecb0df5e1ccbe646c8586f02d98a3eaf7463985bce0)
=> Fix docs build break from SSL module page

dev-tools/mage/crossbuild.go
Added "-buildvcs=false" to GOFLAGS to avoid VCS error during packaging.
Link to discussion: https://github.com/elastic/golang-crossbuild/pull/393
-
=> Disable buildvcs within docker

.buildkite/hooks/pre-command, .buildkite/scripts/common.sh, .buildkite/scripts/generate_xpack_dockerlogbeat_pipeline.sh, .buildkite/scripts/setenv.sh, .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml
Migrate `x-pack dockerlogbeat` pipeline
Example of the pipeline:
https://buildkite.com/elastic/beats-xpack-dockerlogbeat/builds/94
https://github.com/elastic/ingest-dev/issues/2993 - related to MODULE
=> migrate xpack dockerlogbeat pipeline

CHANGELOG.next.asciidoc, filebeat/docs/inputs/input-syslog.asciidoc, filebeat/input/syslog/input.go
- The syslog input has been deprecated in favor of the syslog processor.
- Closes #37555 
```
{"log.level":"warn","@timestamp":"2024-03-18T13:34:27.685Z","log.logger":"cfgwarn","log.origin":{"function":"github.com/elastic/beats/v7/filebeat/input/syslog.NewInput.func1","file.name":"syslog/input.go","file.line":119},"message":"DEPRECATED: Syslog input. Use Syslog processor instead.","service.name":"filebeat","ecs.version":"1.6.0"}
```
=> [filebeat] Deprecate syslog input

auditbeat/module/file_integrity/exeobjparser_test.go
TestExeObjParser fails on Windows because Defender is removing the testdata that is required by the test. This adds a conditional test skip for CI when those files are missing.
Closes #38211
=> auditbeat - skip TestExeObjParser on CI

dev-tools/mage/artifacts/artifacts_api.go, dev-tools/mage/manifest/manifest.go, dev-tools/mage/manifest/manifestspecs.go, dev-tools/mage/pkg.go, dev-tools/mage/version/version_parser.go, dev-tools/mage/version/version_parser_test.go
Fixes incorrect license headers introduced in https://github.com/elastic/beats/pull/38011
=> [7.17] Fix license headers in dev-tools

CHANGELOG-developer.next.asciidoc, filebeat/input/filestream/fswatch.go, filebeat/input/filestream/fswatch_test.go
* Demote warning about empty files to the Debug level
* Demote warnings about files too small to the Debug level
* Improve wording, so it does not sound like an error
```sh
go test
```
- Relates https://github.com/elastic/beats/pull/36076
- Relates https://github.com/elastic/beats/pull/35734
=> Make log messages in the file scanner less noisy

CHANGELOG.next.asciidoc, x-pack/metricbeat/module/azure/mock_service.go, x-pack/metricbeat/module/azure/monitor/client_helper.go, x-pack/metricbeat/module/azure/monitor/client_helper_test.go, x-pack/metricbeat/module/azure/monitor_service.go, x-pack/metricbeat/module/azure/service_interface.go, x-pack/metricbeat/module/azure/storage/client_helper.go, x-pack/metricbeat/module/azure/storage/client_helper_test.go
Please see the issue https://github.com/elastic/integrations/issues/8575.
Metricsets affected by this change: storage and monitor.
This PR fixes the issue the following way:
1. We check if the error produced has the header "Retry After".
2. If this header is present then we use `time.sleep` for the seconds given by the header and try again after the time is up.
3. If the header is not present, then it is likely another error and we return.
This is also the retry suggestion given by [Retry Usage Guidance](https://learn.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#retry-usage-guidance) from Azure.
For monitor metricset, the previous implementation also had a different problem affecting the number of calls: we were trying to get the metrics definition for …
=> [Metricbeat][Azure] Azure monitor/storage: Fix 429 Too Many Requests error

CHANGELOG.next.asciidoc, NOTICE.txt, go.mod, go.sum, x-pack/filebeat/docs/inputs/input-cel.asciidoc
See title.
- Related elastic/mito#54
=> mod: update elastic/mito to version v1.10.0

filebeat/buildkite.yml
This PR adds the missing steps and make sure its similar with the ones from the Jenkinsfile.yaml
This is part of the Buildkite migration.
Related:https://github.com/elastic/ingest-dev/issues/2992
=> Filebeat sync the groups/stages/steps testing from Jenkins

filebeat/buildkite.yml
Proposed commit message
This PR adds the missing steps and make sure its similar with the ones from the Jenkinsfile.yaml
This is part of the Buildkite migration.
Related issues
Related:https://github.com/elastic/ingest-dev/issues/2992
--- 
this is a backport PR
=> [8.13](backport #38484) Filebeat sync the groups/stages/steps testing from Jenkins

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-etw.asciidoc, x-pack/filebeat/input/etw/config.go, x-pack/filebeat/input/etw/input.go, x-pack/filebeat/input/etw/input_test.go
Rename `activity_guid` to `activity_id` in generated ETW events to match [mapping](https://github.com/elastic/beats/blob/c91eaeecc669cfa12df0292f26da855b638d3da6/x-pack/filebeat/input/etw/_meta/fields.yml#L13) and other [Windows inputs](https://github.com/elastic/beats/blob/c91eaeecc669cfa12df0292f26da855b638d3da6/winlogbeat/_meta/fields.common.yml#L33).
It also fixes some typos in the ETW docs and comments.
=> x-pack/filebeat/input/etw: Rename activity_guid to activity_id in ETW events

libbeat/docs/command-reference.asciidoc
So, [a PR in 2019](https://github.com/elastic/beats/pull/11777) removed the `--index` flag for `export template`. However, we never updated the docs.
=> Remove references to `export template --index`

.buildkite/scripts/generate_pipeline.sh
This is done to disable the execution of the pipeline.
Since we paused the work on the dynamic pipeline it makes sense not to actually execute it, thus provisioning VM and adding some noise in the PRs.
=> Comment the buildkite upload step

.ci/scripts/install-tools.bat
This commit ensures that chocolatey is the latest version before installing Python on the Jenkins Windows workers. It fixes errors due to outdated chocolatey versions looking like:
```
Failures
- python (exited 1) - python not installed. An error occurred during installation:
Unable to resolve dependency 'python3 (= 3.8.5)'.
```
=> Update chocolatey to latest version

auditbeat/module/file_integrity/exeobjparser_test.go
The arguments to `errors.Is` are in the wrong order so the check is not working as designed and the test was never skipped.
Also stop the test after `exeObjParser.Parse` fails.
Relates: #38211
```
cd auditbeat/module/file_integrity
rm ./testdata/garble_macho_executable
CI=true go test -run TestExeObjParser -v .
```
=> auditbeat TestExeObjParser - fix errors.Is argument order

libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc, libbeat/outputs/logstash/docs/logstash.asciidoc, libbeat/outputs/redis/docs/redis.asciidoc
As of https://github.com/elastic/beats/pull/37795/files in 8.13.0 queue.flush.min_events is no longer relevant.
=> Remove references to min_events in bulk_max_size docs.

CHANGELOG.next.asciidoc, heartbeat/_meta/config/beat.reference.yml.tmpl, heartbeat/heartbeat.reference.yml, x-pack/heartbeat/heartbeat.reference.yml
Fix heartbeat.reference.yml incorrect formatting.
=> [Heartbeat] Fix reference yaml format

libbeat/docs/keystore.asciidoc
The keystore uses a default, unchangeable password to encrypt data. In this sense it is not secure, only obfuscated on disk. Change the documentation to make this clear.
=> Clarify that the keystore obfuscates secrets only.

CHANGELOG.next.asciidoc, x-pack/filebeat/input/cel/input.go, x-pack/filebeat/input/http_endpoint/handler.go, x-pack/filebeat/input/http_endpoint/input.go, x-pack/filebeat/input/httpjson/input.go, x-pack/filebeat/input/internal/httplog/roundtripper.go
When debugging issues in cel and httpjson the request trace log facility can be very useful, but the separated nature of the log can add friction since the only tie between the agent logs and the request trace logs is the time stamp. This adds an additional log message to the agent logs at DEBUG that marks the creation of a request transaction, noting the transaction ID into the agent logs.
A similar addition is made to http_endpoint.
-
=> x-pack/filebeat/input/{cel,httpjson,http_endpoint,internal/httplog}: add debugging bread crumbs

CHANGELOG.next.asciidoc, x-pack/filebeat/input/entityanalytics/input.go, x-pack/filebeat/input/entityanalytics/provider/activedirectory/activedirectory.go
This adds a missing registration import and publishes the complete entry, not just the user component.
- For elastic/integrations#8559
=> x-pack/filebeat/input/entityanalytics{,/provider/activedirectory}: register and fix published entity

metricbeat/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
Merge only after the release of 8.13.1.
=> [Release] Update test environments for 8.13.2

.golangci.yml
According to LICENSE.txt, the Beats project uses both Apache 2.0 (OSS) and Elastic licenses. The OSS code may not depend on the Elastic License code otherwise the OSS-only binaries become tainted.
This makes golangci-lint emit warnings for OSS code that depends on x-pack code.
Closes #38719
=> .golangci.yml - Disallow OSS -> x-pack dependencies

metricbeat/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
Merge only after the release of 8.13.2.
=> [Release] Update test environments for 8.13.3

CHANGELOG.next.asciidoc, filebeat/input/filestream/internal/input-logfile/clean.go, filebeat/input/filestream/internal/input-logfile/store.go, filebeat/tests/integration/store_test.go, libbeat/tests/integration/framework.go
The `resources` from Filestream registry have a counter to indicate how many 'owners' have got a hold of that resource, this counter was not correctly decremented. Because it never reached zero, no entry was ever removed from the in-memory store and even though the store GC would run periodically, no resource could be removed. That caused the in-memory store to be ever growing and the `op: remove` never to be seen in the registry log file.
This commit fixes this bug by correctly calling `Released` in every resource that is retained.
```yaml
id: "PR-38488"
paths:
- /tmp/logs/*.log …
```
=> Fix Filestream store GC, entries are now removed when they TTL expires

metricbeat/docker-compose.yml, metricbeat/module/logstash/docker-compose.yml, testing/environments/latest.yml, x-pack/metricbeat/docker-compose.yml
Merge only after the release of 7.17.20.
=> [Release] Update test environments for 7.17.21

CHANGELOG.next.asciidoc, filebeat/docs/fields.asciidoc, x-pack/filebeat/input/netflow/input.go
This PR enables event normalisation for netflow input and solves this [this issue](https://github.com/elastic/beats/issues/38703). Specifically the netflow input in 8.13 had a refactor to transition to plugin.V2 and during this it was deemed as safe to disable event normalisation and thus improve the performance. However the produced events contain ip fields that cause similar errors to this following without normalisation enabled
```
Apr 02 13:57:11 tv filebeat[597]: {"log.level":"warn","@timestamp":"2024-04-02T13:57:11.590Z","log.logger":"elasticsearch","log.origin":{"function":"github.com/elastic/beats/v7/libbeat/outputs/elasticsearch.(*Client).bulkCollectPublishFails","file.name":"elasticsearch/client.go","file.line":454},"message":"Cannot index event (status=400): dropping event! …
```
=> [filebeat/netflow]: set event normalisation to true

.buildkite/auditbeat/auditbeat-pipeline.yml, .buildkite/hooks/pre-command
This simplifies the mental model about what is needed and what is not for the pipeline execution.
The Beats pipeline is a pipeline generator and does not need any of those environment variables. This makes it more compact in the future when we want to simplify.
Here is a build that executes the beats pipeline without any issues https://buildkite.com/elastic/beats/builds/5021
Here is a build with a commit (26bbb87875456375cbdb1bd1c16e18fae967efaa) on Auditbeat to show that it triggers and works https://buildkite.com/elastic/beats/builds/5023
=> Remove the beats pipeline slug from sourcing envs

.buildkite/hooks/pre-command, .buildkite/scripts/common.sh
This commit removes the need to configure git for Windows since we migrated to the custom Windows images. It also removes the config_git, which was defined twice in a single file.
=> Clean BK scripts

.buildkite/scripts/changesets.sh, metricbeat/module/windows/module.yml
After the introduction of a centralized beats pipeline and statically
defined changeset rules in #38783, we still need a way to grab
changes for modules for IT tests.
Currently this is done in common.sh#defineModuleFromTheChangeSet().
This commit adds a new script that has only the changeset related
functionality, required to build the `MODULE` env var.
The functions themselves, are copied from common.sh (with minor
enhancements in documentation), paving the way to sunset common.sh
in the future.
When changing e.g. `metricbeat/modules/windows/module.yml` (see 4165994b5766c2b83c10c08090c6a022b973b571), invoking the script returns:
```
$ pwd
beats/metricbeat
$ source .buildkite/scripts/changesets.sh
$ defineModuleFromTheChangeSet …
```
=> Dedicated script for detecting changesets on Buildkite

.buildkite/pull-requests.json
This needs to land in the main branch before migrating the pipeline because the bot expects to find it there.
Follow-up work will happen to migrate the pipeline.
Part of the work needed for https://github.com/elastic/ingest-dev/issues/3072
=> Remove Buildkite pipeline trigger

.buildkite/scripts/changesets.sh
PR #38814 missed a couple of patterns required
by the defineModuleFromTheChangeSet() function.
This commit adds the missing regex patters
needed for identifying module changesets.
=> Fix missing vars in buildkite changesets.sh

.buildkite/scripts/install_macos_tools.sh
This commit adds a stand alone script that
can be sourced before executing mage commands
on macOS (Orka) workers.
For now it only supports macOS x86_64.
- https://github.com/elastic/ingest-dev/issues/3072#issuecomment-2046970938
It can be seen successful run as part of the metricbeat PR in: https://buildkite.com/elastic/beats-metricbeat/builds/4721#018ecc0d-3559-4852-9fcc-0caf7980f66c
The way to use it is as [shown here](https://github.com/elastic/beats/pull/38827/files#diff-87cc9e7aecd3c1a6382e951a1b17429443aa3f12387328521fa06b2c8f83a814R227-R229) i.e.
```
command: |
set -euo pipefail
source .buildkite/scripts/install_macos_tools.sh
cd project && mage build unitTest
```
=> Tool setup for macOS workers on Buildkite

catalog-info.yaml
This commit adjusts the branch configuration of the Beats Buildkite pipelines so that they can be triggerable from branches existing upstream coming from Mergify.
=> Adjust the Beats pipelines branch configuraiton

.buildkite/metricbeat/pipeline.yml
Currently the Packaging Linux group for metricbeat on 7.17
fails with[^1]:
```
Error: unsupported cross build platform darwin/arm64
```
[^1] https://buildkite.com/elastic/beats-metricbeat/builds/4805#018ed1f7-4925-42e7-b043-de3c64f968ac/119-318
This commit fixes it by not including this target, since we don't publish macOS arm64 artifacts on `7.17`.
https://github.com/elastic/ingest-dev/issues/3072
Successful build example: https://buildkite.com/elastic/beats-metricbeat/builds/4818#018ed246-3a5a-48d0-b17b-259a8a64d4c6/130-443
=> Fix metricbeat packaging on 7.17

CHANGELOG.next.asciidoc, filebeat/docs/filebeat-options.asciidoc, libbeat/docs/outputs-list.asciidoc, libbeat/outputs/discard/config.go, libbeat/outputs/discard/discard.go, libbeat/outputs/discard/docs/discard.asciidoc, x-pack/filebeat/docs/inputs/input-benchmark.asciidoc, x-pack/filebeat/input/benchmark/config.go, x-pack/filebeat/input/benchmark/config_test.go, x-pack/filebeat/input/benchmark/input.go, x-pack/filebeat/input/default-inputs/inputs_other.go
filebeat benchmark input and discard output
benchmark is simple input that generates synthetic events, useful for benchmarking outputs or for providing load on outputs.
The message of each event is set in the config file.  Event duplication is avoided with the `thread`, `line` and `filename` fields.  Each go routine that generates an event sets a unique `thread` field.  Within each each thread, every event that is generated increments the `line` field.  The `line` field is a uint64, if the max is reached then the `filename` field is incremented and `line` is reset to 0.
The default behavior is to generate events as quickly as possible until filebeat is stopped.  Optionally you can set the `count` option, which will generate that number of events and then stop.  Or you can use the `eps` …
=> filebeat benchmark input and discard output

catalog-info.yaml
Revert the changes done from https://github.com/elastic/beats/pull/38875
The reason is that when raising a backport PR, it's handled as a normal branch, which was wrong.
=> Revert branch_configuration for beats pipeline

.buildkite/metricbeat/pipeline.yml
This commit adds support for running metricbeat
CI for the arm64 CPU architecture on macOS agents.
=> macOS arm64 CI for metricbeat

.buildkite/pull-requests.json
This commit allows the mergify bot to trigger automatically builds of backport PRs.
=> Allow mergify bot to trigger builds

CHANGELOG-developer.next.asciidoc, CHANGELOG.next.asciidoc, filebeat/input/filestream/internal/input-logfile/harvester.go, filebeat/input/kafka/input.go, filebeat/input/v2/input-cursor/input.go, filebeat/input/v2/input-stateless/stateless.go, filebeat/input/v2/input-stateless/stateless_test.go, libbeat/beat/pipeline.go, libbeat/publisher/pipeline/client.go, libbeat/publisher/pipeline/client_test.go, libbeat/publisher/pipeline/pipeline.go, libbeat/publisher/pipeline/pipeline_test.go, libbeat/publisher/testing/testing.go, x-pack/filebeat/input/awscloudwatch/input.go, x-pack/filebeat/input/awss3/input.go, x-pack/filebeat/input/entityanalytics/internal/kvstore/input.go, x-pack/filebeat/input/lumberjack/input.go, x-pack/filebeat/input/netflow/input.go, x-pack/filebeat/input/shipper/input.go
The publishing pipeline would panic when more than 32767 clients were active, that happened because each client would add two channels to a slice and an infinity loop would use `reflect.Select` on this list. `reflect.Select` supports a maximum of 65536 cases, if there are more it panics.
This PR fixes this by removing the need for this list. The pipeline used an infinity loop to detect if the `CloseRef` from the pipeline client was closed, if it happened, then it would call `client.Close`. By analysing the code setting `CloseRef` we identified there was no need for the pipeline to be responsible for propagating this signal, most of the times the pipeline client was created, there was already a defer to close it, in the few places where it was not present we added one.
Now the pipeline is …
=> Fix panic when more than 32767 pipeline clients are active

.buildkite/metricbeat/pipeline.yml, .buildkite/scripts/install_macos_tools.sh
This commit adds two new functions in
`install_macos_tools.sh` that install nodejs
and common nodejs dependencies.
This has been tested using the dummy commit (now reverted) that triggered the installation of Node.js and node packages on both macOS x86_64 and arm64 agents:
```
command: |
set -euo pipefail
source .buildkite/scripts/install_macos_tools.sh
withNodeJSEnv "18.17.1"
installNodeJsDependencies
cd metricbeat && mage build unitTest
```
In the future, when nodejs is required (AFAIU it's only needed for xpack-heartbeat, hence we don't install it always by default) we should just add
```
withNodeJSEnv "18.17.1"
installNodeJsDependencies
```
after `source .buildkite/scripts/install_macos_tools.sh`
Log links:
- macOS x86_64: …
=> Add support for installing Node.js on macOS

.buildkite/auditbeat/auditbeat-pipeline.yml, .buildkite/pipeline.yml
Fix macOS failures with auditbeat and refactor
the pipeline to be similar to other ones wrt notifications,
build commands and no usage of BEATS_PROJECT_NAME.
Buildkite runs:
- default labels: https://buildkite.com/elastic/auditbeat/builds/3824
- `:Windows` && `:macOS` && `:arm`: https://buildkite.com/elastic/auditbeat/builds/3828
=> Fix macOS failures with auditbeat

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-o365audit.asciidoc, x-pack/filebeat/input/o365audit/input.go
=> x-pack/filebeat/input/o365audit: deprecate input

CHANGELOG.next.asciidoc
Add release note for PR 38126
As discussed in comment https://github.com/elastic/beats/pull/38126#issuecomment-2055653638 I add the note for the release note 38126 (and tried to adjust the changelog.next.asciidoc to avoid duplicates and avoid formatting errors). CC @shmsr 
-
=> Add release note for PR 38126 in changelog.next.asciidoc

.buildkite/pull-requests.json
This commit removes the trigger configuration of the x-pack filebeat from main.
This is done in prep for the https://github.com/elastic/beats/pull/38941
Related: https://github.com/elastic/ingest-dev/issues/3072
=> Remove X-PACK Filebeat bot trigger

.buildkite/filebeat/filebeat-pipeline.yml
As we migrated the Filebeat pipeline into the central triggering pipeline we added the MODULEs changeset for the Filebeat project, which looking at the original Jenkins it was never the case. 
This PR fixes the above inconsistency.
=> Remove modules from Filebeat

CHANGELOG.next.asciidoc, x-pack/filebeat/_meta/config/filebeat.inputs.reference.xpack.yml.tmpl, x-pack/filebeat/docs/inputs/input-gcp-pubsub.asciidoc, x-pack/filebeat/filebeat.reference.yml, x-pack/filebeat/input/gcppubsub/config.go, x-pack/filebeat/input/gcppubsub/pubsub_test.go
- Due to the presence of internal queue, the input gets blocked until `queue.mem.flush.min_events` or `queue.mem.flush.timeout` is reached. To prevent this blockage on GCP Pub/Sub input, default `max_outstanding_messages` is increased to at least `queue.mem.flush.min_events`. The analysis is conducted in https://github.com/elastic/beats/pull/37657#issue-2085892002
- Relates https://github.com/elastic/beats/issues/35029
=> x-pack/filebeat/input/gcppubsub: Prevent input blockage by increasing default `max_outstanding_messages`

metricbeat/module/prometheus/test_prometheus.py
- Closes https://github.com/elastic/beats/issues/38854
My initial attempt to fix this in https://github.com/elastic/beats/pull/38912 failed so just disabling the test while the necessary changes are made.
=> [7.17] Skip failing prometheus remote write test.

CHANGELOG.next.asciidoc, x-pack/filebeat/input/cel/config_auth.go, x-pack/filebeat/input/cel/config_test.go, x-pack/filebeat/input/httpjson/config_auth.go, x-pack/filebeat/input/httpjson/config_test.go
The logic for validation assumed that client.id and client.secret must be present, but this is not the case for password grant, so relax the requirement.
- Ref [elastic/integrations#9600](https://github.com/elastic/integrations/pull/9600#discussion_r1566168742)
=> x-pack/filebeat/input/{cel,httpjson}: fix oauth2 config validation

.ci/packaging.groovy
Follow up from https://github.com/elastic/beats/pull/38951 to fix the failures in https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fpackaging/detail/main/4035/pipeline
```
[2024-04-17T01:56:48.997Z] Started by user Craig MacKenzie
[2024-04-17T01:56:49.074Z] Connecting to https://api.github.com/ using Jenkins - beats-ci
[2024-04-17T01:56:49.571Z] Obtained .ci/packaging.groovy from 3f06575996bc91402a5c330c18b0e7451c43785b
[2024-04-17T01:56:49.571Z] Resume disabled by user, switching to high-performance, low-durability mode.
[2024-04-17T01:56:49.587Z] org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
[2024-04-17T01:56:49.587Z] WorkflowScript: 208: expecting ']', found 'x-pack/auditbeat' @ line 208, column 5.
[2024-04-17T01:56:49.587Z] …
```
=> Adding missing comma in packaging.groovy, add agentbeat for arm.

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-websocket.asciidoc
Please label this PR with one of the following labels, depending on the scope of your change:
- Docs
Updated Input title to align with existing inputs.
-
=> [filebeat][websocket] - Updated Input title to align with existing inputs

.buildkite/pull-requests.json
In preparation for the migration to a static
pipeline (#38845), this commit removes the
Buildkite PR Bot trigger for the pipeline.
Relates https://github.com/elastic/ingest-dev/issues/3072
=> Remove BK PR Bot trigger for x-pack/heartbeat

dev-tools/mage/manifest/manifest.go
Adds `.asc` files to package pipeline, to fix `7.x` packaging bug
list of resulting tar.gz after mage package concludes.
Signed-off-by: DaveSys911 <David.Natachanny@elastic.co>
=> add .asc downloads to elastic-agent-package-7.17

.buildkite/scripts/common.sh
Fix conflict issues after merging #38845
=> Fix conflict issues after merging #38845

.github/CODEOWNERS
The syslog reader and processor are owned by the @elastic/sec-deployment-and-devices team, but were not set in CODEOWNERS until now.
=> Set owner of syslog reader and processor

.buildkite/heartbeat/heartbeat-pipeline.yml, .buildkite/hooks/pre-command, .buildkite/hooks/scripts/util.sh
In scope of https://github.com/elastic/ingest-dev/issues/3072 - fixed issues with heartbeat pipeline (removed BEATS_PROJECT_NAME env var usage and updated commands to unified style)
BK Builds: https://buildkite.com/elastic/heartbeat/builds?branch=oakrizan%3Aheartbeat-fixes
-
=> Fixed issues with Heartbeat pipeline

.buildkite/pipeline.yml, .buildkite/scripts/common.sh, .buildkite/winlogbeat/pipeline.winlogbeat.yml
In scope of https://github.com/elastic/ingest-dev/issues/3072 - moved winlogbeatt pipeline triggering to central pipeline
BK Builds: https://buildkite.com/elastic/beats/builds?branch=oakrizan%3Acentralised-pipeline-winlogbeat
Xpack/Heartbeat failure unrelated to current PR, related issue https://github.com/elastic/ingest-dev/issues/3196
-
=> Moved winlogbeat pipeline to central pipeline

.buildkite/x-pack/pipeline.xpack.metricbeat.yml
PR#38913 had a bug for the extended tests group:
it wouldn't allow to run steps in the extended
group when not using a PR (e.g. merge commits).
This commit allows all steps in the extended
group to run when the trigger is not a PR.
=> Improve conditionals for x-pack/metricbeat BK CI

.buildkite/pull-requests.json
In preparation for the migration to a static pipeline for packetbeat, this commit removes the Buildkite PR Bot trigger.
- elastic/ingest-dev#3072
=> Remove BK PR Bot trigger for packetbeat

.buildkite/scripts/changesets.psm1, .buildkite/scripts/common.sh, .buildkite/x-pack/pipeline.xpack.winlogbeat.yml
In scope of https://github.com/elastic/ingest-dev/issues/3072 - updated Xpack/Winlogbeat pipeline module test step to use changeset calculation
BK Builds: https://buildkite.com/elastic/beats-xpack-winlogbeat/builds?branch=oakrizan%3Axpack-winlogbeat-fixes
-
=> Buildkite Xpack/Winlogbeat pipeline fixes

metricbeat/docker-compose.yml
https://github.com/elastic/beats/commit/57b7595ee851b1a206aef82c7224c70eaea8a616 bypasses using a PR and committed directly to 8.14 while only partially updating the set of versions used in tests.
Make the versions what they should be in the metricbeat docker-compose.yml file. I believe that main is still using 8.12.x for these tests, I will bump those versions separately.
=> [8.14] Update versions in tests to 8.13.2 consistently

metricbeat/docker-compose.yml, x-pack/metricbeat/docker-compose.yml
The main version of https://github.com/elastic/beats/pull/39135
Main is not testing against the latest release, let's fix that.
=> [main] Update test versions to 8.13.2

x-pack/filebeat/input/awscloudwatch/input.go, x-pack/filebeat/input/awscloudwatch/input_integration_test.go, x-pack/filebeat/input/awscloudwatch/processor.go
Remove `EventACKTracker` from `awscloudwatch` event handling.
`EventACKTracker` is buggy (see https://github.com/elastic/beats/issues/38961) but in the `awscloudwatch` input it's also never used -- its callbacks are attached to events, but their result doesn't affect any of the event handling.
This PR doesn't change any functional behavior.
=> Cleanup: Remove unused ACK tracking in `awscloudwatch` input

filebeat/input/v2/input.go, x-pack/filebeat/input/awscloudwatch/input.go, x-pack/filebeat/input/awss3/input.go
Simplify context handling in the awscloudwatch and awss3 inputs.
The awscloudwatch and awss3 inputs both need to convert their Beats input context to a standard golang context for use with the AWS API, and both of them use custom wrappers that create an extra goroutine to listen for Beat shutdown. I added an explicit wrapper object to the `v2.InputContext` API that is a single function call and requires no extra goroutines, and replaced the context wrapper in both inputs.
This doesn't change any functional behavior.
=> Cleanup: Replace custom goroutine shutdown listeners with shared context wrapper

.buildkite/ironbank-valitation.yml, catalog-info.yaml
This commit adds the foundational pipeline
definition needed for the migration of the
IronBank validation Jenkins Job to Buildkite.
- https://github.com/elastic/ingest-dev/issues/3235
=> Add initial BK pipeline for IronBank validation

.buildkite/packaging.pipeline.yml, .buildkite/scripts/dra.sh, .buildkite/scripts/packaging/package-dra.sh
This PR fixes a number of bugs from #39126
=> Fixes for packaging pipeline

CHANGELOG.next.asciidoc, metricbeat/module/elasticsearch/elasticsearch.go, metricbeat/module/elasticsearch/elasticsearch_integration_test.go, metricbeat/module/elasticsearch/index/data.go
This PR removes the `hidden` flag introduced by https://github.com/elastic/beats/issues/18639. The SM UI doesn't use this flag, and retrieving which indices are `hidden` is an expensive operation that can sometimes cause problems such as timeouts depending on how large a cluster is.
```
elasticsearch": {
"cluster": {
"id": "5QYQ1YeeRjy9MJtahqzY6w",
"name": "elasticsearch"
},
"index": {
"status": "green",
"hidden": false,
"shards": {
"total": 1,
"primaries": 1
}
...
}
...
}
```
```
"elasticsearch": {
"cluster": {
"id": "5QYQ1YeeRjy9MJtahqzY6w",
"name": "elasticsearch"
},
"index": {
"status": "green",
"shards": {
"total": 1,
"primaries": 1
}
...
}
...
}
```
- Start a local ES and kibana instances
- Start metricbeat with elasticsearch module enabled
- Run the query below and check if there …
=> [Eleasticsearch] Remove `hidden`  field from indice metricset docs

.buildkite/packaging.pipeline.yml
Added `DEV` flag to snapshot builds. Specified the workflow for `prepare-release-manager.sh` 
-
=> Added DEV flag to snapshot. prepare-release-manager.sh staging param

.buildkite/pipeline-scheduler.py
As a follow up to PR#39179 we need an additional
Buildkite pipeline that can dynamically evaluate
the release branches and trigger separate runs
per branch on a schedule.
This commit adds a Python script that generates
the dynamic steps as dictated by an env var
`PIPELINES_TO_TRIGGER`
It is intended to be used by a generic
scheduler pipeline defining schedules like:
```
schedules:
IronBank Validation:
branch: main
cronline: 30 02 * * *
message: Daily trigger of ironbank-validation pipeline per branch
env:
PIPELINES_TO_TRIGGER: 'ironbank-validation'
```
It's similar to what was implemented (in Bash)
for Logstash in https://github.com/elastic/ingest-dev/issues/2664
We intend to leverage the container image
`docker.elastic.co/ci-agent-images/platform-ingest/buildkite-agent-beats-ci-with-hooks …
=> Dynamic Pipeline scheduler script Buildkite

.buildkite/scripts/dra.sh, .ci/jobs/packaging.yml, .pre-commit-config.yaml, catalog-info.yaml
This commit disables automated DRA builds for
the `main` branch via Jenkins, and enables the
same functionality via Buildkite.
=> Enable DRA for main via Buildkite

.buildkite/pipeline-scheduler.yml
This commit is a follow up to #39254 and adds
a schedule for the IronBank validation pipeline
to the centralized scheduling pipeline.
- https://github.com/elastic/ingest-dev/issues/3235
=> Add IronBank validation to cron schedule

.buildkite/pipeline-scheduler.yml
This commit is a follow up to #39254 and adds
a schedule for the IronBank validation pipeline
to the centralized scheduling pipeline.
Relates: https://github.com/elastic/ingest-dev/issues/3235
This is a backport of https://github.com/elastic/beats/pull/39255
=> [8.14](backport #39255) Add IronBank validation to cron schedule

.buildkite/pipeline-scheduler.yml
This commit is a follow up to #39254 and adds
a schedule for the IronBank validation pipeline
to the centralized scheduling pipeline.
Relates: https://github.com/elastic/ingest-dev/issues/3235
This is a backport of #39255 to branch 8.13
=> [8.13](backport #39255) Add IronBank validation to cron schedule

catalog-info.yaml
This commit fixes the schedule description for the Iron Bank validation and removes the old static schedule, now that we have a centralized scheduling job (#39254).
Additionally, now that the [job has been tested](https://github.com/elastic/beats/pull/39255#issuecomment-2082368821) it enables slack alerts as well.
This PR doesn't need backporting since it's about catalog-info / terrazzo
=> Fix cron description for Iron Bank validation

libbeat/processors/add_docker_metadata/docs/add_docker_metadata.asciidoc
This updates the [Add Docker metadata ](https://www.elastic.co/guide/en/beats/packetbeat/8.13/add-docker-metadata.html) page in the current (8.13) and later Packetbeat docs to note that this processor is not supported, as recommended [here](https://github.com/elastic/enhancements/issues/21415#issuecomment-2079518786).
Rel: https://github.com/elastic/enhancements/issues/21415
These docs are single-sourced across all Beats. The following will appear only on the Packetbeat page:
=> Mark add_docker-metadata process as unsupported in packetbeat

filebeat/docs/inputs/input-filestream-file-options.asciidoc, filebeat/docs/inputs/input-filestream.asciidoc
This commit documents `harvester_limit` for the filestream input and replaces `close_*` by the correct key `close.on_state_change.*`.
- Closes https://github.com/elastic/beats/issues/38784
~~## Logs~~
=> Document havester_limit for Filestream input and fix typo

.buildkite/scripts/dra.sh
DRA: Disable summary reports for dry runs. 
- Relates https://github.com/elastic/ingest-dev/issues/3095
=> DRA: Disable summary reports for dry runs

.buildkite/packaging.pipeline.yml
As things are now we allow parallel builds on the
packaging pipeline, which would result in out of order artifacts (depending on which one takes longer to finish).
This commit leverages a queue to ensure a FIFO queue for DRA artifacts using the design pattern in:
https://buildkite.com/blog/concurrency-gates
Using the [latest approach](https://github.com/elastic/beats/pull/39270/commits/d6c7dc2b12955fd819111a77ca53356e07ff5f41), I triggered two DRA `main` snapshot builds in succession using the env vars:
```
DRA_BRANCH="main"
RUN_SNAPSHOT="true"
DRY_RUN="true"
```
and was able to see the [first one triggered](https://buildkite.com/elastic/beats-packaging-pipeline/builds/92) proceed:
whereas the [second …
=> Ensure ordered DRA artifacts

catalog-info.yaml
PR#39263 introduced a bug causing on packaging DRA builds to be triggered.
This commit fixes the issue and also allowed
triggered builds for `8.14`
=> Fix auto triggered packaging builds

catalog-info.yaml
This commit adds a 60min timeout for DRA builds.
=> Add 1hr timeout for DRA builds

.buildkite/packaging.pipeline.yml
The DRA staging release is failing because the Buildkite step isn't capturing the right artifacts.
This commit fixes the issue by adjusting the artifact_paths to match the other steps.
Example of failure: https://buildkite.com/elastic/beats-packaging-pipeline/builds/96#018f2e52-8eda-4311-91fc-662353604f29
=> Fix missing docker staging DRA artifacts

.buildkite/packaging.pipeline.yml
PR #39293 introduced one concurrency queue per staging/snapshot but this slows down unnecessarily concurrent DRA builds for main and other release branches.
This commit makes the concurrency gates specific per branch.
Example run: https://buildkite.com/elastic/beats-packaging-pipeline/builds/99#018f2ed1-88f4-4f2a-9604-e29c51eba3a3
First run:
Blocked second run (as expected):
=> Branch specific concurrency gates

.buildkite/scripts/dra.sh
This commit adds the `--append` flag to the buildkite-annotate so that when it is called by the snapshot and staging steps will not overwrite the other annotation.
=> Fix the annotating for snapshot and staging

.buildkite/scripts/dra.sh, .ci/jobs/packaging.yml, .pre-commit-config.yaml
This commit disables automated DRA builds for
the 8.14 branch via Jenkins, and enables the
same functionality via Buildkite.
- https://github.com/elastic/ingest-dev/issues/3095#issuecomment-2085726889
=> Enable DRA for 8.14 on Buildkite

.ci/jobs/packaging.yml
This commit is complementing PR #39321 and is needed to disable the execution of 8.14 DRA on Jenkins.
- https://github.com/elastic/ingest-dev/issues/3095#issuecomment-2085726889
(this PR should **not** be backported)
=> Disable 8.14 DRA on Jenkins

.buildkite/packaging.pipeline.yml, catalog-info.yaml
Occasionally packaging steps from the DRA pipeline may get stuck[^1]. This causes a breach of the global pipeline timeout (currently 1hr) and cancels the job.
This commit increases the global timeout to 90min, adds one retry per step and limits the runtime per step to 40min (so that a single stuck step doesn't exhaust the entire global timeout).
Finally, we shush slack notifications if the retry recovered the step.
In a future PR we will consider also adding a daily DRA build to cover for cases where the retries didn't help and there were no subsequent commits to trigger a new build.
Test BK build using this PR targetting `main`: https://buildkite.com/elastic/beats-packaging-pipeline/builds/119
which eventually succeeded despite a stuck step:
- …
=> More resilient DRA packaging

.buildkite/auditbeat/auditbeat-pipeline.yml, .buildkite/filebeat/filebeat-pipeline.yml, .buildkite/heartbeat/heartbeat-pipeline.yml, .buildkite/libbeat/pipeline.libbeat.yml, .buildkite/metricbeat/pipeline.yml, .buildkite/packetbeat/pipeline.packetbeat.yml, .buildkite/winlogbeat/pipeline.winlogbeat.yml, .buildkite/x-pack/pipeline.xpack.auditbeat.yml, .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml, .buildkite/x-pack/pipeline.xpack.filebeat.yml, .buildkite/x-pack/pipeline.xpack.heartbeat.yml, .buildkite/x-pack/pipeline.xpack.libbeat.yml, .buildkite/x-pack/pipeline.xpack.metricbeat.yml, .buildkite/x-pack/pipeline.xpack.osquerybeat.yml, .buildkite/x-pack/pipeline.xpack.packetbeat.yml, .buildkite/x-pack/pipeline.xpack.winlogbeat.yml, dev-tools/mage/pytest.go
In scope of beats migration from Jenkins to Buildkite - added retries to tests (Cloud tests not retried at the moment, see [comment](https://github.com/elastic/beats/pull/39174#issuecomment-2075110905) below).
Packaging, K8Tests are not retried according to global Jenkinsfile.
BK Builds: https://buildkite.com/elastic/beats/builds?branch=oakrizan%3Aenable-retries-for-flaky-tests
Auditbeat MacOS test failure not related/caused by current PR. Related issue: https://github.com/elastic/ingest-dev/issues/3268
-
=> Enabling retries for Beats flaky tests

catalog-info.yaml
This file is absolutely unnecessary (it's only consulted from `main`) but for making backporting easier and keeping things consistent,
this commit brings it up to date with what we have on `main` as of now.
In the future, we'll strive to always backport every change in `catalog-info` to release branches as well.
=> Update catalog-info from main

CHANGELOG.next.asciidoc, auditbeat/module/file_integrity/monitor/monitor_test.go, auditbeat/module/file_integrity/monitor/recursive.go
This PR prevents FIM from losing events for recursive mode on Mac OS X even when the `watchFile` of the root dir, added to be monitored, returns an error by always walking the dir. Specifically, this discrepancy, between Linux and OS X oses, is due to the fact that in the latter the underlying library, namely fsnotify, when you add a watch of a directory it walks the directory and adds the respective sub-dir watchers. If any of these fail, e.g. with EACCESS, it returns an error.  However, auditbeat's wrapper of this library emits created events by walking the directory. So, in order not to lose any events we need to guarantee that we won't interrupt this flow - we will always walk the directory - and accumulate any errors during this process which we will return only at the end.
N/A …
=> [Auditbeat/FIM/fsnotify]: prevent losing events for recursive mode on OS X

x-pack/filebeat/input/awss3/input.go, x-pack/filebeat/input/awss3/input_test.go
Fix an error in region selection that was introduced in a previous cleanup (https://github.com/elastic/beats/pull/38958). When the configured region disagrees with the region detected from the queue URL, the configured region is supposed to take precedence. Due to a misreading, my code instead chose the URL region when there is a conflict.
I've broken region selection out into another helper function to make this logic easier to test, and added several unit test cases that would have caught this mistake.
=> `aws-s3` input: fix SQS region selection

catalog-info.yaml
Now that DRA support via Buildkite has also been backported to 8.13[^1] this commit widens the whitelisted branches that can trigger Buildkite DRA builds to include all 8.x branches.
[^1]: https://github.com/elastic/beats/pull/39198
=> Auto trigger DRA for all 8.x branches

.buildkite/scripts/dra.sh
This commit is the counterpart of #39321 for the 8.13 branch and
disables the default DRY_RUN mode when running DRA packaging on
Buildkite for the 8.13 branch.
- https://github.com/elastic/beats/pull/39387
=> Disable DRY_RUN for 8.13 packaging on Buildkite

.ci/jobs/packaging.yml
This commit disables triggering DRA packaging builds for the 8.x branch via Jenkins.
Relates: https://github.com/elastic/ingest-dev/issues/3095
=> Disable 8.x DRA packaging from Jenkins

.github/PULL_REQUEST_TEMPLATE.md
This PR adds a new section to the PR template for describing any steps users could take to mitigate disruptive changes, when a PR introduces such changes.
=> Add disruptive change mitigations section to PR template

CHANGELOG.next.asciidoc, x-pack/filebeat/input/http_endpoint/input.go
=> x-pack/filebeat/input/http_endpoint: ensure all responses are HTML-escaped

.ci/jobs/packaging.yml
This commit disables triggering DRA packaging builds for the 7.17 branch via Jenkins.
=> Disable 7.17 DRA packaging from Jenkins

.buildkite/scripts/dra.sh
This commit is the counterpart of #39391 for the 7.17 branch and disables the default DRY_RUN mode when running DRA packaging on Buildkite for the 7.17 branch.
- #39391
- elastic/ingest-dev#3095
=> Disable DRY_RUN for 7.17 packaging on Buildkite

.buildkite/pipeline.yml, .buildkite/scripts/common.sh, .buildkite/scripts/setenv.sh, .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml
In scope of https://github.com/elastic/ingest-dev/issues/3254 - added MODULE env var definition for Go Integration tests to match same behavior as on Jenkins.
Jenkins vs. Buildkite comparison: https://gist.github.com/oakrizan/bf2aa5f1cd1ab01daa1184f471a99abc
BK build: https://buildkite.com/elastic/beats-xpack-dockerlogbeat/builds?branch=oakrizan%3Axpack-dockerlogbeat-fixes
-
=> Add MODULE definition for x-pack/dockerlogbeat Go Integration tests

CHANGELOG.next.asciidoc, x-pack/filebeat/input/awss3/input_test.go, x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/graph/graph.go
=> x-pack/filebeat/input/entityanalytics/provider/azuread: fix query handling

CHANGELOG.next.asciidoc, x-pack/filebeat/input/internal/httplog/roundtripper.go
Attempt to log the request and response bodies and other details even when copying the body has been reported to have failed.
-
=> x-pack/filebeat/input/internal/httplog: improve req/resp logging

CHANGELOG.next.asciidoc, x-pack/auditbeat/processors/sessionmd/types/process.go
In order to reduce event data size, remove all fields from the add_session_metadata processor that are not required for the Kibana session viewer to function.
The unnecessary fields that are removed here are thread and tty fields.
These removed fields might have been used for other reasons than session view, but given this processor is in beta, there can be breaking changes. The `add_process_metadata` processor can also be used to get these fields.
- Checked that session view is still …
=> Remove fields not needed for session view in add_session_view processor

.buildkite/auditbeat/auditbeat-pipeline.yml, .buildkite/filebeat/filebeat-pipeline.yml, .buildkite/heartbeat/heartbeat-pipeline.yml, .buildkite/libbeat/pipeline.libbeat.yml, .buildkite/metricbeat/pipeline.yml, .buildkite/packetbeat/pipeline.packetbeat.yml, .buildkite/winlogbeat/pipeline.winlogbeat.yml, .buildkite/x-pack/pipeline.xpack.auditbeat.yml, .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml, .buildkite/x-pack/pipeline.xpack.filebeat.yml, .buildkite/x-pack/pipeline.xpack.heartbeat.yml, .buildkite/x-pack/pipeline.xpack.libbeat.yml, .buildkite/x-pack/pipeline.xpack.metricbeat.yml, .buildkite/x-pack/pipeline.xpack.osquerybeat.yml, .buildkite/x-pack/pipeline.xpack.packetbeat.yml, .buildkite/x-pack/pipeline.xpack.winlogbeat.yml
Fixed pipelines formatting
- Closes https://github.com/elastic/ingest-dev/issues/3310
=> Fixed pipelines formatting

.buildkite/auditbeat/auditbeat-pipeline.yml, .buildkite/filebeat/filebeat-pipeline.yml, .buildkite/heartbeat/heartbeat-pipeline.yml, .buildkite/libbeat/pipeline.libbeat.yml, .buildkite/metricbeat/pipeline.yml, .buildkite/packetbeat/pipeline.packetbeat.yml, .buildkite/scripts/setenv.sh, .buildkite/winlogbeat/pipeline.winlogbeat.yml, .buildkite/x-pack/pipeline.xpack.auditbeat.yml, .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml, .buildkite/x-pack/pipeline.xpack.filebeat.yml, .buildkite/x-pack/pipeline.xpack.heartbeat.yml, .buildkite/x-pack/pipeline.xpack.libbeat.yml, .buildkite/x-pack/pipeline.xpack.metricbeat.yml, .buildkite/x-pack/pipeline.xpack.osquerybeat.yml, .buildkite/x-pack/pipeline.xpack.packetbeat.yml, .buildkite/x-pack/pipeline.xpack.winlogbeat.yml
Explicitly set `DOCKER_PULL `, `RACE_DETECTOR` and `TEST_COVERAGE` variables for pipelines
The previous approach is unobvious and error-prone  
Relates https://github.com/elastic/ingest-dev/issues/3303
=> Explicitly set DOCKER_PULL, RACE_DETECTOR and TEST_COVERAGE for pipelines

.buildkite/metricbeat/pipeline.yml, .buildkite/scripts/changesets.psm1, .buildkite/scripts/changesets.sh, .buildkite/x-pack/pipeline.xpack.auditbeat.yml, .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml, .buildkite/x-pack/pipeline.xpack.filebeat.yml, .buildkite/x-pack/pipeline.xpack.metricbeat.yml, .buildkite/x-pack/pipeline.xpack.winlogbeat.yml
For reasons described in [^1], we hard coded `aws` or `kubernetes` for the env var `MODULE`, when no file changes were detected under `modules/` per project.
This commit reverts this and allows all module tests to run if no changesets apply. As discussed in [^1], for the tests to run properly (and not go into an infinite loop)
if there are no module changes the `MODULE` env var should **not** be set, rather than set to an empty string.
This commit is an important fix as it covers a major delta in test coverage between Jenkins and Buildkite.
[^1]: https://github.com/elastic/ingest-dev/issues/2993#issuecomment-2104741977
- https://github.com/elastic/ingest-dev/issues/2993#issuecomment-2104741977
Closes https://github.com/elastic/ingest-dev/issues/2993
- ✅ BK run with default labels: …
=> Remove hardcoded module definitions in CI

.buildkite/auditbeat/auditbeat-pipeline.yml, .buildkite/filebeat/filebeat-pipeline.yml, .buildkite/metricbeat/pipeline.yml, .buildkite/packetbeat/pipeline.packetbeat.yml, .buildkite/x-pack/pipeline.xpack.auditbeat.yml, .buildkite/x-pack/pipeline.xpack.filebeat.yml, .buildkite/x-pack/pipeline.xpack.heartbeat.yml, .buildkite/x-pack/pipeline.xpack.metricbeat.yml, .buildkite/x-pack/pipeline.xpack.packetbeat.yml
This commit makes some adjustments in the step conditions after reviewing the Jenkins files and how we perform the step validations in Jenkinsfile.
If a key `when` is inside the Jenkinsfile step [1], it will validate the required conditions [2], and if there are no `branches: true`, it will not include that step.
[1]: https://github.com/elastic/apm-pipeline-library/blob/fc2e6901e468e368dd1d44f021cbe55615e48266/vars/beatsStages.groovy#L32
[2]: https://github.com/elastic/apm-pipeline-library/blob/fc2e6901e468e368dd1d44f021cbe55615e48266/vars/beatsWhen.groovy#L35-L43 
I tried to go over the various project and try to consolidate the conditions.
=> [BK] - Remove certain steps from running for Branches

.buildkite/filebeat/filebeat-pipeline.yml, .buildkite/heartbeat/heartbeat-pipeline.yml
While adjusting the triggering conditions for https://github.com/elastic/beats/pull/39533 I missed the filebeat and heartbeat pipelines. 
This commit fixes that.
=> [BK] - Remove osx steps from branch execution

.buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml, .buildkite/x-pack/pipeline.xpack.osquerybeat.yml
This PR performs some cleanup on some environment variables used in the `dockerlogbeat` and `osquerybeat` pipelines.
=> Remove unused env vars from pipelines

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-cel.asciidoc, x-pack/filebeat/input/cel/input.go
=> x-pack/filebeat/input/cel: add http metrics collection

.buildkite/auditbeat/auditbeat-pipeline.yml
This commit adds missing mandatory checks on Buildkite, on the 7.17 branch for auditbeat. They can be found defined in Jenkins in https://github.com/elastic/beats/blob/b5f369062719b350dc31ed6768c25be4b95f2f6f/auditbeat/Jenkinsfile.yml#L36
=> Add next-major tests for auditbeat 7.17

.buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml, .buildkite/x-pack/pipeline.xpack.osquerybeat.yml
This PR performs some cleanup on some environment variables used in the `dockerlogbeat` and `osquerybeat` pipelines.
This is a manual backport from #39558
=> [8.14](backport #39534) Remove unused env vars from pipelines

.buildkite/filebeat/filebeat-pipeline.yml
This commit adds missing mandatory checks on Buildkite, specifically on the 7.17 branch for filebeat. They can be found defined in Jenkins in https://github.com/elastic/beats/blob/b5f369062719b350dc31ed6768c25be4b95f2f6f/filebeat/Jenkinsfile.yml#L39-L53
=> Add prev-minor/next-major tests for filebeat 7.17

.mergify.yml
This PR updates the Mergify configuration to look for the buildkite required checks and not the Jenkins ones.
=> Migrate left over to buildkite

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-cel.asciidoc, x-pack/filebeat/input/cel/input.go, x-pack/filebeat/input/cel/input_test.go
=> x-pack/filebeat/input/cel: add default user-agent to http requests

CHANGELOG.next.asciidoc, filebeat/module/santa/log/ingest/pipeline.yml, x-pack/filebeat/module/checkpoint/firewall/ingest/pipeline.yml, x-pack/filebeat/module/cisco/umbrella/ingest/pipeline.yml, x-pack/filebeat/module/coredns/log/ingest/pipeline-json.yml, x-pack/filebeat/module/iptables/log/ingest/pipeline.yml, x-pack/filebeat/module/panw/panos/ingest/pipeline.yml, x-pack/filebeat/module/threatintel/abusemalware/ingest/pipeline.yml, x-pack/filebeat/module/threatintel/abuseurl/ingest/pipeline.yml, x-pack/filebeat/module/threatintel/anomali/ingest/pipeline.yml, x-pack/filebeat/module/threatintel/malwarebazaar/ingest/pipeline.yml, x-pack/filebeat/module/threatintel/misp/ingest/pipeline.yml, x-pack/filebeat/module/threatintel/otx/ingest/pipeline.yml, x-pack/filebeat/module/threatintel/threatq/ingest/pipeline.yml
```
Prevent rename of message to event.original failing when event.original
already exists as can be the case when documents are being ingested via
logstash.
```
This makes the change for all modules listed as owned by security-service-integrations and sec-deployment-and-devices that still exist (some don't) and have this specific rename*. Some modules already make the check or use another already safe mechanism. 
Note that tthe cisco umbrella pipeline uses a set processor which will not fail, but would clobber `event.original`, so it also includes the check.
- For #38224
=> filebeat,x-pack/filebeat: prevent master=>event.original rename failures

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-http-endpoint.asciidoc, x-pack/filebeat/input/http_endpoint/ack.go, x-pack/filebeat/input/http_endpoint/ack_test.go, x-pack/filebeat/input/http_endpoint/handler.go, x-pack/filebeat/input/http_endpoint/handler_test.go, x-pack/filebeat/input/http_endpoint/input.go, x-pack/filebeat/input/http_endpoint/input_test.go, x-pack/filebeat/input/lumberjack/ack.go, x-pack/filebeat/tests/system/test_http_endpoint.py
See title.
The timeout ACK behaviour is tested manually using `elastic-package` using the the version here injected into the stack.
```
$ curl -X POST http://localhost:8080/ -d '{"data":1}' -H 'Content-Type: application/json'
{"message":"ok!"}
$ curl -X POST http://localhost:8080/?wait_for_completion_timeout=1m -d '{"data":1}' -H 'Content-Type: application/json'
{"message":"ok!"}
$ curl -X POST http://localhost:8080/?wait_for_completion_timeout=1s -d '{"data":1}' -H 'Content-Type: application/json'
{"message":"could not publish event within timeout"}
```
The first instance without a timeout returned immediately, the second took ~5s and the last ~2s. These are consistent with expected behaviour.
- Closes #38979
- Closes #39539
=> x-pack/filebeat/input/http_endpoint: make input GA

catalog-info.yaml
This commit enables Slack alerts for the main Beats Buildkite CI job. We only allow notifications for merge commit triggers i.e. the main and release branches and not for CI for PRs.
=> Enable Slack notifications for main BK CI Job

metricbeat/docs/modules/elasticsearch.asciidoc, metricbeat/module/elasticsearch/_meta/docs.asciidoc
Based on an offline conversation, when the `xpack.enabled: true` for the elasticsearch module, the documentation didn't clearly state the expected metricset list when the `metricsets` property is still set to some entries.
This update should clarify what happens when both `xpack.enabled: true` and `metricsets` are configured.
=> [Docs][Elasticsearch] Specify metricsets list behaviour with xpack mode enabled

.github/dependabot.yml
Set up Dependabot to manage the Azure SDK version.
With the current reactive and manual process, our dependencies are often outdated. To release a bugfix to a dependency, we need to wait for the following stack release instead of merging it shortly after it's available from Azure.
See https://github.com/elastic/beats/issues/39492 to learn more.
- Relates #39492
=> Manage Azure and Event Hub SDKs version with Dependabot

libbeat/monitoring/report/report.go
Delete an unused parameter and some unused decoding results in the beats monitoring initialization. This PR doesn't change behavior.
=> [libbeat] Small cleanup of unused code in monitoring initialization

CHANGELOG.next.asciidoc, x-pack/filebeat/input/http_endpoint/input.go
```
This is a partial backport of #39410 to fix the missing replacement of
"*" with the input ID.
```
Note: This has been tested by injecting into an elastic-package-managed stack running the integration system tests in elastic/integrations#9909, and then examining the resulting request trace file from that.
Without this change the following is seen.
- Related #39410
=> x-pack/filebeat/input/http_endpoint: fix request trace logging file names

CHANGELOG-developer.next.asciidoc, filebeat/beater/acker.go
Remove some debug log entries about acked events. Those log entries turn out to be very verbose and of very little use. They do not carry any information about the acked events, and we already have metrics about acked events in the 30s metrics and monitoring HTTP endpoint.
1. Build Filebeat from this PR
2. Start Filebeat with `filestream` or `log` input configured and debug logs enabled (at least the `acker` selector)
3. Assert no `stateful ack ...` or `stateless ack ...` messages are logged
~~## Logs~~
=> Remove verbose debug logs from acker

.github/workflows/updatecli.d/bump-golang-7.17.yml, .github/workflows/updatecli.d/bump-golang.yml
Use `GITHUB_ACTOR` instead. `GIT_USER` is not anymore available.
This was caused after merging https://github.com/elastic/beats/pull/39646 since https://github.com/elastic/beats/pull/39472 didn't update the variable. 
I tested this feature branch and it worked fine:
- https://github.com/elastic/beats/actions/runs/9192072213
-
=> updatecli: use `GITHUB_ACTOR`

.buildkite/x-pack/pipeline.xpack.metricbeat.yml, x-pack/metricbeat/module/aws/terraform.tf
1. We have been using the default AWS region (eu-cental-1). However, the build agents are located in `us-east`. 
The PR sets AWS region to `us-east-1`.
2. Changed DB instance class to `db.t3.micro`. The previous `db.t2` is now has [depreceted](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html) MySQL support.
3. Un-skipped x-pack/metricbeat Cloud (MODULE) Tests
- Closes https://github.com/elastic/ingest-dev/issues/3170
- Closes https://github.com/elastic/ingest-dev/issues/3025
=> [CI] Metricbeat: set AWS region to terraform.tf

.buildkite/x-pack/pipeline.xpack.filebeat.yml
Enabled macOS arm tests for x-pack/filebeat on Buildkite as it was in Jenkins. After orka macOS agent adjustments & retry enabling tests seems to be working.
Shouldn't be backported to 7.17, since there is no macOS arm step in Jenkins for 7.17.
Jenkins vs. Buildkite comparison: https://gist.github.com/oakrizan/0ef4a4df595547489538cbbc0ad1a4e5
BK builds: https://buildkite.com/elastic/beats-xpack-filebeat/builds?branch=oakrizan%3Axpack-filebet-enable-macos-arm-tests
=> Enable macOS arm tests for x-pack/filebeat

.ci/jobs/docker-compose.yml, x-pack/filebeat/input/awss3/input_integration_test.go
This PR fixes the following errors captured https://github.com/elastic/ingest-dev/issues/3312
```
input/awss3/input_integration_test.go:138:46: undefined: s3Input
input/awss3/input_integration_test.go:144:19: undefined: s3Input
input/awss3/input_integration_test.go:238:14: undefined: s3Input
```
Initially these tests resulted as broken because of this PR https://github.com/elastic/beats/pull/39353 which quoting from the description
> This change is meant to have no functional effect, it is strictly a cleanup and reorganization in preparation for future changes. The hope is that the new layout makes initialization steps and logical dependencies clearer. 
split up the pre-existing `s3input` to `s3PollerInput` and `sqsReaderInput` without reflecting this in the …
=> [aws/s3]: fix s3_input integration test

libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc
👋 Playing forward https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1179, our client-side docs think `index` indicates a literal Elasticsearch index when in now this means any ingest target (index, alias, or data stream). cc: @dakrone @anniegale9538 
Doc update to clarify that Elasticsearch output `index` indicates ingest target (so index, alias, or data stream). 
NA
NA
NA
NA
NA
Will port to saying like [Logstash Elasticsearch output](https://www.elastic.co/guide/en/logstash/master/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-index) now does for `index` the highlighted text: 
NA
=> (+Doc) FB "index" means ingesting target

x-pack/filebeat/input/awss3/input.go, x-pack/filebeat/input/awss3/input_integration_test.go, x-pack/filebeat/input/awss3/input_test.go
Fix issues described in https://github.com/elastic/beats/issues/39706 that prevent using a custom endpoint with S3 + SQS.
Users can workaround this issue via S3 bucket polling. The S3 bucket polling still works just fine with a custom endpoint, it's just adding in SQS where it breaks. We need to publish a [new version of the AWS integration with the endpoint field exposed on the relevant AWS integrations which is tracked here](https://github.com/elastic/integrations/pull/9865)
Proposed Fixes for Main: https://github.com/elastic/beats/pull/39722
Fixes for 8.14:
Optional for 8.14:
Limit the scope of the endpoint resolver:
1. When users provide us an endpoint that begins with S3, do not set an Endpoint Resolver but set the Endpoint field so the Default resolver can generate URLs using the …
=> [8.14] Fix handling of custom Endpoint when using S3 + SQS

CHANGELOG.next.asciidoc, auditbeat/module/file_integrity/kprobes/seccomp_linux_amd64.go
`seccomp.ModifyDefaultPolicy` for amd64 whitelists the specified syscalls. On the contrary, for arm64  the same function blacklists them 🙂 Thus this PR adjusts the code of `kprobes` Backend of FIM to add the missing syscalls only for amd64.
N/A
N/A
N/A
N/A
N/A
N/A
N/A
=> [auditbeat/fim/kprobes] Correct seccomp policy for arm64

CHANGELOG-developer.next.asciidoc, packetbeat/route/route_windows_test.go
This improves the error handling for the testing invocation of netsh to allow
the cause of #39698 to be identified.
- For #39698
=> packetbeat/route: improve netsh output handling

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-http-endpoint.asciidoc, x-pack/filebeat/input/http_endpoint/handler_test.go, x-pack/filebeat/input/http_endpoint/validate.go
=> x-pack/filebeat/input/http_endpoint: add support for base64-encoded HMAC headers

CHANGELOG.next.asciidoc
add:
```
- Fix handling of endpoint for custom domains and ensure region, default_region, and region parsed from queue_url are applied in the order specified in the documentation for the awss3 input {pull}39709[39709]
```
=> Update CHANGELOG.next.asciidoc for Filebeat awss3 Fixes

CHANGELOG.next.asciidoc, winlogbeat/eventlog/errors_windows.go, winlogbeat/sys/wineventlog/syscall_windows.go
Adds ERROR_INVALID_PARAMETER as a recoverable error type.
There have been some reports that under heavy load and when automatic event log backups, a race condition can happen where the handle is reported as invalid when doing the call to EvtNext. This will prevent users from needing to restart winlogbeat when this happens.
=> [winlogbeat] Recover from error 87 if found

NOTICE.txt, filebeat/tests/integration/filebeat_test.go, go.mod, go.sum, libbeat/tests/integration/framework.go
Update elastic-agent-libs to v0.9.11 and add tests to ensure Beats always logs as JSON to a file when no logging is explicitly configured.
None, it's a bug fix. 
1. Build any Beat from this PR branch
2. Run it with no logging configuration set
3. Ensure the default log file is created.
You can also run the integration test added:
```
mage buildSystemTestBinary && go test -count=1 -tags=integration -run=TestFilebeatRunsAndLogs -v ./tests/integration
```
If you want to see the test failing before the fix, downgrade `elastic-agent-libs`
```
go get -u github.com/elastic/elastic-agent-libs@v0.9.8
```
Then run the testt
~~## Logs~~
=> update elastic-agent-libs to v0.9.11

.github/dependabot.yml
Set up Dependabot to manage the GCP SDK version.
With the current reactive and manual process, our dependencies are often outdated. To release a bugfix to a dependency, we need to wait for the following stack release instead of merging it shortly after it's available from GCP.
See https://github.com/elastic/beats/issues/39492 to learn more.
- Relates #39492
=> Manage GCP SDKs version with Dependabot

CHANGELOG.next.asciidoc, x-pack/agentbeat/agentbeat.spec.yml
Add filebeat benchmark input to agentbeat.  This can be used to
generate events to send to the configured output.
Write an integration that uses the benchmark input
https://github.com/elastic/integrations/pull/8733
- Relates #37437
- Benchmark an output so it isn't constrained by the input
=> add benchmark input to agentbeat

CHANGELOG.next.asciidoc, x-pack/heartbeat/cmd/import.go
Fix browser plugin import to be bundled inside agentbeat, which is now being skipped and it prevents browser monitors from working.
Browser monitors do not work as part of agentbeat.
1. Build and package elastic-agent-complete locally.
2. Enroll in a private location.
3. Create a browser monitor and check agentbeat does not error out with:
```
Error creating runner from config: factory could not create monitor: monitor type browser does not exist, valid types are [synthetics/icmp tcp synthetics/tcp http synthetics/http icmp]
```
=> [Heartbeat] Move import to cmd for agentbeat

CHANGELOG.next.asciidoc, x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/okta.go, x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/okta_test.go, x-pack/filebeat/input/entityanalytics/provider/okta/okta.go, x-pack/filebeat/input/entityanalytics/provider/okta/okta_test.go, x-pack/filebeat/input/entityanalytics/provider/okta/statestore.go
See title.
To test the internal package, you will need to obtain an okta account and then run the following in that package's directory:
```
$ OKTA_HOST=dev-<REDACTED>-admin.okta.com OKTA_TOKEN=<REDACTED> go test -log_response -v -run Test$
```
Replacing the redacted parts with the appropriate values.
This should result in output similar to the following. In particular, the output for Test/none/my_groups.
```
=== RUN   Test
=== RUN   Test/none
=== RUN   Test/none/me
okta_test.go:83: user: {"id":"<REDACTED>","status":"ACTIVE","created":"1066-10-13T20:57:12Z","activated":"0001-01-01T00:00:00Z","statusChanged":"1066-10-13T04:37:39Z","lastLogin":"1066-10-13T02:50:06Z","lastUpdated":"1066-10-13T04:37:39Z","passwordChanged":"1066-10-13T04:37:39Z","type":{"id":"<REDACTED>"},"profile":{"login":"ef …
```
=> x-pack/filebeat/input/entityanalytics/provider/okta: add user group membership support

metricbeat/module/docker/memory/memory.go
Stop returning errors when there are no metric values for the Docker memory metricset.
The docker metricset returns an error when there are no memory metric values available. This condition can happen when there are no running containers on Docker.
When no containers are running, the metricset returns an error at every collection, creating noise.
- Is there a use case when we should return an error instead?
- Should I add a logger to log a debug message saying "no memory stats data available"?
-
=> [Docker] Stop returning errors when there are no metric values

CHANGELOG-developer.next.asciidoc, NOTICE.txt, go.mod, go.sum, x-pack/filebeat/input/salesforce/input.go
This reduces the dep count since all other uses of the package are at v5. The API that is used here does not change.
https://github.com/golang-jwt/jwt/blob/main/MIGRATION_GUIDE.md
-
=> x-pack/filebeat/input/salesforce: bump github.com/golang-jwt/jwt to v5

CHANGELOG-developer.next.asciidoc, packetbeat/route/route_test.go, packetbeat/route/route_windows_test.go
```
Windows 2022 appears to have added new text to the output of netsh. The text
is interpreted as having three fields. This impact on the behaviour of the
field splitting which expects five.
- Originally this would cause a panic due to bounds checking. This was fixed
in #39757 by erroring on an unexpectedly short line.
- The fieldsN helper expects lines to be n fields or longer, but does not
terminate on lines with fewer fields.
So treat the first blank line found in the table as the end of the table and
fix the fieldsN helper.
```
- Closes #39698
=> packetbeat/route: fix test failure on Windows 2022

CHANGELOG.next.asciidoc, libbeat/autodiscover/providers/kubernetes/pod.go, libbeat/autodiscover/providers/kubernetes/service.go, libbeat/docs/shared-autodiscover.asciidoc
- WHAT: Apply namespace filter to the watchers of kubernetes provider.
- WHY:  please check https://github.com/elastic/beats/issues/38978 for details.
I also added the option `HonorReSyncs` to [make sure we don't lose any events](https://github.com/elastic/elastic-agent-autodiscover/blob/15147343f9fe5b15d90f756fc1447843101792be/kubernetes/watcher.go#L158-L166).
Run your own metricbeat as stated [here](https://github.com/elastic/beats/tree/main/dev-tools/kubernetes). The way I tested this change is better explained in **Results** section.
- Relates https://github.com/elastic/beats/issues/38978
I have a cluster with the following resources:
```
c@c:~/$ kubectl get pods --all-namespaces
NAMESPACE            NAME                                         READY   STATUS    RESTARTS   AGE
default …
```
=> [Kubernetes Provider] Apply namespace filter to watchers

filebeat/tests/system/test_crawler.py, filebeat/tests/system/test_harvester.py, filebeat/tests/system/test_registrar.py, filebeat/tests/system/test_shutdown.py
This PR fixes following test cases which are flaky for macOS:
- tests/system/test_harvester.py::Test::test_debug_reader
- tests/system/test_crawler.py::Test::test_tail_files
- tests/system/test_crawler.py::Test::test_encodings
- tests/system/test_registrar.py::Test::test_restart_state_reset_ttl_no_clean_inactive
- tests/system/test_registrar.py::Test::test_restart_state_reset
- tests/system/test_registrar.py::Test::test_restart_state
- tests/system/test_registrar.py::Test::test_registry_file_update_permissions
- tests/system/test_shutdown.py::Test::test_shutdown
On MacOS, the FQDN lookup takes some time (~5 seconds) before signal handlers are set up 
- the lingering FQDN lookup code is [here](https://github.com/elastic/beats/blob/main/libbeat/cmd/instance/beat.go#L836-L844)
To make sure …
=> filebeat: Fix flaky test case on macOS

metricbeat/docs/running-on-docker.asciidoc
This adds a section to the "running on docker" doc to mention the use of `--cgroupns=host`.
While monitoring for private cgroup namespaces technically works (after no small amount of effort), the basic use case of "monitor the host cgroups from within a container with a private cgroup namespace" requires a considerable amount of hacks and should probably be considered best-effort. This adds a section telling the user to select a host namespace.
=> Add section on `cgroupns` usage for metricbeat under docker

x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
This PR is to enhance documentation on `expand_event_list_from_field` parameter. When using `expand_event_list_from_field`, `content_type` is required to set to `application/json`.
=> Add a note when using `expand_event_list_from_field`, `content_type` is required to set to `application/json`

dev-tools/packaging/templates/ironbank/auditbeat/Dockerfile, dev-tools/packaging/templates/ironbank/elastic-agent/Dockerfile, dev-tools/packaging/templates/ironbank/filebeat/Dockerfile, dev-tools/packaging/templates/ironbank/heartbeat/Dockerfile, dev-tools/packaging/templates/ironbank/metricbeat/Dockerfile, dev-tools/packaging/templates/ironbank/packetbeat/Dockerfile
Change ubi base image from 9.3 to 9.4 used in Ironbank Docker images for all 7.17 Beats + Elastic Agent
=> Update ubi version to 9.4 in Ironbank Dockerfile

x-pack/osquerybeat/beater/logger_plugin.go
Osquerybeat: Translate osqueryd INFO level logs into osquerybeat DEBUG level logs. 
The osqueryd doesn't have DEBUG level logging and the lowest level is INFO. This was causing too many unwanted log messages captured from osqueryd at the default INFO logging level. 
This addresses the request for reduce the number of logs emitted from osqueryd at the default INFO logging level:
https://github.com/elastic/ingest-dev/issues/2385#issuecomment-2161583521
- Relates https://github.com/elastic/ingest-dev/issues/2385
=> Osquerybeat: Translate osqueryd INFO level logs into osquerybeat DEBUG level logs

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-httpjson.asciidoc, x-pack/filebeat/input/httpjson/input_test.go, x-pack/filebeat/input/httpjson/request.go, x-pack/filebeat/input/httpjson/transform_append.go, x-pack/filebeat/input/httpjson/transform_set.go
See title.
In the httpjson package run the following commands. The first should show a set of messages at DEBUG level and none at ERROR level. The second should show no output.
```
go test -run 'TestInput/.*_not_log_fail' -v | grep ignored
```
```
go test -run 'TestInput/.*[^_][^n][^o][^t][^_][^l][^o][^g][^_][^f][^a][^i][^l]$' -v | grep ignored # ¯\_(ツ)_/¯
```
- Closes #34544
- Closes #38291
=> x-pack/filebeat/input/httpjson: allow elision of set and append failure logging

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-cel.asciidoc, x-pack/filebeat/input/cel/config.go, x-pack/filebeat/input/cel/input.go, x-pack/filebeat/input/cel/input_test.go
The previous configuration system did not allow users to remove trace logs from agents after they are no longer needed. This is potential security risk as it leaves potentially sensitive information on the file system beyond its required lifetime. The mechanism for communicating to the input whether to write logs is not currently powerful enough to indicate that existing logs should be removed without deleting logs from other instances. So add an enabled configuration option to allow the target name to be sent independently of whether the files should be written or removed.
The new option is optional, defaulting to the previous behaviour so that it can be opted into via progressive repair in the client integrations.
---
Similar changes should be made in other inputs that write trace logs. …
=> x-pack/filebeat/input/cel: add ability to remove request trace logs

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-httpjson.asciidoc, x-pack/filebeat/input/httpjson/config_request.go, x-pack/filebeat/input/httpjson/input.go, x-pack/filebeat/input/httpjson/input_test.go
This is a replay of #39969, but for the HTTPJSON input.
The previous configuration system did not allow users to remove trace logs from agents after they are no longer needed. This is potential security risk as it leaves potentially sensitive information on the file system beyond its required lifetime. The mechanism for communicating to the input whether to write logs is not currently powerful enough to indicate that existing logs should be removed without deleting logs from other instances. So add an enabled configuration option to allow the target name to be sent independently of whether the files should be written or removed.
The new option is optional, defaulting to the previous behaviour so that it can be opted into via progressive repair in the client integrations.
-
=> x-pack/filebeat/input/httpjson: add ability to remove request trace logs

x-pack/elastic-agent/pkg/agent/control/server/server.go, x-pack/elastic-agent/pkg/agent/operation/tests/scripts/serviceable-1.0-darwin-x86_64/main.go
Fix `http.MethodGet` constant casing in elastic-agent server code in order to fix CI build.
Change `proto.ConnInfo` to `proto.StartupInfo` after update of `elastic-agent-client` dep introduced with PR #39800
-
=> Fix elastic-agent 7.17 build

x-pack/filebeat/tests/integration/managerV2_test.go
What it says on the tin.
Without this change, the linter complains like so:
```
S1024: should use time.Until instead of t.Sub(time.Now()) (gosimple)
```
See https://github.com/elastic/beats/pull/40030/files#diff-df9d93045b24b2f8f834d399fb096632e419254901cb9f0c504636c7662c369dL244
=> Making linter happy

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-http-endpoint.asciidoc, x-pack/filebeat/input/http_endpoint/config.go, x-pack/filebeat/input/http_endpoint/handler_test.go, x-pack/filebeat/input/http_endpoint/input.go
This is essentially a replay of #39969, but for the http_endpoint input.
The previous configuration system did not allow users to remove trace logs from agents after they are no longer needed. This is potential security risk as it leaves potentially sensitive information on the file system beyond its required lifetime. The mechanism for communicating to the input whether to write logs is not currently powerful enough to indicate that existing logs should be removed without deleting logs from other instances. So add an enabled configuration option to allow the target name to be sent independently of whether the files should be written or removed.
The new option is optional, defaulting to the previous behaviour so that it can be opted into via progressive repair in the client integrations. …
=> x-pack/filebeat/input/http_endpoint: add ability to remove request trace logs

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-entity-analytics.asciidoc, x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/graph/graph.go, x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/graph/graph_test.go, x-pack/filebeat/input/entityanalytics/provider/okta/conf.go, x-pack/filebeat/input/entityanalytics/provider/okta/okta.go, x-pack/filebeat/input/entityanalytics/provider/okta/okta_test.go
This is essentially a replay of #39969, but for the entity analytics providers.
The previous configuration system did not allow users to remove trace logs from agents after they are no longer needed. This is potential security risk as it leaves potentially sensitive information on the file system beyond its required lifetime. The mechanism for communicating to the input whether to write logs is not currently powerful enough to indicate that existing logs should be removed without deleting logs from other instances. So add an enabled configuration option to allow the target name to be sent independently of whether the files should be written or removed.
The new option is optional, defaulting to the previous behaviour so that it can be opted into via progressive repair in the client …
=> x-pack/filebeat/input/entityanalytics/{okta,azuread/fetcher/graph}: add ability to remove request trace logs

.buildkite/auditbeat/auditbeat-pipeline.yml, .buildkite/filebeat/filebeat-pipeline.yml, .buildkite/heartbeat/heartbeat-pipeline.yml, .buildkite/libbeat/pipeline.libbeat.yml, .buildkite/metricbeat/pipeline.yml, .buildkite/packetbeat/pipeline.packetbeat.yml, .buildkite/winlogbeat/pipeline.winlogbeat.yml, .buildkite/x-pack/pipeline.xpack.auditbeat.yml, .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml, .buildkite/x-pack/pipeline.xpack.filebeat.yml, .buildkite/x-pack/pipeline.xpack.heartbeat.yml, .buildkite/x-pack/pipeline.xpack.libbeat.yml, .buildkite/x-pack/pipeline.xpack.metricbeat.yml, .buildkite/x-pack/pipeline.xpack.osquerybeat.yml, .buildkite/x-pack/pipeline.xpack.packetbeat.yml, .buildkite/x-pack/pipeline.xpack.winlogbeat.yml
Updated labels and GH check labels to align styling.
BK builds: https://buildkite.com/elastic/beats/builds?branch=oakrizan%3Apostmigration-naming-fiixes
=> Postmigration naming fixes

CHANGELOG.next.asciidoc, x-pack/filebeat/input/entityanalytics/provider/activedirectory/internal/activedirectory/activedirectory.go
Apparently the base DN prefixes used in the wild are not restricted to CN=Users, so remove that check in the query.
---
See https://discuss.elastic.co/t/ad-entity-analytics-invalid-base-dn/362071 for background.
-
=> x-pack/filebeat/input/entityanalytics/provider/internal/activedirectory: relax base DN constraint

CHANGELOG.next.asciidoc, x-pack/filebeat/input/gcs/config.go, x-pack/filebeat/input/gcs/input_test.go
=> x-pack/filebeat/input/gcs: allow absent credentials when using GCS with ADC

x-pack/libbeat/management/tests/init.go
We're relying on `os.TmpDir` and `unix.Now()` to get us a unique directory for a test env.
This leads to a CI failure [here](https://buildkite.com/elastic/beats-xpack-libbeat/builds/4835) because we're relying on  seconds resolution.
This PR fixes this behaviour and uses `t.TmpDir`. Each subsequent call to `t.TempDir` returns a unique directory and it's also automatically removed once test is executed
=> [x-pack][tests] - switch to t.TempDir

libbeat/publisher/processing/processors.go
This PR is the aftermath of profiling the netflow integration test of [this PR](https://github.com/elastic/beats/pull/40080) (PS: the pcap I used as input is ~25MB thus I won't include it in beats repo)
So this is the cpu profile flamegraph before the commit of this PR
As we can see `debugPrintProcessor` is invoked and we pay the "performance" price of encoding every event in json even when our log isn't set up with DEBUG level. 
The respective cpu profile flamegraph after this PR with debugPrintProcessor still being there but exiting directly when log DEBUG is not enabled
Extracting the average EPS of the aformentioned netflow integration tested on my local macbook with a local ES inside a container
| Before this PR | With this PR |
|----------------|--------------|
| 18490       | 33760 …
=> [debugPrintProcessor]: exit directly when log doesn't have debug level enabled

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-http-endpoint.asciidoc, x-pack/filebeat/input/http_endpoint/handler.go, x-pack/filebeat/input/http_endpoint/handler_test.go, x-pack/filebeat/input/http_endpoint/input.go
In order to avoid precision loss during processing of numeric values that cannot be exactly represented in a double-precision floating point value, the json.Number unmarshaller is used. This has the effect that conversion to native types on exit from the CEL program fails since protobuf does not handle json.Number. For non-nested values that are referenced by the CEL runtime, this does not cause an issue since the native-to-value conversion will attempt to convert the string representation of the numeric value. This conversion is not recursively applied.
Recursively apply the type conversion to all child values on referencing a value; converting numeric values to the most exact type and falling back to a string representation if no native numeric representation is possible.
Also add an …
=> x-pack/filebeat/input/http_endpoint: fix handling of deeply nested numeric values

.buildkite/auditbeat/auditbeat-pipeline.yml, .buildkite/filebeat/filebeat-pipeline.yml, .buildkite/heartbeat/heartbeat-pipeline.yml, .buildkite/libbeat/pipeline.libbeat.yml, .buildkite/metricbeat/pipeline.yml, .buildkite/packetbeat/pipeline.packetbeat.yml, .buildkite/winlogbeat/pipeline.winlogbeat.yml, .buildkite/x-pack/pipeline.xpack.auditbeat.yml, .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml, .buildkite/x-pack/pipeline.xpack.filebeat.yml, .buildkite/x-pack/pipeline.xpack.heartbeat.yml, .buildkite/x-pack/pipeline.xpack.libbeat.yml, .buildkite/x-pack/pipeline.xpack.metricbeat.yml, .buildkite/x-pack/pipeline.xpack.osquerybeat.yml, .buildkite/x-pack/pipeline.xpack.packetbeat.yml, .buildkite/x-pack/pipeline.xpack.winlogbeat.yml, libbeat/tests/compose/wrapper.go
Updated labels and GH check labels to align styling.
Libbeat test failure is not related to changes in current PR - https://github.com/elastic/ingest-dev/issues/3520
BK builds: https://buildkite.com/elastic/beats/builds?branch=oakrizan%3Apostmigration-naming-fixes-7-17
=> Postmigration naming fixes 7.17

.github/dependabot.yml
Fix Dependabot config for cloud providers' SDK dependencies.
After visiting https://github.com/elastic/beats/network/updates, I noted the following message:
> Update configs must have a unique combination of 'package-ecosystem', 'directory', and 'target-branch'
In our use case, the two `package-ecosystem: gomod` definitions have the same values:
```
package-ecosystem: gomod
directory: /
target-branch: <default value>
```
We can't have two `package-ecosystem: gomod` definitions for the same directory. 
So, I guess we must merge the CSP SDK definition into the existing one.
=> Dependabot: fix cloud providers' SDK dependencies

CHANGELOG.next.asciidoc, x-pack/metricbeat/module/aws/utils.go, x-pack/metricbeat/module/aws/utils_test.go
This PR is to fix a bug in cloudwatch metricbeat module when include_linked_accounts is false. Because where the wrongly put return, we are missing metrics in pagination. I also added a test for the case when there is more than one page of results from ListMetrics API.
No disruptive user impact.
1. Setup your AWS account to have multiple RDS clusters and make sure we have metrics in CloudWatch.
2. Start Metricbeat with `aws.yml` looks like this:
```
- module: aws
period: 1m
credential_profile_name: elastic-observability
metricsets:
- cloudwatch
regions: eu-west-3
latency: 10m
include_linked_accounts: false
metrics:
- namespace: AWS/RDS
name: ["CPUUtilization"]
resource_type: rds
statistic: ["Average"]
```
You should see metrics only being collected from 2 RDS clusters. But if you change …
=> [aws] Fix missing metrics bug when include_linked_accounts set to false

CHANGELOG.next.asciidoc, x-pack/filebeat/input/cel/input.go, x-pack/filebeat/input/salesforce/input.go
It turns out that retryablehttp will pass a nil *http.Response to the client's ErrorHandler function although this is not documented. In the cases where we are using this, this will result in a nil deference panic when the retries exceed their maximum. So, check for nilness to avoid this.
-
=> x-pack/filebeat/input/{cel,salesforce}: check response for nilness before logging

.github/workflows/platform-ingest-project-board.yml
This PR updates the GitHub workflow for adding issues to the Platform Ingest project board.  It now defaults the Area field to "Data Plane" (used to be "Elastic Agent" which was renamed to "Control Plane").
=> Default to Area:"Data Plane" when issues are added to Platform Ingest project board

x-pack/filebeat/tests/integration/managerV2_test.go
:warning: **Auto-merge is enabled** :warning:
TestRecoverFromInvalidOutputConfiguration could cause a race condition and close a channel twice, this commit replaces the original implementation by a sync.Once when closing the channel.
None, this PR only fixes a broken test
Run the test that was failing: 
```
mage clean buildSystemTestBinary
go test -tags=integration ./tests/integration -count=1 -run=TestRecoverFromInvalidOutputConfiguration
```
~~## …
=> Prevent race condition on TestRecoverFromInvalidOutputConfiguration

x-pack/metricbeat/module/azure/monitor/client_helper.go
(minor) Fix the missing metric definitions error message.
[Before the change](https://github.com/elastic/beats/blob/5671cff8d1430ec9586ac1442f2033dbb24af678/x-pack/metricbeat/module/azure/monitor/client_helper.go#L48), in case of missing metric definitions, the metricset would log something like this:
```
no metric definitions were found for resource %s and namespace %s. Verify if the namespace is spelled correctly or if it is supported by the resource in case. /subscriptions/123/resourceGroups/abc/providers/Microsoft.Compute/virtualMachines/abcMicrosoft.Compute/virtualMachines
```
=> Azure Monitor: Correct log message format for missing metric definitions

CHANGELOG.asciidoc, x-pack/filebeat/input/awscloudwatch/cloudwatch.go, x-pack/filebeat/input/awscloudwatch/cloudwatch_test.go
- WHAT: Set `startTime` to `0` for the first iteration when retrieving log events from CloudWatch
- WHY:  to fix error:
```
InvalidParameterException: 1 validation error detected: Value '-6795364578871' at 'startTime' failed to satisfy constraint: Member must have value greater than or equal to 0"
```
as mentioned in https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_StartQuery.html#API_StartQuery_RequestSyntax:
```
startTime
The beginning of the time range to query. The range is inclusive, so the specified start time is included in the query. Specified as epoch time, the number of seconds since January 1, 1970, 00:00:00 UTC.
Type: Long
Valid Range: Minimum value of 0.
Required: Yes
```
and in https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs#Filt …
=> [input/awscloudwatch] Set startTime to 0 for the first iteration of retrieving log events from CloudWatch

metricbeat/mb/testing/modules.go, x-pack/metricbeat/module/aws/sqs/sqs_integration_test.go
Try to fetch CloudWatch metrics multiple times instead of just once. 
CloudWatch metrics can take time to appear after creating a brand-new resource. So, the tests must fetch the metrics multiple times until they find the metric values or reach the time limit.
- https://github.com/elastic/beats/issues/40242
=> Add PeriodicReportingFetchV2Error to fetch metrics multiple times

x-pack/filebeat/input/websocket/input.go
```
The flow control of the main loop is simpler without the extra goroutine
and the initial websocket response body was previously not being logged
since an io.ReadCloser is not a JSON-serialisable type.
```
-
=> x-pack/filebeat/input/websocket: do minor clean-up in main loop

.github/dependabot.yml
- Add cloud provider SDKs to the `allow` list. 
- Focus GCP SDK packages to `cloud.google.com/go` only.
The `patterns` list in the `groups` section only matches the dependencies included in the `allow` list. To learn more, see https://github.com/elastic/beats/issues/39492#issuecomment-2217791699
The `cloud.google.com/go` packages focus on Google Cloud Platform (GCP) specifically, allowing the use of APIs for services like Compute Engine, Cloud Storage, BigQuery, Pub/Sub, and others.
- Relates #39492
=> Dependabot: add CSP SDKs to the `allow` list

CHANGELOG.next.asciidoc, NOTICE.txt, go.mod, go.sum, x-pack/filebeat/docs/inputs/input-cel.asciidoc, x-pack/filebeat/input/cel/input_test.go, x-pack/filebeat/input/cel/integration_test.go
This brings error-handling improvements.
* better error localisation in error snippets
* fixed handling of errors containing Go fmt verb syntax
* fix type signature of flatten extension
* recover internal panics to informative errors
---
~If elastic/mito#71 is merged before this PR closes, I think it would be worth adding that into this change and bumping to v1.15.0.~ Now included in this change.
Note that runtime error handling is still not perfect. ~I will come back to this later.~ I've looked into this and what I was thinking was happening is happening; the `_+_` call is returning an error type and there is no `get` overload for an error. It looks like the CEL runtime is not decorating/throwing when the `_+_` call returns the error, so the next call is what gives error location …
=> mod: update elastic/mito to version v1.15.0

CHANGELOG.next.asciidoc, x-pack/filebeat/input/cel/input.go
This is the minimal change necessary to fix the following problem.
Around the time of a rate limit reset, if current time is after the reset time returned in response headers, the rate limiting code will set a negative target rate, and if that's done at a time when no request budget has accumulated, it will not recover and will wait forever.
- For #40106
=> x-pack/filebeat/input/cel: avoid a negative request rate

libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc
In the Elasticsearch output page for each of the Beats, the "Compatibility" section notes that you can only connect to Elasticsearch instances at the same or a newer version as the Beat. The default behaviour is changed via https://github.com/elastic/beats/pull/36884 so this updates the Beats docs accordingly:
---
Rel: https://github.com/elastic/ingest-docs/issues/1135
Related Fleet & Agent docs PR: https://github.com/elastic/ingest-docs/pull/1205
=> Document updated default for `output.elasticsearch.allow_older_versions`

x-pack/auditbeat/processors/sessionmd/provider/ebpf_provider/ebpf_provider.go, x-pack/auditbeat/processors/sessionmd/provider/procfs_provider/procfs_provider.go
Cleanup a couple of log messages formatters.
Noticed a couple of wrong formatters in the log messages resulting in the messages like this:
```
{"log.level":"warn","@timestamp":"2024-07-25T16:15:25.261-0400","log.logger":"processor.add_session_metadata","log.origin":{"function":"github.com/elastic/beats/v7/x-pack/auditbeat/processors/sessionmd/provider/ebpf_provider.prvdr.SyncDB","file.name":"ebpf_provider/ebpf_provider.go","file.line":220},
"message":"%!w(*errors.errorString=&{process 59414 was not seen after 281.383636ms})","service.name":"auditbeat","ecs.version":"1.6.0"}
```
```
{"log.level":"warn","@timestamp":"2024-07-25T16:45:05.690-0400","log.logger":"processor.add_session_metadata","log.origin":{"function":"github.com/elastic/beats/v7/x-pack/auditbeat/processors/sessionmd/provider/ …
```
=> [Auditbeat]: Cleanup a couple of log messages formatters

CHANGELOG.next.asciidoc, NOTICE.txt, go.mod, go.sum, libbeat/cmd/instance/beat.go
use go-sysinfo v1.14.1 and elastic-agent-system-metrics v0.10.6
go-sysinfo was lower-casing FQDN by default, this new version does not. Not its user should do it if necessary. elastic-agent-system-metrics is also upgraded to a version that lowercase the FQDN when it's used as `host.name`
It might cause the FQDN or anything using it to be reported with mixed case instead of lower case
The …
=> use go-sysinfo v1.14.1 and elastic-agent-system-metrics v0.10.6

x-pack/auditbeat/processors/sessionmd/docs/add_session_metadata.asciidoc
We need a placeholder for accurate testing and to break docs-ci gridlock between repos
* [Doc: Add docs for Auditbeat add_session_metadata processor #40252](https://github.com/elastic/beats/pull/40252) won't pass docs-ci because doc build is not pulling from the new repo. 
* [Add x-pack-auditbeat to conf.yaml docs#3038](https://github.com/elastic/docs/pull/3038) won't pass docs-ci because the files we're trying to pull in haven't been merged.
=> Auditbeat: Add placeholder for new docs directory and file

CHANGELOG.next.asciidoc, x-pack/filebeat/input/awss3/input_benchmark_test.go, x-pack/filebeat/input/awss3/interfaces.go, x-pack/filebeat/input/awss3/mock_interfaces_test.go, x-pack/filebeat/input/awss3/s3.go, x-pack/filebeat/input/awss3/s3_objects.go, x-pack/filebeat/input/awss3/s3_objects_test.go, x-pack/filebeat/input/awss3/s3_test.go, x-pack/filebeat/input/awss3/sqs_input.go
=> x-pack/filebeat/input/awss3: allow cross-region bucket configuration

CHANGELOG.next.asciidoc, x-pack/osquerybeat/internal/distro/distro.go
Upgrade to osquery 5.12.1.
Picking up the latest osquery release.
=> Osquerybeat: Upgrade to osquery 5.12.1

CHANGELOG.next.asciidoc, x-pack/metricbeat/module/azure/azure.go, x-pack/metricbeat/module/azure/client.go, x-pack/metricbeat/module/azure/client_test.go, x-pack/metricbeat/module/azure/client_utils.go
Move the timespan logic into a dedicated `buildTimespan()` function with a test for each supported use case. 
Some Azure services have longer latency between service usage and metric availability. For example, the Storage Account capacity metrics (Blob capacity, etc.) have a PT1H time grain and become available after one hour. Service X also has PT1H metrics, however become available after a few minutes.
This PR restores the core of the [older timespan logic](https://github.com/elastic/beats/blob/d3facc808d2ba293a42b2ad3fc8e21b66c5f2a7f/x-pack/metricbeat/module/azure/client.go#L110-L116) the Azure Monitor metricset was using before the regression introduced by the PR https://github.com/elastic/beats/pull/36823. 
However, the `buildTimespan()` does not restore the `interval * (-2)` part …
=> Azure Monitor: fix metric timespan to restore Storage Account PT1H metrics

CHANGELOG-developer.next.asciidoc, x-pack/filebeat/input/websocket/input.go, x-pack/filebeat/input/websocket/input_test.go, x-pack/filebeat/input/websocket/websocket.go
This extracts the common logic between streaming inputs into a new interface type to allow addition of new streaming inputs.
---
No behaviour change.
- For #40264
=> x-pack/filebeat/input/websocket: refactor input for generalisation

CHANGELOG.next.asciidoc, x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/okta.go, x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/okta_test.go, x-pack/filebeat/input/entityanalytics/provider/okta/okta.go, x-pack/filebeat/input/entityanalytics/provider/okta/okta_test.go, x-pack/filebeat/input/entityanalytics/provider/okta/statestore_test.go
Wire logging into the internal package and log rate limit handling.
- For #40106
=> x-pack/filebeat/input/entityanalytics/provider/{,internal/}okta: improve debug logging

.github/dependabot.yml
Set up Dependabot to manage the AWS SDK version.
With the current reactive and manual process, our dependencies are often outdated. To release a bugfix to a dependency, we need to wait for the following stack release instead of merging it shortly after it's available from AWS.
See https://github.com/elastic/beats/issues/39492 to learn more.
- Relates #39492
=> Manage AWS SDK(s) version with Dependabot

CHANGELOG-developer.next.asciidoc, filebeat/docs/filebeat-options.asciidoc, x-pack/agentbeat/agentbeat.spec.yml, x-pack/filebeat/docs/inputs/input-streaming.asciidoc, x-pack/filebeat/input/default-inputs/inputs_other.go, x-pack/filebeat/input/streaming/cel.go, x-pack/filebeat/input/streaming/config.go, x-pack/filebeat/input/streaming/config_test.go, x-pack/filebeat/input/streaming/input.go, x-pack/filebeat/input/streaming/input_manager.go, x-pack/filebeat/input/streaming/input_test.go, x-pack/filebeat/input/streaming/metrics.go, x-pack/filebeat/input/streaming/redact.go, x-pack/filebeat/input/streaming/redact_test.go, x-pack/filebeat/input/streaming/websocket.go
See title.
---
This has been tested by injecting an `agentbeat` compiled with this version into a running 8.15 elastic-package stack and then running the proofpoint_on_demand integration, an integration that depends on the websocket input.
- For #40264
=> x-pack/filebeat/input/{websocket=>streaming}: rename package

CHANGELOG.next.asciidoc, x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/okta.go
```
x-pack/filebeat/i.../entitya.../.../okta: Avoid a negative request rate (#)
This is the minimal change necessary to fix the following problem.
Around the time of a rate limit reset, if current time is after the
reset time returned in response headers, the rate limiting code will
set a negative target rate, and if that's done at a time when no
request budget has accumulated, it will not recover and will wait
forever.
```
The issue linked below lists other fixes and improvements that could be made the the Okta entity analytics rate limiting code. This PR is a version that should go into the next release to relieve the impact if the other changes aren't ready yet.
- Relates #40106
=> x-pack/filebeat/i.../entitya.../.../okta: Avoid a negative request rate

CHANGELOG.next.asciidoc, libbeat/reader/syslog/message_test.go, libbeat/reader/syslog/parser/rfc5424.rl, libbeat/reader/syslog/rfc5424_gen.go, libbeat/reader/syslog/rfc5424_test.go
- Improved syslog RFC 5424 parser to handle escaped closing square brackets in structured data.
- Fix incorrect offset being passed to removeBytes function, which would not remove escaped characters from structured data values.
- Add tests which include escaped brackets in structured data.
N/A
Run unit tests in libbeat/reader/syslog
- Closes #40445
=> [syslog] Fix handling of escaped characters in structured data

.github/workflows/golangci-lint.yml, x-pack/auditbeat/auditbeat.reference.yml, x-pack/auditbeat/module/system/_meta/config.yml.tmpl, x-pack/auditbeat/module/system/package/config.go, x-pack/auditbeat/module/system/package/package.go, x-pack/auditbeat/module/system/package/package_linux_test.go, x-pack/auditbeat/module/system/package/package_test.go, x-pack/auditbeat/module/system/package/rpm_linux.go, x-pack/auditbeat/module/system/package/rpm_linux_test.go, x-pack/auditbeat/module/system/package/rpm_others.go, x-pack/auditbeat/seccomp_linux.go
This is an odd one. It turns out that the BDB backend used by older `rpm` installs is...really easy to corrupt, and also prone to a variety of crashes should you get too aggressive with spinning up multiple threads to access the RPM backend. The only way I've found to actually solve this in auditbeat is to use `setreuid()` to drop out of root before we make any librpm calls; this prevents librpm from touching any lock files or opening any database files in write mode, which means we can't corrupt the DB if auditbeat stops/crashes, and it also seems to reduce the odds of certain crashes originating from within the guts of librpm/libdb, as we can't perform any of the integrity checking/cleanup operations that we would if the database state files were writable. 
The resulting …
=> Move around librpm calls, add `setreuid()` safety net

libbeat/publisher/pipeline/controller.go, libbeat/publisher/pipeline/controller_test.go
A stray `:=` instead of `=` overwrote the intended queue metrics namespace. This PR fixes it and adds a test to make sure the correct namespace is used.
Fixes https://github.com/elastic/beats/issues/40477
=> [libbeat] Fix and test initialization of queue monitors

auditbeat/main.go, filebeat/main.go, heartbeat/main.go, metricbeat/main.go, packetbeat/main.go, winlogbeat/main.go, x-pack/agentbeat/main.go, x-pack/auditbeat/main.go, x-pack/dockerlogbeat/main.go, x-pack/filebeat/main.go, x-pack/functionbeat/main.go, x-pack/heartbeat/main.go, x-pack/metricbeat/main.go, x-pack/osquerybeat/main.go, x-pack/packetbeat/main.go, x-pack/winlogbeat/main.go
In order to handle timezones we import Go's own timezone database. This
import is done indirectly by libbeat/common/cfgtype. We trust that this
package will end up being required by the dependency chain of every beats
main binary.
To ensure that the binaries continue to handle timezones correctly even if the
indirect import is removed let's import time/tzdata explicitly in the main packages.
See discussion at https://github.com/elastic/beats/pull/40326.
- Relates #31329
=> beats: import time/tzdata explicitly in main

CHANGELOG.next.asciidoc, x-pack/elastic-agent/pkg/agent/application/paths/common.go, x-pack/elastic-agent/pkg/agent/application/upgrade/rollback.go, x-pack/elastic-agent/pkg/agent/application/upgrade/service.go, x-pack/elastic-agent/pkg/agent/application/upgrade/service_darwin.go, x-pack/elastic-agent/pkg/agent/application/upgrade/service_windows.go, x-pack/elastic-agent/pkg/agent/application/upgrade/upgrade.go
Adjust Elastic Agent 7.17 to launch upgrade watcher version.
This fixes the issue where upgrading from 7.17 to a 8.x+ version only runs the 7.17 watcher for the latest 8.x release. The latest watcher should be ran instead.
None
- Relates https://github.com/elastic/elastic-agent/issues/5259
=> Adjust Elastic Agent 7.17 to launch upgrade watcher version

CHANGELOG.next.asciidoc, x-pack/filebeat/input/entityanalytics/provider/azuread/azure.go
Previously, the configuration was eager, this caused a panic when the request trace logging option was turned on since it was started without a context.
Move the construction of components to when we have all the parts we need.
---
Tested locally by building at this commit and injecting the agentbeat into a running ep stack with [request trace logging enabled](https://github.com/elastic/integrations/pull/10765). Outputs this to the trace log:
```
{"log.level":"debug","@timestamp":"2024-08-12T08:19:42.840Z","message":"HTTP request","transaction.id":"B0PCS4IRTNL1E-1","url.original":"http://svc-entra_id:8080/v1.0/users/delta?%24select=accountEnabled%2CuserPrincipalName%2Cmail%2CdisplayName%2CgivenName%2Csurname%2CjobTitle%2CofficeLocation%2CmobilePhone%2CbusinessPhones","url.scheme":"http","u …
```
=> x-pack/filebeat/input/entityanalytics/provider/azuread: fix configuration ordering

.buildkite/x-pack/pipeline.xpack.agentbeat.yml, libbeat/tests/compose/wrapper.go, x-pack/agentbeat/magefile.go
Run Agentbeat integration tests on pull requests and on push to main and release branches.
Metricbeat tests are excluded because they require a separate mage target without `docker-compose up`.
Fixed a deprecated `--ansi` flag for docker-compose.
-
=> [CI] Agentbeat integration testing

x-pack/auditbeat/module/system/socket/guess/inetsock.go, x-pack/auditbeat/module/system/socket/guess/inetsock6.go, x-pack/auditbeat/module/system/socket/guess/inetsock_test.go, x-pack/auditbeat/module/system/socket/helper/probes.go
This is a little silly. We have a few kprobes in auditbeat that will attempt to create up to _256_ args to read the return value from the register of a kretprobe; according to the kernel docs, only 128 args are supported. On older kernel releases, it would silently cut off any args greater than 128 (meaning this code never really worked as intended), but sometime around kernel 6.9, the kernel will throw an oops: https://bugzilla.redhat.com/show_bug.cgi?id=2303876. On older kernels, this technically doesn't change anything, as the kernel would just throw out any arguments over 128.
This modifies the kprobe creation so we're not trying to read from over 128 args.
If you want to test this behavior, you'll need Fedora, Arch, or another edge distro. The link above has some C code to reproduce …
=> Don't create kprobes with more than 128 args in auditbeat's guess subsystem

x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
This PR is to update the documentation for max_number_of_messages to inform users to keep default 5 for this parameter and use the `Balanced` or `Optimized for Throughput` presets in the Performance tuning settings to tune your Elastic Agent performance.
This is a followup change after https://github.com/elastic/beats/pull/40231.
=> [aws] Update max_number_of_messages doc

CHANGELOG.next.asciidoc, x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/graph/graph.go
There was no check on the tracer log settings, so the max_size was not being checked for zero. This would result in 100MB log rotation trigger and zero-sized bodies. There is no validation logic to hook this into in the config for the fetcher, so calculate it immediately before use.
---
A [fix is already included](https://github.com/elastic/integrations/pull/10765/files#diff-89d98c7e7d890ac178bdf2944e1e443819b3cf2b2fa34a658badf6cb8ce51a08R5) in the prospective integration change that makes use of this feature.
-
=> x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/graph: set log max_size

CHANGELOG.next.asciidoc, filebeat/tests/integration/event_log_file_test.go, libbeat/outputs/elasticsearch/client.go, libbeat/outputs/elasticsearch/event_encoder.go
The Elasticsearch output, when faced with ingestion errors was logging the raw publisher.Event that had already been encoded, hence no event fields were present in the logs.
This commit fixes it by adding a String method to the encodedEvent type and using the encodedEvent in the logs instead of the publisher.Event.
Closes: https://github.com/elastic/beats/issues/40509
None, it fixes a bug.
Start Filebeat with the following configuration
```yaml
id: filestream-input-id
enabled: true
parsers:
- ndjson:
target: ""
overwrite_keys: true
expand_keys: true
add_error_key: true
ignore_decoding_error: false
paths:
- /tmp/flog.log
output:
elasticsearch:
hosts:
- localhost:9200
protocol: https
username: elastic
password: changeme …
```
=> [ES output] Correctly log event fields in events log file

.golangci.yml
This disables the prealloc linter. Having prealloc enabled on CI leads to false positives which cause build failures, and those are often addressed in ways that are worse for the codebase. For example, allocating an empty slice like `make([]string, 0)` resolves the linter finding but goes against best practices.
It can also be seen as a form of premature optimization, where you are making changes in the name of performance before you have done the performance profiling.
If you still want to check your code locally, you can use `--enable=prealloc` when running golangci-lint.
References
https://go.dev/wiki/CodeReviewComments#declaring-empty-slices
https://golangci-lint.run/usage/linters/#prealloc
=> golangci-lint - disable prealloc linter

x-pack/filebeat/input/azureeventhub/v2_input.go
Minor changes for logging:
- Always use `partition_id` for consistency.
- Log 'no events received' (at debug level) when a consumer receives no events from its partition.
It also fixes other minor issues:
- Create one eventHubMetadata for each event to avoid eventHubMetadata values from previous events leaking into the current one (for example, partition_key).  
No disruptive User Impact is expected.
=> azure-eventhub v2: update logging for consistency (and other minor fixes)

NOTICE.txt, go.mod, x-pack/filebeat/include/list.go, x-pack/filebeat/input/azureeventhub/tracer.go
Add a tracer for the github.com/devigned/tab package to route logs from the legacy event hub SDK to the logp package.
The legacy event hub SDK uses the [github.com/devigned/tab](http://github.com/devigned/tab) package to handle traces and logs.
However, this package is old and seems unmaintained (last commit: 3 years ago). Since it only supports OpenTracing or OpenCensus, in Beats, the library defaults to a `NoOpTracer`, so we don’t see anything happening inside the legacy processor.
I don't expect the trace to impact users or other Beats components. It seems the legacy event hub SDK is the only dependency using this old package:
```shell
$ go mod why -m github.com/devigned/tab
github.com/elastic/beats/v7/x-pack/filebeat/input/azureeventhub
github.com/Azure/azure-event-hubs-go/v3 …
```
=> Add a tracer to send (legacy) Azure Event Hub SDK logs to logp

CHANGELOG-developer.next.asciidoc, filebeat/docs/inputs/input-common-tcp-options.asciidoc, filebeat/docs/inputs/input-common-udp-options.asciidoc, filebeat/inputsource/tcp/config.go, filebeat/inputsource/tcp/config_test.go, filebeat/inputsource/tcp/server.go, filebeat/inputsource/tcp/server_test.go, filebeat/inputsource/udp/config.go, filebeat/inputsource/udp/config_test.go, filebeat/inputsource/udp/server.go, filebeat/inputsource/udp/server_test.go
Add a configuration option for TCP/UDP network type.
Description below is copied from the ticket https://github.com/elastic/beats/issues/40407:
The TCP input would accept these values for the network type:
- `tcp` (default)
- `tcp4`
- `tcp6`
The UDP input would accept these values for the network type:
- `udp` (default)
- `udp4`
- `udp6`
```
- type: tcp
max_message_size: 10MiB
host: "localhost:9000"
network: tcp4
```
```
- type: udp
max_message_size: 10KiB
host: "localhost:8080"
network: udp4
```
- Closes https://github.com/elastic/beats/issues/40407
=> [filebeat] Add a configuration option for TCP/UDP network type

CHANGELOG.next.asciidoc, NOTICE.txt, go.mod, go.sum
See https://github.com/elastic/beats/pull/40507 for a bit more context.
We need to update elastic-agent-system-metrics to fix a logging bug: https://github.com/elastic/elastic-agent-system-metrics/commit/9db0a02d3b85559866acb97d427d18fa8b6d1930
However, the elastic-agent-system metrics repo has gone through so many breaking changes that we can't just cut a new release from main and update the dependency in 8.15. Instead, this updates the dependency to point at a special branch of `elastic_agent_system_metrics`: https://github.com/elastic/elastic-agent-system-metrics/tree/backport_8.15
If anyone can think of a less horrible way to do this, please tell me.
=> Update elastic-agent-system-metrics to point to our special backport for 8.15

CHANGELOG.asciidoc
Manual forward-port of #40631 to main
This just makes sure the change will appear in the 8.15 Release Notes for later docs versions (8.16, ...).
=> [Backport] [main] [40631] [RELEASE NOTES] Known issue azure-eventhub in Windows / 8.15

.buildkite/auditbeat/auditbeat-pipeline.yml, .buildkite/deploy/kubernetes/deploy-k8s-pipeline.yml, .buildkite/filebeat/filebeat-pipeline.yml, .buildkite/heartbeat/heartbeat-pipeline.yml, .buildkite/libbeat/pipeline.libbeat.yml, .buildkite/metricbeat/pipeline.yml, .buildkite/packetbeat/pipeline.packetbeat.yml, .buildkite/winlogbeat/pipeline.winlogbeat.yml, .buildkite/x-pack/pipeline.xpack.auditbeat.yml, .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml, .buildkite/x-pack/pipeline.xpack.filebeat.yml, .buildkite/x-pack/pipeline.xpack.heartbeat.yml, .buildkite/x-pack/pipeline.xpack.libbeat.yml, .buildkite/x-pack/pipeline.xpack.metricbeat.yml, .buildkite/x-pack/pipeline.xpack.osquerybeat.yml, .buildkite/x-pack/pipeline.xpack.packetbeat.yml, .buildkite/x-pack/pipeline.xpack.winlogbeat.yml
This commit reduces the amount of Buildkite retries in CI from 3 to 1 on all non macOS workers.
The rationale is that at the beginning of the CI migration, we faced a lot of CI failures either due to environmental issues (e.g. downloads from the internet timing out) or flaky tests, and in order to reduce the amount of noise set up to three retries per failure.
Since then, many flaky tests have been fixed (e.g.: elastic/beats#40237) and completed custom image coverage on Linux + Windows including predownloaded artifacts that minimize network/transient failures. Therefore most often failures are due to genuine problems with code and having so many retries slows down the feedback loop e.g. in PRs.
Closes https://github.com/elastic/ingest-dev/issues/3690
=> [CI] Set Buildkite retries to 1

filebeat/beater/filebeat.go, heartbeat/beater/heartbeat.go, libbeat/beat/beat.go, libbeat/cmd/instance/beat.go, libbeat/common/reload/reload.go, metricbeat/beater/metricbeat.go, packetbeat/beater/packetbeat.go, x-pack/osquerybeat/beater/osquerybeat.go, x-pack/osquerybeat/internal/config/watcher.go
Refactor libbeat/common/reload to not use a package level global variable.
`RegisterV2` is a package level global variable that would hold all
the inputs, outputs and modules for a Beat.  The problem with this
approach is that you can't have more than one Beat in the same process
because the configurations would overwrite each other.  Moving the
registry to a variable in the Beat struct allows each Beat to have
it's own registry.
~~- [ ] I have added an entry in `CHANGELOG.next.asciidoc` …
=> refactor libbeat/common/reload to not use global variable

x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
Improves filebeat S3 -> SQS documentation by adding a detailed guide backed by a CloudFormation template.
Fixes #40624
=> [Docs] add cloudformation backed guide for s3-sqs setup for filebeats

.buildkite/auditbeat/auditbeat-pipeline.yml, .buildkite/deploy/kubernetes/deploy-k8s-pipeline.yml, .buildkite/filebeat/filebeat-pipeline.yml, .buildkite/heartbeat/heartbeat-pipeline.yml, .buildkite/libbeat/pipeline.libbeat.yml, .buildkite/metricbeat/pipeline.yml, .buildkite/packetbeat/pipeline.packetbeat.yml, .buildkite/winlogbeat/pipeline.winlogbeat.yml, .buildkite/x-pack/pipeline.xpack.auditbeat.yml, .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml, .buildkite/x-pack/pipeline.xpack.filebeat.yml, .buildkite/x-pack/pipeline.xpack.heartbeat.yml, .buildkite/x-pack/pipeline.xpack.libbeat.yml, .buildkite/x-pack/pipeline.xpack.metricbeat.yml, .buildkite/x-pack/pipeline.xpack.osquerybeat.yml, .buildkite/x-pack/pipeline.xpack.packetbeat.yml, .buildkite/x-pack/pipeline.xpack.winlogbeat.yml
This commit reduces the amount of Buildkite retries in CI from 3 to 1 on all non macOS workers.
The rationale is that at the beginning of the CI migration, we faced a lot of CI failures either due to environmental issues (e.g. downloads from the internet timing out) or flaky tests, and in order to reduce the amount of noise set up to three retries per failure.
Since then, many flaky tests have been fixed (e.g.: elastic/beats#40237) and completed custom image coverage on Linux + Windows including predownloaded artifacts that minimize network/transient failures. Therefore most often failures are due to genuine problems with code and having so many retries slows down the feedback loop e.g. in PRs.
Closes https://github.com/elastic/ingest-dev/issues/3690
<hr>This is an automatic backport of …
=> [7.17](backport #40440) [CI] Set Buildkite retries to 1 #40649

filebeat/input/journald/pkg/journalfield/conv_expand_test.go, filebeat/input/journald/pkg/journalfield/conv_test.go, filebeat/input/journald/pkg/journalfield/default.go, filebeat/input/journald/pkg/journalfield/matcher_test.go
See title
None
Build Filebeat by running: `GOOS=linux GOARCH=arm64 go build`
~~## Logs~~
=> Fix build tags in journald input

CHANGELOG.next.asciidoc, x-pack/filebeat/input/entityanalytics/provider/okta/okta.go
While working on elastic/integrations#10973 I found that the group data was not being published. This was due to the field not being part of the user, and not being inserted into the events fields map. This fixes that omission.
- Ref elastic/integrations#10096
=> x-pack/filebeat/input/entityanalytics/provider/okta: fix publication of groups

x-pack/elastic-agent/pkg/artifact/download/snapshot/downloader.go, x-pack/elastic-agent/pkg/artifact/download/snapshot/downloader_test.go
Add http response validation and dumpt the response in case of error when handling artifact URI response.
This should allow for easier investigation and debugging in case of wrong responses from `artifacts-api.elastic.co`
- Relates https://github.com/elastic/elastic-agent/issues/5047
=> Dump artifact uri response body when fail decoding

dev-tools/packaging/templates/docker/Dockerfile.tmpl
Adding required dependencies to run Synthetics to Wolfi-based heartbeat images, from wolfi-os package manager.
- Build heartbeat wolfi image locally with:
```
DEV=true SNAPSHOT=true PLATFORMS=linux/amd64 PACKAGES=docker mage package
```
- Create the following monitor configuration:
```yaml
heartbeat.monitors:
- type: browser
id: korean-characters
name: korean_characters_test
schedule: '@every 1m'
source:
inline:
script: |-
step("first", async () => {
await page.goto('https://www.naver.com/');
});
- type: browser
id: chinese-characters
name: chinese_characters_test
schedule: '@every 1m'
source:
inline:
script: |-
step("first", async () => {
await page.goto('https://baike.baidu.com/');
});
- type: browser …
```
=> [Heartbeat] Add Synthetics to wolfi image

libbeat/cfgfile/cfgfile.go, libbeat/common/fleetmode/fleet_mode.go
refactor fleet mode detection and storage
Currently the fleet mode is only detected by looking at the command
line flags.  This refactor keeps that behavior but also adds the
ability to set the value based independently.  This is important if
you were to embed a Beat within elastic-agent and have it behave as
fleet managed.
There should be no user observed change.
- run `elastic-agent` test suite with agentbeat built from this patch.
- Relates #40110
=> refactor fleet mode detection and storage

CHANGELOG.next.asciidoc, x-pack/filebeat/input/cel/input.go
CEL programs used in the CEL input are specific to return an object that includes an array. This is tested for, but currently the check is indirect and only shows that the type is not expected, rather than a more informative message that the events array is missing. This changes that so that when no events field is present, an error is returned directly. This will flow on to a status update in the handling of the returned error by the input Run method, alerting the user more promptly to the cause. Since a CEL input program is not valid if it returns no events field, a hard error (fleet status failed rather than degraded) seems appropriate.
-
=> x-pack/filebeat/input/cel: improve missing events error value

winlogbeat/eventlog/wineventlog.go, winlogbeat/eventlog/wineventlog_experimental.go
Add check on winlog metrics to prevent panic.
Metrics initialization was deferred to avoid registering them on `CheckConfig` calls. Now that is inside `Open` we need to check to avoid panicking when retrying on recoverable errors.
No changelog entry since the change that introduced this is still not released.
=> [winlogbeat] Only init metrics if needed

dev-tools/packaging/package_test.go, dev-tools/packaging/packages.yml, dev-tools/packaging/templates/docker/Dockerfile.tmpl
* New images with `-wolfi` suffix get created
* Wolfi is used for preparing the file structure for Docker images
Script I use to build all the images:
```sh
#!/bin/bash
set -e
docker rmi -f $(docker images -a -q) || true
BEATS="auditbeat filebeat functionbeat heartbeat metricbeat packetbeat winlogbeat osquerybeat"
ROOT=$PWD
start_date=$(date)
for beat in $BEATS
do
path="$ROOT/$beat"
cd $path || echo "$path not found"
mage clean
(PLATFORMS=linux/arm64 PACKAGES=docker mage package) || (echo "failed to buid Docker image in $path" && exit 1)
path="$ROOT/x-pack/$beat"
cd $path || (echo "$path not found" && continue)
mage clean
(PLATFORMS=linux/arm64 PACKAGES=docker mage package) || (echo "failed to buid Docker image in $path" && exit 1)
done
cd $ROOT
end_date=$(date)
echo "started at …
```
=> Make Wolfi a part of Docker packaging

.mergify.yml
When the `main` branch switches over to `9.0`, we will want most PRs that are merged into `main` to also be backported to `8.x`. This PR makes this process easier by automatically adding the `backport-8.x` label to all PRs targeting the `main` branch.
The exceptions will be PRs for changes that should _only_ be present in `9.0`.  For such PRs, authors should simply remove the `backport-8.x` label from their PR.
=> Automatically label PRs to `main` with `backport-v8.x`

.buildkite/x-pack/pipeline.xpack.heartbeat.yml
Adjust heartbeat pipeline matrix for Windows, to correctly scope unit tests.
- Fixes https://github.com/elastic/beats/pull/40583.
=> [Heartbeat] Adjust Windows test pipeline

CHANGELOG.next.asciidoc, x-pack/filebeat/input/netflow/input.go, x-pack/filebeat/input/netflow/input_test.go
- Fix custom fields not being applied when provided through configuration
Run unit tests for netlow
- Closes #40735
=> [netflow] Ensure custom fields configuration is applied

CHANGELOG.asciidoc
See https://github.com/elastic/beats/issues/40705
- Relates https://github.com/elastic/ingest-docs/pull/1312
=> Add known issue that Beats do not recover from transient network errors 

dev-tools/packaging/templates/docker/Dockerfile.tmpl
The old way of specifying maintainers in a Dockerfile was to use the MAINTAINER instruction. This is now deprecated and the maintainer label was used instead.
Nowadays the recommended way to set a maintainer is through the `org.opencontainers.image.authors` label.
See https://docs.docker.com/reference/build-checks/maintainer-deprecated/.
- I wonder if we look for a maintainer label in the images somewhere, if that is the case this can be a breaking change.
=> Change maintainer label to opencontainers in Dockerfile

libbeat/processors/ratelimit/limit.go
The bitSize argument in strconv.ParseFloat should be either 32 or 64. 
Any value other than 32 will default to 64 in the current implementation, 
though this behavior is undocumented, making it undefined.
See https://cs.opensource.google/go/go/+/refs/tags/go1.23.0:src/strconv/atof.go;l=704-708.
=> fix invalid bitSize in strconv.ParseFloat

libbeat/esleg/eslegclient/connection.go
This commit removes a call to conn.cancelReqs() that causes the Connection to be unusable after Close() is called, leading to the bug described by https://github.com/elastic/beats/issues/40705.
-
=> Do not cancel context on Connection.Close

CHANGELOG.next.asciidoc, libbeat/processors/actions/replace.go, libbeat/processors/actions/replace_test.go
The change in #40047 breaks the use of the replace processor to do `s/<pattern>//` replacement. So make the validation on absence, not zero state.
-
=> libbeat/processors/replace: fix zero string replacement validation

CHANGELOG.next.asciidoc
=> changelog: add missing pr number

testing/environments/Dockerfile, testing/environments/local.yml, testing/environments/snapshot.yml
I stumbled upon some warnings when trying to start the integration testing environment. The logs don't cause any harm but they pollute the output of the tool. Warnings include:
```
WARN[0000] /home/mauri870/git/elastic/beats/testing/environments/snapshot.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avo
id potential confusion
WARN[0000] /home/mauri870/git/elastic/beats/testing/environments/local.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid
potential confusion
WARN: MaintainerDeprecated: Maintainer instruction is deprecated in favor of using label (line 4)
```
- `cd testing/environments; make start ENV=snapshot.yml`
=> testing: Fix Docker deprecation warnings

CHANGELOG-developer.next.asciidoc, CHANGELOG.next.asciidoc, x-pack/filebeat/input/awss3/metrics.go, x-pack/filebeat/input/awss3/s3_objects.go
Fixes #40306 by adding `s3_events_per_object` & `s3_object_size_in_bytes` histograms. These histograms provide valuable insights on the size of S3 objects filebeat processed and the number of events produced by each S3 object. 
Consider below screenshot,
- Uploads two documents with 15 total logs (10 logs in one and another with 5 logs)
- See how `s3_events_per_object` tracks events (logs) per object with max, min and count
- See how `s3_object_size_in_bytes` tracks object size with max and min and count 
- Run filebeat with AWS S3 connectivity
- Access debug metrics through http://<http.host>:<http.port>/inputs/?type=aws-s3
- Observe `s3_object_size_in_bytes` & `s3_events_per_object` histograms
- Closes #40306
=> chore: add debug histograms for s3 object size and events per processed s3 object

libbeat/outputs/util.go, libbeat/outputs/util_test.go
See title
No disruption as the disk queue was already unsupported when running under agent
Package agent using beats binaries that include this change.
Install agent as standalone and modify the `output` in `elastic-agent.yml`
```yaml
outputs:
default:
type: elasticsearch
hosts: [127.0.0.1:9200]
api_key: "example-key"
#username: "elastic"
#password: "changeme"
#preset: balanced
queue.disk: …
```
=> Expose output disk queue settings when running under agent

dev-tools/packaging/package_test.go, dev-tools/packaging/packages.yml
For example, `filebeat-wolfi-oss` -> `filebeat-oss-wolfi`
```sh
PLATFORMS=linux/arm64 PACKAGES=docker mage package
```
for each Beat yields the following results:
```
REPOSITORY                                      TAG          IMAGE ID       CREATED          SIZE
docker.elastic.co/beats-dev/golang-crossbuild   1.22.6-arm   eae46a040730   2 weeks ago      752MB
docker.elastic.co/beats/auditbeat               9.0.0        70d947064a71   41 minutes ago   254MB
docker.elastic.co/beats/auditbeat-oss           9.0.0        cfa91ec283eb   43 minutes ago   243MB
docker.elastic.co/beats/auditbeat-oss-wolfi     9.0.0        ef92ba55d6e2   42 minutes ago   163MB
docker.elastic.co/beats/auditbeat-ubi           9.0.0        dbf6f1705960   41 minutes ago   249MB
docker.elastic.co/beats/auditbeat-wolfi …
```
=> Rename Wolfi images to satisfy the release naming convention

x-pack/metricbeat/module/panw/interfaces/ha_interfaces.go, x-pack/metricbeat/module/panw/interfaces/ifnet_interfaces.go, x-pack/metricbeat/module/panw/interfaces/tunnels.go, x-pack/metricbeat/module/panw/routing/bgp_peers.go, x-pack/metricbeat/module/panw/system/certificates.go, x-pack/metricbeat/module/panw/system/fans.go, x-pack/metricbeat/module/panw/system/filesystem.go, x-pack/metricbeat/module/panw/system/license.go, x-pack/metricbeat/module/panw/system/power.go, x-pack/metricbeat/module/panw/system/resources.go, x-pack/metricbeat/module/panw/system/thermal.go, x-pack/metricbeat/module/panw/vpn/gp_sessions.go, x-pack/metricbeat/module/panw/vpn/gp_stats.go
In the existing code, we create a mapstr.M containing attributes to set in the `RootFields` of metric events, which is reused several times in a loop. In the publisher code, the root fields are modified, e.g. https://github.com/elastic/beats/blob/main/metricbeat/mb/event.go#L79, which causes a panic due to `fatal error: concurrent map iteration and map write`, as the same mapstr.M object is still being used in later iterations of the loop.
-
=> [metricbeat][panw] fix concurrent map write error caused by reusing a mapstr.M

x-pack/metricbeat/module/panw/interfaces/ha_interfaces.go, x-pack/metricbeat/module/panw/interfaces/ifnet_interfaces.go, x-pack/metricbeat/module/panw/interfaces/tunnels.go, x-pack/metricbeat/module/panw/routing/bgp_peers.go, x-pack/metricbeat/module/panw/system/certificates.go, x-pack/metricbeat/module/panw/system/fans.go, x-pack/metricbeat/module/panw/system/filesystem.go, x-pack/metricbeat/module/panw/system/license.go, x-pack/metricbeat/module/panw/system/power.go, x-pack/metricbeat/module/panw/system/resources.go, x-pack/metricbeat/module/panw/system/thermal.go, x-pack/metricbeat/module/panw/vpn/gp_sessions.go, x-pack/metricbeat/module/panw/vpn/gp_stats.go
In the existing code, we create a mapstr.M containing attributes to set in the RootFields of metric events, which is reused several times in a loop. In the publisher code, the root fields are modified, e.g. https://github.com/elastic/beats/blob/main/metricbeat/mb/event.go#L79, which causes a panic due to fatal error: concurrent map iteration and map write, as the same mapstr.M object is still being used in later iterations of the loop.
-
=> fix concurrent map write error caused by reusing a mapstr.M

NOTICE.txt, go.mod, go.sum
Main is already at v1.66.0: https://github.com/elastic/beats/blob/bfed1784c368b5101d107534a4d7698e134e1e2f/go.mod#L154
Addresses https://github.com/advisories/GHSA-xr7q-jx4m-x55m, which does not affect us because we do not log gRPC metadata.
=> [8.15] Upgrade gRPC to v1.64.1

CHANGELOG.next.asciidoc, filebeat/input/v2/compat/compat.go, filebeat/input/v2/input-cursor/input.go, filebeat/input/v2/input.go, x-pack/filebeat/input/cel/input.go, x-pack/filebeat/input/cel/input_test.go, x-pack/filebeat/input/entityanalytics/provider/jamf/jamf.go, x-pack/filebeat/input/entityanalytics/provider/okta/okta.go, x-pack/filebeat/input/http_endpoint/input.go, x-pack/filebeat/input/httpjson/input.go, x-pack/filebeat/input/httpjson/input_test.go
Fix long filepaths in diagnostics exceeding max path limits on Windows.
Following the first proposal here
https://github.com/elastic/elastic-agent/issues/3758#issuecomment-1830229924
Added ```IDWithoutName``` that doesn't include the source name and using that instead.
- Closes https://github.com/elastic/elastic-agent/issues/3758
The screenshot that shows the diagnostics collected before and after this change. The earlier diagnostics shows the long path that includes the sanitized okta log collection URL. The diagnostics after this change have shorter path that doesn't include the sanitized URL in the path.
=> [filebeat] Fix long filepaths in diagnostics exceeding max path limits on Windows

CHANGELOG-developer.next.asciidoc, x-pack/metricbeat/module/aws/billing/billing.go, x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go, x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go, x-pack/metricbeat/module/aws/utils.go, x-pack/metricbeat/module/aws/utils_test.go
This PR is to record the previous endTime from the previous collection period to use for calculating the next collection start time and end time.
With using the previous endTime as the new startTime, we will not skip time range in collection.
This PR also changes log.logger from `cloudwatch` to `aws.cloudwatch` to match the other logger.
N/A. User will see no gap in collection startTime and endTime, should be an enhancement.
1. Pull this PR and run mage build to build Metricbeat locally.
2. `./metricbeat modules enable aws`
3. Configure in `aws.yml`:
```
- module: aws
period: 5m
metricsets:
- cloudwatch
include_linked_accounts: true
metrics:
- namespace: AWS/RDS
```
4. Run metricbeat with debug log on
5. Check metricbeat log to make sure startTime and endTime are connected for all …
=> [AWS CloudWatch Metrics] Record previous endTime to use for next collection period

CHANGELOG.next.asciidoc, x-pack/filebeat/input/cel/config.go, x-pack/filebeat/input/cel/input.go
HTTP functions were previously conditional on the resource URL being an HTTP/HTTPS URL. In hindsight, this offers no benefits and can result in confusing errors when the end user enters an invalid URL for an HTTP-based integration. Instead of a URL-related or HTTP-related error, the user is given a compilation error indicating that the HTTP-related function that are being called (and they may not be aware of in any way) are not valid references. So let's just always make them available.
-
=> x-pack/filebeat/input/cel: make http functions always available

CHANGELOG.next.asciidoc, metricbeat/docs/modules/gcp.asciidoc, x-pack/metricbeat/metricbeat.reference.yml, x-pack/metricbeat/module/gcp/_meta/config.yml, x-pack/metricbeat/module/gcp/_meta/docs.asciidoc, x-pack/metricbeat/module/gcp/metrics/metricset.go, x-pack/metricbeat/modules.d/gcp.yml.disabled
The GCP metric client does not currently allow overriding with a custom endpoint, which is necessary for testing against a mock GCP API endpoint. 
Resolved this issue by implementing a check to determine if an endpoint is specified in the GCP configuration, and subsequently overriding the `ClientOption` with that endpoint.
- Closes #40848
=> x-pack/metricbeat/module/gcp:  Override GCP API endpoint in metric client

README.md
Cleaning up some references to the beats-ci Jenkins in the README.
Relates: https://github.com/elastic/ingest-dev/issues/3477
=> Update beats-ci references in README

.github/CODEOWNERS, CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-streaming.asciidoc, x-pack/filebeat/input/streaming/config.go, x-pack/filebeat/input/streaming/crowdstrike.go, x-pack/filebeat/input/streaming/crowdstrike_test.go, x-pack/filebeat/input/streaming/input.go
=> x-pack/filebeat/input/streaming: add falcon hose stream follower

CHANGELOG.next.asciidoc, filebeat/input/v2/compat/compat.go, filebeat/input/v2/input-cursor/input.go, filebeat/input/v2/input.go, x-pack/filebeat/input/cel/input.go, x-pack/filebeat/input/cel/input_test.go, x-pack/filebeat/input/entityanalytics/provider/jamf/jamf.go, x-pack/filebeat/input/entityanalytics/provider/okta/okta.go, x-pack/filebeat/input/http_endpoint/input.go, x-pack/filebeat/input/httpjson/input.go, x-pack/filebeat/input/httpjson/input_test.go
Reverts elastic/beats#40923
@aleksmaus I am sorry I have to revert this but it introduced a problem with Elastic Agent where lock file on Windows remain and diagnostic are not being generated at all.
cc @ycombinator @cmacknz
=> Revert "[8.x](backport #40909) [filebeat] Fix long filepaths in diagnostics exceeding max path limits on Windows"

.github/CODEOWNERS
As part of the global teams renaming, it's required to change this team to be an @elastic/app-search-team.
@elastic/ingest-eng-prod , can you please add this team to the repo, so the CODEOWNERS is valid again?
=> Change codeowners from ent-search-application to app-search-team

CHANGELOG.next.asciidoc
Adds the changelog entry for https://github.com/elastic/beats/pull/40776 which was missed originally.
=> [8.15] Add missing changelog for connection recovery fix

CHANGELOG.next.asciidoc, filebeat/input/v2/compat/compat.go, filebeat/input/v2/input-cursor/input.go, filebeat/input/v2/input.go, x-pack/filebeat/input/cel/input.go, x-pack/filebeat/input/cel/input_test.go, x-pack/filebeat/input/entityanalytics/provider/jamf/jamf.go, x-pack/filebeat/input/entityanalytics/provider/okta/okta.go, x-pack/filebeat/input/http_endpoint/input.go, x-pack/filebeat/input/httpjson/input.go, x-pack/filebeat/input/httpjson/input_test.go
Reverts elastic/beats#40909
@aleksmaus I am sorry I have to revert this but it introduced a problem with Elastic Agent where lock file on Windows remain and diagnostic are not being generated at all.
cc @ycombinator @cmacknz
=> Revert "[filebeat] Fix long filepaths in diagnostics exceeding max path limits on Windows"

.buildkite/hooks/pre-command
Added Buildkite annotation, for scenarios when build is triggered by GH comment without code changes
- Relates: https://github.com/elastic/ingest-dev/issues/3041
Buildkite builds: https://buildkite.com/elastic/beats/builds?branch=oakrizan%3Aadd-triggering-reason
=> Add Buildkite trigger context annotation

CHANGELOG.next.asciidoc, filebeat/input/v2/compat/compat.go, filebeat/input/v2/input-cursor/input.go, filebeat/input/v2/input.go, x-pack/filebeat/input/cel/input.go, x-pack/filebeat/input/cel/input_test.go, x-pack/filebeat/input/entityanalytics/provider/jamf/jamf.go, x-pack/filebeat/input/entityanalytics/provider/okta/okta.go, x-pack/filebeat/input/http_endpoint/input.go, x-pack/filebeat/input/httpjson/input.go, x-pack/filebeat/input/httpjson/input_test.go
This PR reverts #40980, which was itself a PR reverting #40909, effectively restoring the changes made in #40909.  
The reason #40909 was reverted was that we were suspecting the changes in it were causing Elastic Agent CI builds to fail.  However, reverting #40909 (via #40980) did not have any effect on the Agent CI failures.
=> Revert "Revert "[filebeat] Fix long filepaths in diagnostics exceeding max path limits on Windows""

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc
The changelog for the 8.15.1 bug that causes data ingestion to stop when connections have a transient error was omitted from the 8.15.2 changelog. Add it back.
It was added in https://github.com/elastic/beats/commit/a09bd5160f191b725bd0ea46e3efc69c71b7c36a#diff-867eb8a32d99eda9bb244b7b86d7abd0031618bae71d0276fe139fe697c3063dR71 but we didn't merge 8.15 into https://github.com/elastic/beats/pull/40982 before merging it to pick it up.
=> Add missing changelog for ES fix.

catalog-info.yaml
I noticed that the beats-packaging-pipeline wasn't triggering automatically on the 8.x branch. Looks like adjusting this regex should fix that.
=> Adjust beats-packaging-pipeline to trigger on 8.x

.golangci.yml
This PR (re)enables the `errcheck.check-type-assertions` linter, in light of https://github.com/elastic/beats/pull/41009
=> Enable type assertion checks

libbeat/outputs/fileout/config.go, libbeat/outputs/fileout/config_test.go, libbeat/outputs/fileout/pathformatstring.go, libbeat/outputs/fileout/pathformatstring_test.go
Fixes a small bug where if the `output.file` config is enabled but doesn't have a correctly set `path` setting, the `pathFormatString.Run()` method will be null, and explode. This sets the default config to have a non-null path format string, and also checks to make sure `EventFormatString` is non-null.
=> Fix nil pointer deref if the file output lacks a `path` setting.

filebeat/input/tcp/input.go, filebeat/input/udp/input.go, filebeat/input/unix/input.go, filebeat/inputsource/common/streaming/listener.go
Addressing the issue [filebeat: improve debug logging in udp/tcp inputs](https://github.com/elastic/beats/issues/34060)
- Closes https://github.com/elastic/beats/issues/34060
Examples of added logs:
```
{"log.level":"debug","@timestamp":"2024-09-30T20:41:02.152-0400","log.logger":"input.tcp","log.origin":{"function":"github.com/elastic/beats/v7/filebeat/input/tcp.(*server).Run.func1","file.name":"tcp/input.go","file.line":112},"message":"Data received","service.name":"filebeat","id":"FEAD914EAB357583","host":"localhost:32001","bytes":7,"remote_address":"127.0.0.1:52756","truncated":false,"ecs.version":"1.6.0"}
```
```
{"log.level":"debug","@timestamp":"2024-09-30T20:42:39.869-0400","log.logger":"input.udp","log.origin":{"function":"github.com/elastic/beats/v7/filebeat/input/udp.(*server).R …
```
=> [filebeat]: improve debug logging in udp/tcp inputs

.golangci.yml
This change introduces linting for the `replace` directive in `go.mod`.  It forbids local replacements (generally used as temporary measures during development) and it adds an allowlist for permanent replacements to restrict the dependencies that may be replaced.
Related: https://github.com/elastic/beats/issues/41084 and https://github.com/elastic/beats/issues/41085
=> Add linting for the `replace` directive in `go.mod`

CHANGELOG.next.asciidoc, packetbeat/module/pipeline.go
Detection of data stream identity was using os.PathSeparator which will not match the path separator used by embed.FS which is always "/"[1].
[1]https://pkg.go.dev/embed#hdr-Directives
-
=> packetbeat/module: fix upload of bundled ingest pipelines on Windows

CHANGELOG.next.asciidoc, heartbeat/monitors/monitor.go, heartbeat/monitors/monitor_test.go
Add status reporting for monitors when running under elastic-agent, this will allow the Fleet UI to reflect theres an issue with one or more heartbeat integrations.
1. Build agentbeat locally with:
```sh
DEV=true SNAPSHOT=true  PLATFORMS=linux/amd64 mage package
```
2. Build elastic-agent locally with:
```sh
DEV=true SNAPSHOT=true PLATFORMS=linux/amd64 PACKAGES=docker mage package
```
3. Enroll a non-complete elastic-agent into a private location policy with a browser monitor assigned.
4. Check agent status is eventually reported as degraded and the integration marked as failed.
=> [Heartbeat] Add managed status reporter at monitor factory level

CHANGELOG.next.asciidoc, x-pack/filebeat/input/internal/httplog/roundtripper.go
Add logging of structured fields for request and response headers and drop logging of request/response using httputil. We lose no significant information from dropping the request logging; in requests there will be an "Accept-Encoding: gzip" that we do not get in the headers, but this is always present in all requests from beats clients. The benefit of including headers as structured data is that we gain the ability to more easily search logs for header values.
-
=> x-pack/filebeat/input/internal/httplog: log headers instead of request/response

libbeat/docs/howto/load-index-templates.asciidoc, libbeat/docs/shared-docker.asciidoc, libbeat/docs/tab-widgets/load-dashboards-logstash.asciidoc, libbeat/docs/tab-widgets/load-dashboards.asciidoc, libbeat/docs/tab-widgets/load-index-template.asciidoc
Add --rm to the setup command to automatically remove the container used to setup. This prevents leaving behind a single-use container instance.
No, docs only
=> Docs: update Docker setup commands to remove container when done

libbeat/docs/shared-docker.asciidoc
@blakerouse, Bill noticed a couple of issues with the [Run (beat) on a read-only file system](https://www.elastic.co/guide/en/beats/filebeat/current/running-on-docker.html#_run_filebeat_on_a_read_only_file_system) instructions:
---
```
docker run \
--mount type=source=$(pwd}/data,destination=/usr/share/{beatname_lc}/data
--read-only
{dockerimage}
```
I believe:
- the `$(pwd}` should be `$(pwd)`
- the type is missing should be something like `type=....,source=`
---
This PR fixes up the first issue, but can you please help with the second? I'm not sure what the change should be, if any. I just copied that command from your comment [here](https://github.com/elastic/beats/pull/40092#discussion_r1669388125).
=> Fix read-only instructions for running Beats on Docker

libbeat/cfgfile/cfgfile.go, libbeat/common/fleetmode/fleet_mode.go
Reverts elastic/beats#40667
Due to:
https://github.com/elastic/apm-server/issues/14280
and
https://github.com/elastic/apm-server/pull/14214
basically APM server is relying exactly on how Beats does argument parsing today and when the arguments are set in their final form.
=> Revert "refactor fleet mode detection and storage"

libbeat/cfgfile/cfgfile.go, libbeat/cmd/instance/beat_integration_test.go, libbeat/cmd/root.go
Reverts elastic/beats#40993
Due to https://github.com/elastic/apm-server/pull/14214 and https://github.com/elastic/apm-server/issues/14280
=> Revert "Don't register cfgfile flags on `flag.CommandLine` in `func init()`"

NOTICE.txt, go.mod, go.sum
This PR updates elastic-agent-libs to the latest version in order to fix https://github.com/elastic/beats/issues/41118.
```
cd filebeat
mage build
timeout 3 filebeat --environment docker
```
- Relates to https://github.com/elastic/beats/issues/41118
=> fix: restore stderr logs when running on docker or systemd environments

libbeat/processors/add_docker_metadata/add_docker_metadata.go, libbeat/processors/add_docker_metadata/add_docker_metadata_test.go, libbeat/processors/add_process_metadata/add_process_metadata.go, libbeat/processors/add_process_metadata/add_process_metadata_test.go, libbeat/processors/add_process_metadata/gosigar_cid_provider.go
Turns out that we don't have any tests that actually check to see if the default cgroups callback actually initializes properly, so https://github.com/elastic/beats/pull/41108 broke the processors on non-linux systems.
This re-adds support for systems that don't have cgroups support, and also adds tests that makes sure the processors can startup and run with the default cgroups provider.
=> Add tests, fallback properly if we can't init the cgroups

CHANGELOG.next.asciidoc, NOTICE.txt, go.mod, go.sum
See https://github.com/elastic/go-sfdc/pull/3 for more details on why dependency was bumped to `master@8e176480d727`
Run filebeat module and use JWT authentication to validate if connection to Salesforce is successful or not.
- Relates https://github.com/elastic/go-sfdc/pull/3
=> Bump `github.com/elastic/go-sfdc` to `master@8e176480d727`

libbeat/processors/add_docker_metadata/add_docker_metadata.go, libbeat/processors/add_process_metadata/add_process_metadata.go, libbeat/processors/add_process_metadata/add_process_metadata_test.go, libbeat/processors/add_process_metadata/gosigar_cid_provider.go, libbeat/processors/cgroups.go
Continuation of https://github.com/elastic/beats/pull/41189 . This adds a `NilCGReader` type that makes us a little less likely to hit a nil pointer deref if this code is changed in the future, and also cleans up some of the error handling.
=> Create nil cgroups reader for processor, improve error handling

.github/CODEOWNERS, CHANGELOG-developer.next.asciidoc, x-pack/filebeat/input/internal/private/private.go, x-pack/filebeat/input/internal/private/private_test.go
Initial donation of code from github.com/kortschak/dex/internal/private.
-
```diff
diff --git a/x-pack/filebeat/input/httpjson/input.go b/x-pack/filebeat/input/httpjson/input.go
index 67daa7ef84..41b46c1878 100644
--- a/x-pack/filebeat/input/httpjson/input.go
+++ b/x-pack/filebeat/input/httpjson/input.go
@@ -33,6 +33,7 @@ import (
"github.com/elastic/beats/v7/libbeat/version"
"github.com/elastic/beats/v7/x-pack/filebeat/input/internal/httplog"
"github.com/elastic/beats/v7/x-pack/filebeat/input/internal/httpmon"
+       "github.com/elastic/beats/v7/x-pack/filebeat/input/internal/private"
"github.com/elastic/elastic-agent-libs/logp"
"github.com/elastic/elastic-agent-libs/mapstr"
"github.com/elastic/elastic-agent-libs/monitoring"
@@ -82,6 +83,19 @@ func (log *retryLogger) Warn(msg string, …
```
=> x-pack/filebeat/input/internal/private: add field redaction package

CHANGELOG.next.asciidoc, NOTICE.txt, go.mod, go.sum, libbeat/autodiscover/providers/kubernetes/pod.go, libbeat/autodiscover/providers/kubernetes/pod_test.go, libbeat/processors/add_kubernetes_metadata/kubernetes.go
Use metadata watchers for ReplicaSets in components that need them. The only data we need from ReplicaSets are their name and OwnerReferences, which are used to connect Pods to Deployments and DaemonSets.
This PR makes the change in:
* autodiscovery
* the `add_kubernetes_metadata` processor
For more details see https://github.com/elastic/elastic-agent/issues/5623.
You need a full K8s cluster, unfortunately. I've tested it using the default elastic-agent standalone manifest, by building a custom container image and loading it into a local kind cluster.
- Relates https://github.com/elastic/elastic-agent/issues/5623
=> Only watch metadata for ReplicaSets in K8s

filebeat/input/filestream/fswatch_test.go, filebeat/input/filestream/internal/task/group_test.go
This PR skips two flaky tests from the Filestream input, the tests are:
- TestFileWatcher (issue: https://github.com/elastic/beats/issues/41209)
- TestGroup_Go (issue: https://github.com/elastic/beats/issues/41218)
- Relates https://github.com/elastic/beats/issues/41209
- Relates https://github.com/elastic/beats/issues/41218
~~## Logs~~
=> Skip flaky tests TestFileWatcher and TestGroup_Go

dev-tools/packaging/templates/docker/Dockerfile.tmpl
"Recently" the user in the dockerfile was adjusted to be `1000` instead of `metricbeat`: https://github.com/elastic/beats/pull/35272/files#r1184217000
I believe this was recently changed [here](https://github.com/elastic/beats/pull/40524)
See https://github.com/elastic/cloud-on-k8s/pull/8086#issuecomment-2401624589
This is causing issues when running the container as `runAsNonRoot: true`:
```
container has runAsNonRoot and image has non-numeric user (metricbeat)
```
This should only allow the container to run when `runAsNonRoot: true` is set.
`mage package` I believe
<!-- Recommended
Link related issues below. Insert the issue link or reference after the word "Closes" if merging this should automatically close it.
- Relates #40524
=> Adjust Beats container user to be numeric.

filebeat/input/filestream/internal/task/group_test.go
This PR re-enables the TestGroup_Go test, which was skipped in [#41223](https://github.com/elastic/beats/pull/41223). It also includes fixes to mitigate flakiness in the test logger caused by timming issues and ensures proper waiting for success conditions within the tests.
```bash
$ cd filebeat/input/filestream/internal/task 
$ go test -c
$ go run golang.org/x/tools/cmd/stress@latest ./task.test -test.run TestGroup_Go -test.v
```
- Fixes https://github.com/elastic/beats/issues/41218
=> Re-enable TestGroup_Go and fix flaky behavior

deploy/kubernetes/Makefile, deploy/kubernetes/auditbeat-kubernetes.yaml, deploy/kubernetes/auditbeat/auditbeat-daemonset.yaml, deploy/kubernetes/filebeat-kubernetes.yaml, deploy/kubernetes/filebeat/filebeat-daemonset.yaml, deploy/kubernetes/heartbeat-kubernetes.yaml, deploy/kubernetes/heartbeat/heartbeat-deployment.yaml, deploy/kubernetes/metricbeat-kubernetes.yaml, deploy/kubernetes/metricbeat/metricbeat-daemonset.yaml
By default we test Wolfi-based images but there is now an environment variable `IMAGE_MODIFIER` that can be used for specifying different image prefixes when calling the make target.
Also, now the test verifies the actual container readiness and deletes resources after itself.
Run the packaging command in the following folders:
* x-pack/filebeat
* x-pack/metricbeat
* x-pack/auditbeat
* x-pack/heartbeat
(put your architecture instead)
```sh
PLATFORMS=linux/arm64 PACKAGES=docker mage package
```
Then you need a running K8s cluster with the pre-configured `kubectl`. I used Docker Desktop.
then go to `./deploy/kubernetes` and run
```
make test
```
by default we test against the Wolfi-based images but it can be switched by:
```
IMAGE_MODIFIER="-ubi" mage test
```
or test the main image …
=> Switch K8s tests to Wolfi by default and make it configurable

CHANGELOG.next.asciidoc, x-pack/filebeat/_meta/config/filebeat.inputs.reference.xpack.yml.tmpl, x-pack/filebeat/docs/inputs/input-aws-cloudwatch.asciidoc, x-pack/filebeat/filebeat.reference.yml, x-pack/filebeat/input/awscloudwatch/config.go, x-pack/filebeat/input/awscloudwatch/input.go
This is a follow-up to https://github.com/elastic/beats/pull/41188 where I am adding support to source linked accounts when using `log_group_name_prefix` to derive log groups.
PR introduce `include_inked_accounts_for_prefix_mode` boolean property, which is disabled by default. If enabled (`include_inked_accounts_for_prefix_mode : true`), then we set `includeLinkedAccounts` property of the DescribeLogGroups API [1] to obtain log groups matching prefix and included in linked accounts of the monitoring account. 
ex:- 
```yaml
- type: aws-cloudwatch
...
log_group_name_prefix : /development/AppA/
include_inked_accounts_for_prefix_mode: true
... 
```
This require a linked cloudwatch account. If already has one, then,
- Push logs to a newly created log group OR use an already existing log group …
=> [Filebeat] [AWS] add support to source logs from AWS linked source accounts when using log_group_name_prefix

CHANGELOG-developer.next.asciidoc, x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/okta.go, x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/okta_test.go
See title.
Requires an okta account to test. See header of test file for details.
Example redacted output excerpts from a test run:
```
=== RUN   Test/none/my_roles
{"log.level":"debug","@timestamp":"2024-09-30T08:28:17.132+0930","log.origin":{"function":"github.com/elastic/beats/v7/x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta.getDetails[...]","file.name":"okta/okta.go","file.line":373},"message":"rate limit","limit":0.8323699233704588,"burst":1,"url":"https://REDACTEDADMINDOMAIN.okta.com/api/v1/users/REDACTEDUSER/roles","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2024-09-30T08:28:18.357+0930","log.origin":{"function":"github.com/elastic/beats/v7/x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta.oktaRateLimit","file.name":"okta/okta.go","f …
```
=> x-pack/filebeat/input/entityanalytics/okta/internal: add role and factor client calls

filebeat/input/systemlogs/input.go
See title
- Relates https://github.com/elastic/beats/issues/40526
~~## Logs~~
=> Fix error handling and add nolint comment

CHANGELOG.next.asciidoc, metricbeat/module/kubernetes/util/kubernetes.go, metricbeat/module/kubernetes/util/kubernetes_test.go
Fix Metricbeat k8s metadata sometimes not being present at startup
In the metricbeat k8s module, each metricset has an enricher, which is used to add k8s metadata to events. Enrichers use watchers to watch k8s resource changes, and these watchers can be shared between enrichers. This is implemented by each enricher maintaining a writethrough cache of metadata - when a K8s event indicating a change to a resource is received, the metadata cache is updated.
The problem with this is that a watcher is only started once, so enrichers which are created after it was started, have to catch up on the resource change events. This is a great opportunity for race conditions, and is in general unnecessarily complicated.
Instead, we turn the writethrough cache into a readthrough cache. The change event …
=> Fix Metricbeat k8s metadata sometimes not being present at startup

x-pack/packetbeat/magefile.go
So, turns out I was wrong, we _do_ need to tell packetbeat to use a specific version of npcap, and you can't just set the version flag in the crossbuild scripts. This updates the npcap version to 1.80
=> Use npcap 1.80

CHANGELOG.next.asciidoc, metricbeat/module/kubernetes/util/kubernetes.go, metricbeat/module/kubernetes/util/kubernetes_test.go
Use metadata watchers for ReplicaSets in the metricbeats Kubernetes module. This is a similar change to #41100, with two major differences:
* State metrics for ReplicaSets may actually need all the metadata, so our transform function keeps it.
* Due to the way the update handler function switches over the resource type, our resource needs to have `TypeMeta` present. The informer doesn't set this, so we need to do it ourselves.
A decent chunk of the changes is just passing around a metadata-only k8s client.
For more details see https://github.com/elastic/elastic-agent/issues/5623.
You need a full K8s cluster, unfortunately. I've tested it using the default elastic-agent standalone manifest, by building a custom container image and loading it into a local kind cluster.
- Relates …
=> Only watch metadata for ReplicaSets in metricbeat k8s module

CHANGELOG.next.asciidoc, libbeat/publisher/pipeline/ttl_batch.go, libbeat/publisher/pipeline/ttl_batch_test.go, libbeat/publisher/queue/diskqueue/consumer.go, libbeat/publisher/queue/memqueue/broker.go, libbeat/publisher/queue/memqueue/queue_test.go, libbeat/publisher/queue/queue.go
Fix https://github.com/elastic/beats/issues/41355, where event data in the memory queue was not being freed when event batches were acknowledged, but only gradually as the queue buffer was overwritten by later events. This gave the same effect as if all beat instances, even low-volume ones, were running with a full / saturated event queue.
The root cause, found by @swiatekm, is [this PR](https://github.com/elastic/beats/pull/39584), an unrelated cleanup of old code that accidentally included one live call along with the deprecated ones. (There was an old `FreeEntries` hook in pipeline batches that was only used for deprecated shipper configs, but the cleanup also removed the `FreeEntries` call _inside_ the queue which was essential for releasing event memory.)
- Fixes #41355.
=> Restore memory queue's internal event cleanup after a batch is vended

.buildkite/packaging.pipeline.yml
Packaging with `DEV=true` adds additional Go flags that sometimes lead to linker failures using the old versions of `ld.gold`.
Closes https://github.com/elastic/beats/issues/41270
=> Remove `DEV=true` for snapshot packaging

filebeat/module/system/syslog/ingest/journald.yml, filebeat/module/system/syslog/test/debian-12.journal-expected.json
This PR adds the missing `process.name` field to System module, Syslog fileset
0. Make sure you're testing on a system where system logs are sent to Journald. The Debian 12 Vagrant VM from Beats is a good option.
1. Package Filebeat (adjust for your system/platform). If you don't package it, dashboards won't be loaded
```
DEV=true SNAPSHOT=true EXTERNAL=true PACKAGES="tar.gz" PLATFORMS=linux/amd64 mage -v package
```
2. Extract it, enable the system module
```
./filebeat modules enable system …
```
=> Add the missing process.name field to System module, Syslog fileset

CHANGELOG-developer.next.asciidoc, x-pack/filebeat/input/cel/input_test.go, x-pack/filebeat/input/httpjson/input_test.go
Do not use uncontrolled randomisation in tests where it is not necessary. The retry tests in the httpjson and cel packages were using a randomised 5xx HTTP status code to trigger the retry behaviour of the the go-retryablehttp package. This had the unfortunate consequence of causing 2% of test runs to fail.
The reason for this is given in the go-retryablehttp documentation[1]:
> Mainly, if an error is returned by the client (connection errors, etc.), or if a 500-range response code is received (**except 501**), then a retry is invoked after a wait period.
Since the package is already tested, and is documented to accept all 5xx status codes except 501 to cause a retry, just use 500.
[1]https://pkg.go.dev/github.com/hashicorp/go-retryablehttp@v0.7.7#section-readme
- For #40503
=> x-pack/filebeat/input/{cel,httpjson}: fix flaky test

x-pack/auditbeat/processors/sessionmd/add_session_metadata.go
With the add_session_metadata processor, the config backend option and actual backend in use doesn't always match; the 'auto' option doesn't match a real backend (kernel_tracing, procfs). This fixes some logic so that when the 'auto' option is used, the processor will always follow the code path intended for whatever the actual backend is use is.
None
In the auditbeat config, set each of the available backend options for add_session_metadata processor ("auto", "kernel_tracking", "procfs"), and ensure the processor is enriching data correctly for each.
e.g., use this config
```
- module: auditd
processors:
- add_session_metadata:
backend: "auto"
```
=> [add_session_metadata] Always use correct code for backend in use.

CHANGELOG.next.asciidoc, dev-tools/mage/crossbuild.go
We're dropping support for Debian 10, so no need to crossbuild using the outdated image anymore.
The old linker in Debian 10 caused a packaging issue with some Go dependency updates https://github.com/elastic/beats/issues/41270
So, this update should also help with that.
**This also updates the statically linked glibc from 2.28 to 2.31.**
=> Switch crossbuilding to Debian 11

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-etw.asciidoc, x-pack/filebeat/input/etw/input.go
=> [filebeat][etw] Make ETW input GA

x-pack/auditbeat/processors/sessionmd/add_session_metadata.go, x-pack/auditbeat/processors/sessionmd/processdb/db.go, x-pack/auditbeat/processors/sessionmd/procfs/procfs.go, x-pack/auditbeat/processors/sessionmd/provider/kerneltracingprovider/kerneltracingprovider_linux.go, x-pack/auditbeat/processors/sessionmd/provider/procfsprovider/procfsprovider.go
Reduce logging levels for some log messages in the add_session_metadata processor.
If something goes wrong with the process cache where all, or most, processes are missed, many of these logs would be called for every process event, resulting in a lot of logging spam. These logs have been changed to `Debug`, which is below the default log level and will not cause log spam.
The logs that have been reduce to `Info` are in a timer, so they will not cause a lot of spam, but they should be Informational messages
There are better ways to detect if enrichment has failed, so changing the log levels shouldn't negatively affect anything. For example, an Elasticsearch query or alert on missing fields that only this processor will populate will show processes that weren't properly enriched  (i.e. …
=> Lower logging levels in add_session_metadata processor

x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
See title.
- Ref elastic/integrations#11475
=> x-pack/filebeat/docs/input: clarify interaction between split and cursor updates

.buildkite/auditbeat/auditbeat-pipeline.yml
Refactor the CI integration test steps for the Auditbeat pipeline to use build matrices for Linux tests. By doing this, it will be easier to add additional VM types to the integration tests in the future.
With this, the integration tests will run on  Ubuntu 20.04, 22.04, 24.04 for both x86_64 and arm64, and RHEL 9 x86_64.
=> Add Integration tests to Auditbeat CI pipeline

NOTICE.txt, go.sum, libbeat/outputs/otelconsumer/otelconsumer.go, libbeat/outputs/otelconsumer/otelconsumer_test.go
The call to `ConsumeLogs` can fail in various ways. If the error is of type "Permanent", retrying will have no effect. For any other error, we need to retry the batch. Additionally, only acknowledge a batch when the collector confirms receipt of the data to avoid losing events.
- I'm unsure about the `batch.Drop()` in the permanent error case, should I handle it in a different way?
- For https://github.com/elastic/ingest-dev/issues/3677
=> otelconsumer: adjustments to collector logic and retry/ack unit tests

.golangci.yml, metricbeat/module/kubernetes/util/kubernetes.go, metricbeat/module/kubernetes/util/kubernetes_test.go
Fix Node and container resource limit metrics missing intermittently.
This is a bug very recently introduced by the refactor in #41216. Metadata watchers are not just responsible for updating metadata, but also Node and container metrics. Only updating the latter eagerly when metadata is requested leads to races, where the values may be missing depending on the order in which metrics are fetched.
This fix decouples metrics calculation from metadata calculation. Metrics now have their own handlers attached to the watcher, and are completely detached from metadata enrichers. I don't like the resulting architecture that much, as it concentrates a lot of logic in the watcher. But it is an improvement over the status quo, and I'd like to fix this bug promptly before we release it to users.
The …
=> Fix Node and container resource limit metrics missing intermittently

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-entity-analytics.asciidoc, x-pack/filebeat/input/entityanalytics/provider/okta/conf.go, x-pack/filebeat/input/entityanalytics/provider/okta/okta.go, x-pack/filebeat/input/entityanalytics/provider/okta/okta_test.go, x-pack/filebeat/input/entityanalytics/provider/okta/statestore.go
- For elastic/integrations#10426.
=> x-pack/filebeat/input/entityanalytics/provider/okta: add support for role and factor data collection

CHANGELOG.next.asciidoc, x-pack/filebeat/input/awss3/config.go, x-pack/filebeat/input/awss3/input.go, x-pack/filebeat/input/awss3/input_integration_test.go, x-pack/filebeat/input/awss3/input_test.go, x-pack/filebeat/input/awss3/s3.go, x-pack/filebeat/input/awss3/sqs.go, x-pack/filebeat/input/awss3/sqs_input.go
Fix custom endpoint selection in the S3/SQS input (https://github.com/elastic/beats/issues/39718) by porting @strawgate's 8.14 fix (https://github.com/elastic/beats/pull/39709) to main.
In addition to the previous fixes, this simplifies the logic for detecting queue region, since the 8.14 version still had some broken cases caused by requiring over-strict endpoint matching, and it was concluded (talking to @strawgate) that there's no advantage to rejecting standard region format from queue URLs just because the endpoint URL is different (if there is a genuine mismatch in the queue and endpoint we'll learn it from the connection attempt, not from `getRegionFromQueueURL`).
- Fixes https://github.com/elastic/beats/issues/39718
- Fixes https://github.com/elastic/beats/issues/40792
=> Fix handling of custom endpoints in AWS input

NOTICE.txt, go.mod, go.sum
Move to the elastic/goja fork instead of andrewkroh/goja. This is the same code just moved into the elastic org and tagged with `v2019-01-28+beats`.
For background, this fork contains a small change to goja that allows arbitrary map types (such as elastic's "MapStr" type) to be treated as javascript objects without requiring any conversion.
Also note that since the time of the fork in 2019, there is now a path to accomplish this without a fork by implementing a `toValue(r *goja.Runtime) goja.Value` method on MapStr. It would mean introducing a direct dependency on goja. A tested example of can be found in the linked gist.
- https://gist.github.com/andrewkroh/19eccc0844bb935222914234c9510aa1
- https://github.com/elastic/goja/releases/tag/v2019-01-28%2Bbeats
=> go.mod - use elastic/goja fork

CHANGELOG.next.asciidoc, x-pack/metricbeat/module/gcp/constants.go, x-pack/metricbeat/module/gcp/metrics/metrics_requester.go, x-pack/metricbeat/module/gcp/metrics/metrics_requester_test.go
- [  ] I have commented my code, particularly in hard-to-understand areas
- [  ] I have made corresponding changes to the documentation
- [  ] I have made corresponding change to the default configuration files
- [ x ] I have added tests that prove my fix is effective or that my feature works
- [ x ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.
- Closes https://github.com/elastic/beats/issues/41360
=> Add support for region/zone for Vertex AI service in GCP module

libbeat/outputs/otelconsumer/otelconsumer.go, libbeat/outputs/otelconsumer/otelconsumer_test.go
The elasticsearchexporter does not handle a 413 Request Entity too Large from Elasticsearch, only forwarding the error back to the client.
When using the batcher config in the ES exporter, it runs synchronously, any error reported can be intercepted in the otelconsumer. When using the batch processor this happens asynchronously and there is no way to handle the error. If we can intercept an entity too large error, split the batch and retry.
See https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/36163
- Relates to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/36163.
- For https://github.com/elastic/ingest-dev/issues/3677
=> otelconsumer: handle entity too large errors

.github/workflows/updatecli.d/bump-golang.yml, go.mod
The previous configuration was always replacing the full version of Go with a minor version: 1.22.8 -> 1.22.
Newer versions of Go now put the full version value in `go.mod`. This leads to our CI failing because `go mod tidy` causes a change in `go.mod`.
This is to fix those failures.
=> Put full version of Go in go.mod while updating

metricbeat/module/system/test_system.py, metricbeat/tests/system/metricbeat.py
For `diskio` metricset, https://github.com/elastic/beats/blob/bfaa70fa9ae857322d4deaf9e870ba8b84fbd8e3/metricbeat/module/system/diskio/diskio.go#L118-L120
`serial_number` field is set, conditionally. 
This error has likely originated by bumping [PR](https://github.com/elastic/elastic-agent-system-metrics/pull/178/) on https://github.com/elastic/elastic-agent-system-metrics. 
I think, for such conditional fields, our best case is to remove them from `event` or else they trigger a failure.
We cannot add such fields at https://github.com/elastic/beats/blob/bfaa70fa9ae857322d4deaf9e870ba8b84fbd8e3/metricbeat/module/system/test_system.py#L70-L76 
as that would also result in a failure, because the `serial_number` can be absent for some devices.
This is needed to unblock …
=> [chore][metricbeat/test_diskio]: fix CI failure

CHANGELOG.next.asciidoc, libbeat/processors/add_cloud_metadata/docs/add_cloud_metadata.asciidoc, libbeat/processors/add_cloud_metadata/provider_aws_ec2.go, libbeat/processors/add_cloud_metadata/provider_aws_ec2_test.go, libbeat/processors/add_cloud_metadata/providers.go
This PR adds support to enrich events with EC2 tags iff,
- IMDS endpoint is enabled [^1]
- Tag access is enabled through IMDS endpoint. [^2]
Tags are added to event payload with key `aws.tags.<KEY>`, 
```json
{
"aws" : {
"tags" : {
"org" : "acme",
"owner" : "userA"
}
}
}
```
The best way to validate this is through a beats deployment (ex:- metricbeat) in an EC2 instance.
- Create an EC2 instance
- Enable IMDS endpoint
- Enable tags access through IMDS endpoint 
- Assign instance with a role with adequate permissions
- Add few tags to the instance
- Build metricbeat from this branch
- Deploy custom build into EC2
- Enable `add_cloud_metadata` processor
- Run and observe metrics containing tags 
Closes #31899
[^1]: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-meta …
=> [AWS] [EC2] enrich events with EC2 tags with add_cloud_metadata processor

.buildkite/auditbeat/auditbeat-pipeline.yml, .buildkite/filebeat/filebeat-pipeline.yml, .buildkite/heartbeat/heartbeat-pipeline.yml, .buildkite/metricbeat/pipeline.yml, .buildkite/packetbeat/pipeline.packetbeat.yml, .buildkite/x-pack/pipeline.xpack.auditbeat.yml, .buildkite/x-pack/pipeline.xpack.filebeat.yml, .buildkite/x-pack/pipeline.xpack.heartbeat.yml, .buildkite/x-pack/pipeline.xpack.metricbeat.yml, .buildkite/x-pack/pipeline.xpack.osquerybeat.yml, .buildkite/x-pack/pipeline.xpack.packetbeat.yml
Added concurrency group for all macOS related steps in order to limit orka load.
Only 10 agents can be used simultaneously, while other builds will wait in a queue.
- Relates: https://github.com/elastic/ingest-dev/issues/4337
Buildkite builds: https://buildkite.com/elastic/beats/builds/15099
=> Add concurrency groups to macOS steps on 7.17

.buildkite/packaging.pipeline.yml
The packaging pipeline broke after the update to Go 1.22.9. The issue appeared to be an OOM. This change is to bump the packaging pipeline machine type to have more memory available to avoid an OOM.
Slack context: https://elastic.slack.com/archives/C047NDNGUMU/p1731443732767939
Passing test build: https://buildkite.com/elastic/beats-packaging-pipeline/builds/1633
=> Packaging pipeline mem bump

CHANGELOG.asciidoc, libbeat/template/load_test.go, libbeat/template/template.go
libbeat: increase index template total_fields.limit to 12500
It increased the `index.mapping.total_fields.limit` from `10000` to `12500` in order to avoid ingestion failures caused by too many field in the index. Since 8.15.0 the limit started to be hit.
The field count being exceeded is on the index, counting all mapped fields and the dynamic fields. That's why a small event might trigger the error, the event contains new fields to be mapped which would exceed the total field limit if mapped.
Whereas the `index.mapping.total_fields.limit` might impact …
=> libbeat: increase total_fields.limit to 12500

CHANGELOG.next.asciidoc, winlogbeat/docs/winlogbeat-options.asciidoc, winlogbeat/sys/wineventlog/query.go, winlogbeat/sys/wineventlog/query_test.go
-  Implement exclusion range support for Winlogbeat event_id
- Closes #38623
=> [winlogbeat] Implement exclusion range support for event_id

CHANGELOG.next.asciidoc, x-pack/filebeat/input/streaming/crowdstrike.go, x-pack/filebeat/input/streaming/websocket.go
=> x-pack/filebeat/input/streaming: fix missing key in streaming input logging

metricbeat/mb/module/wrapper.go, metricbeat/mb/module/wrapper_internal_test.go
Add configurable failure threshold before reporting streams as degraded
With this change it is possible to configure a threshold for the number of consecutive errors that may happen while fetching metrics for a given stream before the stream gets marked as DEGRADED.
To configure such threshold, add a `"failure_threshold": <n>` to a module configuration block.
Depending on the value of `<n>` the threshold will be configured in different ways:
- n == 0: status reporting for the stream has been disabled, the stream will never become DEGRADED no matter how many errors are encountered while fetching metrics
- n==1 or `failure_threshold` not specified: backward compatible behavior, the stream will become DEGRADED at the first error encountered
- n > 1: stream will become DEGRADED after at least …
=> Metricbeat: add configurable failure threshold before reporting streams as degraded

CHANGELOG.next.asciidoc, x-pack/filebeat/_meta/config/filebeat.inputs.reference.xpack.yml.tmpl, x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc, x-pack/filebeat/filebeat.reference.yml, x-pack/filebeat/input/awss3/config.go, x-pack/filebeat/input/awss3/config_test.go, x-pack/filebeat/input/awss3/input.go, x-pack/filebeat/input/awss3/input_integration_test.go, x-pack/filebeat/input/awss3/s3.go, x-pack/filebeat/input/awss3/s3_test.go
Added a new option `access_point_arn` to the AWS S3 input as an alternative to the bucket ARN to access S3 buckets.
- Closes https://github.com/elastic/beats/issues/41494
=> x-pack/filebeat/input/awss3: support for Access Point ARN

CHANGELOG.asciidoc
Adds a known issue to the 8.16 and 8.15 [release notes](https://www.elastic.co/guide/en/beats/libbeat/master/release-notes-8.16.0.html) for the AWS S3 input.
---
=> Add known issue for AWS S3 input (target 8.15)

CHANGELOG.asciidoc
Adds a known issue to the 8.16 and 8.15 [release notes](https://www.elastic.co/guide/en/beats/libbeat/master/release-notes-8.16.0.html) for the AWS S3 input.
---
=> Add known issue for AWS S3 input (target 8.16)

NOTICE.txt, go.mod, go.sum
This update includes a notable performance improvement for [determining host ip addresses](https://github.com/elastic/go-sysinfo/pull/246).
It looks like dependabot is currently blocked by a bunch of large collective updates, so I'm submitting this separately.
- Relates https://github.com/elastic/elastic-agent/issues/5835
=> Bump github.com/elastic/go-sysinfo to v1.15.0

x-pack/metricbeat/tests/integration/setup_integration_test.go
```
metricbeat: add integration TestIndexTotalFieldsLimitNotReached
The new integration test TestIndexTotalFieldsLimitNotReached ensures events with at least 500 new dynamically mapped fields can be ingested.
```
This new test will start failing when the metricbeat mapping has increased to the point it isn't possible to add a new event with 500 dynamically mapped fields. It should act as a safe guard to prevent us from releasing a version where the static mapping is too close to the total fields limit.
- ~~[ ] I have added an entry in `CHANGELOG.next.asciidoc` or …
=> metricbeat: add integration TestIndexTotalFieldsLimitNotReached

CHANGELOG.next.asciidoc, NOTICE.txt, go.mod, go.sum
```
Update to go-libaudit v2.6.1.
This release updates the syscall tables for Linux 6.11. And it corrects the ECS `event.type`
value used for SERVICE_STOP, DAEMON_ABORT, and DAEMON_END messages.
https://github.com/elastic/go-libaudit/releases/tag/v2.6.1
```
https://github.com/elastic/go-libaudit/compare/v2.5.0..v2.6.1
=> go.mod - update to go-libaudit v2.6.1

CHANGELOG.next.asciidoc, x-pack/filebeat/input/awss3/metrics.go, x-pack/filebeat/input/awss3/s3_objects.go, x-pack/filebeat/input/awss3/s3_objects_test.go
This fixes a bug with Cloudflare logpush integration, which uses the S3 input. 
https://github.com/elastic/beats/pull/40775 introduced a feature introducing s3_object_size_in_bytes histogram. Internally it utilized S3 SDK's GetObjectOutput instances' ContentLength property [^1].  In code level (SDK internally), this is derived using Content-Length header [^2].
It seems that Cloudflare R2 (API compatible with S3) could omit Content-Length header [^3]. Hence, I have improved how we derive the `s3_object_size_in_bytes` metric by avoiding using Content-Length backed method. 
- Build filebeat from this branch
- Enable monitoring endpoints
- Configure buckets with data and observe metrics in monitoring endpoint
See metric comparison with proposed collection method (before removing content …
=> [AWS] [S3] fix: improve object size metric calculation

x-pack/filebeat/fbreceiver/factory.go, x-pack/filebeat/fbreceiver/receiver.go, x-pack/metricbeat/mbreceiver/config.go, x-pack/metricbeat/mbreceiver/config_test.go, x-pack/metricbeat/mbreceiver/factory.go, x-pack/metricbeat/mbreceiver/receiver.go, x-pack/metricbeat/mbreceiver/receiver_test.go
This adds a metricbeat OTel receiver.  This is necessary to run beats as OTel receivers.
None.  You have to import beats into your OTel project and instantiate a
```shell
cd x-pack/metricbeat/mbreceiver
go test -v .
```
- Closes #41691
=> add metricbeat receiver

NOTICE.txt, go.mod, go.sum
```
This release updates the syscall tables based on Linux v6.11.
https://github.com/elastic/go-seccomp-bpf/releases/tag/v1.5.0
```
https://github.com/elastic/go-seccomp-bpf/compare/v1.4.0..v1.5.0
=> go.mod - update to elastic/go-seccomp-bpf v1.5.0

CHANGELOG.next.asciidoc, libbeat/processors/add_cloud_metadata/docs/add_cloud_metadata.asciidoc, libbeat/processors/add_cloud_metadata/provider_alibaba_cloud.go, libbeat/processors/add_cloud_metadata/provider_aws_ec2.go, libbeat/processors/add_cloud_metadata/provider_azure_vm.go, libbeat/processors/add_cloud_metadata/provider_digital_ocean.go, libbeat/processors/add_cloud_metadata/provider_google_gce.go, libbeat/processors/add_cloud_metadata/provider_hetzner_cloud.go, libbeat/processors/add_cloud_metadata/provider_openstack_nova.go, libbeat/processors/add_cloud_metadata/provider_tencent_cloud.go, libbeat/processors/add_cloud_metadata/providers.go, libbeat/processors/add_cloud_metadata/providers_test.go
This PR fixes incorrect recognition of EC2/AWS cloud provider as Openstack. The root cause was the common metadata endpoints used by both AWS SDK & Openstack logic. And this happened when IMDSv2 is disabled in AWS. 
I attempted to migrate Openstack logic to another metadata implementation. However, I did not manage to create a fully functioning setup to validate the implementation. Hence, this PR focuses on a priority-based solution where priority is given for SDK-backed metadata fetching over HTTP endpoints. 
Current priory providers are - aws/ec2 & azure 
Note - I have done a minor refactoring to rename `Local` struct property to `DefaultEnabled` to make intention clearer
You need a local copy and an EC2 instance to validate the fix.
- Enable metadata service in EC2 instance and make …
=> [libbeat] fix: aws & openstack metadata conflict in add_cloud_metadata processor

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-http-endpoint.asciidoc, x-pack/filebeat/input/http_endpoint/config.go, x-pack/filebeat/input/http_endpoint/handler.go, x-pack/filebeat/input/http_endpoint/handler_test.go, x-pack/filebeat/input/http_endpoint/input.go, x-pack/filebeat/input/http_endpoint/input_test.go
The input does not have a way to communicate back-pressure to clients, potentially leading to unconstrained growth in the publisher event queue and an OoM event. This change adds a mechanism to keep track of the total sum of in-flight message bytes from the client in order to allow the server to return a 503 HTTP status when the total is too large.
Note that this does not monitor the total memory in the queue as that would require a complete understanding of the allocations in the preparation of event values to be sent to the publisher, but rather uses the message length as a reasonable proxy.
- Fixes #41764
=> x-pack/filebeat/input/http_endpoint: fix handling of http_endpoint request exceeding memory limits

libbeat/outputs/kafka/client.go, libbeat/outputs/kafka/kafka_integration_test.go, libbeat/outputs/redis/backoff.go, libbeat/outputs/redis/client.go, libbeat/tests/integration/kafka_test.go
- Closes https://github.com/elastic/beats/issues/41823
In https://github.com/elastic/beats/pull/40794 the Connectable interface was changed to include a `context.Context` argument, causing all clients with a Connect() that weren't updated to have a `Context(context.Context)` method instead to fail the NetworkClient interface check in https://github.com/elastic/beats/blob/367d94e1dc40a82713d651735eac7921bb584474/libbeat/publisher/pipeline/client_worker.go#L64-L70
This made it so that the Kafka and Redis outputs no longer counted as NetworkClients, bypassing the initial call to `Connect()` that was there previously at https://github.com/elastic/beats/blob/367d94e1dc40a82713d651735eac7921bb584474/libbeat/publisher/pipeline/client_worker.go#L143
In the case of Kafka the Connect call never …
=> Fix Kafka output panic at startup

metricbeat/cmd/root.go, metricbeat/main.go, metricbeat/main_test.go, x-pack/agentbeat/main.go, x-pack/libbeat/management/tests/mbtest/metricbeat_v2_test.go, x-pack/libbeat/management/tests/mbtest/system/process_integration_test.go, x-pack/metricbeat/cmd/root.go, x-pack/metricbeat/main.go, x-pack/metricbeat/main_test.go
Move metricbeat command setup outside of `init` function.  Having the setup inside the `init` function causes problems when you import metricbeat into other code bases.  A specific use case is when you use metricbeat as an otel receiver.
None.
Run unit tests
- Relates elastic/elastic-agent#6138
- Relates #41738
=> move metricbeat command setup out of init

metricbeat/module/system/raid/blockinfo/getdev.go, metricbeat/module/system/raid/raid.go, metricbeat/module/system/raid/raid_test.go
When the Linux Metrics integration (beta) is installed with the raid metrics option enabled it causes an error if the host does not have a RAID configuration. This error causes the Agent to go into a degraded state.
This happens because we report not having `/sys/block/md*` devices  as an error, this only means that no RAID configuration is in place.
Instead, do not report this case as an error.
- Closes https://github.com/elastic/elastic-agent/issues/6155
=> metricbeat: suppress error when RAID metrics are enabled on non-RAID system

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-cel.asciidoc, x-pack/filebeat/input/cel/config.go, x-pack/filebeat/input/cel/input.go, x-pack/filebeat/input/cel/input_test.go
This allows a program to conditionally dump a complete set of evaluation states from a program in the case that it fails, allowing a trace of execution leading to the failure.
- Depends #41727
=> x-pack/filebeat/input/cel: add evaluation state dump debugging feature

CHANGELOG.next.asciidoc, libbeat/processors/namespace.go, libbeat/processors/namespace_test.go
Prevent panic if libbeat plugins are loaded more than once.
None.
- Closes #41475
=> Don't panic if libbeat processors are registered more than once

CHANGELOG.next.asciidoc, x-pack/filebeat/input/awss3/input_benchmark_test.go, x-pack/filebeat/input/awss3/s3_input.go, x-pack/filebeat/input/awss3/s3_test.go, x-pack/filebeat/input/awss3/states.go, x-pack/filebeat/input/awss3/states_test.go
Improves S3 polling mode state registry copy by considering the `bucket_list_prefix` usage. Before this change, input stored all registry entries loaded from the underlying registry (ex:- when storing, restarting beats or upgrading while pointing to the same registry). With this improvement, when `bucket_list_prefix` is used, the state registry copy only holds entries matching the given prefix. 
This improvement benefits the state registry clean-up planned through https://github.com/elastic/beats/pull/41694. Further, when beats restart, this change improves the input-specific state copy memory usage by only storing relevant entries, matching the configured prefix. 
None - this change only concerns the input-specific copy of the registry entries
Requires a build and S3 bucket entries with …
=> [AWS] improve S3 input states copy by only storing filtered entries

CHANGELOG.next.asciidoc, x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/okta.go, x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/okta_test.go, x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/ratelimiter.go, x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/ratelimiter_test.go, x-pack/filebeat/input/entityanalytics/provider/okta/okta.go, x-pack/filebeat/input/entityanalytics/provider/okta/okta_test.go
```
x-pack/filebeat/input/entityanalytics/provider/okta: Rate limiting fixes
- Separate rate limits by endpoint.
- Stop requests until reset when `x-rate-limit-remaining: 0`.
```
Can be reviewed commit-by-commit.
The reason a new `rate.Limiter` needs to be created when `x-rate-limit-remaining: 0` is that while `rate.Limiter` allows updating of the rate and burst, it doesn't allow clearing of existing tokens.
None.
- Relates #40106
=> x-pack/filebeat/input/entityanalytics/provider/okta: Rate limiting fixes

CHANGELOG.next.asciidoc, NOTICE.txt, go.mod, go.sum
```
Fix a bug where log files are rotated on startup when interval is configured 
and rotateonstartup is disabled.
Closes: #41894
Relates: elastic/elastic-agent-libs#259
```
- Closes [#41894](https://github.com/elastic/beats/issues/41894)
- Relates https://github.com/elastic/elastic-agent-libs/pull/259
- https://github.com/elastic/elastic-agent-libs/compare/v0.17.3...v0.17.4
=> Fix log file rotation bug

CHANGELOG.next.asciidoc, x-pack/filebeat/input/awss3/s3_input.go, x-pack/filebeat/input/awss3/states.go, x-pack/filebeat/input/awss3/states_test.go
This PR partially addresses https://github.com/elastic/beats/issues/39116 by introducing a registry cleanup strategy for aws-s3 input. 
The cleanup implemented here removes registry entries if the s3 object is no longer available (aka tracked) when listing inside the polling lookup. The cleanup removes objects that are not tracked from both the local state and internal store (backed by the registry) to reduce the memory usage.
Note that, this only benefits when s3 objects get removed (ex:- using lifecycle policy) and are no longer available. There should be a follow-up for instances where such removal is not done at the bucket. For example, this could be done by,
- Defining a time-based sliding window (ex:- only consider s3 objects of the past 3 days)
- Only accept objects of a known …
=> [aws] feat: aws-s3 input registry cleanup for untracked s3 objects

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-azure-eventhub.asciidoc, x-pack/filebeat/input/azureeventhub/tracer.go
Make the `azure-eventhub` input v1 internal logs tracer opt-in. To enable internal (legacy) Event Hub SDK logs, now you need to set the following environment variable:
```sh
BEATS_AZURE_EVENTHUB_INPUT_TRACING_ENABLED: true
```
Before this change, the tracer was enabled by default.
A few customers reported higher than anticipated error logs in edge cases. These error logs are an essential signal to troubleshoot the root cause of several issues. However, we should give the option to completely opt out from the internal logs tracing when needed.
- Closes https://github.com/elastic/beats/issues/41931
=> [azure-eventhub] Make the azure-eventhub input v1 tracer opt-in

CHANGELOG-developer.next.asciidoc, x-pack/filebeat/docs/inputs/input-cel.asciidoc, x-pack/filebeat/input/cel/config.go, x-pack/filebeat/input/cel/input.go, x-pack/filebeat/input/cel/input_test.go
This allows collecting the execution coverage data from a running input. Coverage data is logged as JSON data at debug level when this option is enabled. Currently no tooling is available for rendering the data in a more human-friendly format, but the backing infrastructure for this exists in the mito repository.
Run `go test -v` in x-pack/filebeat/input/cel (maybe with `-run TestInput/coverage` to mimimise irrelevant verbosity, but season to taste).
You should see lines like (jq expanded):
```
{
"log.level": "debug",
"@timestamp": "2024-12-04T11:22:34.585+1030",
"log.logger": "cel_test",
"function": "github.com/elastic/beats/v7/x-pack/filebeat/input/cel.input.run.func1.1",
"file.name": "cel/input.go",
"file.line": 237
},
"message": "coverage",
"input_url": "",
"details": …
```
=> x-pack/filebeat/input/cel: add evaluation coverage collection support

CHANGELOG.next.asciidoc, x-pack/filebeat/input/httpjson/input.go, x-pack/filebeat/input/httpjson/request.go
This requires a small duplication of the mapstr.M API to workaround an issue in that type that can result in corruption of data.
```
x-pack/filebeat/input/httpjson: redact authentication headers in logging
This requires a small duplication of the mapstr.M API to workaround an
issue in that type that can result in corruption of data.
```
- Ref elastic/elastic-agent-libs#232
=> x-pack/filebeat/input/httpjson: redact authorization headers in logging

filebeat/beater/filebeat.go, heartbeat/monitors/mocks.go, libbeat/beat/info.go, libbeat/cmd/instance/beat.go, x-pack/filebeat/input/benchmark/input.go, x-pack/heartbeat/scenarios/framework/framework.go
Add a unique per beat monitoring namespace.  If this is `nil` then the current default namespace is used.  This is necessary so a Beat receiver can be instantiated multiple times without having panics due to registering the same variable twice.
None, behavior is unchanged for normal beats usage.
Run the unit test suites to make sure no behavior changes for normal beats usage
1. Build `elastic-agent` using this PR to satisfy the beat dependency
2. Run `elastic-agent otel -c otel.yml with the following config
```yaml
receivers:
filebeatreceiver/1:
filebeat:
inputs:
- type: benchmark
enabled: true
message: "test"
eps: 1
output:
otelconsumer:
logging:
level: debug
selectors:
- '*'
processors:
- add_fields:
target: project
fields:
name: filebeatreceiver1
filebeatreceiver/2:
filebeat:
inputs:
- …
```
=> Add unique per beat monitoring namespace

libbeat/outputs/otelconsumer/otelconsumer.go, libbeat/outputs/otelconsumer/otelconsumer_test.go
This code was initially added in #41523 because of a limitation from the elasticsearch exporter.
The elasticsearch exporter has been updated to enforce flush::bytes for the batcher extension and will automatically split the batch if it exceeds the limit.
This error is now fixed in the collector v0.115.0.
See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/36396.
- For https://github.com/elastic/ingest-dev/issues/3677
=> otelconsumer: remove temporary handling of entity too large

CHANGELOG.asciidoc
Adds the removed `docker` input for Filebeat to the [Beats 8.0 breaking changes list](https://www.elastic.co/guide/en/beats/libbeat/current/release-notes-8.0.0.html). See the related issue for details.
Closes: https://github.com/elastic/beats/issues/41624
---
=> Add breaking change for Filebeat removed 'docker' input

.github/CODEOWNERS
Removing Eng Prod from being listed as the metricbeat tests owners.
=> Remove Eng Prod metricbeats tests ownership

dev-tools/packaging/templates/ironbank/auditbeat/hardening_manifest.yaml, dev-tools/packaging/templates/ironbank/filebeat/hardening_manifest.yaml, dev-tools/packaging/templates/ironbank/heartbeat/hardening_manifest.yaml, dev-tools/packaging/templates/ironbank/metricbeat/hardening_manifest.yaml, dev-tools/packaging/templates/ironbank/packetbeat/hardening_manifest.yaml
As the original person doing the integration of the Elastic artifacts into the Ironbank, my name made it to the manifest file. I however do not contribute neither to the Ironbank nor to beats and as such, the notifications I am receiving are complely actionable on my end. I would recommend having the right beats* members be added to this file so they can get notifed accordingly.
-
=> Remove Nassim from ironbank maintainers list

auditbeat/auditbeat.reference.yml, filebeat/filebeat.reference.yml, heartbeat/heartbeat.reference.yml, libbeat/_meta/config/logging.reference.yml.tmpl, libbeat/docs/loggingconfig.asciidoc, metricbeat/metricbeat.reference.yml, packetbeat/packetbeat.reference.yml, winlogbeat/winlogbeat.reference.yml, x-pack/auditbeat/auditbeat.reference.yml, x-pack/filebeat/filebeat.reference.yml, x-pack/functionbeat/functionbeat.reference.yml, x-pack/heartbeat/heartbeat.reference.yml, x-pack/metricbeat/metricbeat.reference.yml, x-pack/osquerybeat/osquerybeat.reference.yml, x-pack/packetbeat/packetbeat.reference.yml, x-pack/winlogbeat/winlogbeat.reference.yml
Change 'event-data' to 'events-data' in the document.
https://github.com/elastic/beats/blob/1bd39c5cf55eed1715a41133ef64c324fc83adca/libbeat/tests/system/beat/beat.py#L535
https://github.com/elastic/beats/blob/1bd39c5cf55eed1715a41133ef64c324fc83adca/libbeat/tests/integration/framework.go#L626
=> Correct the default filename of events-data

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-streaming.asciidoc, x-pack/filebeat/input/streaming/config.go, x-pack/filebeat/input/streaming/websocket.go
- Enhancement
Added default values for websocket retries & put a cap on waitTime to be <= waitMax. Updated the documentation accordingly. Capping the waitMax value avoids long/indefinite wait times that can be caused due to backoff calculation.
- Relates https://github.com/elastic/beats/pull/41934
=> [filebeat][streaming] - Added default values for websocket retries & put a cap on waitTime to be <= waitMax

metricbeat/docs/modules/system.asciidoc, metricbeat/metricbeat.reference.yml, metricbeat/module/system/_meta/config.reference.yml, metricbeat/module/system/core/_meta/docs.asciidoc, metricbeat/module/system/core/config.go, metricbeat/module/system/cpu/_meta/docs.asciidoc, metricbeat/module/system/cpu/config.go, x-pack/metricbeat/metricbeat.reference.yml
Alternative to https://github.com/elastic/beats/pull/42042.
This is a temporary fix as CI on elastic-agent's main is broken https://buildkite.com/elastic/elastic-agent-extended-testing/builds/5390#0193c17f-c655-422a-8dc9-ae5a7a40fdbd. 
This most likely happened because user not having enough permissions to read from performance counter. I'll do some more digging and fix the underlying issue.
=> [system/cpu,core] - Disable performance counter by default to unblock agent CI

CHANGELOG.next.asciidoc, metricbeat/include/list_init.go, metricbeat/module/elasticsearch/index/data.go
Changed `CreationDate` field internally from `int` to `string` - the marshalling of the string leads to scientific notation on some versions. Keeping it as string makes sure the value is passed as-is.
=> Changed CreationDate to string to prevent scientific notation conversion

CHANGELOG.next.asciidoc, libbeat/processors/add_kubernetes_metadata/docs/indexers_and_matchers.asciidoc, libbeat/processors/add_kubernetes_metadata/matchers.go, libbeat/processors/add_kubernetes_metadata/matchers_test.go
Add the ability to extract the matching key from fields using a regex pattern to the add_kubernetes_metadata processor. I've added a new field - `regex_pattern` to the existing `fields` matcher. If the field isn't present, the matcher continues to work the same way it used to. The regex pattern has to contain a named capture group: `key`, and the first leftmost match for this group is the extracted key value. Other than this, the semantics are identical to the existing ones for the `fields` matcher.
This was originally intended to fix https://github.com/elastic/ingest-dev/issues/3428, where we want to match on a part of `system.process.cgroup.id`. I've verified this by building an agent container image with this change enabled, and making the following changes to the default agent …
=> Add regex pattern matching to add_kubernetes_metadata processor

CHANGELOG.next.asciidoc, x-pack/filebeat/input/awss3/decoding.go, x-pack/filebeat/input/awss3/decoding_csv.go, x-pack/filebeat/input/awss3/s3_objects.go
=> x-pack/filebeat/input/awss3: fix document ID construction when using csv decoder

metricbeat/docs/modules/mongodb.asciidoc, metricbeat/module/mongodb/_meta/docs.asciidoc, metricbeat/module/mongodb/dbstats/dbstats_integration_test.go, metricbeat/module/mongodb/docker-compose.yml
Use MongoDB 5.0 in metricbeat integration tests.
We're currently using 3.4, which is old enough that GPG signatures have expired for packages in the underlying Ubuntu base image.
This PR is essentially a selective backport of https://github.com/elastic/beats/pull/34624. I've only included the changes necessary to make the tests pass and documentation updates.
```bash
cd metricbeat
MODULE=mongodb make integration-tests
```
Fixes CI failures in https://github.com/elastic/beats/pull/42073.
=> [7.17] Use MongoDB 5.0 in metricbeat integration tests

x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/ratelimiter_test.go
This test is flaky, see: https://github.com/elastic/beats/issues/42059
-
=> Skip flaky test TestRateLimiter

CHANGELOG.next.asciidoc, x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/okta.go, x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/okta_test.go, x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/ratelimiter.go, x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/ratelimiter_test.go
```
.../input/entityanalytics/provider/okta: Handle 429s, concurrent limits
- Retry requests that get a 429 response, up to a maximum number of
retries.
- If the concurrent rate limit[1] is exceeded, reset to the default
initial rate, rather than to zero.
[1] https://developer.okta.com/docs/reference/rl-best-practices/#example-rate-limit-header-with-concurrent-rate-limit
```
Hiding whitespace changes will greatly improve the readability of the diff for `x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/okta.go`. It's mostly indentation changes.
For the concurrent rate limit, the previous behavior was to reset to a rate of zero, which would cause an error because the next wait would exceed the maximum wait time.
- Relates #40106
=> .../input/entityanalytics/provider/okta: Handle 429s, concurrent limits

x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
Preview: https://beats_bk_42114.docs-preview.app.elstc.co/guide/en/beats/filebeat/master/filebeat-input-aws-s3.html
```
Minor improvements to the Filebeat aws-s3 input documentation.
Wrap long lines to generally limit lines to 80 characters.
Increase the heading level for the csv and parquet decoders so
that they are sub-headings of the decoder section.
Fix several grammatical issues and rewrite some unclear sections.
```
I wanted to add a new section about the input's `_id` calculation, but I could ignore the existing issues.
Once this is complete, I'll add the new section.
I recommend reviewing each commit separately. The first (and largest) commit is just line wrapping changes.
From https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-input-aws-s3.html:
=> [Filebeat] minor cleanup to aws-s3 input docs

x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
Preview link: https://beats_bk_42127.docs-preview.app.elstc.co/guide/en/beats/filebeat/master/filebeat-input-aws-s3.html
```
Document the details about how the Filebeat aws-s3 input generates
Elasticsearch document _id values.
Add a subsection for the configuration examples.
Move "Common configuration" section immediately after the input
configuration options.
```
- Relates #42078 (my updated text includes Last-Modified time in the behavioral description)
|Before|After|
|--|--|
|<img width="133" alt="Screenshot 2024-12-19 at 16 46 10" src="https://github.com/user-attachments/assets/cd7f89b0-9726-4019-a11c-c14b897ee408" />|<img width="131" alt="Screenshot 2024-12-19 at 17 45 07" src="https://github.com/user-attachments/assets/90a6ffb5-3d31-4a01-ae93-a3509b32c190" />|
=> [Filebeat] aws-s3 - Document _id generation behavior

CHANGELOG-developer.next.asciidoc, x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/ratelimiter_test.go
```
.../input/entityanalytics/provider/okta: Fix flaky tests
In rate limiting tests by expanding the allowed ranges by 10x.
Earlier failures were double the allowed ranges:
ratelimiter_test.go: doesn't allow requests to resume after reset. had to wait 1.0242622s
ratelimiter_test.go: tokens don't accumulate at the expected rate over 30s: 30.024262
```
None.
- Closes #42059
=> .../input/entityanalytics/provider/okta: Fix flaky tests

CHANGELOG.next.asciidoc, dev-tools/packaging/packages.yml, dev-tools/packaging/templates/docker/Dockerfile.tmpl
Due to ECE compatibility issues we have to switch back to 20.04.
```
PLATFORMS=linux/arm64 PACKAGES=docker mage package
```
```
docker.elastic.co/beats/filebeat 8.17.1 19e23b0fa142 356MB
```
<details>
<summary>docker history</summary>
```
IMAGE          CREATED              CREATED BY                                      SIZE      COMMENT
19e23b0fa142   About a minute ago   CMD ["-environment" "container"]                0B        buildkit.dockerfile.v0
<missing>      About a minute ago   ENTRYPOINT ["/usr/bin/tini" "--" "/usr/local…   0B        buildkit.dockerfile.v0
<missing>      About a minute ago   WORKDIR /usr/share/filebeat                     0B        buildkit.dockerfile.v0
<missing>      About a minute ago   ENV LIBBEAT_MONITORING_CGROUPS_HIERARCHY_OVE…   0B …
```
=> Revert the Ubuntu version update

filebeat/_meta/config/filebeat.inputs.reference.yml.tmpl, filebeat/_meta/config/filebeat.inputs.yml.tmpl, filebeat/filebeat.reference.yml, filebeat/filebeat.yml, x-pack/filebeat/filebeat.reference.yml, x-pack/filebeat/filebeat.yml
This commit adds Journald to the default `filebeat.yml` file and improves 
`filebeat.refenrence.yml` with all configurable options for the journald input
- It's part of https://github.com/elastic/beats/issues/37877
~~## Logs~~
=> Add configuration example and improve reference

CHANGELOG.next.asciidoc, NOTICE.txt, go.mod, go.sum
Closes https://github.com/elastic/beats/issues/41407
=> [go.mod] update elastic-agent-system-metrics

libbeat/asset/registry.go, x-pack/filebeat/fbreceiver/receiver_test.go
While working on #41888 I was benchmarking the filebeatreceiver
CreateLogs factory and noticed that the asset decoding in libbeat
dominates the cpu and memory profile of the receiver creation.
This behavior is expected since asset decoding is intended to occur at
startup. However, it's still worthwhile to optimize it if possible.
Some time ago I worked on `iobuf.ReadAll` at
elastic/elastic-agent-libs#229, an optimized version of `io.ReadAll`
that has a better growth algorithm—based on bytes.Buffer—and
benefits from the `io.ReaderFrom` optimization. The choice of when to
use this is very picky, as using it with a reader that is not a
`io.ReaderFrom` can be slower than the standard `io.ReadAll`. For this
case we are certain of the reader implementation, so we can use it.
Benchmark results …
=> libbeat: optimize asset data decoding

CHANGELOG.next.asciidoc, x-pack/filebeat/input/streaming/websocket.go
- Bug
Some valid websocket retry codes were missing from the initial implementation, which could lead to retries not occurring in some scenarios, hence added some more codes to retry on. There is a table below that shows what codes are currently retryable and why.
```
+---------------------------------------+---------------------------------------------------------+---------+
| Close Code                            | Description                                             | Retry?  |
+---------------------------------------+---------------------------------------------------------+---------+
| 1000 - CloseNormalClosure             | Connection closed normally.(can be a false positive)    | Yes     |
| 1001 - CloseGoingAway                 | Endpoint is going away (e.g., server shutdown). …
```
=> [filebeat][streaming] - Added more retry codes to websocket retry logic

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-streaming.asciidoc, x-pack/filebeat/input/streaming/config.go, x-pack/filebeat/input/streaming/config_test.go, x-pack/filebeat/input/streaming/input_test.go, x-pack/filebeat/input/streaming/websocket.go
- Enhancement
- Docs
Added new config options to enable blanket & infinite retries selectively. There might be edge case scenarios in production environments which might require to retry infinitely (with backoff) in all scenarios. These options can be individually controlled and are not coupled together. Also improved logging for the retry section.
None
- Relates https://github.com/elastic/integrations/issues/11816
=> [filebeat][websocket] - Added infinite & blanket retry options to websockets and improved logging and retry logic 

.github/workflows/check-default.yml, .github/workflows/check-docs.yml
The GitHub runners has been bumped from ubuntu-22 to ubuntu-24 and the default python version has changed from 3.10 to 3.12. See https://github.com/actions/runner-images/issues/10636
For the long run: `make check-default` should be updated to support `3.12`. 
This a workaround for:
```
ModuleNotFoundError: No module named 'lib2to3'
Traceback (most recent call last):
File "/home/runner/work/beats/beats/build/python-env/bin/autopep8", line 8, in <module>
sys.exit(main())
^^^^^^
File "/home/runner/work/beats/beats/build/python-env/lib/python3.12/site-packages/autopep8.py", line 4474, in main
results = fix_multiple_files(args.files, args, sys.stdout)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/runner/work/beats/beats/build/python-env/lib/python3.12/site-packages/autopep8.py", …
```
=> github-actions: python 3.12 is the default when using ubuntu-latest

CHANGELOG.asciidoc, CHANGELOG.next.asciidoc, x-pack/filebeat/_meta/config/filebeat.inputs.reference.xpack.yml.tmpl, x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc, x-pack/filebeat/filebeat.reference.yml, x-pack/filebeat/input/awss3/config.go, x-pack/filebeat/input/awss3/config_test.go, x-pack/filebeat/input/awss3/input_benchmark_test.go, x-pack/filebeat/input/awss3/s3_filters.go, x-pack/filebeat/input/awss3/s3_filters_test.go, x-pack/filebeat/input/awss3/s3_input.go, x-pack/filebeat/input/awss3/s3_test.go
Introduce `ignore_older` and `start_timestamp` properties to AWS S3 input. This is a follow-up for [#41694](https://github.com/elastic/beats/pull/41694).
The configurations introduced here act as input object filters. If the object fails to match derived filters, the entries will be cleaned up from the registry, reducing filebeat memory consumption.
Introduced configurations are, 
- ignore_older : Accepts a time duration in which entries are accepted for processing
- start_timestamp: A timestamp from which objects are accepted for processing
For both inputs, the object's last modified timestamp is taken into comparison. See **Use cases** section for further explanation
None as defaults are disabled. However, when configurations introduced here are used, the following can have an impact on …
=> [aws] [s3] Introduce ignore_older & start_timestamp for S3 input allowing better registry cleanups

libbeat/docs/shared-ssl-config.asciidoc
Remove TLSv1.0 from supported_protocols list and set defaults to TLSv1.2, TLSv1.3 for the 9.x release docs.
- ~~My code follows the style guidelines of this project~~
- #41595
=> Remove TLSv1.0 from supported protocols

libbeat/docs/shared-beats-attributes.asciidoc, libbeat/docs/shared-docker.asciidoc
This updates the [Run [Beatname] in Docker](http://localhost:8000/guide/running-on-docker.html) pages to mention the availability of the Wolfi images, with a link to the Blog article about why they were introduced.
**Note to reviewers:** Please confirm that the path is correct for the Wolfi image. I've just assumed based on what we have in the Elastic Agent docs.
Rel: https://github.com/elastic/ingest-docs/issues/1608#issuecomment-2577852013
Associated Elastic Agent PR: https://github.com/elastic/ingest-docs/pull/1610
---
=> Add description of Wolfi container install image

CHANGELOG-developer.next.asciidoc, x-pack/metricbeat/module/iis/application_pool/reader.go
The error occurs [initAppPools](https://github.com/elastic/beats/blob/main/x-pack/metricbeat/module/iis/application_pool/reader.go#L104) > calls [GetCounterPaths](https://github.com/elastic/beats/blob/main/x-pack/metricbeat/module/iis/application_pool/reader.go#L117) > calls [ExpandWildCardPath](https://github.com/elastic/beats/blob/main/metricbeat/helper/windows/pdh/pdh_query_windows.go#L113) > calls [PdhExpandWildCardPath](https://github.com/elastic/beats/blob/main/metricbeat/helper/windows/pdh/pdh_query_windows.go#L227) which returns no data and no error > `PdhExpandWildCardPath`returns `PdhErrno(syscall.ERROR_NOT_FOUND)` error [here](https://github.com/elastic/beats/blob/main/metricbeat/helper/windows/pdh/pdh_query_windows.go#L249) > the error returns all the way back to …
=> [x-pack][metricbeat][iis] improve error handling on pdh counters in application_pool data stream

.buildkite/packaging.pipeline.yml, .buildkite/scripts/dra.sh, .buildkite/scripts/packaging/prepare-release-manager.sh
This commits adds support for an optional $VERSION_QUALIFIER env var/build option in the packaging pipeline to allow building prerelease artifacts from *staging*.
Tested a staging build using this PR with `VERSION_QUALIFIER="alpha1"` (also passed `DRA_BRANCH="main"` as this PR is based on main and we'd normally have tested alpha1 on main until 9.0 is cut): https://buildkite.com/elastic/beats-packaging-pipeline/builds/2138#01946b34-0e11-40b0-9610-cc647d2bea1e
Also tested a snapshot build (using `DRA_BRANCH="main"` and `RUN_SNAPSHOT="true"`) to ensure that an empty `--qualifier` option works as advertised by the release manager: https://buildkite.com/elastic/beats-packaging-pipeline/builds/2143
https://github.com/elastic/ingest-dev/issues/4857
=> Allow use of version qualifier for staging artifacts

.buildkite/packaging.pipeline.yml
This fixes a small bug related to #42304 (example failure [link](https://buildkite.com/elastic/beats-packaging-pipeline/builds/2149#01946f97-683d-411c-9427-60006fc72faa)).
When we (manually) trigger prerelease builds (by setting VERSION_QUALIFIER="...") we only want them to trigger staging builds and skip snapshot builds.
https://github.com/elastic/ingest-dev/issues/4857
=> Don't run packaging snapshot with prereleases

x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
```
Document how compressed objects are handled by the aws-s3 input.
```
=> x-pack/filebeat/docs - document gzip S3 object handling

filebeat/docs/inputs/input-journald.asciidoc
See title
Build Filebeat docs:
1. Clone Beats and [Docs](https://github.com/elastic/docs)
2. Checkout this PR/Branch on Beats
3. Build the docs:
```
export GIT_HOME=<path to the folder where Beats and Docs have been cloned>
$GIT_HOME/docs/build_docs --respect_edit_url_overrides --doc $GIT_HOME/beats/filebeat/docs/index.asciidoc --resource=$GIT_HOME/beats/x-pack/filebeat/docs --chunk 1 --open
```
4. Open http://localhost:8000/guide/filebeat-input-journald.html
5. Validate the parsers documentation.
- Closes https://github.com/elastic/beats/issues/40478
~~## Logs~~
=> Add parsers documentation to Journald docs

.pre-commit-config.yaml
I've just found that the conflicts in https://github.com/elastic/beats/pull/42376 were not detected as part of the `pre-commit` hook. Hence I accidentally merged the original PR in `8.x`.
https://github.com/pre-commit/pre-commit-hooks#check-merge-conflict supports for `--assume-in-merge` - Allows running the hook when there is no ongoing merge operation.
```bash
$ gh pr checkout 42376
$ git cherry-pick 1d22316c2172a5f65dd0440946b27840b2c595a9
$ pre-commit install
$ pre-commit run --files .github/workflows/updatecli-compose.yml --verbose
check for merge conflicts................................................Failed
- hook id: check-merge-conflict
- duration: 0.07s
- exit code: 1
.github/workflows/updatecli-compose.yml:41: Merge conflict string '<<<<<<<' found …
```
=> pre-commit: detect conflict if no ongoing merge operation

CHANGELOG.next.asciidoc, x-pack/osquerybeat/beater/osquerybeat.go, x-pack/osquerybeat/internal/osqdcli/client.go
Increasing the osquery max query timeout will allow users to run longer running queries that can be done with osquery.
Although osquery only supports running one query at a time, and this may block others from running, it will allow users to decide for themselves if they want to run long-running queries, and opens new use-cases.
<!-- Recommended
Link related issues below. Insert the issue link or reference after the word "Closes" if merging this should automatically close it.
- Relates https://github.com/elastic/kibana/pull/207276
- Relates …
=> Increase Osquery max timeout limit to 24 hours

CHANGELOG.next.asciidoc, libbeat/cmd/instance/beat.go
fixes setting unique per beat namespace for non beat beat receivers.  This only impacted the filebeat benchmark input since it is the only thing currently using this unique namesapce.
See #42288
- Closes #42288
=> fix setting namespace for non beat receivers

libbeat/outputs/elasticsearch/config_presets.go, libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc
Add backoff settings to the `scale` performance preset, as described in https://github.com/elastic/elastic-agent/issues/4469, to reduce load on large deployments.
If users have already set an output backoff while using the scale preset, this will override it (and possibly reduce the effective backoff).
However, this reduces cluster overload in the more common case that users have default backoff settings.
- Closes https://github.com/elastic/elastic-agent/issues/4469
=> Prevent 'thundering herd' issue with the scale preset

CHANGELOG.next.asciidoc, libbeat/outputs/kafka/client.go, libbeat/tests/integration/kafka_test.go
When there is an authorisation error in the Kafka output, the events are dropped and an error message is logged.
Run the tests added by this PR:
```
mage buildSystemTestBinary
go test -tags integration -run=TestAuthorisationErrors -v ./tests/integration
```
If you want to run any Beat yourself, you can modify the test so it only starts the mock and waits, then configure a Beat to connect to it.
- Closes #42343
~~## Logs~~
=> Handle authorization errors in Kafka output

filebeat/registrar/registrar.go, libbeat/common/cleanup/cleanup.go, libbeat/common/schema/schema_test.go, libbeat/statestore/error.go, libbeat/statestore/internal/storecompliance/reg.go, libbeat/statestore/mock_test.go, libbeat/statestore/storetest/storetest.go
In https://github.com/elastic/beats/pull/41446, we are getting some unrelated golangci-lint errors from files that are touched by the PR but in different places. Instead of ignoring the failing CI, it's equally easy to fix them here.
=> Fix some golangci-lint errors

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-cel.asciidoc, x-pack/filebeat/docs/inputs/input-entity-analytics.asciidoc, x-pack/filebeat/docs/inputs/input-http-endpoint.asciidoc, x-pack/filebeat/docs/inputs/input-httpjson.asciidoc, x-pack/filebeat/input/cel/input.go, x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/graph/graph.go, x-pack/filebeat/input/entityanalytics/provider/jamf/jamf.go, x-pack/filebeat/input/entityanalytics/provider/okta/okta.go, x-pack/filebeat/input/httpjson/input.go
```
x-pack/filebeat/input: Fix truncation of bodies in request tracing
When logging request traces, truncate the request/response body to 10%
of the maximum log file size.
Previously, bodies were truncated to the maximum file size, less 10kB.
10kB is a reasonable number for the other trace details, but space is
also required for encoding the body data as a JSON string value.
One example JSON body was 15% larger after encoding, but the 10kB
margin is 1% or less of the total limit. A body approaching the size
limit would typically generate a log entry that exceeded the limit.
Truncating large log entries to fit the file size limit means there may
only be one such entry per file. By truncating body data to 10% of the
file limit, we can expect to see entries for several request/response
pairs …
```
=> x-pack/filebeat/input: Fix truncation of bodies in request tracing

.buildkite/x-pack/pipeline.xpack.metricbeat.yml, NOTICE.txt, go.mod, go.sum
Relates https://github.com/elastic/beats/pull/42358
Update dbadger-io to v4.4.0 in branch 8.17 to match `main` and `8.x`.
To test this PR, due the problem described in https://github.com/elastic/beats/issues/42446, a prerequisite is VM images bundled with the [module pre-downloaded](https://github.com/elastic/ci-agent-images/pull/1187). Example successful run: https://buildkite.com/elastic/beats/builds/18167 (particularly the [x-pack/metricbeat Go IntegTests](https://buildkite.com/elastic/beats-xpack-metricbeat/builds/10972#0194ad3d-b09f-43e3-bd63-eb2e05cd9264/149-618))
- https://github.com/elastic/beats/issues/42446
```
>> go test: Integration-cloudfoundry Test Passed
go: downloading gotest.tools/gotestsum v1.7.0
go: downloading github.com/fatih/color v1.16.0
go: downloading …
```
=> Upgrade dbadger-io to v4.4.0

filebeat/docs/inputs/input-common-options.asciidoc, libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc
Document that the ingest pipeline ID from Elasticsearch defined in the input or output configuration is always lowercased, thus the ingest pipeline in Elasticsearch can only use lowercase names.
1. Clone the [docs](https://github.com/elastic/docs) repository
2. Make sure `beats` and `docs` have the same parent folder
3. Define `$GIT_HOME` as the parent folder from `beats` and `docs`
4. Build the docs, a browser window will open with the rendered docs
```
$GIT_HOME/docs/build_docs --respect_edit_url_overrides --doc $GIT_HOME/beats/filebeat/docs/index.asciidoc --resource=$GIT_HOME/beats/x-pack/filebeat/docs --chunk 1 --open
```
5. Validate the changes in http://localhost:8000/guide/elasticsearch-output.html and some inputs like …
=> Document that `pipeline` needs to be lowercase

libbeat/outputs/otelconsumer/otelconsumer.go, libbeat/outputs/otelconsumer/otelconsumer_test.go
This PR removes the `@metadata` field from plog.Logs. This is an internal field part of the beats event and should not be exposed. While at it, adjust the `@timestamp` field to have the same format as an event ingested by filebeat.
- Closes https://github.com/elastic/ingest-dev/issues/4736
=> otelconsumer: remove metadata and adjust timestamp format

CHANGELOG.next.asciidoc, filebeat/input/journald/environment_test.go, filebeat/input/journald/input.go, filebeat/input/journald/input_test.go, filebeat/input/v2/input.go
This commit adds the status reporting for the Journald input. It also adds a debug log to the `UpdateStatus` function from `v2.Context`.
1. Build the Elastic-Agent with Beats from this PR or build Agent beat and replace its binary in a existing Elastic-Agent installation
2. Create a policy with "Custom Journald logs" or add the integration to an existing policy
3. Set the log level to debug
2. Deploy/Restart the Elastic-Agent
3. Look for the debug messages from the logger `input.journald`:
- `updating status, status: 'Starting', message: 'Starting'`
- `updating status, status: 'Running', message: 'Running'`
4. Ensure the Journald integration for your Elastic-Agent shows the status `Healthy`
- Closes #39791
~~## …
=> Add status reporting for Journald input

libbeat/outputs/kafka/config.go
Wire in Kafka metrics so that we have request latency as well as incoming and outgoing bytes.
=> Wire in Kafka read and write metrics

CHANGELOG.next.asciidoc, x-pack/filebeat/input/entityanalytics/provider/okta/okta.go, x-pack/filebeat/input/entityanalytics/provider/okta/okta_test.go
```
.../input/entityanalytics/provider/okta: Publish events progressively
Instead of waiting for a full sync (which may take hours) to finish
before publishing anything, we now publish data as it is received, so
that users have immediate feedback.
Incremental updates are also published more frequently: page by page
instead of at the end of the pagination sequence.
For the full sync, the previous behavior of adding everything to the
store and publishing it at the end would theoretically de-duplicate
repeated items. However, within a pagination sequence we use opaque
cursors from the API that should avoid overlap between pages. Whether an
item modified after an earlier page in a sequence can appear again in a
later page of the same sequence depends on the API's implementation.
Incremental …
```
=> .../input/entityanalytics/provider/okta: Publish events progressively

CHANGELOG.next.asciidoc, x-pack/filebeat/docs/inputs/input-httpjson.asciidoc, x-pack/filebeat/input/httpjson/input.go, x-pack/filebeat/input/httpjson/metrics.go, x-pack/filebeat/input/httpjson/request.go, x-pack/filebeat/input/httpjson/request_test.go
This is intended to match the events and batches published by the CEL input, but there is no concept of batches in HTTPJSON, the nearest being paging.
- Closes #42340
=> x-pack/filebeat/input/httpjson: add metrics for number of events and pages published

docs/devguide/create-module.asciidoc
```
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/devguide/7.7/creating-metricbeat-module.html contains broken links to:
--
```
=> [DOCS] [7.7] Removes link to master

docs/devguide/create-module.asciidoc
```
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/devguide/7.6/creating-metricbeat-module.html contains broken links to:
--
```
=> [DOCS] [7.6] Removes link to master

docs/devguide/create-module.asciidoc
```
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/devguide/7.5/creating-metricbeat-module.html contains broken links to:
--
```
=> [DOCS] [7.5] Removes link to master

docs/devguide/create-module.asciidoc
```
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/devguide/7.4/creating-metricbeat-module.html contains broken links to:
--
```
=> [DOCS] [7.4] Removes link to master

docs/devguide/create-module.asciidoc
```
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/devguide/7.3/creating-metricbeat-module.html contains broken links to:
--
```
=> [DOCS] [7.3] Removes link to master

x-pack/filebeat/fbreceiver/receiver.go, x-pack/metricbeat/mbreceiver/receiver.go
Wait for the beat to exit during shutdown of beats receivers.
According to the otel component interface, Shutdown should wait for global resources to be freed. In particular, Shutdown returning means that the collector may create and start another component with the same name, which in case of beats receivers leads to a panic due to registry conflicts.
- Relates https://github.com/elastic/elastic-agent/pull/6697
=> Wait for the beat to exit during shutdown of beats receivers

filebeat/beater/filebeat.go
=> filebeat/beater: improve StateStore godoc

CHANGELOG.next.asciidoc, x-pack/filebeat/input/entityanalytics/provider/activedirectory/activedirectory.go
```
x-pack/filebeat/input/entityanalytics/provider/activedirectory: fix use before init bug
The transaction tracker was not being initialised until after the first
call to publishMarker in runFullSync, resulting in a nil pointer
deference when the the tracker Add method is called.
```
-
=> x-pack/filebeat/input/entityanalytics/provider/activedirectory: fix use before init bug

libbeat/beat/info.go, libbeat/cmd/instance/beat.go, libbeat/publisher/processing/default.go, x-pack/filebeat/fbreceiver/factory.go, x-pack/filebeat/fbreceiver/receiver_test.go, x-pack/metricbeat/mbreceiver/factory.go
Currently default processors are only applied under fleet management. Enable default processors for beats when running under OTel receiver mode.
- Fixes https://github.com/elastic/beats/issues/42631
=> fix(otel): ensure default processors are applied in fbreceiver

libbeat/outputs/otelconsumer/otelconsumer.go, libbeat/outputs/otelconsumer/otelconsumer_test.go
The log record attributes added on otelconsumer should be flattened keys (and not nested map structure) for dynamic indexing on ES exporter to work correctly. This is a fix for it
- Fixes https://github.com/elastic/beats/issues/42623
=> [otelconsumer] Add log record attributes as flattened keys

libbeat/docs/metrics-in-logs.asciidoc
Fixes a table column formatting glitch in the metric descriptions table in [Understand metrics in Filebeat logs](https://www.elastic.co/guide/en/beats/filebeat/current/understand-filebeat-logs.html). See screenshot for what it looked like before.
Also uncovers the description of the `.output.write.latency` metric, which was previously hidden due to the formatting glitch.
=> docs: fix table formatting in Filebeat metrics descriptions

libbeat/otelbeat/otelmap/otelmap.go, libbeat/otelbeat/otelmap/otelmap_test.go, libbeat/outputs/otelconsumer/otelconsumer_test.go
Documents ingested in otel mode had discrepancy in `Body.timestamp` and `timestamp` fields. As can be seen here 
This PR fixes this by converting timestamp to UTC format in otelconsumer before sending it to ES exporter.
=> [otelconsumer] Fix timestamp discrepancy for documents ingested in otel mode

CHANGELOG.next.asciidoc, x-pack/filebeat/input/http_endpoint/handler_test.go, x-pack/filebeat/input/http_endpoint/validate.go
```
The HMAC signature validation code had an optimization intended to
return early when the configured HMAC header was not present in the 
request. However, it was checking the wrong variable for emptiness,
which effectively skipped this check. If a request included an empty
HMAC header, the HMAC signature check would still proceed and fail due 
to the missing or incorrect signature.
This issue has been corrected by this commit. The code now returns
`errMissingHMACHeader` only when the header is truly absent (not present
rather than having an empty value). Additionally, before decoding the 
signature, a check for an empty value is added to return a helpful error.
```
The problematic code is this section where on L67 it checks the value of `v.hmacHeader` which is from config instead of …
=> fix(x-pack/filebeat/input/http_endpoint): hmac header validation

CHANGELOG.next.asciidoc, metricbeat/helper/http.go, metricbeat/helper/http_test.go, metricbeat/module/kubernetes/apiserver/metricset.go, metricbeat/module/kubernetes/controllermanager/controllermanager.go, metricbeat/module/kubernetes/kubernetes.go, metricbeat/module/kubernetes/scheduler/scheduler.go
[metricbeat] Refactor kubernetes bearer token authentication
Instead of doing retries on 401 errors, use a mechanism from client-go which simply reloads the token periodically in the background.
Also, don't stop logging errors after the first 401. These errors, if present, need to be addressed by the cluster operator, so we should make them more prominent.
We have a report of the current mechanism running into race conditions in some OpenShift clusters. The exact root cause is unknown, but this change should address it.
After this change, we will continue logging errors when we get a 401 from the API Server of kubelet, whereas up until now we'd only log the first one.
1. Build a local metricbeat docker image using `mage package`.
2. Start a kind cluster.
3. Upload the docker image to the …
=> [metricbeat] Refactor kubernetes bearer token authentication

filebeat/testing/integration/sample_test.go
skip flaky test: TestFilebeat/Filebeat_crashes_due_to_incorrect_config
N/A
run the test `TestFilebeat/Filebeat_crashes_due_to_incorrect_config`. It should be skipped
```
❯ cd filebeat
❯ go test -v -tags integration -run TestFilebeat/Filebeat_crashes_due_to_incorrect_config ./testing/integration/
=== RUN   TestFilebeat
run_beat.go:238: ensuring the filebeat binary is available... …
```
=> Skip flaky test TestFilebeat/Filebeat_crashes_due_to_incorrect_config

NOTICE.txt, filebeat/channel/runner_mock_test.go, go.mod, go.sum
Testify 1.10 fixed NotSame which exposes a bug in our filebeat tests: https://github.com/stretchr/testify/commit/118fb8346630c192421c8914848381af9d4412a7
Remove the structure comparison, as they will never be the same address. Require that the maps they hold have a different backing.
- [] ~~I have made corresponding changes to the documentation~~
https://github.com/stretchr/testify/commit/118fb8346630c192421c8914848381af9d4412a7
https://github.com/elastic/beats/pull/34870#issuecomment-2664864487
https://github.com/elastic/beats/pull/42032#issuecomment-2664877958
=> Update testify and fix filebeat tests

libbeat/otelbeat/beatconverter/beatconverter_test.go, libbeat/otelbeat/oteltranslate/outputs/elasticsearch/config_otel.go, libbeat/otelbeat/oteltranslate/outputs/elasticsearch/config_otel_test.go, x-pack/filebeat/tests/integration/otel_test.go
This adds tests to compare document ingested  by filebeat in normal vs otel mode.
```
mage docker:composeUp
go test -run TestFilebeatOTelE2E -tags integration ./tests/integration -v
```
- Closes https://github.com/elastic/ingest-dev/issues/4595
=> [filebeat] Compare documents ingested by fb in normal vs otel mode

.buildkite/auditbeat/auditbeat-pipeline.yml, .buildkite/filebeat/filebeat-pipeline.yml, .buildkite/heartbeat/heartbeat-pipeline.yml, .buildkite/metricbeat/pipeline.yml, .buildkite/packetbeat/pipeline.packetbeat.yml, .buildkite/scripts/packaging/packaging.sh, .buildkite/winlogbeat/pipeline.winlogbeat.yml, .buildkite/x-pack/pipeline.xpack.agentbeat.yml, .buildkite/x-pack/pipeline.xpack.auditbeat.yml, .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml, .buildkite/x-pack/pipeline.xpack.filebeat.yml, .buildkite/x-pack/pipeline.xpack.heartbeat.yml, .buildkite/x-pack/pipeline.xpack.metricbeat.yml, .buildkite/x-pack/pipeline.xpack.osquerybeat.yml, .buildkite/x-pack/pipeline.xpack.packetbeat.yml, .buildkite/x-pack/pipeline.xpack.winlogbeat.yml
Added binfmt docker to run before packaging for multiarch builds to avoid the exec format errors when attempting to build arm64 inside arm64 workers.
- Relates: https://github.com/elastic/golang-crossbuild/pull/507
Buildkite builds: https://buildkite.com/elastic/beats/builds?branch=elastic%3Aupdate-packaging
=> Added binfmt to beats packaging step

CHANGELOG.next.asciidoc, winlogbeat/eventlog/errors_unix.go, winlogbeat/eventlog/errors_windows.go, winlogbeat/eventlog/runner.go
- Retry if EOF errors are found during eventlog reads.
- Add exponential limited backoff retrials when handling recoverable errors.
- Relates #35662
- Closes #37238
=> {filebeat,winlogbeat} Improve error handling when opening and reading event logs

CHANGELOG.next.asciidoc, x-pack/auditbeat/processors/sessionmd/add_session_metadata.go, x-pack/auditbeat/processors/sessionmd/add_session_metadata_test.go, x-pack/auditbeat/processors/sessionmd/provider/kerneltracingprovider/kerneltracingprovider_linux.go, x-pack/auditbeat/processors/sessionmd/provider/kerneltracingprovider/metrics.go
This does two things:
- Adds quark's stats objects to auditbeat's metrics reporter
- Fixes a bug where the kernel_tracing provider for add_session_metadata would hold a mutex for too long, leading to dropped events within quark
=> Add metrics for kernel_tracing provider, fix mutex issue

x-pack/filebeat/tests/integration/otel_test.go
The TestFilebeatOTelE2E test sometimes fails in CI. This test is designed to ensure that a document ingested by Filebeat and fbreceiver does not have any meaningful differences. Some fields are expected to change, such as agent.id, log.file.path, and at timestamp.
The test explicitly fails if any of the ignored fields match in both documents, as it assumes these fields should not be ignored. In the case of at timestamp, depending on how fast indexing works, it may sometimes match and sometimes differ, introducing flakiness to the test.
This check seems to do more harm than good and I have already removed it from a similar Elastic Agent test in https://github.com/elastic/elastic-agent/pull/6819.
Example of a build failure caused by this: …
=> fix(tests): ensure TestFilebeatOTelE2E does not fail if timestamps are equal

metricbeat/helper/elastic/elastic.go, metricbeat/helper/elastic/elastic_test.go
This PR updates the Stack Monitoring data stream names to match the [new index patterns](https://github.com/elastic/elasticsearch/issues/123102) for release 9 similar to what was done between 7 and 8 (PR #29493)
If this change is not made, the monitoring data collected by Metricbeat will not end up in the right data streams.
1. Run the latest 9 version of any Elastic Stack components (Elasticsearch, Kibana, Logstash, Beats) and monitor them using the appropriate Metricbeat module (`elasticsearch`, `kibana`, `logstash`, `beats`) with `xpack.enabled: true` mode
2. Make sure that the monitoring data ends up in a data stream called `.monitoring-<product>-9-mb`
For monitoring Elasticsearch, the following configuration can be used.
```
- module: elasticsearch
xpack.enabled: true
period: 10s …
```
=> Update Stack Monitoring data stream to 9

CHANGELOG.next.asciidoc, metricbeat/module/elasticsearch/_meta/README.md, metricbeat/module/elasticsearch/index_summary/index_summary.go
This PR fixes the `index_summary` metric set of the `elasticsearch` module and makes sure to only request cluster-level indexing stats (i.e. primaries and total) and not index-level stats. Since the latter are not needed, the module should not request them as that creates unnecessary load on the master node and consumes CPU and network resources for nothing.
There won't be any disruption as currently the `index_summary` metric set requests more info than needed. This PR is simply restricts the API call to only what is needed.
1. Run Metricbeat with the `elasticsearch` module and the `index_summary` metric set enabled
2. 
Fixes https://github.com/elastic/beats/issues/36019
=> [Stack Monitoring] Only fetch cluster-level index stats summary

filebeat/tests/integration/translate_ldap_attribute_test.go
=> Skip Flaky test TestTranslateGUIDWithLDAP

.github/workflows/pre-commit.yml
=> github-actions: enable 9 branches for the pre-commit

CHANGELOG.next.asciidoc, x-pack/filebeat/input/entityanalytics/provider/activedirectory/internal/activedirectory/activedirectory.go
```
x-pack/filebeat/input/entityanalytics/provider/activedirectory: do not consider computers to be users
Active Directory classifies computers in the set of users, so
(objectClass=user) is not an adequately tight query to only return human
users. Adding the (objectCategory=person) condition resolves this.
```
> [!NOTE]
> The query used here has been checked using the command line in the reporter's system.
- For elastic/integrations#11818
=> x-pack/filebeat/input/entityanalytics/provider/activedirectory: do not consider computers to be users

.buildkite/filebeat/filebeat-pipeline.yml, .buildkite/metricbeat/pipeline.yml
Based on [Support Matrix](https://www.elastic.co/support/matrix) Windows 2025 should be included in 8.17 for `filebeat` and `metricbeat` only. Other active branches do not have Windows 2025 support.
Updated Extended Windows unit test group with additional step per beats mentioned above.
- Relates: https://github.com/elastic/ingest-dev/issues/4494
Buildkite builds:
-- filebeat: https://buildkite.com/elastic/filebeat/builds/14161#0195618f-0cb5-4817-aaea-b40d90e895d2
-- metricbeat: https://buildkite.com/elastic/beats-metricbeat/builds/14661#0195618f-0de9-467b-ae6e-ec7ffc2f3ee8
=> Add Windows 2025 for unit test steps

metricbeat/helper/elastic/elastic.go, metricbeat/helper/elastic/elastic_test.go
This PR reverts https://github.com/elastic/beats/pull/42823/
On an afterthought, there are (too) many things that can go wrong on the upgrade path from 8 to 9 (both in ECH and ESM). Given the days of the `.monitoring` indices are counted, we'll keep it low friction and stay on `-8-`.
Sorry for the noise
=> [REVERT] Update Stack Monitoring data stream to 9

.buildkite/packaging.pipeline.yml, dev-tools/mage/settings.go
This commit is the counterpart of
https://github.com/elastic/beats/pull/43019 for the DRA packaging pipeline.
It ensures that arm64 packages get built without qemu emulation on dedicated arm64 workers.
Successful BK link:
https://buildkite.com/elastic/beats-packaging-pipeline/builds/2656#01956655-e341-4ec5-a3a2-859c4fac28a8
and another one using the latest commit: https://buildkite.com/elastic/beats-packaging-pipeline/builds/2664
where both staging + snapshot got triggered using `DRA_DRY_RUN=false`
Additionally, I compared the DRA job output for snapshot artifacts from the above triggered job , against the latest successful [DRA build on main](https://buildkite.com/elastic/beats-packaging-pipeline/builds/2626#01956241-0b5f-4a9f-b6da-1516f27f0d19) and the results were identical.
Closes …
=> Don't package arm64 on amd64 workers

x-pack/metricbeat/module/mssql/performance/performance_integration_test.go, x-pack/metricbeat/module/mssql/transaction_log/transaction_log_integration_test.go
Disable the broken mssql integration tests reported in https://github.com/elastic/beats/issues/43123.
=> Disable broken mssql integration tests

x-pack/filebeat/input/cel/input_test.go
See title.
Issue identified by @AndersonQ, thanks.
-
=> x-pack/filebeat/input/cel: fix incorrect test logic

x-pack/filebeat/input/awss3/sqs_test.go
Fixes flakiness of SQS unit test. Fix focus on accepting `AnyTimes()` to the subsequent `ReceiveMessage` mock. The flakiness originated from `Times(1)` contract which may or may not happen due to the concurrency used in the processing logic. 
In short,
- `ReceiveMessage` reads messages from sqs api
- Messages read are pushed to workers that run concurrently 
- Reader continues to read more messages while workers work
-  Worker deletes the sqs queue entry upon full processing of the message
- This deletion in test is used to invoke context completion 
The flakiness came from reader continuing to read and cancellation of the context, where if context cancellation happens before next message, we end up with missing calls to the mock. 
Closes #41458
=> chore: fix flakiness and add comments to explain testing logic

metricbeat/module/apache/status/status_test.go
```
make the test httpserver wait 'timeout' before writing the response
```
None
the test should always succeed
```
go test -count 100 -run TestFetchTimeout ./metricbeat/module/apache/status
```
- Closes #43158
=> fix flaky test metricbeat/module/apache/status TestFetchTimeout

x-pack/filebeat/tests/system/test_http_endpoint.py
Address [flakiness](https://github.com/elastic/beats/issues/30028) [issues](https://github.com/elastic/beats/issues/43098) in `test_http_endpoint_missing_auth_value`.
`test_http_endpoint_missing_auth_value` involves providing an invalid configuration to the `http_endpoint` input and verifying that the right error message appears in the logs. Logs on failed runs show that (because there are no valid inputs) sometimes the beat shuts down too quickly, before the input's log message about the failure appears in the log files, leading the test to time out waiting for a message on unchanging log files for a (correctly) shut down beat.
This PR addresses that by adding a second (ignored) input to the test configuration, so the beat will not shut down until the test is over. This gives the desired …
=> Fix flaky http_endpoint test

.buildkite/packaging.pipeline.yml
This commit removes x-pack/functionbeat from the DRA process in the 8.x branch, which was missed from #43090
It fixes the currently broken 8.x DRA which is still attempting to build x-pack/functionbeat after the corresponding
scripts got removed via #43090
Can only be tested in CI: [link](https://buildkite.com/elastic/beats-packaging-pipeline/builds/2784) (only available to Elastic internal)
- Relates #43090
=> Remove functionbeat from DRA in 8x branch

.buildkite/auditbeat/auditbeat-pipeline.yml, .buildkite/filebeat/filebeat-pipeline.yml, .buildkite/heartbeat/heartbeat-pipeline.yml, .buildkite/metricbeat/pipeline.yml, .buildkite/packetbeat/pipeline.packetbeat.yml, .buildkite/winlogbeat/pipeline.winlogbeat.yml, .buildkite/x-pack/pipeline.xpack.agentbeat.yml, .buildkite/x-pack/pipeline.xpack.auditbeat.yml, .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml, .buildkite/x-pack/pipeline.xpack.filebeat.yml, .buildkite/x-pack/pipeline.xpack.heartbeat.yml, .buildkite/x-pack/pipeline.xpack.metricbeat.yml, .buildkite/x-pack/pipeline.xpack.osquerybeat.yml, .buildkite/x-pack/pipeline.xpack.packetbeat.yml, .buildkite/x-pack/pipeline.xpack.winlogbeat.yml
It ensures that arm64 packages get built without qemu emulation on dedicated arm64 workers.
https://github.com/elastic/beats/pull/43026 fixed the DRA pipeline, but the CI packaging steps in the BK beats pipelines was not changed.
This should help with some failures we are seeing like:
- https://buildkite.com/elastic/beats-packetbeat/builds/12722#019581e8-89ba-4872-9a94-9314fa2b89cf
In the CI itself, let's see how it goes
In addition, I cherry-picked the changes and updated https://github.com/elastic/beats/pull/43145, so I expect to see if it works.
-
=> bk(package jobs): Don't package arm64 on amd64 workers

metricbeat/module/vsphere/datastore/datastore_test.go
Skip flaky test from https://github.com/elastic/beats/issues/43252
=> Skip flaky vsphere datastore TestFetchEventContents

CHANGELOG.next.asciidoc, metricbeat/module/elasticsearch/index/data.go
Changed the Elasticsearch module behavior to only pull settings from non-system indices. This avoids a deprecation warning that could flood the logs.
=> Removed system indices from extra metadata pull in Elasticsearch module

libbeat/otelbeat/oteltest/oteltest.go, x-pack/filebeat/fbreceiver/receiver_test.go, x-pack/metricbeat/mbreceiver/receiver_test.go
The CheckReceivers function is designed to start receivers in the same process to assert conditions. This simulated environment should closely resemble the real OTel collector startup.
This PR fixes some inconsistencies in the test environment.
First, when instantiating receivers, the collector first [creates them](https://github.com/open-telemetry/opentelemetry-collector/blob/27ff48958a38992b7812af301967132b1a4006ca/service/internal/graph/graph.go#L292) using the factory and only then [starts each component](https://github.com/open-telemetry/opentelemetry-collector/blob/27ff48958a38992b7812af301967132b1a4006ca/service/internal/graph/graph.go#L403). Previously, we were creating and starting each receiver sequentially, which is incorrect and masked issues with global state when multiple …
=> oteltest: make CheckReceivers environment more similar to the collector

metricbeat/module/system/process/process_test.go
Disable `metricbeat/module/system/process TestFetchDegradeOnPartial` reported in https://github.com/elastic/beats/issues/42809.
Also change the failing `t.Assert` to `t.Require` so that when it does fail, it doesn't fall through to a panic on the next line by accessing the first element of an empty array.
=> [Flaky test] Disable flaky metricbeat process test

CHANGELOG.next.asciidoc, x-pack/filebeat/input/entityanalytics/provider/activedirectory/internal/activedirectory/activedirectory.go
```
x-pack/filebeat/input/entityanalytics/provider/activedirectory: do not convert special values of accountExpires
The accountExpires attribute will be set to 0 or 0x7fff_ffff_ffff_ffff
(9223372036854775807) if the account is set to never expire. Return the raw
int in these cases.
```
* `beats\x-pack\filebeat\input\entityanalytics\provider\activedirectory> go test -v -run Test -log_response`
-
=> x-pack/filebeat/input/entityanalytics/provider/activedirectory: do not convert special values of accountExpires

filebeat/input/v2/loader.go
Remove an `Input` returned from a helper in the Filebeat input loader that is never initialized to a non-nil value
=> [cleanup] Remove confusing always-nil return value

.buildkite/auditbeat/auditbeat-pipeline.yml, .buildkite/filebeat/filebeat-pipeline.yml, .buildkite/heartbeat/heartbeat-pipeline.yml, .buildkite/metricbeat/pipeline.yml, .buildkite/packaging.pipeline.yml, .buildkite/packetbeat/pipeline.packetbeat.yml, .buildkite/winlogbeat/pipeline.winlogbeat.yml, .buildkite/x-pack/pipeline.xpack.agentbeat.yml, .buildkite/x-pack/pipeline.xpack.auditbeat.yml, .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml, .buildkite/x-pack/pipeline.xpack.filebeat.yml, .buildkite/x-pack/pipeline.xpack.heartbeat.yml, .buildkite/x-pack/pipeline.xpack.metricbeat.yml, .buildkite/x-pack/pipeline.xpack.osquerybeat.yml, .buildkite/x-pack/pipeline.xpack.packetbeat.yml, .buildkite/x-pack/pipeline.xpack.winlogbeat.yml
Golang Crossbuild:
- for arm64 let's use the aarch64 host
- for amd64 let's use the amd64 host
We changed partially for aarch64, but darwin/arm64 was not changed.
Uses https://github.com/elastic/golang-crossbuild/pull/533 and https://github.com/elastic/golang-crossbuild/pull/559 (1.24.0)
In the CI:
- https://buildkite.com/elastic/beats-packaging-pipeline/builds/2867
See https://github.com/elastic/beats/pull/43145
Requires https://github.com/elastic/golang-crossbuild/pull/533
=> bk(packaging): use arm64 for darwin/arm64

docs/reference/libbeat/upgrading.md
This updates the Beats "Upgrade" page for v9.0. Changes are based on discussion in this [gdoc draft](https://docs.google.com/document/d/1YXobkcOEbDrcy7kn0f3cRExj0lJXKXMuxiZ17kJji3U/edit?tab=t.0#heading=h.xxnnw4d9xod3).
Please see [docs preview](https://docs-v3-preview.elastic.dev/elastic/beats/pull/43363/reference/libbeat/upgrading).
Closes: https://github.com/elastic/ingest-docs/issues/1732
=> Update Beats 'Upgrade' docs for 9.0

CHANGELOG.next.asciidoc, NOTICE.txt, go.mod, go.sum
Update elastic-agent-system-metrics
Closes https://github.com/elastic/beats/issues/42593
=> bump elastic-agent-system-metrics

metricbeat/module/zookeeper/test_zookeeper.py
Disable the flaky test `metricbeat/module/zookeeper/test_zookeeper`, reported in https://github.com/elastic/beats/issues/43385.
Also add a message to the failing assertions indicating the actual data the tests failed on, so when a failure does happen we can see what caused it.
=> [Flaky test] Disable flaky zookeeper tests

.buildkite/packaging.pipeline.yml, .buildkite/scripts/packaging/packaging.sh, .buildkite/x-pack/pipeline.xpack.agentbeat.yml, .buildkite/x-pack/pipeline.xpack.auditbeat.yml, .buildkite/x-pack/pipeline.xpack.filebeat.yml, .buildkite/x-pack/pipeline.xpack.metricbeat.yml, dev-tools/mage/build.go, dev-tools/mage/crossbuild.go, dev-tools/mage/fips-settings.yaml, dev-tools/mage/pkg.go, dev-tools/mage/pkgspecs.go, dev-tools/mage/pkgtypes.go, dev-tools/mage/settings.go, dev-tools/packaging/package_test.go, dev-tools/packaging/packages.yml, x-pack/agentbeat/dev-tools/packaging/packages.yml, x-pack/agentbeat/magefile.go, x-pack/dockerlogbeat/magefile.go
Implement packaging of FIPS compliant Beats.
With this change the following beats are compiled and packaged in a FIPS compliant fashion when specifying env var `FIPS=true`:
- agentbeat (for details see PR #42913)
- auditbeat
- filebeat
- metricbeat
The FIPS config parameters are controlled by `dev-tools/mage/fips-settings.yaml` config file which allows to:
- define the list of FIPS compliant beat names
- control some compile settings like environment variables and build tags.
The initial configuration of FIPS settings is:
```yaml
beats:
- agentbeat
- auditbeat
- filebeat
- metricbeat
compile:
cgo: true
env:
GOEXPERIMENT: systemcrypto
tags:
- requirefips
platforms:
- linux/amd64
- linux/arm64
```
This compile settings are global for all beats and **apply only when building/packaging with …
=> Package fips beats

libbeat/outputs/logstash/deadlock.go, libbeat/outputs/logstash/deadlock_test.go
Fix a flaky logstash output test for the `deadlockListener`. The old test used live time tickers and occasionally failed because timing on CI machines is highly variable. This PR refactors `deadlockListener` to allow tests to override the current time and the ticker channel, so the test can run deterministically in a single goroutine with no calls to `time.Sleep`.
=> Fix flaky logstash output test

filebeat/tests/system/test_registrar.py, libbeat/tests/system/beat/beat.py
A common pattern in flaky python tests is that they `wait_until` expecting a particular set of values in the output file. When this condition fails, though, there's no way to see what the actual output mismatch was. For example, some tests wait until there is (exactly) one entry in the default output file, but fail because there are actually two. In that case the test times out, but there's no way to see if the two output events were actually a bug, or just an over-constrained test condition. Even if it is a genuine failure, there's no way to know what the extra event is. Many test checks are similar, depending on the output file but not reporting why they failed.
This PR updates the python test failure code to include the default output file along with the beat logs, if one is present. …
=> Add more complete failure logs to python tests

CHANGELOG-developer.next.asciidoc, NOTICE.txt, go.mod, x-pack/filebeat/input/o365audit/auth/auth.go, x-pack/filebeat/input/o365audit/auth/cert.go, x-pack/filebeat/input/o365audit/auth/secret.go, x-pack/filebeat/input/o365audit/config.go, x-pack/filebeat/input/o365audit/contentblob.go, x-pack/filebeat/input/o365audit/input.go, x-pack/filebeat/input/o365audit/listblobs.go, x-pack/filebeat/input/o365audit/poll/poll.go
```
Remove direct dependency on Azure/go-autorest/autorest/adal
Remove direct use of the deprecated autorest/adal, replacing it with
azidentity, as described in the migration guide[1].
Indirect dependencies remain:
- github.com/elastic/beats/v7/x-pack/filebeat/input/o365audit
- github.com/Azure/go-autorest/autorest
- github.com/Azure/go-autorest/autorest/adal
- github.com/elastic/beats/v7/x-pack/filebeat/input/azureeventhub
- github.com/Azure/azure-event-hubs-go/v3/storage
- github.com/Azure/go-autorest/autorest/adal
- github.com/elastic/beats/v7/x-pack/metricbeat/module/azure/app_insights
- github.com/Azure/go-autorest/autorest
- github.com/Azure/go-autorest/autorest/adal
[1]: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/MIGRATION.md
```
- Relates #41463
=> Remove direct dependency on Azure/go-autorest/autorest/adal

CHANGELOG.asciidoc
This removes an entry from the 8.17.2 changelog for a change that didn't make it into that branch. See https://github.com/elastic/beats/pull/42654#issuecomment-2752694456 for details.
=> Remove incorrect entry from 8.17.2 changelog

CHANGELOG.next.asciidoc, docs/reference/filebeat/filebeat-input-aws-s3.md, x-pack/filebeat/input/awss3/config.go, x-pack/filebeat/input/awss3/config_test.go, x-pack/filebeat/input/awss3/sqs_input.go, x-pack/filebeat/input/awss3/sqs_test.go
```
x-pack/filebeat/input/awss3: allow a grace time on shutdown
We may have SQS message requests in flight that are being serviced when
the input's context is cancelled. This allows the user to specify a time
to wait after the context is cancelled before the processing and
publication work is terminated.
The approach is a little blunt; it merely waits for the grace period
after the requester has been stopped to allow for incoming messages to
be processed and published. Ideally, we would finish as soon as the set
of pending requests had been received and published, cut short after the
grace time. However, the current structure of data flow does not lend
itself to sharing that information between parts of the input, so a minimal
change is made.
```
- Closes elastic/integrations#13062
=> x-pack/filebeat/input/awss3: allow a grace time on shutdown

Makefile, magefile.go
```
migrate the 'test' and 'unit' root make targets to mage
- removes the 'test' and 'unit' make targets from the root Makefile.
- adds `unitTest` and `integTest` to the root magefile. They call the respective mage target for each project directory. 
```
- N/A
- apply [this patch](https://github.com/user-attachments/files/19472221/dry-run.patch.txt) so you can "dry-run" the tests.
- run …
=> Migrate the 'test' and 'unit' root make targets to mage

NOTICE.txt, go.mod, go.sum
Bump github.com/golang-jwt/jwt/v5 to v5.2.2 for [CVE-2025-30204](https://github.com/advisories/GHSA-mh63-6h87-95cp). Beats is not directly vulnerable, as neither Beats nor any direct dependency uses the affected function outside of tests.
=> chore: bump github.com/golang-jwt/jwt/v5 to v5.2.2

x-pack/filebeat/input/awss3/sqs_test.go
`TestCancelWithGrace` in `sqs_test.go` has a timer correctness margin of only 5ms. This is much too low for a reliable test, timers are not guaranteed to have that granularity (especially on CI nodes where there are often execution delays). I saw it "failing" a couple times because it expected a duration of 1.0 seconds and instead got 1.006. This PR increases the acceptable margin to 50ms instead of 5.
Closes https://github.com/elastic/beats/issues/43668.
=> [Flaky test] Increase timeout on flaky SQS test

x-pack/agentbeat/cmd/cmd.go, x-pack/agentbeat/cmd/prepare_root_command.go, x-pack/agentbeat/cmd/prepare_root_command_fips.go, x-pack/agentbeat/main.go, x-pack/agentbeat/main_test.go
Refactor `x-pack/agentbeat` to be importable.
This allows the `AgentBeat` command to be imported from Elastic Agent.
None
=> Allow agentbeat to be importable

docs/reference/metricbeat/metricbeat-modules.md
Related to https://github.com/elastic/beats/pull/42663
Fixes the Metricbeat modules overview table. The bad formatting was likely the result of migrating a complex AsciiDoc table to Markdown.
=> [docs] Fix metricbeat modules table

libbeat/publisher/queue/diskqueue/reader_loop.go
An oversight in the reader loop checks the serialization format of an incoming request before confirming that the segment handle is valid. In the special case that an active segment file from the current session is deleted or truncated to zero length before it is read, this can cause a panic (https://github.com/elastic/beats/issues/43617). This PR moves the format read to after the error check.
- Fixes https://github.com/elastic/beats/issues/43617
=> [Disk queue] Don't check the serialization format unless there's a valid handle

docs/docset.yml, docs/release-notes/breaking-changes.md, docs/release-notes/index.md
This adds the Beats Release Notes for 9.0.0. These have been ported over (and converted to Markdown) from:
- The 9.0.0-beta and 9.0.0-rc1 [stack docs](https://github.com/elastic/beats/compare/main...kilfoyle:beats:9.0.0-rn?expand=1)
- The Beats [9.0.0-rc1 changelog PR](https://github.com/elastic/beats/pull/43419)
- The Beats [9.0.0 changelog PR](https://github.com/elastic/beats/pull/43741)
=> Add Beats Release Notes for 9.0.0

libbeat/statestore/store.go
This is expected to change the error message reported when the Set operation fails. I don't expect this to be disruptive to users.
How I tested this:
```console
cd libbeat/statestore && go test -v .
```
=> Fix typo in "store/set" operation name

libbeat/otelbeat/oteltest/oteltest.go, x-pack/filebeat/fbreceiver/receiver_test.go
```
oteltest.CheckReceivers increase timeout
There are test failing, the issue seems to be a too short timeout, so this change relaxes it.
```
- N/A
run the test until you're satisfied
```
go test -count 1000 -timeout=0 -run TestMultipleReceivers ./x-pack/filebeat/fbreceiver
```
- Relates #43832
=> [Flaky Test] oteltest.CheckReceivers increase timeout

metricbeat/docs/modules/docker.asciidoc, metricbeat/module/docker/_meta/docs.asciidoc
Redo of https://github.com/elastic/beats/pull/42303 for 8.18 and 8.17 docs.
=> Clarify support of Podman (8.x docs)

dev-tools/mage/common.go, dev-tools/packaging/package_test.go
Add a FIPS check for FIPS `.deb` package tests.
The check is performed by extracting the `data.tar.gz` from the `.deb` archive and verifying that the binaries are compiled with the correct settings for FIPS compliance.
This PR is a follow-up for PR #43001
- Closes #43359
=> Add FIPS check for .deb artifacts

libbeat/publisher/queue/memqueue/runloop.go, libbeat/publisher/queue/memqueue/runloop_test.go
The memory queue had a bug where if `Close` was called on an already-empty queue, it would mark itself as closing but never cancel the final internal context. The main effect was that `Get` requests to such a queue would still block instead of correctly returning `io.EOF` immediately. This caused some test flakiness, e.g. `TestClient/no_infinite_loop_when_processing_fails` depended on the `io.EOF` return value to end the test, but whether `Close` was called before or after draining the queue depended on goroutine execution order. This PR moves the context cancellation check to the end of the run loop iteration, so it's updated after every state change and not just after event deletions. The accompanying unit test fails without this change.
=> Fix memqueue race condition during shutdown

filebeat/input/filestream/internal/task/group_test.go, filebeat/module/apache/access/test/test-vhost.log-expected.json, filebeat/module/apache/access/test/test.log-expected.json, filebeat/module/apache/access/test/ubuntu-2.2.22.log-expected.json, filebeat/module/iis/access/test/test-x-forward-for-extended.log-expected.json, filebeat/module/iis/access/test/test.log-expected.json, filebeat/module/nginx/access/test/access.log-expected.json, filebeat/module/nginx/access/test/test-with-host.log-expected.json, filebeat/module/nginx/access/test/test.log-expected.json, filebeat/module/nginx/ingress_controller/test/test.log-expected.json, filebeat/tests/system/test_modules.py, libbeat/tests/integration/dashboard_test.go, testing/environments/docker/logstash/pipeline-xpack/default.conf, testing/environments/docker/logstash/pipeline/default.conf, testing/environments/snapshot.yml, x-pack/filebeat/module/aws/cloudtrail/test/console-login-json.log-expected.json, x-pack/filebeat/module/fortinet/firewall/test/utm.log-expected.json, x-pack/filebeat/module/gcp/audit/test/audit-log-entries.json.log-expected.json, x-pack/filebeat/module/o365/audit/test/04-sharepoint.log-expected.json, x-pack/filebeat/module/o365/audit/test/06-sharepointfileop.log-expected.json, x-pack/filebeat/module/o365/audit/test/14-sp-sharing-op.log-expected.json, x-pack/filebeat/module/o365/audit/test/15-azuread-sts-logon.log-expected.json, x-pack/filebeat/module/o365/audit/test/25-ms-teams-groups.log-expected.json, x-pack/filebeat/module/okta/system/test/okta-system-test.json.log-expected.json, x-pack/filebeat/module/sophos/xg/test/firewall.log-expected.json, x-pack/filebeat/module/suricata/eve/test/eve-small.log-expected.json
```
fix filebeat module golden files and update test stack
Elasticsearch introduced a fix on 8.16.2 to its ingest pipeline user_agent processor preventing it to add a `.` at the end of the user agent version.
This change adjusts the golden files relying on the output of this processor
It also updates the elastic stack version for testing
```
- ~~[ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-~~developer.next.asciidoc`.
- N/A
- start the stack
```sh
cd filebeat
mage docker:composeUp
```
- ensure the right stack is being used. Check the ES version is …
=> Fix filebeat module golden files and update elastic stack version for testing

dev-tools/mage/integtest_docker.go
Add the standard golang proxy to the GOPROXY passed to docker-based integration tests. If a module isn't in the cache, it will be fetched from the standard proxy first, and only read directly if that fails.
This is to address errors in this branch like:
`/go/pkg/mod/code.cloudfoundry.org/go-loggregator@v7.4.0+incompatible/rpc/loggregator_v2/syslog.go:9:2: unrecognized import path "code.cloudfoundry.org/rfc5424": parse https://code.cloudfoundry.org/rfc5424?go-get=1: no go-import meta tags ()`
which is caused because `code.cloudfoundry.org` shut down their project hosting site, and their auto-forwarder doesn't include the golang meta tags that go needs to find the real repository. The standard proxy preserves the proper meta tags for relocated projects, avoiding this error.
=> Add better GOPROXY fallback to docker-based tests

filebeat/input/v2/input.go, filebeat/input/v2/input_test.go
The input/v2.NewPipelineClientListener function now checks if pipeline metrics are already registered in the registry. If found, the existing metrics instance is reused instead of creating a new one.
```
filebeat: input/v2: NewPipelineClientListener reuses existing metrics
The input/v2.NewPipelineClientListener function now checks if pipeline
metrics are already registered in the registry. If found, the existing
metrics instance is reused instead of creating a new one.
``` …
=> filebeat: input/v2: NewPipelineClientListener reuses existing metrics

dev-tools/mage/gotest.go, metricbeat/module/kafka/broker/broker_integration_test.go, metricbeat/module/kafka/consumer/consumer_integration_test.go, metricbeat/module/kafka/consumergroup/consumergroup_integration_test.go, metricbeat/module/kafka/partition/partition_integration_test.go, metricbeat/module/kafka/producer/producer_integration_test.go, x-pack/metricbeat/module/sql/query/query_integration_test.go
```
execute Go integration testes sequentially within a beat module
The current abstraction the modules integration tests use adds a lock on the `docker-compose.yml` being used by the tests. Some modules have several packages sharing a single `docker-compose.yml`, what would cause a timeout while the test waited to acquire the lock.
Right now it isn't viable to have each test using a unique docker compose project name as some of the setups bind to host ports, making it impossible to run some docker compose projects in parallel. Also, running several docker compose projects in parallel might overwhelm the CI runners. Therefore, running each Go package within a beats module patches the problem while we find a better solution.
```
- ~~[ ] I have made corresponding changes to the …
=> Execute Go integration tests sequentially within a beat module

.github/workflows/backport-active.yml, .mergify.yml
New way of backporting to active branches using new github action.
No need to support the hardcoded branches in the `.mergify.yml` file anymore.
We use a dynamic approach by fetching https://storage.googleapis.com/artifacts-api/snapshots/branches.json and filtering the branches.
Already enabled in Elastic Agent:
- https://github.com/elastic/elastic-agent/actions/workflows/backport-active.yml
=> mergify: new way of backporting to active branches

x-pack/filebeat/input/netflow/netflow_test.go
```
skip x-pack/filebeat/input/netflow TestNetFlow/ipfix_cisco.reversed
```
- N/A
Run the test, ensure it's skipped:
```
❯ go test -v -run "TestNetFlow/ipfix_cisco.reversed" ./x-pack/filebeat/input/netflow
=== RUN   TestNetFlow
=== RUN   TestNetFlow/ipfix_cisco.reversed
netflow_test.go:99: Flaky on macOS: https://github.com/elastic/beats/issues/43670
--- PASS: TestNetFlow (0.00s)
--- SKIP: TestNetFlow/ipfix_cisco.reversed (0.00s)
PASS
ok …
```
=> [Flaky Test] skip x-pack/filebeat/input/netflow TestNetFlow/ipfix_cisco.reversed

.buildkite/metricbeat/pipeline.yml, metricbeat/magefile.go
Add buildkite step to run unit tests with GODEBUG=fip140=only and FIPS=true in order to use go 1.24's FIPS mechanisms to detect non-compliant code paths for metricbeat.
- ~~I have made corresponding changes to the documentation~~
N/A
=> Add fipsonly test step for metricbeat

.buildkite/auditbeat/auditbeat-pipeline.yml, .buildkite/filebeat/filebeat-pipeline.yml, .buildkite/libbeat/pipeline.libbeat.yml, .buildkite/metricbeat/pipeline.yml, .buildkite/x-pack/pipeline.xpack.auditbeat.yml, .buildkite/x-pack/pipeline.xpack.filebeat.yml, .buildkite/x-pack/pipeline.xpack.libbeat.yml, .buildkite/x-pack/pipeline.xpack.metricbeat.yml
Rename the step in buildkite so it is very clear that tests are ran for files (or libraries) that make use of the requirefips build tag.
=> Rename buildkite test step to avoid confusion

dev-tools/mage/pkg.go, x-pack/agentbeat/magefile.go
This PR renames any occurrences in Beats code, comments, etc. matching `/fips.*compliant/i` to "FIPS-capable".  This is done to avoid giving the inaccurate impression that Beats are FIPS-compliant.
=> Rename FIPS-compliant to FIPS-capable

docs/docset.yml, docs/reference/auditbeat/setup-repositories.md, docs/reference/filebeat/setup-repositories.md, docs/reference/heartbeat/setup-repositories.md, docs/reference/metricbeat/setup-repositories.md, docs/reference/packetbeat/setup-repositories.md
The YUM setup instructions for each of the Beats currently have `9.0` in the Elastic Package Repo path (see [Filebeat](https://www.elastic.co/docs/reference/beats/filebeat/setup-repositories#_yum) for example). This fixes the instructions to have `9.x` instead.
Rel: https://github.com/elastic/beats/pull/43386
Closes: https://github.com/elastic/docs-content/issues/1227
---
=> Update APT and YUM docs with correct artifacts path

libbeat/otelbeat/beatconverter/beatconverter_test.go, libbeat/otelbeat/oteltranslate/outputs/elasticsearch/config_otel.go, libbeat/otelbeat/oteltranslate/outputs/elasticsearch/config_otel_test.go
Beats uses unencoded api key to connect to elasticsearch - whereas es-exporter expects encoded api key. This PR addresses this. 
It also ensures `num_workers` is always >=1.  
Create an api key using using following curl command 
``` sh
curl -u "admin:testing" \
--request PUT 'http://localhost:9200/_security/api_key' \
--header "Content-Type: application/json" \
--data '{
"name": "my-api-key",
"expiration": "1d",
"role_descriptors": {
"role-a": {
"cluster": ["all"],
"indices": [
{
"names": ["logs-*"],
"privileges": ["read"]
}
]
}
},
"metadata": {
"application": "my-application",
"environment": {
"level": 1,
"trusted": true,
"tags": ["dev", "staging"]
}
}
}'
```
Start filebeat otel with unencoded api key and you can observe logs correctly being indexed
=> Use encoded api key on es-exporter config

.buildkite/auditbeat/auditbeat-pipeline.yml, .buildkite/packetbeat/pipeline.packetbeat.yml, .buildkite/x-pack/pipeline.xpack.auditbeat.yml, .buildkite/x-pack/pipeline.xpack.packetbeat.yml
Add Windows server 2025 to auditbeat and packetbeat CI pipelines
=> [ci] Add Windows server 2025 to auditbeat and packetbeat CI pipelines

docs/reference/auditbeat/configure-cloud-id.md, docs/reference/filebeat/configure-cloud-id.md, docs/reference/heartbeat/configure-cloud-id.md, docs/reference/metricbeat/configure-cloud-id.md, docs/reference/packetbeat/configure-cloud-id.md, docs/reference/winlogbeat/configure-cloud-id.md
The similarity of the values might mislead users into thinking that they are interchangeable.
Preview https://docs-v3-preview.elastic.dev/elastic/beats/pull/44053/reference/filebeat/configure-cloud-id#_cloud_auth
=> Add a note that `api_key` and `cloud.auth` are not related

dev-tools/packaging/templates/docker/Dockerfile.tmpl, docs/reference/filebeat/filebeat-input-journald.md, docs/release-notes/index.md
The journald input from Filebeat requires the `journalctl` binary to ingest journal logs, this commit adds it by installing systemd in all Filebeat Docker container images
1. Package Filebeat
```sh
DEV=true SNAPSHOT=true PACKAGES="docker" PLATFORMS=linux/amd64 mage -v package
```
2. Ensure `journalctl` is present in the containers (adjust the image name/tag according to the version you built, oss or not)
```sh
docker run --rm -it --user root --entrypoint "journalctl" docker.elastic.co/beats/filebeat-wolfi:9.1.0-SNAPSHOT --version
docker run --rm -it --user root --entrypoint "journalctl" docker.elastic.co/beats/filebeat-ubi:9.1.0-SNAPSHOT --version
docker run --rm -it --user root --entrypoint "journalctl" …
```
=> Install systemd on Filebeat Docker images

x-pack/filebeat/fbreceiver/factory.go, x-pack/metricbeat/mbreceiver/factory.go, x-pack/metricbeat/mbreceiver/receiver.go, x-pack/metricbeat/mbreceiver/receiver_test.go
Enable internal monitoring for metricbeat receiver.  This is analogous to #42886 which enabled internal monitoring for filebeat receiver
The internal monitoring is configured exactly the same way as beats with the `http` configuration block.
Example:
```yaml
http:
enabled: true
host: unix:///tmp/monitoring.socket
```
No user impact.  Beats receivers are not GA yet.
The `TestNewReceiver` unit test start the monitoring endpoint and makes sure that data can be read from it.
```shell
cd x-pack/metricbeat/mbreceiver
go test .
```
- Relates #42886
- …
=> enable internal http monitoring for metricbeat receiver

dev-tools/packaging/templates/docker/Dockerfile.tmpl, docs/reference/filebeat/filebeat-input-journald.md, docs/release-notes/index.md
Due to the security focus and minimalistic nature of the image, systemd should not be present in the image.
Follow up to https://github.com/elastic/beats/pull/44056
=> Remove systemd from the Wolfi image

libbeat/otelbeat/oteltest/oteltest.go, x-pack/filebeat/fbreceiver/factory.go, x-pack/filebeat/fbreceiver/receiver_test.go, x-pack/metricbeat/mbreceiver/factory.go, x-pack/metricbeat/mbreceiver/receiver_test.go
Previously, default processors were only enabled for fbreceiver. This change ensures mbreceiver also uses the default processors. While at it, unify TestDefaultProcessors and TestNewReceiver for fbreceiver.
- Relates to https://github.com/elastic/beats/issues/42631
=> fix(otel): register default processors for mbreceiver

.buildkite/libbeat/pipeline.libbeat.yml
Remove FIPS indicator from annotation that was added by mistake.
=> Remove FIPS inidicator from annotation

.buildkite/libbeat/pipeline.libbeat.yml
The libbeat unit test pipeline is hitting failures ([example](https://buildkite.com/elastic/beats-libbeat/builds/14977#01969138-60b6-4e11-bf7f-72a2af7720b6/535-537)) on "successful" fips-enabled runs because the buildkite rule uses an overly-specific file pattern to collect test results, giving failure messages like `No files found matching 'libbeat/build/TEST-*-unit.xml'` (because the fips tests have filenames like `libbeat/build/TEST-go-unit-fips-only.xml`). This PR replaces the rules with a more general file pattern.
=> [CI] Fix failing libbeat unit test pipeline

x-pack/filebeat/fbreceiver/receiver_test.go
`fbreceiver.TestMultipleReceivers` created two Filebeat receivers using the same config, which meant they both had the same home directory. This can cause conflicts that prevent a beat from starting, which is likely the cause of this test's [recent flakiness](https://buildkite.com/elastic/beats-xpack-filebeat/builds/14573#019691c7-e3d0-430b-83a1-334343b57ef0/97-593). This PR wraps the config in a helper function so the two receivers get different temporary directories.
=> [Flaky test] Give test filebeat receivers distinct home directories

docs/reference/auditbeat/auditbeat-installation-configuration.md, docs/reference/filebeat/filebeat-installation-configuration.md, docs/reference/heartbeat/heartbeat-installation-configuration.md, docs/reference/metricbeat/metricbeat-installation-configuration.md, docs/reference/packetbeat/packetbeat-installation-configuration.md, docs/reference/winlogbeat/winlogbeat-installation-configuration.md
As reported in https://github.com/elastic/ingest-docs/issues/1784, the tabs aren't syncing in the six Beat Quickstart guides. This adds the [tab groups](https://docs-v3-preview.elastic.dev/elastic/docs-builder/tree/main/syntax/tabs#tab-groups) properties to fix that.
Closes: https://github.com/elastic/ingest-docs/issues/1784
=> Fix tabs not syncing bug in Beats quickstart guides

docs/docset.yml, docs/release-notes/breaking-changes.md, docs/release-notes/deprecations.md, docs/release-notes/index.md
Adds the Beats 9.0.1 Release Notes based off of https://github.com/elastic/beats/pull/44172
Please note: The "Handle permission errors while collecting data from Windows services" entry was in the "Breaking Changes" section of the Beats changelog. I moved it to the "Fixes" section, but let me know if it really is a breaking change.
---
=> Add Beats 9.0.1 Release Notes

CHANGELOG.next.asciidoc, filebeat/input/redis/_meta/redis.conf, filebeat/input/redis/input.go, filebeat/input/redis/redis_integration_test.go
filebeat: fix Redis auth method to support username/password
- **WHAT**: Updated the Redis authentication logic within the Filebeat input module to correctly handle username/password combinations. The AUTH command has been improved to use both username and password.
- **WHY**: The previous implementation attempted to authenticate using only the password, causing failures. Redis authentication requires two arguments: a username and a password. This update resolves the issue.
Reference: [Redis AUTH Documentation](https://redis.io/docs/latest/commands/auth/)
Run `redis_integration_test.go` to verify changes.
- https://github.com/elastic/beats/pull/40111
=> filebeat: fix Redis auth method to support username/password

.buildkite/deploy/kubernetes/deploy-k8s-pipeline.yml
This commit fixes failures like
```
make: Entering directory '/opt/buildkite-agent/builds/bk-agent-prod-gcp-1746625288052333369/elastic/deploy-k8s/metricbeat'
Installing mage v1.15.0.
go: downloading github.com/magefile/mage v1.15.0
No version is set for command mage
Consider adding one of the following versions in your config file at /opt/buildkite-agent/builds/bk-agent-prod-gcp-1746625288052333369/elastic/deploy-k8s/.tool-versions
mage 1.14.0
mage 1.15.0
```
as seen e.g. in https://github..com/elastic/beats/pull/44202#issuecomment-2854583273
due to the lack of defining the mage version as done in the rest of pipelines.
Tested only in CI, this PR should result in green CI for the deploy-k8s-pipeline
=> Set MAGE VERSION to 1.15.0 for deploy-k8s-pipeline

docs/reference/auditbeat/elasticsearch-output.md, docs/reference/auditbeat/logstash-output.md, docs/reference/auditbeat/redis-output.md, docs/reference/filebeat/elasticsearch-output.md, docs/reference/filebeat/logstash-output.md, docs/reference/filebeat/redis-output.md, docs/reference/heartbeat/elasticsearch-output.md, docs/reference/heartbeat/logstash-output.md, docs/reference/heartbeat/redis-output.md, docs/reference/metricbeat/elasticsearch-output.md, docs/reference/metricbeat/logstash-output.md, docs/reference/metricbeat/redis-output.md, docs/reference/packetbeat/elasticsearch-output.md, docs/reference/packetbeat/logstash-output.md, docs/reference/packetbeat/redis-output.md, docs/reference/winlogbeat/elasticsearch-output.md, docs/reference/winlogbeat/logstash-output.md, docs/reference/winlogbeat/redis-output.md
This is a follow up to https://github.com/elastic/beats/pull/44214 as discussed with Bill over Slack. It just adds a bit more clarification to the `worker`/ `workers` setting in the Beats docs.
=> [Docs] Clarify 'worker' and 'workers' setting descriptions

libbeat/otelbeat/oteltest/oteltest.go
These logger fields are added by the OTel collector.
- otelcol.component.kind should be lowercase. See https://github.com/open-telemetry/opentelemetry-collector/pull/12865
- otelcol.signal and not signals
See the proposal at https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/rfcs/component-universal-telemetry.md#receivers.
While at it, use the newer All iterator function for logs.
- Relates https://github.com/elastic/elastic-agent/pull/8120
=> oteltest: fix logger fields added by pipeline telemetry

CHANGELOG.next.asciidoc, x-pack/auditbeat/module/system/package/package.go, x-pack/auditbeat/module/system/package/package_test.go
Ensure the schema migration logic properly handles cases where the package.v1 bucket exists but is empty, avoiding assumptions about the presence of the state_timestamp key.
Fixes #44294
-
=> fix(auditbeat system/package): handle empty package.v1 bucket

.github/workflows/golangci-lint.yml
Updated `golangci-lint` version to 2.1.0.
To merge https://github.com/elastic/beats/pull/44308 where `golangci-lint-actions` requires at least 2.1.0.
- Relates: https://github.com/elastic/beats/pull/44308
- Closes: https://github.com/elastic/beats/issues/44312
=> Bump golangci-lint to v2.1.0

CHANGELOG.next.asciidoc, x-pack/filebeat/input/streaming/input_test.go, x-pack/filebeat/input/streaming/websocket.go
- Bug
```
In some scenarios the websocket response object can become nil and
cause  certain logging statements to cause an unexpected panic. This PR
fixes once  such identified scenario.
```
None
-
=> [filebeat][streaming] - Fixed a websocket panic scenario which would occur after exhausting max retries

libbeat/otelbeat/beatreceiver/beat_receiver.go, x-pack/filebeat/fbreceiver/factory.go, x-pack/filebeat/fbreceiver/receiver_test.go, x-pack/metricbeat/mbreceiver/factory.go, x-pack/metricbeat/mbreceiver/receiver_test.go
For beat receivers move when the HTTP endpoint is started to before when the `beater` is created.  This makes it like 
normal" beats and will start the "stats" and "inputs" endpoints.
This does have duplication between mbreceiver and fbreceiver, we can refactor that back into `beatreceiver` package when we refactor the location of the `beatreceiver` package.
None.  Beats receivers not GA and this add "inputs" endpoint that was missing
```shell
cd x-pack/filebeat/fbreceiver
go test .
```
```shell
cd x-pack/metricbeat/mbreceiver
go test .
```
- Closes #43418
=> [beat_receivers] move when monitoring is started

docs/release-notes/index.md
Part of https://github.com/elastic/observability-docs/issues/4902
Adds the Beats 9.0.2 Release Notes based off of the AsciiDoc generated content in https://github.com/elastic/beats/pull/44465. 
This still needs copy/style edits. You can use the existing 9.0.1 release notes below the 9.0.2 section for inspiration.
=> [docs] Add Beats 9.0.2 Release Notes

CHANGELOG.next.asciidoc, x-pack/agentbeat/agentbeat.spec.yml
- Fixes https://github.com/elastic/elastic-agent/issues/8245
See https://github.com/elastic/elastic-agent/issues/8245 for the problem description. To manually test this:
1. Create an agent policy and add the osquery_manager integration.
2. Install any 9.x version of Elastic Agent and enroll it in the policy above.
3. Observe that the osquery input shows in the starting state and the logs show it is existing and restarting.
4. Uninstall the agent.
5. Make the edit in this PR to the agentbeat.spec.yml file.
6. Reinstall the agent.
7. Observe the osquery input is healthy.
=> Agentbeat: preserve the osquery.app/ directory and contents during Elastic Agent installation

CHANGELOG.next.asciidoc, metricbeat/module/prometheus/query/query.go, metricbeat/module/prometheus/query/query_test.go
[Metricbeat] [Prometheus] Query dataset: make understandable error messages in case for http error codes
No impact
My test environment:
- Metricbeat built locally
- Prometheus running in docker, configured to listen on HTTPS with local self-signed certs
- Cloud deployment of Elastic stack
- Closes #44446
- Relates https://github.com/elastic/integrations/issues/13751
- Relates https://github.com/elastic/integrations/pull/13969
and the debug message to the logs
```
{"log.level":"debug","@timestamp":"2025-05-26T16:07:31.937+0300","log.logger":"prometheus.query","log.origin":{"function":"github.com/elastic/beats/v7/metricbeat/module/prometheus/query.(*MetricSet).Fetch","file.name":"query/query.go","file.line":101},"message":"error received from prometheus endpoint: …
```
=> [Metricbeat] [Prometheus] Add proper error handling for query dataset when the auth/ssl is misconfigured

CHANGELOG.next.asciidoc, libbeat/processors/dns/resolver.go, libbeat/processors/dns/resolver_test.go
Fix 'dns' processor to handle IPv6 server addresses properly.
Previously we did not account for IPV6 server addresses, and some of them would trigger a `too many colons in address` error when not properly enclosed.
=> [libbeat] Fix 'dns' processor to handle IPv6 server addresses properly.

auditbeat/tests/system/test_file_integrity.py
Auditbeat's `test_file_integrity.test_file_modified__ebpf` has been failing frequently on main ([for example](https://buildkite.com/elastic/auditbeat/builds/16043#0196f9cd-f6f8-43dc-bb92-500ebee05463)). The cause is that two file operations, a write followed by a truncate, are coalesced and reported as a single event. The test tries to guard against this by sleeping for 1 second between changes, but this does not reliably separate the events (especially without explicit i/o flush). This change adds flushes after file writes, and replaces the 1-second sleeps with an explicit wait for the expected event, so the file is not truncated until after the write has been reported.
=> [Flaky test] Prevent event coalescing in auditbeat file integrity test

CHANGELOG.next.asciidoc, x-pack/filebeat/input/gcppubsub/input.go
```
x-pack/filebeat/input/gcppubsub: fix status updating nil dereference
The status reporter was never handed to the input type resulting in a panic when
the first status update call is made after Run.
```
- Fixes #44624
=> x-pack/filebeat/input/gcppubsub: fix status updating nil dereference

x-pack/agentbeat/agentbeat.spec.yml
This adds the `autoops_es` module to Elastic Agent.
Add `autoops_es` module to Elastic Agent.
None.
Run it from Elastic Agent.
- Relates https://github.com/elastic/opex-product/issues/501
- Use AutoOps ES module from Elastic Agent with OTel.
N/A
N/A
=> [Agent Spec] Add AutoOps

.github/workflows/docs-build.yml
Ensures that the docs are built for version branches ([see docs](https://docs-v3-preview.elastic.dev/elastic/docs-builder/tree/main/migration/versioning#ci-configuration)), which is needed to start onboarding `9.0` to the documentation build.
cc @belimawr
=> [docs] Ensure docs are built for version branches

docs/reference/auditbeat/running-on-kubernetes.md, docs/reference/filebeat/running-on-kubernetes.md, docs/reference/heartbeat/running-on-kubernetes.md, docs/reference/metricbeat/running-on-kubernetes.md
Make the first `h2` heading text more specific in each Running on Kubernetes page. This in intended to help clarify that these pages are not duplicates when being indexed by search engines. I'm not sure if the wording makes sense in the context of Kubernetes so I'm tagging in @eedugon for review. 🙂
=> [docs] Make the first `h2` heading text more specific in each Running on Kubernetes page

CHANGELOG.next.asciidoc, docs/reference/filebeat/filebeat-input-aws-cloudwatch.md, go.mod, go.sum, x-pack/filebeat/input/awscloudwatch/cloudwatch.go, x-pack/filebeat/input/awscloudwatch/cloudwatch_test.go, x-pack/filebeat/input/awscloudwatch/cloudwatch_worker.go, x-pack/filebeat/input/awscloudwatch/cloudwatch_worker_test.go, x-pack/filebeat/input/awscloudwatch/config.go, x-pack/filebeat/input/awscloudwatch/input.go, x-pack/filebeat/input/awscloudwatch/input_integration_test.go, x-pack/filebeat/input/awscloudwatch/processor.go, x-pack/filebeat/input/awscloudwatch/state_handler.go, x-pack/filebeat/input/awscloudwatch/state_handler_test.go, x-pack/filebeat/input/default-inputs/inputs_darwin.go, x-pack/filebeat/input/default-inputs/inputs_other.go, x-pack/filebeat/input/default-inputs/inputs_windows.go
Introduce `lastSync` option to AWS CloudWatch input's `start_position` configuration. This feature utilizes the state registry, which with this update stores the last successful sync timestamp under the `last_sync_epoch` key. 
`start_position` configuration by default uses `beginning` option. This can cause data duplications when restarting filebeats or migrating it to a newer version. Users can avoid such data duplocates by utilizing `lastSync` option for the `start_position` configuration while targeting beats to use the same registry location. 
After the initial review, the need for acknowledgments prior to the state registry update was identified thanks to this remark - https://github.com/elastic/beats/pull/43251#discussion_r1999503090
Based on this feedback, I have implemented the …
=> feat: Introduce lastSync start position to AWS CloudWatch input backed by state registry

CHANGELOG-developer.next.asciidoc, x-pack/libbeat/management/managerV2.go
```
x-pack/libbeat/management: make UpdateStatus a no-op when no change in state
The previous code wound update and emit messages always. This would
either spam logs or require that inputs handle state in addition to the
work that is being done by the manager. The change here reflects the
behaviour in libbeat/management which checks for change before updating.
```
- Ref #44365
=> x-pack/libbeat/management: make UpdateStatus a no-op when no change in state

x-pack/filebeat/input/netflow/decoder/ipfix/decoder_test.go, x-pack/filebeat/input/netflow/decoder/template/template_test.go, x-pack/filebeat/input/netflow/decoder/template/tmpltest/test_helpers.go, x-pack/filebeat/input/netflow/decoder/v1/v1_test.go, x-pack/filebeat/input/netflow/decoder/v5/v5_test.go, x-pack/filebeat/input/netflow/decoder/v6/v6_test.go, x-pack/filebeat/input/netflow/decoder/v7/v7_test.go, x-pack/filebeat/input/netflow/decoder/v8/v8_test.go, x-pack/filebeat/input/netflow/decoder/v9/decoder_test.go
```
x-pack/filebeat/input/netflow/decoder/...: move testing helpers out of exported package
Including the testing helpers in the template package results in
unnecessarily polluting the filebeat binary with the testing package.
So move it into its own package that is only imported by _test.go files.
```
-
=> x-pack/filebeat/input/netflow/decoder/...: move testing helpers out of exported package

CHANGELOG.next.asciidoc, docs/reference/filebeat/filebeat-input-streaming.md, x-pack/filebeat/input/streaming/crowdstrike.go, x-pack/filebeat/input/streaming/crowdstrike_test.go
```
x-pack/filebeat/input/streaming: fix crowdstrike cursor handling
When the follower is given a non-singular set of resource descriptions,
it incorrectly uses the offset obtained from the registry across all of
the resources, and each of those resources' work loops writes their
cursor updates to the same (incorrectly) shared offset. This results in
cursor offset confusion.
The fix here is to retain cursors for each of the resources, keyed on
the dataFeedURL for each resource.
```
- Fixes #44364
=> x-pack/filebeat/input/streaming: fix crowdstrike cursor handling

CHANGELOG.next.asciidoc, dev-tools/mage/crossbuild.go
- Relates https://github.com/elastic/elastic-agent/pull/8497
https://github.com/elastic/beats/issues/41270 missed updating linux/arm to crossbuild with Debian11 like we did for the other platforms. This corrects that.
=> Explicitly crossbuild linux/arm with debian11

CHANGELOG.next.asciidoc, x-pack/filebeat/input/azureblobstorage/input_test.go, x-pack/filebeat/input/azureblobstorage/mock/data_files.go, x-pack/filebeat/input/azureblobstorage/mock/mock.go, x-pack/filebeat/input/azureblobstorage/testdata/txn1.csv, x-pack/filebeat/input/azureblobstorage/types.go
- Bug
```
Currently content-type "text/csv" did not have official filtering
support even though we support  csv decoding. This made blobs having this
content type defined were not picked up for processing. This PR as a "bugfix",
adds support for explicit "text/csv" content-type filtering in the
scheduler. 
```
- Closes https://github.com/elastic/beats/issues/44596
=> [filebeat][ABS] - Added missing "text/csv" content-type filter support

CHANGELOG.next.asciidoc, dev-tools/mage/fips-settings.yaml, dev-tools/packaging/package_test.go
Disables sending telemetry to Microsoft when using their [Go fork](https://github.com/microsoft/go) for producing FIPS-capable build artifacts.
None; FIPS-capable artifacts have not been released yet.
=> [FIPS] Disable Microsoft Go telemetry

CHANGELOG.next.asciidoc, x-pack/metricbeat/module/mssql/_meta/docs.asciidoc, x-pack/metricbeat/module/mssql/connection.go, x-pack/metricbeat/module/mssql/mssql.go, x-pack/metricbeat/module/mssql/performance/data.go, x-pack/metricbeat/module/mssql/performance/data_integration_test.go, x-pack/metricbeat/module/mssql/performance/doc.go, x-pack/metricbeat/module/mssql/performance/performance.go, x-pack/metricbeat/module/mssql/performance/performance_integration_test.go, x-pack/metricbeat/module/mssql/testing/mssql.go, x-pack/metricbeat/module/mssql/transaction_log/data_integration_test.go, x-pack/metricbeat/module/mssql/transaction_log/doc.go, x-pack/metricbeat/module/mssql/transaction_log/transaction_log.go, x-pack/metricbeat/module/mssql/transaction_log/transaction_log_integration_test.go
This PR (similar to #43480) ensures that the Metricbeat `mssql` module code is only compiled in non-FIPS builds of Metricbeat and is, therefore, unavailable in FIPS-capable Metricbeat artifacts.
The module indirectly depends on the Azure Go SDK. The SDK's code uses the `golang.org/x/crypto/pkcs12` package, which is not FIPS-compliant, and the SDK doesn't plan to offer a way to disable the use of this package at compile time (see https://github.com/Azure/azure-sdk-for-go/issues/24336).  
As such, we have little choice but to exclude the `mssql` module from FIPS-capable Metricbeat builds.
The `doc.go` files added to every metricset in the `mssql` module are to prevent compile-time errors like so:
```
build constraints exclude all Go files in x-pack/metricbeat/module/mssql/performance
``` …
=> Disable Metricbeat `mssql` module in FIPS builds

CHANGELOG.next.asciidoc
This PR removes any FIPS-related entries from the CHANGELOG.  See https://github.com/elastic/beats/pull/43428#discussion_r2012737373.
=> Remove FIPS-related CHANGELOG entries

CHANGELOG.next.asciidoc, libbeat/processors/add_cloud_metadata/docs/add_cloud_metadata.asciidoc, libbeat/processors/add_cloud_metadata/provider_azure_vm.go, libbeat/processors/add_cloud_metadata/provider_azure_vm_test.go, libbeat/processors/add_cloud_metadata/providers.go, libbeat/processors/add_cloud_metadata/providers_nofips.go
This PR amends the `add_cloud_metadata` processor initialization such that the Azure Virtual Machine provider is included only in non-FIPS builds. 
The Azure Virtual Machine provider depends on the Azure SDK which, in turn, depends on the golang.org/x/crypto/pkcs12 package, which is not FIPS-compliant, and the SDK doesn't plan to offer a way to disable the use of this package at compile time (see https://github.com/Azure/azure-sdk-for-go/issues/24336).
The `add_cloud_metadata` processor will not support the Azure Virtual Machine provider in FIPS-capable artifacts of Beats.
=> Exclude Azure VM provider in `add_cloud_metadata` processor in FIPS builds

CHANGELOG.next.asciidoc, x-pack/filebeat/input/gcs/input_test.go, x-pack/filebeat/input/gcs/mock/data_files.go, x-pack/filebeat/input/gcs/mock/mock.go, x-pack/filebeat/input/gcs/mock/testdata/txn1.csv, x-pack/filebeat/input/gcs/types.go
- Bug
```
Currently content-type "text/csv" did not have official filtering
support even though we support csv decoding. This made objects having this
content type defined were not picked up for processing. This PR as a "bugfix",
adds support for explicit "text/csv" content-type filtering while processing 
each job. 
```
- Closes https://github.com/elastic/beats/issues/44922
- Relates https://github.com/elastic/integrations/issues/14032
=> [filebeat][GCS] - Added missing 'text/csv' content-type filter support

docs/reference/filebeat/filebeat-input-filestream.md
Fingerprint mode is enabled by default since v9.0.0.
=> docs: remove incorrect sentence

CHANGELOG.next.asciidoc, docs/reference/filebeat/filebeat-input-entity-analytics.md, x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/graph/graph.go, x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/graph/graph_test.go
=> x-pack/filebeat/input/entityanalytic/provider/azuread/fetcher/graph: add support for expand

CHANGELOG-developer.next.asciidoc, libbeat/otelbeat/otelmap/otelmap.go, libbeat/otelbeat/otelmap/otelmap_test.go
This adds support for `map[string]any` and also arrays in general (as opposed to just slices) to the converted map.
Like `mapstr.M` and `[]mapstr.M`, this will dive into the `map[string]any` and `[]map[string]any` objects to ensure that they are properly converted for the pdata code.
Properly handles nested `map[string]any` and array types (not just slices) for OTel conversion to avoid `Invalid type` warnings from OTel.
This should make the code more flexible -- not less.
The easiest way is to inspect the new test and try removing the updated code to see what changes.
- Closes https://github.com/elastic/beats/issues/45007
Metricsets can now ship nested `map[string]any` that contain arrays and slices, including of `[]map[string]any`.
=> [OTel] Support Serializing nested data

filebeat/input/v2/loader.go, filebeat/input/v2/loader_test.go, filebeat/input/v2/plugin.go, libbeat/common/mode_fips.go, libbeat/common/mode_nofips.go
This PR adds a new boolean field, `ExcludeFromFIPS` to the [`v2.Plugin` struct](https://github.com/elastic/beats/blob/c63e539cf8ea40302340ea6ab640a020740e86dd/filebeat/input/v2/plugin.go#L43) for optional use by v2 inputs.  Inputs that set this field to `true` are indicating that they should NOT be usable in FIPS-capable distributions of Filebeat.  If an input that sets this field to `true` is configured in a FIPS-capable Filebeat distribution, Filebeat will exit with an error like so:
```
{"log.level":"error","@timestamp":"2025-06-25T11:22:14.686-0700","log.origin":{"function":"github.com/elastic/beats/v7/libbeat/cmd/instance.handleError","file.name":"instance/beat.go","file.line":1355},"message":"Exiting: Failed to start crawler: starting input failed: error while initializing input: …
```
=> [Filebeat] Allow v2 inputs to opt out of FIPS distributions

libbeat/otelbeat/otelmap/otelmap.go, libbeat/otelbeat/otelmap/otelmap_test.go
This simplifies the serialization of arrays / slices of `map[string]any` and add tests for inner `nil` handling.
Add better tests for `otelmap` and simplified arrays and slices and use less reflection.
No change.
- Run the tests in `otelmap`
- https://github.com/elastic/beats/issues/45007
=> [OTel] Serialize Maps and `nil` Better

CHANGELOG.next.asciidoc, libbeat/outputs/backoff.go, libbeat/outputs/elasticsearch/client.go, libbeat/outputs/elasticsearch/client_test.go
See https://github.com/elastic/beats/issues/36926. This fix has two components:
- Return an error from `Publish` when the Elasticsearch output gets a 429 (too many requests) from Elasticsearch. This triggers a retry delay and reconnection attempt in the pipeline.
- Break the backoff counters for `Publish` and `Connect` into separate values, so a successful `Connect` call (which for Elasticsearch just means that an empty http GET gave an ok response) doesn't reset the exponential backoff for bulk ingest requests when they are being throttled.
[This comment](https://github.com/elastic/beats/issues/36926#issuecomment-3005085250) on the issue has local testing instructions.
- Fixes https://github.com/elastic/beats/issues/36926.
=> Fix Elasticsearch output retry backoff when receiving 429s

docs/reference/filebeat/filebeat-installation-configuration.md
This PR fixes the rendering issue of a code snippet annotation in the "Filebeat quick start" doc.
https://docs-v3-preview.elastic.dev/elastic/beats/pull/45121/reference/filebeat/filebeat-installation-configuration#set-connection
=> Fix rendering of code snippet annotation in Filebeat quick start

x-pack/filebeat/fbreceiver/receiver_test.go
This test is flaking for a while with a high failure rate. We have an integration test that covers the same scenario added by https://github.com/elastic/beats/pull/45093. Skip this test for now.
- For https://github.com/elastic/beats/issues/43832
=> [oteltest][fbreceiver]: skip TestMultipleReceivers

libbeat/otelbeat/otelmap/otelmap.go, libbeat/otelbeat/otelmap/otelmap_test.go
The otelmap package does not handle struct types properly, the convertion of a struct results in a string error.
To follow the libbeat behavior, handle struct types the same way, by serializing to json and back, resulting in a map of keys and values.
We have plans to try and extend otelmap to use the libbeat generic serializer, but that is part of a large refactor that should be done in a separate PR.
- Closes https://github.com/elastic/beats/issues/45005
=> otelmap: handle conversion of struct types

x-pack/metricbeat/module/aws/_meta/kibana/7/visualization/15818fd0-f7f9-11e8-af03-c999c9dea608-ecs.json, x-pack/metricbeat/module/aws/_meta/kibana/7/visualization/233b3400-f7f9-11e8-af03-c999c9dea608-ecs.json, x-pack/metricbeat/module/aws/_meta/kibana/7/visualization/be8828d0-f7f6-11e8-af03-c999c9dea608-ecs.json, x-pack/metricbeat/module/aws/_meta/kibana/7/visualization/f1db6ec0-f7f8-11e8-af03-c999c9dea608-ecs.json, x-pack/metricbeat/module/aws/_meta/kibana/7/visualization/fed59380-f7f8-11e8-af03-c999c9dea608-ecs.json
Updates the CPU/disk/network metric field names in the "[Metricbeat AWS] EC2 Overview" dashboard.
The "[Metricbeat AWS] EC2 Overview" dashboard that comes with the AWS modules was still using the old metric field names that are no longer in use, resulting in a dashboard with multiple empty visualizations.
Here are the current changes:
| Old                          | New                          | Formatter |
| ---------------------------- | ---------------------------- | --------- |
| `aws.ec2.cpu.total.pct`      | `host.cpu.usage`             | `percent` |
| `aws.ec2.diskio.read.bytes`  | `host.disk.read.bytes`       | `bytes`   |
| `aws.ec2.diskio.write.bytes` | `host.disk.write.bytes`      | `bytes`   |
| `aws.ec2.network.in.bytes`   | `host.network.ingress.bytes` | `bytes`   |
| …
=> [Metricbeat] Fix CPU/disk/network visualizations in EC2 overview dashboard

CHANGELOG.next.asciidoc, x-pack/heartbeat/monitors/browser/source/inline.go, x-pack/heartbeat/monitors/browser/source/local.go, x-pack/heartbeat/monitors/browser/source/project.go, x-pack/heartbeat/monitors/browser/source/source.go, x-pack/heartbeat/monitors/browser/source/zipurl.go, x-pack/heartbeat/monitors/browser/sourcejob.go, x-pack/heartbeat/monitors/browser/sourcejob_test.go, x-pack/heartbeat/monitors/browser/synthexec/synthexec.go, x-pack/heartbeat/monitors/browser/synthexec/synthexec_test.go
Add `encoding: base64` option to inline monitors. This change allows inline monitors to support characters that would otherwise break yaml format.
1. Build heartbeat locally
2. Specify a base64-encoded inline script monitor.
3. Execute heartbeat and check monitor is decoded at setup.
-
- Closes #45029.
=> [Heartbeat] Add base64 encoding option to inline monitors

x-pack/metricbeat/module/autoops_es/events/error_event.go, x-pack/metricbeat/module/autoops_es/events/error_event_test.go, x-pack/metricbeat/module/autoops_es/metricset/cluster_info.go, x-pack/metricbeat/module/autoops_es/utils/version.go
This improves the Version Mismatch error to make it easier to debug.
Improve debug support for unsupported versions.
=> [AutoOps] Cleanup Version Mismatch Error

.github/workflows/post-dependabot.yml
This change enhances our post-dependabot workflow by automatically requesting a review from the obs-infraobs-integrations team whenever a Dependabot‐generated Go module PR is scoped to the Obs-InfraObs team.
=> Update post-dependabot.yml to add a team as a reviewer

CHANGELOG.next.asciidoc, x-pack/filebeat/input/httpjson/config_auth.go, x-pack/filebeat/input/httpjson/input.go, x-pack/filebeat/input/httpjson/request.go, x-pack/filebeat/input/httpjson/request_test.go
```
x-pack/filebeat/input/httpjson: share oauth2 clients where possible
The httpjson input makes new http.Client values for every chain step.
This is inefficient for a variety of reasons, but the configuration API
that we expose makes the general fix for this non-trivial. It is,
however, possible to fix the OAuth2 behaviour that arises from this
where root parent steps in a chain make use of OAuth2 and so do its
children, but the children needlessly request tokens because they do
not have access to the oauth2.Transports token cache. The fix here is
to retain the prepared OAuth2 client in the relevant config and use
that if it is non-nil. This does not fix the case that a non-root
parent shares OAuth2 authentication with its children, but this is
likely to be uncommon.
```
- Closes #34834
=> x-pack/filebeat/input/httpjson: share oauth2 clients where possible

x-pack/metricbeat/module/autoops_es/cat_shards/cat_shards_test.go, x-pack/metricbeat/module/autoops_es/events/error_event_test.go, x-pack/metricbeat/module/autoops_es/metricset/cluster_info_test.go, x-pack/metricbeat/module/autoops_es/utils/resource.go, x-pack/metricbeat/module/autoops_es/utils/resource_test.go
This adds a `AUTOOPS_` to ensure resource IDs are intended for AutoOps rather than some other system property.
We do not want to accidentally consume an unrelated ID.
=> [AutoOps] Avoid Environment Collision by prefixing with AUTOOPS_

CHANGELOG.next.asciidoc, x-pack/metricbeat/module/aws/awshealth/awshealth.go
Make error messages explicit by parsing them using smithy library.
- Closes #44852
=> [AWS Health]  Improve error message reporting

.github/dependabot.yml
Update dependabot to take care of modules required by windows and iis modules.
=> Update dependabot.yml with new Windows dependencies

.github/workflows/post-dependabot.yml
Fixes "Resource not accessible by integration (organization.teams)" error when adding team reviewers to dependabot PRs with gh cli
See: https://github.com/cli/cli/issues/6274#issue-1374659270 and https://github.com/cli/cli/issues/6274#issuecomment-1285948958
See: https://github.com/orgs/community/discussions/113519
=> fix: add repository-projects read permission to post-dependabot workflow

.github/dependabot.yml
Add the Windows-related dependencies to the 'allow' list so that it works. In one of the previous PRs, entries were made only to the groups list, but now the 'allow' list and hence Dependabot was not creating the PRs.
=> dependabot: Add Windows dependencies to allow list

libbeat/processors/add_kubernetes_metadata/docs/add_kubernetes_metadata.asciidoc
This is a manual backport of https://github.com/elastic/beats/pull/45315 
---
- Docs
Fix the `host` reference on `add_kubernetes_metadata` with correct param `node`.
Rif commit that brake this: https://github.com/elastic/beats/commit/c1d4f28ff30e28429efed51c817cd02d46633aac
Rif current spec: https://github.com/elastic/beats/blob/main/libbeat/autodiscover/providers/kubernetes/config.go#L47
=> [8.19](backport #45315) Docs: Fix wrong host reference in add_kubernetes_metadata

docs/reference/filebeat/filebeat-input-gcs.md
Type of change:
- Docs
- Added `applies_to` tags to the version-related changes in `docs/reference/filebeat/filebeat-input-gcs.md`
- Reason for change: Starting with v9.0, there is no longer a new documentation set published with every minor release: the same page stays valid over time and shows version-related evolutions. Read more in [Write cumulative documentation](https://elastic.github.io/docs-builder/contribute/cumulative-docs/).
=> Add `applies_to` tags to mark version-related changes

docs/reference/filebeat/filebeat-input-entity-analytics.md
>[!NOTE]
In https://github.com/elastic/beats/pull/44761, @efd6 added support for `expand` in the azure-ad provider. The 9.0 backport was closed without merging, but it is in 9.1 so I _think_ we should add 9.1.0 `applies_to` labels to the new options in `docs/reference/filebeat/filebeat-input-entity-analytics.md`.
Note for @elastic/ingest-docs: For the [code block callout](https://elastic.github.io/docs-builder/syntax/code/#code-callouts), I couldn't come up with language that would make sense alongside …
=> [docs] Adds `applies_to` to changes from #44761

docs/reference/filebeat/filebeat-input-entity-analytics.md
>[!NOTE]
In https://github.com/elastic/beats/pull/43655, @efd6 added support for pagination batch size. According to the [release notes](https://www.elastic.co/docs/release-notes/beats#beats-9.0.1-release-notes), this was added in 9.0.1. This PR adds a 9.0.1 `applies_to` label to the `batch_size` heading in  `docs/reference/filebeat/filebeat-input-entity-analytics.md`.
=> [docs] Adds `applies_to` to changes from #43655

docs/reference/filebeat/filebeat-input-gcp-pubsub.md
>[!NOTE]
In https://github.com/elastic/beats/pull/44892, @efd6 added proxy support to GCP Pub/Sub input and it was confirmed that this is going into 9.1.0. We should add 9.1.0 `applies_to` labels to `docs/reference/filebeat/filebeat-input-gcp-pubsub.md`.
=> [docs] Adds `applies_to` to changes from #44892 

docs/reference/filebeat/filebeat-input-aws-cloudwatch.md
Adds `applies_to` tags to changes in the documentation introduced with https://github.com/elastic/beats/pull/43251 
>[!NOTE]
In https://github.com/elastic/beats/pull/43251, @Kavindu-Dodan introduced `lastSync` option to AWS CloudWatch input's `start_position` configuration. Based on [this comment](https://github.com/elastic/beats/pull/43251#issuecomment-2956087030), we should add 9.1 `applies_to` labels to `docs/reference/filebeat/filebeat-input-aws-cloudwatch.md`.
=> [Docs] Add `applies_to` to changes from #43251

docs/release-notes/breaking-changes.md, docs/release-notes/index.md
Starting with 9.0.0, we're publishing all minor and patch 9.x versions on a single page. In https://github.com/elastic/beats/pull/45354, we targeted the `9.0` branch, but we also need that content in `main` and `9.1` so the 9.0.4 release notes will be visible when we start publishing from `9.1` (the 9.1.0 release day).
This PR cherry picks changes to the Markdown files that were made in https://github.com/elastic/beats/pull/45354.
=> [docs] Add 9.0.4 release notes

docs/reference/filebeat/filebeat-input-filestream.md
Related: https://github.com/elastic/docs-content-internal/issues/68
Closes: https://github.com/elastic/docs-content-internal/issues/83
The column-wrapped changes in https://github.com/elastic/beats/pull/43978/files made this one look like a lot more changed than actually did.  Here's what it boils down to:
=> Doc: Add applies_to label for 9.1 content

CHANGELOG.next.asciidoc, docs/reference/filebeat/filebeat-input-cel.md, docs/reference/filebeat/filebeat-input-streaming.md
```
docs/reference/filebeat/filebeat-input-{cel,streaming}.md: Improve explanation of `state` option
Improved to make it clear that the configuration option only sets the
initial value and that CEL program return values will be used after
that.
```
=> docs/reference/filebeat/filebeat-input-{cel,streaming}.md: Improve explanation of `state` option

dev-tools/mage/pkgtypes.go
Set a different package name for FIPS-enabled `.deb`  packages. This will allow to choose between FIPS and non-FIPS enabled version of the same beat by package name.
- Build a FIPS-enabled beat .deb package:
```shell
FIPS=true SNAPSHOT=true PACKAGES="deb" PLATFORMS="linux/amd64" mage -v package
```
- Have a look at the package metadata
```shell
dpkg --info build/distributions/metricbeat-fips-9.2.0-SNAPSHOT-amd64.deb
new Debian package, version 2.0.
size 67598384 …
```
=> Change package name for fips-enabled deb packages

x-pack/metricbeat/tests/integration/otel_test.go
This test is flaking with a high failure rate. I suspect it has to do with running multiple receivers on the same process, since the single receiver version of this test (TestMetricbeatOTelReceiverE2E) is not flaking.
This test was introduced by https://github.com/elastic/beats/pull/45427.
```
$ cd x-pack/metricbeat/
$ go test -c -tags otelbeat
$ mage docker:composeUp
$ go test -tags "integration" -run 'TestMetricbeatOTelMultipleReceiversE2E' ./tests/integration -v -count=1
=== RUN   TestMetricbeatOTelMultipleReceiversE2E
otel_test.go:297: Flaky test, see https://github.com/elastic/beats/issues/45631
--- SKIP: TestMetricbeatOTelMultipleReceiversE2E (0.00s)
PASS
ok      github.com/elastic/beats/v7/x-pack/metricbeat/tests/integration 0.005s
```
- For …
=> otel: skip flaky test TestMetricbeatOTelMultipleReceiversE2E

CHANGELOG.next.asciidoc, x-pack/filebeat/input/azureblobstorage/config.go, x-pack/filebeat/input/azureblobstorage/input.go
- Bug
```
Improve error handling when both root level "max_workers" and "batch_size" are empty.
```
**NOTE:** Having a mandatory validation would go against the philosophy of the design here were it would be then required
to have a max_worker or batch_size value present at the root level. This fix allows the default container level "max_worker" to get configured without errors and this would eventually trickle down to the "batch_size" if both root level attributes are missing.
- Closes https://github.com/elastic/beats/issues/45680
- Relates https://github.com/elastic/beats/pull/44992
=> [filebeat][abs] - Improve error handling when both root level "max_workers" and "batch_size" are empty

CHANGELOG.next.asciidoc, x-pack/filebeat/tests/integration/managerV2_test.go, x-pack/libbeat/management/managerV2.go, x-pack/libbeat/management/simple_input_config_test.go
```
BeatV2Manager `reload` method calls `reloadInputs`, however it did not
handle the errors returned correctly. This commit fixes it by making
`reloadInputs`, whenever possible, use a cfgfile.UnitError to indicate
the failed unit and `reload` now handles any unexpected error case/type.
Multiple lint warnings are fixed, including:
- An unused wait group is removed
- The parameters order in a `errors.Is` call is fixed
```
- Closes https://github.com/elastic/beats/issues/43118
~~## Logs~~
=> Fix error handling from BeatV2Manager reload

CHANGELOG-developer.next.asciidoc, x-pack/filebeat/magefile.go, x-pack/metricbeat/magefile.go
See title
```
mage -v buildSystemTestBinary # Ensure -tags otelbeat is in the command
./filebeat.test --systemTest otel
cd ../metricbeat
mage -v buildSystemTestBinary # Ensure -tags otelbeat is in the command
./metricbeat.test --systemTest otel
```
~~## Logs~~
=> Enable Otel support in BuildSystemTestBinary

CHANGELOG.next.asciidoc, x-pack/filebeat/input/awscloudwatch/cloudwatch.go, x-pack/filebeat/input/awscloudwatch/cloudwatch_worker.go, x-pack/filebeat/input/awscloudwatch/input.go, x-pack/filebeat/input/awscloudwatch/state_reporter.go, x-pack/filebeat/input/awscloudwatch/state_reporter_test.go
Adds Status reporting for AWS CloudWatch input. I have introduced following,
- `cwStateReporter` : This proxy the status to the actual status reporter. Validate status change from current before conveying status to internal reporter.
- `debugCWStatusReporter`: Performs debug logging when context-bound reporter is missing. For example, this happens in standalone mode
None - Status reports are utilized by the Agent. In standalone mode, logs are added in Debug level
- Run standalone filebeat with CloudWatch input & debug logs
- Observe debug logs with `CloudWatch input status updated:` prefix for status changes 
See below log entries from a standalone run,
Fixes https://github.com/elastic/beats/issues/44648
=> feat: add status reporting to CloudWatch

CHANGELOG.next.asciidoc, metricbeat/module/kafka/consumergroup/consumergroup.go, metricbeat/module/kafka/partition/partition.go
[metricbeat][kafka] change kafka protocol version from 3.6.0 to 2.1.0 to ensure module compatibility with Kafka 2.x
- Relates https://github.com/elastic/obs-integration-team/issues/463
Testing was performed with Kafka 2.2.0 and Kafka 3.6.0:
Kafka 2.2.0
Kafka 3.6.0
Also tests were performed with locally built elastic-agent (that included this change):
Kafka 2.2.0
Kafka 3.6.0
=> [metricbeat][kafka] change kafka protocol version from 3.6.0 to 2.1.0

CHANGELOG.next.asciidoc, x-pack/filebeat/input/o365audit/listblobs.go, x-pack/filebeat/input/o365audit/listblobs_test.go
```
x-pack/filebeat/input/o365audit: trim redundant BOM prefix
Despite it being advised against, the O365 data source prefixes UTF-8
text with a BOM. Remove it before attempting to unmarshal the JSON.
```
- Fixes #44327
=> x-pack/filebeat/input/o365audit: trim redundant BOM prefix

go.mod, go.sum
Match the `prometheus/prometheus` version used by upstream `prometheusreceiver` to avoid dependency conflict in `elastic-agent`
Currently, `prometheusreceiver` uses an unreleased version of `prometheus/prometheus`
```go
github.com/prometheus/prometheus v0.304.3-0.20250703114031-419d436a447a
github.com/stretchr/testify v1.10.0
```
which uses the latest version of `oteltranslator` ( reverted in the `v0.305.0` release https://github.com/prometheus/prometheus/commit/3253ba63107ee5db50f98d3dc418f25a829d1a7b )
This mismatch is causing dependency conflict when updating otel collector dependencies in elastic-agent
Compilation error as follows
```
> build: Building elastic-agent
../pkg/mod/github.com/prometheus/prometheus@v0.305.0/storage/remote/otlptranslator/prometheusremotewrite/helper.go:155:30 …
```
=> Match prometheus version with upstream prometheusreceivers'

metricbeat/module/docker/diskio/diskio.go, metricbeat/module/docker/diskio/diskio_integration_test.go, metricbeat/module/docker/event/event.go, metricbeat/module/docker/memory/memory.go, metricbeat/module/jolokia/jmx/config.go, metricbeat/module/kubernetes/event/event_test.go, metricbeat/module/kubernetes/util/kubernetes_test.go, metricbeat/module/kubernetes/volume/volume.go, metricbeat/module/kubernetes/volume/volume_test.go
This is a follow up backport PR of https://github.com/elastic/beats/pull/44775
The base PR had to be split because currently CI fails on 8.19 if the PR includes changes for K8's and docker modules at the same time
=> [Chore][Backport] Replace global logger with local loggers in mb modules #5 

.buildkite/scripts/custom_fips_ech_test.sh
Follow up to https://github.com/elastic/beats/pull/45784, which was bumping up the version of Beats to `9.1.2`.  In that PR, we had to pin the stack version used in integration tests that spin up ECH deployments to `9.1.1` because artifacts of version `9.1.2-SNAPSHOT` are not yet available in the ECH CFT region.  
This PR here removes the pinning.  It should be merged once CI goes green, which should happen once artifacts of version `9.1.2-SNAPSHOT` are available in the ECH CFT region.
=> Unpin stack version on `9.1` branch

CHANGELOG.next.asciidoc, docs/reference/filebeat/filebeat-input-httpjson.md, x-pack/filebeat/input/httpjson/request.go, x-pack/filebeat/input/httpjson/value_tpl.go, x-pack/filebeat/input/httpjson/value_tpl_test.go
```
x-pack/filebeat/input/httpjson: allow template termination without logging error
This adds a terminate helper that can be used to signal that a template
should terminate without an error. The termination can (should) be used
to report the reason for the termination which will be logged at DEBUG
level, but otherwise ignored.
```
- Closes #45664
=> x-pack/filebeat/input/httpjson: allow template termination without logging error

CHANGELOG.next.asciidoc, x-pack/filebeat/input/default-inputs/inputs_windows.go
```
[Streaming] Restore the Streaming input on Windows
It was originally named the Websocket input and was added everywhere
except AIX. It was accidentally removed from Windows in #36915.
```
This does the same thing for the Streaming (previously Websocket) input as was done for the Netflow input in #39024.
-
=> [Streaming] Restore the Streaming input on Windows

CHANGELOG.next.asciidoc, go.mod, go.sum, libbeat/outputs/metrics.go
This PR adds a new histogram (`latency_delta`) to the `.monitoring.metrics.libbeat.output.write` metrics.  This histogram is cleared every time it is visited (read).  This is useful because the existing histogram (`latency`) is for the lifetime of the output.  If you have a long running process it becomes very difficult to see short term changes in the lifetime histogram.  The original `latency` histogram is unchanged.
This does add 6 new fields to the monitoring output.
Run a beat and look at the "30 sec" metrics output
- Closes elastic/ingest-dev#5882 …
=> Add latency_delta histogram to monitoring.metrics.libbeat.output.write metrics

docs/reference/filebeat/filebeat-input-filestream.md
>[!NOTE]
In #43368, @belimawr added information on deleting ingested log files. Because the initial PR was not backported, I guessed that these changes are planned for 9.2.0. If it is being added to a different version, please adjust the `applies_to` annotations.
Note: We already added a page-level `applies_to` annotation to the new [Removing files after ingestion](https://docs-v3-preview.elastic.dev/elastic/beats/pull/46097/reference/filebeat/delete-file-guide) page in …
=> [docs] Adds applies_to to changes from #43368

dev-tools/mage/gotest.go, filebeat/testing/integration/container_test.go, filebeat/testing/integration/helper.go, libbeat/testing/integration/run_beat.go, x-pack/filebeat/tests/integration/windows/inputs_windows_test.go
```
This commit fixes the process handling for Windows in `testing/integrataion` that was causing `mage goWindowsIntegTest` to fail in CI as well as `TestWinInputs` to fail when run manually.
`TestContainerInput` is also fixed. The `time.Sleep` is replaced by `require.Eventually` and a Filestream input ID is added to the configuration.
```
```sh
cd filebeat
go test -tags=integration -count=1 ./testing/integration
```
```
mage goWindowsIntegTest
```
- Fixes https://github.com/elastic/beats/issues/46100
- Fixes https://github.com/elastic/beats/issues/46126 
~~## Logs~~
=> Fix TestContainerInput and `testing/integrataion` framework 

docs/reference/auditbeat/auditbeat-installation-configuration.md, docs/reference/auditbeat/auditbeat-installation-script.md, docs/reference/filebeat/filebeat-installation-configuration.md, docs/reference/filebeat/filebeat-installation-script.md, docs/reference/heartbeat/heartbeat-installation-configuration.md, docs/reference/heartbeat/heartbeat-installation-script.md, docs/reference/metricbeat/metricbeat-installation-configuration.md, docs/reference/metricbeat/metricbeat-installation-script.md, docs/reference/packetbeat/packetbeat-installation-configuration.md, docs/reference/packetbeat/packetbeat-installation-script.md, docs/reference/winlogbeat/winlogbeat-installation-configuration.md, docs/reference/winlogbeat/winlogbeat-installation-script.md
```
This commit updates the documentation to clarify which versions have the new install script that uses `C:\Program Files-Data` as the base path for Beats.
```
1. Build the docs: `docs-builder serve`
2. For each Beat check (example links for Filebeat)
- http://localhost:3000/reference/filebeat/filebeat-installation-script
- http://localhost:3000/reference/filebeat/filebeat-installation-configuration - Go to "Step 1", then click on "Windows" tab.
~~## Logs~~
=> Improve documentation about Windows install script

docs/reference/index.md, docs/reference/serverless/beats.md
Rework landing page to give more context and direction to users.
Fixes:  https://github.com/elastic/ingest-docs/issues/1831
=> Doc: Refine Beats landing page

auditbeat/module/auditd/audit_linux.go, filebeat/input/log/harvester.go, heartbeat/hbregistry/hbregistry.go, heartbeat/monitors/plugin/regrecord.go, libbeat/cmd/instance/beat.go, libbeat/monitoring/inputmon/httphandler_test.go, libbeat/monitoring/inputmon/input.go, libbeat/monitoring/inputmon/input_test.go, libbeat/processors/add_host_metadata/add_host_metadata.go, libbeat/processors/dns/dns.go, libbeat/processors/dns/resolver.go, libbeat/processors/dns/resolver_test.go, libbeat/processors/ratelimit/rate_limit.go, libbeat/processors/script/javascript/javascript.go, libbeat/processors/syslog/syslog.go, libbeat/publisher/pipeline/controller.go, libbeat/publisher/pipeline/module.go, libbeat/publisher/pipeline/monitoring.go, libbeat/publisher/queue/monitoring.go, metricbeat/mb/module/wrapper.go, x-pack/auditbeat/module/system/process/quark_provider_linux.go, x-pack/auditbeat/processors/sessionmd/add_session_metadata.go
The `NewRegistry` method in `elastic-agent-libs` is inherently unsafe, especially in concurrent code: calling `NewRegistry` on a name that already exists causes a panic, but checking whether the name exists first is not atomic. The recently added `GetOrCreateRegistry` method is a safe alternative that checks the name's existence and initializes it atomically, and never panics. This PR replaces all remaining `NewRegistry` calls with `GetOrCreateRegistry`.
=> Remove all remaining NewRegistry method calls

.github/CODEOWNERS
Marks metricbeats's SQL helper as owned by infraobs-integrations team
=> CODEOWNERS: add /metricbeat/helper/sql @elastic/obs-infraobs-integrations

docs/reference/filebeat/filebeat-input-gcs.md
>[!NOTE]
In #45088, @ShourieG added custom properties to the Google Cloud Storage Input docs. Because the initial PR was not backported, I guessed that these changes are planned for 9.2.0. If it is being added to a different version, please adjust the `applies_to` annotations.
Note: In order to apply a section-level `applies_to` annotation, I had to make some adjustments to the headings to make sure they were incremental.
=> [docs] Adds `applies_to` to changes from #45088

docs/release-notes/breaking-changes.md, docs/release-notes/index.md
Ports release notes from https://github.com/elastic/beats/pull/46224 to Markdown.
=> [docs] Add 9.1.3 release notes in Markdown

docs/reference/metricbeat/metricbeat-module-elasticsearch.md, metricbeat/module/elasticsearch/_meta/docs.md
This marks the fixed support for Base64-encoded API Keys for Elasticsearch.
Document `api_key` support for the `elasticsearch` (and, by extension, the `autoops_es`) module.
- Requires https://github.com/elastic/beats/pull/46358
=> [Docs] Add Support for Base64 encoded `api_key` in Elasticsearch

docs/reference/filebeat/add-cloud-metadata.md
Add missing dash in add-cloud-metadata documentation
=> Add missing dash in add-cloud-metadata documentation

filebeat/beater/filebeat.go
See title
1. Build Agentbeat
```
cd x-pack/agentbeat
go build .
```
2. Download the Elastic Agent 9.2.0-SNAPSHOT
- Linux: https://snapshots.elastic.co/9.2.0-f3caf25b/downloads/beats/elastic-agent/elastic-agent-9.2.0-SNAPSHOT-linux-x86_64.tar.gz
- Darwin ARM: https://snapshots.elastic.co/9.2.0-f3caf25b/downloads/beats/elastic-agent/elastic-agent-9.2.0-SNAPSHOT-darwin-aarch64.tar.gz
3. Extract it and replace the agentbeat binary by the one you compiled
4. Start Elasticsearch (run it from `x-pack/filebeat`): `mage docker:ComposeUp`
5. Start the Elastic Agent
Use the following configuration
```yaml
outputs:
default:
type: elasticsearch
hosts:
- http://localhost:9200
username: "admin"
password: "testing"
inputs:
id: …
```
=> Do not show 'ingest pipeline' warning when managed by Elastic Agent

CHANGELOG.next.asciidoc, filebeat/input/netmetrics/netmetrics.go, filebeat/input/netmetrics/netmetrics_test.go
```
When parsing the port to collect metrics, the TCP & UDP inputs were
parsing the port as a int16, which limited the maximum port to
32767. This commit fixes it by parsing the port as uint16.
```
1. Start Filebeat with the following configuration:
```yaml
- type: udp
host: 127.0.0.1:42000
output.discard:
enabled: true
logging:
to_stderr: true
level: warning
http.enabled: true
```
2. Ensure the following waring is **not** in the logs:
```json
{
"log.level": "warn",
"@timestamp": "2025-09-09T18:02:06.893-0400",
"log.logger": "input.udp",
"function": "github.com/elastic/beats/v7/filebeat/input/netmetrics.NewUDP",
"file.name": "netmetrics/udp.go",
"file.line": 65
},
"message": "failed to get port for …
```
=> Fix TCP & UDP input metricsets for ports > 32767

CHANGELOG.next.asciidoc, go.mod, go.sum, libbeat/processors/add_host_metadata/add_host_metadata.go, libbeat/processors/add_host_metadata/add_host_metadata_test.go
This PR is based on https://github.com/elastic/beats/pull/46546, with some changes to fix concurrency issues.
Make data updates in add_host_metadata processor synchronous.
Right now, the add_host_metadata processor adds a callback tracking changes to the value of the FQDN feature flag. This callback is never cleaned up, and adding a Close method to the processor is a breaking change. This change gets rid of the callback and instead just checks whenever it processes an event.
We reload the data synchronously now, during event processing. The asynchronous updates intentionally blocked processing anyway by taking the expiration lock, so in practice this shouldn't change much. Synchronous updates happen on every cache expiration regardless.
I've also made it possible to substitute real …
=> Make data updates in add_host_metadata processor synchronous

CHANGELOG.next.asciidoc, winlogbeat/eventlog/wineventlog.go
Fix EventLog reset logic to avoid closing renderers
- Closes https://github.com/elastic/beats/issues/45750
=> [winlogbeat] Fix EventLog reset logic to avoid closing renderers

filebeat/input/journald/input_test.go, filebeat/input/journald/pkg/journalctl/reader.go
```
When the --directory option was introduced we broke the behaviour of supporting globs like /foo/*/*, this commit restores it.
If there is any error when trying to stat the path to check whether it is directory, we log at debug level and default to the previous behaviour of using `--path`.
```
1. Create the necessary folder structure with journal files
```sh
cd filebeat/input/journald/testdata
mkdir -p /tmp/journaltest/001
cp journal?.journal.gz /tmp/journaltest/001
cd /tmp/journaltest/001
gunzip *
```
2. Start Filebeat with the following configuration
<details><summary>filebeat.yaml</summary>
<p>
```
- type: journald
id: foo
paths:
- /tmp/journaltest/*/*
queue.mem:
flush.timeout: 0
output.discard:
enabled: true …
```
=> [Filbeat/Journald] Restore support for paths like /foo/*/*

CHANGELOG.next.asciidoc, x-pack/filebeat/input/azureeventhub/config.go, x-pack/filebeat/input/azureeventhub/config_test.go, x-pack/filebeat/input/azureeventhub/connection_string.go, x-pack/filebeat/input/azureeventhub/connection_string_test.go, x-pack/filebeat/input/azureeventhub/v2_input.go, x-pack/filebeat/input/azureeventhub/v2_migration.go
Fix entity path handling in the event hub connection string (v1 and v2 processors).
For context on this issue, see https://github.com/elastic/beats/issues/43715.
Changes:
- v1 & v2: fully parse the connection string for validation and to check the event hub name and entity path match.
- v2: handle event hub name and connection string according to the new Event Hub SDK requirements to support all connection string formats.
Unrelated changes:
- I had to fix an unrelated problem to `metricbeat/module/windows/service/service_integration_test.go` to make the linter happy again.
- Closes #43715
=> [azure-eventhub] Fix handling of connection strings with entity path

x-pack/filebeat/fbreceiver/receiver_test.go
Skip filebeatreceiver TestMultipleReceivers test until we get a few more fixes in.
=> Skip filebeatreceiver TestMultipleReceivers for now

libbeat/api/server.go, libbeat/api/server_test.go
Add strict ordering to the libbeat API server Start and Stop functions.
Without this it is possible to start the API server multiple times and for the calling of the Stop function to precede the calling of the Start function.
Not an issue in normal beats but in beats receivers when Start and Stop may be called quickly.
``` shell
cd libbeat\api
go test . -v -count 1 -run TestOrdering
```
-
=> enforce ordering of libbeat API server Start/Stop functions

.github/CODEOWNERS
Prevents data plane code owner review being requested when it shouldn't be needed.
=> Remove the data plane team as the changelog fragment owners.

docs/reference/serverless/beats.md
Updates the `Create API key` docs link so it no longer 404s.
=> [DOCS] Update API key link

docs/reference/auditbeat/configuring-ssl-logstash.md, docs/reference/auditbeat/ssl-client-fails.md, docs/reference/filebeat/configuring-ssl-logstash.md, docs/reference/filebeat/ssl-client-fails.md, docs/reference/heartbeat/configuring-ssl-logstash.md, docs/reference/heartbeat/ssl-client-fails.md, docs/reference/metricbeat/configuring-ssl-logstash.md, docs/reference/metricbeat/ssl-client-fails.md, docs/reference/packetbeat/configuring-ssl-logstash.md, docs/reference/packetbeat/ssl-client-fails.md, docs/reference/winlogbeat/configuring-ssl-logstash.md, docs/reference/winlogbeat/ssl-client-fails.md
Closes: https://github.com/elastic/docs-content/issues/2821
Propagates changes established in https://github.com/elastic/beats/pull/46457 to other Beats. 
Also corrects a setting in troubleshooting topics that was not included in the original PR.
=> Doc: Use current Logstash SSL settings for beats
