elastic/beats

libbeat/docs/communitybeats.asciidoc
libbeat/docs/processors-config.asciidoc

Cherrypicks https://github.com/elastic/beats/pull/4845 and https://github.com/elastic/beats/pull/5177 into 5.6. Also fixes example.

Backport: Cherrypick #4845 and #5177 into 5.6 branch

---

CHANGELOG.asciidoc
libbeat/docs/release.asciidoc

* Link to the right docs page
* Fixed a wrongly formatted reference

Fixes for the RC1 changelog

---

libbeat/cmd/instance/beat.go
libbeat/cmd/run.go

Fix minor typos

---

metricbeat/docs/fields.asciidoc
metricbeat/module/elasticsearch/node_stats/_meta/data.json
metricbeat/module/elasticsearch/node_stats/_meta/fields.yml
metricbeat/module/elasticsearch/node_stats/data.go

Closes https://github.com/elastic/beats/issues/5209

Add filesystem stats to ES node_stats metricset

---

libbeat/common/field.go
libbeat/kibana/transform.go
libbeat/kibana/transform_test.go

Added support for more format patterns. 
changes:
Do not override other params if pattern is given.

Support multiple format params.

---

libbeat/cmd/instance/beat.go

Remove `-setup` flag deprecation message

---

libbeat/common/field.go
libbeat/kibana/transform.go
libbeat/kibana/transform_test.go

Add scripts support.

---

CHANGELOG.asciidoc
libbeat/processors/add_docker_metadata/watcher.go

Fix data race accessing watched containers

---

CHANGELOG.asciidoc
libbeat/docs/release.asciidoc

This includes the recent releases and eliminates duplicates.

Changelog cleanup in master

---

CHANGELOG.asciidoc
libbeat/docs/release.asciidoc

- Added missing 5.x releases
- Fixed a miscategorised entry

Cleanup changelog in the 6.0 branch

---

metricbeat/module/kibana/_meta/Dockerfile

Already the compose timeout is set to 300. Now also setting the retries in the healtcheck to 300.

Switch to Kibana 6.0.0-rc1 and increase retry to 300

---

auditbeat/docs/configuring-howto.asciidoc
filebeat/docs/configuring-howto.asciidoc
heartbeat/docs/configuring-howto.asciidoc
libbeat/docs/outputconfig.asciidoc
libbeat/docs/queueconfig.asciidoc
metricbeat/docs/configuring-howto.asciidoc
packetbeat/docs/configuring-howto.asciidoc
winlogbeat/docs/configuring-howto.asciidoc

Cherry-pick of PR #4884 to 6.0 branch. Original message:

Cherry-pick #4884 to 6.0: Add queue settings to docs

---

dev-tools/common.bash
dev-tools/jenkins_ci.sh
dev-tools/jenkins_intake.sh

Cherry-pick of PR #5315 to 6.0 branch. Original message: 
jenkins_setup in common.bash will also be used for the generator tests.

Cherry-pick #5315 to 6.0: Introduce jenkins_setup command to be reused

---

filebeat/docs/filebeat-modules-options.asciidoc
metricbeat/docs/metricbeat-options.asciidoc

Add modules.d info to metricbeat docs

---

libbeat/docs/communitybeats.asciidoc

https://github.com/PPACI/krakenbeat[krakenbeat]:: Collect information on each transaction on the Kraken crypto platform.

Added KrakenBeat

---

libbeat/logp/log.go

Include selector in DEBUG log

---

deploy/kubernetes/.travis/setup.sh

It seems to be failing for v1.7.7, this change should fix it

Fix chown timing issues on k8s deploy

---

CHANGELOG.asciidoc
filebeat/filebeat.full.yml
heartbeat/heartbeat.full.yml
libbeat/_meta/config.full.yml
libbeat/docs/loggingconfig.asciidoc
libbeat/logp/file_rotator.go
libbeat/logp/file_rotator_test.go
metricbeat/metricbeat.full.yml
packetbeat/packetbeat.full.yml
winlogbeat/winlogbeat.full.yml

Cherry-pick of PR #4428 to 5.6 branch. Original message: 
This is a submission for a fix to issue #4295.

Cherry-pick #4428 to 5.6: Add a permissions option to logging.files for all beats

---

CHANGELOG.asciidoc
libbeat/outputs/kafka/log.go

As discussed here:
https://discuss.elastic.co/t/kafka-output-logs-everything-with-warn-level/102259

Determine log level for kafka output

---

.travis.yml
CHANGELOG.asciidoc
Makefile
deploy/kubernetes/.gitignore
deploy/kubernetes/.travis/setup.sh
deploy/kubernetes/Makefile
deploy/kubernetes/README.md
deploy/kubernetes/filebeat-kubernetes.yaml
deploy/kubernetes/filebeat/README.md
deploy/kubernetes/filebeat/filebeat-configmap.yaml
deploy/kubernetes/filebeat/filebeat-daemonset.yaml
deploy/kubernetes/filebeat/filebeat-role-binding.yaml
deploy/kubernetes/filebeat/filebeat-role.yaml
deploy/kubernetes/filebeat/filebeat-service-account.yaml
deploy/kubernetes/metricbeat-kubernetes.yaml
deploy/kubernetes/metricbeat/README.md
deploy/kubernetes/metricbeat/metricbeat-daemonset-configmap.yaml
deploy/kubernetes/metricbeat/metricbeat-daemonset.yaml
deploy/kubernetes/metricbeat/metricbeat-deployment-configmap.yaml
deploy/kubernetes/metricbeat/metricbeat-deployment.yaml
deploy/kubernetes/metricbeat/metricbeat-role-binding.yaml
deploy/kubernetes/metricbeat/metricbeat-role.yaml
deploy/kubernetes/metricbeat/metricbeat-service-account.yaml
dev-tools/packer/Makefile
dev-tools/packer/platforms/kubernetes/build.sh
dev-tools/packer/platforms/kubernetes/run.sh.j2
filebeat/docs/running-on-kubernetes.asciidoc
filebeat/docs/setting-up-running.asciidoc
metricbeat/docs/running-on-kubernetes.asciidoc
metricbeat/docs/setting-up-running.asciidoc

Cherry-pick of PR #5349 #5410 & #5418 to 6.0 branch.
closes #5292

Cherry-pick #5349 to 6.0: Add kubernetes manifests

---

auditbeat/docs/configuring-howto.asciidoc
auditbeat/docs/getting-started.asciidoc
filebeat/docs/configuring-howto.asciidoc
filebeat/docs/filebeat-options.asciidoc
filebeat/docs/getting-started.asciidoc
filebeat/docs/load-balancing.asciidoc
filebeat/docs/modules-getting-started.asciidoc
heartbeat/docs/configuring-howto.asciidoc
heartbeat/docs/getting-started.asciidoc
libbeat/docs/config-file-format.asciidoc
libbeat/docs/shared-template-load.asciidoc
metricbeat/docs/configuring-howto.asciidoc
metricbeat/docs/gettingstarted.asciidoc
packetbeat/docs/configuring-howto.asciidoc
packetbeat/docs/gettingstarted.asciidoc
winlogbeat/docs/configuring-howto.asciidoc
winlogbeat/docs/getting-started.asciidoc

Fixes https://github.com/elastic/beats/issues/5083 and https://github.com/elastic/beats/issues/4391, plus a handful of nits that have bothering me.

Fix getting started

---

libbeat/_meta/kibana/default/index-pattern/libbeat.json
libbeat/docs/version.asciidoc

Please only merge this one on the day of the release.

Bump docs version for 6.0.0-rc2

---

filebeat/harvester/registry.go
filebeat/tests/system/test_prospector.py

pull request #5458 was merged with some outstanding changes

Address some minor comments

---

filebeat/docs/running-on-kubernetes.asciidoc
metricbeat/docs/running-on-kubernetes.asciidoc

Fix typo in Running on Kubernetes docs

---

filebeat/docs/running-on-kubernetes.asciidoc
metricbeat/docs/running-on-kubernetes.asciidoc

Cherry-pick of PR #5529 to 6.0 branch. Original message: 
Current command is wrong

Cherry-pick #5529 to 6.0: Fix typo in Running on Kubernetes docs

---

CHANGELOG.asciidoc
libbeat/docs/release-notes/6.0.0.asciidoc
libbeat/docs/release.asciidoc

Combine all the 6.0.0 changes into a single file.
cc-ed @tsg

Add 6.0.0 release notes

---

dev-tools/packer/version.yml
libbeat/version/version.go

In preparation for the next release. Should be merge after 6.0.0 is
officially out.

Bump version to 6.0.1

---

CHANGELOG.asciidoc
heartbeat/_meta/kibana/default/dashboard/Heartbeat-http-monitor.json

Cherry-pick of PR #5564 to master branch. Original message: 
For some reason the format in which was saved didn't work in Kibana 6.0.
This simply re-saves it again.
Fixes #5562.
I tested with KB 6.0 and 5.6.

Cherry-pick #5564 to master: Fix visualization in Heartbeat dashboards

---

metricbeat/module/windows/perfmon/pdh_integration_windows_test.go

This PR fix a failing integration test for perfmon. See #5571 for more info.

Fix failing perfmon test

---

auditbeat/docs/getting-started.asciidoc
auditbeat/docs/running-on-docker.asciidoc
auditbeat/docs/setting-up-running.asciidoc

Add Docker docs for Auditbeat

---

libbeat/docs/repositories.asciidoc

Closes https://github.com/elastic/beats/issues/5638

Fix prerelease links in apt/yum package docs

---

testing/environments/latest.yml

Update test environment for 'latest' to 6.0.0

---

libbeat/common/field.go
libbeat/kibana/transform.go
libbeat/kibana/transform_test.go

Cherry-Pick 718dbdaf532b126f42c16f6c5df04bddc737f002 to 6.x.

Support openLinkInCurrentTab in Kibana Index Pattern. (#5649)

---

CHANGELOG.asciidoc
libbeat/docs/release-notes/6.0.0.asciidoc
libbeat/docs/release.asciidoc

Copied over the RC2, GA, and consolidated release notes, and eliminated duplicates.
Should get this one merged in before branching out 6.1.

Update CHANGELOG in the master branch

---

packetbeat/protos/http/http.go

FIXED: typo

---

CHANGELOG.asciidoc
metricbeat/module/docker/diskio/diskio_test.go
metricbeat/module/docker/diskio/helper.go

* Fixed docker diskio bug due to reseting of map.
Fixes #5568

Fixed docker diskio bug due to reseting of map. (#5582)

---

heartbeat/_meta/fields.common.yml
heartbeat/docs/fields.asciidoc
heartbeat/monitors/active/http/_meta/fields.yml

Taking over changes from https://github.com/elastic/beats/pull/5324. Thanks @ilyaresh for bringing this up.

Fix typos in Heartbeat fields.yml

---

filebeat/docs/modules/system.asciidoc
filebeat/docs/multiline.asciidoc
filebeat/module/system/_meta/docs.asciidoc

Cherry-picks the following changes into master:
https://github.com/elastic/beats/pull/5356
https://github.com/elastic/beats/pull/5678 - (just the commit containing the compatibility statement)

Forward port to master: Misc doc changes #5356 and #5678

---

dev-tools/packer/xgo-scripts/before_build.sh

Fixes #5753
Previous solution only worked for numeric versions, this should tackle master too

Fix `:doc_branch:` editing

---

filebeat/docs/filebeat-options.asciidoc

Add docs for docker prospector

---

filebeat/docs/filebeat-options.asciidoc

Cherry-pick of PR #5752 to 6.1 branch. Original message: 
This adds docs for #5402

Cherry-pick #5752 to 6.1: Add docs for docker prospector

---

CHANGELOG.asciidoc
NOTICE.txt
vendor/github.com/elastic/gosigar/CHANGELOG.md
vendor/github.com/elastic/gosigar/sigar_freebsd.go
vendor/github.com/elastic/gosigar/sigar_linux_common.go
vendor/github.com/elastic/gosigar/sigar_openbsd.go
vendor/github.com/elastic/gosigar/sigar_stub.go
vendor/github.com/elastic/gosigar/sigar_unix.go
vendor/vendor.json

Updated gosigar to v0.6.0
This PR is required by #5545

Update elastic/gosigar to v0.6.0

---

metricbeat/docs/modules_list.asciidoc

metricbeat/docs/modules_list.asciidoc needs updated in master.

Update modules list for Metricbeat

---

CHANGELOG.asciidoc
libbeat/outputs/logstash/sync.go

Cherry-pick of PR #5799 to 6.1 branch. Original message:

Cherry-pick #5799 to 6.1: Fix logstash debug message

---

libbeat/cmd/completion.go

Forgot to update the visible documentation to the user concerning zsh #5761

Missing mention of the zsh completion formation in the error message

---

CHANGELOG.asciidoc
metricbeat/docs/fields.asciidoc
metricbeat/module/ceph/osd_tree/_meta/fields.yml

Fixing what was detected by `make misspell`.

Fix misspellings

---

dev-tools/packer/version.yml
libbeat/version/version.go

Can be / should be merged today.

Bump version to 6.1.1

---

filebeat/docs/autodiscover-docker-config.asciidoc
filebeat/docs/configuring-howto.asciidoc
libbeat/docs/shared-autodiscover.asciidoc
metricbeat/docs/autodiscover-docker-config.asciidoc
metricbeat/docs/configuring-howto.asciidoc

Cherry-pick of PR #5868 to 6.1 branch. Original message: 
This PR adds documentation for #5245

Cherry-pick #5868 to 6.1: Add docs for autodiscover

---

auditbeat/docs/index.asciidoc
auditbeat/module/audit/kernel/_meta/docs.asciidoc
docs/devguide/index.asciidoc
filebeat/docs/index.asciidoc
heartbeat/docs/index.asciidoc
libbeat/docs/config-file-format.asciidoc
libbeat/docs/index.asciidoc
libbeat/docs/outputconfig.asciidoc
libbeat/docs/shared-note-sudo.asciidoc
libbeat/docs/shared-template-load.asciidoc
libbeat/docs/template-config.asciidoc
libbeat/docs/upgrading.asciidoc
metricbeat/docs/index.asciidoc
packetbeat/docs/index.asciidoc
winlogbeat/docs/index.asciidoc

Cherry-picks the following PRs into the 6.1 branch:
#5784
#5786
#5841
#5848
#5850

Backport to 6.1: Cherrypicks multiple doc changes (#5784 #5786 #5841 #5848 #5850)

---

libbeat/docs/breaking.asciidoc

Fix typo in breaking changes doc

---

filebeat/docs/modules/apache2.asciidoc
filebeat/docs/modules/auditd.asciidoc
filebeat/docs/modules/icinga.asciidoc
filebeat/docs/modules/logstash.asciidoc
filebeat/docs/modules/mysql.asciidoc
filebeat/docs/modules/nginx.asciidoc
filebeat/docs/modules/redis.asciidoc
filebeat/docs/modules/system.asciidoc
filebeat/module/apache2/_meta/docs.asciidoc
filebeat/module/auditd/_meta/docs.asciidoc
filebeat/module/icinga/_meta/docs.asciidoc
filebeat/module/logstash/_meta/docs.asciidoc
filebeat/module/mysql/_meta/docs.asciidoc
filebeat/module/nginx/_meta/docs.asciidoc
filebeat/module/redis/_meta/docs.asciidoc
filebeat/module/system/_meta/docs.asciidoc
libbeat/docs/breaking.asciidoc
libbeat/docs/outputconfig.asciidoc
packetbeat/docs/faq.asciidoc

Cherry-picks the following PRs into the 6.1 branch:
#5849
#5867
#5887
#5890

Backport to 6.1: mutliple doc changes (#5849 #5867 #5887 #5890)

---

filebeat/docs/modules/apache2.asciidoc
filebeat/docs/modules/auditd.asciidoc
filebeat/docs/modules/icinga.asciidoc
filebeat/docs/modules/mysql.asciidoc
filebeat/docs/modules/nginx.asciidoc
filebeat/docs/modules/redis.asciidoc
filebeat/docs/modules/system.asciidoc
filebeat/module/apache2/_meta/docs.asciidoc
filebeat/module/auditd/_meta/docs.asciidoc
filebeat/module/icinga/_meta/docs.asciidoc
filebeat/module/mysql/_meta/docs.asciidoc
filebeat/module/nginx/_meta/docs.asciidoc
filebeat/module/redis/_meta/docs.asciidoc
filebeat/module/system/_meta/docs.asciidoc
libbeat/docs/breaking.asciidoc
libbeat/docs/outputconfig.asciidoc
packetbeat/docs/faq.asciidoc

Cherrypicks the following PRs into 6.0:
#5849
#5867
#5887
#5890

Backport to 6.0: multiple doc changes (#5849 #5867 #5887 #5890)

---

CHANGELOG.asciidoc

Close changelog for 6.1.1

---

deploy/kubernetes/filebeat-kubernetes.yaml
deploy/kubernetes/metricbeat-kubernetes.yaml
libbeat/_meta/kibana/default/index-pattern/libbeat.json
libbeat/docs/version.asciidoc

Should only be merged the day of the release.

Bump docs version to 6.1.1

---

testing/environments/docker/kibana/Dockerfile-snapshot
testing/environments/docker/kibana/bin/kibana-docker
testing/environments/docker/kibana/config/kibana-x-pack.yml

Copy over the most recent changes from elastic/kibana-docker.

Update Kibana docker image

---

libbeat/common/mapstr.go
libbeat/common/mapstr_test.go

This allow more more efficient logging of MapStr objects. Something I expect that will be common.
zapcore.ObjectMarshaler: https://godoc.org/go.uber.org/zap/zapcore#ObjectMarshaler
```
Logging via logger.Infow("msg", logp.Reflected("mapstr", m)) which uses json.Marshal.
BenchmarkMapStrLogging-8   	  200000	      7433 ns/op	    1988 B/op	      43 allocs/op
With MapStr.MarshalLogObject implemented (no sorting).
Logging via logger.Infow("msg", "mapstr", m)
BenchmarkMapStrLogging-8   	  300000	      3986 ns/op	     304 B/op	       9 allocs/op
With MapStr.MarshalLogObject implemented (with sorting).
Logging via logger.Infow("msg", "mapstr", m)
BenchmarkMapStrLogging-8   	  300000	      4492 ns/op	     529 B/op	      17 allocs/op
```

Implement zapcore.ObjectMarshaler for common.MapStr

---

deploy/kubernetes/metricbeat-kubernetes.yaml
deploy/kubernetes/metricbeat/metricbeat-deployment-configmap.yaml

This PR fixed a typo in commet.

Fix typo in metricbeat k8s deploy script

---

CHANGELOG.asciidoc
NOTICE.txt
deploy/kubernetes/filebeat-kubernetes.yaml
deploy/kubernetes/filebeat/filebeat-configmap.yaml
deploy/kubernetes/filebeat/filebeat-daemonset.yaml

Cherry-pick of PR #5963 to 6.1 branch. Original message:

Cherry-pick #5963 to 6.1: Use docker prospector in examples, fixes #5934 and #5920

---

NOTICE.txt

This popped up in different PRs. Here is one fixing it seperately.

Update NOTICE file for 2018

---

heartbeat/docs/heartbeat-options.asciidoc

Cherry-picks #5773 to master branch.

Forward port to master: Update port for SSL/TLS on http monitor (#5773)

---

filebeat/docs/modules/kafka.asciidoc
filebeat/docs/modules/logstash.asciidoc
filebeat/docs/modules/postgresql.asciidoc
filebeat/module/kafka/_meta/docs.asciidoc
filebeat/module/logstash/_meta/docs.asciidoc
filebeat/module/postgresql/_meta/docs.asciidoc
heartbeat/docs/heartbeat-options.asciidoc
packetbeat/docs/gettingstarted.asciidoc
packetbeat/docs/packetbeat-options.asciidoc
packetbeat/docs/shared-protocol-list.asciidoc

Cherry-picks the following PRs into the 6.1 branch:
#5773
#5776
#5877

Backport to 6.1: multiple doc changes (#5773 #5776 #5877)

---

filebeat/docs/autodiscover-docker-config.asciidoc

Fix typo in Filebeat autodiscover examples

---

filebeat/docs/autodiscover-docker-config.asciidoc

Cherry-pick of PR #6000 to 6.1 branch. Original message: 
Closes #5969

Cherry-pick #6000 to 6.1: Fix typo in Filebeat autodiscover examples

---

libbeat/ml-importer/importer_integration_test.go

follow up changes in ML importer integration tests
Closes #5863
(cherry picked from commit f1674b5a45041f1bbc29f3da1be8162717775ff2)

Cherry-pick #5865 to 6.1: Follow up changes in ML importer integration tests

---

CHANGELOG.asciidoc
libbeat/docs/release.asciidoc

Close changelog 6.1.2

---

deploy/kubernetes/filebeat-kubernetes.yaml
deploy/kubernetes/metricbeat-kubernetes.yaml
libbeat/_meta/kibana/default/index-pattern/libbeat.json
libbeat/docs/version.asciidoc

Should be merged only on the release day.

Bump docs version for 6.1.2

---

dev-tools/packer/version.yml
filebeat/filebeat.template-es2x.json
filebeat/filebeat.template-es6x.json
filebeat/filebeat.template.json
heartbeat/heartbeat.template-es2x.json
heartbeat/heartbeat.template-es6x.json
heartbeat/heartbeat.template.json
libbeat/beat/version.go
libbeat/libbeat.template-es6x.json
metricbeat/metricbeat.template-es2x.json
metricbeat/metricbeat.template-es6x.json
metricbeat/metricbeat.template.json
packetbeat/packetbeat.template-es2x.json
packetbeat/packetbeat.template-es6x.json
packetbeat/packetbeat.template.json
winlogbeat/winlogbeat.template-es2x.json
winlogbeat/winlogbeat.template-es6x.json
winlogbeat/winlogbeat.template.json

In preparation for the next release.

Bump version to 5.6.7 in the 5.6 branch

---

auditbeat/docs/index.asciidoc
docs/devguide/index.asciidoc
filebeat/docs/index.asciidoc
heartbeat/docs/index.asciidoc
libbeat/docs/command-reference.asciidoc
libbeat/docs/dashboards.asciidoc
libbeat/docs/faq-refresh-index.asciidoc
libbeat/docs/index.asciidoc
libbeat/docs/shared-beats-attributes.asciidoc
libbeat/docs/shared-note-sudo.asciidoc
libbeat/docs/shared-template-load.asciidoc
metricbeat/docs/index.asciidoc
packetbeat/docs/index.asciidoc
packetbeat/docs/packetbeat-geoip.asciidoc
winlogbeat/docs/index.asciidoc

Cherry-picks #5828 into 6.1 branch.

Backport to 6.1: Show separate commands for deb/rpm and mac (#5828)

---

filebeat/docs/multiline.asciidoc
packetbeat/docs/faq-mysql-ssl.asciidoc
packetbeat/docs/faq.asciidoc

Cherry-picks #5846 and #6014 into the 6.1 branch.

Backport to 6.1: Doc changes in #5846 and #6014

---

NOTICE.txt
vendor/github.com/elastic/go-libaudit/CHANGELOG.md
vendor/github.com/elastic/go-libaudit/audit.go
vendor/vendor.json

Update go-libaudit to v0.0.7

---

CHANGELOG.asciidoc
libbeat/kibana/testdata/extensive/fields.yml
metricbeat/docs/fields.asciidoc
metricbeat/module/kubernetes/state_node/_meta/fields.yml

Closes https://github.com/elastic/beats/issues/6123

Change kubernetes.node.cpu.allocatable.cores to float

---

NOTICE.txt
vendor/github.com/elastic/gosigar/CHANGELOG.md
vendor/github.com/elastic/gosigar/concrete_sigar.go
vendor/github.com/elastic/gosigar/sigar_interface.go
vendor/github.com/elastic/gosigar/sigar_stub.go
vendor/github.com/elastic/gosigar/sigar_unix.go
vendor/github.com/elastic/gosigar/sigar_windows.go
vendor/vendor.json

Update gosigar to v0.8.0

---

NOTICE.txt
vendor/github.com/elastic/gosigar/CHANGELOG.md
vendor/github.com/elastic/gosigar/concrete_sigar.go
vendor/github.com/elastic/gosigar/sigar_interface.go
vendor/github.com/elastic/gosigar/sigar_stub.go
vendor/github.com/elastic/gosigar/sigar_unix.go
vendor/github.com/elastic/gosigar/sigar_windows.go
vendor/vendor.json

(cherry picked from commit e53f42d5e1a12e0a0cbbdfa9837b0e50a91bc097)

Cherry-pick #6147 to 6.2: update gosigar to v0.8.0

---

dev-tools/set_docs_version

Similar to the `dev-toosl/set_version` script. At the moment, it
edits the `version.asciidoc` file and runs `make update`.

Add a dev-tools/set_docs_version script

---

CHANGELOG.asciidoc
libbeat/docs/release.asciidoc
testing/environments/args.yml

Also updated the testing env. Can be merged right away.

Close changelog for the 6.1.3 release

---

libbeat/publisher/pipeline/retry.go

Tiny code improvement by changing the event Guaranteed detected function

---

auditbeat/docs/setting-up-running.asciidoc
filebeat/docs/setting-up-running.asciidoc
heartbeat/docs/setting-up-running.asciidoc
libbeat/docs/command-reference.asciidoc
libbeat/docs/https.asciidoc
libbeat/docs/keystore.asciidoc
metricbeat/docs/setting-up-running.asciidoc
packetbeat/docs/setting-up-running.asciidoc
winlogbeat/docs/setting-up-running.asciidoc

Adds docs for https://github.com/elastic/beats/pull/5687

Add docs about keystore

---

auditbeat/docs/setting-up-running.asciidoc
filebeat/docs/reload-configuration.asciidoc
filebeat/docs/setting-up-running.asciidoc
heartbeat/docs/setting-up-running.asciidoc
libbeat/docs/command-reference.asciidoc
libbeat/docs/https.asciidoc
libbeat/docs/keystore.asciidoc
libbeat/docs/loggingconfig.asciidoc
metricbeat/docs/setting-up-running.asciidoc
packetbeat/docs/setting-up-running.asciidoc
winlogbeat/docs/setting-up-running.asciidoc

Cherrypicks the following PRs into the 6.2 branch:
#6046
#6173
#6186

Backport into 6.2: #6046 #6173 #6186

---

NOTICE.txt
filebeat/docs/multiline.asciidoc
packetbeat/docs/faq-mysql-ssl.asciidoc
packetbeat/docs/faq.asciidoc

Cherry-picks #5846 and #6014 into the 6.0 branch.

Backport to 6.0: Doc changes in #5846 and #6014

---

libbeat/docs/shared-docker.asciidoc

Fix docker dockerfile example for auditbeat

---

libbeat/docs/shared-docker.asciidoc

Cherry-pick of PR #6201 to 6.2 branch. Original message: 
Fixes #6201

Cherry-pick #6201 to 6.2: Fix docker dockerfile example for auditbeat

---

libbeat/docs/dashboardsconfig.asciidoc

Add note about changing the index pattern for 5.x

---

CHANGELOG.asciidoc
libbeat/docs/release.asciidoc
libbeat/docs/version.asciidoc
testing/environments/args.yml

* Close changelog
* Update docs version to 5.6.7
* Update testing env

Prepare 5.6.7 release

---

deploy/kubernetes/filebeat-kubernetes.yaml
deploy/kubernetes/metricbeat-kubernetes.yaml
libbeat/_meta/kibana/default/index-pattern/libbeat.json
libbeat/docs/version.asciidoc

Should be merged on the release day.

Bump docs version to 6.1.3

---

libbeat/common/atomic/atomic32.go
libbeat/common/atomic/atomic64.go
libbeat/common/atomic/atomic_test.go

New types atomic.Int and atomic.Uint using 32/64 bit representations,
depending on architecture.

Add atomic.Int and atomic.Uint

---

CHANGELOG.asciidoc

Removes development tool changes introduced in #6157

Remove development tools changes from CHANGELOG

---

CHANGELOG.asciidoc
libbeat/docs/outputconfig.asciidoc

Add docs update and changelog entry for #6250

---

CHANGELOG.asciidoc
libbeat/docs/release.asciidoc

Brought in the recent releases from the other branches and eliminated the duplicates.

Close changelog for 6.2.0

---

CHANGELOG.asciidoc
libbeat/docs/outputconfig.asciidoc

Cherry-pick of PR #6253 to 6.2 branch. Original message: 
Follow up for #6250.

Cherry-pick #6253 to 6.2: Add docs update and changelog entry for #6250

---

auditbeat/docs/index.asciidoc
filebeat/docs/index.asciidoc
heartbeat/docs/index.asciidoc
libbeat/docs/getting-help.asciidoc
libbeat/docs/index.asciidoc
metricbeat/docs/index.asciidoc
packetbeat/docs/index.asciidoc
winlogbeat/docs/index.asciidoc

Use variables for the discuss forum and the
github repository.

Making docs troubleshooting section more generic.

---

auditbeat/Makefile
dev-tools/packer/platforms/binary/run.sh.j2
dev-tools/packer/platforms/centos/run.sh.j2
dev-tools/packer/platforms/debian/run.sh.j2

Update debian and centos packers to use i386 architecture

---

filebeat/input/docker/input.go

Migrate: Docker prospector to the the input interface

---

auditbeat/docs/page_header.html

Backport to 6.2: Remove experimental banner (#6291)

---

libbeat/docs/shared-autodiscover.asciidoc

Noticed a typo, so made a few minor edits while I had the file open.

Edit autodiscover docs

---

dev-tools/packer/docker/fpm-image/Dockerfile

backport fpm deps fix by @graphaelli

provide fpm deps (#6304)

---

libbeat/docs/keystore.asciidoc

Moved some text around and made a few minor edits based on feedback Jordan S made on a similar topic in the LS Reference.

Add minor edits to keystore docs

---

dev-tools/packer/docker/fpm-image/Dockerfile

Cherry-pick of PR #6302 to 5.6 branch. Original message:
provide fpm deps

Cherry-pick #6302 to 5.6: fix packetbeat devices command

---

testing/environments/args.yml

Let Jenkins get the most recent version..

Cache burst

---

libbeat/docs/shared-autodiscover.asciidoc

Backports #6204 to 6.2 branch.

Backport to 6.2: Edit autodiscover docs

---

script/update_golang_x.py

This script updates vendor/golang.org/x/<name> packages

add script/update_golang_x.py

---

filebeat/input/log/harvester.go

Closes https://github.com/elastic/beats/issues/4512

Improve close_timeout logging

---

libbeat/docs/loggingconfig.asciidoc

Bugfix to resolve the attributes in the
logging configuration example.

Resolve attr vars in logging docs.

---

metricbeat/_meta/fields.common.yml
metricbeat/docs/fields.asciidoc

Fix incorrect default type for metricbeat

---

CHANGELOG.asciidoc
libbeat/docs/release.asciidoc

Includes an entry for #6367. This can be merged right away.

Close changelog for 6.2.2

---

CHANGELOG.asciidoc

Remaining updates for the changelog concerning the prospector -> inputs

---

filebeat/docs/autodiscover-kubernetes-config.asciidoc

Cherry-pick of PR #6386 to master branch. Original message:

Cherry-pick #6386 to master: Typos in filebeat.autodiscover documentation

---

filebeat/scripts/generator/fields/main.go
filebeat/scripts/generator/fields/main_test.go
filebeat/scripts/generator/module/main.go

* add basic test for `make create-fileset`
* add basic test for `make create-fields`
* update `_meta/kibana` layout in fileset generator
* add more types to map
Tests of `make create-fields` will fail until #6110 is merged.
Closes #6161

Add tests for Filebeat generators && minor fixes

---

metricbeat/module/golang/_meta/kibana/6/dashboard/Metricbeat-golang-overview.json

set units to bytes in golang heap graphs

---

filebeat/docs/modules-overview.asciidoc

Forward-ports #5812 (made in 5.3) into 5.6 branch.

Cherrypick into 5.6: #5812

---

CHANGELOG.asciidoc
deploy/kubernetes/filebeat-kubernetes.yaml
deploy/kubernetes/metricbeat-kubernetes.yaml
libbeat/docs/version.asciidoc

Should only be merged in the day of the release.

Prepare 6.2.2 release

---

filebeat/docs/modules-overview.asciidoc

Forward-ports #5812 (made in 5.3) into 5.5 branch.

Cherrypick into 5.5: PR #5812

---

filebeat/docs/modules-overview.asciidoc

Forward-ports #5812 (made in 5.3) into 5.4 branch.

Cherrypick into 5.4: PR #5812

---

libbeat/docs/keystore.asciidoc
libbeat/docs/loggingconfig.asciidoc
metricbeat/_meta/fields.common.yml
metricbeat/docs/fields.asciidoc
metricbeat/docs/gettingstarted.asciidoc

Cherry-picks the following PRs into the 6.2 branch: #6322, #6356, #6358, and #6364

Cherrypick into 6.2: #6322, #6356, #6358, and #6364

---

CHANGELOG.asciidoc

The IIS module have added an empty line to the changelog.

Remove unnecessary line in the changelog

---

filebeat/fileset/modules.go

typo in errormessage in  modules.go

---

libbeat/docs/communitybeats.asciidoc

Features:
- Updated to Beats 6.2.1
- Updated to Golang 1.9.4
- Burrow V1.0.0(API V3) Support
- Docker Support

Added hsnburrowbeat to Community Beats

---

dev-tools/packer/Makefile
dev-tools/packer/docker/xgo-image-deb6/.gitignore
dev-tools/packer/docker/xgo-image-deb6/beats-builder/Dockerfile
dev-tools/packer/docker/xgo-image-deb6/build.sh
dev-tools/packer/docker/xgo-image/.gitignore
dev-tools/packer/docker/xgo-image/beats-builder/Dockerfile
dev-tools/packer/docker/xgo-image/build.sh
dev-tools/packer/docker/xgo-image/push_image.md
dev-tools/vendor/github.com/tsg/gotpl/LICENSE
dev-tools/vendor/github.com/tsg/gotpl/README.md
dev-tools/vendor/github.com/tsg/gotpl/tpl.go
dev-tools/vendor/gopkg.in/yaml.v2/LICENSE
dev-tools/vendor/gopkg.in/yaml.v2/LICENSE.libyaml
dev-tools/vendor/gopkg.in/yaml.v2/README.md
dev-tools/vendor/gopkg.in/yaml.v2/apic.go
dev-tools/vendor/gopkg.in/yaml.v2/decode.go
dev-tools/vendor/gopkg.in/yaml.v2/emitterc.go
dev-tools/vendor/gopkg.in/yaml.v2/encode.go
dev-tools/vendor/gopkg.in/yaml.v2/parserc.go
dev-tools/vendor/gopkg.in/yaml.v2/readerc.go
dev-tools/vendor/gopkg.in/yaml.v2/resolve.go
dev-tools/vendor/gopkg.in/yaml.v2/scannerc.go
dev-tools/vendor/gopkg.in/yaml.v2/sorter.go
dev-tools/vendor/gopkg.in/yaml.v2/writerc.go
dev-tools/vendor/gopkg.in/yaml.v2/yaml.go
dev-tools/vendor/gopkg.in/yaml.v2/yamlh.go
dev-tools/vendor/gopkg.in/yaml.v2/yamlprivateh.go
dev-tools/vendor/vendor.json

This backports #6448 #6459 and #6461 to the 5.6 branch.

Backport packaging fixes 5.6

---

filebeat/Makefile

else "make collect" fails on clean build

Update Makefile add python-env to fields

---

CHANGELOG.asciidoc
heartbeat/docs/fields.asciidoc
heartbeat/monitors/active/http/_meta/fields.yml

This takes over the PR https://github.com/elastic/beats/pull/6263

Make the url field of heartbeat aggregatable.

---

metricbeat/module/kubernetes/event/config.go
metricbeat/module/kubernetes/event/event.go

Fixes a misspelling of Kubernetes

fix misspelling of Kubernetes

---

.travis.yml
metricbeat/Makefile
metricbeat/docker-compose.yml

This PR is a subset of https://github.com/elastic/beats/pull/5945 to remove the Metricbeat changes from the PR.

Cleanup Metricbeat composer and Makefile

---

metricbeat/docs/modules/kubernetes.asciidoc
metricbeat/metricbeat.reference.yml
metricbeat/module/kubernetes/_meta/config.yml
metricbeat/modules.d/kubernetes.yml.disabled

Taking over https://github.com/elastic/beats/pull/6048

Add k8s ssl example

---

auditbeat/docs/reload-configuration.asciidoc

Remove `auditbeat.modules:` from config reload example file. And change Glob to glob.

Fix config reload example

---

filebeat/input/log/harvester.go

A data race was sometimes triggered by system tests where a harvester is Run() and Stop()'ed in quick succession from different goroutines.
It is necessary to protect access to a sync.WaitGroup with a mutex to prevent wg.Add(1) and wg.Wait() to execute concurrently.
This race condition had little or no impact in real world usage.
Failed tests for #6341

Fix data race in harvester termination

---

auditbeat/docs/fields.asciidoc
filebeat/docs/fields.asciidoc
heartbeat/docs/fields.asciidoc
libbeat/processors/add_host_metadata/_meta/fields.yml
metricbeat/docs/fields.asciidoc
packetbeat/docs/fields.asciidoc
winlogbeat/docs/fields.asciidoc

Some of the fields were object instead of keyword.

Fix types in host.os fields

---

metricbeat/docs/running-on-docker.asciidoc

I add to format the host like this so go-sql-driver could parse it correctly.

Update hosts example

---

dev-tools/generate_notice.py

As seen in https://github.com/IQAndreas/markdown-licenses
We found it first in #6265

Add markdown-formatted Apache 2 title fo notice generator

---

libbeat/docs/shared-config-ingest.asciidoc

Changed title because it was slightly misleading. Also made line wraps consistent.

Modify title to indicate that ingest node is used for more than logs

---

filebeat/docs/inputs/input-common-harvester-options.asciidoc
filebeat/docs/modules/kafka.asciidoc
filebeat/docs/modules/traefik.asciidoc
filebeat/module/kafka/_meta/docs.asciidoc
filebeat/module/traefik/_meta/docs.asciidoc

Remove old reviewer notes

---

dev-tools/generate_notice.py

To support elastic/apm-server#460 - NOTICE there has revisions pointing to beats rather than the original dependencies, since they are transitive and govendor doesn't preserve that information.  This change should have no impact on beats directly.

support revision overrides for notice generation

---

CHANGELOG.asciidoc

Add changelog entry removed by mistake on dcdfa7dd80ee03264fa041f32f053e7f4ba547af

Add changelog entry for system.raid promotion to beta

---

metricbeat/docs/modules/jolokia.asciidoc
metricbeat/metricbeat.reference.yml
metricbeat/module/jolokia/_meta/config.yml
metricbeat/modules.d/jolokia.yml.disabled

Closes #6643 
I also added a few examples of MBeans config

Fix differences in Jolokia config examples (#6643)

---

metricbeat/docs/modules/kubernetes.asciidoc
metricbeat/metricbeat.reference.yml
metricbeat/module/kubernetes/_meta/config.reference.yml
metricbeat/module/kubernetes/_meta/config.yml
metricbeat/module/kubernetes/_meta/docs.asciidoc
metricbeat/module/kubernetes/container/container.go
metricbeat/module/kubernetes/node/node.go
metricbeat/module/kubernetes/pod/pod.go
metricbeat/module/kubernetes/system/system.go
metricbeat/module/kubernetes/volume/volume.go
metricbeat/modules.d/kubernetes.yml.disabled

Set default metricsets for kubernetes module.

---

CHANGELOG.asciidoc
libbeat/docs/release.asciidoc

Copied the recent releases from the 6.2 branch and removed the duplicates.

Cleanup changelog

---

metricbeat/docs/modules_list.asciidoc
metricbeat/scripts/docs_collector.py

Remove lines in dashboard check column. See https://github.com/elastic/beats/pull/6686#issuecomment-379015793

Improve module overview list

---

libbeat/docs/step-configure-credentials.asciidoc

Fixes https://github.com/elastic/beats/issues/6649

Document role required to load dashboards

---

CHANGELOG.asciidoc
libbeat/docs/release.asciidoc

Close changelog 6.2.4

---

deploy/kubernetes/filebeat-kubernetes.yaml
deploy/kubernetes/metricbeat-kubernetes.yaml
libbeat/docs/version.asciidoc

Should be merged only on the day of the release.

Bump docs version for 6.2.4

---

CHANGELOG.asciidoc
libbeat/cfgfile/reload.go

This PR makes config reloading GA. A follow up PR with potential config changes is in https://github.com/elastic/beats/pull/6883.

Make config reloading GA

---

libbeat/docs/communitybeats.asciidoc

Added nsqbeat to the community beat list.
nsqbeat supports nsq.io as a message broker for input data

Added nsqbeat

---

libbeat/scripts/Makefile
testing/environments/args.yml

6.2.3 Snapshots are not available anymore.

Update 6.2 snapshot build to 6.2.5

---

CHANGELOG.asciidoc
libbeat/cmd/instance/metrics.go
libbeat/metric/system/process/process.go
libbeat/metric/system/process/process_linux.go
libbeat/metric/system/process/process_other.go
libbeat/metric/system/process/process_test.go

Fix self metrix when containerised (backport to 6.2)

---

libbeat/docs/shared-directory-layout.asciidoc

Backports https://github.com/elastic/beats/pull/6557

Backport to 6.2: #6557

---

filebeat/beater/filebeat.go
libbeat/setup/kibana/client.go

Cherry-pick of PR #6991 to 6.3 branch. Original message:
* detect error during requesting status info of Kibana
* add missing whitespace

Cherry-pick #6991 to 6.3: Detect error during requesting status info from Kibana

---

winlogbeat/checkpoint/checkpoint_test.go

Tests in the checkpoint package were susceptible to the timing of certain writes to disk, which caused intermittent failures in CI. Replaced hardcoded delays with an adaptative timeout check.

Winlogbeat: Replace hardcoded delays in checkpoint tests

---

metricbeat/module/kubernetes/_meta/Dockerfile

This is an attempt to further stabalise k8s tests.

Increase retries for k8s healthchecks

---

metricbeat/module/elasticsearch/node/_meta/data.json
metricbeat/module/elasticsearch/node/data.go
metricbeat/module/elasticsearch/node/data_test.go
metricbeat/module/elasticsearch/node/node.go
metricbeat/module/elasticsearch/node/node_integration_test.go
metricbeat/module/elasticsearch/node_stats/data.go
metricbeat/module/elasticsearch/test_elasticsearch.py

* Simplify Elasticsearch system tests
* Add service.name field

Update elasticsearch/node metricset to use reporter interface

---

dev-tools/packer/Makefile
dev-tools/packer/platforms/binary/build.sh
dev-tools/packer/platforms/binary/run.sh.j2
dev-tools/packer/platforms/centos/build.sh
dev-tools/packer/platforms/centos/run.sh.j2
dev-tools/packer/platforms/darwin/build.sh
dev-tools/packer/platforms/darwin/run.sh.j2
dev-tools/packer/platforms/dashboards/build.sh
dev-tools/packer/platforms/debian/build.sh
dev-tools/packer/platforms/debian/run.sh.j2
dev-tools/packer/platforms/windows/build.sh
dev-tools/packer/platforms/windows/run.sh.j2
dev-tools/packer/xgo-scripts/before_build.sh
libbeat/scripts/Makefile

Add ENV variable to allow removal of `beat.reference.yml`.

Make beat.reference.yml optional.

---

libbeat/docs/keystore.asciidoc

{beatname_lc} keystore remove ES_PWD  is rangit

delect keystore doc error

---

CHANGELOG.asciidoc
libbeat/docs/release.asciidoc

Contains minor formatting fixes.

Close changelog for 6.3.0

---

libbeat/docs/command-reference.asciidoc
libbeat/docs/dashboards.asciidoc

Adds a link to the dev guide, where we describe additional options for dashboard loading.

Add link to topic that desribes more dashboard loading options

---

packetbeat/protos/http/http.go

Just resolving the todo now that Beats uses 1.10 :)

MINOR: Resolve string concatenation todo in packetbeat/.../http.go

---

docs/devguide/modules-dev-guide.asciidoc

* remove unreleased `--update-pipeline` flag && add `setup --pipelines` command to update Ingest pipelines
* add a section about `make update`

Update Filebeat modules development guide

---

heartbeat/docs/heartbeat-options.asciidoc
libbeat/docs/command-reference.asciidoc
libbeat/docs/dashboards.asciidoc
libbeat/docs/outputconfig.asciidoc
libbeat/docs/shared-path-config.asciidoc
libbeat/docs/shared-ssl-config.asciidoc

Cherry-picks the following doc changes into the 6.2 branch:
https://github.com/elastic/beats/pull/7180
https://github.com/elastic/beats/pull/7233 
https://github.com/elastic/beats/pull/7236

Backport to 6.2: Cherrypicks mutliple changes (#7180 #7233  #7236)

---

auditbeat/docs/getting-started.asciidoc
docs/devguide/index.asciidoc
docs/devguide/newdashboards.asciidoc
filebeat/docs/getting-started.asciidoc
heartbeat/docs/getting-started.asciidoc
heartbeat/docs/heartbeat-options.asciidoc
libbeat/docs/command-reference.asciidoc
libbeat/docs/dashboards.asciidoc
libbeat/docs/https.asciidoc
libbeat/docs/keystore.asciidoc
libbeat/docs/outputconfig.asciidoc
libbeat/docs/security/basic-auth.asciidoc
libbeat/docs/security/user-access.asciidoc
libbeat/docs/shared-beats-attributes.asciidoc
libbeat/docs/shared-path-config.asciidoc
libbeat/docs/shared-ssl-config.asciidoc
libbeat/docs/shared-template-load.asciidoc
metricbeat/docs/gettingstarted.asciidoc
metricbeat/docs/modules/elasticsearch.asciidoc
metricbeat/docs/modules/kibana.asciidoc
metricbeat/module/elasticsearch/_meta/docs.asciidoc
metricbeat/module/kibana/_meta/docs.asciidoc
packetbeat/docs/gettingstarted.asciidoc
winlogbeat/_meta/fields.yml
winlogbeat/docs/fields.asciidoc
winlogbeat/docs/getting-started.asciidoc
winlogbeat/docs/overview.asciidoc

Cherry-picks the following doc changes into the 6.3 branch:
https://github.com/elastic/beats/pull/6985
https://github.com/elastic/beats/pull/7014
https://github.com/elastic/beats/pull/7180
https://github.com/elastic/beats/pull/7233
https://github.com/elastic/beats/pull/7236
https://github.com/elastic/beats/pull/7246

Backport to 6.3: Cherrypicks mutliple changes (#6985 #7014 #7180 #7233 #7236 #7246)

---

auditbeat/Makefile
auditbeat/module/auditd/_meta/kibana/6/dashboard/auditbeat-kernel-executions.json
auditbeat/module/auditd/_meta/kibana/6/dashboard/auditbeat-kernel-overview.json
auditbeat/module/auditd/_meta/kibana/6/dashboard/auditbeat-kernel-sockets.json
auditbeat/module/file_integrity/_meta/kibana/6/dashboard/auditbeat-file-integrity.json

Follow up from #7224 for Auditbeat.

Decode versioned Auditbeat dashboards

---

filebeat/Makefile
filebeat/module/apache2/_meta/kibana/6/dashboard/Filebeat-apache2.json
filebeat/module/auditd/_meta/kibana/6/dashboard/Filebeat-auditd.json
filebeat/module/icinga/_meta/kibana/6/dashboard/Filebeat-icinga-debug-log.json
filebeat/module/icinga/_meta/kibana/6/dashboard/Filebeat-icinga-main-log.json
filebeat/module/icinga/_meta/kibana/6/dashboard/Filebeat-icinga-startup-errors.json
filebeat/module/iis/_meta/kibana/6/dashboard/Filebeat-iis.json
filebeat/module/kafka/_meta/kibana/6/dashboard/Filebeat-Kafka-overview.json
filebeat/module/logstash/_meta/kibana/6/dashboard/Filebeat-logstash-log.json
filebeat/module/logstash/_meta/kibana/6/dashboard/Filebeat-logstash-slowlog.json
filebeat/module/mongodb/_meta/kibana/6/dashboard/Filebeat-Mongodb-overview.json
filebeat/module/mysql/_meta/kibana/6/dashboard/Filebeat-mysql.json
filebeat/module/nginx/_meta/kibana/6/dashboard/Filebeat-nginx-logs.json
filebeat/module/nginx/_meta/kibana/6/dashboard/Filebeat-nginx-overview.json
filebeat/module/nginx/_meta/kibana/6/dashboard/ml-nginx-access-remote-ip-count-explorer.json
filebeat/module/nginx/_meta/kibana/6/dashboard/ml-nginx-remote-ip-url-explorer.json
filebeat/module/osquery/_meta/kibana/6/dashboard/osquery-compliance.json
filebeat/module/osquery/_meta/kibana/6/dashboard/osquery-rootkit.json
filebeat/module/postgresql/_meta/kibana/6/dashboard/Filebeat-Postgresql-overview.json
filebeat/module/postgresql/_meta/kibana/6/dashboard/Filebeat-Postgresql-slowlogs.json
filebeat/module/redis/_meta/kibana/6/dashboard/Filebeat-redis.json
filebeat/module/system/_meta/kibana/6/dashboard/Filebeat-auth-sudo-commands.json
filebeat/module/system/_meta/kibana/6/dashboard/Filebeat-new-users-and-groups.json
filebeat/module/system/_meta/kibana/6/dashboard/Filebeat-ssh-login-attempts.json
filebeat/module/system/_meta/kibana/6/dashboard/Filebeat-syslog.json
filebeat/module/traefik/_meta/kibana/6/dashboard/Filebeat-traefik-overview.json
filebeat/module/traefik/_meta/kibana/6/dashboard/ml-traefik-access-remote-ip-count-explorer.json
filebeat/module/traefik/_meta/kibana/6/dashboard/ml-traefik-remote-ip-url-explorer.json

Follow up from #7224 for Filebeat.

 Decode versioned Filebeat dashboards

---

libbeat/docs/keystore.asciidoc

Cherry-picks the following PR into master:
https://github.com/elastic/beats/pull/7246

Forward port to master: Fix keystore example (#7246)

---

libbeat/docs/queueconfig.asciidoc

Cherry-pick of PR #6902 to 6.3 branch. Original message:

Cherry-pick #6902 to 6.3: Add file spool to queue docs

---

CHANGELOG.asciidoc
libbeat/docs/release.asciidoc

Can be merged, we don't need to wait for the release day.

Close changelog for 5.6.10

---

libbeat/docs/command-reference.asciidoc

Added a header and converted the list to table format to remove any ambiguity wrt what the list contains.
Output looks like this:

Adds table header to command summary table

---

filebeat/docs/autodiscover-hints.asciidoc

Cherry-pick of PR #7226 to 6.3 branch. Original message:

Cherry-pick #7226 to 6.3: Fix beat name in Filebeat hints autodiscover example

---

filebeat/docs/autodiscover-hints.asciidoc
metricbeat/docs/autodiscover-hints.asciidoc

This PR updates docs for hints based autodiscover. It adds more detail to all supported parameters, with more examples and explanations.

Review hints based autodiscover docs

---

filebeat/docs/autodiscover-hints.asciidoc
metricbeat/docs/autodiscover-hints.asciidoc

Cherry-pick of PR #7228 to 6.3 branch. Original message: 
This PR updates docs for hints based autodiscover. It adds more detail to all supported parameters, with more examples and explanations.

Cherry-pick #7228 to 6.3: Review hints based autodiscover docs

---

filebeat/filebeat.reference.yml
libbeat/docs/keystore.asciidoc
libbeat/docs/yaml.asciidoc
packetbeat/docs/gettingstarted.asciidoc
packetbeat/docs/packetbeat-options.asciidoc

Implements and/or cherry-picks minor doc changes.
Fixes should probably be backported to 6.2 and 6.3

Minor doc fixes

---

auditbeat/auditbeat.reference.yml
auditbeat/docs/index.asciidoc
filebeat/docs/index.asciidoc
filebeat/filebeat.reference.yml
heartbeat/docs/index.asciidoc
heartbeat/heartbeat.reference.yml
libbeat/_meta/config.reference.yml
libbeat/docs/command-reference.asciidoc
libbeat/docs/contributing-to-beats.asciidoc
libbeat/docs/index.asciidoc
libbeat/docs/outputconfig.asciidoc
metricbeat/docs/index.asciidoc
metricbeat/metricbeat.reference.yml
packetbeat/docs/index.asciidoc
packetbeat/packetbeat.reference.yml
winlogbeat/docs/index.asciidoc
winlogbeat/winlogbeat.reference.yml

Cherry-picks the following doc PRs into 6.3 branch:
#6903
#7279
#7302

Backport to 6.3: cherrypick multiple doc changes (#6903 #7279 #7302)

---

filebeat/docs/migration.asciidoc
libbeat/docs/shared-faq.asciidoc
libbeat/docs/shared-logstash-config.asciidoc

Fixes links broken by moving the GS to the stack guide.

Fix broken doc links

---

CHANGELOG.asciidoc
libbeat/docs/release.asciidoc

Close changelog 6.3.1

---

libbeat/docs/dashboardsconfig.asciidoc

Forward port to master: add note about overwriting dashboards (#6828)

---

libbeat/docs/shared-ssl-logstash-config.asciidoc
libbeat/docs/yaml.asciidoc
packetbeat/docs/gettingstarted.asciidoc
packetbeat/docs/packetbeat-options.asciidoc

Cherrypicks the following PRs into the 6.2 branch:
https://github.com/elastic/beats/pull/6428
https://github.com/elastic/beats/pull/7360

Backport to 6.2: Cherrypick #6428 and #7360

---

libbeat/docs/breaking.asciidoc

Backport to 6.3: Add breaking change about host namespace causing mapping issues (#7398)

---

libbeat/docs/shared-autodiscover.asciidoc

I also updated the format for Jolokia provider parameters

Add missing docs for kubernetes autodiscover provider parameters

---

deploy/kubernetes/filebeat-kubernetes.yaml
deploy/kubernetes/metricbeat-kubernetes.yaml
libbeat/docs/version.asciidoc

Can be merged, because it's release day.

Bump docs version for 6.3.1

---

Makefile

https://github.com/elastic/beats/pull/7456#issuecomment-402734994

Fix update target to get pkg/errors

---

Makefile

Per https://github.com/client9/misspell/blame/8f053a4c89062b932a9007d6e4bdbfdd8a990773/README.md#L22

Improve misspell rule

---

heartbeat/look/look_test.go

Add a few tests to heartbeat's look.go

Add tests to heartbeat's look.go

---

libbeat/docs/processors-using.asciidoc

Replaces https://github.com/elastic/beats/pull/7038

Clarify docs to indicate where processors are valid in the config

---

libbeat/publisher/queue/queue_reg.go

Remove unneeded queue code

---

libbeat/docs/command-reference.asciidoc
libbeat/docs/index.asciidoc
libbeat/docs/outputconfig.asciidoc
libbeat/docs/security/securing-beats.asciidoc
libbeat/docs/shared-logstash-config.asciidoc
libbeat/docs/shared-securing-beat.asciidoc
libbeat/docs/shared-template-load.asciidoc

This is to support https://github.com/elastic/apm-server/pull/1103.  While that's still in review, it's moving along and I'd like to know if there are any objections here that need to be factored in there.

add conditionals to support apm-server docs update

---

CHANGELOG.asciidoc

Add missing changelog entry for https://github.com/elastic/beats/pull/7568

Add missing changlelog entry about missing logs

---

docs/devguide/modules-dev-guide.asciidoc

- Replace export_dashboard example to use the recommended `-yml` option
- Add a link to export_dashboard's doc

Update Filebeat module dev guide

---

libbeat/docs/security/securing-beats.asciidoc

Filebeat modules aren't relevant outside of Filebeat, so I should have conditionally coded this.

Add conditional coding to security topic

---

docs/devguide/newbeat.asciidoc
libbeat/docs/shared-docker.asciidoc
metricbeat/docs/running-on-docker.asciidoc

Cherrypicks the following PRs into the master branch:
https://github.com/elastic/beats/pull/5762
https://github.com/elastic/beats/pull/6725

Forward port to master: multiple doc changes (#5762 #6725)

---

docs/devguide/newbeat.asciidoc
libbeat/docs/breaking.asciidoc
libbeat/docs/processors-using.asciidoc
libbeat/docs/security/securing-beats.asciidoc
libbeat/docs/shared-autodiscover.asciidoc
libbeat/docs/shared-docker.asciidoc
libbeat/docs/shared-ssl-config.asciidoc
metricbeat/docs/running-on-docker.asciidoc

Cherrypicks the following PRs into the 6.3 branch: 
https://github.com/elastic/beats/pull/5762
https://github.com/elastic/beats/pull/6725
https://github.com/elastic/beats/pull/7085
https://github.com/elastic/beats/pull/7436
https://github.com/elastic/beats/pull/7468
https://github.com/elastic/beats/pull/7478
https://github.com/elastic/beats/pull/7490
https://github.com/elastic/beats/pull/7602

Backport to 6.3: multiple doc changes (#5762 #6725 #7085 #7436 #7468 #7478 #7490 #7602)

---

filebeat/module/elasticsearch/slowlog/ingest/pipeline.json
filebeat/module/elasticsearch/slowlog/test/test.log-expected.json

- by breaking index name and ID,
- unifies usage of 'space' grok pattern

Improves pipeline for Filebeat slowlog fileset

---

filebeat/module/elasticsearch/server/ingest/pipeline.json
filebeat/module/elasticsearch/server/test/test.log-expected.json

- improves regex pattern for index names
- unifies usage of 'space' grok pattern

Improves pipeline Filebeat server fileset

---

libbeat/processors/actions/rename.go

Instead of the from field the to field was logged.

Fix rename log message

---

CHANGELOG.asciidoc
libbeat/docs/release.asciidoc

Close changelog for 6.3.2

---

libbeat/docs/breaking.asciidoc

Cherrypicks original commit plus edits from #7666 back into master.

Forward port to master: Monitoring breaking changes plus #7666

---

metricbeat/docs/modules/kubernetes.asciidoc
metricbeat/docs/modules/kubernetes/apiserver.asciidoc
metricbeat/docs/modules/kvm.asciidoc
metricbeat/docs/modules/munin.asciidoc
metricbeat/docs/modules/uwsgi.asciidoc
metricbeat/docs/modules_list.asciidoc
metricbeat/module/kubernetes/apiserver/_meta/docs.asciidoc
metricbeat/module/kvm/_meta/docs.asciidoc
metricbeat/module/kvm/dommemstat/_meta/docs.asciidoc
metricbeat/module/munin/_meta/docs.asciidoc
metricbeat/module/munin/node/_meta/docs.asciidoc
metricbeat/module/traefik/health/_meta/docs.asciidoc
metricbeat/module/uwsgi/_meta/docs.asciidoc
metricbeat/scripts/module/docs.asciidoc
metricbeat/scripts/module/metricset/docs.asciidoc

Closes https://github.com/elastic/beats/issues/7643

Fix duplicated module headers

---

libbeat/tests/system/requirements.txt

Needed for https://github.com/elastic/apm-server/pull/1168

Add jsondiff to test requirements.

---

winlogbeat/tests/system/winlogbeat.py

clear_event_log before removing it from registry

---

libbeat/scripts/Makefile

It's not required and published anywhere.

Disable fields.asciidoc generator for libbeat

---

libbeat/docs/outputconfig.asciidoc

Adding an information about minimum and maximum possible number of files

Detailed information about number of files

---

libbeat/docs/shared-autodiscover.asciidoc

Indentation was wrong, this change fixes it

Fix autodiscover appenders example indentation

---

auditbeat/docs/setting-up-running.asciidoc
filebeat/docs/setting-up-running.asciidoc
heartbeat/docs/setting-up-running.asciidoc
metricbeat/docs/setting-up-running.asciidoc
packetbeat/docs/setting-up-running.asciidoc
winlogbeat/docs/setting-up-running.asciidoc

Forward port to 6.3: Fix anchor ID in docs

---

auditbeat/docs/setting-up-running.asciidoc
filebeat/docs/setting-up-running.asciidoc
heartbeat/docs/setting-up-running.asciidoc
metricbeat/docs/setting-up-running.asciidoc
packetbeat/docs/setting-up-running.asciidoc
winlogbeat/docs/setting-up-running.asciidoc

 Forward port to 6.2: Fix anchor ID in docs

---

auditbeat/docs/setting-up-running.asciidoc
filebeat/docs/setting-up-running.asciidoc
heartbeat/docs/setting-up-running.asciidoc
metricbeat/docs/setting-up-running.asciidoc
packetbeat/docs/setting-up-running.asciidoc
winlogbeat/docs/setting-up-running.asciidoc

Forward ports https://github.com/elastic/beats/pull/7856 to 6.1.

Forward port to 6.1: Fix anchor ID in docs

---

auditbeat/docs/configuring-howto.asciidoc
filebeat/docs/configuring-howto.asciidoc
heartbeat/docs/configuring-howto.asciidoc
libbeat/docs/http-endpoint.asciidoc
metricbeat/docs/configuring-howto.asciidoc
packetbeat/docs/configuring-howto.asciidoc
winlogbeat/docs/configuring-howto.asciidoc

This endpoint provides internal beat stats for debugging/monitoring.

Document HTTP endpoint

---

libbeat/conditions/conditions.go
libbeat/conditions/conditions_test.go
libbeat/conditions/equals.go
libbeat/conditions/extractors.go
libbeat/conditions/matcher.go
libbeat/conditions/not.go
libbeat/conditions/not_test.go
libbeat/conditions/range.go

Clean up a few error and warning messages

Used named logger in condition package

---

auditbeat/auditbeat.reference.yml
filebeat/docs/autodiscover-hints.asciidoc
filebeat/docs/inputs/input-common-file-options.asciidoc
filebeat/docs/modules/kibana.asciidoc
filebeat/filebeat.reference.yml
filebeat/module/kibana/_meta/docs.asciidoc
filebeat/scripts/module/_meta/docs.asciidoc
heartbeat/heartbeat.reference.yml
libbeat/_meta/config.reference.yml
libbeat/docs/command-reference.asciidoc
libbeat/docs/template-config.asciidoc
metricbeat/metricbeat.reference.yml
packetbeat/packetbeat.reference.yml
winlogbeat/winlogbeat.reference.yml

Cherry-picks the following PRs into the 6.4 branch:
https://github.com/elastic/beats/pull/7696
https://github.com/elastic/beats/pull/7889
https://github.com/elastic/beats/pull/7903
https://github.com/elastic/beats/pull/7937
https://github.com/elastic/beats/pull/7949

Backport to 6.4: Multiple doc changes (#7696 #7889 #7903 #7937 #7949)

---

CHANGELOG.asciidoc

Cherry-pick of PR #8001 to 6.x branch. Original message:

Cherry-pick #8001 to 6.x: Fix changelog entry

---

CHANGELOG.asciidoc

Cherry-pick of PR #8001 to 6.4 branch. Original message:

Cherry-pick #8001 to 6.4: Fix changelog entry

---

filebeat/docs/inputs/input-log.asciidoc

Closes issue  https://github.com/elastic/beats/issues/7386
@ppf2 FYI

Recommend that users avoid harvesting symlinks when files are rotated

---

winlogbeat/checkpoint/checkpoint.go

During testing it was possible for two goroutines to be reading and writing
to the checkpoint file. This change adds a RWMutex that guards against
the persist() method and the read() method from stepping on each other.
Fixes #7897

Add RW lock to Winlogbeat checkpoint

---

libbeat/docs/version.asciidoc

Please wait for the release day before merging this one.

Bump docs version for 5.6.11

---

CHANGELOG.asciidoc

Documents the known issue and the workaround for #8104.

Document known issue in 6.4.0

---

metricbeat/docker-compose.yml
metricbeat/tests/system/test_kubernetes.py

They are not deterministic as of today, the kubernetes docker-compose
is failing sometimes.
Closes #7973

Disable kubernetes integration tests

---

filebeat/docs/migration.asciidoc
filebeat/docs/modules-getting-started.asciidoc
libbeat/docs/gettingstarted.asciidoc
libbeat/docs/shared-download-and-install.asciidoc
libbeat/docs/shared-getting-started-intro.asciidoc
libbeat/docs/shared-logstash-config.asciidoc
metricbeat/docs/modules/jolokia.asciidoc
metricbeat/module/jolokia/_meta/docs.asciidoc
metricbeat/module/jolokia/jmx/_meta/docs.asciidoc
winlogbeat/docs/getting-started.asciidoc

Cherry-picks the following PRs into the 6.x branch: 
#7969 
#8172

Backport to 6.x: #7969  and #8172

---

.travis.yml

Cherry-pick of PR #8217 to 6.x branch. Original message:

Cherry-pick #8217 to 6.x: Add travis job to test docs build

---

metricbeat/module/system/_meta/kibana/6/dashboard/Metricbeat-host-overview.json

Fixes a simple typo in the dashboard description.

Metricbeat: Fix typo in dashboard template

---

libbeat/docs/index.asciidoc
libbeat/docs/monitoring/monitoring-beats.asciidoc
libbeat/docs/security/beats-system.asciidoc
libbeat/docs/security/securing-beats.asciidoc
libbeat/docs/shared-beats-attributes.asciidoc

to support apm-server xpack monitoring documentation needed for elastic/apm-server#1378.

parameterize beat monitoring docs

---

heartbeat/beater/manager.go
heartbeat/scheduler/schedule/schedule_test.go
heartbeat/scheduler/scheduler.go
heartbeat/scheduler/scheduler_test.go

This commit aims to improve test coverage of these important packages.
It also makes some tiny changes to scheduler.go to improve understanding of some of the code.

Heartbeat Scheduler Tests

---

heartbeat/beater/manager.go
heartbeat/scheduler/schedule/schedule_test.go
heartbeat/scheduler/scheduler.go
heartbeat/scheduler/scheduler_test.go

Cherry-pick of PR #8073 to 6.x branch. Original message: 
This commit aims to improve test coverage of these important packages.
It also makes some tiny changes to scheduler.go to improve understanding of some of the code.

Cherry-pick #8073 to 6.x: Heartbeat Scheduler Tests

---

CHANGELOG.asciidoc

Cherry-pick of PR #8108 to master branch. Original message: 
Documents the known issue and the workaround for #8104.

Cherry-pick #8108 to master: Document known issue in 6.4.0

---

CHANGELOG.asciidoc

Cherry-pick of PR #8108 to 6.x branch. Original message: 
Documents the known issue and the workaround for #8104.

Cherry-pick #8108 to 6.x: Document known issue in 6.4.0

---

deploy/kubernetes/auditbeat-kubernetes.yaml
deploy/kubernetes/filebeat-kubernetes.yaml
deploy/kubernetes/metricbeat-kubernetes.yaml
libbeat/docs/version.asciidoc

Revert "Bump docs version for 6.4.1"

---

libbeat/docs/version.asciidoc

Revert "Docs version bump 5.6.12"

---

auditbeat/module/file_integrity/monitor/monitor_test.go

This is to prevent flaky test failures that have been occurring under Windows recently.
Closes #8208

[auditbeat] Improve file monitor flaky test

---

auditbeat/module/file_integrity/monitor/monitor_test.go

Cherry-pick of PR #8367 to 6.x branch. Original message: 
This is to prevent flaky test failures that have been occurring under Windows recently.
Closes #8208

Cherry-pick #8367 to 6.x: [auditbeat] Improve file monitor flaky test

---

NOTICE.txt
vendor/github.com/Shopify/sarama/CHANGELOG.md
vendor/github.com/Shopify/sarama/async_producer.go
vendor/github.com/Shopify/sarama/broker.go
vendor/github.com/Shopify/sarama/client.go
vendor/github.com/Shopify/sarama/config.go
vendor/github.com/Shopify/sarama/consumer.go
vendor/github.com/Shopify/sarama/dev.yml
vendor/github.com/Shopify/sarama/fetch_response.go
vendor/github.com/Shopify/sarama/length_field.go
vendor/github.com/Shopify/sarama/message_set.go
vendor/github.com/Shopify/sarama/metadata_request.go
vendor/github.com/Shopify/sarama/mockresponses.go
vendor/github.com/Shopify/sarama/offset_manager.go
vendor/github.com/Shopify/sarama/partitioner.go
vendor/github.com/Shopify/sarama/records.go
vendor/github.com/Shopify/sarama/sync_producer.go
vendor/github.com/Shopify/sarama/utils.go
vendor/vendor.json

Upgrade sarama kafka client to v1.18.0, it includes support to Kafka 2.0.

Upgrade sarama (kafka client) to v1.18.0

---

auditbeat/auditbeat.reference.yml
filebeat/filebeat.reference.yml
heartbeat/heartbeat.reference.yml
libbeat/_meta/config.reference.yml
metricbeat/metricbeat.reference.yml
packetbeat/packetbeat.reference.yml
winlogbeat/winlogbeat.reference.yml

This commit means adding below info to config.full.yml
`processors:
- decode_json_fields:
fields: ["field1", "field2", ...]
process_array: false
max_depth: 1
target: ""
overwrite_keys: false`
issues #3513

Add decode_json_fields processor to Beats config

---

heartbeat/docs/heartbeat-options.asciidoc

Cherry-pick of PR #8227 to 6.x branch. Original message: 
Docs for the changes in #8023 for heartbeat automatic reloading.

Cherry-pick #8227 to 6.x: Heartbeat Automatic Reloading Docs

---

filebeat/input/syslog/input.go

fix double negative in error message

---

deploy/kubernetes/auditbeat-kubernetes.yaml
deploy/kubernetes/filebeat-kubernetes.yaml
deploy/kubernetes/metricbeat-kubernetes.yaml
libbeat/docs/version.asciidoc

This should only be merged on the release day!

Bump docs version for 6.4.2

---

filebeat/beater/filebeat.go

This change registers `filebeat.inputs` and `filebeat.modules`
reloadables, exposing them to be handled by central management.

Register filebeat inputs & modules for central management

---

NOTICE.txt
vendor/github.com/elastic/go-ucfg/CHANGELOG.md
vendor/github.com/elastic/go-ucfg/merge.go
vendor/github.com/elastic/go-ucfg/types.go
vendor/github.com/elastic/go-ucfg/variables.go
vendor/vendor.json

Update vendored github.com/elastic/go-ucfg to v0.6.4

---

libbeat/docs/dashboards.asciidoc

Replaces https://github.com/elastic/beats/pull/8135

Fix docker command for loading dashboards

---

metricbeat/module/postgresql/statement/_meta/docs.asciidoc

Replaces https://github.com/elastic/beats/pull/8211

 Removes extraneous heading from the PostgreSQL module docs 

---

libbeat/scripts/Makefile

Fix make fmt after vendoring goimports

---

metricbeat/docs/modules/elasticsearch.asciidoc
metricbeat/metricbeat.reference.yml
metricbeat/module/elasticsearch/_meta/config.reference.yml

Add SSL certificate authorities example for elasticsearch

---

filebeat/beater/filebeat.go

Cherry-pick of PR #8560 to 6.x branch. Original message: 
This change registers `filebeat.inputs` and `filebeat.modules`
reloadables, exposing them to be handled by central management.

Cherry-pick #8560 to 6.x: Register filebeat inputs & modules for central management

---

deploy/kubernetes/filebeat-kubernetes.yaml
deploy/kubernetes/filebeat/filebeat-daemonset.yaml
deploy/kubernetes/metricbeat-kubernetes.yaml
deploy/kubernetes/metricbeat/metricbeat-daemonset-configmap.yaml
deploy/kubernetes/metricbeat/metricbeat-role.yaml
docs/devguide/newbeat.asciidoc
filebeat/docs/running-on-kubernetes.asciidoc
libbeat/docs/dashboards.asciidoc
metricbeat/docs/running-on-kubernetes.asciidoc
metricbeat/module/postgresql/statement/_meta/docs.asciidoc

Cherry-picks the following doc PRs into the 6.x branch:
https://github.com/elastic/beats/pull/8300
https://github.com/elastic/beats/pull/8456
https://github.com/elastic/beats/pull/8530
https://github.com/elastic/beats/pull/8531

Backport to 6.x: Multiple doc PRs (#8300 #8456 #8530 #8531)

---

libbeat/monitoring/report/elasticsearch/client.go
libbeat/outputs/backoff.go
libbeat/outputs/console/console.go
libbeat/outputs/elasticsearch/client.go
libbeat/outputs/failover.go
libbeat/outputs/fileout/file.go
libbeat/outputs/kafka/client.go
libbeat/outputs/logstash/async.go
libbeat/outputs/outputs.go
libbeat/outputs/redis/backoff.go
libbeat/outputs/redis/client.go
libbeat/outputs/transport/client.go
libbeat/publisher/pipeline/output.go
libbeat/publisher/pipeline/stress/out.go

Cherry-pick of PR #6404 to 6.x branch. Original message: 
Closes #5175 
Logs an info line "Attempting to reconnect" at every reconnect attempt.

Cherry-pick #6404 to 6.x: Log reconnect attempts

---

CHANGELOG.asciidoc

I added Kafka dashboard changelog entry to the wrong place on #8457, move it to the correct one.

Move kafka dashboard changelog entry to correct place

---

libbeat/cmd/instance/beat.go
libbeat/monitoring/metrics.go

Cherry-pick of PR #8671 to 6.x branch. Original message: 
This will report central management enabled status
closes #7979

Cherry-pick #8671 to 6.x: Add central management telemetry

---

CHANGELOG.asciidoc
filebeat/docs/inputs/input-docker.asciidoc
filebeat/input/docker/config.go
filebeat/input/docker/input.go

Add CHANGELOG and docs for CRI force flag

---

filebeat/module/iis/_meta/kibana/6/dashboard/Filebeat-iis.json

Cherry-pick of PR #8604 to 6.x branch. Original message:

Cherry-pick #8604 to 6.x: Fix typo in Filebeat IIS Kibana visualization

---

filebeat/module/iis/_meta/kibana/6/dashboard/Filebeat-iis.json

Cherry-pick of PR #8604 to 6.4 branch. Original message:

Cherry-pick #8604 to 6.4: Fix typo in Filebeat IIS Kibana visualization

---

docs/devguide/newbeat.asciidoc
libbeat/docs/dashboards.asciidoc
metricbeat/module/postgresql/statement/_meta/docs.asciidoc

Cherry-picks the following PRs into the 6.4 branch:
https://github.com/elastic/beats/pull/8456
https://github.com/elastic/beats/pull/8530
https://github.com/elastic/beats/pull/8531

Backport to 6.4: Multiple doc changes (#8456 #8530 #8531)

---

dev-tools/jenkins_ci.ps1

Until https://github.com/elastic/beats/pull/8753 fixes the problem

Temporary disable x-pack/functionbeat on windows.

---

dev-tools/packaging/packages.yml
x-pack/functionbeat/dev-tools/packaging/packages.yml

This PR make sure the definition style used by the packages.yml and the custom
function packages.yml match.

Make sure that packages.yml use the same files definition

---

filebeat/module/nginx/error/test/error.log-expected.json

This adds an expected error log file to the nginx error fileset.

Add expected nginx error log file

---

metricbeat/module/system/socket_summary/_meta/docs.asciidoc

Cherry-pick of PR #8846 to 6.x branch. Original message: 
Format in [documentation](https://www.elastic.co/guide/en/beats/metricbeat/6.5/metricbeat-metricset-system-socket_summary.html) is broken, change small list by phrase.

Cherry-pick #8846 to 6.x: Rephrase documentation of socket summary metricset

---

metricbeat/module/system/socket_summary/_meta/docs.asciidoc

Cherry-pick of PR #8846 to 6.5 branch. Original message: 
Format in [documentation](https://www.elastic.co/guide/en/beats/metricbeat/6.5/metricbeat-metricset-system-socket_summary.html) is broken, change small list by phrase.

Cherry-pick #8846 to 6.5: Rephrase documentation of socket summary metricset

---

libbeat/publisher/pipeline/module.go

Cherry-pick of PR #8363 to 6.x branch. Original message:

Cherry-pick #8363 to 6.x: log formatted string

---

libbeat/publisher/pipeline/module.go

Cherry-pick of PR #8363 to 6.5 branch. Original message:

Cherry-pick #8363 to 6.5: log formatted string

---

deploy/kubernetes/auditbeat-kubernetes.yaml
deploy/kubernetes/filebeat-kubernetes.yaml
deploy/kubernetes/metricbeat-kubernetes.yaml
libbeat/docs/version.asciidoc

DO NOT MERGE THIS UNTIL RELEASE DAY.

Bump docs version for 6.4.3

---

libbeat/docs/version.asciidoc

Do not merge until the release day.

Update docs for 5.6.13

---

x-pack/.gitignore

Cherry-pick of PR #8917 to 6.x branch. Original message:

Cherry-pick #8917 to 6.x: Ignore kibana.generated for all x-pack Beats

---

x-pack/.gitignore

Cherry-pick of PR #8917 to 6.5 branch. Original message:

Cherry-pick #8917 to 6.5: Ignore kibana.generated for all x-pack Beats

---

heartbeat/tests/system/test_telemetry.py

Cherry-pick of PR #8967 to 6.5 branch. Original message: 
See https://github.com/elastic/beats/issues/8966 for details

Cherry-pick #8967 to 6.5: Mute flaky heartbeat telemetry test

---

heartbeat/tests/system/test_telemetry.py

Cherry-pick of PR #8967 to 6.x branch. Original message: 
See https://github.com/elastic/beats/issues/8966 for details

Cherry-pick #8967 to 6.x: Mute flaky heartbeat telemetry test

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/question.md

Add issue templates for:
- Bug report
- Enhancement request
- Question

More issue templates

---

dev-tools/mage/dockerbuilder.go

tag container images with snapshot information

---

CHANGELOG.asciidoc
metricbeat/module/kubernetes/util/kubernetes.go

Fix race condition when enriching events with Kubernetes metadata

---

libbeat/docs/shared-directory-layout.asciidoc
libbeat/docs/shared-download-and-install.asciidoc
libbeat/docs/shared-faq.asciidoc
libbeat/docs/shared-securing-beat.asciidoc
x-pack/functionbeat/docs/configuring-howto.asciidoc
x-pack/functionbeat/docs/faq.asciidoc
x-pack/functionbeat/docs/getting-started.asciidoc
x-pack/functionbeat/docs/index.asciidoc

Backports #9030 to the 6.5 branch.

Backport to 6.5: Remove shared content not relevant to Functionbeat (#9030)

---

x-pack/functionbeat/docs/config-options.asciidoc
x-pack/functionbeat/docs/configuring-howto.asciidoc
x-pack/functionbeat/docs/faq.asciidoc
x-pack/functionbeat/docs/filtering.asciidoc
x-pack/functionbeat/docs/general-options.asciidoc
x-pack/functionbeat/docs/getting-started.asciidoc
x-pack/functionbeat/docs/index.asciidoc
x-pack/functionbeat/docs/overview.asciidoc
x-pack/functionbeat/docs/setting-up-running.asciidoc
x-pack/functionbeat/docs/troubleshooting.asciidoc

Cherry-picks #9082 into 6.x branch.

Backport to 6.x: Add x-pack badge to functionbeat topics (#9082)

---

x-pack/functionbeat/docs/config-options.asciidoc
x-pack/functionbeat/docs/configuring-howto.asciidoc
x-pack/functionbeat/docs/faq.asciidoc
x-pack/functionbeat/docs/filtering.asciidoc
x-pack/functionbeat/docs/general-options.asciidoc
x-pack/functionbeat/docs/getting-started.asciidoc
x-pack/functionbeat/docs/index.asciidoc
x-pack/functionbeat/docs/overview.asciidoc
x-pack/functionbeat/docs/setting-up-running.asciidoc
x-pack/functionbeat/docs/troubleshooting.asciidoc

Cherry-picks #9082 into 6.5 branch

Backport to 6.5: Add x-pack badge to functionbeat topics (#9082)

---

x-pack/functionbeat/magefile.go

Define the license type in the functionbeat magefile.go

---

libbeat/docs/shared-central-management.asciidoc
libbeat/docs/shared-license-statement.asciidoc

@lcawl @gchaps Can you help me get this language correct?
I've flagged the content as x-pack, but I'm already seeing users on the forum who don't understand why they can't see the option for central management.
Copying Gail because I plan to add a topic to the Kibana docs, too, and want to use similar language.

Add statement about required license

---

libbeat/docs/shared-central-management.asciidoc
libbeat/docs/shared-license-statement.asciidoc

Cherry-picks #9115 into 6.5 branch.

Backport to 6.5: Add statement about required license (#9115)

---

libbeat/docs/shared-central-management.asciidoc
libbeat/docs/shared-license-statement.asciidoc

Cherry-picks #9115 into 6.5 branch.

Backport to 6.x: Add statement about required license (#9115)

---

CHANGELOG.asciidoc

#9125 is not a breaking change

Move changelog entry to bugfixes

---

deploy/kubernetes/auditbeat-kubernetes.yaml
deploy/kubernetes/filebeat-kubernetes.yaml
deploy/kubernetes/metricbeat-kubernetes.yaml
libbeat/docs/version.asciidoc

DO NOT MERGE THIS UNTIL RELEASE DAY.

Bump docs version for 6.5.1

---

CHANGELOG.asciidoc
metricbeat/module/docker/healthcheck/data.go

Fix panic on docker healthcheck collection on dockers without healthchecks.

Fix panic on docker healthcheck collection

---

x-pack/functionbeat/docs/faq.asciidoc
x-pack/functionbeat/docs/getting-started.asciidoc

Cherry-picks #9085 to the 6.5 branch.

Backport to 6.5: Add docs FAQ topic about deploying to the wrong region (#9085)

---

CHANGELOG.asciidoc
metricbeat/module/system/diskio/diskstat_linux.go

Cherry-pick of PR #9125 to 6.5 branch. Original message: 
Fixes #9124

Cherry-pick #9125 to 6.5: Fix division by zero on diskio metricset

---

filebeat/tests/system/test_registrar.py

Cherry-pick of PR #9207 to 6.x branch. Original message: 
See https://github.com/elastic/beats/issues/7690

Cherry-pick #9207 to 6.x: Skip clean_removed test

---

x-pack/metricbeat/modules.d/foo.yml.disabled

Seems this file was missing in https://github.com/elastic/beats/pull/9242

Add missing modules.d config file for foo module

---

CHANGELOG.asciidoc
libbeat/docs/release.asciidoc

Close changelog for 5.6.14

---

testing/environments/args.yml

Update testing env for 5.6.14

---

deploy/kubernetes/auditbeat-kubernetes.yaml
deploy/kubernetes/filebeat-kubernetes.yaml
deploy/kubernetes/metricbeat-kubernetes.yaml
libbeat/docs/version.asciidoc

Bump docs version for 6.5.2

---

libbeat/docs/version.asciidoc

DO NOT MERGE UNTIL RELEASE DAY

Bump docs version for 5.6.14

---

libbeat/kibana/fields_transformer.go
libbeat/kibana/fields_transformer_test.go
libbeat/scripts/generate_fields_docs.py

* generate better docs
* output the correct index pattern setting

handle object field enabled setting

---

.travis.yml
libbeat/scripts/Makefile
x-pack/libbeat/Dockerfile
x-pack/libbeat/Makefile
x-pack/libbeat/docker-compose.yml
x-pack/libbeat/libbeat.go
x-pack/libbeat/libbeat_test.go
x-pack/libbeat/magefile.go
x-pack/libbeat/management/manager_test.go
x-pack/libbeat/tests/system/base.py
x-pack/libbeat/tests/system/config/mockbeat.yml.j2
x-pack/libbeat/tests/system/test_management.py

Cherry-pick of PR #8762 to 6.x branch. Original message:

Cherry-pick #8762 to 6.x: Add system tests for Central Management

---

dev-tools/packaging/templates/linux/systemd.unit.tmpl

Fix quotation in environment variables of systemd unit

---

docs/devguide/contributing.asciidoc
filebeat/docs/include/var-paths.asciidoc
filebeat/docs/modules/elasticsearch.asciidoc
filebeat/module/elasticsearch/_meta/docs.asciidoc

Cherry-picks the following PRs into the 6.x branch:
https://github.com/elastic/beats/pull/9453 
https://github.com/elastic/beats/pull/9479

Backport to 6.x: PRs #9453 and #9479

---

CHANGELOG.asciidoc
filebeat/channel/util.go

Cherry-pick of PR #7820 to 6.x branch. Original message: 
This fixes a goroutine leaking every time that a harvester is closed.

Cherry-pick #7820 to 6.x: Fix goroutine leak in SubOutlet

---

filebeat/santa.yml.disabled

This file was added accidentally.

Remove extra santa.yml.disabled

---

deploy/kubernetes/auditbeat-kubernetes.yaml
deploy/kubernetes/filebeat-kubernetes.yaml
deploy/kubernetes/metricbeat-kubernetes.yaml
libbeat/docs/version.asciidoc

Bump docs version for 6.5.4

---

deploy/kubernetes/auditbeat-kubernetes.yaml
deploy/kubernetes/filebeat-kubernetes.yaml
deploy/kubernetes/metricbeat-kubernetes.yaml
libbeat/docs/version.asciidoc

Bump docs version for 7.0.0-alpha2

---

libbeat/docs/shared-systemd.asciidoc

Continues with #9564 and #9562.

Fix systemd quotes in documentation too

---

.travis.yml
x-pack/libbeat/docker-compose.yml

revert the disabled tests and restart on failure for a non-healthy container.

[WIP] Fix/enable xpack back

---

NOTICE.txt

Cherry-pick of PR #9841 to 6.x branch. Original message:

Cherry-pick #9841 to 6.x: Update NOTICE file for 2019

---

NOTICE.txt

Cherry-pick of PR #9841 to 6.6 branch. Original message:

Cherry-pick #9841 to 6.6: Update NOTICE file for 2019

---

libbeat/tests/system/requirements.txt

Addresses https://nvd.nist.gov/vuln/detail/CVE-2017-18342.

Upgrade PyYAML

---

auditbeat/auditbeat.reference.yml
filebeat/filebeat.reference.yml
heartbeat/heartbeat.reference.yml
journalbeat/journalbeat.reference.yml
libbeat/_meta/config.reference.yml
metricbeat/metricbeat.reference.yml
packetbeat/packetbeat.reference.yml
winlogbeat/winlogbeat.reference.yml
x-pack/auditbeat/auditbeat.reference.yml
x-pack/filebeat/filebeat.reference.yml
x-pack/functionbeat/functionbeat.reference.yml
x-pack/metricbeat/metricbeat.reference.yml

Cherry-pick of PR #9511 to 6.x branch. Original message: 
There were a few very small grammatical errors in the configuration file. All changes were made only to lines already commented out and used as documentation. No changes were made to configuration option names or to their corresponding values.

Cherry-pick #9511 to 6.x: Minor grammatical fixes to libbeats configuration file

---

heartbeat/monitors/monitor.go

This cleans up a couple small points missed in #9697

[Heartbeat] Clean up some nits from Explicit IDs (9697)

---

dev-tools/cmd/dashboards/export_dashboards.go
libbeat/dashboards/export.go

From now on exported dashboards are pretty printed to all outputs.
++ minor refactoring

Pretty print exported dashboards to output

---

metricbeat/module/elasticsearch/ml_job/_meta/docs.asciidoc
metricbeat/module/elasticsearch/pending_tasks/_meta/docs.asciidoc

Closes #9880. Also fixes a similar issue in the pending_tasks metricset.

[Docs] Remove duplicate metricset pages

---

x-pack/auditbeat/module/system/host/host.go

Cherry-pick of PR #9953 to 6.x branch. Original message: 
At the moment, IP addresses collected from a network interfaces have no specific order. What can happen is that even though an interface has both IPv4 and IPv6 addresses, the IPv6 address might be returned first. This matters because the first IP address of the first non-loopback interface will be used in the `message` string, e.g.: `"message": "Host vagrant-2016 (IP: 10.0.2.15) restarted"`. The IPv4 address (if it exists) should be easier to read and the more "expected" one for the user.

[Auditbeat] Cherry-pick #9953 to 6.x: Sort IPv4 addresses before IPv6

---

x-pack/auditbeat/module/system/host/host.go

Cherry-pick of PR #9953 to 6.6 branch. Original message: 
At the moment, IP addresses collected from a network interfaces have no specific order. What can happen is that even though an interface has both IPv4 and IPv6 addresses, the IPv6 address might be returned first. This matters because the first IP address of the first non-loopback interface will be used in the `message` string, e.g.: `"message": "Host vagrant-2016 (IP: 10.0.2.15) restarted"`. The IPv4 address (if it exists) should be easier to read and the more "expected" one for the user.

[Auditbeat] Cherry-pick #9953 to 6.6: Sort IPv4 addresses before IPv6

---

libbeat/docs/communitybeats.asciidoc

nvidiagpubeat has new home at  https://github.com/eBay/nvidiagpubeat

nvidiagpubeat

---

filebeat/docs/modules-overview.asciidoc

Cherry-picks #9534  into the master branch.

Forward port to master: Fixed small typo (#9534)

---

filebeat/module/kafka/_meta/kibana/6/dashboard/Filebeat-Kafka-overview.json

Cherry-pick of PR #10107 to 6.x branch. Original message:

Cherry-pick #10107 to 6.x: Add suffix to kafka visualization title

---

testing/environments/latest.yml

Update latest testing environment

---

CHANGELOG.next.asciidoc
filebeat/filebeat.reference.yml
filebeat/module/nginx/_meta/config.reference.yml
filebeat/module/nginx/_meta/config.yml
filebeat/module/nginx/access/config/nginx-access.yml
filebeat/module/nginx/access/ingest/default.json
filebeat/module/nginx/access/manifest.yml
filebeat/module/nginx/error/config/nginx-error.yml
filebeat/module/nginx/error/ingest/pipeline.json
filebeat/module/nginx/error/manifest.yml
filebeat/modules.d/nginx.yml.disabled
x-pack/filebeat/filebeat.reference.yml

* Add convert_timezone to nginx module
* Run mage fmt update on x-pack filebeat
(cherry picked from commit d53fa9f8ee6e8e2263143ca33f2dd117a5437839)

Cherry-pick to 6.x: Add convert_timezone to nginx module (#10148)

---

generator/metricbeat/{beat}/magefile.go
libbeat/scripts/Makefile
metricbeat/Makefile
metricbeat/docs/fields.asciidoc
metricbeat/magefile.go

This fields collection is currently only called when running `mage update` and not `make update`.

[Metricbeta] Update fields generation to also include X-Pack fields

---

metricbeat/module/haproxy/info/_meta/data.json
metricbeat/module/haproxy/info/info_integration_test.go
metricbeat/module/haproxy/stat/_meta/data.json
metricbeat/module/haproxy/stat/stat_integration_test.go

Add TestFetch to HAProxy metricsets

---

.github/ISSUE_TEMPLATE/module-checklist.md

Add links to EUI icons and example tutorials.

Add more details around Kibana home tutorials to template

---

CHANGELOG.next.asciidoc
filebeat/module/system/auth/ingest/pipeline.json
filebeat/module/system/auth/test/test.log-expected.json

Remove erroneous coercion of user/group ID in Filebeat system.auth

---

filebeat/docs/modules/mysql.asciidoc
filebeat/module/mysql/_meta/docs.asciidoc

Add percona to mysql module compatibility notes

---

auditbeat/docs/configuring-howto.asciidoc
filebeat/docs/configuring-howto.asciidoc
heartbeat/docs/configuring-howto.asciidoc
journalbeat/docs/configuring-howto.asciidoc
libbeat/docs/outputconfig.asciidoc
libbeat/docs/shared-ilm.asciidoc
metricbeat/docs/configuring-howto.asciidoc
packetbeat/docs/configuring-howto.asciidoc
winlogbeat/docs/configuring-howto.asciidoc
x-pack/functionbeat/docs/configuring-howto.asciidoc

Cherry-picks #9263 into the 6.x branch.

Backport to 6.x: [Docs] Add docs for ILM feature (#9263)

---

auditbeat/docs/configuring-howto.asciidoc
filebeat/docs/configuring-howto.asciidoc
heartbeat/docs/configuring-howto.asciidoc
journalbeat/docs/configuring-howto.asciidoc
libbeat/docs/outputconfig.asciidoc
libbeat/docs/shared-ilm.asciidoc
metricbeat/docs/configuring-howto.asciidoc
packetbeat/docs/configuring-howto.asciidoc
winlogbeat/docs/configuring-howto.asciidoc
x-pack/functionbeat/docs/configuring-howto.asciidoc

Backports #9263 to the 6.6 branch.

Backport to 6.6: [Docs] Add docs for ILM feature (#9263)

---

CHANGELOG.next.asciidoc
metricbeat/docs/fields.asciidoc
metricbeat/docs/modules/kvm.asciidoc
metricbeat/docs/modules/kvm/dommemstat.asciidoc
metricbeat/docs/modules_list.asciidoc
metricbeat/module/kvm/_meta/fields.yml
metricbeat/module/kvm/dommemstat/_meta/fields.yml
metricbeat/module/kvm/dommemstat/dommemstat.go
metricbeat/module/kvm/fields.go

A follow up issue can be found here https://github.com/elastic/beats/issues/10217 to create docs on how to test this.

[Metricbeat] Release kvm module as beta

---

metricbeat/docs/modules/aws.asciidoc

Two PRs were merged in parallel and this got lost.

Fix AWS docs update

---

CHANGELOG.next.asciidoc
x-pack/functionbeat/config/config.go

Cherry-pick of PR #10262 to 6.6 branch. Original message:

Cherry-pick #10262 to 6.6: Ensure that functionbeat is logging at info level not debug

---

CHANGELOG.next.asciidoc
NOTICE.txt
libbeat/publisher/queue/spool/inbroker.go
libbeat/publisher/queue/spool/outbroker.go
vendor/github.com/elastic/go-txfile/CHANGELOG.md
vendor/github.com/elastic/go-txfile/alloc.go
vendor/github.com/elastic/go-txfile/dev-tools/lib/mage/gotool/go.go
vendor/github.com/elastic/go-txfile/dev-tools/lib/mage/mgenv/mgenv.go
vendor/github.com/elastic/go-txfile/dev-tools/lib/mage/xbuild/docker.go
vendor/github.com/elastic/go-txfile/dev-tools/lib/mage/xbuild/xbuild.go
vendor/github.com/elastic/go-txfile/file.go
vendor/github.com/elastic/go-txfile/magefile.go
vendor/github.com/elastic/go-txfile/observe.go
vendor/github.com/elastic/go-txfile/opts.go
vendor/github.com/elastic/go-txfile/page.go
vendor/github.com/elastic/go-txfile/pq/access.go
vendor/github.com/elastic/go-txfile/pq/ack.go
vendor/github.com/elastic/go-txfile/pq/buffer.go
vendor/github.com/elastic/go-txfile/pq/errkind_string.go
vendor/github.com/elastic/go-txfile/pq/error.go
vendor/github.com/elastic/go-txfile/pq/observe.go
vendor/github.com/elastic/go-txfile/pq/pq.go
vendor/github.com/elastic/go-txfile/pq/reader.go
vendor/github.com/elastic/go-txfile/pq/writer.go
vendor/github.com/elastic/go-txfile/tx.go
vendor/github.com/elastic/go-txfile/write.go
vendor/vendor.json

Update go-txfile 0.0.6

---

metricbeat/module/haproxy/info/_meta/data.json
metricbeat/module/haproxy/info/data.go
metricbeat/module/haproxy/info/info.go
metricbeat/module/haproxy/info/info_integration_test.go
metricbeat/module/haproxy/stat/data.go
metricbeat/module/haproxy/stat/stat.go
metricbeat/module/haproxy/stat/stat_integration_test.go

This is required to add proper ECS fields to HAProxy.

[Metricbeat] Convert HAProxy to reporter metricset

---

metricbeat/mb/testing/data_generator.go

Add event filtering for data generation, like #6958, but for V2 reporters. 
When destination path is not a directory, use it as file.

Support generation of multiple data files on metricbeat integration tests

---

metricbeat/module/kvm/dommemstat/_meta/data.json

Add new data.json.
Metricset: dommemstat 
Module: kvm

[Metricbeat] Add data.json to dommemstat metricset (#10217)

---

NOTICE.txt
libbeat/monitoring/adapter/go-metrics.go
vendor/github.com/rcrowley/go-metrics/README.md
vendor/github.com/rcrowley/go-metrics/ewma.go
vendor/github.com/rcrowley/go-metrics/gauge_float64.go
vendor/github.com/rcrowley/go-metrics/json.go
vendor/github.com/rcrowley/go-metrics/meter.go
vendor/github.com/rcrowley/go-metrics/registry.go
vendor/github.com/rcrowley/go-metrics/timer.go
vendor/github.com/rcrowley/go-metrics/validate.sh
vendor/vendor.json

Also add `adapter.GoMetricsRegistry.GetAll()` to match new method, which fixes https://github.com/elastic/beats/issues/10096

vendor: update rcrowley/go-metrics

---

libbeat/docs/communitybeats.asciidoc

Cherry-picks community beat additions into the 6.x branch.

Cherrypick community beats into 6.x branch

---

libbeat/docs/communitybeats.asciidoc

Cherry-picks community beat additions into the 6.6 branch.

Cherrypick community beats into 6.6 branch

---

metricbeat/mb/testing/data_generator.go

Use default path for data.json if no other path is set

---

libbeat/docs/communitybeats.asciidoc

Signed-off-by: Guillaume Dore <corwin@poussif.eu>

Add servicebeat to list of Community Beats

---

libbeat/docs/outputconfig.asciidoc

I did a goof and didn't resolve a conflict before merging.

[docs] Fix the doc build

---

CHANGELOG.next.asciidoc
NOTICE.txt
libbeat/publisher/queue/spool/inbroker.go
libbeat/publisher/queue/spool/outbroker.go
vendor/github.com/elastic/go-txfile/CHANGELOG.md
vendor/github.com/elastic/go-txfile/alloc.go
vendor/github.com/elastic/go-txfile/dev-tools/lib/mage/gotool/go.go
vendor/github.com/elastic/go-txfile/dev-tools/lib/mage/mgenv/mgenv.go
vendor/github.com/elastic/go-txfile/dev-tools/lib/mage/xbuild/docker.go
vendor/github.com/elastic/go-txfile/dev-tools/lib/mage/xbuild/xbuild.go
vendor/github.com/elastic/go-txfile/file.go
vendor/github.com/elastic/go-txfile/magefile.go
vendor/github.com/elastic/go-txfile/observe.go
vendor/github.com/elastic/go-txfile/opts.go
vendor/github.com/elastic/go-txfile/page.go
vendor/github.com/elastic/go-txfile/pq/access.go
vendor/github.com/elastic/go-txfile/pq/ack.go
vendor/github.com/elastic/go-txfile/pq/buffer.go
vendor/github.com/elastic/go-txfile/pq/errkind_string.go
vendor/github.com/elastic/go-txfile/pq/error.go
vendor/github.com/elastic/go-txfile/pq/observe.go
vendor/github.com/elastic/go-txfile/pq/pq.go
vendor/github.com/elastic/go-txfile/pq/reader.go
vendor/github.com/elastic/go-txfile/pq/writer.go
vendor/github.com/elastic/go-txfile/tx.go
vendor/github.com/elastic/go-txfile/write.go
vendor/vendor.json

Cherry-pick of PR #10289 to 6.x branch. Original message: 
Closes: #9874

Cherry-pick #10289 to 6.x: Update go-txfile 0.0.6

---

x-pack/libbeat/tests/system/test_management.py

Skipping because snapshot is not ready yet. see #10481"

Disable CM for 6.x until snapshot is ready.

---

README.md

Cherry-pick of PR #9238 to 6.6 branch. Original message: 
We forgot to update this readme when we created Journalbeat and
Functionbeat.

Cherry-pick #9238 to 6.6: Add Journalbeat and Function in the readme.md

---

journalbeat/_meta/kibana/6/dashboard/Journalbeat-overview.json

Fixes broken Journalbeat dashboard.

Fix Journalbeat dashboard in 6.7

---

filebeat/module/santa/_meta/kibana/7/dashboard/filebeat-santa-log-overview.json

This will make changes to it more reviewable. No changes were made to the JSON itself.

Make santa dashboard formatted JSON

---

CHANGELOG.next.asciidoc

Forgot the changelog entry. Caught it in the backport though.

[Auditbeat] Changelog for #10511

---

filebeat/tests/system/test_registrar.py

See https://github.com/elastic/beats/issues/10606 for more details.

[Filebeat] Skip flaky registrar tests

---

x-pack/auditbeat/tests/system/test_metricsets.py

See https://github.com/elastic/beats/issues/10633

[Auditbeat] Skip flaky test_metricset_package test

---

libbeat/kibana/index_pattern_generator.go
libbeat/kibana/index_pattern_generator_test.go
libbeat/kibana/testdata/beat-6.json
libbeat/kibana/testdata/extensive/metricbeat-6.json

related to https://github.com/elastic/kibana/pull/30789

Ensure index pattern version is a string

---

CHANGELOG-developer.next.asciidoc
CHANGELOG.next.asciidoc

This is a follow up to #10721 as I forgot to add the changelog.

Add changelog entry for PR#10721

---

README.md
metricbeat/README.md
packetbeat/README.md

Also cleans up old inaccurate snapshot refs

Add snapshots to main README

---

CHANGELOG.asciidoc
libbeat/docs/release.asciidoc

close changelog for 5.6.15

---

x-pack/libbeat/tests/system/test_management.py

Since the snapshot are correct and are available we can turn on the integration tests. 
need to be ported to 6.6,7.x, when the snapshots are available.
master snapshots are not yet available.

Since the snapshot are correct and are available we can turn on the integration tests.

---

testing/environments/args.yml

Update testing env for 5.6.15

---

deploy/kubernetes/auditbeat-kubernetes.yaml
deploy/kubernetes/filebeat-kubernetes.yaml
deploy/kubernetes/metricbeat-kubernetes.yaml
libbeat/docs/version.asciidoc

DO NOT MERGE THIS UNTIL RELEASE DAY.

Bump docs version for 6.6.1

---

libbeat/docs/version.asciidoc

DO NOT MERGE UNTIL RELEASE DAY

Bump docs version 5.6.15

---

libbeat/docs/security/basic-auth.asciidoc
libbeat/docs/security/securing-beats.asciidoc

Cherry-picks #10449 into 6.7 branch

[6.7] Document privileges for ILM (#10449)

---

libbeat/docs/security/basic-auth.asciidoc
libbeat/docs/security/securing-beats.asciidoc

Cherry-picks #10449 into 6.6 branch

[6.6] Document privileges for ILM (#10449)

---

libbeat/docs/security/basic-auth.asciidoc
libbeat/docs/security/securing-beats.asciidoc

Cherry-picks #10449 into 7.0 branch.

[7.0] Document privileges for ILM (#10449)

---

metricbeat/module/kubernetes/pod/pod.go

[Metricbeat] Migrate Kubernetes pod Metricset to use ReporterV2 interface

---

metricbeat/module/kubernetes/volume/volume.go

[Metricbeat] Migrate Kubernetes volume Metricset to use ReporterV2 interface

---

metricbeat/module/kubernetes/system/system.go

[Metricbeat] Migrate Kubernetes system Metricset to use ReporterV2 interface

---

heartbeat/monitors/active/http/http_test.go

Cherry-pick of PR #10789 to 7.x branch. Original message: 
Sometimes the httptest package when using fancy TLS options doesn't put the server up as fast as it should (at least that's the theory), and we hit before it's ready, causing a false test failure. This patch makes those tests more resilient.
It's possible there's something else at work here, but this bug is only seen on CI, and impossible to repro on my laptop.
Fixes https://github.com/elastic/beats/issues/10722

Cherry-pick #10789 to 7.x: [Heartbeat] Fix flaky SSL test with retries.

---

heartbeat/monitors/active/http/http_test.go

Cherry-pick of PR #10789 to 7.0 branch. Original message: 
Sometimes the httptest package when using fancy TLS options doesn't put the server up as fast as it should (at least that's the theory), and we hit before it's ready, causing a false test failure. This patch makes those tests more resilient.
It's possible there's something else at work here, but this bug is only seen on CI, and impossible to repro on my laptop.
Fixes https://github.com/elastic/beats/issues/10722

Cherry-pick #10789 to 7.0: [Heartbeat] Fix flaky SSL test with retries.

---

metricbeat/module/mongodb/replstatus/_meta/data.json
metricbeat/module/mongodb/replstatus/replstatus.go
metricbeat/module/mongodb/replstatus/replstatus_integration_test.go

[Metricbeat] Migrate MongoDB replstatus Metricset to use ReporterV2 interface

---

metricbeat/module/postgresql/bgwriter/_meta/data.json
metricbeat/module/postgresql/bgwriter/bgwriter.go
metricbeat/module/postgresql/bgwriter/bgwriter_integration_test.go

[Metricbeat] Migrate PostgreSQL bgwriter Metricset to use ReporterV2 interface

---

metricbeat/module/postgresql/statement/_meta/data.json
metricbeat/module/postgresql/statement/statement.go
metricbeat/module/postgresql/statement/statement_integration_test.go

[Metricbeat] Migrate PostgreSQL statement Metricset to use ReporterV2 interface

---

metricbeat/module/mongodb/metrics/_meta/data.json
metricbeat/module/mongodb/metrics/metrics.go
metricbeat/module/mongodb/metrics/metrics_intergration_test.go

[Metricbeat] Migrate MongoDB metrics Metricset to use ReporterV2 interface

---

.travis.yml

Fix travis GO_VERSION problem

---

metricbeat/module/memcached/stats/_meta/data.json
metricbeat/module/memcached/stats/stats.go
metricbeat/module/memcached/stats/stats_integration_test.go

[Metricbeat] Migrate Memcached stats Metricset to use ReporterV2 interface

---

CHANGELOG.next.asciidoc

#10950 bug fix was missing an entry in CHANGELOG.next

[Filebeat] [NetFlow] Update changelog for #10950

---

docs/devguide/contributing.asciidoc

A very easy rookie contribution:
- Fix a link to PR review. Solves #11069 
- Change recommended go version for development
- Change clone example to use SSH

Beats docs - Contributing improvements

---

metricbeat/module/postgresql/activity/_meta/data.json
metricbeat/module/postgresql/activity/activity.go
metricbeat/module/postgresql/activity/activity_integration_test.go

[Metricbeat] Migrate PostgresSQL activity metricset to use ReporterV2 interface

---

metricbeat/module/couchdb/server/_meta/data.json
metricbeat/module/couchdb/server/server.go
metricbeat/module/couchdb/server/server_integration_test.go
metricbeat/module/couchdb/server/server_test.go

[Metricbeat] Migrate Couchdb server to use ReporterV2 interface

---

metricbeat/module/couchbase/cluster/_meta/data.json
metricbeat/module/couchbase/cluster/cluster.go
metricbeat/module/couchbase/cluster/cluster_integration_test.go
metricbeat/module/couchbase/cluster/cluster_test.go

[Metricbeat] Migrate Couchbase cluster to use ReporterV2 interface

---

metricbeat/module/couchbase/node/_meta/data.json
metricbeat/module/couchbase/node/node.go
metricbeat/module/couchbase/node/node_integration_test.go
metricbeat/module/couchbase/node/node_test.go

[Metricbeat] Migrate Couchbase node to use ReporterV2 interface

---

packetbeat/flows/worker.go

Fix flows timeout setting error message

---

metricbeat/module/ceph/cluster_health/cluster_health.go
metricbeat/module/ceph/cluster_health/cluster_health_integration_test.go
metricbeat/module/ceph/cluster_health/cluster_health_test.go
metricbeat/module/ceph/cluster_health/data.go

[Metricbeat] Migrate Ceph cluster_health to use ReporterV2 interface

---

metricbeat/module/ceph/osd_df/data.go
metricbeat/module/ceph/osd_df/osd_df.go
metricbeat/module/ceph/osd_df/osd_df_integration_test.go
metricbeat/module/ceph/osd_df/osd_df_test.go

[Metricbeat] Migrate Ceph osd_df to use ReporterV2 interface

---

metricbeat/module/ceph/cluster_status/cluster_status.go
metricbeat/module/ceph/cluster_status/cluster_status_integration_test.go
metricbeat/module/ceph/cluster_status/cluster_status_test.go
metricbeat/module/ceph/cluster_status/data.go

[Metricbeat] Migrate Ceph cluster_status to use ReporterV2 interface

---

metricbeat/module/jolokia/jmx/_meta/data.json
metricbeat/module/jolokia/jmx/jmx.go
metricbeat/module/jolokia/jmx/jmx_integration_test.go

[Metricbeat] Migrate Jolokia jmx metricset to use ReporterV2 interface

---

libbeat/docs/communitybeats.asciidoc

New community beat to pull data from Netatmo weather stations.

Add community beat Netatmobeat to the list

---

filebeat/docs/autodiscover-docker-config.asciidoc
metricbeat/docs/autodiscover-docker-config.asciidoc

* Document autodiscover dedot option
(cherry picked from commit 0df955f78b1f79f10630f60d380778f9db2cab2c)

Cherry-pick to 7.0: Document autodiscover dedot option (#10938)

---

libbeat/scripts/generate_fields_docs.py

Cherry-pick of PR #9475 to 6.7 branch. Original message: 
* generate better docs
* output the correct index pattern setting
Partially done in https://github.com/elastic/beats/pull/9672 but missed the python update somehow.  Really should have been done in https://github.com/elastic/beats/pull/9485.

Cherry-pick #9475 to 6.7: handle object field enabled setting

---

CHANGELOG.next.asciidoc

Add missing CHANGELOG entry for #10945

[Filebeat] [NetFlow] Add missing CHANGELOG entry for #10945

---

metricbeat/module/kibana/stats/stats_integration_test.go

To help debug https://github.com/elastic/beats/issues/11261.

Log Kibana GET /api/status response on test failure

---

CHANGELOG.next.asciidoc
filebeat/input/syslog/event.go

Fix of #11010 
Old pull request #11011 will be closed for the same issue because of base branch mismatch.

[Filebeat] Fix of syslog parsing for Priority value <0> ( #11010 )

---

metricbeat/module/mysql/status/status.go
metricbeat/module/mysql/status/status_integration_test.go

[Metricbeat] Update mysql/status to ReporterV2

---

testing/environments/args.yml

Update testing env for 5.6.16

---

libbeat/docs/version.asciidoc

DO NOT MERGE UNTIL RELEASE DAY

Bump docs version 5.6.16

---

CHANGELOG.asciidoc
libbeat/docs/release.asciidoc

close changelog for 5.6.16

---

metricbeat/module/couchdb/server/server.go
metricbeat/module/couchdb/server/server_integration_test.go
metricbeat/module/couchdb/server/server_test.go

[Metricbeat] migrate couchdb module to ReporterV2 error

---

metricbeat/module/etcd/leader/leader.go
metricbeat/module/etcd/leader/leader_integration_test.go
metricbeat/module/etcd/leader/leader_test.go
metricbeat/module/etcd/self/self.go
metricbeat/module/etcd/self/self_integration_test.go
metricbeat/module/etcd/self/self_test.go
metricbeat/module/etcd/store/store.go
metricbeat/module/etcd/store/store_integration_test.go
metricbeat/module/etcd/store/store_test.go

[Metricbeat] migrate etcd module to ReporterV2 error

---

metricbeat/module/memcached/stats/stats.go
metricbeat/module/memcached/stats/stats_integration_test.go

[Metricbeat] migrate memcached module to ReporterV2 error

---

metricbeat/module/couchbase/bucket/bucket.go
metricbeat/module/couchbase/bucket/bucket_integration_test.go
metricbeat/module/couchbase/bucket/bucket_test.go
metricbeat/module/couchbase/cluster/cluster.go
metricbeat/module/couchbase/cluster/cluster_integration_test.go
metricbeat/module/couchbase/node/node.go
metricbeat/module/couchbase/node/node_integration_test.go

[metricbeat] move couchbase module to ReporterV2 error

---

metricbeat/module/vsphere/datastore/datastore.go
metricbeat/module/vsphere/datastore/datastore_test.go

see elastic/beats#10774 
Guess no one wanted to take this up?

[metricbeat] Migrate vsphere/datastore to ReporterV2

---

x-pack/functionbeat/docs/getting-started.asciidoc
x-pack/functionbeat/docs/overview.asciidoc

Fixes typo and removed duplicate link

Fix minor typos in functionbeat docs

---

libbeat/docs/version.asciidoc

Bump docs version for 6.7.0

---

libbeat/docs/breaking.asciidoc

Add a note concerning the breaking change of 6.7 for Central Management
and mention the migration tool.

CM Breaking changes in 6.7

---

libbeat/docs/communitybeats.asciidoc

This PR adds 2 new community beats to the list.
Owmbeat for Open Weather Map api and Safecastbeat for Safecast API

Add new community beats to the list. Owmbeat and Safecastbeat.

---

libbeat/docs/breaking.asciidoc

Cherry-pick of PR #11434 to 6.7 branch. Original message: 
Add a note concerning the breaking change of 6.7 for Central Management
and mention the migration tool.

Cherry-pick #11434 to 6.7: CM Breaking changes in 6.7

---

metricbeat/module/docker/container/container.go
metricbeat/module/docker/container/container_integration_test.go
metricbeat/module/docker/cpu/cpu.go
metricbeat/module/docker/cpu/cpu_integration_test.go
metricbeat/module/docker/diskio/diskio.go
metricbeat/module/docker/diskio/diskio_integration_test.go
metricbeat/module/docker/healthcheck/data.go
metricbeat/module/docker/healthcheck/healthcheck.go
metricbeat/module/docker/healthcheck/healthcheck_integration_test.go
metricbeat/module/docker/memory/memory.go
metricbeat/module/docker/memory/memory_integration_test.go
metricbeat/module/docker/network/network.go
metricbeat/module/docker/network/network_integration_test.go

[Metricbeat] migrate docker module to ReporterV2 error

---

CHANGELOG.next.asciidoc
x-pack/libbeat/management/enroll.go
x-pack/libbeat/tests/system/test_management.py

Add the timestamp when creating the backup file

---

filebeat/module/apache/_meta/kibana/7/dashboard/Filebeat-apache.json
filebeat/module/iis/_meta/kibana/7/dashboard/Filebeat-iis.json
filebeat/module/mysql/_meta/kibana/7/dashboard/Filebeat-mysql.json
filebeat/module/nginx/_meta/kibana/7/dashboard/Filebeat-nginx-overview.json
filebeat/module/traefik/_meta/kibana/7/dashboard/Filebeat-traefik-overview.json
libbeat/docs/field-name-changes.asciidoc

Cherry-pick of PR #11520 to master branch. Original message:

Cherry-pick #11520 to master: Fixed Filebeat ECS dashboards

---

metricbeat/module/docker/image/_meta/data.json
metricbeat/module/docker/image/image.go
metricbeat/module/docker/image/image_integration_test.go

[Metricbeat] Migrate Docker image Metricset to use ReporterV2 interface

---

metricbeat/module/windows/service/_meta/data.json
metricbeat/module/windows/service/service.go
metricbeat/module/windows/service/service_integration_windows_test.go

[Metricbeat] Migrate Windows service to use ReporterV2 interface

---

libbeat/docs/shared-ilm.asciidoc
libbeat/docs/shared-kibana-config.asciidoc
libbeat/docs/shared-path-config.asciidoc

Closes #11347 
Adds new ILM settings plus reworks the conceptual content. Also fixed a minor nit for people who are bothered by the mixture of "configure" and "set up" in the TOC. 
Marking "in progress" because I haven't tested the settings yet. You can feel free to comment whenever you're able.
TODO:

Indicate that ILM is on by default and add new settings

---

deploy/kubernetes/auditbeat-kubernetes.yaml
deploy/kubernetes/filebeat-kubernetes.yaml
deploy/kubernetes/metricbeat-kubernetes.yaml
libbeat/docs/version.asciidoc

Bump docs version for 6.7.1

---

deploy/kubernetes/auditbeat-kubernetes.yaml
deploy/kubernetes/filebeat-kubernetes.yaml
deploy/kubernetes/metricbeat-kubernetes.yaml
libbeat/docs/version.asciidoc

This reverts commit 9f7eca5d232d5c7bffe88c332cee7a24b6a07c41.

Revert "Bump docs version for 6.7.1 (#11560)"

---

libbeat/docs/upgrading.asciidoc

Cherry-picks #11378 into the 7.0 branch.

[7.0] Backport: Add upgrade docs (#11378)

---

deploy/kubernetes/auditbeat-kubernetes.yaml
deploy/kubernetes/filebeat-kubernetes.yaml
deploy/kubernetes/metricbeat-kubernetes.yaml
libbeat/docs/version.asciidoc

Bump docs version for 7.0.0-rc2

---

auditbeat/docs/breaking.asciidoc
libbeat/docs/breaking.asciidoc

Cherry-pick of PR #11439 to 7.0 branch. Original message:

Cherry-pick #11439 to 7.0: Update breaking changes docs

---

x-pack/metricbeat/module/aws/mtest/scripts/README.md
x-pack/metricbeat/module/aws/mtest/scripts/get_temp_creds.go
x-pack/metricbeat/module/aws/mtest/scripts/sqs_send_receive_delete.go

To help more people use/test aws module, I will start putting scripts that I made for testing into aws mtest directory. 
1. get temp credentials using MFA token
2. automate send/receive/delete for SQS

Add scripts for aws module to help testing locally

---

libbeat/docs/processors-using.asciidoc

Cherry-pick of PR #11239 to 7.0 branch. Original message: 
Add docs for add_fields, add_labels, and add_tags processors

Cherry-pick #11239 to 7.0: Add docs for new processors

---

x-pack/functionbeat/docs/getting-started.asciidoc
x-pack/functionbeat/docs/overview.asciidoc

Cherry-picks #11408 into the 6.7 branch

[6.7] Backport: Fix minor typos (#11408)

---

libbeat/docs/shared-ilm.asciidoc

Cherry-picks #11352 into the 7.0 branch.

[7.0] Backport: Remove beta tag

---

x-pack/functionbeat/docs/getting-started.asciidoc
x-pack/functionbeat/docs/overview.asciidoc

Cherry-picks #11408 into 7.0 branch.

[7.0] Backport: Fix minor typos (#11408)

---

libbeat/docs/dashboardsconfig.asciidoc

Cherry-picks #11495 into master.

[master] Forward port: Fix missing period in setup.dashboards.always_kibana. (#11495)

---

metricbeat/docs/autodiscover-kubernetes-config.asciidoc

Add missing `$` in example autodiscover config

---

CHANGELOG.next.asciidoc
Vagrantfile
x-pack/libbeat/licenser/elastic_fetcher.go
x-pack/libbeat/licenser/elastic_fetcher_test.go
x-pack/libbeat/licenser/license.go
x-pack/libbeat/licenser/manager.go
x-pack/libbeat/licenser/manager_test.go
x-pack/libbeat/licenser/testdata/xpack-trial-6.4.0.json
x-pack/libbeat/licenser/testdata/xpack-with-relax-license-uuid.json

Cherry-pick of PR #11649 to 6.7 branch. Original message: 
- Relax validation of the X-Pack license UID value.
- Fix a parsing error with the X-Pack license check on 32-bit system. 
Fixes: #11640
Fixes: #11650

Cherry-pick #11649 to 6.7: Fixes license check issue with invalid license UUID and check on 32 bits system.

---

libbeat/docs/breaking.asciidoc

I made this change directly in the 6.7 branch because master has 7.0 content now, and I don't want folks to get confused.

Add license requirement to breaking changes

---

libbeat/docs/processors-using.asciidoc

Cherry-pick of PR #11717 to 7.0 branch. Original message: 
Behavior changed in #11577

Cherry-pick #11717 to 7.0: Update add_docker_metadata docs after latest changes

---

libbeat/docs/upgrade-setup-commands.asciidoc
libbeat/docs/upgrading.asciidoc

Starting a PR to push fixes for the upgrade docs.

Fix upgrade docs for issues found during testing

---

libbeat/docs/upgrade-setup-commands.asciidoc
libbeat/docs/upgrading.asciidoc

Cherry-pick #11638 into 7.0 branch.

[7.0] Backport: Fix upgrade docs for issues found during testing (#11638)

---

libbeat/autodiscover/providers/docker/docker_integration_test.go

Test was disabled here: #11627

Enable docker provider integration test

---

x-pack/auditbeat/magefile.go

Cherry-pick of PR #11768 to 6.7 branch. Original message:

Cherry-pick #11768 to 6.7: Temporary fix for debian7

---

x-pack/auditbeat/magefile.go

Cherry-pick of PR #11768 to 7.0 branch. Original message:

Cherry-pick #11768 to 7.0: Temporary fix for debian7

---

x-pack/auditbeat/magefile.go

Cherry-pick of PR #11768 to 7.x branch. Original message:

Cherry-pick #11768 to 7.x: Temporary fix for debian7

---

libbeat/docs/breaking.asciidoc

Some folks thought this was worth highlighting in the breaking changes since we talk about other name changes there.

Add apache2 renaming to breaking changes doc

---

metricbeat/module/redis/key/_meta/docs.asciidoc

Fix redis key example pattern in docs

---

metricbeat/module/redis/key/_meta/docs.asciidoc

Cherry-pick of PR #11821 to 7.0 branch. Original message: 
Fix #11733

Cherry-pick #11821 to 7.0: Fix redis key example pattern in docs

---

metricbeat/module/redis/key/_meta/docs.asciidoc

Cherry-pick of PR #11821 to 6.7 branch. Original message: 
Fix #11733

Cherry-pick #11821 to 6.7: Fix redis key example pattern in docs

---

filebeat/docs/modules/suricata.asciidoc
x-pack/filebeat/module/suricata/_meta/docs.asciidoc

Add config example to replace TODO in Suricata module documentation.

Fix TODO in Suricata doc

---

testing/environments/snapshot.yml

[6.7] Update to most recent stack snaphost for testing

---

metricbeat/module/prometheus/collector/_meta/docs.asciidoc

backported at @DanRoscigno 's request.

Cherry-pick of #11865: change hostname/port of example for scraping an exporter 

---

libbeat/docs/repositories.asciidoc

Cherry-picks #11774 into 7.0 branch.

[7.0] Backport: Add info about OSS repos (#11774)

---

deploy/kubernetes/auditbeat-kubernetes.yaml
deploy/kubernetes/filebeat-kubernetes.yaml
deploy/kubernetes/metricbeat-kubernetes.yaml
libbeat/docs/version.asciidoc

Revert "Bump docs version for 6.7.2"

---

metricbeat/module/nats/connections/connections.go
metricbeat/module/nats/connections/connections_integration_test.go
metricbeat/module/nats/connections/connections_test.go
metricbeat/module/nats/connections/data.go
metricbeat/module/nats/routes/data.go
metricbeat/module/nats/routes/routes.go
metricbeat/module/nats/routes/routes_integration_test.go
metricbeat/module/nats/routes/routes_test.go
metricbeat/module/nats/stats/data.go
metricbeat/module/nats/stats/stats.go
metricbeat/module/nats/stats/stats_integration_test.go
metricbeat/module/nats/stats/stats_test.go
metricbeat/module/nats/subscriptions/data.go
metricbeat/module/nats/subscriptions/subscriptions.go
metricbeat/module/nats/subscriptions/subscriptions_integration_test.go
metricbeat/module/nats/subscriptions/subscriptions_test.go

[Metricbeat] Migrate NATS to reporterv2 with error handling

---

deploy/docker/journalbeat.docker.yml
libbeat/docs/shared-docker.asciidoc

Fixes the issue described here:
https://github.com/elastic/beats/pull/10387#issuecomment-462902112
Please respond to my question flagged for REVIEWERS.

Fix docker run example for Journalbeat

---

metricbeat/docs/autodiscover-hints.asciidoc

Fix typo in autodiscover docs

---

filebeat/docs/autodiscover-hints.asciidoc

Fix typo in Filebeat autodiscover hints doc

---

libbeat/docs/upgrading.asciidoc

Cherry-picks #11793 into 7.x branch.

[7.0] Backport: Clarify docs to indicate that aliases will not fix type mismatches

---

CHANGELOG-developer.next.asciidoc
libbeat/tests/system/requirements.txt

Update python package urllib3 used for system tests.

Update urllib3 to version 1.24.2

---

CHANGELOG.next.asciidoc
metricbeat/module/windows/perfmon/pdh_integration_windows_test.go
metricbeat/module/windows/perfmon/pdh_windows.go

Assign object name from counter path when the instance name is not defined

---

metricbeat/docker-compose.yml
metricbeat/docs/modules/mysql.asciidoc
metricbeat/module/mysql/_meta/docs.asciidoc
metricbeat/tests/system/test_mysql.py

Update MariaDB versions and include 10.4 too.

Update MariaDB versions

---

CHANGELOG.next.asciidoc
libbeat/docs/processors-using.asciidoc
libbeat/processors/decode_csv_fields/decode_csv_fields.go

#11753 was merged with a few issues:
- Missing changelog entry
- Lack of support for the `when` clause
- A few mistakes in the docs

Fixes for the decode_csv_fields processor

---

filebeat/generator/module/module.go
libbeat/dashboards/export.go

motivated by removing dependency on filebeat from libbeat

mkdir directly instead for single dir

---

dev-tools/generate_notice.py

following up on vendored beats changes in https://github.com/elastic/apm-server/pull/2133

consider COPYING for license info

---

CHANGELOG.next.asciidoc
x-pack/metricbeat/module/aws/ec2/_meta/docs.asciidoc

* Update documentation with cloudwatch:ListMetrics permission
* Update changelog
(cherry picked from commit 262e51ac460dabcbff54dfe781478a605bda9e69)

Cherry-pick to 7.1: Update documentation with cloudwatch:ListMetrics permission (#11987)

---

filebeat/docs/modules/iptables.asciidoc
x-pack/filebeat/module/iptables/_meta/docs.asciidoc

Forward ports #11852 to master branch.

[master] Forward port: Update docs.asciidoc (#11852)

---

filebeat/docs/modules/iptables.asciidoc
x-pack/filebeat/module/iptables/_meta/docs.asciidoc

Forward ports #11852 to the 7.1 branch.

[7.1] Forward port: Update docs.asciidoc (#11852)

---

libbeat/docs/upgrade-setup-commands.asciidoc

Backports #11862 to 7.1 branch.

[7.1] Backport: Add more platform-specific commands (#11862)

---

libbeat/docs/upgrade-setup-commands.asciidoc

Backports #11862 to 7.0 branch.

[7.0] Backport: Add more platform-specific commands (#11862)

---

filebeat/docs/getting-started.asciidoc

Fixes broken link in the doc build.

[Docs] Comment out section that contains bad link

---

filebeat/docs/getting-started.asciidoc

Backports #12152 to 7.0 branch.

[7.0][Docs] Backport: Comment out section that contains bad link (#12152)

---

filebeat/docs/getting-started.asciidoc

Backports #12152 to 7.1 branch.

[7.1][Docs] Backport: Comment out section that contains bad link (#12152)

---

libbeat/docs/communitybeats.asciidoc

Querying ZFS Storage and Pool Status

Add zfs beat

---

CHANGELOG.asciidoc
libbeat/docs/release.asciidoc

Release notes updates for 6.8.0

---

CHANGELOG.asciidoc
libbeat/docs/release.asciidoc

Changes needed for 7.1.0 release

Release notes for 7.1.0

---

libbeat/docs/version.asciidoc

This PR updates the documentation version in the 7.x branch

[DOCS] Updates 7.3 version attributes

---

journalbeat/docs/getting-started.asciidoc
journalbeat/docs/index.asciidoc

Backports #11931 to the 7.1 branch.

[7.1] Backport: Remove dashboard info from Journalbeat (#11931)

---

deploy/docker/journalbeat.docker.yml
libbeat/docs/shared-docker.asciidoc

Backports #10739 to 7.0 branch.

[7.0] Backport: Fix docker run example for Journalbeat (#10739)

---

deploy/docker/journalbeat.docker.yml
libbeat/docs/shared-docker.asciidoc

Backports #10739 to 7.1 branch.

[7.1] Backport: Fix docker run example for Journalbeat (#10739)

---

journalbeat/docs/getting-started.asciidoc
journalbeat/docs/index.asciidoc

Backports #11931 to the 7.0 branch.

[7.0] Backport: Remove dashboard info from Journalbeat (#11931)

---

x-pack/libbeat/licenser/es_callback.go

Backports the following commits to 7.1:
- Better error message  (#12260)

[7.1] Better error message (#12260)

---

deploy/kubernetes/auditbeat-kubernetes.yaml
deploy/kubernetes/filebeat-kubernetes.yaml
deploy/kubernetes/metricbeat-kubernetes.yaml
dev-tools/jenkins_ci.ps1
dev-tools/jenkins_ci.sh
libbeat/docs/version.asciidoc

DO NOT MERGE THIS UNTIL RELEASE

Bump docs version for 7.1.1

---

auditbeat/docs/auditbeat-modules-config.asciidoc

Forward ports #12176 to the master branch.

[master] Forward port: Update auditbeat-modules-config.asciidoc (#12176)

---

auditbeat/docs/auditbeat-modules-config.asciidoc

Forward ports #12176 to the 7.1 branch.

[7.1] Forward port: Update auditbeat-modules-config.asciidoc (#12176)

---

auditbeat/docs/auditbeat-modules-config.asciidoc

Forward ports #12176 to the 7.2 branch.

[7.2] Forward port: Update auditbeat-modules-config.asciidoc (#12176)

---

libbeat/docs/monitoring/monitoring-beats.asciidoc
libbeat/docs/security/users.asciidoc

A couple of fixes for minor issues that I noticed while doing backports.

Remove to-do and fix attribute resolution

---

filebeat/docs/modules/iptables.asciidoc
x-pack/filebeat/module/iptables/_meta/docs.asciidoc

Backports #12077 to 7.0 branch.

[7.0] Backport: Remove empty sections (#12077)

---

filebeat/docs/modules/iptables.asciidoc
x-pack/filebeat/module/iptables/_meta/docs.asciidoc

Backports #12077 to the 7.1 branch.

[7.1] Backport: Remove empty sections (#12077)

---

libbeat/docs/shared-autodiscover.asciidoc

Fix hard coded beats name

---

filebeat/docs/modules/cisco.asciidoc
filebeat/docs/modules/iptables.asciidoc
filebeat/docs/modules/netflow.asciidoc
x-pack/filebeat/module/cisco/_meta/docs.asciidoc
x-pack/filebeat/module/iptables/_meta/docs.asciidoc
x-pack/filebeat/module/netflow/_meta/docs.asciidoc

Backports #12077 to the 7.2 branch.

[7.2] Backport: Remove empty sections (#12077)

---

libbeat/docs/highlights-7.2.0.asciidoc
libbeat/docs/highlights.asciidoc

Adds placeholder file for 7.2 release highlights.

[DOCS] Add 7.2 release highlights

---

winlogbeat/docs/index.asciidoc
winlogbeat/docs/modules.asciidoc
winlogbeat/docs/modules/security.asciidoc
winlogbeat/docs/modules/sysmon.asciidoc
winlogbeat/docs/modules_list.asciidoc
winlogbeat/scripts/mage/docs.go
winlogbeat/scripts/mage/update.go
x-pack/winlogbeat/module/security/_meta/docs.asciidoc
x-pack/winlogbeat/module/sysmon/_meta/docs.asciidoc

Cherry-pick of PR #12361 to 7.2 branch. Original message: 
Add documentation for the security and sysmon modules that explains
what the modules accomplish and how to configure them.
Relates #11651

Cherry-pick #12361 to 7.2: Add documentation for Winlogbeat modules

---

metricbeat/module/elasticsearch/elasticsearch_integration_test.go

Backports the following commits to 7.2:
- Un-skip flaky tests  (#12388)

[7.2] Un-skip flaky tests (#12388)

---

metricbeat/docs/modules/elasticsearch.asciidoc
metricbeat/docs/modules/kibana.asciidoc
metricbeat/module/elasticsearch/_meta/docs.asciidoc
metricbeat/module/kibana/_meta/docs.asciidoc

Backports https://github.com/elastic/beats/pull/12309

[DOCS] Updates Elasticsearch and Kibana modules

---

x-pack/filebeat/module/envoyproxy/README.md

Fix issue #[12381](https://github.com/elastic/beats/issues/12381)

Update filebeat EnvoyProxy module README file to reflect the changes to autodiscover default input settings

---

testing/environments/latest.yml
testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

Update 7.2 branch to the appropriate snapshots.

---

metricbeat/module/elasticsearch/elasticsearch_integration_test.go

Backports the following commits to 7.1:
- Fix flaky test in Elasticsearch module  (#10874)

[7.1] Fix flaky test in Elasticsearch module (#10874)

---

libbeat/docs/highlights-7.2.0.asciidoc
libbeat/docs/highlights.asciidoc

Backports #12378 to 7.2 branch.

[DOCS] [7.2] Backport: Add 7.2 release highlights (#12378)

---

libbeat/docs/shared-autodiscover.asciidoc

Backports #11905 to 7.1 branch.

[DOCS][7.1] Backport: Fix hard coded beats name (#11905)

---

CHANGELOG.next.asciidoc
filebeat/module/system/auth/ingest/pipeline.json
filebeat/module/system/auth/test/timestamp.log
filebeat/module/system/auth/test/timestamp.log-expected.json
filebeat/tests/system/test_modules.py

Followup of #12568 for system/auth.

Filebeat: Add support for ISO8601 dates to system.auth

---

packetbeat/magefile.go

Fix check for docker user in packetbeat packaging

---

deploy/kubernetes/auditbeat-kubernetes.yaml
deploy/kubernetes/filebeat-kubernetes.yaml
deploy/kubernetes/metricbeat-kubernetes.yaml
libbeat/docs/version.asciidoc

Bump docs version for 6.8.1

---

auditbeat/docs/getting-started.asciidoc
filebeat/docs/getting-started.asciidoc
heartbeat/docs/getting-started.asciidoc
libbeat/docs/dashboards.asciidoc
libbeat/docs/shared-brew-install.asciidoc
libbeat/docs/shared-brew-run.asciidoc
libbeat/docs/shared-directory-layout.asciidoc
libbeat/docs/shared-template-load.asciidoc
metricbeat/docs/gettingstarted.asciidoc
packetbeat/docs/gettingstarted.asciidoc

Backports #12607 to 7.1 branch.

 [DOCS] [7.1] Backport: Add homebrew instructions to install docs  (#12607)

---

auditbeat/docs/getting-started.asciidoc
filebeat/docs/getting-started.asciidoc
heartbeat/docs/getting-started.asciidoc
libbeat/docs/dashboards.asciidoc
libbeat/docs/shared-brew-install.asciidoc
libbeat/docs/shared-brew-run.asciidoc
libbeat/docs/shared-directory-layout.asciidoc
libbeat/docs/shared-template-load.asciidoc
metricbeat/docs/gettingstarted.asciidoc
packetbeat/docs/gettingstarted.asciidoc

Backports #12607 to 7.2 branch.

 [DOCS] [7.2] Backport: Add homebrew instructions to install docs  (#12607)

---

libbeat/docs/shared-brew-install.asciidoc

Backports #12626 to 7.2 branch.

[DOCS] [7.2] Add missing attribute (#12626)

---

CHANGELOG-developer.asciidoc
libbeat/autodiscover/builder/helper.go

`GetConfigs` would be a useful API to expose for being able to get back a slice of `MapStr` objects.

Add helper to get configurations from hints

---

libbeat/docs/command-reference.asciidoc

Backports the following commits to 7.2:
- [docs] Update cmd docs for export and setup.  (#12583)

[7.2] [docs] Update cmd docs for export and setup. (#12583)

---

metricbeat/docs/fields.asciidoc

This PR should fix the failing `master` build.

Regenerating docs

---

docs/devguide/contributing.asciidoc
docs/devguide/newbeat.asciidoc

Backports #10384 to the 7.2 branch.

[DOCS][7.2] Remove duplicated content about setting up the dev environment (#10384)

---

libbeat/docs/highlights-7.2.0.asciidoc

Backports #12654 to 7.2 branch.

[DOCS] [7.2] Add 7.2 release highlights (#12654)

---

libbeat/docs/version.asciidoc

Bump docs version for 7.2.0

---

libbeat/docs/outputconfig.asciidoc

Closes https://github.com/elastic/beats/issues/6142

Add example for setting kafka topic dynamically

---

packetbeat/docs/faq.asciidoc
packetbeat/docs/gettingstarted.asciidoc

Backports #12481 and #12537 to 7.1 branch.

[DOCS][7.1] Backport 12481 and 12537

---

packetbeat/docs/faq.asciidoc
packetbeat/docs/gettingstarted.asciidoc

Backports #12481 and #12537 to 7.2 branch.

[DOCS][7.2] Backport 12481 and 12537

---

libbeat/docs/outputconfig.asciidoc

Backports #12058 to 7.1 branch.

[DOCS][7.1] Backport: Add example for setting kafka topic dynamically (#12058)

---

libbeat/docs/outputconfig.asciidoc

Backports #12058 to 7.2 branch.

[DOCS][7.2] Backport: Add example for setting kafka topic dynamically (#12058)

---

filebeat/docs/getting-started.asciidoc

Backports #12658 to the 7.2 branch.

[DOCS] [7.2] Backport: Remove logstash from main flow of Filebeat getting started

---

libbeat/tests/resources/goroutines_test.go

https://github.com/elastic/beats/issues/12692

Skip flaky test for goroutines checker

---

metricbeat/module/logstash/logstash.go

This PR removes unused code in the `logstash` Metricbeat module.

Removing unused code

---

metricbeat/module/jolokia/_meta/Dockerfile

Central maven is failing on Travis.

Use sonatype mirror to download jolokia

---

libbeat/scripts/Makefile
script/build_docs.sh

Moves `make docs` and `make docs-preview` to the new docker build script. Updates the description as well.

[docs] Update build script and descriptions

---

CHANGELOG.next.asciidoc
journalbeat/reader/journal.go

I have cleaned up the coda around reading entries and fixed an issue when iterating through journals.
Closes #11505

Refactoring of entry reading

---

libbeat/docs/communitybeats.asciidoc

Added [discobeat](https://github.com/hellmouthengine/discobeat) to the list of community beats

Added discobeat to the list of community beats

---

metricbeat/module/beat/_meta/Dockerfile
metricbeat/module/elasticsearch/_meta/Dockerfile
metricbeat/module/kibana/_meta/Dockerfile
metricbeat/module/logstash/_meta/Dockerfile

Bump ELK images for metricbeat tests

[Metricbeat]bump ELK image tags to 7.2.0

---

docs/devguide/contributing.asciidoc

Closes https://github.com/elastic/beats/issues/9532

Mention default branch in developer documentation

---

auditbeat/auditbeat.reference.yml
filebeat/filebeat.reference.yml
heartbeat/heartbeat.reference.yml
journalbeat/journalbeat.reference.yml
libbeat/_meta/config.reference.yml.tmpl
metricbeat/metricbeat.reference.yml
packetbeat/packetbeat.reference.yml
winlogbeat/winlogbeat.reference.yml
x-pack/auditbeat/auditbeat.reference.yml
x-pack/filebeat/filebeat.reference.yml
x-pack/functionbeat/functionbeat.reference.yml
x-pack/metricbeat/metricbeat.reference.yml
x-pack/winlogbeat/winlogbeat.reference.yml

Add missing ILM options

---

libbeat/docs/shared-getting-started-intro.asciidoc
libbeat/docs/shared-ilm.asciidoc
libbeat/docs/shared-template-load.asciidoc

Backports #11984 to 7.2 branch

[7.2][DOCS] Backport: Add pointer to ILM docs for setting index name (#11984)

---

libbeat/docs/shared-getting-started-intro.asciidoc
libbeat/docs/shared-ilm.asciidoc
libbeat/docs/shared-template-load.asciidoc

Backports #11984 to 7.3 branch.

[7.3][DOCS] Backport: Add pointer to ILM docs for setting index name (#11984)

---

auditbeat/auditbeat.reference.yml
filebeat/filebeat.reference.yml
heartbeat/heartbeat.reference.yml
journalbeat/journalbeat.reference.yml
libbeat/_meta/config.reference.yml
metricbeat/metricbeat.reference.yml
packetbeat/packetbeat.reference.yml
winlogbeat/winlogbeat.reference.yml
x-pack/auditbeat/auditbeat.reference.yml
x-pack/filebeat/filebeat.reference.yml
x-pack/functionbeat/functionbeat.reference.yml
x-pack/metricbeat/metricbeat.reference.yml
x-pack/winlogbeat/winlogbeat.reference.yml

Backports #11985 to 7.2 branch

[7.2][DOCS] Backport: Add missing ILM options (#11985)

---

auditbeat/auditbeat.reference.yml
filebeat/filebeat.reference.yml
heartbeat/heartbeat.reference.yml
journalbeat/journalbeat.reference.yml
libbeat/_meta/config.reference.yml.tmpl
metricbeat/metricbeat.reference.yml
packetbeat/packetbeat.reference.yml
winlogbeat/winlogbeat.reference.yml
x-pack/auditbeat/auditbeat.reference.yml
x-pack/filebeat/filebeat.reference.yml
x-pack/functionbeat/functionbeat.reference.yml
x-pack/metricbeat/metricbeat.reference.yml
x-pack/winlogbeat/winlogbeat.reference.yml

Backports #11985 to 7.3 branch

[7.3][DOCS] Backport: Add missing ILM options (#11985)

---

filebeat/docs/getting-started.asciidoc
filebeat/docs/include/enable-modules-command.asciidoc
filebeat/docs/include/list-modules-command.asciidoc
filebeat/docs/include/run-command.asciidoc
filebeat/docs/include/set-paths.asciidoc
filebeat/docs/include/setup-command.asciidoc
heartbeat/docs/getting-started.asciidoc
libbeat/docs/dashboards.asciidoc
libbeat/docs/shared-brew-run.asciidoc
libbeat/docs/shared-template-load.asciidoc
libbeat/docs/step-test-config.asciidoc
metricbeat/docs/gettingstarted.asciidoc
packetbeat/docs/gettingstarted.asciidoc
packetbeat/docs/index.asciidoc

Backports #12642 to 7.2 branch.

[7.2][DOCS] Backport: Add missing run steps for brew installs (#12642)

---

filebeat/docs/getting-started.asciidoc
filebeat/docs/include/enable-modules-command.asciidoc
filebeat/docs/include/list-modules-command.asciidoc
filebeat/docs/include/run-command.asciidoc
filebeat/docs/include/set-paths.asciidoc
filebeat/docs/include/setup-command.asciidoc
heartbeat/docs/getting-started.asciidoc
libbeat/docs/dashboards.asciidoc
libbeat/docs/shared-brew-run.asciidoc
libbeat/docs/shared-template-load.asciidoc
libbeat/docs/step-test-config.asciidoc
metricbeat/docs/gettingstarted.asciidoc
packetbeat/docs/gettingstarted.asciidoc
packetbeat/docs/index.asciidoc

Backports #12642 to 7.3 branch.

[7.3][DOCS] Backport: Add missing run steps for brew installs (#12642)

---

deploy/kubernetes/auditbeat-kubernetes.yaml
deploy/kubernetes/filebeat-kubernetes.yaml
deploy/kubernetes/metricbeat-kubernetes.yaml
libbeat/docs/version.asciidoc

Bump docs version for 7.2.1

---

metricbeat/module/elasticsearch/elasticsearch.go

Prior to this PR, there was a somewhat nasty bug in the `elasticsearch` Metricbeat module code that fetches and caches the license from Elastiscsearch. This bug could potentially result in a runtime `nil` pointer panic error on this line:
https://github.com/elastic/beats/blob/6e38be9f1b127f2054333236182665b134620033/metricbeat/module/elasticsearch/elasticsearch.go#L392
This could only happen if `l` (which is of type `*License`) is `nil`. The only bit of code that sets this memory location to `nil` is this line, which does so when the license cache has expired:
https://github.com/elastic/beats/blob/e5c955ff166c0766ce9e4cca4ce9c4c06dbf9de7/metricbeat/module/elasticsearch/elasticsearch.go#L447
Now consider the implementation of the `GetLicense` function, in particular these operations within …

Fix license nil pointer scenario

---

metricbeat/module/elasticsearch/elasticsearch.go

Backports the following commits to 7.3:
- Fix license nil pointer scenario  (#12958)

[7.3] Fix license nil pointer scenario (#12958)

---

metricbeat/module/elasticsearch/elasticsearch.go

Backports the following commits to 7.2:
- Fix license nil pointer scenario  (#12958)

[7.2] Fix license nil pointer scenario (#12958)

---

filebeat/tests/system/test_tcp_tls.py

Disable the flaky test reported in #13009

[Filebeat] Disable flaky test_tcp_over_tls_mutual_auth_succeed

---

metricbeat/docs/gettingstarted.asciidoc

Backports #13000 into 7.2 branch.

[7.2][DOCS] Backport: Update gettingstarted.asciidoc (#13000)

---

script/build_docs.sh

[7.2] Fix make docs

---

script/build_docs.sh

Fixes broken CI caused by `make docs` failing.

[6.8] Fix make docs

---

metricbeat/module/elasticsearch/elasticsearch_integration_test.go

If license is already enabled, tests will fail. This happens if tests
are run twice with the same ES instance.

Avoid re-enabling trial license on ES tests

---

deploy/kubernetes/auditbeat-kubernetes.yaml
deploy/kubernetes/filebeat-kubernetes.yaml
deploy/kubernetes/metricbeat-kubernetes.yaml
libbeat/docs/version.asciidoc

Bump docs version for 6.8.2

---

libbeat/docs/version.asciidoc

Bump docs version for 7.3.0

---

libbeat/docs/highlights-7.3.0.asciidoc
libbeat/docs/highlights.asciidoc

Content taken from the 7.3.0 release blog and modified to be consistent with the docs.

[DOCS] Add 7.3 release highlights

---

docs/devguide/newdashboards.asciidoc
libbeat/docs/shared-template-load.asciidoc

Backports #12882 to 7.3 branch

[7.3][DOCS] Backport: Replace deprecated --template option with --index-management

---

libbeat/docs/highlights-7.3.0.asciidoc
libbeat/docs/highlights.asciidoc

Backports #13138 to 7.3 branch.

[7.3][DOCS] Backport: Add 7.3 release highlights (#13138)

---

libbeat/docs/outputconfig.asciidoc

Backports #13035 to 7.3 branch.

[7.3][DOCS] Backport: Add pointer to ILM docs from index setting (#13035)

---

libbeat/docs/upgrading.asciidoc

Backports #12932 to 7.3 branch.

[7.3][DOCS] Backport: Add link to blog post about migrating to ECS (#12932)

---

script/build_docs.sh

Backports #13063 to 7.0 branch.

[7.0][DOCS] Backport: Fix make docs (#13063)

---

script/build_docs.sh

Backports #13063 to 7.1 branch.

[7.1][DOCS] Backport: Fix make docs (#13063)

---

libbeat/docs/outputconfig.asciidoc

Backports #13035 to 7.0 branch.

[7.0][DOCS] Backport: Add pointer to ILM docs from index setting (#13035)

---

libbeat/docs/outputconfig.asciidoc

Backports #13035 into 7.1 branch

[7.1][DOCS] Backport: Add pointer to ILM docs from index setting (#13035)

---

libbeat/docs/outputconfig.asciidoc

Backports #13035 to 7.2 branch

[7.2][DOCS] Backport: Add pointer to ILM docs from index setting (#13035)

---

filebeat/docs/modules/ibmmq.asciidoc
x-pack/filebeat/module/ibmmq/_meta/docs.asciidoc

 Update IBM MQ module documentation

---

.github/CODEOWNERS

As discussed internally comment out elastic/beats from CODEOWNERS file
for now.

Remove elastic/beats from CODEOWNERS

---

docs/devguide/create-metricset.asciidoc
docs/devguide/create-module.asciidoc

A few things are not displayed correctly [here](https://www.elastic.co/guide/en/beats/devguide/current/creating-metricbeat-module.html#_test_a_metricbeat_module_manually).
These changes should help address this issue.

Docs fixes for creating a new metricbeat module

---

libbeat/docs/communitybeats.asciidoc

Adds new community beat: earthquakebeat

Adds new community beat: Earthquakebeat

---

auditbeat/docs/faq-ulimit.asciidoc
auditbeat/docs/faq.asciidoc
filebeat/docs/faq.asciidoc
heartbeat/docs/faq.asciidoc
journalbeat/docs/faq.asciidoc
libbeat/docs/faq-limit-bandwidth.asciidoc
libbeat/docs/faq-refresh-index.asciidoc
libbeat/docs/shared-faq.asciidoc
metricbeat/docs/faq.asciidoc
packetbeat/docs/faq-mysql-ssl.asciidoc
packetbeat/docs/faq.asciidoc
winlogbeat/docs/faq.asciidoc
x-pack/functionbeat/docs/faq.asciidoc

Backports #12992 to 7.3 branch.
@karenzone FYI

[7.3][DOCS] Backport: Make each troubleshooting item a separate topic (#12992)

---

auditbeat/docs/faq-ulimit.asciidoc
auditbeat/docs/faq.asciidoc
filebeat/docs/faq.asciidoc
heartbeat/docs/faq.asciidoc
journalbeat/docs/faq.asciidoc
libbeat/docs/faq-limit-bandwidth.asciidoc
libbeat/docs/faq-refresh-index.asciidoc
libbeat/docs/shared-faq.asciidoc
metricbeat/docs/faq.asciidoc
packetbeat/docs/faq-mysql-ssl.asciidoc
packetbeat/docs/faq.asciidoc
winlogbeat/docs/faq.asciidoc
x-pack/functionbeat/docs/faq.asciidoc

Backports #12992 to 7.3 branch.
@karenzone FYI

[7.2][DOCS] Backport: Make each troubleshooting item a separate topic (#12992)

---

deploy/kubernetes/auditbeat-kubernetes.yaml
deploy/kubernetes/filebeat-kubernetes.yaml
deploy/kubernetes/metricbeat-kubernetes.yaml
libbeat/docs/version.asciidoc

Bump docs version for 7.3.1

---

metricbeat/docs/modules/aws.asciidoc
x-pack/metricbeat/module/aws/_meta/docs.asciidoc
x-pack/metricbeat/module/aws/cloudwatch/_meta/docs.asciidoc

Found some documentations not up-to-date, this PR is to fix them.

[Docs] Fix aws cloudwatch metricset documentation

---

libbeat/docs/monitoring/monitoring-beats.asciidoc
libbeat/docs/monitoring/monitoring-internal-collection.asciidoc
libbeat/docs/monitoring/monitoring-metricbeat.asciidoc
libbeat/docs/outputconfig.asciidoc
libbeat/docs/security/users.asciidoc

This PR persists some of the documentation changes needed in https://github.com/elastic/apm-server/pull/2542. This PR also includes a commit (b2b9d36) with Asciidoctor fixes.

[docs] Documentation changes from APM Server

---

x-pack/functionbeat/docs/config-options.asciidoc
x-pack/functionbeat/docs/faq-resource-limit.asciidoc
x-pack/functionbeat/docs/faq.asciidoc
x-pack/functionbeat/docs/getting-started.asciidoc
x-pack/functionbeat/docs/iam-permissions.asciidoc
x-pack/functionbeat/docs/setting-up-running.asciidoc

Closes issue #11787 
Please respond to questions flagged for reviewers. Note that I made some changes to the policies shown in the issue because they had syntax errors and missing permissions.
I documented the permission as requested in the issue. However, I also noticed that there is no explanation of the `role` and `virtual_private_cloud` settings in the documentation. Do you want me to add these? If so, I can create a follow-on PR.

[DOCS] Document AIM permissions required for Functionbeat

---

x-pack/functionbeat/provider/aws/aws/transformer/transformer_test.go

Add test for cloudwatch timestamp

---

CHANGELOG.next.asciidoc
libbeat/autodiscover/providers/kubernetes/kubernetes.go
libbeat/autodiscover/providers/kubernetes/kubernetes_test.go
libbeat/common/kubernetes/metadata.go
libbeat/processors/add_kubernetes_metadata/indexers.go
libbeat/processors/add_kubernetes_metadata/indexers_test.go

Fixes https://github.com/elastic/beats/issues/12688

Add container image in Kubernetes metadata

---

libbeat/docs/queueconfig.asciidoc

Fixed tiny typo

---

filebeat/docs/modules/cisco.asciidoc
x-pack/filebeat/module/cisco/_meta/docs.asciidoc
x-pack/filebeat/module/cisco/shared/gen.go

Forgot this two changes that address review comments:
- Rename of the mapping section in the docs.
- Add an explanatory comment to the generator

Missing changes for Cisco FTD (#13286)

---

libbeat/docs/shared-ilm.asciidoc

agent.version should surrounded by %{} to be resolved

fix ilm.policy_name default value

---

LICENSE.txt

This reverts commit fb1641161961317a4dda02a7c2d90f8e266a51d1.

Revert "Update license test for the repository"

---

LICENSE.txt

This reverts commit f28055f6d37691980bb286ef1ea47b65e76ed164.

Revert "Update license test for the repository (#13347)"

---

libbeat/docs/queueconfig.asciidoc

Documentation Fix:
https://github.com/elastic/beats/pull/12704

Fix for typo

---

CHANGELOG.next.asciidoc

Cherry-pick of PR #13431 to 7.4 branch. Original message:

Cherry-pick #13431 to 7.4: Add missing changelog entries

---

CHANGELOG.next.asciidoc

Missing changelog enty for #13058

[Auditbeat] system/socket: Add changelog entry

---

CHANGELOG.next.asciidoc

Cherry-pick of PR #13445 to 7.4 branch. Original message: 
Missing changelog enty for #13058

Cherry-pick #13445 to 7.4: [Auditbeat] system/socket: Add changelog entry

---

libbeat/docs/command-reference.asciidoc
x-pack/functionbeat/docs/export-cloudformation-template.asciidoc
x-pack/functionbeat/docs/getting-started.asciidoc
x-pack/functionbeat/docs/index.asciidoc
x-pack/functionbeat/docs/setting-up-running.asciidoc

Closes https://github.com/elastic/beats/issues/13095

[DOCS] Document export function command

---

CHANGELOG.next.asciidoc

Backports the following commits to 7.4:
- added statsd module changelog entry  (#13463)

[7.4] added statsd module changelog entry (#13463)

---

auditbeat/docs/fields.asciidoc
docs/devguide/migrate-dashboards.asciidoc
docs/devguide/newdashboards.asciidoc
filebeat/docs/fields.asciidoc
filebeat/docs/index.asciidoc
journalbeat/docs/config-options.asciidoc
journalbeat/docs/filtering.asciidoc
journalbeat/docs/general-options.asciidoc
journalbeat/docs/getting-started.asciidoc
journalbeat/docs/index.asciidoc
libbeat/docs/command-reference.asciidoc
libbeat/docs/monitoring/monitoring-beats.asciidoc
libbeat/docs/outputconfig.asciidoc
libbeat/docs/processors-using.asciidoc
libbeat/docs/reference-yml.asciidoc
libbeat/docs/security/securing-beats.asciidoc
libbeat/docs/shared-central-management.asciidoc
libbeat/docs/shared-docker.asciidoc
libbeat/docs/shared-path-config.asciidoc
libbeat/docs/step-configure-output.asciidoc
libbeat/scripts/generate_fields_docs.py
metricbeat/docs/index.asciidoc
metricbeat/docs/modules_list.asciidoc
metricbeat/scripts/docs_collector.py
packetbeat/docs/packetbeat-filtering.asciidoc
winlogbeat/docs/index.asciidoc

Backports the following PRs to the 7.1 branch and adds additional commits to get the asciidoctor build working in 7.1.
https://github.com/elastic/beats/pull/12006
https://github.com/elastic/beats/pull/12434

[7.1][DOCS] Backport: Fix asciidoctor build

---

auditbeat/docs/fields.asciidoc
docs/devguide/migrate-dashboards.asciidoc
docs/devguide/newdashboards.asciidoc
filebeat/docs/fields.asciidoc
filebeat/docs/index.asciidoc
journalbeat/docs/config-options.asciidoc
journalbeat/docs/filtering.asciidoc
journalbeat/docs/general-options.asciidoc
journalbeat/docs/getting-started.asciidoc
journalbeat/docs/index.asciidoc
libbeat/docs/command-reference.asciidoc
libbeat/docs/monitoring/monitoring-beats.asciidoc
libbeat/docs/outputconfig.asciidoc
libbeat/docs/processors-using.asciidoc
libbeat/docs/reference-yml.asciidoc
libbeat/docs/security/securing-beats.asciidoc
libbeat/docs/shared-central-management.asciidoc
libbeat/docs/shared-docker.asciidoc
libbeat/docs/shared-path-config.asciidoc
libbeat/docs/step-configure-output.asciidoc
libbeat/scripts/generate_fields_docs.py
metricbeat/docs/index.asciidoc
metricbeat/docs/modules_list.asciidoc
metricbeat/scripts/docs_collector.py
packetbeat/docs/packetbeat-filtering.asciidoc
winlogbeat/docs/index.asciidoc

Backports asciidoctor build fixes to 7.0 and removes attributes that are no relevant in this branch.

[7.0][DOCS] Backports asciidoctor build fixes

---

deploy/kubernetes/auditbeat-kubernetes.yaml
deploy/kubernetes/filebeat-kubernetes.yaml
deploy/kubernetes/metricbeat-kubernetes.yaml
libbeat/docs/version.asciidoc

Bump docs version for 6.8.3

---

x-pack/auditbeat/module/system/socket/events.go
x-pack/auditbeat/module/system/socket/kprobes.go
x-pack/auditbeat/module/system/socket/state.go
x-pack/auditbeat/tests/system/test_system_socket.py

Cherry-pick of PR #13470 to 7.4 branch. Original message: 
This fixes a few problems with UDP:
- IPv6/UDP unconnected support was missing.
- Lost packets in UDP due to using zero-destination address.
Added more tests.
Relates #13058

Cherry-pick #13470 to 7.4: [SIEM] [Auditbeat] system/socket: Fix UDP flows

---

libbeat/docs/gettingstarted.asciidoc

Add Azure to the list of available cloud platforms.

Update the list of available cloud platforms

---

auditbeat/docs/fields.asciidoc
docs/devguide/migrate-dashboards.asciidoc
docs/devguide/newdashboards.asciidoc
filebeat/docs/index.asciidoc
heartbeat/docs/fields.asciidoc
journalbeat/docs/config-options.asciidoc
journalbeat/docs/filtering.asciidoc
journalbeat/docs/general-options.asciidoc
journalbeat/docs/getting-started.asciidoc
libbeat/docs/command-reference.asciidoc
libbeat/docs/monitoring/monitoring-beats.asciidoc
libbeat/docs/outputconfig.asciidoc
libbeat/docs/processors-using.asciidoc
libbeat/docs/reference-yml.asciidoc
libbeat/docs/security/securing-beats.asciidoc
libbeat/docs/shared-central-management.asciidoc
libbeat/docs/shared-docker.asciidoc
libbeat/docs/shared-path-config.asciidoc
libbeat/docs/step-configure-output.asciidoc
libbeat/scripts/generate_fields_docs.py
metricbeat/docs/index.asciidoc
metricbeat/docs/modules_list.asciidoc
metricbeat/scripts/docs_collector.py
packetbeat/docs/packetbeat-filtering.asciidoc
script/build_docs.sh
winlogbeat/docs/index.asciidoc

Backports asciidoctor build fixes to 6.7 and removes attributes and other changes not needed for this branch.

[6.7][DOCS] Backport asciidoctor build fixes

---

auditbeat/docs/fields.asciidoc
docs/devguide/migrate-dashboards.asciidoc
docs/devguide/newdashboards.asciidoc
filebeat/docs/index.asciidoc
heartbeat/docs/fields.asciidoc
journalbeat/docs/config-options.asciidoc
journalbeat/docs/filtering.asciidoc
journalbeat/docs/general-options.asciidoc
journalbeat/docs/getting-started.asciidoc
libbeat/docs/command-reference.asciidoc
libbeat/docs/monitoring/monitoring-beats.asciidoc
libbeat/docs/outputconfig.asciidoc
libbeat/docs/processors-using.asciidoc
libbeat/docs/reference-yml.asciidoc
libbeat/docs/security/securing-beats.asciidoc
libbeat/docs/shared-central-management.asciidoc
libbeat/docs/shared-docker.asciidoc
libbeat/docs/shared-path-config.asciidoc
libbeat/docs/step-configure-output.asciidoc
libbeat/scripts/generate_fields_docs.py
metricbeat/docs/index.asciidoc
metricbeat/docs/modules_list.asciidoc
metricbeat/scripts/docs_collector.py
packetbeat/docs/packetbeat-filtering.asciidoc
script/build_docs.sh
winlogbeat/docs/index.asciidoc

Backports asciidoctor build fixes to 6.6 and removes attributes and other changes not needed for this branch.

[6.6][DOCS] Backport asciidoctor build fixes

---

filebeat/docs/command-line.asciidoc
libbeat/docs/command-line.asciidoc
packetbeat/docs/command-line.asciidoc
packetbeat/docs/filtering.asciidoc
topbeat/docs/command-line.asciidoc
winlogbeat/docs/command-line.asciidoc

Fixes asciidoctor build errors in 1.3 branch.

[1.3][DOCS] Fix asciidoctor build errors

---

filebeat/docs/command-line.asciidoc
libbeat/docs/command-line.asciidoc
packetbeat/docs/command-line.asciidoc
packetbeat/docs/filtering.asciidoc
topbeat/docs/command-line.asciidoc
winlogbeat/docs/command-line.asciidoc

Fixes asciidoctor build errors in 1.2 branch.

[1.1][DOCS] Fix asciidoctor build errors

---

filebeat/docs/command-line.asciidoc
libbeat/docs/command-line.asciidoc
packetbeat/docs/command-line.asciidoc
packetbeat/docs/filtering.asciidoc
topbeat/docs/command-line.asciidoc
winlogbeat/docs/command-line.asciidoc

Fixes asciidoctor build errors in 1.2 branch.

[1.2][DOCS] Fix asciidoctor build errors

---

filebeat/docs/command-line.asciidoc
packetbeat/docs/command-line.asciidoc
packetbeat/docs/filtering.asciidoc
packetbeat/docs/https.asciidoc
topbeat/docs/command-line.asciidoc

Fixes asciidoctor build errors in 1.0.1 branch

[1.0.1][DOCS] Fix asciidoctor build errors

---

x-pack/auditbeat/module/system/socket/_meta/docs.asciidoc
x-pack/auditbeat/module/system/socket/config.go

Cherry-pick of PR #13537 to 7.4 branch. Original message: 
Relates #13058

Cherry-pick #13537 to 7.4: [SIEM][Auditbeat] Docs for system/socket dataset

---

auditbeat/docs/fields.asciidoc
docs/devguide/migrate-dashboards.asciidoc
docs/devguide/newdashboards.asciidoc
filebeat/docs/index.asciidoc
heartbeat/docs/fields.asciidoc
journalbeat/docs/config-options.asciidoc
journalbeat/docs/filtering.asciidoc
journalbeat/docs/general-options.asciidoc
journalbeat/docs/getting-started.asciidoc
libbeat/docs/command-reference.asciidoc
libbeat/docs/monitoring/monitoring-beats.asciidoc
libbeat/docs/outputconfig.asciidoc
libbeat/docs/processors-using.asciidoc
libbeat/docs/reference-yml.asciidoc
libbeat/docs/security/securing-beats.asciidoc
libbeat/docs/shared-central-management.asciidoc
libbeat/docs/shared-docker.asciidoc
libbeat/docs/shared-path-config.asciidoc
libbeat/docs/step-configure-output.asciidoc
libbeat/scripts/generate_fields_docs.py
metricbeat/docs/index.asciidoc
metricbeat/docs/modules_list.asciidoc
metricbeat/scripts/docs_collector.py
packetbeat/docs/packetbeat-filtering.asciidoc
script/build_docs.sh
winlogbeat/docs/index.asciidoc

Backports asciidoctor build fixes to 6.5 and removes attributes and other changes not needed for this branch.

[6.5][DOCS] Backport asciidoctor build fixes

---

libbeat/docs/version.asciidoc

[Doc]Add and set ecs-version for 7.4

---

NOTICE.txt
auditbeat/docs/fields.asciidoc
docs/devguide/migrate-dashboards.asciidoc
docs/devguide/newdashboards.asciidoc
filebeat/docs/index.asciidoc
heartbeat/docs/fields.asciidoc
libbeat/docs/command-reference.asciidoc
libbeat/docs/monitoring/monitoring-beats.asciidoc
libbeat/docs/outputconfig.asciidoc
libbeat/docs/processors-using.asciidoc
libbeat/docs/reference-yml.asciidoc
libbeat/docs/security/securing-beats.asciidoc
libbeat/docs/shared-directory-layout.asciidoc
libbeat/docs/shared-docker.asciidoc
libbeat/docs/shared-path-config.asciidoc
libbeat/docs/step-configure-output.asciidoc
libbeat/scripts/generate_fields_docs.py
metricbeat/docs/index.asciidoc
metricbeat/docs/modules_list.asciidoc
metricbeat/scripts/docs_collector.py
packetbeat/docs/packetbeat-filtering.asciidoc
script/build_docs.sh
winlogbeat/docs/index.asciidoc

Backports asciidoctor build fixes to the 6.3 branch.

[6.3][DOCS] Fix asciidoctor build errors

---

NOTICE.txt
auditbeat/docs/fields.asciidoc
docs/devguide/migrate-dashboards.asciidoc
docs/devguide/newdashboards.asciidoc
filebeat/docs/index.asciidoc
heartbeat/docs/fields.asciidoc
libbeat/docs/command-reference.asciidoc
libbeat/docs/monitoring/monitoring-beats.asciidoc
libbeat/docs/outputconfig.asciidoc
libbeat/docs/processors-using.asciidoc
libbeat/docs/reference-yml.asciidoc
libbeat/docs/security/securing-beats.asciidoc
libbeat/docs/shared-directory-layout.asciidoc
libbeat/docs/shared-docker.asciidoc
libbeat/docs/shared-path-config.asciidoc
libbeat/docs/step-configure-output.asciidoc
libbeat/scripts/generate_fields_docs.py
metricbeat/docs/index.asciidoc
metricbeat/docs/modules_list.asciidoc
metricbeat/scripts/docs_collector.py
packetbeat/docs/packetbeat-filtering.asciidoc
script/build_docs.sh
winlogbeat/docs/index.asciidoc

Fixes asciidoc errors in the 6.4 branch.

[6.4][DOCS] Fix asciidoctor build errors

---

libbeat/docs/index.asciidoc
libbeat/docs/overview.asciidoc

Backports #13608 to 7.3 branch.

[7.3][DOCS] Add named anchor to fix links for asciidoctor migration (#13608)

---

libbeat/docs/index.asciidoc
libbeat/docs/overview.asciidoc

Backports #13608 to the 7.4 branch

[7.4][DOCS] Add named anchor to fix links for asciidoctor migration (#13608)

---

libbeat/docs/index.asciidoc
libbeat/docs/overview.asciidoc

Backports #13608 to 7.2 branch.

[7.2][DOCS] Add named anchor to fix links for asciidoctor migration (#13608)

---

libbeat/docs/index.asciidoc
libbeat/docs/overview.asciidoc

Backports #13608 to 7.1 branch.

[7.1][DOCS] Add named anchor to fix links for asciidoctor migration (#13608)

---

libbeat/docs/index.asciidoc
libbeat/docs/overview.asciidoc

Backports #13608 to 7.0 branch.

[7.0][DOCS] Add named anchor to fix links for asciidoctor migration (#13608)

---

libbeat/docs/index.asciidoc
libbeat/docs/overview.asciidoc

Backports #13608 to 6.5 branch.

[6.5][DOCS] Add named anchor to fix links for asciidoctor migration (#13608)

---

libbeat/docs/index.asciidoc
libbeat/docs/overview.asciidoc

Backports #13608 to 6.3 branch.

[6.3][DOCS] Add named anchor to fix links for asciidoctor migration (#13608)

---

libbeat/docs/index.asciidoc
libbeat/docs/overview.asciidoc

Backports #13608 to 5.4 branch.

[5.4][DOCS] Add named anchor to fix links for asciidoctor migration (#13608)

---

libbeat/docs/index.asciidoc
libbeat/docs/overview.asciidoc

Backports #13608 to 5.3 branch.

[5.3][DOCS] Add named anchor to fix links for asciidoctor migration (#13608)

---

libbeat/docs/index.asciidoc
libbeat/docs/overview.asciidoc

Backports #13608 to 5.2 branch.

[5.2][DOCS] Add named anchor to fix links for asciidoctor migration (#13608)

---

libbeat/docs/index.asciidoc
libbeat/docs/overview.asciidoc

Backports #13608 to 5.1 branch.

[5.1][DOCS] Add named anchor to fix links for asciidoctor migration (#13608)

---

libbeat/docs/index.asciidoc
libbeat/docs/overview.asciidoc

Backports #13608 to 5.0 branch.

[5.0][DOCS] Add named anchor to fix links for asciidoctor migration (#13608)

---

libbeat/docs/index.asciidoc
libbeat/docs/overview.asciidoc

Backports #13608 to 1.3 branch.

[1.3][DOCS] Add named anchor to fix links for asciidoctor migration (#13608)

---

libbeat/docs/index.asciidoc
libbeat/docs/overview.asciidoc

Backports #13608 to 1.2 branch.

[1.2][DOCS] Add named anchor to fix links for asciidoctor migration (#13608)

---

libbeat/docs/index.asciidoc
libbeat/docs/overview.asciidoc

Backports #13608 to 1.1 branch.

[1.1][DOCS] Add named anchor to fix links for asciidoctor migration (#13608)

---

libbeat/docs/index.asciidoc
libbeat/docs/overview.asciidoc

Backports #13608 to 1.0.1 branch.

[1.0.1][DOCS] Add named anchor to fix links for asciidoctor migration (#13608)

---

libbeat/publisher/pipeline/client.go
metricbeat/module/system/fsstat/fsstat.go

Cherry-pick of PR #13665 to 7.4 branch.

Cherry-pick #13665 to 7.4: Fix some formats in debug logs

---

libbeat/publisher/pipeline/client.go
metricbeat/module/system/fsstat/fsstat.go

Cherry-pick of PR #13665 to 7.3 branch.

Cherry-pick #13665 to 7.3: Fix some formats in debug logs

---

CHANGELOG.next.asciidoc
auditbeat/auditbeat.yml
filebeat/filebeat.yml
heartbeat/heartbeat.yml
journalbeat/journalbeat.yml
libbeat/_meta/config.yml.tmpl
metricbeat/metricbeat.yml
packetbeat/packetbeat.yml
winlogbeat/winlogbeat.yml
x-pack/auditbeat/auditbeat.yml
x-pack/filebeat/filebeat.yml
x-pack/functionbeat/functionbeat.yml
x-pack/metricbeat/metricbeat.yml
x-pack/winlogbeat/winlogbeat.yml

Backports the following commits to 7.4:
- Fix typos + add CHANGELOG  (#13481)

[7.4] Fix typos + add CHANGELOG (#13481)

---

auditbeat/docs/modules.asciidoc
docs/devguide/newbeat.asciidoc
filebeat/docs/autodiscover-hints.asciidoc
filebeat/docs/fields.asciidoc
filebeat/docs/filebeat-general-options.asciidoc
filebeat/docs/inputs/input-docker.asciidoc
filebeat/docs/inputs/input-redis.asciidoc
filebeat/docs/modules.asciidoc
filebeat/docs/modules/osquery.asciidoc
filebeat/module/osquery/_meta/docs.asciidoc
heartbeat/docs/heartbeat-options.asciidoc
journalbeat/docs/general-options.asciidoc
libbeat/docs/command-reference.asciidoc
libbeat/docs/config-file-format.asciidoc
libbeat/docs/outputconfig.asciidoc
libbeat/docs/processors-using.asciidoc
libbeat/docs/regexp.asciidoc
libbeat/docs/shared-ilm.asciidoc
libbeat/docs/shared-ssl-config.asciidoc
libbeat/docs/template-config.asciidoc
libbeat/scripts/generate_fields_docs.py
metricbeat/docs/autodiscover-hints.asciidoc
metricbeat/docs/fields.asciidoc
metricbeat/docs/modules.asciidoc
packetbeat/docs/faq.asciidoc
winlogbeat/docs/modules.asciidoc

Backports https://github.com/elastic/beats/pull/13753 to the 7.4 branch.
MUST BE MERGED ALONG WITH https://github.com/elastic/docs/pull/1178

[7.4][DOCS] Fix markup issues for asciidoctor migration 

---

auditbeat/docs/modules.asciidoc
docs/devguide/newbeat.asciidoc
filebeat/docs/autodiscover-hints.asciidoc
filebeat/docs/filebeat-general-options.asciidoc
filebeat/docs/inputs/input-docker.asciidoc
filebeat/docs/inputs/input-redis.asciidoc
filebeat/docs/modules.asciidoc
filebeat/docs/modules/osquery.asciidoc
filebeat/module/osquery/_meta/docs.asciidoc
heartbeat/docs/heartbeat-options.asciidoc
journalbeat/docs/general-options.asciidoc
libbeat/docs/command-reference.asciidoc
libbeat/docs/config-file-format.asciidoc
libbeat/docs/outputconfig.asciidoc
libbeat/docs/processors-using.asciidoc
libbeat/docs/regexp.asciidoc
libbeat/docs/shared-ilm.asciidoc
libbeat/docs/shared-ssl-config.asciidoc
libbeat/docs/template-config.asciidoc
libbeat/scripts/generate_fields_docs.py
metricbeat/docs/autodiscover-hints.asciidoc
metricbeat/docs/fields.asciidoc
metricbeat/docs/modules.asciidoc
packetbeat/docs/faq.asciidoc
winlogbeat/docs/modules.asciidoc

Backports #13753 to the 7.2 branch.
MUST BE MERGED ALONG WITH elastic/docs#1178

[7.2][DOCS] Fix markup issues for asciidoctor migration

---

filebeat/docs/configuring-howto.asciidoc
filebeat/docs/faq.asciidoc
filebeat/docs/filebeat-log-rotation.asciidoc
filebeat/docs/inputs/input-log.asciidoc

Backports #13386 to 7.3 branch.

[7.3][DOCS] Backport: Adds troubleshooting topic about log rotation (#13386)

---

docs/devguide/create-metricset.asciidoc
docs/devguide/create-module.asciidoc

Backport for https://github.com/elastic/beats/pull/13233

[Docs] Docs fixes for creating a new metricbeat module (#13233)

---

libbeat/docs/command-reference.asciidoc
x-pack/functionbeat/docs/export-cloudformation-template.asciidoc
x-pack/functionbeat/docs/getting-started.asciidoc
x-pack/functionbeat/docs/index.asciidoc
x-pack/functionbeat/docs/setting-up-running.asciidoc

Backports #13149 to 7.4 branch.

[7.4][DOCS] Backport: Document export function command (#13149)

---

libbeat/docs/command-reference.asciidoc
x-pack/functionbeat/docs/export-cloudformation-template.asciidoc
x-pack/functionbeat/docs/getting-started.asciidoc
x-pack/functionbeat/docs/index.asciidoc
x-pack/functionbeat/docs/setting-up-running.asciidoc

Backports #13149 to 7.3 branch.

[7.3][DOCS] Backport: Document export function command (#13149)

---

filebeat/docs/configuring-howto.asciidoc
filebeat/docs/faq.asciidoc
filebeat/docs/filebeat-log-rotation.asciidoc
filebeat/docs/inputs/input-log.asciidoc

Backports #13386 to 7.4 branch

[7.4][DOCS] Backport: Adds troubleshooting topic about log rotation (#13386)

---

libbeat/docs/command-reference.asciidoc

Backports #13520 to 7.4 branch.

[7.4][DOCS] Backport: Remove run command from functionbeat (#13520)

---

libbeat/docs/command-reference.asciidoc
libbeat/docs/https.asciidoc
libbeat/docs/outputconfig.asciidoc
libbeat/docs/shared-securing-beat.asciidoc
libbeat/docs/shared-ssl-config.asciidoc
libbeat/docs/shared-ssl-logstash-config.asciidoc

This PR persists changes made in the following apm-server PRs:
* APM Server install and run structure https://github.com/elastic/apm-server/pull/2170
* Update Logstash output documentation https://github.com/elastic/apm-server/pull/2691
* Add and improve SSL/TLS documentation https://github.com/elastic/apm-server/pull/2715

[docs][APM] Update APM/Beats documentation

---

script/build_docs.sh

Backports #13772 to 7.3 branch.

[7.3][DOCS] Backport: Switch over local build to use asciidoctor (#13772)

---

script/build_docs.sh

Backports #13772 to 7.1 branch.

[7.1][DOCS] Backport: Switch over local build to use asciidoctor (#13772)

---

libbeat/docs/command-reference.asciidoc
libbeat/docs/https.asciidoc
libbeat/docs/outputconfig.asciidoc
libbeat/docs/shared-securing-beat.asciidoc
libbeat/docs/shared-ssl-config.asciidoc
libbeat/docs/shared-ssl-logstash-config.asciidoc
script/build_docs.sh

Backports #13596 to 7.4 branch.
Also adds a commit to fix the regions tags (I will forward port this to master).
Also backports #13772 (required to fix doc CI).

[7.4][DOCS] Backport: Update APM/Beats documentation

---

script/build_docs.sh

Backports #13772 to 7.2 branch.

[7.2][DOCS] Backport: Switch over local build to use asciidoctor (#13772)

---

script/build_docs.sh

Backports #13772 to 6.7 branch.

[6.7][DOCS] Backport: Switch over local build to use asciidoctor (#13772)

---

script/build_docs.sh

Backports #13772 to 6.6 branch.

[6.6][DOCS] Backport: Switch over local build to use asciidoctor (#13772)

---

script/build_docs.sh

Backports #13772 to 6.5 branch.

[6.5][DOCS] Backport: Switch over local build to use asciidoctor (#13772)

---

auditbeat/docs/modules.asciidoc
filebeat/docs/autodiscover-hints.asciidoc
filebeat/docs/filebeat-general-options.asciidoc
filebeat/docs/inputs/input-redis.asciidoc
filebeat/docs/modules.asciidoc
filebeat/docs/modules/osquery.asciidoc
filebeat/module/osquery/_meta/docs.asciidoc
heartbeat/docs/heartbeat-options.asciidoc
journalbeat/docs/general-options.asciidoc
libbeat/docs/config-file-format.asciidoc
libbeat/docs/outputconfig.asciidoc
libbeat/docs/processors-using.asciidoc
libbeat/docs/regexp.asciidoc
libbeat/docs/shared-ilm.asciidoc
libbeat/docs/shared-ssl-config.asciidoc
libbeat/docs/template-config.asciidoc
libbeat/scripts/generate_fields_docs.py
metricbeat/docs/autodiscover-hints.asciidoc
metricbeat/docs/fields.asciidoc
metricbeat/docs/modules.asciidoc
packetbeat/docs/faq.asciidoc

Backports #13753 to 7.1 branch

[7.1][DOCS] Backport: Fix markup issues for asciidoctor migration

---

libbeat/docs/breaking-7.0.asciidoc
libbeat/docs/breaking-7.2.asciidoc
libbeat/docs/breaking-7.3.asciidoc
libbeat/docs/breaking-7.4.asciidoc
libbeat/docs/breaking.asciidoc
libbeat/docs/highlights-7.4.0.asciidoc
libbeat/docs/highlights.asciidoc

Backports #13803 to the 7.4 branch.
@lcawl FYI

[7.4][DOCS] Backport: Add breaking changes and release highlights (#13803)

---

libbeat/docs/version.asciidoc

DO NOT MERGE UNTIL DAY OF RELEASE

[DOCS] Bump docs version for 7.4.0

---

x-pack/functionbeat/docs/config-options.asciidoc

Fixes the changes originally submitted in #13336

[DOCS] Add role and vpc settings to the config reference

---

x-pack/functionbeat/docs/config-options.asciidoc

Backports #13866 to 7.3 branch

[7.3][DOCS] Backport: Add role and vpc settings to the config reference (#13866)

---

x-pack/functionbeat/docs/config-options.asciidoc

Backports #13866 to 7.4 branch

[7.4][DOCS] Backport: Add role and vpc settings to the config reference (#13866)

---

journalbeat/magefile.go

Cherry-pick of PR #13781 to master branch. Original message:

Cherry-pick #13781 to master: Fix issue installing libsystemd-dev:i386 for journalbeat

---

metricbeat/module/dropwizard/_meta/test/pom.xml

Upgrades a test dependency according to a report provided by [snyk-bot](https://github.com/snyk-bot) in #13708, #13723 and #13887. 
Making the change in a different PR to avoid CLA issues.

Fix test dependency

---

heartbeat/docs/heartbeat-options.asciidoc

I had a rough time figuring out how to send the body of a POST, this is the example that @andrewvc helped me out with.

Add  POST and response.body examples

---

script/build_docs.sh

Backports #13772 to 6.3 branch.

[6.3][DOCS] Backport: Switch over local build to use asciidoctor (#13772)

---

script/build_docs.sh

Backports #13772 to 6.4 branch.

[6.4][DOCS] Backport: Switch over local build to use asciidoctor (#13772)
